### ISSUE TITLE
Create Minio Integration Guide

### ISSUE THREAD

**Issue by repenno** [open-policy-agent/opa#1010]

**Comment by reptillicus** [comment]
I just want to say that I am really jazzed about this and you guys rock for all the effort into this!

**Comment by davie-robertson** [comment]
Any progress/draft on this? We're trying to integrate with a PWA that has keycloak issued tokens for auth and a simple guide would really help.  

Happy to provide some docs ourselves if we do get it working.

**Comment by tsandall** [comment]
The minio project has some basic docs: https://github.com/minio/minio/blob/master/docs/sts/opa.md.

@davie-robertson if you can provide a rough outline of your use case and an example policy you would want to enforce, that would be great!

**Comment by srenatus** [comment]
https://github.com/minio/minio/discussions/12422#discussioncomment-816361

Looks like the docs got removed ☝️

**Comment by tsandall** [comment]
Closing this issue for now since the integration is not well-supported at this time.
