### ISSUE TITLE
Running opa using a bundle doesn't work likewise doing it with the equivalent folder

### ISSUE THREAD

**Issue by EliuX** [open-policy-agent/opa#1019]
## Problem
When I run `opa` in server mode using a system folder that looks like:
```
parent
parent/data.json
parent/dm
parent/projects
parent/projects/projects.rego
parent/projects/projects_test.rego
parent/dm/dm.rego
parent/dm/dm_test.rego
```
All tests run OK and the opa server understand the data namespace  (queried with a GET `http://localhost:8181/v1/data`) as 

```json
{
    "result": {
        "parent": {
            "dm": { ... },
            "projects": { ... }
        },
        "employees": [ ... ],
        "organizations": [ ... ]
    }
}
```

Have in count that the data.json looks like:
```
{ 
   "employees": [ ... ],
   "organizations": [ ... ]
}
```
So this is the way I expected in my code for this to work. So far so good.

The problem comes when I compress the parent folder with:

``
tar --exclude='*_test.rego' -zcvf parent.tar.gz parent
``

when I query the running server using `GET http://localhost:8181/v1/data` I realize that all my `data.json` content was moved into the `parent` package:

```json
{
    "result": {
        "parent": {
            "dm": { ... },
            "projects": { ... },
            "employees": [ ... ],
            "organizations": [ ... ]
        }
    }
}
```
So I tried again creating a bundle file that doesn't contain the parent folder:

```
cd parent
tar --exclude='*test.rego' -zcvf ../parent.tar.gz *
a data.json
a dm
a dm/dm.rego
a projects
a projects/projects.rego
```
Runned  `opa` in server mode again and realized this time the data.json was not even present

```json
{
    "result": {
        "parent": {
            "dm": { ... },
            "projects": { ... }
        }
    }
}
```
So basically I realized that I had to create a bundle containing the `data.json` contained in a folder, but even in that case for the bundle to work I should do one of the following workarounds:
1. Change my whole code, to for instance, use `data.parent.organizations` instead of `data.organizations`.
1. Move `data.json` to the `dm` package, but the problem persists because when I run it using the bundle I get something like:

```json
{
    "result": {
        "parent": {
            "dm": { 
                  ... ,
                 "employees": [ ... ],
                 "organizations": [ ... ]
          },
            "projects": { ... }
        }
    }
}
```
but using the folder directly I get something like 
```json
{
    "result": {
        "parent": {
            "dm": { ... },
            "projects": { ... }
        }
       "dm": {
                 "employees": [ ... ],
                 "organizations": [ ... ]
          }
    }
}
```
So the workaround seems to be a change of code again.

## Analysis
It doesn't seem a good idea to use 2 versions of the same code, one for running `opa` in server mode with a folder and another for a bundle, having both the same structure. It would be nice that if you run 
`tar --exclude='*_test.rego' -zcvf parent.tar.gz parent` to any `parent` folder you get a bundle that runs likewise running it using the folder directly.

**Comment by EliuX** [comment]
Sure, from the directory it works perfect, but I really need this to work on a bundle. Thanks @tsandall.

**Comment by EliuX** [comment]
When I running from a the bundle everything is contained in the parent folder (`root`). In the other hand if I run it from the folder then the `data.json` is contained outside of parent. Something like:
{
```
    "result": {
        "root": {
            "dm": { ... },
            "projects": { ... }
        },
        "employees": [ ... ],
        "organizations": [ ... ]
    }
}
```

Which is not the way it shows to you, which is weird: In your case running opa on the folder takes `dm` outside `root` but contains `organizations` and `employees`. 
I am using this version

```
Version: 0.9.1
Build Commit: d5ba22b7
Build Timestamp: 2018-08-16T15:46:52Z
Build Hostname: b381b3d1a5ac
```

**Comment by tsandall** [comment]
@EliuX can you include the output of something like `tree` or recursive `ls` so that I can see how the files are laid out on disk? If you can include the output of `tar tzvf` on the bundle as well that would be helpful.

**Comment by EliuX** [comment]
It would be something like:

**Comment by EliuX** [comment]
> Can you post similar output for the non-bundle case? In my case I put the `data.json` file under the `root` directory and then ran `opa run .` (where `.` contains a subdir called `root`). This is why the data shows up under `root` for me. If you can post your the files on disk for the non-bundle case it'll help rule out any issues with the normal file loading.

Sorry for the late response @tsandall. Well the content of the bundle is pretty much the content of the folder, except for the test rego files. For that folder I run `opa run root` and it works the way I expected: the data is in the global scope of `data`, not under `root`. This is pretty much the sample scenario I explained at the beginning of the issue, except that I changed the name `parent` for `root`. I will check your solution in the next opa release for sure. Thanks.
