### ISSUE TITLE
Refer other Rego files from a Rego file and selective evaluation of rules based on input parameters

### ISSUE THREAD

**Issue by yashhere** [open-policy-agent/opa#1027]
Hi there, I am relatively new to OPA. I am trying to solve a problem, but I do not know if it is even possible to do such things in OPA. Let me first describe my problem:

One of my services (service A) pushes the policy data (a JSON object) and the Rego policy rules to the OPA and other service (service B) queries OPA for decisions based on these Rego policies. Now, service A can push multiple JSON objects, but each JSON object and its corresponding Rego file(programmatically generated) will be pushed to a random endpoint (the endpoint address is a random string). As there are multiple random endpoints, I do not want the service B to be aware of any of these endpoints. I want it to query a predefined endpoint which in turn will get the result back from all the other random endpoints. Is it even possible to do this in OPA, I mean is it possible to refer to other Rego modules from a Rego module? If yes, can you please give some example and point me to relevant documentation?

Second question is related to Rego as a language. So I have an array of rules in my *data.json* file, which looks something like:
```json
"rules": [
	{
		"source-ip": "192.168.40.23",
		"port":443,
		"result": "allow"
	},
	{
		"source-ip": "192.168.40.23",
		"port": 80,
		"result": "deny"
	},
	{
		"source-ip": "192.168.40.23",
		"dest-ip": "10.10.1.18",
		"port": 80,
		"result": "allow"
	}
]
```
and an *input.json* file, which looks something like:
```json
{
"inputAttributes": [
	{
		"source-ip": "192.168.40.23",
		"port": 80
	}
],
```

and the corresponding Rego file is:
```rego
package example.policy
import data.rules
import input.inputAttributes

match[result] {
	rules[i]["source-ip"] == inputAttributes[j]["source-ip"]
	rules[i]["port"] == inputAttributes[j]["port"]
	rules[i]["dest-ip"] == inputAttributes[j]["dest-ip"]
	result := rules[i]
}
```

So now, you see that I have not provided the **dest-ip** attribute in the *input.json* file, but the Rego file is trying to filter the rules based on **dest-ip** attribute. So as of now, the output is NULL, because the evaluation of policy becomes false at the third statement in the match function. 

Is there any way that I can use to check if an attribute is supplied by the user in *input.json* before Rego tries to evaluate the policy using the attribute? This problem arises because, in my use case, I do not know beforehand, on what attributes the user wants to query the data? There might be thousands of attributes, and I do not think that it is feasible to use each and every combination of these attributes for evaluation purposes.

I haven't been able to come up with a solution for a long time now. That might be mostly because of my lack of experience with declarative programming languages, but also because I have had a hard time finding examples to learn from and whenever I found examples, I am having hard time understanding them. 

Any help or guidance is appreciated.

**Comment by tsandall** [comment]
@yashhere thanks for posting this great writeup.

Regarding the first question, the answer is _yes_ but it'll depend on how the data is structured. Here's a rough example that may (or may not) match your use case.


Suppose service B queries for `/data/example/foo`.

You can write a Rego module that defines the value of `/data/example/foo`:

```
package example

# foo will be a set of x that satisfy conditions.
foo[x] {
   # add logic to generate x
}
```

Suppose service A inserts Rego modules with package `example.endpoints.<endpoint_id>` that contain a rule `baz`. Service A also inserts JSON data for each endpoint at path `example/endpoint_context/<endpoint_id>`. The Rego module might look like this:

```
package example.endpoints.abcdef

import data.example.endpoint_context.abcdef

baz = 100 {
   # use context somehow
}
```

You can modify the Rego module from earlier search over all the endpoints:

```
import data.example.endpoints

foo[x] {
  value := endpoints[id].baz
  x := {"id": id, "value": value}
}
```

There are a couple things to note here.

1. Rego rules generate JSON data.
2. You can refer to raw JSON data and JSON data generated by rules using the same syntax.
3. You can import documents to provide aliases for paths. You can also skip the import and just use absolute paths everywhere.

You'll find more about the document model in [How Does OPA Work?](https://www.openpolicyagent.org/docs/how-does-opa-work.html#rules-and-virtual-documents) and you'll find more about search and imports in [How Do I Write Policies?](https://www.openpolicyagent.org/docs/how-do-i-write-policies.html)

With respect to your second question, references like `inputAttributes[j]["dest-ip"]` are _undefined_ if the value you are referring to does not exist in the input data. You can check if values are undefined by using the `not` keyword (see 3rd expression):

```
match[result] {
	rules[i]["source-ip"] == inputAttributes[j]["source-ip"]
	rules[i]["port"] == inputAttributes[j]["port"]
	not inputAttributes[j]["dest-ip"]
	result := rules[i]
}
```

If you have many cases you need to deal with like this, you could factor the matching differently:

```
match[result] {
        result := rules[_]
        attr := inputAttributes[_]
        matches_source(result, attr)
        matches_dest(result, attr)
        matches_port(result, attr)
}

matches_source(rule, attr) {
	rule["source-ip"] == attr["source-ip"]
}

matches_source(_, attr) {
	not attr["source-ip"]
}
```

**Comment by yashhere** [comment]
Thanks for answering this, @tsandall. I'll try the solutions and tell you my findings. For now, this thread can be closed. I'll open it again, if I require any other help.

**Comment by yashhere** [comment]
Hi, many thanks for your help. The solution that you suggested is assuming that all the attributes in input must match with all attributes in rules, and you match `result` key manually. That gives me another doubt. What will happen when we have not provided some attribute in the `input.json`? For example, let's assume that the input document is as following:
```json
{
  "inputAttributes": [
    {
      "key": "source-ip",
      "value": "192.168.40.99"
    }
  ]
}
```

So according to your solution, the result should be NULL as there will be some undefined results from the `attribute_matching` function.

What I am able to think of about the solution to this problem, in normal programming languages, is to do the following:

```
def match_attributes_with_input(attributes, inputAttributes):
	for input_attribute in inputAttributes:
		if input_attribute.key not exist in attributes:
			return false
			
	for attribute in attributes:
		for input_attribute in inputAttributes:
			if attribute.key == input_attribute.key:
				if attribute.value != input_attribute.value:
					return false
	return true

def matching_rules():
	result = []
	for rule in data.rules:
		output = match_attributes_with_input(rule.attributes, inputAttributes)
		if output is true:
			result.append(rule)

	return result
```

I assume here that:
1. If all attributes in rule matches with all attributes in input, then rule should be evaluated to `true`.
2. If rule contain `source-ip`, `dest-ip` and `port` attributes and input contains `source-ip` and `dest-ip` attribute with same values, then this rule should be evaluated to `true`.
3. If rule contain `source-ip`, `dest-ip` attributes and input contains `source-ip` and `port` attribute then this rule should be evaluated to `false`.
4. Even if `port` key in rule matches with `port` key in input, if their values do not match, evaluate rule to `false`.

Now the problem, that I am facing here, is that I am not able to translate this logic to Rego. I am having a tough time thinking about translating my logic to the logic of declarative language.

Some of the sample `input.json` and outputs (Assuming the `data.json` is from the previous comment):

**input.json**:
```json
{
  "inputAttributes": [
    {
      "key": "source-ip",
      "value": "192.168.40.99"
    }
  ]
}
```

**output**:
```json
[
  {
    "attributes": [
      {
        "key": "source-ip",
        "value": "192.168.40.99"
      },
      {
        "key": "port",
        "value": 443
      },
      {
        "key": "result",
        "value": "allow"
      }
    ]
  },
  {
    "attributes": [
      {
        "key": "source-ip",
        "value": "192.168.40.99"
      },
      {
        "key": "port",
        "value": 80
      },
      {
        "key": "result",
        "value": "deny"
      }
    ]
  },
  {
    "attributes": [
      {
        "key": "source-ip",
        "value": "192.168.40.99"
      },
      {
        "key": "dest-ip",
        "value": "10.10.1.1"
      },
      {
        "key": "port",
        "value": 80
      },
      {
        "key": "result",
        "value": "allow"
      }
    ]
  }
]

```
---

**input.json**:
```json
{
  "inputAttributes": [
    {
      "key": "source-ip",
      "value": "192.168.40.99"
    },
    {
      "key": "dest-ip",
      "value": "10.10.1.1"
    }
  ]
}
```

**output**:
```json
[
  {
    "attributes": [
      {
        "key": "source-ip",
        "value": "192.168.40.99"
      },
      {
        "key": "dest-ip",
        "value": "10.10.1.1"
      },
      {
        "key": "port",
        "value": 80
      },
      {
        "key": "result",
        "value": "allow"
      }
    ]
  }
]
```

**Comment by tsandall** [comment]
@yashhere if you want to extend the rule matching with other cases that _should_ match (e.g., case-1 OR case-2 OR case-3 OR ...) yon can rewrite the beginning as...

```
matching_rules[r] {
    r := rules[_]
    rule_matches(r)
}
```

where `rule_matches` can be implemented as:

```
rule_matches(r) {
  not any_attributes_not_matching(r.attributes)
}

rule_matches(r) {
  r.attributes[i].key = "source-ip"
  r.attributes[j].key = "dest-ip"
  input.inputAttributes[k].key = "source-ip"
  input.inputAttributes[l].key = "dest-ip"
  r.attributes[i].value = input.inputAttributes[k].value
  r.attributes[j].value = input.inputAttributes[l].value
}
```

(Or any other number of special cases.)

I'm not sure that I understand the model you described above. I think it would be a bit easier if you clearly defined the semantics of the model before trying to implement the logic. E.g., I'm not sure what the importance of this statement is:

> Even if port key in rule matches with port key in input, if their values do not match, evaluate rule to false.

Similarly, I don't see how the first input.json/output example in your last comment is covered by your set of assumptions.

As a side note, have you tried the VS Code plugin for OPA? https://github.com/tsandall/vscode-opa. It has a handy feature that let's you visually select blocks of the policy and evaluate them to see what values are generated. It's useful for experimenting with policies. Perhaps you could give that a try to help build up intuition about how the language works.

**Comment by Izano007** [comment]
Hii all i just started working on opa and i know it's a silly please help me. So, my question is that i've data.json, input.json, and my .rego file all in same folder how will run this policy against data and input.
what i am asking here is opa command to do the same. i've alread imported all json to the .rego file.

**Comment by tsandall** [comment]
@Izano007 see https://www.openpolicyagent.org/docs/latest/#2-try-opa-eval.

**Comment by Izano007** [comment]
i ran this command ./opa eval -i input.json -d data.json main.rego . but i'm getting error as

{
  "error": [
    {
      "code": "rego_unsafe_var_error",
      "message": "var main is unsafe",
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      }
    },
    {
      "code": "rego_unsafe_var_error",
      "message": "var _ is unsafe",
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      }
    }
  ]
}

**Comment by tsandall** [comment]
Try `./opa eval -i input.json -d data.json -d main.rego '<put your query here>'`

**Comment by Izano007** [comment]
my input.json is :

{
        "container_id":"563",
        "installation_date": "12/04/2018",
        "build_hosts": "kjsdbcuyh23456",
        "signature_key_IDs": "jkzvkajcgsic34567sd"
}

and my data.json is :

{
   "container": [

      {
         "container_id":"563",
         "installation_date": "12/04/2018",
         "build_hosts": "kjsdbcuyh23456",
         "signature_key_IDs": "jkzvkajcgsic34567sd"
      },

      {
         "container_id":"583",
         "installation_date": "18/07/2018",
         "build_hosts": "njksdbc9837",
         "signature_key_IDs": "sdfghjkmvec34567sd"
      }
   ]
}

and main.rego file = 

package example.rules

import data
import input

default allow = false

allow = true {
        some i
        data.containers[i].container_id == input.container_id
        data.containers[i].installation_date == input.installation_date
        data.containers[i].build_hosts == input.build_hosts
        data.containers[i].signature_key_IDs == input.signature_key_IDs
#       msg = sprintf("return decryption key")
}

and i ran the command : ./opa eval -i input.json -d data.json -d main.rego "data.example.allow"
 the output i'm getting is { }, but the output i should gave gotten is in boolean.

please help me with this.

**Comment by Izano007** [comment]
Sorry msg = sprintf("return decryption key") is commented. ignore it in the code.

**Comment by tsandall** [comment]
You're querying for `data.example.allow` but the rules are defined under `package data.example.rules`. Change the query.

Please take some time to read through the Introduction. Also, you can check out this writeup on the OPA document model that explains some of this in more detail: https://www.openpolicyagent.org/docs/edge/philosophy/#the-opa-document-model

**Comment by Izano007** [comment]
will do @tsandall and thanks for the help :)

**Comment by Izano007** [comment]
okay so changing th equery from data.example.allow to data.example.rules gave me the result as True.
but when i tried executing this command ./opa run --server main.rego and in the browser i ran http://13.21.53.36:8181/v1/data/example/rules/allow, this is giving me the result as false.
my data, input and .rego files all are in same directory.

any help is appreciated.

**Comment by tsandall** [comment]
See the links above. When you're running OPA as a server you have to supply the input in the HTTP request: https://www.openpolicyagent.org/docs/latest/#4-try-opa-run-server.

**Comment by Izano007** [comment]
i did supplied the input using this command in the other terminal : curl localhost:8181/v1/data/example/rules/allow -d '{"input": {"container_id":"563","installation_date": "12/04/2018","build_hosts": "kjsdbcuyh23456","signature_key_IDs": "jkzvkajcgsic34567sd"}}'

it still is giving false.

**Comment by Izano007** [comment]
i've a question that is while running this command ./opa run --server ./main.rego from where does opa get data.json to evaluate the policy?

**Comment by Izano007** [comment]
shall i import both data.json and input.json into the polocy code?

**Comment by Izano007** [comment]
policy*

**Comment by tsandall** [comment]
> i've a question that is while running this command ./opa run --server ./main.rego from where does opa get data.json to evaluate the policy?

OPA will not automatically load data files--you need to specify them explicitly. `./opa run -s ./main.rego ./data.json`. This is probably why you're getting `false` above.

**Comment by Izano007** [comment]
it worked. @tsandall Thank you soo much.

**Comment by Izano007** [comment]
Hi all,

I'm stuck here with an small issue that is whenever i'm running my opa server from this command( ./opa run --server ./main ./data) it is throwing error that is : error: 1 error occurred during loading: ./main.rego:15: rego_parse_error: no match found
        some i
my main.rego file is:

package example.rules

default allow = false

allow[msg] = {
        some i
        data.container[i].container_name == input.container_name
        data.container[i].container_hashvalue == input.container_hashvalue
        msg = sprintf("data.container_passphrase[i]")
}
when i remove the msg part and checked it with true/false, it was working fine.
 any help would be appreciated.

**Comment by shanfer1** [comment]
Hi I have a query regarding calling another rego file from a main rego depending upon the input.json file

**Comment by shanfer1** [comment]
Hi I have a query regarding calling another rego file from a main rego file whose variables are accessed by the REST API calls.
so ultmately what i required is i doesnt want to change the API call which access the variables repeatedly .suppose for example depending upon the input attributes i need to call for particular rego file which process and store the allow variable which is defined inside the main rego file

**Comment by shashankbr11** [comment]
Hi,

I have been checking the solution by @tsandall for checking authorization for port and IP. The code is modified to take inputs from external application via HTTP requests instead of input.json file

```
package ipport

import data.portdata.rules

import data.portdata.attributes

import input.attributes

match[result] {

      result := rules[_]
      attr := input.attributes[_]
      matches_source(result, attr)
      matches_dest(result,attr)
      matches_port(result,attr)
}

matches_source(rules, attr) {
      rules["source-ip"] == attr["source-ip"]
}

matches_source(_, attr) {
      not attr["source-ip"]
}


matches_dest(rules, attr) {
      rules["dest-ip"] == attr["dest-ip"]
}

matches_dest(_, attr) {
      not attr["dest-ip"]
}


matches_port(rules, attr) {
      rules["port"] == attr["port"]
}

matches_port(_, attr) {
      not attr["port"]
}
```

The dataport.json which is imported is
```
{
	"rules": [
	{
		"attributes": [
			{
			 "key": "source-ip",
			 "value": "192.168.0.12"
			},
			{
			 "key": "port",
			 "value": 443
			},
			{
			 "key": "result",
			 "value": "true"
			}
		]
	}
	]
}
```

The query to /v1/data/ipport for IP or Port in the format
`
{
"source-ip": "192.168.0.12"
}
`
or 
`
{
"port": 443
}
`


returns the result as
`
{ 
"result": {"match": []}
}
`

Please suggest the necessary modification for the result of match to be obtained


Regards,
Shashank

**Comment by anderseknert** [comment]
Hi Shashank!

The format of the data you're providing in `portdata.json` does not match what the policy is looking for. `result := rules[_]` is going to have `result` be the entire `attributes` object, which doesn't have the keys required by your policy. You'll probably want to iterate over `data.rules.attributes` instead, and include "key" and "value" in those rules as that's how the data is structured.
