### ISSUE TITLE
Add threshold to coverage

### ISSUE THREAD

**Issue by EliuX** [open-policy-agent/opa#1029]
## Feature
Make coverage fail if the percentage of code covered by the tests is  below an specified value, on which case it might return:
1. Exit code = `1` 
1. Exit code = % of non covered lines

E.g.
```
opa test --coverage --threshold=80 . -v
```
It would fail (exit value > 0) if the policies (rego files) are covered less than the 80% of lines. If for instance it had a 75% of coverage it might fail with an exit code `1` or an exit code `25`: For this last behaviour you can also add a command line flag like `--fail-with-percentage`.

## Beneficts
You can assure in your OPA project during the CI process that a certain percentage of the policies be certified by tests.

**Comment by tsandall** [comment]
Closed by #1042
