### ISSUE TITLE
opa fmt vs git -- trailing newline issue

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#1032]
When committing `opa fmt`'ed files to git, it'll complain about the trailing newline:

<img width="200" alt="screen shot 2018-10-24 at 11 07 07" src="https://user-images.githubusercontent.com/870638/47419657-f61fdd00-d77c-11e8-97ce-51285054c91f.png">

It's by no means a big deal, just a minor annoyance. Anyhow, I think it would be preferable if it wasn't so. 😃 What do you think?

**Comment by tsandall** [comment]
I agree this is annoying. What's the desired behaviour we want? `opa fmt` should only add a newline at the end of the file if one is not present?

**Comment by srenatus** [comment]
> only add a newline at the end of the file if one is not present

Yeah, I suppose that would be it! 👍

**Comment by srenatus** [comment]
@kichristensen thank you! 🎈
