### ISSUE TITLE
Add query metrics to decision logs

### ISSUE THREAD

**Issue by ekarlso** [open-policy-agent/opa#1033]
It would be a nice addition to get the query logs that you can get via the http query in the decision logs instead or in addition.

**Comment by tsandall** [comment]
OPA automatically records parse, compile, and evaluation latency for all decisions and the decision log events internal to the server currently have the metrics object on them--however, we don't copy the metrics onto the event struct that's eventually serialized and uploaded.

We need to update the plugins/logs/plugin.go#EventV1 struct to include a `Metrics` field of type `map[string]interface{}` (`omitempty`) and populate in the plugins/logs/plugin.go#Plugin.Log function.

**Comment by repenno** [comment]
It should be straightforward after #1089 is merged. I will work on it next
