### ISSUE TITLE
Helm chart to deploy OPA

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1035]
Some users have asked whether we have a Helm chart for OPA. As far as I know, today the answer is no. It would be useful to create a Helm chart that (minimally) could be used for the admission control use case on top of Kubernetes. I haven't worked with Helm before, so I don't know if there are gotchas.

- Should the helm chart require a cert (which is required in the admission control use case)?
- Should the helm chart assist in registering OPA as an admission controller?
- Should users be able to manage policies via Helm? We can probably defer this one for now.

In the admission control use case, some users have requested that OPA be scheduled onto the master node(s). The Helm chart must not preclude this.

**Comment by nrshrivatsan** [comment]
For the Policy Store, given OPA has support for S3, I propose using [minio.io](https://hub.kubeapps.com/charts/stable/minio) for a Cloud-Native helm.sh for OPA!

**Comment by srenatus** [comment]
It might be a bit of a digression, but I'd be happy to contribute a Habitat plan for OPA. From that, we could, among other things, [export a helm chart](https://www.habitat.sh/blog/2018/02/Habitat-Helm/). (_"Habi-what?"_ 👉 https://habitat.sh)

**Comment by tsandall** [comment]
@srenatus having a Habitat plan for OPA would be cool. I'm not familiar with Habitat so I don't know what the Helm output would look like. I'd like the Helm chart to be as clear/idiomatic as possible--I think we should start with writing one from scratch, but we can always revisit that in the future.

**Comment by srenatus** [comment]
> having a Habitat plan for OPA would be cool.

🎉 [`core/opa`](https://bldr.habitat.sh/#/pkgs/core/opa/latest)

I certainly agree with being as idiomatic as possible with the helm chart. So, this just adds another deployment option, and it happens to fill a need I had 😄

**Comment by tsandall** [comment]
@srenatus cool! do you mind if I put a link to the habitat plan in the contrib repo README?

**Comment by srenatus** [comment]
@tsandall not at all! thank you 😃

**Comment by tsandall** [comment]
Ref: https://github.com/helm/charts/pull/8915

**Comment by gtaylor** [comment]
I haven't forgotten about this, btw. Will try to get a first pass done on the Chart PR tonight or tomorrow.

**Comment by tsandall** [comment]
@gtaylor sounds good. Just FYI, I've updated the chart PR so that by default it'll pull down a policy from openpolicyagent.org that you can kick the tires with.

**Comment by tsandall** [comment]
This has been merged into the upstream helm repo. https://github.com/helm/charts/pull/8915
