### ISSUE TITLE
Document debugging tips for Kubernetes admission control use case

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1039]
Today we don't document how to debug the Kubernetes admission control use case. If the policy is not being enforced as expected, users are often stuck and have to ask on Slack. A few things we can document to help out.

1. Check the policy status on the configmap. The status should be "ok". If it's not set, or it's set to an error, something is wrong during policy loading. Look at the kube-mgmt logs.

2. Check the kube-mgmt logs. They should be quiet if kube-mgmt is working normally.

3. Check the OPA logs. They should contain 2xx responses for PUT (data loading) and POST (admission webhook) requests. TLS errors or lack of POSTs indicate the webhook configuration was not added properly or network connectivity between the apiserver and OPA is bad.

4. If there are no POSTs in the OPA logs, verify whether the API server can reach OPA over the network. If you're running on EKS make sure your SGs allow traffic from the masters to the worker nodes (assuming you're running OPA on a worker node.)

5. How to generate JSON patches with "/" characters in path component, e.g., annotations like `kubernetes.io/foo` => `kubernetes.io~1foo`.

6. How to marshal JSON patches: use `base64` instead `base64url`.

It would be fine to create a new documentation page for this. We could put it under the Best Practices section.

**Comment by Leeladitya** [comment]
How can we check policy status on the configMap

**Comment by tsandall** [comment]
@Leeladitya kube-mgmt annotates the configmaps to report status. https://github.com/open-policy-agent/kube-mgmt#policies

Run `kubectl get configmap -o yaml <namespace> <name>` on the configmap to get the value.

**Comment by alkar** [comment]
Perhaps slightly out of topic, but I think it would immensely help development or rego policies if we could run the repl against live data. Is this something that's been considered already?

**Comment by tsandall** [comment]
Connecting to a remote data source would be cool. It's something we've thought about in the past but never got around to. It's certainly possible but it would take a bit of work.

One challenge with connecting to live data sources is that they're...live. Meaning the data will be changing under your feet while you test the policy. This can cause more pain than it's worth.

Nonetheless, I think this could be purely additive and would make for some interesting demos :-)

I'd like to see if we could implement similar functionality for the VS Code extension.
