### ISSUE TITLE
Commandline bundles omit 'revision' in decision logs.

### ISSUE THREAD

**Issue by pwmorreale** [open-policy-agent/opa#1062]
If you add a policy bundle, with a .manifest defined, on the command line, the decision logs will not contain the contents of the .manifest 'revision' field.

**Comment by tsandall** [comment]
When bundles are loaded from the command line the `/system/bundle/manifest` document is not being written into the in-memory store. For bundle downloads, this behaviour is implemented inside the bundle plugin. One way to resolve this would be add an optional flag on the bundle reader that would cause it to insert the bundle metadata into the `bundle.Bundle#Data` field. When bundles are instantiated in different places inside OPA, we could set the flag. If users are embedding OPA as a library, they could opt-in to this behaviour.
