### ISSUE TITLE
How to access input document sent to one endpoint in some other endpoints

### ISSUE THREAD

**Issue by yashhere** [open-policy-agent/opa#1066]
Hi there,
I will be referring to issue #1027 in this question. Creating a new issue to keep things clean and separate.

I have two Rego modules(for services X and Y) at `example.endpoints.<endpoint_id>`  and their corresponding JSON data at `example/endpoint_context/<endpoint_id>` where `endpoint_id` is a random string. (see [this](https://github.com/open-policy-agent/opa/issues/1027#issuecomment-432285083) reply by you). Now there is another service A which the client queries. The service A does not have any JSON data of its own. It relies on the data received from other services. It can, in turn, get the query results from the services X and Y. So now my problem is that when the client sends an `input` document as the request body to the service A, I am not able to access this information in services X and Y. I tried with absolute path for accessing input document as well as the `import` method. Both did not work. 

Also, how do I evaluate such kind of problems in the vscode OPA plugin? Is it even possible to use the plugin in such cases?

**Comment by yashhere** [comment]
Also, I pushed policy module(which contains references to `input` document) and the corresponding JSON data to OPA. So the policy is evaluated and the result is `NULL`, as OPA could not find the `input` document. Now when I query the endpoint using a POST request with `input` document in the request body, will OPA reevaluate the policy and serve me the results? My findings say opposite. The same set of policy module, data and input documents is giving correct results in VSCode plugin.

**Comment by tim-styra** [comment]
Query OPA with the `data` URL and provide input as a parameter.  For example...

Create a file **test.rego** policy that allows alice/GET.
```
package foo 
allow {
  input.name == "alice"
  input.method == "GET"
}
```

Run OPA in server mode, loading the test policy.
```
opa run -s test.rego
```

In a different terminal, ask for the `foo/allow` result with input alice/GET.
```
$ curl localhost:8181/v1/data/foo/allow -d '{"input": {"name": "alice", "method": "GET"}}'
{"result":true}
```

If you don't supply input, OPA returns the empty result because allow is not defined.
```
$ curl localhost:8181/v1/data/foo/allow 
{}
```

**Comment by tsandall** [comment]
Closing this issue for now.
