### ISSUE TITLE
Feature request: add opa to homebrew

### ISSUE THREAD

**Issue by wmuizelaar** [open-policy-agent/opa#1070]
Hi,

For easy installation and updates on MacOS I would like to have opa added to the https://brew.sh/ homebrew package management.

Is this something that is considered/desired? If so, I'm willing to create a PR for the homebrew-folks to add OPA.

Regards,
Wietse

**Comment by tsandall** [comment]
@wmuizelaar that would be great! I don't personally have experience with contributing to homebrew. If you can make that happen, please go for it.

**Comment by repenno** [comment]
+1 That would be very userful

**Comment by wmuizelaar** [comment]
Created https://github.com/Homebrew/homebrew-core/pull/34312 for that

**Comment by tsandall** [comment]
Excellent! What's the process like for updating the formula when new release of OPA are available?

**Comment by wmuizelaar** [comment]
It should be as simple as https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#submit-a-version-upgrade-for-the-foo-formula - so I think there's a good possibility to get this automated. But it's my first homebrew contribution as well, so maybe just learn how the process works during the next OPA release, and then afterwards see how things can get automated?

**Comment by tsandall** [comment]
@wmuizelaar that sounds like the right approach. We'll be cutting the 0.11 release in the next two weeks so we experiment with the homebrew process at that point.

**Comment by wmuizelaar** [comment]
@tsandall I got requested to add a (very simple) functionality test to the application. What would be a good oneliner for that?

**Comment by tsandall** [comment]
How about something like...

```
opa eval -f pretty '[x, 2] = [1, y]`
```

This will output:

```
+---+---+
| x | y |
+---+---+
| 1 | 2 |
+---+---+
```

Alternatively, we could do something with JSON...

```
echo '{"x": [1,2,3,4,5]}' | opa eval --stdin-input 'input.x[i] > 2; input.x[i] < 5'
```

**Comment by wmuizelaar** [comment]
It's available!

**Comment by tsandall** [comment]
Those fields are currently set inside the Makefile. If you're downloading the source tarball that might not work. What about having the homebrew installer download the macOS binary from the releases page? Every release contains a pre-built binary for Darwin. WDYT?

**Comment by wmuizelaar** [comment]
Well, homebrew likes to build themselves, to be able to differentiate between different macos-versions. If that's really relevant for a go-binary...  :)
But I found a solutions - don't download the source, but do a git clone of the version-tag, so I can fill those values as well.

**Comment by wmuizelaar** [comment]
https://github.com/Homebrew/homebrew-core/pull/34603 created for that.

**Comment by tsandall** [comment]
Awesome! I'll close this ticket now that we have it working.
