### ISSUE TITLE
Update REST API specification with POST endpoint on Query API

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1082]
The REST API documentation doesn't include a section on the new POST endpoint for the query API. We should extend the existing "Execute an Ad-hoc Query" section with the POST endpoint and recommend that people use this if they have large JSON values included in the query.

/cc @rite2nikhil

**Comment by rite2nikhil** [comment]
Can you point me to docs where I can update. Are there are swagger specs too ? Thanks.

**Comment by tsandall** [comment]
Thanks @rite2nikhil! You can find the REST API documentation in docs/book/rest-api.md. There are is no Swagger spec to update.

**Comment by tsandall** [comment]
Fixed by #1105
