### ISSUE TITLE
Build IDE integration for IntelliJ

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1085]
It would be nice to have an IntelliJ plugin that adds OPA syntax highlighting, syntax checking, testing, tracing, and evaluation features like we have for [VS Code](https://github.com/tsandall/vscode-opa).

I haven't looked into the development effort required for creating IntelliJ plugins. Over time it would be great to have feature parity with the VS Code plugin.

**Comment by tsandall** [comment]
This feature has been proposed as part of GSoC 2019. https://github.com/cncf/soc#open-policy-agent-opa

**Comment by tsandall** [comment]
@vgramer is looking into this.

**Comment by tsandall** [comment]
@vgramer do you have any updates on this? We're going to submit it to GSOC 2020 but if you have made a bunch of progress we can always pull it.

**Comment by vgramer** [comment]
Hi nothing really tangible.  Unfortunately I didn’t have time to work on it during holiday and I have a bit forgotten what I have done :s

Anyway so far,  I have implemented a subset of the rego grammar (a subset was easier to debug) and  some functionally like `highlighting` or `commenting` . But i am still struggling with intelliJ api to know how to execute an action (opa fmt, opa eval ... ) and renderer the result.

I hope to have more time in the next week to work on it . However i think it's a good idea to submit to  GSOC 2020, there are a lots of work to do ;)

**Comment by twisted-sres** [comment]
Hey, If nobody has been working on this, can this be proposed for CommunityBridge?
I would be happy to work on this

**Comment by vgramer** [comment]
Yeah sure. 
Please ping me on opa slack so we can start taking about that.

Slack id `vgramer`

**Comment by ashutosh-narkar** [comment]
@vgramer if you would like to propose the project for CommunityBridge, you would need to add it [here](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md#opa) with a description similar to [this](https://github.com/cncf/mentoring/blob/master/summerofcode/README.md#intellij-plugin-to-experiment-with-and-visualize-policy-evaluation).

The deadline is May 1st 2020.

**Comment by UkonnRa** [comment]
Hi, any update? This is a nice idea

**Comment by vgramer** [comment]
Hi @UkonnRa 
A first version of the plugin is available here: https://github.com/vgramer/opa-idea-plugin. The installation of the plugin requires some manual configuration for the moment (add a custom repository).  It should be available in the stable repository (no manual configuration) by the next week.

**Comment by tsandall** [comment]
I'm going to close this issue now since the plugin exists over at https://github.com/vgramer/opa-idea-plugin. We can file bug/enhancement issues in that repo going forward.
