### ISSUE TITLE
Add OPA version to decision logs.

### ISSUE THREAD

**Issue by pwmorreale** [open-policy-agent/opa#1089]
Enhancement request:  

Add the OPA semver version string to the datum in a decision log.  

From a record-keeping standpoint,  its very useful to tie both the configuration (revision id) and the particular version of OPA used together.

Currently the data  in OPA decision logs does not include the OPA semver version.

**Comment by tsandall** [comment]
This seems like a useful feature. The version information is compiled into the OPA binary (see the `version` package). We can extend OPA to include this field in the decision log events.

**Comment by repenno** [comment]
I will take a stab
