### ISSUE TITLE
Improve Rego syntax highlighting in the docs

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1090]
# Expected Behavior

When I look at the docs, I should see nice colors (maybe this is optional, but it should at least be possible.) It should be possible to write a syntax highlighter for whatever plugin we're using to render Rego in the documentation.

Ideally the Rego snippets would be run through the `format` package. One option would be to add an HTML mode to the format package that emits the Rego source code as HTML.

# Actual Behavior

We currently mark Rego snippets as "ruby" code to get some cheap syntax highlighting.

# Steps to Reproduce the Problem

  1. Go to the docs.
 
# Additional Info

- There's a bit of design work that should be done to figure out the best path forward. To start, we should outline the different approaches and investigate the pros & cons.

**Comment by srenatus** [comment]
Using [SublimeSyntaxConvertor](https://github.com/aziz/SublimeSyntaxConvertor) on your [`tmLanguage` file](https://github.com/tsandall/vscode-opa/blob/master/syntaxes/Rego.tmLanguage) (after adding file extension `rego` to `Rego`), makes for something that's accepted by [`syncat`](https://github.com/trishume/syntect/blob/master/examples/syncat.rs) or [`bat`](https://github.com/sharkdp/bat) (both based on [syntect](https://github.com/trishume/syntect)):

<img width="381" alt="screenshot 2018-11-29 at 16 45 39" src="https://user-images.githubusercontent.com/870638/49233424-44687180-f3f6-11e8-9c80-ad255a98984e.png">

So, while it's not HTML yet (and `synhtml` always explodes for me), it might be a path worth exploring... 🤔

**Comment by tsandall** [comment]
Nice find! The syntect project looks promising. It says it supports the main thing we'd need:

```
Built-in output to coloured HTML <pre> tags or 24-bit colour ANSI terminal escape sequences.
```

**Comment by srenatus** [comment]
> and `synhtml` always explodes for me

This was entirely my fault -- I had assumed it would accept the same arguments that `syncat` accepts. However, it doesn't. With some small alterations, https://github.com/trishume/syntect/compare/master...srenatus:sr/synhtml/allow-for-extra-syntax, it's possible to use it with your tmLanguage (converted with the tool described above)... see this [gist](https://gist.github.com/srenatus/0b8a6f07fbd33dde4314811dfe7318dd), and this [fiddle](http://jsfiddle.net/s97qv61b/).

**Comment by tsandall** [comment]
This has been fixed a little while with the live blocks feature we added a while ago.
