### ISSUE TITLE
Deploying a smaller version of OPA

### ISSUE THREAD

**Issue by ankicracker** [open-policy-agent/opa#1092]
Hi, I am using OPA for a very simple use case. Now I want to deploy my solution using OPA. But OPA docker image is ~35MB in size. Is it possible to reduce the size of this image by removing unnecessary components? I want to keep the option of getting future OPA updates as well. So manually compiling probably is out of question. Also I read about OPA go-library. Is it possible to use OPA in server mode using this library? I want to expose the REST API to my users.

**Comment by srenatus** [comment]
(ℹ️ Just another user, not talking for the project in any way)

I'm wondering that 35M strikes you as _much_ these days 😄

What would you propose to shrink it? Since #825, the docker images are built using the distroless/base image already.

> Is it possible to use OPA in server mode using this library? I want to expose the REST API to my users.

I believe #1018 was meant to make that possible.

**Comment by ankicracker** [comment]
@srenatus I understand that 35MB is not much of a problem nowadays, but I have a lot of data, which OPA will have to process. I was just wondering if it will make any difference if I remove any unused components from the base binary.

**Comment by srenatus** [comment]
> I was just wondering if it will make any difference if I remove any unused components from the base binary.

Hmm I'd be surprised. There's very little cruft in OPA -- did you have something specific in mind?

**Comment by tsandall** [comment]
@ankicracker like @srenatus said, OPA is fairly lightweight. There are very few dependencies. It's unlikely that removing any of the OPA components will have an impact on OPA's ability to handle the data sets you want to throw at it. If you're interested in embedding OPA as a library, take a look at https://github.com/open-policy-agent/example-api-authz-go. Closing this for now as I don't think there's anything else to cover.
