### ISSUE TITLE
How to use OPA go service

### ISSUE THREAD

**Issue by ankicracker** [open-policy-agent/opa#1097]
Hi, I tried the library as suggested by you in #1092. Now I have few doubts:
1. How is the Rest API exposed so they the user can `curl` and get the results?
2. How will I feed the `data.json` files and the policy modules to the OPA? Is it through the configuration file? I could not understand.
3. The [API](https://github.com/open-policy-agent/example-api-authz-go/blob/master/internal/api) folder has code for http server. But this seems a normal rest api which will simply serve the data asked by user.
4. Currently I am using OPA executable and it exposes a api which I curl to query OPA. I feed policy modules and data using the same rest api. How can I achieve the similar flow with this library?

I think, my issue is similar to #951, but I am not able to understand much. Is there any example where the HTTP server is also implemented as a library. Any help is appreciated.

**Comment by tsandall** [comment]
@ankicracker take a look at the opa package in that example repository. It shows how you can configure the OPA to pull down bundles (gzipped tarballs containing policy & data), report status, etc.

If you're going to embed OPA as a library, I wouldn't recommend embedding the OPA HTTP server.

**Comment by yashhere** [comment]
Hi @ankicracker, I am also looking in the same problem for some time now. It seems that there is a server component which can be imported in your service. But as I am currently learning Golang, I was not able to understand the code completely.

@tsandall I was trying to use push data to OPA using a GRPC service and the users would be able to query OPA using its exposed API. So it makes sense not to have two separate services running. So I was trying to integrate both GRPC server and OPA-as-a-library to my service. But above you say
> If you're going to embed OPA as a library, I wouldn't recommend embedding the OPA HTTP server. 

Is there any specific reason not to try integrating OPA HTTP server in the service?

**Comment by yashhere** [comment]
Yeah, I was looking into this particular plugin. It seems promising for my use case, but then I was not able to understand, how the users will query OPA for decision making? As far as I understand, this plugin is not exposing any API for end users to query.

**Comment by tsandall** [comment]
If you try out that plugin you'll see that it exposes the standard OPA APIs in addition to an extra gRPC interface that implements the Envoy ext_authz API.

Closing this issue for now as I don't think there is anything else to add.
