### ISSUE TITLE
"put" same document to same location results in 204 vs expected 304

### ISSUE THREAD

**Issue by SandyWalsh** [open-policy-agent/opa#1099]
# Expected Behavior
Second "put" should return a 304 as per docs

# Actual Behavior
Second "put" returns a 204

# Steps to Reproduce the Problem

  1. create a json data document
  2. start OPA service fresh
  3. put to OPA service endpoint at some location "foo"

    resp = requests.put("%s/v1/data/foo" % (url, ), data=payload, headers={"Content-Type": "application/json"})

  4. confirm you get 204 result
  5. do it again
  6. you should get a 304 (no change and doc already exists)

# Additional Info

Version: 0.10.1
Build Commit: 6c39555
Build Timestamp: 2018-10-30T20:27:04Z
Build Hostname: travis-job-02d92b63-ca08-4efd-b913-9e69c0e36ea3

**Comment by ashutosh-narkar** [comment]
As per the docs a `PUT` call will:
> Create or overwrite a document.  The server will respect the If-None-Match header if it is set to *. In this case, the server will not overwrite an existing document located at the path.

So if you do multiple `PUT` calls for the same path with the same/different data w/o the `If-None-Match: *` header, the server will create/overwrite the document at that path and hence return a `204` always.

OTOH, if you set the `If-None-Match: *` header and make a `PUT` call for a path with some data, the server returns a `204` the first time. Now every subsequent `PUT` call with the `If-None-Match: *` header set, for the same path with same or new data, will return `304` always. This happens as we are telling the server not to modify the document at the given path.

**Comment by tsandall** [comment]
@SandyWalsh per @ashutosh-narkar's you need to add If-none-match to indicate to the server that the request is conditional. Closing this as I don't think there's anything to do. Feel free to correct me!
