### ISSUE TITLE
How to use OPA inmem store?

### ISSUE THREAD

**Issue by yashhere** [open-policy-agent/opa#1100]
Hello there, I am trying to use OPA `inmem` store to store my `data.json` . I have multiple `data.json`. There are two functions -
1. One function will add the data to the the `inmem` store. There will be multiple calls to this function to add multiple `data.json`.
2. Other function will read the data from the `inmem` store and evaluate the results based on a policy module. This function will have access to the input document also.

Below is my progress - 
**Add() :-**
```go
func Add(ctx context.Context, data interface {})(response int, err error) {
    txn, err: = store.NewTransaction(ctx, storage.WriteParams)
    if err != nil {
        fmt.Println("transaction error: ", err)
    }
    
    storage.MakeDir(ctx, store, txn, storage.MustParsePath("/roles"))
    err = store.Write(ctx, txn, storage.AddOp, storage.MustParsePath("/roles"), data)

    if err != nil {
        fmt.Println("Write Error: ", err)
    }
    defer store.Abort(ctx, txn)
    response 1, nil
}
```

**Evaluation() :-**
```go
func Evaluate(ctx context.Context, inputData interface {}) {

  module = `
package example

import data.bindings
import data.roles

default allow = false

allow {
	user_has_role[role_name]
	role_has_permission[role_name]
}

user_has_role[role_name] {
	b = bindings[_]
	b.role = role_name
	b.user = input.subject.user
}

role_has_permission[role_name] {
	r = roles[_]
	r.name = role_name
	match_with_wildcard(r.operations, input.operation)
	match_with_wildcard(r.resources, input.resource)
}

match_with_wildcard(allowed, value) {
	allowed[_] = "*"
}

match_with_wildcard(allowed, value) {
	allowed[_] = value
}`

  r: = rego.New(
    rego.Query("data.example.allow"),
    rego.Module("policy.rego", module),
    rego.Store(store),
  )

  pr, err: = r.PartialEval(ctx)

  if err != nil {
    fmt.Printf("Error in partial evaluation", err)
  }

  examples: = [] map[string] interface {} {
    {
      "resource": "documentA",
      "operation": "write",
      "subject": map[string] interface {} {
        "user": "bob",
      },
    }, {
      "resource": "documentB",
      "operation": "write",
      "subject": map[string] interface {} {
        "user": "alice",
      },
    }, {
      "resource": "documentB",
      "operation": "read",
      "subject": map[string] interface {} {
        "user": "alice",
      },
    },
  }
  for i: = range examples {
    r: = pr.Rego(
      rego.Input(examples[i]),
    )
    rs, err: = r.Eval(ctx)

    if err != nil || len(rs) != 1 || len(rs[0].Expressions) != 1 {
      // Handle erorr.
    } else {
      jsonString, _ := json.Marshal(rs[0].Expressions[0].Value)
      fmt.Println(string(jsonString))
    }
  }
}
```

The code snippets are just for example. They may or may not work. I have taken most of the code from various places in your codebase. The `data` and `input` data are from [this](https://godoc.org/github.com/open-policy-agent/opa/rego#example-Rego-PartialResult) page. I am trying to modify your example to learn more about OPA codebase and GoLang.

So now, most of the examples in your documentation assume that the data is available from some object and almost all of the examples are using `inmem.NewFromObject()` function to create the store. I do not want to do that. I want to create a empty store, which will be accessible to both the functions. Whenever the `Add()` function is called with the data, the data should be stored in the memory. Currently, when I call `Write`, it overwrites the existing data. That is undesirable (as per my discussions on Slack with @ashutosh-narkar, this is the current behaviour of `Write` function). Also as in your example, the `root` objects (`roles` and `bindings`) are arrays. I saw `MakeDir()` in codebase, but it creates an object, is there any function to create an array or append data items to an existing array? (@ashutosh-narkar told me that this is not possible to do currently). Are there any plans to include this feature?

Lastly, I initialised `store` variable globally. Then I was able to `Write` to it in the `Add` function and I also succeeded in reading the value stored in the `store` variable from `Add` function. But when I try to read from the same variable in `Evaluate` function, it prints nothing.

**Comment by tsandall** [comment]
> I saw MakeDir() in codebase, but it creates an object, is there any function to create an array or append data items to an existing array?

No we don't have plans to extend the storage API. You should be able to implement all of the behaviour you mentioned using the current Write function.

> But when I try to read from the same variable in Evaluate function, it prints nothing.

You need to call `Commit` to make the writes visible to other transactions. Currently your Add function is calling Abort so the changes are undone.
