### ISSUE TITLE
wasm: built-in function parity

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1114]
List of built-in function categories:

- [x] comparison
- [x] numbers
- [x] aggregates
- [x] arrays
- [x] sets
- [x] types
- [x] bits
- [x] strings
  - [ ] sprintf
- [ ] conversions
- [ ] graphs
- [ ] net.cidr
- [ ] glob (partial)

# Requires investigation

- [ ] regexp

# Could be external

- [ ] units
- [ ] encoding
- [ ] tokens
- [ ] date/time
- [ ] crypto

# Must be external

- [ ] runtime
- [ ] trace
- [ ] time.now
- [ ] http

# Not supported

- [ ] rego

**Comment by ismailbaskin** [comment]
@tsandall What does it mean "moved this from Planned to To do"?

**Comment by tsandall** [comment]
It just means it's not in the short-term (e.g., within a few weeks) list of things to do.

**Comment by tsandall** [comment]
Closing this in favor of #2679, #2680, #2681, and #2682.
