### ISSUE TITLE
wasm: improve memory management strategy

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1121]
The current malloc implementation in the WASM-C library grows the heap by the required page count each time it's called (which is expensive and inefficient.) Rough benchmarks show that the latency is dominated by the heap operations. For the initial implementation, it may be possible to allocate the heap once.

**Comment by t83714** [comment]
@tsandall The `opa_malloc` function seems to allocate one page (64KB) even for a Boolean value.

Could this make it a more urgent issue as it seems a memory consumption issue rather than only a latency issue?

**Comment by tsandall** [comment]
@t83714 yes this a blocker to using the wasm support in non-trivial cases. We'll hopefully find time to work on this in the next month or so.

**Comment by t83714** [comment]
@tsandall Thanks a lot for the update 👍 

I was trying to figure out something similar to [this](https://github.com/open-policy-agent/npm-opa-wasm) for `scala` to make wasm policies run on the JVM.

As I had to use a fixed size java `ByteBuffer` as the imported memory, it's quite easy for me to hit the `out of memory` error.

I actually was not 100% sure whether it's the issue of the scala wasm runtime I used or the issue of OPA memory allocation --- not very familiar with the C code 😄  

Glad to know it's been covered by your plan already 👍
