### ISSUE TITLE
error details are misaligned when using tabs

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#1129]
## Actual Behavior

With `demo.rego` as
```
package demo

foo {
	as
}
```
where the line with `as` **starts with a tab character**, and I run `opa run demo.rego`, I find:

```
error: 1 error occurred during loading: demo.rego:5: rego_parse_error: no match found
                as
          ^
```

## Expected Behavior

The pointer `^` should respect the tabs _or_ remove them -- right now, it's position is calculated without accounting for the width of the characters that make up [the offset here](https://github.com/open-policy-agent/opa/blob/cfe1927a1c49b22f9dcd2efccc3c14d11595f66c/ast/check.go#L863-L864).

**Comment by tsandall** [comment]
Thanks for filing this. I noticed it a while ago but failed to open a ticket :sweat_smile: 

In this case, the error is reported by the parser. The ^ is generated here: https://github.com/open-policy-agent/opa/blob/master/ast/parser_ext.go#L752 (not in check.go).

I was suspicious of the location you linked to but upon reflection, I don't think there's a problem. The padding is constructed based on the String representation of the ref -- which will not contain tabs.

I haven't thought about the best way to resolve the issue in parser_ext.go. Perhaps we could construct the padding with a mix of spaces & tabs?

**Comment by srenatus** [comment]
> I was suspicious of the location you linked to but upon reflection, I don't think there's a problem. The padding is constructed based on the String representation of the ref -- which will not contain tabs.

Yup, indeed, I was pointing at the wrong thing; I've too noticed that when I was attempting to fix this 😄 

I think the real issue is [somewhere in here](https://github.com/open-policy-agent/opa/blob/59cd91e03457af755ded639c5d5c3c00e847e741/ast/parser_ext.go#L704-L749), as there's nothing accounting for the fact that a char could be "wider" than 1 char when printed... 

Maybe this could be fixed bluntly by a pre-processing step that replaces tabs by n spaces (for some n) before feeding it into the parser? 🤔
