### ISSUE TITLE
kubernetes subject access review

### ISSUE THREAD

**Issue by kfox1111** [open-policy-agent/opa#1130]
I have various users with different permissions granted via rbac. For example, cluster admins can do things regular users can't. I would like to write custom permissions that I bind to users. Currently only username and groups are available in the review. I don't have access to changing/updating the usernames/groups, In talking with the Kubernetes sig-auth team, they recommend doing a subject access review to check if a user has a permission to do something. So I need the ability to do subject access reviews from rego to enforce/disable particular checks. Can this currently be done somehow, or should we add the feature?

**Comment by tsandall** [comment]
Assuming you have OPA running, you can configure the API server to use OPA as an authorizer. See https://kubernetes.io/docs/reference/access-authn-authz/webhook/ for details on configuring the webhook authorizer. With this configuration, the API server will query OPA for authz decisions. The `input` document will be bound to the SubjectAccessReview request and the response from OPA will contain a SubjectAccessReview status.

Here's an old example (I'm not sure if it still works): https://gist.github.com/tsandall/d5575311cd6cd903b6f68334aa9afdce. In this example, the API server would be configured to query the `authorize` decision defined by the policy.

Note, if you only want to write custom permissions over create/update/delete requests (and not reads) you could also enforce the check using an _admission controller_. You can find an example of deploying OPA as an admission controller here: https://www.openpolicyagent.org/docs/kubernetes-admission-control.html.

**Comment by kfox1111** [comment]
I'm thinking the other way around for the SAR. I would like to configure k8s to use OPA for admission control, but have it be able to issue SAR's back to k8s so that k8s can review them. The equivalent of rego doing a 'kubectl auth can-i xxx yyy' for the incoming request. This would allow policy to decide what to do based on what roles/permissions in k8s the user has.

**Comment by tsandall** [comment]
Can you provide more information/detail about the use case? For example, how does the SAR query you want to execute from inside the policy relate to the resource in the admission control query? Is it for the same resource, a related resource, etc. If you can share concrete examples, that would be useful.

While you may be able to execute SAR queries via the `http.send` built-in function, I haven't tried this myself.

**Comment by kfox1111** [comment]
Say I wanted to create a trusted_networking permission.
Maybe something like:
apiGroups:[trusted_networking.k8s.io] resources:[*], resourceNames:[*]

I can use it in k8s role's such as cluster-admin or finer grained roles. And bind it to users/groups/service accounts via rbac for example.

Then I can load an OPA admission controller with a rego policy that would implement rules such as:
if user does not have the trusted_networking permission, block the request if is a service and it has an external_ip: section in the spec
if user does not have the trusted_networking permission, block the request if it is for an ingress and one of the multitenant unsafe annotations that nginx-ingress honors, is specified.

etc.

You can implement most of the policy logic now, but without some way of doing the sar, you have to manage a whole authz layer in the policy separate from the rbac layer already in k8s.

Does that make sense?

I didn't know about http.send. That might be a way to do it. I'll look into that a bit more. thanks.

**Comment by tsandall** [comment]
Thanks for the details!

FWIW, from my perspective, it would be simpler to encode the user/group/service->permission binding in the policy itself (or as context, such as via CRDs). For example:

```
package kubernetes.admission

deny["user not whitelisted to create external-facing services"] {
    input.request.kind.kind = "Service"
    count(input.request.object.spec.externalIPs) > 0
    not whitelisted
}

whitelisted {
    user := input.request.userInfo.username
    trusted_networking_users[user]
}

whitelisted {
    group := input.request.userInfo.groups[_]
    trusted_networking_groups[group]
}

trusted_networking_users = {"alice", "bob"}
trusted_networking_groups = {"netops"}
```

Note the permission binding could also come from a source of context like a CRD.

**Comment by kfox1111** [comment]
it would be if everything was implemented in OPA, yeah. but I already have a bunch of roles/rolebindings/podsecuritypolicies/etc already defined and working. I don't really want to reimplement all of that, along with all the logic podsecuritypolicies in k8s already implements.

**Comment by tsandall** [comment]
Cool. I'm going to close this issue for now as I think the original question has been answered. Feel free to raise other issues or ping me on Slack if you have other questions.

**Comment by kfox1111** [comment]
Ok. I think I have the function working. Its generically useful, so I submitted it to the library repository. I'm pretty new to rego, so could you please review and let me know if there are any unexpected bugs or improvements I could make?

PR:
https://github.com/open-policy-agent/library/pull/22
