### ISSUE TITLE
server should log error cause when returning HTTP 500 response

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1144]
# Expected Behavior

OPA should log internal errors that it encounters while processing API requests.

# Actual Behavior

Currently the errors are only visible in the logs if debug mode is enabled.

# Steps to Reproduce the Problem

  1. Load OPA with a policy that triggers an error, e.g., divide by zero (`p { 1 / 0 }`)
  2. Start OPA in server mode (`opa run -s x.rego`)
  3. Query OPA `curl localhost:8181/v1/data`

The OPA will log the API request/response transaction:

```
INFO[2019-01-09T08:34:20-08:00] Received request.                             client_addr="127.0.0.1:45950" req_id=1 req_method=GET req_params="map[]" req_path=/v1/data
INFO[2019-01-09T08:34:20-08:00] Sent response.                                client_addr="127.0.0.1:45950" req_id=1 req_method=GET req_path=/v1/data resp_bytes=295 resp_duration=5.413209 resp_status=500
```

The log does not include the error information returned in the API response:

```
$ curl localhost:8181/v1/data
{
  "code": "internal_error",
  "message": "error(s) occurred while evaluating query",
  "errors": [
    {
      "code": "eval_internal_error",
      "message": "div: divide by zero",
      "location": {
        "file": "home/torin/x.rego",
        "row": 4,
        "col": 3
      }
    }
  ]
}
```

# Additional Info

**Comment by repenno** [comment]
We will not be merging the changes due to:

https://github.com/open-policy-agent/opa/pull/1167#discussion_r248354705

**Comment by patrick-east** [comment]
After discussing this a bunch with @tsandall the conclusion was that we are going to close this for now.

The reasoning is that the info is already available when debug logging is enabled, it is in the HTTP response (so the logs from the client making the request should be able to dump the errors if required), and that it is already something that a decision logger could handle.

Related to the decision logger there are plans to add a stdout implementation in https://github.com/open-policy-agent/opa/issues/1334 which could also help with this sort of thing if the requirement is to have the errors logged in the servers output.
