### ISSUE TITLE
documentation example fails

### ISSUE THREAD

**Issue by alexch-darillium** [open-policy-agent/opa#1156]
# Expected Behavior
Example from https://www.openpolicyagent.org/docs/get-started.html 
     "5. Define a rule to identify servers in violation of our security policy."
should work:

> import data.servers
> violations[s] {
  s = servers[_]
  s.protocols[_] = "http"
  public_servers[s]
}

> violations[server]

# Actual Behavior
Error message appears:

> import data.servers
> violations[s] {
|   s = servers[_]
|   s.protocols[_] = "http"
|   public_servers[s]
| }
| 
1 error occurred: 1:1: rego_unsafe_var_error: var public_servers is unsafe

# Steps to Reproduce the Problem

  1. copy-pasting example body to repl
  2.
  3.

# Additional Info

**Comment by srenatus** [comment]
❓ Have you created the `data.json` file in the preceding step _2. Create a data file and a policy module._?

**Comment by tsandall** [comment]
@alexch-darillium check that you ran through all of the steps in order. As @srenatus mentioned, the error indicates that the step to create the policy file was missed.
