### ISSUE TITLE
getting false as return value, if any policy fails

### ISSUE THREAD

**Issue by msaadkhan31** [open-policy-agent/opa#1157]
# Expected Behavior
Proper message for the policy

# Actual Behavior
getting true/false

# Steps to Reproduce the Problem

  1.
  2.
  3.

# Additional Info
We are implementing OPA in our infrastructure. But have wrote multiple policy for evaluating the infra, but if any rule of the policy got failed, it returns 'false'. Is there any way to get the proper messages? Like to get the proper message of specific rule/policy that fails?

**Comment by msaadkhan31** [comment]
What's your slack name? i can't find you

**Comment by timothyhinrichs** [comment]
Slack name is
tim

Tim
