### ISSUE TITLE
Integration web portal

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#1194]
OPA has been integrated with 20+ cloud-native systems to provide rich, context-aware policy support, e.g. Kubernetes, Istio, Envoy, Linkerd, Terraform, Ceph, Minio.  Today there is no authoritative guide for users to understand what those integrations are, how they work, or how to get started.  

There should be an interactive web portal that helps users understand the integrations available with OPA.  It will be data-driven, so that new integrations can easily be added to the portal, and each entry will include code-snippets, videos, blog posts, github-repos, tutorials, reviews, and overall status of the integration.

**Comment by tsandall** [comment]
This feature has been proposed as part of GSoC 2019. https://github.com/cncf/soc#open-policy-agent-opa

**Comment by pandyamarut** [comment]
@tim-styra @tsandall @timothyhinrichs 
Hey! I'm Marut third year engineering grad. 
I would Like to Make proposal For this feature. 
I'm proficient in Python. 
I have also worked with some of the javaScript frameworks. 
I'm familiar with HTML and CSS.
website- marutpandya.xyz

**Comment by Harshagarwal19** [comment]
Hey, I am Harsh. I have experience in HTML, CSS, Javascript, Django and Python. I would like to make proposal for this feature.
@tsandall  @timothyhinrichs

**Comment by Infi-Knight** [comment]
Hi, my name is Ravi Soni. I would love to contribute in the development of this portal under gsoc this year. I have experience in React, D3, nodejs and python. Is there any design spec for the portal which we will use as a reference or we have to create it from scratch? Any starter tasks which we are required to complete?

**Comment by tim-styra** [comment]
@Infi-Knight @pandyamarut @Harshagarwal19 Glad you're interested!  There are no mockups right now showing what the screens will look like.  You'll get to design that as part of the project.

Couple of thoughts that will help when you're putting together your application.

1. We're hosting the openpolicyagent page on Github, so you'll be designing/implementing a static HTML/CSS/JavaScript page (of course the JavaScript can be dynamically modifying the page, but there's no backend server).

2. I'd expect at least the following information to be available for each integration.

* System name/logo that is integrated with OPA
* Repository with code integration
* Documentation
* Quick-start guide
* Video
* Company maintaining the integration (logo plus name)
* Sample OPA policy for the integration

3.  For each integration it'd good to give people a sense for how mature/battle-tested the integration is.  For example, has it been used in production?  By who?  At what scale?

**Comment by pandyamarut** [comment]
@tim-styra Thanks. I'll keep in mind before writing application.

**Comment by Infi-Knight** [comment]
@tim-styra thank you for the pointers.

**Comment by Harshagarwal19** [comment]
@tim-styra Thanks. I will make sure to include these points.

**Comment by Sai-Adarsh** [comment]
* @tim-styra Hey, I'm [Sai Adarsh S](http://sai-adarsh.github.io). I'm interested in working in [Integrating web portal](https://github.com/cncf/soc#interactive-website-detailing-opa-integrations) project as a part of GSoC 2019. I'm skilled in HTML, CSS, JS, Django, Python, Node.js and containers. 

* Glad that i saw your indicators in this issue. Having said that I shall working on this project and the proposal. Thanks.

**Comment by pandyamarut** [comment]
@tim-styra Do we have Any communication channel for GSoc'19 related talks?

**Comment by timothyhinrichs** [comment]
Nothing specific to GSOC.  But there are videos/slides on the github
readme: https://github.com/open-policy-agent/opa

Is that what you mean?  Or are you asking if there's a place to publish
talks resulting from the work done around GSOC once they happen?  I think
the answer is the same: https://github.com/open-policy-agent/opa

Tim

**Comment by pandyamarut** [comment]
@timothyhinrichs  Can we start new channel on slack for Gsoc'19. 
Just for Better communication with mentors.

**Comment by geekayush** [comment]
Hi @timothyhinrichs  @tsandall 
This idea interests me.
I am a frontend developer skilled in HTML, CSS, JS, jQuery, Bootstrap, Materializecss, Bulma and ReactJS. For the backend, I'll be taking NodeJS. I have a good knowledge of UI/UX as well.
As @pandyamarut stated above, Do we have any channel for communication?

**Comment by timothyhinrichs** [comment]
Hi Ayush.  Glad you're interested!  On OPA slack, there's a channel #gsoc19.

**Comment by DixonDalmeida** [comment]
is there any progress on this feature?

**Comment by tsandall** [comment]
@DixonDalmeida yeah, this was actually done back in November 2019. https://www.openpolicyagent.org/docs/latest/ecosystem/. The issue was not closed though. Doing that now.
