### ISSUE TITLE
IP Tables integration

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#1195]
One common use of policy is to set up IP packet filter rules in the Linux kernel.  The policy dictates what to do with different kinds of packets.  There have been several requests in the past to use OPA policies to control IPTables, but no one has come forth with an integration.  

An integration requires: designing the layout of IPTable rules using OPA's policy language, implementing the algorithms that generate IPTables from that layout, and writing the code that populates the generated IPTables rules into Linux.  And as usual tests and documentation.

**Comment by tsandall** [comment]
This feature has been proposed as part of GSoC 2019. https://github.com/cncf/soc#open-policy-agent-opa

**Comment by repenno** [comment]
This is an important feature that would have wide applicability.

**Comment by orangehaired** [comment]
I am interested in this issue. I am a GSOC 2020 participant. Can I send a purpose for this? Is Issue still going?

**Comment by tsandall** [comment]
@orangehaired someone actually [worked on this last year](https://github.com/open-policy-agent/contrib/tree/master/opa-iptables) so it's not available anymore. Closing this issue to avoid confusion in the future.
