### ISSUE TITLE
Problems with Go 1.10/1.11 debugging OPA with delve

### ISSUE THREAD

**Issue by sbueringer** [open-policy-agent/opa#1210]
# Expected Behavior

I expect to be able to debug OPA with delve when compiling it with debug symbols.

# Actual Behavior

I got the following error:
````
could not launch process: could not get .debug_frame section: could not find .debug_frame section
````

# Steps to Reproduce the Problem

I used the following commands:
````
go build -o /tmp/___go_build_main_go -gcflags "all=-N -l" $GOPATH/src/github.com/open-policy-agent/opa/main.go
dlv --listen=localhost:44317 --headless=true --api-version=2 exec /tmp/___go_build_main_go -- run --server --addr=http://localhost:8181
````

# Additional Info

It works with Golang 1.9. It seems to be related to the following go issue https://github.com/golang/go/issues/23733. The behaviour seems to be triggered by the usage of the `plugins` package.

Maybe I'm just doing it wrong? :)

**Comment by tsandall** [comment]
I don't use `dlv` so I don't have expertise here. If the issue has to do with the Go stdlib plugin package, you could try building OPA with CGO disabled. The plugin package is only used if CGO is enabled.

**Comment by sbueringer** [comment]
Unfortunately that didn't help:

````
export CGO_ENABLED=0; go build -o /tmp/___go_build_main_go -gcflags "all=-N -l" $GOPATH/src/github.com/open-policy-agent/opa/main.go
dlv --listen=localhost:44317 --headless=true --api-version=2 exec /tmp/___go_build_main_go -- run --server --addr=http://localhost:8181
````

**Comment by teq0** [comment]
The only way I got unblocked was to go to go 1.12.beta2. The issue says 1.10.4 should work but it didn't work for me.

**Comment by sbueringer** [comment]
Oh thx, that's good news. I wasn't aware it's fixed with newer versions. I'll try it and then update the issue.

**Comment by sbueringer** [comment]
I updated to go 1.12 and also used the new dlv version. Now it works for me, too. (even without CGO_ENBALED=0).

Thanks for the info @teq0.
