### ISSUE TITLE
Nitpick: Add trailing new line when pretty printing

### ISSUE THREAD

**Issue by anadon** [open-policy-agent/opa#1213]
Just when using the terminal and curl, it would be nice to have a trailing new line so the command prompt starts on a new line and not on the same line after a response.  This should be fairly trivial.

**Comment by tsandall** [comment]
We could likely make the change [here](https://github.com/open-policy-agent/opa/blob/master/server/writer/writer.go#L88) (for 2xx responses) and [here](https://github.com/open-policy-agent/opa/blob/master/server/writer/writer.go#L66) (for 4xx and 5xx responses).

**Comment by tsandall** [comment]
Fixed by #1226
