### ISSUE TITLE
Enhancement: Scope rules as part of rule name

### ISSUE THREAD

**Issue by anadon** [open-policy-agent/opa#1220]
Instead of having something like
```
package level1.level2

rule{
...
}
```

Allow scoping in the rule name like a usual reference
```
level1.level2.rule{
...
}
```

Now, I may be misunderstanding some aspect of this.  But something in this is useful.

**Comment by tsandall** [comment]
I'd like to leave this issue open for a while and see what if people have thoughts. @anadon could you include more detail on _why_ you think we should add this? Generally, I'd rather avoid adding syntax to the language unless it's addressing a common issue (e.g., like we did with `:=` and `==` to deal with confusion around `=`)

**Comment by anadon** [comment]
In the grammar, there is a mix of Names and References.  If Names were kept purely in the lexing, and references used instead in the grammar it should be more elegant in implementation, microscopically more consistent for users, and be a little more general.

Functionally, this would let me define the exact same runtime structures as if they were assembled from a number of different files.  I like that symmetry.

**Comment by tsandall** [comment]
In OPA, rules are just statements that assign values to variables. For example, the statement `x = 3` can be interpreted as a rule that assigns the value 3 to the variable x in all cases. You can make this assignment conditional by including a body, e.g., `x = 3 { input.a = 1 }`. Now this rule assigns the value 3 to the variable x if input.a is equal to 1. You can understand rules intuitively as "<name> is <value> if <body>".

We put rules into packages to qualify the variables with a namespace.

I'm not sure how to interpret a rule like `x.y.z = 3 { input.a = 1 }` other than variable z in package x.y has value 3 if input.a equals 1. Is this what you're suggesting?

**Comment by anadon** [comment]
That is what I am suggesting.

**Comment by tsandall** [comment]
We don't have plans to add this feature for the time being. We can always revisit it in the future.
