### ISSUE TITLE
Enhancement: Improving Compile REST API unknown inference

### ISSUE THREAD

**Issue by anadon** [open-policy-agent/opa#1221]
In a given rule, mark all members in the `data` root scope as unknown until explicitly specified in order to have better unknown detection.  It is perfectly legitimate to over specify unknowns, so it should be acceptable if everything is considered unknown until it is not.

**Comment by tsandall** [comment]
Improved support for specifying unknowns has been on the back burner for a little while. One idea we had is to let the policy author declare the portions of data that are unknown. For example:

```
package petstore.datafiltering

unknown data.petstore.pets

allowed[pet] {
  pets[pet].owner = input.user
}
```

This simplifies the integration a bit since the caller doesn't have to know what unknowns the policy depends on.

**Comment by anadon** [comment]
Is unknown different than undefined?  If those concepts could be merged within rego, this might solve itself.

**Comment by tsandall** [comment]
They are related but different concepts that cannot be merged. Undefined means that a document or variable has no value. Marking a document or variable as unknown tells the evaluator to save expressions that depend the unknown and return them to the caller.

**Comment by anadon** [comment]
Would it be a best practice to have each reference explicitly set to a default of unknown or undefined?  If so, what might that look like?  Would it be broader use of `default` and warnings on references which have not been given a default?

**Comment by tsandall** [comment]
Closing this for now as the current caller-supplied unknowns approach seems to be working. We can revisit how unknowns are specified in the future.
