### ISSUE TITLE
Expose Go default metrics

### ISSUE THREAD

**Issue by sbueringer** [open-policy-agent/opa#1231]
# Expected Behavior

The Go default metrics should be exposed via the Prometheus metrics endpoint.

# Actual Behavior

Currently no go_ metrics are exposed

# Steps to Reproduce the Problem

  1. Start OPA
  2. Curl metrics endpoint

# Additional Info

This would require only a 1 line change here: https://github.com/open-policy-agent/opa/blob/master/server/server.go#L369. The following line whould have to be added:
````
promRegistry.MustRegister(prometheus.NewGoCollector())
````

If it's ok, I would open a PR for this.

**Comment by tsandall** [comment]
@sbueringer a PR for this would be great!

**Comment by tsandall** [comment]
Fixed by #1233
