### ISSUE TITLE
Update release script to exclude node_modules dir

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1237]
The `build/gen-release-patch.sh` script is executed by the `release-patch` target to generate a patch set that prepares the release. When the script was originally written, the node dependencies for the website were not vendored--however, since we updated the frontpage a few months ago, these dependencies *are* vendored under docs/book/node_modules. As a result, the search-replace inside the release script executes on every file under the node_modules dir.

We should just update the release script to exclude the node_modules dir.

**Comment by tsandall** [comment]
This will be resolved by #1277

**Comment by alindeman** [comment]
This is still in `To do` on the board. It can probably be moved to Done.

**Comment by tsandall** [comment]
Thanks @alindeman.
