### ISSUE TITLE
Evaluate non existing entry in input.

### ISSUE THREAD

**Issue by hasinthaindrajee** [open-policy-agent/opa#1241]
My input post data will have the below format
{
"input" : { "sub" : "username", "email", "email@test.com"}
}

I need to write a rego policy to evaluate whether sub is present or not in the incoming request.
ie the below should evaluate to to true since no sub is present

{
"input" : { "email", "email@test.com"}
}

I tried multiple things such as comparing with null, undefined or using is_null inbuilt method. I coun't get any of them working. Appreciate your help on this. I am using the docker image version openpolicyagent/opa:0.10.3

**Comment by tim-styra** [comment]
To test if 'sub' exists, you write 'input.sub'.  To test if 'sub' does NOT exist you write 'not input.sub'.

For example, suppose you want to deny the request if 'sub' is missing.

deny {
    not input.sub
}

Hope that helps.  Closing the issue.  Feel free to ask on slack or reopen the issue if you have more questions.

**Comment by almostprogrammer** [comment]
@tsandall what if  my input may or may not keys that should be evaluated the same?

Let's say this input where `bar` may be optional

```
{
"input" : { "foo" : "foo", "bar", "foo"}
}
```
And inside my rule either `input.foo` or `input.bar` should result in true

```
default allow = false
allow {
  foos := [input.foo, input.bar]
  foos[_] = "foo"
}
```

The above rule will always result in `false` if input won't have `foo` or `bar`, even though  another key could have the value `foo`. 

I don't know how to resolve this apart from having different rules: one rule could handle `input.foo` and another - `input.bar`. But that approach would result in huge code duplication if, for instance, I have other validation 

```
default allow = false
allow {
  # validation 1
  #  ....
  # validation n
  foos := [input.foo, input.bar]
  foos[_] = "foo"
}
```

**Comment by tsandall** [comment]
@almostprogrammer if you want "allow" to be true if either input.foo or input.bar equals "foo" you could write:

```
allow {
  keys := ["foo", "bar"]  # define array of keys
  key := keys[_]          # iterate over array of keys
  input[key] == "foo"     # check if key value is equal to foo 
}
```

If **any** of the key values are equal to foo, then allow is true.

Alternatively, if you want to define the logic separately for re-use, you could use a helper function:

```
allow {
  keys := ["foo", "bar"]  # define array of keys
  key := keys[_]          # iterate over array of keys
  foo_logic(input[key])
}

foo_logic(x) {
  x == "foo"
}
```

Note, this would be equivalent to defining allow twice:

```
allow {
  foo_logic(input.foo)
}

allow {
  foo_logic(input.bar)
}

foo_logic(x) {
  x == "foo"
}
```
