### ISSUE TITLE
Enhancement: Add array.slice function

### ISSUE THREAD

**Issue by teq0** [open-policy-agent/opa#1243]
https://github.com/open-policy-agent/opa/issues/851 mentions both slice and concat operations on arrays. array.concat was added and https://github.com/open-policy-agent/opa/issues/851 was closed, but I believe there is still a valid need for slice.

**Comment by Infi-Knight** [comment]
I know this was supposed to be a "low-hanging-fruit" but I am stuck and would really appreciate some help:
Going through the code I think that I need to follow these steps:
1.  Register `ArraySlice` in `ast/builtins.go`
2. Implement and register `builtinArraySlice` in `topdown/array.go`
3. Write requisite tests and make sure it works

For the first step I wrote following code:
```go
//Arrays
ArrayConcat,
ArraySlice


// ArraySlice returns a slice of a given array
var ArraySlice = &Builtin{
	Name: "array.slice",
	Decl: types.NewFunction(
		types.Args(
			types.NewArray(nil, types.A),
			types.NewNumber(),
			types.NewNumber(),
		),
		types.NewArray(nil, types.A),
	),
}
```

For the second step, I have setup the following skeleton:
```go
func builtinArraySlice(a, i, j ast.Value) (ast.Value, error) {

	// initialize required variables

	// arrA, err := builtins.ArrayOperand(a, 1)
	// if err != nil {
	// 	return nil, err
	// }

	startIndex, err := builtins.IntOperand(i, 2)
	if err != nil {
		return nil, err
	}

	stopIndex, err := builtins.IntOperand(j, 3)
	if err != nil {
		return nil, err
	}

	arrB := make(ast.Array, 0, stopIndex-startIndex)

	// implement the logic for slicing

	return arrB, nil

}
```

Now when I try to register this new function:
```go
func init() {
	RegisterFunctionalBuiltin2(ast.ArrayConcat.Name, builtinArrayConcat)
	RegisterFunctionalBuiltin2(ast.ArraySlice.Name, builtinArraySlice)
}
```
editor(vscode) hints
 following error:
<img width="928" alt="opa" src="https://user-images.githubusercontent.com/20504781/54860758-c59c9900-4d44-11e9-98de-c76439311ea7.png">

`cannot use builtinArraySlice (type func(ast.Value, ast.Value, ast.Value) (ast.Value, error)) as type FunctionalBuiltin2 in argument to RegisterFunctionalBuiltin2`


What am I doing wrong here?

**Comment by tsandall** [comment]
@Infi-Knight You'll need to use `RegisterFunctionalBuiltin3` instead of `RegisterFunctionalBuiltin2` here. The former takes accepts 3 parameters while the latter only accepts 2.
