### ISSUE TITLE
Enhancement: Add a jsonpatch apply function that works with objects under input and data documents

### ISSUE THREAD

**Issue by lxnch** [open-policy-agent/opa#1244]
Add a function that can apply a [JSON Patch document ](https://tools.ietf.org/html/rfc6902#section-3) i.e. array of [Operation Objects](https://tools.ietf.org/html/rfc6902#section-4) on a given OPA document (either nested under the input document, or under the data document), that returns a new object with the patches applied, which can be used in combination with the `with`  keyword.

**Comment by scevallos** [comment]
Hello, I'm looking at implementing this feature.
The [Development docs](https://github.com/open-policy-agent/opa/blob/master/docs/devel/DEVELOPMENT.md#built-in-functions) say that implementations of built-in functions should avoid third-party dependencies. However, I was looking at using the [json-patch library](https://github.com/evanphx/json-patch), as it might be unreasonable to expect an implementation of JSON Patch to live and be maintained all within the OPA codebase.
Is fine to ignore that in this case, and make use of the json-patch library linked above?

**Comment by patrick-east** [comment]
There was another issue tracking this type of functionality over at #1617 The [last update](https://github.com/open-policy-agent/opa/issues/1617#issuecomment-619539968) was that we were not pursuing the full on JSON path functionality.

@scevallos was there a use-case in mind that required the full JSON patch functionality where the other helpers implemented as part of #1617 wouldn't work? (To clarify, I'm not opposed, just want to make sure we have some documentation around why we'd be adding it)

> The Development docs say that implementations of built-in functions should avoid third-party dependencies. However, I was looking at using the json-patch library, as it might be unreasonable to expect an implementation of JSON Patch to live and be maintained all within the OPA codebase.
Is it fine to ignore that in this case and make use of the json-patch library linked above?

Looking at https://github.com/open-policy-agent/opa/pull/2686 I have a couple of concerns WRT this approach:

First, the reasoning behind limiting the third party depedencies is to keep OPA as simple as possible to use as a golang library. Any time we add a new one we run the risk of causing version conflicts with anyone using OPA who also happens to use the same third party libraray. Being that OPA is often embedded in API authz use-cases it seems likely that a JSON patch library would fall into that kind of "shared" category and cause problems.

The second concern is that we have to round-trip the AST objects through JSON strings to use the library which will cause a somewhat significant performance hit for anyone using this compared to if we had an implementation that operated on the raw AST objects.

The good news is that we have all (most?) of the building blocks required to implement this natively for AST objects from the implementation of the `object.*` and `json.*` builtins. Assuming we move forward with adding the patch builtin I think that is probably the best way to approach it.

**Comment by scevallos** [comment]
Hi @patrick-east,
Thanks for the context, I was not aware of the discussion about this issue on #1617.

I don't personally have use-cases that would require this, but I saw value in providing this functionality. I was looking through the issues tagged with "help-wanted" and thought this would be a good place for me to contribute. I'm fine with scrapping #2686 if we think the helpers are suffice for possible use cases.

Thanks also for the feedback on the approach! If we do decide to build the JSON Patch functionality, I'm happy to address your concerns by eliminating use of the library and implementing it natively.

**Comment by patrick-east** [comment]
>  I'm fine with scrapping #2686 if we think the helpers are suffice for possible use cases.

I would lean towards that until we have some additional use-case. I'm going to close out this issue for now too. Anyone is welcome to re-open as needed.
