### ISSUE TITLE
Anonymous OPA version reporting

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1253]
OPA does not currently include any kind of "phone home" feature which makes it difficult to gauge version adoption.

We propose adding version reporting feature whereby OPA would notify a central service that it had started (and what version it was running.) The version information is currently compiled into the binary so this would be as simple as sending a HTTP POST request to a public server.

Details:

* **The feature will be on-by-default but easily disabled, e.g., `opa run --server --incognito`**.
* The upload will be best effort. If OPA is not able to connect to the public server or a response is not received within some time-window, it will not affect OPA's startup.
* The upload will only be attempted by the `opa run` command (not `opa eval` or other commands.)
* Upload payloads will include the OPA version number (e.g., `0.10.5`). The service can reply with the latest version and OPA can tell users if they're out-of-date.
* The results will be aggregated and published on a public website.

**Comment by pwmorreale** [comment]
You do realize that as security software, a (likely) good number of installations will turn this feature off thus possibly skewing the returned metrics?  

IOW, it may be difficult to draw valid conclusions/trends from such incomplete data.

**Comment by tsandall** [comment]
We expect that in many deployments, the feature will either be disabled or outbound traffic will be firewalled. That said, I think any single metric we use to gauge adoption will be flawed. The best we can do is collect as many signals possible and then look at trends over time. As long as we're transparent about the metric collection, I think people will be understanding.

One thing I'll reiterate is that in the future this feature could be configured to report differently (e.g., perhaps an organization wants to collect their own usage metrics or perhaps an organization finds it acceptable to manually gather the information from their OPAs.) The initial version (phoning home to metrics.openpolicyagent.org) should lay the groundwork for this.

**Comment by tsandall** [comment]
After discussing this with different people recently we have decided to scrap the plan to report usage metrics and simply report on the version of OPA. This will let users know when new versions are available and it will help us make better decisions about deprecation and other changes in the future.
