### ISSUE TITLE
PATCH doesn't interpret JSON-Pointer escaping in the path attribute

### ISSUE THREAD

**Issue by glb** [open-policy-agent/opa#1254]
I have a document where I'd like to have `/` characters in the keys of an object, and I'd like to use `PATCH` requests to update the document contents. However, it seems that OPA isn't interpreting the escape string `~1` the way I'd expect it to, and if I use the `/` character without escaping OPA (correctly) interprets the string as a path with multiple levels.

# Expected Behavior

Because the documentation refers to JSON-Patch

> The server accepts updates encoded as JSON Patch operations. The message body of the request should contain a JSON encoded array containing one or more JSON Patch operations. Each operation specifies the operation type, path, and an optional value. For more information on JSON Patch, see RFC 6902.

and RFC 6902 (JSON-Patch) says that 

> [...] operation objects MUST have exactly one "path" member.
> That member's value is a string containing a JSON-Pointer value
> [RFC6901] that references a location within the target document (the
> "target location") where the operation is performed.

 I expected escaping in the JSON patch `path` attribute to work as defined in [RFC 6901](https://tools.ietf.org/html/rfc6901#section-3)

>    Because the characters '\~' (%x7E) and '/' (%x2F) have special
>   meanings in JSON Pointer, '\~' needs to be encoded as '\~0' and '/'
>   needs to be encoded as '\~1' when these characters appear in a
>   reference token.

So for example, to get a `/` character I'd use `~1`.

# Actual Behavior

The escaping isn't unescaped ... I get `~1` instead of `/` in the patched document.

# Steps to Reproduce the Problem

  1. Create the parent document
```
curl -X PUT \
  http://localhost:8181/v1/data/example \
  -H 'Content-Type: application/json' \
  -H 'If-None-Match: *' \
  -d '{
	"example": {
		"github.com/openpolicyagent": { "message": "OPA is awesome!" }
	}
}'
```
  2. Modify the parent document
```
curl -X PATCH \
  http://localhost:8181/v1/data/example/example \
  -H 'Content-Type: application/json-patch+json' \
  -d '[{
	"op": "add",
	"path": "foo~1bar",
	"value": {
	  "message": "this is an example"
	}
}]'
```
  3. Retrieve the document
```
curl -X GET \
  http://localhost:8181/v1/data/example/example
```

  4. Result
```
{
    "result": {
        "foo~1bar": {
            "message": "this is an example"
        },
        "github.com/openpolicyagent": {
            "message": "OPA is awesome!"
        }
    }
}
```

# Additional Info

**Comment by glb** [comment]
Digging into the code, I see that [ParsePathEscaped](https://github.com/open-policy-agent/opa/blob/fd86f74231f89ecb796cf6cd89d54400b6eb7bcf/storage/path.go#L35) expects the `path` attribute to be URL-escaped.

This works but is surprising ... I wasn't familiar with JSON-Pointer escaping using `~1` and can't say I'm a huge fan, but the documentation doesn't create the expectation that `%2F` would work either.

Thoughts? I'd be happy to try to create a PR to support both styles of path escaping.

**Comment by tsandall** [comment]
@glb nice find! Thank you for the excellent bug report. Yes indeed, OPA should be unescaping ~1 and ~0 properly.

Two thoughts.

1. JSON Pointer only escapes '/' and '~' characters like you describe, but that means that URL unescaping should _not_ be performed. I'm a bit hesitant to change that behaviour right now.

2. Changing the `prepareV1PatchSlice` function to properly unescape ~1 and ~0 to '/' and '~' respectively is welcome. Please update the server_test.go cases to cover these when you make the change.

If you need any pointers, feel free to ask.

**Comment by glb** [comment]
@tsandall agreed on 1 -- I would be similarly hesitant as others may be using the existing behaviour.

I was planning on updating `ParsePathEscaped` since it's the function that's currently doing the unescaping for `prepareV1PathSlice`. Make sense?

https://github.com/open-policy-agent/opa/blob/96289e8589e1fcda38e35d79628d3d1b66dbd61b/server/server.go#L1844

**Comment by tsandall** [comment]
@glb I'd rather deal with this in the HTTP server where we explicitly accept JSON Patch objects. The storage code doesn't make such guarantees. With that in mind, I'd only escape for the portion of the path in the JSON Patch, i.e., not the portion from the HTTP URL Path.
