### ISSUE TITLE
Summary of builtins in docs

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#126]
It'd be great if somewhere in the docs we had a "reference guide" for people who are familiar with the basics but need clarity on something specific.  For this issue, it'd be great if we had a reference guide for the builtins that Rego supports (e.g. addition, string-concatenation).  Perhaps a handful of tables, one for each type of scalar value and the builtins Rego supports for that type.

**Comment by timothyhinrichs** [comment]
Just committed
