### ISSUE TITLE
Question: checking if array does not include an element

### ISSUE THREAD

**Issue by almostprogrammer** [open-policy-agent/opa#1263]
It seems that the only way we could find it out is to "filter" given array to get an array of filtered values and then compare its size to the original array's size.

I can describe this flow using rego syntax:

```
colors := ["red", "blue", "green"]
nonRedColors := [ color | color = colors[i] ; colors[i] != "red"]
count(colors) != count(nonRedColors) 
```

Is this the only way it's possible to find out an element is not included in array?
It is possible to have a separate function that would do this, but isn't there a built in function that can handle this, because this use case seems common

**Comment by tsandall** [comment]
You can write a helper function or rule:

```
contains(colors, elem) {
  colors[_] = elem
}
```

Then refer to that in your policy:

```
not contains(["blue", "green"], "red")
```

If you're constructing the array inside your policy (i.e., it's not supplied as an input) then you consider using a set instead: `s := {"blue", "green"}; not s["red"]`.

**Comment by almostprogrammer** [comment]
Will future releases include some built-ins for such frequently used operations to remove the need of writing custom helpers?

**Comment by tsandall** [comment]
We've been kicking around the idea of a "for all" quantifier that would let you express "Does not exist" as well as other common patterns.

**Comment by almostprogrammer** [comment]
Cool, thanks!

**Comment by tsandall** [comment]
Closing this issue for now. Thanks for opening it.

**Comment by shapled** [comment]
```rego
contains_element(arr, elem) = true {
  arr[_] = elem
} else = false { true }
```

Need to be explicitly declared as a bool type in some cases

```rego
v = [a, b] {
  element_sets = [{1, 2}, {2}]
  a = [contains_element(s, 3) | s = element_sets[_]]
  b = [contains_element2(s, 3) | s = element_sets[_]]
}

contains_element(arr, elem) = true {
  arr[_] = elem
} else = false { true }

contains_element2(arr, elem) {
  arr[_] = elem
}
```

Eval result:
```json
{
    "v": [
        [
            false,
            false
        ],
        []
    ]
}
```

**Comment by kubernegit** [comment]
Why is this helper function actually working? If I define a rule and there is only one statement within that rule that is `false` or `undefined` the whole rule will evaluate to `undefined`. With the expression 
```
arr[_] = elem
```
we loop through the whole array and compare each element with `elem`. In my understanding this function should only evaluate to `true` if **all** elements are eqal to `elem`. What am I missing?

**Comment by anderseknert** [comment]
@kubernegit see https://www.openpolicyagent.org/docs/latest/policy-language/#universal-quantification-for-all

If you _do_ want to check that all elements in `arr` are equal to `elem`, you could use a comprehension to count all elements equal to `elem` and then compare it to the size of the `arr`... something like this:

```rego
allow {
    equal_to_elem := [x | x := arr[_]
                                        x == elem]
    count(arr) == count(equal_to_elem)
}
```
Alternatively, you could just turn the array into a set and make sure only `elem` is present after:

```rego
allow {
    {x | x := arr[_]} == {elem}
}
```

Finally, there's some work in progress to investigate an [every](https://github.com/open-policy-agent/opa/issues/2090) keyword to make this even simpler.

**Comment by anderseknert** [comment]
@RafalMaleska using later version of OPA (and I think, the latest version of Gatekeeper, since that seems to be used here), you could just use `in` to check for membership:

```rego
import future.keywords

your_rule {
    # Use some ... in to iterate over all containers
    some container in input.review.object.spec.containers

    # Use in to check for presence in other collection
    container in input.parameters.excludedContainers
}

```
