### ISSUE TITLE
Dockerfile doesn't specify a non-root `USER`

### ISSUE THREAD

**Issue by glb** [open-policy-agent/opa#1267]
I'd like to be able to deploy OPA in k8s with a restrictive security policy without having to specify `runAsUser: {something}` in the pod's [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), because that leaks information about what userID is appropriate from inside the container out to the pod specification.

# Expected Behavior

If there is no reason for OPA to run as `root`, then the `Dockerfile` should specify a `USER` line with a numeric value other than `0` so that Kubernetes can enforce the `runAsNonRoot` restriction without people jumping through hoops.

Any non-zero number will do, and unfortunately a named user will not, as k8s pod `securityContext` `runAsNonRoot` can't resolve the user ID: https://github.com/kubernetes/kubernetes/issues/40958

# Actual Behavior

Excerpted from a k8s `Deployment` template spec:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
```

Result:

`kubectl describe pod opa-[tab]`
```
Error: container has runAsNonRoot and image will run as root
```

Updating the securityContext to add `runAsUser: 1` allows the image to run.

# Steps to Reproduce the Problem

  1. Create a pod with a `securityContext` that requires the container to run as a non-`root` user and does not explicitly specify a user to run as. Alternatively, have a [pod security policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) that prevents pods from running as `root`.
  2. The pod will fail to start with a `CreateContainerConfigError`.

# Additional Info

Adding a `USER 1` line to the `Dockerfile.in` will set the user that OPA runs as to non-`root`. I'm not super-familiar with the base image you're using, but really any non-zero value would do. I tend to use the following in my `Dockerfile`s:

```Dockerfile
# Any non-zero number will do, and unfortunately a named user will not,
# as k8s pod securityContext runAsNonRoot can't resolve the user ID:
# https://github.com/kubernetes/kubernetes/issues/40958
USER 1
```

**Comment by tsandall** [comment]
@glb can you elaborate a bit on this:

>because that leaks information about what userID is appropriate from inside the container out to the pod specification.

Wouldn't putting `USER 1` inside the Dockerfile be leaky as well?

**Comment by glb** [comment]
@tsandall perhaps I'll phrase it a different way. When you put `USER 1` in the Dockerfile, the person writing the Kubernetes deployment (in this case) doesn't have to know what userid is safe to use in the container. It's not a problem that I can _discover_ that the container runs as `USER 1`, but it is a bit frustrating if I need to _figure out_ that the container _can_ run as `USER 1` (which certainly seems to be working for me) and put that into my k8s deployment spec. It's nice if the container is ... self-contained (sorry, I couldn't come up with another word).

I don't think the user ID matters in the container you're building, but I haven't dug into the details of what's in the base image. I'm actually a little curious why you're not building a `FROM scratch` image, but that's perhaps an investigation for another day.

**Comment by tsandall** [comment]
We used to use scratch, however, since we added support for loading Go plugins we had to enable CGO. That requires libc so scratch and alpine are out. Distroless seemed like the best option since it's very lightweight and appears to be well-maintained.

I'm a bit worried about changing the USER in the Dockerfile because while the internals of OPA don't rely on root capabilities, if users are configuring OPA to bind/listen on :443 then that would require root...I think?

Have you considered automating the injection of OPA into pods that need it?

**Comment by glb** [comment]
re: plugins: I'll have to take your word for it, that's something I haven't looked at yet.
re: "automating the injection of OPA into pods that need it", I don't know what that means, sorry. Could you elaborate?

For your concern: If a person needs to expose the container on `:443`, it's easy to bind a higher port internally and then map that port to `:443` on the host:

```sh
sudo docker run -p 443:8443 -d openpolicyagent/opa:latest run --server --addr :8443 ...
```

This is what I'd consider normal practice when running a service inside a container.

In theory, you should be able to add the `NET_BIND_SERVICE` capability as another option so that the process inside the container is able to bind to `:443` if someone really wants to do that (?) but my experiments with that are not succeeding right now. 🤔 

> CAP_NET_BIND_SERVICE
>              Bind a socket to Internet domain privileged ports (port
>              numbers less than 1024).

People tend to get antsy about containers getting privileges too.

As an alternative, would you consider a parallel `Dockerfile` that results in something like `opa-rootless` that is identical to the original but has the `USER 1` line?

In the worst case, someone in my situation could maintain an alternative `Dockerfile` that's essentially:

```
FROM open-policy-agent/opa:latest
USER 1
```

but that's not a path I'd really like to go down -- I'd really like to stick with "official" images.

**Comment by tsandall** [comment]
Adding a rootless stream of the container image sounds like a good solution. I'd expect this to be something like...

```
openpolicyagent/opa:0.10.5-rootless
```

I think it should be relatively easy to add this:

1. Create a new Dockerfile_rootless.in file
2. Update the Makefile to build/tag/push the rootless images where the other (regular and debug) images are handled

If you'd like to submit a PR for this, I'd be happy to merge to merge it.

**Comment by tsandall** [comment]
I forgot to reply to this comment:

> re: "automating the injection of OPA into pods that need it", I don't know what that means, sorry. Could you elaborate?

The original problem you mentioned seems to be around making the OPA deployment configuration as simple as possible. One thing some users do is automatically inject the OPA container into pods that require it. There are different ways you can do this, e.g., inside a CD pipeline or as a mutating admission controller. This lets you control how the OPAs are deployed.

**Comment by glb** [comment]
re: injection: aha, thanks for the clarification. Interesting.

PR is on its way, doing a test build now.

**Comment by nitharsandvag** [comment]
Hello,

opa-rootless works, but how about kube-mgmt? 

Regards,
Nitharsan

**Comment by tsandall** [comment]
@nitharsandvag if you're interested in the same kind of image for kube-mgmt feel free to post a PR there. Note the original issue was not related to running OPA as an admission controller AFAIK.
