### ISSUE TITLE
Introduce automation to help GC GitHub issues

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1274]
As the project gets older, we're going to continue to accumulate open issues. While many of the issues in the current backlog are valuable, it would be nice to have period reminders to clean up stale and out-of-date issues.

One option would be to run [prow](https://github.com/kubernetes/test-infra/tree/master/prow) on the OPA repo to manage issue lifecycle.

I'd like to avoid relying in prow for other CI/CD functions at this point, but using it for issue labeling seems reasonable.

**Comment by anderseknert** [comment]
We now have automation in place to label stale issues and PRs, and I think we've agreed that's about as far as we want to go for now. Anything more to do here, or OK to close this issue @tsandall ?

**Comment by anderseknert** [comment]
Closing for now. Let’s create a new one if we want specific improvements later.
