### ISSUE TITLE
Rewrite == to = in queries passed to the compile API

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1280]
# Expected Behavior

The compile API should not return drastically different results given `==` or `=` expressions. We need to avoid generating support modules in as many places as possible.

# Actual Behavior

Currently the compile API may return different results depending on whether the caller supplies `=` or `==` expressions when referring to rules with default values. The reason is that `==` expressions in caller supplied queries are not rewritten to `=` expressions like they are everywhere else (i.e., in rule bodies.) The resulting query that gets partially evaluated is something like `p = x; x == true` instead of just `p = true`. Because of this, the evaluator has to generate support rules because the `default` value may be needed in the output.

In the case of the compile API, users are unlikely to need expression values (which is the whole reason for not rewriting `==` as `=`) so we could simply rewrite `==` to `=` like we do in rule bodies. This would help insulate callers in some cases from more complex partial evaluation results.

# Steps to Reproduce the Problem

Take a policy with a default rule:

```
package test

default p = false

p {
  input.x = 1
}
```

Invoke the compile API with two different queries:

```
POST v1/compile {"query": "data.test.p == true"}`
```

and

```
POST v1/compile {"query": "data.test.p = true"}
```

The first query will generate support modules while the second will not.

**Comment by pandyamarut** [comment]
@tsandall Can you point me to the source. 
Thanks.

**Comment by tsandall** [comment]
@patrick-east is looking into this.

**Comment by pandyamarut** [comment]
@tsandall No issues. Will look for another issue now.
Just for reference in future, It'll be great if we tag already assigned Issues with tags like 'assigned' or any similar. 
Thanks.
