### ISSUE TITLE
Add support for graceful shutdown of OPA server

### ISSUE THREAD

**Issue by urvil38** [open-policy-agent/opa#1291]
OPA should wait for active connection to gracefully handled and then shutdown.

```
signalChannel := make(chan os.Signal, 1)
signal.Notify(signalChannel, os.Interrupt,syscall.SIGTERM)

var wait time.Duration

<-signalChannel
log.Println("Recevied SIGINT signal")
log.Println("shutting down server")

ctx, cancel := context.WithTimeout(context.Background(), wait)
defer cancel()

err := server.Shutdown(ctx)
```

**Comment by tsandall** [comment]
We've had users request better support for graceful shutdown of the OPA server deployed in the Kubernetes admission control use case. What I think we would be good is to extend OPA with a command line flag that lets users set the graceful shutdown period, e.g., `opa run --server --graceful-shutdown-period=30s`. When a SIGTERM is received, OPA should wait for the shutdown period before exiting. @patrick-east can you take a look at this?

**Comment by patrick-east** [comment]
Can do. One clarification, we want to let active connections finish *and* stop accepting new ones? Or allow new ones in the grace period too?

**Comment by tsandall** [comment]
I think it's OK to accept new connections during the shutdown period for now. In k8s, the endpoint will get removed, so the OPA should stop receiving new requests. We can revisit in the future as needed.
