### ISSUE TITLE
Make it possible to link and highlight a line in the playground

### ISSUE THREAD

**Issue by F21** [open-policy-agent/opa#1295]
It would be nice if lines in the playground are link-able and highlight-able, similar to gist on github. This would make it possible to share a link to a specific line to the input, output or policy in a playground document.

**Comment by timothyhinrichs** [comment]
That would be great.  Thanks for the suggestion!

**Comment by tsandall** [comment]
The playground now supports links to line numbers. For example:

https://play.openpolicyagent.org/#L23
