### ISSUE TITLE
io.jwt.decode_and_verify does not support non-integer time claims

### ISSUE THREAD

**Issue by klarose** [open-policy-agent/opa#1296]
# Expected Behavior
[rfc7519](https://tools.ietf.org/html/rfc7519#page-10) states that a NumericDate can be a non-integer value (at least, that's my read of it).  The `exp`, `nbf` and`iat` fields are NumericDates. I expect `decode_verify` to support verifying fractional seconds since the epoch for those claims.

If the jwt library doing the validation only supports integer values, I suppose we can get by with taking the floor of the `exp`, and the ceiling of the `nbf` to ensure we're not loosening the claim.

# Actual Behavior
Calling `decode_and_verify` with an otherwise valid jwt containing a non-integer date fails with error: 
`eval_internal_error: io.jwt.decode_verify: parsing 'exp' JWT claim: strconv.ParseInt: parsing "1553722861.6784303": invalid syntax"`

# Steps to Reproduce the Problem

  1. Create a valid JWT with an `nbf` or `exp` claim containing a non-integer numeric value. 
  2. Invoke `io.jwt.decode_verify` with it
 
The following rego playground demonstrates the issue: https://play.openpolicyagent.org/p/4MnaqO4Wx3

This one shows it working with an integer value:
https://play.openpolicyagent.org/p/YjbCHlFh5u

# Additional Information

The python `jwt` library, as well as [jwt.io](https://jwt.io) seem to support non-integer dates.

**Comment by tsandall** [comment]
@klarose Thanks for filing this. The RFC does indeed state that NumericDate is a JSON numeric which may be integer or floating point. I'd expect the JWT decoding built-ins to cope with this. Labeling this as a bug and help-wanted.

I think the fix could be:

* Remove usage of strconv.ParseInt entirely
* Create new ast.Number from constraints.time (or lookup on operand)
* Use ast.Compare(nbf.Value, <ast version of constraints.time>) to check if one is less than the other

**Comment by repenno** [comment]
Having evaluate quite a few JWT implementation recently I can affirm that even through fractional values might be accepted, all provide leeway for clock skew when comparing values. Some allow a seconds, some minutes, so taking ceiling/floor and then comparing should be ok. Usually implementations are stricter while having some form of strict clock (NTP and all) implemented.

The RFCs themselves say implementers MAY allows entire minutes when comparing:

"Implementers MAY
   provide for some small leeway, usually no more than a few minutes, to
   account for clock skew."

**Comment by repenno** [comment]
Sure, I can take of it

**Comment by tsandall** [comment]
@repenno assigning this one to you to look into. Let me know if I should take it off your plate.
