### ISSUE TITLE
Support importing user defined functions

### ISSUE THREAD

**Issue by Arkessler** [open-policy-agent/opa#1316]
Not sure how feasible this is, but it would great to be able to import user defined functions. One use would be abstracting commonly used functions shared between multiple policies. If this is impossible to implement (or already possible to do?) I'd appreciate better understanding why/how.

# Expected Behavior

common_functions.rego:
```
package top.level

my_function(x) {
    x = "foo"
}
```
policy_A.rego: 
```
package top.level.rules.A

import my_function (Or common_functions.rego?)

my_result {
  my_function("value")
}
```

**Comment by tsandall** [comment]
@Arkessler you can do this today. All rules (which covers, functions, they're just rules that take arguments) can be packaged and imported. For example:

```
package top.level

identity(x) = x
```

```
package top.level.rules.A

import data.top.level.identity

p = x {
  x = identity(1)
}
```

**Comment by Arkessler** [comment]
Thanks for the example! I hadn't thought to try importing it using the full data.* path. Much appreciated :)

**Comment by MahikanthNag** [comment]
Hi, @tsandall  I tried the example you have provided and getting this error

`rego_type_error: undefined function data.top.level.identity`

I have spent a lot of time but couldn't understand where I am going wrong..
Does project structure effect the behavior in any way?

**Comment by sadams-evi** [comment]
Is there an update on the undefined function error mentioned above? I am also running into similar issue
