### ISSUE TITLE
Add String Manipulation builtins

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/opa#132]
It'd be really great if we had some additional string manipulation builtins and functions to convert between scalar types.  Use case is checking if 1 docker image name is a previous version of another docker image name, e.g. given the following two strings determine that one is a previous version of the other.

"ubuntu/ubuntu:16.04"
"ubuntu/ubuntu:14.04"

Logic for this would be ...
1) break each string into an array, such as ["ubuntu", "ubuntu", "16.04"]
2) convert last  element of each array into a number: ["ubuntu", "ubuntu", 16.04]
3) check if the first 2 elements of the array are the same for the 2 strings
4) check that element 3 of array 1 is greater than element 3 of array 2

Different ways to implement that of course, but here are some builtins that came to mind.

indexof(string, substring, output)
substring(string, startindex, length, output)
len(string, output)
lower(string, lower-case-output)
upper(string, upper-case-output)

to_num(string-or-bool, output)
to_string(num-or-bool, output)
to_bool(string-or-num, output)

**Comment by tsandall** [comment]
Closing this ticket as we now have indexof...upper as well as to_number and format_int (which covers common use case for to_string). to_bool is missing but I think that can be handled easily enough without a dedicated built-in. If that becomes a problem, we can open another ticket and add it.
