### ISSUE TITLE
hugo `production-build` is broken

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1352]
The https://www.openpolicyagent.org site hasn't been updating after PR's merge.. turns out it has been failing to build the `production-build` target https://app.netlify.com/sites/openpolicyagent/deploys?filter=master since https://github.com/open-policy-agent/opa/commit/41d201566562eb970f6a689dcc7f8039b400bf9d merged.

The error output looks like:

```
{15:36} ~/p/g/s/g/o/o/docs:master ✓ ❯ make production-build
rm -rf public
scripts/load-docs.sh
++ cat RELEASES
.
.
<snip>
.
.
+ echo 'Docs loading complete'
Docs loading complete
hugo \
		--contentDir generated \
		--ignoreCache \
		--minify
Building sites … WARN 2019/04/17 15:36:45 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
Total in 754 ms
Error: Error building site: "/Users/patrick/projects/go/src/github.com/open-policy-agent/opa/docs/generated/docs/v0.10.7/deployments.md:224:1": failed to render shortcode "code": failed to process shortcode: "/Users/patrick/projects/go/src/github.com/open-policy-agent/opa/docs/layouts/shortcodes/code.html:4:16": execute of template failed: template: shortcodes/code.html:4:16: executing "shortcodes/code.html" at <readFile $filepath>: error calling readFile: stat /Users/patrick/projects/go/src/github.com/open-policy-agent/opa/docs/generated/code/deployments-kubernetes/example-pod.json: no such file or directory
make: *** [production-build] Error 255
```

So there are maybe two issues here:
1) The immediate problem of that build error
2) We didn't notice it broke
    - We probably should have a check for this in the normal PR process, right?

**Comment by patrick-east** [comment]
It looks like the versioned copy of the content is importing some file contents: https://github.com/open-policy-agent/opa/commit/41d201566562eb970f6a689dcc7f8039b400bf9d#diff-7a8819308d3d4e2583795271ae51f7d7L224

But the PR removes it: https://github.com/open-policy-agent/opa/commit/41d201566562eb970f6a689dcc7f8039b400bf9d#diff-e59b76bbb9714f8a0e164771738acebc

This also makes it apparent that any documentation content/config/etc that is outside of the `content` directory is *not* versioned. And that older versions will see the newer code snippets.

**Comment by patrick-east** [comment]
/ping @lucperkins ^^  Any ideas? Can we keep snapshots of the code directory along with the content?

**Comment by lucperkins** [comment]
@patrick-east This is broken for me as well for precisely the reason you point out. This was an oversight on my part that came about because the new site setup wasn't initially intended to be versioned. When I added versioning I forgot that I had implemented things this way and given the immutable nature of past tags, I'm not quite sure how to deal with it

**Comment by patrick-east** [comment]
Ok, cool. I added in that file that was missing.. we should probably re-open that one you made to get the other ones added back.

@tsandall you cool with re-adding them temporarily while we can get a better fix in place?

**Comment by patrick-east** [comment]
I filed #1354 to separately track gating PR's on the production build

**Comment by tsandall** [comment]
@patrick-east @lucperkins yep, let's get the site working and get the build process to a place that we're all happy with.

**Comment by patrick-east** [comment]
Files are re-added.. we should see netlify go back to green. Keeping this open until then.

**Comment by patrick-east** [comment]
https://app.netlify.com/sites/openpolicyagent/deploys shows a green deployment from master.
