### ISSUE TITLE
"production" doc build isn't being validated by PR checks

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1354]
# Expected Behavior
When we open PR's there is a netlify check that happens, but it isn't the same build step that happens for the production (post-merge) build.

This means we can easily regress something and not notice unless there is monitoring on netlify or someone checks the site manually after a PR merges.

# Actual Behavior
We should, at a minimum, ensure the hugo build works if any of the doc files were touched. Ideally we can have a preview that actually looks like the real site too.

**Comment by Sai-Adarsh** [comment]
Hello @patrick-east , You expect netlify CI/CD and deploy preview to be implemented in [opa/opa](https://github.com/open-policy-agent/opa) repo?

**Comment by patrick-east** [comment]
Potentially. The immediate problem is that we don't exercise the hugo build (`make production-build`) step as part of the normal checks done to validate a PR. Whether it is netlify that does it or travis matters less.

**Comment by patrick-east** [comment]
This is mostly solved by #1375 as netlify will be doing basically the same build for preview and production (minor differences in flags for base-url kind of stuff).

**Comment by patrick-east** [comment]
Going to close this for now. We are pretty much as close as we can get with the current netlify preview. The gap between the old preview/local build and the production build is now basically just down the the base url we build the site with.
