### ISSUE TITLE
new document themes is hard scroll on mobile devices

### ISSUE THREAD

**Issue by coolyrat** [open-policy-agent/opa#1363]
# Expected Behavior
scrolling the page is smooth

# Actual Behavior
barely move up and down after scrolling

# Steps to Reproduce the Problem

  1. open safari on iphone
  2. visit https://www.openpolicyagent.org/docs/v0.10.7/how-do-i-write-policies/
  3. start scrolling the page up and down

# Additional Info
IOS Version: 12.2

**Comment by tsandall** [comment]
@lucperkins can you take a look into this one?

**Comment by tsandall** [comment]
Fixed by #1364
