### ISSUE TITLE
abac like perms

### ISSUE THREAD

**Issue by vtolstov** [open-policy-agent/opa#1365]
I have actions like list,create ,delete, update.
each resource belongs to user. In some situations i want to grant access to specific resource to different users,but owner must persists.
How can i do that in rego if i can have many such resources of different types?

**Comment by vtolstov** [comment]
Mainly question about list, now i use sql and for list i get all records for specific owner.
In case of additional granted resources i need to get array for it ids to check..
Does it possible to get this data back from opa?
Ps before opa I'm using casbin

**Comment by timothyhinrichs** [comment]
This looks like you could use help with policy-authoring.  I've responded to one of your questions on slack.  Let's continue this discussion there.
