### ISSUE TITLE
Improve error reporting in OPA server 

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#1367]
# Expected Behavior
OPA server should differentiate between errors generated by OPA proper and errors reported by the decision logger.

# Actual Behavior
OPA server logs errors returned by the decision logger using one of OPA's error codes eg. `internal_error` .

# Steps to Reproduce the Problem

  1. Start OPA and a decision log plugin
  2. Return an error from the decision logger
  3. OPA logs the error as one of OPA's error codes

**Comment by tsandall** [comment]
We can prefix the error message to indicate it came from a decision log.
