### ISSUE TITLE
Built-in for Set membership  check in OPA

### ISSUE THREAD

**Issue by infominer75** [open-policy-agent/opa#1384]
# Expected Behavior
For a **Set** type, it is required to have a primitive that will allow checking for existence of an element in the set.
One way to do this now would be to play with intersection:
s1 := {x} //the element to check for existence
s2 := {x, y} //the actual set of elements
s3 := s1 & s2
count(s3) > 0
But the above method is not natural and is definitely prone to errors. Checking for existence in a set is as  fundamental an operation as the union and intersection of sets and hence deserves a built-in.

# Actual Behavior
As per the documentation for built-in set types, Sets do not have an existence check operation
https://www.openpolicyagent.org/docs/v0.10.7/language-reference/#built-in-functions.

# Steps to Reproduce the Problem

  1. Install latest version of OPA
  2. Attempt to check the existence of an element within a set

# Additional Info
None.

**Comment by infominer75** [comment]
This is my very first day with Rego. I realized that we can check for set membership existence by directly using the indexing operator like sett[x] where sett is a set of elements.
For non-existent elements, the return value would be undefined. Can the documentation for Set elements at the above link please be updated with this detail? This issue can then be closed.

Thank you and sorry for the noise.

**Comment by tsandall** [comment]
Hopefully this is addressed by making the language cheatsheet more prominent and reformatting the content a bit. See #1389
