### ISSUE TITLE
cast_xyz functions in language reference are confusing

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1405]
Users frequently think they should use the cast_xyz functions to convert from one type to another however the cast functions have somewhat inconsistent behaviour:

| func | accepts |returns |
| --- | --- | --- |
| cast_null | any | null or error if input is not null |
| cast_boolean | any | boolean or error if input is not boolean |
| cast_string | any | string or error if input is not string |
| cast_set | any | set or error if input is not **set or array** |
| cast_array | any | array or error if input is not **set or array** |
| cast_object | any | object or error if input is not object |

`cast_number` is not defined.

I don't think these functions are worth the confusion they introduce. We should remove them from the docs and deprecate them.

**Comment by GBrawl** [comment]
Hey @tsandall, I'm currently using the cast_set function to cast an array to a set so I can perform functions like intersection. Can you tell me what the alternative is now that cast_set is deprecated?

**Comment by tsandall** [comment]
@GBrawl you can you write a simple comprehension that converts the array into a set:

```rego
a_set := {x | x := arr[_]}
```

**Comment by GBrawl** [comment]
That works well, thanks!
