### ISSUE TITLE
Go runtime version for plugin

### ISSUE THREAD

**Issue by jfyne** [open-policy-agent/opa#1409]
Hello! I am trying to build a plugin for OPA

# Expected Behavior
I am trying to build a plugin for OPA 0.10.7 and I expect it to load it correctly.

# Actual Behavior
However I get this error message
```
Error: plugin.Open("ambassador_auth"): plugin was built with a different version of package errors
```
To me this suggests that I am using the wrong Go runtime. I have tried the go runtimes from the go docker files tagged `1.11` `1.11.4` and `1.11-stretch`, I have even tried `1.10`.

Is there a particular version I should be using?

**Comment by ashutosh-narkar** [comment]
```bash
$ go version
go version go1.11 darwin/amd64
```
I imported the `errors` package in my plugin implementation and built it. I was able to run the plugin with OPA. 

Is this the setup that is giving you the error ?

**Comment by jfyne** [comment]
I am building the plugin within a Docker container, the go version reported there is
```
go version go1.11.9 linux/amd64
```
I also just tried it explicitly with `1.11.0` and that didn't work either... I am running out of ideas!

**Comment by ashutosh-narkar** [comment]
@jfyne To use plugins, you should build OPA from source and use the generated OPA binary to run the plugin.

**Comment by jfyne** [comment]
Ah ok I see, doing that has got me past the error message and onto another one I can probably figure out myself! Thanks
