### ISSUE TITLE
Add time zone support for date/time functions

### ISSUE THREAD

**Issue by teq0** [open-policy-agent/opa#1422]
All the built-in time functions currently work on UTC. This probably OK for many compute tasks, but for some policies local time is relevant ("Deployments aren't allowed on Fridays after 3:00 PM").

It probably only requires an additional optional parameter for, or alternate function, to `time.now_ns()`, maybe `time.now_ns_tz()` to generate an ns value for the given tz. Not sure how far to go to support DST etc, or whether to just take a numeric +/- hours parameter and make DST the caller's problem.

**Comment by tsandall** [comment]
@teq0 adding built-in functions to support timezones sounds good to me. We should able to wrap the Golang time package fairly easily to add this.

**Comment by teq0** [comment]
It's not quite as simple as I thought, as the other time functions like date, clock and weekday all explicitly call `utcTime()`, so not sure where the best place to set the TZ is. I thought maybe cache the TZ name, and replace `utcTime()` with `tzTime()` which checks the cache to see if a TZ is set (via `time.now_tz_ns(tzName)`), otherwise default to UTC, but that wouldn't allow having more than one timezone at a time in a rule though. You actually want to associate the TZ with the ns value that's returned from `time.now_tz_ns(tzName)`.

Also, time.LoadLocation() reads from disk every time, it doesn't cache internally. So it would be good to cache the time.Location once it's read. Is there a long lasting cache for static-like data?

**Comment by tsandall** [comment]
@teq0 what if we extended the time.clock/date/weekday functions to accept either a number (representing unix timestamp) or a tuple (representing unix timestamp and desired location)?

```
time.weekday(time.now_ns())
time.weekday([time.now_ns(), ""])  # same "UTC" or above
time.weekday([time.now_ns(), "Local"])
time.weekday([time.now_ns(), "America/Los_Angeles"])
```

**Comment by teq0** [comment]
Ah, tuple. I couldn't see how to implement optional parameters but of course that's it. Backwards compatible as well. OK, I'll give that a go.
