### ISSUE TITLE
Makefile uses -it args when calling docker commands

### ISSUE THREAD

**Issue by jchauncey** [open-policy-agent/opa#1431]
# Expected Behavior
That I can call make commands without a tty so that builds can be run in a CI environment.

# Actual Behavior
Docker spits back an error saying that commands cannot run without a tty.

By just removing the `-it` from most of the docker commands fixes this issue. Not sure why one would need to add those in a makefile.

**Comment by tsandall** [comment]
@jchauncey thanks for filing this and sorry for the delayed response (kubecon EU stole a lot of cycles.)

The offending line has moved out of the Makefile to [here](https://github.com/open-policy-agent/opa/blob/master/build/run-wasm-tests.sh#L7).

Without `-t` that script will not be interruptible which is sub-optimal. If someone has a suggestion for how to make sigint/sigterm propagate and work correctly, we can get rid of the `-t` flag.

**Comment by urvil38** [comment]
`--tty` has nothing to do with how signals are handled. it is just allocate a pseudo-tty to docker process. with `-it` option, when Ctrl+C is pressed from keyboard, it forwards SIGINT signal from your terminal to docker daemon.

```
docker run -it --rm -e VERBOSE=$VERBOSE -v $PWD:/src -w /src node:8-alpine sh -c 'mkdir -p /test; tar xzf _test/testcases.tar.gz -C /test; cd /test; node test.js opa.wasm'
```

Following is a process list of our container process:
```
PID   USER     TIME  COMMAND
    1 root      0:12 node test.js opa.wasm
   11 root      0:00 ps
```

Docker daemon send this signal to the container process running as `PID 1`. In our case node process is running as `PID 1`. It's process responsibility to catch that signal.

 ```
docker run -it --rm -e VERBOSE=$VERBOSE -v $PWD:/src -w /src node:8-alpine sh -c 'mkdir -p /test; tar xzf _test/testcases.tar.gz -C /test; cd /test; node test.js opa.wasm'
```
Even though  in this command we provided `-it` option, it doesn't make process to be interruptible. 

```
Found 145 WASM test cases in 13 file(s). Took 74.0034ms. Running now.

^C^C^C^C

Nothing happened!!!!
```
In this case, node process doesn't handling the signal it received from docker daemon. so we unable to gracefully shut down the process.

The purpose of `-it` option is to send signal when `Ctrl+C` is pressed. It has nothing to do with signal handling. Without `-it` we can still send a signal to running container using following command:
```
docker kill -s INT <container_id>
``` 
### **Required Changes**
- add signal handler to the node.js process to catch `SIGINT,SIGTERM` signal.

**Comment by urvil38** [comment]
Suggested Changes:

There are multiple approaches we could took to solve this issue:

1. we can add signal handler to node.js process for handling `SIGTERM,SIGINT` signals. It requires source code changes.

2. We can use different init process for `PID 1`. There is an option `--init` in docker run command for launching `tini` as an init process a.k.a `PID 1`. with this configuration our process tree is look like this:
```
docker run --init --rm -e VERBOSE=$VERBOSE -v $PWD:/src -w /src node:8-alpine sh -c 'mkdir -p /test; tar xzf _test/testcases.tar.gz -C /test; cd /test; node test.js opa.wasm'

PID   USER     TIME  COMMAND
    1 root      0:00 /dev/init -- node test.js opa.wasm
    6 root      0:11 node test.js opa.wasm
``` 
When we send signal to docker daemon it forward it to `PID 1`. In this case it is `tini`. When tini receives SIGTERM signal it terminal itself as well as all of it's child process. 

```
docker kill -s TERM <container_id>
```

Benefits of `tini` as an init process are describes in this issue [#8](https://github.com/krallin/tini/issues/8).

**This is widely used approach in docker ecosystem. This approach not required any source code modification.**
