### ISSUE TITLE
Validation code doesn't work if mutation is applied

### ISSUE THREAD

**Issue by danil-fomichev** [open-policy-agent/opa#1442]
Currently if validation and mutation are applied to the same request kind and operation validation doesn't work.

Here is an example.   In this case patch is applied successfully but validation part just skipped.

    package system
    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }

    default response = {"allowed": true}
    response = x {

        x := {
            "allowed": false,
            "status": {"reason": reason},
        }

        reason = concat(", ", admission.deny)
        reason != ""
    }
    response = x {
        count(patch) > 0

        fullPatches := cast_array(patch)

        x := {
            "allowed": true,
            "patchType": "JSONPatch",
            "patch": base64url.encode(json.marshal(fullPatches)),
        }
    }

    patch[patchCode] {
        input.request.kind.kind = "Pod"
        input.request.operation = "CREATE"
        patchCode = {
            "op": "add",
            "path": "/metadata/annotations/foo",
            "value": "test",
        }
    }

    deny[msg] {
        input.request.kind.kind = "Pod"
        input.request.operation = "CREATE"
        endswith(input.request.object.spec.containers[_].image, ":latest")
        msg = "pod contains image using latest tag"
    }

**Comment by tsandall** [comment]
@danil-fomichev sorry for the delay. KubeCon EU ate up a lot of cycles :sweat_smile: 

What I'd recommend you do is run two OPAs with the validating & mutating webhook configurations pointed at each one. You can load the same set of policies into both OPAs. The trick is to have two different [default decisions](https://www.openpolicyagent.org/docs/latest/configuration/#miscellaenous) configured. This way one OPA can evaluate the mutating policies and the other OPA can evaluate the validating policies. Assuming you have the validating webhook configured to run after the mutating webhook (which is recommended best practice in Kubernetes) your validating policies will see the mutated resource.

For example, given the policy above, the following minimal changes would give you what you need:

```
package system

validate = {
  "apiVersion": "admission.k8s.io/v1beta1",
  "kind": "AdmissionReview",
  "response": validate_response,
}

default validate_response = {"allowed": true}

validate_response = x {

    x := {
        "allowed": false,
        "status": {"reason": reason},
    }

    reason = concat(", ", admission.deny)
    reason != ""
}


mutate = {
  "apiVersion": "admission.k8s.io/v1beta1",
  "kind": "AdmissionReview",
  "response": mutate_response,
}

default mutate_response = {"allowed": true}

mutate_response = x {
    count(patch) > 0

    fullPatches := cast_array(patch)

    x := {
        "allowed": true,
        "patchType": "JSONPatch",
        "patch": base64url.encode(json.marshal(fullPatches)),
    }
}

patch[patchCode] {
    input.request.kind.kind = "Pod"
    input.request.operation = "CREATE"
    patchCode = {
        "op": "add",
        "path": "/metadata/annotations/foo",
        "value": "test",
    }
}

deny[msg] {
    input.request.kind.kind = "Pod"
    input.request.operation = "CREATE"
    endswith(input.request.object.spec.containers[_].image, ":latest")
    msg = "pod contains image using latest tag"
}
```

Then you'd configure one OPA with `--set "default_decision=/system/validate"` and the other OPA with `--set "default_decision=/system/mutate"` (see link above for details on OPA configuration).

I'm going to close this for now as I don't think there's anything else to do. We can reopen if there are follow-up issues.
