### ISSUE TITLE
OPA TLS based client authentication with kube-mgmt

### ISSUE THREAD

**Issue by sandeepsharmadevops** [open-policy-agent/opa#1458]
# Expected Behavior
OPA authentication supports bearer token and TLS based.
- referencing document is available when OPA is configured with token-based authN and kube-mgmt, but what if OPA is configured with TLS base authN, in that case how kube-mgmt gets authenticated by OPA, does mgmt support any other cmd line flag to be passed
  - if yes please suggest with an example if possible
  - if not guide me about the solution considering we want to opt for TLS based authN within OPA, how mgmt authentication can be handled by OPA

# Actual Behavior

# Steps to Reproduce the Problem

  1.
  2.
  3.

# Additional Info

**Comment by tsandall** [comment]
kube-mgmt doesn't support client certificates today but if you want to file an issue against kube-mgmt or submit a PR to kube-mgmt please feel free! Closing this issue since it ultimately belongs in kube-mgmt.

**Comment by sandeepsharmadevops** [comment]
Thanks @tsandall raised at respective location https://github.com/open-policy-agent/kube-mgmt/issues/40
