### ISSUE TITLE
Docs: where does p come from? (References)

### ISSUE THREAD

**Issue by nicktimko** [open-policy-agent/opa#1477]
In the docs, it states:

> References are always prefixed with a variable that identifies the root document. In the example above this is `p`.

> -- https://www.openpolicyagent.org/docs/latest/how-do-i-write-policies/#references
> -- https://github.com/open-policy-agent/opa/blob/master/docs/content/how-do-i-write-policies.md#references

I don't see a `p` prefix to the "example(s) above", one of `sites[0].servers[1].hostname` or `sites[0]["servers"][1]["hostname"]`, or on the example data separately: https://www.openpolicyagent.org/docs/latest/how-do-i-write-policies/#example-data

Am I blind? I'm super confused what it's talking about...

**Comment by patrick-east** [comment]
Nope, not blind. Looks like an old bug in the docs. It should say something like:

> "In the example above this is `sites`."
