### ISSUE TITLE
opa eval loads JSON as input very slowly

### ISSUE THREAD

**Issue by mxey** [open-policy-agent/opa#1488]
`opa eval` takes a long time to load JSON as input, but loads it fast as data

# Expected Behavior

```
$ time opa eval --input ./input.json 'count(input)' > /dev/null
real    0m0,092s
user    0m0,086s
sys     0m0,021s
```

# Actual Behavior

```
$ time opa eval --input ./input.json 'count(input)' > /dev/null
real    0m39,916s
user    0m50,088s
sys     0m0,483s

$ time opa eval --data ./input.json 'count(data)' > /dev/null
real    0m0,092s
user    0m0,086s
sys     0m0,021s
```

# Steps to Reproduce the Problem

  1. Create big JSON file (like `kubectl get --all-namespaces …`)
  2. Run `time opa eval --input ./input.json 'count(input)' > /dev/null`

# Additional Info

OPA version 0.11.0 on macOS

**Comment by srenatus** [comment]
🤔 could this be related to the roundtripping? I.e. https://github.com/open-policy-agent/opa/commit/5b077118917c472c1f43d4fdb3c01607c9de6955 and what became of this? Assuming the code path of `--data` doesn't do the roundtrip, and `--input` does, that could explain the difference. ⚠️ just a wild guess.

**Comment by tsandall** [comment]
I believe this is due to the input file being parsed using the generated Rego/AST parser. If we switch the cmd implementation to just call `util.Unmarshal` and then `ast.InterfaceToValue` it should resolve the problem (and as a bonus it'll accept YAML as well as JSON).
