### ISSUE TITLE
Lazy load data files with opa eval

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1502]
Related to #1087 it would be nice if `opa eval ...` and `opa test ...` would only load data files (`*.json`, `*.yaml`, etc) as needed.

As-is if someone has a repo with kubernetes yamls, config json files, etc it makes it harder to manage using opa, especially for testing and authoring of policies with things like the vscode plugin.

I'm opening this issue to track the feature request and will update with a proposal after some investigation. Stay tuned for updates.

**Comment by patrick-east** [comment]
Putting this on the back-burner in favor of #1584

**Comment by tsandall** [comment]
Closing this because we have no plans of implementing lazy loading in the foreseeable future.
