### ISSUE TITLE
Docs: Add 'Search Box' to the documents.

### ISSUE THREAD

**Issue by kenfdev** [open-policy-agent/opa#1504]
This is a proposal to add "Search" to the official docs. I have a slight memory that the search feature existed in the past (apologies if my memory is wrong)

I often find my self not being able to find the right topic when looking at the docs.(e.g. "Was it in 'How Do I Write Policies?' or 'Language Reference', or 'REST API', etc.)

How about adding something like Algolia's [DocSearch](https://community.algolia.com/docsearch/) to improve the docs experience? You can see an example in places like the [Vue.js official docs](https://vuejs.org/).

I'm open to alternatives, but wanted to start a discussion.

Thank you!

**Comment by tsandall** [comment]
cc @patrick-east and @lucperkins might have thoughts here.

**Comment by patrick-east** [comment]
+1 !

I haven't used DocSearch before but it looks promising. I was just recently looking at some options for this with https://lunrjs.com/ since we can generate the index at build time of the static site. I don't really have a ton of preference for which tool we use as long as it is stable and easy for us to maintain.

**Comment by lucperkins** [comment]
@tsandall @patrick-east I've been looking for an excuse to dig into this domain. I'll have a look at the docs and such and make an assessment re: what kinds of resources it would take.

**Comment by kenfdev** [comment]
Side notes on Algolia.

They support Open Source Projects so it should be free if OPA gets qualified.
https://www.algolia.com/for-open-source/

Here are other live usages links for:

* [Bootstrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/)
* [React](https://reactjs.org/docs/getting-started.html)
* [Moment.js](https://momentjs.com/docs/)

Any way, being able to search would be a really nice experience for noobs like me!

Thank you for caring  :)

**Comment by tsandall** [comment]
This was shipped in v0.14.
