### ISSUE TITLE
Add 'data' to help screen

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/opa#151]
It'd be great if we included 'data' as a command in the help screen in the repl so that people can see all their data.  Couple of use cases.

1. show all data currently available. data
2. show top-level keys in the data currently available (for when there's too much data). data[x] = _
3. drill into data. data.foo.bar

Would be nice if all of those were available from help (maybe with subhelp commands like 'help data').

**Comment by tsandall** [comment]
Tempted to add an "Examples" section to the 'help' message. For example:

```
(master)torin:~/go/src/github.com/styrainc/fetchdb/test/usecases/container_vulns$ opa run *.json
OPA 0.2.1-dev (commit f56ae0d, built at 2016-11-14T22:38:16Z)

Run 'help' to see examples and list of commands.

> help

Examples
========

> data           # show all data and evaluate all rules
> data[x] = _    # show top-level keys
> data.foo.bar   # show specific value

Commands
========

        <stmt> : evaluate the statement
package <term> : change currently active package
 import <term> : add import to currently active module
   unset <var> : undefine rules in currently active module
          json : set output format to JSON
        pretty : set output format to pretty
   dump [path] : dump the raw storage content
         trace : toggle full trace
         truth : toggle truth explanation
          help : print this message
          exit : exit back to shell (or ctrl+c, ctrl+d)
        ctrl+l : clear the screen
```

**Comment by timothyhinrichs** [comment]
I like that, though people might want examples for things besides lookup.  And then the examples section might large.  But perhaps that's a bridge we'll cross when we get to it.
