### ISSUE TITLE
Policies not working properly when it has long url with path parameter

### ISSUE THREAD

**Issue by VigneshSonaiya** [open-policy-agent/opa#1531]
I'm writing the policy document in rego for my below schema. But something wrong with this. It only work for first time. second time when I try to change the path parameter. It simply says not authorized.

![api schema](https://user-images.githubusercontent.com/47246527/60323679-692ec280-99a0-11e9-9013-595bc6e04ffa.PNG)

This is my policy
package persons

import input as http_api

token = {"payload": payload} { io.jwt.decode(http_api.token, [_, payload, _]) }
activity = {"codes":codes} {codes := split(token.payload["activities"], ",")}

default allow = true

allow {
    http_api.httpMethod = "GET"
    http_api.resource = "/persons"
}

allow {
    http_api.httpMethod = "POST"
    http_api.resource = "/persons/add"
}

allow {
    http_api.httpMethod = "POST"
    http_api.resource = "/persons/match"
}

allow {
    http_api.httpMethod = "GET"
    http_api.path = ["persons", "organisation", "search", _]
    token.payload["custom:OrganisationErn"] = http_api.pathParameters["organisation_ern"]
}

allow {
    http_api.httpMethod = "PUT"
    http_api.resource = "/persons/register"
}

allow {
    http_api.httpMethod = "POST"
    http_api.resource = "/persons/update"
}

allow {
    http_api.httpMethod = "GET"
    http_api.resource = "persons/{person_ern}"
    token.payload["custom:PersonErn"] = http_api.pathParameters["person_ern"]
}

allow {
    http_api.httpMethod = "GET"
    http_api.resource = "persons/{person_ern}/links"
    token.payload["custom:PersonErn"] = http_api.pathParameters["person_ern"]
}

allow {
    http_api.httpMethod = "GET"
    http_api.resource = "persons/{person_ern}/preferences"
    token.payload["custom:PersonErn"] = http_api.pathParameters["person_ern"]
}

**Comment by tsandall** [comment]
@VigneshSonaiya can you share example input(s) that reproduce the problem?

**Comment by tsandall** [comment]
Closing this for now. Feel free to re-open if/when inputs can be shared.
