### ISSUE TITLE
Decision log path for query against v1/data not correct

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1532]
# Expected Behavior

If clients are executing queries against the root of the data namespace then the decision log path should be empty. Note, this change will be backwards incompatible however it's unlikely that anyone is relying on this behavior today since clients typically query for specific decision paths OR they use the main decision (both of which are logged correctly.)

# Actual Behavior

Currently the decision log path is set to `data` because of how the path prefix is stripped.

# Steps to Reproduce the Problem

  1. Run opa with decision logging enabled: `opa run -s --set decision_logs.console=true`
  2. Execute a query against v1/data: `curl localhost:8181/v1/data`
  3. Observe path in decision log event

**Comment by patrick-east** [comment]
This gets fixed as part of https://github.com/open-policy-agent/opa/pull/1958
