### ISSUE TITLE
Question about Kubernetes example

### ISSUE THREAD

**Issue by devdattakulkarni** [open-policy-agent/opa#1540]
I have a question about Kubernetes Ingress example here:
https://www.openpolicyagent.org/docs/v0.10.7/kubernetes-admission-control/

The function valid_ingress_hosts looks for "ingress-whitelist" annotation in the input.request.namespace. However, in ingress-ok.yaml and ingress-bad.yaml namespace is not provided. Shouldn't ingress-ok.yaml have metadata.namespace field as 'production' and ingress-bad.yaml have metadata.namespace field as 'qa' for correct policy enforcement?

**Comment by tsandall** [comment]
@devdattakulkarni the two commands immediately following the manifests specify the ingress. Hope this clears it up for you.

**Comment by devdattakulkarni** [comment]
Ah! I did not realize that. You are talking about these:
kubectl create -f ingress-ok.yaml -n production
kubectl create -f ingress-bad.yaml -n qa

Thanks!
