### ISSUE TITLE
Testing local policies with YAML configs

### ISSUE THREAD

**Issue by brendanjryan** [open-policy-agent/opa#1546]
Greetings! I am using `rego` and the `opa` toolchain to perform some basic "linting" and structure validation over kubernetes config files, and I have been absolutely loving it so far!

One slight annoyance I ran into during my testing is that `rego` seems to not support multi-line strings as variables, which makes constructing `yaml` test data very hard. As a workaround, I had to convert all of my `yaml` structs to their `json` object form so that they could be represented in rego. Is there any desire to support multi-line strings in the rego language - or is this a feature I missed in the docs?

# Expected Behavior

I am able to test my policies against yaml configs using a syntax similar to the following:

```rego
test_hpa_denied {
    in := "
        kind: 'HorizontalPodAutoscaler
    '"

    deny with input as yaml.unmarshal(in)
}
```

# Actual Behavior

Tests like the following fail to compile: 
```rego
test_hpa_denied {

    in := "
        kind: 'HorizontalPodAutoscaler
    '"

    deny with input as yaml.unmarshal(in)
}
```
```console
1 error occurred during loading: policy_test.rego:5: rego_parse_error: found non-terminated string literal
            in := "
```

# Steps to Reproduce the Problem

  1. Create an example like the one above
  2. Run `opa test .`

Thanks in advance!

**Comment by tsandall** [comment]
hey @brendanjryan sorry for the slow response. With the holidays in the US, most folks were off.

You can use backtick to delimit [raw strings](https://www.openpolicyagent.org/docs/latest/how-do-i-write-policies/#strings) in Rego. For example:

```
example = `
        kind: HrizontalPodAutoscaler
`

unmarshaled = yaml.unmarshal(example)
```

**Comment by brendanjryan** [comment]
@tsandall No sorries for the late reply! Thank you! 🙇
