### ISSUE TITLE
Policies via Bundles not working when Package name is other than "helm_kubernetes_quickstart"

### ISSUE THREAD

**Issue by VF-mbrauer** [open-policy-agent/opa#1547]
# Expected Behavior
After OPA has been downloaded the Bundle, it should accept and process anyPackage name it gets from the *.rego files inside.

# Actual Behavior
When using a different package name ("mypackagename") than the default one ("helm_kubernetes_quickstart") the policy will not be picked up anymore.
So it sticks basically all the time to the default one.

# Steps to Reproduce the Problem
```
  1. Create a Policy .rego File with a Package name other than the default one which is "helm_kubernetes_quickstart" 
  2. Make a TAR and ZIP it so that it is a "Bundle.tar.gz" and upload it to the destination where OPA is able to fetch this bundle from.
  3. Wait some time that it gets applied to OPA.
  4. Try to start working against the Policy to see if it will deny a request.
  5. With this config now, OPA should always accept the actions.
  6. Now Change the Package name inside the .rego file back to the default one: "helm_kubernetes_quickstart".
  7. Redo steps 2 to 4
  8. Now you should see that OPA does deny a request.
```
# Additional Info

**Comment by patrick-east** [comment]
Can you share the config.yaml that OPA is using?

At a guess it might still using the `default_decision: "/helm_kubernetes_quickstart/main"` defined in the values.yaml https://github.com/helm/charts/blob/master/stable/opa/values.yaml#L14

**Comment by VF-mbrauer** [comment]
Attached you will find the values file I use for helm installation:
[values.yaml.gz](https://github.com/open-policy-agent/opa/files/3371977/values.yaml.gz)

So I have not used `default_decision`. So if I don't define, is it still using the one in the Standard Chart values? I tried to put `{}` or `""` for this, but it didn't work either.

**Comment by patrick-east** [comment]
If I understand correctly they would be in the config file `- --config-file=/config/config.yaml` which is defined in this secret https://github.com/helm/charts/blob/master/stable/opa/templates/secrets.yaml#L10 and mounted in the opa container here https://github.com/helm/charts/blob/master/stable/opa/templates/deployment.yaml#L138-L142

Can you verify what the config is? It would also be good to share OPA logs if you can to verify it was able to download and load the bundle as expected.

**Comment by VF-mbrauer** [comment]
This is the output after the Helm Chart Deployment
```
bundle:
  name: vf-bundle.tar.gz
  polling:
    max_delay_seconds: 120
    min_delay_seconds: 60
  prefix: bundles
  service: controller
default_decision: /helm_kubernetes_quickstart/main
services:
  controller:
    url: http://<myURL>
```
So were right, it has been written inside the config `(default_decision: /helm_kubernetes_quickstart/main)` which will be loaded via the `- --config-file=/config/config.yaml` statement. So the question is, how can I influence this when having several Packages which I need anyway to define inside the `.manifest`.

**Comment by patrick-east** [comment]
The webhook is calling OPA's default query (`POST /` https://www.openpolicyagent.org/docs/latest/rest-api/#query-api) which is configured by that `default_decision` config option. You'll want to set it to match the one you defined in your new bundle.

**Comment by VF-mbrauer** [comment]
But for me it is still not clear why do I need to define the OPA `default_decision` and point this to a specify Package. Imaging I have 10 different Packages and all defined via the `.manifest` 
.
Because it needs anyway to iterate through all the packages I have defined to check if the REGO matches or if it doesn't. And the default decision will be part of one of the REGOs.
```
main = {
	"apiVersion": "admission.k8s.io/v1beta1",
	"kind": "AdmissionReview",
	"response": response,
}

default response = {"allowed": true}

response = {
	"allowed": false,
	"status": {"reason": reason},
} {
	reason := concat(", ", deny)
	reason != ""
}
```
[whitelist_play.zip](https://github.com/open-policy-agent/opa/files/3378234/whitelist_play.zip)

So let's guess I need to define this `default_decision`, what is the content/code I need to put in to keep it simple and at minimum level. I hope you're getting my point.
Thanks

**Comment by patrick-east** [comment]
The `default_decision` is what will be evaluated for the response to a request to the root unversioned opa rest api (which is what the k8s api server will POST the admission request to).

With that in mind let me show a quick example, if we take the policy you've attached:

```bash
{10:23} /t/example ❯ cat policy.rego
package my_own_package

whitelist = [
	"*.dev.acmecorp.com",
	"*.test.acmecorp.com",
]

deny[msg] {
	input.request.kind.kind == "Ingress"
	input.request.operation == "CREATE"
	input.request.namespace == "opa-example"
	host := input.request.object.spec.rules[_].host
	not glob_match_one_of(whitelist, host)
	msg := sprintf("ingress host %q is invalid", [host])
}

glob_match_one_of(patterns, str) {
	glob.match(patterns[_], ["."], str)
}

main = {
	"apiVersion": "admission.k8s.io/v1beta1",
	"kind": "AdmissionReview",
	"response": response,
}

default response = {"allowed": true}

response = {
	"allowed": false,
	"status": {"reason": reason},
} {
	reason := concat(", ", deny)
	reason != ""
}
```
and run a local opa server with it loaded:
```bash
{10:27} /t/example ❯ opa run --server ./policy.rego
```
then query it for the default decision
```bash
{10:27} /t/example ❯ curl -X POST  localhost:8181/
{
  "code": "undefined_document",
  "message": "document missing or undefined: data.system.main"
}
```
It is trying to use the default value of `system.main`, which doesn't exist. What we _do_ have is `my_own_package.main` which is defined in the rego file(s) as part of what would be in your bundle.

```bash
{10:29} /t/example ❯ opa run --server --set default_decision=my_own_package.main ./policy.rego
```
And now when we query the root path we get:
```bash
{10:29} /t/example ❯ curl -X POST  localhost:8181/
{"apiVersion":"admission.k8s.io/v1beta1","kind":"AdmissionReview","response":{"allowed":true}}%
```
We now get back the expected admission review object. This is similar to if we had done something like:

```bash
{10:31} /t/example ❯ curl -X POST  localhost:8181/v1/data/my_own_package/main
{"result":{"apiVersion":"admission.k8s.io/v1beta1","kind":"AdmissionReview","response":{"allowed":true}}}%
```
That "simple query" of just `/` is controlled by the `default_decision` config option, https://www.openpolicyagent.org/docs/latest/rest-api/#execute-a-simple-query shows some more examples.

All that being said, if you wanted to use the default value for `default_decision` you could define a rego file with package `system` and define the `main` value in there. Then you can leave `default_decision` empty and it should work as expected.

The trick then for integrating all the other modules is in how that `main` object is defined. I think a pretty tried-and-true way is to do something like what we show in the tutorial 
https://github.com/open-policy-agent/opa/blob/master/docs/content/code/kubernetes-admission-control-validation/admission-controller.yaml#L110-L130 (as seen in https://www.openpolicyagent.org/docs/latest/kubernetes-admission-control/#3-deploy-opa-on-top-of-kubernetes ) where it will `import data.kubernetes.admission` and then aggregate all the deny reasons from there. You would need to do something similar for any other packages where you define deny/allow reasons.

> Imaging I have 10 different Packages and all defined via the .manifest

For each of those you would need to `import` from them and aggregate the decisions with similar logic to what that example is doing.

Hopefully that helps give some more clarity on this. Feel free to ping me on slack too for a lower latency discussion 😄

**Comment by tsandall** [comment]
Closing this for now because it seems the original questions have been answered.

**Comment by danieliziourov-form3** [comment]
in regards to `default_decision` and directly querying policies.

You can use `/v0/data/<package>/<name>/<...>` path to query similar to `/`.

https://github.com/open-policy-agent/opa/blob/e88ad165ba25dfb7839adfd02213e23ebbbae3bf/server/server.go#L830-L832

In my opinion that should be documented or part of a normal query API. This way we can handle both mutator and validation webhooks with a single OPA deployment.

**Comment by anderseknert** [comment]
@danieliziourov-form3 the difference between the `v1` API and the `v0` on is that the former wraps the input document in an `input` attribute. This is recommended for the cases where you control the client code, such as application authorization. For other cases - like kubernetes API server webhooks - the `v0` API may be used to preserve the input document as it is. 

You can definitely use a single OPA deployment for both validation and mutation - just point them to different endpoints / documents, like `/v0/data/kubernetes/validation` and `/v0/data/kubernetes/mutation`.

**Comment by danieliziourov-form3** [comment]
@anderseknert it's a very weird use of API versioning. If you want to support both use cases they should be in the same version. `v0` implies that it'll be eventually deprecated or shouldn't be used since there is a newer version.
