### ISSUE TITLE
Remove/downgrade ad-hoc request logging from Istio/Envoy plugin in v0.13.0

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1554]
Once v0.13.0 is released we should remove (or downgrade to to DEBUG) the request logging in the plugin. For most cases, the console decision logger will be enabled. The request logging is quite expensive and should be avoided (currently a full request payload is logged at INFO level.)

**Comment by tsandall** [comment]
@ashutosh-narkar this is low-hanging fruit that will complement the prepared query changes quite well. Once we have this fixed we should benchmark so we know where we stand.

**Comment by ashutosh-narkar** [comment]
Fixed https://github.com/open-policy-agent/opa-istio-plugin/pull/133
