### ISSUE TITLE
Add installation options documentation to the website

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1559]
Even though OPA is quite simple to obtain and run locally people might not know that there's a package for their favourite installer. We should create an "Installation" page that lists the different ways you can obtain and install OPA:

* Docker
* Github releases
* Source
* Brew
* Habitat

We can also link to deployment methods like Helm, Kubernetes, etc.

**Comment by nitinpatil1985** [comment]
Do I have to compile UCX with intel compilers if I have to run openmpi on OPA?

**Comment by tsandall** [comment]
@nitinpatil1985 we currently publish binaries for Linux/Darwin/Windows 64-bit platforms. You'll need to build from source for any other platforms. I'm not sure what UCX is.

**Comment by remya-savithry** [comment]
Is there any documentation on how we can install OPA from source code?

**Comment by tsandall** [comment]
@remya-savithry you can `go get` opa and it will work fine however you won't have the version information when you run `opa version`. The makefile has an `install` target that produces the binary in your GOPATH. The `build` target produces the binary inside your working copy.

**Comment by barbia** [comment]
@tsandall looks like github releases and docker are covered here: https://www.openpolicyagent.org/docs/latest/#running-opa are you still looking to get the other options listed? If so has the list changed since first writing?

**Comment by tsandall** [comment]
@barbia, thanks for commenting. That comment was made before we rewrote the introduction and made the download links more discoverable. I am going to close this issue now.
