### ISSUE TITLE
Add conditional rule execution (if-then-else in rego)

### ISSUE THREAD

**Issue by FabioDominio** [open-policy-agent/opa#1564]
Good evening, 

I noticed that rego does not seem to fully support the "if-then-else" flow, e.g., when someone needs to evaluate a rule just for certain input.

While the "else" statement is not necessary for rules returning a boolean value, it is not the same for rules returning an array (e.g. "servers" in one of the examples) since, if present, the rule is always evaluated.

I was able at max to return an empty array by discarding each entry when a given input appears, but I couldn't find a working solution to avoid returning an array at all.

If anyone can show me an alternative working solution, it has my uttermost gratitude. 

I am not expert enough in rego.

Thanks.

**Comment by tsandall** [comment]
@FabioDominio if you have a specific example you'd like to express in Rego it would be easier to answer your question directly. Nonetheless if you want to say:

```
return X if conditions A && B && C
else return Y if conditions C && D
else return Z
```

You can do so using the `else` keyword:

```
p = 1 {
   A
   B
   C
} else = 2 {
   C
   D
} else = 3 {
   true
}
```

If your conditions are obviously mutually exclusive (e.g., return X if A, return Y if not A) then you can just write:

```
p = 1 {
   A
}

p = 2 {
   not A
}
```

You want to be careful though because `p` can have AT MOST ONE value. E.g., it can `1` or `2` but NOT `1` and `2`. The latter would result in a conflict error.

**Comment by FabioDominio** [comment]
Thanks a lot for the prompt reply!

I will try tomorrow and report the exact Rego example in case.

Probably I misinterpreted the "rule precedence" example by replacing the numbers with the desired outcome.

More specifically, I would need that "2" in the second code fragment were an array like "servers[s] {...}, that is (ideally, not the right code):

`p = all{
                  A
} else = server[s] {
s:=...
B
}
`

Namely, I need that for certain input "p" is a flag stating if all the servers are selected, or a list of server names (filter) for another kind of input.

Thanks again!

**Comment by tsandall** [comment]
I recommend avoiding trying to distinguish between an empty array and undefined if you can. If you really need to then this would do the trick:

```
# server_aux will be a non-empty array if defined (otherwise it's undefined)
server_aux = s {
   s := server
   count(s) > 0
}

server[s] {
   # some rule that generates s
}
```

Of course you could add other conditions to `server_aux`.

Closing this issue for now because there doesn't seem to be anything else to do.

**Comment by FabioDominio** [comment]
Thanks for the help!
