### ISSUE TITLE
Use prepared queries in the OPA server

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1567]
There is support for preparing and re-using Rego queries so save time with recompiling everything except for the input https://godoc.org/github.com/open-policy-agent/opa/rego#example-Rego-PrepareForEval

 The OPA server has support for partially evaluating and then re-using those partial evaluations https://www.openpolicyagent.org/docs/latest/rest-api/#query-parameters-4 , this would work similarly to help speed up repeat queries with different inputs.

We would need to be careful not to take up too much memory with the prepared queries being cached.

**Comment by tsandall** [comment]
Let's figure out how much memory the prepared queries take and then decide on the caching strategy. Enabling this for the default decision is a no brainer. For /v1/data we could enable it for some number of paths. Defaulting to a large value (e.g., 1,000 distinct paths) might be fine if the memory usage is low (which it should be).
