### ISSUE TITLE
Regex builtin bug

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#157]
Didn't expect the following results.  Bug?

> re_match("d*", "cat")
true

> re_match("ec2*", "ec3")
true

**Comment by johnbelamaric** [comment]
First one matches because anything matches the empty string (0 "d"s = //). Second one matches because /ec/ matches "ec3". * is 0 or more.

**Comment by tsandall** [comment]
Closing this as it's not a bug. @timothyhinrichs feel free to create another ticket for a simpler pattern matching built-in, e.g., one that uses shell file name patterns a la `filepath.Match` or Python's `fnmatch`.
