### ISSUE TITLE
Is there a client-go for OPA api?

### ISSUE THREAD

**Issue by tamalsaha** [open-policy-agent/opa#1576]
I understand that OPA can be used as a library from GO code. But I am looking to access an out-of-process OPA server from my Go code. Is there any client-go library for that?

I see that the types are defined here: https://github.com/open-policy-agent/opa/blob/master/server/types/types.go

I looked at the Framework repo but I could not understand what that is doing. It seems to be about CRDs.

I appreciate any pointers or example repos.

**Comment by ashutosh-narkar** [comment]
Just to understand this a bit more, you are going to start OPA as a server and then your GO server application will access OPA using its APIs. Is that correct @tamalsaha ?

**Comment by tamalsaha** [comment]
Yes, @ashutosh-narkar .

**Comment by ashutosh-narkar** [comment]
[HTTP API AUTHZ](https://www.openpolicyagent.org/docs/latest/http-api-authorization/) example on the OPA website, uses a Python web server to access OPA via its APIs. 

Here is another example https://github.com/open-policy-agent/example-api-authz-python

**Comment by tamalsaha** [comment]
Yeah. I was wondering if there was a `client-go` wrapper for the OPA api instead of directly calling it in place like https://github.com/open-policy-agent/example-api-authz-python/blob/master/server.py#L82 .

**Comment by ashutosh-narkar** [comment]
Afaik there isn't. You would need to write one and can contribute it back as well ! Curious as to why you chose not to embed OPA as a library ?

**Comment by tamalsaha** [comment]
Thanks for clarifying!
