### ISSUE TITLE
--plugin-dir not present 

### ISSUE THREAD

**Issue by cvanderschuere** [open-policy-agent/opa#1577]
# Expected Behavior
Use `opa --plugin-dir=. run` to load plugins in the current directory

# Actual Behavior
```
$ opa --plugin-dir=. run
Error: unknown flag: --plugin-dir
```
# Additional Info
```
$ opa version
Version: 0.12.1
Build Commit: 2799e148
Build Timestamp: 2019-07-06T15:26:21Z
Build Hostname: e48c9991aedb
```

**Comment by ashutosh-narkar** [comment]
@cvanderschuere The published OPA binaries do not support the `plugin` feature, hence the `plugin-dir` flag is unavailable. To use plugins, you will need to build the OPA binary from source and use that use to load your plugins. You need to make sure that you build your plugin with the same version of OPA that will load it. 

We will be updating the [Plugins](https://www.openpolicyagent.org/docs/latest/plugins/) doc to make this more explicit in the next few days.  In the meantime, you can see an example of how to build plugins [here](https://github.com/open-policy-agent/opa-istio-plugin/blob/master/docs/plugin.md).

**Comment by cvanderschuere** [comment]
Confirmed this works if you build from source

**Comment by cvanderschuere** [comment]
A note to add to this for future folks: make sure you are consistent with your use of GO111MODULE=on. 

If you are not, you will get errors like:
```
error: config error: plugin "some_plugin" not registered
```
even though you can confirm the plugin is actually registered. This is due to the plugin being registered in one package (local vendor) and opa is running with another.
