### ISSUE TITLE
opa test diff result 

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#1581]
`opa test` has the `--show-failure-line` flag that shows the line number of the test failure. It would be helpful for debugging if the `opa test` command printed a diff between the actual and expected values that resulted in the test failure.

**Comment by tsandall** [comment]
One option would be to identify failed expressions from test rules in the trace and then plug them to show the actual vs. expected values. This would help quite a bit in terms of debugging failed tests.

**Comment by tsandall** [comment]
Closing this in favor of #2456.
