### ISSUE TITLE
How do I merge two objects in rego?

### ISSUE THREAD

**Issue by sikka** [open-policy-agent/opa#1588]
l1 := {"k1":"v1", "k2": "v2"}
l2 := {"k2":"v4", "k3": "v3"}

How can I merge the two into a third object l3 that looks like below?

l3 := {"k1":"v1", "k2": "v4", "k3": "v3"}

I am trying to use an admission controller to modify labels of a kubernetes pod, but I want to retain the old labels. Only override them when theres a value specified in the patch.

I am currently using this - 

`patches := [patch|patch ={"op":"add","path":"/metadata/labels","value": { "asset": asset, "disk-type": "ssd" }}]`

But this modifies the labels to new ones and discards the old labels.

**Comment by tsandall** [comment]
You can merge two objects like this:

```
# return combination of objects a and b. b's values override a's values.
merge(a, b) = c {
  keys := {k | some k; a[k]} | {k | some k; b[k]}
  c := {k: v | some k; keys[k]; v := pick(k, b, a)}
}

# return k from first obj that contains it.
pick(k, obj1, _) = obj1[k]
pick(k, obj1, obj2) = obj2[k] { not obj1[k] }
```

**Comment by sikka** [comment]
@tsandall  - I should have mentioned I am using version 0.9.2. Getting the follwing error when I try to define the merge function - 
```
> merge(a, b) = c {
|   keys := {k | some k; a[k]} | {k | some k; b[k]}
|   c := {k: v | some k; keys[k]; v := pick(k, b, a)}
| }
|
1 error occurred: 2:21: rego_parse_error: no match found
	  keys := {k | some k; a[k]} | {k | some k; b[k]}
	                    ^
```

Getting errors when defining the first pick function as well-
```
> pick(k, obj1, _) = obj1[k]
3 errors occurred:
1:1: rego_unsafe_var_error: var k is unsafe
1:1: rego_unsafe_var_error: var obj1 is unsafe
1:1: rego_unsafe_var_error: var _ is unsafe
```

**Comment by tsandall** [comment]
@sikka no problem. Here's an version that works in v0.9.2:

```
exists(obj, k) {
	_ = obj[k]
}

pick(k, obj1, obj2) = v {
	v := obj1[k]
}

pick(k, obj1, obj2) = v {
	not exists(obj1, k)
	v := obj2[k]
}

merge(a, b) = c {
	keys := {k | _ = a[k]} | {k | _ = b[k]}
	c := {k: v | k := keys[_]; v := pick(k, b, a)}
}
```

**Comment by sikka** [comment]
Thank you!

**Comment by JAForbes** [comment]
Just because this page has search rank, should note https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-object-objectunion is a built in now
