### ISSUE TITLE
Decision log plugin doesn't support reconfiguration of upload chunk size

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1593]
The decision log plugin has a config parameter that controls the upload chunk size limit. This is the size of the decision log event before it is encoded and uploaded. The default limit is 32KB (which was chosen because of a limitation on the consumers). The limit can be changed at startup, but the reconfigure function on the plugin doesn't flush and re-create the encoder when the configuration changes.

We should update the plugin to flush the encoder and buffer any pending chunks when the upload limit changes. We should also make sure that the plugin can be configured to disable the limit entirely.

**Comment by tsandall** [comment]
@ashutosh-narkar can we close this since it appears to be working?

**Comment by ashutosh-narkar** [comment]
I did not close this as we haven't yet worked on a way to disable the upload limit.

**Comment by tsandall** [comment]
I see, I was referring to your comments on the linked issue which I took to mean this issue could be closed.

> #1593 indicates that the upload size is not reconfigurable which does not seem to the case as the encoder is re-created as seen here.

> This change adds a test to check the upload limit is updated when the plugin is reconfigured.

What are we missing then? Do we need to change the plugin implementation or just add another test?

**Comment by ashutosh-narkar** [comment]
Part of the issue which refers to the upload size not being reconfigurable is addressed by [this](https://github.com/open-policy-agent/opa/pull/3364) PR.


> We should also make sure that the plugin can be configured to disable the limit entirely.

Currently we use a default 32KB for the upload limit. The ⬆️ seemed to indicate that we should not have a default ? If that's the case, we would need to update the plugin to support that.

**Comment by tsandall** [comment]
I'm going to close this issue. It's unclear whether we want to support deployments where the limit is completely removed. E.g., it would be problematic if someone generated an extremely large decision w/ logging enabled.
