### ISSUE TITLE
Update discovery config to match newer `bundles` format

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1597]
We should have a consistent method for defining where to download things from. With the new changes added in #1566 we switched to a map of `name` -> `service` + `resource` where the URL we download from is `service.url`+`resource` without playing any games with prefixes or using the name in the actual url.

As of now the discovery config doesn't support this type of configuration. We should fix that.

**Comment by tsandall** [comment]
I think we only require a "resource" key to be added to the discovery configuration. We could make the resource and name/prefix keys mutually exclusive. Seems like relatively low-hanging fruit that we could address sooner than later. Thoughts?

**Comment by patrick-east** [comment]
@tsandall Yep, I think that is pretty much it. Should be a small change (/me knocks on wood)
