### ISSUE TITLE
Logo License

### ISSUE THREAD

**Issue by wurstbrot** [open-policy-agent/opa#1613]
Hi,

I would like to use the OPA logo in combination with other Logos (e.g. OWASP wasp).
I give pins to security champions as a reward.

I could not find a opa logo policy and right now, I assume that the logo is published under Apache 2 and I can use it in the way I have used in the given pin (https://github.com/wurstbrot/security-pins/blob/master/PNG/no-background/open_policy_agent4.png).

Do you agree that I use the opa logo in this way?

Thank you,
cheers,
Timo

**Comment by tsandall** [comment]
@wurstbrot that's cool. No problem here.
