### ISSUE TITLE
opa-istio-plugin should implement grpc reflection for ease of testing

### ISSUE THREAD

**Issue by danielpops** [open-policy-agent/opa#1615]
# Expected Behavior
A diff of 

```
 internal/internal.go 
 @@ -31,6 +31,7 @@ import (
	"github.com/pkg/errors"
	"github.com/sirupsen/logrus"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

const defaultAddr = ":9191"
@@ -85,6 +86,7 @@ func New(m *plugins.Manager, cfg *Config) plugins.Plugin {
	}

	ext_authz.RegisterAuthorizationServer(plugin.server, plugin)
	reflection.Register(plugin.server)

	return plugin
}
```
Should be sufficient to enable reflection such that tools like `grpc_cli` or `grpcurl` can interact without any knowledge of the proto definitions.

# Actual Behavior
Reflection is enabled, however, something is not working correctly, in that the service endpoint is listed via `grpc_cli ls` but it cannot be interacted with:

```
root@92a418f38c36:/grpc/bins/opt# ./grpc_cli ls localhost:9292
envoy.service.auth.v2.Authorization
grpc.reflection.v1alpha.ServerReflection

root@92a418f38c36:/grpc/bins/opt# ./grpc_cli ls localhost:9292 envoy.service.auth.v2.Authorization/Check
Service envoy.service.auth.v2.Authorization not found.
```

# Steps to Reproduce the Problem

grpc_cli =>
  1. Apply the diff in step1 and run an instance of opa with the opa-istio-plugin enabled
  2. use `grpc_cli` to list the service interfaces
  3. use `grpc_cli` to list the details of a method

grpcurl =>
  1. Apply the diff in step1 and run an instance of opa with the opa-istio-plugin enabled
  2. use `grpcurl` to interact with the server, omitting any proto information (which should work if reflection is implemented correctly)
```
~/grpcurl -plaintext  -d '{
   "attributes": {
     "request": {
       "http": {
         "headers": {
           "Authorization": "Bearer foo"
         },
         "path": "/service/v1/get_the_thing"
       }
     }
   }
 }
 ' localhost:9292 envoy.service.auth.v2.Authorization/Check
Error invoking method "envoy.service.auth.v2.Authorization/Check": target server does not expose service "envoy.service.auth.v2.Authorization"
```
  3. use `grpcurl` with the proto information and observe that the Service and methods do actually exist (this does not leverage the reflection API)
```
~/grpcurl -plaintext -import-path ./proto/ -proto ./proto/envoy/service/auth/v2/external_auth.proto -d '{
   "attributes": {
     "request": {
       "http": {
         "headers": {
           "Authorization": "Bearer foo"
         },
         "path": "/service/v1/get_the_thing"
       }
     }
   }
 }
 ' localhost:9292 envoy.service.auth.v2.Authorization/Check
{
  "status": {

  },
  "okResponse": {

  }
}
```

**Comment by tsandall** [comment]
This would be nice to have? Is there any impact on performance with reflection enabled? We could make it optional as I would guess this is mostly for development/debug purposes?

**Comment by danielpops** [comment]
I don't think there would be any impact on performance, since this ends up being a separate endpoint that test clients such as `grpcurl` would hit to introspect on the proto schemas when hitting the actual desired target endpoint. 

Either way, gating this functionality behind a config or command line flag sounds like the right way to go.

**Comment by tsandall** [comment]
@ashutosh-narkar this looks like it's really easy to add. Could you do that?

**Comment by ashutosh-narkar** [comment]
Sure will do.
