### ISSUE TITLE
Error: unknown flag: --plugin-dir

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#1616]
# Expected Behavior

Being able to run opa with the `--plugin-dir` flag.

# Actual Behavior

Does not work and is not shown in the "Flags" list.

```
opa --plugin-dir=/path/to/plugins run
Error: unknown flag: --plugin-dir
Usage:
  opa run [flags] [flags] [files]

Flags:
  -a, --addr strings                         set listening address of the server (e.g., [ip]:<port> for TCP, unix://<path> for UNIX domain socket) (default [:8181])
      --authentication {token,tls,off}       set authentication scheme (default off)
      --authorization {basic,off}            set authorization scheme (default off)
  -c, --config-file string                   set path of configuration file
  -f, --format string                        set shell output format, i.e, pretty, json (default "pretty")
  -h, --help                                 help for run
  -H, --history string                       set path of history file (default "/Users/anderseknert/.opa_history")
      --ignore strings                       set file and directory names to ignore during loading (e.g., '.*' excludes hidden files)
      --log-format {text,json,json-pretty}   set log format (default json)
  -l, --log-level {debug,info,error}         set log level (default info)
  -m, --max-errors int                       set the number of errors to allow before compilation fails early (default 10)
      --pprof                                enables pprof endpoints
  -s, --server                               start the runtime in server mode
      --set stringArray                      override config values on the command line (use commas to specify multiple values)
      --set-file stringArray                 override config values with files on the command line (use commas to specify multiple values)
      --shutdown-grace-period int            set the time (in seconds) that the server will wait to gracefully shut down (default 10)
      --tls-ca-cert-file string              set path of TLS CA cert file
      --tls-cert-file string                 set path of TLS certificate file
      --tls-private-key-file string          set path of TLS private key file
  -w, --watch                                watch command line files for changes
```

# Steps to Reproduce the Problem

  1.  `curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.13.0/opa_darwin_amd64`
  2. `chmod +x opa`
  3.  `opa --plugin-dir=/path/to/plugins run`

# Additional Info

**Comment by patrick-east** [comment]
The feature is not enabled on the pre-built binaries according to https://github.com/open-policy-agent/opa/issues/1577#issuecomment-513856780 If you build OPA from source you'll be able to load plugins for it.

**Comment by anderseknert** [comment]
That's definitely missing from the documentation. Do you know what the motivation behind that decision is? I think it's an unfortunate one. Seems to me that people who compile OPA from source could just add whatever they need anyway, and are the least likely to need plugins. But at least I have a workaround now. Thanks @patrick-east

**Comment by tsandall** [comment]
Closing in favor of #1509. The dynamic plugin support is quite fragile due to limitations in Go shared library support. We're planning to provide a good way for people who want to get started building from source.

**Comment by anderseknert** [comment]
Thanks @tsandall. Until then a line mentioning this requirement in the [docs](https://www.openpolicyagent.org/docs/latest/plugins/) would likely save others a lot of time. 

Thanks for all the good work you've done on OPA btw. We've been trying it out for a week or two at work and we're really enjoying it so far.
