### ISSUE TITLE
`true` should not equal `undefined` in a comparison

### ISSUE THREAD

**Issue by mikol** [open-policy-agent/opa#1622]
# Expected Behavior
`true == undefined` should return `false`; `true != undefined` should return `true`

# Actual Behavior
Both `true == undefined` and `true != undefined` return `undefined`

# Steps to Reproduce the Problem

```
. opa run
OPA 0.13.0 (commit b06cfaf1, built at 2019-08-06T17:38:54Z)

Run 'help' to see a list of commands.

> a { true }
Rule 'a' defined in package repl. Type 'show' to see rules.
> a
true
> b { false }
Rule 'b' defined in package repl. Type 'show' to see rules.
> b
undefined
> a == b
undefined
> a != b
undefined
> 
```

# Additional Info

This issue applies to all values when compared against `undefined`, not just `true`. It even happens with `undefined == undefined`.

For context, I am attempting to merge two objects – for example, `{"o": 1}` and `{"p": false}` to produce `{"o": 1, "p": false}`.  To do this, I am using the following:

```
void {
  false
}

# Combines `source` and `target` into a new object; if a key is present in both
# `source` and `target`, the key in `source` will overwrite the key in `target`.
merge(target, source) = out {
  keys = {key | target[key]} | {key | source[key]}

  out := {
    key: value |
    keys[key]
    value := get(key, source, target)
    value != void
  }
}

# Returns value for `key` from `object` if `key` is present in `object`;
# otherwise, returns value for `key` from `defaults`.
get(key, object, defaults) = out {
  # Take value from object.
  out := object[key]
  out != void
} else = out {
  # Take value from `defaults` if it isn’t present in `object`.
  out := defaults[key]
}
```

As far as I can tell, comparing against `undefined` is my only option if I want `false` values to be included in the `merge` `out` object comprehension. As a workaround, I will try to use an object partial rule instead of an object comprehension.

**Comment by mikol** [comment]
Workaround:

```
# Combines `source` and `target` into a new object; if a key is present in both
# `source` and `target`, the key in `source` will overwrite the key in `target`.
merge(target, source) = out {
  target_keys := keys with data.context.object as target
  source_keys := keys with data.context.object as source

  out := partial
    with data.context.keys as target_keys | source_keys
    with data.context.source as source
    with data.context.target as target
}

keys[key] {
  data.context.object[key] == false
}

keys[key] {
  data.context.object[key]
}

partial[key] = false {
  ctx := data.context
  key := ctx.keys[_]
  get(key, ctx.source, ctx.target) == false
}

partial[key] = value {
  ctx := data.context
  key := ctx.keys[_]
  value := get(key, ctx.source, ctx.target)
}

# Returns value for `key` from `object` if `key` is present in `object`;
# otherwise, returns value for `key` from `defaults`.
get(key, object, defaults) = out {
  # Handle `false` explicitly because `not undefined == not false`.
  object[key] == false
  out := object[key]
} else = out {
  # Take value from `defaults` if it isn’t present in `object`.
  not object[key]
  out := defaults[key]
} else = out {
  # Take value from object.
  out := object[key]
}
```

**Comment by mikol** [comment]
Better workaround, use identity comparisons:

```
package library.v1.utils.object.v1

# Returns value for `key` from `object` if `key` is present in `object`;
# otherwise, returns value for `key` from `defaults` object.
get(key, object, defaults) = x {
  # Take value from object.
  x := object[key]
} else = x {
  # Take value from `defaults` if it isn’t present in `object`.
  x := defaults[key]
}

# Returns the set of keys in `object`.
keys(object) = x {
  x := {k | object[k] == object[k]}
}

# Mixes objects `a` and `b` into a new object; if a both `a` and `b` define the
# same key, the key defined by `b` will overwrite the key defined by `a`.
merge(a, b) = x {
  u := keys(a) | keys(b)
  x := {k: v | v := get(u[k], b, a)}
}
```

**Comment by tsandall** [comment]
[Here's another option that we recently added to the cheatsheet.](https://www.openpolicyagent.org/docs/latest/language-cheatsheet/#merge-objects)

Today, all operations on undefined values produce undefined results. You can "catch" undefined results using negation. Changing the language semantics as described would be backwards incompatible and would require that we model undefined in the query results (which we don't--undefined is simply an empty result set today.) Moreover, it's not clear that having special behaviour for `==` and `!=` is always desirable. For example, it's unclear what the result set should contain when you say `a != b; a = x; b = y`.

Closing for now as there's no clear path forward for this issue.

**Comment by mikol** [comment]
> You can "catch" undefined results using negation.

Ick. `not` isn’t a good option since `not false_value` and `not undefined_value` produce the same result. As things stand, I don’t see a way to distinguish between `false` and `undefined`.

> For example, it's unclear what the result set should contain when you say a != b; a = x; b = y.

I’m too unskilled in the art to understand what you’re pointing out here. I read this to mean: “Assign the value of `x` to `a` and the value of `y` to `b`. If `a` doesn’t equal `b` (AKA, `x` doesn’t equal `y`), then produce a result (e.g., the default rule value `true`).“ I guess what you’re trying to illustrate is that if, say, `y` is `undefined`, then there will be multiple conflicting effects – namely `y` will cause this query to be missed/failed, producing an `undefined` result. Which I suppose is a fair point – albeit an unsatisfying one.
