### ISSUE TITLE
Clean up tests for opa-istio-plugin

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#1627]
The unit tests for the `internal` package in `opa-istio-plugin` contain some duplicated code. Clean up the tests by adopting a table-driven approach.

**Comment by tsandall** [comment]
Taking a closer look at the tests, it seems they could benefit from having the fixtures factored out but beyond that there's not much to do (the fixtures are modified in slightly different ways in each test case.) Closing this for now.
