### ISSUE TITLE
Add prepocessed path query to input (opa-istio-plugin)

### ISSUE THREAD

**Issue by vetyy** [open-policy-agent/opa#1636]
# Expected Behavior

It would be nice to have `parsed_query` in the input.
E.g. when sending request like: `/v1/path?item_id=1&lang=en` I will be able to do:

    input.parsed_path = ["v1", "path"]
    input.parsed_query["item_id"] == "1"
    input.parsed_query["lang"] == "en"

I am not sure if using new map for the query is the best solution or you think it might make more sense to add this information somewhere else.

# Actual Behavior
In current behavior I would get:

    input.parsed_path = ["v1", "path?item_id=&lang=en"]

# Additional Info
I would be willing to do the PR if needed.

**Comment by ashutosh-narkar** [comment]
@vetyy This should be helpful. Representing the query string as a map sounds fine to me.

The policy would look something like:
```bash
input.parsed_query.item_id = 1
input.parsed_query.lang = "en"
```

It would be great if you can contribute this feature.

**Comment by ashutosh-narkar** [comment]
PR: https://github.com/open-policy-agent/opa-istio-plugin/pull/129
