### ISSUE TITLE
misleading error message when supplying wrong argument type to `-` operator

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#1643]
## Expected/Actual Behavior

When evaluating

```
{ 1, 2, 3 } - 3
```
you get this error message:
```
{ 1, 2, 3 } - 3: eval_type_error: minus: operand 2 must be one of {number, set} but got number
```
and vice versa for `3 - { 1, 2, 3 }`.

I'm not saying that it shouldn't **error** -- it should, this is wrong usage of the `-` operator -- it's just that the error reads funny. 😃 

## Additional Info

👉 [playground](https://play.openpolicyagent.org/p/VYZaAR8f5C)

**Comment by tsandall** [comment]
Fixing this in one place would be relatively easy.

I'm wondering if we'd be better off replacing the built-in function operand errors with the `ast` package-style type errors. E.g., in this case...

```
eval_type_error: invalid argument(s)
   have: (set[number], number)
   want (one of): (set[any], set[any])
                  (number, number)
```
