### ISSUE TITLE
Document different policy combination strategies

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1647]
It's quite common for people ask how conflict resolution works in OPA. We have a section in the FAQ that touches on it however it would be nice to show different combination patterns. To start we could cover those found in XACML: http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html#_Toc325047268

**Comment by davidjbrossard** [comment]
Also check out this blog post on combining algorithms in XACML. The spec itself is a little dry :-)

https://www.axiomatics.com/blog/understanding-xacml-combining-algorithms/

**Comment by tsandall** [comment]
Closing this issue for now. We've found the FAQ on statement order and conflicts to be sufficient.
