### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [open-policy-agent/opa#1652]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [prometheus/prometheus](https://github.com/prometheus/prometheus), [coredns/coredns](https://github.com/coredns/coredns), [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by tsandall** [comment]
hi @yevgenypats. This would be nice! A couple questions:

* Where is the corpus stored?
* How long does the PR check take?

For context, here's the repo that contains a corpus and script from the last time we fuzzed OPA: https://github.com/tsandall/fuzz-opa

We have a couple changes in-progress to our Travis CI makefile targets (#1642). Once those are done I think it would make sense to look into this.

**Comment by yevgenypats** [comment]
hi @tsandall! 

- The corpus is stored on fuzzit servers, you can download it via fuzzit CLI or via the dashboard
- the PR check itself usually takes a few seconds + your current build time

I didn't know that you already have fuzz targets. This will save some time:)

Regarding Travis CI changes, sure, let's wait. I subscribed to that thread.

**Comment by tsandall** [comment]
Ah, just to be clear, that fuzzer is outside of the OPA repo. Sounds good. We'll follow-up as soon as the refactoring is done.

**Comment by yevgenypats** [comment]
cool. btw why it outside the OPA repo itself? I don't have a particular problem with just interesting in the use-case behind it.

**Comment by tsandall** [comment]
I didn't want to integrate it into the repo at the time because corpus contained several thousand files and the build times were quite long. Having it in-repo and run on every PR is ideal as long as the latency isn't too high.

**Comment by yevgenypats** [comment]
gotcha. So I think it might be possible to integrate it in the repo as the corpus will be stored on Fuzzit and will be updated on a daily basis as the fuzzers generate new test-cases

**Comment by yevgenypats** [comment]
@tsandall  @patrick-east  Looks like we have another interesting case for the AST.

looks like this `[{{[{{{{[{{` input causes the ast parser to consume a lot of memory. I'm not sure what would be the right solution but I think it worth discussing. it's not in the blacklist array. I mean I can added it to the blacklist array but not sure this is the right solution.

**Comment by tsandall** [comment]
I believe this is the same/known issue. Expanding the blacklist to catch repeated opening array/set/object literals is probably the best short term solution.
