### ISSUE TITLE
Integrate new values explanation mode into VS Code extension

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1698]
Once the tracer is implemented we can integrate it into VS Code. It is TBD how to the binding values ought to be surfaced. One option would be via a hover/popup dialog in the editor.

The extension should keep track of the last query that ran so that it can be re-run as necessary with the new explanation mode enabled.

**Comment by kmcquade** [comment]
This would be amazing

**Comment by tsandall** [comment]
Closing this as it's no longer relevant.
