### ISSUE TITLE
Failed loading bundle on windows

### ISSUE THREAD

**Issue by brumer** [open-policy-agent/opa#1713]
# Expected Behavior
bundle should pass validation

# Actual Behavior
error occurred during loading: manifest roots do not permit data at path ...

# Steps to Reproduce the Problem

  1. Use OPA as a library within a project on a windows machine
  2. Call loader.All for a bundle containing a manifest file with valid roots and data files

# Additional Info
When OPA reads the bundle and the insertValue function is called for data files the filepath.Dir function is called.
This causes the foreslash in the path to be replaced with os.PathSeparator which on windows is backslash.
The changed paths causes validateAndInjectDefaults to return an error.
filepath.ToSlash can be called to replace os.PathSeparator to "/"

**Comment by patrick-east** [comment]
Hi @brumer can you share more details about the bundle, opa version, environment, etc.

I tried to reproduce this on my system and didn't run into it on the latest master branch of opa:

Bundle (created on non-windows machine <-- maybe a difference in our envs?)
```
$ tar -xvzf ~/Downloads/b1.tar.gz
./
./a/
./b/
./.manifest
./b/data.json
./b/policy.rego
./a/data.json
./a/policy.rego
```

With a `.manifest` defining some roots:
```
$ cat ./.manifest
{
  "revision" : "1",
  "roots": ["a", "b"]
}
```
And a mix of data and policy under those roots.

I made a simple test case using the `loader.All` method, `main.go`:
```go
package main

import (
	"fmt"

	"github.com/open-policy-agent/opa/loader"
)

func main() {
	r, err := loader.All([]string{"c:/users/patrick/downloads/b1.tar.gz"})
	fmt.Println(err)
	fmt.Println(r.Documents)
}
```
And running it I'm getting no error and it is reading in the directories as expected:
```
PS C:\Users\patrick\go\src\test> go run .
<nil>
map[c:map[a:map[x:0 y:1] b:map[x:2 y:3] system:map[bundle:map[manifest:map[revision:1 roots:[a b]]]]]]
```

**Comment by patrick-east** [comment]
Even though I can't repro the issue I still created https://github.com/open-policy-agent/opa/pull/1732 

@brumer if you can try out the change that would be great, if not more info so I can repro and make sure it fixes it 😄

**Comment by patrick-east** [comment]
Going to re-open until we get more info from @brumer

**Comment by brumer** [comment]
to reproduce the issue, use a bundle with this structure:
> tar -xvzf ./bundle.tar.gz
> .manifest
> a/
> a/b/
> a/b/c/
> a/b/c/data.json
> a/b/policy.rego

with a .manifest file:
> {
>   "revision" : "1",
>   "roots": ["a/b"]
> }

you should receive the error:

> 1 error occurred during loading: manifest roots do not permit data at path a\b\c

I believe the issue is at 
`dirpath := strings.TrimLeft(filepath.Dir(path), "/.")`
https://github.com/open-policy-agent/opa/blob/master/bundle/bundle.go#L390

**Comment by patrick-east** [comment]
Apologies for the delay. Was able to repro the issue following the example given. Will have another PR up soon with a fix.
