### ISSUE TITLE
Tag logging with types

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1716]
When collecting logs with tools like fluentd, it can be useful to have types of tags on the logs. For example, if I want to collect only decision logs and send them to somewhere, today I had to do something like that:
```
<filter kubernetes.var.log.containers.**opa**.log>
  @type record_transformer
  enable_ruby true
  <record>
    type ${if record.has_key?("decision_id");  "decision_logs" else "other" end}
  </record>
</filter>
```
Assuming that only decision logs (the one written when `console` is enabled) has the field `decision_id`. Ideally, those logs has a field `type` or `tag` with the value `decision_logs`.

**Comment by tsandall** [comment]
@omerlh could you filter on the `"msg"` field? Decision logs are emitted with the `"msg": "Decision Log"`.

**Comment by omerlh** [comment]
yeah, that exactly what I was aiming for. I can send a PR later.
