### ISSUE TITLE
How does policy access context data from application?

### ISSUE THREAD

**Issue by yogereddy** [open-policy-agent/opa#1717]
The policy outlined here https://www.openpolicyagent.org/docs/latest/http-api-authorization/#2-load-a-policy-into-opa has the context of subordinates. What are the ways to pass this context data in OPA and how can this be updated periodically as and when new users are added to the system.
I couldn't find this anywhere in the documentation. Can you help me understand this?

**Comment by ashutosh-narkar** [comment]
OPA has a [bundle](https://openpolicyagent.org/docs/latest/bundles/) feature which allows to periodically download bundles of policy and data from remote HTTP servers.  Here is doc which provides guidance about getting data into OPA https://www.openpolicyagent.org/docs/edge/data-replication/.

**Comment by tsandall** [comment]
The various options are covered by the doc that @ashutosh-narkar linked. Closing this.
