### ISSUE TITLE
Add support for watch mode in `opa test`

### ISSUE THREAD

**Issue by Fox32** [open-policy-agent/opa#1719]
# Expected Behavior

OPA already has a watch mode when run as a server (#267), which reloads the policy on file-system changes. I would expect a `-w` option also for `opa test` which monitors the file-system, reloads the policies and outputs the test results on every change. This is can be useful when doing TDD of policies.

# Actual Behavior

There is not `-w` option for `opa test`.

**Comment by tsandall** [comment]
This would be nice to have. As far as implementation goes, we should probably factor the watch/fsnotify code out of the `runtime` package into something else that can be shared by the `runtime` and the `tester`.

**Comment by eliw00d** [comment]
Just came across this looking for any previous discussions on --watch functionality since we were interested in it as well. +1!
