### ISSUE TITLE
Support Kubernetes --server-dry-run flag

### ISSUE THREAD

**Issue by spacetj** [open-policy-agent/opa#1749]
# Expected Behavior
When integration testing policies, I want to be able to use the --server-dry-run feature to ensure that the policies are behaving the way that I expect them to without actually applying the resource to the cluster.

# Actual Behavior

OPA doesn't support dry run. Returns the error below.

```bash
Error from server (InternalError): error when creating "file.yaml": Internal error occurred: admission webhook "webhook.openpolicyagent.org" does not support dry run
```

# Steps to Reproduce the Problem

  1. Create a policy.
  2. Install OPA and deploy the policy to a kube cluster with a version of 1.13 or above.
  3. run `kubectl apply -f --server-dry-run file.yaml` with any resource that violates the created policy

**Comment by tsandall** [comment]
@space I think this is supported today via the webhook configuration. Take a look at https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects. If that doesn't address this issue feel free to re-open.
