### ISSUE TITLE
docs: Update Terraform guide to show nested `child_modules`

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#1772]
The current Terraform guide works as expected, but the example only shows using a `root_module` and no `child_modules` nested further down.

This is likely to be a common thing that people run into as it is considered good practice to make smaller modules and piece together larger plans with them.

We should update the docs to show an example and give some hints around how to collect all of the resources.

For reference:
* https://www.terraform.io/docs/internals/json-format.html#plan-representation -- Defines the JSON scheme that the plans will have and shows a good example.
* https://play.openpolicyagent.org/p/0K5cSyB6vi -- Shows an example of one way to gather all the resources, as well as example JSON structure.

**Comment by princespaghetti** [comment]
@patrick-east I'll take a pass at this. Are you thinking an additional example in addition to the blast radius one, or modifying the current one to also have a module included?

**Comment by patrick-east** [comment]
I think another example, maybe doesn't need to be as complex. Just showing how to deal with collecting resources from the child modules.

**Comment by princespaghetti** [comment]
Sounds good! I'll start working on that
