### ISSUE TITLE
Proposal:  Support Key-value stores in OPA data source 

### ISSUE THREAD

**Issue by xin-styra** [open-policy-agent/opa#1798]
# Expected Behavior
Authorization and compliance checks often require information and context besides the policy itself. OPA now supports data source as JSON document and it supports CRUD. However, the changes to JSON is hard.  While key-value store already exists and its CRUD model is relatively simple. 

# Actual Behavior
Allow defining key-value stores in the data source and provide interfaces to maintain.
This store could act as a cache connecting real database data and OPA.
This store could be LRU based cache.

# Steps to Reproduce the Problem
N/A
# Additional Info

**Comment by tsandall** [comment]
There are no plans to implement support for arbitrary key-value stores in OPA right now. Closing this as stale.
