### ISSUE TITLE
Add Additional String Trimming Functions

### ISSUE THREAD

**Issue by hasit** [open-policy-agent/opa#1801]
# Expected Behavior
As a developer, I expect basic string manipulation functions related to trimming to be built into Rego such as:

1. `func Trim(s string, cutset string) string`
2. `func TrimLeft(s string, cutset string) string`
3. `func TrimPrefix(s, prefix string) string`
4. `func TrimRight(s string, cutset string) string`
5. `func TrimSuffix(s, suffix string) string`
6. `func TrimSpace(s string) string`

# Actual Behavior
Only 1 from the above list exists as of OPA 0.14.1.

# Additional Info
Take for example a scenario where I want to trim prefix "bar-" from a string. 

Using `func Trim(s string, cutset string) string`, we cannot achieve the desired result because it would remove all leading and trailing Unicode code points contained in cutset from s. Here is a playground sample - https://play.openpolicyagent.org/p/ZxCvojSLX7.

On the other hand, we could use `func Replace(s, old, new string) string` (which translates to `func ReplaceAll(s, old, new string) string` in Go), but that would replace every instance of "bar-" in the string. Here is a playground sample - https://play.openpolicyagent.org/p/n0aMcjMdhZ.

# Proposal
I propose we add functions 2-6 from the above list to Rego.

**Comment by tsandall** [comment]
These seem like good additions to me.

**Comment by hasit** [comment]
Working on it. You can assign it to me.
