### ISSUE TITLE
Proposal: Add RegexFindAllStringSubmatch and Replacer#Replace to default builtin

### ISSUE THREAD

**Issue by kenfdev** [open-policy-agent/opa#1804]
# Expected Behavior

* The ability to capture values with Regex subexpressions.
* Replace multiple patterns inside a string with a one liner command.

# Actual Behavior

* Capturing values with Regex isn't possible with the [current builtins](https://www.openpolicyagent.org/docs/latest/policy-reference/#regex)
* You can only replace a single pattern in a string with the [current builtins](https://www.openpolicyagent.org/docs/latest/policy-reference/#regex)

# Additional Info

## Motivation

I've come to a case where I wanted to mimic the behavior of **variables** in AWS IAM. A specific use case is the `PrincipalTag` which you can find [here](https://aws.amazon.com/jp/blogs/security/working-backward-from-iam-policies-and-principal-tags-to-standardized-names-and-tags-for-your-aws-resources/).

Given a JSON policy like the following:

```json
{
  "alice": {
    "resource": "arn:aws:sns:*:*:${aws:PrincipalTag/access-project}-${aws:PrincipalTag/access-application}-${aws:PrincipalTag/access-environment}"
  }
}
```

I'd like to see if the requester has permission to a resource with the following payload (this is a very simplified version):

```json
{
	"input": {
		"principal": {
			"name": "alice",
			"access-project": "web",
			"access-application": "nginx",
			"access-environment": "dev"
		},
		"resource": "arn:aws:sns:*:*:web-nginx-dev"
	}
}
```

In order to achieve this, I need to expand the dynamic parts (e.g. `${aws:PrincipalTag/access-project}`) of the JSON policy at evaluation time which means that I want the string to be replaced like this:

**before**
`arn:aws:sns:*:*:${aws:PrincipalTag/access-project}-${aws:PrincipalTag/access-application}-${aws:PrincipalTag/access-environment}`

**after**
`arn:aws:sns:*:*:web-nginx-dev`

#### capture values with regex

I think [Regexp.FindAllStringSubmatch](https://golang.org/pkg/regexp/#Regexp.FindAllStringSubmatch) would be the best to capture all occurrences.

#### replace multiple patterns inside a string

Since there are multiple patterns to be replaced (e.g. `${aws:PrincipalTag/access-project}`, `${aws:PrincipalTag/access-application}`, `${aws:PrincipalTag/access-environment}`), and since Rego is a declarative language, the string needs to be replaced in one go. The [Replacer.Replace](https://golang.org/pkg/strings/#Replacer.Replace) seems to satisfy this.

### Example Rego

Assuming that Regexp.FindAllStringSubmatch will be called `regex.find_all_string_submatch_n` and Replacer.Replace to be `replacer.replace`. The Rego may look like this:

```
package authz

policies = {
  "alice": {
    "resource": "arn:aws:sns:*:*:${aws:PrincipalTag/access-project}-${aws:PrincipalTag/access-application}-${aws:PrincipalTag/access-environment}"
  }
}

default allow = false
allow {
  # find the policy for principal
  p := policies[input.principal.name]
  # find all matches declared in the regex
  matches := regex.find_all_string_submatch_n(`\${aws:PrincipalTag/(.*?)}`, p.resource, -1)
  oldnews := [r | some i, j
    # include only the captured values
    captures := array.slice(matches[i], 1, count(matches[i]))
    # create pairs of old/new
    oldnew := [sprintf("${aws:PrincipalTag/%s}", [captures[j]]), input.principal[captures[j]]]
    # flatten the old/new array
    r := oldnew[_]]
  # replace all the occurrences
  r := replacer.replace(oldnews, p.resource)

  # check if the resource inside the policy matches (wild card check isn't implemented in this example)
  r == input.resource
}
```

With this rego, I can dynamically expand values inside the JSON policy.

### Implementation Example

Here is a branch of a working example version of the OPA:

https://github.com/kenfdev/opa/tree/add-builtins-related-to-string

And here is an implementation I came up with (disclaimer:no docs, not enough test cases):

https://github.com/kenfdev/opa/commit/723bf1b79bc1c2bac819a7b9d921b3063b5be50f

What I explained above is very use case specific and I'm using it with custom builtins in my project, but since these functions are included in the standard library of Go, I thought maybe there are more use cases which can benefit from it and thought I can give some feedback.

If this is not the time or if there are other considerations I'm missing, I'll just close this issue and keep the functionality for my own use case.

Thank you for your attention!

**Comment by tsandall** [comment]
I'm not opposed to adding these built-in functions since they're based on stdlib functions. I'm wondering about the approach though because I suspect it's going to be difficult to optimize the rule you showed above. If the number of policies per user is large, we're going to be stuck performing a linear scan over them. If the policy was expressed in purely in Rego it might be more efficient and clearer. For example:

```
allow {
  input.principal.name == "alice"
  name := sprintf("%v-%v-%v", [input.principal.project, input.principal.app, input.principal.env])
  input.resource == ["arn", "aws", "sns", _, _, name]
}
```

In this case, the indexer will be able to index the 1st and 3rd expressions inside the rule body.

**Comment by tsandall** [comment]
The idea would be to create a separate `allow` rule for each set of variables. For example:

```
allow {
  input.principal.name == "alice"
  name := sprintf("%v-%v-%v", [input.principal.project, input.principal.app, input.principal.env])
  input.resource == ["arn", "aws", "sns", _, _, name]
}

allow {
  input.principal.name == "alice"
  name := sprintf("%v-%v-%v", [input.principal.project, input.principal.app, input.principal.env])
  input.resource == ["arn", "aws", "ec2", _, _, name]
}

allow {
  input.principal.name == "bob"
  name := sprintf("%v-%v-%v", [input.principal.project])
  input.resource == ["arn", "aws", "dynamodb", _, _, name]
}
```

There will be a tradeoff between policy load/compile time and policy evaluation. In the regex version, the policy will load/compile quickly (because it's so small) but the evaluation time will grow linearly with the # of policies per user. OTOH, in the version above, the policy load time will grow with the # of allow rules, but the evaluation time will remain constant.
