### ISSUE TITLE
Supporting multiple webhook configurations

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#1818]
Hello all. I've recently expanded our OPA policy configuration to perform a simple _mutation_ on Kubernetes resources (mostly based on https://github.com/open-policy-agent/opa/issues/943).

However, I now find myself in a situation where I have a single endpoint/handler/`opa-default-system-main` for both a mutating and admission webhook. Sometimes my OPA is returning allowed: false from the mutating webhook instead of the admission one (and while this works, it's not how these features were intended to be used). (I am able to do this because I'm not mutating areas of the objects that are later required for validation.)

I'd like to be able to point my admission webhook at a different `opa-default-system-main` configmap than my mutating webhook. Does anyone know if this is something OPA supports?

My only other option seems to be to run another OPA deployment, one for admission and one for validations. Not ideal but still doable.

(p.s. when I say `opa-default-system-main` I mean the main entry point to an OPA controller that creates an endpoint for kubernetes to query - can I have multiple?)

**Comment by tsandall** [comment]
@charlieegan3 by default the Kubernetes API server will execute an HTTP POST against OPA like:

```http
POST / HTTP/1.1
```

In recent version of Kubernetes you can configure the webhook to specify a path in the service config. If you do this you could point the mutating webhook at `/v0/data/path/to/mutating_decision` and the validating webhook at `/v0/data/path/to/validating_decision`. The /v0 OPA API prefix is documented here: https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-webhook. Then inside you' structure your policy like this:

```
package path.to

mutating_decision = { ... }

validating_decision = { ... }
```

For more detail on the admission control flow see this page: https://www.openpolicyagent.org/docs/latest/kubernetes-primer/#detailed-admission-control-flow

Hope this helps!

**Comment by charlieegan3** [comment]
Ahh, that looks just like what I need - Thanks!
