### ISSUE TITLE
Feature request: Support OpenShift v4 (crc) & OpenShift Service Mesh

### ISSUE THREAD

**Issue by stevef1uk** [open-policy-agent/opa#1822]
# Expected Behavior
I am using crc and installed the OpenShift Service Mesh operator, which installs Istio etc. Note: for some reason RedHat have decided to implement the istio containers in the openshift-operators namespace.

I deployed the sample application from: https://raw.githubusercontent.com/Maistra/bookinfo/master/bookinfo-gateway.yaml
and the application installed ok.

I then tried to follow the guide here: https://github.com/open-policy-agent/opa-istio-plugin
I hoped (but didn't expect this set-up to work). I installed on minikube and of course all was fine.

# Actual Behavior
No sample application containers deployed, just lots of errors as follows:

Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": Post https://admission-controller.opa-istio.svc:443/v0/data/istio/inject?timeout=30s: no endpoints available for service "admission-controller"

# Steps to Reproduce the Problem

  1. Install Code Ready Containers from RedHat - see: https://developers.redhat.com/blog/2019/09/05/red-hat-openshift-4-on-your-laptop-introducing-red-hat-codeready-containers/
 2. Install the RedHat Service Mesh Operator
3. Follow the guide here: https://github.com/open-policy-agent/opa-istio-plugin

# Additional Info

**Comment by ashutosh-narkar** [comment]
@stevef1uk thanks for filing this issue. From the error log, it looks like either the Kube API server cannot communicate with OPA or may have something to do with the webhook configuration.  Can you share OPA's logs ?

**Comment by stevef1uk** [comment]
I found the opa-istio project and the container in there had the following logs:

time="2019-10-04T18:50:43Z" level=info msg="First line of log stream." addrs="[0.0.0.0:443]" insecure_addr=
time="2019-10-04T18:50:43Z" level=fatal msg="Listener failed." err="listen tcp 0.0.0.0:443: bind: permission denied"

I know how to fix that so I used the commands:
$ oc adm policy add-scc-to-user anyuid -z default -n opa-istio
$ oc adm policy add-scc-to-user privileged -z default -n opa-istio

that enabled the admission-controller to run sucessfully

Now when I deploy the sample application I am getting different errors in the project I have used, my project:

productpage-v1-6588d4db7
NamespaceNSmyproject
a few seconds ago
Generated from replicaset-controller
6 times in the last 2 minutes
(combined from similar events): Error creating: pods "productpage-v1-6588d4db7-c4gb9" is forbidden: unable to validate against any security context constraint: []

RSreviews-v1-7464fbc59d
NamespaceNSmyproject
less than a minute ago
Generated from replicaset-controller
6 times in the last 2 minutes
(combined from similar events): Error creating: pods "reviews-v1-7464fbc59d-ggpnp" is forbidden: unable to validate against any security context constraint: []

I realised I need to add the same two command I entered above against my project and the application deployed :-) I also added the command:
kubectl label namespace my project  opa-istio-injection="enabled"
before deploying the application. I can see 3 containers deployed per pod :-)

**Comment by stevef1uk** [comment]
The problem I have now is that the policy does not seem to being applied.

**Comment by ashutosh-narkar** [comment]
That's good progress ! Can you check the OPA logs in the application pod (eg. `productpage`) to see if Istio proxy is forwarding requests to OPA.

**Comment by stevef1uk** [comment]
No logs from product page, but Istio_Proxy  logs:

2019-10-04T20:30:08.803907Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2019-10-04T20:30:10.689466Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2019-10-04T20:30:12.718425Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
[2019-10-04 20:30:12.750][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-10-04 20:30:12.779][19][warning][filter] [src/envoy/http/authn/http_filter_factory.cc:102] mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
[2019-10-04 20:30:12.821][19][warning][filter] [src/envoy/http/authn/http_filter_factory.cc:102] mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
2019-10-04T20:30:14.703027Z	info	Envoy proxy is ready
[2019-10-04 20:30:19.756][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-10-04 20:30:34.917][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-10-04 20:30:35.524][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-10-04 20:30:46.184][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-10-04 20:30:48.030][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-10-04 20:31:47.458][19][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.

****

opa-proxy logs:
{"addrs":[":8181"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2019-10-04T20:28:38Z"}
{"addr":":9191","dry-run":false,"enable-reflection":false,"level":"info","msg":"Starting gRPC server.","query":"data.istio.authz.allow","time":"2019-10-04T20:28:38Z"}

**Comment by ashutosh-narkar** [comment]
Looks like `Istio proxy` and `OPA` are ready but there is no incoming request. Are you exposing the application so that it's accessible outside the cluster ?

**Comment by stevef1uk** [comment]
Yes.

 curl -k --user bob:password -i http://istio-ingressgateway-openshift-operators.apps-crc.testing/productpage
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 4415
server: istio-envoy
date: Fri, 04 Oct 2019 20:34:26 GMT
x-envoy-upstream-service-time: 1941
Set-Cookie: ac57177da280f30d53dc98aee632490e=43f18ec96a287c13848c720c0a216fec; path=/; HttpOnly
Cache-control: private

<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>

*** <snipped rest >

curl -k --user alice:password -i http://istio-ingressgateway-openshift-operators.apps-crc.testing/api/v1/products
HTTP/1.1 200 OK
content-type: application/json
content-length: 395
server: istio-envoy
date: Fri, 04 Oct 2019 19:50:16 GMT
x-envoy-upstream-service-time: 4
Set-Cookie: ac57177da280f30d53dc98aee632490e=8a9cb42c9b0e2b9d8de7123576386c0e; path=/; HttpOnly
Cache-control: private

[{"descriptionHtml": "<a href=\"https://en.wikipedia.org/wiki/The_Comedy_of_Errors\">Wikipedia Summary</a>: The Comedy of Errors is one of <b>William Shakespeare's</b> early plays. It is his shortest and one of his most farcical comedies, with a major part of the humour coming from slapstick and mistaken identity, in addition to puns and word play.", "id": 0, "title": "The Comedy of Errors"}]

**Comment by ashutosh-narkar** [comment]
Are the OPA logs still empty ? If the sample policy was being enforced, `alice` shouldn't have been able to access `api/v1/products`. This could mean that Envoy external authz filter isn't calling out to OPA. Do you see any logs in the Istio proxy container that indicate any errors related to this.

**Comment by stevef1uk** [comment]
The opa-istio side-car logs are as follows:

{"addrs":[":8181"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2019-10-07T13:18:45Z"}
{"addr":":9191","dry-run":false,"enable-reflection":false,"level":"info","msg":"Starting gRPC server.","query":"data.istio.authz.allow","time":"2019-10-07T13:18:45Z"}

The definition of the Product Page pod is as follows & I think it shows the reason why it isn't working.


Name:               productpage-v1-6588d4db7-2qqsj
Namespace:          myproject
Priority:           0
PriorityClassName:  <none>
Node:               crc-chc9n-master-0/192.168.64.82
Start Time:         Fri, 04 Oct 2019 20:34:18 +0100
Labels:             app=productpage
                    pod-template-hash=6588d4db7
                    version=v1
Annotations:        k8s.v1.cni.cncf.io/networks=istio-cni
                    k8s.v1.cni.cncf.io/networks-status=[{
    "name": "openshift-sdn",
    "interface": "eth0",
    "ips": [
        "10.128.1.147"
    ],
    "default": true,
    "dns": {}
},{
    "name": "istio-cni",
 ...
                openshift.io/scc=anyuid
                sidecar.istio.io/inject=true
                sidecar.istio.io/status={"version":"285b5a38edb642950c84f46577bcef4002385f3a7b7b46e65b3bf74a48bd4d53","annotations":{"k8s.v1.cni.cncf.io/networks":"istio-cni"},"initContainers":null,"containers":["ist...
Status:         Running
IP:             10.128.1.147
Controlled By:  ReplicaSet/productpage-v1-6588d4db7
Containers:
  productpage:
    Container ID:   cri-o://0011435da8ec583a6bb9291b735de1db7041e2efe13bdae2606876a46949bb0f
    Image:          docker.io/maistra/examples-bookinfo-productpage-v1:0.12.0
    Image ID:       docker.io/maistra/examples-bookinfo-productpage-v1@sha256:89fd93df7b971437f8491f568c911699f7cf1dd5538493bcdd5b776869914c4a
    Port:           9080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 07 Oct 2019 14:18:08 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 04 Oct 2019 21:28:16 +0100
      Finished:     Mon, 07 Oct 2019 14:15:39 +0100
    Ready:          True
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ffscq (ro)
  istio-proxy:
    Container ID:  cri-o://bb910dd1474b406f03a9506b7f98ec9c2ada191c36d8d5efe189025094ae8a3d
    Image:         docker.io/maistra/proxyv2-ubi8:1.0.0
    Image ID:      docker.io/maistra/proxyv2-ubi8@sha256:b632cb902f4231da9224f1d210b41099eca69bb8f026de752adb0612f9b5bfc4
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      productpage.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.openshift-operators:15010
      --zipkinAddress
      zipkin.openshift-operators:9411
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
      --statusPort
      15020
      --applicationPorts
      9080
    State:          Running
      Started:      Mon, 07 Oct 2019 14:18:28 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 04 Oct 2019 21:28:31 +0100
      Finished:     Mon, 07 Oct 2019 14:15:40 +0100
    Ready:          True
    Restart Count:  2
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                      productpage-v1-6588d4db7-2qqsj (v1:metadata.name)
      POD_NAMESPACE:                 myproject (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           productpage-v1-6588d4db7-2qqsj (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:   myproject (v1:metadata.namespace)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"openshift.io/scc":"anyuid","sidecar.istio.io/inject":"true"}

      ISTIO_METAJSON_LABELS:  {"app":"productpage","pod-template-hash":"6588d4db7","version":"v1"}

    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ffscq (ro)
  opa-istio:
    Container ID:  cri-o://527249058cdcd52cc8357a12fe7b66904a83cabc8e34bc199028f958f2597202
    Image:         openpolicyagent/opa:0.14.2-istio
    Image ID:      docker.io/openpolicyagent/opa@sha256:c07d985cf3d2ba1ea3ead8cc411e2a2f5d8d31c9bd352296621a077fccdea10e
    Port:          <none>
    Host Port:     <none>
    Args:
      run
      --server
      --config-file=/config/config.yaml
      /policy/policy.rego
    State:          Running
      Started:      Mon, 07 Oct 2019 14:18:44 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 04 Oct 2019 21:28:38 +0100
      Finished:     Mon, 07 Oct 2019 14:15:39 +0100
    Ready:          True
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /config from opa-istio-config (rw)
      /policy from opa-policy (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-ffscq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-ffscq
    Optional:    false
  istio-envoy:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.default
    Optional:    true
  opa-istio-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      opa-istio-config
    Optional:  false
  opa-policy:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        opa-policy
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason           Age                From                         Message
  ----     ------           ----               ----                         -------
  Normal   Scheduled        2d                 default-scheduler            Successfully assigned myproject/productpage-v1-6588d4db7-2qqsj to crc-chc9n-master-0
  Normal   Pulled           2d                 kubelet, crc-chc9n-master-0  Container image "docker.io/maistra/examples-bookinfo-productpage-v1:0.12.0" already present on machine
  Normal   Created          2d                 kubelet, crc-chc9n-master-0  Created container productpage
  Normal   Started          2d                 kubelet, crc-chc9n-master-0  Started container productpage
  Normal   Pulled           2d                 kubelet, crc-chc9n-master-0  Container image "docker.io/maistra/proxyv2-ubi8:1.0.0" already present on machine
  Normal   Created          2d                 kubelet, crc-chc9n-master-0  Created container istio-proxy
  Normal   Started          2d                 kubelet, crc-chc9n-master-0  Started container istio-proxy
  Normal   Pulled           2d                 kubelet, crc-chc9n-master-0  Container image "openpolicyagent/opa:0.14.2-istio" already present on machine
  Normal   Created          2d                 kubelet, crc-chc9n-master-0  Created container opa-istio
  Normal   Started          2d                 kubelet, crc-chc9n-master-0  Started container opa-istio
  Warning  Unhealthy        2d (x3 over 2d)    kubelet, crc-chc9n-master-0  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  NetworkNotReady  2d (x7 over 2d)    kubelet, crc-chc9n-master-0  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network
  Normal   SandboxChanged   2d                 kubelet, crc-chc9n-master-0  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled           2d                 kubelet, crc-chc9n-master-0  Container image "docker.io/maistra/examples-bookinfo-productpage-v1:0.12.0" already present on machine
  Normal   Created          2d                 kubelet, crc-chc9n-master-0  Created container productpage
  Normal   Started          2d                 kubelet, crc-chc9n-master-0  Started container productpage
  Normal   Pulled           2d                 kubelet, crc-chc9n-master-0  Container image "docker.io/maistra/proxyv2-ubi8:1.0.0" already present on machine
  Normal   Created          2d                 kubelet, crc-chc9n-master-0  Created container istio-proxy
  Normal   Started          2d                 kubelet, crc-chc9n-master-0  Started container istio-proxy
  Normal   Pulled           2d                 kubelet, crc-chc9n-master-0  Container image "openpolicyagent/opa:0.14.2-istio" already present on machine
  Normal   Created          2d                 kubelet, crc-chc9n-master-0  Created container opa-istio
  Normal   Started          2d                 kubelet, crc-chc9n-master-0  Started container opa-istio
  Warning  Unhealthy        2d (x8 over 2d)    kubelet, crc-chc9n-master-0  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  NetworkNotReady  18m (x6 over 18m)  kubelet, crc-chc9n-master-0  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network
  Normal   SandboxChanged   17m                kubelet, crc-chc9n-master-0  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled           17m                kubelet, crc-chc9n-master-0  Container image "docker.io/maistra/examples-bookinfo-productpage-v1:0.12.0" already present on machine
  Normal   Created          17m                kubelet, crc-chc9n-master-0  Created container productpage
  Normal   Started          16m                kubelet, crc-chc9n-master-0  Started container productpage
  Normal   Pulled           16m                kubelet, crc-chc9n-master-0  Container image "docker.io/maistra/proxyv2-ubi8:1.0.0" already present on machine
  Normal   Created          16m                kubelet, crc-chc9n-master-0  Created container istio-proxy
  Normal   Started          16m                kubelet, crc-chc9n-master-0  Started container istio-proxy
  Normal   Pulled           16m                kubelet, crc-chc9n-master-0  Container image "openpolicyagent/opa:0.14.2-istio" already present on machine
  Normal   Created          16m                kubelet, crc-chc9n-master-0  Created container opa-istio
  Normal   Started          16m                kubelet, crc-chc9n-master-0  Started container opa-istio
  Warning  Unhealthy        16m (x9 over 16m)  kubelet, crc-chc9n-master-0  Readiness probe failed: HTTP probe failed with statuscode: 503

**Comment by ashutosh-narkar** [comment]
In this case, the `opa-istio` sidecar is already included in the `productpage` pod. So now `istio-proxy` would be communicating with `opa-istio` on localhost. The  `opa-istio` sidecar in the `productpage` pod is not getting any request. So we should check if `opa-istio`'s GRPC endpoint at port `9191` is reachable from the `istio-proxy` container. [This](https://github.com/open-policy-agent/opa-istio-plugin#grpc-server-reflection-usage) link could help.

**Comment by stevef1uk** [comment]
Any links to a grpc proxy image I can deploy to the cluster to execute grpcurl on the cluster. The pods deployed have no tools installed to build it and the istio-proxy container has a read-only file system so I can't install golang and do it myself. I have grpcurl on my mac but my attempt to create a service & route to access the service on the product page container didn't work.

**Comment by ashutosh-narkar** [comment]
You will need to set the `enable-reflection` config option for `opa-istio`. Add `enable-reflection: true` to the plugin config https://github.com/open-policy-agent/opa-istio-plugin/blob/master/quick_start.yaml#L227

**Comment by stevef1uk** [comment]
That setting is already enabled. I just took a look at that config file on my project and that parameter is already set:

$ oc get configmap
NAME               DATA      AGE
opa-istio-config   1         3d2h
opa-policy         1         3d2h

$ oc edit configmap opa-istio-config

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        query: data.istio.authz.allow
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"plugins:\n  envoy_ext_authz_grpc:\n    addr: :9191\n    query: data.istio.authz.allow\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"opa-istio-config","namespace":"myproject"}}
  creationTimestamp: 2019-10-04T18:49:02Z
  name: opa-istio-config
  namespace: myproject
  resourceVersion: "421322"

**Comment by ashutosh-narkar** [comment]
I do not see `enable-reflection: true`. Your config should look something like

```yaml
plugins:
    envoy_ext_authz_grpc:
        addr: :9191
        query: data.istio.authz.allow
        enable-reflection: true
```

**Comment by stevef1uk** [comment]
ok, my cluster not in a good state. I will try again when I have decent internet

**Comment by stevef1uk** [comment]
Good news, with a new crc instance I was able to get the OPA policy working with OpenShift Service Mesh. There were quite a few steps & config changes required. I will reproduce this on another machine when I return home, which has loads more RAM which is needed as my MacBook is really struggling to run all this. 16GM of RA is just not enough the VM is using almost 25GB :-)
Once I am comfortable with the steps I will add to this thread for others in case anyone else needs this. As soon as I have access to a cloud based Openshift instance I will do it there too.

What I want to do now is to configure things so that policies are loaded as bundles from an HTTP server as that is what enterprises will really want I think. I have seen the OPA docs on this but would really like a step by step tutorial to follow as I have a feeling this won't be plain sailing but probably not as hard as getting it to run in the fist place :-)

I also need to discuss with RedHat their policy around support of OpenShift if the OPA integration is performed.

**Comment by ashutosh-narkar** [comment]
That's great @stevef1uk ! When you write-up those steps to make the plugin work with Openshift, we can include those instructions in the repo. Let me know if you need any help with the bundles. The instructions on the OPA website are good but if you have questions, feel free to ask.

**Comment by stevef1uk** [comment]
Steps for how to get OPA to work with crc (OpenShift) and RedHat Service Mesh

cry version: 
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)

Service Mesh Install Steps:
1. crc start
2. cry console —url 
3. Install RedHat Elastic Operator from Console logged in as kubeadmin using Operators -> OperatorHub & enable subscription
4. in a terminal login using kubeadmin
5. oc new-project istio-system 
6. oc new-project myproject
7. Install RedHat Jaeger Operator & enable subscription
8. Install RedHat Kiali Operator & enable subscription
9. Wait for all operators to have a status of InstallSucceeded using Operators -> Installed Operators
10. Install RedHat OpenShift Service Mesh & enable subscription
11. Wait until the  Service Mesh operators has installed 
12. Switch to project istio-system and return to Installed Operators pane
13. Select the RedHat Service Mesh Operator API: ’Istio Service Mesh Control Plane’ and then ‘Create Service Mesh Control Plane’
14. 12 Pods are then created - wait for them to all be in running state & there should be 5 routes created - make a note of the istio-ingressgateway URL for lates
15. Select the RedHat Service Mesh Operator API: ‘Istio Service Mesh Member Role’ and then ‘Create Service Mesh Member Rolls’. Edit the YAML to add myproject (or the project you want to use) within members & Create
16. Still in project istio-system edit the config map: istio and find disablePolicyChecks and change true to false and save

OPA Install Steps following: https://github.com/open-policy-agent/opa-istio-plugin :
	1. kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/quick_start.yaml
         2. Using terminal give opa-istio project required permissions:
		oc adm policy add-scc-to-user anyuid -z default -n opa-istio
		oc adm policy add-scc-to-user privileged -z default -n opa-istio
	3. From terminal or console delete the admission-controller pod in project opa-istio so that a new container is created and will run successfully
      	4. Using terminal switch to my project (oc project myproject) & give same permissions as above:
		oc adm policy add-scc-to-user anyuid -z default -n myproject
		oc adm policy add-scc-to-user privileged -z default -n myproject
	5. Enable istio & op automatic injection into myproject: Note: need to use kubectl and namespace rather than oc and project
		kubectl label namespace myproject opa-istio-injection="enabled"
		kubectl label namespace myproject istio-injection="enabled"
	6. oc apply -f https://raw.githubusercontent.com/Maistra/bookinfo/maistra-1.1/bookinfo.yaml 
         7. In myproject to ensure ope-config config maps are present:
		kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/quick_start.yaml
        8.  Wait until all Pods are running and you should see 3/3 for containers in each pod. This takes rather too long for my liking!
	9. oc apply -f https://raw.githubusercontent.com/Maistra/bookinfo/maistra-1.1/bookinfo-gateway.yaml
	10. Test end points as tutorial shows using ingress-gateway URL found above e.g.
              curl --user alice:password -i http://istio-ingressgateway-istio-system.apps-crc.testing/productpage

**Comment by ashutosh-narkar** [comment]
Thanks @stevef1uk for documenting this. I will work on getting these steps into the repo.

**Comment by priyaadama** [comment]
@ashutosh-narkar I have the same permission issue as above on **kind** cluster using https://github.com/open-policy-agent/opa-envoy-plugin/blame/3a9ed1969adac5e246e20549f6af3f9c0f4f86f5/examples/istio/quick_start.yaml#L319
`{"err":"listen tcp 0.0.0.0:443: bind: permission denied","level":"error","msg":"Listener failed.","time":"2023-03-13T06:00:56Z"}`
Do I need to add any special permissions on kind?

**Comment by anderseknert** [comment]
Looks like we'll need to update the docs there. We shouldn't bind on 443 directly, but use something like 8443 and then have the `Service` map 443 -> 8443 in the pod. I'll have them updated.

**Comment by anderseknert** [comment]
PR up: https://github.com/open-policy-agent/opa-envoy-plugin/pull/402

**Comment by anderseknert** [comment]
Merged. Should work with the updated docs @priyaadama. Let me know if it doesn't!

**Comment by priyaadama** [comment]
> Merged. Should work with the updated docs @priyaadama. Let me know if it doesn't!

Thank you for updating, it works .
