### ISSUE TITLE
Data race when evaluating PreparedEvalQuery from multiple go routines

### ISSUE THREAD

**Issue by nischalsheth** [open-policy-agent/opa#1828]
# Expected Behavior

Calling PreparedEvalQuery.Eval() from multiple go routines should be safe.

# Actual Behavior

Data race when evaluating PreparedEvalQuery from multiple go routines.

# Steps to Reproduce the Problem

1. Configure a policy
2. Construct a prepared query as follows:

```go
func GetPreparedQuery(ctx context.Context, regoQuery, regoPolicyTxt string) (*rego.PreparedEvalQuery, error) {
	regoObj := rego.New(
		rego.Query(regoQuery),
		rego.Module("authz.rego", regoPolicyTxt))
	prepQuery, err := regoObj.PrepareForEval(ctx)
	return &prepQuery, err
}
```
 3. Evaluate the PreparedEvalQuery from multiple go routines

# Additional Info

WARNING: DATA RACE
Write at 0x00c0008ccec0 by goroutine 267:
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/metrics.(*timer).Start()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/metrics/metrics.go:163 +0x69
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego.(*Rego).parseRawInput()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego/rego.go:1059 +0x78
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego.preparedQuery.newEvalContext()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego/rego.go:229 +0x7ce
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego.PreparedEvalQuery.Eval()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego/rego.go:250 +0xbd

Previous write at 0x00c0008ccec0 by goroutine 280:
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/metrics.(*timer).Start()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/metrics/metrics.go:163 +0x69
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego.(*Rego).parseRawInput()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego/rego.go:1059 +0x78
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego.preparedQuery.newEvalContext()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego/rego.go:229 +0x7ce
  gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego.PreparedEvalQuery.Eval()
      /go/src/gopkg.volterra.us/xyz/vendor/github.com/open-policy-agent/opa/rego/rego.go:250 +0xbd

Goroutine 267 (running) created at:
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/server.go:689 +0xb8
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport/http2_server.go:421 +0x1622
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport/http2_server.go:461 +0x37a
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/server.go:687 +0x170
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc.(*Server).handleRawConn.func1()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/server.go:649 +0x50

Goroutine 280 (running) created at:
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/server.go:689 +0xb8
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport/http2_server.go:421 +0x1622
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/internal/transport/http2_server.go:461 +0x37a
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/server.go:687 +0x170
  gopkg.volterra.us/xyz/vendor/google.golang.org/grpc.(*Server).handleRawConn.func1()
      /go/src/gopkg.volterra.us/xyz/vendor/google.golang.org/grpc/server.go:649 +0x50

**Comment by patrick-east** [comment]
Can you verify if the version of OPA being used has https://github.com/open-policy-agent/opa/commit/f8442c1345f712e5fbd32b694eed90cfe960ee18 Included in it?

Going off the error message I suspect it might not (and would explain the race condition)

**Comment by nischalsheth** [comment]
@patrick-east Thanks, updating to v0.14.2 fixed the problem.
