### ISSUE TITLE
Reinstitute fuzzing once known parser issues are resolved

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#1843]
We recently removed Fuzzit testing and Regression from the CI https://github.com/open-policy-agent/opa/pull/1842.

If we plan to remove Fuzzit testing entirely, we need to clean it up from the README, Makefile, scripts etc.

**Comment by tsandall** [comment]
The fuzzit integration has been disabled because the fuzzer was running into [a known issue in the generated parser](https://github.com/mna/pigeon/issues/75). Once the underlying issue in the parser is resolved we could re-enable fuzzit.

**Comment by srenatus** [comment]
Oooold. We're now fuzzing in our nightly tests. With #4451, we'll use Go1.18's native fuzzing features.
