### ISSUE TITLE
Rule processing behavior

### ISSUE THREAD

**Issue by gadinaor** [open-policy-agent/opa#1849]
My Input is:
{
  "message": "world"
}

Policy A:
--------
package play

default hello = false
hello {
  x := {}
  #x := {"well"}
  input.message == "world"
  print_that_messup_the_result := sprintf("%v", [x[_]])
}

Policy B:
--------
package play

default hello = false
hello {
  #x := {}
  x := {"well"}

  input.message == "world"
  print_that_messup_the_result := sprintf("%v", [x[_]])
}

Policy A --> result is false
Policy B --> result is true

Playground snippet can be found here:
https://play.openpolicyagent.org/p/jpab3rhdIu

I may very well be missing something, but this behavior is quite confusing - is this by design? a bug?

**Comment by gadinaor** [comment]
@patrick-east thanks for the clarification.

I would expect both the above and yours https://play.openpolicyagent.org/p/35Yk8fG5lt
to render the rule as **true**

My main concern here, is that  **sprintf** affects the policy decision based on its input - I get the pure language behavior, but I'd say such "honest" programming mistakes would be common.

GO is good example of how those undefined Xprintf functions are handled.

Would you consider making sprintf being more "neutral" when it comes to rule processing? for example sprintf can never be 'undefined' or 'false'

**Comment by patrick-east** [comment]
I'm not sure we would be able to make a change to the behavior without affecting people in a backwards incompatible way. In theory we could make a new builtin or some other language feature for that sort of thing.. but I'm not sure if its really the right thing to do.

I think comparing it to GO is fair in some respects, but the main difference is the declarative nature of Rego and how it evaluates things. The line `print_that_messup_the_result := sprintf("%v", [x[_]])` it is effectively the same as:

```ruby
tmp := x[_]
print_that_messup_the_result := sprintf("%v", [tmp])
```

So now the evaluation through the rule body would bail out before it even reaches the sprintf.. so having the special behavior for sprintf wouldn't effect the outcome _but_ (if we had special behaviro for it) the same logic structured differently might. You have to consider then that the variable or reference we are printing out maybe isn't declared anywhere nearby.. and maybe depends on many additional rules/functions. I guess the point I'm getting at is that its much more than just a special case for sprintf or that it is evaluating to false/undefined.

**Comment by gadinaor** [comment]
@patrick-east thanks
