### ISSUE TITLE
Please document how to build the docker image

### ISSUE THREAD

**Issue by stevef1uk** [open-policy-agent/opa#1850]
# Expected Behavior
The container built with make && docker build . should work

# Actual Behavior
When trying to run with the 'run' parameter I am encountering the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"run\": executable file not found in $PATH": unknown.

# Steps to Reproduce the Problem

In the opa/opa-istio-plugin directory
  1. make clean && make
  2. docker build . -t stevef1uk/opa-istio-plugin
  3. docker run --rm  stevef1uk/opa-istio-plugin run server

# Additional Info
Performing his on  a mac with Catalinia installed.
go version go1.13.1 darwin/amd64

**Comment by patrick-east** [comment]
Couple things.. First off, for anyone else reading this in the future. The easiest way is to just do
```
make clean image-quick
docker tag <whatever name just got built> <name you want>
```

To do more customizations you can do the steps the Makefile does manually:
https://github.com/open-policy-agent/opa-istio-plugin/blob/master/Makefile#L67-L69

```
{10:29} ✘ ~/p/g/s/g/o/opa-istio-plugin:master ◈ ❯ make clean build-linux
rm -f .Dockerfile_*
rm -f opa_*_*
rm -f *.so
go generate ./...
go build -o opa_istio_linux_amd64 -ldflags "-X github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/version.Version=0.14.2-istio-5 -X github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/version.Vcs=7db4dccc-dirty -X github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/version.Timestamp=2019-10-17T17:29:54Z -X github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/version.Hostname=Patricks-MBP.localdomain" ./cmd/opa-istio-plugin/...
{10:29} ~/p/g/s/g/o/opa-istio-plugin:master ◈ ❯ sed -e 's/GOARCH/amd64/g' Dockerfile > ./Dockerfile_amd64
{10:30} ~/p/g/s/g/o/opa-istio-plugin:master ◈ ❯ docker build -f ./Dockerfile_amd64 . -t my-opa-istio-img
Sending build context to Docker daemon  163.4MB
Step 1/6 : FROM gcr.io/distroless/base
 ---> a0cfcd4cc98a
Step 2/6 : MAINTAINER Ashutosh Narkar  <anarkar4387@gmail.com>
 ---> Using cache
 ---> 36569f24f0ea
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> 52ce6859048a
Step 4/6 : COPY opa_istio_linux_amd64 /app
 ---> e1ded38792be
Step 5/6 : ENTRYPOINT ["./opa_istio_linux_amd64"]
 ---> Running in dc15e87bc351
Removing intermediate container dc15e87bc351
 ---> 2b8b4d26e677
Step 6/6 : CMD ["run"]
 ---> Running in e7a63c2e81f5
Removing intermediate container e7a63c2e81f5
 ---> 2ce93feee3f1
Successfully built 2ce93feee3f1
Successfully tagged my-opa-istio-img:latest                                                                                                                                                      
{10:30} ~/p/g/s/g/o/opa-istio-plugin:master ◈ ❯ docker run --rm my-opa-istio-img run --server
{"addrs":[":8181"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2019-10-17T17:30:59Z"}
^C{"level":"info","msg":"Shutting down...","time":"2019-10-17T17:31:02Z"}
{"level":"info","msg":"Server shutdown.","time":"2019-10-17T17:31:02Z"}
```

The key being that the Dockerfile requires the architecture subbed in (hence that `sed` command), *and* that you need to build the linux binaries for the image to run. If you run `make` you get binaries for the local environment, in this case being OSX.

At a guess from the bug report you got the GOARCH thing working (else the image build would fail), so probably the last trick is to build the correct binary format for the docker image (linux).


So.. we could/should probably put some of that into the docs. Not sure what the best spot it, @ashutosh-narkar any thoughts?

**Comment by stevef1uk** [comment]
I am still finding that the newly build opa is not working for me:

oc logs ratings-v1-f745cf57b-txqbn -c opa-istio

error: config error: plugin "envoy_ext_authz_grpc" not registered
from the opa

**Comment by ashutosh-narkar** [comment]
@stevef1uk just to make sure you have pulled in the latest code and built the binary for your platform. Just as a test, run `make build` in the repo. This will create a binary for opa-istio (`opa_istio_darwin_amd64` or `opa_istio_linux_amd64`) . Then run the created binary 
```bash
./opa_istio_darwin_amd64 run --server --log-level=debug --config-file=config.yaml policy.rego
```

where your config file looks something like:
```bash
plugins:
    envoy_ext_authz_grpc:
        addr: :9191
        query: data.istio.authz.allow
        dry-run: false
        enable-reflection: true
```

You should see logs similar to:
```bash
{"addrs":[":8181"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2019-10-28T10:07:34-07:00"}
{"addr":":9191","dry-run":false,"enable-reflection":true,"level":"info","msg":"Starting gRPC server.","query":"data.istio.authz.allow","time":"2019-10-28T10:07:34-07:00"}
```

**Comment by stevef1uk** [comment]
Having done that and running:

./opa_darwin_amd64 run --server --log-level=debug --config-file=config.yaml policy.rego
I get the same error locally: 
error:  config error: plugin "envoy_ext_authz_grpc" not registered

**Comment by ashutosh-narkar** [comment]
Can you share your config file ?

Also this is the latest commit. Just making sure you are building off this.
```bash
$ git log -n 1
commit 7db4dccc8dd2779ca82799b41c3b60eff278af0f (HEAD -> master, upstream/master)
Author: Ashutosh Narkar <anarkar4387@gmail.com>
Date:   Fri Oct 11 15:19:16 2019 -0700

    Add example showing how to run opa-istio with policy bundles
```

**Comment by stevef1uk** [comment]
commit 9f3f54050fba231effc04db9346909b4b0f09295 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Paul Mundt <paul.mundt@adaptant.io>
Date:   Tue Oct 15 10:54:48 2019 +0200

    Add openfaas-function-authorization to integration index
    
    Signed-off-by: Paul Mundt <paul.mundt@adaptant.io>


Config files are the sample ones. The one you proposed above & the sample policy from https://github.com/open-policy-agent/opa-istio-plugin

**Comment by ashutosh-narkar** [comment]
The commit you have mentioned is for [open-policy-agent/opa](https://github.com/open-policy-agent/opa). What's the commit for [opa-istio-plugin](https://github.com/open-policy-agent/opa-istio-plugin) ?

It should be https://github.com/open-policy-agent/opa-istio-plugin/commit/7db4dccc8dd2779ca82799b41c3b60eff278af0f

**Comment by stevef1uk** [comment]
Yes, sorry my bad. Building in the right directory does not have this issue.

**Comment by tsandall** [comment]
Looks like this is resolved. Closing.
