### ISSUE TITLE
Crash during parse of rego expression having key of form 'foo.bar'

### ISSUE THREAD

**Issue by rich-dtk** [open-policy-agent/opa#1852]
# Expected Behavior
Loading the following should parse successfully
```
test = { a |
  foo := {"a" : "b"}
  a := { foo.a : "b" }
}
``` 
Code version is OPA 0.14.2 (commit db9855d1, built at 2019-10-04T15:28:47Z)

# Actual Behavior
When opa run is done loading in this expression get
```
panic: corrupt object [recovered]
        panic: corrupt object

goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.(*Compiler).compile.func1()
        /go/src/github.com/open-policy-agent/opa/ast/compile.go:812 +0x73
panic(0xe7bee0, 0x108ca10)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/open-policy-agent/opa/ast.(*object).Iter(0xc0001b2330, 0xc0001ffa80, 0x20, 0xeeb960)
        /go/src/github.com/open-policy-agent/opa/ast/term.go:1736 +0xf2
github.com/open-policy-agent/opa/ast.(*object).Foreach(0xc0001b2330, 0xc0001af460)
        /go/src/github.com/open-policy-agent/opa/ast/term.go:1759 +0x53
github.com/open-policy-agent/opa/ast.walk(0x109f320, 0xc0001aaa60, 0xf737e0, 0xc0001b2330)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:110 +0x835
github.com/open-policy-agent/opa/ast.Walk(0x109f320, 0xc0001aaa60, 0xf737e0, 0xc0001b2330)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:27 +0x15a
github.com/open-policy-agent/opa/ast.walk(0x109f320, 0xc0001aaa60, 0xf53180, 0xc0001a7680)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:104 +0xe9e
github.com/open-policy-agent/opa/ast.Walk(0x109f320, 0xc0001aaa60, 0xf53180, 0xc0001a7680)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:27 +0x15a
github.com/open-policy-agent/opa/ast.walk(0x109f320, 0xc0001aaa60, 0xf751e0, 0xc000191770)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:92 +0x985
github.com/open-policy-agent/opa/ast.Walk(0x109f320, 0xc0001aaa60, 0xf751e0, 0xc000191770)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:27 +0x15a
github.com/open-policy-agent/opa/ast.walk(0x109f320, 0xc0001aaa60, 0xf54260, 0xc0001af420)
        /go/src/github.com/open-policy-agent/opa/ast/visit.go:80 +0xba6

```
# Steps to Reproduce the Problem

  1. create a refo file with content 
```
test = { a |
  foo := {"a" : "b"}
  a := { foo.a : "b" }
}
```
call this test.rego
  2. opa run test.rego
  3.

# Additional Info

**Comment by patrick-east** [comment]
Looking into this a little bit the issue appears to be that we rewrite `foo.a` to `__local0__.a` in the `RewriteLocalVars` compile stage, but didn't update the object `elems` keys so the new hash of `__local0__.a` doesn't match anything in the object and the panic is triggered when what amounts to `obj.get("__local0__.a")` is called:

```go
		node := obj.get(k)
		if node == nil {
			panic("corrupt object")
		}
```

This looks similar (although not quite the same?) as https://github.com/open-policy-agent/opa/issues/1125 and its corresponding fix https://github.com/open-policy-agent/opa/commit/a802ddab093626beb94df33723f16023ad333456

Debugging through the code it looks like we hit https://github.com/open-policy-agent/opa/blob/master/ast/compile.go#L3056 for `{ foo.a: "b"}` and use the key `foo.a` for the copied object, it kind of seems like we should be using the substituted one `__local0__.a` but the key won't be updated until the outer `rewriteDeclaredVarsInTermRecursive` visits that node in subsequent steps.

Not 100% sure the best way to fix this, @tsandall any thoughts?
