### ISSUE TITLE
Excluding a particular namespace (Ex: kube-system)  from OPA 

### ISSUE THREAD

**Issue by pratheep-kumar** [open-policy-agent/opa#1855]
Basically what we are trying to do is like enabling OPA for all the k8s namespaces by default. But it should exclude some specific namespaces like kube-system etc., Is there any possible way to do this efficiently ?

**Comment by tsandall** [comment]
You can configure the webhook to exclude namespaces with a label selector. The installation steps in the tutorial on openpolicyagent.org do this: https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#3-deploy-opa-on-top-of-kubernetes.

You may want to consider RBAC or admission policy that restricts who can set these labels.

**Comment by Abdoul2017** [comment]
Can the values (in this case ignore) be parameterized? Wouldn't this change from cluster to cluster?

webhooks:
  - name: validating-webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore

**Comment by tsandall** [comment]
@Abdoul2017 I do not know of a scenario where those values have to change from cluster-to-cluster--to be clear, that configuration tells Kubernetes NOT to invoke the webhook for objects in namespaces where the namespace is labelled with `openpolicyagent.org/webhook=ignore`. This is a standard Kubernetes resource (like a Deployment or Pod or whatever). If you want to configure different values on a per-cluster basis, that's on you.
