### ISSUE TITLE
How to debug the decision logs from opa-istio-plugin?

### ISSUE THREAD

**Issue by siucng2222-c** [open-policy-agent/opa#1881]
# Expected Behavior
Decision logs should be available from the logs of istio-proxy (envoy) or opa-istio sidecar containers for debugging the input, policy run and allow/fail reasons

# Actual Behavior
Envoy log only shows HTTP 403 in access log when policy not passed. opa-istio did not show any useful log for debugging the fail reason

# Steps to Reproduce the Problem

  1. Setup opa-istio-plugin quickstart and deploy bookinfo sample app according to documentation
  2. Curl test on productpage and try to generate some 403 error using different users
  3. Check istio-proxy or opa-istio containers logs in productpage pod, no details about why the decision made

# Additional Info
Indeed this is a question rather than an issue report. Was not able to found any documentations about how to obtain the decision logs for debugging the failure reason. Unsure if I have any mis-config on the rego code, it has gone through the policy successfully and come up with an "allowed = false" decision ... Would like to know how to enable logs for debug

**Comment by ashutosh-narkar** [comment]
@siucng2222-c you have 2 options to see more debug logs from opa-istio. The logs will tell you the input to OPA, the query, result etc.

1. Turn on console logging of decision logs https://www.openpolicyagent.org/docs/latest/management/#local-decision-logs. You can update the config to add this https://github.com/open-policy-agent/opa-istio-plugin/blob/master/quick_start.yaml#L224. 

2. Set the opa log level to debug `--log-level=debug`.  You can start the plugin with this configuration https://github.com/open-policy-agent/opa-istio-plugin/blob/master/quick_start.yaml#L107.

**Comment by tsandall** [comment]
Closing this because it looks like @ashutosh-narkar's answer covers it.

**Comment by tsandall** [comment]
@siucng2222-c can you let us know if enabling the decision logs like @ashutosh-narkar described is enough? The decision logs will tell you:

* The input that provided to the policy
* The revision of the policy that was evaluated
* The result of the policy query

However, it will not currently give you fine-grained details on the rules that got evaluated.

**Comment by siucng2222-c** [comment]
@tsandall I followed @ashutosh-narkar 's instructions and enabled both debug log and decision logs successfully. I can see the input and the final decision from the logs, but looking forward to more fine-grained details about how the rules was evaluated to give out such decision as you mentioned. In addition, existing plugin returns HTTP 403 when decision returns false, it would be great if more concrete "fail reason" can be returned according to the rule... Anyway it will be separate issue or feature request. This issue can be closed. Thanks in advance for your help
