### ISSUE TITLE
Issue with io.jwt.decode_verify

### ISSUE THREAD

**Issue by prabath** [open-policy-agent/opa#1882]
# Expected Behavior
 
Policy to try out: https://play.openpolicyagent.org/p/C88kN49utc

Should return true.

# Actual Behavior

Returns false. But works fine with io.jwt.verify_rs256(input.token, certificate)

# Steps to Reproduce the Problem

  1. Policy to try out: https://play.openpolicyagent.org/p/C88kN49utc
  2. You can try out it as it is - and I've made token expiry to 2048.

**Comment by patrick-east** [comment]
Looking into this more I believe that the `io.jwt.decode_verify` is working correctly.

I updated the example to make it work: https://play.openpolicyagent.org/p/Vchy9Kdl4x

The key being that the constraints to verify it needed the `aud` field.  As described in the documentation:

>The audience that the verifier identifies with. If this is present then the aud claim is checked against it. If it is absent then the aud claim must be absent too.

And in the JWT spec: https://tools.ietf.org/html/rfc7519#section-4.1.3

>Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.  

Which I think are both saying the same thing. If there is an `aud` claim in the token, you must verify it.

The other helpers like `verify_rs256` are limited to verifying the signature and not the validity of the JWT claims.

In a separate thread I'll look into better ways for us to provide feedback to a user about why these API calls failed. As-is it is not very clear what happened when it failed to verify.

**Comment by danielpopskandor** [comment]
> In a separate thread I'll look into better ways for us to provide feedback to a user about why these API calls failed. As-is it is not very clear what happened when it failed to verify.

@patrick-east sorry for resurrecting such an old thread, but has there been any update in surfacing what failed to verify on `io.jwt.decode_verify`? I desire the ability to know if it's a bad audience, or expired, or bad issued at, etc.

**Comment by charlieegan3** [comment]
Hey, I guess the I've seen people use a combination of a suitable verification function e.g. [io.jwt.verify_hs256](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-tokens-iojwtverify_hs256) and then [io.jwt.decode](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-tokens-iojwtdecode) in the past for this.

Are you handling tokens with different signature types?
