### ISSUE TITLE
How to take union of two JSON objects?

### ISSUE THREAD

**Issue by yashhere** [open-policy-agent/opa#1891]
Hi, I am trying to write the following Rego policy -
```
package 
import input
	
result[result] {
	http.send({"method": "get", "url": "http://localhost:3000/data", "headers": {"X-Foo":"bar", "X-Opa": "rules"}}, output)
        result := json.unmarshal(output) | input
}
```

I have a set of input attributes in JSON format. In the policy, I am fetching some new attributes from an external source, which is stored in the variable `output`. Now I want to merge these two JSON objects. The set-union operation will not work here.  Is it possible to do this kind of operation in Rego?

To give more clarity, please see the examples below - 
`input.json`
```json
{
    "attributes": [{
        "dip": "1.1.1.15",
        "dport": "20",
        "protocol": "UDP",
        "appName": "fakebot",
        "name": "pack_incident-response_crontab"
    }]
}
```

`output.json`
```
{
    "attributes": [{
        "dip": "1.1.1.15",
        "dport": "21",
        "protocol": "UDP",
        "appName": "mediabot",
        "calendarTime": "Thu Oct 31 06:35:06 2019 UTC",
        "hostIdentifier": "ip-172-31-30-114"
    }]
}
```

The result should be 
```json
{
    "attributes": [{
        "dip": "1.1.1.15",
        "dport": "21",
        "protocol": "UDP",
        "appName": "mediabot",
        "calendarTime": "Thu Oct 31 06:35:06 2019 UTC",
        "hostIdentifier": "ip-172-31-30-114",
        "name": "pack_incident-response_crontab"
    }]
}
```

So the result should be a union of `input.json` and `output.json` with preference to `output.json` key-value pairs in case of any contradiction.

Any help is much appreciated.

**Comment by tsandall** [comment]
@yashhere try this: https://play.openpolicyagent.org/p/uyX27w1JuB

Taken from here: https://www.openpolicyagent.org/docs/latest/policy-cheatsheet/#merge-objects

Closing for now but feel free to re-open if you feel this doesn't answer your original q.

**Comment by yashhere** [comment]
Thanks for the help. It works as expected.
