### ISSUE TITLE
http.send: allow caller to disable TLS verification for debug purposes 

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1895]
The `http.send` built-in function doesn't let the caller disable TLS verification for debug purposes which is a bit annoying. It should be relatively simple to extend the built-in to accept a parameter that turns off TLS verification. The docs should strongly recommend avoiding this in practice.

```
http.send({..., "tls_insecure_skip_verify": true})
```

**Comment by Salamandastron1** [comment]
I'm going to look into this because I need this for a couple use cases

**Comment by patrick-east** [comment]
Fixed in #2157
