### ISSUE TITLE
io.jwt.decode_verify should not short-circuit

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1901]
# Expected Behavior

The `io.jwt.decode_verify` implementation should not error if none of the keys can be used to verify the signature. Instead it should simply indicate that the signature is not valid. 

# Actual Behavior

The `io.jwt.decode_verify` implementation short-circuits and halts evaluation if a key cannot be used to verify the signature on the token. If the JWKS contains multiple keys with different signing algorithms, e.g., ES256 and RS256, then the built-in will error out if tries to verify with an ES256 signed token with the RS256 key. This depends on the order of the keys in the JWKS (if it tries the ES256 key first in this case, all is good.)

# Steps to Reproduce the Problem

  1. Create a JWKS containing two keys with different algorithms
  2. Sign a JWT with with the second key in the JWKS
  3. Call `io.jwt.decode_verify` on the token with the JWKS as the cert parameter

**Comment by patrick-east** [comment]
Example that can reproduce this: https://play.openpolicyagent.org/p/AiGN7Bhrar

The issue right now being that we don't use any of the keys contained in a jwks beyond the first one. We need to parse and try to use the others in the set.

In addition we should not raise an error for incompatible key types, it should just fail to verify if there are not any that work.
