### ISSUE TITLE
Feature Request: support bitwise operations

### ISSUE THREAD

**Issue by tahsinrahman** [open-policy-agent/opa#1919]
# Expected Behavior
At https://github.com/kubeshield/bpf-opa-demo, we're writing policy in rego that can filter linux system call data. Most of the system calls have a flag parameter. It'd be a lot easier if opa supported bitwise operations.
For example, to check `O_WRONLY` flag is set on `open` syscall, we could do the following

```
O_WRONLY := (1<<1)

is_open_write {
	(input.event.params.flags & O_WRONLY)  > 0
}
```

# Actual Behavior
Instead, we'd to do the following
```
O_WRONLY := 2

is_open_write {
	round((input.event.params.flags-0.1) / O_WRONLY) % 2 > 0
}
```

cc @tamalsaha

**Comment by tsandall** [comment]
Adding support for bitwise operations on integer numbers would be good. Since bitwise operations are not used frequently today I'd rather not overload the infix `&` and `|` operators for now. We could add bitwise functions like:

```
c := bits.or(a, b)
c := bits.and(a, b)
# etc.
```

This way your policy would read as:

```
O_WRONLY := bits.lsh(1, 1)

is_open_write {
  bits.and(input.event.params.flags, O_WRONLY) > 0
}
```
