### ISSUE TITLE
Investigate whether function overloading can support different arities

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1921]
Currently OPA does not let you overload a function with a different number of arguments. We can investigate whether function overloading with different arities could be supported. This would _should_ only require work in the type checker and evaluator. Since the function arguments are unified with the arguments at the call site, I'd expect an arity mismatch to be undefined.

**Comment by srenatus** [comment]
💭 I might be missing something, but assuming there's
```
foo(a) # arity 1
foo(a, b) # arity 2
```
How could we tell if
```
foo("x", "y")
```
is _the arity 2 variant_ **or** the arity 1 version written using `f(x, y)` to assert `y = f(x)`?

I've forgotten how we call that, but [this example should illustrate what I meant](https://play.openpolicyagent.org/p/NZtqQ7GVOT) 😅

**Comment by anderseknert** [comment]
I have a policy where this would greatly help simplify things by allowing the caller to provide optional arguments. Searched for overloading and ended up here :) Looks like you're right about that other form of return value comparison will block this though @srenatus .. I'm a bit intrigued though as to the purpose of having that? Is it even documented anywhere? 🤔  I've seen it used in internal tests but never in policies in the wild. Would love to learn more 😄

**Comment by srenatus** [comment]
I don't know the history here. To me, when I first came to rego, this `f(x, y)` style felt like it was closer to other logic programming languages -- notably prolog. Learning the details, however, I've quickly transitioned to the `y = f(x)` way of using functions 🤷

**Comment by tsandall** [comment]
Closing this issue for now--the ambiguity caused by supporting outputs in the arg list make this a problem. `print()` is special because it has no return value. If we ever completely remove support for outputs in the arg list we can revisit this.
