### ISSUE TITLE
Add method for fetching JWKs from a URL

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1925]
I would like to validate JWT tokens using a public key. The oauth server exposes the keys uses to validate the token using open id [connect discovery endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html). I would like to have a method that, given a JWKs url, will fetch the keys and cache them. Something like:
```
var provider = JWK_Provider(url: <>)
provider.getKeys(issuer)
```

**Comment by patrick-east** [comment]
Would the `http.send` built-in work for this? It looks like you basically just get some URI back and need to make a `GET` request to it to pull down the jwks(?)

Assuming we implemented the caching improvements mentioned over in https://github.com/open-policy-agent/opa/issues/1753 We may not really need a new builtin or modifications to the existing JWT ones.

**Comment by omerlh** [comment]
Yep, it might be enough to just provide those building block - but it will be nice to have a method that wraps them.

**Comment by yeungalan0** [comment]
For anyone else struggling with this I got the below rego to work with a JWKs from a URL.

`
jwks_request := http.send({"method": "GET", "url": "<JWKS_URL>"})
[valid, header, payload] := io.jwt.decode_verify(http_request.headers.authorization, {
        "cert": jwks_request.raw_body,
        "aud": "<AUD_IF_PRESENT_IN_TOKEN>"
      })

`

**Comment by patrick-east** [comment]
Looks like this is similar to #2057

**Comment by johntron** [comment]
I tried @yeungalan0's suggestion and it works; however, we can't use it in production, because the HTTP response is not cached. We would hit rate limits (20RPS) very quickly.

**Comment by tsandall** [comment]
I'm going to close this now that #1753 has been added. Users can fetch the JWKS w/ caching enabled:

```
jwks_request := http.send({"cache": true, "method": "GET", "url": "<JWKS_URL>"})
[valid, header, payload] := io.jwt.decode_verify(http_request.headers.authorization, {
        "cert": jwks_request.raw_body,
        "aud": "<AUD_IF_PRESENT_IN_TOKEN>"
      })
```
