### ISSUE TITLE
Support gRPC body in OPA Istio plugin

### ISSUE THREAD

**Issue by ledor473** [open-policy-agent/opa#1931]
# Expected Behavior
It would be very neat if the OPA Istio plugin could have a `parsed_body` for gRPC requests. 

# Actual Behavior
Currently, the OPA Istio plugin seems to only provide a `parsed_body` when the request is in JSON: https://github.com/open-policy-agent/opa-istio-plugin/blob/1c7c8bcffbb9e3d95cb4bc7524520a06af9fd869/internal/internal.go#L570-L576

# Steps to Reproduce the Problem
N/A

# Additional Info
I think it could be possible if we provide the `.proto` file ahead of time and use this library: https://godoc.org/github.com/golang/protobuf/jsonpb

**Comment by srenatus** [comment]
I think this might be quite difficult. The body of a grpc http request is protobuf encoded, and there's nothing self describing about that. Without the descriptor supplied in some way, we cannot generate a JSON representation.

There are ways to get the descriptor, via the reflection api of the downstream service, or from configuration, but they all feel quite cumbersome...

I might be missing something, and I haven't yet had a look at other external auth services, though.

**Comment by PF2000** [comment]
Hi, Is there any way to use the [transcoder](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter) to parse the body to JSON and forward it to OPA as "application/json" ?

The structure would be something like this:

```
 (...)
    - filters:
      - name: envoy.http_connection_manager
      (...)
         http_filters:
          - name: envoy.grpc_json_transcoder
         (...)
         - name: envoy.ext_authz
         (...)
```

**Comment by srenatus** [comment]
I'm afraid the grpc json transcoder works the other way: incoming json
requests are turned into grpc calls.

Envoy also has a http1.1-grpc bridge, but that one translates incoming grpc
calls into http2 calls with protobuf payloads.

So, I don't think there's anything close at hand to solve this. However, we
could perhaps have a plugin for OPA that allows you to configure the
relevant protosets, and that could be used to make the payloads available
in the right place.

**Comment by srenatus** [comment]
I could imagine two ways for proceeding here, extending the envoy plugin with some specific functionality, or creating a `pb.unmarshal` builtin via a plugin. The latter would be generic, and could be used from the envoy plugin, too. I believe it's necessary to make it a plugin, as it'll bring a few dependencies, and requires its own configuration for passing in a `proto_descriptor_bin` or `proto_descriptor_file` in the same way the envoy grpc-json transcoder does it. The unmarshal method would take in an object that contains the binary message payload to unmarshal, and either the message type, or the service method the message was provided as an argument to. 

The envoy plugin, when using that new builtin, could either call it when trying to provide the parsed body, or leave it to the author of the policy to make use of that builtin, by providing the raw request payload, suitably encoded.

Just thinking aloud here for purpose of discussion, while I'd like to see this resolved, it'll be weeks before I'd get to pick it up. WDYT?

**Comment by tsandall** [comment]
@serenatus Having some way to ingest protobuf encoded messages would be nice. The approach you laid out makes sense and seems fairly low risk because it doesn't require changes to OPA (it can be done outside for experimental purposes and once we've gained confidence we could look at upstreaming.)

If it's possible to implement inside of server handler as opposed to a built-in function, I think that would be preferable since that way the policy would not be tightly coupled to the wire format (this would make it easier to test/debug policies using standard OPA tooling.)

I have wondered in the past whether we could make this work in OPA itself. For example, if bundles could be extended to include the descriptors then in theory it could unmarshal protobuf messages before running eval. This would require some upfront design work.

**Comment by srenatus** [comment]
> If it's possible to implement inside of server handler as opposed to a built-in function, I think that would be preferable since that way the policy would not be tightly coupled to the wire format [...]

Yup, that's a good point.

> I have wondered in the past whether we could make this work in OPA itself. For example, if bundles could be extended to include the descriptors then in theory it could unmarshal protobuf messages before running eval. This would require some upfront design work.

Would you imagine this like providing support for another content-type (like application/protobuf), where the provided set of descriptors would allow the handler to translate the input before passing it on into eval? We'd need some way to convey the message type then... 🤔 (In gRPC, that's done via a header, see [PROTOCOL-HTTP2.md](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests))

**Comment by tsandall** [comment]
> Would you imagine this like providing support for another content-type (like application/protobuf), where the provided set of descriptors would allow the handler to translate the input before passing it on into eval? We'd need some way to convey the message type then... 🤔 (In gRPC, that's done via a header, see PROTOCOL-HTTP2.md)

Yes, exactly. If PB encoded messages do not even have a type hint that indicates the message type/class then it would have to be sent out-of-band. Without having given it too much thought, what I'd like to see is `opa build` extended to accept a set of proto descriptors so they could be easily packaged into the bundle and distributed with the rest of the policy and data. When OPA activates the bundle, the server handler would have everything it needs to deserialize incoming PB messages assuming they contain enough type info (in the message or out-of-band). Perhaps the server would be gRPC-based; I'm not sure.

> PBs can be made self-describing, too, but I don't think this is used much...

My conclusion was the same; self-describing PBs are not widely used and the client libraries don't support it (e.g,. last time I looked, the golang package didn't support them.)

**Comment by srenatus** [comment]
> If PB encoded messages do not even have a type hint that indicates the message type/class then it would have to be sent out-of-band.

I keep forgetting about `google.protobuf.Any`. It's the PB way of giving the type in-band, by enveloping the serialized message with a type field. To unmarshal the message in the receiving end (see [Any.UnmarshalNew](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/known/anypb#Any.UnmarshalNew)), it needs to know the descriptors through some other means. (The self-describing message is merely the one step further, it sends the descriptors along with the Any.)

Taking a step back, I wonder if it's even worth having OPA know the descriptors: If we end up passing the message into eval as JSON (converted into ast), we don't need more than its JSON representation, and that's cheap to get in the caller. (Using `jsonpb` or `protojson`, depending on the version of the protobuf lib used.) It could be sent to OPA like any other request; or OPA could expose a gRPC endpoint which takes in a [`structpb`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/known/structpb) the JSON equivalent in PB-land.

We'd lose some information, like, the names of all the enums (which are not set), but we wouldn't have much use of those in the rego policy either, I believe.

This hints at another thing to decide: there's multiple  variants of encoding PB in JSON, and we'd have to settle on one, I suppose (or make it configurable). The usual knobs are [these](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/encoding/protojson#MarshalOptions), basically:
- render default field values
- enums as text or numbers
- lowerCamelCase or lower_camel_case for field names

(Whatever is picked determines on how the message looks in rego.)

**Comment by srenatus** [comment]
For illustrative purposes, I've played a bit with self-describing messages: [generating one here](https://github.com/srenatus/pbcat/blob/c187b29029520b1081968c17738f74daff76ba35/generate/generate.go), and reading it back [there](https://github.com/srenatus/pbcat/blob/c187b29029520b1081968c17738f74daff76ba35/main.go).

**Comment by srenatus** [comment]
A code snippet (Apache 2.0 licensed if anyone cares) illustrating the last point: json-encoding a PB message is simple at the call site (here, in an UnaryServerInterceptor)

```go
package opa

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type OPA struct {
	client *http.Client
	server *url.URL
}

type authorizationRequest struct {
	Input input `json:"input"`
}

type input struct {
	Metadata metadata.MD           `json:"metadata"`
	Message  *json.RawMessage      `json:"message"`
	Type     protoreflect.FullName `json:"type"`
}

type authorizationResponse struct {
	Result map[string]interface{} `json:"result"`
}

func New(server *url.URL, client *http.Client) (*OPA, error) {
	if client == nil {
		client = http.DefaultClient
	}
	return &OPA{server: server, client: client}, nil
}

func (o *OPA) authorizeWithMetadata(ctx context.Context, m protoreflect.ProtoMessage) (bool, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return false, fmt.Errorf("no incoming metadata found")
	}

	msgJSON, err := protojson.Marshal(m)
	if err != nil {
		return false, err
	}

	msgRaw := json.RawMessage(msgJSON)
	body := bytes.Buffer{}
	err = json.NewEncoder(&body).Encode(&authorizationRequest{
		Input: input{Metadata: md, Message: &msgRaw, Type: m.ProtoReflect().Descriptor().FullName()}})
	if err != nil {
		return false, err
	}

	req, err := http.NewRequestWithContext(ctx, "POST", o.server.String(), &body)
	if err != nil {
		return false, err
	}
	req.Header.Set("content-type", "application/json")

	resp, err := o.client.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close() // nolint: errcheck
	if resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("unexpected status code %d", resp.StatusCode)
	}

	authzResp := authorizationResponse{}
	err = json.NewDecoder(resp.Body).Decode(&authzResp)
	if err != nil {
		return false, err
	}

	authorized, ok := authzResp.Result["authorized"].(bool)
	if !ok {
		return false, fmt.Errorf("unexpected response %v", authzResp.Result)
	}
	return authorized, nil
}

func (o *OPA) UnaryServerInterceptor() grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		if m, ok := req.(protoreflect.ProtoMessage); ok {
			msg, authorized, err := o.authorizeWithMetadata(ctx, m)
			if err != nil {
				return nil, status.Error(codes.PermissionDenied, err.Error())
			}
			if !authorized {
				return nil, status.Error(codes.PermissionDenied, "permission denied")
			}
			return handler(ctx, req)
		}
		return nil, status.Error(codes.Internal, "cast to proto message failed")
	}
}
```

Another thing I keep forgetting: gRPC is _encoding-agnostic_. But I think that's true in theory more than practice, I suppose we would get by for quite a while if we assume gRPC is using PB.

**Comment by srenatus** [comment]
ℹ️ There's work underway for what hopefully covers the base case here: _unary, non-compressed, using protobuf encoding_ -- https://github.com/open-policy-agent/opa-envoy-plugin/pull/202

**Comment by srenatus** [comment]
I'm closing this as the basics are available with https://github.com/open-policy-agent/opa-envoy-plugin/pull/202. Please give it a try and let us know how it works, and what you still need supported! 😃
