### ISSUE TITLE
Simple loading of data from custom paths does not seem to work

### ISSUE THREAD

**Issue by ahmedtalhakhan** [open-policy-agent/opa#1938]
I am trying to play around with OPA and trying to evaluate if the data loading/policy evaluations can be done easily for multiple customers/tenants inside the same instance of OPA. For that I am trying to load data and policies into custom paths. For the sake of simplicity, here is the sample policy and its associated data

Policy in file new_example.rego
```
package myapi.policy
import input
import data.tenant_1.myapi.acl
default allow = false

allow {
        access = acl[input.user]
        access[_] == input.access
}
```

Data saved in file acl.json
```
{"alice": ["read","write"], "bob": ["read"]}

```

# Steps to Reproduce the Problem

  1. opa run -l debug -s
  2. Load policy: `curl -X PUT http://localhost:8181/v1/policies/tenant_1/myapi --data-binary @myapi/new_example.rego`
  3. Load Data: `curl -X PUT http://localhost:8181/v1/data/tenant_1/myapi/acl --data-binary @myapi/acl.json`
  4. Check if both policy and data reside at the right paths and return correct results: `http://localhost:8181/v1/data/tenant_1/myapi/acl`
`http://localhost:8181/v1/policies/tenant_1/myapi/`
  5. Now try to evaluate the policy: `curl -X POST http://localhost:8181/v1/data/tenant_1/myapi/policy/allow --data-binary '{ "input": { "user": "alice", "access": "write"} }'`
   

      

# Expected Behavior
{"result":true}

# Actual Behavior
{}

# Additional Info
The following query however returns the correct results
`curl -X POST http://localhost:8181/v1/data/myapi/policy/allow --data-binary '{ "input": { "user": "alice", "access": "write"} }'`

Notice that I took out the `tenant_1` from the URL. This is completely unexpected and I am not able to understand why this works whereas the the URL that should work with `tenant_1` does not work.

Any help would be appreciated.

**Comment by patrick-east** [comment]
Hi!

Check out https://www.openpolicyagent.org/docs/latest/rest-api/#policy-api in particular this comment:

> The identifiers given to policy modules are only used for management purposes. They are not used outside of the Policy API.

I think the confusion is from the REST API policy ID versus the Rego `package` path. When you do the `PUT` to `/v1/policies/path/to/policy` that `path/to/policy` becomes the ID for the policy (if loaded locally it would be the file path on the system, or the path inside a bundle, etc). This is _not_ the location in the `data` document at evaluation time where it is located. For Rego modules it is 100% up to the `package` specifier. In this case it is at `myapi.policy`. More info: https://www.openpolicyagent.org/docs/latest/policy-language/#packages

If you change the policy to something like:
```
package tenant_1.myapi.policy
import data.tenant_1.myapi.acl
default allow = false

allow {
        access = acl[input.user]
        access[_] == input.access
}
```
You should see the expected result for `curl -X POST http://localhost:8181/v1/data/tenant_1/myapi/policy/allow --data-binary '{ "input": { "user": "alice", "access": "write"} }'`

**Comment by ahmedtalhakhan** [comment]
Thanks @patrick-east for this.

Does this mean there is no simple to create a single policy file and then upload different `data` sets for different paths/customer/tenants and then evaluate for each. eg Have multiple files uploaded for different paths/customer/tenants

```
curl -X PUT http://localhost:8181/v1/data/tenant_1/myapi/acl --data-binary @myapi/acl_1.json
curl -X PUT http://localhost:8181/v1/data/tenant_2/myapi/acl --data-binary @myapi/acl_2.json
curl -X PUT http://localhost:8181/v1/data/tenant_3/myapi/acl --data-binary @myapi/acl_3.json

```

And then evaluate
```
http://localhost:8181/v1/data/tenant_1/myapi/policy/allow --data-binary '{ "input": { "user": "alice", "access": "write"} }'
http://localhost:8181/v1/data/tenant_2/myapi/policy/allow --data-binary '{ "input": { "user": "bob", "access": "write"} }'
http://localhost:8181/v1/data/tenant_3/myapi/policy/allow --data-binary '{ "input": { "user": "joe", 
"access": "write"} }'
```

Is the only solution to change the policy file every time for each such evaluation?

**Comment by patrick-east** [comment]
Ah ok, as-is you hard code the tenant data path into the policy so I assumed that it already was 1 rego package per tenant.

You can totally do something like that, but you're going to need to structure the data model a little bit differently. For example, if you could supply the tenant id in the input your policy could be something like https://play.openpolicyagent.org/p/SK6KiFEqQw

The difference being that you dynamically look up the acl's based on the input so that the data model is the only place you need to track those. The policy itself can be shared for each.

**Comment by ahmedtalhakhan** [comment]
Ah! Cool. The main piece that I was missing was the fact that you could index into the imported data. So for completeness of this to help anyone looking at this in future,  I was simply able to do
```
package myapi.policy

import input
import data.acls
default allow = false

allow {
        access = acls[input.tid][input.user]
        access[_] == input.access
}
```

And then load different `data` using
```
curl -X PUT http://localhost:8181/v1/data/acls/1 --data-binary @myapi/acl_1.json
curl -X PUT http://localhost:8181/v1/data/acls/2 --data-binary @myapi/acl_2.json
``` 

And then finally query by passing the `tid` in the `input`

**Comment by patrick-east** [comment]
> I must say that documentation pages could use some help in terms of clarifying the core concepts. This is especially true for the rego golang package documentation.

Yea.. they are improving over time but I'm sure still have some rough edges.

If there are any specific suggestions/points feel free to open issues for them or, if you have time for it, go ahead and make changes. Contributions are always welcome 😄

**Comment by ahmedtalhakhan** [comment]
I will try to take out some time to do it.
