### ISSUE TITLE
Does opa-istio-plugin support "permissive mode"?

### ISSUE THREAD

**Issue by siucng2222-c** [open-policy-agent/opa#1943]
# Expected Behavior
If "permissive mode" is available, expect that rules will still be evaluated and decisions will still be made and logged in the decision logs, but it will still permit access to corresponding resource. This will work like permissive mode in Istio policies, which is helpful on debugging and verifying on how my rego behaves before actually enabling it in Prod

# Actual Behavior
N/A

# Steps to Reproduce the Problem
N/A

# Additional Info
N/A

**Comment by ashutosh-narkar** [comment]
@siucng2222-c the opa-istio plugin does support a `dry-run` feature that would unconditionally allow requests but also would log the decisions.

**Comment by siucng2222-c** [comment]
@ashutosh-narkar Could you please advice how to enable dry-run mode for the plugin?

**Comment by ashutosh-narkar** [comment]
See [this](https://github.com/open-policy-agent/opa-istio-plugin/#example-bundle-configuration) sample config. Set `dry-run` to  `true`.

**Comment by siucng2222-c** [comment]
it works! Thanks a lot
