### ISSUE TITLE
Expose topdown built-in functions for Go wasm runtime integration

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1951]
In some library embedding cases, it could advantageous to replace the OPA interpreter (implemented inside the topdown package) with a Go wasm runtime. For example, it's not currently possible to set an upper limit on the OPA interpreter's memory usage (with a Go wasm runtime this would be fairly easily.) Similarly, Go projects that currently rely on webhooks for extension (e.g., the k8s apiserver) could be extended to support wasm runtimes. This removes the need for out-of-process calls that can fail.

As of v0.15.1 the wasm compiler in OPA supports the entire Rego language. The main thing that's missing is support for the Rego built-in functions that are today implemented inside the OPA interpreter in Go.

If we wanted to target Go wasm runtimes we could expose the built-in functions that are already implemented in Go inside the OPA interpreter (they're found in the `topdown` package today.) To avoid introducing a whole set of new exported functions, I'd prefer to expose a simple dynamic dispatch method (e.g., `InvokeBuiltin(name, operands) (result, error)`). Built-ins are statically registered here: https://github.com/open-policy-agent/opa/blob/master/topdown/builtins.go#L80.

If we had the built-in functions exposed like this and picked a suitable Go wasm runtime, we could demonstrate complete support for Rego and all built-in functions in Go relatively quickly.

**Comment by tsandall** [comment]
cc @waynr

**Comment by waynr** [comment]
Hey @tsandall I'm not gonna be able to make it to the meeting today, but wanted to let you know this is still on my radar; work and then holiday travel has been throwing me off my game focus-wise but I'm hoping to settle down into a routine that lets me take this on in the near future.

**Comment by koponen-styra** [comment]
This is done. The golang wasm SDK uses topdown.GetBuiltin for this exact purpose.

**Comment by tsandall** [comment]
Fixed by #2120.

**Comment by tsandall** [comment]
@waynr if you (or anyone else!) is looking you can find the golang-opa-wasm SDK here: https://github.com/open-policy-agent/golang-opa-wasm
