### ISSUE TITLE
Decision log was not showing for some cases

### ISSUE THREAD

**Issue by siucng2222-c** [open-policy-agent/opa#1953]
# Expected Behavior
I have opa-istio-plugin deployed with decision log and debug log enabled. A policy is defined to extract JWT token from header and perform authz against attributes from payload. When I test with one of the JWT token, I can see the policy work as expected, and the logs from opa-istio container within my app pod was able to show a transaction log followed by 2 rows of decision logs. 

# Actual Behavior
However for some cases (e.g. when I test with another JWT tokens), only a row of transaction log was shown, no decision logs corresponding to that transaction was found, and the plugin returns 403 forbidden. I verified my JWT token is valid and suppose the result should be "allowed" according to my policy definitions. I want to debug the decision but without the decision log in that fail case I'm lagging the information to drill down. Also there was no other error logs found. 

# Steps to Reproduce the Problem
N/A

# Additional Info
Below shared my opa plugin config and policy definition. 
https://gist.github.com/siucng2222-c/435baf25a160bcd07b0ace65f47f59ea

**Comment by siucng2222-c** [comment]
It seems like if I passed an empty or incorrect Authorization Bearer token in HTTP header, only the transaction log will be shown, and no decision log will appear, and the opa istio plugin will always return HTTP 403... I wonder if there could be more specific error messages can be generated in the debug log or decision log. It will be especially helpful if the logs can pin point which part of the rego code triggered an error or a "false" decision, like a stacktrace in Java

**Comment by ashutosh-narkar** [comment]
PR: https://github.com/open-policy-agent/opa-istio-plugin/pull/152

**Comment by ashutosh-narkar** [comment]
@siucng2222-c  decision logs should now be generated for all scenarios.
