### ISSUE TITLE
How to deny view/get operation in openshift?

### ISSUE THREAD

**Issue by lambotchi** [open-policy-agent/opa#1959]
# Expected Behavior
Block viewing/describing of secrets

# Actual Behavior
Show tokens

# Steps to Reproduce the Problem

  1. oc create cm t1 --from-file=test.rego -n opa
  2. test.rego
```
import data.k8s.matches

# Deny all user except osadmin
deny[query] {
    matches[[kind, namespace, name, resource]]

    not "osadmin" == resource.userInfo.username

    msg := sprintf("Custom Unauthorized user: %v", [resource.userInfo.username])

    query = {
        "id": "sa-unauthorized-namespace-scoped",
        "resource": {
            "kind": kind,
            "namespace": namespace,
            "name": name
        },
        "resolution": {
            "message": msg
        },
    }
}
```

# Additional Info

minishift 1.24
openshift v3.9.0+2e78773-56
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

**resource** object

_{\"kind\": {\"group\": \"\", \"kind\": \"Secret\", \"version\": \"v1\"}, \"name\": \"s5-token-n6v6q\", \"namespace\": \"demo\", \"operation\": \"DELETE\", \"resource\": {\"group\": \"\", \"resource\": \"secrets\", \"version\": \"v1\"}, \"uid\": \"748cdab2-1c1d-11ea-8b11-080027f8814d\", \"userInfo\": {\"groups\": [\"system:cluster-admins\", \"system:masters\", \"system:authenticated\"], \"username\": \"system:admin\"}_

**Comment by patrick-east** [comment]
As mentioned over in https://github.com/kubernetes/kubernetes/issues/85991#issuecomment-564363695 the OPA admission controller integration will not be able to block view/get requests for API objects. 

In theory you could maybe wire up OPA as an authorization webhook https://kubernetes.io/docs/reference/access-authn-authz/webhook/ and use a policy like this. But there isn't a pre-made integration for doing so.
