### ISSUE TITLE
fatal error: concurrent map writes 

### ISSUE THREAD

**Issue by yuvalamar** [open-policy-agent/opa#1962]
# Expected Behavior
Opa should not panic and exit

# Actual Behavior
panic

# Steps to Reproduce the Problem
I think the bug is found in :
`func (m *Manager) Client(name string) rest.Client {
	return m.services[name]
}`

I added the full log with panic stack
we had 19 OPA restarts in production in the last 24 hours

[panic.log](https://github.com/open-policy-agent/opa/files/3973220/panic.log)

# Additional Info
opa version 15.0

**Comment by patrick-east** [comment]
Can you share more details about the OPA configuration and logs leading up to the panic? I only see the stack trace log.

**Comment by yuvalamar** [comment]
This happens during everyday operation, but I think it relates to Status API with multiple bundles.
(https://www.openpolicyagent.org/docs/latest/management/#status) we enabled it and the panic was shown in our logs

**Comment by patrick-east** [comment]
#1991 makes some speculative changes (at least fixing _some_ issue).

@yuvalamar any chance you can try that change out? I haven't been able to repo the issue on my environments.

**Comment by patrick-east** [comment]
Re-opening until we get some verification that #1991 fixes it

**Comment by patrick-east** [comment]
Was able to reproduce this by using ~1000 bundles (each with their own unique service) and updating the discovery config to remove bundles (dropped it to ~980). 

The trick appeared to be having enough bundles and updating them at a high enough frequency that there was constantly a status update message being sent, this pretty much guaranteed that the reconfiguration that happened when discovery updates would modify the status map while the status plugin was trying to read it.

With the build including the changes from #1991 it was no longer reproducing.
