### ISSUE TITLE
Allow CA file to be specified for bundle download TLS

### ISSUE THREAD

**Issue by msklosak** [open-policy-agent/opa#1968]
# Expected Behavior
There should be a configuration option to specify a CA file to be used in the TLS configuration for bundle downloads.

Additionally, a separate (optional) configuration option can be created to determine whether or not to bundle the system certificate pool with the desired CA file.

Example:
`with_system_ca: false`:
```
ca, err := x509.NewCertPool()
ca.AppendCertsFromPEM(...caFileBytes...)
```

`with_system_ca: true`:
```
ca, err := x509.SystemCertPool()
ca.AppendCertsFromPEM(...caFileBytes...)
```

# Actual Behavior
You cannot specify a CA file to be used in the TLS configuration for bundle downloads, only the certificate file, key file, and (optional) key file passphrase.

# Steps to Reproduce the Problem

  1. As per the [documentation](https://www.openpolicyagent.org/docs/latest/configuration/#client-tls-certificate), there is no way to specify a CA file to use in the TLS configuration for bundle downloads.

# Additional Info

Because we cannot specify a CA file, we have to use `allow_insecure_tls: true` which is not ideal.

**Comment by patrick-east** [comment]
> Because we cannot specify a CA file, we have to use allow_insecure_tls: true which is not ideal.

For a temporary work-around can you just install the CA into the host system (or into the container image)?

**Comment by tsandall** [comment]
@msklosak is this still required?

**Comment by clarshad** [comment]
@tsandall I am interested in working on this issue.
Wanted to verify the expected behaviour - We currently have `cert` , `private_key` and `private_key_passphrase` fields for TLS authentication. We need to add two more optional fields `ca_cert` - for root CA and `ca_cert_with_system_ca` - boolean to check if system certificate to be appended with root CA
Please confirm if I could start working on this

**Comment by clarshad** [comment]
Will go ahead and start working on this for now, however please do let me know if this is no longer needed
