### ISSUE TITLE
Formal verification?

### ISSUE THREAD

**Issue by DragD** [open-policy-agent/opa#1974]
Is OPA formally verified?

**Comment by tsandall** [comment]
@DragD can you be a bit more specific? The answer is probably "no" but it would be useful to know what you have in mind.

**Comment by DragD** [comment]
As OPA role might be critical, I wonder if there is plan to formally specify and/or verify OPA in [this sense](https://www.wikiwand.com/en/Formal_verification). [This article](https://www.hillelwayne.com/post/why-dont-people-use-formal-methods/) gets deeper into the subject.

**Comment by tsandall** [comment]
We don't have any plans to work on different kinds of formal verification at this point in time. There was some discussion within the Kubernetes Policy WG and SIG-Security about this. You can find more on that discussion [here](https://github.com/cncf/sig-security/blob/105a5dd9fccdbcf23fb726276d6bb21054daa0c5/policy/overview-policy-formal-verification.md).
