### ISSUE TITLE
Add support for authenticating clients via SO_PEERCRED

### ISSUE THREAD

**Issue by kfox1111** [open-policy-agent/opa#1975]
It would be great if the authz.rego module could use unix socket peercred info for determining access. An example use case, root can upload new policy, non root cant.

This can be accomplished like:
https://blog.jbowen.dev/2019/09/using-so_peercred-in-go/

For the use case, that should be enough as uid 0 can be passed as identity.uid and authz check can be
```
allow {
 identity.uid == 0
}
```

Additionally, more identity info can be derived from the uid like:
```
identity.user = LookupId(identity.uid) #https://golang.org/pkg/os/user/#LookupId
identity.groups = GroupIds(identity.uid) #https://golang.org/pkg/os/user/#GroupIds
```

Then policy could be done like:
```
#Either root or wheel members can access
allow {
  identity.groups[_] == 'wheel'
}

allow {
  identity.user == "root"
}
```

**Comment by tsandall** [comment]
Thanks for filing this @kfox1111. I'm not sure where (exactly) all of the changes would need to be made to support this. Currently we have two kinds of "identifiers" that know how to extract client credentials from incoming requests (bearer and client TLS). Those are found [here](https://github.com/open-policy-agent/opa/tree/master/server/identifier). In this case, we might need some extra code to configure the connection correctly. That could may need to live alongside the unix domain socket creation [here](https://github.com/open-policy-agent/opa/blob/9ba923d5854baadb4dd69301758f6e4f9f4b9ecd/server/server.go#L510).

**Comment by kfox1111** [comment]
+1. I looked for a bit and couldn't trace it all to find the right place for it before running out of time. For now, the unix socket support in pam_opa has alleviated the immediate need. But it would still be useful to have.

**Comment by srenatus** [comment]
I'll close this issue for cleanup 🧹 If you read this because you're looking for this feature, please ping us! 🛎️
