### ISSUE TITLE
"opa eval" is slow

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#1978]
# Expected Behavior
for a simple "is this item in that hash" test I'd expect sub 1ms execution time

# Actual Behavior
10ms/test

# Steps to Reproduce the Problem

`opa test foo.rego` .. see https://gist.github.com/grosser/5286168e3d009e16494555fa1d2e13b0

# Additional Info
```
opa version
Version: 0.16.0
Build Commit: b50e6266
Build Timestamp: 2019-12-19T13:13:07Z
Build Hostname: ea6c209497f1
```

**Comment by patrick-east** [comment]
Can you share results of running the tests on your machine and more info about the environment? I'm seeing pretty reasonable timing on my local macbook with that linked gist:

```
{9:44} /tmp ❯ opa test -v ./slow.rego
data.k8srequiredlabels.test_allowed0: PASS (501.621µs)
data.k8srequiredlabels.test_allowed1: PASS (290.191µs)
data.k8srequiredlabels.test_allowed2: PASS (290.793µs)
data.k8srequiredlabels.test_allowed3: PASS (314.717µs)
data.k8srequiredlabels.test_allowed4: PASS (287.37µs)
data.k8srequiredlabels.test_allowed5: PASS (294.357µs)
data.k8srequiredlabels.test_allowed6: PASS (273.866µs)
data.k8srequiredlabels.test_allowed7: PASS (278.84µs)
data.k8srequiredlabels.test_allowed8: PASS (286.645µs)
data.k8srequiredlabels.test_allowed9: PASS (371.3µs)
--------------------------------------------------------------------------------
PASS: 10/10
```

There is also some interesting accounting for the test timing versus actual evaluation, it would be good to validate if those 10ms times you see are from evaluation time or with the test framework. For example, using one of the tests that was ~500 microseconds:

```
{9:46} /tmp ❯ opa eval -d ./slow.rego --metrics -f pretty 'data.k8srequiredlabels.test_allowed0'
true
+------------------------------+----------+
|            METRIC            |  VALUE   |
+------------------------------+----------+
| timer_rego_load_files_ns     | 59446197 |
| timer_rego_module_compile_ns | 3733991  |
| timer_rego_module_parse_ns   | 59346423 |
| timer_rego_query_compile_ns  | 53297    |
| timer_rego_query_eval_ns     | 79470    |
| timer_rego_query_parse_ns    | 182240   |
+------------------------------+----------+
```

So only ~80 microseconds of actual eval time for it (by far the majority of the time is spent loading everything and getting ready to evaluate)

**Comment by grosser** [comment]
```
time opa test -v slow.rego
```
is slow though ... seems to be the loading of the file ... maybe the parser or so ...
I tried making many small files / 1 big file but the time comes out the same

**Comment by patrick-east** [comment]
Yea, which seems about right. Check out the metrics from doing the `opa eval ..` command like what I ran above.

The test runner will roughly include the same amount for each `opa test ..` invocation for the module parse+compile, and then for each test it runs you'll have the query parse+compile and then eval cost. Add in a little extra time for processing the results and output formatting. The bulk of it though is, currently, spent loading stuff.

I guess maybe to circle back to the root of this issue.. the title for this is `"opa test" is very slow` and based on your last comment you're saying you expect a <1ms real time for CLI invocation of opa test per test case.. but I'm not sure what basis that is on or what the requirement is. Are you running into issues with tests taking too long? Scaling problems? I ask because I think generally speaking the timing overhead for this isn't typically a priority. Usually the focus is on evaluation time (which, in this case, is pretty fast). If there is a use-case or some specific issue though that might help guide the discussion.

**Comment by grosser** [comment]
My usecase is that I have ~40k kubernetes objects as json that I'd like to run against 5 rules ... I already parallelized it, but it's just kinda slow :)
... I suspect most time is spent in parsing the big json blogs, so if there is a way to load them from a file or generate them in a more native format that loads faster, that would help a lot

**Comment by patrick-east** [comment]
> My usecase is that I have ~40k kubernetes objects as json that I'd like to run against 5 rules

Perfect! Thats the kind of context I hoping to get 😄

To make sure I'm understanding how you are doing that today,  I'm guessing that each test case is generated for the objects using `with input as ..` kind of things like in those test cases in the gist?

One thing to check is whether or not loading the objects in as json files and referencing them in the test cases helps out. It might be that loading them and parsing as json, and internally having them pushed into the store versus having them parsed as part of the Rego might help lower some of the overhead.

To test that theory I modified the examples in the gist to do that, so each rule is like:

```rego
test_allowed0 {
  item := data.test_resources[0]
  count(violation) == 0 with input as {"review":{"object":item},"parameters":parameters}
}
```

And the data file structured something like:
```json
{
    "test_resources": [
        {"metadata":{"annotations":{"deployment.kubernetes.io/revision":"93","samson/deploy_url":"https://samson.zende.sk/projects/zendesk_ars/deploys/892794"},"creationTimestamp":"2019-11-08T20:42:03Z","generation":93,"labels":{"project":"auto-remediation-service","role":"worker","team":"znoc"},"name":"ars-workers","namespace":"auto-remediation-service","resourceVersion":"53751118","selfLink":"/apis/apps/v1/namespaces/auto-remediation-service/deployments/ars-workers","uid":"38b66766-0268-11ea-8b52-0a7a529b5bd5"}},
        ...
    ]
}
```
(note: I didn't really put much thought into the structure of this, just dumped them into the file.. in theory this could be a bunch of separate files too)

Then run the tests with something like `time opa test -v ./slow.rego ./slow.json`

Doing this dropped the real time for the `opa test` by roughly half on my machine. It went from about 0.085s to 0.045s.

Looking at the `opa eval ..` for the new version:
```
{19:39} /t/slow ❯ opa eval -d ./slow.rego -d ./slow.json --metrics -f pretty 'data.k8srequiredlabels.test_allowed0'
true
+------------------------------+----------+
|            METRIC            |  VALUE   |
+------------------------------+----------+
| timer_rego_data_parse_ns     | 116208   |
| timer_rego_load_files_ns     | 17814427 |
| timer_rego_module_compile_ns | 3370475  |
| timer_rego_module_parse_ns   | 17247561 |
| timer_rego_query_compile_ns  | 62296    |
| timer_rego_query_eval_ns     | 88667    |
| timer_rego_query_parse_ns    | 205030   |
+------------------------------+----------+
```
The one I posted earlier had a `timer_rego_module_compile_ns` of almost 60ms and is down to like 17. So thats nice... We did introduce some more time in `timer_rego_data_parse_ns` but nowhere near the amount that changed in the module parse. This is roughly just the time it takes to parse json in golang compared to the Rego parser.

I think barring a new parser for Rego (not as crazy as it sounds, @tsandall was playing around with that) this kind of approach to load all that data is probably going to work best.

If we then want to do more parallelization there are a few options.. easiest is probably to split up the data files and load+test them independently. The main downside is that if you end up with a lot of rego policies (not just the mock data) each of those processes handling some shard of the data file(s) would have to parse+compile it. 

Ratcheting things up a little more.. to get the most optimal performance, in theory, you could use the OPA golang API and write a helper tool that prepares a Rego object with the modules and then can re-use that in parallel with any number of threads loading the json as actual input documents (so you can avoid using the `with input as blah` stuff) All-in-all its probably not too much code.

Another thing, which I'm not sure if we have looked into/discussed much, is whether or not `opa test` can or should have a parallel evaluation mode. A quick look at the code and it seems like it could theoretically evaluate each test case separately and it would then only do the setup a single time (similar to the suggested optimal workflow.. with a few extra things). Although we'd need to look into it more to see how feasible that is... might not be a viable option.

Hopefully something in all that is useful. I'd be curious to know how much of a difference just moving the objects out into json files helps.

**Comment by grosser** [comment]
that works nicely!
