### ISSUE TITLE
V1 Data API is confusing when input isn't wrapped in an input field

### ISSUE THREAD

**Issue by jjshanks** [open-policy-agent/opa#1993]
# Expected Behavior
Both or either:

1. `openpolicyagent.org/decision_logs` explicitly showing no input was received
1. 400 error code  

# Actual Behavior

Decision logs just omits the `input` field in the logs and a 200 is returned

# Steps to Reproduce the Problem
bug.rego
```
package bug.repo

default allow = false

allow = true {
    count(violation) == 0
}

violation["yes"] {
    input.foo = "bar"
}
```

bad-input.json
```
{"foo":"bar"}
```

good-input.json
```
{"input":{"foo":"bar"}}
```

  1. `docker run -d --rm --name opa-bug-repo -p 8181:8181 openpolicyagent/opa:0.16.0 run --server --log-level debug --log-format=json-pretty --set=decision_logs.console=true`
  1. `curl -X PUT --data-binary @bug.rego localhost:8181/v1/policies/bugrepo`
  2. `curl localhost:8181/v1/data/bug/repo/allow -s -d @bad-input.json -H 'Content-Type: application/json' | jq .result`
  3. result will be true

`good-input.json` returns false which is expected

# Additional Info
I was able to quickly get help on the slack channel but this was confusing and unexpected when switching from testing with the CLI to testing with a server.

**Comment by tsandall** [comment]
OPA (perhaps wrongly) adheres to Postels Law and doesn't complain if you send extra attributes in the API requests. I'm wary about changing the existing APIs to reply with 400 since that could break users. An alternative would be to include a list of unsupported fields in the answer.  For example:

```json
{
  "result": false,
  "unsupported_parameters": ["foo"]
}
```

This would at least tell someone who's looking that there was a problem. Including that field in the decision log would be a relatively simple addition.

**Comment by ashutosh-narkar** [comment]
We could also consider making the `unsupported_parameters` field more descriptive by including text that mentions the parameters OPA expects eg `input`.

**Comment by jjshanks** [comment]
@tsandall Since I think this would mostly be for newer users to avoid confusion the simplest approach would be to denote that the input field was omitted in the decision log. I think some people wouldn't want to increase the payload size for the common case.

I can work on this.

**Comment by anderseknert** [comment]
This was solved some time ago, and the OPA server will now return a warning in the result if the `input` attribute is ommited:

```
$ curl -d '{"foo": "bar"}' localhost:8181/v1/data
{"result":{},"warning":{"code":"api_usage_warning","message":"'input' key missing from the request"}}
```

Closing as resolved.
