### ISSUE TITLE
Feature: A way to open docs samples in playground

### ISSUE THREAD

**Issue by lawrencegripper** [open-policy-agent/opa#1995]
# Expected Behavior

I'm brand new to rego and trying to wrap my mind around things. This doc is an awesome starting place and the editable samples are super useful. 

https://www.openpolicyagent.org/docs/latest/#overview

I also love the playground 

https://play.openpolicyagent.org/

One thing that I really long for is the ability to pop open the document samples in the playground so I can see the `input`, `rego` and `output` all next to each other easily as I struggle to hold all three in my head while working through the samples and end up scrolling up and down the page a ton. 

# Actual Behavior

No easy button (sorry if I've missed it) to open samples in [The Rego Playground](https://play.openpolicyagent.org/)

**Comment by srenatus** [comment]
Slightly related -- hacked something up some time ago to get "Open in playground" links here: https://github.com/srenatus/99-rego-problems/tree/master/1_lists/01_last

👍 It would be great if there was a simpler, supported way to achieve this 😄

**Comment by lawrencegripper** [comment]
I think this was me being an idiot, related to #1996, I didn't realize that the playground can only run `rego` which contains rules and noticed that examples lower down in the doc did have an "Open in playground" button.

**Comment by tsandall** [comment]
There is a button but it's super small and non-obvious. If someone has the web design/dev skills to fix that, it would be welcome.
