### ISSUE TITLE
gosec issues

### ISSUE THREAD

**Issue by prabhu** [open-policy-agent/opa#2001]
# Expected Behavior
Security issues identified and addressed

# Actual Behavior
A gosec scan of this repo has identified a number of medium issues. The report can be viewed here

https://github.com/prabhu/opa/commit/8630c3688f65a7620d894854918f1b19a39280dc/checks?check_suite_id=399791160#step:4:387

To view the report, download the sast-scan-reports from artifacts and use any sarif viewer such as http://sarifviewer.azurewebsites.net/

# Steps to Reproduce the Problem

  1. Run [sast-scan](https://github.com/AppThreat/sast-scan) against this repo. The Easiest way is to use the GitHub action workflow as [shown](https://github.com/prabhu/opa/blob/master/.github/workflows/sastscan.yml) in my fork. Happy to send a PR if you are interested.
  2.
  3.

# Additional Info

**Comment by tsandall** [comment]
@prabhu could you post a plaintext report on this issue? I don't want to have to install thirdparty software to view the report. If the scan results represent meaningful, actionable issues we can file separate issues to resolve them.

**Comment by prabhu** [comment]
[golang-report.sarif.txt](https://github.com/open-policy-agent/opa/files/4065610/golang-report.sarif.txt)

Rename and remove .txt to use online viewer. Or open with a text editor since .sarif is json format.

**Comment by tsandall** [comment]
These are the warnings from the report:

```json
[
  "https://github.com/open-policy-agent/opa/blob/master/loader/loader.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/plugins/rest/aws.go: Potential HTTP request made with variable url.",
  "https://github.com/open-policy-agent/opa/blob/master/bundle/file.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/ast/parser.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go: Use of weak cryptographic primitive.",
  "https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go: Blacklisted import crypto/sha1: weak cryptographic primitive.",
  "https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go: Blacklisted import crypto/md5: weak cryptographic primitive.",
  "https://github.com/open-policy-agent/opa/blob/master/test/wasm/cmd/wasm-rego-testgen/main.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/test/wasm/cmd/wasm-rego-testgen/main.go: Expect directory permissions to be 0750 or less.",
  "https://github.com/open-policy-agent/opa/blob/master/util/test/tempfs.go: Expect directory permissions to be 0750 or less.",
  "https://github.com/open-policy-agent/opa/blob/master/cmd/run.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/cmd/fmt.go: Subprocess launched with function call as argument or cmd arguments.",
  "https://github.com/open-policy-agent/opa/blob/master/cmd/fmt.go: Potential file inclusion via variable.",
  "https://github.com/open-policy-agent/opa/blob/master/cmd/eval.go: Potential file inclusion via variable."
]
```

Summary:

1. File I/O operations using variables. These are non-issues (I think).
2. HTTP request constructed using variables. This is a non-issue.
3. Weak cryptographic function being used. These are hash functions that users request/need. OPA doesn't use these internally.
4. Weak permissions on mkdir call (755 instead of 750) - this is a program that generates inputs for test. This is not high priority.
5. Subprocess launched launched with function return value/variable value. This is inside of the `opa fmt` command. The function return value/variable value is the filename that's being used. If someone can get `opa fmt` to execute arbitrary commands we should fix this.

**Comment by prabhu** [comment]
Thank you for the prompt response. I think the best place to add your comments will be the source code along with #nosec marker. This way any future sast-scan against your project will not flag up the same issue. Also consider adding such scans as part of your build step in the future since making the static analysis test results available would also greatly help assess the state and maturity level of a project.
