### ISSUE TITLE
Terraform: Add helper functions for terraform plan policies

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2003]
There are a few things that most users will want (or need) to do when processing terraform json plan outputs https://www.terraform.io/docs/internals/json-format.html

We should have a small set of helper functions with Rego to get users started quickly and using some recommended best practices.

We would want helpers to:
* Flatten the resource tree and/or walk efficiently over it while processing rules
  * Potentially building efficient models for the resources grouped by type, module, etc.
* Map from a resource to the module configuration where it came from

These modules could be kept in the OPA libraray for terraform https://github.com/open-policy-agent/library/tree/master/terraform and maybe some of those examples changed to use them.

**Comment by srenatus** [comment]
You're probably aware, but anyways -- there's prior art in Regula: https://github.com/fugue/regula/tree/master/lib/

**Comment by anderseknert** [comment]
As suggested, this would likely better belong outside of OPA core, be it in contrib, library or projects in the OPA ecosystem. I think it's safe to close this here for now.
