### ISSUE TITLE
Test Result output shows for each decision

### ISSUE THREAD

**Issue by WhiteBoardDev** [open-policy-agent/opa#2013]
When running OPA in server mode and evaluating policies via HTTP I am getting the test results back for each decision. I would like the decision results to not contain the test output because my calling application would never need to use this data and it takes up more size on the response than the decision result itself. As more tests are written for the policy, the output is growing for each decision result.

Maybe when creating a bundle I wasn't supposed to add the tests? I assumed that bundling the tests is a good thing to allow opa to self test when it starts up. Is there a config option to hide the results?

Thank you

## Steps to reproduce

1. `authz.rego`

```
package something

default allow = false

allow {
  "admin" == input.role
}

```

2. `test_authz.rego`

```
package something

test_allowed_because_admin {
  allow with input as {
      "role": "admin"
   }
}
```
3. Build Bundle

```tar -czvf ../build/opa_bundle.tar.gz ./*```

3. Starting OPA

```opa run -s -b ./build/opa_bundle.tar.gz```

4. Execute the policy

```curl -X POST --data '{ "input": { "role" : "admin" } }' http://localhost:8181/v1/data/something```

5. HTTP Response contains test output

```
{"result":{"allow":true,"test_allowed_because_admin":true}}
```

**Comment by ashutosh-narkar** [comment]
One option for your calling application would be to query the `allow` rule itself. Eg.

```bash
$ curl -X POST --data '{ "input": { "role" : "admin" } }' http://localhost:8181/v1/data/something/allow
{"result":true}
```

**Comment by patrick-east** [comment]
+1 for @ashutosh-narkar 's suggestion, you ideally want to have a narrowly focused query to minimize what all is evaluated.

Other options include placing the tests in a different package namespace, or even exclude them from the bundle entirely.

**Comment by tsandall** [comment]
Closing this issue as there's nothing else to be done.

**Comment by WhiteBoardDev** [comment]
Thanks for the detailed responses. This gives me a few options to experiment with.
