### ISSUE TITLE
Allow policies to be passed in code

### ISSUE THREAD

**Issue by aykay76** [open-policy-agent/opa#2021]
# Expected Behavior
When using OPA as a Go library (https://www.openpolicyagent.org/docs/latest/#5-try-opa-as-a-go-library) it would be nice to pass the policy in memory rather than having to specify a filename.

```
r := rego.New(
    rego.Query("x = data.example.allow"),
    rego.Load([]string{"./example.rego"}, nil))
```

# Actual Behavior
I need to specify filename(s) which means if i'm getting the policy from a web server I need to write to local storage to then pass the filename to rego to load. It would be more efficient if I could just pass the bytes straight to rego.

Thanks for considering,

**Comment by srenatus** [comment]
> It would be more efficient if I could just pass the bytes straight to rego.

I think you can that right away using [rego.Module()](https://godoc.org/github.com/open-policy-agent/opa/rego#Module). It still needs a file name (like `policy.rego`), but that doesn't have to exist on disk. See [here](https://github.com/open-policy-agent/opa/blob/ac74fc77ffada9f48f0a94bc765922df2ffc5ad5/rego/example_test.go#L93-L100) for an example.

**Comment by aykay76** [comment]
Yes, that has worked for me, thanks for the quick response Stephan!
