### ISSUE TITLE
Add support for replacing functions using with keyword

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2028]
Currently the `with` keyword cannot mock/replace functions. The semantic checks will reject an attempt to replace functions using the with keyword. There are a few cases where this causes problems:

1. Custom built-in functions. If users have custom built-ins they rely on, they can't test their policies without recompiling OPA from source.
2. Parameterized built-in calls like `http.send`. If users have parameterized calls to built-ins like `http.send` it's difficult to mock them out.

It would be nice if users could replace functions with their own definition or data sets. For example:

```
package x

f(x) = x * x

p = f(2)

test_p {
   p with f as fake_f
}

fake_f(x) = x+x
```

Some thought needs to be given to the semantic checks we need to preserve (e.g., recursion).

**Comment by rLitto** [comment]
+1

**Comment by lcharest-godaddy** [comment]
+1

**Comment by rmetcalf9** [comment]
+999

**Comment by srenatus** [comment]
Done in 0.40.0.
