### ISSUE TITLE
Document metrics returned by Prometheus /metrics  API

### ISSUE THREAD

**Issue by bjethwan** [open-policy-agent/opa#2037]
Need a grafana dashboard to start with.
This will be useful for people starting new with OPA in k8s.
Or maybe you can enhance the docs for individual metrics 
https://www.openpolicyagent.org/docs/v0.16.2/monitoring/

And there's no supporting doc for metrics from kube-mgmt.
I guess there would definitely be some metrics to watch from kube-mgmt, other than normal cpu/memory stats from the pod?.

**Comment by tsandall** [comment]
@bjethwan this feels like a good addition to the https://github.com/open-policy-agent/contrib repo. Users could take that as inspiration and customize it for their own environments. As for Kubernetes specific metrics, there is a bunch of on-going work in https://github.com/open-policy-agent/gatekeeper to add support for metrics around how many policies are loaded and so on.

I think the most actionable next step here is to document the existing metrics on the Monitoring page: https://www.openpolicyagent.org/docs/latest/monitoring/

If someone wants to work on this, you can find the source for the monitoring page here: https://github.com/open-policy-agent/opa/blob/master/docs/content/monitoring.md.

**Comment by bjethwan** [comment]
@tsandall 
localhost:8181 will never work for Prometheus scrape, I think you should change that to 0.0.0.0 in the monitoring doc and have that port defined in the Service object in https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/

**Comment by bjethwan** [comment]
@tsandall 
I think for starters like me if you can give a quick hint on metrics to monitor the overall time http request take to complete an OPA request would help...aggregated across all the policies, so we can keep a track on how it impacts the latency as we keep adding more policies.

Does it matter to monitor go matrics ...which one should we worry about the most?

**Comment by tsandall** [comment]
@bjethwan all of the HTTP API endpoints (POST v1/data, GET v1/policies, etc.) are instrumented to record latency. The latency is exported as a standard Prometheus histrogram. The main HTTP endpoint people should care about is POST v1/data (that's how you execute policy queries against OPA.)

If you run OPA as a server, execute a policy query, and then check the metrics endpoint, you'll see the metric(s):

```
opa run -s
```

In another terminal:

```
curl -X POST localhost:8181/v1/data/example/allow   # path suffix after data/ doesn't matter
```

Query the metrics endpoint:

```
curl localhost:8181/metrics
```

This will return the standard Prometheus format and at the end you'll see the histogram for the POST v1/data endpoint. This is what we should document.

**Comment by amitkanfer** [comment]
added the description in this PR:
https://github.com/open-policy-agent/opa/pull/2908

**Comment by tsandall** [comment]
This is done now.
