### ISSUE TITLE
glob.match function does not default delimiter like the docs describe

### ISSUE THREAD

**Issue by FredrikAppelros** [open-policy-agent/opa#2039]
# Expected Behavior

Queries for a particular document should return the same result both with and without the `partial` parameter as detailed [here](https://www.openpolicyagent.org/docs/latest/rest-api/#query-parameters-4). 

Using the policy and request given below we would expect the following response:

```
{
    "result": true
}
```

# Actual Behavior

We receive expected response when querying the document without the `partial` parameter. However when we add it we instead get the following response:

```
{
    "result": false
}
```

# Steps to Reproduce the Problem

  1. Start OPA with the policy file given in the gist below using the following command:
    ```
    opa run -s authz.rego
    ```
  2. Verify that we get the expected response without the `partial` parameter:
    ```
    curl "http://localhost:8181/v1/data/authz/allow" -d '{"input": {"user": {"name": "bob", "groups": ["admins"]}, "resource": {"name": "foo"}, "operation": "foo.read"}}'
    ```
  3. Send the same request but this time with the `partial` parameter
    ```
    curl "http://localhost:8181/v1/data/authz/allow?partial" -d '{"input": {"user": {"name": "bob", "groups": ["admins"]}, "resource": {"name": "foo"}, "operation": "foo.read"}}'
    ```

# Additional Info

Use the following request body when calling the data API:

```
{
  "input": {
    "user": {
      "name": "bob",
      "groups": ["admins"]
    },
    "resource": {
    	"name": "foo"
    },
    "operation": "foo.read"
  }
}
```

You can find example code of the issue in [this gist](https://gist.github.com/FredrikAppelros/848d630561601e4af31a0c00b8c61205).

**Comment by FredrikAppelros** [comment]
It seems to be an issue with the globbing of `operation`. I can only reproduce the issue when `operation` has a `.` character in it.

**Comment by tsandall** [comment]
@FredrikAppelros thanks for filing this (and btw, this is an excellent bug report...)

Executing the query with the partial eval optimization enabled indeed returns a different answer. With tracing enabled we can see what's different:

```
$ curl 'localhost:8181/v1/data/authz/allow?pretty&explain=full&partial' -d @input.json
{
  "explanation": [
    "Enter data.partial.__result__ = _",
    "| Eval data.partial.__result__ = _",
    "| Index data.partial.__result__ = _ (matched 1 rule)",
    "| Enter data.partial.__result__",
    "| | Eval data.partial.authz.allow = _",
    "| | Index data.partial.authz.allow = _ matched 0 rules)",
    "| | Enter data.partial.authz.allow",
    "| | | Eval true",
    "| | | Exit data.partial.authz.allow",
    "| | Exit data.partial.__result__",
    "| Exit data.partial.__result__ = _",
    "Redo data.partial.__result__ = _",
    "| Redo data.partial.__result__ = _",
    "| Redo data.partial.__result__",
    "| | Redo data.partial.authz.allow = _",
    "| | Redo data.partial.authz.allow",
    "| | | Redo true"
  ],
  "result": false
}
```

This line suggests the rule indexer is to blame:

```

**Comment by FredrikAppelros** [comment]
Thank you for the detailed explanation and quick response!
