### ISSUE TITLE
opa-istio quick start sidecar injection fails due to image pull error

### ISSUE THREAD

**Issue by dmaxim** [open-policy-agent/opa#2040]
# Expected Behavior
The opa-istio sidecar should be injected into a pod

# Actual Behavior

The injection is failing due to an image pull error.  The openpolicyagent/opa:0.16.1-istio image is not found.
# Steps to Reproduce the Problem

  1. Install the opa Istio quick start (https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/quick_start.yaml)
  2.Deploy an application to a namespace with opa-istio-injection enabled

**Comment by ashutosh-narkar** [comment]
@dmaxim We just released `openpolicyagent/opa:0.16.2-istio` and also pushed `openpolicyagent/opa:0.16.1-istio` image.
