### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by bukowa** [open-policy-agent/opa#2048]
It would be a really great to have a **simple** quickstart just going straight to the point. For example, with docker-compose and 2 services in different languages actually using the OPA. Thank you

**Comment by patrick-east** [comment]
There is this https://www.openpolicyagent.org/docs/latest/http-api-authorization/ which is similar (maybe) to what you're describing.

Maybe one thing we could maybe do is to have pointers to the example projects in https://github.com/open-policy-agent/contrib as references for people looking to get started quickly with some particular language/framework or use-case.

**Comment by bukowa** [comment]
Thanks!

**Comment by tsandall** [comment]
Looks like the HTTP authorization tutorial was the right place to get started. I'm going to close this because I don't think there's anything else to do at the moment.
