### ISSUE TITLE
Make `opa test -v` default to showing trace with fails and notes

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2068]
# Desired Behavior
When some test fails when running `opa test` and `-v` is specified you get the default `fails` explain mode trace. If you then add in some `trace()` calls into the policies to troubleshoot you have to specify `--explain notes` to see them in a human friendly way... but you lose the context of the `fails` trace. It would probably be the most useful default to show both so that someone wouldn't have to use `--explain full` to see both failure events and note output.

# Proposed change
We can add a new `--explain` option to be the default for `opa test` and have it combine both notes and fail nodes of the trace. Alternatively we can make the `--explain` option take in a list of modes and then default to `fails` and `notes`, but allow it to be more flexible for other users that may have the need to combine other explain modes in the future.

**Comment by tsandall** [comment]
> Alternatively we can make the --explain option take in a list of modes and then default to fails and notes, but allow it to be more flexible for other users that may have the need to combine other explain modes in the future.

In terms of flexibility this would be nice however I think that some explanation modes will be mutually exclusive. We could address this with error checking but I'm not sure how usable it will be.

Another option would be to update the code in topdown to expose the predicates that filter for `Fail` and` Note` events and then compose them when `-v` is specified. IOW, do the right thing when `-v` is specified -- output the notes and the fails.

In conjunction with #2069 (which just makes `opa test` emit the trace when `--explain` is given) this would provide a nice improvement to the tester.
