### ISSUE TITLE
The "Next Steps" section of the Introduction page isn't formatting correctly

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2071]
Over on https://www.openpolicyagent.org/docs/latest/#next-steps the list of "popular tutorials" isn't rendering as a list, just `*` separated content

![image](https://user-images.githubusercontent.com/3614287/73998376-4c834180-4916-11ea-9871-77c61666969b.png)

**Comment by rleekin** [comment]
Hi, I'm new to the project and interested in working on this issue.

**Comment by patrick-east** [comment]
@rleekin Awesome! If you need any help with getting the dev workflow on the docs to work don't hesitate to ping me on the OPA slack.

I probably should have linked it in the original issue description, but take a look at https://github.com/open-policy-agent/opa/blob/master/docs/README.md for instructions on how to build/run the docs locally. The actual content for that one is in https://github.com/open-policy-agent/opa/blob/master/docs/content/_index.md#next-steps (interestingly GitHub renders it correctly as markdown.. so this might be some weirdness with Hugo).

**Comment by rleekin** [comment]
Thanks @patrick-east, I'll get started on it this week.

**Comment by evrardjp** [comment]
@rleekin hey, I thought I would help, would you mind having a look at the PR here? That would be awesome.
