### ISSUE TITLE
Headers on "Configuration" docs are not rendering correctly

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2072]
Over on https://www.openpolicyagent.org/docs/latest/configuration/ there are some headers that are using 7(?) `#`'s and are not being picked up by the markdown -> html and translated. We should take a look and see if we can just use less deep header levels.. They don't appear to actually be 7 levels deep.

![image](https://user-images.githubusercontent.com/3614287/73998540-ce736a80-4916-11ea-9a7c-fe13e0c4eb46.png)

**Comment by evrardjp** [comment]
Seens like merging the commit didn't close this. We should probably close this.
