### ISSUE TITLE
Playground policy examples on "Policy Testing" page are broken

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2073]
There are a handful of open-able live doc snippets on https://www.openpolicyagent.org/docs/latest/policy-testing/ but none of them actually work if you open them and click "Evaluate".

There are two classes of problematic examples:

Boring ones -- For example, the first one on the page in https://www.openpolicyagent.org/docs/latest/policy-testing/#getting-started for `example.rego` gives.. https://play.openpolicyagent.org/p/ArWZTgjykq which parses and evaluates fine.. but doesn't really do anything. We should probably include a sample input document or something, or a `default allow = false` or something.

Next up in that same section is https://play.openpolicyagent.org/p/av8yGfvifo which opens up but if you hit evaluate you are greeted with:

```
1 error occurred: policy.rego:15: rego_parse_error: unexpected package
```

Because the policy looks like:

```
package authz

allow {
    input.path == ["users"]
    input.method == "POST"
}

allow {
    some profile_id
    input.path = ["users", profile_id]
    input.method == "GET"
    profile_id == input.user_id
}

package authz

test_post_allowed {
    allow with input as {"path": ["users"], "method": "POST"}
}

test_get_anonymous_denied {
    not allow with input as {"path": ["users"], "method": "GET"}
}

test_get_user_allowed {
    allow with input as {"path": ["users", "bob"], "method": "GET", "user_id": "bob"}
}

test_get_another_user_denied {
    not allow with input as {"path": ["users", "bob"], "method": "GET", "user_id": "alice"}
}
```
Which looks fine on the docs.. but in here you can't define the package twice.

This same sort of thing happens later on in the https://www.openpolicyagent.org/docs/latest/policy-testing/#data-mocking section

**Comment by tsandall** [comment]
One option would be to remove the playground link on the test examples that cannot be opened today.
