### ISSUE TITLE
Support for OAuth 2.0 flows required for http.send callouts

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2096]
In some cases policies may need to reach out to the APIs that require an OAuth 2.0 flow for authentication. Since there are different OAuth 2.0 flows that could be supported, the first thing to do is scope this enhancement.

For the API, one option would be to provide a built-in function that returns a token that could be used in a subsequent `http.send` call. For example:

```
token := oauth.request(params)
http.send(..., "headers": {"Authorization": token})
```

For implementation, we'll have to consider implementing the OAuth 2.0 flow from scratch as opposed to relying on a thirdparty library.

**Comment by anderseknert** [comment]
With the recent improvements to caching in `http.send` this is _almost_ possible to do in-policy now:

```rego
token = t {
    r := http.send({
        "url": "https://authorization-server.example.com/token",
        "method": "POST",
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded",
            "Authorization": concat(" ", ["Basic", base64.encode(sprintf("%v:%v", [client_id, client_secret]))]),
        },
        "raw_body": "grant_type=client_credentials",
        "force_cache": true,
        "force_cache_duration_seconds": 3600,
    })

    t := r.body.access_token
}
```

Caveats:
1. Token lifetime must be known beforehand as we can't use the lifetime provided in the response. This would obviously be possible with a built-in.. but on the other hand token lifetime pretty much always _is_ known beforehand, so I'm not sure this is much of a problem.
2. Caching the response from the token endpoint doesn't actually work, as the authorization server [per spec](https://tools.ietf.org/html/rfc6749#section-5.1) will return no-store directives, and those are currently respected even with `force_cache` set. Issue #2841 was actually discovered when trying to do the above.

**Comment by tsandall** [comment]
@anderseknert it sounds like we might be able to close this issue now that we have caching support and #2841 has been fixed. WDYT?

**Comment by anderseknert** [comment]
Definitely! 👍 With #2841 merged `http.send` cover both the non-interactive flows (client credentials flow + the (not commonly used) resource owner password credentials flow), and those are really the ones applicable for use inside of policies. I think it would be useful to have a "kicking the tires" section on OAuth and OIDC in the docs to document token retrieval as well as verification flows involving a JWKS endpoint, etc.. and I'm planning to work on that in a not too distant future. But yeah, this ticket may be closed.

**Comment by tsandall** [comment]
Sounds good. I'll wait until those docs are ready and then I'll close this. Marking this as planned.
