### ISSUE TITLE
Add support for offline recovery by saving and reading bundles from disk

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2097]
OPA does not currently save downloaded bundles to disk. This means that if OPA restarts and is unable to connect to a bundle server it will be unable to serve policy decisions until the bundle server is reachable.

To better support offline recovery, OPA could be extended to save activated bundles to disk. If OPA restarts after saving a bundle to disk it can read the bundle from disk and use it until it's able to download the latest version from the bundle server.

Misc. thoughts:

* The status API should report errors that occur while saving bundles to disk
* The bundle persistence option should be optional and off-by-default initially

**Comment by WeiZhang555** [comment]
For server mode, I see that if I put new rego policy or data into OPA daemon via RESTful API, the policy and data won't be saved to disk, this also means the policy and data will be lost once I restart the OPA server. 

Do you have plan to fix this too?

**Comment by tsandall** [comment]
@WeiZhang555 we don't have any immediate plans to add support for persistence in OPA itself. If you build OPA from source, you can replace the in-memory store with your own implementation.
