### ISSUE TITLE
opa-istio-plugin fails when parsing json body with array

### ISSUE THREAD

**Issue by jam-cognitive** [open-policy-agent/opa#2102]
# Expected Behavior
When Envoy is configured to [pass request body](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto) to opa-istio-plugin and request content type is `application/json`, OPA attempts to parse the body and make it available in `parsed_body` field. When the request body contains a JSON object, e.g. `{}`, `parsed_body` is correctly populated. When the request body contains an array, e.g. the empty array `[]`, I expect `parsed_body` to contain the array because it is a valid JSON.

# Actual Behavior
When the request body contains an array, processing the request fails. Here is an example of a decision log:

```
{
  "decision_id": "",
  "erased": [
    "/input/attributes/request/http/headers"
  ],
  "error": {
    "Field": "",
    "Offset": 1,
    "Struct": "",
    "Type": {},
    "Value": "array"
  },
  "input": {
    "attributes": {
      "metadata_context": {},
      "request": {
        "http": {
          "body": "[]",
          "host": "my-service:7777",
          "id": "15968943781211735851",
          "method": "POST",
          "path": "/my-service/my-path",
          "protocol": "HTTP/1.1",
          "size": 2
        }
      },
    },
    "parsed_path": [
      "incident-service",
      "2170839428",
      "clusters",
      "statistics"
    ],
  },
  "labels": {
    "id": "88eeba66-ac13-4c1d-8420-e4481f089c07",
    "version": "0.15.1-istio-3"
  },
  "level": "info",
  "msg": "Decision Log",
  "path": "istio/authz/allow",
  "query": "data.istio.authz.allow",
  "requested_by": "",
  "time": "2020-02-13T11:44:56Z",
  "type": "openpolicyagent.org/decision_logs"
}
```

# Steps to Reproduce the Problem
  1. Enable with_request_body in EnvoyFilter (this is the default in [quick_start.yaml](https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/quick_start.yaml)
  2. Make a request to a service with opa-istio sidecar, which has `application/json` content type and `[]` as body, e.g.: ```curl -H 'Content-Type: application/json' -X POST -d '[]' -v http://my-service/path```

# Additional Info
* The relevant part of code which does the parsing is https://github.com/open-policy-agent/opa-istio-plugin/blob/master/internal/internal.go#L604
* The docker image we are using is `openpolicyagent/opa:0.15.1-istio-3`

**Comment by ashutosh-narkar** [comment]
PR: https://github.com/open-policy-agent/opa-istio-plugin/pull/163

**Comment by ashutosh-narkar** [comment]
`openpolicyagent/opa:0.17.1-istio-1` image supports valid json in request body.

**Comment by jam-cognitive** [comment]
That was a super-fast response :)
I have verified the new version to work. Thanks!
