### ISSUE TITLE
OPA - printing additional details during eval 

### ISSUE THREAD

**Issue by nyalavarthi** [open-policy-agent/opa#2104]
# Expected Behavior
I am running the opa as part of gitlab cicd pipeline and wanted to print additional information when there is a compliance violations / validation failures.  
I am using this example code to validate aws terraform code ( from https://www.openpolicyagent.org/docs/latest/terraform/) :
 
sample  AWS S3 terraform code for compliance checks :

`#Enforce S3 bucket region to "eu-central-1"`
`s3_region_change[resource_type] = num {`
    `some resource_type`
    `resource_types[resource_type]`
    `all := resources[resource_type]`
    `creates := [res |  res:= all[_]; res.change.after.region != "eu-central-1"]`
    `num := count(creates)`
`}`

`//S3 acl property should be private`
`s3_acl_change[resource_type] = num {`
    `some resource_type`
    `resource_types[resource_type]`
    `all := resources[resource_type]`
    `modifies := [res |  res:= all[_]; res.change.after.acl != "private"]`
    `num := count(modifies)`
  ` trace(num) -- THIS DOES NOT PRINT ANYTHING`
`}`
`
opa command : 
opa eval  -f pretty --data s3-validate.rego --input tfplan.json  "data.terraform.analysis.authz"
false ( result output is printed as false as expected.) 

opa eval  -f pretty --data s3-validate.rego --input tfplan.json  "data.terraform.analysis.score"
10 ( result output is printed as 10 as expected ) 

what i am expecting is , if I have about 10 compliance validations in my code and only couple of them fails to meet my compliance policies, I want to know which policies failed . currently I have to either guess or go line by line and find out where the issue is.

in comparison , if I use open source version of fugue ( regula), the results will clearly tell us where the issue is. ( sample results below) 

my questions : 
1. what is the best way in OPA to print more information regarding the validation failures. 
2. how do I print sys logs to console ? , I have tried trace commands but nothing was printed to console ( command prompt) when i run my opa eval commands

Fugue / Regula command and results. 
command : opa eval -i .\infra.json -d C:\tools\regula\regula-master\lib\ -d  .\rules 'data.fugue.regula.report'

`
result : 
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "controls": {},
            "rules": {
              "my_simple_rule": {
                "resources": {
                  "aws_ebs_volume.example": {
                    "id": "aws_ebs_volume.example",
                    "message": "",
                    "type": "aws_ebs_volume",
                    "valid": true
                  }
                },
                "valid": true
              }
            },
            "summary": {
              "controls_failed": 0,
              "controls_passed": 0,
              "rules_failed": 0,
              "rules_passed": 1,
              "valid": true
            }
          },
          "text": "data.fugue.regula.report",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
`

**Comment by tsandall** [comment]
@nyalavarthi OPA implements a feature called "tracing" whereby the evaluator emits events as it executes policy statements. Together these events form an execution "trace" that explain why the policy decision was generated. You can use the `trace(msg)` built-in function to emit "notes" to the trace. By default tracing is turned off because it's relatively expensive. If you run `opa eval -f pretty --explain=notes ...` OPA will print "note" events and some context to help understand where the event occurred.

The way people often structure these kinds of policies to define a set of "deny" or "violation" rules that codify compliance policies. For example:

```rego
package terraform.analysis

violation["missing required tags"] {
   # some logic expressed against the plan
}

violation["bad encryption parameters"] {
   # some logic expressed against S3 resources in the plan
}
```


The top-level "authz" decision can be made based on this violation set. For example:

```rego
package terraform.analysis

default authz = true

authz = false { count(violation) >= 0 }
```

If you want to query for both authz and violation you could:

```rego
authorized = data.terraform.analysis.authz; violations = data.terraform.analysis.violation
```

The result that comes contains a value for the `authorized` variable and a value for the `violations` variable. The latter would you provide a human-readable error message for users.

I'm going to close the issue because I don't think there's anything else to be done at this point. We do have another issue #2089 that's related.

**Comment by stevend-15** [comment]
@tsandall 

Regarding the 'violation' partial rules you mentioned above, could you explain the usage of the string within the [ ] boxies? I've looked through the docs for examples and have used the playground but still cannot seem to fully grasp the significance of their usage. 

Why use those strings if you cannot change their value like the case of a variable? Why not just use a default statement and make a complete rule? 

I understand the concept of chaining together 'violation' rules as per your response [here](https://stackoverflow.com/questions/61578607/parameters-in-rego-rules-open-policy-agent) and elsewhere. However, the usage of those strings is confounding to me.

**Comment by anderseknert** [comment]
@stevend-15 partial set building rules can be thought of as "if this rule evaluates, add the value provided to the set"
if you want to change their value dynamically, use a variable:

```rego
violation[message] {
    # ...
    message := sprintf("resource %s in violation of foo", [input.resource.name])
}
```

**Comment by stevend-15** [comment]
@anderseknert OK, thank you. So, those string values can just be thought of as a more rigid addition to the set in some use cases. Understood
