### ISSUE TITLE
OPA docs should provide pronunciation of "rego"

### ISSUE THREAD

**Issue by teq0** [open-policy-agent/opa#2106]
The current documentation provides the standard pronunciation of ["OPA"](https://github.com/open-policy-agent/opa/blob/master/docs/content/_index.md), it should also provide the standard pronunciation of "rego".

**Comment by teq0** [comment]
Which is "ray-go", obviously.

**Comment by pyzenberg** [comment]
> Which is "ray-go", obviously.

Obviously how? I mean in which language and do we all have enough time to get to know the language you want?

**Comment by anderseknert** [comment]
@pyzenberg feel free to pronounce it any way you wish :) FWIW I commonly pronounce the "e" the same way as "Lego", as that sounds natural in Scandinavian languages, saving the "ray-go" pronounciation for when I try to blend in with a north American audience 😄

**Comment by teq0** [comment]
I'm going to defer to Torin on this one :)
