### ISSUE TITLE
opa server should accept a net.Listener

### ISSUE THREAD

**Issue by drewwells** [open-policy-agent/opa#2111]
# Expected Behavior
This method is implemented https://golang.org/pkg/net/http/#Server.Serve

# Actual Behavior
Only string addresses are possible

# Steps to Reproduce the Problem
N/A

# Additional Info
One of the primary use cases here is for writing unit tests against Opa. I want my unit test to support a variety of environments, so I will request an open port from the OS ie. :32050. I then pass this listener into opa for binding to.

An incomplete workaround is to open a listener then close it and pass it along. 

```
 // Retrieve a random port from the OS and pass it to opa
    l, err := net.Listen("tcp4", ":0")
    if err != nil {
        t.Fatal(err)
    }
    addr := l.Addr().String()
    l.Close()

    addrs := []string{addr}

    opaSvr := server.New()
    opaSvr.WithAddresses(addrs)
```

**Comment by patrick-east** [comment]
Can you just pass like `127.0.0.1:0` to opa as the address and let it pick an open one? You can get the list of addresses back for the test clients via https://pkg.go.dev/github.com/open-policy-agent/opa/server?tab=doc#Server.Addrs  (or if you have the full `runtime` it also has an `Addrs()` helper). These are used by the OPA unit test framework to do a very similar sort of thing, check out https://github.com/open-policy-agent/opa/tree/master/test/e2e for some examples of tests and the helpers to spin up a local OPA server in unit tests.

**Comment by tsandall** [comment]
I'm going to close this issue because it looks like it's handled by telling OPA to bind on `:0`.
