### ISSUE TITLE
OPA should (optionally) read secrets from file system

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/opa#2131]
Secrets that OPA needs to connect to external systems (e.g. for the bundle or discovery APIs) today are read out of the configuration file.  This makes secret provisioning and rotation difficult.  People don't want to check tokens into version control, but they do want to check their OPA configurations into version control.

It would be helpful if OPA could read its secrets from a file.  This would make it possible when running on k8s to mount a secret into the OPA container, which would help with provisioning.  

Moreover, if OPA reads its secrets from a file every time it needs it, that would allow for easier secret rotation.

**Comment by patrick-east** [comment]
We already support loading from environment variables and/or files by using https://www.openpolicyagent.org/docs/latest/configuration/#environment-variable-substitution or https://www.openpolicyagent.org/docs/latest/configuration/#cli-runtime-overrides in particular the `--set-file` option is the "best practice" for k8s secrets (don't put them as env vars, mount as files and point OPA to the file)

The main addition would maybe be to extend to support re-reading each time it is used (although IIRC when working on that the first time the thought was that just restarting the service was sufficient)
