### ISSUE TITLE
profiler panics if expressions are missing location info

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2134]
If the profiler tracer is used on a query prepared with partial eval enabled the expressions seen by the profiler may not have location data. We should make the profiler tolerate expressions that are missing location data either by discarding the events or grouping and reporting them anonymously (e.g., use a magic/invalid location like `???`.)

This Go snippet reproduces the issue:

```
package main

import (
	"context"

	"github.com/open-policy-agent/opa/profiler"
	"github.com/open-policy-agent/opa/rego"
)

type S struct {
	M map[string]string
}

func main() {

	ctx := context.Background()

	pq, err := rego.New(
		rego.Module("x.rego", "package foo\np=1"),
		rego.Query("data.foo.p"),
	).PrepareForEval(ctx, rego.WithPartialEval())
	if err != nil {
		panic(err)
	}

	profiler := profiler.New()

	_, _ = pq.Eval(ctx, rego.EvalTracer(profiler))

}
```

**Comment by ashutosh-narkar** [comment]
If we discard events where the expression location is `nil`, after slightly modifying the above script the result would look like: 

```
undefined
+---------+----------+----------+-------------------------+
|  TIME   | NUM EVAL | NUM REDO |        LOCATION         |
+---------+----------+----------+-------------------------+
| 5.964µs | 1        | 0        | data.partial.__result__ |
+---------+----------+----------+-------------------------+
```

@tsandall does this result look reasonable to you ?

**Comment by tsandall** [comment]
I'd like to see the alternative of grouping expressions that have no location. Intuitively, I'm guessing that simply discarding events could be confusing because the tool could report only a small portion of the overall evaluation time. WDYT?

**Comment by ashutosh-narkar** [comment]
Agreed. Below is an example profiler output by grouping expressions that are missing location information:
```
+----------+----------+----------+-------------------------+
|   TIME   | NUM EVAL | NUM REDO |        LOCATION         |
+----------+----------+----------+-------------------------+
| 29.01µs  | 2        | 2        | ???                     |
| 13.624µs | 1        | 1        | data.partial.__result__ |
+----------+----------+----------+-------------------------+
```

**Comment by patrick-east** [comment]
Seems like using the fake location is the best one for now. Depending on the use-case it almost seems like it might be useful to group the time spent under the original location that is responsible for the generated code. Like for this example instead of `???` and `data.partial.__result__` we'd say `data.foo.p`, the other stuff is almost like an eval implementation detail for these cases.
