### ISSUE TITLE
File name truncation in pretty trace hides file name

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2143]
# Expected Behavior
The pretty trace shows location info including the file name and line number. This works great if the path to the file is short, but if its longer than the cutoff it gets truncated. I would expect however that we keep the file name and truncate the path.

# Actual Behavior

The file name is cut off so its hard to tell what file it came from, ex:

```
{11:48} ~ ❯ opa eval -b /tmp/bundle/ -i /tmp/input.json -f pretty --explain full 'data.policy.authz.allow'
query:1             Enter data.policy.authz.allow = _
query:1             | Eval data.policy.authz.allow = _
query:1             | Index data.policy.authz.allow = _ (matched 1 rule)
/tmp/bundle/pol:3   | Enter data.policy.authz.allow
/tmp/bundle/pol:4   | | Eval input.x = "foo"
/tmp/bundle/pol:3   | | Exit data.policy.authz.allow
query:1             | Exit data.policy.authz.allow = _
query:1             Redo data.policy.authz.allow = _
query:1             | Redo data.policy.authz.allow = _
/tmp/bundle/pol:3   | Redo data.policy.authz.allow
/tmp/bundle/pol:4   | | Redo input.x = "foo"
true
{11:48} ~ ❯ find /tmp/bundle
/tmp/bundle
/tmp/bundle/policy
/tmp/bundle/policy/authz
/tmp/bundle/policy/authz/policy.rego
```

# Additional Info

What we have setup to show the traces works pretty well, but we need to iterate a little bit on the truncation algorithm (or get fancy and have more dynamic spacing for the location info rather than a fixed width.. or some combination of the two).  Most of the changes will just be over in https://github.com/open-policy-agent/opa/blob/master/topdown/trace.go#L209

**Comment by isaeef** [comment]
@patrick-east would like to work this issue

**Comment by patrick-east** [comment]
@isaeef awesome! Let me know if you need any pointers or help.

**Comment by patrick-east** [comment]
@isaeef Hi, just wanted to check in and see if there were any updates. Feel free to ping me on the OPA slack if there is anything I can do to help 😄
