### ISSUE TITLE
Way to mock time in tests

### ISSUE THREAD

**Issue by mjgpy3** [open-policy-agent/opa#2150]
This may already exist, but, is it (or would it be) possible to control the results of functions like `time.now_ns()` from tests?

My use-case is pretty simple, I have a policy which has certain rights which expire. I would like to test the boundaries around expiry (right before, at the instant of expiry and right after).

I can potentially workaround this testing feature by adding/subtracting time to `time.now_ns()` in the test input data, however, that solution's not perfect (I can elaborate if needed).

Cheers, thanks for your work on this very nice tool!

**Comment by patrick-east** [comment]
The best option right now is to hide the call to `time.now_ns()` in a helper rule, then use the `with` keyword to mock it out in tests. https://play.openpolicyagent.org/p/xjy7hoOGMV shows an example (snippet below too)
```
current_time := time.now_ns()

allow {
    current_time <= input.expires_or_whatever
}

test_allow_not_expired {
    mock_current_time := 1582753190807116800
    expires := 1582753190807116800 + 1
    
    allow with current_time as mock_current_time
        with input as {"expires_or_whatever": expires}
}
```

There is an open issue to extend the `with` keyword to support mocking functions which would also provide a solution to this #2028

**Comment by mjgpy3** [comment]
@patrick-east thank you, mocking a helper rule or what #2028 would provided if resolved sound like good options!
