### ISSUE TITLE
Load external data from database in OPA

### ISSUE THREAD

**Issue by priyanka-5** [open-policy-agent/opa#2169]
I am new to REGO. I want to write policies to authorize the user based on its role and resources assigned to him/her. All information of user is stored in database, so I want to write policies which will work on this data. But how do I get or fetch the data from database in OPA.
I read OPA's official documentation for[ External data ](https://www.openpolicyagent.org/docs/latest/external-data/) but I didn't get any idea about how can I fetch data from my database and execute policies. Is there any way to connect REGO to database or is there any other way so that I can execute policies on data from database.

**Comment by ashutosh-narkar** [comment]
One of the options mentioned on that page uses [Bundles](https://www.openpolicyagent.org/docs/latest/external-data/#option-3-bundle-api) approach. In this scenario, you would create a service that fetches the relevant info from your database and then OPA would query that service to get policy/data. 

You could use the same service to push data into OPA instead of the pull approach. That's [option 4](https://www.openpolicyagent.org/docs/latest/external-data/#option-4-push-data).

Additionally, there is a new use-case around data filtering that translates Rego polices to SQL and Elasticsearch queries. See https://github.com/open-policy-agent/contrib/tree/master/data_filter_elasticsearch and https://github.com/open-policy-agent/contrib/tree/master/data_filter_example. I would recommend trying the options in the External data page first.

**Comment by priyanka-5** [comment]
@ashutosh-narkar thank you. I'll try it.
I didn't get what does that "OPA would query that service to get policy/data" means ?

**Comment by ashutosh-narkar** [comment]
> OPA would query that service to get policy/data

When your service gets a user api request and needs to make an authz decision it will ask OPA for it. OPA would load policies/data by making a call to a aggregator service (which you would have to create). The aggregator service gets relevant info from the database and makes it available to OPA.

Regarding memory, it depends how you deploy OPA and how much memory you assign to it. If your data is too big to fit in memory, there are approaches like fetching data during policy evaluation ([Option 5](https://www.openpolicyagent.org/docs/latest/external-data/#option-5-pull-data-during-evaluation-experimental)) or  having the aggregator service provide the piece of info that is relevant to make that decision.

**Comment by priyanka-5** [comment]
Ok. Thank you @ashutosh-narkar I'll try it

**Comment by patrick-east** [comment]
Going to close this out, it seems like the questions are answered. Feel free to re-open if more questions/issues come up!

**Comment by AjayShekar01** [comment]
Hello Everyone, 
Thanks for explaining about aggregator service which will fetch relevant data from database for the OPA. Can you link any documentation or examples for integrating this aggregator service ?

**Comment by anderseknert** [comment]
@AjayShekar01 see the docs section on external [data](https://www.openpolicyagent.org/docs/latest/external-data/), and [bundles](https://www.openpolicyagent.org/docs/latest/management-bundles/).

I think an "aggregator service" makes it sound a bit more complex than it needs to be. The last time I implemented something like this it was a cron job calling a Python script of 50 lines of code, or something like that. The script would do this:

1. Fetch relevant data from a "permissions" table in a legacy MySQL database
2. Transform the data from a SQL resultset to JSON
3. Store the JSON data on disk (`data.json`)
4. Build an OPA bundle (`opa build bundle policy.rego data.json`)
5. Push the bundle to AWS S3 or some other HTTP server capable of serving bundles (see bundle docs for examples)

Set the cron job to repeat as frequently as we deemed acceptable in terms of "lag". You could of course also trigger the same script manually in case you know that an update has happened and you want the data to be propagated to OPA as quickly as possible.

**Comment by obsd** [comment]
You can also use [OPAL](https://www.opal.ac/) which is a new cool opensource that can load real-time data into OPA from various sources

**Comment by tsandall** [comment]
As others have mentioned there are a few ways you can get data into OPA. You can also extend OPA with [Custom Built-in Functions](https://www.openpolicyagent.org/docs/latest/extensions/#custom-built-in-functions-in-go) or [Plugins](https://www.openpolicyagent.org/docs/latest/extensions/#custom-plugins-for-opa-runtime) that fetch data from remote sources. There are quite a few examples of people doing this today. For example, [this talk from Chime](https://www.youtube.com/watch?v=qHvh7ilYGQk) shows how they extended OAP to fetch data from multiple sources.

If you'd like to avoid developing and maintaining your own built-in functions and plugins to fetch data, check out [Enterprise OPA](https://docs.styra.com/enterprise-opa/). It's an OPA distribution that comes with out of the box support for [SQL](https://docs.styra.com/enterprise-opa/tutorials/abac-with-sql), [Kafka](https://docs.styra.com/enterprise-opa/tutorials/kafka), etc.

**Comment by erald14** [comment]
Hey, quick question. We are planning to use OPA, and have a trigger on database events, so we can a table data through the API. 
Question: How would one go about implementing this data to be available in case of a startup?

**Comment by OnkarKumbharDatastack** [comment]
Hello I have written opa rule in one bundle and another bundle which download from another service api endpoint which defined in config.yaml and stored in opa but when i hit api from postman then data come correctly but second time result {} third time fetch success like that problem
