### ISSUE TITLE
object.get with multilevel key

### ISSUE THREAD

**Issue by mnuthan1** [open-policy-agent/opa#2175]
# Expected Behavior
object.get with multi-level key (with . notation) should return actual values
# Actual Behavior
Currently its returns null

# Steps to Reproduce the Problem

  1. with the following input
`{
    "message": "world",
    "level1" : {
    	"level2" : {
            "level3" :"I am level 3"
        } 
	}
}`
  2. input["level1.level2.level3"] should return values of "I am level3"
  3.

# Additional Info
https://play.openpolicyagent.org/p/LmMMuWfPeV

**Comment by patrick-east** [comment]
You are seeing the expected behavior, it is looking for key `"level1.level2.level3"` (a single string):, ex: https://play.openpolicyagent.org/p/xZIM4Cj5ed

**Comment by patrick-east** [comment]
There is discussion around adding some additional functionality to potentially allow for this sort of thing over in #1617 Check through there and if the use-case isn't addressed please add a comment with the desired behavior and use-case for it.

**Comment by mnuthan1** [comment]
@patrick-east is there any way to get value with the multilevel key.  I am trying to validate spinnaker pipelines where a JSON field can refer to another field. for example with below input I need to validate min_nodes < 3
 
`{
    "pipelineParameters" : {
        "k8" : {
            "NODES" : "1"
        },
        "min_nodes" : "${k8.NODES}"
}`
