### ISSUE TITLE
[wasm] error when calling eval: object merge conflict

### ISSUE THREAD

**Issue by itaysk** [open-policy-agent/opa#2194]
# Expected Behavior
I can use wasmer.io in C to run an opa wasm module.

# Actual Behavior
```
clang opa.c -o opa -I ./include -L ./lib -l wasmer -rpath ./lib
opa_ctx_address: 105a0
opa_abort: 2118
ERROR (opa_abort): object merge conflict
ERROR (call_wasm_function_and_return_i32): call to wasm function failed: func: eval, params:
  param 0 { tag: 0, i32: 66976 }
ERROR (print_wasmer_error): `Call error: Caught exception of type "Unreachable".`
```

# Steps to Reproduce the Problem
It's going to be hard to share the entire project here but I have isolated the issue as following:

1. Build a simple opa policy using `opa build`. I'm using the sample policy:
```rego
package example
foo := 1
myrule {
  foo == 1
}
```
2. read the opa module file into memory
3. setup a wesmer.io C project
4. initialize a wasmer instance with the module, and opa's required imports
5. execute a test like the following:
```c
  wasmer_value_t opa_eval_ctx_new_params[] = { 0 };
  int opa_ctx_address = call_wasm_function_and_return_i32(instance, "opa_eval_ctx_new", opa_eval_ctx_new_params, 0);
  printf("opa_ctx_address: %x\n", opa_ctx_address);
  wasmer_value_t eval_params[] = { {.tag = WASM_I32, .value.I32 = opa_ctx_address} };
  call_wasm_function_and_return_i32(instance, "eval", eval_params, 1);
  return 0;
```
6. see the command and output in the "Actual Behavior" above

# Additional Info
- This is a followup of the following discussion in slack: https://openpolicyagent.slack.com/archives/C1H19LW4F/p1583667715144800
- I have tested the same module in node.js using the opa-wasm npm package, and the module itself works.
- I have ommitted code for steps 2-4, and I assume the issue is not there because:
  - I can call the exported function `opa_eval_ctx_new` 
  - The module can call my imported function `opa_abort`
  - I looked into the constructed opa context and tried to set it's input and data and it appears ok.

Update: I have uploaded the sample project here https://github.com/itaysk/opa-wasm-issue2194
Run it with `make opa`

**Comment by patrick-east** [comment]
> I have ommitted code for steps 2-4

Makes sense that they may not be related to the issue, but if you could share it would make it easier for others to repro the issue and help troubleshoot quicker.

**Comment by itaysk** [comment]
Ok, I have uploaded the sample project here: https://github.com/itaysk/opa-wasm-issue2194
Run it with `make opa`

**Comment by patrick-east** [comment]
@itaysk thanks!

**Comment by patrick-east** [comment]
@itaysk One more question, what was the query used when compiling the policy?

**Comment by itaysk** [comment]
iirc it was `data = x`

**Comment by tsandall** [comment]
The `object merge conflict` error is generated when a recursive object merge is executed on two values and one of the values is not an object. If you specify `-D` on `opa build` the plan will be emitted and you can see where the merge conflict error would be occurring:

```
$ opa build -d object-merge-error-repro.rego 'data = x' -D
PLAN:
-----
*ir.Policy Policy
| *ir.Static Static (5 strings)
| | *ir.StringConst &{Value:x}
| | *ir.StringConst &{Value:example}
| | *ir.StringConst &{Value:foo}
| | *ir.StringConst &{Value:1}
| | *ir.StringConst &{Value:myrule}
| *ir.Plan Plan (2 blocks)
| | *ir.Block Block (1 statements)
| | | *ir.MakeStringStmt &{Index:0 Target:2}
| | *ir.Block Block (13 statements)
| | | *ir.MakeObjectStmt &{Target:3}
<---SNIP--->
| | | | | | | *ir.ObjectMergeStmt &{A:1 B:3 Target:10}    <--- THIS INSTRUCTION GENERATES THE MERGE ERROR
<---SNIP--->
```

In this case `A` is the local variable referring to base documents (raw JSON) loaded into `data` and `B` is the local variable referring to the virtual document generated by the `data` reference. We can see from the plan that `B` is an object. **What's unclear is whether `A` refers to an object value.** If you call `opa_eval_ctx_set_data` and initialize it to an empty object, does the error go away?

**Comment by itaysk** [comment]
@tsandall Thank you! the issue was indeed that I didn't initialize the data object.
Before opening this issue I checked that the node.js version works without initializing data (I wanted the minimal example), but my check was faulty - I removed [the call](https://github.com/open-policy-agent/npm-opa-wasm/blob/master/examples/nodejs-app/app.js#L22) to `policy.set_data(data);` from my app, but after looking deeper now I see that the data is initialized anyway [in the constructor](https://github.com/open-policy-agent/npm-opa-wasm/blob/master/src/opa.js#L143) and [evaluation](https://github.com/open-policy-agent/npm-opa-wasm/blob/master/src/opa.js#L164), and also that the [docs say this is mandatory](https://github.com/open-policy-agent/opa/blame/master/docs/content/wasm.md#L89). 

Thanks alot for all you help on Github, StackOverflow and on Slack, it's very much appreciated!
