### ISSUE TITLE
docs: Homepage links to "Learn More" should be more visually distinct

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2205]
On the home page for OPA https://www.openpolicyagent.org/ we have:

![image](https://user-images.githubusercontent.com/3614287/77207982-02b27d00-6ab8-11ea-92a8-fd22bf647b57.png)

Which is somewhat confusing as it looks like one big button but each of the text items is a separate link. We should split them up into separate buttons or something more distinctive.

**Comment by arunbsar** [comment]
@patrick-east I will pick this
