### ISSUE TITLE
docs: Homepage policy snippets should have visual indication you can click on examples

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2206]
About halfway down on https://www.openpolicyagent.org/ we have the "Declarative Policy" section with a few Rego samples in "live" blocks. As-is you can select different examples by clicking on the box of text that describes them, but it isn't very easy to notice. We should have them change color or something when the mouse hovers over them

![image](https://user-images.githubusercontent.com/3614287/77208121-5c1aac00-6ab8-11ea-8b54-e4b9506c1911.png)
^^ In that example the slightly darker grey one is visiable and you can click on the thing below it, but its not as discoverable as it could be.

**Comment by arunbsar** [comment]
@patrick-east I will work on this issue

**Comment by patrick-east** [comment]
Thanks @arunbsar, let me know if you run into any issues with building/testing the docs (it can be kind of difficult sometimes)

**Comment by patrick-east** [comment]
This was fixed in #2309
