### ISSUE TITLE
Add config/scripts/tooling to build OPA RPM and Deb packages

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2210]
OPA currently provides binaries for osx, linux, and windows, plus docker images (for amd64 linux). However there have been requests for RPM's (#2162) for OPA installation.

There is even support for `brew` https://formulae.brew.sh/formula/opa

So it isn't too big of a stretch to say that we could have some simple RPM/Deb files for installing OPA (useful for installing on hosts directly or building images without downloading raw binaries/building from source)

That being said we do *NOT* want to take on supporting/pushing/maintaining upstream support in various linux distros.

What I would propose is we provide enough configuration to use something like FPM https://github.com/jordansissel/fpm so that we can have a single config and generate whatever format people would like to consume. It would then be pretty easy to just include the RPM and Deb files on the releases in GitHub as well as hosting them with the binaries for download at https://openpolicyagent.org/downloads/ (<- that link doesn't go anywhere right now, they aren't browsable)

High level steps to get this started:
* Add script to create the packages to `./build` using https://fpm.readthedocs.io/en/latest/source/dir.html and maybe start with `deb` and `rpm` targets.
* Add a MakeFile target to build it
* Add a step for Travis to build it and push (like we do with binaries) https://github.com/open-policy-agent/opa/blob/master/Makefile#L246
* Add as a step in the `release` target, document on https://github.com/open-policy-agent/opa/blob/master/docs/devel/RELEASE.md#building

**Comment by anderseknert** [comment]
Cleaning up some older issues, and given that we've not heard other requests for this, I'll close it. If someone still finds this important, let us know!
