### ISSUE TITLE
Please provide actionable info for error "object value has non-string key (<nil>)"

### ISSUE THREAD

**Issue by fadycopty** [open-policy-agent/opa#2229]
# Expected Behavior
Error "object value has non-string key (<nil>)" show a line number and suggest a way to fix the problem

# Actual Behavior
The full error is "object value has non-string key (<nil>)"

# Steps to Reproduce the Problem

**Comment by patrick-east** [comment]
Thanks for filing an issue @fadycopty. Could you provide some additional context and/or steps to reproduce the problem?

**Comment by patrick-east** [comment]
@fadycopty I'm going to close this, if you have any more context or steps to reproduce please feel free to reopen
