### ISSUE TITLE
Publish arm64 binaries and container images

### ISSUE THREAD

**Issue by povilasv** [open-policy-agent/opa#2233]
# Expected Behavior

It would be great if it was possible to run open-policy-agent on arm64 architecture, via multi arch container images (https://docs.docker.com/engine/reference/commandline/manifest/#create-and-push-a-manifest-list) 

Muliarch images show on dockerhub:

![image](https://user-images.githubusercontent.com/22289110/77816813-9a265a00-70ce-11ea-8248-f4e8ea59f1e6.png)

Those images seamlessly run on supported architectures

**Comment by patrick-east** [comment]
This should already be supported by just specifying the `GOARCH` option and building OPA from source.

Ex:

```
$ make build GOARCH=arm64 GOOS=linux
make: '_obj/opa.wasm' is up to date.
cp wasm/_obj/opa.wasm internal/compiler/wasm/opa/opa.wasm
GO111MODULE=on GOFLAGS=-mod=vendor go generate
GO111MODULE=on GOFLAGS=-mod=vendor go build -o opa_linux_arm64 -ldflags "-X github.com/open-policy-agent/opa/version.Version=0.19.0-dev -X github.com/open-policy-agent/opa/version.Vcs=88d6ca32 -X github.com/open-policy-agent/opa/version.Timestamp=2020-03-29T02:25:25Z -X github.com/open-policy-agent/opa/version.Hostname=Patricks-MacBook-Pro.local"
$ file opa_linux_arm64
opa_linux_arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=j_yyDbC8Pu-fQJ7oq9VH/6aqO2bg5NvfQoXMp8jgo/8bT9gva510YbDWZxDm3j/q9AxXn6FTP1ORmwqT4AC, not stripped
```

To make the container image for this you'd just need to grab the OPA source and use the `golang` base image (similar to what OPA does https://github.com/open-policy-agent/opa/blob/master/Makefile#L170) then copy the binary into the base image you want to use (see https://github.com/open-policy-agent/opa/blob/master/Dockerfile for reference, it doesn't need to do a whole lot).

**Comment by patrick-east** [comment]
I think there are a few things we'd want to do to add support:

* Add arm binaries to be part of the "release" Makefile target(s)
* Add support for publishing multi-arch images
* Update travis to build/push the arm binaries with the others

**Comment by pieterv-icloud-com** [comment]
I tried deploying opa using helm on a Rancher k3s cluster running on a number of Raspberry Pis.

The deployment fails with an "exec format error" message

opa only supports the amd64 architecture, not the arm/v6 architecture.

**Comment by anagarjunr** [comment]
would love to have to this as we would use arm64 ec2 instances

**Comment by srenatus** [comment]
ℹ️ We cannot support wasm on that architecture yet, so if you're reading this try setting WASM_ENABLED=0 in your custom builds. 

I've brought this to the attention of the fine folks working on wasmtime-go: https://github.com/bytecodealliance/wasmtime-go/issues/79

**Comment by srenatus** [comment]
Times have changed, aarch64 and wasmtime-go should work now.

So, what remains to be done for this is building and testing. There's ways to do that on github actions using either docker buildx or some multi-arch qemu thing, with prior art in github.com/bytecodealliance/wasmtime, for example.

**Comment by manelpb** [comment]
+1

**Comment by srenatus** [comment]
Relevant: #4044 -- but that doesn't mean were publishing these images (yet), so this issue is still relevant.

**Comment by manelpb** [comment]
bump

**Comment by anderseknert** [comment]
@manelpb If you want to endorse the issue, just "vote" on it by liking (i.e. thumbs up emoji) the original description. Saying "bump" or "+1" just adds noise, and as such tend to have the opposite effect on maintainers ;)

**Comment by srenatus** [comment]
Take that, stalebot. Thanks  again @ngraef
