### ISSUE TITLE
Potential issue with opa fmt when interacted via stdin

### ISSUE THREAD

**Issue by psibi** [open-policy-agent/opa#2235]
# Expected Behavior

Should properly format and write out the code

# Actual Behavior

Produces no output. (This has a side effect of deleting the entire code when this is integrated with editors!)

# Steps to Reproduce the Problem

This is a sample step to reproduce:

``` 
$ opa fmt
package hello

hello = "world"
Ctrl-D
$
```

Note that if `Ctrl-D` is pressed without entering a newline, it works as expected:

```
$ opa fmt
package hello

hello = "world"Ctrl-D
package hello

hello = "world"
$
```

# Additional Info

This is much frequently reproduced when automatic formatting is enabled on the emacs major mode for rego: https://github.com/psibi/rego-mode

**Comment by patrick-east** [comment]
I think this is normal, you either have to have a newline+ctrl-d or use two ctrl-d's to indicate that the input is done. If you do just a single ctrl-d it bash (not sure if its just bash, or linux, etc) just sends the line without an EOF. So you need either the newline or the second ctrl-d to get the EOF through.

You get the same behavior with other unix-y tools like (try it out with `wc` or something)

**Comment by psibi** [comment]
@patrick-east 

>  you either have to have a newline+ctrl-d 
But I'm having a "newline + Ctrl-D" in the first example and it reproduces the bug.

**Comment by patrick-east** [comment]
Sorry! I totally misread the issue from the first example. That is _not_ normal 😄

**Comment by patrick-east** [comment]
Looks like this might be intentional behavior if there are no changes after formatting:

https://github.com/open-policy-agent/opa/blob/29d8fbbef6facc96d03be3e07473d12e38acd843/cmd/fmt.go#L161-L164

Will need to look into why it does that, and if we are OK with changing that behavior.

In the short term with the plugin if you can just check if it has nothing in stdout from `opa fmt` it should be assumed that there were no changes required to the original content.

**Comment by patrick-east** [comment]
> Will need to look into why it does that, and if we are OK with changing that behavior.

Checked with the team and we're ok to make the behavior change to _always_ write the formatted policy to stdout.

**Comment by psibi** [comment]
Thanks @patrick-east for the quick update. :-) I'm happy that this is getting fixed!
