### ISSUE TITLE
OPA sends status reports without a reason

### ISSUE THREAD

**Issue by brumer** [open-policy-agent/opa#2236]
# Expected Behavior
OPA sends status reports when bundles are downloaded and activated – If the bundle download or activation fails for any reason, the status update will include error information describing the failure. This includes Discovery bundles.

# Actual Behavior
OPA sends status reports after every download regardless if the bundle was activated or not.
(should not send a status report if the bundle had the same ETAG)

**Comment by tsandall** [comment]
@brumer as of v0.17.0 OPA will send status updates to indicate that OPA _tried_ to download a bundle. This allows status API implementations to easily determine (via the last request timestamp) that OPA deployments are checking in. Can you elaborate on why this is a problem?

**Comment by brumer** [comment]
In my deployment, I have a lot of OPA instances, each instance downloads a lot of bundles which causes the status reports to be sent none stop.
It got to the point I started to see CPU impact.

is it possible to have this reporting behavior configurable?

**Comment by tsandall** [comment]
@brumer not today -- though we could add a flag that lets you disable reporting when OPA _attempts_ to download a bundle. This would reduce the # of status messages you see.

**Comment by brumer** [comment]
such a flag would be helpful, thanks.

**Comment by patrick-east** [comment]
I filed #2252 to track that enhancement.
