### ISSUE TITLE
[opa-istio-plugin] Wait for bundles on opa sidecar startup

### ISSUE THREAD

**Issue by michaelwittig** [open-policy-agent/opa#2242]
# Expected Behavior
The injected OPA sidecar does not wait to serve traffic until bundles are fetched

# Actual Behavior
1. The injected OPA sidecar starts
2. All request from now on are rejected if we rely on bundles
3. Bundles are downloaded
4. AuthZ works

# Additional Info
This issue can be fixed by adding the a probe here: https://github.com/open-policy-agent/opa-istio-plugin

```json
"readinessProbe": {
    "httpGet": {
      "path": "/health?bundles",
      "port": 8181
    }
},
```

Let me know if this is an acceptable fix.

I wonder if startupProbe might be a better fit (doesn't work on GCP Cloud Run for Anthos).

```json
"startupProbe": {
    "httpGet": {
      "path": "/health?bundles",
      "port": 8181
    },
    "failureThreshold": 20,
    "periodSeconds": 3
},

**Comment by patrick-east** [comment]
Using a probe like:

```
"readinessProbe": {
    "httpGet": {
      "path": "/health?bundles",
      "port": 8181
    }
},
```
Seems like the right solution. Seems like maybe just updating the docs and manifests we publish?

**Comment by michaelwittig** [comment]
see https://github.com/open-policy-agent/opa-istio-plugin/pull/171

**Comment by michaelwittig** [comment]
merged
