### ISSUE TITLE
Deprecate (and eventually remove) the `?watch` option from the REST API

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2265]
The `?watch` option for the REST API is not widely used (if at all) and adds quite a bit of complexity into the server.. which is prone to having bugs as a result of the additional complexity.

Due to it not really being used we should deprecate the option and eventually remove it altogether.

First steps:

* Log a depreciation warning whenever it is used
* Remove it from the documentation
* Mark code in OPA source as deprecated
* Put a notice in the changelog

**Comment by tsandall** [comment]
The changes above are in. Let's schedule removal for v0.24.0 (the release after next).
