### ISSUE TITLE
Deprecate (and eventually remove) the `?partial` option from the REST API 

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2266]
**NOTE: This does not deprecate partial evaluation itself, just a REST API query parameter that triggers it on certain calls. Partial evaluation is still supported.**

The `?partial` option on the REST API will do a partial evaluation of the query, cache that, and then return the result. Subsequent requests will use the cached partial result to evaluate the query.

The downside to this is that partial evaluation puts several slow things into the "hot" path for evaluations of OPA, and the cache is cleared any time data changes. This means that occasionally requests will have severely increased latency, which is not ideal.

What we should do is deprecate the `?partial` flag, and move towards doing more automatic optimizations with partial evaluation in the background of the server (maybe when bundles are loaded), as well as pushing more for users that benefit from partial evaluations to consider doing it prior to loading policies into the OPA runtime.

First steps:

* Log a depreciation warning whenever it is used
* Remove it from the documentation, and suggest alternative approaches
* Mark code in OPA source as deprecated
* Put a notice in the changelog

**Comment by tsandall** [comment]
The changes above are in. Let's schedule removal for v0.24.0 (the release after next).
