### ISSUE TITLE
Change the `tls_use_system_certs` default to true

### ISSUE THREAD

**Issue by jpeach** [open-policy-agent/opa#2271]
The default for the `http.send` parameter `tls_use_system_certs` has always been false, but most users probably expect Rego to do some sort of server certificate validation, so using the system CA store by default seems like a more reasonable default.

Not sure about the compatibility aspects of this. If the default changes, then some validations that previously didn't succeed may now succeed.

**Comment by patrick-east** [comment]
> Not sure about the compatibility aspects of this. If the default changes, then some validations that previously didn't succeed may now succeed.

Yea.. not sure about that either. I tend to agree that most people would assume that system certs to be the default.

I'm OK with making the change. I think generally speaking the system CA certs are trusted (hence why they're packaged with the OS and/or curated by the system owner).

**Comment by patrick-east** [comment]
Chatted with @tsandall about this briefly. We're good to make this change but we will need to enforce that if a user specified a specific CA file/env var and did not specify any value for `tls_use_system_certs` then we default to the old behavior of _only_ using the specified ones. So the behavior should be like:

| `tls_use_system_certs` | `tls_ca_cert_file`  or `tls_ca_cert_env_variable` | cert pool |
|---|---|---|
| n/a | n/a |   system | 
| `true` | n/a |   system | 
| `false` | n/a |  no CA's | 
| n/a | provided |   provided file | 
| `false` | provided |  provided file | 
| `true` | provided |  system + provided file |

**Comment by jpeach** [comment]
@patrick-east Yep, that table looks reasonable to me. I'll try to get to this, but it will be a little while :)

**Comment by patrick-east** [comment]
> I'll try to get to this, but it will be a little while :)

No worries, just us know when/if you get around to it and I'll assign the issue to you. Until then we'll leave it open for anyone to contribute.

**Comment by timakin** [comment]
@patrick-east Your table shows the conditional branch is not so different from the original.
However, 4th is the key.
If you’d like to use provided certs when the flag is n/a(as a default, true), you have to distinguish n/a and a real true flag.
How do you imagine the implementation become?
Changing this bool var into bool pointer seems a realistic method, right?

**Comment by patrick-east** [comment]
Yep, if you change 

https://github.com/open-policy-agent/opa/blob/e6ac0a0753d0b984014ea841d63b2c76bd62b671/topdown/http.go#L177

to a pointer we can check for `nil` to distinguish when it was passed in.

Then we would need to make some conditional check to "default" it to `true`, but only if all of the 3 CA options were empty/not provided.

https://github.com/open-policy-agent/opa/blob/e6ac0a0753d0b984014ea841d63b2c76bd62b671/topdown/http.go#L249-L254

**Comment by tsandall** [comment]
@patrick-east it looks like this hasn't been sorted yet. I'm going to assign @frankiecerk who is interested in working on this.

**Comment by olamiko** [comment]
@anderseknert, thank you for suggesting this issue. Please can you assign this to me?

**Comment by anderseknert** [comment]
Sure thing @olamiko 👍 You probably did already, but if not then make sure to start with reading what's already been said in this ticket :) Let me know if you need any help with this, either here on on the OPA Slack.
