### ISSUE TITLE
prometheus section in monitoring had a wrong config 

### ISSUE THREAD

**Issue by NewbMiao** [open-policy-agent/opa#2277]
# Expected Behavior

There is a wrong config in https://www.openpolicyagent.org/docs/latest/monitoring/#prometheus

# Actual Behavior

```yaml
global_config:
  scrape_interval: 15s
```
should be

```yaml
global:
  scrape_interval: 15s
```

# Steps to Reproduce the Problem

  1. `brew install prometheus`
  2. `promtool check config prometheus.yml`
  Or `docker run -p 9090:9090 -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus`

# Additional Info

**Comment by patrick-east** [comment]
Thanks @NewbMiao !

Interestingly enough in https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config they show the default as being:

```
 # How frequently to scrape targets from this job.
[ scrape_interval: <duration> | default = <global_config.scrape_interval> ]
```

But I suspect that is old, there was a change at some point that looks like it renamed from `global_config` to just `config` https://github.com/prometheus/prometheus/commit/a703241bf8fb792f2bfe893b6675264538ecf704#diff-46feeb6751071cb78392915fc8f622aa

**Comment by NewbMiao** [comment]
@patrick-east  Yep, but seems you had a tyro: `global_config`to `gloabl`

BTW. When i explore opa bundle and monitor stuff, i built some demo for this. 
Hope it will be helpful for some newer to opa bundle:

https://github.com/NewbMiao/opa-koans/tree/master/bundle
