### ISSUE TITLE
Documentation on base/virtual document lost in upgrade

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#2284]
# Expected Behavior

The docs used to have a section on the base document, virtual documents and their relation to policies: https://www.openpolicyagent.org/docs/v0.13.5/how-does-opa-work/

These docs were very useful to help connect the OPA dots!

# Actual Behavior

No current documentation covering the topic.

# Additional Info

There are still links scattered around in the docs pointing to the "how-does-opa-work" page for en explanation of the base/virtual document, though that's not really explained by that page anymore.

**Comment by tsandall** [comment]
Thanks for filing this @anderseknert! We'll bring this page back (albeit not inside the intro) soon.
