### ISSUE TITLE
Example for PartialResult is using PartialEval

### ISSUE THREAD

**Issue by itaysk** [open-policy-agent/opa#2294]
The example for `PartialResult` is using `PartialEval`. Probably a leftover from the deprecation of `PartialEval` https://github.com/open-policy-agent/opa/blob/master/rego/example_test.go#L389

**Comment by patrick-east** [comment]
Good catch @itaysk! we should get that updated.

**Comment by agarwalrounak** [comment]
Can I take up this issue?
