### ISSUE TITLE
Remove -l flag from test subcommand

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2306]
In 8edf554c6092d2885e2c4feefe00980a11729997 we have marked the `opa test -l` flag as deprecated so we should remove it eventually.

**Comment by anderseknert** [comment]
Not really, no @damienjburks ... I guess it's more a question of whether it's safe to remove it now. Considering it's been deprecated with a warning printed for almost two years, I think it is. Would you agree @tsandall?

**Comment by damienjburks** [comment]
If it's safe to remove, I'd love to dive in and take it out.

**Comment by tsandall** [comment]
Yep, let's remove it.
