### ISSUE TITLE
Navigation links wrapping incorrectly on the website

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2319]
# Expected Behavior

<img width="994" alt="Screen Shot 2020-04-20 at 9 21 40 AM" src="https://user-images.githubusercontent.com/238885/79756295-6f53ae00-82e8-11ea-8d42-856bda07b497.png">

# Actual Behavior

<img width="1182" alt="Screen Shot 2020-04-20 at 9 21 14 AM" src="https://user-images.githubusercontent.com/238885/79756260-6236bf00-82e8-11ea-9a2f-2cbb59733748.png">

**Comment by arunbsar** [comment]
@tsandall I will work on this

**Comment by tsandall** [comment]
Closing this for now. The current behaviour is that the hamburger shows up once you shrink the window enough.
