### ISSUE TITLE
OPA APIs Enhancement

### ISSUE THREAD

**Issue by jingnanzhou** [open-policy-agent/opa#2336]
# Expected Behavior
In OPA GO library,  when creating a new rego via  rego.New, we would like to directly use string or byte[] for policy input, not via file name  to load string/byte[] (via rego.Load )

**Comment by patrick-east** [comment]
You can do that via the `Module` option https://godoc.org/github.com/open-policy-agent/opa/rego#Module

You still have to provide a "filename" but its really just metadata (used in error messages and stuff)

**Comment by patrick-east** [comment]
Update: For `input` you can use the https://godoc.org/github.com/open-policy-agent/opa/rego#Input

Example: https://godoc.org/github.com/open-policy-agent/opa/rego#example-Rego-Eval-Input

**Comment by tsandall** [comment]
@jingnanzhou let us know if you need more pointers or if there's some gap in the Go API that needs to be filled.

**Comment by SidharthBansal** [comment]
I will be happy to participate in Community Bridge with OPA
https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md
Shall anyone help me on how to get started?

**Comment by jingnanzhou** [comment]
> @jingnanzhou let us know if you need more pointers or if there's some gap in the Go API that needs to be filled.

@tsandall Thank you for following up.  @patrick-east provided very helpful information.  For this particular issue, we can close.  We are extensively using OPA Go Library, I am sure we will discover more gaps. Thanks for support again
