### ISSUE TITLE
units.parse_bytes does not support standard Kubernetes suffixes

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2340]
The following errors because "Mi" is not considered valid. However, since this built-in was originally added to support resource quantities in Kubernetes, it seems like a bug to me.

```
units.parse_bytes("128Mi")
```

Perhaps we just need a powers-of-2 conversion string conversion? E.g., `units.parse_pow2("128Mi")`

**Comment by GBrawl** [comment]
As a simple fix we could add the units to the switch case located here:

https://github.com/open-policy-agent/opa/blob/master/topdown/parse_bytes.go#L66

or the parse_pow2 builtin would also be an option, if you tell me which you prefer I could make a PR for this.

**Comment by patrick-east** [comment]
I'd be inclined to update parse_bytes to support the units that omit the `b`/`B` in the unit. The implication of calling `parse_bytes` is that you are parsing some number of bytes so it follows that someone could pass in `"128M"` and the expectation is that you wanted 128 mega*bytes*

If its confusing or something that we would want to make more generic there's no reason we couldn't expose a `units.parse_pow2` later on in the future too (probably just sharing code with `units.parse_bytes`).

**Comment by tsandall** [comment]
@patrick-east that's a good point--it would be kind of annoying to have to check if the string has a suffix and then use a different built-in function. I think we should go w/ your suggestion.
