### ISSUE TITLE
calling functions from HTTP API

### ISSUE THREAD

**Issue by andriyfomenko** [open-policy-agent/opa#2359]
# Expected Behavior

POST /v1/query
{
"input": ...,
"query": "my_var := data.my_package.my_function(..)"
}
I'm expecting to get result similar to the one I would get if evaluating my function in VSC 

# Actual Behavior

My result is empty, trying to check for input shows it is not getting recognized

What is the right way of making a query where input is injected from the POST and I evaluate some function I defined?

**Comment by ashutosh-narkar** [comment]
I believe you would have to wrap your function in a rule and call the rule. For example:

_policy.rego_
```
package foo

default allow = false

allow {
    is_allowed(input.message)
}

is_allowed(msg) {
    msg == "hello"
}
```

Query the `allow` rule:
```
$  curl -X POST -H "Content-Type: application/json" -d '{"input": {"message": "hello"}}' localhost:8181/v1/data/foo/allow

{"result":true}
```

**Comment by andriyfomenko** [comment]
thanks for explanation!
I was under impression I'm doing something wrong.

**Comment by tsandall** [comment]
Just to add to what @ashutosh-narkar said, you _can_ execute ad-hoc queries today for example:

```
curl -d '{"query": "x:=sort([3,2,1])"}' localhost:8181/v1/query
```

Results in:

```
{"result":[{"x":[1,2,3]}]}
```

The response contains a result set (i.e., a set of variable assignments that satisfy the query). In this case, there is one assignment to `x` that satisfies the expression `sort([3,2,1])`. If there are no variables in the query the result set will contain empty objects:

```
$ curl -d '{"query": "sort([3,2,1])"}' localhost:8181/v1/query
{"result":[{}]}
```

In this case, there's one result but no variables so the result set is `[{}]`.

If the query is undefined (i.e., the result set is empty) then the result key will be omitted entirely:

```
$ curl -d '{"query": "[3,2,1] = sort([3,2,1])"}' localhost:8181/v1/query
{}
```

However, all this said, @ashutosh-narkar's answer is the right one--you probably just want to point clients at the `v1/data` endpoint as they rarely need to execute arbitrary queries.
