### ISSUE TITLE
panic: unable to start write transaction when store was provided

### ISSUE THREAD

**Issue by aaahrens** [open-policy-agent/opa#2362]
# Expected Behavior
Just to Evaluate the query

# Actual Behavior
Crashes

# Steps to Reproduce the Problem

  1. Use code snippet below on any dummy main.rego file 

# Additional Info
Code snippet is below, I think this is expected behaviour but can't seem to find examples that provide a workaround.

```
func main() {
	ctx := context.Background()
	data := make(map[string]interface{})
	store := inmem.NewFromObject(data)
	t, err :=  store.NewTransaction(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Println(t.ID())
	j, _ := json.Marshal(authorization.Input{
		UserID: "uuid",
	})
	reg := rego.New(
		rego.Query("x = data.rbac"),
		rego.Store(store),
		rego.Input(j),
		rego.Load([]string{"rbac/main.rego"}, nil),
	)
	q, err := reg.Eval(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Println(q)
}
```

**Comment by patrick-east** [comment]
When using `rego.Load` https://godoc.org/github.com/open-policy-agent/opa/rego#Load OPA will need a "write" transaction for the store. What you've got right now is the default, which is a "read" transaction.

There is an example that shows how to create and use a write transaction over in https://godoc.org/github.com/open-policy-agent/opa/rego#example-Rego-Eval-Transactions

**Comment by aaahrens** [comment]
Thank you!  (Also thanks for your insanely fast response) :D
