### ISSUE TITLE
eval.go is using PartialEval instead of PartialResult

### ISSUE THREAD

**Issue by sresthas** [open-policy-agent/opa#2364]
It is using PartialEval instead of PartialResult, PartialEval is deprecated. 
 https://github.com/open-policy-agent/opa/blob/master/topdown/eval.go#L1920

**Comment by patrick-east** [comment]
Hi @sresthas , can you elaborate more on the issue? I'm not sure that this applies to the `topdown` package.

**Comment by sresthas** [comment]
I am not sure, I just opened it because I thought PartialEval is deprecated. This case might be an exception.

**Comment by patrick-east** [comment]
Going to close this one out, the usage in eval.go is a different case.
