### ISSUE TITLE
possible race in decision logs

### ISSUE THREAD

**Issue by brumer** [open-policy-agent/opa#2365]
# Expected Behavior
Decision logs should be written with the correct bundles loaded at the time of the decision

# Actual Behavior
We are loading bundles into OPA using the discovery bundle feature.
We noticed a situation where a query that depends on data loaded from a bundle returned an unexpected result.
The decision log for that query shows that the bundle was loaded with the correct revision.
A few milliseconds later a different decision log from the same OPA showed that the bundle was no longer listed under the "bundles" key, meaning it was removed from the discovery bundle and later from OPA.
Could it be that the bundle was removed from OPA while the decision log still reported it loaded?

# Steps to Reproduce the Problem

  1. Use discovery to load bundles into OPA
  2. Query OPA while removing a bundle from the discovery
  3. the result based on the bundle should fail while the decision log should show the bundle is still loaded

**Comment by patrick-east** [comment]
Thanks for the bug report @brumer 

If you can provide a few more details it would greatly aid in getting a fix for this:
* What version of OPA did you see the issue with?
* What configuration was used (in particular decision logs, discovery, bundles, etc)
* How was OPA run (eg. stand-alone`opa run -s`? Golang API's? etc)
* Does this occur only at startup (initial discovery bundle load?) Or any change for the discovery configuration?
* Can you provide logs from OPA when it occurs? In particular we would want to see when the different bundle downloads/updates occurred along with the requests that had the incorrect results.
* How consistent is the issue?

**Comment by brumer** [comment]
Thanks for the quick response @patrick-east 

- The OPA version being used is v0.17.3
- OPA is being run with `opa run --server --pprof --log-level=error --config-file=config.yaml`
- The configuration used is for discovery configured with bundles, status reporting and decision log plugin (specifically using [this example](https://www.openpolicyagent.org/docs/latest/extensions/#putting-it-together) to write to stdout the decision logs)
- I only noticed it happening once and during a discovery configuration change (not the initial load)
- because OPA is being run with `--log-level=error` I only had the decision logs that are being written to stdout
- I no longer have the logs but I saw it once and it was very clear: every decision log had the same result with the same input and the same bundle revision specified under "bundles" except for one that had an empty result for the same input with the same bundle revision still specified under "bundles".
In the next decision log (~100 milliseconds later) the bundle revision was no longer listed under "bundles".
It's normal for the bundle to be removed from the discovery but that one decision log with the bundle revision specified and still no result shouldn't have happened.

**Comment by patrick-east** [comment]
I suspect that this issue has been corrected by https://github.com/open-policy-agent/opa/commit/05761a8dec20f4f8e28cfc643d7b9297072abf98

Previously the decision logger was able to be out of sync with the storage transaction used for the query, which would have affected what revisions it reported.

@brumer any chance you could verify the issue is resolved with the current `edge` version of OPA?

**Comment by brumer** [comment]
Unfortunately, I don't have a way to recreate this issue but looking at the commit I think moving `s.getDecisionLogger()` inside the storage transaction fixed it.

Thanks for the help!
