### ISSUE TITLE
Integration doc has two compile errors in example Go code

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2367]
The Go integration section in https://github.com/open-policy-agent/opa/blob/master/docs/content/integration.md contains two errors in the example code:

1. `module` is not defined anywhere. `module` should be defined as a string variable that contains the example policy from earlier in the page.

2. `context.Context` should just be `ctx.

**Comment by sresthas** [comment]
Can I take this up?

**Comment by patrick-east** [comment]
@sresthas I've assigned the issue to you, let us know if you need any guidance.

**Comment by agarwalrounak** [comment]
Can I take this issue up?

**Comment by agarwalrounak** [comment]
Can I take this issue up? I have figured out the corrections needed to be made to resolve this issue.

**Comment by patrick-east** [comment]
@sresthas were you still working on this one?
