### ISSUE TITLE
Remove gopkg.in/yaml.v2 dependency

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2377]
[A while ago](https://github.com/open-policy-agent/opa/commit/346aa964e8a542dd0cc2ec030fc0617c8aaa702a#diff-a02872f5f4d9adce6db6154b9e13c173) we vendored another yaml library as a result of depending on it inside the bundle config validation tests. gopkg.in/yaml.v2 behaves slightly differently than the ghodss library that we use elsewhere in OPA (the differences manifest in the generic/interface{} result types that get returned from parsing YAML.) I ran into because my editor automatically imports packages for me and it decided to use the gopkg.in/yaml.v2 while I was in the middle of refactoring. This resulted in some head scratching because I couldn't understand how the refactoring could have broken the code. I think the simplest solution is to just remove the use of gopkg.in/yaml.v2 inside the bundle config validation tests.

**Comment by patrick-east** [comment]
I'm not sure we can remove it completely. At best I think we can remove its usage in OPA, but other dependencies will still cause it to be included. 
```
{11:45} ~/p/g/s/g/o/opa:VineethReddy02-vineeth-fix-import-nit ◈ ❯ ag 'yaml.v2'
<snip>
vendor/golang.org/x/tools/internal/module/module.go
47:// For example, the path "yaml/v2" only corresponds to
328:		// For example, gopkg.in/yaml.v2@v2.2.1's go.mod requires gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405.

vendor/github.com/spf13/cobra/doc/yaml_docs.go
26:	"gopkg.in/yaml.v2"

vendor/github.com/ghodss/yaml/yaml.go
11:	"gopkg.in/yaml.v2"
154:		// From my reading of go-yaml v2 (specifically the resolve function),
<snip>
```

Which includes the other yaml library.. https://github.com/ghodss/yaml/blob/25d852aebe32c875e9c044af3eef9c7dc6bc777f/go.mod#L3

**Comment by tsandall** [comment]
Closing this because fixing this would involve removing dependencies on cobra and ghodss/yaml.
