### ISSUE TITLE
OPA example - API authorization

### ISSUE THREAD

**Issue by debasisc-opa** [open-policy-agent/opa#2392]
Trying example from https://github.com/open-policy-agent/opa

`
C:\OPA>opa_windows_amd64.exe run data.json
OPA 0.19.2 (commit 40f9c1fe, built at 2020-04-27T22:51:13Z)

Run 'help' to see a list of commands.

> default allow=false
Rule 'allow' defined in package repl. Type 'show' to see rules.
> allow{
| input.method = "GET"
| input.method = ["salary",id]
| input.user.id=id
| }
|
Rule 'allow' defined in package repl. Type 'show' to see rules.
> allow{
| input.method="GET"
| input.path=["salary",id]
| managers=data.management_chain[id]
| input.user_id=managers[_]
| }
|
Rule 'allow' defined in package repl. Type 'show' to see rules.
`

The following works -
`
> data.management_chain["bob"]
[
  "ken",
  "janet"
]
>
`
But the following query fails -
`
> input := {"method": "GET", "path": ["salary","bob"], "user_id": "bob"}
2 errors occurred:
3:1: rego_type_error: match error
        left  : string
        right : array<string, ???>
4:1: rego_type_error: undefined ref: data.repl.input.user.id
        data.repl.input.user.id
                        ^
                        have: "user"
                        want (one of): ["method" "path" "user_id"]
`

Can you please check and advise?

Thank you

**Comment by ashutosh-narkar** [comment]
@debasisc-opa `input.method = ["salary", id]` should be `input.path = ["salary", id]`. There seems to be a typo.

**Comment by tsandall** [comment]
Like @ashutosh-narkar mentioned, the rule is not defined as it's written in the README. Two issues:

1. `input.method = [...]` results in a match error because `input.method` is a string and the RHS is an array.
2. `input.user.id=id` results in a ref error because `input.user.id` is never defined (we've defined input statically so we know this statement is never true.

**Comment by debasisc-opa** [comment]
Thank you. This now works well.
`
> input := {"method": "GET", "path":["salary","bob"], "user_id": "bob"}
Rule 'input' defined in package repl. Type 'show' to see rules.
> allow
true
`
