### ISSUE TITLE
Correct time comparison in Envoy Authorization tutorial doc

### ISSUE THREAD

**Issue by pvsone** [open-policy-agent/opa#2395]
# Expected Behavior
In the Envoy tutorial (https://www.openpolicyagent.org/docs/latest/envoy-authorization/), the `is_token_valid` rule in policy.rego should evaluate to true for the sample tokens

# Actual Behavior
It evaluates to false, as the time comparison is comparing `time.now_ns()` (a value in nanoseconds) to the token `nbf` and `exp` fields which are values in seconds.  

# Steps to Reproduce the Problem
Open the policy from Step 3 in the Rego Playground via the playground link (https://play.openpolicyagent.org/p/252FCEX43z).  Evaluate the selection fo `is_token_valid`

To workaround, I updated the policy to:
```
is_token_valid {
  token.valid
  now := time.now_ns() / 1000000000
  token.payload.nbf <= now
  now < token.payload.exp
}
```

**Comment by princespaghetti** [comment]
I'll grab this one!

**Comment by ashutosh-narkar** [comment]
Thanks @princespaghetti !
