### ISSUE TITLE
h2c support rest api

### ISSUE THREAD

**Issue by drewwells** [open-policy-agent/opa#2399]
Thanks for opening an issue to request a feature or file a bug! If you provide some
basic information it helps us address problems faster.

# Expected Behavior
CLI flag to enable h2c support
# Actual Behavior
No mentions of h2c in the github repo
# Steps to Reproduce the Problem
Connect to opa with a h2c client. See that the connection does not upgrade to http/2. This requires importing the http2/h2c package the server transport. See a walkthrough here: https://www.mailgun.com/blog/http-2-cleartext-h2c-client-example-go/

**Comment by tsandall** [comment]
@drewwells could you provide some info on why you want H2C support? I'm guessing it's performance related--have you tried using a UNIX domain socket instead? Would that work for your use case? I'm curious how much H2C improves performance over that.

**Comment by drewwells** [comment]
so we can connect http/2 without TLS. We have a lot of headers that are invalid for http/1

**Comment by tsandall** [comment]
@patrick-east do you have any opinions here? I'd imagine we could just plumb the flag down into the server that enables this fairly easily. I think I tried this out a while ago and just didn't do anything with it because the performance benefit was minimal.

**Comment by gaga5lala** [comment]
@tsandall I'd like to contribute some code, does this suit for beginner? or do you have other suggestion? Thanks.

**Comment by patrick-east** [comment]
@gaga5lala this one may not be a good one to start with, depends on how familiar you are with the h2c support in golang. Check out the ones labeled with "low-hanging-fruit":  https://github.com/open-policy-agent/opa/labels/low-hanging-fruit for some (potentially) better issues to start with

**Comment by tsandall** [comment]
Fixed by #2739
