### ISSUE TITLE
[Feature Request] Container image for CI

### ISSUE THREAD

**Issue by marshallford** [open-policy-agent/opa#2404]
**Background:** At work we use Jenkins for CI and I'm getting into the habit of using the [Jenkins Kubernetes Plugin](https://github.com/jenkinsci/kubernetes-plugin) to manage pipeline dependencies as code. The plugin allows shell commands to be run from within the context of a container image. This has worked great for doing things like validating YAML via `kubeval` or linting files with `editorconfig-checker`.

**The Gotcha:** There are two requirements that must be met in order to use a container image with this Jenkins plugin. 1) A shell (`/bin/sh`, `/bin/bash`, etc) in the image. 2) A binary such as `cat` to keep the container running instead of immediately exiting. It is possible that other CI tools have the same or similar requirements, although to be fair I have not validated this suspicion.

**My ask:** I'd like to see a fourth container image built by Travis that uses a more fully featured base image (with a shell) that also adds `opa` into the `$PATH` of the container. That would allow folks to run `opa test` in Jenkins without curling the binary on every Jenkins run.

My attempt at solving this issue should be in PR form shortly, but feel free to declare out of scope.

Thank you!

**Comment by patrick-east** [comment]
Thanks for filing this @marshallford its a topic that has come up a number of times. Historically we have recommended a few alternatives to having OPA start to support more images.

1) Use the *-debug OPA image, we build it based on the "distroless" base so the instructions here https://github.com/GoogleContainerTools/distroless#debug-images apply for the OPA images. Ex:
```
{14:28}  ~/p/g/s/g/o/opa:master ✓ ❯ docker run --rm -it --entrypoint=sh openpolicyagent/opa:0.19.2-debug
Unable to find image 'openpolicyagent/opa:0.19.2-debug' locally
0.19.2-debug: Pulling from openpolicyagent/opa
Digest: sha256:7c037c7f3a4ced7fc1fec99192c9298548f7032a48cec18602f820cbd8289a11
Status: Downloaded newer image for openpolicyagent/opa:0.19.2-debug
/ # which cat
/busybox/cat
/ # which bash
/ #
```
The downside for your usecase is that there is no bash installed (as seen above). Which leads to..

2) Build and maintain your own CI image of OPA. Typically for organizations maintaining another image is kind of a drop in the bucket.. especially when all you need is a Dockerfile like:

```Dockerfile
FROM ubuntu:20.04

COPY --from=openpolicyagent/opa:0.19.2 /opa /bin/opa

# Whatever custom tools you want
#RUN apt-get update && apt-get install -y \
#    build-essentials
```

The reasoning for the push back is that it's kind of a slippery slope. It starts with one CI image based on maybe alpine, then someone needs debian, someone else needs RHEL, someone needs a different set of base packages... soon we have a lot of things to worry about keeping patched/updated/documented.

**Comment by tsandall** [comment]
I agree with @patrick-east that we should minimize the number of artifacts we generate and therefore have to maintain. @marshallford do you need bash specifically or is a POSIX compliant shell enough? If so, I'd recommend just going with -debug like @patrick-east suggested. Perhaps we should re-tag -debug to indicate it's useful for more than just debugging?

**Comment by marshallford** [comment]
@patrick-east the debug container image you suggested worked perfectly for my Jenkins use-case. For posterity's sake, see below for a minimal Jenkinsfile snippet. As for re-tagging, it was my mistake for missing/trying that image. I don't think it's worth the effort as "debug" should have been plenty clear. Maybe it would be worth adding a table to the readme that describes that various image types?

Thank you both!

```
pipeline {
    agent {
        kubernetes {
        yaml '''
apiVersion: v1
kind: Pod
spec:
    containers:
        -
            name: jnlp
            image: jenkins/inbound-agent:4.3-4-alpine

        -
            name: opa
            image: openpolicyagent/opa:0.19.2-debug
            command:
                - cat
            tty: true
'''
        }
    }
    stages {
        ...
        stage('foobar') {
            steps {
                container('opa') {
                    sh '/opa test -v **/*.rego'
                }
            }
        }
    }
}
```
