### ISSUE TITLE
Use base64 encoding for JSONPatch in opa-istio-plugin/quick_start.yaml

### ISSUE THREAD

**Issue by pvsone** [open-policy-agent/opa#2407]
# Expected Behavior
Modifying the contents of the `patch` object within `inject.rego` (e.g. to update the opa run arguments) should not result in an error when the inject.rego policy is evaluated at runtime

# Actual Behavior
For many types of updates a runtime error occurred, such as:
```
Error from server (InternalError): Internal error occurred: failed calling webhook "istio.openpolicyagent.org": v1beta1.AdmissionReview.Response: v1beta1.AdmissionResponse.PatchType: Patch: decode base64: illegal base64 data at input byte 299, error found in #10 byte of ...|5In19XQ==","patchTyp|..., bigger context ...|vcGEtcG9saWN5In0sIm5hbWUiOiJvcGEtcG9saWN5In19XQ==","patchType":"JSONPatch"}}|...
```

# Steps to Reproduce the Problem
Delete line 108 `"/policy/policy.rego",` and (re-)deploy the quick_start.yaml.  Deploy a pod and k8s will return an error similar to above

# Additional Info
To resolve, I changed the encoding from `base64url` to `base64` on line 83, e.g.
```
"patch": base64.encode(json.marshal(patch)),
```

**Comment by agarwalrounak** [comment]
Can I take up this issue?

**Comment by tsandall** [comment]
@agarwalrounak sure. It should be  oneline change in the quickstart file where the policy is inlined per the issue description.

**Comment by patrick-east** [comment]
@agarwalrounak go for it
