### ISSUE TITLE
Improve http.send with a connection reuse and a concurrency support.

### ISSUE THREAD

**Issue by timakin** [open-policy-agent/opa#2418]
Currently, `http.send` built-in function seems to generate `http.Client` for each requests.
https://github.com/open-policy-agent/opa/blob/c5c85795aaa3701763f98d16308c5944f05f3da4/topdown/http.go#L448

However, it doesn't maximize the scalability with Go `http` package.
So, how about considering the following 2 plans?

- To use the full potential of concurrency, add fields `max_conns_per_host`, `max_idle_conns`, `idle_conn_timeout`, `max_idle_conns_per_host`
- For the connection reuse, add the field `keep_alive(bool)` and store `http.Client` into `map[string]*http.Client` with the key of `url` value.

This may not be so high cost-performance, compared with #1753 , but must be a good help for the environment under frequent transactions.

**Comment by tsandall** [comment]
It would be nice to implement connection re-use for `http.send`. For high-throughput use cases involving http.send, where the policy is queried hundreds or thousands of times per second, the connection resource utilization could add up.

A few thoughts:

* The params you suggested look fine to me. We'll probably need to key the client cache off more than just the URL though--I'd assume any parameters that affect the client configuration would have to be taken into account.

* The http.send function can be instructed to read the TLS certs from disk--we don't have a guarantee that I am aware of on how frequently these files are re-read however currently it's on each request. If we cache the clients we'll need to make sure to invalidate them when the files on disk change. One option would be to check the file modification timestamp.

I'm not sure if there are other "gotchas" that we need to take into account.

**Comment by TheHydGuy** [comment]
Hello everyone,
I have the same issue with http.send failing whenever I have high load to the service. After around 1000 requests in a given minute (may be 1024), the http.send fails with error "too many openfiles" and I believe it is the same issue mentioned here (creating a new client on request) and my container is running out of the open file descriptors.
After that minute, everything works for next 1000 calls before it bombs. Not sure what is the limit for 1000 per min in here. 
Any suggestions/work arounds to mitigate this issue.
Thank you!

**Comment by ashutosh-narkar** [comment]
>After that minute, everything works for next 1000 calls before it bombs. Not sure what is the limit for 1000 per min in here.

@TheHydGuy I'm curious what's the value for `ulimit -n` ?

**Comment by TheHydGuy** [comment]
> > After that minute, everything works for next 1000 calls before it bombs. Not sure what is the limit for 1000 per min in here.
> 
> @TheHydGuy I'm curious what's the value for `ulimit -n` ?

Thank you for the quick response. I'm trying to check that but not sure how to execute the shell command inside the distroless image (envoy-opa).

Could you please share any instructions if you have it handy. Thank you!

**Comment by TheHydGuy** [comment]
> > > After that minute, everything works for next 1000 calls before it bombs. Not sure what is the limit for 1000 per min in here.
> > 
> > 
> > @TheHydGuy I'm curious what's the value for `ulimit -n` ?
> 
> Thank you for the quick response @ashutosh-narkar . I'm trying to check that but not sure how to execute the shell command inside the distroless image (envoy-opa).
> 
> Or I can set ulimt for my container (I know docker has that support while running the container - docker run). I do not know the file to set it to.
> 
> Could you please share any instructions if you have it handy. Thank you!

Update: Increasing the ulimit fixed the issue.

**Comment by ashutosh-narkar** [comment]
With the addition of the inter-query cache and further improvements as part of [this](https://github.com/open-policy-agent/opa/pull/4017) change, we can close this issue.
