### ISSUE TITLE
Deprecate and remove any() and all() functions

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2437]
We should deprecate and eventually remove the `any()` and `all()` built-in functions. Neither of these functions implement behaviour that's otherwise hard to implement in Rego yet their implementation makes some arbitrary assumptions that are problematic (e.g., non-true/false values are not considered "true-ish" like most other Rego constructs asusme, both are satisfied by empty collections, etc.)

The any function is particularly bad since there is almost no difference between saying `any({x | ...})` and simply `...`. Similarly, once we have the every keyword (#2090) the need for `all` will be substantially reduced.

**Comment by gaga5lala** [comment]
Hi @tsandall, does this means to remove built-in ast functions defined in `ast/builtins.go` and relative files (are they mostly defined in https://github.com/open-policy-agent/opa/pull/828?). And then run go test locally (or submit PR wait test result on CI) to check is there any missing pieces?

**Comment by patrick-east** [comment]
@gaga5lala That is correct, however I'm not sure how soon we would want to make the change. These backwards compatibility changes will need to be handled carefully.

**Comment by srenatus** [comment]
💭 While we're at it, should we drop `and` and `or` as non-infix variants of set intersection `&` and union `|`? Those must seem confusing to newcomers.
