### ISSUE TITLE
The default keyword should be honored on functions

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2445]
If you define a function with a default value, the default should be honored if all of the functions with the same name are undefined.

```
package test

default f(x) = 0

f(x) = x { x > 0 }
```

Today the default is ignored. Example:

```
$ opa eval -d x.rego 'data.test.f(1)'
{
  "result": [
    {
      "expressions": [
        {
          "value": 1,
          "text": "data.test.f(1)",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

```
$ opa eval -d x.rego 'data.test.f(-1)'
{}
```

**Comment by srenatus** [comment]
Wasm does that already (see #3389).

**Comment by oren-zohar** [comment]
@tsandall any workaround for this?

**Comment by tsandall** [comment]
You can use `else` to define the default value:

```rego
package repl

f(x) = 1 {
        x > 1
}

else = 0 {
        true
}
```

```
> f(-1)
0
```

**Comment by oren-zohar** [comment]
@tsandall thanks for the quick response!
Small question, why do we need to add the:
```rego
else = 0 {
        true
}
``` 
inside the else clause? seems redundant no?

Wouldn't it be more elegant to have it like that:
```rego
package repl

f(x) = 1 {
        x > 1
} else = 0
```

I'm asking this since I noticed that `opa fmt -w` adds the same thing into the else clause if it's empty, even though it works the same.

**Comment by anderseknert** [comment]
Checking in from my vacation, and I'm happy that you went with the conservative approach here and made default functions similar to default rules @ashutosh-narkar 👍 

Looking at the PR though, I don't see anything added to the documentation around this. Was that added elsewhere?

**Comment by ashutosh-narkar** [comment]
Hey @anderseknert good point. I'll update the docs to add a note about this.
