### ISSUE TITLE
Rego: Precedence rules and use of OR/AND rules

### ISSUE THREAD

**Issue by rohrit** [open-policy-agent/opa#2446]
This is more of a question than an issue. I have looked through the online documentation at https://www.openpolicyagent.org/docs/latest/#rego and i am not sure if this is addressed elsewhere.

# Expected Behavior

I want to build policy rules which have arbitrary combinations of OR and AND logic as well as enforce precedence amongst the defined rules.

For example, if A, B, C, D etc. are Rego policy rules, is there a way to write the combination of them as

(A OR B) AND (C OR D)

OR logic in Rego requires rules to written with same name in a different block as opposed to AND logic which is within the same block. I suppose the Rego syntax would need to be extended to support rule combinations as shown above.

# Actual Behavior

N/A

# Steps to Reproduce the Problem

N/A

# Additional Info

I am able to construct simpler combinations by refactoring the statements, for example

(A OR B) AND C

can be rewritten as

(A AND C) OR (B AND C)

However, this is not convenient and gets complicated soon as the number of conditions increases.

**Comment by tsandall** [comment]
@rohrit I'm not exactly sure what you mean by _precendence_ in the context of your question. Precedence usually has to do with the order that operators are evaluated in. Is that what you mean?

To express "(A OR B) AND (C OR D)" define two rules with the same name to express "A OR B" and another two rules to express "C OR D":

```rego
a_or_b { A }
a_or_b { B }

c_or_d { C }
c_or_d { D }
```

Now you can write:

```rego
p { 
  a_or_b
  c_or_d
}
```

**Comment by rohrit** [comment]
Thank you for the response. That answers my question.

I realized the question of precedence does not directly apply for Rego and it is essentially expressed by the way the rules would be written in policy.
