### ISSUE TITLE
Support EKS IRSA for Signing S3 Bundle Requests

### ISSUE THREAD

**Issue by RichiCoder1** [open-policy-agent/opa#2462]
# Expected Behavior
When using [OPA Bundle's S3 Support](https://www.openpolicyagent.org/docs/latest/configuration/#aws-signature), a pod containing OPA with [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) configured is able to sign and retrieve bundles as that pod's assigned role using the provided AWS Web Identity.

(From #2607)
The provided environment variables look like so: 
```
AWS_ROLE_ARN=arn:aws:iam::{my account}:role/{my role}
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

# Actual Behavior
Attempting to retrieve the bundle fails as OPA does not see and utilize the credentials, and as so can not authenticate.

# Additional Info

IAM Roles for Service Accounts is the Amazon-blessed way to do IAM in EKS, and as such we've been moving to using it for everything. However OPA doesn't support this so we either have to open up the bucket or hard code credentials since we're not giving the EC2 privileges.
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

The AWS Go SDK provides out of the box support for the Web Identity Provider: https://github.com/aws/aws-sdk-go/blob/f6443cd3144c36f0470a6b2230f1c315979d01de/aws/credentials/stscreds/web_identity_provider.go

**Comment by RichiCoder1** [comment]
Possibly related to #1600, but could probably also be accomplished without.

**Comment by hangxie** [comment]
> we either have to open up the bucket or hard code credentials

I use a workaround to avoid using credential as rotation will be a headache:

1. Create emptyDir volume so containers within the pod can share the same storage
2. Let OPA watch (`--watch`) the policy file, it will reload if things change
3. Create an AWS sidecar (https://hub.docker.com/r/amazon/aws-cli) to load S3 object periodically (`aws s3 cp` to /tmp, compare with running one, overwrite if there is diff).
4. There needs to be an init container to load policy like the AWS sidecar to make sure OPA starts with a good policy

This is definitely not the perfect way to solve this problem, but it works for me before OPA support service account with IAM role.

**Comment by patrick-east** [comment]
Pretty much. Ideally the changes specific to this can be contained in the "aws" auth plugin code https://github.com/open-policy-agent/opa/blob/30271bc18bc942296607e4bd9d5f0d79825835ea/plugins/rest/aws.go but its all part of that same `rest` package.
