### ISSUE TITLE
How to send customised https response message from OPA to the caller

### ISSUE THREAD

**Issue by ajoysinha** [open-policy-agent/opa#2472]
This is not an issue but a question.

I am implementing OPA as sidecar in kubernetes and istio. invoking OPA from EnvoyFilter "envoy.ext_authz". my rego policy is as below and it is working as expected.

```
package opa.meddetails

import input.attributes.request.http as http_request
import input.attributes.source.address as source_address

default allow = false

allow = true {
    customer_has_access_to_external_ui
}

externalurl := "**/test/**"
customer_has_access_to_external_ui {
      http_request.method = "GET"
      glob.match(externalurl, ["/"] , http_request.path)
}
```
For different condition policy is allowing and disallowing [ return code 403 Forbidden ].

My config.yaml for OPA is as below 
```
config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: opa/meddetails/allow
```
Now my query is as below ..

Does OPA provide any feature to return custom message which will be retuen to caller as http reponse message [ like : "User do not have access for this operation" ] ..If OPA do not have any feature like this, how OPA suggest to implement the same. 

I want to send response body along with Http Status code.

**Comment by ashutosh-narkar** [comment]
You can write a rule that returns an object which has some headers, status etc. which is then included in the response sent to the downstream client or upstream. See [this](https://github.com/open-policy-agent/opa-istio-plugin/#example-policy-with-object-response) example.

**Comment by patrick-east** [comment]
Going to close this out, looks like the example provided should cover it.

Feel free to re-open if more info is needed

**Comment by loeffel-io** [comment]
can please someone provide a updated link to the example 🙏

**Comment by anderseknert** [comment]
I believe this would be the equivalent doc today: https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-additional-controls

**Comment by anderseknert** [comment]
I believe this would be the equivalent doc of today: https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-additional-controls
