### ISSUE TITLE
Rego file generated on windows IDE always returned policy allow as false

### ISSUE THREAD

**Issue by karunchennuri** [open-policy-agent/opa#2484]
I've used [Playground](https://play.openpolicyagent.org/) to generate a rego policy that decodes a JWT token to extract claims, it then maps claim against predefined ACL to take policy decisions. I am hitting `/policy/allow/result` to fetch the result as boolean value true/false. 

Further editing rego policy from Playground to Windows environment VSCode IDE and uploading the policy via 
```
curl -X PUT http://localhost:8181/v1/policies/myapi --data-binary @myapi-policy.rego
``` 
Run the tests with sample input always returned false

```
curl -k -X POST https://localhost:8181/v1/data/myapi/policy --data-binary @test-input.json | jq .
```

# Expected Behavior

Policy is returning false for every input (includes success case too)

# Actual Behavior

Policy should've returned true for input that resolves to a policy rule.

# Steps to Reproduce the Problem

1. Create a Policy in playground
2. Copy the policy and save as rego file on windows
3. Upload the policy using 
```
curl -X PUT http://localhost:8181/v1/policies/myapi --data-binary @myapi-policy.rego
``` 
4. Go to /v1/policies/myapi to see that "raw" field has special character "\r\n"
5. Now test the policy against +ve and -ve inputs. In both cases policy result returned is false.

To workaround this:
1. ```curl https://play.openpolicyagent.org/v1/input/<redacted> | curl -k http://localhost:8181/v1/data -d @-```
2. Go to /v1/policies/myapi to see that "raw" field now contained only "\n" (unlike rego file edited on Windows OS that came with "\r\n" --> I am not sure if that's what is the problem here, but I don't find any other difference other wise)
3. Now test the policy against +ve and -ve inputs. This time results returned just fine.

I suspect policies edited on Windows OS with VSCode IDE added `\r` which I believe OPA is not liking!?

# Additional Info

OPA
Version: 0.20.5
Build Commit: 64dd76e

**Comment by patrick-east** [comment]
Thanks for filing the issue!

One thing to clarify, OPA _should_ handle windows-style line endings in policies. The parser is equipped to deal with them correctly and we have quite a bit of testing. While possible there is an issue there, I wouldn't expect to see it manifest in this way. I'd expect an error response from the server saying it couldn't parse the policy or input document.

What I am suspicious of is the input document. You mentioned that the workaround is to use:

```
curl https://play.openpolicyagent.org/v1/input/<redacted> | curl -k http://localhost:8181/v1/data -d @-
```

The document that is produced from this API call is actually different than the document you see in the playground UI. For example:

![image](https://user-images.githubusercontent.com/3614287/85426601-8f455f00-b52f-11ea-84c4-0ea31087f946.png)

Where the input is:

```json
{"message":"worldsdf"}
```

Via that API call you get:
```
$ curl https://play.openpolicyagent.org/v1/input/uJwnx3YuCV
{"input":{"message":"worldsdf"}}
```

That wrapping of:
```
{
    "input": <doc>
}
```

Is required by the `/v1/data/` REST API for OPA: https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-with-input as the payload may contain additional fields in the future. There are other API's which do not require the wrapper, for example see https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-webhook

For all other OPA golang API or CLI invocations (eg `opa eval --input some.json ..`) this wrapper is not required and the document is used directly, the playground UI operates the same way.

I did a quick test on my a windows machine with this example https://play.openpolicyagent.org/p/CJIq9dnzfC and it works as expected as long as I modify the input JSON to be compatible with the REST API.

Double check your input documents and let us know if that fixes it.

**Comment by karunchennuri** [comment]
I think I already figured out from the docs that the input should be wrapped in 
`
{ "input": <doc>}
`

This time I tried the following steps:

`opa run --server` 

`curl -k -X POST http://localhost:8181/v1/data --data-binary @my-input-jwt.json | jq .`

my-input-jwt.json 

`
λ cat magentaauth-input-karun-client-id.json
{
    "input": {
        "attributes": {
`

**Comment by patrick-east** [comment]
Can you try without `--data-binary` for the input? I was unable to reproduce an issue, and policy aside that was the only difference with what i did.

If that doesn't help please share the policy and input that reproduces the issue.

**Comment by karunchennuri** [comment]
I reran the steps with a slight change in ACL definition

Instead of -
`
λ curl -X PUT http://localhost:8181/v1/data/uaajwt/acl --data-binary @my-acl-data.json
`

Changed to below

`
curl -X PUT http://localhost:8181/v1/data --data-binary @maxsmythe -acl-data.json
`

This worked perfectly fine!

You are right if it's nothing to do with windows styling `\r\n` doesn't seem to have any impact vs `\n` on Linux.

**Comment by karunchennuri** [comment]
You may close this @patrick-east

**Comment by patrick-east** [comment]
Glad to hear it is working! 👍
