### ISSUE TITLE
Standard istio application is not working [ 403 forbidden ] after installing opa-istio-plugin in the same namespace

### ISSUE THREAD

**Issue by ajoysinha** [open-policy-agent/opa#2498]
I am trying to do following steps but not getting expected behavior.

**Steps A**
 
1.  I have a namespave dev-a
2.  in that namespace following lebel setup : 
                     opa-istio-injection: disabled
                     istio-injection: enabled
3. deployed app in that name space
4. Application is accessible using URL : status code 200

**Steps B**

5. Installed opa-instio-plugin using attached yaml file [ configure-opa-istio-plugin.yaml ]

[configure-opa-istio-plugin.yaml.txt](https://github.com/open-policy-agent/opa/files/4844810/configure-opa-istio-plugin.yaml.txt)

6. When i am trying to access previously deployed URL , it is returning response code 403 [ forbidden ]

**Expectation**

I should be able to access previously deployed application without any issue

**Comment by ashutosh-narkar** [comment]
It would helpful to see the OPA logs to see the request that it gets. Also you have a custom policy loaded, have you unit-tested it ?

**Comment by ashutosh-narkar** [comment]
@ajoysinha any update on this ?

**Comment by ajoysinha** [comment]
Added workload selector in EnvoyFilter to resolve it 
```
spec:
  workloadSelector:
    labels:
      opa-enabled: yes

```
