### ISSUE TITLE
Sprintf format int or float with precision

### ISSUE THREAD

**Issue by albqmasqeet** [open-policy-agent/opa#2504]
While trying to use sprintf in OPA I found that there is no good way to print an integer with precision. I'm trying to figure out how to use sprintf to print at least two decimal places and no leading zeros. 

For instance, when input is:

```
56
56.0
56.5
56.55
56.555
56.0000
```

output must be:
```
56.00
56.00
56.50
56.55
56.555
56.00
```

**Comment by patrick-east** [comment]
The builtin is plumbed into the golang `fmt.Sprintf` function, so you get access to all of what is described in https://golang.org/pkg/fmt/

Can you use `sprintf("%.2f", [n])` to achieve the desired output?

**Comment by albqmasqeet** [comment]
```sprintf("%.2f", [n])``` works when n is float, it doesn't work when n is int. I don't know a way in rego to convert int to float either. float64() from golang doesn't exist in rego.

**Comment by albqmasqeet** [comment]
I want sprintf to print two decimal precision regardless of whether the input is int or float.

```sprintf("%.2f", [64])``` fails with ```%!f(int=64)``` because 64 is not float
```sprintf("%.2f", [64.123])```  because 64.123 is float

**Comment by patrick-east** [comment]
🤔  Hmm yea.. that is kind of annoying.

We don't have a convenient way to force the underlying number to be a float if it doesn't have a decimal value. That might be something that can be handled with a builtin function. Not 100% sure.. would need to dig in more.

As an immediate solution you can handle this with a helper function and some string formatting, for example see: https://play.openpolicyagent.org/p/g1CImSHZaP

**Comment by albqmasqeet** [comment]
Thanks for taking a look, I will settle for this code for now, because looks like there isn't a more direct way of doing this.

**Comment by srenatus** [comment]
I hadn't found this issue before creating #4610. Closing this for the other one that @damienjburks is already looking into!
