### ISSUE TITLE
show all failures when running `opa test --coverage`

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#2505]
currently it stops after the first failure which makes it hard to see what failed ... prefer keeping the same output as `opa test` produces (show all failed tests)

**Comment by eliw00d** [comment]
The same is true with `--threshold float`.

**Comment by tsandall** [comment]
I'm going to close this because it's a dupe of #2139 though the description is slightly different. OPA should just run all of the tests and report the coverage regardless of whether there were failures or errors.
