### ISSUE TITLE
Split out Gatekeeper's certificate management code into a new repo

### ISSUE THREAD

**Issue by maxsmythe** [open-policy-agent/opa#2506]
Gatekeeper's [certificate management code](https://github.com/open-policy-agent/gatekeeper/blob/v3.1.0-beta.10/pkg/webhook/certs.go) allows embedding easily-toggled certificate management in a project.

This is beneficial for generating simple certificates for zero-dependency installs and unit testing, while still leaving room for self-managed certificates or more fully-featured solutions such as cert-manager.

As such, it has become generally useful for other projects, such as the [Hierarchical Namespace Controller](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc/third_party/open-policy-agent/gatekeeper).

Unfortunately the Gatekeeper repo does not work well as a module because:

1) It was never intended to
2) It's directory structure does not meet the versioning requirements of gomod

In order to reduce code duplication, we suggest:

1) Creating a new repo under open-policy-agent called "cert-controller" that has the same set of maintainers as exists for the current "gatekeeper" repo
2) Migrating the current gatekeeper certificate code into this new repo.

Per our governance policy, adding a new repo requires a 2/3 approval vote from all organizations.

**Comment by maxsmythe** [comment]
+1 vote, Google

**Comment by ritazh** [comment]
+1, Microsoft

**Comment by tsandall** [comment]
+1

**Comment by tsandall** [comment]
The repo has been created and the gatekeeper-maintainers team has admin access. 🎊
