### ISSUE TITLE
with_request_body from Envoy

### ISSUE THREAD

**Issue by gituserjava** [open-policy-agent/opa#2507]
If we specify with_request_body in ExtAuth in envoy.yaml with max_request_bytes, will the body be sent to OPA server? If yes, how can we log or see that body in OPA logs?

My assumption is if we do not specify with_request_body, the body will not be sent to OPA. Is that correct?

**Comment by ashutosh-narkar** [comment]
Yes the body will be sent to OPA. To see the logs, one option is to turn on console decision logging `"--set=decision_logs.console=true"`. See [this](https://www.openpolicyagent.org/docs/latest/envoy-authorization/) step-by-step tutorial for details.

**Comment by gituserjava** [comment]
@ashutosh-narkar , thank you for the response. 

One more question, what is the maximum size of the request body that can be sent to OPA?

**Comment by ashutosh-narkar** [comment]
OPA does not set any limit on that. It depends eventually if the input can fit in memory.

**Comment by tsandall** [comment]
Closing because the question was answered.
