### ISSUE TITLE
Installation of EnvoyFilter on istio-syatem [ for OPA implementation ] is returning 502 error

### ISSUE THREAD

**Issue by ajoysinha** [open-policy-agent/opa#2509]
We have following architecture implemented in our AWS eks cluster with ISTIO and OPA

client --> ingress controller -->  istio proxy -->  OPA-istio --> microservice.

**Now, during opa-istio installtion if we install EnvoyFilter application is not reaching and it is giving 502 error.**

This error is holding our progress in a full stop.

but if we delete EnvoyFilter application is reachable and responding as expected.

```
############################################################
# Envoy External Authorization filter that will query OPA.
############################################################
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:
      with_request_body:
        max_request_bytes: 8192
        allow_partial_message: true
      grpc_service:
        # NOTE(tsandall): when this was tested with the envoy_grpc client the gRPC
        # server was receiving check requests over HTTP 1.1. The gRPC server in
        # OPA-Istio would immediately close the connection and log that a bogus
        # preamble was sent by the client (it expected HTTP 2). Switching to the
        # google_grpc client resolved this issue.
        google_grpc:
          target_uri: 127.0.0.1:9191
          stat_prefix: "ext_authz"
  - insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: TCP
    filterType: NETWORK
    filterName: "envoy.ext_authz"
    filterConfig:
      stat_prefix: "ext_authz"
      grpc_service:
        google_grpc:
          target_uri: 127.0.0.1:9191
          stat_prefix: "ext_authz"
---

```

Am i missing to open and cluster port for this communication. not getting any clue from logs also.

502 bad gateway is returing from server openresty/1.15.8.2 [ i think this is ingress controller implementation ]

**Comment by ashutosh-narkar** [comment]
What version of Istio is this ? Is there any information in `kubectl describe` that could be helpful ? First thing to check is if opa-istio container in injected in the pod. If it is, see if it's reachable. The latter could point to a more platform specific issue.

**Comment by ajoysinha** [comment]
Istio version is 1.5.4

Yes, opa-istio container is injected. But how can i see it is reachable ..
one more thing ..
if we delete the envoy filter then request is reaching to service.

Just installing the envoy filter is blocking everything.

Just another request , do we have any sample implementation where in can use lua filter inplace of ext_autz filter to cimmunicate with opa sidecar. Trying to make it work somehow so that we can push it in implementation / deployment stage .. for this 502 error everything stuck.

**Comment by ashutosh-narkar** [comment]
Where is the 502 coming from ? Do you see any errors in the Envoy logs ? Also if the  opa-istio container is running, can you check its logs. It should log requests it's getting from Envoy. If it's not getting any requests, then it's most likely Envoy cannot reach the opa-istio container. In that case, check how the networking is setup.

**Comment by ajoysinha** [comment]
1. opa istio container is running ..and its log is printing the request .
2. But it is returning false always and surprisingly for each call it is printing 3 ( three ) logs as below 
```
{"decision_id":"2356293c-df4d-4ca7-9a84-a697addf2a80","input":{"attributes":{"destination":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":20200},"address":"10.136.155.129"}}}},"source":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":51516},"address":"10.136.133.165"}}}}},"parsed_body":null,"parsed_path":[""],"parsed_query":{}},"labels":{"id":"3b3bee7d-d44a-4bb3-b6d6-b33b5d5d65a6","version":"0.21.0-istio"},"level":"info","metrics":{"timer_rego_query_eval_ns":124053,"timer_server_handler_ns":170612},"msg":"Decision Log","path":"opa/meddetails/allow","requested_by":"","result":false,"time":"2020-07-02T09:15:46Z","timestamp":"2020-07-02T09:15:46.16289855Z","type":"openpolicyagent.org/decision_logs"}
{"decision_id":"0681215b-3146-4f43-ac1d-e56f6f66067b","input":{"attributes":{"destination":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":20200},"address":"10.136.155.129"}}}},"source":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":51520},"address":"10.136.133.165"}}}}},"parsed_body":null,"parsed_path":[""],"parsed_query":{}},"labels":{"id":"3b3bee7d-d44a-4bb3-b6d6-b33b5d5d65a6","version":"0.21.0-istio"},"level":"info","metrics":{"timer_rego_query_eval_ns":101750,"timer_server_handler_ns":136432},"msg":"Decision Log","path":"opa/meddetails/allow","requested_by":"","result":false,"time":"2020-07-02T09:15:46Z","timestamp":"2020-07-02T09:15:46.165543076Z","type":"openpolicyagent.org/decision_logs"}
{"decision_id":"e2339523-fe03-4b6c-827d-95317db401cd","input":{"attributes":{"destination":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":20200},"address":"10.136.155.129"}}}},"source":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":51524},"address":"10.136.133.165"}}}}},"parsed_body":null,"parsed_path":[""],"parsed_query":{}},"labels":{"id":"3b3bee7d-d44a-4bb3-b6d6-b33b5d5d65a6","version":"0.21.0-istio"},"level":"info","metrics":{"timer_rego_query_eval_ns":87305,"timer_server_handler_ns":120546},"msg":"Decision Log","path":"opa/meddetails/allow","requested_by":"","result":false,"time":"2020-07-02T09:15:46Z","timestamp":"2020-07-02T09:15:46.168009446Z","type":"openpolicyagent.org/decision_logs"}
```

4. It means that opa -istio is getting the request but the query which is returning true , same query is returning false here .
5. also parsed_path is blank. it should have path value ..

**Comment by ajoysinha** [comment]
If we add failure_mode_allow=true then only we are getting 502 error , but if we add failure_mode_allow=false, no response is coming back ..

**Comment by ajoysinha** [comment]
I have another query, the way opa-istio, istio-proxy and grpc server, it is required to be communicated using port 9191 and 8181 and localhost. but all of them are running inside a single pod [in this environment]
In AWS EKS environment do we need to open any specific ports in security group.

**Comment by ashutosh-narkar** [comment]
I haven't tried deploying opa-istio in EKS so can't comment on whether the security group needs to be updated.

The OPA ports are configurable. Since they are running in the same pod, I doubt you would have to open any port but I/m not sure about that.

Regarding the decision OPA sends, it would help to write unit tests for the policy before deploying this. Also can you share the input OPA gets ?

**Comment by ajoysinha** [comment]
After doing some investigation .. I have done following steps .. 
1. get into istio-proxy container of one pod 
2. from there I did **curl localhost:8282**, it prints output which shows OPA is running
3. from there i did **curl localhost:9191**, it prints output which shows grpc server is running

but still when communicating, we are getting 502.

Do we have any way to see Grpc Server log

**Comment by ashutosh-narkar** [comment]
The log shows OPA getting the input and returning a result back to Envoy. I would have expected `parsed_path` to be set but that's a different issue.

From the above log at least it looks like Envoy - OPA connection seems to be working. The issue could be in the path after the authorization decision is received by Envoy.

**Comment by ajoysinha** [comment]
I have found following information from proxy config of pod configuration. 
```
istioctl proxy-config listeners hello-world-t2-548c8d58cb-msvt7 -n nexus-sitb --port 15006 -o json
```
**Surprisingly I am not able to find **"http_connection_manager"** in proxy-config. proxy config.** 
output attached as file. 

[proxy-config.txt](https://github.com/open-policy-agent/opa/files/4878518/proxy-config.txt)
and I assume this is the main reason why EnvoyFIlter is introducing 502.

But question still open, why "envoy.http_connection_manager" is not injected in pod proxy config. am i missing any prerequisite for istio.

**Comment by ashutosh-narkar** [comment]
@ajoysinha try this with the newer Envoy Filter format as described [here](https://github.com/open-policy-agent/opa-istio-plugin/pull/190). That may not resolve the issue but at least we can eliminate any deprecated config issue.

**Comment by ajoysinha** [comment]
I am able to solve this issue. this was not for the OPA plugin but due to the configuration of istio. to enable open policy agent plugin we do require http communication between istio proxy [ Envoy Filter ] with grpc server and OPA sidecar. http communication only enable in istio if we configure service.yaml file as below 

Name should be attached with **http** prefix. That was the mistake i was doing in one of the cluster. 

```
Spec:
       ports:
       - name: http-*
         port: 443
         targetPort: 20200
```

Thanks everybody for your help.

I am closing the issue
