### ISSUE TITLE
Download bundle from AWS S3

### ISSUE THREAD

**Issue by 00subra8** [open-policy-agent/opa#2511]
Hi,

We are trying to connect OPA to our AWS S3 server and download a bundle.
The AWS auth used is described in this link:
https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

Could u pls let us know if this is possible with the current OPA version??

**Comment by patrick-east** [comment]
No, not yet. There is an open feature request tracking it: https://github.com/open-policy-agent/opa/issues/2462
