### ISSUE TITLE
Rego error or warning for unused local variable

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/opa#2514]
As a policy author, I sometimes make mistakes that OPA might be able to detect by declaring a local variable that never gets used.  It could be valuable for OPA to provide a warning, error, linter that lets me know.

In the following example, it seems clear that I intend to condition `deny` on the port number computed as `port`, but nowhere in the rule is that variable `port` used.  Some sort of feedback that this is probably not what is intended could be useful.

```
deny {
    values := split(input.request.path, ":")    
    port := to_number(values[1])
    input.user == "alice"
}
```

For those cases where, for example, a function returns a value that is never used we can use the `_` variable.  Example:

```
deny {
    [_, payload, _] := io.jwt.decode(input.token, "mykey")
    payload.username == "alice"
}
```

Making this an error would be backwards incompatible.

**Comment by tsandall** [comment]
This would be a nice improvement. I'd be curious to see how many policies in the wild (e.g., rego files on GitHub) would break if we introduced the change. If the % is small enough, I could imagine just going ahead with it. Users will probably be happy about this in the long run. Assuming they're writing tests or checking their .rego files before pushing them into deployment, it would be caught and fixed relatively easily.

**Comment by johanfylling** [comment]
As discussed with @tsandall out-of-band, this will only be implemented for assignments via `:=`.
The following will also be considered an error: 
```
p {
   j := input[_]
}
```
