### ISSUE TITLE
Add an aggregation function to count the number of times a pattern occurs in a collection

### ISSUE THREAD

**Issue by PrahathessRaghavan** [open-policy-agent/opa#2522]
Essentially we need a way to check for elements repeating in an array that works similar to : 

`count(collection_or_string)`

that would take in a pattern and an array then return the  count or number of matches  something like : 

`regex_count(collection_or_string,pattern)`

eg. here is a sample input
`
      "request": {
        "tags": [
           "networkTag1",
           "networkTag1",
           "metadata"
        ],
  } 
`
the function would look like :

`regex_count(input.request.tags,"*.Tag.*")`  and returns 2 as the output

If there is a way to do this currently please do let me know

**Comment by patrick-east** [comment]
You don't need a new function for this AFAIK. This kind of functionality can be done with Rego, you'll likely just want to make some helper functions.

Take a look at the example here: https://play.openpolicyagent.org/p/HuPjLx2dcN it shows a helper with the same signature proposed all in Rego.

**Comment by PrahathessRaghavan** [comment]
Thank you @patrick-east ,  cannot open the link though  , can you please post an example here so its easier to find if anyone else wants it.

**Comment by patrick-east** [comment]
Try it again, there was a temporary outage for the playground

**Comment by PrahathessRaghavan** [comment]
Works now , Thanks so much ! , Will play around with rego more

**Comment by tsandall** [comment]
Closing this issue as the original question was resolved.
