### ISSUE TITLE
`make release-patch` for bugfix releases puts the changelog entry in the wrong place

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2533]
When following the instructions on https://github.com/open-policy-agent/opa/blob/master/docs/devel/RELEASE.md for a bugfix release we have the steps for:

```
make release-patch VERSION=<semver> > ~/release.patch
```

Which currently generates the correct changelog snippet, but inserts it at the end of the CHANGELOG.md _and_ replaces a line right before. Eg:

```
{12:41} ~/p/g/s/g/o/opa:release-0.21 ✓ ❯ git cherry-pick -x opa/master
[release-0.21 d9509b4f] Add nightly github workflow with race detector job
 Date: Thu Jul 9 17:15:52 2020 -0700
 3 files changed, 33 insertions(+)
 create mode 100644 .github/workflows/nightly.yaml
{12:41} ~/p/g/s/g/o/opa:release-0.21 ✓ ❯ make release-patch VERSION=99.9.9 > ~/release.patch
{12:42} ~/p/g/s/g/o/opa:release-0.21 ✓ ❯ cat ~/release.patch
Cloning into '/go/src/github.com/open-policy-agent/opa'...
done.
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 53d09db3..88b5c606 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -2075,4 +2075,10 @@ And many other small improvements and fixes.
 - Introductions to policy, policy-enabling, and how OPA works
 - Language reference that serves as guide for new users
 - Tutorial that introduces users to the REPL
-- Tutorial that introduces users to policy-enabling with a Docker Authorization plugin
+
+## 99.9.9
+
+### Fixes
+
+- Add nightly github workflow with race detector job ([#2388](https://github.com/open-policy-agent/opa/issues/2388))
+
diff --git a/Makefile b/Makefile
index 208436f4..9740f17c 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,7 @@
 # Use of this source code is governed by an Apache2
 # license that can be found in the LICENSE file.

-VERSION := 0.21.1
+VERSION := 99.9.9

 CGO_ENABLED ?= 0
```

The snippet is at the very bottom of the file and removed:

```
-- Tutorial that introduces users to policy-enabling with a Docker Authorization plugin
```

The steps to repro locally are to:
* Checkout a release branch
* Cherry-pick _some_ change (doesn't really matter which)
* Run the `make release-patch` script

-----

It looks like the issue is in https://github.com/open-policy-agent/opa/blob/e8f004c6c26fb7d243fcd46ad26040e8b86c8d9a/build/gen-release-patch.sh#L48-L59

For the bugfix branches there is no "Unreleased" section, so the script isn't working as expected. We will need to adjust behavior based on whether it finds that section or not. If it doesn't exist the new snippet should be inserted at the top of the file.

**Comment by tsandall** [comment]
> For the bugfix branches there is no "Unreleased" section, so the script isn't working as expected. We will need to adjust behavior based on whether it finds that section or not. If it doesn't exist the new snippet should be inserted at the top of the file.

👍 we can insert at the top of the file before the first ## header.
