### ISSUE TITLE
REST API for create data works only for paths starting with "/v1"

### ISSUE THREAD

**Issue by tauseefj** [open-policy-agent/opa#2541]
REST API for create data works only for paths starting with "/v1".
Example : The below curl fails
curl --location --request PUT 'localhost:8181/data/myset/servers5' \
--header 'Content-Type: application/json' \
--data-raw '{
    "servers": [
        {"id": "app", "protocols": ["https", "ssh"], "ports": ["p1", "p2", "p3"]},
        {"id": "db", "protocols": ["mysql"], "ports": ["p3"]},
        {"id": "cache", "protocols": ["memcache"], "ports": ["p3"]},
        {"id": "ci", "protocols": ["http"], "ports": ["p1", "p2"]},
        {"id": "busybox", "protocols": ["telnet"], "ports": ["p1"]}
    ]
}'

But the below curls passes and creates the data
curl --location --request PUT 'localhost:8181/v1/data/myset/servers5' \
--header 'Content-Type: application/json' \
--data-raw '{
    "servers": [
        {"id": "app", "protocols": ["https", "ssh"], "ports": ["p1", "p2", "p3"]},
        {"id": "db", "protocols": ["mysql"], "ports": ["p3"]},
        {"id": "cache", "protocols": ["memcache"], "ports": ["p3"]},
        {"id": "ci", "protocols": ["http"], "ports": ["p1", "p2"]},
        {"id": "busybox", "protocols": ["telnet"], "ports": ["p1"]}
    ]
}'

Note: I tried with data-binary also and it does not work.
# Expected Behavior
The data should be created

# Actual Behavior
404 Not found is shown

# Steps to Reproduce the Problem
Use Postman or run a manual curl

If this is a bug report please provide as much detail as possible so that we can
reproduce the problem. Examples:

* OPA version - 0.21
* Example query, input, data, and policy that OPA was given
curl --location --request PUT 'localhost:8181/data/myset/servers5' \
--header 'Content-Type: application/json' \
--data-raw '{
    "servers": [
        {"id": "app", "protocols": ["https", "ssh"], "ports": ["p1", "p2", "p3"]},
        {"id": "db", "protocols": ["mysql"], "ports": ["p3"]},
        {"id": "cache", "protocols": ["memcache"], "ports": ["p3"]},
        {"id": "ci", "protocols": ["http"], "ports": ["p1", "p2"]},
        {"id": "busybox", "protocols": ["telnet"], "ports": ["p1"]}
    ]
}'

* Example output that OPA returned
404 Not fund
* For server and CLI, the flags/configuration that you provided to OPA
* For server, any relevant log messages from OPA
* For Go and Wasm, the arguments you invoked OPA with

# Additional Info
Works only if the path starts with /v1 and does not work for anything else. even if I use /v2 it does not work.
This was run on my local laptop
Any additional information you think might be helpful. Examples include the environment
where OPA was running (e.g., if inside Kubernetes, what resource limits did you configure
OPA with?), how long OPA had been running for, what was happening around the time
when you identified the problem, etc.

**Comment by tsandall** [comment]
The API version prefix ensures backwards compatibility in the future (e.g., if we ever make a new version of the Data API, it would need to be under a different API version prefix, e.g., `/v2/`). Closing this issue because we are not going to support unversioned API requests. For more information on the HTTP/REST API see https://www.openpolicyagent.org/docs/latest/rest-api/.
