### ISSUE TITLE
PEM decoding in crypto certificate built-ins

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#2557]
I'm interested in parsing  x509 pem encoded encoded certificates in my rules (sourced from k8s secrets) but found that this didn't seem to be possible with the current crypto built-ins.

While the CSR built-in parses data in the [pem format](https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go#L75-L78), the certificate function [does not](https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go#L23-L33).

This was raised in the [PR for the CSR built-in](https://github.com/open-policy-agent/opa/pull/2444#discussion_r432665898).

I'm in the position where I'd like to decode x509 pem encoded certificates/chains (as are found in k8s secrets) and am wondering what the best approach would be to support this in OPA. Perhaps a new built-in to do pem decoding and output as base64, ready for input to `crypto.x509.parse_certificates` would be the least breaking? But then the inconsistency with cert/csr handling remains. Would be interested to hear any ideas.

**Comment by patrick-east** [comment]
Thanks for raising this issue! 👍 

I think we have some room to improve the support for certificates in the OPA builtins. As you mentioned there is some inconsistency in what types are supported.

One thing that confuses the matter is that `crypto.x509.parse_certificates` will actually work with ASCII PEM certs... but you can't have the PEM wrapper. It's expecting the raw encoded payload. Ex:

https://play.openpolicyagent.org/p/7krENfkVpG
```rego
package play

pem_cert := `-----BEGIN CERTIFICATE-----
MIICQDCCAamgAwIBAgIBADANBgkqhkiG9w0BAQ0FADA9MQswCQYDVQQGEwJ1czES
MBAGA1UECAwJd2FzaGludG9uMQwwCgYDVQQKDANvcGExDDAKBgNVBAMMA29wYTAe
Fw0yMDA3MTcxNzQyMTFaFw0yMTA3MTcxNzQyMTFaMD0xCzAJBgNVBAYTAnVzMRIw
EAYDVQQIDAl3YXNoaW50b24xDDAKBgNVBAoMA29wYTEMMAoGA1UEAwwDb3BhMIGf
MA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQfntu8mcLbWewvyqw2JMoS9cN9bWc
ybPYPqNPUSu90pNZJ6SBiOA/SWrHFOMPc4eendban7dU1Wv+FsEHpOg6wVtrqoSy
0audwe1GZbZQUBMifjZdvPypyGxIiiooD9uF9CuxvTGjgdAtSOl6+1VCf4We/ky7
+E0JdtN2Sr4MhwIDAQABo1AwTjAdBgNVHQ4EFgQUZZLD+ORi5+Zm9pyEtnfMzwVz
5vIwHwYDVR0jBBgwFoAUZZLD+ORi5+Zm9pyEtnfMzwVz5vIwDAYDVR0TBAUwAwEB
/zANBgkqhkiG9w0BAQ0FAAOBgQC7xX5CY+e6DYY0cRIWaYshs4+B9jwwQEyCu7PP
QPpzFVfso4sS7hPUkIBlc5T1tITuXxgpvE9jBp4cO+tSiRq6EgAiRUqnDpMmnoP+
tlu0KkoGpU2V3+8EZTopjPGRfa7b1HCGwwONmJaSewkXxtI9DuPaCtE7PcQjFNir
9hst6Q==
-----END CERTIFICATE-----`


parsed := crypto.x509.parse_certificates(pem_cert)  # <-- raises an error
```

However if you trim the PEM wrapper like in:
https://play.openpolicyagent.org/p/kj1SLhhuWT
```rego
package play

pem_cert := `-----BEGIN CERTIFICATE-----
MIICQDCCAamgAwIBAgIBADANBgkqhkiG9w0BAQ0FADA9MQswCQYDVQQGEwJ1czES
MBAGA1UECAwJd2FzaGludG9uMQwwCgYDVQQKDANvcGExDDAKBgNVBAMMA29wYTAe
Fw0yMDA3MTcxNzQyMTFaFw0yMTA3MTcxNzQyMTFaMD0xCzAJBgNVBAYTAnVzMRIw
EAYDVQQIDAl3YXNoaW50b24xDDAKBgNVBAoMA29wYTEMMAoGA1UEAwwDb3BhMIGf
MA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQfntu8mcLbWewvyqw2JMoS9cN9bWc
ybPYPqNPUSu90pNZJ6SBiOA/SWrHFOMPc4eendban7dU1Wv+FsEHpOg6wVtrqoSy
0audwe1GZbZQUBMifjZdvPypyGxIiiooD9uF9CuxvTGjgdAtSOl6+1VCf4We/ky7
+E0JdtN2Sr4MhwIDAQABo1AwTjAdBgNVHQ4EFgQUZZLD+ORi5+Zm9pyEtnfMzwVz
5vIwHwYDVR0jBBgwFoAUZZLD+ORi5+Zm9pyEtnfMzwVz5vIwDAYDVR0TBAUwAwEB
/zANBgkqhkiG9w0BAQ0FAAOBgQC7xX5CY+e6DYY0cRIWaYshs4+B9jwwQEyCu7PP
QPpzFVfso4sS7hPUkIBlc5T1tITuXxgpvE9jBp4cO+tSiRq6EgAiRUqnDpMmnoP+
tlu0KkoGpU2V3+8EZTopjPGRfa7b1HCGwwONmJaSewkXxtI9DuPaCtE7PcQjFNir
9hst6Q==
-----END CERTIFICATE-----`

unwrapped := trim_prefix(trim_suffix(pem_cert, "\n-----END CERTIFICATE-----"), "-----BEGIN CERTIFICATE-----\n")

parsed := crypto.x509.parse_certificates(unwrapped)
```
You'll see it actually parse successfully.


So... I think we can probably help to improve this. Just sort of brainstorming but I can see a few options (in no particular order):

1) We could (and probably should) update the docs to explain this nuance with the current implementation.
2) We could add the helper you mentioned to convert from PEM to DER, it would likely be pretty harmless to add this regardless of other options we take... seems like it could be useful.
3) We can potentially make the parse certificate function be more flexible and accept PEM and DER certs, and should update the CSR one to do the same. Ideally their behaviors are consistent. There are maybe some backwards compatibility concerns.. but honestly this seems more like a bug. I doubt it was originally intended to make people strip off the PEM header and footer to parse the cert. Based on the comments on the source I think it was intended to only support base64 DER certs and the helper we use happens to also be cool with the payload of PEM cert.

@tsandall thoughts?

**Comment by tsandall** [comment]
I'd prefer #3 (update the `crypto.x509.parse_certificates` function to accept the header and trailer)

**Comment by charlieegan3** [comment]
Hey both, thanks for the replies. I'd like to have a go this week. I'll see what I can do to make the functionality more consistent to both built-ins, while supporting DER and PEM to keep it backwards compatible.
