### ISSUE TITLE
make coverage threshold show lines missing coverage

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#2562]
Running with `--threshold` can fail and then shows "expected 100% got 98%", which then means I have to get out the coverage data and figure out where the problem is.
Ideally it would show `missing coverage:\nfoo.rego:12`
this could be overwhelming when lots of things are uncovered, so it should be opt in or only show the first N lines with missing coverage.

/cc contributors from threshold https://github.com/open-policy-agent/opa/issues/1029 @EliuX  @tsandall  @flavio @srenatus

**Comment by tsandall** [comment]
This would be a nice enhancement and is a good area for contribution. At a high-level, I'd expect we would want to:

1. Update `opa test` so that the "pretty" format reports text instead of JSON
1. Update the "pretty" output mode to include the missing lines (sorted by file/line #)

I'm not too worried about the # of missing lines since I would expect most policies to be completely covered (and in my experience this is often the case.)

**Comment by Syn3rman** [comment]
Hey @tsandall,

Can I take this up if it is available? 
From my understanding, implementing a `PrettyCoverageReporter` similar to the `JSONCoverageReporter` should suffice, right?

Also, does the following output format work?
```
$ opa test -c --threshold 80 ex_tests/ -v

ex_tests/example.rego 57.15%
--------------------------------------------------------------------------------
Not covered: Line 3 to 5

Code coverage threshold not met: got 76.90 instead of 80.00
```

```
$ opa test -c ex_tests/ -v
Coverage: 76.9%

ex_tests/example_test.rego 100%
--------------------------------------------------------------------------------
Covered: Line 3 to 4
Covered: Line 7 to 8
Covered: Line 11 to 12

ex_tests/example.rego 57.15%
--------------------------------------------------------------------------------
Covered: Line 8 to 8
Covered: Line 10 to 12
Not covered: Line 3 to 5
```

**Comment by grosser** [comment]
- showing covered lines is redundant
- showing full file + number makes it easy to copy and navigate to in editor

```
missing coverage:
foo.rego:123-125
foo.rego:127
```

**Comment by grosser** [comment]
thx, that looks perfect!
