### ISSUE TITLE
Consider checksums or signing for release binaries

### ISSUE THREAD

**Issue by amouat** [open-policy-agent/opa#2583]
## Expected Behavior

If I go to releases (https://github.com/open-policy-agent/opa/releases) I expected to find checksums or GPG signatures for each release.

## Actual Behavior

No signatures or checksums are available.

## Additional Info

It seems to be becoming less and less common to distribute checksums or signatures, which surprises me slightly. In the case of distributing software via GitHub, it perhaps doesn't cut out a large number of attacks - if an attacker can change a binary, they can probably change the checksum in the release notes as well (but they may not have access to signing keys). In cases where the download comes from a different place (e.g. a third-party CDN or FTP site) it is more useful, as it removes the need to completely the trust the third-party. If a user obtains OPA from a third-party because of bandwidth or other restrictions, it would be nice if they could still use the site to verify the binary (see xcodeghost).

Also if I install OPA as part of CI/CD or an automated system, I would normally check that I'm receiving the same binary that I tested with each time. I can do this myself by manually generating the checksum after testing the software, but checking it also matches the value on the site gives me an extra level of trust. Even better is if there is a signature, as I don't need to continually test the binary and recreate the checksum (and have an extra level of belief that it was produced by the project).

I did see #2211 which overlaps with this issue.

Apologies if I missed a discussion about this somewhere else, I did try to search the tracker.

Update: having a look through GitHub, it doesn't seem that many projects sign releases. I feel it's unfair of me to single out OPA now. Feel free to close this, I would have myself if it wasn't for #2211, which implies that you may want to think about it as a form of parity with the MacOS/Windows signed releases.

**Comment by amouat** [comment]
I'm going to close this for the minute, whilst I look at how other projects handle this. I'm not sure it's fair to expect this from the OPA project.

**Comment by patrick-east** [comment]
FWIW it would be very low cost for us to publish a checksum with the release assets. If you were interested in contributing we'd just need to adjust these targets to like sha1 or something the binaries and put them into the release dir: https://github.com/open-policy-agent/opa/blob/a6724c74561157b9d63492b7ee1a18f7d5a1dc0e/Makefile#L237-L250

Then update https://github.com/open-policy-agent/opa/blob/a6724c74561157b9d63492b7ee1a18f7d5a1dc0e/build/github-release.sh#L31-L35 to include the checksum files in the automated release info.
