### ISSUE TITLE
Question: Can OPA send decisions_log to Logstash with the decisions_log configuration?

### ISSUE THREAD

**Issue by nestajah** [open-policy-agent/opa#2590]
Currently the audit of decisions_logs needs to be sent for an ELK cluster. Therefore, I cannot find a way to do it through the functions offered on the OPA configuration file.

**I don't know if this work in  this way:**

services:
  controller:
    url: https://url_where_my_bundle_are.  <--- This work pretty good
    allow_insecure_tls: true
  logstash:
    url: xx.xx.xx.xx:xxxx.        <---- I don't know if this works. I want to upload the logs on this route.
    allow_insecure_tls: true

bundles:
  opa-test:
    service: controller
    resource: xxxxxxxxx/bundle.tar.gz
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120

decision_logs:
  service: logstash           <---- I don't know if this works
  reporting:
    min_delay_seconds: 60
    max_delay_seconds: 120

###############

Logs from Opa before set this configuration:

{
  "level": "info",
  "msg": "Starting decision logger.",
  "plugin": "decision_logs",
  "time": "2020-07-31T15:04:30Z"
}
{
  "level": "info",
  "msg": "Log upload skipped.",
  "plugin": "decision_logs",
  "time": "2020-07-31T15:04:30Z"
}
{
  "level": "debug",
  "msg": "Waiting 8m19.368015965s before next upload/retry.",
  "plugin": "decision_logs",
  "time": "2020-07-31T15:04:30Z"
}

###

opa version: Open Policy Agent/0.20.5-istio

**Comment by tsandall** [comment]
@nestajah the Decision Log API is not compatible w/ Logstash as far as I know. OPA can be configured to send decision logs to the console; if you have some way to send console output to Logstash, that might work better.

**Comment by nestajah** [comment]
I was reading the next information on the OPA web: 

"OPA can periodically report decision logs to remote HTTP servers. The decision logs contain events that describe policy queries. Each event includes the policy that was queried, the input to the query, bundle metadata, and other information that enables auditing and offline debugging of policy decisions" Logstash can work like http server.

The configuration to  load report decision logs to remote HTTP servers what would it be?

**Comment by tsandall** [comment]
You just need to enable decision logging. Something like this:

```yaml
services:
  acmecorp:
    url: http://example.com

decision_logs:
  service: acmecorp
```

In this case, OPA will periodically POST a gzipped JSON array of decision log records to `http://example.com/logs/`. This is described in the Decision Log docs on openpolicyagent.org. The `/logs/` suffix is added automatically by OPA.

**Comment by nestajah** [comment]
The only mode to upload the logs its in gzipped mode?
