### ISSUE TITLE
Locked out of EKS API after OPA install

### ISSUE THREAD

**Issue by cabrinha** [open-policy-agent/opa#2596]
## Expected Behavior
Install OPA via helm with defaults and things work normally. Kubectl can still get logs, delete pods, edit objects, etc.

## Actual Behavior
Can't tail logs, can't create / edit / delete any objects other than validatingwebhookconfiguration and mutatingwebhookconfiguration

After deleting the webhook configurations, things start working again.

## Steps to Reproduce the Problem
Spin up new EKS cluster using this TF module: https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v12.1.0

Install OPA via helm `helm install opa stable/opa`

Try to delete the opa pod or tail logs of the pod, or create a new pod/deployment, it doesn't work.

* OPA version: `appVersion: 0.15.1`

Default installation from helm chart

## Additional Info
* EKS 1.16 using the above Terraform module.
* Calico installed using this method: https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks
* Also had issues with cert-manager webhooks, so we disabled those webhooks.

**Comment by tsandall** [comment]
@cabrinha can you share examples of the errors that EKS returns in response to tail/create/edit/delete of objects? Thanks!

**Comment by cabrinha** [comment]
Sure:
```
Timeout: request did not complete within requested timeout 30s

... and ...

Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```

**Comment by cabrinha** [comment]
Turns out this is an issue with Calico not running on EKS control plane:
```
Note: Calico networking cannot currently be installed on the EKS control plane nodes. As a result the control plane nodes will not be able to initiate network connections to Calico pods. (This is a general limitation of EKS’s custom networking support, not specific to Calico.) As a workaround, trusted pods that require control plane nodes to connect to them, such as those implementing admission controller webhooks, can include hostNetwork:true in their pod spec. See the Kuberentes API pod spec definition for more information on this setting.
```
