### ISSUE TITLE
How to conditionally call functions/rules 

### ISSUE THREAD

**Issue by ahmedtalhakhan** [open-policy-agent/opa#2603]
Fairly new to OPA and trying to map it to a use-case where a policy can be built using different types of matching-rules(not to be confused with the OPA rule). Every policy schema contains an array of matches, each with its own type defined by `type`

```
"Policy_1": {
      "name":"Test1",
      "matches": [
        {
          "type": "type1",
          "operator": "in",
          "values": ["1","2","3"],
          "exclude_values": [],
          "sub_rules": []
        },
        {
          "type": "type2",
          "operator": "prefix_match",
          "values": ["/a/b/c", "/k/l/m"],
          "exclude_values": ["/x/y/z"],
          "sub_rules": []
        }
      ],
      "responses": []
    },
```

My intention is to write a top level policy which can handle any type of matches within it.  I am trying to write the policy in the fashion below. The problem is that I have not come across any IF-ElSE construct within rules to do this.

How can I conditionally evaluate rules/functions based on the value of a field? This is needed because evaluation of different match types is/might be different.

```
package test.policy

import input
import data.test_policies


match [policy.name]   {
    policies := test_policies[input.customer_id]
    policy := policies[_]

    match := policy.matches[_]

   // Now what i want to do something like the following 
   // but it seems there is no IF-ELSE construct

   match_type = match.type

   if match_type == "type1"
      type1_match(match.values, input.type1_params)
   else if match_type == "type2"
      type2_match(match.values, input.type2_params)
}



type1_match (policy_values, input_values){
    policy_values[_] == input_values[_]
}

type2_match(policy_values, input_value) {
    path := policy_value[_]
    startswith(input_value, path)
}

```

How can I achieve this? Any help would be appreciated. 
Thanks.

**Comment by tsandall** [comment]
What you're looking for is Logical OR. To express Logical OR inside of Rego you define multiple rules with the same name:

```
# this says "p is true if input.a is 1 or input.b is 2"
p { input.a = 1 }
p { input.b = 2 }
```

In this case, it might be natural to define a rule as a function that accepts the match type as an argument:

```
# same as above, except these rule accepts two arguments
type_match(type, match) {
  type == "type1"
  type1_match(match)
}

type_match(type, match) {
  type == "type2"
  type2_match(match)
}
```

Then you can call this as follows:

```
match := policy.matches[_]
type_match(match.type, match)
```

**Comment by ahmedtalhakhan** [comment]
@tsandall if that approach is to to taken, then  N number of different match types will result in N number of definitions for `type_match`. If N is large, would this not become very expensive. Imagine N=10 meaning that 10 conditions will be evaluated out of which only 1 will come out to be true.
Is this the standard approach in rego? Would this not be bad for performance?

**Comment by tsandall** [comment]
@ahmedtalhakhan yes, this is the recommended approach.

With the examples shared above the runtime would linear with respect to the number of matches however that's no different than your if-else logic you included in the issue above.

To reduce the runtime there are certain optimizations we could look at. Some of them are already implemented and others would need work. Today, partial evaluation could applied to inline the policies/matches and then rule indexing could deliver approximately constant runtime. We could also look at other indexing strategies for functions. For example, if the type was encoded into the function signature OPA could easily index based on the function parameters.

```
# this is valid syntax today however there are no optimizations
type_match("type1", match) {
  type1_match(match)
}

type_match("type2", match) {
  type2_match(match)
}
```

**Comment by ahmedtalhakhan** [comment]
@tsandall thanks for this clarity. I am able to use the indexing you explained above. But now I am facing issues with the semantics of FOR ALL matches.. In the example above, I would like ALL matches to be true for the policy to be applicable.

The problem is that the matches are still being ORed between them.. Meaning, if any of the match is satisfied, the policy is matching, where as the expectation is that ALL matches need to happen for the policy to match.

 I am using the following rego code now.


```
package test.policy

import input
import data.test_policies


match [policy.name]   {
    policies := test_policies[input.customer_id]
    policy := policies[_]

    # Here, we want ALL match to be true. For rego, the concept of ALL match
    # is tied to finding a negative case and then doing a negation , so we will see
    # if any match DID NOT happen and then try to negate the expression.
 

    match_results := eval_matches(policy.matches)
    no_match_false(match_results)


    # PROBLEM! The policy is matching if ANY of the match is taking place instead of ALL.
    # Even though we are trying to follow the FOR ALL semantic as explained by rego documentation
    # but it does not seem to be working in this case.
}



eval_matches(matches) = match_results {
    match := matches[_]
    match_type := match.type
    match_results := type_match(match_type, match).  ## Use the indexed definitions of type_match
}


## Everything below this is fine
no_match_false(match_results) {
    not any_match_not_true(match_results)   ## This the negation
}

# Figures out if ANY of the results is false. Meaning if ANY match did not happen
any_match_not_true(match_results){
    result := match_results[_]
    result == false
}




## This implements conditionally execution of different match types based on their type. This function index works perfectly fine!
type_match("type1", match) {
  type1_match(match)
}

type_match("type2", match) {
  type2_match(match)
}
```
