### ISSUE TITLE
Integration With CA Technology Gateway

### ISSUE THREAD

**Issue by gorishagh** [open-policy-agent/opa#2609]
Hi,

I was wondering if OPA is integratabtle with CA Tech. Gateway? If not, any suggested work around? Any plans in the roadmap to integrate with CA Gateway?

Thanks,
Goris.

**Comment by tsandall** [comment]
> I was wondering if OPA is integratabtle with CA Tech. Gateway?

Sure! You can integrate OPA as a library or via HTTP. See the HTTP API Authorization tutorial on the OPA website for a simple example of how to integrate: https://www.openpolicyagent.org/docs/latest/http-api-authorization/

> Any plans in the roadmap to integrate with CA Gateway?

No at the moment, but if you do build something, let us know!
