### ISSUE TITLE
Not able to return array of results from function to implement FOR ALL

### ISSUE THREAD

**Issue by ahmedtalhakhan** [open-policy-agent/opa#2610]
Trying to implement a FOR ALL match for a use-case where my policy is a collection of different types of rules and ALL rules need to match for the policy to match.

I evaluation logic looks something like this

```
package test.policy

import input
import data.test_policies


match [policy.name]   {
    policies := test_policies[input.customer_id]
    policy := policies[_]
    rule_results := eval_rules(policy.rules).     <--- here rule_results is always an array with 1 element only which gets set to true even if 1 rule matchs. Thats the issue
    no_rule_mismatch(rule_results)



eval_rules(rules) = rule_results {
    some i
    rule_results := [rule_match(rules[i].type, rules[i])]. <--- This is where I am trying to return an array of results since rules is an array
}

no_rule_mismatch(rule_results) {
    not any_rule_not_matched(rule_results)
}

# Figures out if ANY of the results is false. Meaning if ANY rule did not match
any_rule_not_matched(match_results){
    result := match_results[_]
    result == false
}


# Using rule indexing here based on type of rule
rule_match("type1", rule) {
    //some custom matching(rule)
}


rule_match("type2", rule) {
    //some custom matching(rule)
}
```

I am able to verify that `rule_results` is `[true]` using a rego debugging toolkit named fregot. It outputs the following at that point

```
test.policy(debug)% :s
21|     no_rule_mismatch(rule_results)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.policy(debug)% rule_results
= [true]
| policies = package data_label.d66688a0-214a-4bdc-aceb-389ccc956e56
| policy = package data_label.d66688a0-214a-4bdc-aceb-389ccc956e56.Policy_1
| rule_results = [true]

```

## Expected Behavior
`rule_results` in `match` should be an array of results of the form `[true, true, true...ntrue]`

## Actual Behavior
`rule_results` in `match` should is always an array with only 1 element of the form `[true]` if even a SINGLE rule matches. 

## Steps to Reproduce the Problem

Policies in the data look like this
```
"Policy_1": {
      "name":"Test1",
      "rules": [
        {
          "type": "type1",
          "operator": "in",
          "values": ["1","2","3"],
          "exclude_values": [],
          "sub_rules": []
        },
        {
          "type": "type2",
          "operator": "prefix_match",
          "values": ["/a/b/c", "/k/l/m"],
          "exclude_values": ["/x/y/z"],
          "sub_rules": []
        }
      ],
      "responses": []
    },
``` 

Any help to resolve the issue will be appreciated.

**Comment by tsandall** [comment]
Why not just simply say:

```rego
matching_rules := [r | r := policy.rules[_]; rule_match(r.type, r)]
count(matching_rules) == count(policy.rules)
```

This computes a set of matching rules (called `matching_rules`) by finding all of the rules in the policy that match some predicate (named `rule_match`) and then checks if the set of rules is the same size as the input.

**Comment by ahmedtalhakhan** [comment]
wow! I would never have been able to reach this concise syntax. The ability to use rules+iteration to compute arrays/set is something that wasnt every evident to me from the documentation.

Would you mind explaining what was wrong in my attempt? Off course that is for understanding purpose.

**Comment by tsandall** [comment]
There were a few problems with the original attempt. The main issue was this line:

```
rule_results := [rule_match(rules[i].type, rules[i])]
```

Arrays are _static_. The number of elements in an array will not change.

For example, what would you expect if you replaced the variable `i` with a hardcoded number?

```
rule_results := [rule_match(rules[1].type, rules[1])]
```

You probably expect `rule_results` to be an array containing a single element (which would be the result of `rule_match`).

Importantly, the array would always contain a single element--it would never contain multiple elements. The _array_ has been defined _statically_.

If you change the array index from a hardcoded value to a variable, it does not change how the _array_ has been defined:

```
x := [rule_match(rules[i].type, rules[i])]
```

The array is still defined statically--OPA may find many results (each assignment to `i`) but the expression is still only constructing an array containing a single element.

To construct an array dynamically we need to use another language construct, an [array comprehension](https://www.openpolicyagent.org/docs/latest/policy-language/#comprehensions). Comprehensions build composite values (arrays, sets, objects) dynamically from queries:

```
[i | rule_match(rules[i].type, rules[i])]
```

Comprehensions consist of two parts (a head and a body):

Array comprehension: `[ <head> | <body> ]`
Set comprehension: `{ <head> | <body> }`
Object comprehension: `{ <head-key>: <head-value> | <body> }`

The head defines the value to add into the composite that's being constructed dynamically. The body defines the conditions under which a head should be added.

Hope this helps.

**Comment by ahmedtalhakhan** [comment]
Awesome! Thats really helpful. Thanks @tsandall
