### ISSUE TITLE
Debugging in VScode

### ISSUE THREAD

**Issue by Jeyakumardevarajulu** [open-policy-agent/opa#2616]
![OPA](https://user-images.githubusercontent.com/67360651/89777622-ac5adf00-db29-11ea-80c0-612147656497.png)

I have installed opa executable for windows and I have setup the path of the executable for vscode and when I try to run and I don't see OPA to run 

{
    "opa.path": "C:\\TestPolicy\\opa\\executable\\opa_windows_amd64.exe",
    "opa.checkOnSave": false,
    "opa.bundleMode": true,
    "opa.roots": [true]
}

## Expected Behavior
I don't see any option to run rego file.

**Comment by tsandall** [comment]
@Jeyakumardevarajulu what are you expecting to happen? The extension gives you a number of ways to interact with the policy (evaluation, testing, coverage, etc.) They're listed in the features section of the README (which are visible in the extension description): https://github.com/open-policy-agent/vscode-opa#features. Try running `OPA: Evaluate Package`.
