### ISSUE TITLE
Ability to selectively trace events based on Event type eg. topdown.NoteOp

### ISSUE THREAD

**Issue by vineet-garg** [open-policy-agent/opa#2618]
## Expected Behavior
While running OPA in embeded mode, need ability to selectively trace events based on Event type eg. topdown.NoteOp. Not just filter after obtaining a huge list of events trace.
## Actual Behavior
There is no ability to trace events selectively, Tracing all events causes the response time to go up 10 times. After obtaining events, filtering from a huge list of Events again shoots up the response time. 

## Steps to Reproduce the Problem
```
        ctx := context.Background()
	buf := topdown.NewBufferTracer()
	store := inmem.NewFromObject(*mymap)
	compiler := ast.NewCompiler()
        module := ast.MustParseModule(Policy)
	compiler.Compile(map[string]*ast.Module{"": module})
	if compiler.Failed() {
		fmt.Printf("Unexpected error(s): %v", compiler.Errors)
	}
	r := rego.New(
		rego.Compiler(compiler),
		rego.Store(store),
		rego.Query(AllowQuery),
		rego.QueryTracer(buf),
		rego.Trace(true),
	)
      pq, _ := r.PrepareForEval(ctx)
        _, _ := pq.Eval(*opa.Ctx, rego.EvalInput(inputJson), rego.EvalQueryTracer(buf))
       for _, event := range *buf {
		if event.Op == topdown.NoteOp {
			fmt.Printf("%v %q", event.Op, event.Message)
		}
	}
	//topdown.PrettyTraceWithLocation(os.Stdout, *buf)
```
## Additional Info

I am running OPA in my go application. I need to print some values during policy evaluation in logs. What is the best option. built-in trace("string") comes with lot of baggage as described above.

**Comment by tsandall** [comment]
You can implement the `topdown.QueryTracer` interface and record whatever events you want (e.g., only NoteOp events). Use the `rego.QueryTracer` option to supply your tracer (instead of using `Trace(true)`). In the trace config that your QueryTracer returns, set `PlugLocalVars` to `false` so that the evaluator doesn't have to materialize the local variable values (that's where the 10x cost comes from).

**Comment by vineet-garg** [comment]
It worked. Thanks!
