### ISSUE TITLE
istio-opa plugin is not working with centos-8

### ISSUE THREAD

**Issue by shibi1989** [open-policy-agent/opa#2619]
The Istio-opa plugin is not working with lentos-8, because ip table issue. see the log from proxy-init container

[root@ip-xxx-xx-x-xxx istio-1.6.7]# kubectl logs example-app-xxxxx proxy-init
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

Centos-8 is not using iptables .

**Comment by ashutosh-narkar** [comment]
You'll need to update the [proxy_init](https://github.com/open-policy-agent/contrib/blob/master/envoy_iptables/proxy_init.sh) script to use `nftables ` instead of `iptables ` and create a new `proxy_init` image. Let me know if you need any help.

**Comment by shibi1989** [comment]
Thanks for the support. Sorry I am not well in shell scripts , could you please help me to update the proxy_init image.

**Comment by ashutosh-narkar** [comment]
@shibi1989 we are currently not planning to support Centos-8 in proxy_init. Feel free to add a contribution to support this and we could possibly upstream it. Closing this for now.
