### ISSUE TITLE
How to efficiently query an incoming http request path in a huge list of REST API path

### ISSUE THREAD

**Issue by vineet-garg** [open-policy-agent/opa#2621]
## Expected Behavior
Trying to use OPA with an API gateway.
Looking for a way to match incoming HTTP request path to a huge list of REST API paths. Segments within a path can have variables.eg /base/resource/{resource-id}/foo/baar.{format}
## Actual Behavior
I began with converting my paths from API specs(swagger) to regular expressions and putting them in JSON document and iterating over the paths but I think there should be an efficient way as shown below.
## Steps to Reproduce the Problem
Simplifying the problem:
```
permsissions: [
"5": {
      "RestPermission": {
        "Path": "^[/]/upgrades/[^/]+/log[/]?$",
        "Method": "GET",
        "Scopes": [
          "read"
        ],
        "Audience": upgrader
      }
}]

allow { 
    permId := permIds[_]
    data.Permissions[permId].RestPermission.Method == input.Method
    re_match(data.Permissions[permId].RestPermission.Path, input.Path)
    trace(sprintf("Matching permission %v found.", [permId]))
    {x | x = data.Permissions[permId].RestPermission.Scopes[_]} == {x | x = input.Scopes[_]} & {x | x = data.Permissions[permId].RestPermission.Scopes[_]}
    trace("Scope validation passed.")
    {x | x = data.Permissions[permId].RestPermission.Audience[_]} == {x | x = input.Audience[_]} & {x | x = data.Permissions[permId].RestPermission.Audience[_]}
    trace("Aud validation passed.")
}
```
I have flexibility in structuring the paths JSON documents, so if structuring the data in a particular way helps reduce the search space, it will work as well. I don't impose any limitations on the API designers by making any assumptions. Once a matching path is found, I have to do additional validations like Oauth scopes matching, audience matching, etc, which is simple.

## Additional Info

Built-in 'walk' looked promising, but from what I understand, it does not support wildcards/variables as found in REST API specs.

**Comment by patrick-east** [comment]
For performance concerns with the policies be sure to read through https://www.openpolicyagent.org/docs/latest/policy-performance/ 

Now.. more specific to your use-case. If you have a large set of API paths you would ideally not have to iterate through all of them and apply their regex. Best case scenario you are able to leverage the indexing capabilities in OPA https://www.openpolicyagent.org/docs/latest/policy-performance/#use-indexed-statements to minimize that search space. With the URL matching you may be able to get away with using the glob matching features rather than regex (since regex's aren't understood by the indexer right now). This may or may not be possible with your requirements for the variables in the paths.

> Built-in 'walk' looked promising, but from what I understand, it does not support wildcards/variables as found in REST API specs.

Right, you would need to handle that in your data structure. The other potential performance issue is that you cannot short-circuit the walk when it matches some path, you would always iterate over the entire permissions object.

I guess before going too far onto other ideas, would it be possible to use glob matches for your paths?

**Comment by vineet-garg** [comment]
@patrick-east Thanks for the suggestions. With Glob, you are suggesting, if I am able to express my paths in the form of glob patterns instead of regex, and make one line change in policy (to call glob.match instead of re_match), OPA will automatically break down the policy into multiple policies and use indexing to reduce the search space?

**Comment by patrick-east** [comment]
> if I am able to express my paths in the form of glob patterns instead of regex, and make one line change in policy (to call glob.match instead of re_match), OPA will automatically break down the policy into multiple policies and use indexing to reduce the search space?

It may not be that simple, as documented on https://www.openpolicyagent.org/docs/latest/policy-performance/#use-indexed-statements there are some caveats about what type of expressions can be indexed.

> there is one (hopefully last) functional problem equally applicable to using re_match() glob.match(). Open API specs supports path conflicts eg. /foo/baar and /foo/{fooId} can both co-exist and and incoming path /foo/baar should match to /foo/baar and not /foo/{fooId} unlike /foo/1234. There can be any number of variables to add more complexity to the problem.

It seems like you would need to express some kind of ordering/precedence information for the paths in your `permissions`. How is that handled by the OpenAPI spec?

**Comment by vineet-garg** [comment]
@patrick-east This is how I describe my problem and pseudocode that can possibly solve it:

Suppose my API Gateway serves two endpoints:
```
Paths:  /base/myservice
            /base/{service-id}
```
Read OpenAPI specs and create json data as follows:
```
tree = base: {isleaf = false,
                       exactClildren: [ myservice: {isLeaf= true, exactChildren: nil, variableChildren: nil, details :{<security requirements>}} ]
                       variableChilderen: [ [^/]+: {isLeaf= true, exactChildren: nil, variableChildren: nil, details :{<security requirements>}} ]
                       details: null
                       }
```
sample input paths:
```
input1.path = {“base”, “myservice”}
input2.path = {“base”, “123”}
```
pseudocode for illustration.
```
returnMatchingNode(input.path, tree) (string, node) {
if path.size ==0 {
    if tree.isleaf return nil, tree
    else return nil // path did not lead to a valid leaf
}  else {
    find a child such that path[0] is one of exactChildren or else matches one of variableChildren
    if (child != nil) {
        returnMatchingNode(p[1:], tree[child])
    } else return nil
```        
We use Open API specs, so security requirements can only be specified at a leaf, and this is sufficient for me but this can be generalized to return a list of all nodes that had security requirements specified on path prefixes so that all requirements can be validated such as in case of web Apps.

**Comment by vineet-garg** [comment]
@patrick-east Do you think this is something that can be expressed using rego? If there is something similar that can be modified to achieve this, I am open to explore that.

**Comment by anderseknert** [comment]
Curious about how you proceeded with this @vineet-garg :) Did you find a workable model?

**Comment by vineet-garg** [comment]
> Curious about how you proceeded with this @vineet-garg :) Did you find a workable model?

@anderseknert I did not pursue with OPA. We just wrote our own evaluation logic.

**Comment by anderseknert** [comment]
Thanks for following up @vineet-garg ! I think the `returnMatchingNode` from your example could be translated using the [walk built-in](https://www.openpolicyagent.org/docs/latest/policy-reference/#graphs), but it would obviously need to be tested on your data set :)

I'll close the issue then and we can re-open if you come back to it later.
