### ISSUE TITLE
OPA Envoy Plugin: Support for multiple headers of same name

### ISSUE THREAD

**Issue by Jajcoszek** [open-policy-agent/opa#2628]
It would be nice if the opa-envoy-plugin supported setting a table of values for headers, similar to how how it's been done in Envoy: https://github.com/envoyproxy/envoy/pull/7851

It's needed to be able to send multiple cookies to the client, for example when making an `http.send` request and forwarding them. It's the format that `http.send` itself uses in the response, too.

This would mean that the following works:
```rego
default allow = {
  "allowed": false,
  "headers": {
    "x-ext-auth-allow": "no",
    "set-cookie": [
      "cookie1=value1; Path=/",
      "cookie2=value2; Path=/"
  ]},
  "body": "Permission denied",
  "http_status": 403
}
```

Right now it throws a type assertion error, as it expects a string.

**Comment by ashutosh-narkar** [comment]
The opa-envoy plugin uses the [go-control-plane](https://github.com/envoyproxy/go-control-plane) library which is a Go-based implementation of Envoy's data-plane-api.  The headers that are set in the response are of [this](https://github.com/envoyproxy/go-control-plane/blob/v0.9.0/envoy/api/v2/core/base.pb.go#L370) type. So for both the header key and value only string type is supported and hence the plugin only supports string values currently. Even the latest release of the library only supports string type.  We can re-visit this in the future if `go-control-plane` library supports other types for header values.

**Comment by Jajcoszek** [comment]
Oh, I see... Thanks for the answer!

**Comment by Jajcoszek** [comment]
On the other hand, `headers` is a string-to-string map and [only later](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/internal/internal.go#L497) it gets converted to `HeaderValue`. So the limiting factor here is just that the keys have to be unique, as it is not an array of `HeaderValue` objects, as in:

```json
{
  "headers": [
    {"set-cookie": "cookie1=value1; Path=/"},
    {"set-cookie": "cookie2=value2; Path=/"}
]}
```
which is what it is in the control plane in the end.

So in https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/internal/internal.go#L493 it should be possible to check for an array and add multiple `HeaderValue` objects to `responseHeaders` based on the current map key, as this is just an array of `HeaderValue`s and the unique key problem is not an issue for it?

Or am I not seeing something else?

**Comment by ashutosh-narkar** [comment]
Well you could update the policy itself so that the headers are a map to sting to string, thus simplifying the plugin code.  Feel free to open a PR if you think that approach won't work for your use-case.
