### ISSUE TITLE
unknown jws validation failure using opa-envoy-plugin

### ISSUE THREAD

**Issue by helpfulBadger** [open-policy-agent/opa#2640]
# Summary

- I'm using the latest envoy-opa-plugin with a simple docker compose environment. I'm trying to validate 3 jws identity tokens in OPA. I've tried by both decode_verify and simply verify. Rego policy test pass. OPA REST API works correctly. gRPC request from envoy fails. I've tried both ES256 and RS256 tokens. Numerous other tools validate the tokens as valid. Including https://jwt.io/

## Expected Behavior

- Passing valid JWS tokens in request headers should validatable by OPA

## Actual Behavior
- OPA returns a 403 error and seems like it isn't even following the default logic in the policy.

## Steps to Reproduce the Problem

1. `git clone https://github.com/helpfulBadger/envoy_getting_started.git`

1. `cd 05_opa_validate_jws
`
1. `docker-compose up -d`                                              # creates the environment

1. `./bug_report/bug_report_opa_grpc_api_tests.sh`      # shows the failure and captures logs

1. `./bug_report/bug_report_opa_rest_api_tests.sh`       # shows the same requests working fine via the OPA rest API

1. Docker compose [details are here](https://github.com/helpfulBadger/envoy_getting_started/blob/master/05_opa_validate_jws/docker-compose.yml) 

1. The [REGO Policy used is here](https://github.com/helpfulBadger/envoy_getting_started/blob/master/05_opa_validate_jws/policy.rego)

1. Logs showing the [gRPC failure are here ](https://github.com/helpfulBadger/envoy_getting_started/blob/master/05_opa_validate_jws/bug_report/bug_report_grpc_fails_opa_logs.json#L8-L11
)

1. [Envoy error logs](https://github.com/helpfulBadger/envoy_getting_started/blob/master/05_opa_validate_jws/bug_report/bug_report_grpc_fails_envoy_logs.txt#L181-L230) showing what it sent to OPA

1. [Logs showing the REST API working fine](https://github.com/helpfulBadger/envoy_getting_started/blob/master/05_opa_validate_jws/bug_report/bug_report_rest_succeeds_opa_logs.json#L8-L13) with the same tokens

## Additional Info
The entire environment is just running in docker. The results do not change whether OPA is running for a short or long period of time. The issue happens with these 3 versions of OPA

- openpolicyagent/opa:0.23.0-envoy

- openpolicyagent/opa:0.22.0-envoy

- openpolicyagent/opa:0.21.1-istio

**Comment by ashutosh-narkar** [comment]
The GRPC use-case fails since the opa-envoy plugin expects the `headers` field in your `allow`  rule to be a map with both keys and values as string. Your headers are a map of string to bool as defined [here](https://github.com/helpfulBadger/envoy_getting_started/blob/master/05_opa_validate_jws/policy.rego#L97). Here's an updated policy that results in passing for the GRPC use-case. 

```ruby
package envoy.authz

import input.attributes.request.http as http_request

default allow = {
  "allowed": true,
  "headers": {"validation": "unknown failure", "set-by": "Global_Default"},
  "body": "OPA Logic failure to reach here",
  "http_status": 200
}

jwks = `{
  "keys": [
    {
      "use": "sig",
      "kty": "EC",
      "kid": "APIGW-ES256",
      "crv": "P-256",
      "alg": "ES256",
      "x": "g3uF5OZrWsU6yKJhv0FQxhALlmNbw6_Wa9_exT3-eNA",
      "y": "lJbCP1oz0vDs6Dxd_3my5Ga5fLSXRDzQVbTTlt9pr98"
    },
    {
      "use": "sig",
      "kty": "EC",
      "kid": "custIDP-ES256",
      "crv": "P-256",
      "alg": "ES256",
      "x": "HmVjNgoTIECfvja3E7WZX2H1OzXtvDhD5_SSMXGYxZU",
      "y": "ugCW-AoKaSyNqIbyNUgRWMJ8WY6s2W78YI2LdVVTGcY"
    },
    {
      "use": "sig",
      "kty": "EC",
      "kid": "workforceIDP-ES256",
      "crv": "P-256",
      "alg": "ES256",
      "x": "_Vg3wsKsY9XH5E5aPn2SLUTUljgum2TXnDY7m73p2Ek",
      "y": "rSbvTXUdPnFpJq5zqgRLMMAQP8bJ7UcggP1ERkEibGI"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "APIGW-RS256",
      "alg": "RS256",
      "n": "thiAsWa8crD-RhGbAewoYjyWpgZpaFKHWqzqAM2iCJ94eQnSwFJJcFayOklSfKK8tUUYulG7FQijpdBLVzbilPtpYK8HjHoLZBLrvNPbEvwlMCVMDX5ttyn1lJV-6momFwuV6EJFnPMXJQU3KTX_QeFejiamxmYQsakyWxxDtTWJ1XAlvtIX3k0osQbFrLbF5SGIwAk9UBFlm2B_3M0lbqu6w8eOxgSc3z-Owd6maYu2Q43MZv-opjObHNfcc60o90iOO9pY5_qSkJt7Slf2cuKU6eOUjsoSCOgValKngogup_itt7LJkrt-ugFiwUITEt6V6MY1MHEw1RgM75N_iQ",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "custIDP-RS256",
      "alg": "RS256",
      "n": "z6AtZ3MpSZ1dd-AFyfxk5stjIrbLa8GLSq0GPqZ5RciZIkv-ad-phosgPSDvG1Nx4pcZcENrXAdMA6v6FjRvdGT0EH9CU2vXTu5kCmGP1vV1WfzFdL3K-mswnEaT6-9bO4-m6SEmR3J3YV5QwFVvxIVJqFSmLIggl1PVCM0pXCYb6vkcacg24E-vh6J28LdZmQFqmWHrF7mOL59oz1Gx8ePOr4WnqhP991DeIpzgiofGAS7QQSiNQoKvtizITk3-kcpjWmdw0Zh32xmhsUCu4NKn8DjY2dJ2-WwcL3KK__E0WBJt3I97Nr-m88BSEVl3-P--fsRiEgIP1Co2ulGMbQ",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "workforceIDP-RS256",
      "alg": "RS256",
      "n": "ucjZ1pagZuXL4GkFXzG7llZbhPUkl1GzG2vyE0YC3NCvgf2WS67KRH6ck_iMHsWraaPdEcbB8t6ftr0qEXC1ciwVc656Q4V4L_-pxWcD1XMfdiZoViaKyMlq1QzB55XgzM1g7cvgg6_rCmTEmTo3-LUvFd7HxpdHdkYz0U_EUmEB8amz3NxR3LaB-STyxnlsRDrIKmYqDNaPqArdn44INwkGeuJUir0ojw5gdbbazT1NIsuJb2y0zHXuu9ESnyKB8N40ydYe2ECxkdynOQaHt8tCKWhh3F32VwOOuZx34RuVSA_bQraGrduVBd05fEdsPUxq38f1-Z7I5YuokqE_Dw",
      "e": "AQAB"
    }
  ]
}`

verify_subject {
    subject := http_request.headers["subject-token"]
    io.jwt.verify_es256(subject, jwks)
}

verify_subject {
    subject := http_request.headers["subject-token"]
    io.jwt.verify_rs256(subject, jwks)
}

verify_actor {
    actor := http_request.headers["actor-token"]
    io.jwt.verify_es256(actor, jwks)
}

verify_actor {
    actor := http_request.headers["actor-token"]
    io.jwt.verify_rs256(actor, jwks)
}

verify_app {
    app := http_request.headers["app-token"]
    io.jwt.verify_es256(app, jwks)
}

verify_app {
    app := http_request.headers["app-token"]
    io.jwt.verify_rs256(app, jwks)
}


allow = response {
  verify_subject
  verify_actor
  verify_app

  response := {
      "allowed": true,
      "headers": {
        "Customer-Authenticated": "true",
        "Agent-Authenticated": "true",
        "App-Authenticated": "true"
      }
  }
}
```

**Comment by helpfulBadger** [comment]
Thank you SOOOO much for finding the problem. I spent 2 days trying to figure out why it didn't work.


Would it be possible to have the Envoy plugin detect and marshal any valid JSON into strings?

Mike

**Comment by ashutosh-narkar** [comment]
The opa-envoy plugin uses the [go-control-plane](https://github.com/envoyproxy/go-control-plane) library which is a Go-based implementation of Envoy's data-plane-api. The headers that are set in the response are of [this](https://github.com/envoyproxy/go-control-plane/blob/v0.9.0/envoy/api/v2/core/base.pb.go#L370) type. So for both the header key and value only string type is supported and hence the plugin only supports string values currently. 

Although it would be better if the policy itself defined the headers as a map of sting to string, thus simplifying the plugin code, we could update the plugin to handle valid JSON as you've suggested or at least we could make it explicit in [this](https://github.com/open-policy-agent/opa-envoy-plugin#example-policy-with-object-response) section of the docs that the headers is a string-string map.

WDYT ?

**Comment by helpfulBadger** [comment]
Explicit documentation would be a minimum. I tried searching the code base for the error message I was getting and couldn't find it.  So, it seems reasonable to expect the policy to supply a string. It just needs to be clear that there is a contract that the plugin is expecting you to conform to. 

Once again, thank you so much!

**Comment by ashutosh-narkar** [comment]
Happy to help ! Thanks for your feedback ! We will add the necessary documentation.
