### ISSUE TITLE
What storage does it support? Mysql, redis, or others?

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2652]
What storage does it support? Mysql, redis, or others?

**Comment by tsandall** [comment]
OPA stores policy and data used for making decisions in-memory. There's no built-in support for MySQL, Redis, or others.

**Comment by andyyumiao** [comment]
> OPA stores policy and data used for making decisions in-memory. There's no built-in support for MySQL, Redis, or others.

My understanding is that if the instance where the service is located is hung up, what should I do if the data is lost?

**Comment by tsandall** [comment]
OPA is not the source of record for policy and data--you can load that those through different mechanisms. The recommended approach is to configure OPA to download [Bundles](https://www.openpolicyagent.org/docs/latest/management/#bundles) from a remote service.

**Comment by andyyumiao** [comment]
> OPA is not the source of record for policy and data--you can load that those through different mechanisms. The recommended approach is to configure OPA to download [Bundles](https://www.openpolicyagent.org/docs/latest/management/#bundles) from a remote service.

OK，got it， many thnaks！！！
