### ISSUE TITLE
Netlify build is not reliable

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2656]
The Netlify script(s) don't wait long enough for release binaries to show up when a release is triggered. As a result, the Netlify build has to be triggered manually. One option is to crank the timeout on waiting for the binaries to show up. Another option is to just build the binaries locally.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/pull/3972

**Comment by tsandall** [comment]
Let's see how things go with #3972 in place. If we find that it's reliable, we could just close this.

**Comment by tsandall** [comment]
Looks like the band-aid is working 🤞 The post-release job ran and kicked Netlify as expected and the website updated w/o any errors. Also, the Netlify deploys show that 0.35.0 was skipped during the time between when the tag was created and the release was published.
