### ISSUE TITLE
Improved Custom Plugin Documentation

### ISSUE THREAD

**Issue by kubaj** [open-policy-agent/opa#2664]
It would be great to have better custom plugin documentation, specifically `logs.EventV1` structure which contains many fields but it's not straightforward what exactly these fields mean. Then there are fields Input and Result which don't have types and it's difficult to extract information that is needed in the decision log. 

## Steps to Reproduce the Problem

* OPA version: 0.22.0

**Comment by tsandall** [comment]
@kubaj do you have something specific in mind? The `logs.EventV1` structure pretty maps 1-1 to the Decision Log API (which is well documented): https://www.openpolicyagent.org/docs/latest/management/#decision-log-service-api. If you have something concrete in mind, we can keep this open. The input and result fields are untyped for good reason (callers can supply arbitrary input data and policies can generate arbitrary result data.)

**Comment by kubaj** [comment]
@tsandall ah, nice, that's exactly what I was looking for! Can we link it within [this doc](https://www.openpolicyagent.org/docs/latest/extensions/#custom-plugins-for-opa-runtime)?

Regarding input and result fields – I expressed myself inaccurately in my original message. I see the motivation behind not having a type for fields input and result, but I'd find helpful to just leave a comment there that says that result of the policy is mapped 1:1 to result in the logs.EventV1. For example, if I have the following policy:
```
allowed = false

allowed {
  input.method == "GET"
}
```

then I can do:

```go
...
result, ok := (*event.Result).(bool)
...
```

I just wasn't sure if the result field have or doesn't have additional data.
