### ISSUE TITLE
Custom Plugins for Bundle/Data loading

### ISSUE THREAD

**Issue by drewwells** [open-policy-agent/opa#2667]
As a consumer of OPA, I want to abstract the storage backend of bundles for writing custom loaders. These loaders would be highly specialized and probably not suitable for inclusion in the standard OPA package. This would use the go plugin architecture https://golang.org/pkg/plugin/

The plugin would be loaded by OPA and opa could wait on initial loading, then offer an eventing system for pushing bundle updates to OPA. As an example, we'll look at implementing the K8s ConfigMap API in OPA via a plugin.

```
type Loader interface {
  // Ready configures the plugin with options, if needed, and gets notified the Plugin is ready
  Ready(LoaderConfig...) error
  // RegisterEventStream passes a method to the plugin
  // This func can be called to push updates to OPA. We could support
  // sending the actual bundle data or a HTTP url to call to fetch it.
  RegisterSender(Sender)
}

// Sender registers an interface with the plugin to push 
// bundles to OPA
type Sender interface {
  // Send accepts a bundle for notifying OPA of an update
  Send(bundle.Bundle) error
}
```

1. OPA Loads Plugin and queries availability of Interface Methods. We can support a variety of interfaces with plugin.Lookup() checks
2. OPA configures the Plugin with required Options
3. OPA calls RegisterSender() to pass methods for the plugin 
4. Plugin performs necessary initialization and calls Sender.Send when updates bundles are prepared
5. OPA waits for notification on Send and loads the new data. The send method can block until this entire operation is complete.

![image](https://user-images.githubusercontent.com/239123/91588574-fca1b180-e91d-11ea-9c40-036c980b3b56.png)

**Comment by patrick-east** [comment]
OPA historically provided support for binary plugins as suggested, but we found that they were very brittle. Nearly all users has to build OPA from source with the same toolchain that the plugin was built from, so there was not really any advantage over having OPA be very simple to extend.

The current suggested approach is to use OPA as a library and, if you wanted the same look and feel as "normal" OPA binaries, wrap its entry points. Take a look at https://www.openpolicyagent.org/docs/latest/extensions/#custom-plugins-for-opa-runtime

What you would need to do to support your use-case of loading data is to keep a reference to the [Manager](https://godoc.org/github.com/open-policy-agent/opa/plugins#Manager) which is passed into your plugins [New(..)](https://godoc.org/github.com/open-policy-agent/opa/plugins#Factory) implementation. That gives you direct access to the [Store](https://godoc.org/github.com/open-policy-agent/opa/storage#Store) which the runtime is using, so you can open transactions and write whatever data/policies you want into it.

**Comment by drewwells** [comment]
The manager explanation makes sense, we'll investigate this approach. Thanks!
