### ISSUE TITLE
Opa panics during partial evaluation

### ISSUE THREAD

**Issue by j-denner** [open-policy-agent/opa#2678]
## Expected Behavior
Partial evaluation should not panic.

## Actual Behavior
Depending on the order of comparison `["a", "b"][_] == __dat.test` versus `__dat.test == ["a", "b"][_]` opa panics during partial evaluation. 

## Steps to Reproduce the Problem

The following code contains four test examples. The first three are successful while the forth fails.
While tests 1 & 2 are successful, test 3 & 4 have a switched comparison in the allow_... rule. The switched comparison works for eval (test 3) but not for partial (test 4).

This panic **only** happens, when the `__dat` rule has an `else` clause.

```
# Filename: bug.rego
#
# Input:
# {
#    "data1": {
#        "test": "a"
#    }
# }
package rego


__dat = x {
  x := input["data1"]
} else = x {
  x := input["data2"]
}

allow_OK {
	["a", "b"][_] == __dat.test
}

allow_Issue {
	__dat.test == ["a", "b"][_]
}

# Tests:
# ======
# opa version
# >> Version: 0.23.2
#
# opa eval -d bug.rego             -i input.json data.rego.allow_OK # Success
# >> { ... }
#
# opa eval -d bug.rego -p -u input -i input.json data.rego.allow_OK # Success
# >> { ... }
#
# opa eval -d bug.rego             -i input.json data.rego.allow_Issue # Success
# >> { ... }
#
# opa eval -d bug.rego -p -u input -i input.json data.rego.allow_Issue # opa panics
# >> panic: interface conversion: ast.Value is ast.Array, not ast.Var
# >>
# >> goroutine 1 [running]:
# >> github.com/open-policy-agent/opa/ast.outputVarsForTerms.func1(0xc0002a2d40, 0x19e9800)
# >> 	github.com/open-policy-agent/opa/ast/compile.go:2481 +0x1cf
# >> github.com/open-policy-agent/opa/ast.WalkTerms.func1(0x189b140, 0xc0002a2d40, 0xc0002a2c40)
# >> 	github.com/open-policy-agent/opa/ast/visit.go:181 +0x42
# >> github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk(0xc00027ae38, 0x189b140, 0xc0002a2d40)
# >> 	github.com/open-policy-agent/opa/ast/visit.go:270 +0x58
# >>  ...
```

**Comment by tsandall** [comment]
@j-denner thanks for filing this. It looks like an issue in some of the term rewriting that's done to accept terms like `["a", "b"][_]`. We'll get this fixed in the next release.
