### ISSUE TITLE
wasm: Implement net.cidr functions natively

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2681]
The wasm library should implement the [net.cidr](https://www.openpolicyagent.org/docs/latest/policy-reference/#net) functions natively. This issue supersedes #1114.

**Comment by koponen-styra** [comment]
Update: master has now wasm implementations for net.cidr_contains,net.cidr_overlap, and net.cidr_intersects.

**Comment by tsandall** [comment]
We're currently missing native support for `net.cidr_contains_matches`, `net.cidr_merge`, and `net.cidr_expand` however those are not widely used so I'm closing this issue for now. If the need arises we can open issues in the future to track that work.
