### ISSUE TITLE
Local system.authz ignored when bundles are active?

### ISSUE THREAD

**Issue by zerok** [open-policy-agent/opa#2684]
Hi 👋

When I try to configure token-based authentication with basic authorisation I get some weird behaviour with version 0.23.2: I'm using the following command to start opa:

	$ opa run --server --authorization basic --authentication token local/authz.rego --config-file config.yaml

`local/authz.rego` contains the following policy:

	package system.authz
	default allow = false
	allow {
		input.identity
	}

The config file is empty.

When I now query /v1/policies *without* a token I get the expected error message:

	$ curl -X GET http://localhost:8181/v1/policies
	{
		"code": "unauthorized",
		"message": "request rejected by administrative policy"
	}

Providing a token resolves it:

	$ curl -X GET http://localhost:8181/v1/policies -H "Authorization: Bearer hello"
	{"result":[{"id":"local/authz.rego","raw":"package system.authz\n\ndefault allow = false\n\nallow {\n    input.identity\n}\n","ast":{"package":{"path":[{"type":"var","value":"data"},{"type":"string","value":"system"},{"type":"string","value":"authz"}]},"rules":[{"default":true,"head":{"name":"allow","value":{"type":"boolean","value":false}},"body":[{"index":0,"terms":{"type":"boolean","value":true}}]},{"head":{"name":"allow","value":{"type":"boolean","value":true}},"body":[{"index":0,"terms":{"type":"ref","value":[{"type":"var","value":"input"},{"type":"string","value":"identity"}]}}]}]}}]}

So far, so good. But when I now add a bundle to the config file, the content of local/authz.rego seems to be ignored. That's the config file:

```
services:
  - name: "upstream"
    url: "https://zerokspot.com/t/"

bundles:
  upstream:
    service: upstream
    resource: sample-bundle.tar.gz
```

Now it looks like that opa does no longer look for the system.authz changes:

```
curl -X GET http://localhost:8181/v1/policies -H "Authorization: Bearer hello"
{
  "code": "internal_error",
  "message": "authorization policy missing or undefined"
}
```

Any idea what I'm doing wrong here? Thank you 😀

**Comment by patrick-east** [comment]
Couple of things to check:

* Do you define `roots` in the bundle manifest? (https://www.openpolicyagent.org/docs/latest/management/#multiple-sources-of-policy-and-data). It is possible that the bundle is overwriting the files loaded in on the CLI, you can check for that case by running with the `--bundle` CLI flag pointing at the authz policy's directory. It would then be treated as a bundle in OPA and conflicts would be checked, you'd see an error message indicating as much when the remote bundle was downloaded.

* Are there any errors or other indications in the OPA debug logs that indicate something going wrong? (Or I guess maybe the ask here is to just share the logs if possible).

* Was there any difference in the CLI arguments between the two? Or only the config.yaml changes?

**Comment by zerok** [comment]
@patrick-east Thank you :) It was the missing roots declaration :)
