### ISSUE TITLE
Pull Data during Evaluation

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2685]
I want to use option5 of https://www.openpolicyagent.org/docs/latest/external-data
do you have the document for how to deploy opa in this mode?

**Comment by patrick-east** [comment]
That option refer's to using the `http.send` builtin function in your policy. There is documentation for the builtin here: https://www.openpolicyagent.org/docs/latest/policy-reference/#http

There isn't anything special that needs to be done to deploy OPA for this mode, it is more of a change in how you structure/write the policies.

**Comment by andyyumiao** [comment]
> That option refer's to using the `http.send` builtin function in your policy. There is documentation for the builtin here: https://www.openpolicyagent.org/docs/latest/policy-reference/#http
> 
> There isn't anything special that needs to be done to deploy OPA for this mode, it is more of a change in how you structure/write the policies.

If i use it in a production environment, which deployment mode is the best? for options in https://www.openpolicyagent.org/docs/latest/external-data

**Comment by andyyumiao** [comment]
> That option refer's to using the `http.send` builtin function in your policy. There is documentation for the builtin here: https://www.openpolicyagent.org/docs/latest/policy-reference/#http
> 
> There isn't anything special that needs to be done to deploy OPA for this mode, it is more of a change in how you structure/write the policies.

Can you provide a detailed demo for this?

**Comment by patrick-east** [comment]
> If i use it in a production environment, which deployment mode is the best? for options in https://www.openpolicyagent.org/docs/latest/external-data

The summary in https://www.openpolicyagent.org/docs/latest/external-data/#summary gives a recommendation for which approach to use depending on the type of data (the "Recommended Data" column) and the limitations associated with that approach ("Limitations" approach).

Generally speaking we would recommend using bundles https://www.openpolicyagent.org/docs/latest/external-data/#option-3-bundle-api unless there are requirements for the use-case which prevent using them.

> Can you provide a detailed demo for this?

There are examples for using `http.send()` in the reference doc, but we don't have any detailed demo's for using it on the OPA documentation ☹️

**Comment by andyyumiao** [comment]
> unless there are requirements for the use-case which prevent using them.

OK，got it，thanks very much for the greate solution!
