### ISSUE TITLE
Watching input files for changes does not work in MacOS

### ISSUE THREAD

**Issue by iofik** [open-policy-agent/opa#2697]
I could not make `-w/--watch` switch work on my mac, although it perfectly works when run in Linux container.

## Steps to Reproduce the Problem

Unpack `data.json` and `policy.rego` from [data.zip](https://github.com/open-policy-agent/opa/files/5213731/data.zip).
Run:
```
opa run --server --addr=localhost:8181 -w policy.rego data.json
```
Call:
```
echo '{ "input": { "path": "/test" } }' | curl http://localhost:8181/v1/data/example/allow -d@-
```
Edit `data.json`, replacing `/test` with `/test1`. Call `curl` again:
```
echo '{ "input": { "path": "/test" } }' | curl http://localhost:8181/v1/data/example/allow -d@-
```

## Expected Behavior
```
{"result":true}
{"result":false}
```

## Actual Behavior
```
{"result":true}
{"result":true}
```

## Additional Info

```
$ opa version
Version: 0.23.2
Build Commit:
Build Timestamp:
Build Hostname:

$ uname -a
Darwin myhost.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

Update: Although when an entire dir is specified instead of individual files, the feature is working:
```
opa run --server --addr=localhost:8181 -w .
```

**Comment by tsandall** [comment]
@iofik can you share the OPA logs from when you ran this experiment? You should see something like "Processed file watch" when you save the file. I just tried this out on macOS and it worked fine (using Darwin 19.5.0 mind you).

**Comment by iofik** [comment]
Sorry, seems to be my bad. That's probably related to how `vim` writes the files. This:
```
{"duration":156056,"err":"1 error occurred during loading: stat data.json: no such file or directory","level":"warning","msg":"Processed file watch event.","time":"2020-09-14T21:48:16+03:00"}
```
happens only when I edit `data.json` with `vim`. Otherwise everything works fine.
