### ISSUE TITLE
Duplicate import references shouldn’t be allowed

### ISSUE THREAD

**Issue by mikol** [open-policy-agent/opa#2698]
## Expected Behavior

The following code defines `foo` four times.

```rego
package play

import data.foo
import data.bar as foo
import data.foo
import input.foo

x := foo
```

The actual value referenced by `foo` depends on how the imports are ordered (the last import wins). Overwriting prior imports of the same name (i.e., `foo`) can lead to unexpected behavior so should be caught at parse or compile time.

## Actual Behavior

OPA selects the last import without raising an error.

## Steps to Reproduce the Problem

* OPA v0.23.2

**Comment by tsandall** [comment]
This is a reasonable expectation though the change would be backwards incompatible. I think it's unlikely that many users would be affected by this change but we should leave the issue open for a little while and do some investigation to see how many policies in wild would be impacted.
