### ISSUE TITLE
Client library for REST API

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#270]
Integrating with OPA would be easier if we had a client library that handled request/response wrappers, metrics, logging, etc. Creating a ticket to track work related to this.

**Comment by repenno** [comment]
We will take care of a Python3 client

**Comment by tsandall** [comment]
@repenno: Excellent. Looking forward to this.

Where would you like the client library to live? Would it be useful to have another repository? E.g., github.com/open-policy-agent/opa-client-python?

**Comment by tsandall** [comment]
See https://github.com/open-policy-agent/client-python for Python client. In the future, it would be nice to have clients for other languages as well.
