### ISSUE TITLE
OPA docker terminates under reasonably high load

### ISSUE THREAD

**Issue by balasenthil-d** [open-policy-agent/opa#2704]
We are doing some performance tests and when we run the service in bundle service mode with 5 min pull interval and with 2 core and 4GB RAM.

When we run 100 concurrent users with 10 loop count, the OPA service terminates and not able to continue processing. 

OPA service is run as docker image with version 0.23.2.

## Expected Behavior
Able to scale up to 1000 concurrent users. 

## Actual Behavior
Starts failing with 100 concurrent users
## Steps to Reproduce the Problem
1. Load 10,000 users and a rego file with just one rule. 
2. Provision 2 vCPU and 4GB RAM in AWS fargate / local docker process
3. version: 0.23.2

**Comment by patrick-east** [comment]
Can you provide more details about the issue? For example, what do you mean by concurrent users? Concurrent API requests? If so, what kind of API requests?

Can you provide actual steps to reproduce the problem (so that an OPA developer could reproduce the issue...)

**Comment by balasenthil-d** [comment]
Yes these are concurrent requests. The requests are generated through jmeter script.

Steps to reproduce
1. Have s bundle server that exposes an endpoint to pull zip file at regular intervals. The zip has one to file with one rule and a days json with 10k records. Run opa as docker server pulling from bundle server every 5 mins.
2. Run jmeter script that invokes the rule in rego file with a mix of inputs: some that are in data and some not in data
3. Run with 50, 100 threads with a ramp up of 20 seconds
4. You will see opa docker gets terminated on high load

**Comment by tsandall** [comment]
@balasenthil-d thanks for listing those steps but there's some crucial information we don't have yet:

1. Scripts you wrote to send traffic to OPA
1. Scripts/configs you wrote to start OPA
1. The .rego file in question
1. A sample of the 10K record data set

Please help us out by providing a minimal example that reproduces the issue; it'll save us a lot of time.

**Comment by patrick-east** [comment]
@balasenthil-d any chance you can provide the additional information requested by @tsandall ?

**Comment by patrick-east** [comment]
Going to close this. Feel free to re-open if more info can be provided.
