### ISSUE TITLE
Decisions logs response: Log upload skipped.

### ISSUE THREAD

**Issue by nestajah** [open-policy-agent/opa#2706]
## Expected Behavior

The decisions_logs are enabled and the gzip file is expected to be sent.

## Actual Behavior

The decisions_logs are enabled but it does not show any type of error in the logs only information. Only gets this message in logs even if we set the log in debug mode:

{
  "level": "info",
  "msg": "Log upload skipped.",
  "plugin": "decision_logs",
  "time": "2020-09-17T19:09:16Z"
}

## Steps to Reproduce the Problem

* OPA version = 0.23.2-envoy
* OPA config =
services:
  controller:
    url: https://url for bundle
    allow_insecure_tls: true
  logstash: 
    url: https://IP:PORT <--- URI for decisions logs
    allow_insecure_tls: true
    
bundles:
  opa-test:
    service: controller
    resource: Bundle URL
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120

decision_logs:
  partition_name: /
  service: logstash
  reporting:
    min_delay_seconds: 60
    max_delay_seconds: 120

* Example output that OPA returned

{
  "level": "info",
  "msg": "Log upload skipped.",
  "plugin": "decision_logs",
  "time": "2020-09-17T19:09:16Z"
}

## Additional Info

OPA server over AKS 1.16.13

**Comment by patrick-east** [comment]
As I understand it the "Log upload skipped" message happens when there is nothing to upload in the buffer when the plugin attempts to flush a batch of decisions.

To clarify the steps to reproduce the problem, are you making evaluation API calls to OPA?

**Comment by nestajah** [comment]
Thanks for your response @patrick-east. We are testing certain configurations in OPA for the whole issue of cross-microservice authorization. We assume that all traceability will be sent to the server that is configured or that shows an error about loading this information.

**Comment by patrick-east** [comment]
>  We assume that all traceability will be sent to the server that is configured or that shows an error about loading this information.

All "decision" logs are sent there, which means 1 log entry for every evaluation call the server processes. The current "Steps to reproduce the problem" make sense, and is behaving correctly. as you do not make any API requests. Try making a call, for example, to the `/v1/data` API to evaluate something and you should see a decision log sent as part of the next batch (which could be 60-120 seconds later, based on your posted config).

**Comment by nestajah** [comment]
OK, that point is clear to me, but for example if I load a wrong file like configmap, opa detects it, then it should try to upload the logs right?

Thanks for the support

**Comment by patrick-east** [comment]
> for example if I load a wrong file like configmap, opa detects it, then it should try to upload the logs right?

No, it would not. They are _only_ for the policy decisions results (essentially an audit log for that OPA instance).

For monitoring the status of OPA, including if one of the bundles was an invalid file, there is a separate [Status API](https://www.openpolicyagent.org/docs/latest/management/#status), otherwise for logging you will need to collect the OPA stdout/stderr output.

**Comment by nestajah** [comment]
Ok, The decisions type logs are the ones that will be sent gzip type. You will always prepend /logs before the partition-name that you define: Ex:

partition-name: dev

The Uri would be /logs/dev
?

**Comment by tsandall** [comment]
Yes, the URL that logs are sent to will be `<SERVICE_BASE_URL>/logs`. If a partition name is configured, it will be appended. Clsoing this issue because there doesn't appear to be any bug in OPA.
