### ISSUE TITLE
Flush decision logs on graceful shutdown

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#2710]
## Expected Behavior

An attempt is made to flush the decision logs currently buffered to the remote server on graceful shutdown. This should at least be attempted once, but probably until the buffer has been flushed or until `--shutdown-grace-period` is reached. 

## Actual Behavior

Buffered decision logs are discarded on SIGINT/SIGTERM.

## Steps to Reproduce the Problem

1. Start OPA with decision logging to remote server configured.
2. Send a couple of queries to generate decisions.
3. Terminate the OPA server by sending a SIGINT/SIGTERM (ctrl +c, kubectl delete pod, etc).
4. Check the decision log server for log entries (there will be none since the last configured push interval).

**Comment by tsandall** [comment]
Thanks for filing @anderseknert. We've got another issue tracking this so I'm going to close this one (#780).

**Comment by anderseknert** [comment]
@tsandall I thought I searched thoroughly for "decision" before spending an hour debugging this last night - apparently there was a page 2 to those search results 🤦 Doesn't matter though, what's important is that it's tracked! I was actually thinking I might take a shot at this one if you guys have the patience to deal with that, given I've not coded much in Go before.
