### ISSUE TITLE
Expression Evaluator in rego policy

### ISSUE THREAD

**Issue by amar1728** [open-policy-agent/opa#2711]
Is it possible to evaluate an expression in rego policy. For example, suppose there is a string "employee.age > 25" and employee.age is replaced with the value that is sent in the input, which would result in something like "23 > 25" or "28 > 25". When evaluated the string should return the result. This would help in doing operations like the following
output := eval("23 > 25")
output := eval("'image1' != 'image2'")
output := eval("'bucket123' == 'bucket12'")

If there is no such feature available, is it possible to create a function that could do this.

**Comment by tsandall** [comment]
@amar1728 no - there's no such built-in function today and it would be better if it stayed that way :-)

You could encode expressions into the input data and evaluate them inside of Rego, but think carefully before doing so:

```json
{
  "expr": {
     "op": ">",
     "args": [23, 25]
  }
}
```

```rego
package interp

p {
   eval(input.expr.op, input.expr.args)
}

eval("!=", args) {
   args[0] != args[1]
}

eval(">", args) {
   args[0] > args[1]
}
```

**Comment by amar1728** [comment]
@tsandall Thank you for the response. Would you let me know why I need to be careful if I do something you suggested.

**Comment by tsandall** [comment]
I'd mostly worry about performance and readability. For simple examples like the one above, it's fine. If you end up with logical AND, OR, etc. then you're basically just reinventing a fragment of Rego and then implementing that inside of Rego.
