### ISSUE TITLE
input.identity is not available outside of the system namespace

### ISSUE THREAD

**Issue by mneil** [open-policy-agent/opa#2712]
# Expected Behavior

When I make a request with a JWT bearer token I expect to be able to use `input.identity` in my package and inspect the payload / use it as additional input.

## Actual Behavior

When I make a request with a JWT bearer token I can decode it in my `system.authz` package and verify the caller identity. This token is available in `input.identity`. When I try to use `input.identity` in any package outside of the `system.authz` namespace the token is empty.

## Steps to Reproduce the Problem

v0.23.2

### Rego Files

Create a rego file like:

```
# token.rego
package system.authz

# Helper to get the token payload.
token = {"payload": payload, "header": header} {
  # Verify the signature against publicly known information
  io.jwt.verify_rs256(input.identity, data.bundles.system.authz.jwks)
  # Decode the payload
  [header, payload, _] := io.jwt.decode(input.identity)
}
```

Pass in a valid token where the jwks data can verify the signature of the key. Decodes the payload and returns it for inspection:

```
# authorization.rego
package system.authz

import data.system.authz.token

default allow = false  # Reject requests by default.

allow {
  # Allow any valid JWTS from mmm-id.auth0.com
  token.payload.iss == "https://issuer.auth0.com/"
  token.payload.exp * 1000000000 > time.now_ns()
  # Do any other required validation of the payload here.
  # Example. Only allow specific audience(s) or check additional data
}
```

Create a package in another namespace

```
# playground.rego
package playground

import data.system.authz.token

# evaluates false
allow {
  token.payload.iss == "https://issuer.auth0.com/"
}
```

Where I define the token method has no impact. I tried redefining the token in the same `playground` namespace to no effect.

### Input

POST `http://localhost:5000/v1/data/playground/allow`

Requires a valid JWT token from issuer `https://issuer.auth0.com/` (example issuers - not real)

```json
{}
```

### Response

{
  "decision_id": "0814ebe5-eaa6-4186-bf84-5254bffbd875",
  "result": false
}

**Comment by patrick-east** [comment]
Couple of things to maybe clarify. The OPA API authz functionality which uses the `system.authz` package as described in https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization will, for `--authentication=token` and `--authorization=basic`, have the `input.token` set to the bearer token on the request to OPA for the evaluation of the authz policy. This will _not_ be the same `input` that the query is evaluating against.

For example:

Same files as described in the issue, modified a tiny bit to use a HS256 secret for the token instead (i just made one from jtw.io with a secret and added the correct `iss` field) and removed the check for `exp` so this example will continue to work for anyone in the future.

```
$ cat authorization.rego
# authorization.rego
package system.authz

import data.system.authz.token

default allow = false  # Reject requests by default.

allow {
  # Allow any valid JWTS from mmm-id.auth0.com
  token.payload.iss == "https://issuer.auth0.com/"
  # Do any other required validation of the payload here.
  # Example. Only allow specific audience(s) or check additional data
}
$ cat token.rego
package system.authz

# Helper to get the token payload.
token = {"payload": payload, "header": header} {
  # Verify the signature against publicly known information
  io.jwt.verify_hs256(input.identity, "s3cret")
  # Decode the payload
  [header, payload, _] := io.jwt.decode(input.identity)
}
$ cat playground.rego
package playground

import data.system.authz.token

# evaluates false
allow {
  token.payload.iss == "https://issuer.auth0.com/"
}
```

Start up OPA as as server with the token auth options:
```
$ opa run -s --authentication=token --authorization=basic ./token.rego ./playground.rego ./authorization.rego
{"addrs":[":8181"],"diagnostic-addrs":[],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2020-09-23T12:24:05-07:00"}
...
```

Then to test the policies:
```
$ curl -X POST http://localhost:8181/v1/data/playground/allow
{
  "code": "unauthorized",
  "message": "request rejected by administrative policy"
}
```

So far so good, the authz policy is hooked up...

```
$ export TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJpc3MiOiJodHRwczovL2lzc3Vlci5hdXRoMC5jb20vIn0.cJbA-zmt8RgOid5xyOp5Lhx-oeT7FZOyUh8Lik1-AQo
$ curl -X POST -H "Authorization: Bearer ${TOKEN}" http://localhost:8181/v1/data/playground/allow
{}
```

Success! The `input.identity` was populated, and our `system.authz.allow` was `true` (otherwise the request would have come back as "unauthorized").

But now the question is why wasn't the `data.playground.allow` true? Well, for that policy evaluation the input document was empty:

Starting OPA up with the decision logger:

```
$ opa run -s --authentication=token --authorization=basic --set decision_logs.console=true ./token.rego ./playground.rego ./authorization.rego
{"addrs":[":8181"],"diagnostic-addrs":[],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2020-09-23T12:51:10-07:00"}
{"level":"info","msg":"Starting decision logger.","plugin":"decision_logs","time":"2020-09-23T12:51:10-07:00"}
...
```

And sending the same request again:

```
$ curl -X POST -H "Authorization: Bearer ${TOKEN}" http://localhost:8181/v1/data/playground/allow
{"decision_id":"aa2e9fe4-a297-462b-8428-c634e8ff0765"}
```

We see from the decision log that there is no `input` document:

```
{
  "decision_id": "aa2e9fe4-a297-462b-8428-c634e8ff0765",
  "labels": {
    "id": "4b95e7d7-b588-402e-9325-44f986779b9f",
    "version": "0.22.0-dev"
  },
  "level": "info",
  "metrics": {
    "counter_server_query_cache_hit": 0,
    "timer_rego_input_parse_ns": 2827,
    "timer_rego_query_compile_ns": 50344,
    "timer_rego_query_eval_ns": 10067,
    "timer_rego_query_parse_ns": 8497,
    "timer_server_handler_ns": 110319
  },
  "msg": "Decision Log",
  "path": "playground/allow",
  "requested_by": "[::1]:64019",
  "time": "2020-09-23T12:51:53-07:00",
  "timestamp": "2020-09-23T19:51:53.004372Z",
  "type": "openpolicyagent.org/decision_logs"
}
```

Checking out the [REST API docs for `/v1/data`](https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-with-input) we can see that you need to provide input in the payload like:

```
{"input": ... }
```

So the new curl command looks something like:

```
$ curl -X POST -H "Authorization: Bearer ${TOKEN}" -d "{\"input\": {\"identity\": \"${TOKEN}\"}}" http://localhost:8181/v1/data/playground/allow
{"decision_id":"c6babc38-7a77-4419-a8b8-9361e0d0d990","result":true}
```
And now we are getting back `true`, and in the decision log we have our input defined:

```
{
  "decision_id": "c6babc38-7a77-4419-a8b8-9361e0d0d990",
  "input": {
    "identity": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJpc3MiOiJodHRwczovL2lzc3Vlci5hdXRoMC5jb20vIn0.cJbA-zmt8RgOid5xyOp5Lhx-oeT7FZOyUh8Lik1-AQo"
  },
  "labels": {
    "id": "4b95e7d7-b588-402e-9325-44f986779b9f",
    "version": "0.22.0-dev"
  },
  "level": "info",
  "metrics": {
    "counter_server_query_cache_hit": 1,
    "timer_rego_input_parse_ns": 21256,
    "timer_rego_query_eval_ns": 1119852,
    "timer_server_handler_ns": 1164713
  },
  "msg": "Decision Log",
  "path": "playground/allow",
  "requested_by": "[::1]:64074",
  "result": true,
  "time": "2020-09-23T12:58:07-07:00",
  "timestamp": "2020-09-23T19:58:07.034531Z",
  "type": "openpolicyagent.org/decision_logs"
}
```

I guess the main take-away here is that the OPA API auth evaluation is separate from the actual query evaluation, and the input documents are different for each (usually with different clients/use-cases).

**Comment by mneil** [comment]
Thanks for the detailed reply!

I get this and we're on the same page. My question is, why? Or better, how can we pass this token down (without requiring applications to send the token in 2 locations) and is this something OPA should do?

Could it be set in the `data` namespace instead of input in subsequent evaluations? I'm doing exactly what you describe now (setting it in the header and the body). But, it's not an ideal developer experience to have to place the token twice. Supporting moving or placing the token in the policy evaluation for users would be a nice feature (at least I think so :)).

**Comment by patrick-east** [comment]
> My question is, why?

There are a number of reasons, but I think for this type of use-case the main one is that typically they aren't the same tokens. The API authorization for OPA is intended to lock down service to service communication, so you'd have a token which has permissions to make requests to OPA configured for say your apps API server. This service token is _not_ the same one that an incoming request to your apps API server would provide as the `input` for a policy evaluation, that would be the like end-user or some other service.

Part of the confusion maybe is that OPA itself when evaluating those policies via like `/v1/data` is totally agnostic to authz or really even that it was evaluated via the REST API versus say `opa eval .. ` on the CLI or via the golang API. The REST API auth that OPA provides is a specific integration of OPA that leverages the policies loaded, but the evaluation it does it not the same as what the actual `/v1/data` one is doing, the auth one _is_ that use-case specific implementation.

**Comment by mneil** [comment]
Ah, if that's the typical use case then it make sense. We're really letting any signed token from our provider hit the OPA server to check policies. So for that case we pass the token through. It feels really awkward to pass the same token twice. But, now that I understand why it makes more sense. The reason is that it's more flexible and allows the common use case.

Thanks!
