### ISSUE TITLE
Restrict data output - Question

### ISSUE THREAD

**Issue by Jeyakumardevarajulu** [open-policy-agent/opa#2721]
When I execute below command and it returns complete data.json along with my result "true" or false" from rego policy. How to restrict it?

opa eval -i input.json -d testPolicy.rego -d data.json "data"

testpolicy.rego

is_user_owner_or_viewer = false {
true
}

**Comment by tsandall** [comment]
Don't query for "data". Just query for the value you're interested in: `data.<package>.<rule-name>`, e.g., `data.foo.bar.is_user_owner_or_viewer`.

**Comment by Jeyakumardevarajulu** [comment]
For Example
Below is the data.json and I want to validate where "Users" and "UserGroups" and in this case I need both data.users and as well as data.usergroups. how can I pass multiple packages as input?

opa eval -i input.json -d testPolicy.rego -d data.json "data"

{
    "users": {
        "jk@lti.com": {
            "email": "jk@lti.com",
            "userrole" : "viewers"
        }
    },
    "usergroups": {
        "jk@lti.com": {
            "groups": [
                {
                    "name": "admin",
                    "email": "owner@lti.com"
                },
                {
                    "name": "user,",
                    "email": "user@lti.com"
                },
                {
                    "name": "viewer",
                    "email": "view@lti.com"
                }
            ]
        }
    }
}

below is the rego validation

package rbac.authz
user_name := "jk@lti.com"

default validate_user = false

validate_user[input.usergroups[user_name].groups[k].email] {
# Check the basic user access
   roles := input.usergroups[user_name]
}

**Comment by tsandall** [comment]
@Jeyakumardevarajulu I don't understand your question. If you're asking how to supply multiple policy files you can either do so explicitly with -d (e.g,. `opa eval -d p1.rego -d p2.rego ...`) or you can pass entire directories (which will be loaded recursively!) If you structure your workspace to follow the [Bundle](https://www.openpolicyagent.org/docs/latest/management/#bundles) format, you can easily pass the entire workspace with `-b`.

As a side note, one thing I noticed is your policy refers to `input.usergroups`. Is that intentional? It should be `data.usergroups` from what I can gather from the rest of your comment.

**Comment by Jeyakumardevarajulu** [comment]
Below is my rego file

-------------------------------------------------------
package rbac.authz
user_name :="jk@lti.com"
Legal_tags[data.results[i].acl[input.users[user_name].userrole][j] ] {

data.results[i].acl[input.users[user_name].userrole][j] == input.usergroups[user_name].groups[k].email

}
---------------------------------------------------------
Below is my data.json
----------------------------------------------------------

{
    "results": [
        {
            "data": {
                "id": 123,
                "version": 12124124
            },
                "acl": {
                    "viewers": [
                        "view@lti.com"
                    ],
                    "owners": [
                        "owner@lti.com"
                    ]
                },
            "legal": {
                "legaltags": [
                    "eu"
                ],
                "otherRelevantDataCountries": [
                    "US"
                ],
                "status": "compliant"
            }
        },
        {
            "data": {
                "id": 123456,
                "version": 234255456
            },
                "acl": {
                    "viewers": [
                        "view@lti.com"
                    ],
                    "owners": [
                        "owner@lti.com"
                    ]
                },
            "legal": {
                "legaltags": [
                    "eu"
                ],
                "otherRelevantDataCountries": [
                    "US"
                ],
                "status": "compliant"
            }
        }
    ]
}
------------------------------------------------------------------------
Below is my user.json
-----------------------------------------------------------------------

{
    "users": {
        "jk@lti.com": {
            "email": "jk@lti.com",
            "userrole" : "viewers"
        }
    },
    "usergroups": {
        "jk@lti.com": {
            "groups": [
                {
                    "name": "admin",
                    "email": "owner@lti.com"
                },
                {
                    "name": "user,",
                    "email": "user@lti.com"
                },
                {
                    "name": "viewer",
                    "email": "view@lti.com"
                }
            ]
        }
    }
}
-------------------------------------------------------------------------------
Below is the command I am executing

opa eval -i input.json -d testPolicy_test.rego -d data.json "data"

I need to get only the below output

{
              "authz": {
                "Legal_tags": [
                  "view@lti.com"
                ],
                "user_name": "jk@lti.com"
              }
            }

but I am getting additional of complete data.json . I just want to get only the above results. Hope I am clear right?

**Comment by tsandall** [comment]
Query for `data.rbac` then instead of just `data`.

**Comment by Jeyakumardevarajulu** [comment]
This is what I was looking for. Thanks @tsandall
