### ISSUE TITLE
Accessing OPA metrics endpoint through diagnostic listener

### ISSUE THREAD

**Issue by shreyas-badiger** [open-policy-agent/opa#2728]
In my setup, OPA is hosted on a kubernetes pod.
I am trying to access the OPA **metrics** and **health** endpoints by port-fowarding
I followed this link, and created a diagnostic listener (on port 8282) as advised.
https://www.openpolicyagent.org/docs/latest/security/#secure-health-and-monitoring

## Expected Behavior
Expected to access the OPA metrics on 8282

## Actual Behavior
```
shreyas-badiger$ curl -k https://localhost:8282/metrics
{
  "code": "unauthorized",
  "message": "request rejected by administrative policy"
}
```
## Steps to Reproduce the Problem

- Run OPA pod with **--diagnostic-addr 8282**
- kubectl port-forward <opa_pod_name> 8282:8282
- curl -k https://localhost:8282/metrics

## Setup details:

* OPA version
0.23.2
* Example query, input, data, and policy that OPA was given
`curl -k https://localhost:8282/metrics`
* Example output that OPA returned
```
shreyas-badiger$ curl -k https://localhost:8282/metrics
{
  "code": "unauthorized",
  "message": "request rejected by administrative policy"
}
```
* For server and CLI, the flags/configuration that you provided to OPA
` Run OPA pod with --diagnostic-addr 8282`

**Comment by patrick-east** [comment]
That error message:
```
{
  "code": "unauthorized",
  "message": "request rejected by administrative policy"
}
```

Indicates that you have OPA running with an auth policy (https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization ) You would need to adjust the policy to allow access to the `/metrics` endpoint, or provide whatever credentials required.

If you can share the full CLI parameters for opa and your `system.authz` policy we can potentially give more specific instructions.

**Comment by shreyas-badiger** [comment]
@patrick-east Thanks!
We are using token based authentication. Here are the complete CLI parameters for OPA.
```
    Args:
      run
      --server
      --tls-cert-file=/certs/tls.crt
      --tls-private-key-file=/certs/tls.key
      --addr=0.0.0.0:443
      --insecure-addr=127.0.0.1:8181
      --diagnostic-addr=0.0.0.0:7676
      --log-level=info
      --authentication=token
      --authorization=basic
      --ignore=.*
      --set=decision_logs.console=true
      --set=status.console=true
```

We have enabled the /metrics in the authz.rego file as well.

  ```
 package system.authz

 import data.auth.tokens

 # Rights are described as Role with allowed Path and Verbs (similar to RBAC).
 # Path is an array of strings parsed from endpoint e.g., '/v1/data/example' equals ["v1", "data", "example"] or '*' for any.
 # Verbs are a set of {GET, POST, PUT, PATCH, DELETE} or '*' for any.
 # Current rights:
 #       "admin": Allows requests from any path and any verb, this right is meant to be kept for administration requests / debugging.
 #       "api-server": Used by api-server to call OPA via Validating/Mutating Webhooks. Allows on limited calls to /v1/data.
 #       "metrics": To access the metrics endpoints of OPA pods.
 rights = {
     "admin": {
         "path": "*",
         "verbs": "*",
     },
     "api-server": {
         "path": [""],
         "verbs": {"GET", "POST"},
     },
     "metrics": {
         "path": ["/metrics"],
         "verbs": {"GET", "POST"},
     },
 }
```

But, I assumed adding a diagnostic listener (with --diagnostic-addr option)to OPA doesn't need a token to access the health/monitoring data. Atleast that's what [this](https://www.openpolicyagent.org/docs/latest/security/#secure-health-and-monitoring) link says, correct?

**Comment by tsandall** [comment]
The `--diagnostic-addr` flag exists so that those APIs (/health, /metrics, etc.) can be served on a public interface (as opposed to just localhost). If you're running OPA with authorization enabled, you'll need to permit access to those endpoints. Something as simple as this will do it:

```
allow {
        input.path = ["metrics"]
}

allow {
        input.path = ["health"]
}
```

The docs do not say that authorization is disabled on the diagnostic listener so I'm going to close this.

**Comment by shreyas-badiger** [comment]
It worked! Thanks @tsandall
