### ISSUE TITLE
Custom Log Formats

### ISSUE THREAD

**Issue by eliw00d** [open-policy-agent/opa#2729]
We have very specific requirements around the shape of our logs in our system. With our Node.js services we use Winston and that allows us to create custom format functions to shape them. Would it be possible to add something like that to OPA? For example:

```json
{
  "client_addr": "[::1]:63902",
  "level": "info",
  "msg": "Sent response.",
  "req_id": 1,
  "req_method": "GET",
  "req_path": "/v1/data",
  "resp_body": "{\"decision_id\":\"f4b41501-2408-4a14-8269-1c1085abeda4\",\"result\":{}}",
  "resp_bytes": 66,
  "resp_duration": 2.545972,
  "resp_status": 200,
  "time": "2019-05-08T17:25:41-07:00"
}

```

would become something like:

```json
{
  "level": "info",
  "message": "Sent response.",
  "milliseconds": 1557361541000,
  "meta": {
    "client_addr": "[::1]:63902",
    "req_id": 1,
    "req_method": "GET",
    "req_path": "/v1/data",
    "resp_body": "{\"decision_id\":\"f4b41501-2408-4a14-8269-1c1085abeda4\",\"result\":{}}",
    "resp_bytes": 66,
    "resp_duration": 2.545972,
    "resp_status": 200
  }
}
```

**Comment by patrick-east** [comment]
Its a little hacky, but I think you might be able to do something like this by making a customize OPA binary (essentially the same idea as https://www.openpolicyagent.org/docs/latest/extensions/#custom-plugins-for-opa-runtime without the custom plugin) and by setting the global logrus formatter https://github.com/sirupsen/logrus#formatters either to a version that works for you, or implementing a custom one. The tricky part right now is that you have to change it _after_ you start the server (or it will be overridden when the server initializes).

It might be relatively easy to expose an API on the OPA `runtime` package to make this more official. I suspect that is the most simple way to provide this type of functionality.

For anyone with these types of requirements, in the short term, you may want to consider wrapping OPA with a script/tool that captures the stdout and stderr from OPA to transform it to the required structure. I think most of the more popular log collectors can handle doing some kind of transformation on the raw inputs.

**Comment by asleire** [comment]
Could this be solved by adding support for specifying a custom policy that takes the original log statement as input, and logs the decision? Similar to the mask functionality

We would also like this as we run in kubernetes and use a scraper to collect stdout logs which need to be converted to a specific format before being easily accessed in our log viewer

**Comment by anderseknert** [comment]
Heh, that'd be an interesting approach :) What kind of logs are you interested in? I think the common recommendation is to run with log level set to error in production, which should (hopefully!) be prettty quiet.

**Comment by asleire** [comment]
I was thinking about the decision logs, but also error logs of course. Preferably every log item would be formatted the same way

**Comment by anderseknert** [comment]
Oh! I'd suggest sending those to a remote rather than having hem printed to the console. The remote server would then be free to reformat them as required. I don't think we'll want to do that client side.

**Comment by asleire** [comment]
Sure, we could also write some custom logic in our log scraper or wrap the OPA process like patrick-east suggested above, but the very best solution for us would be to keep the logic as close to OPA as possible by keeping it in OPA itself 😄 

Of course if you think such a feature does not belong in OPA that's fair enough

**Comment by ashutosh-narkar** [comment]
Closing this for now. We can revisit if/when there is more interest for this feature. Also this can be implemented outside of OPA as an initial implementation.

**Comment by parshva-shah-dsw** [comment]
@eliw00d @patrick-east  @ashutosh-narkar  Do we have any integration using fluentd where we can transform OPA logs "msg" field to "message" while logging?

**Comment by anderseknert** [comment]
You could look at something like https://www.benthos.dev/ I guess?
it provides support for a whole bunch of inputs and outputs, with transformations in between.
