### ISSUE TITLE
Provide description on docker tags in the docker hub overview page

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#2730]
I've received a few questions lately on what the difference between the available docker tags is. While there is a [short section](https://www.openpolicyagent.org/docs/latest/deployments/#tagging) in the OPA docs on this, it seems people unfamiliar with these or OPA go to docker hub to check. This makes sense, since it's probably the first place to look if stumbling upon an unknown image in a kubernetes resource or elsewhere. Currently they'll find the overview page empty. Providing some basic information on OPA (with links pointing to the docs for further reading) along with information on the available tags, like `-rootless` and `-debug`, would help here. And given that page currently says OPA has 10+ million pulls, it seems like a great opportunity to help promote OPA for people curious about it. 

The [nginx overview page](https://hub.docker.com/_/nginx) is a pretty good example here IMO. Unfortunately it doesn't look like there's a way to push this information programmatically (I'd love to be wrong on that though) or we could have pushed something as part of the CI build.

**Comment by patrick-east** [comment]
Quick look at the source for https://github.com/peter-evans/dockerhub-description I see them using this API: https://github.com/peter-evans/dockerhub-description/blob/17abc79f553e83016eeb703a35345313cf4b07fc/src/dockerhub-helper.ts#L36

I can't find any docs for it though 😆  so I'm guessing it may not be an officially supported API

**Comment by anderseknert** [comment]
Oh, I hadn't seen that! Looks useful for personal stuff, but..

> Docker Hub Personal Access Tokens cannot be used as they are not supported by the API. [...] Unfortunately, this means that enabling 2FA on Docker Hub will prevent the action from working.

Ouch! Looks like it's doing a regular [login](https://github.com/peter-evans/dockerhub-description/blob/17abc79f553e83016eeb703a35345313cf4b07fc/src/dockerhub-helper.ts#L14) and then using the session token for the next request! 😄

**Comment by tsandall** [comment]
I've added a description of the different variants to the repo README. It's a bit brittle but I think it will do for now. If we enabled automated builds on the repo DockerHub will pickup the README content but that would be a problem since we already build and push through GitHub actions. I'm tempted to close this for now unless someone wants to look into the automated build hack.

**Comment by anderseknert** [comment]
Just read the description there - looks great! Only thing missing I'd probably add is a link to the OPA main page or docs for further reading. With all the information there I think we can close the issue and re-open another one for automating publishing if desired later - as long as there's no mentions of versions or other things that are likely to change over time I don't think we really need to.

**Comment by tsandall** [comment]
There are no mentions of specific versions so I think it's fine for now. Closing.
