### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2732]
1.For bundle deploy mode(https://www.openpolicyagent.org/docs/latest/external-data/#option-3-bundle-api),if a policy is updated, will all policies be pulled again? and will the API not respond when the policy is updated?
2.How to optimize the performance of decision API? 
3.How to turn on multi-core mode for OPA?

**Comment by tsandall** [comment]
> 1.For bundle deploy mode(https://www.openpolicyagent.org/docs/latest/external-data/#option-3-bundle-api),if a policy is updated, will all policies be pulled again?

Yes. Bundles contain an entire snapshot of the policy (.rego) and data.json files to load into the OPA.

>  and will the API not respond when the policy is updated?

The /v1/data API will always serve responses. If no bundle has downloaded, the decision will simply be undefined. If you want to block startup you can do so using readiness checks (see the Health API in the docs).

> 2.How to optimize the performance of decision API?

See the Policy Performance page: https://www.openpolicyagent.org/docs/latest/policy-performance/

> 3.How to turn on multi-core mode for OPA?

OPA will utilize all available cores by default. See the Resource Utilization section in the link above for details.
