### ISSUE TITLE
Custom response object  is  not available when policy evaluates to  true

### ISSUE THREAD

**Issue by hepmkj** [open-policy-agent/opa#2735]
Hello, 
   I am trying to pass custom  response object (to the caller of  service ) using  opa-envoy  authorization filter. I followed the instructions as mentioned on the following urls

For using  opa  with envoy proxy:
https://www.openpolicyagent.org/docs/latest/envoy-authorization/

Policy  with object response:
https://github.com/open-policy-agent/opa-envoy-plugin#example-policy-with-object-response

When the OPA  policy  evaluates to  false,  the caller of the service gets the custom response (basically  header part  "x-ext-auth-allow:no"). Please see below

"""
[cloud_user@4f3873276c1c Envoy]$ curl -i -H 'Authorization: Bearer "${BOB_TOKEN}" ' -d '{"firstname":"Bob", "lastname":"Rego"}' -H "Content-Type: application/json" -X POST  http://172.17.0.3:30891/people
HTTP/1.1 301 Moved Permanently
content-length: 20
content-type: text/plain
x-ext-auth-allow: no
date: Mon, 28 Sep 2020 17:51:14 GMT
server: envoy

Unauthorized Request
"""

But,  when policy evaluates to  true.  I  am  not getting any header  attribute  in the response.  
^^^
curl -i -H "Authorization: Bearer "${BOB_TOKEN}" http://172.17.0.3:30891/people
HTTP/1.1 200 OK
content-type: application/json
date: Mon, 28 Sep 2020 17:54:37 GMT
content-length: 96
x-envoy-upstream-service-time: 0
server: envoy

[{"id":"1","firstname":"John","lastname":"Doe"},{"id":"2","firstname":"Jane","lastname":"Doe"}]

^^^
In the above  response, there is no header attribute.  How  to get the header attribute  when the policy  evaluates  to true ?

Thanks.

"""  

   

_Originally posted by @ashutosh-narkar in https://github.com/open-policy-agent/opa/issues/2472#issuecomment-644880415_

**Comment by srenatus** [comment]
> But, when policy evaluates to true. I am not getting any header attribute in the response.

When the policy evaluates to true, those headers are forwarded to the service; so you should see them *there*.

I didn't think the intention of the Envoy feature is to send the headers _back to the client_... I could be wrong. 🤔

**Comment by patrick-east** [comment]
> I didn't think the intention of the Envoy feature is to send the headers back to the client

+1

The reason you aren't seeing the header it is in the forwarded request from envoy to the demo app. You are seeing the response from the demo app, which would not include the header.

Quick diagram to maybe help explain:
Not-allowed case:
```
                 original
 +-----------+   request    +-------------+
 |           |              |             |
 |  curl     +------------->+    Envoy    |
 |           |              |             |
 |           +<-------------|             |
 +-----------+ envoy deny    -------------+
               w/ header        |    ^
                                |    |
                                |    | ext authz response w/ header (1)
                                v    |
                            +-------------+
                            |             |
                            |   OPA       |
                            |             |
                            |             |
                            |             |
                            +-------------+
```
Allowed case:
```
                 original                     enriched request
 +-----------+   request    +-------------+   w/ new header   +---------------+
 |           |              |             |                   |               |
 |  curl     +------------->+    Envoy    +------------------>+ App Service   |
 |           |              |             |                   |               |
 |           +<-------------|             +<------------------+               |
 +-----------+ app response  ---+----+----+   app response    +---------------+
                                |    ^
                                |    |
                                |    | ext authz response w/ header (2)
                                v    |
                            +---+----+----+
                            |             |
                            |   OPA       |
                            |             |
                            |             |
                            |             |
                            +-------------+

```

1) https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#service-auth-v3-deniedhttpresponse
2) https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#service-auth-v3-okhttpresponse

If you wanted the header to be on the app response you need to have the app service explicitly set the header on the response. The demo app for the docs/tutorial does not, you can modify it to echo the headers back and you should see them, source for it is here: https://github.com/ashutosh-narkar/go-test-server

**Comment by hepmkj** [comment]
Thanks for your  reply.  When OPA  policy evaluates to false (not allowed case),  the header is available in response (as expected).  

I am talking of the case when OPA policy  evaluates to  true (allowed case). Here, the header information  is not available in the request coming from envoy   and reaching app service.  In the above figure (allowed case), this request is being represented as "enriched request w /new header".  I tried to  print out the header  attributes (from app) available in the request coming from envoy.  My  app is a simple spring boot which can be found on following link
https://github.com/hepmkj/Work/tree/master/docker-spring-boot

Deployment file for app  using Envoy  and OPA can be found in the folder 
https://github.com/hepmkj/Work/tree/master/Istio/OPA/Envoy

Deployment file:
https://github.com/hepmkj/Work/blob/master/Istio/OPA/Envoy/deploy_opa.sh

Header  attributes can be seen in  the app log file by hitting the endpoint:
curl -i -X GET http://${SERVICE_URL}/test

**Comment by patrick-east** [comment]
Can you verify that the app is logging the headers correctly? I am not seeing the expected behavior with only the API service:

I start up the app:
```shell
$ docker run --rm -it -p 8080:8080 hepmkj1/java:spring-boot
Unable to find image 'hepmkj1/java:spring-boot' locally
spring-boot: Pulling from hepmkj1/java
df20fa9351a1: Already exists
ffa7158a1780: Pull complete
dce2455ca101: Pull complete
27f238637bd6: Pull complete
1798b6357d70: Pull complete
Digest: sha256:e73edf86f8a123cdc4a822c8783415bc4b6a27b70782d3d72ab5ce07632fab2e
Status: Downloaded newer image for hepmkj1/java:spring-boot

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.4.RELEASE)

2020-09-29 21:42:58.345  INFO 1 --- [           main] com.manoj.StartApplication               : Starting StartApplication v1.0 on 81a94256ae52 with PID 1 (/opt/app/app.jar started by root in /opt/app)
2020-09-29 21:42:58.349  INFO 1 --- [           main] com.manoj.StartApplication               : No active profile set, falling back to default profiles: default
2020-09-29 21:42:59.166  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2020-09-29 21:42:59.179  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-09-29 21:42:59.179  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2020-09-29 21:42:59.237  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-09-29 21:42:59.237  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 791 ms
2020-09-29 21:42:59.386  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-09-29 21:42:59.542  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2020-09-29 21:42:59.546  INFO 1 --- [           main] com.manoj.StartApplication               : Started StartApplication in 1.657 seconds (JVM running for 2.036)
2020-09-29 21:43:08.567  INFO 1 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-09-29 21:43:08.568  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-09-29 21:43:08.575  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
```

And curl with a custom header:

```shell
$ curl -i -X GET -H "x-ext-auth-allow: yes" localhost:8080/test
HTTP/1.1 200
Content-Type: text/plain;charset=UTF-8
Content-Length: 14
Date: Tue, 29 Sep 2020 21:48:26 GMT

testing: /test
```

The log shows:

```
2020-09-29 21:48:26.598  INFO 1 --- [nio-8080-exec-7] com.manoj.LoggerInterceptor              : url: http://localhost:8080/test, uri: /test, verb: GET, token: null, remoteUser: null, remoteAddr: 172.17.0.1, responseTime: 1 ms, responseStatus: 200, executionHost: 81a94256ae52, parameters from headers: ?&_psip=172.17.0.1
```

**Comment by ashutosh-narkar** [comment]
In the allowed use-case, OPA returns an object with the `headers` key which has the custom headers. I updated the [test app](https://github.com/ashutosh-narkar/go-test-server) to print all the headers. The policy is as below:

```rego
allow = response {
   response := {
       "allowed": true,
       "headers": {"x-ext-auth-allow": "yes"}
    }
}
```

I can verify that the test app receives the custom headers which means that Envoy is forwarding the headers upstream. Below is a log from the test app:
```bash
Header Key: X-Ext-Auth-Allow, Header Value: yes
```

As @patrick-east mentioned, can you check the code that logs the headers ?

**Comment by hepmkj** [comment]
@patrick-east   Nice catch.  Closing the  ticket.
