### ISSUE TITLE
Question: How to check existence of "key" and the value of a "sub-key" existing in the set of "key"

### ISSUE THREAD

**Issue by NeonOriginal** [open-policy-agent/opa#2736]
I am trying to write a policy for my kubernetes cluster using gatekeeper. This policy is to check if a Service is being created of type LoadBalancer, with Port 80 being exposed and an annotation hasn't been set.

I have been using the Rego playground and haven't been able to make this work at all.

I have written this policy:
`package kubernetes.admission

violation[msg] {
  input.review.kind.kind == "Service"
  input.review.object.spec.ports[_].port == 80
  input.review.object.spec.type == "LoadBalancer"
  object.get(input.review.object.metadata.annotations, "service.beta.kubernetes.io/load-balancer-internal", "false") != "true"
  msg := "port 80 is not allowed on public loadbalancer services, set 'service.beta.kubernetes.io/load-balancer-internal' to 'true'"
}`

I am providing this as input:
`{
  "kind": "AdmissionReview",
  "review": {
    "kind": {"kind":"Service"},
    "object": {"metadata": {"annotations": {"service.beta.kubernetes.io/load-balancer-internal": "true"}},"kind":"Service","spec": {"ports": [{"port": 8080,"protocol": "tcp"},{"port": 80, "protocol": "tcp"}], "type": "LoadBalancer"}}
  }
}`

## Expected Behavior
The expected behavior is that it would deny the creation of an object if it was a Kubernetes Service and it's type was LoadBalancer, and port 80 was defined, and it did not have the annotation "load-balancer-internal" set to true. It would also deny if the field annotations doesn't exist under the metadata field.

## Actual Behavior
However the problem arises when the object trying to be validated does not have the key "annotations" under "metadata". So even though that specific load-balancer annotation doesn't exist, it still passes the check.

## Steps to Reproduce the Problem
Remove the "annotations" field entirely or edit it to not specifically say "annotations" and this passes. Input like this, will pass even though the specific annotation doesn't exist:
`{
  "kind": "AdmissionReview",
  "review": {
    "kind": {"kind":"Service"},
    "object": {"metadata": {},"kind":"Service","spec": {"ports": [{"port": 8080,"protocol": "tcp"},{"port": 80, "protocol": "tcp"}], "type": "LoadBalancer"}}
  }
}`

I have tried doing a check like this before checking if the load-balancer annotation is set 
`# check if key "foo" exists and is not false
obj.foo` this is described in the Policy language page and that works if I remove the checking for the specific annotation. 

If I check for both the existence of the annotations field and the value of a specific annotation then it again starts to pass no matter what I do.

How do I get Rego to deny the input if the annotations field doesn't exist but if it does only deny if the value of a specific annotation isn't correct. I cannot seem to get both to work, only one or the other

**Comment by ashutosh-narkar** [comment]
@NeonOriginal does this example satisfy the use-case https://play.openpolicyagent.org/p/Yn7spcm6Jt ?

More info on checking a key in an object -> https://www.openpolicyagent.org/docs/latest/policy-reference/#objects

**Comment by NeonOriginal** [comment]
Thank you Ashutosh for helping! And I appreciate the work on the example. 

The issue I am facing is that when the whole annotation field doesn't exist the code doesn't seem to work. And when I add in code for checking if that field exists. It never for any reason denies in what I think should be proper case of the annotations field not existing.

I have added a new test case to the work you did and what looks like should be the correct code from what I saw in the language guide to check for the existence of the annotations field, but it never triggers properly to detect the field is missing.

https://play.openpolicyagent.org/p/UZBdNZbqwR

I am definitely missing something in how Rego works and didn't find it in the documents. But it doesn't like me testing for the existence of annotations field and then acting like it exists in the next line. It results in no test case failing. Because in some cases in my environment the annotations field might not be set and that should also raise a violation just like if it is present but the annotation "load-balancer-internal" is or isn't present with the wrong value.

**Comment by NeonOriginal** [comment]
So really looking at your code @ashutosh-narkar I see that you can indeed have two methods with the same name, I didn't know that. So I tried it with one looking specifically at the annotation's value and then another one with the same name that looks specifically for the existence of that annotations field.

So although I really don't get why it doesn't work with checking for the existence of the annotations field and then checking for a value of a specific subfield in the annotations field right after and splitting it up into two methods named the exact same works I won't argue with it.

Thank you so much for your help @ashutosh-narkar , without you doing that work I wouldn't have been able to figure out how to solve this!
