### ISSUE TITLE
Date Validation in REGO - Question

### ISSUE THREAD

**Issue by Jeyakumardevarajulu** [open-policy-agent/opa#2737]
Hi Team,

       I want to compare 2 date values and when I checked Policy reference document, I don't see any date comparison and below is what I have done to get the date from nanosecond time. Do we have any comparison operator for date or any other way to compare date?

Datetime_parser[start]
{
    start := time.date(time.now_ns())
    # t := date.now(ns)
    # expirationDate = to_date("2045-01-01")
    # elapsed := expirationDate - start
}

**Comment by ashutosh-narkar** [comment]
Here's an example https://play.openpolicyagent.org/p/0vd9yrcOnQ.

**Comment by tsandall** [comment]
The link @ashutosh-narkar posted answers the question; convert the timestamp/date string into a number representing nanoseconds since epoch and then just use normal comparison operators.
