### ISSUE TITLE
Import modules into different packages

### ISSUE THREAD

**Issue by Smith-Anthony-CH** [open-policy-agent/opa#2743]
Allow imports of modules into existing packages.

## Expected Behavior

If I have two existing packages that contain rules for a tool we use at say:
```
package common.sonarqube

violation[msg] {
    to_number(input.coverage) >= 80
    msg := "Sonarqube: Coverage should be below 80%"
}
```
```
package common.veracode

violation[msg] {
    to_number(input.vulerabilities.high) < 1
    msg := "Veracode: Vulnerabilities are higher than 1"
}
```

and want to create a superset of rules at a higher level 

```
package composition
import common.veracode
import common.sonarqube
```

## Actual Behavior

From reading documentation I don't think it can currently be done, If I'm wrong and can be pointed in the right direction that would be awesome!

**Comment by Smith-Anthony-CH** [comment]
Actually that last example you posted I was able to get working in my use case! Thanks a bunch that's awesome, now we can decompose our policies into modules and import them where needed.

**Comment by shagil-meesho** [comment]
@patrick-east could you kindly explain how is the following use case of importing the policies from one rego file to another working? It's not working for me.

Here's the StackOverflow answer (I'm not sure why it's marked as "✅".

https://stackoverflow.com/questions/73646952/how-to-import-different-policies-inside-opa-rego-policy

Looking forward to your guidance.

**Comment by anderseknert** [comment]
Hi @shagil-meesho 👋 Can you expand on how you are loading your policies into OPA, and what issues you are seeing?

**Comment by shagil-meesho** [comment]
Hi @anderseknert Thanks for acknowledging !

In the above StackOverflow answer, the person uses something like this:
-----------------------------------------
filenameA.rego

package com.example.A
import rego.v1

default allow:=false

allow if { input.message=="admin" }
-----------------------------------------
filenameB.rego

package com.example.B
import com.example.A.allow

default deny:=true

deny if {allow==false}
------------------------------------------


But I think rego doesn't support the above way of importing.
We can however mimic that using the same package name across filenameA.rego and filenameB.rego.

I just wanted to confirm if the above StackOverflow answer is right or wrong/outdated.

**Comment by shagil-meesho** [comment]
Ohh got it!
Thanks @anderseknert !
