### ISSUE TITLE
Mask data in decision log, but not /v1/data response.

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2752]
## Expected Behavior

When input/result is masked, e.g. `mask["/result/something_sensitive"]`, it should be removed from the decision logs, but not from the `/v1/data` API response (optionally?).  Decision logs tend to be shipped centrally, and sensitive data should be removed from those, but the `/v1/data` API response should still contain that data so that calling apps can use it as needed.

## Actual Behavior

When `mask` is used, it impacts both the decision logs and the `/v1/data` API response.

## Steps to Reproduce the Problem

OPA version: 0.24.0-dev

**Comment by tsandall** [comment]
This sounds like a bug. The result sent to the caller should not be mutated by the decision log mask--the decision logger will need to make a deep copy of the result before applying the mask (if the mask doesn't refer to the result, we can avoid the copy for performance.)
