### ISSUE TITLE
Custom credentials for rest client used by opa management services

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2758]
We've implemented the Status/Decision Log APIs in our stack without authentication and it works great, but now we need to integrate the APIs with a bespoke authentication system. This means we need to implement this bespoke authentication protocol in the rest client used by opa.  I'm not immediately seeing a way to extend the [rest Credentials](https://github.com/open-policy-agent/opa/blob/master/plugins/rest/rest.go#L43), is there a way to do this gracefully (without forking opa)?

One alternative I see for us is to use the bearer token credentials with a token file path. To do this, we'd have to implement some sort of plugin to grab the token and drop it on the file system, and refresh as needed.  However, we'd like to avoid having to put the token in plaintext on the file system if possible, hence our desire to create a custom Credentials implementation.

Thoughts/suggestions?  Thanks!

**Comment by anderseknert** [comment]
Rather than having OPA support your bespoke authentication scheme (through a custom plugin or a fork), does this not sound like a good case for a proxy? That way you could translate whatever auth scheme is made available in OPA to the requirements of your backend. 

As for how/where to store the credentials, what would you suggest as the preferred alternative?

**Comment by gshively11** [comment]
A proxy is certainly feasible, but I see a few issues with that approach:

- It's another running process we need to secure/patch/monitor
- It adds an additional point of failure
- It adds another hop between opa and our APIs

Our custom authn flow involves calling one of our APIs with AWS credentials and getting a token back, caching it, and then using that token for subsequent calls. We'll be providing the AWS credentials through environment or the metadata service. It seems reasonable to have the rest client support registering a custom authn plugin.  It looks like it would require some refactoring...the [auth interface](https://github.com/open-policy-agent/opa/blob/master/plugins/rest/rest.go#L30) is already exported, and there's [reflection](https://github.com/open-policy-agent/opa/blob/master/plugins/rest/rest.go#L55) to load the plugins, but the registration piece is missing (similar to how custom built ins are registered?).  I'm still super new to golang and opa, so I'm just guessing on this stuff right now.  If y'all are open to this idea, I'm happy to start experimenting with how it could be accomplished.

**Comment by patrick-east** [comment]
IIRC the intention of using more of a plugin style interface for these was to allow for this kind of thing. What we would probably want to do is support something like:

```
services:
  foo:
    url: ...
    auth:
      plugin: myCustomAuthPlugin

plugins:
  myCustomAuthPlugin:
    ... 
```

We use a similar pattern for custom decision logger plugins.

The tricky part is the plumbing changes to give the rest clients the pointer to the auth plugin instance (and/or plugin manager so they can look it up). Would need to dig through the code more to see how much we would have to adjust.
