### ISSUE TITLE
OPA should expose version information via the REST API

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#277]
It would be nice if OPA's version information could be retrieved through the API.

With the new /data/system namespace we could put it under /data/system/version for instance.

If we do this we should fix the version information shown in the REPL to go under /data/system/version as well.

**Comment by repenno** [comment]
Hi,

returning the version information for a GET request to /data/system/version is straightforward even if there is nothing really inmem under data.system.  All we need is a new route. 

But if we want to actually have the version under data.system, we need to insert this information when the system starts. Basically we need to create a new document during initialization. Maybe something inside opa/cmd/run.go inside init() function? Is there a place where the system itself we can create documents before repl is up?

**Comment by kichristensen** [comment]
Isn't this closed by #986?

**Comment by tsandall** [comment]
Fixed by #986
