### ISSUE TITLE
Result masking behavior changes based on path in /v1/data request

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2776]
## Expected Behavior

If I have decision logs enabled and I define the following mask rules

```
mask["/result/a/b/c/foo"]
mask["/result/a/b/c/bar"]
```
and I have the following data
```
{
  "a": {
    "b": {
      "c": {
        "foo": "something sensitive",
        "bar": "something sensitive",
        "ok": "other data"
      }
   }
}
```
and I make a request to `/v1/data/a/b/c`, I expect to NOT see `foo` and `bar` in the decision logs.

## Actual Behavior

`foo` and `bar` do appear in the decision logs.  However, if I make a request to `/v1/data`, they are properly masked/deleted.

## Steps to Reproduce the Problem

* OPA version 0.24.0-dev

**Comment by patrick-east** [comment]
I believe this is working as expected. The mask paths are expected to be relative to the result object, not the overall data document.

If you wanted to allow for both queries and mask the results you would need to have the mask policy setup to mask both locations. The mask rules can be generated with partial rules so if you did have a use-case for covering optional paths to some key, or just a key name in general, you can do that inside a

```
mast[path] {
    ...
}
```
rule with whatever logic you need to generate the `path`(s)

Generally speaking most use-cases with OPA lock the requests down to a single path (typically the default query) which limits the structure of the result making these easier to mask. I wouldn't really recommended allowing clients to query arbitrary paths of the OPA API.
