### ISSUE TITLE
Envoy Plugin: Migrate to xDS ext_auth v3

### ISSUE THREAD

**Issue by bcelenza** [open-policy-agent/opa#2798]
([Plugin repository](https://github.com/open-policy-agent/opa-envoy-plugin) does not allow issue creation at this time, so creating it here)

Envoy is close to officially deprecating the v2 API and moving to v3 (end of December 2020). However, the Envoy plugin is currently [tied to v2](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/internal/internal.go#L24). Envoy allows choosing which transport to use ([API docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthz)), and the default if not specified is currently still v2 ([docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto#enum-config-core-v3-apiversion)).

We should update the plugin to use v3 APIs for forward compatibility. The translation from v2 to v3 itself is straight forward (most if not all fields translate directly from v2), the bigger question is how best to handle to migration of the plugin itself.

A few options:
1. Supporting both v2 and v3 are possible through a configuration parameter in the OPA plugin that allows an operator to choose which API to use. The existing plugin can have v2 and v3 variants aligned along import path. This comes with additional code and testing complexity since we'd need to support both versions in the same base, but it's manageable. This is the approach the [go control plane](https://github.com/envoyproxy/go-control-plane) takes.
2. Fork the entire plugin to a v3 version, allowing the old version to be maintained and eventually phased out in favor of v3. We could have images for both, but there's overhead in the management of multiple, largely duplicative code bases.
3. Wholesale cut-over -- I wouldn't recommend this since v2 is still the default, and it would likely break someone.

My initial take is (1) is the best approach from an overall code and plugin maintenance perspective, but would love some input from maintainers/contributors since I'm new here. Have we handled a similar situation with other plugins?

**Comment by ashutosh-narkar** [comment]
Thanks for filing this issue @bcelenza. We are currently in the process of migrating from the v2 API to the v3 API via [this](https://github.com/open-policy-agent/opa-envoy-plugin/pull/202) PR. One of the features of the new V3 API is that it supports sending the request body as raw bytes to the external authorization server which would be a good addition for the plugin. I did not find much of a difference between the v2 and v3 API for the components that the plugin utilizes. I don't think we should support 2 different versions of the API given the older API will be deprecated soon and also it's a management overhead. Even after incorporating the V3 API the plugin itself would still be backward compatible so I'm not too worried about breaking anyone. Please let us know if any questions/concerns.

**Comment by bcelenza** [comment]
Hey @ashutosh-narkar, thanks for bringing that PR to my attention. 

I think my only real concern with dropping v2 support entirely is around vulnerability discovery in an old version that supports v2 that’s being run by a significant number of users. If we have the ability to patch an old version after such a discovery is made, then its probably fine to move to v3 wholesale going forward.

Given Envoys upcoming xDS versioning scheme, I do wonder if we’ll end up in a situation where multiple versions have to be supported anyway, but v2 to v3 could make sense as a wholesale change since it’s moving to the new scheme.

Thanks!
