### ISSUE TITLE
Unable to import custom-functions in other rego file

### ISSUE THREAD

**Issue by MahikanthNag** [open-policy-agent/opa#2811]
Reference issue https://github.com/open-policy-agent/opa/issues/1316

## Expected Behavior
common_functions.rego:

```
package top.level

my_function(x) {
    x = "foo"
}
```

policy_A.rego:

```
package top.level.rules.A

import my_function (Or common_functions.rego?)

my_result {
  my_function("value")
}
```

I used the same sample code @tsandall provided but still unable to import a custom function.. : 
`rego_type_error: undefined function data.top.level.identity`

I have spent a lot of time but couldn't understand where I am going wrong..
Does project structure effect the behavior in any way?

**Comment by tsandall** [comment]
@MahikanthNag you're receiving that error because you're only loading `policy_A.rego` into OPA. Either specify both files or specify the directory that contains them.

**Comment by MahikanthNag** [comment]
Thanks a lot! It worked now

**Comment by tsandall** [comment]
👍 I'm glad it's working!

**Comment by ParasharaRamesh** [comment]
I am still facing a similar issue:

file1.rego

package blah.something

func(x){
x="foo"
}

file2.rego

import data.blah.something.func
 ..
.


getting an error message saying undefined function.

**Comment by sharmilamuthukrishnan** [comment]
@MahikanthNag, I am new to Rego and I am also facing the same error. Can you please explain the solution in detail with example possible?

**Comment by MahikanthNag** [comment]
Hi @sharmilamuthukrishnan 
So basically import is kind of a dependency. So we have to load this dependency file to opa server before we load the actual rego file in which this dependency is used.

I am pretty sure you load a rego file to opa server for querying sonething using opa query api. Just load the dependency file first.

**Comment by sharmilamuthukrishnan** [comment]
Thanks @MahikanthNag
I got it.its working now.
But I have another problem, how I can execute the unit test cases in Visual Studio Code. I am getting rego_type_error: undefined function. I understood the problem that OPA agent in VScode does not aware of the custom function, but how can I make the OPA agent in VS Code to understand that?

**Comment by sadams-evi** [comment]
yes I also need help on this .. any suggestions

**Comment by anderseknert** [comment]
@sadams-evi I'd be happy to provide suggestions if you can provide an example of what you are trying to do.
