### ISSUE TITLE
Side Effects from with statement in rego tests

### ISSUE THREAD

**Issue by cwlowder** [open-policy-agent/opa#2813]
## Expected Behavior
Please look at this first: https://play.openpolicyagent.org/p/q586MYokKP. Here is the test that is failing unexpectedly:
```
test_allow {
	test_input := {
    	"type": "farmer",
    	"resource": resource,
    }
    
    # The king should always be allowed gold!
    allow with input as test_input with input.type as "king"
    
    # Farmers should only be allowed gold if they have stuff to sell
    not allow with input as test_input with input.has_stuff_to_sell as false
}
```
## Actual Behavior
When I run this test, I expect that using `with input.type as "king"` will only change `input` and not `test_input`. However, there is a side effect here and rego will also change the contents of test_input.
## Steps to Reproduce the Problem
This seems to affect both the Rego playground and the version of OPA cli I use `0.24.0`

## Additional Info
The OPA documentation doesn't seem to make this behavior clear https://www.openpolicyagent.org/docs/latest/policy-language/#with-keyword at least to me.

**Comment by tsandall** [comment]
@cwlowder Thanks for filing this! Looks like a bug.
