### ISSUE TITLE
Access JSON fields using JSON path based on conditions

### ISSUE THREAD

**Issue by MahikanthNag** [open-policy-agent/opa#2816]
Are we having support to access JSON objects using JSON paths like the following:
"$.key1.key2[?(@.key3=='val3')].key4"

Is there any reason why OPA doesnt support standard representation of json paths like the ones shown here?? : https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html
## Expected Behavior
example JSON : 
`path := "$.key1.key2[?(@.key3=='val3')].key4"`
`js := {"key1" : {"key2": [{"key3": "val3", "key4": "val4"}, {"key3": "xyz", "key4": "abc"}]}}`

`value := json.find(js, path) // returns "val3"`

**Comment by patrick-east** [comment]
For OPA you would do this with conditions in a rule, for example 
```rego
js := {"key1" : {"key2": [{"key3": "val3", "key4": "val4"}, {"key3": "xyz", "key4": "abc"}]}}

value = x {
	js.key1.key2[i].key3 == "val3"
	x = js.key1.key2[i].key4
}
```
https://play.openpolicyagent.org/p/SDOirtHR9Q

You are checking the condition and finding a variable `i` which makes that path assertion true for the `key3 = val3` condition, and then you want the value of key4 for the same index.

**Comment by patrick-east** [comment]
I guess to elaborate a bit on jsonpath vs rego. The intention of jsonpath is to provide a URL friendly single line query string, Rego is not as compact (as that wasn't really a design priority). Instead it favors being more flexible. You can make considerably more powerful queries/assertions over json structures with rego rules (IMO) than you can with jsonpath.

**Comment by MahikanthNag** [comment]
That surely is a nice unique way of finding out! Thanks a lot!
But i have a small concern here..
I need to use these for different json paths.. so trying to figure out a common way to write a function and pass in necessary arguments to it that returns the desired output.

**Comment by patrick-east** [comment]
Can you elaborate more on the use-case? We might be able to help give some direction on how to help avoid requiring that type of function.

**Comment by MahikanthNag** [comment]
Sure! Thanks for your time!

We have few JSON files in a git repo, and we want to enforce rules on those files that certain JSON paths in it are NOT allowed to change in any PR made on that repo. 
And if the data in any of those JSON paths are changed, we should return false form the policy rule and we fail the PR. So the policy takes, filename, master file content and PR file content as inputs... We want to check all change-denied json_paths (basically a list) in both master and pr contents and to see if there is data change in any of them.

**Comment by patrick-east** [comment]
Other folks might have ideas, but typically each of those paths that are being checked, especially if they are conditional like the original example, would be rules. So like the list of those change-denied json_paths would be a bunch of rules in your rego files.

**Comment by MahikanthNag** [comment]
Got. it.. will try to incorporate the approach you suggested for now. Thanks a lot!

@patrick-east  I have another question.. slightly off topic to the current one.. Please let me know if I need to create other issue for this.. Sorry if this is not the right place to ask this question!

I am having hard time finding a way to convert list of any type of elements to list of strings

Ex : 
Input : list = [1, True, "hi"]
Output : ["1", "True", "hi"]

**Comment by patrick-east** [comment]
You can use the `sprintf` builtin with the `%v` template (it uses the golang fmt syntax https://golang.org/pkg/fmt/ ) and if you have a list of them I would use a comprehension https://www.openpolicyagent.org/docs/latest/policy-language/#comprehensions , so for example check out https://play.openpolicyagent.org/p/mDIA68ITT1

**Comment by anderseknert** [comment]
Closing as questions have been answered. Will re-open on request in case I missed something.
