### ISSUE TITLE
opa fmt -w some_test.rego generates invalid json

### ISSUE THREAD

**Issue by kirk-patton** [open-policy-agent/opa#2817]
```opa fmt -w some_test```

 formats the file, but adds ",",s creating invalid json.

Before (valid json block)
========================================================
test_deployment_admission_has_cpu_limit {
        testInput := {
                "kind": "AdmissionReview",
                "apiVersion": "admission.k8s.io/v1beta1",
                "request": {
                        "namespace": "our-namespace",
                        "kind": {
                                "group": "extensions",
                                "version": "v1beta1",
                                "kind": "Deployment"    <==== no comma
                        },
                        "operation": "CREATE",
                        "object": {
                                "apiVersion": "extensions/v1beta1",
                                "kind": "Deployment",
                                "metadata": {
                                        "name": "policy-test",
                                        "namespace": "our-namespace"
                                },
                                "spec": {
                                        "template": {
                                                "spec": {
                                                        "containers": [{
                                                                "name": "test",
                                                                "resources": {
                                                                        "limits": {
                                                                                "cpu": "1m"
                                                                        }
                                                                }
                                                        }]
                                                }
                                        }
                                }
                        }
                }
        }
        count(admission.deny) == 0 with input as testInput
}
======================================================
after opa fmt -w

test_deployment_admission_has_cpu_limit {
        testInput := {
                "kind": "AdmissionReview",
                "apiVersion": "admission.k8s.io/v1beta1",
                "request": {
                        "namespace": "our-namespace",
                        "kind": {
                                "group": "extensions",
                                "version": "v1beta1",
                                "kind": "Deployment",   <=== invalid 
                        },
                        "operation": "CREATE",
                        "object": {
                                "apiVersion": "extensions/v1beta1",
                                "kind": "Deployment",
                                "metadata": {
                                        "name": "policy-test",
                                        "namespace": "our-namespace",   <=== invalid
                                },
                                "spec": {"template": {"spec": {"containers": [{
                                        "name": "test",
                                        "resources": {"limits": {"cpu": "1m"}},   <=== invalid
                                }]}}},
                        },
                },
        }

        count(admission.deny) == 0 with input as testInput
}

## Expected Behavior
Expected either the formatting to fail because the rego file is not all json
or the json blocks to have valid formatting.  There are ","s introduced that
cause syntax validation to fail.

## Steps to Reproduce the Problem

opa fmt -w some_test.rego

**Comment by tsandall** [comment]
Rego is a superset of JSON and trailing commas are allowed. Because of this, `opa fmt` is behaving correctly. I'm going to close this issue.
