### ISSUE TITLE
Question: OPA injection

### ISSUE THREAD

**Issue by briannd81** [open-policy-agent/opa#2823]
I'm using opa as the mutating admission controller to inject securityContext into new pods. The below policy only injects             the paths for "/spec/containers/0/securityContext/privileged", "/spec/containers/0/securityContext/allowPrivilegeEscalation", and "/spec/containers/0/securityContext/readOnlyRootFilesystem".

It did not inject other security contexts including volumes, fsGroup, hostNetwork, hostIPC, etc...

Any ideas why these other security contexts were not injected?

`
kind: ConfigMap
apiVersion: v1
metadata:
  name: psp-mutating-policy
  namespace: psp-controllers
data:
  main.rego: |
    package system
    import data.kubernetes.admission

    # Entry point to the policy. This is queried by the Kubernetes apiserver.
    main = {
        "apiVersion": "admission.k8s.io/v1beta1",
        "kind": "AdmissionReview",
        "response": response,
    }

    # If no other responses are defined, allow the request.
    default response = {
        "allowed": true
    }

    # Mutate the request if any there are any patches.
    response = {
        "allowed": true,
        "patchType": "JSONPatch",
        "patch": base64url.encode(json.marshal(patches)),
    } {
        patches := [p | p := patch[_][_]] # iterate over all patches and generate a flattened array
        count(patches) > 0
    }

    # Note: patch generates a _set_ of arrays. The ordering of the set is not defined.
    # If you need to define ordering across patches, generate them inside the same rule.
    patch[[
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext",
            "value": {}
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/privileged",
            "value": false
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/allowPrivilegeEscalation",
            "value": false
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/requiredDropCapabilities",
            "value": ["ALL"]
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/volumes",
            "value": [
                "configMap",
                "emptyDir",
                "projected",
                "secret",
                "downwardAPI",
                "persistentVolumeClaim"
            ]
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/hostNetwork",
            "value": false
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/hostIPC",
            "value": false
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/hostPID",
            "value": false
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/fsGroup",
            "value": {
                "rule": "MustRunAs",
                "ranges": [
                    {
                        "min": 1,
                        "max": 65535
                    }
                ]
            }
        },
        {
            "op": "add",
            "path": "/spec/containers/0/securityContext/readOnlyRootFilesystem",
            "value": false
        }
    ]] {

        # Only apply mutations to objects in create/update operations (not
        # delete/connect operations.)
        is_create

        # If the resource has the "test-mutation" annotation key, the patch will be
        # generated and applied to the resource.
        has_psp_policy_label
    }
    is_create { input.request.operation == "CREATE" }
    has_psp_policy_label { input.request.object.metadata.labels["cf.psp/policy"] == "restricted" }
`

**Comment by tsandall** [comment]
@briannd81 That sounds odd. Does the API server log anything about the admission response? I don't see how it would only apply a few of the operations and not all (i.e., I'd expect it to be all or nothing.) Is it possible that NONE of the patches are being applied? The fields you pointed to having been patched are all `false` values--my guess is that's the default value for those fields anyway. That points to an issue with the API server not applying the patch for some reason.

**Comment by anderseknert** [comment]
@briannd81 - I hope you managed to resolve your issue by now? :) 

If there are still any open questions or issues, let me know and I can re-open this ticket. Closing for now.
