### ISSUE TITLE
Add out-of-band API to view and configure explanations

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#283]
It would be very convenient if users could enable explanations on OPA out-of-band from requests.

- Users would write an explanation policy and load it into OPA
- OPA would evaluate the explanation policy on each incoming request to determine if explanations should be generated
- Explanations enabled this way would be stored in a ring buffer inside OPA
- Users could query the API to get the contents of the ring buffer.

**Comment by tsandall** [comment]
This could also be applied to #236.

**Comment by mmussomele** [comment]
Wasn't this resolved by #402?
