### ISSUE TITLE
Rego Libraries

### ISSUE THREAD

**Issue by RichiCoder1** [open-policy-agent/opa#2830]
To enable the better sharing of commonly created and re-used code, it would be great if there was a tooling supported way to create rego code dependent on third-party provided rego "libraries", supported at build, test, and runtime.

This could be made possible as opa cli support for ensuring bundles are present and loaded locally and using bundles as the native format for code sharing, with runtime support using the normal bundle methodology.

**Comment by tsandall** [comment]
I'm going to close this issue as it's been inactive and we have plans on the horizon to start tackling this. See #3371
