### ISSUE TITLE
logging panic under load test with unix domain socket

### ISSUE THREAD

**Issue by mstrYoda** [open-policy-agent/opa#2835]
We are running opa envoy plugin with Istio authz. We have EnvoyFilter connects to opa plugin over Unix Domain Socket.
When we run load test we faced with panic.

## Expected Behavior

Prints decision logs without error.

## Actual Behavior

We faced with panic error.

## Steps to Reproduce the Problem

OPA Plugin args:

`{
		"run",
		"--server",
		"--set=services.bundle.url=" + bundleAPIUrl,
		"--set=bundles.authz.service=bundle",
		"--set=bundles.authz.resource=" + policyPath,
		"--set=bundles.authz.polling.min_delay_seconds=60",
		"--set=bundles.authz.polling.max_delay_seconds=120",
		"--set=plugins.envoy_ext_authz_grpc.addr=unix:///sock/opa-envoy.sock",
		"--set=plugins.envoy_ext_authz_grpc.path=" + defaultDecision,
		"--set=decision_logs.console=true",
	}`

## Additional Info

`authz-agent panic: runtime error: invalid memory address or nil pointer dereference                                                                          │
│ authz-agent [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb1e44e]                                                                           ││ authz-agent goroutine 203286 [running]:                                                                                                                      ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs.(*Plugin).maskEvent(0xc000158fd0, 0xf6b980, 0 │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs/plugin.go:661 +0 ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs.(*Plugin).Log(0xc000158fd0, 0xf6b980, 0xc0009 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/open-policy-agent/opa/plugins/logs/plugin.go:440 +0 │
│ authz-agent github.com/open-policy-agent/opa-envoy-plugin/internal.(*envoyExtAuthzGrpcServer).log(0xc00013e800, 0xf6b980, 0xc00099f0e0, 0xcdf2e0, 0xc0007715 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/internal/internal.go:458 +0x25e                                       ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/internal.(*envoyExtAuthzGrpcServer).Check.func1(0xc000575840, 0xc00013e800, 0xf6b980, 0xc00099f0e0 │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/internal/internal.go:216 +0xcb                                        ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/internal.(*envoyExtAuthzGrpcServer).Check(0xc00013e800, 0xf6b980, 0xc00099f0e0, 0xc00099f110, 0xc0 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/internal/internal.go:343 +0x9a6                                       │
│ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2._Authorization_Check_Handler(0 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/e ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001358c0, 0xf735a0, 0xc000c24600, 0xc0 │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:995 +0x460                    ││ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001358c0, 0xf735a0, 0xc000c24600, 0xc0001 ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:1275 +0xd3d                   │
│ authz-agent github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000504040, 0xc0001358c0, 0xf735a0, ││ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:710 +0xa1                     ││ authz-agent created by github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc.(*Server).serveStreams.func1                              │
│ authz-agent     /Users/emre.savci/go/src/github.com/open-policy-agent/opa-envoy-plugin/vendor/google.golang.org/grpc/server.go:708 +0xa1                     ││ authz-agent stream closed                                                                                                                                    ││`

![image](https://user-images.githubusercontent.com/12763626/97428678-655dd800-1927-11eb-838f-d119aac75c59.png)

**Comment by srenatus** [comment]
ℹ️ The unix socket support isn't part of master, it's been built from this branch: https://github.com/srenatus/opa-istio-plugin/tree/sr/uds

However, I believe it's probably not related to the socket use, but rather due to the load testing scenario. What do you think? 🤔

**Comment by tsandall** [comment]
@mstrYoda can you provide some simple steps to reproduce this? Ideally without involving Istio. Also, can you elaborate on what triggered this issue:

* Does this happen on the very first query or only after some time?
* Once it panics once, does it keep panicking or is the issue transient?

**Comment by tsandall** [comment]
@mstrYoda any updates?

**Comment by mstrYoda** [comment]
> @mstrYoda can you provide some simple steps to reproduce this? Ideally without involving Istio. Also, can you elaborate on what triggered this issue:
> 
> * Does this happen on the very first query or only after some time?
> * Once it panics once, does it keep panicking or is the issue transient?

- It panics after a while
- It keep running but gives error about uploading logs

I will share any further information after a bit while.
