### ISSUE TITLE
add OR

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#2850]
there are lots of docs on how to work around not having or, but how about adding or to avoid all these workarounds and user confusion ?

<img width="682" alt="Screen Shot 2020-10-30 at 4 09 42 PM" src="https://user-images.githubusercontent.com/11367/97764088-b954f200-1aca-11eb-80ed-c8f9cef99aa7.png">

```
action_is_read
user_is_authenticated or path_is_root
```

under the hood it could just translate it to the more verbose statement for example

**Comment by patrick-east** [comment]
@tsandall @timothyhinrichs  thoughts?

**Comment by srenatus** [comment]
Just a side note, we had been talking about adding some sort of "default" operator, say `//`, where
```rego
x // y
```
would evaluate to `y` iff `x` is undefined.  If your `or` here is short-circuiting, I believe it's the same operator with a different name 😄 

(Personally, I think I'd prefer a more symbolic `//` over `or`, for example in `input.foo // "default"` vs `input.foo or "default"`.  Well, it both reads OK, I guess. 🤔)

**Comment by grosser** [comment]
I'd prefer to not use `//` because it looks like a comment
Also would love to have a real `or` and not some "thing that kinda behaves like or but not really", writing rego is hard enough already

**Comment by grosser** [comment]
@srenatus  can this issue be added to a "project" ? 
... since that seems to be the only thing that stale bot ignores

**Comment by srenatus** [comment]
It's been marked as inactive, and I believe that's accurate. The bot is not going to close it, as far as I've reviewed its config.

**Comment by grosser** [comment]
yeah true, all good then :)

**Comment by srenatus** [comment]
@grosser I'm inclined to close this in favour of https://github.com/open-policy-agent/opa/issues/3183 -- to consolidate, for one thing. You could also subscribe to the other one, I suppose 😎
