### ISSUE TITLE
How to cleanly uninstall opa-envoy-plugin for Istio

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#2857]
I have a very basic question on how to "cleanly" (or perhaps correctly) uninstall the opa-envoy-plugin for Istio. 

I guess just deleting all the resources it created along with the "opa-istio" ns should do the job but would like to know if that is the proper way to do it 

thanks
-KB

**Comment by ashutosh-narkar** [comment]
`$ kubectl delete -f quick_start.yaml` should remove the envoyfilter crd and other resources.

**Comment by tsandall** [comment]
Closing this because it doesn't look like there's anything else to answer. We only publish the quick start manifest so deleting the resources contained inside of it should be sufficient.
