### ISSUE TITLE
Unable to get token based authorization to work with bookinfo sample app

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#2860]
Setup: AKS cluster, Istio v1.6.13, opa-envoy-plugin for Istio v 0.24(?)

I had confirmed the sample book app, when using the existing authorization policy in [quick_start](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio), works correctly with above setup .

Next I wanted to change the policy to do authorization decisions using information from a JWT token. For that I decided to use the policy provided in [envoy authorization](https://www.openpolicyagent.org/docs/latest/envoy-authorization/) (section 3 - define a OPA policy). I updated the policy to suit the bookinfo sample app in following manner:
- Allow anyone with guest role (obtained from token) to have GET access to "/productpage" path
- Allow anyone with admin role (obtained from token) to have GET access to "/productpage" AND "/api/v1/products" paths

I replaced the original policy in quick_start.yaml from [opa-envoy-plugin/examples/istio](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio) with above updated policy. Attached find the updated yaml (note - renamed to .txt to stay with allowed file types here).
[qs_token_authz.txt](https://github.com/open-policy-agent/opa/files/5483384/qs_token_authz.txt)

I created a new AKS cluster and installed Istio 1.6.13. Used above yaml to deploy opa-istio plugin and the policy. No errors during any steps. Enabled opa-istio-injection and istio-injection in default ns. Installed the sample bookinfo app, exposed it externally. Bookinfo app was deployed successfully and all pods are running.

I used the following tokens to access the bookinfo app - obtained from the [envoy-authorization](https://www.openpolicyagent.org/docs/latest/envoy-authorization/) page:
export ALICE_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJzdWIiOiJZV3hwWTJVPSIsIm5iZiI6MTUxNDg1MTEzOSwiZXhwIjoxNjQxMDgxNTM5fQ.K5DnnbbIOspRbpCr2IKXE9cPVatGOCBrBQobQmBmaeU"
export BOB_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJZbTlpIiwibmJmIjoxNTE0ODUxMTM5LCJleHAiOjE2NDEwODE1Mzl9.WCxNAveAVAdRCmkpIObOTaSd0AJRECY2Ch2Qdic3kU8"

 curl -H "Authorization: Bearer $ALICE_TOKEN" http://$GATEWAY_URL/productpage

Alice is guest so would have expected the above to get the page contents. But there is no response - not even 403. I tried with $BOB_TOKEN who is admin but same symptoms. 

I captured opa-istio, istio-proxy, opa-istio-admission-controller, productpage logs. The opa-istio log shows decision entries with "message": "undefined decision" but it is not clear what is causing that. Logs attached. 

[opa-istio-admission-controller.log](https://github.com/open-policy-agent/opa/files/5483405/opa-istio-admission-controller.log)
[productpage.log](https://github.com/open-policy-agent/opa/files/5483406/productpage.log)
[istio-proxy.log](https://github.com/open-policy-agent/opa/files/5483407/istio-proxy.log)
[opa-istio.log](https://github.com/open-policy-agent/opa/files/5483408/opa-istio.log)

I suspect there is some problem with the policy but its not obvious to me. Thanks for any help.

-KB

**Comment by ashutosh-narkar** [comment]
From the `opa-isito` logs, OPA seems to be getting the JWT in the input request. Have you tried to unit test your policy before running it in the system ?  It would help to debug this further. See [this](https://www.openpolicyagent.org/docs/latest/policy-testing/) section on unit testing policies.

**Comment by jsane-vp** [comment]
Am having trouble testing my policy. I did this:

1. Installed opa on my system. Created a folder with following two files: one with policy and one with tests. Executed `opa test . -v` in the folder but keep getting "**1 error occurred: opa-plugin-token-authz_test.rego:5: rego_unsafe_var_error: var allow is unsafe**". I had attempted compacting all the input in the _test file on single line but no difference. Attaching the policy file and policy-test files (renamed as .txt). 
[opa-plugin-token-authz_test.rego.txt](https://github.com/open-policy-agent/opa/files/5484605/opa-plugin-token-authz_test.rego.txt)
[opa-plugin-token-authz.rego.txt](https://github.com/open-policy-agent/opa/files/5484606/opa-plugin-token-authz.rego.txt)

2. Attempted doing an eval as follows but am missing something fundamental in what additional input it expects. With the below I thought I provided it with a policy and an input to test the policy against but it keeps demanding a "query" which I don't understand. 
opa eval -i policy_test_input.json -d opa-plugin-token-authz.rego  

Attaching policy_test_input.json (renamed). Same policy file as above. 
[policy_test_input.json.txt](https://github.com/open-policy-agent/opa/files/5484625/policy_test_input.json.txt)

rgds
KB

**Comment by kyle-burnette** [comment]
Am having trouble testing my policy. I did this:

Installed opa on my system. Created a folder with following two files: one with policy and one with tests. Executed opa test . -v in the folder but keep getting "1 error occurred: opa-plugin-token-authz_test.rego:5: rego_unsafe_var_error: var allow is unsafe". I had attempted compacting all the input in the _test file on single line but no difference. Attaching the policy file and policy-test files (renamed as .txt).
[opa-plugin-token-authz.rego.txt](https://github.com/open-policy-agent/opa/files/5484813/opa-plugin-token-authz.rego.txt)
[opa-plugin-token-authz_test.rego.txt](https://github.com/open-policy-agent/opa/files/5484814/opa-plugin-token-authz_test.rego.txt)

Attempted doing an eval as follows but am missing something fundamental in what additional input it expects. With the below I thought I provided it with a policy and an input to test the policy against but it keeps demanding a "query" which I don't understand.
`opa eval -i policy_test_input.json -d opa-plugin-token-authz.rego`

Attaching policy_test_input.json (renamed). Same policy file as above.
policy_test_input.json.txt
[policy_test_input.json.txt](https://github.com/open-policy-agent/opa/files/5484816/policy_test_input.json.txt)

rgds
KB

**Comment by ashutosh-narkar** [comment]
I tested your policy in the Rego playground. It seems to work https://play.openpolicyagent.org/p/AfIqMbfruj.

**Comment by kyle-burnette** [comment]
Indeed! Thanks for your help. 
I also removed the test_ rule(?) from the left pane and upon pasting the actual input (below) in INPUT window/pane on right, and doing an evaluate it works as one would expect. 
```
{
  "attributes": {
     "request": {
         "http": {
          "method": "GET",
          "path": "/productpage",
          "headers": {
              "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJzdWIiOiJZV3hwWTJVPSIsIm5iZiI6MTUxNDg1MTEzOSwiZXhwIjoxNjQxMDgxNTM5fQ.K5DnnbbIOspRbpCr2IKXE9cPVatGOCBrBQobQmBmaeU"
              }
           }
         }
    }
}

```
I confirmed the policy contents in "opa-policy" configmap in my cluster are same as what is tested in the Rego playground. Not sure why it would not work there. Is there a way to make opa-istio container log more verbose messages like the json output in Rego playground output. That can help figure what part of the policy or input it is having problems with. Unless it wont generate any JSON if it cannot evaluate something the policy using the supplied input (by design).

I tested again using the same curl command as earlier but now I get a 503 which is different from getting no output till before. Nothing changed...  Am attaching a trimmed version of opa-istio log after the latest attempt. The entries look no different from the last time around. Productpage and istio-proxy logs do not show any errors around that time. 

```
HTTP/1.1 503 Service Unavailable
date: Wed, 04 Nov 2020 19:41:07 GMT
server: istio-envoy
content-length: 0
x-envoy-upstream-service-time: 64
```
[trimmed_opa-istio.log](https://github.com/open-policy-agent/opa/files/5490159/trimmed_opa-istio.log)


thanks for your help. 
KB

**Comment by ashutosh-narkar** [comment]
The decision log contains the actual input OPA receives. Is the config map that contains the policy being loaded into the OPA-Envoy container ? I wouldn't have expected an `undefined decision`  error in the decision logs.

**Comment by kyle-burnette** [comment]
It looks like the policy is loaded in the opa-envoy container. I queried it as: 
kubectl exec ratings-complete-pod-name -c ratings -- curl http://localhost:8181/v1/policies. It's quite raw and formatting is gone but definitely see the policy contents. Let me know if you would like to see it ; there is some more gobly gook there than I can make sense of. 
 
More over, all I had done was just replace the policy in the original [quick_start.yaml](https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/examples/istio/quick_start.yaml) with my policy. I have attached qs_token_authz.txt in my first post of this issue.  

I took the "input" portion of one of decision log entries in opa-istio container log and placed in rego playground input. It works as expected. Am attaching that sample input from one of the decision entries from opa-istio log. 
[working-policy-input-in-regoplayground.txt](https://github.com/open-policy-agent/opa/files/5491802/working-policy-input-in-regoplayground.txt)

Am confused now. Wondering if there is something different being passed to opa envoy than just the "input" shown in the log. And then the question is - why only in case of this policy and not the original simple policy from quick_start.yaml (with the same setup). 

regards
KB

**Comment by ashutosh-narkar** [comment]
Can you share your entire `quick_start.yaml` file ?

**Comment by kyle-burnette** [comment]
Please find attached my version of qs_token_authz.yaml (renamed to .txt to conform to github file attach policy). 
[qs_token_authz.txt](https://github.com/open-policy-agent/opa/files/5496122/qs_token_authz.txt)

I also examined the policy as loaded in opa-envoy container and it is correct/matches with that in above yaml. 

thanks,
KB

**Comment by ashutosh-narkar** [comment]
The package name for your policy should be `istio.authz` and not `envoy.authz` as you are setting `path: istio/authz/allow` in the plugin config.

**Comment by kyle-burnette** [comment]
Sorry about that. I am new to this space and so did not realize. 

I removed the bookinfo app, opa-envoy plugin (but kept Istio), changed the policy package to "istio.authz" and deployed it back again. Re-enabled opa-istio-injection in default ns.

It seemed to work this time but my joy was short lived. It was allowing any access - with no tokens, arbitrary tokens or tokens w/o right roles etc. Turns out the requests are not being sent to opa-istio at all. There are no decision_id entries in its log. I looked at istio-proxy logs but they do not look any different than when it used to consult opa-istio (when the policy package was set to "envoy.authz"). 

I am thinking of starting everything fresh in a new cluster just in case the above steps might have led to some inconsistent state. 

But in meantime if you can think of something to check that I may have missed pl let me know. Apologies if I did blunder again. 

rgds
KB

**Comment by ashutosh-narkar** [comment]
A fresh start would help. In my setup, the plugin seems to work as expected with Istio `1.6.13`. If you're not seeing the correct response from the OPA policy (assuming the request reaches OPA), I would take the input from the decision log and apply it to your policy in the playground etc. and make the necessary updates to the policy.

**Comment by kyle-burnette** [comment]
After starting with a new cluster everything works as expected. 

Appreciate all the help. thx
KB

**Comment by kyle-burnette** [comment]
Quick q: 
I do not see a 403 response though when requests are denied. Is that normal in this case?

**Comment by ashutosh-narkar** [comment]
If the OPA decision is `false`, Envoy returns a `403` to the client.
