### ISSUE TITLE
issue for go library

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2861]
**I have just run the sdk demo with:**  
go run main.go example.rego 'data.example.violation' < input.json
**But my question is:  how to pass the data file? my understand is opa need three model, e.g. acl.rego、acl.data、acl.input
should we must write data and input to  input.json? I mean, how to separate data and input from input.json?

And for example, i used opa with api just need three steps, but opa sdk seem not support these?**
curl -X PUT http://opa.xxx.com/v1/data/jmrdata/acl --data-binary @acl.json
curl -X PUT http://opa.xxx.com/v1/policies/jmrdata --data-binary @acl.rego
curl -s -X POST http://opa.xxx.com/v1/data/jmr/jmrdata/policy/allow --data-binary @acl.input

**Comment by tsandall** [comment]
@andyyumiao I'm assuming you're talking about this example? https://www.openpolicyagent.org/docs/latest/#5-try-opa-as-a-go-library

The `rego.Load` option will load all .rego, .yaml, and .json files from the given path: https://pkg.go.dev/github.com/open-policy-agent/opa/rego#Load

Otherwise, if you want fine-grained control over the raw JSON stored under `data` you can pass and manage a store: https://pkg.go.dev/github.com/open-policy-agent/opa/rego#Store

**Comment by andyyumiao** [comment]
> https://pkg.go.dev/github.com/open-policy-agent/opa/rego#Store

Hi @tsandall , many thanks for the reply~

**Comment by andyyumiao** [comment]
> https://www.openpolicyagent.org/docs/latest/#5-try-opa-as-a-go-library

yes @tsandall ,more exactly, we know opa have the 'import' keywords, such as:
import data.xx.xxx  #the policy data
import input  #the user input

1.should i use the rego.Load option for loading all of them? 
2.How should we initialize them separately and sometimes update the policy data dynamically?

**Comment by andyyumiao** [comment]
> @andyyumiao I'm assuming you're talking about this example? https://www.openpolicyagent.org/docs/latest/#5-try-opa-as-a-go-library
> 
> The `rego.Load` option will load all .rego, .yaml, and .json files from the given path: https://pkg.go.dev/github.com/open-policy-agent/opa/rego#Load
> 
> Otherwise, if you want fine-grained control over the raw JSON stored under `data` you can pass and manage a store: https://pkg.go.dev/github.com/open-policy-agent/opa/rego#Store

@tsandall I just constructed a Rego object like below, it contains a rego and data file:
                r := rego.New(
		rego.Query(os.Args[3]),
		rego.Load([]string{os.Args[1],os.Args[2]},  nil))

But how could i update the rego and json data dynamically after the program starts running？

**Comment by tsandall** [comment]
@andyyumiao you can use the store to manage data dynamically. For modules you can either use `rego.Module` or parse and compile yourself and use `rego.Compiler`.

**Comment by andyyumiao** [comment]
> @andyyumiao you can use the store to manage data dynamically. For modules you can either use `rego.Module` or parse and compile yourself and use `rego.Compiler`.

@tsandall About `rego.Module` and `rego.Compiler`,  can you provide a complete demo for them? we can't know the specific usage with basic API method definition...

**Comment by tsandall** [comment]
@andyyumiao take a look at the package examples: https://godoc.org/github.com/open-policy-agent/opa/rego#pkg-examples

**Comment by andyyumiao** [comment]
> @andyyumiao take a look at the package examples: https://godoc.org/github.com/open-policy-agent/opa/rego#pkg-examples

@tsandall **I'm sorry for that i still not found how to load new policy dynamically, it seems that we can only create rego.New(...) once at the begin, for example, we can create a new query that uses the compiled policy as below:**
rego := rego.New(
    rego.Query("data.example.allow"),
    rego.Compiler(compiler),
    rego.Input(
        map[string]interface{}{
            "identity": "bob",
            "method":   "GET",
        },
    ),
)

But after that, more policy will come in, should we create many new query for more policy? ? such as:
rego := rego.New(...)
rego1 := rego.New(...)
rego2 := rego.New(...)
rego3 := rego.New(...)
