### ISSUE TITLE
Improve runtime error reporting for wasm compiled policies

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2862]
Runtime errors do not include any source location information currently. This makes it difficult to pinpoint the source of the error in large policies. The planner and wasm backend should propagate source locations so that runtime errors can be identified more easily.

**Comment by srenatus** [comment]
I think this could be only tangential, but for _debugging_ WASM, DAWRF seems to be the relevant format to support :thinking: https://developers.google.com/web/updates/2019/12/webassembly (Raises some questions on merging the C debug symbol info with the one coming from rego...)

**Comment by tsandall** [comment]
Yep, we should preserve the DWARF symbols for the C library and ideally emit them for the compiled rules. We have an issue for this already: #2788. This issue is specifically for improving the reporting on runtime errors like conflict errors.
