### ISSUE TITLE
user not a member of list

### ISSUE THREAD

**Issue by keg7271** [open-policy-agent/opa#2864]
not a bug just a question

I have a list of users
{ "validUsers": [ "userA", "userB", "userC", "userD" ] }

Then I have two user groups
{ "userGroup1": [ "userA", "userB" ], "userGroup2": [ "userC", "userD", "userE" ] }

I am trying to identify and fail a rule when userE in userGroup2 is not a member of the validUsers list.

**Comment by tsandall** [comment]
This boils down to computing the set of invalid group members and then doing something with it. One approach would be to write writes that identify valid and invalid group members. Assuming we have the following assignments:

```rego
users := [ "userA", "userB", "userC", "userD" ]
groups := { "userGroup1": [ "userA", "userB" ], "userGroup2": [ "userC", "userD", "userE" ] }
```

```rego
# generates a set of users that are members of a group and in the validUsers array.
valid_group_members[user] {
  some group, i, j
  user := groups[group][i]
  users[j] == user
}
```

```rego
# generates a set of users that are members of a group but NOT contained in the set above.
invalid_group_members[user] {
   some group, i
   user := groups[group][i]
   not valid_group_members[user]
}
```

However, using set comprehensions and taking the difference is quite a bit more concise:

```rego
members := {u | u := groups[_][_]}
valid_users := {u | u := users[_]}
invalid_members := members - valid_users
```

Now we can just use the `invalid_members` however we like...

```rego
deny { count(invalid_members) > 0 }
allow { count(invalid_members) == 0 }
```

Etc.
