### ISSUE TITLE
JWT encode with HMAC problem

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#2870]
From the docs on [JWT HMAC encoding](https://www.openpolicyagent.org/docs/latest/policy-reference/#round-trip-sign-and-verify) it sounds like the JWK provided should just contain any base64url encoded secret in the `k` attribute. This however seems to break for many variations of the secret.

## Expected Behavior

Expected to work:

`jwt := io.jwt.encode_sign({"alg":"HS256"},{},{"kty":"oct","k":base64url.encode("abcdefghijklm")})`

## Actual Behavior

`policy.rego:3: eval_builtin_error: io.jwt.encode_sign: Failed to unmarshal JWK: failed to decode from base64: illegal base64 data at input byte 18`

Removing the last `m` in the secret has the encoding working again - other letters and combinations work sometimes and sometimes not.

## Steps to Reproduce the Problem

https://play.openpolicyagent.org/p/ucvNsK9gMV

## Additional Info

https://tools.ietf.org/html/rfc7518

**Comment by srenatus** [comment]
Is this related to #2867, by any chance? Comparing `base64url.encode("abcdefghijklm")` and `base64url.encode("abcdefghijkl")`, the former is padded,
```
YWJjZGVmZ2hpamtsbQ==
```
the latter is not. So I'd guess the base64url no_padding variant from #2867 would solve this, possibly?

**Comment by anderseknert** [comment]
Yeah, looks like it would @srenatus 👍 Given how no one (?) reported this before I guess it's just not a commonly used feature, but this HMAC encoding feels pretty clunky as it is already, and having the policy author "base64url no_padding" encode the secret before manually crafting a JWK.. I don't know. I'd much prefer it if there was a helper like the various `_decode` functions here which would just take payload + secret and do the heavy lifting - especially so since HMAC is primarily used for development and testing and as such should be simple. As things get closer to production one would normally reach for the asymmetric algorithms (and can tolerate the increased complexity in that context).

So yeah - short term fix would be to update the docs for 0.25.0 and then consider making the HMAC encoding story somewhat more appealing.

**Comment by anderseknert** [comment]
Just saw the 0.25.0-rc1 commits, but if / when #2876 is merged I'll follow up with a PR updating the docs to use that.

**Comment by srenatus** [comment]
Of course you can remove the padding in rego, too, without extra builtins... https://play.openpolicyagent.org/p/H2YxO3rAfn :wink:
