### ISSUE TITLE
OPA policy got enabled on docker daemon but local root user cannot authorize with policy

### ISSUE THREAD

**Issue by AmalKeecheril** [open-policy-agent/opa#2876]
## Actual Behavior
- OPA plugin enabled for docker daemon
- policy enabled for remote user was working perfectly but local root user got restriction error 
- Not sure, how to define the local root user for enabling access or 
- Is there any way to whitelist local root user for unix socket and only apply policy for remote user with tcp socket

**Comment by tsandall** [comment]
@AmalKeecheril you'd have to dig into the input data sent to OPA by the Docker authorization framework. If you have authentication enabled on the Docker daemon, you could check the `input.User` field. If that field is set, then you may be able to identify the user. I don't think there is a way to distinguish between calls via TCP vs UNIX domain sockets.
