### ISSUE TITLE
OPA sidecar not running with istio proxy sidecar.

### ISSUE THREAD

**Issue by shashanksrivastava10** [open-policy-agent/opa#2877]
Hi Team,

This issue is with respect to the page https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio that demonstrates injection of opa with istio envoy sidecar to enforce policies.

## Expected Behavior
I actually expected it to be pretty stratightforward  and to work it like when we inject our own envoy with opa as described here: https://github.com/open-policy-agent/opa-envoy-plugin (This one works fine).

## Actual Behavior
After labelling the namespace where we deploy the bookinfo application for istio proxy and opa sidecar injection i could see that the opa container does not come up and throws an error stating that Liveness probe failed: HTTP probe failed with statuscode: 403, the readiness probe also fails with the same error, i tried debugging it lot and was able to see it working when isito injection was disabled. but with istio injection enabled it never worked, Can you please assist me here as to what i might be doing wrong.

* OPA version : 0.24.0
* Istio proxy version : proxyv2:1.7.4
* Kubernetes version : 1.16

**Comment by tsandall** [comment]
This sounds like it's the same issue as described in https://github.com/istio/istio/issues/26805 and https://github.com/open-policy-agent/opa/issues/2831. I'm going to close this because it seems like a duplicate. We can reopen if needed.
