### ISSUE TITLE
Add check policy endpoint to the REST API

### ISSUE THREAD

**Issue by peledkfir** [open-policy-agent/opa#2889]
It would be nice to have an endpoint to check the policy (without saving it) same as the cli command check

**Comment by tsandall** [comment]
We could add a `dry-run` option to the `PUT /v1/policies` API however I'm a bit skeptical about how useful this would be.

**Comment by peledkfir** [comment]
I'm trying to build my own playground and for that I wished I had a dry-run without using the command line :)

Thanks anyway

**Comment by tsandall** [comment]
@peledkfir ah :) in that case it would probably work reasonably well!

**Comment by anderseknert** [comment]
Another ticket for this feature request is open [here](https://github.com/open-policy-agent/opa/issues/1730). Closing this in favor of that.
