### ISSUE TITLE
Docs should indicate which built-in functions are automatically supported w/ wasm

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2910]
Users compiling policies to wasm need to ensure all referenced built-in functions are available otherwise the wasm module will not instantiate.

Currently we don't provide an easy way for users to know whether built-in functions are supported natively. It would be nice if the built-in reference in the documentation indicated whether each function (or group of functions) has native support. One option would be to include a column in each function table to indicate wasm status (i.e., supported or SDK dependent.) To avoid maintaining this column manually, the site generator can inspect the wasm compiler backend for the list of natively implemented built-ins.

**Comment by anderseknert** [comment]
In addition to the docs, could this info perhaps be pushed to the capabilities.json file for each release as well? Seems useful to have this kind of info collected in a single place.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/pull/2952 fixed at least a part of this, I believe?

I like the capabilities idea. 💡

**Comment by tsandall** [comment]
I'm going to close this issue for now because #2952 does address the most important bit (communicating to users what's supported and what's not.) We can revisit automation and inclusion in the capabilities document in the future as needed.
