### ISSUE TITLE
Using else keyword swallows result of rule in else branch

### ISSUE THREAD

**Issue by SadCodePoet** [open-policy-agent/opa#2912]
When using a with the `else` keyword, where any of the else branches is the valid one, the rule evaluates to just `true`.

As an example take the following:
``` rego
response(obligations) = result {
    result := {
        "result": true,
        "obligations": obligations
    }
}

allow = result {
	branch == 1
    result :=  response([1])
} else {
	branch == 2
    result := response([2])
} else {
	branch == 3
    result := response([3])
}
```

For `branch == 1` the output is as expected:
``` json
"allow": {
        "obligations": [
            1
        ],
        "result": true
    }
```

## Expected Behavior
for `branch := 2` or `branch := 3` the same output is expected.
## Actual Behavior
The Output for 2 and 3 is simply `"allow": true`

It appears to shortcut and swallow the evaluation of `response(obligations)`.

Note that this is visible from Rego Playground, CLI and from Explain.

**Comment by anderseknert** [comment]
The return binding from the first rule does not implicitly carry over to the else rules. Unless provided an explicit return variable or value, they (as any other rule) will return an implicit true, as you noted. If you explicitly declare what you want your else rules to return it works as you expect: 

```rego
allow = result {
    branch == 1
    result :=  response([1])
} else = result {
    branch == 2
    result := response([2])
} else = result {
    branch == 3
    result := response([3])
}
```

**Comment by SadCodePoet** [comment]
Hi Anders,
thanks for the swift reply and the example!
Best regards,
Sebastian
