### ISSUE TITLE
Improve error message when with statement cannot merge documents

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2921]
The error message that topdown reports when a with statement cannot merge documents is a bit confusing:

```rego
true with input as [] with input.foo as 1
```

In this case, the second with statement cannot be applied because `input` has been set to an empty array. The same would occur if input was previously set to an array and then only second the with statement was applied.

The current error message is:

```
<location>: eval_conflict_error: conflicting documents
```

We should improve the error to better indicate the source of the issue. For example:

```
<location>: eval_conflict_error: cannot apply with statement because 'input' is array
```

**Comment by srenatus** [comment]
With #3010, this would no longer be a conflict: `input` would end up as `{"foo": 1}`.

**Comment by srenatus** [comment]
Closing -- Not a conflict anymore:
```
open-policy-agent/opa % ./opa_darwin_amd64 eval 'input with input as [] with input.foo as 1' --format=pretty
{
  "foo": 1
}
open-policy-agent/opa %
```
