### ISSUE TITLE
wasm: With keyword "target confict: internal error"

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2922]
There are a handful of test cases which fail with an unexpected runtime error when evaluated with the Wasm SDK:

```
with target conflict: internal error
```

This includes the following test cases:

"withkeyword/with base doc exact value" --> [test/cases/testdata/withkeyword/test-withkeyword-1036.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1036.yaml)
"withkeyword/with base doc any index" --> [test/cases/testdata/withkeyword/test-withkeyword-1037.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1037.yaml)
"withkeyword/with virtual doc specific index" --> [test/cases/testdata/withkeyword/test-withkeyword-1037.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1037.yaml)
"withkeyword/undefined_1" --> [test/cases/testdata/withkeyword/test-withkeyword-1038.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1038.yaml)
"withkeyword/with virtual doc exact value" --> [test/cases/testdata/withkeyword/test-withkeyword-1040.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1040.yaml)
"withkeyword/with virtual doc any index" --> [test/cases/testdata/withkeyword/test-withkeyword-1041.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1041.yaml)
"withkeyword/with virtual doc not specific index" --> [test/cases/testdata/withkeyword/test-withkeyword-1043.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/withkeyword/test-withkeyword-1043.yaml)

**Comment by tsandall** [comment]
The tests are erroring because of a discrepancy in the `with` statement implementation:

* topdown upserts the value at the path, overwriting intermediate values as needed
* wasm expects the path to refer thru objects, it errors if intermediate values are not objects

We should be able to change the wasm compiler to treat a non-object intermediate value the same as a missing value.
