### ISSUE TITLE
wasm: Difference in handling virtual doc conflicts

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/opa#2926]
For this test case: [test/cases/testdata/baseandvirtualdocs/test-baseandvirtualdocs-0704.yaml](https://github.com/open-policy-agent/opa/blob/master/test/cases/testdata/baseandvirtualdocs/test-baseandvirtualdocs-0704.yaml)

The expected behavior is that the evaluation can be performed and a result is found. For the Wasm generated policy we get a runtime error:

```
unexpected error: object merge conflict: internal error
```

The behavior seems to be that for a topdown evaluation it would use the base document value from the store, whereas the wasm implementation seems conflict with that when evaluating the result.

**Comment by tsandall** [comment]
In this test case, the planner generates the virtual document value and then emits ir.ObjectMergeStmt which the backend implements by calling `opa_value_merge`. The latter returns NULL if there are any conflicts and the compiler handles the NULL result by aborting. To solve this, we can implement another value merge function that prefers one side in case of conflicts.
