### ISSUE TITLE
Add ceil() function

### ISSUE THREAD

**Issue by tsunny** [open-policy-agent/opa#2930]
We have `round()` function at the moment. But it would be nice to have ceil() and floor() math functions as well.

```
# 1.0 -> 1.0
ceil(value) = result {
  round(value) == value
  result := value
}

# 1.6 -> 2
ceil(value) = result {
  round(value) - value > 0
  result := round(value)
}

# 1.1 -> 2
ceil(value) = result {
  (round(value) - value) < 0
  result := round(value) + 1
}
```

Thanks!

**Comment by anderseknert** [comment]
Would this do?

`ceil(n) = round(n + 0.5)`

Or is there any case I'm missing? :)

**Comment by tsandall** [comment]
These would be nice to have. I don't see a reason not to add them. The implementation just has to be careful to use big numbers internally.

**Comment by grosser** [comment]
ah yes, that's even simpler :)
