### ISSUE TITLE
Proposal: New plugin state "WARN"

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2932]
We have a custom authorization plugin for the opa rest client that involves periodically grabbing credentials to use in requests sent to the status/log APIs.  We rotate the credentials ~15 minutes before they expire.  In the event that the rotation fails, we need to be able to surface this state in our status logs.  However, the existing "ERROR" state causes the opa server healthcheck to fail, which we don't want, because that will terminate our OPA instance.  We need a new state that allows us to indicate there is a potential future problem, without causing the healthcheck to fail.  We propose a "WARN" state for this purpose.

**Comment by patrick-east** [comment]
Seems like a pretty reasonable addition. One more thing to consider along with this is extending the status to include a message or something. Could probably get away with something simple like a new (optional) string field added to https://github.com/open-policy-agent/opa/blob/c23ae41440b08bf9ce0cdfb4521e1218180dafa5/plugins/plugins.go#L117-L120

**Comment by gshively11** [comment]
Yea, that comment on line 117 threw me for a little loop, I couldn't find the message 😁

**Comment by patrick-east** [comment]
Hah, yea.. I think the original implementation included the message but we removed it since we didn't really have a good use-case for them at the time. We can "fix" the comment by bringing it back 😆
