### ISSUE TITLE
Planner generates cross-product given non-ground refs to packages

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2936]
The planner is generating a cross-product unnecessarily when it encounters non-ground refs to packages and rules. For example, given the following modules, the query `data.foo[x].p; data.foo[x].q` will generate blocks that are never satisfied because `x` does cannot unify in both cases.

```
package foo.bar
p = 1
q = 1
```

```
package foo.baz
p = 2
q = 2
```

In this case, the planner essentially generates:

```
assign "bar" to x
call foo.bar.p
   if "bar" == x { call foo.bar.q }
   if "bar" == x { call foo.baz.q }
   add to result set
assign "baz" to x
call foo.baz.p
   if "baz" == x { call foo.bar.q }
   if "baz" == x { call foo.baz.q }
  add to result set
```

As the compiler output grows, module load times and memory usage increase. At a certain point, wasm runtimes reject the module because the inlined code section is too large. To address this, the planner and wasm backend can implement dynamic dispatch:

```
assign "bar" to x
call foo[x].p {x: "bar"}
  call foo[x].q {x: bar"}
assign "baz" to x
call foo[x].q {x: "baz"}
  call foo[x].q {x: "baz"}
```

The wasm backend will be responsible for building a function table for dynamically dispatched rules. The wasm backend can then invoke a lookup function that takes the dynamically dispatched ref (e.g., `foo[x].p`), a set of variable assignments (e.g., `{x: "bar"}`) and returns the function index invoke (e.g., `foo.bar.p`).

**Comment by srenatus** [comment]
Still a problem with empty rule sets on leaves, will do a followup.

**Comment by tsandall** [comment]
@stephan I'm going to close this out now that we've added the optimization for empty leaves.
