### ISSUE TITLE
how to load new policy incrementally

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2939]
For example, how to load 100,000 pieces of policy data? I mean not one-time loading. These policys need dynamically loaded and changed frequently. How to write it with api? Or how should the core sdk code be written？

**Comment by srenatus** [comment]
There's a few options outlined in the ["External Data" docs section](https://www.openpolicyagent.org/docs/latest/external-data/#option-4-push-data), which also discusses the different trade-offs wrt frequently-changing data. Have you had a chance to review that, and its [_Option 4, Push Data_](https://www.openpolicyagent.org/docs/latest/external-data/#option-4-push-data) specifically? 😃

**Comment by andyyumiao** [comment]
> There's a few options outlined in the ["External Data" docs section](https://www.openpolicyagent.org/docs/latest/external-data/#option-4-push-data), which also discusses the different trade-offs wrt frequently-changing data. Have you had a chance to review that, and its [_Option 4, Push Data_](https://www.openpolicyagent.org/docs/latest/external-data/#option-4-push-data) specifically? 😃
@srenatus thanks for the reply, the demo(https://www.openpolicyagent.org/docs/latest/external-data/#option-4-push-data) seems for the http rest api, but i mean how to do this with go library...

**Comment by srenatus** [comment]
@andyyumiao Ah thanks, I didn't get that. Using the Go library, you can control the store directly, 

https://github.com/open-policy-agent/opa/blob/5c6c96331803c17158bc0a1b1b705cecef023ea1/storage/interface.go#L17-L37

You should find many example usages in this code base, since it's the method the HTTP handlers use. LMK if you get stuck. :)

**Comment by andyyumiao** [comment]
> You should find many example usages in this code base, since it's the method the HTTP handlers use. LMK if you get stuck. :)

@sy

**Comment by andyyumiao** [comment]
> @andyyumiao Ah thanks, I didn't get that. Using the Go library, you can control the store directly,
> 
> https://github.com/open-policy-agent/opa/blob/5c6c96331803c17158bc0a1b1b705cecef023ea1/storage/interface.go#L17-L37
> 
> You should find many example usages in this code base, since it's the method the HTTP handlers use. LMK if you get stuck. :)

@srenatus another questions, do we have a way to batch insert the policy?

**Comment by srenatus** [comment]
> @srenatus another question, do we have a way to batch insert the policy?

Hmm I'll have a look at the code later, I'm not sure that something like this would be possible. For clarification, you're not asking if it's possible to add multiple policies in one transaction, but you're looking for a way to add multiple policies in one operatiion...?

**Comment by andyyumiao** [comment]
> > @srenatus another question, do we have a way to batch insert the policy?
> 
> Hmm I'll have a look at the code later, I'm not sure that something like this would be possible. For clarification, you're not asking if it's possible to add multiple policies in one transaction, but you're looking for a way to add multiple policies in one operation...?

@srenatus yes you are right, it's enough to add multiple policies in one transaction. and would you mind giving me a suggestion: as i found that an ordinary decision needs about tens of µs, but a slightly more complicated rule may be in hundreds of µs. How to optimize it？

**Comment by srenatus** [comment]
One thing to note is that you only get one data point this way. You can wire the eval call into golang's benchmark machinery for more robust numbers, I think.
