### ISSUE TITLE
storage_invalid_txn_error: stale transaction

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#2941]
I committed a transaction before the `PrepareForEval` method,   then i got the error when executed the `PrepareForEval` method...
so,  should the transaction must be commit after `PrepareForEval` method?

**Comment by srenatus** [comment]
Can you include a sample snippet? While your description is probably on the spot, it would perhaps be easier to help if we were able to play with some code of yours. 🤔

**Comment by andyyumiao** [comment]
> Can you include a sample snippet? While your description is probably on the spot, it would perhaps be easier to help if we were able to play with some code of yours. 🤔 Some MWE would be great 😃

@srenatus below is my test code:
`package main

import (
	"bytes"
	"context"
	"fmt"
	"github.com/open-policy-agent/opa/rego"
	"github.com/open-policy-agent/opa/storage"
	"github.com/open-policy-agent/opa/storage/inmem"
)

func main()  {
	ctx := context.Background()

	// Create storage layer and load dummy data.
	store := inmem.NewFromReader(bytes.NewBufferString(`{
		"favourites": {
			"pizza": "cheese",
			"colour": "violet"
		}
	}`))

	// Open a write transaction on the store that will perform write operations.
	txn, err := store.NewTransaction(ctx, storage.WriteParams)
	if err != nil {
		// Handle error.
	}

	// Create rego query that uses the transaction created above.
	inside := rego.New(
		rego.Query("data.favourites.pizza"),
		rego.Store(store),
		rego.Transaction(txn),
	)

	// Write change to storage layer inside the transaction.
	err = store.Write(ctx, txn, storage.AddOp, storage.MustParsePath("/favourites/pizza"), "pepperoni")
	if err != nil {
		// Handle error.
	}

	// Run evaluation INSIDE the transaction.
	rs, err := inside.Eval(ctx)
	if err != nil {
		// Handle error.
	}

	fmt.Println("value (inside txn):", rs[0].Expressions[0].Value)

	if err := store.Commit(ctx, txn); err != nil {
		// Handle error.
		fmt.Println("commit failed",err)
	}

	query, err := inside.PrepareForEval(ctx)
	if err != nil {
		fmt.Println(err)
	}

	rs1, err := query.Eval(ctx, rego.EvalInput(`{"a":"b"}`))
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(rs1)
}
`

**Comment by tsandall** [comment]
@andyyumiao committing the transaction closes it. You cannot continue using it after it's been committed or aborted.
