### ISSUE TITLE
Questions on policy using URL extraction

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#2943]
I am not sure if this is a bug or me  not understanding something. I wanted to test/experiment with URL extraction from within a policy. 
I went to the Rego playground and selected the "URL extraction" example from the drop down. Without changing anything, in the policy and the input data, it evaluates correctly to true as expected. 

I wanted to test behavior by changing the "charlie" in the request path to something else. I updated the **input data** with following changes one by one:

## Actual behavior
1. Changed the path in "request.http.headers" to replace charlie with test. It continued to evaluate to true.
2. In addition to above, changed the path in "request.http" to replace charlie with test. It continued to evaluate to true.
3. In addition to above, replaced charlie in "parsed_path" with test. This time it started evaluating to false. In fact, only changing it here while leaving the path in both request.http.headers and request.http intact seems to matter.

## Expected behavior
I am confused. I would have thought the `input.parsed_path = ["users", "profile", user_name]` in the policy would make it evaluate the parsed_path dynamically based in the incoming path in the HTTP request. To test that hypothesis I deleted the following from input data while leaving everything else intact - path in request.http.headers and request.http was set to "users/profile/charlie".  With that it would evaluate to false. 

Otherwise, having to parse out the URL first and providing it as an input seems quite meaningless and perhaps infeasible. What was the purpose of showing this example? 

My question would be - how does one change the policy so it can use portions of request path that are parsed dynamically. 

## Steps to Reproduce the Problem
See above.

* OPA version: Rego playground (online)

My second question is about the package declaration of "package envoy.http.urlextract". I wish to use URL extraction when using a policy with OPA plugin for Istio. And I know based on experience that the package is sensitive to where the policy is being used. In case of OPA plugin for Istio, it needs to be "istio.authz" - I had accidentally set it to "envoy.authz" and it would not work. 

What am I missing? 

thanks
KB

**Comment by tsandall** [comment]
> In addition to above, replaced charlie in "parsed_path" with test. This time it started evaluating to false. In fact, only changing it here while leaving the path in both request.http.headers and request.http intact seems to matter.

Correct. Changing `request.http.headers` has no affect because the policy does not refer to it. I think you're expecting `parsed_path` to be something special--it's not. It's just another field that's provided inside the `input` document. 

> Otherwise, having to parse out the URL first and providing it as an input seems quite meaningless and perhaps infeasible. What was the purpose of showing this example?

The `input.parsed_path` field is provided by the opa-envoy integration. If you want convenient access to the HTTP request path that can be efficiently pattern-matched on, you have it.

> My question would be - how does one change the policy so it can use portions of request path that are parsed dynamically.

Are you saying that you want to parse the raw HTTP request path inside the policy instead of using the one provided by the opa-envoy integration? Why?

> My second question is about the package declaration of "package envoy.http.urlextract". I wish to use URL extraction when using a policy with OPA plugin for Istio. And I know based on experience that the package is sensitive to where the policy is being used.

The package is just a namespace for the rules. To query for the value generated by one or more rules, you need to know the package because that controls where the values are generated under `data`. In the case of the opa-envoy integration, the default decision is `data.envoy.authz.allow`. See the configuration for the plugin for more info.

> In case of OPA plugin for Istio, it needs to be "istio.authz" - I had accidentally set it to "envoy.authz" and it would not work.

It sounds like you're running an old version of opa-envoy. Take a look at the config docs: https://github.com/open-policy-agent/opa-envoy-plugin#configuration

**Comment by kyle-burnette** [comment]
> The input.parsed_path field is provided by the opa-envoy integration. If you want convenient access to the HTTP request path that can be efficiently pattern-matched on, you have it.
> Are you saying that you want to parse the raw HTTP request path inside the policy instead of using the one provided by the opa-envoy integration? Why?

Thank you for your response. I was not aware that the input.parsed_path was already provided/constructed by opa-envoy integration. I certainly don't mind using it if it gets constructed (dynamically) based on the request's path. Would it be available in OPA plugin for Istio? My opa container is just opa and not opa-envoy so asking (comes from [opa-envoy-plugin for istio quick start](https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/examples/istio/quick_start.yaml). 

> The package is just a namespace for the rules. To query for the value generated by one or more rules, you need to know the package because that controls where the values are generated under data. In the case of the opa-envoy integration, the default decision is data.envoy.authz.allow. See the configuration for the plugin for more info.

So I understand correctly, do the 'path: /istio/authz/allow' in opa-istio-config below control what the package should get named as? 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-istio-config
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: istio/authz/allow
    decision_logs:
      console: true
```
With the above, I had to set the package in my policy to "istio.authz" for my policy to work.  

> It sounds like you're running an old version of opa-envoy. Take a look at the config docs: https://github.com/open-policy-agent/opa-envoy-plugin#configuration

Not sure. The container image in my opa plugin for Istio, as listed in [quick_start.yaml](https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/examples/istio/quick_start.yaml), is "- image: openpolicyagent/opa:0.24.0". Note the version is same 0.24.0 as in the opa-envoy-plugin configuration. 

I do have to use Istio v1.6.13 (< 1.7) due to the health check issue that I had stumbled upon in #2831

thx, KB

**Comment by kyle-burnette** [comment]
I did some testing with my OPA envoy plugin for Istio and it seems that the input.parse_path is being set that can be used from a policy. 
Closing this issue. thanks for your help.

KB
