### ISSUE TITLE
Question on data in bundles

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#2945]
Still a novice with OPA so a basic question. I wanted to understand how exactly to structure & package the **data** within a bundle. 

So far I have managed to package a policy within a bundle and have OPA use it successfully. There was a single policy file under this folder hierarchy: bundles/istio/authz/opa-policy-bundle.tar.gz. Note that the actual tar contents were like this:

>     bundles/
>     bundles/istio/
>     bundles/istio/authz/
>     bundles/istio/authz/policy.rego
 
I am looking to include some data in my bundle. Specifically, I wanted to mimic the data provided in the "ABAC" example in [Rego playground](https://play.openpolicyagent.org/p/AfIqMbfruj#L7) consisting of user_attributes and pet_attributes. Can I just copy the whole data section verbatim and place it in a file with an json extension? 

Importantly, should the 'data.json' file reside alongside the policy.rego file in bundles/istio/authz/ folder?  If not, what folder hierarchy should one be using if I want to use the exact same ABAC example policy in Rego playground?

I have the same other question about name of the package. The example has it as "app.abac". Can I simply change it to istio.authz since I plan to use OPA plugin for Istio? 

As indicated this is a question and not a bug report so not including expected and actual behavior and OPA version etc. 

thanks for any guidance.
KB

**Comment by ashutosh-narkar** [comment]
You could put the entire attribute data in file named `data.json` and include it at the root of the bundle or in a directory as shown in [this](https://www.openpolicyagent.org/docs/latest/management/#bundle-file-format) example. Depending on where you place the data file in the bundle will decide how you can access it from the policy. 

>I have the same other question about name of the package. The example has it as "app.abac". Can I simply change it to istio.authz since I plan to use OPA plugin for Istio?

If you are using this [quick_start.yaml](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/quick_start.yaml) then yes.

**Comment by kyle-burnette** [comment]
Thanks! After placing the data.json at the root of the bundle it worked fine. 

However I have some more questions & a possible issue that I open a separate ticket for. 

rgds
KB
