### ISSUE TITLE
OPA-envoy plugin for Istio authorization question

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#2953]
I have two questions with one being a potential issue. 

1. Authorization:
I have a simple made up policy that either allows or denies access based on the value of an attribute associated with an element in the request path. Specifically, it allows an API version to be accessed only if it is designated as being "stable". Attached find the policy file and data.json hosting the API attributes.
[policy.rego.txt](https://github.com/open-policy-agent/opa/files/5599425/policy.rego.txt)
[data.json.txt](https://github.com/open-policy-agent/opa/files/5599426/data.json.txt)

The policy is taking effect and works for all rules except for this one below. 
```
# Allow anyone to access API so long as the version is stable.
allow {
  is_token_valid
  some version
  http_request.method == "GET"
  input.parsed_path = ["api", version, "products"]
  data.api_attributes[version].stable == true
}
```
The api_attributes have API version v1 to be stable and v2 to be not stable.  Note that in my sample app deployment, the path "/api/v2/products" do not exist. So there is no expectation that attempting to access it to succeed. However it is the error why it does not or should not succeed that I am after.

## Expected Behavior
Per the above "allow" block in the policy and that the v2's stable is set to false, I would have expected a request with ALICE_TOKEN (guest role) for "api/v2/products" to get denied with a 403 error. Note that the policy allows tokens with admin role to access any API. It also allows requests with ALICE_TOKEN to access /api/v1/products - as expected.

## Actual Behavior
But I get a '404 - not found" error. I am curious as I would have thought the request should have got denied first and should not even be reaching the target app which would return a 404. Does that mean the request is being allowed by OPA? How?

## Steps to Reproduce the Problem
Install Istio v1.6.13, install opa-envoy plugin v 0.24.0 per the [instructions](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio) for Istio, enable istio and opa-istio injection, install the Istio sample bookinfo app. Use the policy + data in attached files above. 
Attempt accessing (curl) the product page api at http://external-ip:port/api/v2/products with ALICE_TOKEN available at [envoy-authorization](https://www.openpolicyagent.org/docs/latest/envoy-authorization/). 

2. Logs do not have any decision entries. 
I wanted to check how OPA was evaluating the various policies/rules where it seems to be allowing access in above case. But opa-istio log contain no decision_id entries at all. Logs for opa's admission controller also do not have anything. Neither do istio-proxy logs have any entries listing access attempts to /api/v[1|2]/products. 
I know opa-istio do or is supposed to have decision_id log entries based on what i have seen in the past. I don't know if anything is wrong with my setup.

thanks
KB

**Comment by ashutosh-narkar** [comment]
OPA's decision logging is set in the config [here](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/quick_start.yaml#L382) so I would have expected OPA to log the input that it gets and the decision it generates. 

More importantly have you unit tested your policy ? We recommend [unit testing ](https://www.openpolicyagent.org/docs/latest/policy-testing/) the policy before running it in the system. It helps with the debugging. Here's an example https://play.openpolicyagent.org/p/CUv2bKJlUC.

**Comment by kyle-burnette** [comment]
You are right. I updated the above playground instance to add other elements of my policy just to make sure that they were not influencing the policy evaluation to allow access. The complete policy is evaluating correctly in the playground - denies when attempting to access /api/v2/products. 

Will figure out what is happening in my deployment once I manage to get the logs. 

thanks
KB

**Comment by kyle-burnette** [comment]
After looking at opa-istio logs, it looks like the request is not even reaching OPA and is being intercepted and processed by Istio proxy (istio-envoy). It seems to make a determination whether the path exists before consulting OPA. Perhaps thats how it behaves but curious why and how it figures whether a resource exists w/o first actually accessing it (which the application or target would know best). And accessing it first, w/o authorization, does not look right. I will check with Istio folks. 

> GET /api/v2/products HTTP/1.1
> Host: 52.162.3.99
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJZbTlpIiwiaXNzIjoidGVzdGluZ0BzZWN1cmUuaXN0aW8uaW8iLCJuYmYiOjE2MDQ5NDU5MzYsImV4cCI6NDc1ODU0NTkzNn0.in4vYOXrj2kBKtSshuU-5BwGB8QcFXLbOtl5nbdaq3l0GuFs7m_3_VhTjFSrxUzuT7NlJaaUYaxNAhiSMpajoH4UITrGE3jgN7Xki3rqnNcqXGRB6FEbmGW2dvlopM2uIzIpi1l369-q_N1s_Zf7e3ZU7emNCMurmjbJWuxa7CkHQyOZSByrMlwLDjU8wSg7-wqtpIJaqzPEhH6B3jyvqnHscDJ48yQgGH0Hpu-4Ow5bWZopGeesKvX57JkEYCEFUvohx-6-GEKu1U9larcuaalbZIKb-RdA62JPfi-9OB_b7eC-NCbFjUkAUFfABx2A2bwKOmp37sopWus0goT4OA
>
< HTTP/1.1 404 Not Found
< date: Mon, 30 Nov 2020 19:25:31 GMT
< server: istio-envoy
< content-length: 0
<  

regards, KB

**Comment by ashutosh-narkar** [comment]
That does not sound right. Istio-proxy should consult OPA if the `EnvoyFilter` is configured correctly. One thing to check would be the Envoy configuration, specifically the ext-authz filter config.

**Comment by jsane-vp** [comment]
Here is how that section looks like in my spec. It came from [quick_start.yaml](https://raw.githubusercontent.com/open-policy-agent/opa-istio-plugin/master/examples/istio/quick_start.yaml). I just changed the opa-istio-config ConfigMap to have it pull bundles from my server. I can attach the complete yaml if you prefer. 
Strangely it works fine when I access paths that exist in the app - enforces all the different policy conditions correctly. 

```
############################################################
# Envoy External Authorization filter that will query OPA.
############################################################
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz"
            status_on_error:
              code: ServiceUnavailable
            with_request_body:
              max_request_bytes: 8192
              allow_partial_message: true
            grpc_service:
              # NOTE(tsandall): when this was tested with the envoy_grpc client the gRPC
              # server was receiving check requests over HTTP 1.1. The gRPC server in
              # OPA-Istio would immediately close the connection and log that a bogus
              # preamble was sent by the client (it expected HTTP 2). Switching to the
              # google_grpc client resolved this issue.
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz"
```

I noticed that the latest version of quick_start.yaml has the type updated to v3 under [typed_config](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/quick_start.yaml#L25-26). Not sure if that should/would matter. I have been using quick_start.yaml that I had saved from a couple of weeks ago which has that line as.
 "@type": "type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz"

**Comment by ashutosh-narkar** [comment]
We have updated the plugin to support Envoy's v3 xDS API and hence the change in the `quick_start.yaml`. There isn't a release version of the plugin with this change yet.

**Comment by kyle-burnette** [comment]
Am attaching the complete yaml. Do the ext-authz filter config look correct? I did not change it from what was in the quick_start.yaml.  
[qs_policy_bundle_polling.yaml.txt](https://github.com/open-policy-agent/opa/files/5619605/qs_policy_bundle_polling.yaml.txt)

From your response it looks like I can/should continue Envoy's v2 version of xDS API.  
Like I said it works properly so long as I access paths that exist. If the ext-authz filter is correct then what could be causing this?

**Comment by ashutosh-narkar** [comment]
You should check the actual Envoy config that is used by Istio-proxy. It may help debug your issue. See [this](https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/#deep-dive-into-envoy-configuration) for more information.

**Comment by kyle-burnette** [comment]
I captured the various configs per the above but I don't know what I am looking for and/or is anything is wrong with the envoy config. Some of the configs look slightly different from what the "[Deep dive into Envoy configuration](https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/#deep-dive-into-envoy-configuration)" section shows but not sure if that is the problem. 
Sorry for the bother but let me know if this is something I should follow up with Istio. 

Am attaching the various configurations.

istioctl proxy-config cluster -n istio-system istio-ingressgateway-xxx output: 
[istio-proxy-config.log](https://github.com/open-policy-agent/opa/files/5624098/istio-proxy-config.log)

1. istioctl proxy-config listeners productpage-v1-xxx output:
[productpage-pod-listeners.log](https://github.com/open-policy-agent/opa/files/5624095/productpage-pod-listeners.log)

2. istioctl proxy-config listeners productpage-v1-xxx --port 15001 -o json output:
[productpage-pod-15001-listener.json.txt](https://github.com/open-policy-agent/opa/files/5624102/productpage-pod-15001-listener.json.txt)

3. istioctl proxy-config listeners productpage-v1-xxx -o json --address 0.0.0.0 --port 9080 output: 
[productpage-pod-9080-listener.json.txt](https://github.com/open-policy-agent/opa/files/5624099/productpage-pod-9080-listener.json.txt)

4. istioctl proxy-config routes productpage-v1-xxxx --name 9080 -o json output:
[productpage-pod-9080-routes.json.txt](https://github.com/open-policy-agent/opa/files/5624100/productpage-pod-9080-routes.json.txt)
 
5. istioctl proxy-config cluster productpage-v1-xxx--fqdn reviews.default.svc.cluster.local -o json output: 
[productpage-pod-reviews-cluster.json.txt](https://github.com/open-policy-agent/opa/files/5624096/productpage-pod-reviews-cluster.json.txt)

6. istioctl proxy-config endpoints productpage-v1-xxx--cluster "outbound|9080||reviews.default.svc.cluster.local" output: 
[productpage-pod-reviews-cluster-endpoints.log](https://github.com/open-policy-agent/opa/files/5624097/productpage-pod-reviews-cluster-endpoints.log)

thx

**Comment by ashutosh-narkar** [comment]
From the logs you've sent, I don't see envoy's external authz filter (`envoy.ext_authz`) configured which is responsible for sending the request to OPA. If you have a working setup the `envoy.ext_authz` should be seen in the Envoy config generated by Istio.

**Comment by kyle-burnette** [comment]
Am confused. My setup is definitely working. It is correctly enforcing the policies when accessing the sample bookinfo. And I see the decsion_id entries in opa-istio logs. I will open a ticket with Istio since their proxy-config is not showing envoy.ext_authz configuration and I don't know why or how to get it. 
I wonder if this is to do with me using Istio version 1.6.13 and not the latest version. I will try setting up using 1.7.x (w/o testing the app since it does not work due to the health check issue) but see if that shows envoy.ext_authz configuration.

**Comment by kyle-burnette** [comment]
Not sure this is related but I also noticed the following. 

When attempting to access any of the protected paths w/o providing a valid authorization token then it (istio-envoy) returns a "503 Service unavailable" error when I would have expected a 403 since all policy rules require a valid token. 
I guess it is because opa is returning an error as it fails to parse the token and not a clear "result": true|false.

> {"decision_id":"f7622199-4439-47c1-aff5-fb3233069495","error":{"code":"eval_builtin_error","location":{"col":28,"file":"bundles/istio/authz/policy.rego","row":19},"message":"io.jwt.decode_verify: encoded JWT had no period separators"},"input":{"attributes":{"destination":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":9080},"address":"10.244.1.7"}}},"principal":"spiffe://cluster.local/ns/default/sa/bookinfo-productpage"},"metadata_context":{},"request":{"http":{"headers":{":authority":"52.162.3.99",":method":"GET",":path":"/productpage","accept":"*/*","authorization":"Bearer TOKEN","content-length":"0","user-agent":"curl/7.58.0","x-b3-sampled":"0","x-b3-spanid":"01683df8c2832bb9","x-b3-traceid":"aa23888f748e576a01683df8c2832bb9","x-envoy-internal":"true","x-forwarded-client-cert":"By=spiffe://cluster.local/ns/default/sa/bookinfo-productpage;Hash=ed8913b5be5758a6dbd238b835028682c63b4ea0f19438d43aa64d03559061b5;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account","x-forwarded-for":"10.240.0.4","x-forwarded-proto":"http","x-request-id":"ac135389-25c5-4bf9-be91-9ea6b7cf7483"},"host":"52.162.3.99","id":"11899359201003885500","method":"GET","path":"/productpage","protocol":"HTTP/1.1"},"time":{"nanos":168360000,"seconds":1606866352}},"source":{"address":{"Address":{"SocketAddress":{"PortSpecifier":{"PortValue":38096},"address":"10.244.0.6"}}},"principal":"spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"}},"parsed_body":null,"parsed_path":["productpage"],"parsed_query":{},"truncated_body":false},"labels":{"id":"73fd0311-4887-4109-915f-a485a47f7fa3","version":"0.24.0-envoy"},"level":"info","metrics":{"timer_rego_query_eval_ns":428020,"timer_server_handler_ns":729535},"msg":"Decision Log","path":"istio/authz/allow","requested_by":"","time":"2020-12-01T23:45:52Z","timestamp":"2020-12-01T23:45:52.170024617Z","type":"openpolicyagent.org/decision_logs"}

If I do not send any Authorization header at all then it correctly returns "403 - forbidden".

**Comment by ashutosh-narkar** [comment]
This is a different issue to the previous one. At least in this case your request reaches OPA. It would be helpful to see the OPA logs for the above. I think OPA would return an error and the `status_on_error` is set to `503`. Is that the case ?

**Comment by kyle-burnette** [comment]
No I do not see that. Anyway lets disregard this one as it is reaching OPA. 

I will see what Istio (after trying with 1.7 version) have to say on the original/previous issue as I suspect it might bite someone even when the paths exist but envoy might not send it to OPA (az bypass will be serious).

**Comment by kyle-burnette** [comment]
I tried setting it up with latest version of Istion v1.8.0. But the sample book info deployments would not succeed - kept crashing. 
I anyway tried looking thru the proxy config and still do not see any configuration for ext_authz anywhere. 
I will open a ticket with Istio and see where it goes.

**Comment by ashutosh-narkar** [comment]
>I tried setting it up with latest version of Istio v1.8.0. But the sample book info deployments would not succeed - kept crashing.

This may be due to the same health-check issue we saw in Istio v1.7.x. If you update the policy to allow those health-check requests, the plugin will work with Istio v1.8.0. [Here's](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/quick_start.yaml#L388) a policy example. I was able to get the plugin (`version: openpolicyagent/opa:0.24.0-istio-14`) to work with Istio v1.8.0.

**Comment by kyle-burnette** [comment]
Actually yesterday I had used the latest version of quick_start.yaml which had the allow rule for health-check request. 
Anyway I created a new pristine cluster, installed istio 1.8.0, opa with the latest quick-start.yaml,  enabled injection of both istio proxy and opa-istio, installed the sample bookinfo from under istio v1.8.0. 

It still keeps crashing. I collected logs from all containers in productpage-xxxx pod and opa admission controller but do not see any obvious error or issue that could be causing except for the last two three lines in the opa-istio log (this is all it is).

> {"addrs":["localhost:8181"],"diagnostic-addrs":["0.0.0.0:8282"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2020-12-03T17:09:22Z"}
> {"level":"info","msg":"Starting decision logger.","plugin":"decision_logs","time":"2020-12-03T17:09:22Z"}
> {"addr":":9191","dry-run":false,"enable-reflection":false,"level":"info","msg":"Starting gRPC server.","path":"istio/authz/allow","query":"","time":"2020-12-03T17:09:22Z"}
> {"level":"info","msg":"Shutting down...","time":"2020-12-03T17:09:52Z"}
> {"level":"info","msg":"Server shutdown.","time":"2020-12-03T17:09:52Z"}
> {"level":"info","msg":"Stopping decision logger.","plugin":"decision_logs","time":"2020-12-03T17:09:52Z"}
> 

Istio proxy indicates no errors. 

thx, KB

**Comment by ashutosh-narkar** [comment]
What version of `opa-istio` are you using ?

**Comment by kyle-burnette** [comment]
From the quick_start.yaml I am using:

 "image": "openpolicyagent/opa:0.24.0-istio",
        - image: openpolicyagent/opa:0.24.0

**Comment by ashutosh-narkar** [comment]
Try `openpolicyagent/opa:0.24.0-istio-14` or `openpolicyagent/opa:latest-istio`. I assume you are following the steps from [this](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/README.md#quick-start) tutorial.

**Comment by kyle-burnette** [comment]
That did the trick! And sorry I noticed you had mentioned to use the latest version of opa earlier but I seem to have overlooked :-( 
Yes I have been following steps in the [tutorial](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/README.md#quick-start). 

With the app running, I attempted accessing /api/v2/products but continue to get 404 instead of 403. 
Those requests are not getting forwarded to OPA like before; no entries corresponding to those requests in opa-istio log.

I am attaching the ext authz config for productpage service. 
[envoy-ext_authz-config.json.txt](https://github.com/open-policy-agent/opa/files/5638802/envoy-ext_authz-config.json.txt)

 thanks

**Comment by ashutosh-narkar** [comment]
Great that it works now ! Regarding the `404` I think one possibility is that there are other filters in the chain before the `ext_authz` which may be returning that. I would check with Istio folks to confirm that behavior.

**Comment by munjalpatel** [comment]
@ashutosh-narkar I am also trying the `opa-istio` example at []

With `openpolicyagent/opa:0.26.0-istio` I still get the same exact logs as described by @kyle-burnette and the container keeps restarting.

```json
{"addrs":["localhost:8181"],"diagnostic-addrs":["0.0.0.0:8282"],"level":"info","msg":"Initializing server.","time":"2021-02-16T09:00:07Z"}
2/16/2021 1:00:07 AM {"level":"info","msg":"Starting decision logger.","plugin":"decision_logs","time":"2021-02-16T09:00:07Z"}
2/16/2021 1:00:07 AM {"addr":":9191","dry-run":false,"enable-reflection":false,"level":"info","msg":"Starting gRPC server.","path":"istio/authz/allow","query":"","time":"2021-02-16T09:00:07Z"}
2/16/2021 1:00:36 AM {"level":"info","msg":"Shutting down...","time":"2021-02-16T09:00:36Z"}
2/16/2021 1:00:36 AM {"level":"info","msg":"Server shutdown.","time":"2021-02-16T09:00:36Z"}
2/16/2021 1:00:36 AM {"level":"info","msg":"Stopping decision logger.","plugin":"decision_logs","time":"2021-02-16T09:00:36Z"}
```

I have also tried to simplify the policy like this but doesn't seem to work:
```rego
package istio.authz

import input.attributes.request.http as http_request
import input.parsed_path

# default allow = false
default allow = true

# allow {
# 	parsed_path[0] == "health"
# 	http_request.method == "GET"
# }

```

Any ideas on how to resolve this?

**Comment by ashutosh-narkar** [comment]
@munjalpatel I believe Stephan's helping you out in https://github.com/open-policy-agent/opa/issues/3154.  Thanks.

**Comment by srenatus** [comment]
I don't this this discussion is still alive -- closing. Please feel free to reopen, or add a new issue, if there are remaining problems.
