### ISSUE TITLE
Date-time builtins

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#296]
Having builtins for manipulating dates and times would be valuable.  Probably the easiest thing to do is find an appropriate date-time library in Go and design the builtins around that.  So instead of concrete functions, here is a list of possible functionality.

- Date less-than/greater-than/leq/geq
- Date addition/subtraction
- Time less-than/greater-than/leq/geq
- Time addition/subtraction
- Datetime less-than/greater-than/leq/geq
- Datetime addition/subtraction
- Conversion of date-time to integer and from integer to date-time

**Comment by tsandall** [comment]
With #341 OPA supports this functionality so I'm going to close this. If we come across a reason to support a date-time type or more built-ins we can open additional issues.
