### ISSUE TITLE
Azure authentication using Shared Key or Shared Access Signature

### ISSUE THREAD

**Issue by KumarReddyPingili** [open-policy-agent/opa#2964]
## Added configurations to connect with azure storage, we have a secret key to communicate with storage but do not know how to pass that key in configuration file. As we can see only credentials -> bearer -> token.
In our case we won't have any tokens but we have a secret key or connection string either of these we can connect to storage.
Sample configuration file:

services:
  acmecorp:
    url: https://<<hostname>>/storage/
    response_header_timeout_seconds: 5
	credentials:
      bearer:
        token: "<<SECRET KEY>>"

bundles:
  authz:
    service: acmecorp
    resource: <<bundle name>>

    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120

## Additional Info

We can able to download the bundle when we use public azure storage account only issue with private storage account particularly do not know where to pass secret key in opa configuration file of private storage .

**Comment by anderseknert** [comment]
The latest current release (v0.24.0) of OPA supports bearer tokens, client certificates or AWS signatures for [authentication against service endpoints](https://www.openpolicyagent.org/docs/latest/configuration/#services). The upcoming v0.25.0 release will see both OAuth2 and GCP access/identity tokens added to that list. Support for Azure storage is not yet there, presumably because it's not been requested before, or at least no one stepped up to add it. 

From looking at the docs on how to [create signature strings](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key) for auth it's a fair bit more complex than what the current bearer token auth option would allow for.

**Comment by KumarReddyPingili** [comment]
Thank you for your quick response @anderseknert , and below are the questions I have now. 

1. **Bearer tokens :** Can we generate the token up on each request from configuration file. (Periodically OPA will make a call to service,each time can we pass different token?)
 
2. In V 0.25.0 version as you mentioned **oauth2** will be added to list. will there be any way to pass access token dynamically then where/how do we generate tokens and passing to configuration file.

As of now I know only environment variables which would be replace with ${KEY-NAME} this will be passed when we are initializing the opa server. I doubt we can't use this environment variables for passing dynamic access tokens?

**Comment by anderseknert** [comment]
1. Yes. Given you provide a `services[_].credentials.bearer.token_path`, OPA will re-read the token on each request sent to the remote service, so I guess you could run another process to generate the actual token stored there.
2. It would be somewhat hackish, but you could setup a service that emulated the OAuth2 token endpoint (accepting client credentials) and returned a generated token in return. 

And you are right about env vars not being good for this use case, as they are populated only when OPA starts up.

**Comment by johanneslarsson** [comment]
> 1. Yes. Given you provide a `services[_].credentials.bearer.token_path`, OPA will re-read the token on each request sent to the remote service, so I guess you could run another process to generate the actual token stored there.

Are you sure about this? I doesn't work for me, I have restart my OPA for it to re-read the token?
`
opa version
Version: 0.25.0-dev
Build Commit: 039d3b2
Build Timestamp: 2020-11-17T22:12:28Z
Build Hostname: b30cf3114367
Go Version: go1.14.9
WebAssembly: unavailable

`

**Comment by anderseknert** [comment]
That's a bug then - question is whether it is in the implementation or in [the documentation](https://www.openpolicyagent.org/docs/latest/configuration/#bearer-token) :)

I think the docs state the intention here though and this should actually work. Would you want to open a ticket?

**Comment by johanneslarsson** [comment]
> That's a bug then - question is whether it is in the implementation or in [the documentation](https://www.openpolicyagent.org/docs/latest/configuration/#bearer-token) :)
> 
> I think the docs state the intention here though and this should actually work. Would you want to open a ticket?

Never mind I was using a different flag (token), token_path works as expected.

**Comment by anderseknert** [comment]
Revisiting this for another project, and OAuth2 Client Credentials _does_ work for authenticating requests against Azure Storage. Example config would look something like this:

```yaml
services:
  blob:
    url: https://my-storage-account.blob.core.windows.net
    headers:
      # This header _must_ be present in all authenticated requests
      x-ms-version: "2020-04-08"
    credentials:
      oauth2:
        token_url: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
        client_id: "${CLIENT_ID}"
        client_secret: "${CLIENT_SECRET}"
        scopes:
          - https://storage.azure.com/.default

bundles:
  authz:
    service: blob
    resource: my-container/bundle.tar.gz
```

First release with [this fix](https://github.com/open-policy-agent/opa/pull/3374) will also allow the OAuth2 Client Credentials JWT Authentication option. See [Authorize access to blobs and queues using Azure Active Directory](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad) for details.

**Comment by anderseknert** [comment]
Given how the Microsoft [docs on the topic](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad) states..

> Authorizing requests against Azure Storage with Azure AD provides superior security and ease of use over Shared Key authorization. Microsoft recommends using Azure AD authorization with your blob and queue applications when possible to minimize potential security vulnerabilities inherent in Shared Key.

..and we now support the recommended Azure AD authorization, there aren't many incentives to add support for inferior methods. If someone can 1) motivate why those are needed and 2) is willing to do the work for adding these, we can revisit this issue. Until that happens I'll close this issue.
