### ISSUE TITLE
Possible memory leak involving topdown/http?

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2978]
## Expected Behavior

Using the http built-in with cache enabled should completely free up memory after cache expiration.

## Actual Behavior

We've been running OPA in production the last few days and it seems like there might be a memory leak involving the HTTP built-in.

![possible_leak](https://user-images.githubusercontent.com/1852172/101182698-aa9eb500-360b-11eb-9f1a-cafdf1473d93.png)

![Screen Shot 2020-12-04 at 8 35 45 AM](https://user-images.githubusercontent.com/1852172/101182737-bd18ee80-360b-11eb-8d94-a0be8faefca7.png)

I found a few spots where I think [an HTTPResponse isn't being closed properly](https://github.com/godaddy/opa/commit/42d618d3aa7b8e6b1a00176bcf72edcef4092628), but after running it overnight with those changes it still seems to be leaking.  I'm going to keep digging, but I know very little about how OPA evaluates and caches things, so I could use some help finding the root cause.

## Steps to Reproduce the Problem

* OPA version: 0.25.0-dev, [forked with a few tweaks](https://github.com/godaddy/opa/tree/main-fork), but nothing in the path of this leak as far as I can tell.

**Comment by tsandall** [comment]
@ashutosh-narkar can you take a look at this?

**Comment by ashutosh-narkar** [comment]
@gshively11 Can you help me understand the usage pattern for the `http.send` builtin ? 

Is it the case where you are running OPA in server mode, it gets a request which results in evaluating a policy which uses `http.send` and then you see the memory increase over time w/o any new requests while OPA is running ? 

OR is it case where we have multiple requests to OPA while its running and each of these requests results in evaluating a policy with `http.send` ? The HTTP request itself executed by the `http.send` builtin may vary with each eval run.

**Comment by gshively11** [comment]
We are running OPA in server mode, with `?explain=notes&pretty`, and are receiving many requests to `/v1/data/somepolicy` that results in policy with `http.send` (with cache enabled) initiating requests to one of our APIs that returns some blob of data.  There would be many unique requests generated by `http.send`, so I would expect the cache size to grow initially, but the `max-age` is only 5 minutes, so it should then plateau at some point, not continue growing as it does.

**Comment by ashutosh-narkar** [comment]
The underlying cache replacement algorithm is FIFO. By default, there is no size limit set on the underlying cache. You could change that by using the [max_size_bytes](https://www.openpolicyagent.org/docs/latest/configuration/#caching) parameter and then OPA will drop old items from the cache if this limit is exceeded.

**Comment by gshively11** [comment]
But if `max-age` is set on the API responses, shouldn't the cache be clearing those old items out when they expire?

**Comment by ashutosh-narkar** [comment]
The way the cache works is if a new request is already cached, OPA will then check if the cached response is stale is not. If it's stale, the cached entry is removed and then the new response from the server will be cached. So the size of the cache keeps growing unless you cap it using `max_size_bytes`. There currently isn't a separate process that continuously checks the items in the cache removes them if they are stale.

**Comment by gshively11** [comment]
Gotcha.  Ok, let me give `max_size_bytes` a shot, thanks!

**Comment by gshively11** [comment]
That doesn't appear to have worked.  This is the config in our discovery bundle:

```
"caching": {
  "inter_query_builtin_cache": {
    "max_size_bytes": 64000000
  }
}
```

Which should cap the cache at 64mb.  I have our container mem limit set to 512mb.  It still reached the 512mb limit and crashed overnight.  I didn't snag a snapshot of the heap when it was near max this time around, I'll try to get that again tonight.

**Comment by gshively11** [comment]
Here is the heap when our container stats are showing it at around 75% of our 512mb mem limit.  As you can see, `top` is showing the process consuming around 379mb, but the pprof heap is showing around 129mb total.  Not sure what's up with that.

![Screen Shot 2020-12-09 at 3 14 41 PM](https://user-images.githubusercontent.com/1852172/101695135-61969880-3a31-11eb-90c4-1b2f3dfdeb39.png)
![profile002](https://user-images.githubusercontent.com/1852172/101695242-7f63fd80-3a31-11eb-8570-9ce934c93b8f.png)

If I look at the same code running in our test environment (which barely receives any traffic), it doesn't have unbounded memory growth, so it seems likely that the leak in prod has something to do with policy evaluation or http.send.

I'm going to try to get one more heap snapshot right when it's close to the 100% limit, should be later this evening sometime.

**Comment by gshively11** [comment]
And in case a comparison is helpful, here's a heap snapshot from our test environment for an instance that's been running for 48 steadily at 25% of mem limit (receiving very little traffic)

![profile003](https://user-images.githubusercontent.com/1852172/101696797-e4205780-3a33-11eb-8bfe-eff704043d80.png)

**Comment by ashutosh-narkar** [comment]
Thanks for providing these metrics. If you have any other metrics, logs and scripts that will help to reproduce the issue, it would be great if you could share those as well. Also can you also share the policy ?

**Comment by gshively11** [comment]
I can't share the exact policy, it's somewhat sensitive, and it's using some custom built-in functions, plugins, and APIs.  Let me try to get a stripped down version I can send you.

Are there any other pprof tricks I can use to give you more useful information?

**Comment by ashutosh-narkar** [comment]
If you haven't tried this already, you could start OPA like `opa run -s --pprof` and then look at the heap profile using `go tool pprof localhost:8181/debug/pprof/heap`.

**Comment by gshively11** [comment]
That's what I used to generate the heap images I've already sent you :grin:

**Comment by gshively11** [comment]
Also, we can't really replicate this locally very well, because we don't see the leak without a ton of production traffic (~3-5k unique users over the course of an 18-24hr period)

**Comment by gshively11** [comment]
Here's a reproducible example of the leak: https://github.com/gshively11/opa-mem-leak. Let me know if you have any issues getting it to work.

**Comment by ashutosh-narkar** [comment]
Thanks @gshively11 ! I'll try to reproduce the issue this week.

**Comment by gshively11** [comment]
Actually, I think the problem might be that the InterQueryCache never actually gets the Config (and thereby the max_size_bytes) when used by the http.send builtin.  I'm out of time to dig farther today, but I think I can confirm that tomorrow morning.

**Comment by gshively11** [comment]
Ah...the cache config doesn't work with discovery because it never receives config updates from a `Reconfigure`.

**Comment by gshively11** [comment]
Ok, there's definitely still a leak even with the inter-query cache set at startup.  I'm attaching a progression of full heap snapshots over the course of multiple hours from one of our production instances.  It's configured for a 16mb inter-query cache.  [Here is the exact code we're running in prod](https://github.com/godaddy/opa/tree/main-fork), it has my discovery changes, plus I added what I think are some missing http response closings, but it doesn't seem to have much of an effect.  I really need help from someone who has a better understanding of how the eval process works, because it seems like maybe something is holding onto things there?  It's not just the http.send-related code that grows, but that entire eval loop you can see in the heap snapshots.

[leak.tar.gz](https://github.com/open-policy-agent/opa/files/5712253/leak.tar.gz)

**Comment by ashutosh-narkar** [comment]
I am going to reproduce this with a policy that uses `http.send` similar to what you've shared. In your example code you've embedded OPA as a library and then you're starting in from your script. Is that how you are running OPA in production ? Basically do you run the OPA binary as-is or have you modified it in your setup ?

**Comment by gshively11** [comment]
We are embedding OPA and have a custom cobra command to start the OPA runtime in server mode with some special configuration (stuff like grabbing secrets from AWS, hot-reloading credentials, etc).  I've poured over the code multiple times and I can't see how any of our wrapper code would cause the leak, but I'm sure it's possible.  I'm also going to go back to the reproduction code I provided and try some more digging.

Also, I did notice that the opa process is using a bit more than twice the memory than appears in these heap snapshots (e.g. ~100mb in heap, ~250mb in RSS).  I think I need to tweak the opa pprof server integration to add a method to retrieve active goroutines...because memory outside the heap seems to be leaking too, which means it's probably something in the stack, or native?

Any help you can provide is much appreciated.  This is the last big hurdle keeping us from a bigger rollout of our project.

**Comment by ashutosh-narkar** [comment]
One thing we could do is to periodically print memory usage. You could modify the OPA server as below.  Our underlying cache implementation uses a map and a linked list to keep track of the keys in the map. We'll see if the heap object are garbage collected and memory returned back to OS or it just keeps going up when the cache is updated.

```go
func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}

func PrintMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	// For info on each, see: https://golang.org/pkg/runtime/#MemStats
	fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
	fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
	fmt.Printf("\tNumGC = %v\n", m.NumGC)
}

// Init initializes the server. This function MUST be called before Loop.
func (s *Server) Init(ctx context.Context) (*Server, error) {

	go func() {
		t := time.Tick(time.Second * 5)
		for {
			<-t
			PrintMemUsage()
		}
	}()
```

**Comment by gshively11** [comment]
I'm making some more progress I think.  I created another local reproduction using code and policy that more closely mirrors what we're running in production and I'm seeing different heap behavior (and leaking) compared to what I saw in the reproduction scenario I provided you.  So for now I recommend pausing on trying to reproduce with the code/policy I provided earlier.  I'll see where I get with this new reproduction and get back to you.

**Comment by gshively11** [comment]
Hmmm, I think part of the problem might be that the max bytes specified for the cache config is wayyyy less than the actual memory used from all the refs getting held onto by the cached items.  When running some local tests, I had the cache configured to 500000 (500kb). My item size according to the cache was 298 bytes.  I confirmed that the cache would eventually hit the limit and start pruning old items.  But with a maxed out 500kb cache, I was actually holding onto around 28mb of memory space.  I'm in the process of dropping our production cache limit way down to see if this is the root of the issue.

**Comment by ashutosh-narkar** [comment]
Could it be that the underlying Go structures (maps, linked list etc.) are contributing to the memory held and when we remove an item from the cache, garbage collection is not happening frequently enough and hence memory is not returned to the OS leading to increasing memory usage ? I wonder if we tried to force a garbage collection `debug.FreeOSMemory()`, if we could see better usage numbers. WDYT ?

**Comment by gshively11** [comment]
Success!  I set the cache at `750000` bytes and we plateaued at an RSS of `121828kb` with around `23642kb` held by the http.send builtin.  So it definitely looks like the underlying Go structures of the inter-query cache result in a large chunk of memory being held from garbage collection.  I confirmed that garbage collections are happening frequently, so there shouldn't be a need to trigger it manually.  I think it's just that the AST'd http responses end up being much larger than their raw string size (both of which are held in a cache item).

I'm going to update the documentation for the cache size config to indicate that the actual memory footprint for the cache is significantly larger than the configured size (maybe we can nail down a percentage estimate to include)?

I'm on vacation this week, so I'll update my PR next week.  Thanks again for your help with this!

**Comment by ashutosh-narkar** [comment]
Good find ! The memory usage sounds about right. We've seen there's approximately 20x more memory needed when JSON is loaded into Go data structures.

**Comment by anderseknert** [comment]
This has been fixed, right @gshively11 @ashutosh-narkar ?

**Comment by geekhckr** [comment]
I am still seeing the leak when I use opa-envoy-plugin (using grpc). I have set max_size_bytes to 64mb. Find my config below

```
caching:
        inter_query_builtin_cache:
            max_size_bytes: 64000000
```

![image](https://user-images.githubusercontent.com/11797297/120750506-1793f880-c524-11eb-87e6-be6d980e41e9.png)

**Comment by tsandall** [comment]
@geekhckr what does the memory usage look like over time? The image you've attached shows current heap usage which is sometimes helpful understanding _where_ memory is allocated but it doesn't give any indication about memory usage over time.

**Comment by geekhckr** [comment]
@tsandall over the time it is keep on increasing and not coming down. In one of our performance setup, it has increased to 490mb from 55mb in 2 days with 360 req/sec. We had to disable the cache. In another production setup where we have less load also, it is keep on increasing.

Above attached one is collected in one of my laptop with simulated load using grpcurl, after running load for 2 hours, I have waited for 12 hours and collected heap dump using pprof.

**Comment by tsandall** [comment]
@geekhckr thanks, that's helpful. @ashutosh-narkar sounds like there's something odd going on here... PTAL...

**Comment by geekhckr** [comment]
I have used below command for generating the load. And I am changing cookie intentionally so that each request gets cached. But cache should not grow more than 64mb, because of the max_size_bytes.

```
for i in {0..100000}
do
./grpcurl -plaintext -d "{\"attributes\": {\"request\": {\"http\": { \"method\": \"GET\", \"path\": \"/api/v1/products\", \"headers\": {\"cookie\":\"session_cookie_a=d${i}\"} } } } }" localhost:9191 envoy.service.auth.v2.Authorization/Check
done
```

Below one is the policy I have used
```
package envoy.authz.grpc

import input.attributes.request.http as http_request

default allow = false

allow {
    "test1" == get_groups[0]
}

allow {
    "test1" == "test1"
}

get_groups = groups {
    response := http.send({
        "method": "GET",
        "url": "http://127.0.0.1:9292/userinfo",
        "force_cache": true,
        "force_cache_duration_seconds": 300,
        "headers" : {"Cookie": concat(" ", regex.find_n("session_cookie_(.*?)(;|$)+", http_request.headers["cookie"], -1))}
    })
    groups := response.body.groups
}
```

**Comment by geekhckr** [comment]
Is this leak related to this https://github.com/golang/go/issues/20135 ? I think topdown cache is using golang map.

**Comment by gshively11** [comment]
good find @geekhckr, seems like it does https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go#L86

**Comment by ashutosh-narkar** [comment]
Thanks for the information @geekhckr. We ran a test setup similar to what you reported. We kept it running for more than 2 days. What we noticed is that the allocated bytes (`Alloc`) increase and decrease over time but `Sys` always increases and never goes down. This seems to indicate that Go isn't giving memory back to the OS.

**Comment by gshively11** [comment]
yea, per the issue that @geekhckr linked, it looks like you have to occasionally create a new map and migrate over active items, which is pretty annoying

**Comment by geekhckr** [comment]
@ashutosh-narkar looks like issue is https://github.com/golang/go/issues/37585 and it has been fixed in the golang v1.16 by reverting back to `MADV_DONTNEED` https://go-review.googlesource.com/c/go/+/267100/

Also I have verified this with simple program that populates and removes items from map, at least with golang v1.16, in htop RSS is coming down. For golang v1.15, if I use `GODEBUG=madvdontneed=1` I can see the same behaviour.

I will try this in one of our perf setup with opa-envoy-plugin and let you know the result.

**Comment by ashutosh-narkar** [comment]
Good to know @geekhckr. Let us know how it works out.

**Comment by geekhckr** [comment]
We have tested the workaround in our perf setup, and it is working. I mean RSS is coming down, previously, it used to continuously increase.

**Comment by ashutosh-narkar** [comment]
@geekhckr that's great ! Did you use `GODEBUG=madvdontneed=1` as your workaround or something else ?

**Comment by geekhckr** [comment]
Yes I am using `GODEBUG=madvdontneed=1` as workaround. If opa-envoy-plugin is build with go v1.16, then we don't require to use this. Currently it is being built with v1.15, that's why we have to use this workaround.

**Comment by ashutosh-narkar** [comment]
@geekhckr we've update the OPA-Envoy plugin to build with Go 1.16.5. See [here](https://github.com/open-policy-agent/opa-envoy-plugin/pull/266) for details. We'll release a new version of the plugin soon.

**Comment by ashutosh-narkar** [comment]
OPA-Envoy plugin [v0.29.4-envoy-3](https://github.com/open-policy-agent/opa-envoy-plugin/releases/tag/v0.29.4-envoy-3) is built with Go 1.16.5.

**Comment by tsandall** [comment]
Can we close this now?

**Comment by gshively11** [comment]
I say yes, with the caveat that I haven't fully tested the original fix @ashutosh-narkar implemented for the http cache in production.  We actually removed our http calls in rego in favor of another solution, so I don't have a way to test the fix at scale.

So, closing for now seems reasonable, and we can always re-open if we uncover another issue.

**Comment by geekhckr** [comment]
FYI, we have v0.29.4-envoy-3, but still I can see the memory leak. Also in v0.28.0 with `GODEBUG=madvdontneed=1`, we were observing memory leak, but it is slow. So, we have stopped using the caching feature for now and making the requests every time.
I think it is better to investigate this issue.

**Comment by ashutosh-narkar** [comment]
@geekhckr when you refer to a memory leak, are you noticing both the allocated bytes and Sys usage going up always or is it only the Sys memory. From the experiments we've done in the past we've noticed the latter. Also how much memory have you assigned to the OPA container and what's the cache size limit?

**Comment by geekhckr** [comment]
With `GODEBUG=madvdontneed=1` sys memory is not growing constantly, it is periodically reclaiming the memory.
I have given my container 2 GB, and with v0.29.4-envoy-3 it crashed within 7 hours, but with v0.28.0 and `GODEBUG=madvdontneed=1` we were able to run it for more than week, but RSS is constantly growing.

**Comment by geekhckr** [comment]
Cache limit is 64mb. 
Also I have observed some CA cert store related changes as well in the v0.29.x.
