### ISSUE TITLE
Can we fetch data and cache in a variable for OPA policy

### ISSUE THREAD

**Issue by dinesh71** [open-policy-agent/opa#2982]
Hi Team,

I'm looking to write a policy which it should get a value on the first hit (by calling external API) and cache  the value for the subsequent opa requests.

Can we achieve this or in any alternate manner

Thanks

**Comment by anderseknert** [comment]
Yes - see the `cache`, `force_cache` and `force_cache_duration` [options for the `http.send` built-in.](https://www.openpolicyagent.org/docs/latest/policy-reference/#http)

**Comment by tsandall** [comment]
Closing this because there's not much else to add.
