### ISSUE TITLE
OPA is returning 403 if URL string do have line feed charecter ( %0A ) embeded into it

### ISSUE THREAD

**Issue by ajoysinha** [open-policy-agent/opa#3004]
OPA istio implementation is failing for a specific use case. If URL is having a "line feed" character embedded into it as below it is returning response code as 403.

Suppose my URL is as below.

Case 1: **Working** Working fine for following URL
<<ID>>.ap-south-1.elb.amazonaws.com/api/ping 

Case 2: **Error** Returning 403 unauthorized error for following URL
<<ID>>.ap-south-1.elb.amazonaws.com/api/ping?**query=%0A**

I have shorten the URL for understanding purpose. but I have found that it failed for %0A [ Line feed ] character only.

Note : 
We got the query parameter derived out of another process. hence expecting to have the line feed character embedded. 

Do we have any way to escape this kind of special character in OPA implementation approach. Need suggestion.

**Comment by ajoysinha** [comment]
Any solution for this issue to handle special character in URL during OPA integration .
Platform : 
EKS : 1.16
istio : 1.6.11
OPA : 0.24

**Comment by srenatus** [comment]
OK, so I've briefly looked at that. The logic OPA uses to parse the URL is piggy-backing on golang's stdlib (`net/url`), which in turn forbids control characters in the query (https://github.com/golang/go/commit/829c5df58694b3345cb5ea41206783c8ccf5c3ca).

**However**, the plugin is unescaping the provided path before feeding it into the golang function: https://github.com/open-policy-agent/opa-envoy-plugin/blob/948fe7867579f034c23b3d12a900927b4af8c409/internal/internal.go#L696-L704 That causes the properly-urlencoded path to become an invalid control character.

I'll try to dig up why we've done that this way, and hopefully come up with a PR soon 😃

**Comment by srenatus** [comment]
So, two more things:

I hadn't been explicit about this before: the error in parsing causes the plugin to return 403. So, this is the "fail closed" case.

That aside, this issue seems to have been presented before, here: https://github.com/open-policy-agent/opa-envoy-plugin/pull/175. I think we should try to revive that PR.
