### ISSUE TITLE
OPA Build 'bundle.tar.gz' has 2 'policy.wasm' since 0.25.0

### ISSUE THREAD

**Issue by xescugc** [open-policy-agent/opa#3007]
## Expected Behavior

When I run `opa build wasm ...` I expect to have a `.tag.gz` with only one `.wasm` inside

## Actual Behavior

Since version `0.25` it has the `.wasm` repeated 2 times, in `0.24` did not had it.

## Steps to Reproduce the Problem

You can check it using this simple example https://github.com/xescugc/opa-wasm-error (was for another issue which is now solved but it happens with that too).

* Run `opa build -t wasm -e 'example/hello' ./example.rego`
* Check the inside of the `bundle.tar.gz` you'll see 2 `policy.wasm`

**Comment by tsandall** [comment]
Thanks for reporting this @xescugc!

```
$ docker run -v $PWD:/src -it --rm openpolicyagent/opa:0.24.0 build -t wasm -e example/hello /src -b -o /src/bundle.tar.gz
$ tar tzvf bundle.tar.gz
tar: Removing leading `/' from member names
-rw------- 0/0               3 1969-12-31 19:00 /data.json
-rw------- 0/0             101 1969-12-31 19:00 /src/example.rego
-rw------- 0/0          232046 1969-12-31 19:00 /policy.wasm
-rw------- 0/0              29 1969-12-31 19:00 /.manifest
```

After 0.25:

```
$ docker run -v $PWD:/src -it --rm openpolicyagent/opa:0.25.2 build -t wasm -e exa
mple/hello /src -b -o /src/bundle.tar.gz
(master)torin:~/scratch/opa-wasm-error$ tar tzvf bundle.tar.gz
tar: Removing leading `/' from member names
-rw------- 0/0               3 1969-12-31 19:00 /data.json
-rw------- 0/0              43 1969-12-31 19:00 /src/example.rego
-rw------- 0/0          555012 1969-12-31 19:00 /policy.wasm
-rw------- 0/0          555012 1969-12-31 19:00 /policy.wasm
-rw------- 0/0              93 1969-12-31 19:00 /.manifest
```

I guess there's something going wrong during the bundle serialization.

**Comment by srenatus** [comment]
🔍 Both `bundle.Wasm` contains the module bytes, and there's an entry for `policy.wasm` in `bundle.WasmModules`. The former is deprecated, but I'm still tracking down where it's set.
