### ISSUE TITLE
Staticcheck not used in CI

### ISSUE THREAD

**Issue by TomMD** [open-policy-agent/opa#3020]
The project appears to be CI friendly but the major go checker - staticcheck - doesn't seem to be in the list yet. 
 It has some style and a few more interesting [results](https://console.muse.dev/result/TomMD/opa/01EST4A807R06Q1GZ0KX1MWVAD?tab=results&type=S1008&type=S1009&type=SA1017&type=SA9004).  That link is a run of [Muse](https://github.com/apps/muse-dev), which will comment exactly those staticcheck results on any PRs if you'd like to install the linked app.

**Comment by srenatus** [comment]
Thanks for bringing this up. I've reviewed the findings and addressed the one I found worthwhile in #3021.

There's a bunch of further options to explore with CI -- we'll keep staticcheck in mind for sure. Thanks again.

Btw, since you're mentioning the muse product, wouldn't that be even more awesome if it supported conftest? 😄

**Comment by TomMD** [comment]
> wouldn't that be even more awesome if it supported conftest? 😄

That, or really supporting opa, is why I started looking around here in the first place 😃.   I'm still not sure about done details of the integration.  Muse integration is easiest when tools have structured output and default rules.  I'm trying to understand how to infer what the call should look like without user input (ex just because there is a `deployment.yaml` doesn't mean that's a k8s file or we know what rules should hold.

**Comment by srenatus** [comment]
> I'm trying to understand how to infer what the call should look like without user input [...]

For plain OPA, that's going to be hard. With conftest, you could depend on the presence of a `policy/` directory, [see its usage docs](https://www.conftest.dev/#usage). Also, there's [a `conftest.yaml`](https://www.conftest.dev/options/#configuration).

**Comment by srenatus** [comment]
Spring-cleaning! (Hah I wish) I'll close this 🧹 Happy to discuss the OPA/conftest use case in Slack, too!
