### ISSUE TITLE
docs/envoy-authorization: images can't be pulled from the registry anymore

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3024]
## Expected Behavior

I should be able to follow the Envoy authz tutorial, https://www.openpolicyagent.org/docs/latest/envoy-authorization/#4-create-app-deployment-with-opa-and-envoy-sidecars

## Actual Behavior

It looks like some images have disappeared from the registry, presumably because they haven't been used in a while.

## Steps to Reproduce the Problem

`docker run openpolicyagent/demo-test-server:v1` just hangs for me.

## Additional Info

👉 Workarounds: there's working tutorials in the opa-envoy-plugin repo: See [examples/istio](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio#overview) for a fully-fleshed Istio setup, and [examples/grpc](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/grpc#envoy-and-grpc-example) for a simple setup with three services and a docker-compose file.

**Comment by ashutosh-narkar** [comment]
@srenatus the Envoy tutorial seems to be working as expected. Would be please be able to verify ?

**Comment by srenatus** [comment]
@ashutosh-narkar huh! It works for me, too, now:
```
open-policy-agent/opa % docker pull openpolicyagent/demo-test-server:v1
v1: Pulling from openpolicyagent/demo-test-server
Digest: sha256:1143e17316479074df6af7b33eaf3eebf87bf6902bec9be913a00919e8955b6d
Status: Image is up to date for openpolicyagent/demo-test-server:v1
docker.io/openpolicyagent/demo-test-server:v1
open-policy-agent/opa %
```
