### ISSUE TITLE
No support for unit testing with input files

### ISSUE THREAD

**Issue by nishkrishnan** [open-policy-agent/opa#3026]
## Expected Behavior

I expect to be able to provide an input file when writing test cases for my policies. 

## Actual Behavior

Seems as if you can only specify inline inputs in your test cases. Since i use this to validate terraform plans, this is quite annoying since I'd rather be able to just copy and paste "fake" terraform plans and reference them in the code. Doing this inline is super messy.

**Comment by anderseknert** [comment]
You can provide test data in separate files. Example:

**policy.rego**
```rego
package policy

allow {
    input.my_input == "somedata"
}
```
**policy_test.rego**
```rego
package policy_test

import data.policy.allow

test_with_testdata {
    allow with input as data.testdata.input1
    not allow with input as data.testdata.input2
}
```
**input.json**
```json
{
    "testdata": {
        "input1": {
            "my_input": "somedata"
        },
        "input2": {
            "my_input": "someotherdata"
        }
    }
}
```

```shell
$ opa test .
PASS: 1/1
```

If you are testing data rather than the policies themselves, you might want to take a look at [conftest](https://github.com/open-policy-agent/conftest) too.

**Comment by p0tr3c** [comment]
I have run into the same use case and solved it by adding Builtin function which parses Terraform into Json and you can pass it to tests. 
This is extremely helpful in making sure your policy works against actual terraform syntax, and not preparse the test fixtures. 
For example
```
deny with input as hcl2.ParseFile("path/to/fixture/file.tf")
```
Would this be something helpful to contribute back to `topdown`?

**Comment by anderseknert** [comment]
@p0tr3c writing policy against files like Terraform is where [conftest](https://www.conftest.dev/) shines. Did you find it missing in functionality for your use case?

**Comment by p0tr3c** [comment]
Yes, I've only showed very simplistic example. We actually return entire `set` of results and do assertions on results. 
With `conftest` I would have to pipe the output and maintain extra test logic outside of opa. 
For example we test if the result contains `deny` messages we expect, but also if it does not include messages which should be allowed. 
I really like that my policy library only needs `opa test -v .` to validate.

**Comment by anderseknert** [comment]
@p0tr3c sounds like a custom plugin is the right approach for you then 👍

**Comment by anderseknert** [comment]
Closing as original question has been answered.

**Comment by amitlevy21** [comment]
> You can provide test data in separate files. Example:
> 
> **policy.rego**
> 
> ```rego
> package policy
> 
> allow {
>     input.my_input == "somedata"
> }
> ```
> 
> **policy_test.rego**
> 
> ```rego
> package policy_test
> 
> import data.policy.allow
> 
> test_with_testdata {
>     allow with input as data.testdata.input1
>     not allow with input as data.testdata.input2
> }
> ```
> 
> **input.json**
> 
> ```json
> {
>     "testdata": {
>         "input1": {
>             "my_input": "somedata"
>         },
>         "input2": {
>             "my_input": "someotherdata"
>         }
>     }
> }
> ```
> 
> ```shell
> $ opa test .
> PASS: 1/1
> ```
> 
> If you are testing data rather than the policies themselves, you might want to take a look at [conftest](https://github.com/open-policy-agent/conftest) too.

@anderseknert Perhaps I missed it, but I can't find a reference in the docs? 
It seems that something implicit is happening that I'm missing.

1. How does the test know about `input.json`?
2. Does it have to be in the same folder as the test? can it have a different name?
3. Can we load multiple files as you showed?

An explanation would be very much appreciated, thanks!

**Comment by amitlevy21** [comment]
I got it, from  `opa test --help`:
```
Without the '--bundle' flag OPA
will recursively load ALL *.rego, *.json, and *.yaml files for evaluating the test cases.
```

so if I got yaml test data under `policies/test_data/*.yaml` and I run `opa test policies` I can reference the yaml content with `data.test_data`

Hopes this helps others and maybe would be added to the docs

**Comment by anderseknert** [comment]
That's correct @amitlevy21 .. thanks for providing some detail on that!
