### ISSUE TITLE
docs: Improve documentation for --claims-file

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3027]
The `--claims-file` file argument for opa build/sign is explained like this:

```shell
--claims-file string        set path of JSON file containing optional claims (see: https://openpolicyagent.org/docs/latest/management/#bundle-signature-format)
```

## Expected Behavior

The provided link to explain the purpose of adding extra claims and why one might want those.

## Actual Behavior

Link points to a non-existing anchor, and nowhere on the page is a claims file mentioned.

(anchor should probably be https://openpolicyagent.org/docs/latest/management/#signature-format)

**Comment by princespaghetti** [comment]
I can grab this! Should have the fix in within the next day or so!

**Comment by anderseknert** [comment]
Sounds great @princespaghetti 👍 Holler out if you need any help.
