### ISSUE TITLE
Inquiry and suggestion for improvement

### ISSUE THREAD

**Issue by steowens** [open-policy-agent/opa#3034]
## Expected Behavior
Open Policy Agent would provide an SMT policy analyzer or a means to integrate one in order to achieve the same capability for analyzing policy that AWS IAM Access Policy Analyzer does for AWS IAM.

## Actual Behavior
Nothing in the documentation mentions that such an integration or capability is supported or possible.

## Steps to Reproduce the Problem
Read the documentation and other OPA literature.

## Additional Info
Reference to architecture underpinning AWS IAM Policy Analyzer: https://aws.amazon.com/blogs/aws/identify-unintended-resource-access-with-aws-identity-and-access-management-iam-access-analyzer/

Citation of academic literature related to this capability: https://dl.acm.org/doi/10.1145/2595222

Open Policy Agent Documentation showing the approach used to test policies in OPA: https://www.openpolicyagent.org/docs/latest/policy-testing/

**Comment by anderseknert** [comment]
That's an interesting feature. Would this not require extensive knowledge about the domain protected by the policies though? As a general purpose policy engine OPA doesn't really know whether its policies govern access to AWS, Kubernetes, a CI/CD pipeline or something else entirely.. so this would be difficult to pull off without also formalizing/limiting the objects covered by policy, such as AWS seems to have done, as documented in your provided link.

For cases where the domain _is_ known though, like [Gatekeeper](https://github.com/open-policy-agent/gatekeeper) policies for Kubernetes admission control, I suppose something like this could be employed.

**Comment by Joffref** [comment]
Personally, I don't really understand the purpose of this feature, do you mean OPA should integrate a Policy analyzer? Even if the Rego rule is compilated? 

Like @anderseknert I think it's mostly a domain problem that should be resolved by the developer not the tool itself.

If you want to diagnose policy in real-time you should check [this feature already integrated](https://www.openpolicyagent.org/docs/latest/management-decision-logs/) in OPA or you can [build a plugin](https://www.openpolicyagent.org/docs/latest/extensions/#custom-plugins-for-opa-runtime) that may fit your use case.

**Comment by anderseknert** [comment]
I don't think we'll be able to have something like this in OPA core, but I could definitely see something like this in projects building on top of OPA where the data domain is well-known. Since there's nothing actionable here at the moment, I'll close this for now, but if there are projects picking up on the idea, I'd love to know about them!
