### ISSUE TITLE
Using OPA with Kustomize generating multiple YAML documents

### ISSUE THREAD

**Issue by jdormit** [open-policy-agent/opa#3037]
Hi! I am just starting to look into OPA, so this is more of a usage question than a bug. I would like to use OPA in our CI/CD pipeline. We are using [Kustomize](https://kustomize.io/) to build out our Kubernetes config. The way I'm thinking about using OPA is to run a `kustomize build` on our build server, save the results to a YAML file and run `opa eval` with the YAML file and whatever OPA policy we end up writing.

The issue I'm running into is that `kustomize` outputs multiple YAML documents separated by a `---`. This is valid Kubernetes configuration - `kubectl apply` is happy to accept multiple documents and deploy multiple Kubernetes resources from them. But it seems that `opa eval` will only ever read the first document in the YAML file and ignores all the others.

Here's a really simple example to reproduce:
```
$ printf 'foo: bar\n---baz: qux' | opa eval -f pretty -I 'input'
# OPA only reads the first document:
{
  "foo": "bar"
}
```

Am I thinking about this the wrong way? Or is there a way to tell OPA to read multiple YAML documents from a single input?

**Comment by anderseknert** [comment]
Your example sounds like a perfect candidate for [conftest](https://github.com/open-policy-agent/conftest), which AFAIK supports multiple YAML documents in a single file. Was that evaluated for your use case?

**Comment by jdormit** [comment]
Ah, conftest looks perfect! Just tried it out, and confirmed that it works with multiple YAML documents. Thanks!
