### ISSUE TITLE
Invalid JWK in JWKS break the io.jwt.verify operation

### ISSUE THREAD

**Issue by johanneslarsson** [open-policy-agent/opa#3038]
This is perhaps just a case of bad test data, but I spent more time than I'd like to admit to troubleshot this.

## Expected Behavior
An invalid JWK in the JWKS passed to the io.jwt.verify_es256 should be ignored and the validation should still pass if a valid JWK is part of the JWKS.

## Actual Behavior
An invalid JWK in the JWKS passed to the io.jwt.verify_es256 will stop the validation and make it fail.

## Steps to Reproduce the Problem
https://play.openpolicyagent.org/p/34teELZVXQ

I believe the first JWKS `jwksMultipleBrokenJWK` containing the JWK with kid `broken`, trigger a parse error: 
```
parseTokenConstraints: failed to parse a JWK key (set): Failed to generate key: %s: Failed to generate key from JWK: Missing mandatory key parameters N or E
```

## Additional Info

The current workaround is to filter out the matching kid, but that will only work along as the kid is part of the JWT header. Another option would probably be to clean up this mess with invalid keys.

**Comment by anderseknert** [comment]
Even assuming well formed keys in the JWKS it seems like a worthwhile optimization to only ever parse the key as given by the key ID `kid` in the incoming JWT. As you noted, it looks like we currently iterate through all of them and parse them on each invocation. The key ID _must_ be part of the JWT header if more than one key is published by the issuer, so I think this would make sense.

**Comment by johanneslarsson** [comment]
Just realised that the kid is optional according to the RFC. https://tools.ietf.org/html/rfc7515#section-4.1.4

**Comment by anderseknert** [comment]
Well, like they say - the good thing about standards is that there are so many to choose from ;)

When a JWKS is involved and used for verification there are often more RFCs involved - I think the [OpenID Connect one got it right](https://openid.net/specs/openid-connect-core-1_0.html#Signing) with regards to `kid`:

> If there are multiple keys in the referenced JWK Set document, a kid value MUST be provided in the JOSE Header. 

I.e. if there's only one possible key present there's really no need for an identifier, but as soon as there are more than that it needs to be there. Always including it seems like a good choice for a token issuer.

**Comment by anderseknert** [comment]
Having looked into the performance aspect of this briefly tonight I'm unable to reproduce any significant performance issues even with sizeable JWKS provided for verification. See [playground example here](https://play.openpolicyagent.org/p/9af2cRleIv). Evaluation time is around ~1ms with 32 keys in the set, which isn't too bad given how most JWKS contain only one or at most a handful of JWKs. 

So unless someone can provide a test case that proves this to be a problem I think we can drop at least chasing performance issues here.

As for supporting broken JWKS's, I'd be inclined to drop that too - what do you feel @johanneslarsson now that the initial frustration from your bad test data session hopefully has subsided? 😄 

CC @MrSaints

**Comment by johanneslarsson** [comment]
Hey, I guess it depends on where the correct key is. Once the signature is valid the execution stops. But I don't see a good way to fix this without introducing a breaking change.

The only concern I still have is that it was hard to understand why it failed until I read the source code. Is there way to make it easier to understand that I sent invalid input to the verify builtin? Or is that logged somewhere that I missed? I just like the next one to do the same mistake as I did spend less time on it.

**Comment by anderseknert** [comment]
@johanneslarsson verification time increases with the size of the JWKS even if only the correct key is repeated in there. You can try it on the playground example posted before. But again, the difference is small enough that I don't think it's worth optimizing for.

The behavior around errors in the built-in functions was changed with the [v0.25.0 release](https://github.com/open-policy-agent/opa/releases/tag/v0.25.0). Since I don't think that is likely to change what's probably best to do here then is to log the error at debug level, so at least it can be caught when hacking locally.

**Comment by johanneslarsson** [comment]
Agree. Alright, I'm happy!
