### ISSUE TITLE
Migrating vgramer/opa-idea-plugin to open-policy-agent

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3051]
@vgramer and others have created an [IntelliJ IDEA plugin for OPA](https://github.com/vgramer/opa-idea-plugin) that provides similar functionality to the [VS Code extension](https://github.com/open-policy-agent/vscode-opa) that's already in the OPA organization. After chatting with @vgramer and others involved in the IntelliJ plugin, we concluded it would make sense to host the plugin under the OPA organization on GitHub. Over time this will help with discovery and maintenance of the plugin.

To move forward we need to:

* [x] Hold a vote amongst the OPA maintainers (the process is outlined in the GOVERNANCE.md file).
* [x] Create an intellij-maintainers team on GitHub and add @vgramer and @asadali to the new team.
* [x] Transfer the vgramer/opa-idea-plugin repo into the open-policy-agent organization
* [x] Ensure that DCO check is enabled on the repo
* [x] Add a security notice on the plugin repo pointing back to SECURITY.md

The project is currently using GHA for CI and does not have any secrets configured so migration should be simple.

@vgramer @anderseknert can you mention anyone else who should be added to the maintainer team for the plugin?

@ritazh @maxsmythe @shomron cc-ing you folks to vote on this like we've done in the past for GK, conftest, etc.

**Comment by anderseknert** [comment]
Ping @irodzik @lkadalski

**Comment by lkadalski** [comment]
Unfortunately I have more responsibilities since last month and I can't act as an active maintainer. :baby: At least during pandemic. I hope you understand. 
Regards

**Comment by irodzik** [comment]
Thanks for nomination @anderseknert! :) I will continue this project supporting project by reviewing merge requests, but I don't feel that I am correct person for maintainer. I believe it should be someone who was way more involved in developing the plugin.

**Comment by shomron** [comment]
+1 for me, as a Goland user I'm excited to have this project hosted under OPA umbrella!

**Comment by maxsmythe** [comment]
+1, glad to see more IDE support!

**Comment by ritazh** [comment]
+1 👏 💯 🎉

**Comment by anderseknert** [comment]
@lkadalski of course! Family first 👶 :)

@irodzik I'm sure occasional PR reviews will be appreciated 👍

**Comment by tsandall** [comment]
@vgramer @asadali you both should have received an email invite for the intellij-maintainers team.

@vgramer if you go to https://github.com/vgramer/opa-idea-plugin/settings and scroll down to `Danger Zone` you should see an option to start the repo transfer.

**Comment by vgramer** [comment]
@tsandall I have transferred the repository :)

**Comment by tsandall** [comment]
Excellent! You should have admin access on the repo now. Looks like we're all done! Thanks all! 🎊
