### ISSUE TITLE
Wasm breaking change from 0.24 to 0.25.2?

### ISSUE THREAD

**Issue by christophwille** [open-policy-agent/opa#3069]
I grabbed 0.25.2 https://github.com/open-policy-agent/opa/releases and re-compiled my sample policies to wasm. However, I am running into an issue https://github.com/christophwille/csharp-opa-wasm/issues/11 insofar as the execution now returns [] for the [rbac.rego](https://github.com/christophwille/csharp-opa-wasm/blob/master/sample-policies/rbac.rego). It worked ever since I checked it in initially, and I have upgraded a couple times already. (it is a simplified version of the rego from the playground sample; and it still runs fine in the playground, just checked now)

Are there any breaking changes in 0.25.2 that might trip my implementation up? (I am very close to the JS impl)

**Comment by srenatus** [comment]
Hmm I'm afraid I'm having trouble reproducing this. With a policy.wasm extracted from a wasm bundle built with opa 0.25.2 and your rbac.rego, I've tried this nodejs code,

```js
const fs = require('fs');
const util = require('util');
const { loadPolicy } = require("@open-policy-agent/opa-wasm");

const policyWasm = fs.readFileSync('policy.wasm');

input = {user: "bob"};
data = {
 user_roles: {
   bob: [
     "op",
     "facility",
     "admin"
   ]
 }
};

loadPolicy(policyWasm).then(policy => {
    policy.setData(data);
    resultSet = policy.evaluate(input);
    if (resultSet == null) {
        console.error("evaluation error")
    }
    if (resultSet.length == 0) {
        console.log("undefined")
    }
    console.log(util.inspect(resultSet, false, null, true));
}).catch( error => {
    console.error("Failed to load policy: ", error);
})
```

using `npm-opa-wasm` master, I get this:
```console
$ node run.js
[ { result: { allow: true, user_is_admin: true } } ]
```

...which is what you'd expect, isn't it?

I haven't checked your implementation closely (yet)... 🤔

**Comment by srenatus** [comment]
💡 Scratch that, I have been using a different command to build the bundle:

```
opa build -t wasm -e app/rbac rbac.rego
```

When using your command, `opa build -t wasm -e app.rbac rbac.rego`, I get an empty result set, too.

**Comment by christophwille** [comment]
Dang, thanks! https://github.com/christophwille/csharp-opa-wasm/blob/master/sample-policies/build-on-windows.bat it was correct for the first compilation, but wrong for the rbac one.

**Comment by srenatus** [comment]
That's a cool project. Do you want it featured on https://github.com/anderseknert/awesome-opa? 😃 

(Also, I'd love to know more about your usage and experience with OPA WASM. Are you on the community slack?)

**Comment by anderseknert** [comment]
@christophwille I'd be happy to merge a PR adding your .NET WASM integration to Awesome OPA 😃

**Comment by anderseknert** [comment]
Btw @christophwille feel free to drop in to our bi-weekly community meeting later today. See the [README for details](https://github.com/open-policy-agent/opa/#want-to-contribute-to-opa).

**Comment by christophwille** [comment]
Very unlikely because in half an hour the DIF Face to Face starts and there is a session at 6PM CET.

**Comment by anderseknert** [comment]
Oh well, next time then :)
