### ISSUE TITLE
time.now_ns() should return the current time each time it is invoked

### ISSUE THREAD

**Issue by ghsbhatia** [open-policy-agent/opa#3073]
## Expected Behavior

time.now_ns() should return the current time each time it is invoked

## Actual Behavior

Multiple calls to the time.now_ns() built-in function within a single policy evaluation query will always return the same value

## Steps to Reproduce the Problem

Invoke time.now_ns() multiple times within the query, it will return the same value. The documentation is pretty misleading: 

output := time.now_ns() | output is a number representing the current time since epoch in nanoseconds.

## Additional Info

I am not sure what the rationale is behind time.now_ns() to return the cached value that remains fixed during the duration on query execution, but it will be quite useful to return the actual current time so that it can be used to calculate the time spent in executing a particular block of the query if needed.

**Comment by anderseknert** [comment]
Just below the section you quoted from the docs on `time.now_ns()` you'll find:

> Multiple calls to the time.now_ns built-in function within a single policy evaluation query will always return the same value.

I believe the rationale is to keep policy evaluation deterministic - for the same reason you won't find built-ins to generate random numbers, UUID's will be the [same for any given input](https://www.openpolicyagent.org/docs/latest/policy-reference/#uuid), etc.

Have you checked out the [profiling tools](https://www.openpolicyagent.org/docs/latest/policy-performance/#profiling)? They should help you in measuring policy performance.

**Comment by tsandall** [comment]
Policy profiling is supported through tooling like `opa eval --profile` as @anderseknert mentioned. There are several reasons why `time.now_ns` operates the way it does. Fundamentally, policy execution should be deterministic--if `time.now_ns()` was not cached then policy replay would become much more difficult. So would optimizations that perform reordering. I'm going to close this issue as there's not much to do for now.
