### ISSUE TITLE
Convert list to object with duplicated keys in linear time

### ISSUE THREAD

**Issue by xciter** [open-policy-agent/opa#3079]
I need to convert a list of objects which I get from input to an object in linear time. The problem is that used key may be duplicated in a list. What is the most optimal way to do this without changing the input?

Input example:
`[
    {
        "id": "a",
        "body": {...}
    },
    {
        "id": "b",
        "body": {...}
    },
    {
        "id": "a",
        "body": {...}
    }
]`

Desired output:
`{
    "a": [
        {
            "id": "a",
            "body": {...}
        },
        {
            "id": "a",
            "body": {...}
        }
    ],
    "b": [
        {
            "id": "b",
            "body": {...}
        }
    ]
}`

The only way I found how to do it is using inner comprehension, which decreases overall performance dramatically:
`output_obj := {i.id : [j | j:= inpt[_]; j.id == i.id] | i := inpt[_]}`

## Expected Behavior
To get an object in linear time

**Comment by anderseknert** [comment]
Hi @xciter 👋 Just answered your question on [StackOverflow](https://stackoverflow.com/questions/65805313/how-to-convert-a-list-to-an-object-with-key-duplications-in-opa-rego), but I'll copy it here if anyone ends up here in search for the same answer.

[Comprehension indexing](https://www.openpolicyagent.org/docs/latest/policy-performance/#comprehension-indexing) should ensure O(n) runtime complexity given the rule meets the conditions for that (which yours does):

```rego
package test

output_obj := {id: list |
	some i
	id := input[i].id
 	list := [obj |
    	some j
		input[j].id == id
		obj := input[j]
	]
}
```

**Comment by xciter** [comment]
@anderseknert thanks for such a quick and great answer!
