### ISSUE TITLE
health check is failing 

### ISSUE THREAD

**Issue by Phaniharsha2908** [open-policy-agent/opa#3088]
Hi, I am trying to inject the opa-istio - I have followed the documentation at https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio

I am deployed everything as per the document but i am getting the below error with opa-istio cointainer - am i missing some thing - can you please assist?

Warning  Unhealthy  28m (x278 over 163m)    kubelet  (combined from similar events): Readiness probe failed: Get http://ip:8282/health?plugins: read tcp ip:49238->ip:8282: read: connection reset by peer.

Warning  BackOff    3m42s (x640 over 161m)  kubelet  Back-off restarting failed container

fyi,

opa-istio:
    Container ID:  docker://
    Image:         openpolicyagent/opa:0.26.0-istio....
    Image ID:      docker-pullable://openpolicyagent/opa@sha256:5d54ea...
    Port:          <none>
    Host Port:     <none>
    Args:
      run
      --server
      --config-file=/config/config.yaml
      --addr=localhost:8181
      --diagnostic-addr=0.0.0.0:8282
      /policy/policy.rego
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 22 Jan 2021 12:35:09 +0000
      Finished:     Fri, 22 Jan 2021 12:35:39 +0000
    Ready:          False
    Restart Count:  57
    Liveness:       http-get http://:8282/health%3Fplugins delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8282/health%3Fplugins delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /config from opa-istio-config (rw)
      /policy from opa-policy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-productpage-token-ncq6g (ro)

istio versio : 1.8

GKE - 1.16

please let me know if any info, thanks

**Comment by srenatus** [comment]
🔍 Can you provide some logs of your "opa-istio" service? Does it output anything?

**Comment by Phaniharsha2908** [comment]
Hi @srenatus 

Thanks for the response 

please find the attached logs, thanks!

[opa.logs.txt](https://github.com/open-policy-agent/opa/files/5856614/opa.logs.txt)

**Comment by srenatus** [comment]
Can you please double-check that your policy allows health requests to the opa sidecar? 👉 https://github.com/open-policy-agent/opa-envoy-plugin/blob/3130a1b821cff3674fbd19975f2990082216b8de/examples/istio/quick_start.yaml#L401-L404

**Comment by Phaniharsha2908** [comment]
@srenatus 

yes it is there -thanks

**Comment by ashutosh-narkar** [comment]
@Phaniharsha2908 I do not see any health check requests in OPA's logs. This could be due to how the networking is setup in GKE. Do you have any other logs that could indicate any connection errors may be a debug level ?

**Comment by ashutosh-narkar** [comment]
Also what does your deployment manifest look like ? I have seen in the past on GKE that naming the service port has helped.

**Comment by DR0ZZA** [comment]
Hi, I have a similar problem with the non-istio Quick Start Example. If I remove ["-w", "8282"] from [this line](https://github.com/open-policy-agent/opa-envoy-plugin/blob/102f9ee741ea820acf8023c61efe4dc1b516de47/quick_start.yaml#L28) and add the following code to the policy:
```
    # Allow health-checks
    allow {
        split(http_request.host, ":")[1] == "8282"
    }
```
I get "result": "true", as shown in  
[opa_envoy_health_log.txt](https://github.com/open-policy-agent/opa/files/5860789/opa_envoy_health_log.txt).

But the Kubernetes events show:
```
42m         Warning   Unhealthy                      pod/example-app-746c6d88d5-s29t7    Liveness probe failed: HTTP probe failed with statuscode: 403
42m         Warning   Unhealthy                      pod/example-app-746c6d88d5-s29t7    Readiness probe failed: HTTP probe failed with statuscode: 403
```
Any idea what might be causing this? I'd like for all traffic to pass through the policy if possible.

**Comment by Phaniharsha2908** [comment]
I could not find the RCA. however reinstalled everything from scratch  again resolved the issue, thanks

**Comment by srenatus** [comment]
🎉 not the most satisfying resolution, but I guess we can close this. 😃

**Comment by yerinu2019** [comment]
health check is not stable.
it did succeed and started to fail after rule refactoring without changes in health check allow rule.
i rollbacked rule refactoring but health check still fails with "undefined decision".
when i test the failed input in the log as is using the unit test, the test passes.

**Comment by ashutosh-narkar** [comment]
@yerinu2019 have you defined a `livenessProbe` and `readinessProbe` in your deployment manifest ? Also can you share some logs and examples that describe the issue you're facing.

**Comment by anderseknert** [comment]
With the situation resolved it sounds difficult to move this one forward. Let's close this for now and we can re-open later if we have more information to work with.
