### ISSUE TITLE
OPA WASM 0.26 opa_heap_top_get missing?

### ISSUE THREAD

**Issue by christophwille** [open-policy-agent/opa#3092]
I recompiled my sample policies https://github.com/christophwille/dotnet-opa-wasm/tree/master/sample-policies with 0.26 (previously compiled with 0.25.2) - now I get the following error:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  HResult=0x80131500
  Message='Wasmtime.Instance' does not contain a definition for 'opa_heap_top_get'
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

https://github.com/open-policy-agent/opa/releases/tag/v0.26.0 doesn't mention a surface area change like that... intentional? (did not verify with npm-opa-wasm)

**Comment by srenatus** [comment]
Good catch, it's been an oversight not to export `opa_heap_top_get` in #3061. The PR in question was mentioned in the release notes, under _Enhancements_,
> In addition, Wasm compiled policies only export the minimal set of APIs

however, it wasn't intentional not to export it. The surprising thing is that our tests _in this repo_ still passed.

I believe this calls for two things,

- [ ] exporting the previously exported function
- [ ] testing against the latest release, or master ref, of npm-opa-wasm in this repo (per PR or nightly)

**Comment by srenatus** [comment]
Oh wait I was a bit quick here, I believe. The function in question isn't a documented export at all, is it?

Looking at the SDKs I'm aware of, we find:
- npm-opa-wasm does _not_ use it
- our golang SDK makes note of it (`heapTopGet: i.Exports["opa_heap_top_get"],`), but doesn't use it.

So, I guess the proper resolution is something to be discussed. We could either document and export it, or leave everything as-is.

(Either way, I think having a nightly test against npm-opa-wasm would be good to have.)

**Comment by christophwille** [comment]
Back in the day I based my initial implementation on npm-opa-wam. But didn't check back to see if changes were applied simply assuming if my implementation still worked it would be OK. Means I will have to revisit how the implementation should be today...

**Comment by christophwille** [comment]
ok, back in the day I also used https://webassembly.github.io/wabt/demo/wasm2wat/ to generate me a nice doc comment https://github.com/christophwille/dotnet-opa-wasm/blob/master/src/Opa.Wasm/OpaPolicy.cs#L62. Now, when I upload my example.rego compiled with 0.26, it tells me "Error: readWasm failed: 0000004: error: bad magic value" - who is wrong? (the Web site or the .wasm)

**Comment by christophwille** [comment]
https://github.com/open-policy-agent/npm-opa-wasm/blob/master/src/opa.js#L128 according to https://webassembly.github.io/wabt/demo/wasm2wat/ this is no longer in there, correct?

**Comment by srenatus** [comment]
`opa_println` is a bit of a special case -- it's only used internally now. opa's WASM code won't use it, but if you happen to work on the `wasm/src` stuff in this repo (like during development), you can use it; and if the host SDK supports `opa_println`, you'll see those messages. Long story short, you shouldn't _need_ to provide this function in the host, not if you're only using release WASM builds.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/npm-opa-wasm/pull/28 👈  found the reference. Heap top setting isn't supported anymore.
