### ISSUE TITLE
Calling a Rego file from another Rego

### ISSUE THREAD

**Issue by Jeyakumardevarajulu** [open-policy-agent/opa#3100]
I have an existing rego policy and I want to call anther rego policy from the existing policy (asc.rego) and I have tried with different option to access the rego policy and I am unable to access it. I am sure that I may be accessing it wrongly

```rego
package asc
import input
import data.agreement

main = allow
default allow=false
test[data.agreement.allow]
{
  true
}
```

----------------------------------------------
second policy (agreement.rego)

```rego
package agreement

main = allow

default allow=false

allow
{
  true
}
```
--------------------------------------
I am calling the policy suing below opa command

```
opa eval -i input.json -d  psc.rego "data.psc"
```

## Expected Behavior
```json
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "Test": [true],
            "allow": false,
            "main": false
          },
          "text": "data.psc",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

## Actual Behavior

```json
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "Test": [],
            "allow": false,
            "main": false
          },
          "text": "data.psc",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

**Comment by anderseknert** [comment]
You'll need to include both your source files when calling opa eval, like:

```shell
opa eval -d asc.rego -d agreement.rego "data.asc"
```

**Comment by tsandall** [comment]
You could also just pass the directory containing the files:

```
opa eval -b $dirpath "data.asc"
```

Use -b instead of -d unless you want all JSON/YAML files to be picked up.
