### ISSUE TITLE
Feature Request - Add a way for tests to be skipped

### ISSUE THREAD

**Issue by 06kellyjac** [open-policy-agent/opa#3104]
With many testing frameworks you can write an empty test and it'll just be marked as TODO or Skipped until it's filled out.

https://jestjs.io/docs/en/api#testtodoname
https://github.com/mochajs/mocha/issues/1510#issuecomment-142481408

I'm writing a bunch of policies for use with conftest & I have some unit tests (`conftest verify`)
There are a couple edge cases that my policies don't account for right now and rather than leave these edge cases failing constantly while I work on other policies I'd rather it was marked as TODO or Skipped.
I currently have to comment the test out and leave a TODO comment but those aren't visible when running `conftest verify` or `opa test`
I want prospective users of my policies to have an idea of what coverage the policies have.

The idea of skipping tests was also floated in an original issue for improving tests
https://github.com/open-policy-agent/opa/issues/428#issuecomment-325491561

**Comment by tsandall** [comment]
@06kellyjac how would you feel if we added support for marking tests as skipped/todo by changing the test rule name? E.g.,

```
package example

test_foo_bar {
   data.foo.bar with input as 1
}

todo_test_foo_baz {
   # some logic, doesn't matter
}

test_foo_qux {
   data.foo.qux with input as 1
}
```

When the test runner executes it will skip execution of the second test rule but include it in the report:

```
$ opa test y.rego  # or conftest verify
PASS: 2/3
TODO: 1/3
```

```
$ opa test y.rego -v # or conftest verify
data.example.test_foo_bar: PASS (139µs)
data.example.todo_test_foo_baz: SKIPPED
data.example.test_foo_qux: PASS (59.6µs)
--------------------------------------------------------------------------------
PASS: 2/3
TODO: 1/3
```
