### ISSUE TITLE
opa test --bench fails with "eval_cancel_error: caller cancelled query execution"

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3107]
## Expected Behavior

`opa test --bench testing.rego` to report the result of benchmarking a simple policy.

## Actual Behavior

```shell
$ opa test --bench testing.rego
data.testing.test_allow_is_true: ERROR (5.000137933s)
  eval_cancel_error: caller cancelled query execution
--------------------------------------------------------------------------------
ERROR: 1/1
```

## Steps to Reproduce the Problem

testing.rego
```rego
package testing

allow {
	true
}

test_allow_is_true {
	allow
}
```
```shell
$ opa test --bench testing.rego
```

## Additional Info

Setting the `--timeout` flag to 30s provides the benchmark result. Two things stand out to me here:

1) If no explicit `--timeout` is provided, I believe the default should be to run until finished.
2) If a `--timeout` is provided and exceeded, a human readable message should be printed.

**Comment by tsandall** [comment]
I think we can fix this easily by making the timeout default dynamic. If `--bench` is not specified, the 5s timeout is fine (that's more than enough time a query to return). If `--bench` is specified, we can just crank the timeout to 30s as that would give the Go benchmark runner enough time to find a stable measurement.
