### ISSUE TITLE
The policy test missing understand. why not  for input then try ?

### ISSUE THREAD

**Issue by netroby** [open-policy-agent/opa#3122]
I am not quite understand the test cases for policy rules. 

https://www.openpolicyagent.org/docs/latest/policy-testing/

see the origin test
```
package authz

test_post_allowed {
    allow with input as {"path": ["users"], "method": "POST"}
}

test_get_anonymous_denied {
    not allow with input as {"path": ["users"], "method": "GET"}
}

test_get_user_allowed {
    allow with input as {"path": ["users", "bob"], "method": "GET", "user_id": "bob"}
}

test_get_another_user_denied {
    not allow with input as {"path": ["users", "bob"], "method": "GET", "user_id": "alice"}
}
```

for programmer , who want really a test, he may wrote like this

```
package authz

test_post_allowed {
  input {"path": ["users"], "method": "POST"}
   test   allow 
}

test_get_anonymous_denied {
   input {"path": ["users"], "method": "GET"}
    test not allow 
}

test_get_user_allowed {
   input {"path": ["users", "bob"], "method": "GET", "user_id": "bob"}
    test allow
}

test_get_another_user_denied {
   input {"path": ["users", "bob"], "method": "GET", "user_id": "alice"}
    test not allow 
}
```

**Comment by netroby** [comment]
The missing understand was the input 

A as B ????
what the fuck.

If you say make A as B, 

What is from , what is target.


copy file from C as D

how to understand  this ?   copy from C to D? or from D to C?

**Comment by ashutosh-narkar** [comment]
OPA’s `with` keyword can be used to replace the input and data document. You can find more info in the docs [here](https://www.openpolicyagent.org/docs/latest/policy-testing/#data-mocking) and specifically about the `with` keyword [here](https://www.openpolicyagent.org/docs/latest/policy-language/#with-keyword).

**Comment by tsandall** [comment]
I'm going to close this issue. The docs explain how `with` works and they show examples of how to use it inside of tests.
