### ISSUE TITLE
What does this file ' ._.' do?

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3127]
As title, when i run opa server with bundle, then got the error:

`./opa run -b ./bundle.tar.gz --signing-alg RS256 --verification-key ./sha256_pub`
error: load error: bundle /Users/yumiao3/Downloads/test/bundle.tar.gz: file ._. not included in bundle signature

the content of my .signatures.json:
```
{
 "signatures": [
  "eyJhbGciOiJSUzI1NiJ9.eyJmaWxlcyI6W3sibmFtZSI6Ii5tYW5pZmVzdCIsImhhc2giOiIyMmNlMmJiNTU5ZDBjYWRkMzA5NThkOTkwYWE0NzcwMDIyY2Q3ZDMxYmVjOTQ5NGQyMWM1Njg2YzQ1N2EwZTI4IiwiYWxnb3JpdGhtIjoiU0hBLTI1NiJ9LHsibmFtZSI6Imh0dHAvZXhhbXBsZS9hdXRoei9hY2wucmVnbyIsImhhc2giOiJkMDUxOGM5ODliMDIzZmQ2YzYyY2QzN2YyZjM2OGNiYTNjNDhkMTI4ZDFjYTQyYmYyYWFhMzI4NzQwN2NkYjA5IiwiYWxnb3JpdGhtIjoiU0hBLTI1NiJ9LHsibmFtZSI6InJvbGVzL2JpbmRpbmdzL2RhdGEuanNvbiIsImhhc2giOiIwMmEyNDlhMGUyOWNjZjY0OWY4NzU2ZTU4YTUwYzY2ZTFmYTI1ZWU4ZmJlMjVlNWZjYTM4N2IxZjc3MDVhOWU5IiwiYWxnb3JpdGhtIjoiU0hBLTI1NiJ9XX0.rGNu86VJiqFMeXE_obKXp8xOeFkn286vPMlHsIgl8bT_H2ZCN16hFqsHGljC88Biqv0KBqVBuxj6kDrVk2Nst7G6fqakvgawOP6XsS-mAatcK-TmmG3GTZlCJ3I_7au-rApovBrh5qd5KiN9GomJuheTZrIxghnhuekWUvmX4hg"
 ]
}
```

**Comment by srenatus** [comment]
There's no "special file" like that in OPA. How is your bundle created, and what happens between creation and your call there...? It must have gotten in some way, but it's not "an OPA thing". What does it contain? 🤔 (A quick google search makes me think the file could be an OSX thing.)

**Comment by andyyumiao** [comment]
> There's no "special file" like that in OPA. How is your bundle created, and what happens between creation and your call there...? It must have gotten in some way, but it's not "an OPA thing". What does it contain? 🤔 (A quick google search makes me think the file could be an OSX thing.)

@srenatus does we have a rest api to generate .signatures.json on opa server? otherwise we have to implement it in our own bundle service，because of It introduces extra work, and this signature generation logic is difficult to keep in sync with OPA in future releases.

**Comment by srenatus** [comment]
I don't think there's any API in the OPA server that'll let you generate bundles, let alone sign them. The server is meant to retrieve bundles, verify their signatures, and run with it.

Is there anything blocking you from using the cli? 
```
$ opa build p.rego # build bundle.tar.gz
$ opa build --signing-key secret --signing-alg HS256 -b bundle.tar.gz # sign bundle.tar.gz
$ tar ztvf bundle.tar.gz
tar: Removing leading `/' from member names
-rw------- 0/0               3 1970-01-01 01:00 /data.json
-rw------- 0/0              36 1970-01-01 01:00 /bundle.tar.gz/p.rego
-rw------- 0/0              29 1970-01-01 01:00 /.manifest
-rw------- 0/0             637 1970-01-01 01:00 /.signatures.json
$
```
I suppose that's the way of least effort for your bundle service.... Anyhow, I am convinced that we'll try very hard not to break any compatibility there, so, I wouldn't expect that you have to change too often how you'd sign bundles if you wanted to do it yourselves.

**Comment by andyyumiao** [comment]
> I suppose that's the way of least effort for your bundle service.... Anyhow, I am convinced that we'll try very hard not to break any compatibility there, so, I wouldn't expect that you have to change too often how you'd sign bundles if you wanted to do it yourselves.

@srenatus thanks for the reply, but we will be using OPA in production to manage millions of policy data, which means that many policies will be updated, which means bundles will be updated, i.e. re-signed

**Comment by tsandall** [comment]
I believe @srenatus was suggesting that you run the `opa build` program as a subprocess. Alternatively, if you're writing your bundle service in Go then you can integrate w/ the OPA bundle package to do the signing and bundle encoding.

However, I think we should rewind a bit:

> @srenatus does we have a rest api to generate .signatures.json on opa server? otherwise we have to implement it in our own bundle service，because of It introduces extra work, and this signature generation logic is difficult to keep in sync with OPA in future releases.

The signature logic is not complicated. Others have implemented it themselves in Java for example. You can find all of the details you need here: https://www.openpolicyagent.org/docs/latest/management/#signing. As for backwards compatibility, what makes you think that it's going to change in future releases?

**Comment by tsandall** [comment]
Closing this issue as there's nothing actionable at the moment. We can reopen if needed.
