### ISSUE TITLE
Requests including % in the url should not fail

### ISSUE THREAD

**Issue by Pocokwins** [open-policy-agent/opa#3129]
## Expected Behavior

Requests including a percentage sign ('%') are not failing

## Actual Behavior
When we send a request to OPA, which contains percentage sign (%) in the request path, we get HTTP ERROR 503 with the following error message in decision log: 
```
"error":{
      "message":"invalid URL escape \"%\""
   }
```
## Steps to Reproduce the Problem

Call a URL with '%' sign in the path.

OPA version: v0.26.0.

**Comment by anderseknert** [comment]
Hi @Pocokwins 
Could you a full example request that is failing? Are you querying the data API? And are you trying to use the `%` for escape or you want an actual percentage sign in the path? 🤔

**Comment by Pocokwins** [comment]
Hi @anderseknert ,

We use the compile API. We would like to use % in the path, not for escape something.

Here I send you a decision log entry, hope it will help.

```
{
   "decision_id":"dd367b9f-26d7-4d17-8174-8f9eaf50030c",
   "error":{
      "message":"parse \"/%\": invalid URL escape \"%\""
   },
   "input":{
      "attributes":{
         "destination":{
            "address":{
               "Address":{
                  "SocketAddress":{
                     "PortSpecifier":{
                        "PortValue":8443
                     },
                     "address":"10.4.140.28"
                  }
               }
            },
            "principal":"www.xxxlutz.at"
         },
         "metadata_context":{
            
         },
         "request":{
            "http":{
               "headers":{
                  ":authority":"www.xxxlutz.at",
                  ":method":"GET",
                  ":path":"/%",
                  "accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                  "accept-encoding":"gzip",
                  "accept-language":"en-US,en;q=0.9,de;q=0.8",
                  "cache-control":"no-cache",
                  "cdn-loop":"cloudflare",
                  "cf-connecting-ip":"---",
                  "cf-ipcountry":"HU",
                  "cf-ray":"61e5e9ec6d781cfe-BUD",
                  "cf-request-id":"08239087bd00001cfe14bbf000000001",
                  "cf-visitor":"{\"scheme\":\"https\"}",
                  "pragma":"no-cache",
                  "sec-ch-ua":"\"Chromium\";v=\"88\", \"Google Chrome\";v=\"88\", \";Not A Brand\";v=\"99\"",
                  "sec-ch-ua-mobile":"?0",
                  "sec-fetch-dest":"document",
                  "sec-fetch-mode":"navigate",
                  "sec-fetch-site":"none",
                  "sec-fetch-user":"?1",
                  "upgrade-insecure-requests":"1",
                  "user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
                  "x-envoy-decorator-operation":"---",
                  "x-envoy-external-address":"---",
                  "x-envoy-peer-metadata":"---",
                  "x-envoy-peer-metadata-id":"---",
                  "x-forwarded-for":"---",
                  "x-forwarded-proto":"https",
                  "x-request-id":"d170476d-e7aa-4bcd-b659-c78241b56655"
               },
               "host":"www.xxxlutz.at",
               "id":"674096597367835044",
               "method":"GET",
               "path":"/%",
               "protocol":"HTTP/1.1"
            },
            "time":{
               "nanos":882827000,
               "seconds":1612793212
            }
         },
         "source":{
            "address":{
               "Address":{
                  "SocketAddress":{
                     "PortSpecifier":{
                        "PortValue":37456
                     },
                     "address":"10.156.0.71"
                  }
               }
            }
         }
      },
      "version":{
         "encoding":"encoding/json",
         "ext_authz":"v2"
      }
   },
   "labels":{
      "id":"da88669a-c282-481b-aa1a-0b20494c075e",
      "version":"0.26.0-envoy"
   },
   "level":"info",
   "metrics":{
      "timer_server_handler_ns":650604
   },
   "msg":"Decision Log",
   "path":"istio/authz/authz_response",
   "requested_by":"",
   "time":"2021-02-08T14:06:52Z",
   "timestamp":"2021-02-08T14:06:52.884956371Z",
   "type":"openpolicyagent.org/decision_logs"
}

```

**Comment by tsandall** [comment]
I think this error is being generated inside the OPA-Envoy server handler [here](https://github.com/open-policy-agent/opa-envoy-plugin/blob/102f9ee741ea820acf8023c61efe4dc1b516de47/internal/internal.go#L695) which is called [here](https://github.com/open-policy-agent/opa-envoy-plugin/blob/102f9ee741ea820acf8023c61efe4dc1b516de47/internal/internal.go#L312). I suppose we could modify the OPA-Envoy server handler to still run evaluation even if the path/query/body could not be parsed... 🤔

**Comment by anderseknert** [comment]
As far as I know, that would be an [invalid URI](https://tools.ietf.org/html/rfc3986#section-2.4):

>  Because the percent ("%") character serves as the indicator for percent-encoded octets, it must be percent-encoded as "%25" for that octet to be used as data within a URI.

So if you'd really want `%` as part of a path component it would have to be escaped as `%25`.

**Comment by Pocokwins** [comment]
> As far as I know, that would be an [invalid URI](https://tools.ietf.org/html/rfc3986#section-2.4):
> 
> > Because the percent ("%") character serves as the indicator for percent-encoded octets, it must be percent-encoded as "%25" for that octet to be used as data within a URI.
> 
> So if you'd really want `%` as part of a path component it would have to be escaped as `%25`.

Yes, it's not a valid URI, but it is accepted by Istio this is why we also would like to use it.

**Comment by anderseknert** [comment]
Closing this for now. If a more compelling reason for breaking standards is presented later, we can always re-open.
