### ISSUE TITLE
allow undefined data when only using virtual extents

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3130]
## Expected Behavior

[This test case](https://github.com/open-policy-agent/opa/blob/master/test/wasm/assets/013_virtual.yaml#L40-L62)

```yaml
  - note: virtual data extent
    query: |
      data == {
        "x": {
          "y": {
            "p": 1,
            "r": {
              "a": 3
            },
            "s": {"elem1"}
          }
        }
      }
    modules:
      - |
        package x.y
        p = 1
        q = 2 { false }
        r["a"] = 3
        r["b"] = 4 { false }
        s["elem1"]
        s["elem2"] { false }
    want_defined: true
```

should result in a non-empty result set (`[{}]`) if run without any calls to set data to anything (e.g. not calling `policy.setData({})` in the npm-opa-wasm SDK).

The equivalent opa_test.go case is
```go
		{
			Description: "Virtual extent, undefined data",
			Policy: `package a.b
			c = 3`,
			Query: `data == {"a": {"b": {"c": 3 }}}`,
			Evals: []Eval{
				// {NewData: `{}`, Result: `{{}}`}, // PASS
				{Result: `{{}}`}, // FAIL
			},
		},
```

## Actual Behavior

There's an empty result set.

**Comment by srenatus** [comment]
I think the cleanest approach could be allocating `{}` for data in `opa_eval_ctx_new`... 🤔 So if it's never provided in any other way, it'll default to that. WDYT?

**Comment by srenatus** [comment]
Here's a simpler case btw.
```
		{
			Description: "Undefined data",
			Query:       `data == { "p": {}}`,
			Evals: []Eval{
				// {NewData: `{}`, Result: `{{}}`},
				{Result: `{{}}`},
			},
		},
```

**Comment by tsandall** [comment]
> I think the cleanest approach could be allocating {} for data in opa_eval_ctx_new... 🤔 So if it's never provided in any other way, it'll default to that. WDYT?

That sounds fine to me though I'm curious why the data pointer being null returns undefined.

**Comment by srenatus** [comment]
Yeah that's happening in opa_value_merge, which might be the better place to fix it.

**Comment by srenatus** [comment]
⏩ https://github.com/open-policy-agent/opa/pull/3136
