### ISSUE TITLE
Custom authentication support in OPA when securing HTTP APIs

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#3132]
This may qualify as a feature request and apologies for misleading title but that was the closed to express it briefly in a title. Hopefully the description will make it clearer.

We would like to use Istio/OPA plugin to secure some HTTP APIs and I have been able to do so using a  dummy/sample app in Istio. In addition to the authorization policy I was able to also have OPA do an authentication check since I was using a signed JWT token; one can have rules in OPA's policy to validate the token like being issued by a trusted source/key, has not expired etc. Basically an implicit authentication policy. 
All good there but the [documentation](https://www.openpolicyagent.org/docs/latest/http-api-authorization/) also gives examples where user:password can be passed as HTTP headers and OPA's authorization policy defines some authorization rules to allow/deny based on user's roles etc. 
This assumes the user has been authenticated (user:password combination is validated) before the request hits OPA. My question is - in the Istio/OPA plugin setup how and where would one be able to do the authentication so it would have happened before the request reaching OPA (as it would only be able to do authorization in this case).

We actually need do a different kind of authentication check than validating user:password. We expect our requests to come with an OAuth reference token which would need to be validated against our identity server and obtain a JWT containing claims about the user/entity making the request. OPA can then use the JWT in its authorization policies. Do we need to develop a custom plugin to do this?

Another related question: 
In our setup we have a web application and then some web services (REST/HTTP API) endpoints. Typically a user goes to the web app, web app will redirect user to login if the user is not yet authenticated, user(client) is issued a reference token that he uses to access the web app and the HTTP APIs. The endpoints or web app validate and dereference the reference token against the identity server and get back a JWT with claims. 
Question: If we are to use OPA to secure the above setup, can OPA be used to redirect user to a login URL if the request is found to be lacking any authentication attributes or authentication check fails. I am guessing this too would need to be done by the custom authentication plugin which is able to intercept the request before it reaching OPA. 

regards
K

**Comment by ashutosh-narkar** [comment]
The `opa-envoy` plugin extends OPA with a gRPC server that implements the [Envoy External Authorization API](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ext_authz_filter.html). In the Istio example, the `EnvoyFilter` crd is used to configure the External Authorization Filter. This filter along with other Envoy filters get added to a list of filters that are executed in order.  So regrading your first question about an authentication check, it would be performed by a different filter presumably placed before the `ext_authz` filter in the chain of filters. For example, Envoy's JWT Authentication filter performs JWT validation and Istio I believe has a crd that allows users to control the behavior of this filter. You can then of course use that JWT as part of the OPA policy which you've been doing.

Regarding support for OAuth this [link](https://www.openpolicyagent.org/docs/latest/oauth-oidc/) should provide more information. 

Finally in the sample setup that you've defined, there would typically be a frontend service that handles end-user authentication with the help of say an IdP and then the token obtained from that provider can be sent to OPA for usage in other authz policies. Are the apis behind some sort of a gateway ? Check out [this](https://blog.styra.com/blog/api-authorization-apigee-okta-opa-part-1) blog that may have some resemblance to the setup you've described.

**Comment by anderseknert** [comment]
Closing as answered. Let me know if there was anything I missed and I'll re-open @kyle-burnette .
