### ISSUE TITLE
Expose simple Go API to enable OPA config embedding

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3140]
We don't do a good job of enabling OPA config embedding today yet there are several use cases where a simple Go API that instantiates the management plugins and exposes an evaluation function would be useful. The beginnings of this idea are here: https://github.com/open-policy-agent/example-api-authz-go/blob/master/internal/opa/opa.go.

We should introduce a simple Go API like the one linked above inside of OPA proper and document when and how to use it on the website.

Some improvements need to be made to the code linked above:

* Evaluation should not be limited to boolean responses (e.g., use `interface{}`)
* Evaluation should leverage prepared queries to avoid unnecessary work.

**Comment by anderseknert** [comment]
This is done, though we still need to document the SDK and update some of our side project repos to use it. Closing and creating separate issue for docs.
