### ISSUE TITLE
opa parse: Allow source location to be provided in output

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3143]
## Expected Behavior

To enable better tooling around the OPA AST, it would be helpful if the `opa parse` command could include source locations in the output.. either by default or when provided a flag, like `--location` or `--include-location`.

**Comment by anderseknert** [comment]
Just to provide a bit more background here. While an easy fix would be just changing the `"-"` serialization directives on the [structs](https://github.com/open-policy-agent/opa/blob/master/ast/policy.go#L115-L203) in `policy.go`, we likely won't want _all_ serialization to contain location (as this will be verbose to say the least), so inclusion of location must be conditional.

Something like [this](https://github.com/liip/sheriff), but preferably without introducing a new dependency just for this. A custom marshaling function could also be used, but it would need to traverse the full AST and not just the top nodes.

**Comment by charlieegan3** [comment]
I have a PR open for this here: https://github.com/open-policy-agent/opa/pull/5576
