### ISSUE TITLE
Add kube-mgmt to "External data" section of docs

### ISSUE THREAD

**Issue by eshepelyuk** [open-policy-agent/opa#3145]
Related to this thread in Slack https://openpolicyagent.slack.com/archives/C1H19LW4F/p1612895367214200?thread_ts=1612895367.214200

It would be great to explicitely point in docs that kube-mgmt could be used as one of the options to load external data and policies into OPA.

Like other options mentioned here https://www.openpolicyagent.org/docs/latest/external-data/

**Comment by srenatus** [comment]
K8s is one specific use case, and the docs are trying to be generic. Perhaps there's another place that a mention of `kube-mgmt` would fit it? 🤔

**Comment by eshepelyuk** [comment]
Hello @srenatus 

Please feel free to pick up any place where it suitable.

My intention is to update docs in such way, that it would become clear that `kube-mgmt` could (should) be used 
not only for [K8S policy admission controller flow](https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/), 

but as rather generic tool to reliable and declaratively load data \ policy to OPA in K8S env.

**Comment by srenatus** [comment]
I suppose we could mention it on the external data docs as an example of how this is done in a k8s setting? Wouldn't be entirely out of place, I think.

**Comment by eshepelyuk** [comment]
That's fine as soon as doc users will be made aware of `kube-mgmt` for loading arbitrary data into OPA.

**Comment by obsd** [comment]
You can send me what you want to add and I will add it to my article:
[Load data into OPA](https://www.reddit.com/r/devops/comments/twqw9u/loading_external_data_into_opa_the_good_the_bad/)
