### ISSUE TITLE
bigInts are converted to float64 with a precision of 16

### ISSUE THREAD

**Issue by johanneslarsson** [open-policy-agent/opa#3147]
Certificates uses serial numbers of the data type big.Int. There is a use case to compare these against a list of known values. However it looks like OPA converts large numbers to float64, but with a precision of 16 which isn't enough. 

## Expected Behavior
`28857836529306024611912 != 2.8857836529306023e+22`

## Actual Behavior
`28857836529306024611912 == 2.8857836529306023e+22`

## Steps to Reproduce the Problem
https://play.openpolicyagent.org/p/z2pYIWddo3

```
cases:
- data:
  modules:
  - |
    package generated

    certs = "MIIDQTCCAimgAwIBAgIKBhxi7pQIeREQSDANBgkqhkiG9w0BAQsFADA1MQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxEzARBgNVBAMTCklzc3VpbmcgQ0EwHhcNMjEwMjEzMjIxNDU3WhcNMjIwMjEzMjIxNTA3WjBAMQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxHjAcBgNVBAMTFUJpZyBJbnQgU2VyaWFsIE51bWJlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOd8wN14tSdV6uLdGkmhWFTdC4aSYGJ+SzC7jNt84neZem7GbW7tPIpNH7zkjBEDwXprLooPtkmHy8fW1D+qL1aYu3iy5WlGq5A8qkngsIcOMBbkY/XzFO0Z/+CJE+IQOiymY9m1EuXHsPLv+3IqOlu+Jxv8giv42Gbe8Z7orwank9QS9elWiin5ZBDwvOBhyWizw7OIyVF+Y7QE8rRlHkbwD2/Q0V+D6ePPmcbuPbtvGcfN4ZIEO1y58w3TPaxo5tYvjn8WMqbw4y6TSh1tjtqNtSlJLCFVXcacxuXAzJwkdm0zeKrwOIFI+KFmqLYJiCZY256C40YgGMcNafeiwx0CAwEAAaNIMEYwDgYDVR0PAQH/BAQDAgECMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdIwQYMBaAFIQRCGnMVD+t+OD6MOIz6GktfgAcMA0GCSqGSIb3DQEBCwUAA4IBAQARY4vagu50rqltlZYUXZhs5uAoib2PLkUHsypOjIwQyP7HVv6cYH9tFwLNrbnrJkV93IBathC+vfpk5g+j8UCOBfwyXiGitzAVyn+KdYmQ3m9Wlga4yVm2WUd20TeuuhxuQFBrUvd/q28qhpEVgkXg40jZxBgvI7YtFCUNcEhMdgCR1xj1wjb65/RIlkjK0e9IYLSCSzQKokbqQs3lrZCLIHQlmGqudc9dnW2wwF7dGk88YcrFXpoek1NnO0X1bKdx8HyhILwHA1UTov6ayXjLeruLDiCTAgUePMfeMvyFjrLYgAb59zROs0WHgJi40tsF/uVJzgzuERtZ3Ca3EGkA"

    p = __local2__ {
      __local4__ = data.generated.certs
      crypto.x509.parse_certificates(__local4__, __local3__)
      __local0__ = __local3__
      __local2__ = [__local1__ | __local1__ = __local0__[_].SerialNumber]
    }
  note: cryptox509parsecertificates/DER, single cert, bigint
  query: data.generated.p = x
  want_result:
  - x:
    - 28857836529306024611912

```

```
go test -run "TestRego/cryptox509parsecertificates/DER,_single_cert,_bigint" ./...

...

    --- FAIL: TestRego/cryptox509parsecertificates/DER,_single_cert,_bigint (0.00s)
        exported_test.go:136: unexpected query result:
            exp: {{"x": [2.8857836529306023e+22]}}
            got: {{"x": [28857836529306024611912]}}
```

**Comment by johanneslarsson** [comment]
Ooops, updated the variable names to align the numbers without testing my playground policy again.

**Comment by srenatus** [comment]
Yeah so I believe what we're trying is this:

First, we convert via json.Number().Int64(); and if that fails, we do `new(big.Float).SetString()`.

For extra precision, we could probably add an attempt to do `new(big.Int).SetString(..., 10)`... 🤔

**Comment by srenatus** [comment]
I _believe_ the extra logic should go here, https://github.com/open-policy-agent/opa/blob/06c3d7e4b659a64a27d0d2678481d0fbe3c0dd49/ast/term.go#L1507-L1537 and https://github.com/open-policy-agent/opa/blob/06c3d7e4b659a64a27d0d2678481d0fbe3c0dd49/ast/term.go#L1568-L1598 and https://github.com/open-policy-agent/opa/blob/06c3d7e4b659a64a27d0d2678481d0fbe3c0dd49/ast/term.go#L1973-L2002 and https://github.com/open-policy-agent/opa/blob/06c3d7e4b659a64a27d0d2678481d0fbe3c0dd49/ast/term.go#L2027-L2057 and https://github.com/open-policy-agent/opa/blob/06c3d7e4b659a64a27d0d2678481d0fbe3c0dd49/ast/compare.go#L88-L108

Note that the duplication you see there was intentional to avoid stuff escaping to the heap. ⚠️ 

@johanneslarsson from how I understand this, the `big.Int` attempt should go between the two things we try right now.

I suppose one could start with the last thing, in `compare.go`, to see progress on this issue.

**Comment by johanneslarsson** [comment]
Multiple ways to skin the cat. Seems like there is no clear definition on how large a json number could be. With less experience in the code base my initial thought was to make float-less sprintf function. 

https://github.com/open-policy-agent/opa/blob/master/topdown/strings.go#L369

Then my test below would pass. I had to remove the certificate, it has some sensitive details.

`cases:
- data:
  modules:
  - |
    package generated

    certs = "Mmm.."

    p = __local2__ {
      __local4__ = data.generated.certs
      crypto.x509.parse_certificates(__local4__, __local3__)
      __local0__ = __local3__
      __local2__ = [__local1__ | __local1__ = sprintf("%v", [__local0__[_].SerialNumber])]
    }
  note: cryptox509parsecertificates/DER, single cert, b64
  query: data.generated.p = x
  want_result:
  - x:
    - "28857836529306024611912"
`

**Comment by srenatus** [comment]
Ignore my previous post, I think I was completely on the wrong track here. 😄 

Playground aside (which seems to have an issue with now input containing big numbers is stored), opa eval seems alright to me:

```
$ opa eval '28857836529306024611912 != 2.8857836529306023e+22' --format=pretty
true
```

That said, you're working with the `parse_certificates` builtin... That makes me wonder if we aren't using [`UseNumber()`](https://golang.org/pkg/encoding/json/#Decoder.UseNumber) here:

https://github.com/open-policy-agent/opa/blob/b535cbfde11445df658878af9e8290ed38b9b4ab/topdown/crypto.go#L75-L85

It turns out _we are_ calling UseNumber on the used decoder:
https://github.com/open-policy-agent/opa/blob/b535cbfde11445df658878af9e8290ed38b9b4ab/util/json.go#L47

`x509.Certificate` clearly has a big.Int serial number, https://golang.org/pkg/crypto/x509/#Certificate, I wonder if that get's lost somewhere in the process.

I'd like to get sprintf out of the picture here. Do you need a string representation for your tests...?

Also, it would be great if you could try to come up with an example cert that has a big.Int serial number but no confidential details...

**Comment by johanneslarsson** [comment]
Unless there is some limit on how big json numbers can be I don't see a good reason for reverting to strings.

Here is a working test with a bogus certificate I just created.
```
cases:
- data:
  modules:
  - |
    package generated

    certs = "MIIDQTCCAimgAwIBAgIKBhxi7pQIeREQSDANBgkqhkiG9w0BAQsFADA1MQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxEzARBgNVBAMTCklzc3VpbmcgQ0EwHhcNMjEwMjEzMjIxNDU3WhcNMjIwMjEzMjIxNTA3WjBAMQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxHjAcBgNVBAMTFUJpZyBJbnQgU2VyaWFsIE51bWJlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOd8wN14tSdV6uLdGkmhWFTdC4aSYGJ+SzC7jNt84neZem7GbW7tPIpNH7zkjBEDwXprLooPtkmHy8fW1D+qL1aYu3iy5WlGq5A8qkngsIcOMBbkY/XzFO0Z/+CJE+IQOiymY9m1EuXHsPLv+3IqOlu+Jxv8giv42Gbe8Z7orwank9QS9elWiin5ZBDwvOBhyWizw7OIyVF+Y7QE8rRlHkbwD2/Q0V+D6ePPmcbuPbtvGcfN4ZIEO1y58w3TPaxo5tYvjn8WMqbw4y6TSh1tjtqNtSlJLCFVXcacxuXAzJwkdm0zeKrwOIFI+KFmqLYJiCZY256C40YgGMcNafeiwx0CAwEAAaNIMEYwDgYDVR0PAQH/BAQDAgECMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdIwQYMBaAFIQRCGnMVD+t+OD6MOIz6GktfgAcMA0GCSqGSIb3DQEBCwUAA4IBAQARY4vagu50rqltlZYUXZhs5uAoib2PLkUHsypOjIwQyP7HVv6cYH9tFwLNrbnrJkV93IBathC+vfpk5g+j8UCOBfwyXiGitzAVyn+KdYmQ3m9Wlga4yVm2WUd20TeuuhxuQFBrUvd/q28qhpEVgkXg40jZxBgvI7YtFCUNcEhMdgCR1xj1wjb65/RIlkjK0e9IYLSCSzQKokbqQs3lrZCLIHQlmGqudc9dnW2wwF7dGk88YcrFXpoek1NnO0X1bKdx8HyhILwHA1UTov6ayXjLeruLDiCTAgUePMfeMvyFjrLYgAb59zROs0WHgJi40tsF/uVJzgzuERtZ3Ca3EGkA"

    p = __local2__ {
      __local4__ = data.generated.certs
      crypto.x509.parse_certificates(__local4__, __local3__)
      __local0__ = __local3__
      __local2__ = [__local1__ | __local1__ = __local0__[_].SerialNumber]
    }
  note: cryptox509parsecertificates/DER, single cert, b64
  query: data.generated.p = x
  want_result:
  - x:
    - 28857836529306024611912

```

**Comment by johanneslarsson** [comment]
Looking at "exp" and "got" (see test result in first post), it looks like OPA manages the big.Int from the serial number but fails to parse the "exp" value.

**Comment by srenatus** [comment]
Could still be an artifact of our test runner. I guess if we do the comparison in opa, ie. have `p` be a rule that is true if the serial is the expected one, it'll pass?

**Comment by johanneslarsson** [comment]
I wish that was the case, but it doesn't look like it.

main.rego
```
package play

allow {
    certs = crypto.x509.parse_certificates(input.cert)
    goodList[_].key == certs[0].SerialNumber
}

goodList = [
    {"key":28857836529306024611912,"name":"a good value"}]
```

main_test.rego
```
package play

# SERIALNUMBER: 28857836529306024611912
test_cert_allow {
	allow with input as {"cert": "MIIDQTCCAimgAwIBAgIKBhxi7pQIeREQSDANBgkqhkiG9w0BAQsFADA1MQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxEzARBgNVBAMTCklzc3VpbmcgQ0EwHhcNMjEwMjEzMjIxNDU3WhcNMjIwMjEzMjIxNTA3WjBAMQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxHjAcBgNVBAMTFUJpZyBJbnQgU2VyaWFsIE51bWJlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOd8wN14tSdV6uLdGkmhWFTdC4aSYGJ+SzC7jNt84neZem7GbW7tPIpNH7zkjBEDwXprLooPtkmHy8fW1D+qL1aYu3iy5WlGq5A8qkngsIcOMBbkY/XzFO0Z/+CJE+IQOiymY9m1EuXHsPLv+3IqOlu+Jxv8giv42Gbe8Z7orwank9QS9elWiin5ZBDwvOBhyWizw7OIyVF+Y7QE8rRlHkbwD2/Q0V+D6ePPmcbuPbtvGcfN4ZIEO1y58w3TPaxo5tYvjn8WMqbw4y6TSh1tjtqNtSlJLCFVXcacxuXAzJwkdm0zeKrwOIFI+KFmqLYJiCZY256C40YgGMcNafeiwx0CAwEAAaNIMEYwDgYDVR0PAQH/BAQDAgECMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdIwQYMBaAFIQRCGnMVD+t+OD6MOIz6GktfgAcMA0GCSqGSIb3DQEBCwUAA4IBAQARY4vagu50rqltlZYUXZhs5uAoib2PLkUHsypOjIwQyP7HVv6cYH9tFwLNrbnrJkV93IBathC+vfpk5g+j8UCOBfwyXiGitzAVyn+KdYmQ3m9Wlga4yVm2WUd20TeuuhxuQFBrUvd/q28qhpEVgkXg40jZxBgvI7YtFCUNcEhMdgCR1xj1wjb65/RIlkjK0e9IYLSCSzQKokbqQs3lrZCLIHQlmGqudc9dnW2wwF7dGk88YcrFXpoek1NnO0X1bKdx8HyhILwHA1UTov6ayXjLeruLDiCTAgUePMfeMvyFjrLYgAb59zROs0WHgJi40tsF/uVJzgzuERtZ3Ca3EGkA"}
}

# SERIALNUMBER: 28857836529306024611913
test_cert_not_allow {
    not allow with input as {"cert": "MIIDTTCCAjWgAwIBAgIKBhxi7pQIeREQSTANBgkqhkiG9w0BAQsFADA1MQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxEzARBgNVBAMTCklzc3VpbmcgQ0EwHhcNMjEwMjE0MDk1NDQxWhcNMjIwMjE0MDk1NDUxWjBMMQswCQYDVQQGEwJOTzERMA8GA1UEChMISm9oYW5uZXMxKjAoBgNVBAMTIUJpZyBJbnQgU2VyaWFsIE51bWJlciBub3QgYWxsb3dlZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJUiuGcGehQHtLKP3MZIUtH2kxd8aC7RMRQsrIAAjs5VQqnH/JHaTQsCZjKu32/JT8MnuNeKztLyopNoVb5ruDylEsDKmEhChq4S2KApdJ74tVpH8+Le1JZBzfxy4dS86PCqL1KzBd2oj4Gti2WqVK6DHSXc64AAgYFAqWOQFWv9yf8VWYTScFPe111loCadASZ7L8SvsCah2hjvagWvM550/djr/8XoVhQcJ/EYENyhNNtD050RbGmUMA9vTNTM7SneeazIMMRrB3NOi3ZgxqLvTNfQwrl3Jclyvv5FnaUN5hiSVZa0fvkGZmrgNijQzVabf5jZvUO0Hfyg6C9VCV8CAwEAAaNIMEYwDgYDVR0PAQH/BAQDAgECMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdIwQYMBaAFPJ2PRuXVQ3Xm5SXHKLXvhGiOE31MA0GCSqGSIb3DQEBCwUAA4IBAQCDeZcuDq0QHHoRJzzts6bddnOnAdh+9fYm+qKmrZV66HrQieYyHA/rf4eEnvLjaPlrQuDnqaiu3v8oh05Uw4fyssW1ozPdZVFEBAwcvqGAvWnwGWmZJvfxOjvS07fhb/bTZdLx3GiruU5SY2aj1x+KZg4HAlRWllXqQvdMedlbwsjx5pV1rQp/xemIXU70749KsqHs/b7TlocDVGVOx0CYCWnrhxdDTJBxzytC30XNb30B3ogzN/4GihkVXnSgzG2s7ORPi7555F6atZAeW7YOtFDGdh66Xzs0tTv72nesBa0o4wcv7fhCEmhGjCsv31EFpJ6o/eZMKCPbuQyqM0Li"}
}

```

Test result, both shouldn't be "allow".
```
SUMMARY
--------------------------------------------------------------------------------
data.play.test_cert_allow: PASS (1.130292ms)
data.play.test_cert_not_allow: FAIL (467.902µs)
--------------------------------------------------------------------------------
PASS: 1/2
FAIL: 1/2
```

**Comment by srenatus** [comment]
🔍 looks like it boils down to this, then:

```
$ opa eval --format=pretty '28857836529306024611913 == 28857836529306024611912'
true
```

**Comment by johanneslarsson** [comment]
> 🔍 looks like it boils down to this, then:
> 
> ```
> $ opa eval --format=pretty '28857836529306024611913 == 28857836529306024611912'
> true
> ```

Indeed, well spotted :star:

**Comment by srenatus** [comment]
I guess I might not have been completely off track before (https://github.com/open-policy-agent/opa/issues/3147#issuecomment-778326091). Look at this playground, https://play.golang.org/p/7QKCf7NRlNh, for what we do vs. what we might want to do.

> But I'm not sure if we could have both big.Int and big.Float, aren't they overlapping?

They sure are. But so are int64 (`(Number).Int64()`) and big,.Float, and we still manage 😄 We'd need some extra care, though, I suppose, to not introduce even weirder bugs.

**Comment by johanneslarsson** [comment]
No you weren't. 

Question is what is the actual use-case for float in OPA? Its large numbers without precision. But who wants that? Most of the policies that we write are for comparing two values. Floats are not ideal in that regard.

**Comment by andrehaland** [comment]
I have started looking into this issue. By trying to convert to big.Int, before we try to convert to big.Float in ast.Compare(), we get the expected behaviour when comparing big ints with opa eval:
```
$ ./opa_darwin_amd64 eval --format=pretty '28857836529306024611913 == 28857836529306024611912' 
false
```

**Comment by srenatus** [comment]
Backwards compatibility concerns aside, how about replacing`big.Float` by `big.Rat`?

**Comment by andrehaland** [comment]
To me it seems that there is an underlying problem with how big numbers are parsed with JSON (`jq` and other online JSON parsers produces the same output)

```bash
$ cat serial_number.json
{"SerialNumber": 28857836529306024611912}
```

```bash
jq '.' serial_number.json
{
  "SerialNumber": 28857836529306023000000
}
```

This is also shown when looking at the returned value of `builtinCryptoX509ParseCertificates()` by adding the following lines 
```go
val, err := ast.InterfaceToValue(x)
fmt.Println(val)
```

before the return of function at 
https://github.com/open-policy-agent/opa/blob/30a06544f26b2dd52df8b785543ccc1ba431b54f/topdown/crypto.go#L80-L86

in which we get (with irrelevant information removed)
```
[{..."SerialNumber": 28857836529306024611912,...}]
```
with the test cert provided in https://github.com/open-policy-agent/opa/issues/3147#issuecomment-778756035

**Comment by johanneslarsson** [comment]
> Backwards compatibility concerns aside, how about replacing`big.Float` by `big.Rat`?

It's probably worth a try, that should give us "infinite" precision. This is also how `jsonschema` handles numbers. However print a rat isn't pretty so then the float could come handy.

https://play.golang.org/p/XJujE_XvMep

**Comment by srenatus** [comment]
https://golang.org/pkg/math/big/#Rat.FloatString maybe?

I don't know where `big.Float` "ends" though, and if it's range is bigger than that of `big.Rat` or not 🤔

**Comment by andrehaland** [comment]
By the way, I found that the test runner uses `github.com/ghodss/yaml` to convert YAML to JSON:

https://github.com/open-policy-agent/opa/blob/a2cf431d4c7260077dd343bf8f8e460375b68065/test/cases/cases.go#L78-L86
https://github.com/open-policy-agent/opa/blob/a2cf431d4c7260077dd343bf8f8e460375b68065/util/json.go#L107-L113

In this conversion, big integers are also converted to a float with precision 16, and thus, we get `"exp": 2.8857836529306023e+22` for the test in https://github.com/open-policy-agent/opa/issues/3147#issue-807253596

https://play.golang.org/p/HSgy3wsHcwm

**Comment by andrehaland** [comment]
Following up on the YAML to JSON conversion, I see that `github.com/ghodss/yaml` uses `github.com/go-yaml/yaml` (`gopkg.in/yaml.v2`) to Unmarshal (https://github.com/ghodss/yaml/blob/25d852aebe32c875e9c044af3eef9c7dc6bc777f/yaml.go#L116-L118)

It is in this Unmarhal tha big integers are converted to a float with precision of 16, see playground https://play.golang.org/p/Sjrf7U3fufb

**Comment by andrehaland** [comment]
> Could still be an artifact of our test runner. I guess if we do the comparison in opa, ie. have `p` be a rule that is true if the serial is the expected one, it'll pass?

So this were right when combining it with changing to big.Rat here:
https://github.com/open-policy-agent/opa/blob/f817ea5a32e795d078a0650e595e2d2e46e3153a/ast/compare.go#L100-L108

Then the tests in https://github.com/open-policy-agent/opa/issues/3147#issuecomment-778756035 passes

**Comment by koponen-styra** [comment]
Looking at the golang big.Float SetString implementation suggests that the parsing code sets the precision to 64 bits by default. In the example, this default precision is not enough and the test fails. Whenever constructing a big.Float with SetString, I think we need to set the precision explicitly to the maximum to enable lossless parsing.

I didn't test fixing all the SetStrings (seems like there's about 15 of them in the code base), but I did test replacing the new(big.Float).SetStrings in ast/compare.go with new(big.Float).SetPrec(big.MaxPrec).SetStrings. It did fix the failing test case.
