### ISSUE TITLE
Add support for object and set comprehensions

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#315]
We're currently missing support for object and set comprehensions. The language already supports array comprehensions so the changes to introduce similar support for objects and sets should not be too bad.

```
my_obj = {k: v | <query> }
my_set = { v | <query> }
```

**Comment by mmussomele** [comment]
Working on this.

**Comment by mmussomele** [comment]
This is merged now.

**Comment by tsandall** [comment]
Fixed in #368
