### ISSUE TITLE
Question: filtering array in Rego

### ISSUE THREAD

**Issue by munjalpatel** [open-policy-agent/opa#3155]
Hello,

I get cookie in my policy with values like this:
```
access_token=<access_token_value>;ctid=<ctid_value>
```

I also get base64 encoded header that contains JWT payload processed by Istio. Here is how decoded value of the payload looks like:
```json
{
  "teams": [
    "Team 1",
    "Team 2"
  ]
}
```

The policy needs to ensure `<ctid_value>` is one of the values in the `teams` array.
However, I am not able to find any good documentation that explains how to filter arrays in Rego.

This is what I have so far:
```rego
package istio.authz

import input.input.attributes.request.http as request
import input.input.parsed_path

default allow = false

allow {
  "a" == "1"
}

is_user_team_member {
  teams := json.unmarshal(base64.decode(request.headers["x-myapp-auth-payload"])).teams
  cookies := split(request.headers["cookie"], ";")

  # @todo:
  # 1. find index in `cookies` where `index(value, "ctid=") == 0`
  # 2. [_ignore, team] := split(cookies[index], "=")
  # 3. check if `teams` contains `team`
}
```

**Comment by anderseknert** [comment]
You can use an [array comprehension](https://www.openpolicyagent.org/docs/latest/policy-language/#array-comprehensions) to filter:

```rego
teams = ["Team 1", "Team 2"]

filtered = [team | team := teams[_]; team == "Team 1"]

# filtered == ["Team 1"]
```

But using sets is often preferable:

```rego
# Convert to set using set comprehension
teams := {team | team := json.unmarshal(base64.decode(request.headers["x-kooyal-auth-payload"])).teams[_]}

# Check if "Team 1" is in the set
teams["Team 1"]
```

**Comment by munjalpatel** [comment]
Thanks @anderseknert !

However, this first problem I am trying to solve is how do I extract the value of `ctid` from `cookie` as mentioned in my question above.

**Comment by anderseknert** [comment]
Array comprehensions to the rescue once more ;)

```rego
ctid_teams := [t | parts := split(cookie, ";")
                   part := parts[_]
                   kv := split(part, "=")
                   kv[0] == "ctid"
                   t := kv[1]]

team := ctid_teams[0]
```
You might want to add a helper function for that though to keep the rule easily readable.

**Comment by munjalpatel** [comment]
Awesome! Thanks @anderseknert I'll give this try.

**Comment by anderseknert** [comment]
Great! Let me know if you run into any other hurdles. If not, feel free to close the issue when you consider it resolved 👍

**Comment by munjalpatel** [comment]
@anderseknert is there a way to set HTTP headers from the policy for the downstream app to consume?

**Comment by anderseknert** [comment]
No, that’s not currently possible. You’ll need to include any data you want in the response body. What headers are you thinking of?

**Comment by munjalpatel** [comment]
I would like to set extracted `team` as `x-team-id` for the actual app to consume.
Can you point me to the docs that shows how to modify incoming request body?

**Comment by anderseknert** [comment]
You can’t modify the incoming request body. You can only affect the (JSON) structure of the response by having your policies and rules return the data structure you’d like.

**Comment by munjalpatel** [comment]
You mean response going back to the client (browser)?
I though policies only execute on request from client.

**Comment by anderseknert** [comment]
The (OPA) client is whoever called OPA for a decision. And yes, policies only execute on requests from clients. Any data you want sent back to the client must be encoded in the response (i.e. the decision). To provide you an example from your policy:

```rego
package istio.authz

default allow = false
default team = ""

allow {
    is_user_team_member
}

team = function_to_extract_team(arg)

decision = {
    "allow": allow,
    "team": team,
}
```
Now if you were to query the `decision` rule above, at `http://address-to-opa:8181/v1/data/istio/authz/decision` you'd get back a response like:

```json
{
    "allow": true,
    "team": "Team 1"
}
```

**Comment by munjalpatel** [comment]
I see, okay, that makes sense. Thanks!
