### ISSUE TITLE
Unable to use a custom decision log plugin when using the opa-envoy-plugin

### ISSUE THREAD

**Issue by cknakal** [open-policy-agent/opa#3165]
# Overview
I'm trying to use a custom decision log plugin with my OPA instance that runs with the opa-envoy-plugin.
My `main.go` file looks something like this:
```
import envoy "github.com/open-policy-agent/opa-envoy-plugin/plugin"

func main() {
	// register Envoy plugins
	runtime.RegisterPlugin("envoy.ext_authz.grpc", envoy.Factory{}) // for backwards compatibility
	runtime.RegisterPlugin(envoy.PluginName, envoy.Factory{})
	// register our custom decision log plugin
	runtime.RegisterPlugin(plugin.PluginName, plugin.Factory{})

	if err := cmd.RootCommand.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

## Expected Behavior
Requests to Envoy should be forwarded to an OPA sidecar via gRPC. When I use the [binary from the Dockerfile](https://github.com/open-policy-agent/opa-envoy-plugin/blob/611d696a330b45efe6d7e9cc6859a4fa380df0d7/Dockerfile#L11) that ships with the opa-envoy-plugin, everything works. But, if I try to compile a new binary that references the opa-envoy-plugin plugins, I get behavior like... (see below)

## Actual Behavior
Envoy always returns a 403 error. This happens even if I disable my custom plugin an only try to run a newly compiled binary with just the Envoy plugin specified.
Like so:
```
import envoy "github.com/open-policy-agent/opa-envoy-plugin/plugin"

func main() {
	// register Envoy plugins
	runtime.RegisterPlugin("envoy.ext_authz.grpc", envoy.Factory{}) // for backwards compatibility
	runtime.RegisterPlugin(envoy.PluginName, envoy.Factory{})
	// register our custom decision log plugin
	// runtime.RegisterPlugin(plugin.PluginName, plugin.Factory{}) // disabled

	if err := cmd.RootCommand.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

## Steps to Reproduce the Problem
1. Create a `main.go` file in a new repo like the one above
2. Compile a new binary
3. Start running the binary in conjunction with an Envoy container
4. You should see that the Envoy container never sends requests to the OPA container and always returns a 403 response

## Additional Info
I've verified that the gRPC plugin is running on the OPA container when trying to use the Envoy plugin in another custom plugin repo.
```
   "envoy_ext_authz_grpc": {
      "state": "OK"
    },
```

My current guess is that there's something I'm missing when compiling the custom decision log binary. When I compile the opa-envoy-plugin binary and use that with my applicaiton, everything works. When I switch over to my custom binary, that's when I see the 403 responses from Envoy.

**Comment by ashutosh-narkar** [comment]
Can you share the link to the source code of your modified plugin ?

**Comment by cknakal** [comment]
Here's an example of what I'm trying to do:
https://github.com/cknakal/opa-custom-plugin-test
(Instructions for getting everything running in the README)
After running the `curl` command in the README you should see a 403 response in the Envoy logs.

**Comment by deepahoskote** [comment]
Hi @ashutosh-narkar : Checking in to see if you had any updates on this?

**Comment by ashutosh-narkar** [comment]
[This](https://github.com/ashutosh-narkar/custom-decision-logger) example should provide some pointers.

**Comment by srenatus** [comment]
It's been a while...cleaning up old issues, feel free to reopen if this hasnt been resolved.
