### ISSUE TITLE
Unable to call function by a dynamically generated package path

### ISSUE THREAD

**Issue by rehmanmuradali** [open-policy-agent/opa#3167]
I am trying to call a function that has a dynamic package path. For example
```
data.rules[input.x].match(r)
```
Here the actual package is determined by the value of variable `input.x`

For rules, it is working fine, but for functions, it is a compile-time error in rego.
```
rego_type_error: undefined function data.rules[__local9__].match
```
## Expected Behavior
If `input.x= rule1`, function `match(r)` of package `data.rules.rule1` should be called.

## Actual Behavior
Compile time error:
```
rego_type_error: undefined function data.rules[__local9__].match
```

## Steps to Reproduce the Problem
1) Create a rego file with package `data.rules.rule1` and define a function:
```
match(r) {
    true
}
```
2) Create another rego file, define a function:
```
allow {
   arg := { "a" : 1 }
   data.rules[input.x].match(arg)
}
```
3) Invoke allow function with input `{ "x" : "rule1" }`

**Comment by tsandall** [comment]
Thanks for filing this @rehmanmuradali. We'll put this into the backlog and consider it for a future version.

NOTE: To support this we'd have to improve both the compiler and the query evaluator. The compiler would need to be able to enumerate the functions that are referenced by expressions like `data.rules[x].match` and then type check the result. The `evalFunc` stage in the evaluator would need to be updated to use the plugged reference.

**Comment by tsandall** [comment]
Closing this in favor of #4025 as there's a bit more conversation there that goes into detail on how this could work.
