### ISSUE TITLE
Add CI job that runs tests on macOS

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3176]
We've recently run into crashes in the wasm runtime test suite on macOS (#3168). It would be nice to have an extra GitHub Action job that at least runs tests on macOS during pre-merge.

**Comment by srenatus** [comment]
FWIW we're now smoke-testing the built binaries on macos. We still don't run tests on either macos or windows.

**Comment by tsandall** [comment]
@srenatus how much work would it be to get the tests running on the macos builder?

**Comment by srenatus** [comment]
With some caveats, yeah, I think so. We cannot rebuild the wasm bits on macos because it's got no docker, but we could split that off. A bit more involved that way, though.
