### ISSUE TITLE
sdk: allow better control of logging when integrating OPA as a library

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3180]
## Expected Behavior

When integrating OPA through the Go SDK it should be possible to control what and how the OPA runtime logs. 

## Actual Behavior

Today a Go integration starting the OPA runtime with provided config will see messages from loaded plugins, like below:

```
time="2021-02-23T14:29:31+01:00" level=info msg="Starting bundle downloader." name=test plugin=bundle
time="2021-02-23T14:29:31+01:00" level=info msg="Starting decision logger." plugin=decision_logs
time="2021-02-23T14:29:31+01:00" level=info msg="Log upload skipped." plugin=decision_logs
```

## Additional Info

While a simple solution could be to just silence the logs, a better one would be to allow injecting a custom logger implementation to allow the caller to forward the messages to their logging framework of choice, or in other ways act on the log events.

**Comment by tsandall** [comment]
I'm putting this issue in the planned category as I think it's a must-have for the Go SDK. No one wants their libraries to log.
