### ISSUE TITLE
Improve decision log controls for large scale environments

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3182]
There are a few improvements we need to make to address issues in large scale environments that rely on HTTP decision logging:

1. Currently the HTTP decision logger can be configured to drop events if the buffer size exceeds a threshold. From a user's point of view, it would be nice to be able to configure the limit in terms of decisions per second (DPS) instead of sheer bytes as the latter can be tough to determine.

2. OPA does not indicate when the rate limit is exceeded via status or any other APIs today. We should extend the decision logger to record a drop count in the metric registry. Since metric registry is dumped into status updates, it should allow control planes to monitor for drops.

3. Dynamic reconfiguration should be supported. #1593 indicates that the upload size is not reconfigurable however from looking at the [code](https://github.com/open-policy-agent/opa/blame/b447f50d506f6a02dc89bdcb90927b9ed787e9e4/plugins/logs/plugin.go#L596), it seems like reconfiguration _should_ take affect on the next upload. We need to test this.

4. Additionally, it would be nice if OPA could respect a back-pressure response from the control plane (HTTP 429)

For implementing the DPS rate limit we can use https://pkg.go.dev/golang.org/x/time/rate.

**Comment by ashutosh-narkar** [comment]
The decision log improvements have been completed:

1) https://github.com/open-policy-agent/opa/pull/3314

2) https://github.com/open-policy-agent/opa/pull/3337

3) https://github.com/open-policy-agent/opa/pull/3364

4) OPA implements an exponential backoff based delay in case of non-200 response from the server
