### ISSUE TITLE
Update tutorials to make use of the management APIs

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3184]
The tutorials on openpolicyagent.org do not make use of management APIs. Instead they rely on several different mechanisms for managing policies, observing decisions, etc. The user experience would be much better if instead all of the tutorials followed a consistent model that made use of the management APIs.

For status and decision logging, it should be easy enough to enable the console loggers. For bundles, it's slightly more complex as it requires that users have some way of publishing their policies.

**Comment by ashutosh-narkar** [comment]
For bundles, we could point OPA to the Rego playground maybe ? Other option would be to bring up a local Nginx server as described in the [Bundle](https://www.openpolicyagent.org/docs/latest/management-bundles/#nginx) docs and use that.
Alternatively we could replace Nginx with a local python server to serve policies.

**Comment by anderseknert** [comment]
This is done for the [HTTP API](https://www.openpolicyagent.org/docs/latest/http-api-authorization/) docs already (using Nginx and console decision logger) and next up that I am gonna work on is the Docker docs, but that's blocked due to me not being able to push the 0.8 version I worked on to to Docker hub. Gonna have to revisit that now.

**Comment by ashutosh-narkar** [comment]
Thanks @anderseknert! I'll look into the Envoy and Kubernetes tutorials then.

**Comment by ashutosh-narkar** [comment]
PR for the Envoy tutorial - https://github.com/open-policy-agent/opa/pull/3775

**Comment by ashutosh-narkar** [comment]
PR for the Kubernetes tutorial - https://github.com/open-policy-agent/opa/pull/3814

**Comment by anderseknert** [comment]
Current status:
- [x] Kubernetes
- [x] Envoy
- [x] Docker
- [x] HTTP APIs
- [ ] Kafka (though this needs other updates first)
- [ ] SSH and sudo
- [ ] Terraform (though this uses `opa eval` so not really applicable, unless we introduce `opa run --exec` or similar)

**Comment by tsandall** [comment]
Closing in favour of #3962 #3963 and #3965
