### ISSUE TITLE
Signature V4 Signing for AWS API Gateway Endpoints

### ISSUE THREAD

**Issue by cogwirrel** [open-policy-agent/opa#3193]
## Feature Request

It would be really useful to be able to define services for bundles or decision logs that are fronted by API Gateway with IAM auth.

At the moment, the sigv4 signer [is hardcoded to use the service `s3`](https://github.com/open-policy-agent/opa/blob/2b59293753e4ae88b186777602b0c71399a93efb/plugins/rest/aws.go#L456). It would be great if the signing service could be specified in the service configuration, defaulting to `s3` to preserve backwards compatibility.

**Comment by anderseknert** [comment]
Thanks @cogwirrel! Seems like a useful addition.

**Comment by anderseknert** [comment]
@cogwirrel so if I understand you correctly, all that's needed here is to make the "s3" path component in `/s3/aws4_request` configurable? Feel free to submit a PR, or I can probably add this if you'd rather want that.

**Comment by cogwirrel** [comment]
@anderseknert yes that's right, I think everything else with the signing should be fine :) it'd need to be the 3 occurences of "s3" in that method.

If it's easy for you to add this that'd be great, but if you're low on time I should be able to get some time next week to send a PR (will need to learn a little Go too haha!)

**Comment by anderseknert** [comment]
Of course you should contribute the fix then! I too started my Go journey by contributing to this project :)
Should be fairly simple:

1) Introduce service name as config option (with s3 as default).
2) Replace hardcoded reference to service with above config option.
3) A test to verify that configured service name is used in signature.

I'd be happy to help you along the way. See the [contributing section](https://github.com/open-policy-agent/opa/#want-to-contribute-to-opa) of the README for how to best get started. And join the OPA Slack if you haven't already :)

**Comment by cogwirrel** [comment]
Sounds good, thanks! I'll let you know if I get stuck :)

**Comment by cogwirrel** [comment]
@anderseknert Would you be opposed to me sending a PR which uses the [AWS SDK for Go](https://github.com/aws/aws-sdk-go) to sign requests?

From some local testing, I discovered the existing signing algorithm doesn't work for API Gateway, and there are quite a few nuances with signing for the different AWS services or the different request headers used, so to save reimplementing all that complexity we can just delegate to the SDK's signer :).

I did find some objections in an older issue here: https://github.com/open-policy-agent/opa/issues/1600

I'm not super familiar with the Go ecosystem so I'm not sure how big an issue the mentioned "version conflicts" are, but it feels like the most robust and maintainable option would be to use the authoritative library for SigV4 signing :)

**Comment by anderseknert** [comment]
Yeah, since so many use OPA as a library, introducing new dependencies potentially introduces conflicting versions. For a library as common as the AWS SDK this is probably even likely to happen. So if we can avoid it we should. Is there any docs on how the signature is built when sending requests to the API Gateway as opposed to S3?

**Comment by cogwirrel** [comment]
Ok all good, yeah there are [some apigateway specific docs](https://docs.aws.amazon.com/apigateway/api-reference/signing-requests/), and I can use the SDK's implementation as a reference. Should have a PR for you shortly :)
