### ISSUE TITLE
Decision logger doesn't stop if there is nothing to log

### ISSUE THREAD

**Issue by istalker2** [open-policy-agent/opa#3197]
## Expected Behavior

logger.Stop() to flush the remaining unsent logs and then exit

## Actual Behavior

This only happens if there are unsent logs. Otherwise, Stop() will fait for the context expiration which
can be too long.

## Steps to Reproduce the Problem
```
ctx := context.WithDeadline(context.Background(), time.Now().Add(time.Hour))
logger.Start(ctx)
logger.Stop(ctx)
```

**Comment by anderseknert** [comment]
Fixed by https://github.com/open-policy-agent/opa/pull/3198
