### ISSUE TITLE
docs: Add Gloo Edge tutorial for the OPA-Envoy plugin

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#3199]
The OPA-Envoy plugin is integrated with Gloo Edge and a step-by-step tutorial is available [here](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/gloo-edge). We should add this tutorial to the [Envoy](https://www.openpolicyagent.org/docs/edge/envoy-introduction/) section of the OPA docs. We could update the existing tutorial to send the request body to OPA and use that in the OPA policy to make a decision.

**Comment by Parsifal-M** [comment]
Hey, assign this to me if you like, I have some extra bandwidth.

**Comment by anderseknert** [comment]
@Parsifal-M assigned to you 👍

**Comment by Parsifal-M** [comment]
Hey @anderseknert, I am looking at this today, which is the existing tutorial? I assume https://www.openpolicyagent.org/docs/edge/envoy-tutorial-standalone-envoy/? Is this what we want to update to have the Gloo edge docs? or do we make a separate page i.e. Tutorial: Gloo Edge?

Let me know! :smile:

**Comment by anderseknert** [comment]
@ashutosh-narkar is probably better equipped to answer that :)

**Comment by Parsifal-M** [comment]
> @ashutosh-narkar is probably better equipped to answer that :)

Oh of course sorry 😅

**Comment by ashutosh-narkar** [comment]
@Parsifal-M we have an example tutorial with Gloo Edge [here](https://github.com/open-policy-agent/opa-envoy-plugin/tree/main/examples/gloo-edge). Currently in the [Envoy](https://www.openpolicyagent.org/docs/edge/envoy-introduction/) section of the OPA docs, we have a standalone Envoy and Istio tutorial. We can create one more for Gloo Edge. Hope this helps.

**Comment by Parsifal-M** [comment]
Sorry I am still working on this 🙏😂

**Comment by Parsifal-M** [comment]
Hey Team :wave:, @ashutosh-narkar

I think this one can be closed right? :point_right: #5120 

:partying_face:
