### ISSUE TITLE
Do regular expressions support indexing for policy rules？

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3202]
As title, can the following rules be indexed？

```
package reg

allow {
  regex.match("x{10}", "xabc") = true
}
```

**Comment by tsandall** [comment]
@andyyumiao no, the rule indexer does not support regex.match expressions. Currently it supports equality expressions and `glob.match`: https://www.openpolicyagent.org/docs/latest/policy-performance/#use-indexed-statements
