### ISSUE TITLE
About indexer

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3205]
I know the rule indexer does not support regex.match expressions. Currently it supports equality expressions and glob.match, and i have two questions:
1. Will more data types(e.g. regex) be supported in the future? Are there any plans for the next step?
2. We want to expand the opa indexer. Is it possible for context data to be introduced into the index? If it is feasible, what problems may be encountered?

**Comment by srenatus** [comment]
> 1. Will more data types(e.g. regex) be supported in the future? Are there any plans for the next step?

This is not on our roadmap at the moment.

> 2. We want to expand the opa indexer. Is it possible for context data to be introduced into the index? If it is feasible, what problems may be encountered?

What does "context data" mean here? Before attempting to expand the indexer, have you considered other approaches? What problem do you want to solve?

**Comment by andyyumiao** [comment]
> > 1. Will more data types(e.g. regex) be supported in the future? Are there any plans for the next step?
> 
> This is not on our roadmap at the moment.
> 
> > 1. We want to expand the opa indexer. Is it possible for context data to be introduced into the index? If it is feasible, what problems may be encountered?
> 
> What does "context data" mean here? Before attempting to expand the indexer, have you considered other approaches? What problem do you want to solve?

@srenatus We want to use OPA for Big Data permission control, which mainly includes Hadoop HDFS directory permission and Hive table permission control (e.g. HDFS will have tens of millions of path data), so:
1. the 'context data' which i means is as bellow:
![contextdata](https://user-images.githubusercontent.com/11346379/109810504-90a15c80-7c64-11eb-855f-929b7d28bbee.jpg)
2.We want to keep uniform rule settings, and have a brief enough policy file. We have done simple design and testing, such as the following：
`package example

import data
default allow = false

allow{
	input.resource.jrn = resourceSelect[_]
}

allow {
	glob.match("jrn:bdpops:hdfs:table:/10k/jd_ad/app/*", ["~"], input.resource.jrn) = true
}

allow {
	glob.match("jrn:bdpops:hdfs:table:/10k/jd_ad/*/mogo", ["~"], input.resource.jrn) = true
}

resourceSelect [x]{
	x = data.rbac_permissions[input.subjects.name][input.actions][_]
}`
3.Our input data is like this：
`{
"subjects": {
	"type": "ROLE",
	"name": "BIZLINE_PRINCIPLE"
},
"resource": {
	"jrn": "jrn:bdpops:jsm:mall:*:web-element/account/index/addButton"
},
"actions": "PAGE_ELEMENT:VISIBLE"
}`
4.Our data is like this：
`
{
	"subjects": {
		"ROLE1": [
			"tom",
			"cook",
			"ext"
		],
		"ROLE2": [
			"bag"
		]
	},

	"rbac_permissions": {
		"ROLE1": {
			"VISIBLE": ["jrn:bdpops:hdfs:table:/evil/test/app/*"],
			"ENABLE": ["jrn:bdpops:hdfs:table:/10k/jd_ad/app/*"]
		},
		"ROLE2": {
			"VISIBLE": ["jrn:bdpops:hdfs:table:/10k/jd_ad/app/table1","jrn:bdpops:hive:table:/10k/jd_ad/m/*","jrn:bdpops:hive:table:/10k/jd_ad/app/table2"],
			"ENABLE": ["jrn:bdpops:hdfs:table:/evil/test/app/*"]
		}
	}
}
`
![89](https://user-images.githubusercontent.com/11346379/109811478-d90d4a00-7c65-11eb-9ce0-1a9eb1dde309.jpg)

5. With the growth of data, we get a linear performance, this is what I asked above. Is it possible to index the data, or is there any other solution?I don't know if I have described it clearly or not.

**Comment by anderseknert** [comment]
@andyyumiao I think we forgot about this one. Is it still an open question, or should we close it?

**Comment by andyyumiao** [comment]
> @andyyumiao I think we forgot about this one. Is it still an open question, or should we close it?

ok，closed it.
