### ISSUE TITLE
Rego linter

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3218]
We currently have a handful of compile-time checks that we'd like to enforce (but can't because they could break existing policies.) An alternative would be to roll out these checks as linting steps that are opted into by users. As a starting point we could expose a flag on the opa check and opa build commands that users could opt into (e.g., opa check --strict .) In the future, we could introduce an opt-in import (e.g., import future.strict)

The set of linting rules can be pulled from the lint label linked above.

Some potential benefits of a linter include:
- Spot common mistakes and bugs and suggest fixes.
- Help enforcing agreed upon rules and conventions in larger teams and organizations.
- Enforce style guides.
- Learning tool - get help writing idiomatic Rego without "manual" assistance.

It would be useful if we started compiling a list of potential linter rules. One example of such a rule could be to catch `!=` in iteration, as it almost never does what the author intended. Another one could be to prefer using sets over the `any`and `all` functions.. and so on.

**Comment by srenatus** [comment]
`concat` on sets (not arrays), see #3252

**Comment by anderseknert** [comment]
Some possible rules I wrote down elsewhere the other day. More to come :)

* Boolean rule (i.e. allow) without default condition.
* Calling non-boolean functions without using the return value.
* Use of deprecated functions (any, all, re_match, etc)
* Use of != in iteration.
* Constant conditions (i.e. 1 == 1)
* Warn on prohibitive cost of some operations, like excessive iteration.
* Warn on cases where indexing has been made impossible.

**Comment by dgreene1** [comment]
I think it would also be valuable to have linter rules for any maneuver that would cause performance issues in OPA. So for instance, I saw that @orweis recommended ([here](https://permit-io.slack.com/archives/C01RUUYV3TP/p1677767611213649?thread_ts=1677766522.856169&channel=C01RUUYV3TP&message_ts=1677767611.213649)) to

> Looking at the playground example -
You can save a lot by dropping (or moving to a separate hash map) the entityType and role fields you are not using, and are probably repeating a lot.

because apparently

> OPA is known to bloat loaded data in memory - as it loads it into objects;
You can improve that by changing the data schema and policy structure.

> And yes high volume of data, and inefficient structure will lead to bad performance.

Sorry if I didn’t provide enough info, I’m like 4 hours into understanding Rego. But as someone who is consider using Permit.io (with GitOps rego policies) at our company we would want our policies to not kill our SLAs.

**Comment by anderseknert** [comment]
That's a cool idea @dgreene1, but I think it would be difficult for a linter to know whether a datastructure could be remodeled for better performance without knowing about the type of queries the policy will deal with. The documentation on [OPA performance](https://www.openpolicyagent.org/docs/latest/policy-performance/) is a good starting point on the topic, but given how you're only hours in on your OPA journey, I would probably put that on hold until a little later :)

**Comment by agentreno** [comment]
There's a great number of good linter rules that could be derived just from the (rather excellent) academy training courses. @anderseknert also wrote [this great blog article](https://www.styra.com/blog/linting-rego-with-rego/) - would that still be the best way to implement such a linter? If there was a foundational codebase in place, the community could start contributing rules. I'd be looking to contribute to such a repository. 👍

**Comment by agentreno** [comment]
I've just seen https://github.com/open-policy-agent/opa/issues/4132 - it's great that it's being worked on and included in opa itself. But perhaps there's still value in creating a separate linter with community-contributed lint rules. Would be happy to hear your thoughts.

**Comment by anderseknert** [comment]
For sure, @agentreno! Are you on the OPA slack? I’d be happy to share some ideas with you there 🙂

**Comment by anderseknert** [comment]
I'm very happy to *finally* be able to close this issue as resolved! By introducing Regal, a linter for Rego with the ambitious goal of catching bugs and mistakes in policy **and** to help people learn Rego by providing pointers to best practices, good style and idiomatic constructs. Check it out!

https://github.com/StyraInc/regal
