### ISSUE TITLE
Static data in rego disappeared when running

### ISSUE THREAD

**Issue by gmywq** [open-policy-agent/opa#3222]
I wrote some static data in rego, and load to the opa to eval some inputs. The police works like a data store without any dynamic "data in OPA".

Recently, the users inform us that some lists are empty, and yes, I implement the api based on OPA.

It's pretty weird.

The response from OPA suddenly disappeared after several days of working fine.

And the most terrify thing is that I can't even reproduce it because I can't figure out the situation.

I'm wondering is the a cache logic under the rego? 

And I have two questions:
1. How is the rego's lifecycle ?
2. Does the GC happen in OPA affect eviction of rego inside the OPA? 

I's using the docker hosted OPA with version 0.22.0.

**Comment by srenatus** [comment]
Can you share some (MWE of) your policy there? It does sound quite odd, nothing "static" declared in rego should ever _disappear_.

I'm assuming you're querying some virtual document. Whatever is returned what that doesn't depend on the input and has no rule body that could ever fail to evaluate should _always_ return the same thing.

**Comment by gmywq** [comment]
Yes! Exactly what you pointed.

Policy like:
basic.rego:
```
package public.basic

services = ["Activity", "Support", "BlockList", "ITEntitySetting"]

```
userA.rego:
```
package service.user_a

import data.public.basic.services as services

denied_services = ["Support", "BlockList"]

opened_services = diff {
 	diff :=  services - denied_services
}
```

userB.rego
```
package service.user_a
import data.public.basic.services as services

denied_services = ["Support"]

opened_services = diff {
 	diff :=  services - denied_services
}

```
And let's suppose userA.rego as policy id: user_a, userB.rego as policy id: user_b.

The request happens now like following:

GET v1/data/user_a/opened_services
return ["ITEntitySetting"]

GET v1/data/user_b/opened_services
return ["Activity", "BlockList", "ITEntitySetting"]

The second one is correct right? I don't know what's the reason for the first one.

And more detail is, I post the basic.rego first before user_a.rego, the origin content is:

`services = ["Support", "BlockList", "ITEntitySetting"]`

After some days, I add a new item to the services array "Activity", and refresh the policy "public.basic".

And I post a new policy userB.rego. Since I got the correct answer from "v1/data/user_b/opened_services", I thought that works fine, and no user_a inform us something wrong.

But the current situation is user_a missed the "Activity".

**Comment by srenatus** [comment]
Just to rule out the obvious, your `userB.rego` example has `package services.user_a` -- I'd assume it's a copy-paste mistake when compiling the example, isn't it?

**Comment by tsandall** [comment]
It's also worth noting that those examples don't compile. The `-` operator is not supported on arrays. Presumably the actual policy uses sets however it's really hard to point to an issue in OPA given the possibility for user error here...

**Comment by gmywq** [comment]
[regos.zip](https://github.com/open-policy-agent/opa/files/6098372/regos.zip)
Sorry for my poor representation, I'm not good at English.

But the problem still got me. I've attached the regos which are using in production. Please take a look~

Now, let me detail the difficulty agian:

I got **_tenant 789978819485237248 's open_services response array without "Activity",_** 
`[
  "OrganizationalStructure",
  "EmployeeManagement",
  "AttendanceManage",
  "WorkFlowSetting",
  "AttendanceSetting",
  "VacationSetting",
  "EmployeeTurnover",
  "OrganizationalInformationSetting",
  "OnBoarding",
  "Support",
  "SpecialLeaveSetting",
  "NoticeManagement",
  "AuthorityManagement",
  "ContingentBillApproval",
  "RecruitmentApplicationApproval",
  "RecruitmentInformationRegistrationApproval",
  "RecruitmentInformationUpdateApproval",
  "TeamOverworkApproval",
  "TeamLeaveApproval",
  "TemporaryTransfersApproval",
  "WorkforceApplication",
  "WorkforceReceive",
  "WorkforceRegistration",
  "WorkforceInformationUpdate",
  "Bill",
  "WorkforceManagement",
  "ProjectLibrary",
  "LeaveManage",
  "DateReminderSetting",
  "TeamOvertime",
  "TeamLeave",
  "FinanceBudget",
  "PersonnelBudget",
  "Scheduling",
  "SchedulingOfficer",
  "BasicSetting",
  "DepartmentTemporaryTransfer",
  "TemporaryTransferEmployeeManage",
  "TemporaryOrder",
  "TemporaryReceiveOrder"
]`
and the **_tenant 780384617910763520's with "Activity"_** 
`[
  "OrganizationalStructure",
  "EmployeeManagement",
  "AttendanceManage",
  "WorkFlowSetting",
  "AttendanceSetting",
  "VacationSetting",
  "EmployeeTurnover",
  "OrganizationalInformationSetting",
  "OnBoarding",
  "Support",
  "HealthReportRecord",
  "SpecialLeaveSetting",
  "ITEntitySetting",
  "PersonnelInfoReport",
  "ITDeclarationPayment",
  "CommissionDashboard",
  "PerformanceKanban",
  "Commissionanban",
  "PerformanceDataManagement",
  "PBOManagement",
  "MatrixManagement",
  "EvaluationGroupManagement",
  "KPIManagement",
  "MetricManagement",
  "EvaluationCycleManagement",
  "NoticeManagement",
  "AuthorityManagement",
  "ContingentBillApproval",
  "RecruitmentApplicationApproval",
  "RecruitmentInformationRegistrationApproval",
  "RecruitmentInformationUpdateApproval",
  "TeamOverworkApproval",
  "TeamLeaveApproval",
  "TemporaryTransfersApproval",
  "WorkforceApplication",
  "WorkforceReceive",
  "WorkforceRegistration",
  "WorkforceInformationUpdate",
  "Bill",
  "WorkforceManagement",
  "WorkforceTicket",
  "Workforce",
  "WorkforceBill",
  "WorkforceDispatch",
  "ProjectLibrary",
  "LeaveManage",
  "DateReminderSetting",
  "PayrollBusinessItem",
  "EmployeeSalaryInformationPermission",
  "TeamOvertime",
  "TeamLeave",
  "ExpenseApproval",
  "ClaimRecord",
  "ClaimGroupSettings",
  "ClaimSettings",
  "ClaimManagement",
  "PayRollReport",
  "PayRollManage",
  "SalaryCalculation",
  "SalaryItemSetting",
  "SalaryAccountSetting",
  "FinanceBudget",
  "PersonnelBudget",
  "TargetManagement",
  "Scheduling",
  "SchedulingOfficer",
  "BasicSetting",
  "CommissionOrganizationLevelManagement",
  "DepartmentTemporaryTransfer",
  "TemporaryTransferEmployeeManage",
  "TemporaryRequirementOrder",
  "TemporaryOrder",
  "TemporaryAssignOrder",
  "TemporaryReceiveOrder",
  "ActivityConfirm",
  "Activity",
  "ActivityAllocation",
  "RoleManagement",
  "CommissionETLConvert",
  "IndicatorManagement",
  "CommissionManagement",
  "ActivityCalc",
  "ActivityCalcReport",
  "BlockList",
  "RecruitStatistics"
]`
with **_the same input {"platform": "web"}_** and I've taken carefully about these three rego's policy ids as seperate namespace. 



Since the app_feature stores all the "**_detail.code_**" as static data structure, so I named the issue like this last weekend. Sorry again for that if bother you guys. 🙏

**Comment by gmywq** [comment]
And more troublesome situation‘ve taken twice since last two months according to out users feedback(that's awful😟).

Both the 789978819485237248 and 780384617910763520's response of "open_services" was **empty**.
I'll upload the logs after some checks which can show the **resp_bytes** suddenly going down.

Please think about my last two questions I've asked last weekend, it might help me out.

**Comment by gmywq** [comment]
I know why...
Some teammate change the refactor the file "app_feature.rego" and the new namespace doesn't upgrade in the reference rego.
Sorry for bothering you again.

**Comment by tsandall** [comment]
ah! that's explains it--looking at those .rego files, it's clear that that the imports are referring to data that does not exist. Fixing the imports should fix the problem. Closing this issue as there is nothing left to do.
