### ISSUE TITLE
Add OPA Playground evaluate, publish commands to the cli

### ISSUE THREAD

**Issue by developer-guy** [open-policy-agent/opa#3224]
It would be nice if we can add playground capabilities to the OPA CLI, for example, publish, also, open the local folder on the playground page.

## Expected Behavior
```bash
$ opa publish --rego policy.rego --input input.json --data data.json
https://play.openpolicyagent.org/p/pluFLZm5T7

$ opa playground --policy-dir ./policy <-- maybe, we can define a folder template to be able to open this folder on the playground, for example, it has to include rego, input, and data files.
```

## Actual Behavior
There is no support for that kind of scenario.

## Additional Info
The Rego Playground has many useful APIs to use it.
https://play.openpolicyagent.org/v1/share <-- get a shareable link
https://play.openpolicyagent.org/v1/data <-- evaluate the policy against data and input

we can use them in the CLI to add that kind of capabilities.

**Comment by developer-guy** [comment]
@srenatus do you think it makes sense ? 🙏

**Comment by anderseknert** [comment]
@developer-guy I don't think we'll want to couple the OPA executable to the Rego playground. Is there are any particular features in the playground you find missing in the editor plugins for VS Code or IntelliJ IDEA?

**Comment by ashutosh-narkar** [comment]
Closing for now. We can re-visit in future based on use-case, demand etc.
