### ISSUE TITLE
Support TLS minVersion and maxVersion in opa server so that it can disable TLS 1.0 and 1.1

### ISSUE THREAD

**Issue by shaoxt** [open-policy-agent/opa#3226]
## Expected Behavior

OPA server should allow to disable TLS 1.0 and 1.1 by either configuration or argument.

## Actual Behavior
HTTPS server supports the TLS minVersion and maxVersion, but opa server doesn't expose them in arguments or configuration.

## Steps to Reproduce the Problem

Any OPA version.

**Comment by srenatus** [comment]
That's a great idea. Thanks for bringing it up.

**Comment by srenatus** [comment]
We could also default to denying 1.0 and 1.1 unless configured otherwise. What's the use of a max version here? I'm not sure i understand the situation where you'd want to restrict the upper bound 🤔

**Comment by kale-amruta** [comment]
@srenatus @anderseknert is this something that I can take up ?

**Comment by anderseknert** [comment]
@kale-amruta I don't see why not 😃 As @srenatus said I don't know if a max version is really needed, but a new `--tls-min-version` option seems useful to me.
