### ISSUE TITLE
WASM: Reducing compiled file size by opting-out of native built-in implementations

### ISSUE THREAD

**Issue by helmutkian** [open-policy-agent/opa#3230]
Is there an official recommendation on reducing the size of the outputted WASM file or controlling compilation to exclude natively implemented builtins so that an external implementation can be provided?

## Expected Behavior

A way to determine which builtins implemented natively in WASM are included in the outputted WASM or can be replaced by external implementations. 

## Actual Behavior

A Rego file of 60 rules using builtins such as `net.cidr_contains`, `regex.match`, `glob.match` compiles to `policy.wasm` of 405K size.

## Additional Info

Larger WASM files are not an impediment when the module is only loaded once, but becomes particularly important when deploying to a serverless compute platform or any other environments where fast load times are critical.

**Comment by srenatus** [comment]
Thanks for reporting this! 😃

I've got some work that's almost good to go related to this in https://github.com/open-policy-agent/opa/pull/3206. By any chance, could you have a look and let me know what you think?

Since we've got this issue now, recording the need, I'll try to get this merged Tuesday or Wednesday. ☺

**Comment by srenatus** [comment]
I'm also curious, can you share more about what you are implementing there? Which platform, language, runtime... =)

**Comment by helmutkian** [comment]
I am using JavaScript on Deno, specifically within Deno Workers.

@srenatus Good work! From what I can tell, your changes remove functions that are not used in the policy. That will certainly help, and I'm curious to see the effect it has on my generated WASM file size. 

What I was specifically asking about was whether it was possible to exclude builtins' native WASM implementations even if they are included in the policy, and importing them from the host runtime into the WASM rather than having them automatically bundled.

Let's say I have a simple policy that uses `regex.match`:

````rego
package example 

match {
   regex.match(input.pattern, input.str)
}
````

I want to compile it to WASM, but not include the WASM code for `regex.match` and instead import it from the host runtime:

````
$ opa build -t wasm --stub="regex.match" -e example/match policy.rego
````

**Comment by srenatus** [comment]
Ah I see. Thanks for sharing, that makes sense. 💡

Say, do you depend on the naming of the builtins? I believe there could be a decent workaround in using the capabilities to declare another builtin, "hostregex.match", use that in your policy, and in the wasm _that_ won't be using the native implementation but end up in calling the host function.

**Comment by srenatus** [comment]
Please see that issue ☝️ The workaround mentioned wouldn't help because of that.

Another thing to try would be to use [wasm-snip](https://github.com/rustwasm/wasm-snip) and wasm-opt (binaryen) on the resulting Wasm files. (We'd be happy to incorporate any such optimizations natively, too!)

**Comment by srenatus** [comment]
With the fix for #3250 merged (any minute now), you should be able to workaround this as follows:

Add whatever builtin you'd like to replace to `capabilities.json`, use it in your policy code, and it'll be called from the host using the normal mechanism if you use the produced wasm file.

With `capabilities.json` changed like this,

```diff
diff --git a/capabilities.json b/capabilities.json
index b9046a6e..444d644c 100644
--- a/capabilities.json
+++ b/capabilities.json
@@ -1,5 +1,22 @@
 {
   "builtins": [
+    {
+      "name": "myregex.match",
+      "decl": {
+        "args": [
+          {
+            "type": "string"
+          },
+          {
+            "type": "string"
+          }
+        ],
+        "result": {
+          "type": "boolean"
+        },
+        "type": "function"
+      }
+    },
     {
       "name": "abs",
       "decl": {
```

and this `myregexp.rego`,
```rego
package test

main { myregex.match("/foo/", input) }
```

the call
```
opa --capabilities capabilities.json build -t wasm -e test/main myregexp.rego && tar xzvf bundle.tar.gz /policy.wasm
```

produces a wasm module of 116K, and depends on the host runtime to provide `myregex.match`.

As mentioned before, this only works if you're OK with changing your rego code for this.

**Comment by helmutkian** [comment]
The merged changes made a huge difference. Thanks for your work there!

Without replacing the builtins, the resulting WASM file was reduced to 333K. Replacing `regex.match` and `glob.match`, reduced it down to 124K and resulted in a significant performance improvement in loading the module.

From my perspective, this issue is resolved.

**Comment by srenatus** [comment]
Thanks for your response. I'll close this.

The stuff you've done isn't open source, by any chance? I'd love to have a look :)

**Comment by helmutkian** [comment]
@srenatus Unfortunately, the work is proprietary so it can't be shared yet. Perhaps a write up or presentation may come in the future.

**Comment by srenatus** [comment]
@helmutkian I've just stumbled upon this once again -- By any chance, are there write ups to share?

**Comment by jondot** [comment]
@srenatus we've bumped into this as a design limit, still working on finding a creative solution to compiled WASM size (vs plain rego size). I can share on zoom what we're doing and if that's interesting we can do a write up.

**Comment by srenatus** [comment]
Yeah let's chat in the new year. Are you on the community slack?
