### ISSUE TITLE
Regression due to recent big number change

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3262]
The fuzzer has identified a regression that appears to be caused by the recent big number change. For example, this input will run for a very long time (whereas in 0.26.0 there was no issue):

```
docker run openpolicyagent/opa:0.27.0 eval 10245423601e680507880
```

As a side note, the limit we place on numbers in the parser is not effective in this case: https://github.com/open-policy-agent/opa/blob/master/ast/parser.go#L893. The exponent returned by `MantExp` is dependent on the internal representation. In this case, the exponent is zero and the mantissa is +Inf when given a new(big.Float).

**Comment by tsandall** [comment]
@koponen-styra @srenatus any thoughts?

**Comment by srenatus** [comment]
> As a side note, the limit we place on numbers in the parser is not effective in this case: https://github.com/open-policy-agent/opa/blob/master/ast/parser.go#L893.

That would have been unrelated to the big.Rat change -- i.e. before, that input would have crept past the check, too, but the outcome was different, correct?

**Comment by tsandall** [comment]
That's correct.
