### ISSUE TITLE
About 'eval_conflict_error: functions must not produce multiple outputs for same inputs'

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3269]
As title, How to make a function return an array with temporary variables, for example:

**z(x) = y{
	some i
	role = someArrayModule2
	data.someArrayModule1[i][x][_] == role[_]
	y = data.someArrayModule1[i]
}**

The above module returns an error：functions must not produce multiple outputs for same inputs

**Comment by anderseknert** [comment]
Hi @andyyumiao 👋 Could you provide a playground link with a full example? The function included above has some invalid syntax, and depends on values not defined here. Either way, if you'd want to build a list and have that returned, you'd most likely want to use an [array comprehension](https://www.openpolicyagent.org/docs/latest/policy-language/#array-comprehensions).

**Comment by andyyumiao** [comment]
> Hi @andyyumiao 👋 Could you provide a playground link with a full example? The function included above has some invalid syntax, and depends on values not defined here. Either way, if you'd want to build a list and have that returned, you'd most likely want to use an [array comprehension](https://www.openpolicyagent.org/docs/latest/policy-language/#array-comprehensions).

@anderseknert yes, array comprehension can resolve the issue, thanks for the reply!
