### ISSUE TITLE
`opa build -t wasm` doesn't generate `bundle.tar.gz`

### ISSUE THREAD

**Issue by onelittlenightmusic** [open-policy-agent/opa#3270]
`opa build` doesn't seem to be able to generate `bundle.tar.gz` after 0.27.0. Before 0.26.0, it works well.

## Expected Behavior

```sh
opa build -t wasm -e hello/hello hello.rego
(no error and generated bundle.tar.gz)
```

## Actual Behavior

Using v0.27.0 or later
```sh
bin/opa0.27.0 build -t wasm -e hello/hello hello.rego
error: compiler ABI version not in capabilities (have [], want {1 1})
```

Using v0.26.0, this command works.
```sh
bin/opa0.26.0 build -t wasm -e hello/hello hello.rego
(no error)
```

## Steps to Reproduce the Problem

- Create a file `hello.rego`

```rego
package hello

default hello = ""

hello = rtn {
    m := input.message
    rtn := concat("", ["hello, ", m])
}
```

- Following the document, run this command.
https://www.openpolicyagent.org/docs/latest/wasm/#compiling-policies

```sh
opa  build -t wasm -e hello/hello hello.rego
```

Environment
- MacOS 11.2.3 (big sur)
- Each version of binaries were separately downloaded from release page.
Thank you, all the community!!

## Additional Info

I am not sure if this is related to #3264 or not..

**Comment by srenatus** [comment]
You'll have to provide a capabilities json of the target version. Your cli executable doesn't have wasm enabled so it won't build what it cannot run.

**Comment by onelittlenightmusic** [comment]
@srenatus Thank you so much for your advice! You saved my day. I downloaded the following file to the same directory.
https://github.com/open-policy-agent/opa/blob/master/capabilities/v0.27.1.json
And I ran this command.
```sh
opa build -t wasm -e hello/hello hello.rego --capabilities v0.27.1.json
```
Finally, I got bundle.tar.gz correctly. I appreciate that.

I guess a description about necessity of capacilities json can be added in the following document. What do you think about it?
https://www.openpolicyagent.org/docs/latest/wasm/#compiling-policies
```
# download
curl -L -o  v0.27.1.json https://raw.githubusercontent.com/open-policy-agent/opa/master/capabilities/v0.27.1.json
opa build -t wasm -e example/allow example.rego --capabilities v<version>.json
```

**Comment by srenatus** [comment]
Yup there's definitely a documentation need here. Would you want to contribute a note there or would you prefer if I did that? 😃

**Comment by srenatus** [comment]
Nevermind the docs, we'll fix this in code 😅

**Comment by onelittlenightmusic** [comment]
@srenatus Thank you for your comment! I am sorry for late response. If I have a chance, I would like to contribute. I am not familiar document structure, but I found a likely document in the following document. Is this correct? If so, I will try PR in a few days.
https://github.com/open-policy-agent/opa/blob/master/docs/content/wasm.md
I feel like that the concept of capabilities is vaster than wasm itself. I guess in the future, there might be a documentation need of vast concept of capabilities (is there already such a document?). Anyway, I think at least the description in wasm is needed, so I will make PR.

**Comment by srenatus** [comment]
>  Anyway, I think at least the description in wasm is needed, so I will make PR.

Thank you! As hinted on above, I'll put a PR out for changing the default behaviour here. (Next thing, tomorrow at the latest.)

**Comment by onelittlenightmusic** [comment]
Oh, I see. Great! Default behavior change is much better. There will be no need to amend document. No need to hurry. Thank you for all!
