### ISSUE TITLE
OPA does not support EC PKCS8 keys

### ISSUE THREAD

**Issue by andrehaland** [open-policy-agent/opa#3283]
## Expected Behavior
OPA should be able to use EC PKCS8 private keys.

## Actual Behavior
OPA parses EC PKCS1 but fails parsing EC PKCS8 keys.

## Steps to Reproduce the Problem
Configure OAuth2 JWT auth with an EC PKCS8 PEM private key.

## Additional Info
Support for RSA PKCS8 keys were added in https://github.com/open-policy-agent/opa/pull/3117, but when configuring with an EC PKCS8 key the following error is returned:
`request failed: x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)`

Relevant code snippet:
https://github.com/open-policy-agent/opa/blob/99c81cab7c754f9b0f62e77a300f7455d3bcea2b/internal/jwx/jws/sign/sign.go#L47-L57

**Comment by anderseknert** [comment]
Thanks for reporting @andrehaland. That would be a good addition 👍 #3117 used GCP as the test target, and they only provide RSA keys. Would you want to submit a PR?

**Comment by andrehaland** [comment]
> Would you want to submit a PR?
Currently I am busy with other work, so if anybody else wants to pick it up that would be great. Otherwise I can pick it up later when I got time
