### ISSUE TITLE
force_cache property not caching requests

### ISSUE THREAD

**Issue by mattgogerly** [open-policy-agent/opa#3284]
## Expected Behavior
Requests made using `http.send()` are cached when the `force_cache` property is enabled, even if the server returns a `no-store` response.

## Actual Behavior
Requests are not being cached on 0.25.2 using the `force_cache` property.

## Steps to Reproduce the Problem
We have a SpringBoot API returning the below headers. The cache-control headers are the default Spring Security headers, and it's strongly recommended these aren't disabled.  To bypass this we're using force_cache in OPA:

```
x := http.send({
    "method": "GET",
    "url": sprintf("http://example.com/endpoint?id=%v", [id]),
    "timeout": "15s",
    "force_cache": true,
    "force_cache_duration_seconds": 3600
})
```

This call is made by a number of deny policies and can sometimes take a while to return, but the data returned doesn't change frequently, so we want to cache it. However we see the requests being made every time the policies are evaluated.

```
 cache-control: no-cache, no-store, max-age=0, must-revalidate 
 content-encoding: gzip 
 content-type: application/json 
 date: Tue, 16 Mar 2021 18:02:00 GMT 
 expires: 0 
 pragma: no-cache 
 server: envoy 
 status: 200 
 strict-transport-security: max-age=31536000 ; includeSubDomains 
 vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers, Accept-Encoding 
 x-content-type-options: nosniff 
 x-envoy-upstream-service-time: 1250 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block
```

**Comment by ashutosh-narkar** [comment]
The cache uses the entire request (ie. input to `http.send`) as the cache key. In your example above, does the URL change ?

**Comment by mattgogerly** [comment]
No, this is happening even if the id is the same (i.e. the whole url is constant)

**Comment by anderseknert** [comment]
Looks like the `Expires: 0` header could be causing this. Reproduced with the following:

**policy.rego**
```rego
package policy

headers := {
	"cache-control": "no-cache, no-store, max-age=0, must-revalidate",
	"content-type": "application/json",
	"expires": "0",
	"pragma": "no-cache",
}

headers_encoded := {k:v | h := headers[k]; v := urlquery.encode(h)}

query := concat("&", [q | v := headers_encoded[k]; q := concat("=", [k, v])])

r := http.send({
    "method": "get",
    "url": concat("", ["https://www.httpbin.org/response-headers?", query]),
    "force_cache": true,
    "force_cache_duration_seconds": 3600
})
```
`opa run --server --watch policy.rego`

**with expires: 0**
```shell
$ curl -s localhost:8181/v1/data/policy/r | jq -r .result.headers.date
[
  "Tue, 16 Mar 2021 21:01:48 GMT"
]
$ curl -s localhost:8181/v1/data/policy/r | jq -r .result.headers.date
[
  "Tue, 16 Mar 2021 21:01:51 GMT"
]
```
(i.e. date is incremented == not cached)

**without expires: 0**
```shell
$ curl -s localhost:8181/v1/data/policy/r | jq -r .result.headers.date
[
  "Tue, 16 Mar 2021 21:02:50 GMT"
]
$ curl -s localhost:8181/v1/data/policy/r | jq -r .result.headers.date
[
  "Tue, 16 Mar 2021 21:02:50 GMT"
]
```
(date header remains the same)

**Comment by ashutosh-narkar** [comment]
When we parse the expires header and it has an invalid date like 0, we return an error. As a result, we don't use the inter-query cache. We should update the parsing logic for the expires header. I'll add a fix for this.
