### ISSUE TITLE
Tooling to support package renaming

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3290]
There are a few use cases that would benefit from tooling in OPA proper to support package renaming. One is simple refactoring (e.g., a user wants to rename some packages in their .rego files and would like to have all references in the set of .rego files updated consistently.) Another use case would be isolation of policies from different groups. The constraint framework includes tooling that does something like this today.

Minimally, this tooling could be exposed via Go but it could also be included as part of a separate tool.

```
opa refactor move --path=<from>:<to> <file-path> [<file-path> [...]]
```

The `--path` flag could be specified multiple times.

At the golang level, the API would be something like:

```
refactor.Move(map[string]*ast.Module, srcDst map[string]string) (map[string]*ast.Module, error)
```

### Rename a package

input:
```rego
package lib.foo
```

operation:
`move(..., {"data.lib.foo": "data.baz.foo"})`

output:
```rego
package baz.foo
```

### Rename a prefix for one or more packages

input 1:
```rego
package lib.foo
```

input 2:
```rego
package lib.bar
```

operation:
`move(..., {"data.lib": "data.hidden"})`

output 1:
```rego
package hidden.foo
```

output 2:
```rego
package hidden.bar
```

### Inject a prefix

input 1:
```rego
package a.b
p { data.x.q }
```

input 2:
```rego
package x
q = true
```

operation:
`move(..., {"data": "data.deadbeef"})`

output 1:
```rego
package deadbeef.a.b
p { data.deadbeef.x.q }
```

output 2:
```rego
package deadbeef.x
q = true
```

### With keyword

input 1:
```rego 
package a.b

import data.x.q as r

p { r with data.foo as 7 }
```

input 2:
```rego
package x

q { data.foo == 7 }
```

operation:
`move(..., {"data": "data.acme"}) <-- inject a prefix`

output 1:
```rego
package acme.a.b

import data.acme.x.q as r

p { r with data.acme.foo as 7 }
```

output 2:
```rego
package acme.x

q { data.acme.foo == 7 }
```

### Invalid input: constant prefix too short

input 1:
```rego
package foo.bar

p = 7
```

input 2:

```rego
package a

p = data.foo
```

operation:
`move(..., {"data.foo.bar": "data.baz"}`)

error:
```
input 2.rego:3: `data.foo` prefix too short
```

The problem here is that the move operation would relocate `data.foo.bar` but not other documents under `data.foo` (e.g., `data.foo.baz`, `data.foo.qux`, etc.) Since we can't relocate everything under `data.foo`, the result of `p = data.foo` would be different if the move operation were to be applied.

### Invalid output: conflicting rule definitions

input 1:
```rego
package a.b

p[1]
```

input 2:

```rego
package b

p = 7
```

operation:
`move(..., {"data.a": "data"})`

error:
```
<this should be caught by compiling the resulting modules after the move operation>
```

## Notes

* Move operations could produce invalid Rego (see **conflicting rule definitions** example above). To prevent this, we can run the compiler on the result of the move operation before returning the result to the user. Don't return the compiled policies, just use the compiler to validate the result.
* Move operations could produce valid Rego that produces incorrect results (see **constant prefix too short** example above). To prevent this, we can check each reference in the policy against the srcDst mapping. If the `ConstantPrefix()` of any reference in the policy is a prefix of (and not equal to) a src ref in the srcDst mapping, the move operation should fail.
* In terms of implementation, this should amount to using the `ast.Transformer` on `ast.Ref` nodes in the input ASTs. The transform function should simply replace matching ref prefixes using the src-dst mapping.

**Comment by timothyhinrichs** [comment]
It would be useful to allow path prefixes in <from>:<to> as well....

`
# prefix all packages with `foo.bar`
opa refactor rename-package --package=data.:data.foo.bar.
`
