### ISSUE TITLE
OPA Metrics

### ISSUE THREAD

**Issue by HarshitaJha** [open-policy-agent/opa#3295]
This is a question, not an issue.
I am trying to monitor the OPA running on my K8s cluster via prometheus and grafana. I have observed that OPA exposes only go metrics and http metrics on its metrics endpoint. I need some clarification on this. Does OPA expose any OPA specific metrics like no of times a policy was applied or any rego metrics along with these?

**Comment by srenatus** [comment]
> Does OPA expose any OPA specific metrics like no of times a policy was applied or any rego metrics along with these?

The metrics exposed are per-query, see https://www.openpolicyagent.org/docs/latest/rest-api/#performance-metrics.

There's no counters like "number of times a policy was

**Comment by srenatus** [comment]
sorry misclicked 😬

**Comment by srenatus** [comment]
Does this capture what you're looking for? 👉 https://github.com/open-policy-agent/opa/issues/1578

**Comment by HarshitaJha** [comment]
Thanks @srenatus . Can these metrics be observed on Prometheus? Also, are grafana dashboards available for them?

**Comment by srenatus** [comment]
No, that issue I've pointed to is about exposing the per-query metrics we have right now in some way such that prometheus/grafana could have them available. So right now, that isn't the case, I'm afraid.

**Comment by tsandall** [comment]
@HarshitaJha the existing HTTP metrics you're referring to tell you how long the server handler that executes policy queries is taking. Why is that not sufficient?

**Comment by HarshitaJha** [comment]
@tsandall the existing go runtime metrics are good. However, in addition to those I am looking for some metrics which can give an idea about the operations which OPA is performing. For my task, I need such metrics to be visible on prometheus and grafana for easy monitoring of OPA.

**Comment by tsandall** [comment]
@HarshitaJha it sounds like you're not sure what you want/need to monitor.

I recommend that you monitor the existing `http_request_duration_seconds` metric. That will tell you how long the different server handlers are taking. Policies queries are typically executed via `POST v1/data` so you'd take the `http_request_duration_seconds` metric with keys `handler=v1/data` and `method=post` to monitor policy evaluation time.

**Comment by HarshitaJha** [comment]
Thanks @tsandall. I am looking for metrics like number of policies that are present, the number of objects that have been modified by the mutation webhook, etc. 
Also, can you please tell me if there are metrics for kube-mgmt? Are they exposed on the metrics endpoint to be scraped by Prometheus?
