### ISSUE TITLE
units.parse_bytes does not support float numbers

### ISSUE THREAD

**Issue by andy-paine** [open-policy-agent/opa#3297]
## Expected Behavior
`units.parse_bytes("1.2KB")` returns `1200`

## Actual Behavior
`units.parse_bytes("1.2KB")` fails

## Steps to Reproduce the Problem
* Run `units.parse_bytes("1KB")`
* Observe correct `1000` returned
* Run `units.parse_bytes("1.2KB")`
* Observe failure

https://play.openpolicyagent.org/p/rrMSMmZ2QH

* OPA version: 0.27.1

## Additional Info
I think Kubernetes is likely converting requests/limits (I assume this is the main use of this builtin) into a whole number before sending to Gatekeeper so this may not have been picked up on before. We are using OPA in the context of [Concourse](https://concourse-ci.org/) which isn't performing this conversion so we need to be able to handle float numbers such as `1.2KB`

**Comment by tsandall** [comment]
Thanks for filing this @andy-paine. Indeed, `units.parse_bytes` does not support floating point values. The code that does the string parsing for the `units.parse_bytes` function is here: https://github.com/open-policy-agent/opa/blob/134ed9b50f2ac8a74cf9993a3cafd36817a3aeda/topdown/parse_bytes.go#L108. I think we can extend it fairly easily to handle floating point values. We should be careful to deal with edge cases like multiple periods, empty ones (`units.parse_bytes(".5KB")`), etc.

**Comment by andy-paine** [comment]
Happy to take this on myself. Do you think fractional bytes should be an error or should we use the default behaviour of go to round a `float64` down to the nearest `int64` (effectively calling `math.Floor` on it)?

**Comment by andy-paine** [comment]
Hmm I think this will have to just round it down as the the `KiB,`MiB` etc. numbers are base 2 and something like `3.1GiB` (which seems like a totally reasonable number) ends up as `3328599654.4B` when converted.
