### ISSUE TITLE
Possibility to shorten package name

### ISSUE THREAD

**Issue by onelittlenightmusic** [open-policy-agent/opa#3318]
## Expected Behavior
#3290 is also an awesome idea!! 
I feel like it would be more useful to allow shorter reference to rules in our .rego files. 
I wonder whether there might be some syntax sugar like `from <package> import *` in python. 
For example, `--import "data.main.*"`.

```rego
package main
<rule a>
<rule b>
```

I wrote `data.main.a ... data.main.b ...` to use these rules, 
and every time I wrote "data.main.<anything>" to do that. 
But if we could write like,
```
opa eval -d main.rego --import "data.main.*" 'a ... b ...'
```
tooling could be easier.
If there is an existing method, could you please let me know how to do that?

If #3290 is solved, I thought we could write `--package data.main.:.` (I am not sure).

## Actual Behavior

At this time, `opa eval --import "data.main.*"` returns this parse error.

```
rego_parse_error: expected path
	import data.main.*
```

Thank you community!

**Comment by tsandall** [comment]
@onelittlenightmusic one thing you can today is import the parent package and then refer to the rules through the parent. For example, suppose you have:

```rego
package acmecorp.foo.bar.baz

# rule a
a { ... }

# rule b
b {... }
```

And you want to refer to those rules in another package in many places w/o repeating `data.acmecorp.foo.bar.baz.a`, `data.acmecorp.foo.bar.baz.b`, etc. everywhere. Instead, you can write (in the other place):

```rego
import data.acmecorp.foo.bar.baz
```

And now you can refer to `baz.a`, `baz.b`, etc.

If `baz` already exists in the scope of the caller, you can write:

```rego
import data.acmecorp.foo.bar.baz as other
```

And then refer to `other.a`, `other.b`, etc.

Does this solve your use case?

**Comment by onelittlenightmusic** [comment]
@tsandall  I appreciate your great explanations! Yes. My use case was solved by your solution. I feel `as other` is also useful. I can shorten reference like `import data.***.something as lib'. I found an option `opa eval --import` also accepts the same writing like `--import 'data.acmecorp.foo.bar.baz as other'`. Well designed:)  I close this issue. Thank you again 😄
