### ISSUE TITLE
Availability of metrics for kube-mgmt

### ISSUE THREAD

**Issue by HarshitaJha** [open-policy-agent/opa#3322]
This is a question, not an issue.
I am trying to monitor the OPA running on my K8s cluster via prometheus and grafana. Can you please tell me if there are metrics for kube-mgmt? Are they exposed on the metrics endpoint to be scraped by Prometheus?

**Comment by anderseknert** [comment]
Questions around kube-mgmt are better asked in that [project](https://github.com/open-policy-agent/kube-mgmt). Looking at the code of that though, there's currently no metrics exposed as far as I can see.

**Comment by HarshitaJha** [comment]
Thanks @anderseknert

**Comment by anderseknert** [comment]
Closing here as question has been [asked](https://github.com/open-policy-agent/kube-mgmt/issues/92) in kube-mgmt project.
