### ISSUE TITLE
Query parameter ?pretty=true does not work for v0 API

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3332]
## Expected Behavior

Pretty printed output on /v0/data if ?pretty=true is [provided](https://www.openpolicyagent.org/docs/latest/rest-api/#query-parameters-5).

## Actual Behavior

Parameter has no effect.

## Steps to Reproduce the Problem

**policy.rego**
```rego
package policy

x := {
	"maps": {
		"should": {
			"be": "indented"
		}
	}
}
```
`opa run --server policy.rego`

```shell
$ curl -d '{}' localhost:8181/v1/data/policy/x?pretty=true
{
  "result": {
    "maps": {
      "should": {
        "be": "indented"
      }
    }
  }
}

$ curl -d '{}' localhost:8181/v0/data/policy/x?pretty=true
{"maps":{"should":{"be":"indented"}}}
```

**Comment by clarshad** [comment]
@anderseknert I could work on this bug, involves minor code change (couple of lines)

**Comment by anderseknert** [comment]
That would be great @clarshad 😃
