### ISSUE TITLE
wasm: Improve WASM support for OPA packages 

### ISSUE THREAD

**Issue by dxh9845** [open-policy-agent/opa#3342]
## Expected Behavior
I have been using OPA for my day to day job, and it's been pretty great. We've structured our OPA policies into packages., where each package we use correlates to what we call a "resource" some actor is acting upon. It's served us pretty well for our API backend authorization, and now we want to see how we can translate these collection of OPA packages to show or hide elements in our frontend.

The WASM support works well for evaluating specific entrypoints, but for a solution like ours, the WASM bundle solution isn't a natural fit - we have multiple entrypoints split across our packages. In our case, it would look like:

`
opa build -t wasm -e resource_one/allow resource_two/allow resource_one.rego resource_two.rego ...
`

for as many resources as we need.

In terms of WASM compilation, it would be great to be able to translate our packages directly to a WASM bundles directly without having to specify each entrypoint in each file individually. This would enable us to do *something* like:

`
opa build -t wasm -p resource_one
`

Not sure on the feasibility of this, and would be more than willing to discuss different approaches here (or even best practice on structuring OPA code to delineate between authorizing different "resources").

Initial discussion began here: https://openpolicyagent.slack.com/archives/CBR63TK2A/p1617217484077300

**Comment by srenatus** [comment]
I was a little quick assigning "enhancement" there. I'll give this some thought next week! 🤞

**Comment by srenatus** [comment]
👀 So, given your example,

    opa build -t wasm -e resource_one/allow resource_two/allow resource_one.rego resource_two.rego ...

I wonder if you couldn't work around the necessity to declare all those entrypoints by adding one more rule,

```rego
package entrypoint

allow {
  data[input.resource].allow
}
```

then you should be able to pass `-e entrypoint/allow`, and add the resource information to your input when evaluating the policy.

**Comment by dxh9845** [comment]
Just getting around to this - will let you know how this goes!

**Comment by srenatus** [comment]
Any news? 😃

**Comment by srenatus** [comment]
I'll close this. Feel free to re-open if there's more need for discussion or question 😄
