### ISSUE TITLE
go get: unknown revision v0.27.1

### ISSUE THREAD

**Issue by Dentrax** [open-policy-agent/opa#3343]
## Expected Behavior

It should get `v0.27.1`

## Actual Behavior

```
go: github.com/open-policy-agent/opa@v0.27.1: reading github.com/open-policy-agent/opa/go.mod at revision v0.27.1: unknown revision v0.27.1
```

## Steps to Reproduce the Problem

```
$ go get github.com/open-policy-agent/opa@v0.27.1
```

Same error:
```
$ go mod vendor
```

I cannot use it in the project which requires `github.com/open-policy-agent/opa v0.27.1`.  

Any thoughts? 🤔

**Comment by ashutosh-narkar** [comment]
`go get github.com/open-policy-agent/opa@v0.27.1` seems to work for me. Have you checked if it's something specific to your environment ?

**Comment by srenatus** [comment]
https://pkg.go.dev/github.com/open-policy-agent/opa@v0.27.1 👈 this also resolves just fine, so I think the go ecosystem side here is fine. Are you using any specific Go module proxy of some sort...?

**Comment by Dentrax** [comment]
@ashutosh-narkar 

`$ go clean --modcache` solved my problem somehow. 🤷‍♂️
