### ISSUE TITLE
Bundle download failed: scope mismatch

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3347]
**I got the error below when i start the opa main program:**
`{"level":"error","msg":"Bundle download failed: failed to parse PEM block containing the key","name":"authz","plugin":"bundle","time":"2021-04-06T17:45:35+08:00"}`

**And my opa.yaml is as below:**
![企业咚咚20210406175306](https://user-images.githubusercontent.com/11346379/113693244-fd46c580-9700-11eb-9557-90933220981c.jpg)

**Comment by andrehaland** [comment]
Try adding `\n` to the key value instead of breaking the lines

**Comment by andyyumiao** [comment]
> Try adding `\n` to the key value instead of breaking the lines

I fix this by changed opa.yaml:
![企业咚咚20210406192607](https://user-images.githubusercontent.com/11346379/113703848-f5d9e900-970d-11eb-88b5-9834577c5656.jpg)
but got another error:
![企业咚咚20210406192645](https://user-images.githubusercontent.com/11346379/113703915-0b4f1300-970e-11eb-90b9-cc41c25742e1.jpg)

**Comment by ashutosh-narkar** [comment]
What's the scope provided in the JWT that's included in the bundle's `.signatures.json` file ?

**Comment by andyyumiao** [comment]
> What's the scope provided in the JWT that's included in the bundle's `.signatures.json` file ?

@ashutosh-narkar I used `bundle.GenerateSignedToken` to generate the sign token, but it seems that it does not provide such a method to generate scope, or is there other way to set scope?

**Comment by ashutosh-narkar** [comment]
You can use the `opa sign` command to generate a bundle signature.
