### ISSUE TITLE
Built-ins: time diff function

### ISSUE THREAD

**Issue by andrehaland** [open-policy-agent/opa#3348]
There are some use cases for calculating the difference between two `Time` values (e.g. calculate time since last login, or calculate the age based on birthdate). Is this something that would be accepted as an addition to the `time` built-ins?

`output := time.diff(a, b)`

Example implementation can be seen from this SO post:
https://stackoverflow.com/a/36531443

**Comment by ashutosh-narkar** [comment]
One way of doing this currently is something like https://play.openpolicyagent.org/p/ZDLf9k1fuC. The time-builtins use Go's [time](https://golang.org/pkg/time/)  package. Feel free to add a new one !

**Comment by andrehaland** [comment]
> One way of doing this currently is something like https://play.openpolicyagent.org/p/ZDLf9k1fuC

I should have been more specific. I was thinking of a difference on the format `[years, months, days, hours, minutes, seconds]`. The provided example only gives a duration, and when converting a duration to the wanted format we have to take make some considerations, such as the number of days in a specific month into account etc., as described in the SO post:

> https://stackoverflow.com/a/36531443

I am not sure if the required logic is possible to implement with Rego, so I will start on adding the new builtin. I was thinking of something like this:
````
./opa_darwin_amd64 eval 'diff := time.diff(time.parse_ns("2006-01-02", "2000-12-01"), time.now_ns())' --format=pretty
+-------------------+
|       diff        |
+-------------------+
| [20,4,6,10,10,21] |
+-------------------+
````
Any comments on this format @ashutosh-narkar?

**Comment by ashutosh-narkar** [comment]
This seems reasonable to me.
