### ISSUE TITLE
Allow OPA to be executed as an Azure function using Azure Functions Custom Handler

### ISSUE THREAD

**Issue by langes2BE3** [open-policy-agent/opa#3349]
When using OPA as a central source of fine-grained authorization in solutions build on Azure Functions using C#, Java or any other non Go way, OPA must be run on its own VM(s), making management cumbersome. With [Azure Functions Custom Handlers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers) OPA could be integrated using the Azure Functions Ecosystem taking care of scaling and limiting the amount of cost incurred by VMs. This way we can further introduce OPA into the realm of serverless computing.

Since Azure functions relay the requests to Custom Handlers using the _api/{function name}_ path prefix, OPA REST requests currently fail.

## Expected Behavior
allow for specifying a path prefix, under which all OPA REST endpoints are accessible (e.g. /api/opa)

## Actual Behavior
no such behavior is available

## Things to consider
* adding this functionality will not incur overhead for traditional uses
* a similar solution request was already posted under #2906,  although not with serverless in mind
* using OPA executable as an Azure function might have detrimental effects due to first start behavior, which should be communicated to prospective users
* A potential PR has already been  prepared

**Comment by srenatus** [comment]
Hmm I might be missing something there, but from the examples (https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers#examples), it sounds like the path invoked on the service implementing the custom handler was configurable:

> Even though the Functions host received original HTTP request at /api/order, it invokes the custom handler using the function name (its folder name). In this example, the function is defined at the path of /order. The host sends the custom handler an HTTP request at the path of /order.

So, where does the need to add a base path come from here? 🤔

**Comment by langes2BE3** [comment]
Hi Stephan,
first of,  thanks for picking this up so quickly!

I understand (and tried) that in order to define a function (even if using a custom handler) you have to define a function of a certain name (in the example given it's **orders**. This does get prepended to the request as shown in the examples. Since current OPA REST endpoints assume (rightfully) to be called starting from base '/' this leads to 404s. Hence the problem. My guess is that Azure has no vital interest in serving 9 minutes of VMs time on a pay per request basis, which would be the implication otherwise. So instead server apps hosted as an Azure Function (with all the scaling and cost effectiveness, but also slow cold starts) have to deal with being in front of a non-opaque reverse proxy, hence this feature request. Also a possible fix was attached as a CR, but I screwed up on reading the manual and committed without signed-off-by and now everything GitHub is giving me headaches - my bad - but it's not much work IMHO and would allow OPA to be used as a serverless component. Something that helps win over management tremendously in the get go.

**Comment by srenatus** [comment]
> So in the least we end up with something like /order/v1/data instead of /v1/data if we stick with order being the function name for calling out to OPA. Since current OPA REST endpoints assume (rightfully) to be called starting from base '/' this leads to 404s. 

Sorry if I'm being silly, but could `/v1/data` not be the function name? Or even the concrete query, `/v1/data/my-policy/allow`?


> Also a possible fix was attached as a CR, but I screwed up on reading the manual and committed without signed-off-by and now everything GitHub is giving me headaches - my bad - but it's not much work IMHO and would allow OPA to be used as a serverless component.

Let's revisit that at some point, I'm happy to help with the githubbing! Unlocking the serverless scenario would be great.

Going off on a tangent, I've been wondering if a custom function could be better served by using OPA's Wasm output... What do you think?

**Comment by langes2BE3** [comment]
Hi Stephan,
sorry for replying late.

> 
> Sorry if I'm being silly, but could `/v1/data` not be the function name? Or even the concrete query, `/v1/data/my-policy/allow`?
> 
It is quite true what you are saying. Unfortunately, the Azure Function Host will repack the request to include it into a quite different JSON structure than originally send by wrapping the "Url", "Method", "Headers", "Content-Type", "Params" and "Body" into separate elements in the request finally received by OPA cf. [HTTP Example](https://docs.microsoft.com/de-de/azure/azure-functions/functions-custom-handlers#implementation) Catering for this Azure Functions specificity feels wrong to me, though. The workaround for this is to instruct Azure Function Host to send the request virtually unchanged by the Functions Host by setting the `"enableForwardingHttpRequest": true`. This, however, reintroduces the problem of the mangled path as all requests to Azure Func start with `/api/`.

> Going off on a tangent, I've been wondering if a custom function could be better served by using OPA's Wasm output... What do you think?
Firstly, I believe this is an excellent idea. I haven't been able to play around with it yet, but JS is generally well known to behave for better in cold start scenarios. On the other hand starting OPA as executable on cold start only adds about 3s to that one request every 9 minutes. Secondly I'm not sure how well the Wasm approach works with bundles containing policy updates (as our services bring data AND policy updates as part of their respective bundles.

**Comment by srenatus** [comment]
Hey!

Still trying to wrap my head around this, please bear with me.

> Unfortunately, the Azure Function Host will repack the request to include it into a quite different JSON structure than originally send by wrapping the "Url", "Method", "Headers", "Content-Type", "Params" and "Body" into separate elements in the request finally received by OPA

I take it you're referring to this, as being what would be sent to the `/order` endpoint on the custom http function:

```
POST http://127.0.0.1:<FUNCTIONS_CUSTOMHANDLER_PORT>/order HTTP/1.1
Content-Type: application/json

{
  "Data": {
    "req": {
      "Url": "http://localhost:7071/api/order",
      "Method": "POST",
      "Query": "{}",
      "Headers": {
        "Content-Type": [
          "application/json"
        ]
      },
      "Params": {},
      "Body": "{\"id\":1005,\"quantity\":2,\"color\":\"black\"}"
    }
  },
  "Metadata": {
  }
}
```

I'm not sure I see the problem there 😄 What in your process makes it difficult to write rego policies for this? There's builtins for unmarshaling JSON into a rego object. 

----

On the wasm tangent, if you'd like to use bundles (or other management API features), wasm isn't the right answer. It's the bare minimum logic piece emitted by OPA that could be put into some wasm-shaped hole, but you'd have to find ways to update data yourself; updating the policy would mean rebuilding the wasm module.

**Comment by anderseknert** [comment]
@langes2BE3 did you manage to solve this or is it still an issue?

**Comment by srenatus** [comment]
🧹 Cleanup. Please re-open or create another issue if this is still a concern of yours! 😃
