### ISSUE TITLE
'persist' and 'persistence_directory' seems take no effect

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3355]
My opa.yaml is as below, but didn't generate bundle.tar.gz in `/Users/yumiao3/Documents/workspace/Logs`
![企业咚咚20210407155341](https://user-images.githubusercontent.com/11346379/113830969-b36de600-97b9-11eb-94ae-818105882c9d.jpg)

**Comment by anderseknert** [comment]
OPA version?

**Comment by andyyumiao** [comment]
> OPA version?

the latest version from master trunk

**Comment by andyyumiao** [comment]
> OPA version?

has resolved,thanks
