### ISSUE TITLE
About decision logs invalid

### ISSUE THREAD

**Issue by andyyumiao** [open-policy-agent/opa#3357]
**My decision log api didn't receive any request after i called the opa decision api, it seems something wrong happened.**
---------------------------
**The decision log api addr is:** 
`http://localhost:8080/opakeeper/v1/logs/report`
---------------------------
**And my opa config file is as below:**
![企业咚咚20210408161408](https://user-images.githubusercontent.com/11346379/113991897-7ff88d80-9885-11eb-956b-fc6f7ff37142.jpg)
---------------------------
**opa version:**
latest version from master trunk

**Comment by anderseknert** [comment]
What does the OPA logs say? If something went wrong uploading the decisions the error should be printed there. Do note though that with your configuration it will take a _minimum_ 5 minutes for this to happen and 10 minutes at most.

**Comment by andyyumiao** [comment]
> What does the OPA logs say? If something went wrong uploading the decisions the error should be printed there. Do note though that with your configuration it will take a _minimum_ 5 minutes for this to happen and 10 minutes at most.

Thank you, it is due to the upload delay！
