### ISSUE TITLE
REPL exhibits strange spacing when query spans multiple lines

### ISSUE THREAD

**Issue by mmussomele** [open-policy-agent/opa#336]
If the terminal in use wraps the query when typing, the terminal cursor is `x` spaces in front of where new text is inserted, where `x` is the number of times the query has been wrapped.

**Comment by jjshanks** [comment]
Couldn't repo this, may have been fixed somewhere else and can be closed out.

**Comment by tsandall** [comment]
Confirmed that this issue has been fixed.
