### ISSUE TITLE
Intermittent hangs when trying to ctrl+c kill OPA

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3363]
## Expected Behavior

Ctrl+c / Ctrld+d on a running server should stop the process.

## Actual Behavior

Ctrl+c / Ctrld+d initiates shutdown, but does not always kill the process.

```shell
air:opa anderseknert$ opa run --server \
        --set bundles.play.polling.min_delay_seconds=1 \
        --set bundles.play.polling.max_delay_seconds=2 \
        --set services.play.url=https://play.openpolicyagent.org \
        --set bundles.play.resource=bundles/bLXxY4TDgm
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2021-04-09T15:20:07+02:00"}
{"level":"info","msg":"Starting bundle downloader.","name":"play","plugin":"bundle","time":"2021-04-09T15:20:07+02:00"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"7b4049fc4b3a23e85a76da64b64442233b45c74b81429163721e28e95cd45011\".","name":"play","plugin":"bundle","time":"2021-04-09T15:20:08+02:00"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"7b4049fc4b3a23e85a76da64b64442233b45c74b81429163721e28e95cd45011\".","name":"play","plugin":"bundle","time":"2021-04-09T15:20:12+02:00"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"7b4049fc4b3a23e85a76da64b64442233b45c74b81429163721e28e95cd45011\".","name":"play","plugin":"bundle","time":"2021-04-09T15:20:17+02:00"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"7b4049fc4b3a23e85a76da64b64442233b45c74b81429163721e28e95cd45011\".","name":"play","plugin":"bundle","time":"2021-04-09T15:20:22+02:00"}
^C{"level":"info","msg":"Shutting down...","time":"2021-04-09T15:20:24+02:00"}
{"level":"info","msg":"Server shutdown.","time":"2021-04-09T15:20:24+02:00"}
{"level":"info","msg":"Stopping bundle downloader.","name":"play","plugin":"bundle","time":"2021-04-09T15:20:24+02:00"}
^C^F^C^C <-- process hanged
```

## Steps to Reproduce the Problem

There does not seem to be a way to do this consistently, but I've only ever managed to do this when configuring remote bundles so that seems like a required component.

## Additional Info

This has always been on my Mac. If others are seeing this on Mac or other platforms, please make your voice heard.

**Comment by johanneslarsson** [comment]
Isn't it a graceful shutdown you see? For example if it uploading decision logs, let it finish that task before it stops? In your case with that low bundle polling its probably busy polling bundles.

https://github.com/open-policy-agent/opa/blob/main/runtime/runtime.go#L407

**Comment by anderseknert** [comment]
While it's not unlikely that the bug is in the graceful shutdown routine, it's not _just_ graceful shutdown as intended going on here. That should always terminate after the provided timeout value, but either doesn't or something else is involved.

**Comment by amitkatyal** [comment]
@ashutosh-narkar, I am running OPA in the k8s cluster and came across the OPA hang issue. I am not sure where the OPA was stuck (maybe we will collect more information if the issue happens next time), but can this deadlock happen in the running OPA or it can only happen during the graceful shutdown of the OPA.

**Comment by ashutosh-narkar** [comment]
What OPA version are you using ? We recommend you use the latest released version and let us know if you're still facing the issue.
