### ISSUE TITLE
Improve HTTP server to surface 403 responses/authorization failures

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3378]
OPA's HTTP server supports authorization however if the policy denies the API request, the denial doesn't get accounted for via any of the management APIs today:

- The Decision Log API does not contain internal authorization decisions
- The metrics added to the Status API do not count 403 responses from deny decisions

~I don't think we want the OPA server to emit decision logs for every internal authorization decision (since that would effectively double decision log traffic) but perhaps every deny should be emitted. If the OPA server emitted decision logs for denials, the path would simply be set to the system authorization policy path. In the past, we have talked about decision log filtering, so this would be a natural use case.~

We fix the server so that 403s are counted in the metric registry. This would require some refactoring in the server so that the authorization handler is added _before_ the metric handlers.

**Comment by ashutosh-narkar** [comment]
Surfacing these denials via metrics that can be part of the Status API seems like the right approach.
