### ISSUE TITLE
Authentication option doesn't take effect if there's no authorization policy

### ISSUE THREAD

**Issue by jmassardo** [open-policy-agent/opa#3380]
When running opa as a server, if you specify the `--authentication` option without the `--authorization=basic` option, the authentication never takes effect.

While this is spelled out in the [docs](https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization), it would be beneficial to also have opa emit a warning message at runtime to make it clear that no authentication is happening due to the lack of a authz policy.

**Comment by kale-amruta** [comment]
@srenatus @tsandall I would like to work on this issue. I have tried and tested this on my local

**Comment by tsandall** [comment]
@kale-amruta sure. What I would do is add a log message in the `runtime` package. Something like:

```go
if rt.Params.Authorization == server.AuthorizationOff && rt.Params.Authentication == server.AuthenticationToken {
  logrus.Warning("Token authentication enabled without authorization. Authentication will be ineffective. See https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization for more information.")
}
```

This can go here: https://github.com/open-policy-agent/opa/blob/main/runtime/runtime.go#L307
