### ISSUE TITLE
Add builtin function support for Go strings.Repeat

### ISSUE THREAD

**Issue by scarbeau** [open-policy-agent/opa#3393]
Would love to see support for the `strings.Repeat(s string, count int) string` go function within OPA's built-in functions. 

I am using the output of the `walk` function to create "fingerprints" of highly nested objects and need to output a list of strings for all paths. I have a work arounds, but this would be much cleaner if the Repeat function were added to builtins.

## Expected Behavior
```rego
somePathArray := ["topLevelKey", "nestedKey", 1, "item"]
fstring := strings.repeat(".%v", count(somePathArray))  # --> ".%v.%v.%v.%v"
pathString := sprintf(fstring, somePathArray)           # --> ".topLevelKey.nestedKey.1.item"
```

## Link To Function
https://golang.org/pkg/strings/#Repeat

**Comment by anderseknert** [comment]
Did this in another policy some time back and ended up with this:
```rego
repeat(str, x) = concat("", [str | numbers.range(0, x - 1)[_]])
```
But yeah, makes sense to have as a built-in I guess.

**Comment by Ivan-Z** [comment]
Can I grab this?

**Comment by anderseknert** [comment]
@Ivan-Z sure! Just let me know if you need any help along the way.

**Comment by olamiko** [comment]
@Ivan-Z, are you working on this issue?

**Comment by anderseknert** [comment]
@olamiko if you’d like to work on some other good first issue I’d be happy to point you in the right direction!

**Comment by olamiko** [comment]
@anderseknert, yes, please point me in the right direction. I would like to work on some other good first issue.

**Comment by anderseknert** [comment]
@olamiko sure! How about this one https://github.com/open-policy-agent/opa/issues/2271 ? If you'd like to discuss the details we can either do so in the ticket, or perhaps better on the [OPA Slack](https://slack.openpolicyagent.org/)'s #development channel.

**Comment by anderseknert** [comment]
@Ivan-Z any progress on this? Let me know if you need any help.

**Comment by anderseknert** [comment]
`strings.repeat` and `array.repeat` was added in OPA v0.36.0
