### ISSUE TITLE
& in chained query param being encoded in url path in http.send method

### ISSUE THREAD

**Issue by AshRing** [open-policy-agent/opa#3395]
## Expected Behavior
& in a url path should stay & and not be encoded

## Actual Behavior
```
    reqUrl := concat("", ["/api/requests?clientId=", clientIdAccess, "&requestId=", parsed_body.requestId])
    reqResponse := http.send({"method": "GET", "url": reqUrl})
````
the above request encodes the & in the url string to 
`"/api/requests?clientId=clientId\u0026requestId=requestId"`
\u0026

I need this to be & so I can chain query parameters on the request.

## Steps to Reproduce the Problem
Use a & (ampersand) in a url path and send through http.send() method. Notice the & is being encoded to \u0026

## Additional Info
I tried escaping it and using %26 instead to no avail.

**Comment by anderseknert** [comment]
Which web server are you using where this is an issue? As far as I can tell this seems to be about presentation only - i.e. whether to display the ampersand as-is or to display it in it's unicode literal form. Not sure why some output formats prefer one over the other. Just listening on a port like `$ nc -l 8000` and then querying that seems to preserve the `&`:

```shell
$ opa eval 'http.send({"method":"get", "url": "http://localhost:8000/path?x=1&y=2"})'

# nc -l window would now display

GET /path?x=1&y=2 HTTP/1.1
Host: localhost:8000
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
```

On the other hand, it looks like e.g. `opa eval` prefers to display the literal form:

```shell
$ opa eval 'http.send({"method":"get", "url": "https://httpbin.org/anything?x=1&y=2"}).body.url'
{
  "result": [
    {
      "expressions": [
        {
          "value": "https://httpbin.org/anything?x=1\u0026y=2",
          "text": "http.send({\"method\":\"get\", \"url\": \"https://httpbin.org/anything?x=1\u0026y=2\"}).body.url",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```
But on the other hand not when printing the "raw" value:

```shell
$ opa eval --format raw 'http.send({"method":"get", "url": "https://httpbin.org/anything?x=1&y=2"}).body.url'
https://httpbin.org/anything?x=1&y=2
```

Could you be more specific as to how this manifests as a problem?

**Comment by AshRing** [comment]
I'm so sorry! I was confused that it was being encoded in the OPA decision logs and thought that was why the request wasn't being allowed. It turns out it was a missing object key. Thanks for the response & sorry to waste your time - closing this issue.

**Comment by anderseknert** [comment]
No worries at all. Good to know for future reference, and not strange at all to point to as a likely problem. Great though that it wasn’t!
