### ISSUE TITLE
Can I call variables defined in separate files?

### ISSUE THREAD

**Issue by budiprihhastomo** [open-policy-agent/opa#3396]
I want to try creating a variable and calling it in a separate file. Is this supported by rego?
## Expected Behavior
authz.rego
`package docker.authz`
`allow {
	user_id := input.Headers["Authz-User"]
	user_id == root[_]
}`

users.rego
`package docker.authz`
`root = ["primary_token_user", "secondary_token_user"]`

Can i call the root variable into auth.rego ? I need help to solve this problem. Thanks.

**Comment by anderseknert** [comment]
Yes, just start OPA with both files provided.

```shell
$ opa run .
OPA 0.27.1 (commit , built at )

Run 'help' to see a list of commands and check for updates.

> data.docker.authz.allow with input.Headers["Authz-User"] as "primary_token_user"
true
```

**Comment by budiprihhastomo** [comment]
@anderseknert, Thanks for your answer, but how to start OPA with both files provided when setup docker authz with authz.rego and users.rego ?

**Comment by anderseknert** [comment]
How would you normally start OPA? If you are trying to start OPA the server you'd probably do `opa run --server authz.rego users.rego`, or simply `opa run --server .` to start with all files in the current directory.

**Comment by budiprihhastomo** [comment]
I installed opa-docker-authz to handle authentication in my docker environement. So, where sholud I run the command `opa run --server .`? Or enough to run the command on my local machine ? I just try following the documentation in here : [opa-docker-authz](https://www.openpolicyagent.org/docs/latest/docker-authorization/)

**Comment by anderseknert** [comment]
Ah, I see! I missed the part about running the opa-docker-authz plugin.. I haven't tested but could you put the two (or more) files in the `/etc/docker/policies/` directory and then start the plugin with `opa-args="-policy-file /opa/policies/"`?

**Comment by budiprihhastomo** [comment]
I already try to add the files in `/etc/docker/policies/` directory and restart the plugin with `opa-args="-policy-file /opa/policies/"`, but the policy isn't working ?

**Comment by anderseknert** [comment]
Ah, okay! Looks like it isn't doable with the way that plugin currently works then :/ Feel free to open an issue over at https://github.com/open-policy-agent/opa-docker-authz/issues about it.

**Comment by budiprihhastomo** [comment]
Okay, thanks for your help. In future, I hope there is a feature that can solve this issue.
