### ISSUE TITLE
Rego if else condition

### ISSUE THREAD

**Issue by dsnr-pavankumar** [open-policy-agent/opa#3397]
I am trying to write if else condition based on the input. I am getting input "optimizeScheme" as true or false, based on the that I am trying to evaluate condition.

## Expected Behavior
Based on the input "optimizeScheme" as true or false, condition should be executed

## Actual Behavior
I tried couple of things, in the end the rego policy is not working based on the condition.

## Steps to Reproduce the Problem
The below is the rego policy that I had written.
package test
default allow = false
import input

scheme_match(schemeNames, schemeIds) {
input.optimizeScheme = "true"
	input.test.scheme[i] = schemeNames[k]
input.optimizeScheme = "false"
	input.test.scheme[i] = schemeIds[l]
}

allow {
  	schemeNames := {"a"}
    schemeIds := {"123"}
    scheme_match(schemeNames, schemeIds)
}

* OPA version: Latest version of OPA
* Example query: input
{
    "optimizeScheme": "true",
	"test":{
        "scheme": ["a", "b"]
    }
}
* Example output that OPA returned:
* {
    "allow": false
}

I am not expert enough in rego.

Thanks

**Comment by dsnr-pavankumar** [comment]
Appreciate your help

**Comment by anderseknert** [comment]
I'd probbably split scheme_match in two parts for each condition. Something like:

```rego
package test

default allow = false

schemeNames := {"a"}
schemeIds := {"123"}

scheme_match {
	input.optimizeScheme == "true"
	input.test.scheme[i] == schemeNames[k]
}

scheme_match {
	input.optimizeScheme == "false"
	input.test.scheme[i] == schemeIds[l]
}

allow {
	scheme_match
}
```

See the [Rego Playground](https://play.openpolicyagent.org/p/emqOunrtHX) if you wanna try it out.

**Comment by dsnr-pavankumar** [comment]
Thanks a lot **Anderseknert**, this helped me.
One more question, and in schemeID's and schemNames each contains 100 items and scheme contains 5 to 10 items, based on the optimizeScheme comparison, only one condition comparison should execute. but in the above, both condition comparison will execute or only one will execute?

Note:- I am asking this question as I am doing the performance tuning of the policy.

Once again thanks Anderseknert

Thanks
Pavan

**Comment by anderseknert** [comment]
Yes, only one of the "loops" will execute, based on the value of `input.optimizeScheme`.

**Comment by dsnr-pavankumar** [comment]
Thanks a lot Anderseknert.

Above example, I have converted according to my requirement Please find the rego policy below. currently with the input below provided policy is taking good of time to do the validation. I made a call to OPA with the below input using jmeter and per second I am making 1000 calls, this caused CPU spike from 6 to 8 cores. Is there any we can optimize the policy further to improve the performance.

**Rego playground link:-**
https://play.openpolicyagent.org/p/nY3Cj7xf3R

Your help is really appreciated. Thanks a lot for your help.

Thanks
Pavan

**Comment by anderseknert** [comment]
Oh, yeah there seems to be a lot of `glob.match` in iterations going on in there :) If you can restructure the data to allow for map lookups instead that would be an obvious improvement, but with the glob matching that's probably difficult. 

Pehaps @tsandall can point out any possible performance wins.

**Comment by srenatus** [comment]
Feel free to reopen!
