### ISSUE TITLE
Policy decision caching question

### ISSUE THREAD

**Issue by kyle-burnette** [open-policy-agent/opa#3405]
This is a question and not a bug or issue.

I thought I saw this someplace documented earlier but can't seem to find it anymore. Did not have any luck when searching thru issues here either that discussed this.
I am not referring to policy optimizations where it can (partially) evaluate parts of a policy and inline the virtual documents (where ever it can). 

Does OPA cache "policy decisions" that it can use when responding to queries/requests with identical inputs/parameters/attributes without actually evaluating the policy in question? 

If yes, how does it work or rather how long does it cache the policy decisions. Is this (policy decision) caching configurable? Also pl point me to the documentation if it is documented but I overlooked.

thanks
KB

**Comment by tsandall** [comment]
@kyle-burnette OPA does not cache any virtual documents across queries today. Each time your client queries (e.g., `POST v1/data/example/allow`), OPA will recompute the virtual documents required to produce the decision. During query evaluation, virtual documents are memoized in many cases (so the same rules are not re-evaluated twice) but those caches are blown away at the end of evaluation.

Where OPA can do inter-query caching today is at the built-in function level. The only built-in function in OPA that relies on this is `http.send`.

https://www.openpolicyagent.org/docs/latest/policy-reference/#http
https://www.openpolicyagent.org/docs/latest/configuration/#caching

**Comment by kyle-burnette** [comment]
Thanks for the response/clarification. 

This actually would be a separate question but if you don't mind I have this related q around the various options of getting external data to OPA. 

Pardon my naivety as I have not experimented enough but I wanted to know whether it is possible to have a combo model of getting external data to OPA: 

- Have some of the data either pulled or pushed into OPA PLUS 
- Design some policies which can fetch needed data during evaluation (as described in option 5 of [external data](https://www.openpolicyagent.org/docs/latest/external-data/)) 

I am thinking that should be possible but wanted to check as I had noticed (limited experimentation so take this with a grain of salt) that when OPA is configured to pull bundles then it does not seem to allow to additionally push/add policies using its REST APIs (claims it is configured to use bundles). I have not tried pushing data to OPA instance configured to pull bundles yet in case that is allowed. 

rgds,
KB

**Comment by kyle-burnette** [comment]
I have a question on OPA's inter-query caching ability. Does this cache any external data as well or rather what all things are included in the cache?  

thx
KB

**Comment by ashutosh-narkar** [comment]
> I am thinking that should be possible but wanted to check as I had noticed (limited experimentation so take this with a grain of salt) that when OPA is configured to pull bundles then it does not seem to allow to additionally push/add policies using its REST APIs (claims it is configured to use bundles). I have not tried pushing data to OPA instance configured to pull bundles yet in case that is allowed.

You could scope OPA's bundles to a subset of OPA’s policy and data and in that way the bundle would be responsible for only those. See [this](https://www.openpolicyagent.org/docs/latest/management-bundles/#multiple-sources-of-policy-and-data) section for more details.

> I notice that http.send in Policy reference allows some cache control. The "cache" parameter defaults to false. Does that mean that OPA will by default not cache the data it obtained using http.send even if the inter-query caching ability (global configuration I guess) was enabled ?

If the `cache` parameter in the request to `http.send` is not set, it will not use the **inter-query** cache. The response is still cached but only for that query. If you want the `http.send` response to be cached across queries, you'll have to set `cache` or `force_cache` to `true`.
