### ISSUE TITLE
Write comprehensive docs section on annotations

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3406]
With the schema support expanding on OPA/Rego to include annotations on rules, it would be useful to include a docs page on annotations. Perhaps it could exist on the existing Policy Language page. The docs should include the current sections on overriding as well as descriptions of the various fields with examples. We should pull in the example docs from @aavarghese's external repo as well.

**Comment by tsandall** [comment]
related #3398

**Comment by tsandall** [comment]
Moving this back to TODO. This will be easier to complete when we have other annotation types (e.g., rule metadata, entrypoints, etc.)

**Comment by anderseknert** [comment]
@tsandall is this covered by our current documentation of metadata annotations and schemas?

**Comment by ashutosh-narkar** [comment]
OPA docs has a page on `Annotations`. It can be found [here](https://www.openpolicyagent.org/docs/latest/annotations/).
