### ISSUE TITLE
Relax := restrictions at file-scope

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3413]
Currently the := operator can only be used at the file-scope to declare complete rules. We have restrictions in place so that the := operator only allows one rule per name per package. This restriction is primarily in place to match the semantics of the := at the query/rule-body scope (i.e., to declare local variables). When we initially added support for := at the file-scope, we figured it would be confusing for users if they could use the := operator in partial rules, functions, or for multiple rule declarations. Over time, we've found that this causes more confusion.

It would be nice to relax the restrictions slightly so that:

1. := can be used to declare partial rules and functions
2. := can be used to declare complete rules w/ a default value

Note, we can make the first change without allowing multiple declarations for now. In the future, we could decide to relax the restrictions further.

The only feature we lose by relaxing these restrictions is the ability to ensure only a single rule definition exists per package for a given name. Since it's unlikely that anyone is relying on this behaviour and there are otherwise it could be achieved (e.g., today w/ linting or tomorrow with a new keyword) this seems like a reasonable compromise.

# Examples (allowed by this change)

**partial rule**

```rego
p[x] := y { ... }
```

**function**

```rego
f(x) := y { ... }
```

**default values on complete rules**

```rego
default p := 0

p := 7 { ... }
```

## Examples (not allowed by this change)

**multiple complete rules**

```rego
p := 7 { ... }
p := 8 { ... }
```

**Comment by anderseknert** [comment]
Resolved by #4583.
