### ISSUE TITLE
sprintf inherits all its behaviour from golang

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3415]
```
$ opa eval --format=pretty 'sprintf("foo %s %s", [1])'
"foo %!s(int=1) %!s(MISSING)"
```
☝️ Two things are going on here:
1. the mismatched type `%s` and `1` is displayed as `%!s(int=1)`
2. the missing parameter is `%!s(MISSING)`

Both are inherited from the golang implementation. Looking at the docs, it's not actually specified much, so I guess that's intentional 🤔 

Also, there's some implementation details shining through when using `%T`:
```
$ opa eval --format=pretty 'sprintf("%s %[1]T", [{ "x": 1 }])'
"{\"x\": 1} string"
```

Related: https://github.com/open-policy-agent/opa/issues/2504

**Comment by anderseknert** [comment]
Is the problem just that leaky implementation details are ugly, or is this about WASM compatibility concerns? 😊

**Comment by srenatus** [comment]
A bit of both, I suppose. 😃 and also a docs issues of sorts, we are pretty silent about the current behaviour...

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/issues/4771 will fix this.
