### ISSUE TITLE
Memoize function outputs

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3417]
Today, topdown only memoizes complete rules with zero arguments. We should see if we can add memoization for functions without too much effort. The cache structures we have _should_ support arbitrary keys (e.g., arrays, objects, etc.) so it should not be a massive change.

**Comment by srenatus** [comment]
The same is true for wasm, I suppose.

**Comment by srenatus** [comment]
> The cache structures we have should support arbitrary keys (e.g., arrays, objects, etc.) so it should not be a massive change.

Yeah, since paths may not overlap, I think we should be OK with putting the results of `data.p.f(1, "foo")` and `data.p.f(2, "bar")` into the virtualCache as
```
data
 - p
   - f
     - 1
       - "foo"
     - 2
       - "bar"
```
