### ISSUE TITLE
OPA Metrics: rejected requests

### ISSUE THREAD

**Issue by konstantin-tkachuk** [open-policy-agent/opa#3454]
## Expected Behavior
I expect to be able to see in the metrics the number of rejected requests.

## Actual Behavior
https://www.openpolicyagent.org/docs/latest/monitoring/ describes a set of metrics and I can confirm that they work for me. However, these metrics do not contain the above information.

## Context
I am currently running OPA with Envoy as a sidecar of a microservice and am wondering how I am supposed to track this. While successful request metrics are available from the metrics of the application, the rejected requests never reach it.

How can I get this information?

**Comment by srenatus** [comment]
I wonder if envoy provides something already there...?

**Comment by srenatus** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#statistics looks relevant

**Comment by srenatus** [comment]
Sorry for the brevity. Some context here, to OPA, allowed/denied are not special concepts, it's just the response to a query. You could deploy a policy telling you the date of the week, for all that OPA cares. As such, it would be a little odd to introduce a metric for a specific type of response.

That said, for the opa-envoy-plugin, the scenario is much more focused, capturing denied/allowed would make sense there. But in that setting, envoy seems to already expose those numbers. Does that do the trick for you?

**Comment by konstantin-tkachuk** [comment]
Thank you for the explanation, now I understand why this is not already part of the existing metrics.

I will be checking out the Envoy documentation and attempt to configure it all in my cluster soon (probably next week). At first look it does seem like exactly what I am looking for.

**Comment by konstantin-tkachuk** [comment]
As a follow-up to this, I managed to use the envoy metrics to get a total number of denied requests. It does not quite fulfill everything that I want, but it is definitely a step in the right direction. I am currently asking follow-up questions on the Envoy side here: https://github.com/envoyproxy/envoy/issues/16573

I am closing this issue, because there is nothing on the OPA side that needs doing here.
