### ISSUE TITLE
OPA uses insecure deprecated legacy PEM encryption

### ISSUE THREAD

**Issue by willbeason** [open-policy-agent/opa#3461]
We use RFC1423 PEM encryption, which has been [deprecated due to having known vulnerabilities](https://golang.org/pkg/crypto/x509/#DecryptPEMBlock).

From the x509 Go documentation:

```
// Deprecated: Legacy PEM encryption as specified in RFC 1423 is insecure by
// design. Since it does not authenticate the ciphertext, it is vulnerable to
// padding oracle attacks that can let an attacker recover the plaintext.
```

The documentation does not suggest what to do instead. I am not well-versed in crypto so I do not know the alternative we should be using.

**Comment by willbeason** [comment]
Alternatively - does the code in `plugins/rest/rest_auth.go` simply intend to *support* the use of such PEM encryption, but otherwise pose no security vulnerability? As in, "enough users want to use this insecure format, so we support it"?

**Comment by anderseknert** [comment]
This weakness is not in OPA. More like a warning not to rely on password encryption standards from 1993. OPA does not enforce or even recommend the use of password encryption in PEM encoded keys, but should the user have one and they’d like to use it with OPA we will let them do so. Seems fair, or what do you think?

**Comment by willbeason** [comment]
Yep, that's what I figured.
