### ISSUE TITLE
internal/jsonschema should support the latest JSON schema drafts

### ISSUE THREAD

**Issue by willbeason** [open-policy-agent/opa#3476]
The [JSON Schema specification](https://json-schema.org/specification.html) is ever-evolving. The library we've copied into `internal/gojsonschema` only supports through Draft 7, which was published in 2017. There have since been two JSON Schema versions which we do not support. **As written, we process schemas following more recent specifications as Draft 7 and silently return incomplete schemas.** For example, in 2019 `definitions` was renamed to `$defs`. Right now we simply take no action as we do not check for `$defs`.

Unfortunately the Go community is lacking [an implementation](https://json-schema.org/implementations.html#validator-go) that covers more modern specifications and is backwards compatible. This means we could use a more recent existing one, but:

- we would lose backwards compatibility with Draft 6 and Draft 7, and
- we would still not get compatibility with the 2020 specification, as there currently is no such implementation.

My main question is: How tied are we to supporting older schema specifications? We should certainly support _some_ specifications older than the most recent, but how long do we intend to continue supporting older ones?

**Comment by tsandall** [comment]
> My main question is: How tied are we to supporting older schema specifications?

We're not tied to a specific version at this point. I'd be curious to know, in practice, how widely used newer features are. E.g., would updating the library give us better support when working with JSON Schemas generated from the Kubernetes OpenAPI spec? One of the main reasons for using JSON Schema here is that we want to be able to ingest pre-existing schemas and use them to inform type checking.

> We should certainly support some specifications older than the most recent, but how long do we intend to continue supporting older ones?

We haven't defined this yet. Support for JSON Schema is still early and I'd expect that we'll learn quite a bit in next few releases as more folks try it out.

**Comment by willbeason** [comment]
Looking through the [swagger.json](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json), it looks like Kubernetes uses Draft 7 by standard, so this is moot unless they ever decide to upgrade.

**Comment by tsandall** [comment]
I'm going to just mark this as an enhancement and we can keep the issue around for the future. If we start to see compatibility issues we can revisit it!

**Comment by srenatus** [comment]
💭 The kubernetes API is primarily defined through protobuf, isn't it? I guess having another "schema provider", like protobuf-encoded-to-json according to the spec, could be useful, too.

**Comment by willbeason** [comment]
Sounds good! What if in the meantime we try to recognize if a user has mistakenly used a newer draft and just send an error that says we don't yet support later ones? Many of the changes can be recognized by the presence of new schema keys.

**Comment by anderseknert** [comment]
Let's close this for the time being. We can always re-open should we find a concrete use case where we'd need this.
