### ISSUE TITLE
Safety check reports output variables as unsafe

### ISSUE THREAD

**Issue by mmussomele** [open-policy-agent/opa#348]
If an input to a builtin is unsafe, none of the inputs or outputs are considered safe as is, resulting in verbose error messages. Output variables should be considered safe regardless of input safety. Compilation will still fail, but have more helpful/actionable errors.

**Comment by tsandall** [comment]
Closing this for now since users typically do not specify variables in the output position anymore (e.g., instead of writing `plus(1,x,y)` they'll write `x := 1+y` which is better handled since the safety check elides errors for generated vars.)
