### ISSUE TITLE
Very high scale of policies (millions)

### ISSUE THREAD

**Issue by shoaibbanikartester** [open-policy-agent/opa#3482]
Hi Team, 

We have a scenario where in a multi-tenant system, end users (customers) can define their own Rego policies that we need to Save and evaluate against particular input (Almost like [Rego playground](https://play.openpolicyagent.org/), on scheduled basis. 

Now as you can imagine, number of policies can grow here in millions. Now, we see 3 challenges over here:

1. We are thinking on deploying OPA as container and integrating via [rest API](https://www.openpolicyagent.org/docs/latest/rest-api/). Considering OPA would load these millions policies in memory, we would mostly run out-of-memory.
2. With such high volume of policies, we suspect that OPA will have performance issues as well.
3. Since OPA does not have any persistence for policies, we may have to to Push all these policies again, every time container restart. [Bundles](https://www.openpolicyagent.org/docs/latest/management-bundles/) does not seem a suitable option either, considering our new policies can get added/updated frequently. Also, [http.send](https://www.openpolicyagent.org/docs/latest/policy-reference/#http) seems to be option only for "data" and not "policies".

Any suggestions would be of great help here.

Worst case option we have is, to Add Policy > Query > Delete Policy. :( This would be very inefficient though, considering:

1. 3 API calls. There is no single Rest API available to evaluate arbitrary Rego expressions and policies e.g. [OPA Eval](https://www.openpolicyagent.org/docs/latest/#2-try-opa-eval)
2. This would mean OPA need to parse, compile, and install the policy, before it can query. And then delete it. Too bad.

**Comment by amitkanfer** [comment]
One option i can think of, in case you really have millions of distinct policies, is to write a builtin function like `evaluate(<tenantid>, <path>, <params...>` or similar that knows how to load a policy from an external data source (git for example), evaluate and then return a result.
This also provides you with the ability to "wrap" the result you get per tenant with your own high level logic, something that you want to enforce for ALL tenants regardless of their specific use case.

**Comment by anderseknert** [comment]
What does it mean that the policies are evaluated on a scheduled basis? If that is the case you could use something like `opa eval` to load policies as they're evaluated.

There's some work planned for disk based store as an alternative to purely in-memory. You can track the issue [here](https://github.com/open-policy-agent/opa/issues/3231).

**Comment by shoaibbanikartester** [comment]
Thanks @anderseknert for your input. By scheduled I meant, users define the policy once and we evaluate it multiple times as per cron-like schedule.

Regarding `opa eval`, There is no equivalent [Rest API](https://www.openpolicyagent.org/docs/latest/rest-api/) for same, where I can provide both "input" and "policy" and get the result. Is there one? Also, even if there is one, assuming that with `opa eval` OPA need to _parse, compile, and install the policy_ and then evaluate it against input. This would be lot slower in performance, but might be acceptable as last resort, as long as Rest API is available.

Thanks for sharing [disk-based store implementation](https://github.com/open-policy-agent/opa/issues/3231). Definitely inline with what we would require.

**Comment by anderseknert** [comment]
`opa eval` allows you to provide both policy and input. Relevant options can be seen with `opa eval --help`:
```
  -d, --data string                           set policy or data file(s). This flag can be repeated.
  -i, --input string                          set input file path
  -I, --stdin-input                           read input document from stdin
```
And yeah, it's going to be slower than keeping everything in memory, but doing that was ruled out before, so.. 🙂 

I'm curious about the performance requirements though, given how this workload is scheduled. Why would that need to be so fast? I would have assumed that a scheduled workload means no one is synchronously waiting for the processing to finish.

**Comment by shoaibbanikartester** [comment]
Thanks @anderseknert .

Regarding opa eval, There is no equivalent Rest API for same, where I can provide both "input" and "policy" and get the result. Is there one? I may have to extend OPA to implement such API?

My concern with performance is, in our case, "same" policy would run for multiple inputs, multiple times a day. so despite being "same" policy, it would get parsed and compiled, multiple (thousands) times. So it is little inefficient, but might be acceptable given it is asynchronous in nature. But any clue on how fast/slow OPA parse and compile implementation is?

**Comment by anderseknert** [comment]
`opa eval` is not exposed at a REST endpoint. Given how `eval` loads policies and data from local disk I'm not sure it would make sense to do so either. If you want to expose that over a REST endpoint you're probably better off using OPA as a library, but just as with your performance concerns I think you'd need to do some real world tests to see what works and what doesn't given your somewhat unorthodox requirements 🙂

**Comment by anderseknert** [comment]
@shoaibbanikartester anything left unanswered here or should we close the issue?

**Comment by shoaibbanikartester** [comment]
I think, I have got the answers/suggestions I wanted. Thanks @anderseknert and team.

**Comment by cs-pablorb** [comment]
@shoaibbanikartester we have a similar situation in our project. Are you using OPA, or have you moved away from it? Could you share some insights if possible?
