### ISSUE TITLE
Question: Any suggestion on soft policy enforcement?

### ISSUE THREAD

**Issue by evanchaoli** [open-policy-agent/opa#3486]
We are introducing policy enforcement via OPA to our systems. Once we enabled certain policies, some workflow may fail suddenly. Besides publishing advertisements, we are thinking on soft enforcement. Meaning that, OPA still evaluate policies over inputs, but instead fail, it just gives warnings, and allow workflow to go on.

Any suggestion or existing practices?

**Comment by evanchaoli** [comment]
@anderseknert Thanks a lot for your quick response. I'm new to OPA. AFAIK, OPA returns `{result: true/false}`. Could you please point some doc for configuring OPA or a policy to return a result like you mentioned?

**Comment by anderseknert** [comment]
Presumably you have a rule called `allow` or similar which you query. So if your policy looks something like this:

```rego
package policy

default allow = false

allow {
    input.user.role[_] == "admin"
}
```

You would then query the allow rule by calling `http://localhost:8181/v1/data/policy/allow` and you'd see `{result: true/false}` like you said, which is the value returned by the allow rule. Now if you rather query the `policy` document you would see not just the result of the allow rule but all rules in the module. Change the request to `http://localhost:8181/v1/data/policy` and you'll see a response like `{result: {allow: true/false}}`. Now you can add more rules to the module, like "severity" and have those evaluated just like the allow rule.


```rego
package policy

default allow = false

allow {
    input.user.role[_] == "admin"
}

severity = "warning" {
    not allow
}
```

Or you could simply have a single rule return an object right away: 


```rego
package policy

decision = {"violation": violation, "severity": severity} {
    violation = # query some other rules here
    severity = # query some other rules here
}
```

See the OPA [document model](https://www.openpolicyagent.org/docs/latest/philosophy/#the-opa-document-model) section from the docs for a pretty good guide on this.

**Comment by evanchaoli** [comment]
@anderseknert Thank you a ton! Your answer is exactly what I was looking for.

BTW, a follow up question is, is it possible to make OPA to include a reason in returned result when result is false?

**Comment by anderseknert** [comment]
Are we ready to close this @evanchaoli ?

**Comment by evanchaoli** [comment]
Sure. Thanks again.
