### ISSUE TITLE
Adjust logging for "Log upload skipped"

### ISSUE THREAD

**Issue by andrewbanchich** [open-policy-agent/opa#3487]
Every second, OPA outputs the following to stdout for me:

```
opa               | {
opa               |   "level": "info",
opa               |   "msg": "Log upload skipped.",
opa               |   "plugin": "decision_logs",
opa               |   "time": "2021-05-25T13:54:40Z"
opa               | }
```

This makes things pretty noisy and makes it hard to see important logs from other services. Could this be set to `DEBUG` level instead?

Also, the `Log upload skipped` message, from what I understand, simply means there were no logs to send. I originally took this to mean that there were logs but it decided to not upload them for some reason. Could this be reworded for clarity?

**Comment by anderseknert** [comment]
I'm guessing the reason this does not annoy more people is that the default of five **minutes** is enough to have most production OPAs at least have some decisions to upload at each occasion 😃 I'm curious to know more about any configuration that requires this to be done every second! That said, the event itself seems uninteresting enough to warrant DEBUG level demotion.

**Comment by tsandall** [comment]
Agreed w/ @anderseknert that uploading every second is a bit odd however it's also a reasonable change make. The line in question is [here](https://github.com/open-policy-agent/opa/blob/main/plugins/logs/plugin.go#L569). I don't think anyone is going to care if that message goes to debug.
