### ISSUE TITLE
Add function to read files from fs.FS to create bundle

### ISSUE THREAD

**Issue by simongottschlag** [open-policy-agent/opa#3489]
Hi!

First of all, thank you for everything you do and all the great work with OPA. I'm using OPA in so many projects in many different forms and it is such a powerful tool.

I've been working on a way to dynamically create bundles using Go and it's been a pleasure working with your lib as well, it's one of the better ones I've had the pleasure of working with.

I am combining bundles from both embed and an API. When using `NewDirectoryLoader()`, I need to first create all the files in a temporary directory and then pass this directory to the function.

My proposal is to create an additional function, `NewFsLoader(files fs.FS)` that takes an FS interface as input:
https://golang.org/pkg/io/fs/#FS

This would make it possible for the end user of the function to handle how they want to expose files to your function. In my case, that would remove the necessity of creating a temp directory and instead just handle the logic dynamically with the interface.

What are your thoughts around this? If you would like to, I could give it a try and create a PR.

**Comment by tsandall** [comment]
@simongottschlag thanks for the kind words!

I agree w/ @srenatus that we want to maintain compatibility w/ older versions of Go (e.g., we don't want to break users that haven't updated yet.) Stubbing out the fs.FS dependency makes sense. Hopefully we can keep the amount of stubbed out code to a minimum.

**Comment by simongottschlag** [comment]
Hi @tsandall and @srenatus! 

I've created an initial PR: #3493 . I'm no expert when it comes to this, but I wanted to try and offload the majority of the work from you - if possible.

Feel free to give feedback on whatever you see, as I learn by doing and your expertise will of course be appriciated and warmly welcomed!

**Comment by srenatus** [comment]
Thanks! I'll review this tomorrow at the latest.
