### ISSUE TITLE
linux build depends on glibc 2.18+

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3524]
Follow-up to #3499.

As it turns out, the binaries we've built with wasm enabled (starting from 0.29.0) depend on glibc, but also have a minimum requirement: 2.18. As far as I can tell, that comes in from the version of glibc present in the host system used when building the binary -- in our case, that's the golang docker image.

The problem is Centos 7 (EOL 2024, still alive for a bit), which has an older version and no easy way to upgrade.

The workaround for now would be to use the static linux binaries on Centos 7, if you can work without the embedded wasm engine. If you need the wasm engine on Centos 7, you'd have to build the binary yourself on that system. (There's no known reason what that should be impossible.)

**Comment by srenatus** [comment]
👉 https://gist.github.com/wagenet/35adca1a032cec2999d47b6c40aa45b1 Centos 7 seems to be the only popular linux distribution affected by this.

**Comment by tsandall** [comment]
Going forward we recommend people use the `opa_linux_amd64_static` executable if they need to deploy to one of these systems.
