### ISSUE TITLE
undefined reference to `__res_init' when linking against musl libc

### ISSUE THREAD

**Issue by mspraggs** [open-policy-agent/opa#3528]
## Expected Behavior

Build succeeds without errors.

## Actual Behavior

The build fails with the following error:
```
/usr/bin/ld: /home/matthew/go/pkg/mod/github.com/bytecodealliance/wasmtime-go@v0.27.0/build/linux-x86_64/libwasmtime.a(std-0a9489cf400f65e4.std.bb9ro8wy-cgu.0.rcgu.o): in function `std::sys::unix::net::on_resolver_failure':
/rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53//library/std/src/sys/unix/net.rs:447: undefined reference to `__res_init'
```

## Steps to Reproduce the Problem

I ran the following on Linux Mint 20.1, but I first experienced this error when compiling OPA for use at work, where we link against musl and run in a Docker image derived from Alpine Linux.

These are the shell commands I ran to produce the error above:

```
sudo apt install musl-dev musl-tools golang-go
cd /tmp
git clone https://github.com/open-policy-agent/opa
cd opa
git checkout v0.29.4
CC=/usr/bin/musl-gcc make
```

## Additional Info

From what I can see, it looks like wasmtime calls the libc function `res_init`, and my theory is that Rust optimises the call so that a direct reference is made to the internal `__res_init` symbol, which doesn't exist in musl.

Also worth mentioning that I encounter the same problem when compiling v0.27.0 and v0.28.0.

**Comment by tsandall** [comment]
@mspraggs do you want/need the wasm runtime to be available in your OPA executable? If not, you can disable it:

```
make build WASM_ENABLED=0
```

IF you want to build a static executable (which cannot include the wasm runtime) you can also disable CGO:

```
make build WASM_ENABLED=0 CGO_ENABLED=0
```

**Comment by mspraggs** [comment]
Hi @tsandall, thanks for getting back so quickly!

Currently we don't _need_ WASM support in our builds, so we could disable this for the moment. That said, we may need it in future, so if there is a solution to this problem we'd be interested.

**Comment by tsandall** [comment]
For now I'd recommend just disabling the wasm runtime in your OPA builds.

If you want the wasm runtime to be available, I recommend filing an issue upstream w/ the wasmtime-go/wasmtime maintainers--they're quite responsive.

I'm going to close this issue for now since there is nothing we can do inside of OPA proper.
