### ISSUE TITLE
Support Abstract Unix Domain Sockets

### ISSUE THREAD

**Issue by amanymous-net** [open-policy-agent/opa#3533]
## Expected Behavior

Since OPA supports domain sockets, sockets with abstract addresses (@authz.sock) should also be accepted.

## Actual Behavior

Since OPA parses the domain as a URL, the conventional naming scheme (e.g. "unix://@authz.sock") translates to listening on just "authz.sock". The Go net package already supports abstract unix sockets, so OPA just needs a mechanism to flag unix abstract socket. This can be done by a new scheme (e.g. abstract-unix://) or by checking if the resulting Url object created a User (see https://play.golang.org/p/8whbGZJUWeg) 

Happy to contribute a PR if this change sounds good and you have a preferred method.

**Comment by tsandall** [comment]
Is there any scenario where implying abstract sockets based on the URI scheme and user would bite us? E.g., does `unix://foo@bar.sock` have any meaning? Could it?

**Comment by amanymous-net** [comment]
Domain sockets are just filepaths, so that _could_ be a valid non-abstract domain socket. 

Most other systems determine its a Unix socket (through some means) and then just check if the first byte to determine if it's abstract or not. I think following this pattern would be ideal, even if it means converting the URL back to a full string and then stripping off the scheme (once its determined to be unix://)

I can send a PR and we can see if it looks clean.
