### ISSUE TITLE
decode_verify fails silently when constraint aud is an array

### ISSUE THREAD

**Issue by ninawang-uhn** [open-policy-agent/opa#3538]
I am trying to decode_verify a token that has an array of two strings as its aud
When I put "aud": ["xxx", "yyy"] in the constraints, it fails silently without any output

## Expected Behavior
return true and decoded token

## Actual Behavior
not returning anything
## Steps to Reproduce the Problem
https://play.openpolicyagent.org/p/2v7F8NFPWD

**Comment by anderseknert** [comment]
Hi @ninawang-uhn!

When verifying the `aud` claim, OPA acts as a single principal, as described in [the specification](
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3):

> The "aud" (audience) claim identifies the recipients that the JWT is intended for.  Each principal intended to process the JWT MUST identify itself with a value in the audience claim. 

While a JWT may have many intended recipients, a single recipient can't identify as multiple principals. If you want/need to go outside of the spec, you may do so by verifying and decoding the JWT in separate steps, and add custom claims validation logic to your policy. Even when staying within the confines of the spec, many still prefer this over over using decode_verify.

**Comment by anderseknert** [comment]
Closing this for now. Let me know if you feel I missed something from the spec and I'll re-open @ninawang-uhn.
