### ISSUE TITLE
Go 1.17 x509.ParseCertificate error message will break tests in test/cases/testdata/cryptox509parsecertificates

### ISSUE THREAD

**Issue by yukinying** [open-policy-agent/opa#3547]
## Expected Behavior

Test pass

## Actual Behavior

Test fail

## Additional Info

Go 1.17 x509 has [encapsulated](https://github.com/golang/go/blob/048cb4ceee652e358d84fbca260fc93d7a0dfbe3/src/crypto/x509/parser.go#L812) the ASN.1 error during parsing. 

The test cases mentioned in the subject has hardcoded that the error message must contain `asn1: structure error`. The error message with Go 1.17 would be `x509: malformed certificate`. As a result, tests would fail in Go 1.17.

**Comment by olivierlemasle** [comment]
Test failure logs with Go 1.17:

```
--- FAIL: TestRego (1.35s)
    --- FAIL: TestRego/cryptox509parsecertificates/invalid_DER_or_PEM_data,_b64 (0.00s)
        exported_test.go:149: expected topdown error text "asn1: structure error" but got: "test-0.rego:7: eval_builtin_error: crypto.x509.parse_certificates: x509: malformed certificate"
FAIL
FAIL	github.com/open-policy-agent/opa/topdown	23.422s

```

**Comment by anderseknert** [comment]
I guess the test could just accept either of the two messages, or what do you think? Even if Go 1.17 is yet to be released I suppose the message is unlikely to change again.

**Comment by yukinying** [comment]
It doesn't look like these error messages would change often, and this would break the build process only so it would make sense to patch the error message signature matching logic to make it work for Go 1.17.

**Comment by anderseknert** [comment]
Sounds good to me! Would you want to submit a fix @yukinying? 😃

**Comment by yukinying** [comment]
@anderseknert I am not available for doing that shortly and that's why I was submitting the issue rather than a pull request directly :)
