### ISSUE TITLE
How to set env variables to golang pkg?

### ISSUE THREAD

**Issue by kotyara85** [open-policy-agent/opa#3548]
We're using in memory store to test regos for our app.
Specifically we expect this to be set as env variable in regos:
```
opa.runtime()["env"]["TOKEN"]
```

If there a way specify env variables for in-memory opa in golang?

os.Setenv is not working

Thanks

**Comment by ashutosh-narkar** [comment]
@kotyara85 to clarify you're asking how to pass environment variables to OPA ? If yes, how are you running OPA ? For example, if you had a policy like 
```rego
package authz

allow {
    opa.runtime().env.foo == "bar"
}
```

You could run it like below with `opa eval` or `opa run`:
```bash
$ foo=bar opa eval 'data.authz.allow' -d policy.rego -f pretty
true
```

> os.Setenv is not working

Are you embedding OPA as a library ?

**Comment by kotyara85** [comment]
@ashutosh-narkar yes, we embed it as a go library

**Comment by ashutosh-narkar** [comment]
Can you share some code to help understand what you're trying to achieve here ? You could manually create a store using [inmem.NewFromObject](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.29.4/storage/inmem#NewFromObject) and provide some custom data and then use the `rego` package to evaluate.

**Comment by kotyara85** [comment]
sure,
here's the rego
```
valid_user(token) = true {
  SECRET= opa.runtime()["env"]["SECRET"]
  AUDIENCE = opa.runtime()["env"]["AUDIENCE"]
  ISSUER = opa.runtime()["env"]["ISSUER"]
    result := io.jwt.decode_verify(token, {
        "secret": SECRET,
        "aud": AUDIENCE,
        "iss": ISSUER
    })
    result[0]
}
```

New store is just initiated with this command
```
store := inmem.New()
```

I do verify is the user is actually valid or not.
opa in memory doesn't recognize env variables. I guess runtime can be setup somehow?
Thanks

**Comment by tsandall** [comment]
The [rego.Runtime](https://pkg.go.dev/github.com/open-policy-agent/opa/rego#Runtime) option is what you're looking for. This controls the result of the `opa.runtime()` function.

**Comment by kotyara85** [comment]
@tsandall so what would be a Location in my case?

**Comment by kotyara85** [comment]
So in case if anyone will face a similar issue, that's a code straight from opa/runtime.go

```
	// add env variables to rego query
	obj := ast.NewObject()
	env := ast.NewObject()
	for _, s := range os.Environ() {
		parts := strings.SplitN(s, "=", 2)
		if len(parts) == 1 {
			env.Insert(ast.StringTerm(parts[0]), ast.NullTerm())
		} else if len(parts) > 1 {
			env.Insert(ast.StringTerm(parts[0]), ast.StringTerm(parts[1]))
		}
	}
	ast := obj.Insert(ast.StringTerm("env"), ast.NewTerm(env))
```

and then in query you can pass
rego.Runtime(ast)

**Comment by tsandall** [comment]
You don't have to specify location technically. The location information is for when values are parsed out of source files. In this case there are no source files so just leave the location nil.
