### ISSUE TITLE
OPA kubernetes policy : mutation webhook add unexpected values 

### ISSUE THREAD

**Issue by sanjaygopinath89** [open-policy-agent/opa#3550]
Create a mutation webhook to add ENV variable to a deployment with a specific vaules

**Environment variable that need to be added to a deployment** 

`
env:
    - name: OTEL_K8S_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://$(OTEL_K8S_HOST_IP):55680"

` 

**Policy Created** 

`
package system

main = {
    "apiVersion": "admission.k8s.io/v1beta1",
    "kind": "AdmissionReview",
    "response": {
        "allowed": true,
        "patchType": "JSONPatch",
        "patch": patch_bytes,
    }
} {
    is_create_or_update
    input.request.object.metadata.annotations["test-mutation"]
    input.request.kind.kind == "Deployment"
    patch = [
                {"op": "add", "path": "/spec/template/spec/containers/0/env/1", "value": {
            "name": "OTEL_K8S_HOST_IP",
            "valueFrom": {
                        "fieldRef": {
                        "fieldPath": "status.hostIP"
                        }
                    }
          }},
                  {"op": "add", "path": "/spec/template/spec/containers/0/env/1", "value": {
                     "name": "OTEL_EXPORTER_OTLP_ENDPOINT",
                     "value": "http://$(OTEL_K8S_HOST_IP):55680"
      }},
    ]
    patch_json = json.marshal(patch)
    patch_bytes = base64url.encode(patch_json)
}
is_create_or_update { is_create }
is_create_or_update { is_update }
is_create { input.request.operation == "CREATE" }
is_update { input.request.operation == "UPDATE" }

`
**Issue Identified** 

When I deployed an application, Deployment got mutated but seeing an unwanted value "apiVersion: v1" in one if the environment variable . Below given is the env variable added in the newly created Deployment 

`
spec:
  containers:
  - env:
    - name: APP_DELAY_TIME_NEW
      value: 12s
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(OTEL_K8S_HOST_IP):55680
    - name: OTEL_K8S_HOST_IP
      valueFrom:
        fieldRef:
          **apiVersion: v1**
          fieldPath: status.hostIP
    - name: APP_DELAY_TIME
      value: 1s
`

## Expected Behavior

Environment variable added should be as same as one given in the policy 

## Actual Behavior

Environment variable added has unwanted expected value "**apiVersion: v1**"

## Steps to Reproduce the Problem

1. Create the above given policy 
2. Create a deployment kind 
3. Check the deployment definition and see what all env variable got add and its values.

**Comment by anderseknert** [comment]
Hi @sanjaygopinath89! I don't think this is a bug - if you don't provide a version Kubernetes will simply fall back to the default value. See the [schema for ObjectFieldSelector](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#objectfieldselector-v1-core).

```
apiVersion | string | Version of the schema the FieldPath is written in terms of, defaults to "v1".
```

**Comment by sanjaygopinath89** [comment]
@anderseknert  ok its a default value. Thanks  for the details.
