### ISSUE TITLE
Inefficient type checking for builtins with object parameters 

### ISSUE THREAD

**Issue by jkbschmid** [open-policy-agent/opa#3564]
Hi there!

When `object.Get` is used on an object with 10^6 entries, type checking is in O(n^2) which leads to start-up times > 2h.

## Expected Behavior
```
checkInLargeObject {
 "myValue" == object.Get( largeObject, 3, "missing") 
}

largeObject = {
  "0": "test",
  ... # ~1,000,000 entries
}
```
When running `opa test .` without any test, OPA should terminate.

## Actual Behavior

OPA doesn't terminate (after two hours).
When using the same policy with regular object access instead of `object.Get`, `opa test` terminates.

## Additional Info

The root cause for this issue is that - during type checking - OPA tries to [unify](https://github.com/open-policy-agent/opa/blob/0be809feacd57fd3bfc2a6b09ea44361b1fcd70a/ast/check.go#L329) the large object with an arbitrary object. It uses `unifiesObjectsStatic`, which is in O(n^2) https://github.com/open-policy-agent/opa/blob/0be809feacd57fd3bfc2a6b09ea44361b1fcd70a/ast/check.go#L850-L853

OPA version: v0.29.4/master

## Proposed Solution

Would it be possible to add an early exit to `unifiesObjects` https://github.com/open-policy-agent/opa/blob/0be809feacd57fd3bfc2a6b09ea44361b1fcd70a/ast/check.go#L838 if of one of the objects is 'arbitrary' (as is the case for `object.Get`)? 
If I am not mistaken, then the types of objects to be unified `a` and `b` are not modified during unification, so an early exit should be permissible.

Thank you!

**Comment by tsandall** [comment]
@jkbschmid I've just opened #3567 which should speed things up a bit (though it's not going to be O(1) like it would be if we special cased the `object[any:any]` case...) I did a quick test and it looks like the type check phase takes about 12 seconds on an object with 1,000,000 keys.

**Comment by jkbschmid** [comment]
Hi @tsandall , thanks for the quick reply + fix! 
I'll load the list as data - I guess this is the proper way to use OPA ;)
