### ISSUE TITLE
Print OPA query result output in decision logs

### ISSUE THREAD

**Issue by AvniWala-Sophos** [open-policy-agent/opa#3568]
## Expected Behavior
Note: This is a query, not an issue.

I configured OPA with Envoy using grpc interface. Respective sections of configmap are as provided in "Steps to Reproduce" section below.

My policy rego file looks like so: https://play.openpolicyagent.org/p/ofSZBo0lYV

A typical output of the above policy would be:
{
    ...
    "decision": {
        "allow": false,
        "reason": "Device Unhealthy"
    },
    ...
}

I have enabled decision logs and they print the query result as "true/false".  

However, I am interested in printing the entire output of decision section:

    "decision": {
        "allow": false,
        "reason": "Device Unhealthy"
    },

Is there any way I can achieve this?

## Steps to Reproduce the Problem
Relevant sections from envoy and opa configmaps are as below:

opa-configmap.yaml

    plugins:
         envoy.ext_authz.grpc:
           addr: :{{ .Values.opa.ports.grpcPort }}
           query: data.envoy.authz.decision.allow

envoy-configmap.yaml

    static_resources:
      clusters:
      - name: opa
        connect_timeout: 30.0s
        type: logical_dns
        load_assignment:
          cluster_name: opa
          endpoints:
          - lb_endpoints:
              endpoint:
                address:
                  socket_address:
                    address: {{ .Values.opa.name }}
                    port_value: {{ .Values.opa.ports.grpcPort }}

## Additional Info
OPA Version: 0.28.0-envoy
Envoy Version: 1.14.4

**Comment by srenatus** [comment]
Have a look at using an object response instead: https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-object-response

You can then insert any keys you'd like in to the policy's object response, and they'll all go into the decision log, without affecting the way opa-envoy-plugin decides that to do with the policy result. opa-envoy-plugin will only look at the keys that are relevant for it.

**Comment by AvniWala-Sophos** [comment]
> Have a look at using an object response instead: https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-object-response
> 
> You can then insert any keys you'd like in to the policy's object response, and they'll all go into the decision log, without affecting the way opa-envoy-plugin decides that to do with the policy result. opa-envoy-plugin will only look at the keys that are relevant for it.

Thanks @srenatus - I tried this out. I get response body in the decision logs if I make an http request, but when my interface between envoy and OPA is GRPC the policy fails because result does not evaluate into just a true/false. Any way to overcome that?

**Comment by srenatus** [comment]
We'll need more information to help you here. Please include your policy and the config used with opa-envoy-plugin. 😃

**Comment by AvniWala-Sophos** [comment]
> We'll need more information to help you here. Please include your policy and the config used with opa-envoy-plugin. 😃

Hi @srenatus  - Apologies for the delay. It did indeed work (there was a typo in my rego). Here is a working sample in case someone needs it in the future: https://github.com/AvniWala-Sophos/opa-envoy-grpc-test

Thanks much for your help!
