### ISSUE TITLE
Query regarding opa to find out if filebase64sha256 is used in terraform

### ISSUE THREAD

**Issue by prithakundu** [open-policy-agent/opa#3569]
This is query regarding opa.

Can we use opa to find out if in terraform lambda filebase64sha256 hash is used or filesha256?

**Comment by anderseknert** [comment]
I think something like:

```rego
is_filebase64sha256 {
	count(base64.decode(input.x)) == 44
}
```
ought to do it.

**Comment by prithakundu** [comment]
It doesn't work. base64.decode function is able to decode filesha256 hash key as well

**Comment by anderseknert** [comment]
Yes, the second assertion checking for length would fail on filesha256 though. Remember that both assertions must be true in order for the rule to be.

**Comment by prithakundu** [comment]
so the hash key for filebase64sha256 should always be 44? is there any chance that other hash key can also have length 44?

**Comment by anderseknert** [comment]
You can use `terraform console` to try the various SHA functions and check their output length. As far as I know these hashing functions will always return a fixed length hash, but I guess you'd have to check their implementations if you're looking for guarantees :)

**Comment by prithakundu** [comment]
Okay thanks for the help
