### ISSUE TITLE
Safety check on rule heads should raise error for vars declared with some

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3580]
There's a bug in the safety check that arises because of interaction between the safety check, locally declared variables, and comprehensions.

For example:

```rego
p[x] {
  some x
  [1 | x = 1]
}
```

This rule compiles however queries return an error (`var requires evaluation`). The problem is that `x` is never assigned in the body of the rule, so it appears in the output. However, the rule should not compile because `x` is never assigned. The reason it compiles is due to the interaction mentioned above...

In this case, the rule is rewritten to:

```rego
p[__local0__] {
  [1 | __local0__ = 1]
}
```

When we added the `some` keyword initially, we allowed it to declare variables inside of closures. Perhaps that was the wrong decision however undoing that now could break existing policies.

Once the rule is rewritten, the safety check runs but the error is discarded because it's for a generated variable (we don't report safety errors on generated vars because they create too much noise in the output.)

Note, this doesn't occur if the user would write something like:

```rego
p[x] { some x; x > 7 }  # safety error caught in body check
p[x] { some x }  # unused var declaration error
```

This only comes about because `some` can be used to declare vars local to comprehensions.

It should be possible to fix this problem by tweaking the rule head safety check to see if the rewritten var was user supplied.

**Comment by anderseknert** [comment]
Not that this rule makes sense, but I get the same `var requires evaluation` error even without the comprehension:
```rego
p[x] { some x }
```
With the other rule `p` rule present from your example it doesn't seem to trigger though as the `rego_unsafe_var_error` is thrown instead.
```rego
p[x] { some x; x > 7 }
p[x] { some x }
```
