### ISSUE TITLE
regarding how to create a new policy rule and execute it

### ISSUE THREAD

**Issue by nagarajtrivedi** [open-policy-agent/opa#3582]
## Expected Behaviour
-NA-
## Actual Behaviour
-NA-
## Steps to Reproduce the Problem
-NA-

## Additional Info
Hi, please let me know how to create a new policy rule, execute, do a benchmark testing. Also in what order the make commands should be executed. If there are any links or documents on these then please provide them.

**Comment by nagarajtrivedi** [comment]
Hi all, I want to know how to create a new policy rule, execute it and do the benchmark testing.
I have downloaded the code and want to know in what order I need to execute make commands like make build, make all, make generate etc
If there are any links or documents providing these information then please share them.

Thank You

**Comment by anderseknert** [comment]
Hi @nagarajtrivedi 👋 

The [OPA docs](https://www.openpolicyagent.org/docs/latest/) are great for getting started. Did you check them out yet?

**Comment by srenatus** [comment]
I'll clean this up. Please don't hesitate re-opening, or adding another issue with any questions you can't find a good answer for 😃
