### ISSUE TITLE
Resolving contradictory assignments during partial evaluation

### ISSUE THREAD

**Issue by jkbschmid** [open-policy-agent/opa#3587]
Hi there!

I am doing partial evaluation with the policy below that is always undefined. The example is obviously simplified, but we do have the use case where the input decides which policy to evaluate, which leads to similar constructs. 

`opa eval -p data.allow -d test.rego -u input.action`
```
allow {
    test1
    test2
}
test1{
  "A" == input.action
}
test2{
  "B" == input.action
}
```

## Expected Behavior
undefined

## Actual Behavior
```
+---------+--------------------+
| Query 1 | "A" = input.action |
|         | "B" = input.action |
+---------+--------------------+
```

## Solution

Would it theoretically be possible to detect and resolve such cases?
It seems like the whole `"B" = input.action` expression is added to the saveStack without any unification (I think this is by design).  
Could we do unification if the expression is of a certain form, e.g. if a literal is assigned to a ref?

To reproduce the behaviour above, the policy can even be simplified further
```
allow {
  "A" == input.action
  "B" == input.action
}
``` 

OPA version: 0.29.4

Thank you!

**Comment by srenatus** [comment]
Hey there, thanks for the report.

I've run into this before myself -- but in the context of the time it takes to PE a policy: https://github.com/open-policy-agent/opa/issues/1447

So, just for clarification: you're not interested in performance (like, avoiding cross products in support rules) here, right?

Assuming that, I'll have a closer look at what happens with your example code. 🔍

**Comment by jkbschmid** [comment]
Hi @srenatus, thanks for looking into it! :)
> you're not interested in performance (like, avoiding cross products in support rules) here, right?


No, at this point, I'm not interested in performance, only about more rigorous evaluation. 
I'd be interested to know, if the behaviour mentioned above is a bug or by design and whether it would make sense to evaluate further.

**Comment by srenatus** [comment]
I don't think it's a bug, but I'll have a closer look into how we could avoid it.

For non-partial evaluation, such a rule (`allow { "A" = input.action; "B" = input.action }`) would be ignored: the rule indexer would never return for evaluation. Compare: 

```
$ echo '{"action": "A" }' | opa eval --disable-indexing --format=pretty --explain=full -I -d pe.rego data.pe.allow
query:1       Enter data.pe.allow = _
query:1       | Eval data.pe.allow = _
query:1       | Index data.pe.allow (matched 1 rule)
pe.rego:3     | Enter data.pe.allow
pe.rego:4     | | Eval "A" = input.action
pe.rego:5     | | Eval "B" = input.action
pe.rego:5     | | Fail "B" = input.action
pe.rego:4     | | Redo "A" = input.action
query:1       | Fail data.pe.allow = _
undefined
$ echo '{"action": "A" }' | opa eval --format=pretty --explain=full -I -d pe.rego data.pe.allow
query:1     Enter data.pe.allow = _
query:1     | Eval data.pe.allow = _
query:1     | Index data.pe.allow (matched 0 rules)
query:1     | Fail data.pe.allow = _
undefined
```

Given an unknown `input` (or `input.action`), i.e. PE, it looks like the indexer returns everything. 🤔

**Comment by jkbschmid** [comment]
Interesting, I hadn't thought about the indexer yet. 🤔
I'm not sure if my original problem can be solved via the indexer, though, because I simplified the original code quite a bit.

This is the what one of our policies looks like:
```
allow {
    data.package1[input.policy1]
    data.package2[input.policy2]
}
```
So the policies in allow are not necessarily contradictory, but they can be. Since the indexer is built independent of the input (right?), it won't be able to detect contradictions.

**Comment by srenatus** [comment]
> Since the indexer is built independent of the input (right?), it won't be able to detect contradictions.

The index is built independent of the input, and the input is used to retrieve applying rule bodies at eval-time.

I was thinking about a side-track here, though -- the indexer would help if it was processing your (simplified) PE output. However, that's not the case, there's no second eval involved here.

----

Just how simplified is your example? I was thinking about ways to make the rule body
```rego
x = "foo"
x = "bar"
```
fail type checking, which could be used to eliminate such a query from the PE result. Would you think that this would help?

**Comment by jkbschmid** [comment]
>I was thinking about a side-track here, though -- the indexer would help if it was processing your (simplified) PE output.

Ah ok, I get it. Thanks for the explanation.

---

> Just how simplified is your example? 

There's some more simplification there, e.g. we use a partial function and one orderer statement to preprocess input. I'm not allowed yet to publicly share the code, unfortunately. 
At what point would this type check be done? Before or after evaluation? 

If it's done before, I don't think it would help in my special case.
