### ISSUE TITLE
Go 1.17 - Test failure in gojsonschema time format validation

### ISSUE THREAD

**Issue by olivierlemasle** [open-policy-agent/opa#3589]
## Expected Behavior

Test success (works for Go <= 1.16)

## Actual Behavior

Test failure with Go 1.17 rc:

```
--- FAIL: TestFormats (0.07s)
    jsonschema_test.go:102: Test failed : /opa/internal/gojsonschema/testdata/draft7/optional/format/time.json
        validation of time strings.
        only RFC3339 not all of ISO 8601 are valid.
        expects: false, given true
        Schema: {"format":"time"}
        Data: "01:01:01,1111"
```
## Additional Info

A test in [`internal/gojsonschema/testdata/draft7/optional/format/time.json`](https://github.com/open-policy-agent/opa/blob/47feea7cbb25d45b3ecb431fb14289dde4432602/internal/gojsonschema/testdata/draft7/optional/format/time.json) verifies that `01:01:01,1111` **fails** to validate as a time.

Time validation is done here: https://github.com/open-policy-agent/opa/blob/47feea7cbb25d45b3ecb431fb14289dde4432602/internal/gojsonschema/format_checkers.go#L266-L271

However ` _, err := time.Parse("15:04:05", "01:01:01,1111")` returns an error `parsing time "01:01:01,1111": extra text: ",1111"` with Go <= 1.16, and no error with Go 1.17.

This is due to this change in Go: https://github.com/golang/go/commit/f02a26bed0f21de7aeef7a60cf62dac2e3dab737 ("," supported as separator for fractional seconds)

**Comment by srenatus** [comment]
Thanks for raising this. Let's fix it. I'm not certain, but I don't think that this has a huge relevance for our use of json schema 🤔 Also, it would mean that some previously forbidden inputs become valid, as far as I understand.

What would be the best approach in your opinion? I'm not sure this is even worth introducing a build tag for go 1.17 into our tests... 💭

**Comment by olivierlemasle** [comment]
- I've just updated my comment above (I had mixed `TimeFormatChecker` and `DateTimeFormatChecker`);
- As the objective of the failing test is to verify that the JSON schema requires RFC 3339 and not all valid ISO 8601 times, I would switch to test `14:30`, which is a valid (according to [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601), as I don't have access to the ISO spec), but not a RFC 3339 "full-time".
- I don't think a build tag for go 1.17 is currently needed.
