### ISSUE TITLE
Getting error messages displayed when tried executing test script to validate rules

### ISSUE THREAD

**Issue by nagarajtrivedi** [open-policy-agent/opa#3594]
## Expected Behavior
It should execute the policy rule verification test scripts successfully (example_test.rego)
## Actual Behavior
Displaying error message as 
./opa test . -v
4 errors occurred:
example_test.rego:3: rego_unsafe_var_error: var allow is unsafe
example_test.rego:7: rego_unsafe_var_error: var allow is unsafe
example_test.rego:11: rego_unsafe_var_error: var allow is unsafe
example_test.rego:15: rego_unsafe_var_error: var allow is unsafe
## Steps to Reproduce the Problem
1. Access this page https://www.openpolicyagent.org/docs/latest/policy-testing/
2. Create both example.rego and example_test.go as described in the web page from step 1
3. run the command ./opa test . -v

## Additional Info
The OS environment was Ubuntu

**Comment by anderseknert** [comment]
This works as expected here. Did you by any chance rename the `package` in one of the files?

**Comment by nagarajtrivedi** [comment]
Hi anderseknert, it works. Yes exactly same thing happened. In one of the file it was written as 'auth' instead of 'authz' and it worked.

Thanks
Nagaraj
