### ISSUE TITLE
Consider publishing images to GitHub Container Registry

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/opa#3596]
Any thought on publishing container images to GitHub Container Registry as well as / instead of Docker Hub? Would be happy to create the PR, would look something like this: https://github.com/artis3n/ansible_galaxy_collection/blob/main/.github/workflows/release.yml#L18

**Comment by srenatus** [comment]
Hey there. Thanks for raising this.

May I ask what your main impetus is here? Why prefer GitHub registry over dockerhub? 🤔

**Comment by srenatus** [comment]
Ah nevermind you've mentioned that in the conftest issue. ✔️

**Comment by anderseknert** [comment]
As a Docker-"approved" open source project, none of our (including projects like conftest, gatekeeper, etc) images are subject to rate limiting. Might still be nice with an alternative registry, but there's that.

**Comment by artis3n** [comment]
> Ah nevermind you've mentioned that in the conftest issue. ✔️ 

Yeah, but to copy the same in this ticket: 

> Benefit would be small convenience in avoiding Docker Hub rate limits in edge case scenarios. I guess maybe if one goes temporarily down it's already up somewhere else. It is mostly for my preference, to be honest.

Although the rate limit isn't a problem for this project it turns out. I have no real justification then :shrug:

**Comment by tsandall** [comment]
I'm going to close this for now since there's no need to switch at this time.
