### ISSUE TITLE
OPA Policy Authoring > "var allow is unsafe" errors

### ISSUE THREAD

**Issue by dxps** [open-policy-agent/opa#3597]
Dear all,

While studying and playing with _CarInfoStore_ sample, part of the nice [OPA Policy Authoring](https://academy.styra.com/courses/opa-rego) course, I noticed an issue whose cause is unclear atm:

- Using VSCode, it all works fine: policy and its test are parsed without complains, and _OPA: Evaluate Package_ command runs fine.

- But when trying to have it loaded as bundle into a local OPA (ver. `0.29.4`, currently the latest release), it throws a couple of `rego_unsafe_var_error: var allow is unsafe` errors. 

All the details, including the scripts used for this setup can be found [here](https://github.com/dxps/opa_playground/tree/master/basic_rego_rules).

Any hints, please?

Thank you!

**Comment by srenatus** [comment]
Hey. I'm having a look -- first of all, this is a great way to open an issue, with reproduction steps etc. 💯 Thanks for putting in the effort.

**Comment by dxps** [comment]
Hi Stephan, as always, your feedback is a very friendly and welcoming one! :hugs:   Sure, glad to help.

**Comment by srenatus** [comment]
Uhm it looks like your bundle only contains the test rego file. So, it makes sense that it cannot find `allow`, as it's not defined as far as this bundle is concerned:
```
$ tar tf basic_rego_rules/bundles/test_basic_rego_rules___bundle.tar.gz
test_basic_rego_rules___policy.rego
```

How did you create that bundle?

**Comment by srenatus** [comment]
I've created a new bundle with both files included:

```
$ cd basic_rego_rules/
basic_rego_rules $ tar czf bundles/test_basic_rego_rules___bundle.tar.gz basic_rego_rules___policy.rego test_basic_rego_rules___policy.rego
basic_rego_rules $ file bundles/test_basic_rego_rules___bundle.tar.gz
bundles/test_basic_rego_rules___bundle.tar.gz: gzip compressed data, last modified: Wed Jun 30 07:35:23 2021, from Unix, original size modulo 2^32 5120
basic_rego_rules $ opa eval -b bundles/test_basic_rego_rules___bundle.tar.gz data
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "rules": {
              "allow": false,
              "test___car_create___anyone": true,
              "test___car_create___employee": true,
              "test___car_create___manager": true,
              "test___car_status___anyone": true,
              "test___car_status___employee": true,
              "test___car_status___manager": true,
              "test___car_update___anyone": true,
              "test___car_update___employee": true,
              "test___car_update___manager": true,
              "test_car_read_negative": true,
              "test_car_read_positive": true,
              "user_is_employee": false,
              "users": {
                "alice": {
                  "manager": "charlie",
                  "title": "salesperson"
                },
                "bob": {
                  "manager": "charlie",
                  "title": "salesperson"
                },
                "charlie": {
                  "manager": "dave",
                  "title": "manager"
                },
                "dave": {
                  "manager": null,
                  "title": "ceo"
                }
              }
            }
          },
          "text": "data",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
basic_rego_rules $
```

**Comment by dxps** [comment]
Oh no! Such a silly mistake! :facepalm:  I was in a hurry of documenting and testing. Sorry for bothering with it.

Recreated the bundle correctly (with just the policy, using a simple `https://signicat.atlassian.net/wiki/spaces/TECH/pages/21782724651/Cross-Service+AuthN`), and it's all good! Updated also the aforementioned materials.

<br/>

:information_source:  Still related to OPA and contributing to it, probably I will try to have a quick talk with you in another issue context or another channel (if you prefer). Let me just get the clearance from my employer first.

Other than that, I'll still look into other ways to help. Thanks again for the quick feedback and help!

**Comment by srenatus** [comment]
No worries! 😃 

Happy to chat in whatever channel you'd like.

I wasn't able to access that confluence page. LMK if there's something you'd like me to see. 👀

**Comment by dxps** [comment]
Definitely, it seems that I need to wake up this morning. That was another wrong copy/paste. Thanks again! :pray:
