### ISSUE TITLE
opa-envoy-plugin: parse application/x-www-form-urlencoded request bodies

### ISSUE THREAD

**Issue by rszabolcs** [open-policy-agent/opa#3600]
## Expected Behavior
As I currently understand it is not possible to make OPA decision based on body contents that has content type `application/x-www-form-urlencoded`.

## Actual Behavior
Decision log says "content-type: application/x-www-form-urlencoded parsing not supported".
Also the `parsed_body` is empty:
`[
      {
        "type": "string",
        "value": "parsed_body"
      },
      {
        "type": "null",
        "value": {}
      }
    ]
`

## Steps to Reproduce the Problem
Make some POST request with said content type and try to process its body at OPA side. Eg.

> POST /test HTTP/1.1
> Host: foo.example
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 27
> 
> field1=value1&field2=value2
> 

## Additional Info
Converting to JSON-object would be very useful or as a fallback solution in such cases the raw body could also be sent to OPA to process it there.

This [function](https://github.com/open-policy-agent/opa-envoy-plugin/blob/8db9ac9b51e5cd631a17be61ec32a2f4f04b1f9d/envoyauth/request.go#L109) seems related.

**Comment by ashutosh-narkar** [comment]
> Converting to JSON-object would be very useful or as a fallback solution in such cases the raw body could also be sent to OPA to process it there.

@rszabolcs are you saying the raw body is not passed to OPA when content-type is `application/x-www-form-urlencoded` ?

**Comment by rszabolcs** [comment]
@ashutosh-narkar If understand correctly then [this](https://github.com/open-policy-agent/opa-envoy-plugin/blob/8db9ac9b51e5cd631a17be61ec32a2f4f04b1f9d/envoyauth/request.go#L26) function should do that. If that't the case, then yes, the raw body is missing. Would be great if I was wrong.

**Comment by srenatus** [comment]
Let's verify a few things:

- Are you using the V3 ext authz protocol?
- Have you set [`with_request_body `](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-field-extensions-filters-http-ext-authz-v3-extauthz-with-request-body)?

I'll run a few tests myself here, but I believe `raw_body` will only be populated if you specify `pack_as_bytes`:

> `pack_as_bytes` (bool) If true, the body sent to the external authorization service is set with raw bytes, it sets the `raw_body` field of HTTP request attribute context. Otherwise, `body` will be filled with UTF-8 string request body.

**Comment by srenatus** [comment]
So, running `curl -d "param1=value1&param2=value2" -X POST http://127.0.0.1:51051` to send a x-www-form-urlencoded form through envoy + opa-envoy-plugin, with a config having `pack_as_bytes: true` gives me the following decision log entry (its policy is `default allow = false`, I merely wanted to see the input from the decision log):

```json
{
  "decision_id": "b26c6996-f561-4a71-9d8f-16af923aa027",
  "input": {
    "attributes": {
      "destination": {
        "address": {
          "socketAddress": {
            "address": "172.31.0.4",
            "portValue": 51051
          }
        }
      },
      "metadataContext": {},
      "request": {
        "http": {
          "headers": {
            ":authority": "127.0.0.1:51051",
            ":method": "POST",
            ":path": "/",
            ":scheme": "http",
            "accept": "*/*",
            "content-length": "27",
            "content-type": "application/x-www-form-urlencoded",
            "user-agent": "curl/7.64.1",
            "x-envoy-auth-partial-body": "false",
            "x-forwarded-proto": "http",
            "x-request-id": "d77dac95-f7d8-4f43-a067-b8fe4f9b14aa"
          },
          "host": "127.0.0.1:51051",
          "id": "8697434616907312425",
          "method": "POST",
          "path": "/",
          "protocol": "HTTP/1.1",
          "rawBody": "cGFyYW0xPXZhbHVlMSZwYXJhbTI9dmFsdWUy",
          "scheme": "http",
          "size": "27"
        },
        "time": "2021-07-01T08:40:23.310085Z"
      },
      "source": {
        "address": {
          "socketAddress": {
            "address": "172.31.0.1",
            "portValue": 61374
          }
        }
      }
    },
    "parsed_body": null,
    "parsed_path": [
      ""
    ],
    "parsed_query": {},
    "truncated_body": false,
    "version": {
      "encoding": "protojson",
      "ext_authz": "v3"
    }
  },
  "labels": {
    "id": "25eb36f0-ce30-4f91-baa8-cf03bbb80a47",
    "version": "0.26.0-envoy"
  },
  "level": "info",
  "metrics": {
    "timer_rego_query_eval_ns": 67900,
    "timer_server_handler_ns": 315900
  },
  "msg": "Decision Log",
  "path": "envoy/authz/allow",
  "requested_by": "",
  "result": false,
  "time": "2021-07-01T08:40:23Z",
  "timestamp": "2021-07-01T08:40:23.3111969Z",
  "type": "openpolicyagent.org/decision_logs"
}
```

Note the `rawBody: cGFyYW0xPXZhbHVlMSZwYXJhbTI9dmFsdWUy`, which is:
```
$ opa eval --format=pretty 'base64.decode("cGFyYW0xPXZhbHVlMSZwYXJhbTI9dmFsdWUy")'
"param1=value1\u0026param2=value2"
```

With `pack_as_bytes: false`, we get this input:

```json
{
  "decision_id": "ee6e4adb-acad-4810-be3a-4cbf4ed9cee7",
  "input": {
    "attributes": {
      "destination": {
        "address": {
          "socketAddress": {
            "address": "192.168.0.4",
            "portValue": 51051
          }
        }
      },
      "metadataContext": {},
      "request": {
        "http": {
          "body": "param1=value1&param2=value2",
          "headers": {
            ":authority": "127.0.0.1:51051",
            ":method": "POST",
            ":path": "/",
            ":scheme": "http",
            "accept": "*/*",
            "content-length": "27",
            "content-type": "application/x-www-form-urlencoded",
            "user-agent": "curl/7.64.1",
            "x-envoy-auth-partial-body": "false",
            "x-forwarded-proto": "http",
            "x-request-id": "8ebe4527-759c-437f-8de1-f003aa01ea43"
          },
          "host": "127.0.0.1:51051",
          "id": "12159437848725456569",
          "method": "POST",
          "path": "/",
          "protocol": "HTTP/1.1",
          "scheme": "http",
          "size": "27"
        },
        "time": "2021-07-01T08:46:39.723236Z"
      },
      "source": {
        "address": {
          "socketAddress": {
            "address": "192.168.0.1",
            "portValue": 60340
          }
        }
      }
    },
    "parsed_body": null,
    "parsed_path": [
      ""
    ],
    "parsed_query": {},
    "truncated_body": false,
    "version": {
      "encoding": "protojson",
      "ext_authz": "v3"
    }
  },
  "labels": {
    "id": "7c0a1dcb-eb5b-4fbf-9d25-09f213a41b27",
    "version": "0.26.0-envoy"
  },
  "level": "info",
  "metrics": {
    "timer_rego_query_compile_ns": 223800,
    "timer_rego_query_eval_ns": 37400,
    "timer_server_handler_ns": 545800
  },
  "msg": "Decision Log",
  "path": "envoy/authz/allow",
  "requested_by": "",
  "result": false,
  "time": "2021-07-01T08:46:39Z",
  "timestamp": "2021-07-01T08:46:39.7261521Z",
  "type": "openpolicyagent.org/decision_logs"
}
```
Note that `input.request.body` is `"param1=value1&param2=value2"`.


------
👉 here's my playground: https://github.com/srenatus/opa-istio-plugin/commit/4572013ddae7cb85daf2f3852d3718d59aabc605

**Comment by rszabolcs** [comment]
Dear @srenatus , you are my hero! Indeed, with the suggested settings of `with_request_body` I could achieve the fallback solution so I can move forward for the time being.

Nevertheless, adding the parsing capability still would be really nice to have.
