### ISSUE TITLE
issue with indexof in 0.30.0

### ISSUE THREAD

**Issue by AndreyLevchenko** [open-policy-agent/opa#3606]
I'm getting weird result when calling `indexof` with opa 0.30.0 on ubuntu
```
test_index_of {
 r:=my_test with input as {"cmd":"apt-get update && adduser mike", "install":"install"}
}
my_test[res] {
 res:=indexof(input.cmd,input.install)
}

```

## Expected Behavior
```
{
r:-1
}
```

## Actual Behavior
result is 
```
{
r:27
}
```
## Steps to Reproduce the Problem
run code above

**Comment by anderseknert** [comment]
Thanks for reporting this @AndreyLevchenko! 0.30.0 added support for unicode code points, but looks like we mistakenly only scan for the first character now.

https://github.com/open-policy-agent/opa/blob/main/topdown/strings.go#L105

Fixing.

**Comment by srenatus** [comment]
ℹ️ We'll push a 0.30.1 release when this is done.

**Comment by srenatus** [comment]
Fixed on main. Release in progress. I'll close this -- Thanks @anderseknert for the quick fix 👏
