### ISSUE TITLE
want to know the procedure to find total time took to execute benchmark testing

### ISSUE THREAD

**Issue by nagarajtrivedi** [open-policy-agent/opa#3607]
## Expected Behavior
It should display total time took to execute certain number of test cases for verifying rules as part of benchmark testing
## Actual Behavior
It is displaying the time took for executing each individual test case for verifying rules
## Steps to Reproduce the Problem
./opa test --bench -v example.rego example_test.rego

## Additional Info
It is run on ubuntu OS

**Comment by srenatus** [comment]
What do you mean by _total time_? The `opa test --bench` command will execute a non-fixed number of runs to get a good estimate of the test performance. See [the benchmark docs](https://www.openpolicyagent.org/docs/edge/policy-performance/#example-benchmark-rbac-unit-tests), where an example output is
```
data.rbac.test_user_has_role_dev	   44749	     27677 ns/op	     23146 timer_rego_query_eval_ns/op	   12303 B/op	     229 allocs/op
data.rbac.test_user_has_role_negative	   44526	     26348 ns/op	     22033 timer_rego_query_eval_ns/op	   12470 B/op	     235 allocs/op
```

The first number is how often the test was run, `data.rbac.test_user_has_role_dev` was run 44749 times, and the **average** time a run took was 27677 ns.

Given that, what's the **total** your interested in? 

If you need a better idea of your query performance, it `opa bench` will give you percentiles (see [docs](https://www.openpolicyagent.org/docs/edge/policy-performance/#example-benchmark-rbac-allow)):

```
+-------------------------------------------+------------+
| samples                                   |      27295 |
| ns/op                                     |      45032 |
| B/op                                      |      20977 |
| allocs/op                                 |        382 |
| histogram_timer_rego_query_eval_ns_stddev |      25568 |
| histogram_timer_rego_query_eval_ns_99.9%  |     335906 |
| histogram_timer_rego_query_eval_ns_99.99% |     336493 |
| histogram_timer_rego_query_eval_ns_mean   |      40355 |
| histogram_timer_rego_query_eval_ns_median |      35846 |
| histogram_timer_rego_query_eval_ns_99%    |     133936 |
| histogram_timer_rego_query_eval_ns_90%    |      44780 |
| histogram_timer_rego_query_eval_ns_95%    |      50815 |
| histogram_timer_rego_query_eval_ns_min    |      31284 |
| histogram_timer_rego_query_eval_ns_max    |     336493 |
| histogram_timer_rego_query_eval_ns_75%    |      38254 |
| histogram_timer_rego_query_eval_ns_count  |      27295 |
+-------------------------------------------+------------+
```

**Comment by nagarajtrivedi** [comment]
Hi, thanks for your reply. I have already tried this and works fine for one single query.
But I want more than 1 query to be executed let us say 10, 20, 100, 200, 1000
For that purpose I have created 10 rules in a file example.rego and 10 queries in a file example_test.rego. I want to find out how much total time it takes to execute 10 queries against 10 rules.
Attached are the both rule file example.rego and query file example_test.rego
Please have a look at it and let me know how to do a benchmark testing in this scenario
Please note that the extension of file names is changed from .rego to .txt just for upload as it is accepting only .txt files. When you download it change its extension to .rego
[example.txt](https://github.com/open-policy-agent/opa/files/6754076/example.txt)
[example_test.txt](https://github.com/open-policy-agent/opa/files/6754077/example_test.txt)

Expecting your reply at the earliest.

Thanks
Nagaraj

**Comment by srenatus** [comment]
> For that purpose I have created 10 rules in a file example.rego and 10 queries in a file example_test.rego. I want to find out how much total time it takes to execute 10 queries against 10 rules.

I suppose you could use `opa bench` on one rule with a body that contains 10 queries, or something like that...

Our benchmark framework here is focused on microbenchmarking the evaluation times of rules and queries, it's probably not a good fit for what you're looking after.

On a general note, I'd wonder if some end-to-end benchmarking with OPA in a prototypical deployment wouldn't be more useful than knowing how long it takes to run one query 1000 times. 🤔  For example, see the recently added guidance docs on benchmarking OPA when used from Envoy: https://www.openpolicyagent.org/docs/latest/envoy-performance/

**Comment by nagarajtrivedi** [comment]
Thanks for the info. I will try.

Thanks
Nagaraj
