### ISSUE TITLE
Is http.send a server-runtime only feature? How to devlop/test policies with http.send?

### ISSUE THREAD

**Issue by keydon** [open-policy-agent/opa#3612]
## Expected Behavior
http.send should work in the REPL
http.send should work in the opa-cli eval cmd
http.send should be mockable in tests

## Actual Behavior
Seems to only work in server-mode `opa --server`

## Steps to Reproduce the Problem
i.e. 
```
$ opa run
 http.send({"method": "get", "url": "https://cat-fact.herokuapp.com/facts/1" })
> undefined
```

i.e.
```
$ opa eval 'http.send({"method": "get", "url": "https://cat-fact.herokuapp.com/facts/1" })'
{}
```

Windows 10
OPA 0.30.0 (commit 84d0b65, built at 2021-07-01T08:10:22Z)

**Comment by anderseknert** [comment]
That's weird - both seem to work on the same OPA version on my Mac.
Could you try adding `"raise_error": false` to the arguments and see if that provides any clues what goes wrong?

```rego
http.send({"method": "get", "url": "https://cat-fact.herokuapp.com/facts/1", "raise_error": false})
```

**Comment by srenatus** [comment]
Also please add `--strict-builtin-errors` to `opa eval` to see whatever error the builtin has hit.

The `{}` you see in the `opa eval` call is the same as the undefined in the REPL, but in a different format. If you do `opa eval --format=pretty`, it'll give you `undefined`.

**Comment by keydon** [comment]
```
$ opa eval 'http.send({"method": "get", "url": "https://cat-fact.herokuapp.com/facts/5887e1d85c873e0011036889", "raise_error": false })'
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "error": {
              "code": "eval_http_send_internal_error",
              "message": "http.send({\"method\": \"get\", \"url\": \"https://cat-fact.herokuapp.com/facts/5887e1d85c873e0011036889\", \"raise_error\": false }): eval_builtin_error: http.send
: crypto/x509: system root pool is not available on Windows"
            },
            "status_code": 0
          },
          "text": "http.send({\"method\": \"get\", \"url\": \"https://cat-fact.herokuapp.com/facts/5887e1d85c873e0011036889\", \"raise_error\": false })",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}

```

**Comment by keydon** [comment]
and
```
$ opa eval  --strict-builtin-errors 'http.send({"method": "get", "url": "https://cat-fact.herokuapp.com/facts/5887e1d85c873e0011036889" })'
{
  "errors": [
    {
      "message": "http.send: crypto/x509: system root pool is not available on Windows",
      "code": "eval_builtin_error",
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      }
    }
  ]
}

```

**Comment by anderseknert** [comment]
Oh, so it _was_ Windows specific! We'll need to work around that.. possibly in other places as well.

**Comment by srenatus** [comment]
Thanks, that's immensely helpful. Please try passing `"tls_use_system_certs": false` to the builtin. The default behaviour has changed in 0.29.0 (https://github.com/open-policy-agent/opa/pull/3481)...

**Comment by keydon** [comment]
holy crap, it works with `"tls_use_system_certs": false` :D THANK YOU :)
But without the argument it also does not work for "http"-only sites, interesting :D

**Comment by srenatus** [comment]
Sure thing.

We'd better fix this somehow. I suppose we could have the builtin _ignore_ `tls_use_system_certs` on Windows, so there would be no system certs whatsoever, regardless of how it's configured 🤔
