### ISSUE TITLE
Add rand.Intn(n) to built-in functions

### ISSUE THREAD

**Issue by base698** [open-policy-agent/opa#3615]
I have a use case where I'm directing traffic based on a set of rules.  Some of the rules involve only routing the request a fraction of the time.  I'm essentially just passing a random generated number into OPA and if it's X I return true.  The calling code can then stop the request from proceeding.  

Generating the random number in OPA would be cleaner.

**Comment by base698** [comment]
@srenatus https://github.com/open-policy-agent/opa/pull/3620

No tests yet, just posting for discussion.

**Comment by tsandall** [comment]
This is done with #3620!
