### ISSUE TITLE
Allow destination log path override 

### ISSUE THREAD

**Issue by dolevf** [open-policy-agent/opa#3618]
Hi,

Open Policy Agent, when configured to send logs remotely, is sending logs to `/logs` by default. When adding partitions, partitions are appended to `/logs/<partition>` as documented and expected.

This became a bit of a problem for me when I wanted to send logs to a SaaS SIEM. SIEMs would typically provide a static path, and they don't expect any paths after the designated endpoint.

For example, we are provided with an endpoint such as this:

`customer.saas-company.com/http/collect`

If we configure in OPA the following config:

```
services:
  siem:
    url: https://customer.saas-company.com/http/collect
```

OPA will append a `/logs` to this URL, resulting in a 404 from the remote logging system.

I'm hoping this can be addressed by allowing to override the default `/logs` with any other path (such as `/`). This is especially useful and important for security teams who want to keep track of decision logs using 3rd party security event aggregation systems.

**Comment by tsandall** [comment]
@dolevf thanks for filing this.

I suggest we add a new configuration field (`decision_logs.resource`) that lets users set the entire path like we do for bundles. This way OPA will `POST` to `<service_url>/<decision_logs.resource>`. The default value for `decision_logs.resource` can be `/logs` for backwards compatibility. If we put this in place, we can deprecate the `partition` option.

The changes required for this will be:

* Add new field to decision log config struct [here](https://github.com/open-policy-agent/opa/blob/main/plugins/logs/plugin.go#L229)
* Update the config validation/default injection function for the config struct [here](https://github.com/open-policy-agent/opa/blob/main/plugins/logs/plugin.go#L240) (right below the struct)
* Update the `uploadChunk` function [here](https://github.com/open-policy-agent/opa/blob/main/plugins/logs/plugin.go#L780) to use the configured path.
