### ISSUE TITLE
Add the description about Note event for debugging

### ISSUE THREAD

**Issue by enori** [open-policy-agent/opa#3628]
[Debugging](https://www.openpolicyagent.org/docs/latest/policy-reference/#debugging) feature is described in the official docs as follow. But a beginner like me did not know what Note event is, and it took me a while to figure out how to use it.

> trace outputs the debug message string as a Note event in the query explanation.

A brief description that what Note event is and how Note event is output is valuable for OPA beginners.
If you agree with this issue, I will create PullRequest.
What do you think?

**Comment by tsandall** [comment]
🙏 thank you for filing this @enori! Yes, I think for now a short example in that debugging section would be useful. Perhaps an `opa eval` example like: `opa eval --explain=notes --format=pretty 'trace("hello world")'`...?

**Comment by enori** [comment]
If you don't mind, let me send you a PullRequest later. I have the following as the PullRequest.

trace function can be used like `printf` function to output variables in processing in rules and functions.
The argument of trace function should be a single string, so if you output variables, you need to use `sprintf` function.

---
Note that the explanation is not output in default setting. To enable to output varriables, you have to set as the following. The way to set it depends on the provide form of OPA.

|   Provide Form   | Setting Way               | Example         | memo                   |
| ------------ | ----------------------- | ------------------------ | ---------------------- |
| CLI          | add option `--explain=notes`     | `opa eval --explain=notes --format=pretty 'trace("hello world")'` |                        |
| Server Mode | add query string `?explain=full` | `curl localhost:8181/v1/data/some_package?explain=full`           | Support for full only currently |

**Comment by tsandall** [comment]
hi @enori, sure, feel free to submit a PR. I did a bit of editing, here's what I came up with:



The `trace` function can be used to output the values of variables inside of rules similar to "printf" in other languages. The `trace` function accepts a single string argument as input. To print the value of variables call `sprintf` and pass the output into `trace`. For example:

```rego
x := 7; trace(sprintf("the value of x is %d", [x]))
```

When you call `trace`, the output is added to the _query explanation_ (which explains the steps the evaluator followed to produce the query result.) By default, explanations are disabled. The following table summarizes how you can enable tracing:

API | Parameter | Example | Memo
--- | --- | --- | ---
CLI | `--explain` | `opa eval --explain=notes --format=pretty 'trace("hello world")'` |
HTTP | `explain=notes` | `curl localhost:8181/v1/data/example/allow?explain=notes&pretty` |
REPL | `notes` | n/a | The "notes" command enables trace explanations. See `help` for more details`.

**Comment by srenatus** [comment]
Ah this is merged. Thanks again!
