### ISSUE TITLE
Clarify what count special characters for key

### ISSUE THREAD

**Issue by Hongbo-Miao** [open-policy-agent/opa#3638]
Based on https://www.openpolicyagent.org/docs/latest/configuration/#keys-with-special-characters

> If you have a key which contains a special character (`.`, `=`, etc), like opa.example.com, and want to use the `--set` or `--set-file` options you will need to escape the character with a backslash (`\`).

Currently it uses "etc", it would be great to clarify more what count special characters.
For example I am wondering does `_` and `-` count as they are very common being used.
Or provide a full list of characters that count special, that will be very helpful too.

Thanks! 😀

**Comment by tsandall** [comment]
[The runs happen to be: `= [ , .`](https://github.com/open-policy-agent/opa/blob/main/internal/strvals/parser.go#L139). If you could submit a patch on the docs it would be much appreciated. [Here](https://github.com/open-policy-agent/opa/blob/main/docs/content/configuration.md#keys-with-special-characters) is the source for that page.

**Comment by Hongbo-Miao** [comment]
Sure, happy to help. Thanks for the info!

**Comment by Hongbo-Miao** [comment]
Done at #3642
