### ISSUE TITLE
Support for excluding certain variables/functions from opa test --coverage

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/opa#3640]
## Expected Behavior

Would love to be able to exempt a specific line(s) or function from coverage such that `opa test --coverage` doesn't flag us as missing that function. Not sure what format that exemption should take, not really a fan of this comment but to highlight what behavior is missing:

```rego
# COVERAGE: exempt-next-line
my_function(stuff) = output {
  # ...
}
```

When `opa test --coverage` is run, the output is JSON by default and lists the file name as a key, then a map of `{"covered": [...], "not_covered": [..], "coverage": <float>}`. Another key named `"exceptions": [...]` should be added in similar format to `covered` and `not_covered` that includes the lines exempted from coverage in that file. The similar format is an entry in the array looking like `{"start": { "row": <int> }, "end": { "row": <int> }}`. The final `coverage` float calculation should exclude any lines under `exceptions`.

## Actual Behavior

The behavior does not exist today.

## Steps to Reproduce the Problem

See https://github.com/open-policy-agent/opa/issues/3639 for more detail on the actual policy I'm working on where I hit this gap in opa coverage functionality.

## Additional Info

See https://github.com/open-policy-agent/opa/issues/3639 for additional information on the policy I'm working on where this need arose.

**Comment by tsandall** [comment]
Generally speaking, most policies can be covered completely by tests. The only time when this isn't feasible is when built-in functions have to be mocked out because of external dependencies (e.g., http.send). If we added function mocking as described in #2028 then we could potentially just mock out http.send and then the policy would have perfect coverage.

Another potential solution that comes to mind would be pragmas/build constraints that exclude .rego files from being loaded... for example:

```rego
# pragma: +test
package foo.bar

my_function(x, y) = output {
  # mocked function logic
}
```

```rego
# pragma: -test
package foo.bar

my_function(x, y) = http.send(...)
```

**Comment by artis3n** [comment]
I like the pragma approach, that would also solve my core need. #2028 would also be a way to get full coverage of policies such that excepting certain lines would not be "necessary."

**Comment by anderseknert** [comment]
With https://github.com/open-policy-agent/opa/issues/2028 now implemented, do you think we can close this, @artis3n ?

**Comment by artis3n** [comment]
I've moved roles and we unfortunately don't use OPA here - yet! - so just eyeballing that PR, but it looks like a great solve for this issue.
