### ISSUE TITLE
Evaluation order inside policy using type assertion is not working

### ISSUE THREAD

**Issue by fams** [open-policy-agent/opa#3643]
I´m trying to create a policy with different behaviours depending input data.

## Expected Behavior
Only rule with is_array() is evaluated

## Actual Behavior
Both Rules are evaluated raising a type mismatch

1 error occurred: policy.rego:34: rego_type_error: split: invalid argument(s)
	have: (array<string, string>, string, ???)
	want: (string, string, array[string])

## Steps to Reproduce the Problem

Code:
https://play.openpolicyagent.org/p/A0rGnmtdaQ

roles = ["foo", "bar"]
#roles = "foo bar"

trusted = [ "foo", "zoo"]

my_roles = r {
 is_array(roles)
 r = roles
}
my_roles = r {
 is_string(roles)
 r = split(roles, " ")
}

**Comment by anderseknert** [comment]
When you make `roles` a constant like that, the type checker will know the type of `roles` beforehand, and won't like it when you try to provide it as an argument for functions taking other types in their args. This won't happen when using the `input` variable, as the contents of that can't be known until runtime. See [example here](https://play.openpolicyagent.org/p/A0rGnmtdaQ).

**Comment by srenatus** [comment]
🤦 How did I not see this. Thanks 👏 @anderseknert 

@fams do you think we can close this?
