### ISSUE TITLE
Add --sample flag to eval running in profiler mode

### ISSUE THREAD

**Issue by gabbifish** [open-policy-agent/opa#3651]
## Expected Behavior

`opa eval --profile` has been incredibly useful. Between multiple runs of the same `opa eval --profile` invocation, we've noticed variance of up to a factor of 2 between the same lines, and we would be interested in having sampling available to smooth out this variance.

## Actual Behavior

Include a `--sample` flag for `opa eval --profile`, similar to the `--sample` flag for `opa bench`

**Comment by srenatus** [comment]
> similar to the `--sample` flag for `opa bench`

You got me confuse there...you probably mean `--count`, I think?

```
      --count int                      number of times to repeat each benchmark (default 1)
```
(That's from `opa bench --help`.)

**Comment by gabbifish** [comment]
@srenatus ah, you're right--`--count` is what I was referring to!

**Comment by srenatus** [comment]
@gabbifish I've made a sketch for discussion purposes, https://github.com/open-policy-agent/opa/pull/3655 -- I'd appreciate your input!
