### ISSUE TITLE
verify_rs256 and decode_verify

### ISSUE THREAD

**Issue by roygbip** [open-policy-agent/opa#3658]
`verify_rs256 `return `true` but `decode_verify` return `false`, why?

![image](https://user-images.githubusercontent.com/16715027/126038119-e4a10b26-6bcb-4136-b5b6-d16b44255e91.png)

**Comment by roygbip** [comment]
sorry, i forget the "aud" claim. this is not in the examples.

**Comment by srenatus** [comment]
Docs improvements are always welcome - sorry you've had to stumble there
