### ISSUE TITLE
Include the file name in the input data for a policy

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/opa#3662]
## Expected Behavior

When evaluating a large set of files, it would be very useful to be able to match against certain known file names as opposed to attempting to examine the input to match that file's expectation. This is for scenarios where we are evaluating a set of policies against a set of arbitrary files and we need the Rego to determine which policies should apply to which input. Perhaps a feature flag to enable such behavior to avoid breaking input expectations for the existing Rego schema.

I am using Conftest however I believe the feature request is on the OPA side in terms of a feature request in how input to a Rego policy is structured.

## Actual Behavior

Supported files are parsed into a JSON representation with no mapping to the file the input comes from.

## Steps to Reproduce the Problem

1. Create a `package.json` file
2. Create a Rego policy to evaluate whether [publishConfig](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#publishconfig) is set correctly on the npm package as internal packages are required to be published to a private registry (this is one example. Our policies will be OSS soon but for now cannot link to the direct source)
3. The only requirements for a `package.json` file is that the top-level input contains a `name` and a `version` field. When evaluating arbitrary input from a source code commit for security policy violations, the only current way to attempt to determine whether a file is appropriate to evaluate against this policy is to check whether the top-level input contains `name` and `version` fields. This can match multiple file inputs. Instead, would be helpful to be able to say if `input.filename == "package.json"` then do something with `input.data`, where what I am envisioning as `input.data` is just `input` today.

## Additional Info

Is this more relevant as a feature request for Conftest? Seems like a tall order to ask for that schema change in Rego, may be more manageable as a differentiating feature inside Conftest.

**Comment by tsandall** [comment]
hey @artis3n, thanks for filing this. One option would be to leave `input` as is (representing the file content) and instead put the metadata that you're describing (e.g., basename, absolute path, etc.) under `data`, e.g., `data.system.file.basename` or something.

Like you said, I think that it would be easier to implement this inside of Conftest for the time being because we don't have an opinionated CLI runner for testing config files with Rego inside of `opa` (it's something we'd like to do but it's not high priority since Conftest already does it.)

**Comment by artis3n** [comment]
Absolutely, thanks for the feedback. We can close this
