### ISSUE TITLE
partial evaluation response

### ISSUE THREAD

**Issue by javid-dastgoshadeh** [open-policy-agent/opa#3677]
I have a rule in rego and I want to send request to v1/complie direction to partial evalution and I get a json response .How to I convert this response to sql query to enforce that in mysql.I use php and I can't find a packege to do it.
thank you from your helps.

**Comment by srenatus** [comment]
> I use php and I can't find a packege to do it.

I'd start searching through https://github.com/open-policy-agent/contrib, but on a quick look, there is nothing php-related.

You could use [the python code there as a example](https://github.com/open-policy-agent/contrib/blob/main/data_filter_example/data_filter_example/sql.py).

**Comment by andrewbanchich** [comment]
I've also been stuck on this and think it would be very helpful to have some documentation on how to build this. Third party contributions may not cover every case, and if you aren't super familiar with a certain language it may be hard for you to use language specific implementations as a reference.

**Comment by srenatus** [comment]
I'm afraid there isn't any comprehensive documentation here. [This blog post](https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4) could serve as a starting point, but from there on, you're best served by looking at the partial eval response, figure out with subset of rego you'll have to cover, and build your query translation logic accordingly. (Ideally, there's not much more than `=`, `!=` and the usual rego semantics to cover.)

When it gets too hairy, feel free to ask more questions, of course!

**Comment by srenatus** [comment]
The bot reminded me of this. I believe this can be closed, but feel free to re-open, or [post a question on the feedback forum](https://github.com/open-policy-agent/feedback/discussions), if it still troubles you.
