### ISSUE TITLE
how to use an upserted policy?

### ISSUE THREAD

**Issue by coolyrat** [open-policy-agent/opa#3678]
## Problem
I'm trying to put policies into the store on app start. And construct Rego PrepareForEval for later use. But when I tried to Eval the query, I got an Expected result. I wonder am I going on the wrong path?

I've already search through the internet and some of the testing codes, any help would be appreciated.

## Expected Behavior
Eval and get the following result.
`{
    "hello": true
}`
## Actual Behavior
Result return nil instead.

## Steps to Reproduce the Problem

```go
var exampleRule = `package play

default hello = false

hello {
    m := "world"
    m == "world"
}
`

func main() {
	ctx := context.Background()
	store := inmem.New()

	txn := storage.NewTransactionOrDie(ctx, store, storage.WriteParams)

	if err := store.UpsertPolicy(ctx, txn, "play.rego", []byte(exampleRule)); err != nil {
		fmt.Println(err)
		return
	}

	if err := store.Commit(ctx, txn); err != nil {
		fmt.Println(err)
		return
	}

	r := rego.New(
		rego.Store(store),
		rego.Query("data.play.hello"),
	)
	q, err := r.PrepareForEval(ctx)
	if err != nil {
		fmt.Println(err)
		return
	}

	rs, err := q.Eval(ctx)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(rs)

}
```

**Comment by srenatus** [comment]
Hello!

First off, are using `store.UpsertPolicy` for a reason (such as updating the store and its policies later)?

Since if you want to use `r.PrepareForEqual` and `q.Eval` to evaluate a policy _only_, you could pass [`rego.Module("play.rego", exampleRule)`](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.30.2/rego#Module) to your `rego.New()` call, and it'll be a lot simpler.

**Comment by coolyrat** [comment]
Hello~

> First off, are using store.UpsertPolicy for a reason (such as updating the store and its policies later)?

My first thought of using a store is to dynamically update the policy. In my case above is the `exampleRule`. 

> Since if you want to use r.PrepareForEqual and q.Eval to evaluate a policy only, you could pass rego.Module("play.rego", exampleRule) to your rego.New() call, and it'll be a lot simpler.

Definitely! But I was thinking if I have the store pass into the `rego.New()`,  does that mean I could update the policy in the store to make changes to the evaluation? 

Or is that when the policy is changed, I should replace the rego object with the `rego.New()`?  I wonder what is the use case of `store.UpsertPolicy`.

**Comment by srenatus** [comment]
I've had a look at what the server does when a policy is uploaded via the `v1/policies` API: It calls `UpsertPolicy(ctx, txn, "some/policy", buf)`, where `some/policy` corresponds to the request path, I had used a `PUT /v1/policies/some/policy` request. As far as the virtual docs (accessible via `v1/data`) is concerned, that path doesn't matter much, what matters is the ` package xyz` in the policy uploaded.

But regarding your question, 
> My first thought of using a store is to dynamically update the policy. In my case above is the exampleRule.

I believe this won't work. `PrepareForEval` does as much as it can do (short of partial evaluation), and thus reads in and prepares all the modules in the store at the time it's called:

https://github.com/open-policy-agent/opa/blob/3ec75dc61a098be3fc0606137125b413397e1619/rego/rego.go#L1579-L1582

-------

How to proceed? I think you could either pass the module via `rego.Module` as mentioned above, or use a store and dynamically update the policy, **but** not re-using the `rego.PrepareEvalQuery` state. Instead, you'd call [`Eval`](https://github.com/open-policy-agent/opa/blob/3ec75dc61a098be3fc0606137125b413397e1619/rego/rego.go#L1128)
 right away.

What's better will depend on how often your policies are updated, I suppose. You could also keep the PrepareEvalQuery state, and update it whenever a policy is updated. I suppose some benchmarks on your concrete situation would help 🤔

**Comment by coolyrat** [comment]
> How to proceed? I think you could either pass the module via rego.Module as mentioned above, or use a store and dynamically update the policy, but not re-using the rego.PrepareEvalQuery state. Instead, you'd call Eval
right away.

Yes, right now I'm passing `rego.Module('neveruse', 'package nerveruse')` into `rego.New`. And it works as expected. But I'm not sure this is the right way.

https://github.com/open-policy-agent/opa/blob/3ec75dc61a098be3fc0606137125b413397e1619/rego/rego.go#L1604-L1608

**Comment by srenatus** [comment]
> My first thought sees PrepareXXX is like SQL's prepareStatement, I should reuse them when they stay the same.

I think that's not a bad way to think of it -- it's just that the "statement" equivalent here are the policies _and_ the query. If either one changes, the PrepareEvalQuery state needs to be reconstructed.

**Comment by coolyrat** [comment]
> If either one changes, the PrepareEvalQuery state needs to be reconstructed.

Absolutely, so passing a no-use module is good to go? Although this looks a bit confusing.

**Comment by srenatus** [comment]
Oh, I'm not actually sure if that's needed. Can't you roll with `r.modules` unset? Can you share your current approach's code? I guess I've kind of lost track 😅

**Comment by coolyrat** [comment]
> Can't you roll with r.modules unset?

No. Unset `r.modules` won't be able to get a policy from the store. Refer to the link below.

https://github.com/open-policy-agent/opa/blob/3ec75dc61a098be3fc0606137125b413397e1619/rego/rego.go#L1604-L1619

Please have a look into the gist. 
![image](https://user-images.githubusercontent.com/1881159/127120662-31453bd6-0af5-46e3-ad27-24fe6d82a477.png)

https://gist.github.com/coolyrat/3842bc08f00e77c4c1db3af267629fe9

**Comment by srenatus** [comment]
💡 Now I get it. 🤦 Thanks. Yeah looks like a decent workaround.

That said, how about passing `rego.Module()` to your `PrepareForEval` call? As far as I can see, you'll have to update that PrepareEvalQuery state anyways, so you could just ignore the store completely. (Unless you'd like to use data, of course.)

**Comment by coolyrat** [comment]
I have to keep the store for data, of course~

> That said, how about passing rego.Module() to your PrepareForEval call?

I don't get the idea, how to do that? I've updated the gist. Seems like I have to `rego.New` every time I update a policy.



https://gist.github.com/coolyrat/3842bc08f00e77c4c1db3af267629fe9

**Comment by srenatus** [comment]
> Seems like I have to rego.New every time I update a policy.

Sorry I wasn't clear -- by updating the `PrepareEvalQuery` state, I meant re-executing these steps:

https://gist.github.com/coolyrat/3842bc08f00e77c4c1db3af267629fe9#file-opa-go-L48-L57

...and since you've got to do that anyways, you might as well use `rego.Module()` directly for updating the rego policies used for the evaluation. What's better depends on the usage pattern, I guess. 🤔

**Comment by coolyrat** [comment]
If that's the fact, for now, I might just do `rego.New` every time. If the benchmark tells there are performance issues, I might try the store trigger approach, `rego.New` when the policy changed.

**Comment by srenatus** [comment]
Sounds about right. What kind of app are you building? If you don't mind me being curious. 😄

**Comment by coolyrat** [comment]
We are building a user account center. Trying to use OPA as the underlying model, calculating the user permissions.

**Comment by srenatus** [comment]
Oh cool, thanks for sharing. Please don't hesitate with opening issues, or reaching out on slack!

**Comment by coolyrat** [comment]
sure, thank you very much!
