### ISSUE TITLE
ast.Array should cache groundness bit to avoid unnecessary computation

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3679]
The ast.Array structure does not memoize groundness. As a result, checks for groundness have to recompute for all elements which can be expensive for large arrays.

Related: 00be8a27cb189f4a732ddbd51546088e2a348493

**Comment by srenatus** [comment]
This is a little hairier with arrays compared to sets: when slicing an array, the elements are still shared. So
1. the slice could have a different groundness than the original
2. changes to the slice could change the original's groundness

Still worth improving, of course. 👍

**Comment by srenatus** [comment]
Looking further into this, the `evalTerm`'s `get/next/enumerate` code path isn't the same for array as it is for sets and objects,
https://github.com/open-policy-agent/opa/blob/8fc2ba17a1f4e654d970736e81513894e71bd4f2/topdown/eval.go#L2709-L2731

we'll get a Number term for the index here, and feed that into `get`,
https://github.com/open-policy-agent/opa/blob/8fc2ba17a1f4e654d970736e81513894e71bd4f2/topdown/eval.go#L2777-L2782

without any checks for groundness.
