### ISSUE TITLE
Create a Feedback repository and enable GitHub Discussions

### ISSUE THREAD

**Issue by peteroneilljr** [open-policy-agent/opa#3685]
[GitHub Discussions](https://docs.github.com/en/discussions) is a tool where community members can ask and answer questions, share updates, have open-ended conversations. 

Enabling GitHub discussions for the OPA community creates the following benefits:
1. Centralized place for community discussions around OPA 
2. GitHub issues can be focused on code development and bugs 
3. Members have a place to ask questions and share information

Recommended actions to enable GitHub Discussions.
1. Create a new repository under `open-policy-agent` called `feedback`
2. Create a new "feedback-maintainers" team. Any existing organization member interested in joining the team can be added.
	2A. Suggested members: @peteroneilljr , @tsandall , @maxsmythe , @shomron , @jpreese, @sozercan 
3. Enable Discussions for the feedback repository  

GitHub Discussions Examples
[Linkerd](https://github.com/linkerd/linkerd2/discussions)
[Homebrew](https://github.com/Homebrew/discussions/discussions)

Per our governance policy, adding a new repo requires a 2/3 approval vote from all organizations.

**Comment by tsandall** [comment]
@maxsmythe @shomron @sozercan - we'd like to create a new repo in the org that we can enable the GitHub Discussions feature on. Are you folks okay with this addition?

**Comment by maxsmythe** [comment]
Absolutely, though it looks like discussions are already available in the Gatekeeper repo? I know I've gotten a few there.

**Comment by sozercan** [comment]
Sounds good to me. Like @maxsmythe said, we had GitHub discussions enabled for Gatekeeper for some time. Would it make sense to have it enabled for individual repos so they can be specific to the project and easier to find for users?

**Comment by peteroneilljr** [comment]
Hi @maxsmythe and @sozercan, enabling Discussions in multiple repos might make it easier for a knowledgable community member to find the answer they're looking for in a specific project, but I feel this leaves out a large number of new members and casual browsers that haven't built up that knowledge yet. Searching for answers in a centralized repository should make it generally easier for the overall community.

From a community management perspective this creates a clear path to direct people from Slack into GitHub Discussions. Inside of Discussions we can have top level categories like Gatekeeper and Conftest, that will make it easy to move questions into. Then we can get very specific with labels like point release versions and attaching to specific feature requests. 

Lastly, having these discussions in a centralized location will increase awareness for the different areas of the OPA project, and as new OPA sub-groups emerge it should create opportunities for the groups to work together. 

Super happy to dive into this deeper. But if everyone is onboard, the next steps should be to create a feedback repository and migrate any discussions from the Gatekeeper and OPA repositories into the feedback repo.

**Comment by ritazh** [comment]
I can definitely see the benefit of having a centralized discussion forum to help new users to discover projects, features, and discuss integrations between projects. As a maintainer, this seems like yet another place I have to check for questions and discussions. It would be great if this centralized discussion forum can notify me when discussions relevant to my project need my attention (much like github issues) and be able to filter using tags. When a new discussion item is created, who will be doing the initial triaging to make sure the relevant projects and maintainers are tagged?

**Comment by peteroneilljr** [comment]
Hi @ritazh thank for the comment and I totally understand your concern. Currently, between Slack and GitHub there are a handful of places community members can ask a question or strike up a conversation, each of these places is somewhat interchangeable and receive various degrees of attention from the community and maintainers. This process seems like it has been frustrating for all parties involved. I am looking to consolidate the various channels to simply the process. 

Starting with Slack I want to remove all nonessential channels. The goal here is to make it very clear where community members should go. What this is going to look like is; 3 primary channels for new members, announcements, help and chit-chat. Then the topic specific channels for everything else, conftest, gatekeeper, envoy, etc. 

After Slack has this organization structure, the next step will be to start encouraging community members to ask questions in GitHub Discussions. Retraining habits into a community can be hard, which is why I'm hoping to have a centralized repository to make this transition as easy as possible. Once people are aware of the Discussions board, making sure the categories match the available Slack channels will hopefully make it crystal clear where to go.

While this process to retrain community behavior may take sometime, I feel that we will end up in a much better place. The maintainers for each project should ultimately have a GitHub discussions to check for questions, and a Slack channel for general communication.

As for notifications, I recognize that the built-in options for GitHub Discussions are not great (hopefully it improves when it's out of beta). During the transition, I will have my eyes on Discussion board frequently and will be making sure conversations get sorted into the right categories. 

My suggestion would be for people to watch the entire Discussion board, as it seems unlikely that volume of questions will suddenly increase. However, this is asynchronous forum, so if the maintainers check their relevant categories every few days or so, that should be sufficient coverage. 

I hope this break down gives a clearer picture of the direction we are hoping to go in and how it should organize things in a way that will be easier for everyone. I'm also happy to hop on a call and discuss this in-depth if you have any questions or concerns.

**Comment by tsandall** [comment]
@peteroneilljr can we close this out now that the feedback repo has been created?

**Comment by peteroneilljr** [comment]
I'm good to close this issue as it was just for opening the repository, but just going to note here what is still in progress: 

- Linking between Slack and Discussions
- Create labels in the Feedback repository
- Scanning other repositories for Discussions and moving them over
- Creating templates for members to follow to open discussions
- Pinned post for "Getting Started with OPA Discussions"
- Announcement that Discussions is open
