### ISSUE TITLE
opa envoy - http.send errors out with too many open files under load

### ISSUE THREAD

**Issue by TheHydGuy** [open-policy-agent/opa#3688]
## Expected Behavior
http.send should be working fine under load 

## Actual Behavior
After processing 1000 requests in a given minute, it fails with too many open file descriptor error and resumes after that part particular minute

## Steps to Reproduce the Problem

* OPA version: openpolicyagent/opa:0.31.0-envoy
* Example query, input, data, and policy that OPA was given: 
`policy_response := http_response {
    http_response := http.send({
        "method" : "POST",
        "url": opa.runtime()["env"]["URL"],
        "headers": {
        	"authorization": token
        },
        "raise_error": false,
        "timeout": "3s",
    })
}`
* Example output that OPA returned
`{"code":"eval_http_send_network_error","message":"Post \"{url}\": dial tcp: lookup {hostname} on x.x.x.x:53: dial udp x.x.x.x:53: socket: too many open files","status_code":0,"x-request-id":"b643f986-44ca-44c4-95a6-fc4cbe1f5639"}}`

I believe the http.send is creating a new HTTP client on every single request that is causing the problem. Are there any alternatives to overcome this issue.
Thank you in advance!

**Comment by ashutosh-narkar** [comment]
Related to #2418.

**Comment by ashutosh-narkar** [comment]
@TheHydGuy can we close this in favor of #2418 ?

**Comment by TheHydGuy** [comment]
@ashutosh-narkar  - closed the issue. Thanks again for the prompt response.
