### ISSUE TITLE
DOCS: Syntax diagram for grammar

### ISSUE THREAD

**Issue by greggirwin** [open-policy-agent/opa#3690]
%docs/content/policy-reference.md has a semi-formal EBNF-ish grammar. ;^) Since it's not correct EBNF a colleague adapted it so we could render a syntax diagram for it. We can re-render using your actual grammar if you make it EBNF (or ABNF) compliant. Attached are the diagram and the grammar we used to render it.

It was done very quickly, so we're not 100% sure of our accuracy in understanding your grammar variant. e.g. `raw-string`'s use of `CHAR-` seems to imply `not`, but there may be other things we misinterpreted.

![rego](https://user-images.githubusercontent.com/460079/127554078-a59beaa7-cb9b-44e9-ba47-839acc332e23.png)
[rego.rule.txt](https://github.com/open-policy-agent/opa/files/6903167/rego.rule.txt)

If this is useful, feel free to include it in your docs. I'm happy to make changes as well.

**Comment by srenatus** [comment]
Heh, intriguing. 😃 Thanks for sharing this.

I'd say a _proper_ formal grammar would be a great addition to either the docs here, or the [contrib](https://github.com/open-policy-agent/contrib) repo. (Haven't had a close look at the one you've shared yet, sorry.)

We _used to_ use [pigeon](https://pkg.go.dev/github.com/mna/pigeon) for parsing, and we had a  PEG grammar for it in the repo. That had the advantage of ensuring that the grammar is never out-of-date. Nowadays, we've got a hand-rolled parser, for better error messages, and better performance (https://github.com/open-policy-agent/opa/pull/2219).

Now, you've also gotten me quite curious what you and your (redlake?) colleague are doing with the Rego grammar. 😄

**Comment by greggirwin** [comment]
Conftest is what brought me in. In designing the config library for Red, I want to consider verification, constraints, and also ties to a capability security model. I also plan to tinker up an HCL parser, to get more familiar with IaaC (IaaD) tooling out there. While Red _is_ a programming language, it's a data format first and foremost. Anyway, I saw your grammar and then we had to play. :^)

The grammar I posted is in Red's `parse` dialect, which offers us the same benefit as `pigeon` did for you. The diagram was rendered with a commercial tool we built that supports that grammar, as well as ABNF, EBNF, BNF, McKeeman, YACC, and (experimentally) regex. The tool (DiaGrammar) also supports input testing, so if you have test files I can try them out there. You're free to try the tool yourself of course. We also give licenses to FOSS projects that can benefit.

I needed to add the JSON* rules, and a quick whitespace rule (your grammar doesn't account for that, so I just added it for the package rule to test), but with those in place this grammar can parse the example in the `conftest` readme. Looking quickly, other examples seem to be in YAML rather than rego.

[rego.rule.txt](https://github.com/open-policy-agent/opa/files/6908954/rego.rule.txt)

**Comment by greggirwin** [comment]
Ah, I can pull examples from the playground if nothing else.

**Comment by srenatus** [comment]
Yeah. There are also a few test cases here, https://github.com/open-policy-agent/opa/tree/main/test/cases/testdata, that should cover most of the grammar in one way or another.

**Comment by anderseknert** [comment]
@greggirwin you might find this useful https://github.com/open-policy-agent/opa-idea-plugin/blob/master/src/main/grammar/Rego.bnf

**Comment by greggirwin** [comment]
Thanks @srenatus ! Looks like I'd need to extract `modules:` from each of the YAML files to get straight %.rego content for testing, yes?

@anderseknert thanks for that, though the grammar there isn't valid BNF or EBNF either. I think it's the same as from the docs.

**Comment by srenatus** [comment]
Correct, multiline yaml strings. Twice the fun. ;)

**Comment by anderseknert** [comment]
@greggirwin not the same as the one in the docs. The IntelliJ IDEA plugin uses this to generate its Rego parser. Whether the BNF is pristine or not, it seems to work well for the intended purpose :) @vgramer might know more about the details on that specific format.

Either way, I think a diagram would be a nice addition to the grammar section.

**Comment by greggirwin** [comment]
As if YAML isn't enough fun to begin with. Hack time. :^)

@anderseknert, this is the issue with sooooo many tools. They use slight variants of known grammars. Even the huge OData projects added case sensitive switches to ABNF. Of course, any grammar is better than no grammar, and we hope to support people and make them more popular. Clearly we also think diagrams have value.

**Comment by srenatus** [comment]
I'm not personally a huge fan of diagrams -- but having more parsers for Rego lowers the bar for implementing further tooling, and that's something I'm very much interested in 😄

**Comment by greggirwin** [comment]
Is it the diagrams themselves you don't like, or the pain of creating and maintaining them? If it's the diagrams themselves, what is it you don't like about them?

**Comment by srenatus** [comment]
First of all, this is just my opinion and not in any way binding for this discussion 😎 

> Is it the diagrams themselves you don't like, or the pain of creating and maintaining them?

If there's a good formalism, I tend to not look at the visual representation. That said, visuals generated programmatically are the best, and much much preferable over hand-crafted diagrams... what's important then is that the tooling used is readily available (and at best, automatically invoked when the sources change...)

The diagrams you've shared themselves look nice! 😃 What I can't answer myself is the significance of the colours. What's special about `set`? 🤔

**Comment by greggirwin** [comment]
Thanks for the extra info. I asked because we're trying to learn and get more feedback. So far, the main reason people push back is a) They think it will be too much work to maintain (even though it has value), and b) they still use YACC or Bison and think those should be enough for anybody. I exaggerate to make jokes. :^) The positive feedback we've gotten is that people didn't realize how the diagrams work as a meta-description, which crosses more boundaries. It's a common notation. Once you know how to read the diagrams, which is not too difficult, even for non-deep devs and others, because there's a real world analogy. 

Our tool has a CLI interface, for the very reason you mention. 

We can change colors at will. `Set` shows up (and I didn't bother to change it) because it's a keyword in Red's `parse` dialect, because we ported to that in the essence of time. Here you'll see a few more show up. 
![rego](https://user-images.githubusercontent.com/460079/127747061-46e9ec0e-d597-486d-87a8-1dd0e203af27.png)

Here it is in a plain style:
![rego-plain](https://user-images.githubusercontent.com/460079/127747154-e96ab988-e166-4ac4-a947-8ecce9aad992.png)

**Comment by greggirwin** [comment]
![rego-plain](https://user-images.githubusercontent.com/460079/127747292-61ce7548-5cb2-4d75-b96f-12174d85ec67.png)
Truly plain this time.

**Comment by greggirwin** [comment]
Any further thoughts on this? I'm happy to render the diagram with colors you prefer, and clean up the diagram that goes with it, but have some other things in the queue as well, so would like to wrap this up while it's fresh.

**Comment by srenatus** [comment]
Sorry for dropping the ball here. I'm not sure I've understood how those diagrams can be regenerated. Being able to do that would be quite important from my perspective. 🤔

**Comment by greggirwin** [comment]
With our tool. I can do it as needed, you can use the free version which watermarks the image (forced attribution :^), and I can put one of you on the list for a FOSS license so you can handle it all (and no watermark).

**Comment by greggirwin** [comment]
Our tool currently targets Windows. We have to decide if GTK and Mac are worth the time and effort, but that would be next year.

**Comment by srenatus** [comment]
Thanks for the details and thanks for bearing with my style requests above. I think I'd like to let someone else chime in, but my preference would be to _pass_ on this for now. Since we cannot have a simple make target to regenerate the file, it'll potentially be something that grows stale when the grammar changes... 🤔

**Comment by greggirwin** [comment]
OK. Diagrams are documentation, and suffer the same issue as all other documentation.
