### ISSUE TITLE
OPA Envoy docker - Create log file

### ISSUE THREAD

**Issue by TheHydGuy** [open-policy-agent/opa#3694]
I'm trying to deploy the OPA Envoy that runs along side of my application for external Authorization. I'm having difficulty to understand how the logging can be configured to write to a log file.
## Expected Behavior
Option to configure opa envoy to write logs to file.
`FROM openpolicyagent/opa:0.31.0-envoy`

**Comment by srenatus** [comment]
Usually, you'd have some service management component take care of capturing the logs, and writing them to a file, or some other data store. Like, kubernetes, docker, systemd, runit or whatever floats your boat.

OPA itself (and the same holds for opa-envoy-plugin) doesn't know how to write logs to a file.

What is your deployment scenario? How come you'd prefer OPA to manage the log files?

**Comment by srenatus** [comment]
If you're interested in decision logs, see also https://github.com/open-policy-agent/opa/issues/2605.

**Comment by TheHydGuy** [comment]
> Usually, you'd have some service management component take care of capturing the logs, and writing them to a file, or some other data store. Like, kubernetes, docker, systemd, runit or whatever floats your boat.
> 
> OPA itself (and the same holds for opa-envoy-plugin) doesn't know how to write logs to a file.
> 
> What is your deployment scenario? How come you'd prefer OPA to manage the log files?

I'm running a docker container, can you please point me how I can redirect the console logs to logfile may be.

**Comment by srenatus** [comment]
Please refer to the docker docs and stuff... googling turned up this, https://earthly.dev/blog/understanding-docker-logging-and-log-files/, looks like a decent intro 🤔

**Comment by srenatus** [comment]
I don't know of more to do here -- please re-open if this keeps bugging you and you think it's something that should be fixed in OPA. 😃
