### ISSUE TITLE
opa-wasm compile error

### ISSUE THREAD

**Issue by lambneo** [open-policy-agent/opa#3707]
### Describe the bug
A compile bug related with `opa.OPA` struct initialization.

### A clear and concise description of what the bug is
I tried to use this SDK to realize a simple policy center but to find a very strange compile error:
```
/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64/link: 
running clang failed: exit status 1 Undefined symbols for architecture x86_64: 
 "_wasi_config_arg", referenced from:
      __cgo_cbbfd67d0eb3_Cfunc_wasi_config_arg in 000042.o
     (maybe you meant: __cgo_cbbfd67d0eb3_Cfunc_wasi_config_arg)
  "_wasi_config_capture_stderr", referenced from:
      __cgo_cbbfd67d0eb3_Cfunc_wasi_config_capture_stderr in 000042.o
     (maybe you meant: __cgo_cbbfd67d0eb3_Cfunc_wasi_config_capture_stderr)
  ... errors like the above...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
After debug I found this error is related with the reference of `opa.OPA` in different packages. However, **I failed to reproduce** this error in a new project.
### Steps to reproduce
The followings are probably the codes that trigger the error.
I wrote the `policycenter.go` to realize a rules:
```
package policycenter

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/open-policy-agent/golang-opa-wasm/opa"
)

type PolicyCenter interface {
	Eval(entity *PolicyEntity, rego *opa.OPA) (*Result, error)
}

type Result struct {
	Result interface{}
}

type PolicyEntity struct {
	ctx        context.Context
	PolicyName string
	InputQuery interface{}
}

func NewPolicyEntity(ctx context.Context, policyName string, inputQuery interface{}) *PolicyEntity {
	return &PolicyEntity{
		ctx:        ctx,
		PolicyName: policyName,
		InputQuery: inputQuery,
	}
}

func Eval(entity *PolicyEntity, rego *opa.OPA) (*Result, error) {
	result, err := rego.Eval(entity.ctx, &entity.InputQuery)
	if err != nil {
		return nil, err
	}
	return &Result{result.Result}, nil
}
```
Then I wrote a main function in different packages and execute to check if it works:
```
package main

import (
	"goplayground/pkg/policycenter"
	"context"
	"fmt"
	"github.com/open-policy-agent/golang-opa-wasm/opa"
	"io/ioutil"
)

func main()  {
	input := map[string]interface{}{"Field1": "false", "Field2": "true"}
	wasmBytes, err := ioutil.ReadFile("policy.wasm")

	if err != nil {
		fmt.Printf("error: %v", err)
		return
	}

	rego, err := opa.New().WithPolicyBytes(wasmBytes).Init()

	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	defer rego.Close()

	ctx := context.Background()
	entity := policycenter.NewPolicyEntity(
		ctx, "PA", input)
	result, _ := policycenter.Eval(entity, rego)
	res := result.Result.([]interface{})[0].(map[string]interface{})["result"].(string)
	fmt.Println(res)
}
```
Then the error occuered:
<img width="1009" alt="截屏2021-08-04 上午11 12 56" src="https://user-images.githubusercontent.com/37793830/128280674-e995803a-2dab-4a39-ae43-323ea7535baf.png">
I found out that I cannot declare `*opa.OPA` and `policycenter.go` at the same time in the main function I wrote above, if I only init `opa.OPA` or something in `policycenter.go`, the error won't occur.
Here is the example error occurring:
```
func main()  {
	wasmBytes, _ := ioutil.ReadFile("policy.wasm")
	rego, _ := opa.New().WithPolicyBytes(wasmBytes).Init()
	defer rego.Close()
}

func launchEval(rego *opa.OPA, entity *policycenter.PolicyEntity) {
	result, err := policycenter.Eval(entity, rego)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}
	res := result.Result.([]interface{})[0].(map[string]interface{})["result"].(string)
	
	fmt.Println(res)
}
```
If I delete anything related with `policycenter`, the error will disappear.
### Additional context
I wrote a `policycenter_test.go` in the same package of `policycenter.go` and it works well, it seems this compile error is related with opa.OPA reference and declaration in different packages. Here is the code:
```
package policycenter

import (
	"context"
	"fmt"
	"github.com/open-policy-agent/golang-opa-wasm/opa"
	"io/ioutil"
	"reflect"
	"sync"
	"testing"
)
var(
	cases = []interface{}{map[string]interface{}{"Fields1": "false", "Fields2": "true"},
		map[string]interface{}{"Fields1": "true", "Fields2": "true"},
		map[string]interface{}{"Fields1": "false", "Fields2": "false"},
	}
	ctx = context.Background()
	entity0 = NewPolicyEntity(ctx, "Policy", cases[0])
	entity1 = NewPolicyEntity(ctx, "Policy, cases[1])
	entity2 = NewPolicyEntity(ctx, "Policy", cases[2])
        input = []*PolicyEntity{entity0, entity1, entity2}
)



func TestEval(t *testing.T)  {
	var 
	wasmBytes, err := ioutil.ReadFile("../../policy.wasm")
	if err != nil {
		fmt.Printf("error: %v", err)
		return
	}

	rego, err := opa.New().WithPolicyBytes(wasmBytes).Init()

	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}

	defer rego.Close()
	var wg sync.WaitGroup

	wg.Add(100)
	for i := 0; i < 100; i++ {
		go func() {
			t := i % 3
			launchEval(t, rego, input[t])
			wg.Done()
		}()
	}
	wg.Wait()

}

func launchEval(flag int, rego *opa.OPA, entity *PolicyEntity) {
	result, err := Eval(entity, rego)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		return
	}
	res := result.Result.([]interface{})[0].(map[string]interface{})["result"].(string)
	switch flag {
	case 0:
		if res != "1P" {
			fmt.Println("failure occurs, expected 1P while get" + res)
		}
	case 1:
		if res != "2P" {
			fmt.Println("failure occurs, expected 2P while get" + res)
		}
	case 2:
		if res != "3P" {
			fmt.Println("failure occurs, expected 3P while get" + res)
		}
	}
}
```
and the test passed:
<img width="354" alt="截屏2021-08-05 上午10 25 54" src="https://user-images.githubusercontent.com/37793830/128281198-47eabbdd-3dde-4cea-963d-7162cbe6d437.png">
this complie error confuses me a lot, why this error occurs?

**Comment by srenatus** [comment]
😬 I'm afraid we've done a poor job with messaging that the sdk was moved to an internal package, and is developed there.

So, right now, what I'd expect to work is the code in https://github.com/open-policy-agent/opa/tree/main/internal/wasm. (It's diverged from golang-opa-wasm quite a bit, too.)

That said, depending on what you want to do, the `rego` interface should be a more convenient API for using OPA's wasm -- if passing target = wasm, it'll be built into a wasm module, and evaluated using the internal wasmtime-based sdk:

```go
	mod := `
	package test
	default p = false
	p {
		input.x == 1
	}
	`


	r, err := rego.New(
		rego.Query("data.test.p = x"),
		rego.Target("wasm"),
		rego.Module("a.rego", mod),
	)
	// if err != nil ... 

	// r.Eval(), r.PrepareForEval() etc
```

Would this be an OK alternative for you?

**Comment by lambneo** [comment]
> 😬 I'm afraid we've done a poor job with messaging that the sdk was moved to an internal package, and is developed there.
> 
> So, right now, what I'd expect to work is the code in https://github.com/open-policy-agent/opa/tree/main/internal/wasm. (It's diverged from golang-opa-wasm quite a bit, too.)
> 
> That said, depending on what you want to do, the `rego` interface should be a more convenient API for using OPA's wasm -- if passing target = wasm, it'll be built into a wasm module, and evaluated using the internal wasmtime-based sdk:
> 
> ```go
> 	mod := `
> 	package test
> 	default p = false
> 	p {
> 		input.x == 1
> 	}
> 	`
> 
> 
> 	r, err := rego.New(
> 		rego.Query("data.test.p = x"),
> 		rego.Target("wasm"),
> 		rego.Module("a.rego", mod),
> 	)
> 	// if err != nil ... 
> 
> 	// r.Eval(), r.PrepareForEval() etc
> ```
> 
> Would this be an OK alternative for you?

OK, thanks for your advice. I just scanned the new repo and  I found the concurrent mode is still the same with the old one(pool <- vms), so I wonder if it is convenient to directly use struct `OPA` to finish the evaluation, I do prefer this way.

**Comment by srenatus** [comment]
So you'd like to not use the built-in pooling? I don't think there's a convenient way to do that.

Could you give me a more complete picture what you're trying to do, and how the pooling is an issue there? Maybe there's a good middle ground somewhere. 🤔

**Comment by lambneo** [comment]
Thanks Srenatus! Well, I get three reasons for that:

1. Actually I want to implement OPA in my Java project (not integrated with framework like Spring ), but OPA hasn't supported Java integration yet. 
2. The policy I define is not complicated and no advanced features of OPA get involved. It is much easier for me to use wasmer-java to implement a simple opa-java sdk rather than making many complicated things I don't need for now.
3. I don't consider the OPA-http integration.

**Comment by srenatus** [comment]
Oh sorry I must have misunderstood you earlier. To generate Wasm modules from your Rego policies, you don't need the golang-opa-wasm sdk; it'll work out of the box with `opa`, `opa build -t wasm`, and the wasm file will be in that bundle. You can use that file with any Wasm engine available to your host language.

**Comment by srenatus** [comment]
It's explained here, https://www.openpolicyagent.org/docs/latest/wasm/#compiling-policies -- please let us know if you get stuck.

**Comment by lambneo** [comment]
> It's explained here, https://www.openpolicyagent.org/docs/latest/wasm/#compiling-policies -- please let us know if you get stuck.

Hahaha, I reached this step long time ago, so back to the beginning, it is the compile error while I execute the `main.go` in the examples I gave that confuses me.
To fully illustrate the problem, the `policy.wasm` in my case is built from this simple rego file:
```
package policy

allow = "1P" {
   input.Field1 = "true"
} esle = "2P" {
   input.Field2 = "false"
} else = "3P"
```
`data.policy.allow` is the default entrypoint I set while compiling. 
Could you help me to fix this strange compile error? I will be very grateful!

**Comment by srenatus** [comment]
> data.policy.allow is the default entrypoint I set while compiling.

What's your call arguments there? Just double checking...

**Comment by lambneo** [comment]
> > data.policy.allow is the default entrypoint I set while compiling.
> 
> What's your call arguments there? Just double checking...

For rego it should be `allow`, the logic of my case is correct because the results of test codes I left in `Additional context` are correct, the problem is realted with the reference of `opa.OPA` in different packages.

**Comment by srenatus** [comment]
It looks like you're having issues compiling the cgo portions of golang-opa-wasm. I doubt that this has much to do with the duplicate definitions, those errors would look differently.

As mentioned above the golang-opa-wasm package has bitrot a bit. I'd try to copy some sources from the internal package, or look around if people had similar issues using wasmer-go.

**Comment by lambneo** [comment]
> It looks like you're having issues compiling the cgo portions of golang-opa-wasm. I doubt that this has much to do with the duplicate definitions, those errors would look differently.
> 
> As mentioned above the golang-opa-wasm package has bitrot a bit. I'd try to copy some sources from the internal package, or look around if people had similar issues using wasmer-go.

Thank you so much srenatus! Looking forward to your response!

**Comment by srenatus** [comment]
Sorry this was meant as a hint what to do 😅 
But I'll try to play with this a bit tomorrow anyways.

**Comment by lambneo** [comment]
> 😬 I'm afraid we've done a poor job with messaging that the sdk was moved to an internal package, and is developed there.
> 
> So, right now, what I'd expect to work is the code in https://github.com/open-policy-agent/opa/tree/main/internal/wasm. (It's diverged from golang-opa-wasm quite a bit, too.)
> 
> That said, depending on what you want to do, the `rego` interface should be a more convenient API for using OPA's wasm -- if passing target = wasm, it'll be built into a wasm module, and evaluated using the internal wasmtime-based sdk:
> 
> ```go
> 	mod := `
> 	package test
> 	default p = false
> 	p {
> 		input.x == 1
> 	}
> 	`
> 
> 
> 	r, err := rego.New(
> 		rego.Query("data.test.p = x"),
> 		rego.Target("wasm"),
> 		rego.Module("a.rego", mod),
> 	)
> 	// if err != nil ... 
> 
> 	// r.Eval(), r.PrepareForEval() etc
> ```
> 
> Would this be an OK alternative for you?

Hello srenatus, I tried the methods you gave but to find interesting part in https://github.com/open-policy-agent/opa/blob/main/rego/rego.go line 1476 - 1481:
```
if r.target == targetWasm {

		if r.hasWasmModule() {
			_ = txnClose(ctx, err) // Ignore error
			return PreparedEvalQuery{}, fmt.Errorf("wasm target not supported")
		}
                ...
}
```
it seems that rego don't support wasm target for now😅

**Comment by srenatus** [comment]
Nope that works. You'll exercise the same code path from the command line, like `opa eval -t wasm '1+3'`

**Comment by lambneo** [comment]
> Nope that works. You'll exercise the same code path from the command line, like `opa eval -t wasm '1+3'`

But the codes run in this logic once I get to `r.PrepareForEval()` steps, and It will run `hasWasmModule()` to check if there is a wasm files readed, if there is, returns err "wasm target not supported".

**Comment by srenatus** [comment]
Ah, I see! Sorry -- would you mind sharing that code? I think only modules passed via `rego.New(..., rego.Module(...))` are support for that code path. Parsed modules, or modules on the compiler, are not.

**Comment by lambneo** [comment]
```
policy := `
		package sample
		allow = "1"{
  		input.Field1 == "true"
		} else = "2" {
  		input.Field2 == "true"
		} else = "3"
	`
	r := rego.New(
                rego.Query("data.sample.rego.allow"),
		rego.LoadBundle("$BUNDLEPATH"),
		rego.Target("wasm"),
		rego.Module("sample.rego", policy),
	)

	ctx := context.Background()
	query, err := r.PrepareForEval(ctx)  // throws "wasm target not supported" err
```
I compiled the bundle and loaded it with the `rego.LoadBundle` because the OPA binary on my Macos can only be executed in its directory.

**Comment by srenatus** [comment]
Oh so the bundle must the the problematic thing here. Looking at the code of `r.hasWasmModule`:

https://github.com/open-policy-agent/opa/blob/b3e0fb6654279bfd0d2a72822944d989cf85a9dd/rego/rego.go#L2291-L2298

So, is your bundle a wasm bundle? (Built with `opa build -t wasm`?) If so, it shouldn't be.

Let me please clarify, there are two different workflows here, and I believe I may have contributed to mixing them up:

1. You can generate a `policy.wasm` file, and use that via some wasm SDK, in some host language. There's a few, like, for nodejs, C#, python; and the slightly bitrot one of golang-opa-wasm.
2. You can use wasm as evaluation engine through either `opa eval -t wasm`, or by passing `rego.Target("wasm")` to `rego.New()`.

These two are entirely separate. Passing a wasm bundle to `rego.New` will lead to the error you've seen.

**Comment by lambneo** [comment]
Ok got it, but it leads to another, I already set opa binary global, but run the version without loading any bundle will get errors like this:
<img width="603" alt="截屏2021-08-06 下午4 12 02" src="https://user-images.githubusercontent.com/37793830/128479048-c82290d4-a3d9-499c-b424-c5fc0267e646.png">
This error is the reason why I choose to build myself.

**Comment by srenatus** [comment]
What is your host OS? As of OPA 0.29.4, the binaries for linux/windows/macos come with wasm enabled -- could you try running with the latest releases binary for your OS, https://github.com/open-policy-agent/opa/releases/tag/v0.31.0?

**Comment by lambneo** [comment]
Macos, I downloaded the corresponding opa binary and it is already the newest:
<img width="402" alt="截屏2021-08-06 下午4 18 47" src="https://user-images.githubusercontent.com/37793830/128480065-09be36d1-b33b-4cfe-a552-4ad1a3288e70.png">

**Comment by srenatus** [comment]
OK so that binary looks OK. The build hostname is not a confidential property, it's the same for me, it's where the binary was built (some github actions' runner).

Back one step, what did you do or run that go you this error message? https://github.com/open-policy-agent/opa/issues/3707#issuecomment-894088369

**Comment by lambneo** [comment]
```
policy := `
		package sample
		allow = "1"{
  		input.Field1 == "true"
		} else = "2" {
  		input.Field2 == "true"
		} else = "3"
	`
	r := rego.New(
                rego.Query("data.sample.rego.allow"),
		rego.Target("wasm"),
		rego.Module("sample.rego", policy),
	)

	ctx := context.Background()
	query, err := r.PrepareForEval(ctx)
```
run this part

**Comment by srenatus** [comment]
OK so now we're back with option (2.) I've mentioned above (https://github.com/open-policy-agent/opa/issues/3707#issuecomment-894076632). There, the OPA binary doesn't matter at all, since the wasm module is built from the rego code.

Please try passing a build tag "-tags opa_wasm" to whatever `go` command you use to run this code.

**Comment by lambneo** [comment]
That works! I found the `OPA` used in this workflow leads to `nop.go`, that is the reason why this error occurred. Thanks srenatus!

**Comment by srenatus** [comment]
@lambneo are you unblocked? We could close this 😅

**Comment by lambneo** [comment]
Though the compile error still confuses me, it enough for this issue, thanks srenatus.
