### ISSUE TITLE
Proposal: Optionally exclude specified plugins from /health?plugins

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#3713]
We co-locate OPA with our applications and use the `/health?bundles&plugins` route in our orchestration layer to verify OPA is up and healthy before we start sending traffic to our app/OPA.  If the health route starts returning 500s, this will shutdown both our app and OPA, after the initial start period, as intended.

We also have some custom plugins that enter a `WARN` state when they become unhealthy (custom log shipping), so that we can see their status via the status plugin.  Right now, this results in the `/health` route failing, which brings down our app and OPA, which is bad for a non-critical function like log shipping (i.e., right now, if our log ingest breaks, so will all our apps).

We propose adding another optional querystring parameter to the health route, something like `/health?exclude-plugin=foo&exclude-plugin=bar`, which will be used in the health route handler to exclude those plugins from the StateOK check.

**Comment by ashutosh-narkar** [comment]
Just to understand this a bit more, you're saying that there could be some plugins whose state does not matter for OPA to be considered healthy and then there are some plugins that **have to be** in the `OK` state.

Just not including the `plugin` query param won't satisfy your use-case ?

**Comment by gshively11** [comment]
> Just not including the plugin query param won't satisfy your use-case ?

Correct.  An example of a plugin that (usually) shouldn't make the `/health` route fail are the logging plugins. In our case, if the logging plugins go into a `WARN` state because Kinesis goes down, we don't want to bring down the entire OPA process, and by association, the app that depends on it.  Whereas something like the bundle plugin failing should probably bring down the OPA process.

Another factor that I had originally considered is that there should really be two separate stage for the `/health` route (start period and ongoing), with the ability to exclude plugins from either or both, but decided to go with the simpler choice of excluding the plugin altogether.  But now that I'm thinking about it again, we may actually need the start vs ongoing behavior of `/health`.  Consider this:

When the OPA process starts up, we require the bundle plugin to be healthy to retrieve all our policy, and that has to happen before OPA should take any traffic. But, once bundles are fully loaded, a failure in the bundle plugin isn't actually a critical issue, especially if it's transient.  Our ideal behavior would be setting the plugin to a WARN state, but not failing the `/health` route. This would allow the OPA process to continue serving requests, while alerting on-calls that something is wrong.

Really, any transient error in a plugin, after the start period, shouldn't immediately cause the `/health` route to fail (maybe after a configureable period of time?)
