### ISSUE TITLE
Integration guide

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#372]
# How Do I Query OPA?

Goal: Show canonical way to integrate with OPA to query for decisions.

Content:
  - CLI (exists in Terraform example)
  - HTTP API (exists in HTTP tutorial/REST API reference)
  - Library (exists in GoDoc)

# How Do I Manage OPA?

Goal: Show how to manage OPA and what to consider. Everything except last point is covered already. Could be organized into one section.

Content:
  - Bundles
  - Status
  - Decision Logs
  - Security
  - Monitoring
  - Push vs. pull (explain tradeoffs)

# How Do I Extend OPA?

Goal: Show how to customize/extend OPA.

Content:
  - Adding custom built-in functions
  - Building shared libraries

# Misc.

- Partial evaluation. What's covered vs. what's not?

**Comment by farrukhny** [comment]
It will be great if you can add some kind of tutorial how to integrate OPA as golang lib not using opa manager as in example example-api-authz-go in case if i don't need all functionality of of opa like bundle  etc.

**Comment by tsandall** [comment]
@farrukhny take a look at the OPA GoDoc examples for the rego package. https://godoc.org/github.com/open-policy-agent/opa/rego#example-Rego-PrepareForEval
