### ISSUE TITLE
OPA output result is not complete

### ISSUE THREAD

**Issue by mvbn6789** [open-policy-agent/opa#3737]
OPA output result is not complete
https://play.openpolicyagent.org/p/uUwBFjSF8P
## Expected Behavior

Input:

{
    "message": "world"
}

Policy:

package play

default hello = false

hello {
    m := input.message
    m == "world"
}

hello2 {
    m := input.message
    m == "world"
}

hello3 {
    m := input.message
    m != "world"
}

OutPut:

{
    "hello": true,
    "hello2": true,
    "hello2": false,
}

## Actual Behavior

OutPut:

{
    "hello": true,
    "hello2": true,
}

The output not include hello3

If I change Policy and set hello3 default 

package play

default hello = false
default hello3 = false

hello {
    m := input.message
    m == "world"
}

hello2 {
    m := input.message
    m == "world"
}

hello3 {
    m := input.message
    m != "world"
}

OutPut is complete  and it  is my expect result :
{
    "hello": true,
    "hello2": true,
    "hello3": false
}

I am not sure  it is expect behavior ？

**Comment by srenatus** [comment]
> I am not sure it is expect behavior ？

Yes, it's expected: you are querying for full extent of the _package_ `play`. It consists for three _rules_ (`hello1`, `hello2`, `hello3`), and any rule that has a body that can't be satisfied will evaluate to undefined, and doesn't contribute to the full package extent, and is not displayed.

Introducing `default hello3 = false`, you say that _if `hello3` cannot be satisfied, return false_ -- and that's what you see there.

Hope this helps making sense of your observations.

**Comment by mvbn6789** [comment]
thank you for  quick reply ! I will close it
