### ISSUE TITLE
type-checking with jsonschema should not fetch remote schema refs without opt-in

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3746]
Tests have made it obvious that schemas that reference remote schemas cause network calls:

```
--- FAIL: TestSetTypesWithSchemaRef (10.03s)
    schema_test.go:53: unexpected error: compile failed: unable to compile the schema due to: Get "https://kubernetesjsonschema.dev/v1.14.0/_definitions.json": net/http: TLS handshake timeout
FAIL
```

The offending `http.Get` is [here](https://github.com/open-policy-agent/opa/blob/b02a36e25180d179f4b45ef5fe52681d40bad029/internal/gojsonschema/jsonLoader.go).

1. This should be something disabled by default, and opted into voluntarily.
2. ❓ It's a naked Get -- no context parameters, no concern for any REST auth plugins.

I'd think fixing (2.) isn't as urgent as fixing (1.), though.

**Comment by tsandall** [comment]
👍 let's get (1) solved for the next release. I'm not sure if anyone is relying on the remote schema loading feature today. @aavarghese do you know if any of your users are relying on this?

**Comment by tsandall** [comment]
@vazirim said that many of the schemas they have include remote refs but the feature is not actively used so it should be fine to disable for now.
