### ISSUE TITLE
Add support for sigv4 signing in http.go module

### ISSUE THREAD

**Issue by jicowan** [open-policy-agent/opa#3749]
## Additional Info
I'd like the OPA community to consider adding [sigv4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) signing to the topdown/http.go module. This will be particularly useful for validating signed images where you have to call an AWS service to verify the signature's authenticity (without implementing a proxy service or wrapper). A similar PR has already been implemented for fetching bundles from AWS services like S3, API GW, etc, see https://github.com/open-policy-agent/opa/blob/00a29c47f222f5260a9729899b2f787571c6b41a/plugins/rest/aws.go#L411 Can we do something similar for `http.send`?

**Comment by ashutosh-narkar** [comment]
@jicowan we should be able to re-use some of the code you've pointed out to implement this in `http.send`.

**Comment by mehrankamal** [comment]
@ashutosh-narkar I would like to work on this issue if it's not assigned to anyone yet.

Also, can I get some pointers for implementing this functionality as I am relatively new to OSS?

**Comment by ashutosh-narkar** [comment]
Sure @mehrankamal feel free to work on it! The [http.send](https://github.com/open-policy-agent/opa/blob/main/topdown/http.go) builtin has support for TLS certificate currently. I would imagine we would need a new request parameter(s) that can be used to accept the necessary credentials. Then when we [create the HTTP request](https://github.com/open-policy-agent/opa/blob/main/topdown/http.go#L264), we would include the computed signature in the HTTP `Authorization` header. The signature computation code exists in [this](https://github.com/open-policy-agent/opa/blob/main/plugins/rest/aws.go) file. Let us know if you have any questions.

**Comment by rmetcalf9** [comment]
Will this mean we can add the aws_access_key_id and aws_secret to the params and have http send sign the request as required by the aws API?

**Comment by anderseknert** [comment]
@rmetcalf9 I believe so, yes.

**Comment by alekov87** [comment]
Hey everyone, what's the status of this issue? Is anyone working on it? @mehrankamal @ashutosh-narkar 
Thank you

**Comment by anderseknert** [comment]
I don't believe anyone is working on this @alekov87 ... let me know if you want to take a shot at it :)

**Comment by alekov87** [comment]
@anderseknert I could, but I'm curious how long it would take for PR to be merged and this feature to be released in a latest version of OPA?

**Comment by anderseknert** [comment]
We try to keep a monthly release cadence, with a new release published by the end of each month… so if you’re fast this could make it into OPA v0.42.0… no stress 😄

**Comment by alekov87** [comment]
> We try to keep a monthly release cadence, with a new release published by the end of each month… so if you’re fast this could make it into OPA v0.42.0… no stress 😄

Nice! Do you know when is the cut out date for v0.42.0? 😃

**Comment by anderseknert** [comment]
We don't have fixed dates for releases, but I'd guess by the end of next week. Feel free to join the #development channel on the OPA slack if you have questions, or want to provide updates, along the way :)

**Comment by Parsifal-M** [comment]
Hey Team, is anyone working on this? If @alekov87 is not working on it, I wouldn't mind taking a look at it if you could assign to me?

Thanks!

**Comment by Parsifal-M** [comment]
Hey, am still working on this, haven't had a lot of time over the last few days but will put some time in on the weekend :)

**Comment by DonghanYang** [comment]
Hi @Parsifal-M could I get some status updates on this? We are interested in this as well.

**Comment by Parsifal-M** [comment]
Hey @DonghanYang, unfortunately I've not had much time in-between heatwaves and work to look into much more than the code as this is still new to me, I will continue to chip at it when I have time. If you would like to take a shot at implementing this I am happy with that :+1:

**Comment by ashutosh-narkar** [comment]
> we more or less need the whole function to compute the auth header https://github.com/open-policy-agent/opa/blob/main/plugins/rest/aws.go#L522 right?

Looks like. We can move the common code in an `internal` package to avoid duplication if needed.

> how would these parameters get their values?

We'll have to add new request parameter(s) to the `http.send` builtin that can be used to accept the necessary credentials.

**Comment by anderseknert** [comment]
The `http.send` function can already be configured to accept any arbitrary headers, so I guess that would be where you'd put the credentials? As for the _generated_ signature header, we could either add another config option to the `http.send` function to have this generated automatically with the outgoing request, _or_ we could add another built-in function that took the `http.send` config map in it's entirety, and returned the same map with the generated signature added as a new attribute (i..e `AWS4-HMAC-SHA256 Credential` and whatever more is needed). The benefit of that approach would be that `http.send` would have no coupling to AWS, and the signature generation could be properly namespaced, like `aws.sign_v4_request(request_object)`, or something like that 🤔

**Comment by jicowan** [comment]
@Parsifal-M On EKS you could use IAM Roles for Service Accounts (IRSA). A webhook running in the EKS cluster will add the following environment variables:
```
AWS_ROLE_ARN=arn:aws:iam::111122223333:role/iam-role-name
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
to the pod. The latest versions of the AWS SDKs know to look at these variables for credentials. 
See https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ for further details.

**Comment by jicowan** [comment]
This may help too, https://blog.jimmyray.io/kubernetes-workload-identity-with-aws-sdk-for-go-v2-927d2f258057

**Comment by Parsifal-M** [comment]
Hey, I have something put together for this, I'm still tidying it up a bit and trying to figure out a way to test it as I don't have any access to anything AWS (which I should have considered in hindsight...)

**Comment by jicowan** [comment]
@Parsifal-M AWS has a pretty generous free tier, but if you have issues getting access to an AWS account, please let me know.

**Comment by Parsifal-M** [comment]
Sorry, have been busy recently and this took a backseat. 

Will give it some more time this weekend otherwise I will drop it for now and see if anyone else is brave enough for it... :smiley:

**Comment by philipaconrad** [comment]
Proposal for a quick-and-dirty implementation:
```rego
aws.sigv4.sign_req(obj, aws_config) # Returns a signed request object for http.send().
```
Where:

 - `obj`: Is the original request config object for [`http.send`](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-http-httpsend)
 - `aws_config`: Is the Amazon-specific config information needed to sign the request. This would be an object including fields for the access/secret keys, AWS region, header ignore list, etc. Many of the fields could be optional, to allow for flexible configuration.

This would allow direct composition with http.send, and a fairly minimal, extensible implementation for the builtin itself.

I am leaning towards specifying intelligent defaults for several AWS parameters (like the default header ignore list), and plan to document these in the configuration table for the builtin's docs.

Usage example:

```rego
req := {... HTTP request configuration key/values ...}

# Fetch request signing parameters from environment variables:
signed_req := aws.sigv4.sign_req(req, {
    "aws_access_key": opa.runtime()["env"]["AWS_ACCESS_KEY_ID"],
    "aws_secret_access_key": opa.runtime()["env"]["AWS_SECRET_ACCESS_KEY_ID"],
    ...
})

check_signature {
    # Normal usage of http.send, but it will have the correctly-signed headers for AWS:
    resp := http.send(signed_req)
    # ... response-handling logic here ...
}

**Comment by ashutosh-narkar** [comment]
This approach makes sense. Have you thought about the namespace for the new builtin? Something like `providers.aws` or similar would be better I think.

**Comment by jicowan** [comment]
Not sure, but perhaps this could help? https://github.com/awslabs/aws-sigv4-proxy
