### ISSUE TITLE
Feature Request: Expose Triggers over REST API

### ISSUE THREAD

**Issue by bhoriuchi** [open-policy-agent/opa#3762]
Triggers discussed in #2899 allow manually triggering bundle updates. I would like to formally request plugin updates be exposed over the REST API so that external applications can trigger the updates

**Comment by bhoriuchi** [comment]
@anderseknert that looks good to me. 

I started this journey seeing that the tigger functionality was added so thats where I naturally started.

In thinking over my initial request I would ideally like to keep the OPA server on periodic updates and have a method (REST API endpoint) to perform an on demand pull/update of the bundles. 

My limited understanding of the trigger addition is that if you set the plugin update to manual, then periodic updates will no longer occur. Which means some external process would need to trigger them on schedule if I want to both have the updates run periodically and be able to manually trigger them.

**Comment by anderseknert** [comment]
Yeah, I believe #1336 preceeds the idea of plugin triggers, and sounds more like what you want to me. Before that though, ensure that your bundle server handles etag caching :) With that working, even quite frequent polling will be pretty inexpensive as OPA will only download a new bundle if something actually changed.

**Comment by bhoriuchi** [comment]
I was also able to achieve the functionality I need by creating a plugin that subscribes to topics (currently testing with NATS) and can trigger a specified bundle. For reference https://github.com/bhoriuchi/opa-plugin-subscribe/tree/main/subscribe

**Comment by bhoriuchi** [comment]
closing since addressed in #1336 and by other means.
