### ISSUE TITLE
Feature Request: Built-In RSA Key Parser for JWT Signing (RSA PEM to JWK)

### ISSUE THREAD

**Issue by cris-he** [open-policy-agent/opa#3765]
## Expected Behavior
I generated a pair of RSA keys that will be used for JWT signing, and in the example on the OPA docs (https://www.openpolicyagent.org/docs/v0.14.2/policy-reference/#rsa-key-rsa-signature-with-sha-256), it is asking the RSA key in the JWK format where contains the algo params (e.g. "n", "e", "d", "p", "q" etc.)

<img width="351" alt="image" src="https://user-images.githubusercontent.com/17036744/131163621-e4d027b2-7f20-428f-b92a-e42313fac131.png">

I am looking for a built-in function that can convert the RSA key into the JWK, so end users can use it in the rego file.

**Comment by cris-he** [comment]
Hi there, @srenatus and @anderseknert , I have made the changes in my local, could you please walk me thru how to create a pull request?

I made a branch locally named "#3765" but I can't push due to permission denied.

**Comment by srenatus** [comment]
Oh great! Thank you!

In short, you'll have to push your branch to a *fork* of this repo. If you fork it, you'll have full access to your fork and push it there. When you've done that, you can open a PR using github's features. See for example https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork.

**Comment by srenatus** [comment]
Also let us know if you get stuck there. Happy to help!

**Comment by cris-he** [comment]
Thanks for the information, and I have created a PR, could anyone please take a look? Thanks again.
