### ISSUE TITLE
Filename too long when creating bundle

### ISSUE THREAD

**Issue by panitaxx** [open-policy-agent/opa#3766]
When signing a bundle with `bundle.GenerateSignature` it returns a filename too long error. 

## Expected Behavior

No error

## Actual Behavior

 returns a filename too long error. 

## Steps to Reproduce the Problem

I made a small repo to show the error https://github.com/panitaxx/opatest

This happens only when using a private key that is not a filename (key in a string) 

It happens because `SigningConfig.GetPrivateKey` tries to stat the file first. A limitation on the OS does not allow file of more than 255 bytes or path of more than 4096 bytes. If the key contains '/' character stat thinks it is a path. On linux max path length is usually 4096 and that's fine for most keys but some keys do not contain the '/' so the system sees it as a single file and it  does not work because the 255 character limit applies. 

I can make a PR to fix it but there are some  considerations: 

* Detecting the filename too long error may be a way but that would probably be very OS dependent. (Have to extract syscall error see: https://stackoverflow.com/questions/53871749/how-to-check-for-file-name-too-long-error) 
* Can also be done by checking for a string suffix (.pem/.key/.crt) but a file may not have a suffix. 
* Can check if there is no "/" and the size of the string is > 255 and not stat if this is true but the 255 limit is OS-dependent.

**Comment by tsandall** [comment]
@ashutosh-narkar can you take a look at this?

**Comment by ashutosh-narkar** [comment]
Yes I'm looking into it.
