### ISSUE TITLE
hypens in keys

### ISSUE THREAD

**Issue by guyneedhamcanva** [open-policy-agent/opa#3768]
I'm unable to access JSON data where keys which contain hyphens. This is problematic as Kubernetes ephemeral storage requests are hyphenated: `ephemeral-storage`.

## Expected Behavior

JSON keys containing hyphens should be accessible.

## Actual Behavior

Where the hyphenated key `ephemeral-storage` is not surrounded by backticks, I get the error `var storage is unsafe`. When it is surrounded by backticks, the policy evaluates but the extracted data is not as expected. When I change the key to `ephemeral_storage` the policy works as expected.

## Steps to Reproduce the Problem

Playground link: https://play.openpolicyagent.org/p/betNvdkEQo

Input JSON:

```
{
    "ephemeral-storage": "128Mi"
}
```

Rego:

```
package play

default hello = false

hello {
    `input.ephemeral-storage` == "128Mi"
}
```

Output:

```
{
    "hello": false
}
```

**Comment by anderseknert** [comment]
Hi @guyneedhamcanva! You can quote the key  like:

`input["ephemeral-storage"] == "128Mi"`

**Comment by guyneedhamcanva** [comment]
Thanks a lot for the speedy reply.
