### ISSUE TITLE
Add documentation section on capabilities

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3769]
We don't currently have a documentation section on capabilities. Since capabilities could be used during build-time or deploy-time, it's unclear what the right location is for them in the docs. I could imagine just adding them to the deployment docs for the time being and refactoring them later. The docs should:

* Explain why capabilities exist
* Show the capabilities structure and features
* Show an example with `opa build`

Resources:

* `opa build --help` explains capabilities
* `opa eval --help` has an example (as of v0.32.0) as well
* https://github.com/open-policy-agent/opa/blob/main/CHANGELOG.md#capabilities

**Comment by peteroneilljr** [comment]
Working draft located [here](https://github.com/peteroneilljr/opa/pull/1)

I installed the latest Hugo version, so my local rendering is kinda borked. I tried to render it directly in Netlify but it doesn't pick up any of the changes I've made.

**Comment by peteroneilljr** [comment]
Unblocked: Latest releases live under /edge.
https://deploy-preview-1--serene-shockley-45be55.netlify.app/docs/edge/deployments/#capabilities

The next step is to add the available capabilities from the code into the docs.
https://github.com/open-policy-agent/opa/blob/main/ast/capabilities.go
