### ISSUE TITLE
admissionregistration.k8s.io/v1beta1 deprecated problem with OPA / ISTIO 1.11 / K8S 1.22

### ISSUE THREAD

**Issue by danilorsilva** [open-policy-agent/opa#3778]
Hello all,

I am trying to install OPA (using quickstart guide) with Istio 1.11 and Kubernetes 1.22

https://www.openpolicyagent.org/docs/latest/envoy-tutorial-istio/

I have facing some problems with admissionregistration.k8s.io/v1beta1 api because it was deprecated and removed from kubernetes 1.22. I tried to edit the configmaps to replace v1beta1 for v1 without sucess.

error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/opa-envoy-plugin/main/examples/istio/quick_start.yaml": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"

Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": failed to call webhook: converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion

Is there any work in progress to update opa quickstart doc?

Thanks!

**Comment by ashutosh-narkar** [comment]
Not at the moment. We'll have to update the recommend Kubernetes version in the doc and use the new api which means it won't work with previous versions.  Have you tried to update the manifest itself as defined [here](https://raw.githubusercontent.com/open-policy-agent/opa-envoy-plugin/main/examples/istio/quick_start.yaml) and use it for your use-case.

**Comment by danilorsilva** [comment]
Hello @ashutosh-narkar , thanks for your quick reply.

My step-by-step:

1 - minikube start --memory 8192 --cpus 4

2 - istioctl install --set profile=demo -y

3 - kubectl label namespace default istio-injection=enabled

4 - kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/opa-envoy-plugin/main/examples/istio/quick_start.yaml

#####

Warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
envoyfilter.networking.istio.io/ext-authz created
namespace/opa-istio created
secret/server-cert created
configmap/inject-policy created
service/admission-controller created
deployment.apps/admission-controller created
configmap/opa-istio-config created
configmap/opa-policy created
error: unable to recognize "quick_start.yaml": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"

###

First i changed line 313, replacing admissionregistration.k8s.io/v1beta1 for admissionregistration.k8s.io/v1 to solve this error.

and repeat the step 4

###

Warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
envoyfilter.networking.istio.io/ext-authz created
namespace/opa-istio created
secret/server-cert created
configmap/inject-policy created
service/admission-controller created
deployment.apps/admission-controller created
error: error validating "quick_start.yaml": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "sideEffects" in io.k8s.api.admissionregistration.v1.MutatingWebhook, ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1.MutatingWebhook]; if you choose to ignore these errors, turn validation off with --validate=false

###

So, i added this lines to solve this problem:

  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None

and repeat the step 4.

Warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
envoyfilter.networking.istio.io/ext-authz created
namespace/opa-istio created
secret/server-cert created
configmap/inject-policy created
service/admission-controller created
deployment.apps/admission-controller created
mutatingwebhookconfiguration.admissionregistration.k8s.io/opa-istio-admission-controller created
configmap/opa-istio-config created
configmap/opa-policy created

Everything okay.

###

5 - kubectl label namespace default opa-istio-injection="enabled"

     default           Active   10m     istio-injection=enabled,kubernetes.io/metadata.name=default,opa-istio-injection=enabled

6 - kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/bookinfo.yaml

1s          Warning   FailedCreate              replicaset/productpage-v1-6b746f74dc   Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": failed to call webhook: converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion
8s          Normal    ScalingReplicaSet         deployment/productpage-v1              Scaled up replica set productpage-v1-6b746f74dc to 1
2s          Warning   FailedCreate              replicaset/ratings-v1-b6994bb9         Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": failed to call webhook: converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion
8s          Normal    ScalingReplicaSet         deployment/ratings-v1                  Scaled up replica set ratings-v1-b6994bb9 to 1
1s          Warning   FailedCreate              replicaset/reviews-v1-545db77b95       Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": failed to call webhook: converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion
8s          Normal    ScalingReplicaSet         deployment/reviews-v1                  Scaled up replica set reviews-v1-545db77b95 to 1
1s          Warning   FailedCreate              replicaset/reviews-v2-7bf8c9648f       Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": failed to call webhook: converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion
8s          Normal    ScalingReplicaSet         deployment/reviews-v2                  Scaled up replica set reviews-v2-7bf8c9648f to 1
1s          Warning   FailedCreate              replicaset/reviews-v3-84779c7bbc       Error creating: Internal error occurred: failed calling webhook "istio.openpolicyagent.org": failed to call webhook: converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion

Any idea?

Thanks one more time.

**Comment by ashutosh-narkar** [comment]
This seems to be something related to porting the manifest to the new k8s version. Are there any errors in the OPA container ? I doubt OPA even gets the request but good to check. Also any logs in the Envoy container ?

**Comment by danilorsilva** [comment]
@ashutosh-narkar Do you recommend an approved version for k8s, istio and opa to test here without problems?

**Comment by ashutosh-narkar** [comment]
I tried the tutorial with the following and it worked as expected:

```
minikube version: v1.22.0
kubernetes version: v1.21.2
istio version: 1.11.2
opa image: openpolicyagent/opa:latest-istio 
```

We need to update [Step 4](https://www.openpolicyagent.org/docs/latest/envoy-tutorial-istio/#4-set-the-gateway-url-environment-variable-in-your-shell-to-the-public-ip-port-of-the-istio-ingress-gateway) of the tutorial.[ Install Istio ](https://istio.io/latest/docs/setup/getting-started/#install)and follow the tutorial up to step 3 and then:

In a second terminal, start a minikube tunnel to allow for use of the LoadBalancer service type.
```
$ minikube tunnel
```

Then in the first terminal exercise the policy:

```
$ curl --user alice:password -i http://127.0.0.1/productpage                       <---- 200
$ curl --user alice:password -i http://127.0.0.1/api/v1/products                   <---- 403

$ curl --user bob:password -i http://127.0.0.1/productpage                         <---- 200
$ curl --user bob:password -i http://127.0.0.1/api/v1/products                     <---- 200
```

**Comment by danilorsilva** [comment]
i did as you and i have no error.  Thank you so much @ashutosh-narkar 

Now i will test https://www.openpolicyagent.org/docs/latest/http-api-authorization/#8-optional-use-json-web-tokens-to-communicate-policy-data
