### ISSUE TITLE
Rule output is a list, but is treated like an object

### ISSUE THREAD

**Issue by jalseth** [open-policy-agent/opa#3779]
## Expected Behavior

Rules that output a list are able to be referenced by index number.

## Actual Behavior

Rules that output a list are treated as objects/dictionaries and cannot be referenced by index, but are able to be referenced by specifying the key.

## Steps to Reproduce the Problem

```rego
package play

# my_numberes is a list of numbers
my_numbers := [3, 4, 5]

# my_numbers_rule is a rule that copies my_numbers
my_numbers_rule[n] {
	n := my_numbers[_]
}

x := my_numbers[1] # Equals 4 as expected

y := my_numbers_rule[4] # Should be undefined because the length is only 3, but equals 4

z := my_numbers_rule[1] # Should equal 4, but is undefined
```

Which evaluates to:

```json
{
    "my_numbers": [
        3,
        4,
        5
    ],
    "my_numbers_rule": [
        3,
        4,
        5
    ],
    "x": 4,
    "y": 4
}
```

**Comment by ashutosh-narkar** [comment]
`my_numbers_rule ` generates a set containing your numbers.  If you wanted to write a rule that returns a list of numbers you could try something like

```rego
my_numbers_rule_list = res {
	res := [ x | x := my_numbers[_]]
}

allow {
	my_numbers_rule_list[0] == 3
        my_numbers_rule_list[1] == 4
        my_numbers_rule_list[2] == 5
}
```

More information can be found [here](https://www.openpolicyagent.org/docs/latest/policy-language/#rules).

**Comment by jalseth** [comment]
Ah, that makes sense. I was relying too much on the JSON output in the Playground, but JSON doesn't have a way of differentiating ordereds lists and unordered sets so they appeared to be the same. Thank you!
