### ISSUE TITLE
Add "edit on github" to website's docs

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3784]
The docs section of the website is driven by git-tracked files. It would be neat to display "edit on github" ribbons or buttons, like [on the deno docs](https://deno.land/manual@v1.13.2/getting_started/webassembly), for example:

![image](https://user-images.githubusercontent.com/870638/133233721-370d61d5-1ec8-49bb-8c75-9bfc2815aa44.png)

**Comment by msidana** [comment]
Can I work on this?

**Comment by srenatus** [comment]
Yes of course! Thanks for looking into it !
