### ISSUE TITLE
kubernetes examples: admission.k8s.io/v1beta1 -> admission.k8s.io/v1

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3785]
The tutorials and examples still use `admission.k8s.io/v1beta1` in a bunch of places, a version that was deprecated with kubernetes 1.16.

The examples should be updated and verified with a recent k8s cluster.

**Comment by srenatus** [comment]
@olamiko sure!

**Comment by srenatus** [comment]
@olamiko thanks for working in this! with https://github.com/open-policy-agent/opa-envoy-plugin/pull/291 merged, are we done here? 🔍 or any there still old bits untouched somewhere..

**Comment by anderseknert** [comment]
Not seeing `admission.k8s.io/v1beta1` anywhere in the docs now, so I think this is good to close. Will reopen if anyone proves me wrong.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/issues/3991 is a follow-up, I guess.
