### ISSUE TITLE
Fix network name in docker commands in the Kafka tutorial

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3790]
Just running through the kafka usecase on the website and found a typo.  In the compose up we specify the project name to be opa-kafka-tutorial:

```
docker-compose --project-name opa-kafka-tutorial up
```

But in all the later run examples we specify the network to be opakafkatutorial_default:

```
docker run --rm --network opakafkatutorial_default ...
```

Adding the dashes allowed all the run commands to work.

This is likely an issue caused by a newer version of Docker. We should just update the tutorial and mention the supported version of Docker.

The source for the tutorial is here: https://github.com/open-policy-agent/opa/blob/main/docs/content/kafka-authorization.md

**Comment by nathan-415** [comment]
I would like to work on this. Thanks

**Comment by anderseknert** [comment]
This was fixed in the recent rewrite.
