### ISSUE TITLE
sprintf not working in rego policy

### ISSUE THREAD

**Issue by sburnwal** [open-policy-agent/opa#3806]
I have sprintf in one of the rule, but does not seem to be working. This is very basic but can someone tell me what am I doing wrong? Both online on https://play.openpolicyagent.org/ as well offline with opa version 0.32.0 does not seem to be working.

## Expected Behavior
policy should evaluate 

## Actual Behavior
policy does not evaluate

## Steps to Reproduce the Problem
On https://play.openpolicyagent.org/, try with:
Rego policy:
```
package cs

deny[reason] {
    input.spec.resourceAttributes.namespace == "sveltos"
    reason := sprintf("OPA: User (%v) must belong to valid group", input.spec.user)
}

```

Input:
```
{
  "spec": {
    "resourceAttributes": {
      "namespace": "sveltos",
      "resource": "pods"
    },
    "user": "jane"
  }
}
```

Output simply comes as:
```
{
    "deny": []
}
```

I expect the output to be:
```
{
    "deny": ["OPA: User Jane must belong to valid group"]
}
```

**Comment by anderseknert** [comment]
OPA doesn’t (yet) have varargs functions, so the second argument to sprintf must be an array. In your example:

```rego
package cs

deny[reason] {
    input.spec.resourceAttributes.namespace == "sveltos"
    reason := sprintf("OPA: User (%v) must belong to valid group", [input.spec.user])
}
```

**Comment by srenatus** [comment]
Relevant: #3742 would show this, I think.

**Comment by sburnwal** [comment]
Thank you so much for the prompt response, Closing the issue!
