### ISSUE TITLE
OPA build command: Unexpected bundle output when provided absolute path

### ISSUE THREAD

**Issue by teodora-sandu** [open-policy-agent/opa#3820]
## Expected Behavior
I have some rego rules defined in my current folder.
If I run `opa build .`, I get an archive that contains the rules in my current folder.
If I run `opa build /absolute/path/to/local/folder`, I get an archive that contains a top folder `absolute`, with the structure `absolute` -> `path` -> `local` -> `folder`.

## Actual Behavior
If I run `opa build /absolute/path/to/local/folder`, I want the resulting archive to have the rules in my current folder.

## Steps to Reproduce the Problem

Result of running `opa version`:
```
Version: 0.31.0-dev
Build Commit:
Build Timestamp:
Build Hostname:
Go Version: go1.16.2
WebAssembly: unavailable
```

1. Create any Rego rule
2. Run `opa build .`
3. Save archive and look inside of it to find the contents of your current folder
4. Run `pwd` (if Linux/MacOS) then pass the result as the path to `opa build`
5. Save archive and look inside of it to find the top-level folder returned by the `pwd` 

## Additional Info
N/A

**Comment by ashutosh-narkar** [comment]
Can you help me understand the issue you're having with the resulting bundle in both cases. If you do a `opa run` on the bundle and checkout the layout it should be the same in either case.

**Comment by teodora-sandu** [comment]
The bundle works either way.

The issue is if I run `opa build /Users/test/Documents/example`, the resulting bundle contains the `data.json` and a `Users` folder with the following structure.
```
Users
└───test
│     └───Documents
│       │     └───example
│       │       │     └───test.rego
```

Whereas it should just contain my `test.rego` file. If I need to unarchive the resulting bundle and have a look at the files inside of itm I need to know what folder to `cd` into.

**Comment by ashutosh-narkar** [comment]
Currently `data.json` is always written to the resulting bundle. It may be empty as in your example above. Also the bundle write code uses the absolute path to write the module.

> If I need to unarchive the resulting bundle and have a look at the files inside of itm I need to know what folder to cd into.

I think the work that will be done as part of [this](https://github.com/open-policy-agent/opa/issues/3754) issue should make bundle inspection easier.

**Comment by teodora-sandu** [comment]
Thank you, I think the issue you linked would solve the core problem I was trying to fix. If you want to close this feel free to!

**Comment by ashutosh-narkar** [comment]
@teodora-sandu we have added a new command to called `opa inspect` to help with inspecting bundles. It should be part of the next release. It's also available in the `main` branch if you want to try it out.
