### ISSUE TITLE
Docs: Kubernetes Tutorial should support K8s 1.22+

### ISSUE THREAD

**Issue by pvsone** [open-policy-agent/opa#3821]
https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#3-deploy-opa-on-top-of-kubernetes

In the latest version of minikube it runs kubernetes version 1.22 in which the ValidatingWebhookConfiguration is now in api v1 rather than v1beta1. There are also two new required fields.

This patch to the ValidatingWebhookConfiguration in your tutorial worked for me:

apiVersion: admissionregistration.k8s.io/v1
webhooks:
  - name: validating-webhook.openpolicyagent.org
    admissionReviewVersions:
    - "v1beta1"
    sideEffects: None

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/issues/3785

**Comment by tsandall** [comment]
@anderseknert @srenatus can we close this now?

**Comment by anderseknert** [comment]
Indeed!
