### ISSUE TITLE
Allow plugins to be manually triggered from SDK instance

### ISSUE THREAD

**Issue by edpaget** [open-policy-agent/opa#3828]
## Expected Behavior

I would like to manually trigger a bundle download against an instance of the OPA Go SDK using the triggers added in #2899

## Actual Behavior

The SDK does not provide an interface whereby a plugin's manual trigger can be invoked.

## Steps to Reproduce the Problem

N/A

## Additional Info

I think an interface like `func (opa *OPA) TriggerPlugin(ctx context.Context, pluginName string)` would be enough to do this. The SDK could find the plugin from its internal state and invoke Trigger. Not sure if there's any case to expose the plugin instances themselves from the SDK.

**Comment by anderseknert** [comment]
This is possible in [v0.36.0](https://github.com/open-policy-agent/opa/releases/tag/v0.36.0)+ 😃 

```go
options := sdk.Options{
    Config: bytes.NewReader(config),
    Logger: logger,
    Ready:  make(chan struct{}), // <-- neeeded or else sdk.New will block
}

opa, err := sdk.New(ctx, options)
if err != nil {
    log.Fatal(err)
}
defer opa.Stop(ctx)

// Safety check omitted :) 
bundle := opa.Plugin("bundle").(*bundle.Plugin)

err = bundle.Trigger(ctx)
if err != nil {
    log.Fatal(err)
}
```

Will close the issue, but do let me know if something doesn't work as expected and I'll reopen it.
