### ISSUE TITLE
Possible error in `allOf` implementation

### ISSUE THREAD

**Issue by jdesrosiers** [open-policy-agent/opa#3834]
https://thenewstack.io/json-schema-keywords-allof-and-anyof-in-opa-type-checker/

Hi, I came across this article on twitter and I noticed that there seems to be a misunderstanding about how `allOf` is supposed to work. I don't know if the misunderstanding extends to the implementation or just the article, but I wanted to report it just in case.

```
{
    "type": "object",
    "allOf":[
        {
            "properties": {
                "State":  { "type": "string" },
                "City":   { "type": "string" },
                "ZipCode": { "type": "string" }
            }
        }  
    ]
}
```
> allowing “allOf” ensures security in that all the required information will be there.

The article gives the impression that the `allOf` keyword asserts that all of the properties declared are required. The `allOf` keyword means that all of the schemas provided must successfully validate against the instance. In the example schema, the `allOf` really does nothing. It's like the parenthesis in the expression `A && (B && C)`. It doesn't hurt anything, but it's not really helping either. The keyword to use to require that properties are present is the `required` keyword.

Here's a couple references that might be helpful
* [Understanding JSON Schema - allOf](https://json-schema.org/understanding-json-schema/reference/combining.html#allof)
* [Understanding JSON Schema - required](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties)
* [Official JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/)

Also, we have a channel in the official [JSON Schema Slack](https://json-schema.org/slack) called `#implemeters` that you might be interested in joining. It's a good place to share ideas with others that are writing or have written JSON Schema implementations.

**Comment by tsandall** [comment]
@aavarghese can you weigh in on this?

**Comment by srenatus** [comment]
Thanks for the attention. @aavarghese would know better, but I believe there's no problem here: JSON Schema support in OPA is all about catching typos in references to documents that we have a JSON schema for. So, from the article, if you write `input.States` you'll get this error:

```
input.States
   ^
   have: "States"
               want (one of): ["City" "County" "PostCode" "State" "ZipCode"]
```

So, our support for anyOf and allOf means we use them to collect the _potential_ properties.

When writing a rego policy against a document, we don't care if the document is well-formed -- we only care about the policy not referencing parts of the document that don't exist, as per the JSON Schema.

Does that clarify things?

**Comment by aavarghese** [comment]
@jdesrosiers @tsandall @srenatus thank you for bringing up this discussion. 

The Address example used in the blog was really meant as an intro to the policy being discussed later in the blog. And as @srenatus correctly pointed, they keywords "allOf" and "anyOf" determine the form of the resulting schemas (with all its potential properties) that is then used to type-check the policy document. Json data itself is not validated against the schema.

The statement ```Allowing “anyOf” then adds the flexibility of choosing different mailing address options, and allowing “allOf” ensures security in that all the required information will be there.``` is incorrect when considering JSON validation but was explaining essentially the structure of the schemas against which type checking will happen.

OPA's type checker implements these keywords in accordance with the JSON Schema specifications - where all schemas under allOf are merged into a single schema and then type checked against. Hopefully the official doc helps explain a bit better: https://www.openpolicyagent.org/docs/latest/schemas/#supporting-json-schema-composition-keywords

**Comment by jdesrosiers** [comment]
> our support for anyOf and allOf means we use them to collect the _potential_ properties.

Great. That's exactly what I would expect those keywords to do. So, the use of `allOf` in the example from the article shows that the system understands the `allOf` keyword, but it wasn't actually necessary (because all of the `allOf`s are singletons) to express the constraints of the Address. The same potential properties would be collected either way.

> OPA's type checker implements these keywords in accordance with the JSON Schema specifications - where all schemas under allOf are merged into a single schema and then type checked against.

Actually, JSON Schema does not specify `allOf` as a merge, but I understand if you need to implement it that way because you're using JSON Schema for something it wasn't designed for (it was only designed for validation). You can usually merge schemas, but it's not trivial to do right. For example,

```json
{
  "type": "object",
  "allOf": [
    {
      "properties": {
        "a": { "type": "string" }
      }
    },
    {
      "additionalProperties": false
    }
  ]
}
```
The first schema in the `allOf` says, if it has an "a" property, it must be a string. There might be other properties present, but they are unconstrained. The second schema allows no properties at all. The only thing that would match this schema is an empty object. This means the merged schema should look like this,

```json
{
  "additionalProperties": false
}
```

If we had done a simple merge, we would have ended up with the following which does not describe the same structure.

```json
{
  "type": "object",
  "properties": {
    "a": { "type": "string" }
  },
  "additionalProperties": false
}
```

I saw in your documentation that you don't support `additionalProperties`, so I know this exact example doesn't apply to you, but I wanted to show a dramatic example as a warning that schemas don't always merge the way you might expect.

Good luck you all. I hope my comments have been helpful and not just unsolicited ramblings.

**Comment by aavarghese** [comment]
Thank you @jdesrosiers - this was VERY helpful for us.

When `additionalProperties` is implemented, it will change the design for some of this type checking work. So this is great to keep in mind.
