### ISSUE TITLE
Better support for violation detection in watches

### ISSUE THREAD

**Issue by mmussomele** [open-policy-agent/opa#384]
Once #376 is merged, watches will allow a client to set a watch on a query or data document in order to be notified of changes to it. One use case of this is to set a watch on violation detecting policies. But watches currently are not as well suited for this particular use case as they could be, for 2 reasons:

1. They batch updates. If two different data items that a watch depends on are changed before the server gets a chance to re-evaluate, only one notification will be sent, representing the most recent state of the query. Violation detecting watches would want to see every change, especially for those with security implications.

2. Watches send full updates instead of diffs. Diffs themselves are a tricky thing to get right, as some clients may have certain semantics around diffs (i.e. a modification sent as a deletion-insertion pair may cause state to be destroyed and recreated instead of just updated). But in the context of violation watches, diffs on queries that produce sets could be valuable.

Whenever (or if) violation watches are supported, we should think about how to best update the watch API to support them.

**Comment by tsandall** [comment]
Closing this for now as we don't have plans to work on this for the time being.
