### ISSUE TITLE
`opa fmt` changed for `with x as { ... }` expressions in 0.33.0

### ISSUE THREAD

**Issue by iainmcgin** [open-policy-agent/opa#3849]
## Expected Behavior

Given some example rego like the following for a test:

```rego
package example

test_require_context {
	require_context("monkey", "eat", "banana") with input as {
		"principal": {"id": 101, "type": "monkey"},
		"action": "eat",
		"entity": {"id": 102, "type": "banana"},
	}
}
```

This was acceptable to `opa fmt` as correctly formatted, in 0.32.1. With 0.33.0, this now appears to try and reorder the keys, and produces:

```rego
test_require_context {
	require_context("monkey", "eat", "banana") with input as {
		"action": "eat",
		"entity": {"id": 102, "type": "banana"}, "principal": {"id": 101, "type": "monkey"},
	}
}
```

I can manually change this to:

```rego
test_require_context {
	require_context("monkey", "eat", "banana") with input as {
		"action": "eat",
		"entity": {"id": 102, "type": "banana"}, 
		"principal": {"id": 101, "type": "monkey"},
	}
}
```

The formatter will accept this, but it's a little frustrating that the produced reformatting squashes all the reordered keys onto a single line.

## Actual Behavior

As a contrived example:

```rego
test_contrived {
	allow with input as {
		"a": 101,
		"b": 101,
		"z": 101,
		"y": 101,
		"x": 101,
		"w": 101,
		"v": 101,
		"u": 101,
		"t": 101,
		"s": 101,
		"r": 101,
		"q": 101,
		"p": 101,
		"o": 101,
		"n": 101,
		"j": 101,
		"k": 101,
		"l": 101,
		"m": 101,
	}
}
```

Is reformatted to:

```rego
test_contrived {
	allow with input as {
		"a": 101,
		"b": 101,
		"j": 101,
		"k": 101,
		"l": 101,
		"m": 101, "n": 101, "o": 101, "p": 101, "q": 101, "r": 101, "s": 101, "t": 101, "u": 101, "v": 101, "w": 101, "x": 101, "y": 101, "z": 101,
	}
}
```

## Steps to Reproduce the Problem

Using OPA 0.33.0, run the above examples through `opa fmt --diff` or `opa fmt --write`. Compare this to the output with OPA 0.32.1.

## Additional Info

This issues likely gets into thorny prioritization problems around where line breaks should occur and what indentation to respect when formatting. Hopefully the above examples will help serve as tie-breaking examples to help tune the formatter for readability.

**Comment by srenatus** [comment]
Thanks for raising that! It's an unintended consequence of sorting object keys on creation (#3823 fixing #3819). I'm not entirely certain how it's deciding when to line break and when to put the remaining keys on one line...

What would you prefer? All line breaks? 🤔

**Comment by srenatus** [comment]
I suppose we could also maintain two key slices, one for comparisons (sorted), one for iteration order... 🤔

**Comment by srenatus** [comment]
⏩ Fixes in [0.33.1](https://github.com/open-policy-agent/opa/releases/tag/v0.33.1)

**Comment by iainmcgin** [comment]
Thank you for fixing this, and apologies for being slow to answer your questions. Line breaks are probably best, but I had wanted to find some prior art in JSON formatters for what thresholds to use for formatting smaller objects on one line vs indent-and-break.

**Comment by srenatus** [comment]
No worries! It's been a genuine ugly bug, so I've decided to move fast on it. Thanks again for testing the release raising it this quickly before more folks would have stumbled over this. 🎉
