### ISSUE TITLE
Report a coding bug about unused result.

### ISSUE THREAD

**Issue by guodongli-google** [open-policy-agent/opa#3850]
## Expected Behavior

At https://github.com/open-policy-agent/opa/blob/main/bundle/bundle_test.go#L31, the result of function [`Equal`](https://github.com/open-policy-agent/opa/blob/main/bundle/bundle.go#L189-L199) not used:
```
m.rootSet().Equal(stringSet{"x/y": struct{}{}, "y/z": struct{}{}})
```
while this function has no side effect:
```
func (ss stringSet) Equal(other stringSet) bool {
	if len(ss) != len(other) {
		return false
	}
	for k := range other {
		if _, ok := ss[k]; !ok {
			return false
		}
	}
	return true
}
```
The correct code may be something like:
```
if !m.rootSet().Equal(stringSet{"x/y": struct{}{}, "y/z": struct{}{}}) {
	t.Fatal("expected roots to be equal")
}
```

**Found by static analyzer #deepgo**

**Comment by srenatus** [comment]
LGTM. Would you be interested in opening a PR?

**Comment by guodongli-google** [comment]
> LGTM. Would you be interested in opening a PR?

I will be happy to, but opening a PR to fix this issue will require going through a tedious process within my organization, even if that involves only 1-line change.

**Comment by srenatus** [comment]
Noted! Let's make this a low-hanging fruit issue for anyone wanting to get into OPA development. After all, the code change isn't the tricky bit here, but it's setting up the dev env, running tests locally, opening a PR, etc.

**Comment by srenatus** [comment]
@olamiko sure!

**Comment by cyclinder** [comment]
@srenatus tks~
