### ISSUE TITLE
docs: mention discussion site on contributing page

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3859]
There's https://github.com/open-policy-agent/feedback/discussions now for general questions and discussions, and having a look at those, contributing your knowledge and helping others is another great way to contribute to the OPA project. I think we should thus mention the discussion page in the Contributing section.

**Comment by anderseknert** [comment]
AFAIKS, this is done - https://www.openpolicyagent.org/docs/latest/contributing/

> Help out other members in the OPA Slack Org and on the GitHub Discussions Board

Close this, @srenatus, or did you have another location than the above in mind?

**Comment by srenatus** [comment]
Indeed! Thanks for checking.
