### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by kotyara85** [open-policy-agent/opa#3867]
Hey there,
Our team have been doing OPA related stuff for a while now and noticed a bit weird memory profile.
We did run lot of tests and our policies seems to be pretty optimized, we don't use any glob stuff, but have ~40mb of raw json data.
Per this page - https://www.openpolicyagent.org/docs/latest/policy-performance/#optimization-levels it should account in about 20x more memory used by opa which sort of reflected in pprof heap profile.
But what's interested that the actual pod memory usage in k8s ranges between 4-7Gb

Any suggestions on what could be wrong here?

Thanks

**Comment by anderseknert** [comment]
This can’t move forward unless we’re provided with more details. Closing and will reopen if that comes in later.
