### ISSUE TITLE
Mask passwords in input

### ISSUE THREAD

**Issue by kotyara85** [open-policy-agent/opa#3874]
Hello there,
We've using opa 0.29 and trying to use this - https://www.openpolicyagent.org/docs/v0.13.5/decision-logs/
to mask sensitive data in the debug output. This didn't work and I still see user passwords.

Is there anything need to be done extra to it?

log.rego
```
$ cat ../log.rego
package system.log

mask["/input/user"]
``` 

Thanks

**Comment by ashutosh-narkar** [comment]
Can you share the input ? `"/input/user"` will remove the `user` field from decision log events. Also [here](https://www.openpolicyagent.org/docs/latest/management-decision-logs/#masking-sensitive-data) are the latest docs on that feature.

**Comment by kotyara85** [comment]
Figured it out, thanks!
