### ISSUE TITLE
Improve visibility into OPA in server mode

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#389]
When OPA is running in server mode, it logs semi-structured request/response data via logrus. In some cases, it would be easier to understand if OPA is working if we had higher level support exposed through the API.

Some ideas:

- Introduce a ring buffer to store evaluation diagnostics. Incoming queries could be filtered to see if diagnostics should be enabled. If diagnostics are enabled then tracing, profiling, and so on would be saved in-memory.

- Introduce aggregate metrics in the server to show which policies are being evaluated.

**Comment by tsandall** [comment]
Related to #236

**Comment by mmussomele** [comment]
Idea 1 fixed by #402

**Comment by mmussomele** [comment]
Idea 2 fixed by #403

**Comment by tsandall** [comment]
Fixed by #403 #402
