### ISSUE TITLE
Pull external data from redis

### ISSUE THREAD

**Issue by kotyara85** [open-policy-agent/opa#3894]
Is there any docs on how to pull data from external k=v stores like Redis?
Thanks

**Comment by anderseknert** [comment]
Hi @kotyara85!

OPA itself doesn't come with drivers or connectors for external datasources like Redis. You'll either need to package the data you're interested in into a bundle and have OPA fetch that periodically, or use any of the other methods available to[ load external data into OPA](https://www.openpolicyagent.org/docs/latest/external-data/). If you want to reach out to Redis directly from inside of your policies, the `http.send` function together with something like [Webdis](https://webd.is/) might do the trick.

As a last, more advanced option, you could write a custom built-in that fetches data from Redis using a [Go client](https://github.com/go-redis/redis), though this would of course require some development effort.
