### ISSUE TITLE
Policy that reaches namespaces label through deployment

### ISSUE THREAD

**Issue by DcardosoJS** [open-policy-agent/opa#3903]
Hello,

I am writing this to get some official assistance on a policy idea that my organization has been struggling with.
We have tried to replicate this concept with both OPA and Kyverno but to no success.

The issue is that we are trying to prevent certain Deployments to be created, if the corresponding Namespace does not have a label with an alarm group (for integration with AlertManager ex: alarmGroup: "X")

The logic would be that the policy validates this with the following logic:

Deployment -> check deployment's Namespace -> Namespace label -> Approve

We have been unable to do this and want to know if this is possible at all.

**Comment by srenatus** [comment]
I'm cleaning this up. 🧹  Feel free to reopen if you get back to this.
