### ISSUE TITLE
GRPC server in opa-envoy-plugin should be configured with MaxRecvMsgSize

### ISSUE THREAD

**Issue by maclaf** [open-policy-agent/opa#3933]
Hi,
I would like to have possibility to define max message size for gprc server that is created here:
https://github.com/open-policy-agent/opa-envoy-plugin/blob/50b620edeb2855697e54b859075453ed38bc6fcd/internal/internal.go#L108

At the moment there is no possibilities to handle by this plugin requests larger than 4MB. 

In go GRPC from version 1.4.0 there is the option to set server option MaxRecvMsgSize:
https://pkg.go.dev/google.golang.org/grpc@v1.41.0#MaxRecvMsgSize
"MaxRecvMsgSize returns a ServerOption to set the max message size in bytes the server can receive. If this is not set, gRPC uses the default 4MB."

Could you upgrade go grpc from version 1.39 .1 to > 1.4.0 and make MaxRecvMsgSize to be configurable for this plugin, please ?

Thanks.

**Comment by christian1607** [comment]
Hi @srenatus, I've seen this issue has already been solved.
https://github.com/open-policy-agent/opa-envoy-plugin/blob/21e73a859ecdbf12c2e4da45600381dd2c1167d3/internal/internal.go#L69

**Comment by srenatus** [comment]
Thanks @christian1607
