### ISSUE TITLE
Allow policy-based dropping of some decision log items

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3945]
Similar to how we currently allow masking sensitive data from decision logs, it would sometimes be useful to be able to drop decision log events entirely based on certain conditions. Some clients, like the Kubernetes API server, are very chatty, and will send a huge number of requests which aren't really interesting for most policies, like the `Event` resource admission review object. Another use case is when OPA is used to serve data from some endpoints which aren't really decisions. Logs like this occupy unnecessary space, and makes it more difficult to filter out events of importance.

**Comment by ashutosh-narkar** [comment]
Another criteria would be if users wanted to log decisions based on the policy decision maybe. For example, allowed decisions would be less interesting than the denied ones.

**Comment by asleire** [comment]
I would like to see this as well. Every incoming request is verified with OPA which causes a ton of decision logs. We would like to only log the interesting decisions, which is mainly the denied ones. I think being able to specify a policy that takes the decision as input would be a good solution, similar to `default_authorization_decision`.

**Comment by anderseknert** [comment]
@asleire that type of policy is available for [masking](https://www.openpolicyagent.org/docs/latest/management-decision-logs/#masking-sensitive-data) sensitive data from logging already. I think we could reuse that for dropping decisions entirely, if requested.

**Comment by asleire** [comment]
Yea, I'd like to be able to use it to drop decisions entirely

**Comment by ashutosh-narkar** [comment]
I wonder if we could do something simple like define a `drop` rule like below to achieve this

```rego
package system.log

drop {
 # some logic based on result, query etc.
}
```

**Comment by anderseknert** [comment]
Yeah, I believe the implementation would be fairly simple.
