### ISSUE TITLE
website: when version picker exceeds screenful, it's impossible to select "lower" versions

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3955]
In this picture, there's no way to "scroll" in the version picker:

![image](https://user-images.githubusercontent.com/870638/139841974-291e21c9-e6ed-4849-9c5a-026f4dd89d33.png)

So depending on the viewer's screen size and resolution, some versions just can't be selected. (We've reached a point now where it fills the entire screen for me, which is why I'd noticed 😅) 

Adding the `help-wanted` tag. The simplest solution might be to make the version picker scrollable. If anyone has the knowledge to come up with a better solution, please suggest them! 📢

**Comment by orweis** [comment]
I think scrollable is the way to go here:
![image](https://user-images.githubusercontent.com/2079277/140201201-7cc9accf-d3ca-4a90-8293-9cc89bb2273b.png)

Simply add something like this:
```css
    { 
    max-height: 60vh;
    overflow-y: auto;
    }
```
to .dropdown-menu.dropdown-content

If you want to point me at the source files, I can do a PR
