### ISSUE TITLE
Use go embed to serve capabilities files via package level variable

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3961]
We currently export the capabilities files for each version in the capabilities directory. It would be nice if those capabilities were available via the Go module. We can do this quite easily with go embed:

Create a new file called capabilities/capabilities.go:

```go
package capabilities

import (
	"embed"
)

//go:embed *.json
var Capabilities embed.FS
```

**Comment by srenatus** [comment]
IIRC this means removing support for building with go 1.15. but that's probably ok.

**Comment by tsandall** [comment]
> IIRC this means removing support for building with go 1.15. but that's probably ok.

I'm not sure what the general feeling is around this. Since this is a pretty niche need, I'd suggest we hold off for a bit--but I don't feel too strongly.

**Comment by anderseknert** [comment]
Would including these in the executable mean we could have a way of exposing the capabilities from the CLI? I'm thinking something like `opa capabilities <version>` could print the JSON object of capabilities. This would be useful when building bundles targeting a specific version of OPA, and currently requires the user to download the OPA sources:

```shell
opa build ./policies --capabilities $OPA_SRC/capabilities/v0.22.0.json
```
If they are included in the binary, we could instead do something like:
```shell
opa build ./policies --capabilities < $(opa capabilities v0.22.0)
```
Or even
```shell
opa build ./policies --capabilities v0.22.0
```
But we might still want to have a standalone command to print them if the admin wants to modify them.

**Comment by srenatus** [comment]
> Since this is a pretty niche need, I'd suggest we hold off for a bit--but I don't feel too strongly.

 If this is just about the package level variables, we can build flag this. 1.15 users won't get trouble and also won't get the package level vars.
