### ISSUE TITLE
Kafka Tutorial Showcasing Management APIs

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#3963]
This issue replaces #3184 and is purely focused on the Kafka plugin. We need to update that tutorial to use a newer version of the Kafka plugin (e.g., [this one](https://github.com/Bisnode/opa-kafka-plugin)) that is compatible with more recent versions of Kafka. In addition, we'll want to show how to configure the management APIs.

**Comment by anderseknert** [comment]
Resolved by https://github.com/open-policy-agent/opa/pull/4129
