### ISSUE TITLE
High CPU when Pull Data during Evaluation

### ISSUE THREAD

**Issue by vinhph0906** [open-policy-agent/opa#3973]
I try to Pull Data during Evaluation for my use case which will use http.Send to my server to get external for evaluation. 

In test case 1 I have my rego file look like

```
external_datas := http.send(request).body
allow {
    true
}
```
My benchmark result is:
CCU: 1k
Requests/s: 4k 
CPU: 200% ~ 2 core CPU

In test case 2  just lookup in my external_datas like:
```
external_datas := http.send(request).body
allow {
    external_data := external_datas[_]
}
```
My benchmark result is:
CCU: 1k
Requests/s: 1k(time OPA response high) 
CPU: 1500% ~ 15 core CPU(my VM hash 16 vCPU)

My external_datas is an array with one item

I don't why in my test case 2 OPA  "eat" a lot of CPU.

**Comment by srenatus** [comment]
Thanks for compiling this.

One piece that's missing to understand what's going on here is the shape of external_datas itself. Is it large?

**Comment by vinhph0906** [comment]
```
{
    "external_datas": [
        {
            "members": [
                "c3d813b9-ff48-4876-ba51-b4c8853592f2"
            ],
            "policy_id": "6183954e5126dc3d35d7c048",
            "roles": [
                "owner_role"
            ],
            "statements": {
                "statment_1": {
                    "conditions": {},
                    "effect": "allow",
                    "methods": [
                        "GET",
                        "POST"
                    ],
                    "path_regex": "^(/.+)*/people$"
                },
                "statment_2": {
                    "conditions": {},
                    "effect": "allow",
                    "methods": [
                        "GET",
                        "POST"
                    ],
                    "path_regex": "^(/.+)*/people$"
                }
            }
        }
    ]
}
```
This is my external_datas used in the two test cases above. And I think it isn't large.

**Comment by srenatus** [comment]
Oh I think I had missed that you're running some sort of perf test here, aren't you? So what'll be relevant then is an if the request can be cached. Does the server response include the necessary headers?

**Comment by vinhph0906** [comment]
I load test OPA by K6 tool with 
```
options = {
    stages : [
        { duration: '60s', target: 1000 },
        { duration: '60s', target: 1000 },
      ]
```
and sleep time is 0.25s. One VU will send 1 request to OPA sever to make the decision. However, I don't know what are necessary headers?

**Comment by srenatus** [comment]
The caching machinery behind `http.send` is documented here, https://www.openpolicyagent.org/docs/edge/policy-reference/#http, below the options.

**Comment by vinhph0906** [comment]
In the two test cases above, I don't use any cache option. For request:
```
        "method": "POST",
        "url": "url",
        "headers": {
            "Content-Type": "application/json",
            "Accept": "application/json"
            },
        "body":body
```
But I don't understand why lookup my external_datas array have one item with a size that isn't large can increase CPU very high.

**Comment by srenatus** [comment]
Every API call there will create a request, send it to the server, and parse the response. So there's work involved, even if the response only contains a single entry.

You could try to inline that snippet to figure out how much of this http-related overhead and what is not:

```rego
external_datas := [
        {
            "members": [
                "c3d813b9-ff48-4876-ba51-b4c8853592f2"
            ],
            "policy_id": "6183954e5126dc3d35d7c048",
            "roles": [
                "owner_role"
            ],
            "statements": {
                "statment_1": {
                    "conditions": {},
                    "effect": "allow",
                    "methods": [
                        "GET",
                        "POST"
                    ],
                    "path_regex": "^(/.+)*/people$"
                },
                "statment_2": {
                    "conditions": {},
                    "effect": "allow",
                    "methods": [
                        "GET",
                        "POST"
                    ],
                    "path_regex": "^(/.+)*/people$"
                }
            }
        }
    ]
allow {
    external_data := external_datas[_]
}
```

**Comment by srenatus** [comment]
In general, it's best to avoid HTTP requests that aren't necessary. So the server that's serving the response should include how long that information is valid and can be cached. You can override the caching in the parameters to `http.send`.

Alternatively, you could use some other method: bundles, or pushing the data into OPA via the Data API.

**Comment by vinhph0906** [comment]
In my real use case, my external data is dynamic and very large. I have used bundles and pushing the data, but pef of this isn't not good. Now I try to save my external data to db such as MongoDB and have sever with will query db to return external data to OPA evaluation.

**Comment by vinhph0906** [comment]
I agree with the idea is http.send will increase complexity. However, in my test case 1, I have used http.Send but the number of CPU doesn't increase so much like test case 2.

**Comment by srenatus** [comment]
Oh I see. In the first example, assuming your query for `allow`, the http.send call will not be executed: it doesn't affect the query outcome.

**Comment by vinhph0906** [comment]
oh, I understand this issue. Thank you for helping me.

**Comment by vinhph0906** [comment]
On another side, Can you recommend the best way to deal with dynamic and large external data? My project is similar to AWS IAM, with 100k-1M external datas(10k users, 50-100 policies per user) and change very often.

**Comment by srenatus** [comment]
🤔 For the IAM-y use case, does the data really change that often? I.e. would you think the policies get updated more often than queried?

If so, I'd think about the caching parameters -- just how fresh does the data need to be? -- and do more benchmarking in a more realistic setting, if possible.

**Comment by vinhph0906** [comment]
I think the update is less than queried and I can cache in 5 minutes or less. I have tested save external data on memory but is so high RAM. Can I use bundle for my use case?

**Comment by srenatus** [comment]
OPA stores data in memory. Bundles are one way to get that data there, and to have it updated. But ultimately, the data will consume RAM. The only way to avoid storing all the data in RAM would be do what you do here to query the relevant pieces of the data on a per-query basis. However, you cannot ensure that you don't end up storing it all in RAM anyways -- if every user executes requests, and the external data is cached, it'll be in RAM for a while, too.

**Comment by srenatus** [comment]
Does that help? We can move this into a discussion if you'd like to further discuss the pros and cons of different ways for pulling in data. I think the question at hand here has been resolved..? 🤔

**Comment by vinhph0906** [comment]
I think my question is resolved. Thank you for your help.
