### ISSUE TITLE
Add support for graceful shutdown period in SDK

### ISSUE THREAD

**Issue by brianchhun-chime** [open-policy-agent/opa#3980]
## Expected Behavior

When calling `Stop()` on an OPA SDK instance, it should be possible to provide a graceful shutdown period so that plugins can cleanup before shutting down. In our case, we noticed that the decision logging plugin was not given time to flush its logs before shutting down.

## Actual Behavior

Calling `(*sdk.OPA).Stop()` will immediately shutdown without giving time for plugins to cleanup

If one sets a timeout on the context passed to `Stop()`, it seems to be ignored:

```
const timeout = 1 * time.Minute
ctx, cancel := context.WithTimeout(context.Background(), timeout)
defer cancel()
opaSDK.Stop(ctx) // 1m timeout is ignored
```

After tracing through the OPA SDK code, it appears to call  [`(*plugins.Manager).Stop()`](
https://github.com/open-policy-agent/opa/blob/main/plugins/plugins.go#L575-L594). This method ignores the context's timeout and relies on its own `gracefulShutdownPeriod` value, which cannot be set by the SDK and evaluates to 0 because of default values in Go.

**Comment by tsandall** [comment]
From looking at the implementation, I don't see a reason why we need to implement the graceful shutdown period as an option on the plugin manager. In other words, we can pull the line that sets the timeout on the golang context into the runtime package and keep it out of the plugin manager itself. This way the SDK (and other code that calls into the Manager) will just work.

@anderseknert unless you object, I'll make that change next week.

**Comment by anderseknert** [comment]
@tsandall Sounds good to me!
