### ISSUE TITLE
allow testing opa.runtime()

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#3984]
## Expected Behavior

My code is using for example `opa.runtime().env.FOOBAR`
and I'd like to be able to modify that during a test to test that behavior

## Actual Behavior

Unable to modify it, so unable to test it (unless I change env externally and restart the test).

* OPA version: 0.24.0

**Comment by anderseknert** [comment]
Thank you @grosser! Would your needs be covered by https://github.com/open-policy-agent/opa/issues/2028 ? That would allow you to mock the `opa.runtime()` built-in and other built-in functions. The best way to do it before that lands is probably to use a helper rule/variable and mock that. Something like:
```rego
foobar := opa.runtime().env.FOOBAR

test_me {
    allow with foobar as "mocked"
}
```

**Comment by grosser** [comment]
yeah that should work! :)
