### ISSUE TITLE
OPA/Rego AND operator usage

### ISSUE THREAD

**Issue by gituserjava** [open-policy-agent/opa#3985]
I am new to OPA(and Rego) and writing simple policies. My use-case is the policy should return true when both input.path and input.headers values match and return false when one of them does not match. When I execute below policy I am not getting expected result. Please advise on the correct usage of AND operator. I tried using semi-colon and it also did not work.

**Policy:**
```
package demo

default allow = false

allow = {
        input.path == "/api/v1/employees/departments",
        input.headers["x-custom-header"] == "foo"
}
```

**Input:**
```
{
       "path":"/api/v1/employees/divisions",
       "headers": {
              "x-custom-header" :"foo"
        }
}
```
**As I have passed incorrect path, expected Output should be below:**
```
{
     "allow": [
           false
     ]
}
```

**However i see actual Output as below:**
```
{
     "allow": [
           false,
           true
     ]
}
```

**Comment by anderseknert** [comment]
There shouldn't be a comma after the first line inside the rule body. Each condition inside of the rule will be AND'ed by default, so there's no need for anything more. The problem you see is due to assigning a _set_  to `allow` by using `=`. Remove that (and the comma) and it should work as you intended:

```rego
allow {
        input.path == "/api/v1/employees/departments"
        input.headers["x-custom-header"] == "foo"
}
```

**Comment by gituserjava** [comment]
@anderseknert, you are right. The `=` was the main issue and it worked after removing `=` and `,`.

**Comment by gituserjava** [comment]
@anderseknert , do you have an example policy that can validate an array of header values? In my use-case, there could be multiple values for `x-custom-header`. So if `x-custom-header` is `foo` or `baa` or `abc`; the policy should evaluate to true. Please advise.

**Comment by anderseknert** [comment]
In that case I would expect the header values from the input to be arrays rather than strings. There are many ways to do that, but I'd probably convert the header values to a set, and then use the [set intersection](https://www.openpolicyagent.org/docs/latest/policy-reference/#sets-2) operator to check for common elements.

```json
{
       "path": "/api/v1/employees/departments",
       "headers": {
              "x-custom-header": ["foo", "bar", "qux"]
        }
}
```

```rego
package demo

default allow = false

expected_x := {"foo", "baa", "abc"}

allow {
	input.path == "/api/v1/employees/departments"
	x_custom_values := {x | x := input.headers["x-custom-header"][_]}
    
    count(expected_x & x_custom_values) > 0
}

```

**Comment by srenatus** [comment]
As far as I know, Envoy will send
```json
{
       "path": "/api/v1/employees/departments",
       "headers": {
              "x-custom-header": "foo,bar,qux"
        }
}
```

See https://github.com/open-policy-agent/feedback/discussions/61#discussioncomment-1604611 for source links)

**Comment by anderseknert** [comment]
Didn’t see envoy mentioned, but just split the string on , then… unless there are commas in the values 😄

**Comment by srenatus** [comment]
Here, the discussion if this issue is a bit all over the place 😅 Just wanted to connect the open ends here.

**Comment by srenatus** [comment]
Please reopen if this hasnt been resolved by the answers given... 🧹
