### ISSUE TITLE
website: k8s examples outdated

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3991]
![image](https://user-images.githubusercontent.com/870638/140929379-1c8d3bfe-08af-49b9-88ff-e733719c36d9.png)

These two examples point to hardcoded playground URLs, https://play.openpolicyagent.org/p/ikesWCFIH8 and https://play.openpolicyagent.org/p/oL4Ofd1nQi.

They contain input documents that don't match the latest kubernetes schema, i.e. `"apiVersion": "admission.k8s.io/v1beta1"`.

The playground examples need to be updated, creating new playground links, and those should replace the ones from the website.

**Comment by anderseknert** [comment]
As far as I can see, this was fixed by https://github.com/open-policy-agent/opa/pull/4655

Let me know if that's not the case, and I'll re-open.
