### ISSUE TITLE
built-in function: nslookup

### ISSUE THREAD

**Issue by pvsone** [open-policy-agent/opa#3993]
For some policies it would be useful to resolve an FQDN to an IP Address, therefore a built-in function for `nslookup` would help.

**Comment by tsandall** [comment]
We can wrap Go's `net` package for this.

* Use the [`LookupIPAddr`](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/net/lookup.go;l=206) function and pass the context to ensure timeouts are respected
* The signature in rego will be `(string) => array[string]`
* This function should be added to `ast.IgnoreDuringPartialEval`

**Comment by srenatus** [comment]
Merged. Will be part of the next release.
