### ISSUE TITLE
Issue with SkipPartialNamespace

### ISSUE THREAD

**Issue by thomascoquet** [open-policy-agent/opa#3997]
Hello,
I stumbled upon something strange to me.

`github.com/open-policy-agent/opa v0.33.1`

Here is a snippet:
```go
func TestPartial(t *testing.T) {
	ctx := context.Background()

	// Define a simple policy for example purposes.
	module := `package test

	default allow = false

	allow {
	  input.subject = "j.doe"
	}
	`

	r := rego.New(
		rego.Query("data.test.allow"),
		rego.Module("example.rego", module),
		rego.SkipPartialNamespace(true),
	)
	_, err := r.PartialResult(ctx)
	if err != nil {
		log.Println(err.Error())
	}
}
```

## Expected Behavior
No error.

## Actual Behavior
Yields:
```
example.rego:3: rego_type_error: multiple default rules named allow found
```

## Additional Info

Could you expand at the use of `rego.SkipPartialNamespace` ?

At first, I wanted to define custom functions in a rego file (like `data.operators`) and map them to SQL ones at a later step, for example with array intersection operator `&&`:
```rego
intersects(a, b) {
    a[_] = b[_]
}
```

This is why I wanted to prevent:
- the use of a partial namespace, to catch `data.operators.intersects` when parsing the AST,
- and the inlining of the function using `rego.DisableInlining`.

Thanks, Thomas

**Comment by srenatus** [comment]
I'm not sure I completely understand why `rego.DisableInlining([]string{"data.operators.intersects"})` alone wouldn't do the trick 🤔 Can you show me what I'm missing?

**Comment by srenatus** [comment]
In other words, have you tried doing all this without the SkipPartialNamespace?

Your running into issues because the partially-evaluated policy's `allow` default, which would usually be put into `data.partial.allow`, now is in the same module as the original `allow` rule, I suspect.

I don't think you need to mess with the partial namespace at all, the inline controls should be good enough for this: don't inline the function call you'd like to later replace in the AST.

**Comment by srenatus** [comment]
Have you had a chance to try this?

**Comment by thomascoquet** [comment]
Hello,
Sorry I got caught up with other matters :-)

Here is another snippet closer to what I am doing:

```go
package main

import (
	"context"
	"fmt"

	"github.com/open-policy-agent/opa/rego"
)

var example = `
package example

allow {
	input.subject.user = "alice"
	input.auth_type = "hmac"
}

allow {
	input.subject.user = "john"
	input.auth_type = "api_key"
	data.operators.intersects(input.subject.groups, input.resource.acls)
}
`
var operators = `
package operators

intersects(a, b) {
	a[_] = b[_]
}
`

func main() {
	ctx := context.Background()
	r := rego.New(
		rego.Query("data.example.allow"),
		rego.DisableInlining([]string{"data.operators.intersects"}),
		rego.Module("example.rego", example),
		rego.Module("operators.rego", operators),
	)
	pr, err := r.PartialResult(ctx)
	if err != nil {
		panic(err.Error())
	}
	rb := pr.Rego(
		rego.Input(map[string]interface{}{"auth_type": "api_key"}),
		rego.Unknowns([]string{"input.subject", "input.resource"}),
		rego.DisableInlining([]string{"data.operators.intersects"}),
	)
	q, err := rb.Partial(ctx)
	if err != nil {
		panic(err.Error())
	}
	for _, b := range q.Queries {
		fmt.Println(b.String())
	}
}
```
Yields:
```console
input.subject.user = "john"; input.subject.groups[_] = input.resource.acls[_]
```
It gets inlined because `data.operators.intersects` is modified into `data.partial.operators.intersects`.

----
 So to make it work:
```go
func main() {
	ctx := context.Background()
	r := rego.New(
		rego.Query("data.example.allow"),
		rego.DisableInlining([]string{"data.operators.intersects"}),
		rego.Module("example.rego", example),
		rego.Module("operators.rego", operators),
	)
	pr, err := r.PartialResult(ctx)
	if err != nil {
		panic(err.Error())
	}
	rb := pr.Rego(
		rego.Input(map[string]interface{}{"auth_type": "api_key"}),
		rego.Unknowns([]string{"input.subject", "input.resource"}),
		rego.DisableInlining([]string{"data.partial.operators.intersects"}),
	)
	q, err := rb.Partial(ctx)
	if err != nil {
		panic(err.Error())
	}
	for _, b := range q.Queries {
		fmt.Println(b.String())
	}
}
```

Yields:
```console
input.subject.user = "john"; data.partial.partial.operators.intersects(input.subject.groups, input.resource.acls)
```

that is kind of ugly.

---

To overcome this behavior and 

Thomas

**Comment by thomascoquet** [comment]
Another use case that is weird to me:

```go
package main

import (
	"context"
	"fmt"

	"github.com/open-policy-agent/opa/rego"
)

func main() {
	ctx := context.Background()
	module := `
		package example

		default allow = false
		allow {
			input.subject.user = "john"
		}
	`

	r := rego.New(
		rego.Query("data.example.allow"),
		rego.Module("example.rego", module),
	)

	pr, err := r.PartialResult(ctx)
	if err != nil {
		panic(err.Error())
	}
	rb := pr.Rego(
		rego.Unknowns([]string{"input.subject"}),
	)
	q, err := rb.Partial(ctx)
	if err != nil {
		panic(err.Error())
	}
	for _, b := range q.Queries {
		fmt.Println(b.String())
	}
}

```

yields:

```console
data.partial.partial.example.allow
```

Where as I would have liked to get, maybe:
```console
input.subject.user = "john"
false
```

**Comment by srenatus** [comment]
> Yields:
>
>     input.subject.user = "john"; data.partial.partial.operators.intersects(input.subject.groups, input.resource.acls)
> that is kind of ugly.

But it does exactly what you wanted it to do, doesn't it? 🤔 

I guess there's little reason to move functions when they're not inlined, i.e. calls to them are added to the safe set. Would have to dive into the code to verify that.

**Comment by srenatus** [comment]
:broom: Cleaning up inactive issues -- I hope you've overcome the hurdle by now 😅 Feel free to reopen, or start a new discussion, if this is still troubling you.
