### ISSUE TITLE
Dynamically call a rule in same package

### ISSUE THREAD

**Issue by kamlakant** [open-policy-agent/opa#4008]
I want to perform a simple action. I have N decision rules and 1 main rule in the same package. The main rule processes the input and calls the appropriate decision rule and returns the response, like a `switch` statement. However, when I call a rule dynamically, I get an error:

`1 error occurred: policy.rego:10: rego_recursion_error: rule allow is recursive: allow -> allow`
## Expected Behavior
```
package main

default allow = "deny"

rule_map := {
    "resource1_action1": "rule1",
    "resource2_action2": "rule2"
}

allow = output {
    pair := concat("_", [input.resource, input.action])
    rul := rule_map[pair]
    output := data.main[rul]
}

rule1 = output {
    output := "hello"
}

rule2 = output {
    output := "world"
}

```
For above policy, with input `{
    "action": "action2",
    "resource": "resource2"
}`, main rule `allow` should call `rule2` and return `world`.
## Actual Behavior
Error: `1 error occurred: policy.rego:10: rego_recursion_error: rule allow is recursive: allow -> allow`
## Steps to Reproduce the Problem
https://play.openpolicyagent.org/p/J4wsLHns4X

## Additional Info
Dynamic policy composition works when the main rule and decision rules are in separate packages.
https://blog.styra.com/blog/dynamic-policy-composition-for-opa
Due to some restrictions, I have to keep all the rules in one Rego file.

**Comment by anderseknert** [comment]
I don't think you can do dynamic dispatch to rules like that in the same package, as the compiler will have no way of knowing that you aren't calling the same rule your call came from, which would of course be an infinite recursion. You could put the results of each rule directly in the map, but since each of those rules would need to be evaluated it could be expensive if there are many. 

```rego
package main

default allow = "deny"

rule_map := {
    "resource1_action1": rule1,
    "resource2_action2": rule2
}

allow = output {
	pair := concat("_", [input.resource, input.action])
    output := rule_map[pair]
}

rule1 = output {
    output := "hello"
}

rule2 = output {
    output := "world"
}
```
> Due to some restrictions, I have to keep all the rules in one Rego file.

I'd be interested to learn more about these restrictions!

**Comment by kamlakant** [comment]
@anderseknert Thanks for the clarification. We have a process to publish Rego files which only supports one file for now.

**Comment by anderseknert** [comment]
OK @kamlakant. If the user can upload one file each, perhaps you could have the main router loaded before that? So that the user would only need to supply the `rule_map` and the router would look for this in each file.
