### ISSUE TITLE
Digest mismatch error for custom build bundles

### ISSUE THREAD

**Issue by CristianJena** [open-policy-agent/opa#4009]
Hello, 

I’m working in a project that is using OPA to enforce access control rules and we stumbled upon this behavior.

## Expected Behavior

OPA should start with a signed bundle that contains a valid `data.json` file, even if the bundle is not constructed using `opa build` command but respects all rules from [bundle file format](https://www.openpolicyagent.org/docs/latest/management-bundles/#bundle-file-format).

## Actual Behavior

OPA reports a digest mismatch error for data file when such a bundle is loaded.

## Steps to Reproduce the Problem

We have a service (written in Kotlin) that will receive policies (expressed as JSON) and data (user info, roles etc.). 
This service is translating the JSON policies to REGO, will compose the data file from multiple sources and will construct a signed bundle. The bundle is not created using `opa build` command but programatically.

As the model for `data.json` file became more mature we encountered a digest mismatch error as OPA was not able to load the bundle – reason will be` data.json` file.

We checked the OPA code and found that for structured data (JSON), in the signature validation step, there is a recursive alphabetical sort on properties that is done before calculating the signature value - [here](https://github.com/open-policy-agent/opa/blob/d687e0efb3b454b06b0964da4ba2f97619b3e70b/bundle/hash.go#L94).

From our bundle generator service, the data is kept as a (java) `Object` in memory and the contents are written as a `String` to final file, using the Jackson library. The file signature is calculated based on the string that we obtained from the previous step.

As an example, if a custom client will generate a data file with this format:

```
[
   {
    "property2":"value2",
    "property1":"value1"
   },
   {
    "property3":"value3",
    "property1":"value1"
   }
]
```

At bundle load time, in the validation process, OPA will sort it to calculate its signature, the data will end up like this:

```
[
   {
    "property1":"value1",
    "property2":"value2"
   },
  {
   "property1":"value1",
   "property3":"value3"
  }
]
```

Thus, resulting in a digest mismatch (as the 2 strings do not match so a different SHA is calculated) and bundle load failure – again this is only when we work with signed bundles.

As workaround we write the data sorted by properties now, like this:

```kotlin
val mapper = ObjectMapper()
mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true)
```

We’ve seen that the same sort operation is executed at packing time while using `opa build` command. We assume that this is done for data access performance reasons.

I would have expected that data validation step will be decoupled by any optimisation operation, as OPA can accept arbitrary formatted JSON.

In my opinion this will be a 2-step operation:

1 – Validate file structure for structured data.
2 – Optimise internally the data representation.

Further, this 2 step approach will decouple all OPA clients that are building a bundle using other methods from the input requirements that OPA has (in case there is any kind of data optimisation done beforehand) and will not introduce a dependency on the input format.

Thank you!

## Additional Info

OPA version - 0.32.0

**Comment by ashutosh-narkar** [comment]
After you built your bundle with your bundle generator service, did you consider using `opa sign` to generate a signature for it ? That command generates the signature in a manner that OPA would expect while verifying it. Or are you trying to build and sign w/o any feature OPA provides for bundle creation, signing etc.

**Comment by costimuraru** [comment]
Hey @ashutosh-narkar - on the bundle generation part, we're not using any `opa` tool. It's a (Kotlin) service, that periodically generates the bundle and uploads it.

**Comment by tsandall** [comment]
@costimuraru @CristianJena OPA converts the JSON to a canonical format before calculating the signature partially to support optimization use cases but also because in many cases JSON is sourced from databases and guaranteeing the order of keys is problematic esp. if the JSON gets roundtripped at any point (e.g., depending on the language/serialization library, you'll find different behaviour.) Calculating the signature based on a canonical format avoids that issue.

It's not unreasonable to request that OPA support another signing/verification mode for data files however I'm not convinced that it's going to make it substantially easier to implement the signing side in your bundle service.

Since the bundle docs specify that object properties must be sorted, I don't know if there's anything else to do here. I'm tempted to close this issue.

**Comment by CristianJena** [comment]
Hello @tsandall , thank you for looking into this. Indeed, the docs mentioned that (it seams we missed that part).
