### ISSUE TITLE
Report a coding bug about unused writes

### ISSUE THREAD

**Issue by guodongli-google** [open-policy-agent/opa#4011]
At
https://github.com/open-policy-agent/opa/blob/075344b85018506c7b98cb88ff1130c9e93a3677/ast/index.go#L102-L103
variable `prio` is a local one within the loop, which will be allocated at each iteration of the loop and won't be shared by different loop iterations.
Then at
https://github.com/open-policy-agent/opa/blob/075344b85018506c7b98cb88ff1130c9e93a3677/ast/index.go#L117-L118 `prio++` increases `prio` by 1. However the updated value is never used. As a consequence, all the `prio` values stored in `node.rules` are 0.

A simplified bug reproducer is available at: https://play.golang.org/p/pkIcHmLOmYj, which shows the all the `prio` values are indeed 0.

This issue may be minor since it affects only the priority order.

## Expected Behavior

variable `prio` shall be shared by the loop iterations:
```
var prio int
for idx := range rules {
    ...
}
```

## Additional Info

**Found by static analyzer DeepGo**

**Comment by srenatus** [comment]
The closure passed to WalkRules may be invoked multiple times. The prio would matter then.

**Comment by guodongli-google** [comment]
Thanks for clarification. Marked as FP then.

**Comment by anderseknert** [comment]
Perhaps it could be marked as a false positive in a comment (or whatever DeepGo respects) so that we avoid having this flagged in the future?

**Comment by srenatus** [comment]
Btw thanks for bringing these up, it's much appreciated! 👏

**Comment by guodongli-google** [comment]
Yes the tool will handle the closures better and won't report such FPs. Thanks.
