### ISSUE TITLE
Feature Request: object.union with any number of arguments or new function to support merging N objects

### ISSUE THREAD

**Issue by eliw00d** [open-policy-agent/opa#4012]
## Expected Behavior
object.union takes N arguments

## Actual Behavior
object.union takes 2 arguments

## Steps to Reproduce the Problem
object.union(objectA, objectB, objectC)

## Additional Info

It would be nice if object.union was enhanced to support N arguments or a new function was added that did.

**Comment by srenatus** [comment]
As of now, this would have to be a new builtin, like `object.union_n` taking a set of objects as inputs. Variadic functions are only supported if they return nothing (notably print).

**Comment by srenatus** [comment]
@anderseknert yeah of course! 🤦 ordering matters here.
