### ISSUE TITLE
OPA fails to load bundle when optimizations are enabled

### ISSUE THREAD

**Issue by torsrex** [open-policy-agent/opa#4018]
OPA fails to load bundle when optimizations are enabled.

## Expected Behavior
First running `opa build -O=1 . -e rules/main/allowed` and then `opa run -s -b bundle.tar.gz` should successfully start the server.

## Actual Behavior
The exceptions shown in the image below are thrown:
![image](https://user-images.githubusercontent.com/1499173/141983329-46e447dd-7a30-4bf4-9352-73a2e94c43b8.png)

Here is the corresponding un-optimized rego code:

```
bearer_token(auth_header) = t {
	startswith(auth_header, "Bearer ")
	parts := split(auth_header, " ")
	count(parts) == 2
	t := parts[1]
}
```

And the optimized rego code:

```
bearer_token(__local15__6) = __local17__6 {
	startswith(
		__local15__6,
		"Bearer ",
	)
	split(
		__local15__6, __local57__6,
		" ",
	)
	__local16__6 = __local57__6
	count(__local16__6, __local58__6)
	__local58__6 = 2
	__local17__6 = __local16__6[1]
}
```

Creating the same bundle without optimizations by using `opa build . -e rules/main/allowed` allows the server to be started normally:

![image](https://user-images.githubusercontent.com/1499173/141984560-a7e4ac2e-5b1f-4dbc-ac3a-15f299665a37.png)

## Steps to Reproduce the Problem

* OPA version: 
```
Version: 0.34.2
Build Commit: 9f11f21
Build Timestamp: 2021-11-10T18:33:08Z
Build Hostname: Mac-1636569091949.local
Go Version: go1.17.3
WebAssembly: available
```

**Comment by srenatus** [comment]
Interesting, thanks for bringing this up. I wonder what's going on there.

```rego
	split(
		__local15__6, __local57__6,
		" ",
	)
```
should be
```rego
	split(
		__local15__6, 	" ",
		__local57__6,
	)
```

This could be an issue in the formatter, too, perhaps an unintended side-effect of https://github.com/open-policy-agent/opa/pull/3864 🤔
