### ISSUE TITLE
opa inspect should pretty print by default

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#4021]
The `inspect` subcommand should pretty print by default. Programs that need to consume the output of `inspect` should specify `--format=json` to avoid relying on implicit default behaviour.

To reproduce this problem just build a simple bundle:

x.rego:

```
package foo.bar

p := 7
```

Run `opa build` to produce a bundle:

```
opa build x.rego
```

Then inspect the bundle:

```
opa inspect bundle.tar.gz
```

The fix is simply to update the default format in cmd/inspect.go

**Comment by emilytao** [comment]
I'd like to work on this issue! This will be my first time contributing, so I apologize if I make some mistakes.

**Comment by anderseknert** [comment]
That's great @emilytao! 😃 Feel free to ask about anything you might need help with, here or on the OPA Slack.
