### ISSUE TITLE
opa inspect prints empty namespace for data.json at root

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#4022]
Given the following policy and manifest:

```
$ cat .manifest
{
    "roots": [
        "policy"
    ]
}
```
```
$ cat x.rego
package policy

allow {
    data.foo[x]
}
```

Run OPA build:

```
$ opa build --debug -O=1 -e policy/allow -b .
compile.go:645: optimizer: entrypoint: data.policy.allow
compile.go:646:   partial-namespace: partial
compile.go:647:   disable-inlining: []
compile.go:648:   shallow-inlining: true
compile.go:651:   unknown: data.foo
compile.go:651:   unknown: input
```

Inspect the bundle:

```
$ opa inspect bundle.tar.gz  -f pretty
MANIFEST:
+-------+---------+
| FIELD |  VALUE  |
+-------+---------+
| Roots | partial |
|       | policy  |
+-------+---------+
NAMESPACES:
+-------------+------------------------+
|  NAMESPACE  |          FILE          |
+-------------+------------------------+
|             | /data.json             |
| data.policy | /optimized/policy.rego |
+-------------+------------------------+
```

In the above table, I think that we should at least print `data` instead of an empty namespace for the `/data.json` file.

**Comment by tsandall** [comment]
I also wonder if it would be more natural to flip the FILE and NAMESPACE column ordering. 🤔

**Comment by ashutosh-narkar** [comment]
> I also wonder if it would be more natural to flip the FILE and NAMESPACE column ordering. 

The way I would have read this is the following namespace/package is provided by these files. But I imagine this is subjective.

**Comment by tsandall** [comment]
Yeah, that's fair--I think both are valid, I just happened to want to know what files contributed to what namespaces and so the other direction felt more natural. I'm not sure which use case is more common (maybe it's 50/50). Not a big deal.

**Comment by ashutosh-narkar** [comment]
This would be the output if we made this change

```
MANIFEST:
+-------+---------+
| FIELD |  VALUE  |
+-------+---------+
| Roots | partial |
|       | policy  |
+-------+---------+
NAMESPACES:
+-------------+------------------------+
|  NAMESPACE  |          FILE          |
+-------------+------------------------+
| data        | /data.json             |
| data.policy | /optimized/policy.rego |
+-------------+------------------------+
```

Do you think someone would be confused that the `data` namespace is provided by the `data.json` file ? In your example that file will be empty.

**Comment by tsandall** [comment]
> Do you think someone would be confused that the data namespace is provided by the data.json file ? In your example that file will be empty.

I do not think it's any worse than showing a blank field. One thing that's worth pointing out is that the files providing these namespaces do not provide them exclusively--so saying "data is provided by /data.json" is true but it's probably more accurate to say that it's _partially_ provided. The same will go for any of the Rego files. A namespace would be completed defined by a file in some cases, e.g., if the JSON file contents contain a non-object value (like an array) or when wasm modules are included. Not sure there's anything to be done about this at the moment.

Alternatively I could imagine just representing the namespaces as slash-separated paths implicitly rooted at data:

```
NAMESPACES:
+-------------+------------------------+
|  NAMESPACE  |          FILE          |
+-------------+------------------------+
| /           | /data.json             |
| /policy     | /optimized/policy.rego |
+-------------+------------------------+
```
