### ISSUE TITLE
support parsed_body input for json payloads sent as bytes (pack_as_bytes: true)

### ISSUE THREAD

**Issue by vinhph0906** [open-policy-agent/opa#4027]
I think the opa-envoy-plugin has failed when parser HTTP request body. In my envoy external authorization config set pack_as_bytes: true, then when envoy receives the request(HTTP request with content-type application/json) and sends it to OPA for make decision, this plugin can't parser body of the request. My OPA log looks like
`
{"decision_id":"60e74faa-d8e0-4bac-a8fe-f96e6a5c6944","input":{"attributes":{"destination":{"address":{"socketAddress":{"address":"172.20.0.2","portValue":8000}}},"metadataContext":{},"request":{"http":{"headers":{":authority":"103.245.249.31:8000",":method":"POST",":path":"/people",":scheme":"http","accept":"*/*","accept-encoding":"gzip, deflate, br","authorization":"Bearer ","content-length":"176","content-type":"application/json","postman-token":"80a40911-153b-4a1b-afb9-98e8326d0f59","user-agent":"PostmanRuntime/7.26.8","x-envoy-auth-partial-body":"false","x-forwarded-proto":"http","x-request-id":"b5913712-6a00-4ec4-90b1-08dad73318d7"},"host":"103.245.249.31:8000","id":"17104387768271030378","method":"POST","path":"/people","protocol":"HTTP/1.1","rawBody":"WwogICAgewogICAgICAgICJpZCI6ICIxIiwKICAgICAgICAiZmlyc3RuYW1lIjogIkpvaG4iLAogICAgICAgICJsYXN0bmFtZSI6ICJEb2UiCiAgICB9LAogICAgewogICAgICAgICJpZCI6ICIyIiwKICAgICAgICAiZmlyc3RuYW1lIjogIkphbmUiLAogICAgICAgICJsYXN0bmFtZSI6ICJEb2UiCiAgICB9Cl0=","scheme":"http","size":"176"},"time":"2021-11-17T09:00:50.674801Z"},"source":{"address":{"socketAddress":{"address":"116.110.40.35","portValue":59716}}}},"parsed_body":null,"parsed_path":["people"],"parsed_query":{},"truncated_body":false,"version":{"encoding":"protojson","ext_authz":"v3"}},"labels":{"id":"6db19c6a-04c2-4d48-b7e3-22f87f97c823","version":"0.34.2-envoy-1"},"level":"info","metrics":{"timer_rego_query_compile_ns":247408,"timer_rego_query_eval_ns":988854,"timer_server_handler_ns":10248079},"msg":"Decision Log","query":"data.cls.authz.authorized","requested_by":"","result":true,"time":"2021-11-17T09:00:50Z","timestamp":"2021-11-17T09:00:50.690008029Z","type":"openpolicyagent.org/decision_logs"}
`
I think this issue caused by the envoy sending HTTP body as field `rawbody` and the plugin getting field `body` for parser.

**Comment by srenatus** [comment]
`pack_as_bytes: true` is required for binary payloads -- notably gRPC request bodies.

For plain `application/json` payloads, you could try without, and it should appear in `body` (sent to opa-envoy-plugin), and `parsed_body` (input), respectively.

From the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter): 
> Please note that by default check request carries the HTTP request body as UTF-8 string and it fills the `body` field. To pack the request body as raw bytes, it is needed to set `pack_as_bytes` field to true. In effect to that, the `raw_body` field will be set and `body` field will be empty.

**Comment by srenatus** [comment]
I suppose it would be good if opa-envoy-plugin just checked both `body` and `raw_body` for the `application/json` flow. That way, it wouldn't matter how you've configured it. I think that would make for a good contribution for someone who wants to get their feet we in opa-envoy-plugin's development:

Here, https://github.com/open-policy-agent/opa-envoy-plugin/blob/7b4e500f6b90e884f3a45c9a1aac2d0635adba57/envoyauth/request.go#L119, instead of returning nothing, we'd check the `rawBody` instead -- it's already extracted from the request coming from Envoy and passed to the function doing the work.

**Comment by vinhph0906** [comment]
I think we can change it to 
`			if body == "" {
				if len(rawBody) == 0 {
					return nil, false, nil
				}
				body = string(rawBody)
			}`
and it will work with the least effect.

**Comment by srenatus** [comment]
Yup! Just some added tests and we'd be golden. Is contributing this something you'd be up to? 😃

**Comment by vinhph0906** [comment]
Yeah, It is my honor.

**Comment by srenatus** [comment]
Thanks again for contributing this!

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa-envoy-plugin/pull/296
