### ISSUE TITLE
Provide a Language Server for Rego

### ISSUE THREAD

**Issue by scevallos** [open-policy-agent/opa#4041]
## What part of OPA would you like to see improved?
I would really like to see improvements to the developer experience of writing complex Rego policies (for example: jump to declaration of some element, find all usages of some element, etc.) and some aspects of making these improvements would be facilitated through the production of a [Language Server](https://microsoft.github.io/language-server-protocol/) for Rego.

The [OPA VSCode plugin](https://github.com/open-policy-agent/vscode-opa) currently only provides a small set of features which could be expanded to include [more](https://code.visualstudio.com/api/language-extensions/overview#programmatic-language-features), such as hover information, auto completion, jump to definition, among others through the use of a language server.

The production of a language server would allow use of these features by any tool that can leverage the Language Server Protocol (LSP).

## Describe the ideal solution
A fully-featured Rego language server and its integration within the OPA VSCode plugin.

## Describe a "Good Enough" solution
A Rego language server with a limited set of capabilities (at least [find references](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references) and [go-to definition](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition) as "must-haves")

Nice-to-have: integration with the current OPA VSCode plugin, but that could be done independently.

## Additional Context
Related: I've created [an issue in the IDEA plugin Repo](https://github.com/open-policy-agent/opa-idea-plugin/issues/113) for the same functionality to be added, however it would be done through extending the existing plugin.
It appears that [IntelliJ IDEs do not have 1st party support for LSP](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001627960-IntelliJ-support-for-Language-Server-Protocol-as-a-client-), just a 3rd party plugin.

**Comment by anderseknert** [comment]
That would indeed be awesome! There are a lot of ideas around [improving the OPA/Rego development and debugging experience](https://blog.openpolicyagent.org/open-policy-agent-2021-survey-summary-e749bbd7b824) in the pipeline, so this is a great one to keep in mind in that space!

**Comment by anderseknert** [comment]
The new JetBrains IDE [Fleet](https://www.jetbrains.com/fleet/) seems to provide language integrations via LSP as well:

> Fleet provides a polyglot experience, offering smart support for many languages and technologies out of the box, with support for even more planned via dedicated plugins. **With the help of LSPs you will also be able to use other language services in Fleet.**

**Comment by msvechla** [comment]
Is there any news on this? Having an LSP for rego would really improve the daily workflow of developers working with rego.

**Comment by RmStorm** [comment]
There is this project but it seems to not be fully featured yet: https://github.com/kitagry/regols.

**Comment by anderseknert** [comment]
Cool! I hope we'll see more progress there 😃 Great work so far @kitagry 👍

**Comment by anderseknert** [comment]
I had forgotten that this was still an open issue! While there are still a few parts of the specification not yet supported, [Regal](https://github.com/styrainc/regal) implements most of the LSP features, and reading the original description of this ticket, I'd say it ticks most of the boxes. If there's any specific feature from the LSP spec you find important and that's currently missing, feel free to open an issue in that repo. Closing this as "not planned" as we're not likely to consider this for the OPA project itself, but from any other point of view, it's completed.
