### ISSUE TITLE
how to deploy opa policies where main rego calls other rego files

### ISSUE THREAD

**Issue by zhoupoko2000** [open-policy-agent/opa#4066]
### Organization Name

bank

### Organization Website

sry. cannot

### How is your organization using OPA?

Hello,
our organization is trying to use opa core to architect the policies which limit the objects that are going to be created in kube managed cloud.
I develop opa policy based upon framework in this repo
https://github.com/open-policy-agent/library/tree/master/kubernetes/mutating-admission

my sample code:
https://github.com/zhoupoko2000/opa_test/tree/master

However, when I test it (running opa as server), I do not see the expected result. No patched results are shown though with qualified json input. btw, unit test passes though...
So my question is, can OPA community provide some full and detailed example regarding deploy multiple mutation rego files?
The structure of the regos can be like main rego call other mutation rego rules and mutation rego rules can call other sub rego modules?

below is my test results:

server side:

 ./opa run --server --set=default_decision=library/kubernetes/admission/mutating/main cloud_projects/opa_test/main.rego
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2021-11-30T02:12:09Z"}
{"client_addr":"127.0.0.1:50662","level":"info","msg":"Received request.","req_id":1,"req_method":"POST","req_path":"/","time":"2021-11-30T02:18:25Z"}
{"client_addr":"127.0.0.1:50662","level":"info","msg":"Sent response.","req_id":1,"req_method":"POST","req_path":"/","resp_bytes":103,"resp_duration":1.264123,"resp_status":200,"time":"2021-11-30T02:18:25Z"}

client side:

curl localhost:8181 -i -d @datatestpod.json -H 'Content-Type: application/json'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 30 Nov 2021 02:52:10 GMT
Content-Length: 103

{"apiVersion":"admission.k8s.io/v1beta1","kind":"AdmissionReview","response":{"allowed":true,"uid":""}}

I suppose to see the patches though....

it seems like I have to push everything under main.rego to see the expected result...But this is not how I plan to structure my policy files as there will be many mutation policies...

 

### Source Code Link (optional)

https://github.com/zhoupoko2000/opa_test/tree/master

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by anderseknert** [comment]
Having many policy files is fine, but you'll need to either point OPA to each one of them when you start the process, or just provide the entire directory. So in your case you could either do:

```
./opa run --server --set=default_decision=library/kubernetes/admission/mutating/main cloud_projects/opa_test/main.rego cloud_projects/opa_test/main.rego cloud_projects/opa_test/mutate.rego
```
Or, simpler, all policies in the directory.
```
./opa run --server --set=default_decision=library/kubernetes/admission/mutating/main cloud_projects/opa_test/
```

**Comment by zhoupoko2000** [comment]
Thanks a lot. this works!
