### ISSUE TITLE
opa fmt: format statements, not only complete modules

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4104]
## What part of OPA would you like to see improved?

`opa fmt` could be more versatile, and used in different ways if it could work on structures less than a module, such as statements

## Describe the ideal solution

```
$ `echo 'xs := {1,     3,2,3,4}' | opa fmt`
xs := {1, 2, 3, 4}
```

## Additional Context

I'd like to wire this into our live-block scripts, so any code blocks on the website would automatically be formatted properly. Last time, @anderseknert had done a manual sweep, d6133a27656bb368d67809a8789c4d6778346086.

**Comment by anderseknert** [comment]
Closing in favor of #4508, where we'll try to compile all ideas for the next iteration of `opa fmt` (and where this is included).
