### ISSUE TITLE
Rich Metadata

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#4113]
In [v0.28.0](https://github.com/open-policy-agent/opa/releases/tag/v0.28.0) we added support for schema annotations on rules and packages. Schema annotations let authors declare the schema of input and data base documents that inform the type checker and provide better error messages. Building on the annotation support, we would like to expand OPA to support a richer set of metadata on policies. Common examples include:

* Generic fields like `title`, `description`, `authors`, `organizations`, `license`, etc. (#4331)
* Example inputs (each with title, description, URL or inline value, etc.)
* Decision paths/entrypoints (#3459)
* Related resources (URLs) (#4331)
* Custom attributes (this would be a catch all for user-specific extensions) (#4331)

Expanding OPA to support richer metadata would mean:

* [x] Expand the parser and ast types to support these new metadata fields
* [x] Documenting supported metadata fields
* [x] Surfacing metadata inside of tooling like `opa inspect` (#4387)
* [x] Exposing metadata to the evaluator via a mechanism like `self` (#4396)

**Comment by danielvrog** [comment]
Multiple tools above OPA are currently using tailor made metadata fields, including **unique IDs for rules** besides titles. This allows better governance (one-offs, custom severity, aggregated reporting), customization of CI pipelines and visibility. 
References:

- [Regula](https://regula.dev/examples/writing-a-rule.html#regula-metadata) 
- [Terrascan](https://github.com/accurics/terrascan/blob/master/docs/usage/command_line_mode.md?plain=1#L277)

**Comment by mikouaj** [comment]
@tsandall is v0.38 release likely to happen in March 2022 ?
i'm looking forward to use rich metadata capabilities in my project.

**Comment by anderseknert** [comment]
Yes, next week most likely.

**Comment by tsandall** [comment]
This is done now.
