### ISSUE TITLE
Add ability to specify input document via command line

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#413]
`opa run --eval` evaluates a query provided via the command line. Inputs currently need to be defined at `data.repl.input`. It would be nice if we could pass input directly via some command line argument, e.g., `opa run -e '...' --input='{"foo":"bar"}'`.

**Comment by tsandall** [comment]
This is handled as part of the `eval` subcommand.

**Comment by salahalsaleh1993** [comment]
Could you please provide an example of how to pass the input via command line with `opa eval` ?

**Comment by tsandall** [comment]
@salahalsaleh1993 there are two options today: 

1. --input or -i specifies a file to load the input document from
2. --stdin-input or -I tells opa eval to read the input document from stdin

This is documented in the --help output for the eval subcommand.

**Comment by salahalsaleh1993** [comment]
Thanks @tsandall ! I was not aware of how to use that. It's working now.
