### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#4132]
We currently have a [handful of compile-time checks](https://github.com/open-policy-agent/opa/issues?q=is%3Aopen+is%3Aissue+label%3Alint) that we'd like to enforce (but can't because they could break existing policies.) An alternative would be to roll out these checks as linting steps that are opted into by users. As a starting point we could expose a flag on the `opa check` and `opa build` commands that users could opt into (e.g., `opa check --strict .`) In the future, we could introduce an opt-in import (e.g., `import future.strict`)

The set of linting rules can be pulled from the lint label linked above.

**Comment by anderseknert** [comment]
Closing in favor of https://github.com/open-policy-agent/opa/issues/3218 since that one has quite a few watchers. Will update that ticket description to include the information from here.
