### ISSUE TITLE
Migrating infracost/setup-opa to open-policy-agent

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4141]
@tim775 and @alikhajeh1 have created a [Github Action to setup OPA](https://github.com/infracost/setup-opa) that allows a simpler setup of OPA in a Github Actions Workflow. It's fixing a [year-old (on the day, almost) issue](https://github.com/open-policy-agent/opa/issues/3014) we've had, this is long-awaited feature of the OPA ecosystem. @tim775 has agreed to help maintaining the action code when it's in the open-policy-agent org.

To move forward we need to:

* [x] Hold a vote amongst the OPA maintainers (the process is outlined in the GOVERNANCE.md file).
* [x] Create an setup-opa-maintainers team on GitHub and add @tim775 to the new team.
* [x] Transfer the infracost/setup-opa repo into the open-policy-agent organization
* [x] Ensure that DCO check is enabled on the repo
* [x] Add a security notice on the action repo pointing back to SECURITY.md

The project is currently using GHA for CI and does not have any secrets configured (other than the standard github token) so migration should be simple.

@tim775 can you mention anyone else who should be added to the maintainer team for the action?

@ritazh @maxsmythe @shomron cc-ing you to vote on this like we've done in the past for GK, conftest, etc.

**Comment by tim775** [comment]
Please make @aliscott a maintainer also.  Cheers.

**Comment by tsandall** [comment]
+1

**Comment by shomron** [comment]
+1

**Comment by maxsmythe** [comment]
This SGTM (+1 vote)

Thanks for doing this!

**Comment by ritazh** [comment]
+1
Thanks for working on this! 🙇

**Comment by tsandall** [comment]
@srenatus @tim775 I've created the new `setup-opa-maintainers` team. Once you initiate the repo transfer we can accept it and finish this off!

**Comment by tim775** [comment]
I'm not able to transfer to `open-policy-agent`, I get the error `You don’t have the permission to create public repositories on open-policy-agent`

I think it may be better for you to create a fork in open-policy-agent.  The action is already being used in a few actions and I'm not sure if transferring will cause those to break.  If you create the fork I will update infracost/setup-opa README directing people to open-policy-agent, then archive it.

What do you think?

**Comment by anderseknert** [comment]
That's awesome @tim775 ! Yeah, we'd like be the first to break should the redirect not work ;)

https://github.com/open-policy-agent/opa/blob/abc353be91385f591881d9bf5411da9f60066711/.github/workflows/pull-request.yaml#L286-L287

Thank you for this 😃

**Comment by srenatus** [comment]
This is done, thanks everyone! 🥳 🎈
