### ISSUE TITLE
Built-ins: add indexof_n()

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4155]
## What part of OPA would you like to see improved?

Currently looking at a policy where it would be useful to get all the indexes of a specific substring or character from a string.

## Describe the ideal solution

```rego
str := "something here and something there"

indexof_n(str, "thing") == [4, 23]
```

## Additional Context

This is currently easy to do with a single character, since we can just split the string on `""` and iterate over the result, but searching for strings makes it trickier.

`regex.find_n` and `regex.find_all_string_submatch_n` doesn't work for this, since they return the actual substrings and not their position.

**Comment by shuheiktgw** [comment]
Let me work on this issue as my first contribution to OPA 🙏

**Comment by anderseknert** [comment]
@shuheiktgw sure!
