### ISSUE TITLE
Missing fields in status log payload

### ISSUE THREAD

**Issue by donovan-lampa** [open-policy-agent/opa#4157]
## Short description 
We're receiving some status logs that contain bundles that do not have an active revision, and the timestamps contained in the bundle all are from the start of CE.

Below is an example of the params received from an opa status post request made to our control plane service.

```
{"labels"=>
  {"id"=>"eaf5f54b-f11b-4283-ac4f-6e7853341e5a",
   "serviceNames"=>"example",
   "version"=>"0.35.0"},
 "bundles"=>
  {"example_bundle_1"=>
    {"name"=>"example_bundle_1",
     "last_successful_activation"=>"0001-01-01T00:00:00Z",
     "last_successful_download"=>"0001-01-01T00:00:00Z",
     "last_successful_request"=>"0001-01-01T00:00:00Z",
     "last_request"=>"0001-01-01T00:00:00Z"},
   "example_bundle_2"=>
    {"name"=>"example_bundle_2",
     "last_successful_activation"=>"0001-01-01T00:00:00Z",
     "last_successful_download"=>"0001-01-01T00:00:00Z",
     "last_successful_request"=>"0001-01-01T00:00:00Z",
     "last_request"=>"0001-01-01T00:00:00Z"},
   "example_bundle_3"=>
    {"name"=>"example_bundle_3",
     "active_revision"=>"2021-12-17T16:30:45.124Z",
     "last_successful_activation"=>"2021-12-20T15:14:44.49848702Z",
     "last_successful_download"=>"2021-12-20T15:14:44.494282898Z",
     "last_successful_request"=>"2021-12-20T15:14:44.494282898Z",
     "last_request"=>"2021-12-20T15:14:44.494282898Z",
     "metrics"=>
      {"timer_rego_load_bundles_ns"=>5614931,
       "timer_rego_module_compile_ns"=>3789899,
       "timer_rego_module_parse_ns"=>1073538}},
   "example_bundle_4"=>
    {"name"=>"example_bundle_4",
     "last_successful_activation"=>"0001-01-01T00:00:00Z",
     "last_successful_download"=>"0001-01-01T00:00:00Z",
     "last_successful_request"=>"0001-01-01T00:00:00Z",
     "last_request"=>"0001-01-01T00:00:00Z"},
   "example_bundle_5"=>
    {"name"=>"example_bundle_5",
     "last_successful_activation"=>"0001-01-01T00:00:00Z",
     "last_successful_download"=>"0001-01-01T00:00:00Z",
     "last_successful_request"=>"0001-01-01T00:00:00Z",
     "last_request"=>"0001-01-01T00:00:00Z"}},
 "plugins"=>
  {"bundle"=>{"state"=>"NOT_READY"},
   "decision_logs"=>{"state"=>"OK"},
   "discovery"=>{"state"=>"OK"},
   "status"=>{"state"=>"OK"}}}
```

It appears that all bundles have loaded successfully on the instance since it's taking traffic and rendering policy evaluations, but I'm not sure how to confirm that with OPA in its SDK mode since we don't have access to the normal opa-as-server http routes in the SDK

Details about our deployment:
* Running on k8s pods in aws
* OPA v 0.35.0
* Running OPA as SDK bundled into a custom go bin, but no modifications to the status plugin have been made

## Steps To Reproduce

This one's tricky. It does seem to be consistently happening, but we're not sure how to reproduce it quite yet.

It does seem to be happening across multiple deployed instances (each of which potentially load different bundles), and doesn't seem to be consistent between status log post requests.

## Expected behavior
Loaded bundles have their status reported correctly.

**Comment by anderseknert** [comment]
Thanks for reporting this @donovan-lampa

I think the plugin status object might be a good hint here: `"bundle"=>{"state"=>"NOT_READY"}` 

But it's definitely not clear how the server could be operational in that state.

I think a good next step in order to try and figure out what's going on here is if you'd be able to temporarily turn on logging in the OPA SDK. The default logger is (IIRC) a NoOpLogger since nobody likes libraries that logs :) But you can change this when you instantiate OPA:

```go
logger := logging.New()
logger.SetLevel(logging.Info)
	
opa, err := sdk.New(ctx, sdk.Options{
	Config: bytes.NewReader(config),
	Logger: logger,
})
```
If the errors persist and the logs don't provide any clues, we could try the `logging.Debug` level.. though it's quite noisy of course.

**Comment by donovan-lampa** [comment]
Thanks @anderseknert you're totally right, i missed that. Now i'm wondering if this status log was triggered while the async bundle update process was also in flight 🤔 .

I'll work on gathering some logs to see if I can prove that hypothesis.

**Comment by anderseknert** [comment]
@donovan-lampa any discoveries made so far? 🙂

**Comment by donovan-lampa** [comment]
@anderseknert sorry for the radio silence! 

I actually tried recreating this, but wasn't able to. We also haven't seen the error recently, so I'll close this out for now and re-open if we see it come up again.
