### ISSUE TITLE
How can I check validity of the JWT token?

### ISSUE THREAD

**Issue by hauleth** [open-policy-agent/opa#417]
From documentation I see that `io.jwt.decode` accepts only 1 argument however JWT documentation also requires "secret key" required for validation. Is there any way to check if given JWT is valid one or OPA will happily accept everything as valid?

**Comment by tsandall** [comment]
The existing `io.jwt.decode` built-in does not verify the signature cryptographically. Doing so would require having the secret key in OPA which raises security questions.

If offloading signature verification would be helpful, we can add a built-in to do this but it would be on the deployment to ensure that the key doesn't get leaked, gets rotated, etc.

**Comment by hauleth** [comment]
@tsandall it would be great when combined with #416 Vault integration.

I have also [mentioned](https://gitter.im/hashicorp-nomad/Lobby?at=5995f5b3ee5c9a4c5fcfe80d) that project as an idea for Hashicorp's Nomad policy management.

**Comment by hauleth** [comment]
@tsandall also if there would be access to environment variables in OPA policy description then this could be place for storing secret key. Because without verification JWT functionality is quite useless as anyone can now check for everything they want.

**Comment by hauleth** [comment]
@tsandall I think that HS* family is most popular one, however there are ready to use libraries that allow verification (list on https://jwt.io) and this seems promising https://github.com/dgrijalva/jwt-go

But remember to https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by tsandall** [comment]
@hauleth thanks for reaching out. I've created two separate issues to track the improvements required. If you think this should be re-opened for some reason, go ahed and do so or just comment. Thanks!
