### ISSUE TITLE
incorrect coverage when using `input`

### ISSUE THREAD

**Issue by ekcs** [open-policy-agent/opa#4170]
## Short description 
OPA coverage can be incorrect in the case of referencing `input`. In the playground screen shot, lines 4, 8, and 12 should all be green, but line 12 is red. The same bug is observed in Styra DAS, so it is likely OPA issue rather than playground or DAS. OPA v0.35.0.

![Screen Shot 2021-12-25 at 3 17 41 PM](https://user-images.githubusercontent.com/13672872/147395339-1c73c022-e43c-4279-87f3-8f742cc9b362.png)

## Steps To Reproduce

Run coverage on:
input: `{"a": 1}`
policy:
`package play

a {
  false
}

a {
  1 == 0
}

a {
  input.a == 0
}

b {
  input.a == 1
}`

See that line 12 is not covered.

## Expected behavior

lines 4, 8, 12 should all be covered.

**Comment by srenatus** [comment]
This is rule indexing in action. Line 12 is not evaluated because it cannot match based on that input. I suppose it's easy to be mislead by that, but the missing coverage kind of reflects reality, I suppose.

What do you think?

**Comment by anderseknert** [comment]
@srenatus just curioys, why can't the indexer come to the same conclusion when constants are compared? 🤔

**Comment by srenatus** [comment]
The indexer tries to figure out the subset of rules that are relevant given some `input`. For the first two rule bodies, the value of `input` doesn't make a difference, so they're always included in the index lookup result.

**Comment by srenatus** [comment]
While it's confusing, it's also very uncommon to have world policies with bodies that always fail. It this doesn't seem necessary to optimise that case. 💭

**Comment by anderseknert** [comment]
If you by "real world" mean policies deployed to production, then sure. I don't think that's where the coverage feature is most likely to be used or useful though. It shines precisely in the type of context the Rego Playground (or DAS, or other editor integrations) provides, and in that type of exploratory/learning environment, using constant conditions for testing things is in my experience **very** common.

**Comment by srenatus** [comment]
> in that type of exploratory/learning environment, using constant conditions for testing things is in my experience very common.

Granted, what would you suggest follows for the indexer behaviour? 💭

**Comment by anderseknert** [comment]
I'm not sure to be honest—obviously the coverage reported should show the actual paths traversed, so the current behavior isn't wrong, only unintuitive and confusing. I suppose it would be useful to have an "advanced options" dropdown in the Playground that would allow things like the equivalent of `opa eval --disable-indexing`, `--disable-early-exit`, et. al... as that would at least give you a chance to tap into the mind of the evaluator and the indexer :)

**Comment by srenatus** [comment]
> I suppose it would be useful to have an "advanced options" dropdown in the Playground

I guess so....but I'd also think that if the PG's simple approach is insufficient, what's a natural next thing to use to dig in? The VSCode extension? (If so, does it expose those advanced options?) Would the next step be `opa eval`? 🤔

**Comment by anderseknert** [comment]
Removing the bug label, as things work as expected, albeit perhaps not as _expected_ :) @ekcs would improved docs on coverage be helpful?

**Comment by ekcs** [comment]
Ah super appreciate the clarification @srenatus and @anderseknert !
I understand now it is working as designed. Yes a little note box in the doc would be helpful! Here? https://www.openpolicyagent.org/docs/latest/policy-testing/#coverage

I guess the situation is analogous to how in C you can get different coverage results depending on compiler optimization settings.

For the purpose of learning, debugging, and understanding, I think the un-optimized coverage would be very helpful. Is there an option to disable rule-indexing in OPA? Then playground and DAS can offer that version of coverage for learning or debugging. (There is this [optimization level](https://www.openpolicyagent.org/docs/latest/policy-performance/#optimization-levels), but I think that's controlling rule-rewriting.)

**Comment by anderseknert** [comment]
Yes, `opa eval` has a `--disable-indexing` flag which will let you do that. I don't think it's possible to pass via the REST API, so it wouldn't currently be possible to do in the Rego Playground, but I agree it might be a useful option to consider for the future.

I'll add a note in the docs where you suggested.
