### ISSUE TITLE
docs: Envoy primer docs look broken in input dropdowns

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4186]
Something's not right with the style in the [Example input](https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-input) section in the Envoy primer docs.

![Screenshot 2022-01-05 at 16 55 32](https://user-images.githubusercontent.com/510711/148249291-d0ad55a4-c493-4323-a656-0621c6e2710a.png)

**Comment by srenatus** [comment]
Good find. Probably got hosed when updating Hugo? 🤔

**Comment by anderseknert** [comment]
Yeah, could be - I guess it could have been this way for a long time though, given how these aren't visible unless one clicks.

**Comment by anderseknert** [comment]
Fixed by #4199
