### ISSUE TITLE
Getting 403 Forbidden Response When Exercising OPA Policy Following the OPA Tutorial: Standalone Envoy

### ISSUE THREAD

**Issue by yeanchiat** [open-policy-agent/opa#4212]
## Short description
Following [OPA Tutorial: Standalone Envoy](https://www.openpolicyagent.org/docs/latest/envoy-tutorial-standalone-envoy/) and build the use case on AWS EKS instead of using Minikube, as shown in the tutorial.

## Expected behavior
Everything works fine as shown from the tutorial. In fact, last year December we have built it on EKS as well following the steps, everything worked out fine (please refer to the screenshot). 

![image](https://user-images.githubusercontent.com/76905501/149061813-a9f985de-5128-4535-94c2-ed307dae7621.png)

## Actual behavior
However, last week, we tried to rebuild the use case all over again, and this time when we exercise the OPA policy. it returns 403 Forbidden. Check through several times the steps taken and configuration, everything seems to be similar to those in OPA Tutorial.

![image](https://user-images.githubusercontent.com/76905501/149061963-72c937f5-b21a-4c4b-b79a-c9f868b62f1f.png)

## Logs
Logs from Envoy proxy container

`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:205] initializing epoch 0 (hot restart version=10.200.16384.127.options=capacity=16384, num_slots=8209 hash=228984379728933363 size=2654312)`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:207] statically linked extensions:`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:209]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log`
[`2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:212]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:215]   filters.listener: envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:218]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:220]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:222]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.zipkin`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:225]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:228]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
`
`[2022-01-12 02:46:54.911][1][info][main] [source/server/server.cc:234] buffer implementation: old (libevent)
`
`[2022-01-12 02:46:54.917][1][info][main] [source/server/server.cc:281] admin address: 0.0.0.0:8001
`
`[2022-01-12 02:46:54.917][1][info][config] [source/server/configuration_impl.cc:50] loading 0 static secret(s)
`
`[2022-01-12 02:46:54.917][1][info][config] [source/server/configuration_impl.cc:56] loading 1 cluster(s)`
`[2022-01-12 02:46:54.918][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:137] cm init: all clusters initialized
`
`[2022-01-12 02:46:54.918][1][info][config] [source/server/configuration_impl.cc:60] loading 1 listener(s)
`
`[2022-01-12 02:46:54.919][1][info][config] [source/server/configuration_impl.cc:85] loading tracing configuration`
`[2022-01-12 02:46:54.919][1][info][config] [source/server/configuration_impl.cc:105] loading stats sink configuration`
`[2022-01-12 02:46:54.919][1][info][main] [source/server/server.cc:462] all clusters initialized. initializing init manager`
`[2022-01-12 02:46:54.919][1][info][config] [source/server/listener_manager_impl.cc:1006] all dependencies initialized. starting workers`
`[2022-01-12 02:46:54.919][1][info][main] [source/server/server.cc:478] starting main dispatch loop`
`[2022-01-12 03:01:54.922][1][info][main] [source/server/drain_manager_impl.cc:63] shutting down parent after drain`

Logs from OPA Container

`  "bundles": {
    "default": {}
  },
  "decision_id": "cf9202ee-bf67-4791-ba01-eb4ec8cef005",
  "input": {
    "attributes": {
      "destination": {
        "address": {
          "Address": {
            "SocketAddress": {
              "PortSpecifier": {
                "PortValue": 8000
              },
              "address": "100.64.57.212"
            }
          }
        }
      },
      "request": {
        "http": {
          "headers": {
            ":authority": "internal-a6060c66a2183489c973129bcd82819d-1771550755.eu-west-1.elb.amazonaws.com:8080",
            ":method": "GET",
            ":path": "/people",
            "accept": "*/*",
            "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ3Vlc3QiLCJzdWIiOiJZV3hwWTJVPSIsIm5iZiI6MTUxNDg1MTEzOSwiZXhwIjoxNjQxMDgxNTM5fQ.K5DnnbbIOspRbpCr2IKXE9cPVatGOCBrBQobQmBmaeU",
            "user-agent": "curl/7.79.1",
            "x-forwarded-proto": "http",
            "x-request-id": "081778e5-f03f-4f18-8fde-46d7c392ee50"
          },
          "host": "internal-a6060c66a2183489c973129bcd82819d-1771550755.eu-west-1.elb.amazonaws.com:8080",
          "id": "14835809428344775996",
          "method": "GET",
          "path": "/people",
          "protocol": "HTTP/1.1"
        }
      },
      "source": {
        "address": {
          "Address": {
            "SocketAddress": {
              "PortSpecifier": {
                "PortValue": 40482
              },
              "address": "100.64.18.234"
            }
          }
        }
      }
    },
    "parsed_body": null,
    "parsed_path": [
      "people"
    ],
    "parsed_query": {},
    "truncated_body": false,
    "version": {
      "encoding": "encoding/json",
      "ext_authz": "v2"
    }
  },
  "labels": {
    "id": "229f7426-5c1c-4d8e-9a51-2a8a8d78ec36",
    "version": "0.35.0-envoy-8"
  },
  "level": "info",
  "metrics": {
    "timer_rego_query_eval_ns": 177910,
    "timer_server_handler_ns": 312658
  },
  "msg": "Decision Log",
  "path": "envoy/authz/allow",
  "requested_by": "",
  "result": false,
  "time": "2022-01-12T04:06:42Z",
  "timestamp": "2022-01-12T04:06:42.834479287Z",
  "type": "openpolicyagent.org/decision_logs"
}`

**Comment by ashutosh-narkar** [comment]
The issue seems to be the JWTs assigned to Alice and Bob in the example expired on 1/1/2022. As a result the `is_token_valid` rule fails. Feel free to open a PR if you'd like.

**Comment by yeanchiat** [comment]
> The issue seems to be the JWTs assigned to Alice and Bob in the example expired on 1/1/2022. As a result the `is_token_valid` rule fails. Feel free to open a PR if you'd like.

Hi @ashutosh-narkar, thanks for the reply. I am actually glad to know that the token is expired instead of some configuration mistakes from our side :)
When you say open a PR, do you mean generating a new token and raise a PR to update it? Sorry I'm not too familiar with this, appreciate if you can provide more guidance on this matter.

**Comment by yeanchiat** [comment]
@anderseknert sure yeah! Thanks for pointing me at the right direction. My colleague is working on it and will raise a PR soon :)

**Comment by anderseknert** [comment]
Great! :)
