### ISSUE TITLE
Spinnaker policy doesn't affect existing pipelines

### ISSUE THREAD

**Issue by Asiya-Yunusa** [open-policy-agent/opa#4213]
I have created policies using OPA on Spinnaker but it only works for new pipelines when they are being saved. It doesn't affect existing pipelines if they don't need editing. Please is there a way to create a policy to affect both new and existing pipelines.
Thank you.

**Comment by anderseknert** [comment]
Hi @Asiya-Yunusa! 👋 

I haven't used Spinnaker, but OPA has no notion of whether it's called for new pipelines or existing ones. Scanning the Spinnaker [docs](https://docs.armory.io/armory-enterprise/armory-admin/policy-engine/policy-engine-use/), I don't see any obvious way to scan existing resources/pipelines. "Runtime" checks sounds promising but doesn't seem to be what you want when reading the details. I'd suggest you check with Armory or in one of the Spinnaker community channels as this isn't really an issue with OPA, and as far as I know we have not been involved in building that integration.

**Comment by Asiya-Yunusa** [comment]
@anderseknert okay, thank you. I'll check with Armory.

**Comment by anderseknert** [comment]
Great! I'll close this issue for now then 👍
