### ISSUE TITLE
Unable to load multiple bundles due to merge error

### ISSUE THREAD

**Issue by langes2BE3** [open-policy-agent/opa#4214]
OPA version: 0.36 (but visible since at least 0.34)

We are trying to load data bundles from multiple locations. 

For repro scenario let's use two simple bundles:
| test |
test1.tar.gz:
`.manifest`
`test1/data.json`
test2.tar.gz:
`.manifest`
`test2/data.json`
with the manifests set to `{"roots":["test1"]}` and `{"roots":["test2"]}` accordingly.

The bundles do not have any overlapping roots.

When trying to load them via `opa run -s test1.tar.gz test2.tar.gz` we get the error `error: load error: 1 error occurred during loading: .\test2.tar.gz: merge error`.

While digging into the code we saw that line `537` in `bundle/bundle.go` 
``` go
// For backwards compatibility always write to the old unnamed manifest path
// This will *not* be correct if >1 bundle is in use...
if err := bundle.insertData(legacyManifestStoragePath, metadata); err != nil { // <== This appears to be the problem
	return bundle, errors.Wrapf(err, "bundle load failed on %v", legacyRevisionStoragePath)
}
```
adds the revision to the bundle representation. This throws off the `hasConflicts()` and `merge()` code and produces the above error. While commenting out these lines solves our problem we find it hard to judge on the implications.

Also, the same happens when we load the bundles from external services (e.g. BlobStorage via config file). Is there something fundamentally wrong in the way we create the bundles or try to load them? Is it at all possible to load multiple bundles?

Thanks and best regards,
Sebastian
[test1.tar.gz](https://github.com/open-policy-agent/opa/files/7856067/test1.tar.gz)
[test2.tar.gz](https://github.com/open-policy-agent/opa/files/7856068/test2.tar.gz)

**Comment by ashutosh-narkar** [comment]
Try running with the `-b` flag to load paths as bundle files. `opa run -s -b test1.tar.gz test2.tar.gz` should work.

**Comment by langes2BE3** [comment]
I'm truly humbled about this stupid mistake. Sorry.
