### ISSUE TITLE
docs: Grammar section missing in keyword, and some iteration construct

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4216]
https://www.openpolicyagent.org/docs/latest/policy-reference/#grammar

The new `in` keyword should be added, and `some` should be updated to include it being used for iteration.

**Comment by srenatus** [comment]
While we're at it, let's fix `expr-call` to `var [ "." var ] "(" [ expr { "," expr } ] ")"`.

**Comment by srenatus** [comment]
🙈 https://github.com/open-policy-agent/opa/tree/main/misc/syntax there's more to be done here.

**Comment by tsandall** [comment]
@srenatus is this being tackled as part of #4359? If so, let's add a Fixes line to the commit.
