### ISSUE TITLE
Expose capabilities.json through CLI command

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4236]
For external tooling, It would be a nice if the [capbilities.json](https://github.com/open-policy-agent/opa/blob/main/capabilities/capabilities.go) was easily retrievable "offline" through a command line argument—either a new one or retrofitted inside something like `opa inspect`, e.g:

```shell
opa inspect --capabilities
```
To print the capabilities JSON from the currently running version, or
```shell
opa inspect --capabilities v0.29.0
```
To print capabilities from a past version.

**Comment by srenatus** [comment]
💭 Since we've got an `opa inspect` already, perhaps `opa capabilities` would be a good one-argument command? I wouldn't want to lump this together with bundle inspection...

**Comment by anderseknert** [comment]
That works well for me.. just thinking of avoiding "sub-command explosion" :) And "inspect" kinda makes sense for anything that inspects the state of something, but `opa capabilities` is fine 👍

**Comment by srenatus** [comment]
Or `opa inspect capabilities`? We've only just unhid `opa inspect` so we could turn it into `opa inspect bundle`...
