### ISSUE TITLE
Seeing lots of TLS handshake errors in OPA logs 

### ISSUE THREAD

**Issue by superff** [open-policy-agent/opa#4243]
thanks
## Short description 

I am  seeing lots of 

2022/01/19 00:27:41 http: TLS handshake error from 172.16.65.122:26835: EOF
2022/01/19 00:27:21 http: TLS handshake error from 172.16.66.13:7628: EOF
2022/01/19 00:27:21 http: TLS handshake error from 172.16.65.227:41959: EOF
2022/01/19 00:27:21 http: TLS handshake error from 172.16.64.118:40032: EOF
2022/01/19 00:27:21 http: TLS handshake error from 172.16.65.248:36861: EOF
2022/01/19 00:27:22 http: TLS handshake error from 172.16.64.4:18399: EOF
2022/01/19 00:27:23 http: TLS handshake error from 172.16.64.55:53269: EOF
2022/01/19 00:27:23 http: TLS handshake error from 172.16.65.122:9829: EOF
--

TLS handshake errors and couldnt figure out what is the root cause

**Comment by anderseknert** [comment]
Hi Fred. That seems very random, and it's difficult to say what might cause that without more information. Have you identified the clients calling OPA from those IP addresses?

Are these OPAs deployed in Kubernetes? TCP probes configured for liveness checks rather than HTTP, maybe?

**Comment by anderseknert** [comment]
Moved to discussion https://github.com/open-policy-agent/feedback/discussions/101
