### ISSUE TITLE
Expose status code of last bundle download request

### ISSUE THREAD

**Issue by jkbschmid** [open-policy-agent/opa#4259]
## What part of OPA would you like to see improved?
I'd like to improve the Status API endpoint (/v1/status).

We would like to decide locally whether an OPA instance is OK or not. To achieve this, we'd like to use the newly added `/v1/status` API. Depending on the specific error when downloading bundles, we'd like to automatically perform certain actions (e.g. restart). One piece of information that is useful here is the status code OPA receives when trying to download a bundle (e.g. 500 or 403). 

At the moment, [this bundle struct](https://github.com/open-policy-agent/opa/blob/8a1aab376f0dc7428e3a393924814fbde0fc6498/plugins/bundle/status.go#L22) is being returned for every bundle as part of the `/v1/status` output.

## Describe the ideal solution
In addition to the time of the lastRequest to download a bundle, the status endpoint also returns the status code of this request.
I'm wondering if the [Code field](https://github.com/open-policy-agent/opa/blob/8a1aab376f0dc7428e3a393924814fbde0fc6498/plugins/bundle/status.go#L29) could be used to that end, since it currently only ever contains "bundle_error" or the empty string (correct my if I'm wrong).

## Describe a "Good Enough" solution
From a users perspective, it would be sufficient to keep the pre-existing [Message field](https://github.com/open-policy-agent/opa/blob/8a1aab376f0dc7428e3a393924814fbde0fc6498/plugins/bundle/status.go#L30) stable. That way, users could derive the error code (e.g. 500) from the error message (e.g. "internal server error"). 
However, this is very brittle and obviously not good coding style.

## Additional Context
This is what is currently being returned from the status API:
```
curl localhost:9888/v1/status
{
  "result": {
    "labels": {
      "id": "db305188-a0f3-421c-afbb-eb301f546e42",
      "version": "0.36.0"
    },
    "bundles": {
      "myBundle": {
        "name": "myBundle",
        "last_successful_activation": "0001-01-01T00:00:00Z",
        "last_successful_download": "0001-01-01T00:00:00Z",
        "last_successful_request": "0001-01-01T00:00:00Z",
        "last_request": "2022-01-20T16:10:22.093047Z",
        "code": "bundle_error",
        "message": "server replied with HTTP 400",
        "metrics": {
          "timer_bundle_request_ns": 216062406
        }
      }
...
```

Thank you!

**Comment by anderseknert** [comment]
Seems reasonable to me. 

I suppose adding a new field like "http_status" for this purpose would be the non-breaking solution, given how any external system currently parsing the status checking for `"code": "bundle_error"` would break if we changed the value, or even type, of this attribute.

**Comment by tsandall** [comment]
I agree with @anderseknert here. Let's just add another field to the status message to capture the HTTP status code in case of error. That seems like a simple change that preserves compatibility and gives clients wanting that extra bit of information a nice programmatic interface.

**Comment by jkbschmid** [comment]
Awesome! :)
I opened https://github.com/open-policy-agent/opa/pull/4328.
It would be great if you could have a look.
