### ISSUE TITLE
Improve policy testing support

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#428]
OPA should provide a way for policy authors to implement unit tests. This is particularly useful for helper libraries that may end up being used by a large number of higher-level policies.

It's possible to accomplish this today, but by introducing a *test runner* into OPA we could:

- Provide consistent failure messages and result ordering
- Discover and run all tests cases in the suite
- Provide convenient out-of-the-box testing support (e.g., just `opa test *`)
- Pave way for better tooling around coverage, performance analysis, etc.

**Comment by tsandall** [comment]
Proposed convention...

- Tests are implemented as rules that define test result docs. If any test doc is NOT `true` the test run 'failed'.
- Runner iterates ASTs of supplied Rego files and runs all tests in order.
- If any tests fail, runner exits with non-zero status.
- Test runner can output results as JSON for easy consumption

E.g.,

**my-app-authz.rego**:

```
package myapi.authz

default allow = false

allow { ... }
```

**my-test.rego**:

```
package myapi.authz

test_allow_bob {
   allow with input as {"user": "bob"}
}

test_deny_alice {
   not allow with input as {"user": "alice"}
   1 = 2 # this is never true; test will fail
}

# opa:test:skip
test_allow_admin { false }
```

**usage**:

```
$ opa test my-test.rego my-app-authz.rego
myapi.authz.test_allow_bob   : SUCCESS
myapi.authz.test_deny_alice  : FAIL
myapi.authz.test_allow_admin : SKIPPED
----
1/3 tests succeeded
1/3 tests failed
1/3 tests skipped
```

**Comment by 06kellyjac** [comment]
Were skippable tests added in the end? I can't find any references in the PR or docs https://www.openpolicyagent.org/docs/latest/policy-testing/#test-results

**Comment by tsandall** [comment]
@06kellyjac `opa test` does not support skipped tests currently. If you'd like to file a feature request, go for it! It would be useful if you could explain the context of why you need skippable tests. IME, skipped tests are usually needed due to things like flakes which are unlikely to occur in policy tests.

**Comment by 06kellyjac** [comment]
Well I'm actually using `conftest` but I was wondering if this was implemented in the end.

I want the skip feature for tests that are TODO or more accurately with my project tests that I want to pass but don't yet and I don't have time to fix right now. (e.g. weird edge cases)
It'd be nice to have it skip rather than commenting it out so it's visible as a test to finish.

Not sure if that should be filed under OPA or conftest

**Comment by tsandall** [comment]
Ah, the term "test" is a little bit overloaded 😅 

Are you referring to the tests you write for your own rules (which you'd run w/ `conftest verify`) or are you referring to the rules that you execute with `conftest test` (which execute against your config files)?

If it's the former, this is the right place. If it's the latter, file it against conftest.

**Comment by 06kellyjac** [comment]
Using verify
