### ISSUE TITLE
GraphQL to JSON translation support

### ISSUE THREAD

**Issue by adam-sandor** [open-policy-agent/opa#4283]
## What part of OPA would you like to see improved?

I would like to be able to authorise GraphQL queries in OPA. As GraphQL queries are not valid JSON they are currently not usable as OPA inputs.

## Describe the ideal solution

A built-in function that translates a GraphQL query to a JSON structure would do the trick. A good example of such a transformation is the [graphql-query-to-json](https://github.com/trayio/graphql-query-to-json) library. The GraphQL query would come in the input doc as a string and the policy would pass it to the transform function.

## Describe a "Good Enough" solution

A simple built-in function converting a GraphQL query string to JSON like the graphql-querty-to-json library does.

**Comment by anderseknert** [comment]
Hey Adam! 👋 

I take it this transformation cannot be done in the client while preparing the input data? 

Either way, I think such a built-in function could be useful. I don't know enough about GraphQL to tell, but I'm guessing a problem would be that there isn't a "standard" way to represent a GraphQL query as JSON, or is there? Looking at the repo you linked they use attribute names like `__args` .. is that an agreed upon convention? Are there other such "oddities" in GraphQL queries that must be represented using some special annotation?

It would be nice if we didn't have to spend an entire section in the docs just exlaining the structure of the data returned by that builtin 😅

**Comment by adam-sandor** [comment]
I'm no expert on GraphQL but as far as I understand there isn't a convention for serialising GraphQL to JSON. You're right that this makes things quite complex as OPA would have to define the format.

**Comment by kroekle** [comment]
Actually there is a standard way to represent the document as JSON (in AST form).  Unfortunately the reference implementation is javascript: https://github.com/graphql/graphql-js

The translation is fairly simple:

`
var { parse } = require('graphql');

exports.parse = (req, res) => {
  res.send(parse(req.body.query));
};
`

**Comment by anderseknert** [comment]
Thanks @kroekle , thats useful 👍 I tried following the examples from that page, but couldn't really find a complete one to get a provided query as string, and transform it into an AST in JSON format. Could you provide a full example of that? The `parse` method seems to return something close to that, but it's not JSON nor really an AST (all I see is start location and end location, nothing in between).

**Comment by kroekle** [comment]
I suspect you might be using some invalid graphql.  Try my example from here: https://github.com/kroekle/gql-to-ast

**Comment by anderseknert** [comment]
Thanks Kurt! This seems to work.

```javascript
var { parse } = require('graphql');

console.log(JSON.stringify(parse("{hero {name}}")))
```
>
```json
{
  "kind": "Document",
  "definitions": [
    {
      "kind": "OperationDefinition",
      "operation": "query",
      "variableDefinitions": [],
      "directives": [],
      "selectionSet": {
        "kind": "SelectionSet",
        "selections": [
          {
            "kind": "Field",
            "name": {
              "kind": "Name",
              "value": "hero",
              "loc": {
                "start": 1,
                "end": 5
              }
            },
            "arguments": [],
            "directives": [],
            "selectionSet": {
              "kind": "SelectionSet",
              "selections": [
                {
                  "kind": "Field",
                  "name": {
                    "kind": "Name",
                    "value": "name",
                    "loc": {
                      "start": 7,
                      "end": 11
                    }
                  },
                  "arguments": [],
                  "directives": [],
                  "loc": {
                    "start": 7,
                    "end": 11
                  }
                }
              ],
              "loc": {
                "start": 6,
                "end": 12
              }
            },
            "loc": {
              "start": 1,
              "end": 12
            }
          }
        ],
        "loc": {
          "start": 0,
          "end": 13
        }
      },
      "loc": {
        "start": 0,
        "end": 13
      }
    }
  ],
  "loc": {
    "start": 0,
    "end": 13
  }
}
```
I'm curious to know though - is this kind of AST something devs would want to work with in their policies? 🤔

**Comment by kroekle** [comment]
Not that they would "want" to work with the AST, but it would give them the ability to to create rules.  I think helper libraries (with bringing in graphql schema context) would make rules more practical.  I'm working on some here: https://github.com/kroekle/gql-rego-library
