### ISSUE TITLE
compile.go missing option to add manifest.metadata

### ISSUE THREAD

**Issue by johanneslarsson** [open-policy-agent/opa#4289]
## compile.go missing option to add manifest.metadata
Currently we use the compile.go to create bundles. In addition to revision we'd like to provide more details, regarding the bundle build process, such as opa version that built the bundle. I think the .manifest/metadata would be a good fit for this data. Initial intention was not to add it for every bundle OPA builds, but to enable the option in the compile.go.

Example .manifest:
```
{
  "revision": "26f803",
  "roots": [
    "rules",
    "test"
  ],
  "entries": [
    "rules/allow"
  ],
  "metadata": {
    "version": "0.36.1"
  }
}
```

## Capacity
There is capacity to start working on a PR, if we find the idea useful.

**Comment by anderseknert** [comment]
So, an added `WithManifest`? Sounds good to me.

**Comment by johanneslarsson** [comment]
> So, an added `WithManifest`? Sounds good to me.

Close, I was thinking of `WithManifestMetadata`. But great, will give it a go.

**Comment by anderseknert** [comment]
I think`WithManifest` would be more generally useful, but I guess eiher one is fine.

**Comment by johanneslarsson** [comment]
> I think`WithManifest` would be more generally useful, but I guess eiher one is fine.

`WithManifest` would indicate we could replace it all, but we already one of the fields covered with `WithRevision`. And the remaining Roots and WasmResolvers seem to come from the compile process. I think `WithManifestMetadata` or the shorter version  `WithMetadata` is enough.
