### ISSUE TITLE
OpenTelemetry spans for gRPC ext_authz calls 

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4290]
## What part of OPA would you like to see improved?

The OpenTelemetry feature used through opa-envoy-plugin. If configured, spans should be emitted for ext_authz calls, too. `http.send` calls happening in policies should be descendants of the gRPC endpoint's spans.

## Describe the ideal solution

The existing config would enable the feature.

## Describe a "Good Enough" solution

Verify that _at least_ the `http.send` calls in policy eval cause spans to be emitted.

**Comment by vinhph0906** [comment]
hey, @srenatus. Do you have any updates on this issue?

**Comment by srenatus** [comment]
No, I'm afraid not. But it would make for a good contribution and I could help you with that.

**Comment by anderseknert** [comment]
@vinhph0906 done 👍

**Comment by srenatus** [comment]
@vinhph0906 are you still on this? LMK if I can assist you.

**Comment by vinhph0906** [comment]
Sorry for this. I have a lot of workloads this week. But, I will come back and update it in the next week.

**Comment by srenatus** [comment]
It's cool! Thanks for the update.

**Comment by ashutosh-narkar** [comment]
Closing in favor of https://github.com/open-policy-agent/opa/issues/5903.
