### ISSUE TITLE
SDK should not panic if config reader not supplied

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#4303]
The following code panics:

```go
package main

import (
	"context"
	"log"

	"github.com/open-policy-agent/opa/sdk"
)

func main() {

	ctx := context.Background()
	opa, err := sdk.New(ctx, sdk.Options{}) // Config MUST be provided
	if err != nil {
		log.Fatal(err)
	}

	result, err := opa.Decision(ctx, sdk.DecisionOptions{})
	if err != nil {
		log.Fatal(err)
	}

	log.Println(result)
}
```

We should fix the sdk so that this doesn't cause a panic. All we need to do is check if the `Config` reader is nil and default to an empty object here: https://github.com/open-policy-agent/opa/blob/main/sdk/options.go#L64 (e.g., set `bs` to `[]byte("{}")`).

**Comment by damienjburks** [comment]
Is anyone assigned to this issue? I would like to take this on.

**Comment by anderseknert** [comment]
@damienjburks 👍
