### ISSUE TITLE
Creating opa bundle with soft link to files doesn't work

### ISSUE THREAD

**Issue by keshavprasadms** [open-policy-agent/opa#4335]
> Opa version - 0.34.2

I am trying to create a a bundle with some files which are a soft link. But these soft link files are missing within the bundle. Please see below to reproduce.

- Create two directories with the rego files
```
mkdir main policy
cat > main/main.rego <<EOF
package main

import data.policy as policy

identified_action = "check_block"

default allow = {
  "allowed": false
}

allow = status {
   policy[identified_action]
   status := {
      "allowed": true
   }
}
EOF

cat > policy/policy.rego <<EOF
package policy

check_block {
  input.message == "ok"
}
EOF
```

- Create the bundle
```
cd policy/
ln -s ../main/main.rego main.rego
opa build --bundle . --optimize 0 --entrypoint "main/allow"
```
- Check the contents of the `bundle.tar.gz` and `main.rego` file will be missing

Please can you let me know if this behaviour is expected? Is there a way to include the soft linked files within the bundle? Changing the files as a hard link works.

**Comment by keshavprasadms** [comment]
Okay thanks for the info. We are using opa for our API checks in our microservices. So our directory structure looks like this -
```
tree opa
opa
├── analytics
│   ├── common.rego -> ../common/common.rego
│   ├── main.rego -> ../common/main.rego
│   ├── policies.rego
│   └── policies_test.rego
├── certregistry
│   ├── common.rego -> ../common/common.rego
│   ├── main.rego -> ../common/main.rego
│   ├── policies.rego
│   └── policies_test.rego
├── common
│   ├── common.rego
│   ├── main.rego
│   ├── main_test.rego
│   ├── policies.rego
│   └── policies_test.rego
├── content
│   ├── common.rego -> ../common/common.rego
│   ├── main.rego -> ../common/main.rego
│   ├── policies.rego
│   └── policies_test.rego
├── knowledgemw
│   ├── common.rego -> ../common/common.rego
│   ├── main.rego -> ../common/main.rego
│   ├── policies.rego
│   └── policies_test.rego
├── learner
│   ├── common.rego -> ../common/common.rego
│   ├── main.rego -> ../common/main.rego
│   ├── policies.rego
│   └── policies_test.rego
└── lms
    ├── common.rego -> ../common/common.rego
    ├── main.rego -> ../common/main.rego
    ├── policies.rego
    └── policies_test.rego
```
- We have defined many of the common API checks in a central place (`common` directory) and during the microservice deployment we create a bundle and inject in the pod.

**Comment by ashutosh-narkar** [comment]
It's a common pattern to share code with some package like in your example. Have you tried using the `import` keyword to access the common package ? [This](https://www.openpolicyagent.org/docs/latest/faq/#collaboration-using-import) should provide more reference. So basically your microservices should just re-use the polices in `common` and not have to create symlinks.

**Comment by keshavprasadms** [comment]
Actually I am using imports as `import data.common as common` in the `policies.rego` file. We add only the specfic policy files in the bundle for a particular microservice and do not include all the policies. So a bundle for a microservice has only the below files.
```
├── common.rego
├── main.rego
├── policies.rego
```
For my above comment if I include the entire `opa` directory as a bundle, then its straigforward to just write as
```
import data.common.common as common
```
which imports the ` common.rego` code.

Anyways thanks for the info. We are handling this by changing the soft link to an actual copy at the time of microservice deployment.
