### ISSUE TITLE
Patch.json: Change "upsert" to "add" (matching RFC 6902) or support both?

### ISSUE THREAD

**Issue by ReadyPlayerEmma** [open-policy-agent/opa#4344]
## What part of OPA would you like to see improved?
It seems an odd choice for patch.json to support what seems to be the most useful parts RFC 6902, but for some reason, renaming "add" to "upsert". Is there a good reason that "add" was replaced with "upsert"? If not, perhaps consider aligning with the RFC.

Even in the code itself, the "upsert" operation is mapped to "AddOp".

https://github.com/open-policy-agent/opa/blob/dd02a7f848828b9428a0bf96a3779f2cad4d5f98/bundle/store.go#L696-L697
```go
		case "upsert":
			op = storage.AddOp
```

## Describe the ideal solution
Directly support RFC 6902. It seems nice to use existing standards when they make sense. Especially when the system is essentially already a subset of RFC 6902.

## Describe a "Good Enough" solution
At least support "add" as being equivalent to "upsert". Perhaps changing the docs to show "add" and deprecating "upsert" at some point.

## Additional Context
https://datatracker.ietf.org/doc/html/rfc6902

**Comment by ashutosh-narkar** [comment]
Thanks for filing this. [This](https://github.com/open-policy-agent/opa/issues/4336) issue discusses a similar topic and the resolution would help with this issue too.

**Comment by ReadyPlayerEmma** [comment]
@ashutosh-narkar Can you check this PR that adds the simple fix to allow "add" to function the same as "insert"?
https://github.com/open-policy-agent/opa/pull/4352

**Comment by ashutosh-narkar** [comment]
Closing this for now. If we do decide to support the `add` operation, we should implement it as per the RFC instead of being an alias for `upsert`.
