### ISSUE TITLE
Race on first usage of Eval on PrepareForEval

### ISSUE THREAD

**Issue by skillcoder** [open-policy-agent/opa#4345]
## Short description 

Reproduced in all version of opa, for example (v0.27.1, v0.29.4 and even in **latest v0.37.2**)

## Steps To Reproduce
I create a test which reproduces race condition in 100% cases.
To run it:
```sh
git clone git@github.com:skillcoder/opa-race.git
cd opa-race
make test
```

Race looks like described by me in #2129
```
==================
WARNING: DATA RACE
Read at 0x00c005dc0d48 by goroutine 118:
  github.com/open-policy-agent/opa/ast.(*object).Hash()
      .../vendor/github.com/open-policy-agent/opa/ast/term.go:1844 +0x64
  github.com/open-policy-agent/opa/ast.(*Term).Hash()
     .../vendor/github.com/open-policy-agent/opa/ast/term.go:395 +0x71
  github.com/open-policy-agent/opa/ast.(*set).get()
      .../vendor/github.com/open-policy-agent/opa/ast/term.go:1611 +0x4f
...
Previous write at 0x00c005dc0d48 by goroutine 121:
  github.com/open-policy-agent/opa/ast.(*object).Hash()
      .../vendor/github.com/open-policy-agent/opa/ast/term.go:1847 +0x108
  github.com/open-policy-agent/opa/ast.(*Term).Hash()
      .../vendor/github.com/open-policy-agent/opa/ast/term.go:395 +0x71
  github.com/open-policy-agent/opa/ast.(*set).get()
      .../vendor/github.com/open-policy-agent/opa/ast/term.go:1611 +0x4f
...
```

## Expected behavior

Test passed without any errors

## Additional context

Seems reproduced only for first Eval for PrepareForEval query.
Have a look at this comment
https://github.com/skillcoder/opa-race/blob/main/groups/groups_test.go#L44

**Comment by srenatus** [comment]
Thanks for digging into this. I'll have a look!

**Comment by skillcoder** [comment]
Seems running `Eval` with different `EvalInput` also may cause race. 
Race not happened only on second run with same `EvalInput`

**Comment by srenatus** [comment]
The same applies to sets and arrays (see https://github.com/open-policy-agent/opa/commit/1bdae88f6a8b098d72cd13f8de8d91b27e6d17b8), so any of those rules can be used to trigger the race:
```rego
allow[{"foo": "bar"}] { true }
allow[{"foo"}] { true }
allow[["foo"]] { true }
```
(It's got nothing to do with the EvalInput)
