### ISSUE TITLE
Strict mode: fail on unused imports

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4354]
Running `opa check` with the `--strict` flag currently fails when unused assignment is encountered. It would be a good addition if we added a new check to similarly fail on unused imports:

```rego
package foo

import data.foo.x

allow {
    input.foo == "bar"
}
```

```shell
$ opa check --strict foo.rego
1 error occurred: policy.rego:3: rego_compile_error: import data.foo.x unused
```

Whoever wants to work on this might be helped by taking a look at [this](https://github.com/open-policy-agent/opa/pull/4301/files) strict mode PR forbidding the use of `input` and `data` as identifiers in rules and variables.

**Comment by damienjburks** [comment]
Hey y'all! I'd love to take on this issue.
