### ISSUE TITLE
Deprecate or promote WARN level in logging package

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4373]
Although used sparingly, our logging implementation supports a WARN level. This is however currently not possible to set as the `--log-level` of the server, and the default implementation of `.Warn` currently just [defers](https://github.com/open-policy-agent/opa/blob/main/logging/logging.go#L145) to log at ERROR level, making it somewhat confusing/misleading.

I'd suggest either deprecate/remove the WARN level and rewrite the few places where it's used to log at INFO or ERROR, or that we promote WARN to a distinct logging level available as a `--log-level` option.

**Comment by damienjburks** [comment]
This sounds like an interesting challenge. I'd love to take a look at this one @anderseknert,

**Comment by anderseknert** [comment]
Sounds good @damienjburks! 👍 Just give me some time to coordinate with the other maintainers on what path we should take here, i.e. either promote the `warn` level or deprecate it. I'll let you know as soon as I know.

**Comment by damienjburks** [comment]
@anderseknert for sure! Just let me know!

**Comment by anderseknert** [comment]
Our conclusion is this:

* Keep the three log levels available for `--log-level` configuration, i.e. debug, info and error
* When `--log-level=error` is set, set the "real" log level to `warn` to include both warnings and errors
* Remove the redirect from warn->error (as referenced in the description) to have .Warn calls actually print at WARN level, providing more fine grained logging.

Should be fairly straightforward. @damienjburks if you want to work on this and just add some basic tests, there's a [test logger](https://github.com/open-policy-agent/opa/blob/main/logging/test/test.go#L26) that you can use for that purpose.

**Comment by damienjburks** [comment]
Sounds good. Assign this guy to me; I'll definitely work on it.

**Comment by anderseknert** [comment]
Have you had any time to look into this, @damienjburks?

**Comment by damienjburks** [comment]
@anderseknert I just raised a PR. Take a look at it and see if what I've done makes sense?

**Comment by anderseknert** [comment]
Awesome! Bedtime over here, but I’ll take a look first thing tomorrow 😊
