### ISSUE TITLE
`opa fmt` indentation issues with `with/as` statements

### ISSUE THREAD

**Issue by tiwood** [open-policy-agent/opa#4376]
* Version: 0.37.2

`width/as` statements get currently formatted like this:

![CleanShot 2022-02-23 at 4 07 21](https://user-images.githubusercontent.com/6249819/155346710-2191f3b6-d36e-4c98-988a-98b30bbfe696.png)

## Expected behavior

* each `width` statements is on its own line
* `tab` and `spaces` should not be mixed, the line should be indented further with an additional `tab` instead of a single space.

Example:

![CleanShot 2022-02-23 at 4 11 45](https://user-images.githubusercontent.com/6249819/155347603-c8ebb63a-eb62-4dd5-bcf2-0df099b73316.png)

**Comment by anderseknert** [comment]
Hi @tiwood! 

And thanks for filing this. I think the first point is a bit subjective (although subjectively, correct), but mixing tabs and spaces definitely wasn't something I expected. If spaces were used for alignment, I'd at least prefer see the following `with` to align with the one above (given the current formatting is kept), like: 

```rego
test_me {
    not 1 with input.x as 1
          with input.y as 2
          with input.z as 3
}
```
Though I guess that could be problematic if the expression to the left of `with` was longer.

**Comment by srenatus** [comment]
We should replace the space with tabs!
