### ISSUE TITLE
Warn when input attributes is missing in /v1/data body

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4386]
Every now and then we see users new to OPA missing the fact that `/v1/data` requires the JSON request body to wrap the `input` document, ala: `{"input": {"x": "y"}}`. Unless e.g. default assignment is used, OPA currently returns just an empty response for a request missing the "input" wrapper, i.e. `{"x": "y"}` ... it's easy to see why this would be, given how people likely have worked on their policy in the Rego Playground or using `opa eval` before running the server. 

It would be an improvement if we informed the user of what's missing! Suggested response might look something like:

```shell
HTTP/1.1 200 OK
Content-Type: application/json

{
  "result": <JSON>,
  "warning": {
    "code": "api_usage_warning",
    "message": "The 'input' key was missing from the request. See <DOC_URL> for more details."
  }
}
```

Note that while it's tempting to return a 400 response, this would both break a lot of existing integrations, and would need to differentiate between input missing _entirely_ (i.e. no JSON body) and JSON body but with missing `input` attribute. For that reason we'll keep the 200 response but with an added warning.

**Comment by aflmp** [comment]
@anderseknert Can I work on this please? like others, I have also been bitten by this issue in the past.

**Comment by anderseknert** [comment]
Sure! Let me know if you need any help along the way, either here or in the #development channel on the OPA slack.

**Comment by aflmp** [comment]
from a quick parse, looks like we want to address the issue [here](https://github.com/open-policy-agent/opa/blob/cb01fba01562665fe197192ff204deed1ce2be57/server/server.go#L1312-L1319)

**Comment by anderseknert** [comment]
Yeah, at least you have the `input` variable there and can check if it's `nil` or not.. but since it shouldn't be treated as an error but rather just as a warning to add to the response, you'll probably want to do that check where the response is built, i.e. somewhere [here](https://github.com/open-policy-agent/opa/blob/cb01fba01562665fe197192ff204deed1ce2be57/server/server.go#L1414).
