### ISSUE TITLE
Improve regex syntax

### ISSUE THREAD

**Issue by cxflores** [open-policy-agent/opa#4403]
## What part of OPA would you like to see improved?
Regex syntax improvement

## Describe the ideal solution
Support negative lookahead

(?!re) | before text not matching
-- | --

<br class="Apple-interchange-newline">

## Additional Context
According to OPA documentation https://www.openpolicyagent.org/docs/latest/policy-reference/#regex, the regex library https://github.com/google/re2/wiki/Syntax used by OPA does not support some functionality we are looking to leverage.

Would like to leverage negative lookaged regex syntax for the following regex: ^(?!c\.namespace\.restricted-.*)^(?!s\.namespace\.restricted-.*)(c\.namespace\..*|ns\.namespace|s\.namespace\..*)

This is to be used in an RBAC hierarchical entitlements model. Where generally a user should have access to most namespaces, and collections/sequences under those namespaces. However, there are a select few namespaces that only a smaller subset of the general population should have access to (admins). Our idea is to have 2 roles, one for general access to most namespaces where the resource is the regex above. And a second role for those more restricted resources which will follow a specific naming convention (c.namespace.restricted-).

**Comment by srenatus** [comment]
Adding a new regex engine is probably  _a lot_ of work... there hasn't been a lot of (recorded) interest in a PCRE-compatible regex.match, for example.

So, I'd wonder if there are easier ways to make this happen. Rego is a good language for encoding stuff like that, too, so how about:

```rego
package play
import future.keywords.every

# ^(?!c.namespace.restricted-.)^(?!s.namespace.restricted-.)(c.namespace..|ns.namespace|s.namespace..)
restricted_re = {`^c\.namespace\.restricted-`, `^s\.namespace\.restricted-`}

matches_ordinary(inp) {
  every re in restricted_re { not regex.match(re, inp) }
  regex.match(`^(c\.namespace\.|ns\.namespace|s\.namespace\.)`, inp)
}

test_a = matches_ordinary("c.namespace.restricted-foo")
test_b = matches_ordinary("s.namespace.restricted-foo")
test_c = matches_ordinary("c.namespace.foo")
test_d = matches_ordinary("ns.namespace.foo")
test_e = matches_ordinary("s.namespace.foo")
```

[playground](https://play.openpolicyagent.org/p/lhBGuoRqiD)

**Comment by cxflores** [comment]
Thanks @srenatus , this is a great idea. This can definitely work with my use case. I will go this route.

**Comment by cxflores** [comment]
Closing issue as the alternate solution will suffice for my usecase.
