### ISSUE TITLE
Docker install keeps restarting the OPA container

### ISSUE THREAD

**Issue by rajapriyapt** [open-policy-agent/opa#4413]
## Short description 
Docker install keeps restarting the OPA container

* OPA version - 0.37.2

```
  openpolicyagent:
    image: openpolicyagent/opa:$OPA_TAG
    container_name: $OPA_CONTAINER_NAME
    restart: always
    env_file: .env
    networks:
      - opa-network

```

The following output is seen in docker logs of the container, how do I prevent the prompt

```
> 
Do you want to exit ([y]/n)? OPA 0.37.2 (commit 7fdcead, built at 2022-02-11T09:39:26Z)

Run 'help' to see a list of commands and check for updates.

> 
Do you want to exit ([y]/n)? OPA 0.37.2 (commit 7fdcead, built at 2022-02-11T09:39:26Z)

Run 'help' to see a list of commands and check for updates.

> 
Do you want to exit ([y]/n)? OPA 0.37.2 (commit 7fdcead, built at 2022-02-11T09:39:26Z)

Run 'help' to see a list of commands and check for updates.

> 
Do you want to exit ([y]/n)? OPA 0.37.2 (commit 7fdcead, built at 2022-02-11T09:39:26Z)

Run 'help' to see a list of commands and check for updates.
```

**Comment by srenatus** [comment]
Try some command. A typical command line for running the server would be `opa run -s`. The docker image's entrypoint is `opa`, so you'll only need the other arguments. Please see https://www.openpolicyagent.org/docs/latest/cli/#opa-run

See this for another example: https://github.com/anderseknert/opa-sidecar/blob/master/opa-sidecar.yaml#L33

**Comment by ashutosh-narkar** [comment]
@rajapriyapt the links mentioned in the comments should help you out. Feel free to re-open the issue if any questions.
