### ISSUE TITLE
OPA re_match function can't handle negative lookahead in regex

### ISSUE THREAD

**Issue by AshutoshNirkhe** [open-policy-agent/opa#4415]
## Short description 

I have a use case where I want to build a regex which will match a certain pattern of strings and will not contain a particular word at the end of string. For example, docker image should come from an allowed list of container registries and the image shouldn't be the 'latest' tag (i.e. image name shouldn't end in ':latest').
For example: regex should match 'docker.io/fluent-bit:1.2.1' but not 'docker.io/fluent-bit:latest'

## Expected behavior

I would except Rego to support negative lookahead or any similar logic that can be basically used to exclude a particular word from the input string.

## Additional context

We are using Azure Policy Gatekeeper admission controller that's based on OPA.

**Comment by srenatus** [comment]
> I would Rego to support negative lookahead or any similar logic that can be basically used to exclude a particular word from the input string.

_any similar logic_? I'd think that stuff like this is best expressed in Rego, not regular expressions:

```rego
import future.keywords

allowed_registries = {"docker.io"}

valid_image(img) {
  not endswith(img, ":latest")
  some reg in allowed_registries
  # some reg; allowed_registries[reg] # for GK without future.keywords import support
  startswith(img, reg)
} else = false # leave this off if you're OK with undefined

test_a = valid_image("docker.io/fluent-bit:1.2.1")
test_b = valid_image("docker.io/fluent-bit:latest")
```
https://play.openpolicyagent.org/p/16j2dGpMTF

Please note:
- https://github.com/open-policy-agent/opa/issues/4403
- `re_match` is the deprecated name of `regex.match`
- You can't import future keywords in GK _yet_, see https://github.com/open-policy-agent/gatekeeper/issues/1827.

**Comment by srenatus** [comment]
Cool. Looks like we can close this, then? Adding another regex engine is likely to be a significant amount of work.

**Comment by AshutoshNirkhe** [comment]
> Cool. Looks like we can close this, then? Adding another regex engine is likely to be a significant amount of work.

Yes closing, thanks.

**Comment by grosser** [comment]
I'd also need this feature and would prefer to not build it in rego 😞

**Comment by AshutoshNirkhe** [comment]
> I'd also need this feature and would prefer to not build it in rego 😞

Hey @grosser , not sure what exactly you are looking for. But if you also want to disallow docker images with ':latest', then may be you could something like this. May be, it's not perfect, but serves the purpose at least.

        violation[{"msg": msg}] {
          container := input_containers[_]
          not input_container_excluded(container.name)
          endswith(container.image, ":latest")
          msg := sprintf("Container image %v for container %v has not been allowed.", [container.image, container.name])
        }
