### ISSUE TITLE
`opa test -b .` fails when using every keyword

### ISSUE THREAD

**Issue by kristiansvalland** [open-policy-agent/opa#4420]
## Short description
OPA test command fails when using the bundle flag on policies with the `every` keyword.

OPA version v0.38.0

## Steps to reproduce
1. Define main.rego as
    ```
    # ./main.rego
    package main

    import future.keywords.every

    allow {
	   every x in [1, 2, 3] { x > 0 }
    }
    ```

2. Run `opa test -b .` 
3. Observe the following error message:

     ```
     opa test -b .
     1 error occurred: main.rego:6: rego_compile_error: declared var __local0__ unused
     ```

4. Optionally run `opa test .` (without the bundle flag) to observe that it does not fail without the bundle flag.

For completeness, a test can be included, but is not necessary for reproducing the results:

```
# ./test.rego
package test.main

import data.main

test_allow {
	main.allow
}
```

## Expected behaviour
Tests succeeds when using the bundle flag.

## Additional context
Relevant slack thread in the help channel: https://openpolicyagent.slack.com/archives/CBR63TK2A/p1646904624793089

I have also tested using `opa build .` followed by `opa test -b bundle.tar.gz` with the same result.

I think I have narrowed it down to it being the `every` keyword which is the culprit, because substituting the rule with one that does not use it will not show this behaviour.

**Comment by srenatus** [comment]
What happens is this: the bundle loader will parse the module, and during that process `every x in ...` is expanded to `every __local0__, x in ...`. Now the test runner will compile the module sources, and that runs the same compiler stages which will yield an unused `__local0__` var.

Still looking for the best way to fix this.
