### ISSUE TITLE
Non-overlapping roots being detected as overlapping

### ISSUE THREAD

**Issue by migscabral** [open-policy-agent/opa#4428]
## Short description 
`opa run` detects non-overlapping roots `/authz/url` and `/authz/actions` as overlapping. Based on the examples given on the [documentation](https://www.openpolicyagent.org/docs/v0.12.2/bundles/#multiple-sources-of-policy-and-data):

This is non-overlapping
```
acmecorp/policy    acmecorp/oncall
```

This is overlapping:
```
a/b/c    /a/b
```

## Additional details
* OPA version: 0.38.0-rootless
* `docker-compose.yaml`
```
version: '2'
services:
  opa:
    # image: openpolicyagent/opa:0.38.0-rootless
    image: openpolicyagent/opa
    ports:
    - 8282:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
    - "run"
    - "--server"
    - "--log-level=debug" 
    - "--log-format=json-pretty"
    - "--set=decision_logs.console=true"
    - "--bundle"
    - "/authz/actions"
    - "/authz/url"
    volumes:
    - ./policies/authz:/authz
```

* `/policies/authz` directory structure:
```
+ policies/
|
+-+ authz/
  |
  +-+ actions/
  | |-- data.json
  | |-- actions.rego
  |
  +-+ url/
    |-- data.json
    |-- actions.rego
```

* Container logs:
```
opa-opa-1  | error: initialization error: detected overlapping roots in bundle manifest with: [/authz/url /authz/actions]
opa-opa-1 exited with code 1
```

## Steps To Reproduce
1. Copy code snippet above into `docker-compose.yaml`
2. Create a similar directory structure in your local copying the structure described above in `policies/authz`.
3. Run `docker-compose up`

## Expected behavior
`/authz/actions` and `/authz/url` should **_not_** be detected as overlapping roots

**Comment by srenatus** [comment]
Thanks for reporting. Those roots should indeed be non-overlapping. Interesting.

**Comment by srenatus** [comment]
(Sorry misclicked.)

**Comment by srenatus** [comment]
I believe you need manifests to declare your bundles' roots when loading them like that, otherwise the bundle root will be assumed to be `/`.

If you put a `.manifest` into each of your directories, `authz/actions/.manifest` and `authz/url/.manifest`, with

```
{
  "roots": ["authz/actions"]
}
```
and
```
{
  "roots": ["authz/url"]
}
```
...I think things should start work as expected. Could you try that, please?

**Comment by anderseknert** [comment]
Interesting. We really should improve the error message to reflect that if that's the case.

**Comment by migscabral** [comment]
Seems like adding `.manifest` at each directory resolved it. I'm no longer getting the overlapping roots error message. 

@srenatus could you point me to the section in the documentation indicating that I have to include manifest file per root? Would like to read more about it. Thank you!

---

However, another issue came up. This time I'm getting this error:
```
opa-opa-1  | error: bundle /authz/actions: manifest roots [authz/actions] do not permit data at path '/role_actions' (hint: check bundle directory structure)
opa-opa-1 exited with code 1
```

This might be unrelated already. I'll go through the docs again to see what I'm doing wrong this time, and just post another issue if ever can't be resolved.

**Comment by srenatus** [comment]
> @srenatus could you point me to the section in the documentation indicating that I have to include manifest file per root? Would like to read more about it. Thank you!

I'm afraid it's rather more in between the lines: https://www.openpolicyagent.org/docs/latest/management-bundles/ describes the bundle file structure -- if you're using `-b`, your expected to replicate the same structure in your file system. For roots, it states

>  - If you expect to load additional data into OPA from outside the bundle (e.g., via OPA’s HTTP API) you should include a top-level roots field containing of path prefixes that declare the scope of the bundle. See the section below on managing data from multiple sources. *If the roots field is not included in the manifest it defaults to [""] which means that ALL data and policy must come from the bundle.*

But from your comments above, I take it you had already read that.

For the other issue, I think it's a matter of the file structure, but I'd have to dive into the code, too, to be sure. @anderseknert, any ideas?

**Comment by srenatus** [comment]
@migscabral Have you gotten over this bump in the road?

**Comment by srenatus** [comment]
> Interesting. We really should improve the error message to reflect that if that's the case.

From the code, we have the information but don't log it: https://github.com/open-policy-agent/opa/blob/35184350b5380bfa63bd63688ee3a24d07330856/bundle/store.go#L675-L680

Perhaps it would be nicer if we said something like: _"overlapping roots: root1 (bundle-a, bundle-b), root2 (bundle-a, bundle-c)"_? In this case, it would have shown that the overlapping root was `""`, so it's the all-of-data-root. 🤔 I suppose we could also *hint about defining roots* if we notice that they're all `""`?

**Comment by migscabral** [comment]
Sorry late reply @srenatus had to work on other tasks. Back on this now and I'm still stuck on this error:
```
opa-opa-1  | error: bundle /authz/actions: manifest roots [authz/actions] do not permit data at path '/role_actions' (hint: check bundle directory structure)
opa-opa-1 exited with code 1
```

Not sure if I understand the structure correctly as mentioned in the docs?: 
```
$ tar tzf bundle.tar.gz
.manifest
roles
roles/bindings
roles/bindings/data.json
roles/permissions
roles/permissions/data.json
http
http/example
http/example/authz
http/example/authz/authz.rego
```

Does this mean I can't have the data file together with the policy file? Currently I have both data files and policy files together in one directory:
```
authz/actions/.manifest
authz/actions/data.json
authz/actions/actions.rego
authz/urls/data.json
authz/urls/manifest
authz/urls/urls.rego
authz/urls/urls.rego
```

But from the docs as well there's also [example](https://www.openpolicyagent.org/docs/v0.12.2/deployments/#volume-mounts) of data.json and policy.rego residing in the same directory:
```
$PWD/example/data.json
...
$PWD/example/policy.rego
```

At this point I'm not sure whether there's something wrong with my directory structure, or something wrong with my code (wrong use of package keyword maybe?)

For reference here's the contents of the data and policy files:

authz/actions/data.json:
```
{
	"role_actions": [{
			"role": "approver",
			"actions": {
				"payout": [
					"view-members",
					"approve-members",
					"download-failed-invites"
				],
				"invoicing": [
					"view-invoice"
				],
				"transfer": [
					"approve-transfer",
					"decline-transfer"
				]
			}
		},
		{
			"role": "checker",
			"actions": {
				"payout": [
					"view-members",
					"approve-members",
					"download-failed-invites"
				],
				"transfer": [
					"approve-transfer",
					"decline-transfer"
				]
			}
		},
		{
			"role": "maker",
			"actions": {
				"transfer": [
					"create-transfer"
				]
			}
		}
	]
}
```

authz/actions/actions.rego:
```
package authz.actions

import future.keywords.in

default allow = false

allow {
	input.role == "admin"
}

allow {
	some grant
	user_is_granted[grant]

	input.action == grant
}

user_is_granted[grant] {
    some i
	data.role_actions[i].role == input.role
    actions := data.role_actions[i]["actions"][input.action_group]
	some grant in actions
}
```

authz/urls/data.json: 
```
{
    "role_url_resources": [
     	{
            "role": "role-1",
            "urls": [
                "/authorized/url/1",
                "/authorized/url/2"
	        ]
    	},
     	{
            "role": "role-2",
            "urls": [
                "/authorized/url/3"
	        ]
    	}
}
```

authz/urls/urls/json: 
```
package authz.url

import future.keywords.in

default allow = false

allow {
	input.role == "admin"
}

allow {
	some grant
	user_is_granted[grant]

	input.url == grant
}

user_is_granted[grant] {
	some i
    data.role_url_resources[i].role == input.role
    some grant in data.role_url_resources[i].urls
}
```

**Comment by srenatus** [comment]
```
authz/actions/.manifest
```
This looks suspicious. Can you put it into the top-level? Like this:

```
.manifest
authz/actions/data.json
authz/actions/actions.rego
authz/urls/data.json
authz/urls/manifest
authz/urls/urls.rego
authz/urls/urls.rego
```

**Comment by migscabral** [comment]
@srenatus moving the `.manifest` file to the root went back to the previous error:

```
opa-opa-1  | error: initialization error: detected overlapping roots in bundle manifest with: [/authz/actions /authz/url]
opa-opa-1 exited with code 1
```

This is my dir structure now:
```
/.manifest
/authz/actions/data.json
/authz/actions/actions.rego
/authz/urls/data.json
/authz/urls/urls.rego
```

I'm using volume mounts to mount the bundle directory and manifest file from my host machine to the container:

```
version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.38.0-rootless
    ports:
    - 8282:8181
    command:
    - "run"
    - "--server"
    - "--log-level=debug" 
    - "--log-format=json-pretty"
    - "--set=decision_logs.console=true"
    - "--bundle"
    - "/authz/actions"
    - "/authz/urls"
    volumes:
    - ${PWD}/policies/authz:/authz
    - ${PWD}/policies/.manifest:/.manifest
```

**Comment by srenatus** [comment]
I thought there were two bundles at play here...? What's the `.manifest` of the other one? 🤔 

(Sorry I'm on the run, I'll have another look tomorrow if nobody beats me to it.)

**Comment by migscabral** [comment]
I may have misunderstood, I thought I should move the .manifest file up to the top-level? 

Should my dir structure look like this?:
```
/.manifest

/authz/actions/.manifest
/authz/actions/data.json
/authz/actions/actions.rego

/authz/actions/.manifest
/authz/urls/data.json
/authz/urls/urls.rego
```

**Comment by migscabral** [comment]
You beat me to it. I just made it work using the same layout before I saw your comment. This layout worked for me too.

Thanks!
