### ISSUE TITLE
With keyword target must start with input or data

### ISSUE THREAD

**Issue by gabrielfern** [open-policy-agent/opa#4431]
## Short description 
When referencing a non-existing target for the with keyword, the compiler raises an error saying
that the target must start with input or data, but that's misleading, as the with keyword supports replacing/mocking
other rules too.

Here's an example of using with to replace the value of another rule:
![Screenshot_20220313_154506](https://user-images.githubusercontent.com/25506386/158074722-e6fa28ee-2315-494f-bd52-f94a700fbd5e.png)

## Steps To Reproduce

Here's an example rego that shows the error:
![Screenshot_20220313_154403](https://user-images.githubusercontent.com/25506386/158074856-fffb38ae-d871-4065-a116-2cd401313884.png)

Here's the code used:
```java
package main

n = 4

default even = false

even {
	n % 2 == 0 with nn as 5
}
```

## Expected behavior

The error shouldn't imply we can only use with with the input or data documents.

## Additional context

Also, OPA documentation, under Policy Language/With Keyword doesn't mention that the with keyword can be used with other things too.

**Comment by anderseknert** [comment]
Hey Gabriel! And thanks for filing this. Agreed, we should fix the error message and update the docs.

**Comment by anderseknert** [comment]
Technically, any rule or var _is_ `data`, but it certainly doesn't need to "start with" `data.` ... perhaps we should just update the message to something like: `with keyword must reference existing input or data`?

**Comment by srenatus** [comment]
Here's what's happening when this policy is compiled:
```rego
package main

n = 4

default even = false

even {
	n % 2 == 0 with n as 5
}
```

The compiler stage _resolving all references_ will turn this into
```rego
package main

n = 4 { true }
default even = false
even = true { equal(rem(data.main.n, 2), 0) with data.main.n as 5 }]
```
et voila, the with target `n` becomes `data.main.n`.

When it's `nn`, however, we'll find
```rego
package main

n = 4 { true }
default even = false
even = true { equal(rem(data.main.n, 2), 0) with nn as 5 }]
```
☝️ here, `nn` doesn't get replaced -- it's not a reference to a rule in the same module -- so the error condition for invalid `with` targets is satisfied: it's neither starting with `input` nor with `data`. ⚡ 

It's OK not to reference an existing rule, but only if you reference some piece of `data` or `input` either directly or via an import.

To complicate matters, see this
```rego
package main

import data.foo

n = 4
default even = false
even {
	n % 2 == 0 with foo.nn as 5
}
```

here, `foo` is resolved into `data.foo`, and `foo.nn` thus becomes `data.foo.nn` --  a valid `with` target.

It's quite a puzzle to come up with a succinct error message that describes this 🤔

**Comment by anderseknert** [comment]
Thanks for expanding on this, @srenatus! I **think** the suggested change to `with keyword must reference existing input or data` still holds, or no? It pretty much describes what you said in:

> It's OK not to reference an existing rule, but only if you reference some piece of data or input either directly or via an import.

**Comment by srenatus** [comment]
Yeah it's certainly true but is it more enlightening to users? A bit perhaps, we'd avoid the confusion introduced by "starting"... 🤔

**Comment by anderseknert** [comment]
Yeah, it's a small improvement for sure, but an improvement nonetheless :)

**Comment by gabrielfern** [comment]
I think if the documentation clearly states that rules are also data, then the suggested change is good. (I'm sorry for not remembering if it mentions this or not, it's been sometime). Because if this relation of rules being data is not well stated in the docs, then the new message could still mislead users into thinking rules are not supported by the with keyword.
But even then, it would still be better than the current message just for not saying the target is expected to start with data or input.

Hope this helps, from a user perspective.

**Comment by anderseknert** [comment]
Yes, that is useful, @gabrielfern 👍 The docs on the OPA [document model](https://www.openpolicyagent.org/docs/latest/philosophy/#the-opa-document-model) explain this fairly well, IMHO... would you agree?

**Comment by gabrielfern** [comment]
Yes, for sure, it does.

Although it could be even more explicit about the relation:
rules (their generated values) -> virtual document -> data
Like starting a section saying: Rules are data, everything in OPA is data...
I feel like the way it's worded there can be missed by newcomers if they don't pay enough attention
(but then this could be seen more of a user's fault at this point).

These are just some of my thoughts after reading the part of the doc you shared.
But yeah, I agree with you.
