### ISSUE TITLE
safety check does not completely consider `in` keyword

### ISSUE THREAD

**Issue by ekcs** [open-policy-agent/opa#4456]
## What part of OPA would you like to see improved?

This snippet using `in` is considered unsafe.
```
package play
import future.keywords.in
graph1 := { 1:[2,3] }
a {
  some node_a
  some node_b
  node_b in graph1[node_a]
  node_a < node_b
}
```

The equivalent version without the new keyword is safe:
```
package play
graph1 := { 1:[2,3] }
a {
  some node_a
  some i
  node_b := graph1[node_a][i]
  node_a < node_b
}
```

## Describe the ideal solution

Ideally, both ways are considered safe.

## Describe a "Good Enough" solution

Current situation could be considered good enough because it does not limit expressiveness.
It is merely inconvenient and potentially frustrating. Good enough if the ideal ask is hard.

## Additional Context

OPA v0.38.1

**Comment by anderseknert** [comment]
The equivalent using `in` would use `some ... in` for iteration—not `some` separated from `in`, as then the `some` simply declares a variable to be used later. I.e. this would work:

```rego
a {
  some node_a
  some node_b in graph1[node_a]
  node_a < node_b
}
```

`in` on its own simply checks for membership.

**Comment by ekcs** [comment]
Ah I see. Thank you!
So the original version with the `some node_b` separated from the `in` is unsafe in the same way this version is also unsafe. Difference is assignment vs equality.

```
package play
graph1 := { 1:[2,3] }
a {
  some node_a
  some node_b
  some i
  node_b == graph1[node_a][i]
  node_a < node_b
}
```

**Comment by ekcs** [comment]
Still, it would be nice if `x in arr` behaved as `x = arr[_]` (safe) rather than `as x == arr[_]`. Or does that cause other problems?

To summarize my understanding of current situation:
- `some x in arr` behaves as `x := arr[_]`. (Safe)
- `x in arr` behaves as `x == arr[_]`. (Unsafe)

**Comment by anderseknert** [comment]
`in` works for any collection type, so if you have a set, `x in s` could just as well be translated to `s[x]` with no iteration at all involved. Additionally, `some`/`in` works with both index/value, key/value, including "known" keys/values, like:
```
some is_5, 5 in {"x": 5, "y": 5, "z": 10}
```
So while your assumption might be correct in some cases—and the compiler probably agrees when rewriting the `some`/  `in` constructs—I'd rather think of it as an alternative way of doing membership checks and iteration than a direct translation of another way of doing it.

**Comment by ekcs** [comment]
Thank you!

One more related observation. These two rules behave differently:
```
set := {0, 1, 2}
a {
  set[x]  # safe
}
b {
  x in set  # unsafe
}
```

Would it be better if they behaved the same way?

In general, my beginner analysis is that having `in` bind variables (similar behavior as `=`) would greatly reduce user frustration without breaking anything.

What do you think?

**Comment by anderseknert** [comment]
Sets are tricky that way :) 

Since `x` is unbound, `set[x]` will bind it for _iteration_ over the set. So the equivalent `b` rule would be:
```rego
{
    some x in set
}
```
If you'd want to check for membership, you'd need to first know what to check for, i.e. these would be equivalent:

```rego
set := {0, 1, 2}

x := 0

a {
    set[x]
}

b {
    x in set
}
```
