### ISSUE TITLE
Configurable Request Path

### ISSUE THREAD

**Issue by adam-bodrogi-epam** [open-policy-agent/opa#4460]
## Actual request
Please make the request path configurable, so it can listen on e.g. _opa/v1/..._.

## Context
We are integrating OPA as a standalone microservice in AWS EKS and we would like to hook it on an ingress rule. The problem is OPA works with a non-configurable base url, and the request paths start with _/v1/_. This way the other microservices must use something different than this, e.g. the existing routes have to be reconfigured. Alternatively a custom URL (Route53) or load balancer can be registered, but that costs extra.

**Comment by srenatus** [comment]
ℹ️ Please re-open when you get to this and there are still questions 🧹

**Comment by AdrianDiazCode** [comment]
Hi, I would really like this feature too
