### ISSUE TITLE
Timestamps and Metrics for Delta Bundles

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#4477]
OPA has support for [Delta Bundles](https://www.openpolicyagent.org/docs/latest/management-bundles/#delta-bundles). It would be useful to capture some metrics related to deltas such as their size, download duration etc. We should also record timestamps such as the last successful activation for a delta and snapshot bundle. The metrics and timestamps are made available via the status api.

**Comment by ashutosh-narkar** [comment]
PR to include bundle type in status: https://github.com/open-policy-agent/opa/pull/4633

**Comment by bryan-styra** [comment]
PR to include bundle size in status: https://github.com/open-policy-agent/opa/pull/4984

**Comment by ashutosh-narkar** [comment]
We've added few metrics to the bundle status. Closing this issue.
