### ISSUE TITLE
decisionlog upload Content Type header

### ISSUE THREAD

**Issue by iamatwork** [open-policy-agent/opa#4487]
Decisionlog uploads sets the header "Content-Type" to "application/json", even if set manually in the configuration.

IMHO it should be "application/x-ndjson", which would allow easy ingest into ELK.

services:
    decisionlogger:
        headers:
            Content-Type: application/x-ndjson

{"headers":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"User-Agent":["Open Policy Agent/0.37.2 (linux, amd64)"]},"level":"debug","method":"POST","msg":"Sending request.","time":"2022-03-25T13:40:19Z","url":"https://elastic:9200/opa_log/_doc"}

Also some headers should not be logged? Like (Basic) Authorization?

**Comment by ashutosh-narkar** [comment]
> Also some headers should not be logged? Like (Basic) Authorization?

Looks like you're using the `debug` level.  In prod, you would typically use `error` or `info`, you'll notice those are not logged.

Regarding the content-type OPA, we set this explicitly in both the decision log and status plugin to indicate the actual content. Have you tried updating the content-type to `application/x-ndjson` (will need a code change) and seeing if it works as expected. I haven't tried this. Also means if we don't set the header and use what is in the configuration, are there some types we support and some we don't.

**Comment by anderseknert** [comment]
Even in prod you might need to temporarily set the log level to `debug` in case you need to troubleshoot some issue. I agree that we shouldn't log the value of the authorization header, and I thought we masked that already. Maybe I'm thinking of some other context.

**Comment by ashutosh-narkar** [comment]
@anderseknert are you referring to masking decision logs ?

**Comment by anderseknert** [comment]
Yeah, that's probably what I was thinking of. @iamatwork I might take a shot at masking the `Authorization` header value for the debug logs. Was there some other header you had in mind wherr you think this should be done?

**Comment by ashutosh-narkar** [comment]
@anderseknert were you planning on masking a list of hardcoded headers or can users specify this maybe through the service config or through policy ?

**Comment by anderseknert** [comment]
That'd be cool! Might not be worth it for the purpose of debug logging though. I think we can start simple by e.g. just mask the `Authorization` header value, so hard coded like you said. WDYT?

**Comment by ashutosh-narkar** [comment]
Yeah we can start with this and always iterate.

**Comment by anderseknert** [comment]
Changing this between versions could break existing control planes. I wonder though if it would be possible to change the `Content-Type` header via the config option, i.e. `services.my_logging_service.headers`? 🤔 I'm guessing we'll overwrite that at a later stage, but perhaps a viable workaround could be to respect whatever the user set via config if so? That would provide more flexibility for other use cases as well.

**Comment by iamatwork** [comment]
@anderseknert the Authorization header was the only one, that I really wouldn't log.  I'm happy with your fix.

Setting the Content-Typ didn't really fix my problem. I'll try some additional things, and maybe repopen the issue.

Thanks

**Comment by anderseknert** [comment]
I suspected as much. I think allowing that type of override would be a reasonable solution.
