### ISSUE TITLE
docs: tokens in OPA Envoy tutorial are expired

### ISSUE THREAD

**Issue by pvsone** [open-policy-agent/opa#4499]
In the opa-envoy tutorial (https://www.openpolicyagent.org/docs/latest/envoy-tutorial-standalone-envoy/), the example tokens for alice and bob have an `exp` value of "1641081539" which is a date of "Sat Jan  1 17:58:59 CST 2022".  Therefore both tokens fail exp validation used during the `decode_verify` check in the policy.

**Comment by anderseknert** [comment]
I knew I recognized this from somewhere 🤦 https://github.com/open-policy-agent/opa/issues/4212

Looks like that PR never came in, and we forgot about it as the ticket got closed... oh well, let's fix this now!

**Comment by anderseknert** [comment]
If you want to submit a PR @pvsone , there's a rego policy to create two fresh ones in that issue. Should just be a matter of copy-pasting them to replace the old ones. If not, l can do it on Monday.

**Comment by anderseknert** [comment]
Fixed in https://github.com/open-policy-agent/opa/pull/4504
