### ISSUE TITLE
print function doesn't work in test with json format

### ISSUE THREAD

**Issue by wermerb** [open-policy-agent/opa#4520]
## Short description 

When running `opa test -v -f json`, the print function results are not added to the output

Examples:

* OPA version: v0.38.1

## Steps To Reproduce
Given the following policy:
```rego 
package policy

default allow = false

allow {
 true
}
```
Test:
```rego
package policy

test_should_allow {
  print("text")
  allow with input as {}
}
```
Then run the following command: `opa test policy.rego test.rego -f json -v`

Output:
```json
[
  {
    "location": {
      "file": "test.rego",
      "row": 3,
      "col": 1
    },
    "package": "data.policy",
    "name": "test_should_allow",
    "duration": 520300,
    "output": "dGV4dAo="
  }
]
```
## Expected behavior
It should display print result as well.

**Comment by anderseknert** [comment]
It's in the `output`:

```shell
opa test -v --format json . | jq -r '.[0].output' | base64 -d
text
```

**Comment by wermerb** [comment]
@anderseknert Thank you very much for the prompt response. Indeed its there, much apricated for the help.
