### ISSUE TITLE
Wiz has adopted OPA

### ISSUE THREAD

**Issue by alonweisswiz** [open-policy-agent/opa#4538]
### Organization Name

Wiz

### Organization Website

https://www.wiz.io/

### Organization Logo (optional)

https://test.wiz.io/static/assets/wiz_auth0_logo.png

### How is your organization using OPA?

Wiz (https://wiz.io/) helps every organization rapidly remove the most critical risks in their cloud estate. It simply connects in minutes, requires zero agents, and automatically correlates the entire security stack to uncover the most pressing issues. Wiz policies leverage Open Policy Agent (OPA) for a unified framework across the cloud-native stack. Whether for configurations, compliance, IaC, and more, OPA enables teams to move faster in the cloud.
For more information on how Wiz uses OPA, contact us.

### Want to link blogs or videos? Share them here.

https://www.wiz.io/blog/wiz-magic-shifts-left/

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by srenatus** [comment]
Merged. 🥳

**Comment by alonweisswiz** [comment]
Thanks! :)
