### ISSUE TITLE
OPA integration example with Kuma service mesh

### ISSUE THREAD

**Issue by braghettos** [open-policy-agent/opa#4576]
## What part of OPA would you like to see improved?

There are examples available of integration of OPA with Istio and Gloo Edge. I would like to understand how to use it with Kuma service mesh.

## Describe the ideal solution

An example/tutorial like https://github.com/open-policy-agent/opa-envoy-plugin/tree/main/examples/istio

**Comment by pvsone** [comment]
Hi @braghettos - the integration with Kuma is similar to Istio, Gloo, or any other Envoy based proxy.  Although not part of the 
OPA docs, I have an example integration here: https://github.com/pvsone/opa-ext-authz/tree/master/kuma

If you have any questions, feel free to reach out on the OPA slack (@Peter Sullivan)
