### ISSUE TITLE
`io.jwt.decode_verify` does not work for tokens with base64-encoded secrets generated outside of OPA

### ISSUE THREAD

**Issue by eliw00d** [open-policy-agent/opa#4585]
## Short description 

The documentation for this is very confusing. If I provide the plaintext secret as `k` in `io.jwt.encode_sign_raw` it generates a JWT with base64-encoded secret which both jwt.io and Node.js accept. However, when I use the base64-encoded secret, using `base64url.encode_no_pad` [as the example shows](https://www.openpolicyagent.org/docs/latest/policy-reference/#round-trip---sign-and-verify), OPA accepts it but neither jwt.io nor Node.js accept it.

The real issue comes from generating a JWT from either jwt.io or Node.js with a base64-encoded secret and being unable to use `io.jwt.decode_verify` to decode and verify it. It is always invalid. 

I am guessing there is a difference in how OPA deals with secrets being base64?

## Steps To Reproduce
https://play.openpolicyagent.org/p/Nr6cPQZ7K4

## Expected behavior

I should be able to use `io.jwt.decode_verify` to decode and verify a JWT with base64-encoded secret generated outside of OPA.

## Additional context

https://openpolicyagent.slack.com/archives/CBR63TK2A/p1650040544145109

**Comment by anderseknert** [comment]
I think the confusion here is what that feature of jwt.io [does](https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/3997bdde7cc0405152a8e2106c192e4d038dcdd8/src/editor/jwt.js#L11). Checking that box seems to simply mean "my secret is base 64 encoded, please use the decoded form as the secret value".  If you create a secret as base64:

```shell
echo -n "secret" | base64
c2VjcmV0
```
And use the "c2VjcmV0" value as the secret in jwt.io, **and** check the "secret base64 encoded" checkbox.. the resulting token can then be verified using "secret" as the key:

```rego
package play

verify := io.jwt.decode_verify(input.token, { "secret": "secret" })
```

```json
{
    "verify": [
        true,
        {
            "alg": "HS256",
            "typ": "JWT"
        },
        {
            "iat": 1516239022,
            "name": "John Doe",
            "sub": "1234567890"
        }
    ]
}
```

**Comment by eliw00d** [comment]
> I think the confusion here is what that feature of jwt.io [does](https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/3997bdde7cc0405152a8e2106c192e4d038dcdd8/src/editor/jwt.js#L11). Checking that box seems to simply mean "my secret is base 64 encoded, please use the decoded form as the secret value". If you create a secret as base64:

I think checking it actually encodes it for you. When you toggle it you can actually see the signature changing. Take a look at this Node.js example I built to show this: https://replit.com/@PaavoBennett/OPA#index.js

**Comment by eliw00d** [comment]
@anderseknert I think I had several confusions that led me down the wrong path. I figured it out and all is good now, though. Thanks!
