### ISSUE TITLE
Errors with net.cidr_merge

### ISSUE THREAD

**Issue by alexhu20** [open-policy-agent/opa#4596]
## Short description 
In short, the net.cidr_merge seems not produce the smallest possible set of CIDRs.

Examples:
I have IP addresses: ["192.168.1.254", "192.168.1.254"]
output: `192.168.1.0/24`
expect: `192.168.1.254/32`
Seems like it is actually expanding the IP range.

* OPA version
latest

## Additional context
In addition, the net.cidr_merge does not handle ipv6 very well. I have an ipv6 address that cannot be converted to ipv4(not mapped)
and 
```
2022/04/19 16:53:00 http: panic serving [::1]:35204: runtime error: index out of range [15] with length 0
goroutine 30 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go-1.18/src/net/http/server.go:1825 +0xbf
panic({0xe90d20, 0xc0003123d8})
        /usr/lib/go-1.18/src/runtime/panic.go:844 +0x258
github.com/open-policy-agent/opa/internal/cidr/merge.GetAddressRange({{0x170c3c0, 0x0, 0x0}, {0xc00025aeb0, 0x10, 0x10}})
        /home/alex_hu/go/pkg/mod/github.com/open-policy-agent/opa@v0.38.1/internal/cidr/merge/merge.go:117 +0x3c5
github.com/open-policy-agent/opa/internal/cidr/merge.partitionCIDR({{0xc00025ae30, 0x10, 0x10}, {0xc00025ae40, 0x10, 0x10}}, {{0x170c3c0, 0x0, 0x0}, {0xc00025aeb0, ...}})
        /home/alex_hu/go/pkg/mod/github.com/open-policy-agent/opa@v0.38.1/internal/cidr/merge/merge.go:225 +0x1c5
github.com/open-policy-agent/opa/internal/cidr/merge.RangeToCIDRs({0x170c3c0, 0x0, 0x0}, {0x170c3c0, 0x0, 0x0})
        /home/alex_hu/go/pkg/mod/github.com/open-policy-agent/opa@v0.38.1/internal/cidr/merge/merge.go:87 +0x6ba
github.com/open-policy-agent/opa/topdown.evalNetCIDRMerge({0xc0005cb640, 0x4, 0xc00001a060?})
        /home/alex_hu/go/pkg/mod/github.com/open-policy-agent/opa@v0.38.1/topdown/cidr.go:327 +0x39c
github.com/open-policy-agent/opa/topdown.builtinNetCIDRMerge({{0x107a4e0, 0xc00051aa20}, {0x107d928, 0xc0005cb420}, {0x10709e0, 0xc00011a1e0}, 0xc0005afb48, {0x10757a8, 0xc00025ac38}, 0xc000599da0, ...}, ...)
        /home/alex_hu/go/pkg/mod/github.com/open-policy-agent/opa@v0.38.1/topdown/cidr.go:288 +0x18b
github.com/open-policy-agent/opa/topdown.builtinErrorWrapper.func1({{0x107a4e0, 0xc00051aa20}, {0x107d928, 0xc0005cb420}, {0x10709e0, 0xc00011a1e0}, 0xc0005afb48, {0x10757a8, 0xc00025ac38}, 0xc000599da0, ...}, ...)
        /home/alex_hu/go/pkg/mod/github.com/open-policy-agent/opa@v0.38.1/topdown/builtins.go:126 +0x79
github.com/open-policy-agent/opa/topdown.evalBuiltin.eval({0xc000001c20, 0x16b6060, {{0x107a4e0, 0xc00051aa20}, {0x107d928, 0xc0005cb420}, {0x10709e0, 0xc00011a1e0}, 0xc0005afb48, {0x10757a8, ...}, ...}, ...}, ...)
```
Input ipv6 address: `2601:600:8a80:207e:a57d:7567:e2c9:e7b3` the Ip address is valid, but cannot map to any ipv4

**Comment by anderseknert** [comment]
Hi Alex! And thanks for reporting this. And ouch! That panic looks bad indeed..

**Comment by srenatus** [comment]
Had a quick look:

> I have IP addresses: ["192.168.1.254", "192.168.1.254"]
> output: 192.168.1.0/24
> expect: 192.168.1.254/32

So what happens is this: the IP if passed without a CIDR, so "192.168.1.254", not "192.168.1.254/32" is parsed, and gets its "default mask". For 192.168.1.254, that'll be 255.255.255.0 (or /24). So, when it is further processed, it's treated as if the input was `["192.168.1.254/24", "192.168.1.254/24"]`. For that, the output 192.168.1.254/24 is correct.

So if the default mask as determined by [this golang stdlib function](https://pkg.go.dev/net#IP.DefaultMask) _is not what you want_, you've got to provide it with your input:

```
$ opa eval -fpretty 'net.cidr_merge({"192.168.1.254/32", "192.168.1.254/32"})'
[
  "192.168.1.254/32"
]
```

The panic is another problem, though 💥

**Comment by srenatus** [comment]
OK I've had another look at the IPv6 case -- and it seems like it's very similar: everything works as expected if you pass in the IP including a CIDR range. There's no "default mask" for IPv6 _at all_, so you'll always have to provide it.

We get the expected outcome then:
```
% opa eval -fpretty 'net.cidr_merge(["2601:600:8a80:207e:a57d:7567:e2c9:e7b3/128", "2601:600:8a80:207e:a57d:7567:e2c9:e7b3/128"])'
[
  "2601:600:8a80:207e:a57d:7567:e2c9:e7b3/128"
]
```

So much for the workaround. We should probably default to /128 if nothing is provided for IPv6, what do you think?

**Comment by srenatus** [comment]
@alexhu20 discussing the PR, we've come up with making prefix-less IPv6 inputs to `net.cidr_merge` _a non-fatal error_. I.e. `net.cidr_merge(["2601:600:8a80:207e:a57d:7567:e2c9:e7b3"])` would be `undefined`; if run with `--strict-builtin-errors`, it would return an error message. What do you think?
