### ISSUE TITLE
Review Rego snippets in docs and update to follow current best practices

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4599]
Some things to consider for the review. Obviously up for discussion!

* Use `:=` for [file level assignments](https://github.com/open-policy-agent/opa/issues/4555)
* Prefer `foo in bar` over `foo == bar[_]` or `foo[bar]`
* Prefer `some foo in bar` over `foo := bar[_]`, `some foo, bar in baz` over `bar := baz[foo]`
* Prefer `every foo in bar { .. }` over iteration with helper rules
* Prefer metadata annotations over comments on rules and packages

Additionally, we should use `opa fmt` for consistent formatting of snippets, and use `opa check --strict` to catch mistakes (unless of course that's what's being demonstrated in a snippet).

**Comment by johanfylling** [comment]
Perhaps we could update the build step (or add a linting step) for docs to search for rego blocks and diff those against the output of `opa fmt` for that same block 🤔 .

**Comment by srenatus** [comment]
@johanfylling totally. unfortunately, there's another prereq to that: https://github.com/open-policy-agent/opa/issues/4104 (now https://github.com/open-policy-agent/opa/issues/4508)

**Comment by anderseknert** [comment]
This eventually culminated into the [Rego Style Guide](https://github.com/StyraInc/rego-style-guide). Having a mix of styles in the docs could actually be good, I think, as long as the recommended path is documented *somewhere*. Closing this for now, but if someone feels that there are some particular part of our docs that need an update, do holler out!
