### ISSUE TITLE
Reorganize the miscellaneous section

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#4614]
The MISCELLANEOUS top-level section in the docs navigation has grown organically over time. It feels like it's time to reorganize the content under MISCELLANEOUS that it's easier for people to find and more consistent.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/238885/164894976-c168418f-165b-40ac-9451-5c73399c1967.png">

Here's my proposal for where the content ought to live:

CORE

- Policy Language
  - Metadata (currently called "Annotations")
  - Schema (currently called "Type Checking")
  - Future (w/ explanation of opt-in mechanism)
  - Strict Mode (currently called "Compiler Strict Mode")
- External Data
  - Option 1: JWT Tokens
  - OAuth2 and OIDC Samples (currently called "OAuth2 and OIDC")
- Intermediate Representation
- WebAssembly

OPERATIONS

- Storage
  - Disk (should also mention this under Policy Performance page when discussing memory footprint)

MISCELLANEOUS
- Editor and IDE Support
- Comparison to Other Systems

SUPPORT

- FAQ
- Ecosystem
- Enterprise

The only item that I've left out is the Rego Playground link. I think we should make this more prominent--e.g., put a link into the horizontal navbar at the top.

**Comment by aarushisoni** [comment]
Hi! I want to work on this issue.

**Comment by aarushisoni** [comment]
Hi, I want to contribute to this issue.

**Comment by srenatus** [comment]
@aarushisoni Please do! Also please have a look at the prior attempts ☝️

**Comment by aarushisoni** [comment]
> @aarushisoni Please do! Also please have a look at the prior attempts ☝️

it  will be helpful if you can tell me where  exactly I have to make changes like in which file.

**Comment by srenatus** [comment]
So we're using Hugo for organizing our docs pages. The preamble of each markdown file determines its section, like,
[wasm.md](https://sourcegraph.com/github.com/open-policy-agent/opa/-/blob/docs/content/wasm.md?L2-4&view=code):
```md
---
title: WebAssembly
kind: misc
weight: 1
---

# What is WebAssembly (Wasm)?
```

I'm afraid I'm not 100% certain what "weight" means here...

**Comment by Parsifal-M** [comment]
Hey Team :wave:, @srenatus, @aarushisoni 

I hope this helps with the `weight` :point_right: https://bwaycer.github.io/hugo_tutorial.hugo/content/ordering/

Its something to do with the way Hugo orders content

**Comment by charlieegan3** [comment]
I once worked on a Hugo site that made use of the weight field on staff pages - it raised the eyebrows of a few new joiners! 😂 In the end I opted for a random order (on build) to avoid the problem of ranking the staff page...

**Comment by lakhanjindam** [comment]
is anyone still working on it ? or else i can pick it up ?

**Comment by ashutosh-narkar** [comment]
Thanks @lakhanjindam. Go for it! Let us know if you have any questions.

**Comment by lakhanjindam** [comment]
Just confirming, this is the final format we are expecting, right ? https://github.com/open-policy-agent/opa/issues/4614#issue-1213291154
Let me know if there are any changes from the proposed format 👍

**Comment by ashutosh-narkar** [comment]
> Just confirming, this is the final format we are expecting, right ? https://github.com/open-policy-agent/opa/issues/4614#issue-1213291154

Yes that seems about right.

**Comment by lakhanjindam** [comment]
Documentation for setting up docs locally using netlify is kind of outdated, can you share what are the current steps or commands around that ?

**Comment by ashutosh-narkar** [comment]
I haven't tried to build the site locally lately. You can push your changes to your fork and create a draft PR. In that Netlify will generate a docs preview.

**Comment by Parsifal-M** [comment]
> Documentation for setting up docs locally using netlify is kind of outdated, can you share what are the current steps or commands around that ? Also i am getting an error when i try to build site from main branch on netlify <img alt="Screenshot 2023-04-04 at 11 01 10 PM" width="1040" src="https://user-images.githubusercontent.com/48401688/229871800-c5cd7cc2-111e-4995-999d-3310047bd0c7.png">

Hey 👋 

Apologies, not trying to derail the conversation but I was wondering if you are following this? -> https://www.openpolicyagent.org/docs/latest/contrib-docs/#test-your-changes

I have worked on the docs recently and did not face any issues, maybe also @charlieegan3 might know whats happening here 🤔

**Comment by lakhanjindam** [comment]
@Parsifal-M  The documentation that you mentioned, `make docs-serve-local` this make cmd is not there instead `make serve-local` is present, doc might be out of date. And there are 2 makefiles one on repo root level and another inside `docs/` dir, so i was confused about from where to run cmds.

**Comment by lakhanjindam** [comment]
its working fine now, i was able to load local preview via netlify cli. Thanks!

**Comment by lakhanjindam** [comment]
so when i try to run the remote netlify preview using this cmd `make docs-serve-remote` it fails eventually after these events 
```
WARNING: skipping v0.46.0 because https://github.com/open-policy-agent/opa/releases/download/v0.46.0/opa_linux_amd64 does not exist (or GET failed...)
WARNING: skipping v0.29.0 because https://github.com/open-policy-agent/opa/releases/download/v0.29.0/opa_linux_amd64 does not exist (or GET failed...)
```
Referring this [readme](https://github.com/open-policy-agent/opa/blob/main/docs/README.md#serving-the-full-site)
> Some links are redirecting to other pages which is not rendering my local changes that's the reason i am trying with remote preview which imitates prod site.

**Comment by lakhanjindam** [comment]
> Documentation for setting up docs locally using netlify is kind of outdated, can you share what are the current steps or commands around that ? Also i am getting an error when i try to build site from main branch on netlify <img alt="Screenshot 2023-04-04 at 11 01 10 PM" width="1040" src="https://user-images.githubusercontent.com/48401688/229871800-c5cd7cc2-111e-4995-999d-3310047bd0c7.png">

So this is me trying to build netlify preview from my PR and not from my local terminal 😄 , getting the above error ⬆️

**Comment by ashutosh-narkar** [comment]
I was suggesting you create a draft PR in https://github.com/open-policy-agent/opa with your changes and then you can get the Netlify preview of the docs.

**Comment by lakhanjindam** [comment]
I've made the changes, please review the PR and let me know what changes are required.
On one thing, I can use your help -> 
```
Storage
Disk (should also mention this under Policy Performance page when discussing memory footprint)
```
Under policy performance where we have to add the reference to disk storage as mentioned for this issue ?

**Comment by ashutosh-narkar** [comment]
[Resource Utilization](https://www.openpolicyagent.org/docs/latest/policy-performance/#resource-utilization) would be a good place to mention this.
