### ISSUE TITLE
OCI: Bundles are reloaded and activated unconditionally

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4637]
When using an OCI registry for bundle storage (#4518), each periodic call to the OCI reg will now fetch the bundle, and load and activate it.

For HTTP sources, we're using the ETag. We could probably record the digest of the OCI artifact? Or use it as ETag...?

👉 https://github.com/open-policy-agent/opa/blob/v0.40.0/download/oci_dowload.go#L101-L103

**Comment by viovanov** [comment]
I think we should use the digest. AFAIK, we're not downloading layers already downloaded, but the bundle is loaded/activated each time anyway.
I think if the digest has not changed, the bundle should not be loaded/activated.
