### ISSUE TITLE
OCI: use oras/v2

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4648]
ORAS is doing a revamp in their v2 work: among other things, this should cut down dependencies significantly, and that would be very welcome to the use in OPA.

* See [oras.land/oras-go/v2](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-20220427084858-ed1a2571617e) and its directories for the new interface.
* The [`Copy` API](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-20220427084858-ed1a2571617e#Copy) we're currently using is already ported.
* The _target_ of the copy seems to allow for different things:
  * [file](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-20220427084858-ed1a2571617e/content/file)
  * [memory](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-20220427084858-ed1a2571617e/content/memory)
  memory could be interesting for us when there is not persistence directory.

I _think_ this issue should perhaps precede the other OCI issues (#4637 and #4639  and #4638) since it has consequences on their content or implementation. (WDYT @carabasdaniel?)

**Comment by carabasdaniel** [comment]
Hi @srenatus, I think we might be able to tackle the [bug](https://github.com/open-policy-agent/opa/issues/4637) first and then focus on bumping to [oras/v2](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-20220427084858-ed1a2571617e) before any other feature work.

**Comment by srenatus** [comment]
https://github.com/oras-project/oras-go/issues/49 done, alpha release out.

**Comment by anderseknert** [comment]
This was resolved in https://github.com/open-policy-agent/opa/pull/5690
Thanks @ashutosh-narkar 👍
