### ISSUE TITLE
ast: support using refs as rules (or "dots in rule heads")

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4653]
Currently, when you want to write a policy like this:

```rego
package authz

allow {
  data.rules[input.method][input.resource].allow
}
```

...you'll have to create **one** rego file per input method/resource pair, like

* `get_pets.rego`:
```rego
package rules.GET.pets {
allow {
    input.name = "snoopy"
}
```

* `delete_pets.rego`:
```rego
package rules.DELETE.pets {
allow {
    input.name != "snoopy"
}
```

This can grow out of proportion, and it's cumbersome.

The enhancement would be to allow for creating those rules **in a single rego file**:

```rego
package authz

allow {
  data.authz.rules[input.method][input.resource].allow
}

rules.GET.pets.allow {
    input.name = "snoopy"
}

rules.DELETE.pets.allow {
    input.name != "snoopy"
}
```

**Comment by anderseknert** [comment]
Agreed, this would be a nice addition! Would the "dots" work for partial map rules too? E.g. something like:
```
users[user].claims := c {
    input.users[user]
    user.authenticated
    c := {
        # building claims object per user here
    }
}
```

**Comment by srenatus** [comment]
> Would the "dots" work for partial map rules too?

Yes, but without allowing for variables in the refs -- it's a shortcut for defining rules, not for generating them. So that example wouldn't be valid, since `user` isn't known at compile time.

What should work, however, is
```rego
package authz
rules.GET.pets[x] = y {
  x := "snoopy"
  y := 100
}
```
to define the _partial set rule_ `authz.rules.GET.pets`.

**Comment by srenatus** [comment]
There's some ambiguity to resolve here. In references, `foo["bar"]` and `foo.bar` are the same thing. When defining rules like ☝️ this,

```rego
package p
foo["bar"] { true }
```
defines a partial set rule `data.p.foo` with (as it stands) one element, `"bar"`, whereas

```rego
package p
foo.bar { true }
```
defines a complete document rule `data.p.foo.bar` (which is true).

The same holds for partial object rules.

To deal with this, and keep backwards compatibility, "trailing" `[...]` like this will always need to be parsed as definition partial objects/sets. `[...]` in the middle sections are OK, like
```rego
package authz

tenants["example.com"].allow { true }
```

**Comment by srenatus** [comment]
OK I've realised on constraint given our current approach to parsing rules from expressions (it's some parser intricacy taken as a given for now) -- when we currently write
```rego
package p

foo.bar = 12
```
we define a _partial object rule_ `data.p.foo` which contains the key "bar" with value 12. (Only one dot. Multiple dots aren't allowed.)

I wasn't aware that this is allowed input, i.e. `foo.bar` is treated as `foo["bar"]` here, that's because when the module is parsed, it'll become an equality expression with LHS ref "foo.bar"; and we've then already lost if it was provided as one way or the other in the input policy.

So for a dotty-head rule,
```rego
package p

x.y.z.bar = 12
```
we wouldn't be able to tell if it's `x.y.z["bar"] = 12` (partial object) or `x.y.z.bar = 12` (complete document).

👉 To keep backwards-compatibility, we'll hook in on the number of dots: if it's only one, we'll assume `foo.bar` is meant to define a partial object rule; if there two or more dots, we'll take it to be a complete document.

So this means you cannot define "dotty-head" partial objects _this way_. You can, as a workaround, do this:
```rego
package p

x.y.z[b] = 12 { b := "bar" }
```
if you _really need_ dotty-head partial objects.
