### ISSUE TITLE
strict mode: fail on duplicate set elements

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#4665]
Saw this rule in the [clj-kondo](https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#duplicate-set-key) linter, and I think it would be a good addition to our strict mode. Having duplicate elements in sets is probably always a mistake in a production policy, and while it's "harmless", the intent is likely to provide another element rather than the duplicate, leading to an unexpected result.

Example sets that would fail strict mode checks:

```rego
required_roles := {"dba", "developer", "ops", "dba"}

users := {
    {"name": "alice"},
    {"name": "bob"},
    {"name": "eve"},
    {"name": "bob"},
}
```

**Comment by GeauxEric** [comment]
According to https://www.openpolicyagent.org/docs/edge/strict/, `strict` mode only belongs to the `check` command.
To really enable checking duplicate values, the flag needs to be passed all the way to the [ParserOptions](https://github.com/open-policy-agent/opa/blob/main/ast/parser.go#L97)?

**Comment by johanfylling** [comment]
`strict mode` is currently only a compiler feature, and doesn't extend to the parser. Your assessment is however correct @GeauxEric, for this to work, we need to update the parser where the set is created, before duplicate values are dropped. Adding an option to the `ParserOptions` struct is the sensible way forward.

An unfortunate side effect of this is that the SDK will no longer be a single compiler toggle. But perhaps that is ok. We just need to be clear in the docs (which currently aren't very elaborate on this anyways).

**Comment by anderseknert** [comment]
If this is a hassle to implement for strict mode, I'd be fine with doing it as part of https://github.com/open-policy-agent/opa/issues/3218 instead.

**Comment by johanfylling** [comment]
I don't envision the implementation itself being a hassle, but this might be more appropriate as a linter feature, yes.

**Comment by anderseknert** [comment]
Closing this in favor of implementing this check elsewhere.
