### ISSUE TITLE
unable to parse input: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by Octogonapus** [open-policy-agent/opa#4673]
## Short description 

I encountered this error when running OPA with a Terraform plan (simplified to `/tmp/test.json`) as input:
```
opa eval -i /tmp/test.json -b /tmp/policy.rego allow
unable to parse input: yaml: control characters are not allowed
```

It's worth noting that the Terraform plan contains binary data, which seems to be confusing the parser.

```
opa version
Version: 0.39.0
Build Commit: cc965f6
Build Timestamp: 2022-03-31T12:34:11Z
Build Hostname: f9db5089da69
Go Version: go1.18
Platform: linux/amd64
WebAssembly: unavailable
```

## Steps To Reproduce

`/tmp/test.json`:
```
":"
```

Also since that's not renderable, here's the hex version of `/tmp/test.json`:
```
xxd test.json                                                                               
00000000: 223a c29a 22                             ":.."
```

`/tmp/policy.rego`:
```
default allow = false
```

## Expected behavior

I think the parser shouldn't have trouble with this data since it's just a string.

**Comment by srenatus** [comment]
🤔 From the yaml lib, it looks like your input is outside the allowed range. It's not like all weird characters were forbidden, but yours seem to be:

https://github.com/open-policy-agent/opa/blob/v0.40.0/vendor/gopkg.in/yaml.v3/readerc.go#L364-L381

Usually, binary data in json files is encoded in some way... can you share your terraform plan json? 🔍

**Comment by anderseknert** [comment]
Interesting case :) Looks like `yq` has the same complaint: 

```shell
yq eval -P tfplan.json
Error: bad file 'tfplan.json': yaml: control characters are not allowed
```

While `jq` does not, suggesting it's valid JSON but not valid YAML... which I wasn't aware of as being possible. 

From the godoc on the conversion function: 

```
// Convert YAML to JSON. Since JSON is a subset of YAML, passing JSON through
// this method should be a no-op.
```
I guess not then 😄
