### ISSUE TITLE
unknown flag: --tls-ca-cert-path

### ISSUE THREAD

**Issue by pramodak** [open-policy-agent/opa#4678]
Documentation of OPA security mentions "--tls-ca-cert-path"

## Short description 
Documentation of OPA security mentions "--tls-ca-cert-path", but I think, it should be "--tls-ca-cert-file"

## Steps To Reproduce
Go to https://www.openpolicyagent.org/docs/latest/security/
Search for --tls-ca-cert-path

Also, when we try to use --tls-ca-cert-path while starting an OPA server, we see the usage displayed with the below error.
unknown flag: --tls-ca-cert-path

## Expected behavior
Documentation should be corrected to mention --tls-ca-cert-file

**Comment by srenatus** [comment]
Thanks for reporting. This would be a great first contribution! Would you be up to giving this a try?

**Comment by pramodak** [comment]
Sure, I will check https://www.openpolicyagent.org/docs/edge/contrib-docs/ and contribute this change as a pull request.
