### ISSUE TITLE
Request Suggestion to know the feasibility of evaluation of rules for the given input

### ISSUE THREAD

**Issue by Vighi88** [open-policy-agent/opa#4679]
Dear All, 

Im new to OPA and i have below list of scenario's to evaluate for the given input data 

Given that the input data will be Arraylist of object. eg : {"input" : [{"name":"n/a", "age": 25, "Country":"Poland"},{"name":"Raja", "age": 35, "Country":"Ireland"}, {"name":"David", "age": , "Country":"Australia"}] }

1.  Rule 1  - Iterate the list input and validate whether all the key is present, which means 'name, age and country' keys should be available in all the objects in the array . If any of the key is missing then return false with reason. (Here im able to check this if input is a single object but unable to execute the same rule in iteration. )
2. Rule 2  - Iterate the list input and validate whether the values are not null . Even if one of the object in the list is null, return false with reason (Here im able to check this if input is a single object but unable to execute the same rule in iteration. )
3. Rule 3 - Iterate the list input and validate whether the keys are in the same order . For example , the order should be 'name, age, country' suppose if any of the object in the list has the order changed something like 'country , name , age' then return false with reason (Please advise with example , whether it is possible with OPA )
4. Rule 4 - Iterate the input list and validate the datatype of the values of each keys of each object in the list . For example , the value of the name should be string and the value of age should be number and the value of the country should be string etc. if any of the object in the list has the value is having datatype which is different from the expected one , then return false with reason (Please advise with example , whether it is possible with OPA )
5. Assume more than one rule is written in a rego file and if one or more than one or if all fails, then returns false and then the end result should contain reason for all the rule failure as well (Please advise with example , whether it is possible with OPA )
6. Expectation is to group these rules in different combinations . Reason because , the rule can be executed by simple calling the category and bypass the rest of the rules as and when required (Please advise with example , whether it is possible with OPA )
     For example
        1. Category 1 - executes Rule 1 and Rule 3
        2. Category 2 - executes Rule 2 and Rule 3
        3. Category 3 - executes Rule 1, Rule 2 and Rule 4
        4. etc.,   
------------------------------------------------------------------------------------------------------------------------------------------------
Logic i used for one single object as input is as below(covers Rule 1 and Rule 2): 

{"input" : {"name":"n/a", "age": 25, "Country":"Poland"} }

package play

default headercheck = false
default notnullcheck = false

headercheck {
input["name"]; input["age"]; input["country"]
}

notnullcheck {
input.name != " "; input.country!= " "; input.age!= " "
}

------------------------------------------------------------------------------------------------------------------------------------------------
Logic i used for one single object as input (Covers rule 5 with 1 rule but not with multiple rules)

{"input" : {"name":"n/a", "age": 25, "Country":"Poland"} }

package play

default headercheck = false

headercheck {
input["name"]; input["age"]
}

headerevalresult = {
    "reason": "Header is missing or incorrect"
} {
  not headercheck
}

**Comment by Vighi88** [comment]
Hi @anderseknert , 

Thanks a lot . It really helps. 

I will play around with partial rule . Thanks for sharing it

**Comment by Vighi88** [comment]
Point 1, 2 and 5 has been addressed with below rego policy 

package play

import future.keywords.in
import data.requiredheaders
import future.keywords.every

default completenesscheck=false
default exactnesscheck=false
default rowcountcheck=false

#Null Check- Rule2
completenesscheck_result[message] {
    headers := input[_] 
    some key, val in headers
    val == " "
    message := sprintf("The value of the header '%v' in the given input is null", [key])
}

completenesscheck_result[message] {
    headers := input[_] 
    some key, val in headers
    val == ""
    message := sprintf("The value of the header '%v' in the given input is null", [key])
}
completenesscheck {
    count(completenesscheck_result)==0
}

completenesscheck_selective_result[message]{
 	headers := input[_] 
    some key, val in headers
    key in requiredheaders;val == " "
    message := sprintf("The value of the required headers in the given input is null %v", [key])
}

completenessselectivecheck {
    count(completenesscheck_selective_result)==0
}

Header Check - Rule 1
exactnesscheck_result[message] {
    headers := input[_]
    some key, _ in headers
    not key in requiredheaders
    message := sprintf("Missing or incorrect header '%v' in the given input", [key])
}

exactnesscheck {
count(exactnesscheck_result)==0
}

#Additional checks 
headercountcheck_result[message]{
    header := input[_]
    count(header) != count(requiredheaders)  #Here the expectation is that the requiredheader should have all the header value captured as data json
    message:= sprintf("Expected header count is %v, but number of headers in the given input is %v" , [count(requiredheaders), count(header)])
}

headercountcheck{
    count(headercountcheck_result)==0
}

**Comment by Vighi88** [comment]
For Rule 3 Iterate the list input and validate whether the keys are in the same order . For example , the order should be 'name, age, country' suppose if any of the object in the list has the order changed something like 'country , name , age' then return false with reason (Please advise with example , whether it is possible with OPA )

I tried below but there is no way to identify the index of the Key in object and the assignment(i++ or i=i+1) is not supporting

Any help is much appreciable

package play

#import data.requiredheaders
import future.keywords.in

#default ordercheck=false

ordercheck_result[message]{
headers:=input[_]
i:=0
j:=1
some key,_ in headers
#not has_key(key, i)
message:=sprintf("index is %v and Key is %v",[i, key])
i=sum({i, j}) # - It didn't work
#i=i+1   - It didn't work
#i=i+j  - It didn't work
#In General , there is no way to increment the i value based on 'some of key,_ in headers' 
} 

#has_key(key,i){
#   key==requiredheaders[i]
#}

**Comment by anderseknert** [comment]
Objects are not ordered collections:
```
opa eval -f pretty '{"b": 1, "a": 2} == {"a": 2, "b": 1}'
true
```

**Comment by Vighi88** [comment]
Yes , i agree but while iterating using 'some key, _in headers' im getting the keys in the same order in which the input is given . 

Please correct me if my understanding is wrong .

**Comment by Vighi88** [comment]
The place where im stuck is at below point 

i:=0
i=i+1 ---------> In this line im not able to overwrite the already defined value of i from 0 to any other

**Comment by anderseknert** [comment]
> Yes , i agree but while iterating using 'some key, _in headers' im getting the keys in the same order in which the input is given

Since you are working with an unordered collection type, iteration order can't be taken for granted. You can't require ordering for something which isn't ordered. Same thing with e.g. sets.

**Comment by Vighi88** [comment]
Update on the points . 

Point 4 (datatype validation) has been addressed as below . Also Point 5 to get overall result as false has been handled in my API service layer

package datatype

import data.numbertypeheaders
import data.stringtypeheaders
import data.booleantypeheaders

default datatype_check=false

datattype_check_result[message] {
    header := numbertypeheaders[_] #Here we need to have the data file with all numbertypeheaders else this logic will fail
    value := input[_]
    not is_number(value[header])
    message := sprintf("The input value is not a number for the column/header '%v'", [header])
}
datattype_check_result[message] {
    header := stringtypeheaders[_] #Here we need to have the data file with all stringtypeheaders else this logic will fail
    value := input[_]
    not is_string(value[header])
    message := sprintf("The input value is not string for the column/header '%v'", [header])
}
datattype_check_result[message] {
    header := booleantypeheaders[_] #Here we need to have the data file with all booleantypeheaders else this logic will fail
    value := input[_]
    not is_boolean(value[header])
    message := sprintf("The input value is not boolean for the column/header '%v'", [header])
}
datatype_check {
count(datattype_check_result)==0
}

**Comment by Vighi88** [comment]
For point 6 

i have kept each policy into one rego file . For example: datatypecheck.rego , headercheck.rego, headercountcheck.rego

When i keep all policies in one rego and executes, i get the result as below 

{
    "result": {
       "datatype": {
            "datattype_check_result": [
                "The input value is not a number for the column/header 'count'",
                "The input value is not a number for the column/header 'eventId'",
                "The input value is not a number for the column/header 'expire_time'"
            ],
            "datatype_check": false
        },
        "datatype_check": false,
        "exactness_check": true,
        "exactness_check_result": [],
        "headercount": {
            "headercount_check": false,
            "headercount_check_result": [
                "Expected header count is 7, but number of headers in the given input is 34"
            ]
        },
        "headercount_check": false,
        "headercount_check_result": [
            "Expected header count is 7, but number of headers in the given input is 34"
        ],
        "main": {
            "message": [
                "The input value is not a number for the column/header 'count'",
                "The input value is not a number for the column/header 'eventId'",
                "The input value is not a number for the column/header 'expire_time'"
            ]
        }
    }
}

**Comment by Vighi88** [comment]
I have got the Categorization requirement worked with minor tweaks. 

Thanks all for your support
