### ISSUE TITLE
How to use Schema feature via REST API to perform Type Checking?

### ISSUE THREAD

**Issue by Vighi88** [open-policy-agent/opa#4683]
Dear All ,

I have a requirement to validate all the the input data's datatype and return false if the datatype is different from the expected datatype. 

I have gone through the OPA documentation and found that the Schema feature will help in this case . However , i could see commands like " opa eval --format pretty data.example.public_server -i opa-example/input.json -d opa-example/example.rego -s opa-example/input-schema.json" 

But unable to see any examples by making use of this feature via REST API calls . 

Does anyone has any idea whether the Schema feature can be used via REST API's to perform type checking on the Input data 

Some Reference links as below : 
 https://github.com/aavarghese/opa-schema-examples
https://www.openpolicyagent.org/docs/edge/schemas/#usage-scenario-with-a-single-schema-file

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/issues/3341 like this? It's not supported right now.

**Comment by Vighi88** [comment]
Yeah exactly the same . Thanks for letting me know

**Comment by srenatus** [comment]
OK I'll close this as duplicate then. :+1: Please watch out for the other issue, #3341.

**Comment by Vighi88** [comment]
Sure .👍 Between do we any workaround for type check?

**Comment by anderseknert** [comment]
Types will commonly be checked implictly in the conditions building the rules of your policy. A simple condition like e.g.
```rego
allow {
    "admin" in input.user.roles
}
```
will only ever match if "admin" is a string value contained in the user roles. If there are other values in there of some other type does not really matter. I think there are cases where type checking at runtime could be useful, but I'm no longer sure it should be made a part of the server — a new builtin function taking some data as input, along with a schema, and validated that would probably be a better option. That way there are no "decisions" made outside of the policy, which is essentially what the alternative would be. Given that we have JSON schema support in OPA already, such a builtin function would probably be fairly simple to add.
