### ISSUE TITLE
Strict-mode to phase-out the "single =" operator

### ISSUE THREAD

**Issue by ekcs** [open-policy-agent/opa#4688]
## What part of OPA would you like to see improved?

Newcomers to OPA have almost universally find the distinction between `=`, `:=`, and `==` confusing.
Even for experienced users, `=` is error-prone and difficult to maintain because a variable being bound in the containing scope can unintentionally change the meaning of a condition. It quietly behaves differently depending on whether a variable is already bound or not.

Example:
`allow {
  input.path = [path1, path2]
}` changes behavior if somewhere else in the same package `path1` becomes defined as a rule head.

## Describe the ideal solution
The community and the language design have both been evolving to disfavor `=` when `:=` or `==` can be used instead. Here is a proposal for finishing the job:

1. As of v0.40.0, `:=` can replace `=` completely in rule heads. Phase into strict-mode (or another check) the disallowing of `=` in rule head.
2. Extend `==` to behave the same way as `=` but require that every variable referenced is declared (unless it is the anonymous variable `_`). Example: `allow {some x, y; input.path == [x, y]}` would work, but `allow {input.path == [x, y]}` would not.
3. With the extension to `==`, there is no longer any real need for `=`. So phase-in a strict-mode check to disallow the use of `=` completely.

## Describe a "Good Enough" solution

One alternative:

- Don't extend `==`.
- Strict-mode requires the declaration of variables used in `=`. (Unless it is the anonymous variable `_`)

**Comment by srenatus** [comment]
Thanks for taking the time to think about this, and how to improve the current situation.

I'd be down to improving the documentation to move the discussion of the `=` operator for _explicit unification_ into some "advanced" section.

However, I'm sceptic about removing it. For one thing, unification is omnipresent, and having an explicit way to do it seems necessary to me.

I wouldn't blame the operator for the language's scoping rules.

> `allow { input.path = [path1, path2] }` changes behavior if somewhere else in the same package `path1` becomes defined as a rule head.

Yeah and there's `some path1, path2` to prevent that; or using `[path1, path2] := input.path` (as I'm sure you are well aware).

There are cases where it's desired to have a variable used with `=` **not** be fresh, although they might be rare:

```rego
package play

import future.keywords

mydata = [["a", 1], ["a", 2], ["b", 5], ["a", 10], ["b", 17]]

zipper := { k:  { v | some v; [k, v] = mydata[_] } | some [k, _] in mydata }
```

Also here's one thing we can't replace with `:=` just yet:
```rego
some day
[2022, _, day] = time.date(time.now_ns())
```
If `:=` allowed for "assignment to constants", that would become `[2022, _, day] := time.date(time.now_ns())` to declare and assign `day`.

**However**, that would muddy the distinction between `:=` and `=`. Your `==` extension proposal would overload `==` with unification properties it doesn't have right now. In my opinion, having three different operators for the three distinct concepts might not be the worst situation:

1. Assign a variable: `x := 42`
2. Compare two terms (of which one or both may be _bound_ variables): `x == y`
3. Explicit unification: `=` as we have it.

From my point of view, the clearer the distinction, the better: well-informed policy authors will have the right tool for the job. They may always be fine with `:=` and `==`; but maybe they want or need `=` every now and then, too. The docs and tooling should help new users to understand the distinction, and to pick the right operator for each use case.

**Comment by anderseknert** [comment]
Thanks for submitting this, Eric! It's been a rather frequent topic for discussion in recent times, with suggestions for both `opa check --strict` and `opa fmt` to better deal with this.

As for the examples above, rewritten versions without unification are IMHO not less comprehensible, but possibly more so.
```rego
# Comprehension indexing
zipper := {k: v |
    some i
    k := mydata[i][0]
    v := [n |
        some j
        mydata[j][0] == k
        n := mydata[j][1]
    ]
}
```
```rego
[year, _, day] := time.date(time.now_ns())
year == 2022
```
The latter has the additonal benefit of strict mode flagging `year` and `day` as unused (if applicable), which isn't going to be the case for the `some day` declaration, since that's not considered "assignment".

While there's no doubt unification _may_ be used for much, the examples presented in the docs or elsewhere, don't make a strong case for why or when it's _great_. I could imagine such a case being more advanced destructuring, but since that's not provided... 🤷 

With `:=` now serving most of the trivial use cases previously requring `=`, there's definitely a case to be made for scrapping `=` entirely. Obviously not going to happen for OPA pre-1.0, but having strict mode deal with it as a violation might be a reasonable way forward 🤔

If I'm wrong and there actually are cases where unification clearly simplifies some not too far-fetched use cases, we should update the docs to include those.

**Comment by srenatus** [comment]
> As for the examples above, rewritten versions without unification are IMHO not less comprehensible, but possibly more so.

Nit: Without explicit unification. The snippet surely unifies `i` and `j` with different indices of `mydata`. 🙃 

> While there's no doubt unification may be used for much, the examples presented in the docs or elsewhere, don't make a strong case for why or when it's great. I could imagine such a case being more advanced destructuring, but since that's not provided... 🤷

I don't think the docs should tell you _why it's great_ -- and I'm not claiming that you can't be effective with the `:=` and `==` subset of Rego.

But I do think that the individual author's background and experience matters when they approach Rego. Anyone with a logic programming background will not feel at home without explicit unification. After all, you _can_ do perfectly fine (and safe) with Rego with `some` and `=` alone.

To be welcoming to everyone, I think we should _not_ remove `=`. Changing the documentation and tooling to make sure that beginners are spared as many pitfalls as possible? Sure thing.

**Comment by anderseknert** [comment]
> Nit: Without explicit unification. The snippet surely unifies `i` and `j` with different indices of `mydata`. 🙃

Right, `=` is what's suggested for phase-out here. I'm not sure the equivalent `some i, k` construct would provide comprehension indexing, but if does, sure — that would have been preferable.

> I don't think the docs should tell you _why it's great_ 

Why not? I can't think of anything that would work better to drive home an idea, especially not one new to most readers.

> Changing the documentation and tooling to make sure that beginners are spared as many pitfalls as possible? Sure thing.

Yep, that's where we'd need to start. But unless there's a compelling case for `=`, and this is on the other side of the weight:

> Newcomers to OPA have almost universally find the distinction between =, :=, and == confusing.

🤷

**Comment by anderseknert** [comment]
Agreed. A Rego Style Guide is in the making :) And while we might not realistically remove `=` from the language, I think the [proposed linter](https://github.com/open-policy-agent/opa/issues/3218) would be a good place to flag its use. We'd have more freedom in our recommendations in that context, and would not be limited to features bound for removal at some point, like strict mode currently targets.

**Comment by ekcs** [comment]
> Agreed. A Rego Style Guide is in the making :) And while we might not realistically remove `=` from the language, I think the [proposed linter](https://github.com/open-policy-agent/opa/issues/3218) would be a good place to flag its use. We'd have more freedom in our recommendations in that context, and would not be limited to features bound for removal at some point, like strict mode currently targets.

Thank you Stephan and Anders for the discussion! Yes, I would love to see a general linter guidance to warn against any unbound variable introduced without declaration. I'll suggest this in the draft style guide, Anders.

Examples:
```rego
allow {
    input.roles[role]  # warn against this usage because it's easy accidentally change meaning if role gets defined in outer scope
    data.admin.roles[role]
}
```

```rego
allow {
    some role
    input.roles[role]  # this is ok
    data.admin.roles[role]
}
```

```rego
role := "admin" {
  ...
}

allow {
    input.roles[role]  # this is ok
    data.admin.roles[role]
}
```

This kind of warning I think would fix the biggest pitfall with `=`. Of course it's not specific to `=`, but really any construct that allows introducing a new variable without declaration.

**Comment by ekcs** [comment]
> However, I'm sceptic about removing it. For one thing, unification is omnipresent, and having an explicit way to do it seems necessary to me.
> 
> I wouldn't blame the operator for the language's scoping rules.
> 
> > `allow { input.path = [path1, path2] }` changes behavior if somewhere else in the same package `path1` becomes defined as a rule head.
> 
> Yeah and there's `some path1, path2` to prevent that; or using `[path1, path2] := input.path` (as I'm sure you are well aware).
> There are cases where it's desired to have a variable used with `=` **not** be fresh, although they might be rare:
> 
> ```rego
> package play
> 
> import future.keywords
> 
> mydata = [["a", 1], ["a", 2], ["b", 5], ["a", 10], ["b", 17]]
> 
> zipper := { k:  { v | some v; [k, v] = mydata[_] } | some [k, _] in mydata }
> ```
> 
@srenatus Agreed that the operator is not to blame. A linting rule I suggest in comment above would help avoid this pitfall but still allow the example you show.

> **However**, that would muddy the distinction between `:=` and `=`. Your `==` extension proposal would overload `==` with unification properties it doesn't have right now. In my opinion, having three different operators for the three distinct concepts might not be the worst situation:
> 
> 1. Assign a variable: `x := 42`
> 2. Compare two terms (of which one or both may be _bound_ variables): `x == y`
> 3. Explicit unification: `=` as we have it.
> 
> From my point of view, the clearer the distinction, the better: well-informed policy authors will have the right tool for the job. They may always be fine with `:=` and `==`; but maybe they want or need `=` every now and then, too. The docs and tooling should help new users to understand the distinction, and to pick the right operator for each use case.

Thank you for explaining your point of view! I do see what you are saying and understand there is no desire to collapse the three operators into two.

Just for completeness, I'll elaborate a different perspective a bit more. Consider these examples:

```rego
# (1)
allow {
  some user
  input.path[1] == data.path_map[user]
  is_admin(user)
}
```

```rego
# (2)
allow {
  some user
  input.path[1] == user
  is_admin(user)
}
```
The first works in Rego, but the second fails the safety check according to traditional datalog definition because `==` is not an extensional table. But in the context of Rego, there seems to be no practical reason to prevent this kind of thing. In both examples, the intent is clear and natural. The finiteness is syntactically established (already implemented for `=`). Someone not trained in datalog would find it strange when they go from (1) to (2) and find a safety check fail.

So I think it makes sense for Rego to relax its safety check for `==` to permit this type of usage, but still reject using `==` to introduce a brand new variable.
And if we do relax the safety check this way, then the following (3) is also permissible, clear, natural, and provably finite.

```rego
# (3)
allow {
  some user
  input.path == ["users", user]
  is_admin(user)
}
```

At this point, the only time to use `=` over `==` would be to introduce a brand new variable not already existing in the current scope or in the containing scopes. But we want people to explicitly introduce new variables using `some` or `:=` anyway. So then there is not a reason to recommend using `=`.

A prolog programmer may find this strange because (as I'm sure you know) in Prolog `==` and `=` can lead to very different executions and different outcomes.

But Rego is different. It is more purely declarative, and there is no semantic difference between `==` and `=`. The only current difference is an artificial difference in safety checking.

In the long term, I would love to see the community recommend only `:=` and `==`. The clear difference is that `:=` declares a variable while `==` one does not. These two things would be very clear and natural to most programmers.

Another perspective: I believe in early Rego, there was just `=`. No `:=` and no `==`. But many procedural programmers found this confusing because assignment and comparison feel fundamentally different in procedural programming. It is confusing that doing comparison using `=` has the side-effect of introducing new variables without declaration. So `:=` and `==` were introduced as special cases of `=`.

My proposed relaxation of safety checking for `==` would still preserve this distinction between `:=` which declares a new variable and `==` which requires all variables used be declared (either in current scope of containing scopes).

**Comment by anderseknert** [comment]
@ekcs I've included recommendations on this in the Rego style guide [here](https://github.com/StyraInc/rego-style-guide#dont-use-unification-operator-for-assignment-or-comparison). I think that's probably the best we can do, given backwards compatibiity concerns, and the other points made above. If there's something you think should be added to that guide, PRs are welcome :)

OK to close this issue?

**Comment by ekcs** [comment]
> @ekcs I've included recommendations on this in the Rego style guide [here](https://github.com/StyraInc/rego-style-guide#dont-use-unification-operator-for-assignment-or-comparison). I think that's probably the best we can do, given backwards compatibiity concerns, and the other points made above. If there's something you think should be added to that guide, PRs are welcome :)
> 
> OK to close this issue?

Thank you @anderseknert !

**Comment by ekcs** [comment]
> @ekcs I've included recommendations on this in the Rego style guide [here](https://github.com/StyraInc/rego-style-guide#dont-use-unification-operator-for-assignment-or-comparison). I think that's probably the best we can do, given backwards compatibiity concerns, and the other points made above. If there's something you think should be added to that guide, PRs are welcome :)
> 
> OK to close this issue?

Thank you @anderseknert !
