### ISSUE TITLE
docs: Include part of grammar is incorrect

### ISSUE THREAD

**Issue by mmzeeman** [open-policy-agent/opa#4689]
## Include part of grammar is wrong

https://www.openpolicyagent.org/docs/latest/policy-reference/#grammar

Defines import rules as:

```ebnf
module  = package { import } policy
package = "package" ref
import  = "import" package [ "as" var ]
```

Which means that include rules should look like this:

```rego
package test.package

import package test.include 

...
```

But in practice the `package` part is always omitted.

Should the import rule be `import = "import" ref [ "as" var ]` instead?

**Comment by srenatus** [comment]
There's no such thing as `import package data.foo`. I think the grammar is just wrong. Would you be up to fixing it in a PR? Your suggestion seems alright 👍
