### ISSUE TITLE
docs: Grammar rule for ref includes too many things.

### ISSUE THREAD

**Issue by mmzeeman** [open-policy-agent/opa#4692]
## Grammar rule for ref includes way too many things.

The grammar rule for refs is:

```ebnf
ref             = ( var | array | object | set | array-compr | object-compr | set-compr | expr-call ) { ref-arg }
```

I don't know rego that well, but I don't think you want to be able to use array comprehensions as package ref or imports. 

I'm not sure how to fix this. In the examples I only see `var { "." var }`.

**Comment by srenatus** [comment]
I think there'are two things going on here: I think it's true that a ref can contain a comprehension, see this:

```rego
package x

p {
	{a | a := [1][_]}[0]
}
```
👇 
```
$ opa parse parse.rego 
module
 package
  ref
   data
   "x"
 rule
  head
   p
   true
  body
   expr index=0
    ref
     setcomprehension
      a
      body
       expr index=0
        ref
         assign
        a
        ref
         array
          1
         _
     0
```

But it's also true that you cannot use them in `package` definitions. However, there's more to `package` than `var { "." var }`, e.g.
```rego
package x["foo-bar"].y
```

I don't think the grammar is meant to capture only valid programs.  However, I think we'd do well if programs that match the grammar would not yield `rego_parse_error`s, but only other types of errors. Right now, that's no the case, as you rightly pointed out:

```
1 error occurred: parse.rego:1: rego_parse_error: unexpected number token: expecting string
 package x["foo-bar"].y[0]
```

**Comment by srenatus** [comment]
I'll clean this up
