### ISSUE TITLE
cherry-pick and release v0.39.1 for gatekeeper

### ISSUE THREAD

**Issue by thomasmckay** [open-policy-agent/opa#4711]
cherry-pick https://github.com/open-policy-agent/opa/commit/e9d3828db670cbe11129885f37f08cbf04935264 and release v0.39.1

gatekeeper-3.8 relies on opa-0.39, rather than bumping to opa-0.40 in a 3.8.z it would be better to have the fix backported

Thoughts?

**Comment by tsandall** [comment]
We'd recommend just updating to v0.40.0. Is there something in v0.40.0 that you're particularly worried about?

**Comment by thomasmckay** [comment]
Nothing specific but bumping to a y-stream in the underlying core tech could be perceived as "risky". A y-stream bump to `opa` would be better consumed in a y-stream of `gatekeeper`. In the community meeting there wasn't strong pushback against bumping `opa` but for future reference, should consumers of `opa` not expect cve/bug backports? Is there a doc on the threshold?

**Comment by tsandall** [comment]
If GK can update to 0.40 that's preferable. We don't provide a backport guarantee today--but that's not to say we can't do it, e.g., in this case, if there are specific needs for a v0.39.1 release, we're happy to do it.

**Comment by tsandall** [comment]
@ritazh @willbeason is GK 3.8 going to update to v0.40?

**Comment by willbeason** [comment]
@tsandall I don't think there's any danger in upgrading GK 3.8 to v0.40 in a patch release. I don't have a good understanding of the need for a v0.39.1 release. If there were a specific reason to not upgrade to v0.40 in a patch release, that would be compelling, but in the absence of anything specific it's hard to justify.

I have a PR out for upgrading (future) GK 3.9 to v0.40: https://github.com/open-policy-agent/gatekeeper/pull/2069

**Comment by anderseknert** [comment]
OK to close this now?

**Comment by willbeason** [comment]
@thomasmckay @maxsmythe ?

**Comment by srenatus** [comment]
Looks like it's OK to close? We can always re-open 🧹
