### ISSUE TITLE
Creating a signed bundle implicitly signs a .manifest file even when one doesn't exist

### ISSUE THREAD

**Issue by friedrichsenm** [open-policy-agent/opa#4712]
## Short description 

When running `opa build` to create a signed bundle against a directory that doesn't include a `.manifest` file, OPA create a signature over a phantom `.manifest` file and you won't be able to load or verify the bundle and will get the error:
`error: load error: bundle example.tar.gz: file(s) [.manifest] specified in bundle signatures but not found in the target bundle`

## Steps To Reproduce

(requires PEM private and public keys for signing and verification, respectively)
1. Create a directory `dir` with a data file and a policy file (say `data.json` and `policies.rego`)
2. Create a signed bundle using that directory as the source `opa build -b dir -o example.tar.gz --signing-key signing.key`
3. Try to verify the bundle `opa build -b example.tar.gz --verification-key signing.pub`

## Expected behavior

I would expect bundle loading/verification to succeed even if there wasn't a `.manifest` file in the original directory or for a generic `.manifest` to be created in the `.tar.gz` file and used in the signing process.

Based on the [Bundle File Format](https://www.openpolicyagent.org/docs/latest/management-bundles/#bundle-file-format) link, I would expect that the `.manifest` should not be included if it isn't present.

## Additional context

It appears the problem comes from here:
https://github.com/open-policy-agent/opa/blob/643eacd0ca19bb704e7e8de7ed307bc25b9e9a54/bundle/bundle.go#L854-L870

**Comment by ashutosh-narkar** [comment]
The fix could be to only include the manifest if it's non-empty. Something like below should fix this. If you'd like to contribute we'd be happy to help.

```go
if !b.Manifest.Equal(Manifest{}) {
  mbs, err := json.Marshal(b.Manifest)
  if err != nil {
	  return files, err
  }
  
  var result map[string]interface{}
  if err := util.Unmarshal(mbs, &result); err != nil {
	  return files, err
  }
  
  bs, err = hash.HashFile(result)
  if err != nil {
	  return files, err
  }
  
  files = append(files, NewFile(strings.TrimPrefix(ManifestExt, "/"), hex.EncodeToString(bs), defaultHashingAlg))
}
```

**Comment by friedrichsenm** [comment]
I'd be happy to take a crack at it.
Looking at this piece in `initBundle()`, it seems that if you did have a `.manifest` file that had roots set to just the empty string then maybe it wouldn't be picked up.
https://github.com/open-policy-agent/opa/blob/cb6a4c0b725c3569b6a6adf4f549c86cafec3bea/compile/compile.go#343-#L348

I'll have to test it out to see if it causes problems. If it does, the solution might be to create a `.manifest` file before creating the tarball if one doesn't exist.
