### ISSUE TITLE
Terminus Software has adopted OPA

### ISSUE THREAD

**Issue by charlieflowers** [open-policy-agent/opa#4713]
### Organization Name

Terminus Software, Inc.

### Organization Website

terminus.com

### Organization Logo (optional)

https://b2s2w3e9.rocketcdn.me/wp-content/uploads/2021/12/Terminus-Logo.svg

### How is your organization using OPA?

Microservice authorization

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by anderseknert** [comment]
Thanks @charlieflowers! I'll have you added to the ADOPTERS.md file :) Could you provide me a link to your web site, and perhaps a few words on how, or in what type of environment, you're using OPA for authorization?

You can see the current entries [here](https://github.com/open-policy-agent/opa/blob/main/ADOPTERS.md).
