### ISSUE TITLE
Make configuration of /metrics http request/response logging

### ISSUE THREAD

**Issue by yortch** [open-policy-agent/opa#4731]
We are using OPA Agent version 0.49. We have prometheus enabled with log-level set to info. We have a ServiceMonitor that is scraping metrics from the "/metrics" endpoint. Scraping interval is set at 15 seconds and we cannot make it much less infrequent. However the problem at hand is that our logs are becoming too verbose because these entries are INFO level. We would like a way to make disable entries for the /metrics endpoint or perhaps these entries should be logged only at debug level.

Sample entries from OPA agent log:

{"client_addr":"<ip:port>","level":"info","msg":"Received request.","req_id":14,"req_method":"GET","req_path":"/metrics","time":"2022-06-02T15:17:26Z"}
{"client_addr":"<ip:port>","level":"info","msg":"Sent response.","req_id":14,"req_method":"GET","req_path":"/metrics","resp_bytes":2940,"resp_duration":1.281055,"resp_status":200,"time":"2022-06-02T15:17:26Z"}

**Comment by anderseknert** [comment]
Hi @yortch! 

Is there any particular reason you want to log at INFO level? Our usual recommendation is to log at ERROR level for production environments, and use the [decision logging](https://www.openpolicyagent.org/docs/latest/management-decision-logs/) capabilities of OPA to send decision logs to a remote server / control plane.

The access logs are generally noisy, and I think that even at INFO level, we might want to provide an option to have those turned off.

**Comment by yortch** [comment]
There are some info level entries that we’d like to preserve, for instance bundle loading entries. INFO level seems to be working for us in terms of verbosity except for these metrics entries. Since this customer is adopting OPA for the first time they feel more comfortable going live with INFO level and will consider changing to WARN later on.

Thank you,
Jorge

**Comment by yortch** [comment]
Yes, disabling the access logger should be a viable solution.

Thank you,
Jorge

**Comment by yortch** [comment]
Another viable solution could be to allow writing the access logs into a separate log file.

Thank you,
Jorge

**Comment by ashutosh-narkar** [comment]
Closing this in favor of https://github.com/open-policy-agent/opa/issues/4744
