### ISSUE TITLE
Trace should include expression and value

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/opa#474]
When viewing the trace, today we see the expressions that are involved, but it's valuable to see both the expression and the value that expression has.  For example, the trace below shows `data.repl.p[1] > 20`, `data.repl.p[2] > 20`, ..., but we don't know what `data.repl.p[1]` evaluates to.

```
> p = [17, 34, 6, 5, 51, 19]
> q { p[i] > 20 }
> trace
> q
Enter data.repl.q = _
| Eval data.repl.q = _
| Enter q = true
| | Eval data.repl.p[i] > 20
| | Enter p = [17, 34, 6, 5, 51, 19]
| | | Eval true
| | | Exit p = [17, 34, 6, 5, 51, 19]
| | Fail data.repl.p[0] > 20
| | Redo data.repl.p[0] > 20
| | Exit q = true
| Redo q = true
| | Redo data.repl.p[1] > 20
| | Fail data.repl.p[2] > 20
| | Redo data.repl.p[2] > 20
| | Fail data.repl.p[3] > 20
| | Redo data.repl.p[3] > 20
| | Exit q = true
| Redo q = true
| | Redo data.repl.p[4] > 20
| | Fail data.repl.p[5] > 20
| Exit data.repl.q = _
true
```

**Comment by tsandall** [comment]
Closing this for now because we know that simply plugging all of the vars in the expressions is going to generate too much noise and more sophisticated trace visualization/representation requires much more design/thought.
