### ISSUE TITLE
Update OPA version within the OPA-Envoy plugin from 0.40.0 to 0.41.0

### ISSUE THREAD

**Issue by ramezmoussa** [open-policy-agent/opa#4740]
Currently, the latest version of the OPA-Envoy plugin uses OPA version 0.40.0 which results in an ' OPA is out of date.' message whenever it receives a request. Can you please update OPA's version in the plugin to match the latest release and consequently avoid this problem?

Thanks in advance!

**Comment by ashutosh-narkar** [comment]
OPA-Envoy plugin [v0.41.0](https://github.com/open-policy-agent/opa-envoy-plugin/releases/tag/v0.41.0-envoy) released.
