### ISSUE TITLE
not: expression expansion leads to unexpected evaluation results

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4743]
In this snippet, evaluated with an empty input,

```rego
package play

obj := {}
c {
    not obj[input.key_not_present]
}
```

it's to be expected that the result is `c = true`. However, because the compiler rewrites it to
```rego
c = true {
    __local1__ = input.key_not_present
    not data.play.obj[__local1__]
}
```
we instead get `undefined`. This is with or without rule indexing, but with rule indexing, we furthermore don't get any rules returned from the lookup because of `__local1__ = input.key_not_present` not being met.

I think the problem is in expression expansion: when `not obj[input.key_not_present]` is expanded, `expr.Negated` is not taken into account at all. Similar issues exist with negating function calls, `not f(input.key_not_present)`.

**Comment by anderseknert** [comment]
Looks like this has been reported before: https://github.com/open-policy-agent/opa/issues/1877

**Comment by srenatus** [comment]
Yeah. I thought so but didn't find it. Closing as duplicate. Thanks!
