### ISSUE TITLE
Add errcheck to automated PR checks

### ISSUE THREAD

**Issue by philipaconrad** [open-policy-agent/opa#4765]
## What part of OPA would you like to see improved?

Adding `errcheck` ([Github repo link](https://github.com/kisielk/errcheck)) to the automated PR checks for OPA would allow us to detect cases where we've forgotten to do something with an error, and provides yet another safeguard against subtle bugs.

Naive usage of the tool generates a lot of chaff, but when used on specific packages, and with tests ignored (`-ignoretests`), it generates pithy and useful reports about unhandled errors.

Usage example (commit f137da2):
```bash
$ errcheck -ignoretests github.com/open-policy-agent/opa/topdown
topdown/http.go:719:25:	defer result.Body.Close()
topdown/trace.go:237:15:	fmt.Fprintln(w, formatEvent(event, depth))
topdown/trace.go:253:14:	fmt.Fprintf(w, "%-*s %s\n", locationWidth, location, formatEvent(event, depth))
```

## Describe the ideal solution

 - Clean up existing unhandled error cases in OPA's packages.
 - Create a list of modules we'd like `errcheck` to report on.
 - Add `errcheck` to the automated PR checks list. (With module-specific targets, and `-ignoretests` on.)

## Describe a "good enough" solution

  - Clean up existing unhandled error cases in OPA's packages.
  - Document `errcheck` workflow in the "Development" docs.

## Additional Context

@charlesdaniels originally pointed this issue out with an obscure nil pointer deref bug in OPA that could've been caught if a nearby unhandled error was dealt with immediately vs being ignored.

**Comment by srenatus** [comment]
Is this repackaged in golangcihlint?

**Comment by philipaconrad** [comment]
| Is this repackaged in golangcihlint?

Yes, apparently it is available in golangci, according to their [linters][golangci-linters] page. :smiley: 

[golangci-linters]: https://golangci-lint.run/usage/linters

**Comment by charlesdaniels** [comment]
The way I have dealt with false positives (cases where we really don't care about errors) in my personal projects has been to just use `_ := somefunc()` to explicitly discard the error. I think that's clearer anyway.

I'd also suggest [ineffassign](https://github.com/gordonklaus/ineffassign), as this will catch cases where there are variables that are assigned but never checked.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/blob/main/.golangci.yaml#L13

Perhaps we should check why this hasn't been raised. Both errcheck and ineffassign (which I like, too!) are enabled.

**Comment by philipaconrad** [comment]
It's possible it's only linting the top-most module, or has whacky default configuration settings?

**Comment by philipaconrad** [comment]
This is very odd because if I run `golangci-lint run -v` locally at the root of the OPA repo, I get errors, but `make check` (which *should* be running `golangci-lint` internally!) doesn't generate any error output.

**Comment by philipaconrad** [comment]
@srenatus So, apparently `golangci/golangci-lint:v1.45.2` changed something in how they do their checks. The diff in errors from even `golangci/golangci-lint:v1.45.0` is substantial, and gets us entirely new error output. (For reference: `make check` uses `golangci/golangci-lint:v1.43.0`)

I was seeing noticeable differences in running `golangci-lint` locally because my local copy was at `v1.45.2`.

**Comment by srenatus** [comment]
IIRC there's a "patch-only" mode? So, we could use 1.45.0 and only have it raise errors introduced in PRs..?

**Comment by srenatus** [comment]
Or rather, how large is the number? We could divide and conquer.
