### ISSUE TITLE
gopkg.in/yaml.v2 deprecated or not supported

### ISSUE THREAD

**Issue by rajeev159** [open-policy-agent/opa#4818]
## Short description 
I am trying to use this package in my go project.
While installing this package, I am getting following error...
go: finding module for package gopkg.in/yaml.v2
example/hello imports
	github.com/open-policy-agent/opa/rego imports
	github.com/open-policy-agent/opa/ast imports
	gopkg.in/yaml.v2: module gopkg.in/yaml.v2@latest found (v2.4.0), but does not contain package gopkg.in/yaml.v2

My Go version is 1.18
opa version: v0.41.0

Statement in go file to import opa: import "github.com/open-policy-agent/opa/rego"
Command to install: go mod tidy

Please help to fix this issue.

**Comment by srenatus** [comment]
Please clarify: Using `go mod tidy` doesn't work or is it something you don't want to do?

**Comment by rajeev159** [comment]
It throws error if i use go mod tidy.
go clean -modcache this command fixed the issue.

Thanks
