### ISSUE TITLE
Decision Log API improvements

### ISSUE THREAD

**Issue by chicco785** [open-policy-agent/opa#4820]
We have implemented an API to receive Decision Logs client calls,
and we found out that:
- only 200 is accepted as value (while logically 201 should be also fine)
- in case of value returned different from 200, the client infinitely attempts to send the logs, this risks to make the API (and probably also OPA) going in overload. The possibility to configure an exponential backoff with a limited number of retries, would be a more solid solution.

**Comment by anderseknert** [comment]
Accepting a 201 response... yeah, maybe :)

As for backoff, that should be there [already](https://github.com/open-policy-agent/opa/blob/main/plugins/logs/plugin.go#L680). Did you find that not working? "Limited number of retries" sounds good to me — the question is what to do with the logs in OPA when that happens? There's already the option to discard logs, but it would be good to have another option as well, like either a fallback service, or persisting logs to disk while waiting for the remote to come up. There are a few issues open on [that topic](https://github.com/open-policy-agent/opa/issues?q=is%3Aissue+is%3Aopen+decision+logging), but more ideas are always welcome!

**Comment by srenatus** [comment]
2xx responses was done recently. Cleaning this up.
