### ISSUE TITLE
rego_parse_error thrown for example tests from documentation

### ISSUE THREAD

**Issue by robert-elles** [open-policy-agent/opa#4849]
Hi,

I am following the documentation for [Policy Testing](https://www.openpolicyagent.org/docs/latest/policy-testing/)
and as in the documentation I created the two files with their contents: example.rego and example_test.rego.
To run the tests you are supposed to run `opa test . -v` in the folder where the rego files are. So I do this via docker:
`docker run -v $PWD:/tests openpolicyagent/opa:0.42.0-static test /tests -v`
The result output is:
_/tests/example.rego:4: rego_parse_error: var cannot be used for rule name
/tests/example.rego:9: rego_parse_error: var cannot be used for rule name
/tests/example_test.rego:3: rego_parse_error: var cannot be used for rule name
/tests/example_test.rego:7: rego_parse_error: var cannot be used for rule name
/tests/example_test.rego:11: rego_parse_error: var cannot be used for rule name
/tests/example_test.rego:15: rego_parse_error: var cannot be used for rule name_

So it looks like opa test isn't able to run the tests from its own documentation.
What is wrong here?

**Comment by srenatus** [comment]
Thanks for the report! Well likely push a 0.42.1 soon, if this gets fixed quickly, it'll be part of it. Would you be up to giving it a go?

**Comment by srenatus** [comment]
☝️ Taken care of it. We had been missing some future.keyword imports (and the error messages could use more hints...)
