### ISSUE TITLE
Improve re_match built-in function docs to refer to raw strings

### ISSUE THREAD

**Issue by jc-m** [open-policy-agent/opa#485]
There is a weird behavior that may be a bug, or in need of documenting:
```
> re_match("\*", "aa*")
|
1 error occurred: 1:12: rego_parse_error: no match found, expected: "u" or [ " \\ / b f n r t ]
```
while this works:
```
> re_match("\\*", "aa*")
true
```
I have not tested if this cause other issues in the regexp specification.

**Comment by tsandall** [comment]
Strings are defined as JSON strings, so the you need to escape backslashes. The docs should be improved to refer to the raw string support when referring to regex patterns.

Regex functions described here: http://www.openpolicyagent.org/docs/language-reference.html#strings

Raw strings described here: http://www.openpolicyagent.org/docs/how-do-i-write-policies.html#strings

**Comment by tsandall** [comment]
The above example can be written using raw strings as: ```re_match(`\*`, "aa*")```

**Comment by jc-m** [comment]
Doc in the string section is clear - it may be more of a RTFM issue. Feel free to close.
