### ISSUE TITLE
Migrating chewong/gatekeeper-external-data-provider to open-policy-agent

### ISSUE THREAD

**Issue by chewong** [open-policy-agent/opa#4893]
Hi All. I am a maintainer of https://github.com/open-policy-agent/gatekeeper and several Gatekeeper-related projects under the open-policy-agent GitHub organization. I am also one of the main contributors to Gatekeeper's [external data](https://open-policy-agent.github.io/gatekeeper/website/docs/externaldata) feature. It is a highly-requested feature that allows users to write rego policies in Gatekeeper that incorporate data from external sources.

I created https://github.com/chewong/gatekeeper-external-data-provider to address https://github.com/open-policy-agent/gatekeeper/issues/1695. It is a template repository that allows users to create custom external data provider projects from scratch. It is currently in good shape and I am planning to transfer the ownership to the open-policy-agent GitHub organization so the community can continue contributing to it.

To move forward we need to:

* [x] Hold a vote amongst the OPA maintainers (the process is outlined in the GOVERNANCE.md file).
* [x] Create a [gatekeeper-external-data-provider-maintainers](https://github.com/orgs/open-policy-agent/teams/gatekeeper-external-data-provider-maintainers) team on GitHub
* [x] Transfer the chewong/external-data-provider repo into the open-policy-agent organization
* [x] Ensure that DCO check is enabled on the repo
* [x] Add a security notice on the action repo pointing back to SECURITY.md

**Comment by chewong** [comment]
Tagging Gatekeeper's maintainers @maxsmythe @ritazh @sozercan

**Comment by ritazh** [comment]
+1

**Comment by chewong** [comment]
> should we start the repo name with `gatekeeper-`?

Done!

**Comment by maxsmythe** [comment]
+1

**Comment by ritazh** [comment]
bump @timothyhinrichs @tsandall

**Comment by tsandall** [comment]
+1

**Comment by tsandall** [comment]
I've created the team, who should be added aside from @ritazh and @chewong ?

**Comment by tsandall** [comment]
Alright! All the steps have been taken care of. Thanks all!
