### ISSUE TITLE
Delta bundle and multiple bundle documentation gap

### ISSUE THREAD

**Issue by vas-rus** [open-policy-agent/opa#4895]
Hi Team,
I am solving a problem that along with data.json of policy there are additional fields from user configuration that I want to be available for rego file processing. I found that Delta bundles can be used for same. Can someone guide me how to create config and use delta bundle for same. The document currently doesn't have this option for those, who are just starting with opa.
A simple config along with delta bundle will be helpful.
Moreover there is written one more way like configuring two bundles in "roots". If someone can put light there also.

**Comment by srenatus** [comment]
https://github.com/orgs/open-policy-agent/discussions/240 using discussions was a good idea, let's keep it there
