### ISSUE TITLE
build(deps): OTel 1.11.0

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4901]
There are a bunch of related modules that should be updated to stay on top of this. Since the number of PRs are annoying and I'd rather take care of the bump in a single bump PR, I've closed the dependabot PRs:

[[opa]](https://github.com/open-policy-agent/opa) The branch "dependabot/go_modules/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc-1.8.0" was deleted by dependabot[bot]
[1:43](https://openpolicyagent.slack.com/archives/CMH9GCJFM/p1658144596680499)
[[opa]](https://github.com/open-policy-agent/opa) The branch "dependabot/go_modules/go.opentelemetry.io/otel-1.8.0" was deleted by dependabot[bot]
[1:43](https://openpolicyagent.slack.com/archives/CMH9GCJFM/p1658144596762759)
[[opa]](https://github.com/open-policy-agent/opa) The branch "dependabot/go_modules/go.opentelemetry.io/otel/trace-1.8.0" was deleted by dependabot[bot]
[1:43](https://openpolicyagent.slack.com/archives/CMH9GCJFM/p1658144596839459)
[[opa]](https://github.com/open-policy-agent/opa) The branch "dependabot/go_modules/go.opentelemetry.io/otel/exporters/otlp/otlptrace-1.8.0" was deleted by dependabot[bot]
[1:43](https://openpolicyagent.slack.com/archives/CMH9GCJFM/p1658144596916579)
[[opa]](https://github.com/open-policy-agent/opa) The branch "dependabot/go_modules/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp-0.33.0" was deleted by dependabot[bot]

**Comment by srenatus** [comment]
😅

**Comment by anderseknert** [comment]
Currently blocked as one dependency requires Go 1.18 ... once Go 1.20 is out, we can proceed with #5542
