### ISSUE TITLE
ast/compiler: retain unprocessed parsed modules

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4910]
It would sometimes be handy -- when using OPA via Go -- to be able to retrieve the modules that the compiler has worked on _in pristine state_. So far, the code flow goes like this:

1. `c.Modules` is a `map[string]*Module` of parsed `ast.Module` structs, as per the `ast` package's `ParseModule(string, string) (*Module, error)`
2. `c.Compile()` is run
3. `c.Modules` now contains the modules that have been rewritten by the various compiler stages

The enhancement here would be to add a new compiler options, e.g.

```go
func (c *Compiler) WithKeepModules(yes bool) *Compiler {
	c.keepModules = yes
	return c
}
```
and if it was provided during compiler setup, we'd copy the modules into `c.ParsedModules`, a `map[string]*Module` to add to the compiler struct.

**Comment by tsandall** [comment]
In addition, the ParsedModules map should include modules pulled in via the [module loader](https://github.com/open-policy-agent/opa/blob/54c09bf93ad9a9222d94cbfa687540eb52c75da9/ast/compile.go#L1429-L1448) callback.
