### ISSUE TITLE
result of opa-istio decision logs will be null after a period time

### ISSUE THREAD

**Issue by WellyHong** [open-policy-agent/opa#4918]
## Short description 
I deployed [opa-istio](https://www.openpolicyagent.org/docs/latest/envoy-tutorial-istio/) as a sidecar to k8s which is composed of istio envoy service mesh,
and I combine opa-istio with OPAL to update policy & policy data in realtime.
opa-istio serve well initially, but  after a while(half-day maybe) it shutdown because k8s liveness/readiness probe fail afterwards.
probe settings are `"initialDelaySeconds": 60`, `"periodSeconds": 15`, `"failureThreshold": 6`
I'm sure the authz.rego file has health setup like
```
# ------------------------------ health check ------------------------------
allow {
	input.parsed_path[0] == "health"
	request_http.method == "GET"
}
```

* OPA version: openpolicyagent/opa:latest-istio

## Expected behavior
opa-istio sidecar runs continuously

## Additional context
after some investigation, except decision log's `result: null`,
- there are some metrics like below:
```json
"metrics": {
    "counter_rego_builtin_http_send_interquery_cache_hits": 1, // after 1's fail, this value doesn't  log any more 
    "timer_rego_builtin_http_send_ns": 0, // no idea why it becomes 0
    "timer_rego_external_resolve_ns": 1000,
    "timer_rego_query_eval_ns": 199984289, // logner than successful time(e.g. 1436033)
    "timer_server_handler_ns": 200181694,  // logner than successful time(e.g. 1598337)
  },
```

- full log
```json
{
  "decision_id": "e9faae6f-9e4c-48dc-8b1c-ad193c04b283",
  "input": {
    "attributes": {
      "destination": {
        "address": {
          "socketAddress": {
            "address": "10.30.xx.xx",
            "portValue": 8282
          }
        }
      },
      "metadataContext": {},
      "request": {
        "http": {
          "headers": {
            ":authority": "10.30.xx.xx:8282",
            ":method": "GET",
            ":path": "/health?plugins",
            ":scheme": "http",
            "accept": "*/*",
            "user-agent": "kube-probe/1.23",
            "x-forwarded-proto": "http",
            "x-request-id": "d26cf2e4-725f-4705-8125-7096bdca882e"
          },
          "host": "10.30.xx.xx:8282",
          "id": "9491385769855241719",
          "method": "GET",
          "path": "/health?plugins",
          "protocol": "HTTP/1.1",
          "scheme": "http"
        },
        "time": "2022-07-19T18:02:32.933054Z"
      },
      "source": {
        "address": {
          "socketAddress": {
            "address": "10.30.xx.xx",
            "portValue": 47412
          }
        }
      }
    },
    "parsed_body": null,
    "parsed_path": [
      "health"
    ],
    "parsed_query": {
      "plugins": [
        ""
      ]
    },
    "truncated_body": false,
    "version": {
      "encoding": "protojson",
      "ext_authz": "v3"
    }
  },
  "labels": {
    "id": "4a272925-0d86-4c8b-a394-73a78133fd76",
    "version": "0.42.0-envoy"
  },
  "level": "info",
  "metrics": {
    "counter_rego_builtin_http_send_interquery_cache_hits": 1,
    "timer_rego_builtin_http_send_ns": 0,
    "timer_rego_external_resolve_ns": 1000,
    "timer_rego_query_eval_ns": 199984289,
    "timer_server_handler_ns": 200181694
  },
  "msg": "Decision Log",
  "path": "istio/authz",
  "result": null,
  "time": "2022-07-19T18:02:33Z",
  "timestamp": "2022-07-19T18:02:33.133749425Z",
  "type": "openpolicyagent.org/decision_logs"
}
```

**Comment by srenatus** [comment]
👀 thanks for the report.

So one thing: when a `http.send` query is used with caching, one of two things happens:

1. it's not in the cache, so the request is sent, and the response is the response of _that request_
2. it _is_ in the cache, so the request is not sent, and the response is taken _from the cache_

For (1.), you'll see
```
timer_rego_builtin_http_send_ns: <some positive number>
counter_rego_builtin_http_send_interquery_cache_hits: 0 (or maybe it's just omitted)
```

For (2.), you should see
```
timer_rego_builtin_http_send_ns: 0 (no request was sent)
counter_rego_builtin_http_send_interquery_cache_hits: 1 (or more, depending on your policy code)
```

So I think something is going on with your policy in that is related to `http.send`, and can't be gleamed from the snippet you've shared. If you only had that allow rule quote in the issue, none of this would happen, as _that rule's body_ doesn't use `http.send`.

Perhaps you can check the logs of the other system; or play with the `raise_error` option.

**Comment by WellyHong** [comment]
in the policy rego, I indeed use `http.send` to fetch jwks for request token validation, will dig into this point further. 
thank for you advice.

**Comment by WellyHong** [comment]
I adjust `http.send` usage conditions, the issue hasn't been happened  last 3 days, seems it was the root cause, will keep observation for a week.

**Comment by srenatus** [comment]
OK. I'll close this issue, we can reopen it if the problem appears again.

**Comment by ashutosh-narkar** [comment]
What is the `timeout` in your[ Envoy gRPC service configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice)? Try increasing that value when you're load testing and let us know if you still get the same issue.

**Comment by sudhirpandey** [comment]
@ashutosh-narkar  yeah so the `timeout` was 0.5s. We have adjusted that to be 0.9s and now we dont see `result:null` on previous stress test (cases)
But when we ramp up the load  we are seeing these occasional  failues , where metrics shows that api evaluation took more than 1sec
```
 metrics: { [-]
     timer_rego_builtin_http_send_ns: 0
     timer_rego_query_eval_ns: 148780234
     timer_server_handler_ns: 149033759
   }
```

```
metrics: { [-]
     timer_rego_builtin_http_send_ns: 0
     timer_rego_query_eval_ns: 356748975
     timer_server_handler_ns: 356964619
   }
```

We also tried to find some performance metrics related to our policy and when we run opa test -v.  locally , as described here 
https://www.openpolicyagent.org/docs/latest/policy-performance/

we see following test is taking a large chunk of time to get evaluated
```
data.test.test_is_jwt_token_signature_valid: PASS (630.556625ms)
```

our policy looks like this  
```
bearer_token := t {
    # Bearer tokens are contained inside of the HTTP Authorization header. This rule
    # parses the header and extracts the Bearer token value. If no Bearer token is
    # provided, the `bearer_token` value is undefined.
    v := input.attributes.request.http.headers.authorization
    startswith(v, "Bearer ")
    t := substring(v, count("Bearer "), -1)
}

# Get the token parsed from the bearer token read from the http header, its has three parts [header, payload, sign]
token := {"header": header, "payload": payload} {
    [header, payload, _] := io.jwt.decode(bearer_token)
}

# Query the the issuer wellknown endpoint to get the jwks url
metadata_discovery(issuer) := http.send({
    "url": concat("", [issuer, "/.well-known/openid-configuration"]),
    "method": "GET",
    "force_cache": true,
    "force_cache_duration_seconds": 86400, # Cache response for 24 hour
})

metadata := metadata_discovery(token.payload.iss)

# Construct the jwks url with rotated key, as the jwks can have multiple keys, hence using kid we got from jwt token
jwks_url := concat("?", [
    metadata.body.jwks_uri,
    urlquery.encode_object({"kid": token.header.kid}),
])

# Call jwks endpoint to get the jwks for verification
jwks_request(url) := http.send({
    "url": url,
    "method": "GET",
    "force_cache": true,
    "force_cache_duration_seconds": 3600, # Cache response for an hour
    "timeout": "20s",
})

jwks := jwks_request(jwks_url).raw_body

is_jwt_token_signature_valid {
    io.jwt.verify_es256(bearer_token, jwks)
}

is_jwt_token_signature_valid {
    io.jwt.verify_es384(bearer_token, jwks)
}

is_jwt_token_signature_valid {
    io.jwt.verify_es512(bearer_token, jwks)
}
```

So as per the test result `data.test.test_is_jwt_token_signature_valid: PASS (630.556625ms) ` and `timeout` configured in envoygrpcplugin (0.5s), we are very close to the limit where we would get fail most of the time when we donot use cache. So  I was wondering if there is any way  of we could optimise the above policy.  Most of the time is used by the this. 
```
io.jwt.verify_es512(bearer_token, jwks)
```
which in turn depends on 
```
http.send
```
So quite unsure how we can optimise the run/eval time of opa policy. 

For cached scenerio From metrics we saw `timer_rego_builtin_http_send_ns: 0` but ` timer_rego_query_eval_ns: 356748975`  when `result:null` was returned, Is there way to find/profile opa on runtime when we are throwing load at it and see, in which block its spending huge amount of time, ( like opa test we run locally), or the whole process is slow altogether.

Our end goal is to get reduced time when verfiy jwt using cached jwks.
