### ISSUE TITLE
glob.match without delimiters

### ISSUE THREAD

**Issue by vinhph0906** [open-policy-agent/opa#4923]
## Short description 
I used glob.match to valid path. However, without delimiters it will set default  `to ["."]`. Therefore, I fail the test case below:

## Steps To Reproduce

My rego looks like: 
`result := glob.match("test*",[],"test.txt")`

## Expected behavior
I expected output is `"result": true` but it is `"result": false`.

**Comment by srenatus** [comment]
I'm not sure I follow. From my understanding of globs, `test.txt` isn't matched by `test*` with delimiter `.` -- `test.*` would be a glob that matches `test.txt` with delimiter `.` 🤔

**Comment by vinhph0906** [comment]
if globs with delimiter `.` is as you understand. But if globs without delimiter [here](https://go.dev/play/p/6otp4NDZYNo), its matched.

**Comment by srenatus** [comment]
💡 Got it. So you'd expect `glob.match("test*", [], "test.txt")` to be _true_, but since if `delimiters` is empty, OPA will use `"."`, there's no way to have it use _no delimiters_.

Hmm I wonder how we could pull that off without breaking backwards-compatibility. I think it would have to be a new built-in, like `glob.match_no_delim(pattern, text)`? What do you think?

**Comment by vinhph0906** [comment]
Can I contribute to this function?

**Comment by anderseknert** [comment]
Would a simple `regex.match` not do the trick then? 🤔

**Comment by vinhph0906** [comment]
In the past, I have used regex for my rego. But I realized golang is not good with regex. You can see results in this [benchmark](https://github.com/mariomka/regex-benchmark). Then I use glob for this and my application latency goes down.

**Comment by srenatus** [comment]
> Can I contribute to this function?

Yeah sure, contributions are always welcome. I'm still not sure what the best name is here... 🤔 But we can discuss that later, too.

**Comment by anderseknert** [comment]
Fair enough @vinhph0906! Perhaps we could use `null` as the delimiter argument to say “use no delimiter” over adding another builtin function?

**Comment by vinhph0906** [comment]
In the `glob.match` function, `delimiters` is `array string` type. So I can't use `null` as `delimiters` argument.

**Comment by srenatus** [comment]
Not right now, but I think Anders meant that as a proposal for how to enhance that built-in instead of creating a new one. It's a good idea, I think.

**Comment by vinhph0906** [comment]
`delimiters` is `StringSlice` type, but in code, it is used as `RuneSlice`.  I think we can modify [the hander error](https://github.com/open-policy-agent/opa/blob/main/topdown/glob.go#L23) if it is `ArrayString` we say “use no delimiter”. What do you think?

**Comment by srenatus** [comment]
Yeah we can inspect the argument. There are examples of similar functions that work on multiple types, like `count`, I suppose.
