### ISSUE TITLE
Rule evaluation mismatch between `opa test` and kubernetes environment

### ISSUE THREAD

**Issue by dpiddock** [open-policy-agent/opa#4924]
## Short description 

We've noticed a rule evaluation mismatch between `opa test` and running in a Kubernetes environment. Where by the `opa test` cases will pass but the rule will not deny correctly when run in kubernetes. This appears to be related to a specific combination of a single element set "assigned" using the unification operator.

* OPA: 0.42.2
* kube-mgmt: 7.0.6
* Kubernetes: 1.21 (testing mainly done in minikube running k8s 1.21.14)

Sample rule:
```rego
package kubernetes.admission

deny[msg] {
    is_watched_operation
    msg := "Test CREATE fail"
}

is_watched_operation {
    operations = {
        "CREATE"
    }
    operations[input.request.operation]
}
```

Sample rego tests:
```rego
package kubernetes.admission

test_should_fail {
    msg := deny with input as {
        "request": {
            "operation": "CREATE"
        }
    }

    1 == count(msg)
}

test_should_pass {
    msg := deny with input as {
        "request": {
            "operation": "DELETE"
        }
    }

    0 == count(msg)
}
```

Sample JSON object for testing the "admission" controller:
```json
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "operation": "CREATE",
    "uid": "6ccca7ef-4a8f-4c4a-a226-febf6937f381"
  }
}
```

OPA is started with the arguments:
```yaml
args = [
            "run",
            "--server",
            "--tls-cert-file=/certs/tls.crt",
            "--tls-private-key-file=/certs/tls.key",
            "--addr=0.0.0.0:8181",
            "--diagnostic-addr=http://0.0.0.0:8182",
            "--log-format=json",
            "--authentication=token",
            "--authorization=basic",
            "--ignore=.*", # exclude hidden dirs created by Kubernetes

            # For testing
            "--set", "decision_logs.console=true",

            "/bootstrap",
          ]
```

## Steps To Reproduce

1. Sample rule and test passes: `opa test policy.rego policy_test.rego` `PASS: 2/2`
2. Deploy to kubernetes
3. Attempt to CREATE a resource is granted when it should be rejected
    ```json
    {"apiVersion":"admission.k8s.io/v1",
     "kind":"AdmissionReview",
     "response":{"allowed":true,"uid":"6ccca7ef-4a8f-4c4a-a226-febf6937f381"}
    }
    ```

## Expected behavior

Either the `opa test` call should have a FAIL or the Kubernetes admission hook call should be rejected with the error.

## Additional context

Any minor change fixes the issue. Like using assignment operator instead of unification, or having multiple items in the set.

**Comment by srenatus** [comment]
This is very puzzling. 🤔 Have you tried posting the same payload via curl?

**Comment by dpiddock** [comment]
Yes, I tried with the sample payload:
```
$ curl --insecure -X POST https://127.0.0.1:49266/ -d '{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "request": {
    "operation": "CREATE",
    "uid": "6ccca7ef-4a8f-4c4a-a226-febf6937f381"
  }
}'
{"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","response":{"allowed":true,"uid":"6ccca7ef-4a8f-4c4a-a226-febf6937f381"}}
```

If I change the `operations = {` line to `operations := {` and try again I get the desired fail output:
```
{"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","response":{"allowed":false,"status":{"reason":"Test CREATE fail"},"uid":"6ccca7ef-4a8f-4c4a-a226-febf6937f381"}}
```
I have also tried with a full deployment input payload copied from the opa logs.

**Comment by srenatus** [comment]
I there more to your rego policy? Any other mention of `operations`, a rule named like that perhaps? That's usually the only interference that using `:=` protects you from. This would mean that the `opa test` call might not be loading all the relevant rego files...? 🤔

**Comment by srenatus** [comment]
Btw if you don't _want_ anything other than a locally-defined variable, use `:=`. Only use `=` if it's your desire to explicitly fiddle with unification of your terms directly.

**Comment by dpiddock** [comment]
You are correct. A different ConfigMap rule started off with:
```yaml
package kubernetes.admission

operations := {
    "CREATE",
    "UPDATE"
}
```
Each rego file is tested in individually. This is a design flaw on our side as OPA rules files obviously don't run in isolation.

I should have stripped back my test environment more.

Thank you 😄
