### ISSUE TITLE
VNG Cloud has adopted OPA

### ISSUE THREAD

**Issue by vinhph0906** [open-policy-agent/opa#4945]
### Organization Name

VNG Cloud

### Organization Website

https://www.vngcloud.vn/en/home

### Organization Logo (optional)

https://www.vngcloud.vn/documents/20126/906379/logo-vng-cloud-color.png

### How is your organization using OPA?

[Identity and Access Management (IAM)](https://iam.vngcloud.vn/) provides administrators with fine-grained access control to VNG Cloud resources and help centralize and manage permissions to access resources. In IAM, we use OPA as a policy-based decision engine for authorization. Specifically, we integrate OPA to evaluate policies to make the decision about denying or allowing incoming requests. 

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by srenatus** [comment]
I'd be happy to add your entry to adopters.md; but I've found that there is no information behind your IAM link, https://iam.vngcloud.vn/ -- it requires me to sign in first. Is there any other link we could use?

**Comment by vinhph0906** [comment]
We have [docs](https://docs.vngcloud.vn/display/ONVINA/IAM+-+Identity+and+Access+Management). However, it writes in Vietnamese. We will update the English version soon.
