### ISSUE TITLE
Custom cache_key for http.send inter-query cache

### ISSUE THREAD

**Issue by rmetcalf9** [open-policy-agent/opa#4953]
I am working on using http.send to access data during policy evaluation.
I would like the opa agents to cache the response for 60 seconds to reduce load on the upstream servers.

## Short description 
In my setup the opa agent is running in aws fargate. The opa agent is being called from a java application.
I am able to monitor the http_access logs of the upstream server and I can see calls coming from the opa-agent.
I have verified that every time I call my endpoint and have a single policy evaluation I get a single call to the upstream service.
I expect to only get a call to the upstream service once every 60 seconds.
I have the following policy which calls the upstream service:
```
get_grabyo_s2s_call(method, url, params) = result {
    jwtToken = wrapper_get_s2s_jwt_token(service_name)
    headers := {
        "Authorization": concat("", ["Bearer ", jwtToken])
    }
    http_send_response = http.send({
        "raise_error": false,
        "method": method,
        "url": url,
        "cache": true,
        "force_cache": true,
        "force_cache_duration_seconds": 60,
        "enable_redirect": true,
        "headers": headers
    })
    result := http_send_response
}
```
Does this show an issue with opa or have I set the policy settings incorrectly.

* OPA version - v0.40.0
* I have verified the OPA agent returns allow=false
* I have not set caching.inter_query_builtin_cache.max_size_bytes to any value

## Expected behavior
I expect to see only a single call to the upstream service every 60 seconds.

## Additional context
I don't know if this is relevant but this is a difference between us and a standard opa agent.
We needed to add our own built in functions to OPA.
So we have built a docker container with our own go application and imported the opa packages as part of the go application.
e.g. our go.mod is as follows:
```
module github.com/grabyo/opa-agent

go 1.16

require (
	github.com/aws/aws-sdk-go v1.44.18
	github.com/golang/mock v1.6.0
	github.com/grabyo/go-jwt-helper v1.0.2
	github.com/open-policy-agent/opa v0.40.0
	github.com/sirupsen/logrus v1.8.1
	github.com/stretchr/testify v1.7.1
)
```

This lets us have a main.go which registers our extra functions:
```
package main

import (
	"os"

	"github.com/grabyo/opa-agent/grabyo"
	"github.com/open-policy-agent/opa/cmd"
	log "github.com/sirupsen/logrus"
)

var (
	Version string
)

func init() {
	log.SetFormatter(&log.JSONFormatter{})
	log.SetOutput(os.Stdout)
	log.SetLevel(log.InfoLevel)
}

func main() {
	log.Info("Entering application")
	log.Infof("Version %s", Version)
	grabyo.RegisterGrabyoBuiltinFns(Version)

	log.Info("Running OPA")
	if err := cmd.RootCommand.Execute(); err != nil {
		log.Error(err)
		os.Exit(1)
	}
}
```

**Comment by rmetcalf9** [comment]
I have updated to OPA v0.43.0 and the issue is still there

**Comment by anderseknert** [comment]
Hi Robert!

The cache key will be built from any part of the request, so if there's anything different between invocations (like a header value, query param, whatever), the cache won't be consulted. Could something like that be at play?

I don't think it should make a difference, but just to confirm, could you try the same `http.send` call on a non-modified OPA?

(unrelated, I think, but you won't need to set `"cache": true,` when you have the `force_cache` attribute set)

**Comment by rmetcalf9** [comment]
The params sent to http.send are
```
    http_send_response = http.send({
        "raise_error": false,
        "method": method,
        "url": url,
        "cache": true,
        "force_cache": true,
        "force_cache_duration_seconds": 60,
        "enable_redirect": true,
        "headers": headers
    })
```
and between the requests that are not being cached the value for each of these is the same.

I have tried both with and without the cache: true setting and get the same behaviour.
I have tried to a different endpoint completely and am getting the same issue.

**Comment by anderseknert** [comment]
When I test caching I normally spin up a local Python web server to see what it logs, as each request to that emits a line for the request. Doing this here right now, and I'm not able to reproduce.

```
❯ python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
```

```
package policy

method := "GET"
url := "http://localhost:8000"

http_send_response = http.send({
    "raise_error": false,
    "method": method,
    "url": url,
    "force_cache": true,
    "force_cache_duration_seconds": 60,
    "enable_redirect": true,
    "headers": {
        "X-Custom": "test"
    }
})
```
```
opa run --server .
```
```
❯ curl localhost:8181/v1/data/policy/http_send_response
{"result":{"body":null,"headers":{"content-length":["0"],"content-type":["text/html"],"date":["Mon, 01 Aug 2022 14:40:02 GMT"],"last-modified":["Mon, 01 Aug 2022 14:11:35 GMT"],"server":["SimpleHTTP/0.6 Python/3.9.13"]},"raw_body":"","status":"200 OK","status_code":200}}%

❯ curl localhost:8181/v1/data/policy/http_send_response
{"result":{"body":null,"headers":{"content-length":["0"],"content-type":["text/html"],"date":["Mon, 01 Aug 2022 14:40:02 GMT"],"last-modified":["Mon, 01 Aug 2022 14:11:35 GMT"],"server":["SimpleHTTP/0.6 Python/3.9.13"]},"raw_body":"","status":"200 OK","status_code":200}}%

... 
```
No matter the number of requests, the Python web server shows only one received:
```
::1 - - [01/Aug/2022 16:40:02] "GET / HTTP/1.1" 200 -
```

If you try the above, do you see the same result? If so, we'll need to figure out where things stop working.

**Comment by rmetcalf9** [comment]
Hi,
We have determined that our Authorization header is actually different for each request.
Do you know if it is possible to exclude this from the cache key?

**Comment by anderseknert** [comment]
OK. No that's not currently possible, as the whole request map is used as the cache key: https://github.com/open-policy-agent/opa/blob/main/topdown/http.go#L1221

I suppose a `cache_key` option could be introduced that would allow one to override this. It's just never been requested in the past.

**Comment by anderseknert** [comment]
I changed the title to reflect the feature request. If someone has the same need later and would want to work on this, let's reopen it then. Good to hear you have way forward 👍

**Comment by kdlugajczyk** [comment]
Hey @anderseknert!
I believe we have similar issue in our project - we do use `http.send` to perform additional checks in external service during policy evaluation that we would like to cache. But the problem is that with each request we pass different value in `trace` header, making it impossible to cache the response. Ideally, it would be good to have control over what is treated as cache key, but maybe can you propose some workarounds for now?

**Comment by anderseknert** [comment]
So the trace ID comes from the `input`? I think `http.send` is included in traces if you run with the open telemetry integration, and in that case caching would work as expected. But this sounds like something home cooked? Not sure about workarounds in that case 🤔
