### ISSUE TITLE
Support opa-envoy linux/arm64 Docker Image

### ISSUE THREAD

**Issue by Nebu1eto** [open-policy-agent/opa#4965]
## What is the underlying problem you're trying to solve?

I'm using opa-envoy, but it doesn't support linux/arm64 architecture. So I can't use this on Graviton 2 (AWS).

## Describe the ideal solution

If there are no problem to build opa-envoy image for arm64, can you please support this? If not, It is issue and it have to be resolved.

**Comment by srenatus** [comment]
Contributions welcome! Happy to assist.

The setup here could also be simpler than what OPA does: since no cgo is needed, we could use ko.

**Comment by sidharthramesh** [comment]
Thank you @srenatus. I'll get started on this. CC: @Areefks

**Comment by sidharthramesh** [comment]
@srenatus Ko seems to do all of the heavy lifting of multiarch image builds. Should I replace all of these lines with Ko's CLI instead of docker build?

**Comment by sidharthramesh** [comment]
@srenatus Do we need the whole replacing the Dockerfile arch business when we switch to Ko?
```
sed -e 's/GOARCH/$(GOARCH)/g' Dockerfile > .Dockerfile_$(GOARCH)
```

**Comment by sidharthramesh** [comment]
Where exactly is the docker build happening?

https://github.com/open-policy-agent/opa-envoy-plugin/blob/c37ea9d489b8f8144d449abbe294a1d6cde7ffa2/.github/workflows/post-tag.yaml#L23 this doesn't seem to be building the images, only the binaries?

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/blob/main/.github/workflows/post-merge.yaml#L160 should do it, at least the -edge images.

**Comment by 3goats** [comment]
+1

**Comment by kenissongmelo** [comment]
+1

**Comment by leandrosantoro** [comment]
+1

**Comment by tjons** [comment]
@srenatus I'll work on this one!

**Comment by tjons** [comment]
https://github.com/open-policy-agent/opa-envoy-plugin/pull/577 should resolve this!

**Comment by srenatus** [comment]
🥳 yaaaay
