### ISSUE TITLE
Documentation request - Docker config-file

### ISSUE THREAD

**Issue by hutchins** [open-policy-agent/opa#4993]
## Documentation Update Request
Please update documentation to include how to use/pass a config-file yaml with docker hub opa image https://hub.docker.com/r/openpolicyagent/opa

## Ideal solution
Ideally it would be as easy as -v /local/path/to/config.yaml:/container/opapath/to/config.yaml

**Comment by anderseknert** [comment]
Hi @hutchins! Are you referring to the OPA Docker plugin for authorization? Or just want to mount a config file into the regular OPA container?

**Comment by anderseknert** [comment]
Alright! Your ideal solution is pretty much it :)

```
docker run -it --rm -p 8181:8181 -v ${PWD}:/conf  openpolicyagent/opa run --server --config-file=/conf/opa-conf.yaml
```

**Comment by anderseknert** [comment]
Did you get it to work, @hutchins ?

**Comment by anderseknert** [comment]
Let me know if we should re-open this. Closing for now.
