### ISSUE TITLE
Forward incoming HTTP Request ID to remote services when using http.send

### ISSUE THREAD

**Issue by kotyara85** [open-policy-agent/opa#5008]
It looks like OPA doesn't honor x-request-id header at this moment
It would be great if it did, because that would give an ability to run E2E traces in case if http.send is involved
Thanks

**Comment by srenatus** [comment]
Can you please elaborate on your expectations? Should the request ID header become part of the response, or part of the open telemetry spans, or be used in decision logs...? What is you're checking in your E2E traces?

**Comment by kotyara85** [comment]
Yeah,
for example:
serviceA -> OPA -> serviceB

serviceA adds x-request-id header
this header would be exposed as reqId in opa info log and passed down to serviceB as x-request-id header

This way you can see one call across all the systems

Thanks

**Comment by srenatus** [comment]
Ah. So concretely, you're expecting the header to be sent along with `http.send` calls to remote services.

**Comment by kotyara85** [comment]
> Ah. So concretely, you're expecting the header to be sent along with `http.send` calls to remote services.

Yeah

**Comment by kotyara85** [comment]
@srenatus it would be also beneficial to add reqId to logs

**Comment by anderseknert** [comment]
@kotyara85 did you check out the [open telemetry integration](https://www.openpolicyagent.org/docs/latest/monitoring/#opentelemetry)?

**Comment by anderseknert** [comment]
With the Open Telemetry support and #5196, I'm not sure this is needed. Let's re-open this if so.
