### ISSUE TITLE
semver docs typo

### ISSUE THREAD

**Issue by tetsuya28** [open-policy-agent/opa#5012]
## Short description 

In `semver.compare()`, found docs typo and I think the following is correct.
~`1 if b > a;`~ → `1 if a > b;`
Ref: https://www.openpolicyagent.org/docs/latest/policy-reference/#semver
> Returns:
result
(number)
-1 if a < b; 1 if b > a; 0 if a == b

**Comment by srenatus** [comment]
Thanks, good catch. It's defined here: https://github.com/open-policy-agent/opa/blob/39fa5cf79caec81433dba1770346b57c932a6414/ast/builtins.go#L2751 -- would you be up to filing a PR with the fix? 😃
