### ISSUE TITLE
Status API last_successful_activation timestamp is updated even when there is no change to policy/data

### ISSUE THREAD

**Issue by rashmigs1993** [open-policy-agent/opa#5020]
## Short description 

We are using the status API of OPA to know if the bundle is downloaded & activated successfully. Even when the bundle is not changed, the following metrics are updated to the latest timestamp. 
"last_successful_activation": "2022-08-08T17:19:54.928510907Z",
      "last_successful_download": "2022-08-08T17:19:54.122427015Z",
      "last_successful_request": "2022-08-08T17:19:54.122427015Z",

**Comment by srenatus** [comment]
> Even when the bundle is not changed, the following metrics are updated to the latest timestamp.

Can you elaborate that, please? Without Etags, a remote bundle is activated again and again. There's no internal logic to figure out if it's unchanged or not, other than that Etag mechanism. 

Do your logs show that bundle activation happened or that it didn't happen?

**Comment by ashutosh-narkar** [comment]
I would expect `last_successful_request` to be set on every download that does not have any download error. `last_successful_activation` and `last_successful_download` should only be set if the remote server returns a status `200` with a non-empty body.

As Stephan mentioned if you have caching via etag set correctly, you should see a OPA debug log `Bundle load skipped, server replied with not modified.` and `last_successful_activation` / `last_successful_download` should not be updated.

**Comment by rashmigs1993** [comment]
@srenatus @ashutosh-narkar "caching via etag set correctly" Can you elaborate more on this? How do we set this? Is there documentation you can share?

**Comment by ashutosh-narkar** [comment]
@rashmigs1993 the bundle server can set the `Etag` header in bundle responses to identify the revision of the bundle. OPA will include this value in the `If-None-Match` while requesting the next bundle. More info [here](https://www.openpolicyagent.org/docs/latest/management-bundles/#caching).

**Comment by rashmigs1993** [comment]
@ashutosh-narkar We will try this out. Please keep the issue open until we confirm. 

cc: @tim-styra  @ravichauhan03
