### ISSUE TITLE
How to compile opa-envoy-plugin for arm64

### ISSUE THREAD

**Issue by eliaharm** [open-policy-agent/opa#5025]
Hello,
I am trying to compile opa-envoy-plugin using Docker for arm64.
I am getting the below error (i have limited experience in Go)
```
package .: build constraints exclude all Go files in /src/myapp
```
This is my dockerfile
```dockerfile
FROM --platform=arm64 golang:1.15.15-alpine AS build
WORKDIR /src
RUN apk add --no-cache git
ENV CGO_ENABLED=0
ENV BUILD_GOARCH="arm64" 
RUN git -c advice.detachedHead=false clone -b master --depth 1 --branch  v0.43.0-envoy https://github.com/open-policy-agent/opa-envoy-plugin.git /src/myapp/
WORKDIR /src/myapp
RUN go env -w GO111MODULE=off
RUN GOOS="linux" GOARCH="arm64" go build -o /out/example .

FROM scratch AS bin
COPY --from=build /out/example /
```

and using the command:
```
docker build  --progress=plain --no-cache --target bin --output bin/ --platform arm64 .
```

Thanks,

**Comment by srenatus** [comment]
You're trying to build a directory that doesn't have the command. Try
```
RUN GOOS="linux" GOARCH="arm64" go build -o /out/example ./cmd/opa-envoy-plugin/main.go
```
instead.

Alternatively, try using `RUN GOARCH=arm64 make build-linux` in the checkout directory, to use the standard build logic that's used when building for the other architectures.

**Comment by srenatus** [comment]
BTW officially supporting linux/arm64 images has been brought up before, perhaps you could chat. I'm happy to assist if you'd like to push this forward.

**Comment by eliaharm** [comment]
Hello,
Thanks for the help
got it working using the below dockerfile


```dockerfile
FROM --platform=arm64 golang:1.18.5-alpine AS build
WORKDIR /src
RUN apk add --no-cache git make
ENV CGO_ENABLED=0
ENV BUILD_GOARCH="arm64" 
RUN echo "$(go version)"
RUN echo "$(go env)"
RUN git -c advice.detachedHead=false clone -b master --depth 1 --branch  v0.43.0-envoy https://github.com/open-policy-agent/opa-envoy-plugin.git /src/

WORKDIR /src
RUN make build-linux-static

FROM scratch AS bin
COPY --from=build /src/opa_envoy_linux_arm64 /bin/opa_envoy
EXPOSE 8181/tcp
EXPOSE 8181/udp
ENTRYPOINT ["/bin/opa_envoy"]
CMD ["run","--server"]
```

I launched `docker build` so that it will compile the code using the command:
```
docker build  -t opa-envoy:v0.43.0-arm64-static --progress=plain --no-cache --platform arm64 .
```

I ended up having an image tagged `opa-envoy:v0.43.0-arm64-static` that only contains the arm64 executable that I pushed to my hosted registry and was able to execute.

Thanks,

**Comment by eliaharm** [comment]
I have seen a couple of issues mentioning ARM64 support and that you need some infrastructure, you might like to check out the oracle cloud (OCI) they have an interesting free tire ;)

**Comment by srenatus** [comment]
The problem with CI and testing on Arm64 isn't really getting access to hardware, it's more what comes on top of it: maintain a (set of) custom github actions runners. If there was simple way to get CI results from real arm64 hardware without too much extra effort, I'm all ears 😃

**Comment by eliaharm** [comment]
I am not an expert in CI, I experimented a little with GitLab CI/CD, you can install the gitlab runner on a arm64 machine and have it execute the build there. don't know much about github...

**Comment by anderseknert** [comment]
Hey there :) Is there anything actionable left here, or are we OK to close this?
