### ISSUE TITLE
Bundle plugin: Trigger does not propagate errors

### ISSUE THREAD

**Issue by lvisterin** [open-policy-agent/opa#5029]
## Short description 

Context:

* OPA version: v0.43.0
* Using OPA SDK inside application

I ran into some unexpected behavior when integrating with the OPA SDK.

We use the `Trigger()` method of the bundle plugin to manually trigger a policy update. When the triggered update fails, we want to handle this in our application.

However, looking at the source code for `Trigger`:

```go
for _, d := range downloaders {
	// plugin callback will log the trigger error and include it in the bundle status
	_ = d.Trigger(ctx)
}
return nil
```

I was about to make a PR, but looking at the comment it seems almost intentional that the Trigger function always returns a nil error regardless of success.

If this is really intentional, why is this so? If not, are you open for a PR to change this code to return the first (or last) non-nil error encountered when downloading bundles? Keeping the behaviour that it will make an attempt to download every bundle regardless of other errors of course.

## Steps To Reproduce

1. Initialize OPA SDK with configuration to pull the bundle from a server that is down and the trigger set to manual
2. Run `err := bundlePlugin.Trigger(ctx)` and observe how err is nil

## Expected behavior

When the trigger operation fails, the returned error should not be nil.

## Additional context

The other plugins behave as I expected:

### Status plugin

```go
case update := <-p.trigger:
	err := p.oneShot(update.ctx) // returns error if non-2xx status
	if err != nil {
		p.logger.Error("%v.", err)
		if update.ctx.Err() == nil { // if no ctx error
			update.done <- err // return bad status code error
		}

func (p *Plugin) Trigger(ctx context.Context) error {
	done := make(chan error)
	p.trigger <- trigger{ctx: ctx, done: done}

	select {
	case err := <-done: // recieves error from block above
		return err
```

### Logs plugin

```go
done := make(chan error)
go func() {
	if p.config.Service != "" {
		err := p.doOneShot(ctx)
		if err != nil {
			if ctx.Err() == nil {
				done <- err
			}
		}
	}
	close(done)
}()
select {
case err := <-done:
	return err
```

**Comment by srenatus** [comment]
@ashutosh-narkar What do you think? IMO, if we can make it backwards-compatible, it's a good idea to return the errors...

For context, I think the code was written at a time when the SDK wasn't a thing yet... So, when running OPA with bundles configured, it's a dumb thing that does its job, reporting its status through the status and decision logs. Hence the errors would have bubbled up in the expected way. But yeah, when you run the SDK from Go, I guess it's a good idea to return the error there. And it matches what an SDK user would expect given the function signature...

**Comment by lvisterin** [comment]
@ashutosh-narkar Thanks for the hint about the `Loaders` method, I've changed my code to use that and it works well.

>we should return errors if we can make it backwards-compatible but I'm not sure which error(s) to return from the bundle plugin's Trigger method.

If we look at the golang standard library extensions, [`(*errgroup.Group).Wait()`](https://pkg.go.dev/golang.org/x/sync/errgroup#Group.Wait) returns the _first_ non-nil error. (Errgroup does what the multi-bundle downloader but in parallel)

Some people solve this by returning all errors instead:

* Hashicorp uses a special multi-error type in their projects (https://github.com/hashicorp/go-multierror)
* Uber has a package with the same principle (https://github.com/uber-go/multierr)

I'd go with the simple approach of x/errgroup (first error) which avoids making a new 3rd party package part of the external interface. I don't know of any major project returning the last error.

**Comment by lvisterin** [comment]
One interesting thing about using the `Loaders` method: Trigger() appears to safely copy the downloaders map by locking `p.mtx`:

```go
func (p *Plugin) Trigger(ctx context.Context) error {
	p.mtx.Lock()
	downloaders := map[string]Loader{}
	for name, dl := range p.downloaders {
		downloaders[name] = dl
	}
	p.mtx.Unlock()
```

However `Loaders` returns the map directly:

```go
func (p *Plugin) Loaders() map[string]Loader {
	return p.downloaders
}
```

This makes it possible for SDK users to have a race on the downloaders map when for example using both `Reconfigure` and the value they got from `Loaders`. I don't do this so I don't immediately run into a race here but just leaving this here in case anyone does this with the current code.

**Comment by ashutosh-narkar** [comment]
> This makes it possible for SDK users to have a race on the downloaders map when for example using both Reconfigure and the value they got from Loaders. I don't do this so I don't immediately run into a race here but just leaving this here in case anyone does this with the current code.

Good point. We probably need to lock and make a copy of the map like the Trigger() call.

**Comment by lvisterin** [comment]
>Good point. We probably need to lock and make a copy of the map like the Trigger() call.

Unfortunately even when I add a lock to `Loaders` my example below seems to trigger the race detector. So I guess SDK users should mostly avoid doing parallel read/write on the bundle plugin which is not too bad.

<details>
<summary>expand example</summary>

```go
// Loaders returns the map of bundle loaders configured on this plugin.
func (p *Plugin) Loaders() map[string]Loader {
	p.mtx.Lock()
	defer p.mtx.Unlock()

	downloaders := map[string]Loader{}
	for name, dl := range p.downloaders {
		downloaders[name] = dl
	}

	return downloaders
}
```

```go
plugin.Reconfigure(ctx, &Config{
	Bundles: map[string]*Source{
		"b1": {Config: baseConf, Service: serviceName, Resource: "/bundles/bundle1.tar.gz"},
	},
})

wg := &sync.WaitGroup{}
wg.Add(2)

go func() {
	plugin.Loaders()["b1"].Trigger(ctx)
	defer wg.Done()
}()

go func() {
	cfg2 := &Config{
		Bundles: map[string]*Source{
			"b1": {Config: baseConf, Service: serviceName, Resource: "/bundles/bundle1.tar.gz"},
			"b2": {Config: baseConf, Service: serviceName, Resource: "/bundles/bundle2.tar.gz"},
		},
	}
	plugin.Reconfigure(ctx, cfg2)
	defer wg.Done()
}()
```

</details>

Anyways, sorry for getting off-topic here, the main issue was the Trigger method not returning any errors :) If you agree I can submit a PR for returning the first error.

**Comment by ashutosh-narkar** [comment]
> Anyways, sorry for getting off-topic here, the main issue was the Trigger method not returning any errors :) If you agree I can submit a PR for returning the first error.

If we return say the first error from the Trigger method, it won't be a backward-compatible change if you look at a multi-bundle scenario. The expectation is the errors should be handled in the callback function which the bundle plugin sets.  The `Loaders` seems to be an alternative to have more control on the downloader's trigger.

**Comment by anderseknert** [comment]
Is there anything actionable here, or are we OK to close this? 🧹

**Comment by lvisterin** [comment]
> Is there anything actionable here, or are we OK to close this? broom

On my end it is now clear how this works, so I was able to continue.

I understand the concerns about backwards compatibility that make the proposed change harder to make, so I'm okay with closing this one.
