### ISSUE TITLE
opa build ignores `.manifest` file

### ISSUE THREAD

**Issue by alam-chime** [open-policy-agent/opa#5041]
## Short description 
running `opa build ./` results in a bundle that ignores manifest file.

```
Version: 0.43.0
Build Commit: d75bbdd
Build Timestamp: 2022-07-29T21:14:35Z
Build Hostname: Mac-1659129125033.local
Go Version: go1.18.4
Platform: darwin/amd64
WebAssembly: available
```

## Steps To Reproduce

directory structure
```
.
├── .manifest
└── one
    └── two
        └── data.json
 ```
 
`.manifest` file
```
{
    "roots": ["one/two"]
}
```

`data.json`
```
{"other-data-point": true}
```

from the root running `opa build ./` results in `bundle.tar.gz` and debugging the bundle shows
```
opa run bundle.tar.gz
OPA 0.43.0 (commit d75bbdd, built at 2022-07-29T21:14:35Z)

Run 'help' to see a list of commands and check for updates.

> dump
{"one":{"two":{"other-data-point":true}},"system":{"bundle":{"manifest":{"revision":"","roots":[""]}},"version":{"build_commit":"d75bbdd","build_hostname":"Mac-1659129125033.local","build_timestamp":"2022-07-29T21:14:35Z","version":"0.43.0"}}}
```
the roots in the bundle is set to `[""]`

## Expected behavior

the roots with above setup should be `"roots":["one/two"]` instead of `"roots":[""]`

**Comment by ashutosh-narkar** [comment]
Use the `-b, --bundle` flag to load paths with the `build` command. The manifest should be correctly set.

**Comment by alam-chime** [comment]
ahh, you're right. `opa build -b ./ ` is including the manifest.
Thanks @ashutosh-narkar. closing this.
