### ISSUE TITLE
upgrade gqlparser to 2.5.0

### ISSUE THREAD

**Issue by vikstrous2** [open-policy-agent/opa#5065]
## What is the underlying problem you're trying to solve?
We are using gqlgen and the latest version of gqlgen requires gqlparser 2.5.0. Unfortunately, we also import this repo and this repo expects gqlparser v2.4.6. We can't upgrade our version of gqlgen until github.com/open-policy-agent/opa also upgrades gqlparser.

## Describe the ideal solution
Remove the dependency on gqlparser? No dependency = no problem :) There might be others relying on other versions of gqlgen. It might be good to not bundle this dependency and keep the dependencies of this go module as minimal as possible.

## Describe a "Good Enough" solution
Upgrade to the latest version of gqlparser and fix the incompatible changes. The only thing to fix might be error formatting.

## Additional Context
This is gqlgen https://gqlgen.com/

**Comment by philipaconrad** [comment]
Hello @vikstrous2, thanks for filing an issue. I am aware of gqlgen, as it is one of the major downstream users of the gqlparser library.

Removing gqlparser out of our vendored dependencies list entirely would be great, except that it provides critical data structures and logic for OPA's [GraphQL builtin functions](https://www.openpolicyagent.org/docs/latest/policy-reference/#graphql). :slightly_frowning_face:

We cannot rip it out for the time being, but we should be upgrading to version 2.5.0 soon.

**Comment by vikstrous2** [comment]
Ok! Thanks for the quick response. This works for us.
