### ISSUE TITLE
Support fs.FS in FileLoader

### ISSUE THREAD

**Issue by ear7h** [open-policy-agent/opa#5066]
## What is the underlying problem you're trying to solve?

I have an application that uses the OPA library to evaluate policies, i.e. using raw `Rego`s and not the `sdk` package. The problem with this is that the the `.rego` files must be deployed along with the app binary, and I have to provide the location of these files to the binary. This problem is exacerbated in testing and release environments where we have to upload multiple files and deal with the `.rego` files having different absolute paths (this is also a problem when dealing with the fact that multiple developers work on the application).

## Describe the ideal solution

My ideal solution is pretty minimal, so see below

## Describe a "Good Enough" solution

A method `WithFS(fs.FS)` added to [`FileLoader` interface](https://pkg.go.dev/github.com/open-policy-agent/opa@v0.43.0/loader#FileLoader). We could then pass an `fs.FS` provided by the [`embed` package](https://pkg.go.dev/embed) and files would be loaded from the provided `fs.FS` instead of the local filesystem.

**Comment by srenatus** [comment]
:+1: good idea. We've got something similar for the bundle loader already: https://github.com/open-policy-agent/opa/blob/main/bundle/filefs.go

**Comment by ear7h** [comment]
Cool, I can submit a PR for this later this week
