### ISSUE TITLE
The `deprecated` attribute missing from many deprecated builtins

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5072]
Currently, only the `any` and `all` functions have the `deprecated: true` attribute set. There are however [many more builtins](https://github.com/open-policy-agent/opa/blob/main/ast/builtins.go#L2821) that have been deprecated, and `re_match` in particular seems to be quite prevalent in policies found in the wild. Properly marking them as deprecated will allow the strict mode checker to fail compilation when encountering these functions, which will help users move away from them.

In addition to adding the attribute to all deprecated functions, make sure to update the [docs for strict mode](https://www.openpolicyagent.org/docs/latest/strict/) to reflect this.

**Comment by srenatus** [comment]
When these are properly marked, we can remove this kludge: https://github.com/open-policy-agent/opa/blob/1841703e77cfaef14c65684e11a05ec4c72c6bbb/internal/cmd/genbuiltinmetadata/main.go#L159-L161

**Comment by srenatus** [comment]
Thinking about it, a useful follow-up would be to introduce a new category, "deprecated", and render some docs for those deprecated built-in functions, too. After all, if a user finds a use of `re_match` somewhere, they have no chance to figure out what it is given our current docs.

**Comment by anderseknert** [comment]
@srenatus won't that kludge still be needed for `assign`, `eq` and `print`? 🙂

**Comment by srenatus** [comment]
Yeah. But that's less than before 😄
