### ISSUE TITLE
add a config to envoy plugin to allow bypass of content type for the request and send body

### ISSUE THREAD

**Issue by guptaarvindk** [open-policy-agent/opa#5081]
## What is the underlying problem you're trying to solve?

Current envoy plugin looks at content type and parse the body before sending it to OPA. If body is malformed, the OPA plugin fails.  Often user may not be able to control if body could be malformed or not,  and this results in failure in plugin itself.

Steps to replicate the issue:
- Run the envoy base image (`sudo docker run --network=host -e ENABLE_AUTHZ=true --rm -it envoy-base:latest`)
- Update mappings.json to something simple  (return everything as true)
- Run the OPA image (`sudo docker run --network=host fidopa:latest`)
- Send requests to OPA with content-type as application/json but junk body (`curl -ivk -H "Content-Type: application/json" -X POST -d "pizza" https://127.0.0.1:8443/healthcheck2`)
Envoy Error:
```
[2022-08-08 11:30:17.006][19][info][main] [source/server/drain_manager_impl.cc:171] shutting down parent after drain
[logtype=access] x-client-ip="-" time=[2022-08-08T15:33:28.901Z] request="POST /healthcheck2 HTTP/1.1" http_status=403 content_length=0 user_agent="curl/7.68.0" duration=9 fsreqid="-" srcip=127.0.0.1 rflags="UAEX" upstream="-" rdetails="ext_authz_error" xff="10.192.2.105" req_body_size="5"
```
 
OPA Error:
```
{"decision_id":"4fabcabf-cd17-4d11-a289-09c3e8f19a01","error":{"message":"invalid character 'p' looking for beginning of value"},"input":null,"labels":{"id":"f36491b1-e160-4ec0-9b8c-0f272925b947","version":"0.38.1-envoy-3"},"level":"info","metrics":{"timer_server_handler_ns":1343909},"msg":"Decision Log","query":"data.envoy.authz.allow","time":"2022-08-08T18:08:09Z","timestamp":"2022-08-08T18:08:09.448693342Z","type":"openpolicyagent.org/decision_logs"}
 ```

## Describe a "Good Enough" solution

We need a way to bypass this behavior so that we can control this from rego policy itself to decide what to do with packet instead of a failure in OPA envoy plugin in parsing.  We need to add a config to envoy plugin to allow bypass of content type for the request and send body in this scenario.

**Comment by ashutosh-narkar** [comment]
We should add a config parameter to the plugin like `parse_request_body` which defaults to `true`. This would result in the `parsed_body` field in the OPA input to not be set.

**Comment by kumar98ksp** [comment]
@srenatus ,I want to work on this issue , could you assign me.

**Comment by kumar98ksp** [comment]
thank you for assigned
