### ISSUE TITLE
HTTP request built-in function

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#510]
OPA does not currently provide a way to call out to external services to obtain context from within policies. In some cases this would be very useful, though it should be used with caution as it introduces dependencies and will make policies more difficult to test.

Example:

```
request = {"method": "GET", "url": "http://1.2.3.4:8080/some/path"}
response = http.send(request)
```

**Comment by tsandall** [comment]
The built-in ought to make use of the evaluation cache to avoid resending requests unnecessarily.

**Comment by ashutosh-narkar** [comment]
Pull request: https://github.com/open-policy-agent/opa/pull/575
