### ISSUE TITLE
any_prefix_match differs from doc

### ISSUE THREAD

**Issue by ericjkao** [open-policy-agent/opa#5126]
## Short description 
In OPA 0.44.0, the new `strings.any_prefix_match` behaves differently from [docs](https://www.openpolicyagent.org/docs/latest/policy-reference/#strings).
Docs say:

> Returns true if any of the search strings begins with any of the base strings.

But in fact, `strings.any_prefix_match({"x-0, z-0"}, "z-")` evaluates to false contrary to the doc.

## Steps To Reproduce

https://play.openpolicyagent.org/p/G5VMwfeI6s
See lines 11 and 14.

## Expected behavior

According to doc and the motivating example in [issue](https://github.com/open-policy-agent/opa/issues/4994), both lines should evaluate to `true`.

## Additional context

Strange that this bug exists and does not fail this test case: https://github.com/open-policy-agent/opa/blob/e7130a888d1d609cd23a22b34b2e2a233dba1fe9/test/cases/testdata/strings/test-anyprefixmatch.yaml#L3
Hmmm.

**Comment by srenatus** [comment]
```
{"x-0, z-0"}
```
☝️ This is a set containing of one string: `"x-0, z-0"`. Did you mean to use
```
{"x-0", "z-0"}
```
a set of two strings, by any chance? 🤔

**Comment by srenatus** [comment]
BTW we really need more examples in the docs, #4623

**Comment by ericjkao** [comment]
Oh lol that's a hilarious mistake on my part!
