### ISSUE TITLE
var  is unsafe when variable is nested

### ISSUE THREAD

**Issue by liu-du** [open-policy-agent/opa#5148]
## Short description 

When variable is nested, opa incorrectly thinks it is unsafe. opa version is v0.44

Examples:
`opa test` pass with the following `auth.rego`:
```
package auth

allow {
  input.x > 0
}

test_allow {
    base_test_case := {"x": 1}
    allow with input as base_test_case
}
```

output:
```
> opa test auth.rego
PASS: 1/1
```

`opa test` fail if I nested `base_test_case` inside a function:
```
package auth

allow {
  input.x > 0
}

test_allow {
    base_test_case := {"x": 1}
    allow with input as object.union(base_test_case, {"x": 2})
}
```

Error output:
```
> opa test auth.rego
1 error occurred: auth.rego:9: rego_unsafe_var_error: var base_test_case is unsafe
```

## Steps To Reproduce

run `opa test auth.rego` with above example files

## Expected behavior
nesting `base_test_case` should work

**Comment by srenatus** [comment]
Thanks for the report. Indeed this should just work as you expected it to work.

**Comment by liu-du** [comment]
It seems this only happens when `with` keyword is used.
