### ISSUE TITLE
Decision logging: confusing "upload chunk size too small" error message

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5155]
When the size of a decision log chunk exceeds the size limit set by the `upload_size_limit_bytes` configuration attribute, an error message saying "[upload chunk size too small](https://github.com/open-policy-agent/opa/blob/main/plugins/logs/encoder.go#L68)" is printed to the logs. This is confusing to users, as arguably, the upload chunk size is too _big_, and the _configured_ value is too small. Additionally, there's no indication as to what configuration attribute controls this, so it's not immediately clear what to do in order to fix this. A better error message could say something like:

"upload chunk size (81293) exceeds upload_size_limit_bytes (64000)"

**Comment by philipaconrad** [comment]
I like the updated error message! That gives the user more context, and makes the problem a bit clearer.
