### ISSUE TITLE
Improve error message when using an invalid object key

### ISSUE THREAD

**Issue by andy-styra** [open-policy-agent/opa#516]
When using a non-string value as an object key, OPA returns an internal error, rather than a more specific error pointing out the error.

This can be reproduced using the following policy:
```
package foo

g[key] = value {
    key = ["foo"]
    value = []
}
```

Response from OPA:
```
curl localhost:8181/v1/data/foo
{
    "code": "internal_error",
    "message": "object value has non-string key ([]interface {})"
}
```

**Comment by repenno** [comment]
Looked at this one, we can improve the message. For example. for the policy below:

`package foo

	g[app] = zone {
    	app = ["foo"]
    	zone = 456
	}
	`

The message would be:

"object value ({[\"foo\"]: 456}) has non-string key of type ([]interface {}), value ([foo])"

The "[]interface {}" comes from the fact that during parsing ["foo"] is considered an object of type []interface{} meaning basically we do not know what it is so consider it to map[]interface{}

I will submit a pull

**Comment by repenno** [comment]
We will not merging the changes due to:

https://github.com/open-policy-agent/opa/pull/1193#pullrequestreview-199691086
