### ISSUE TITLE
Proposal: regex.replace(search, pattern, value)

### ISSUE THREAD

**Issue by datfinesoul** [open-policy-agent/opa#5162]
## What is the underlying problem you're trying to solve?

See the un-commented parts of the example
https://play.openpolicyagent.org/p/aApnhKICLK

We were asking around about ways to do some more complex string manipulation, in this case taking the "friendly" github usernames, and converting them into their ID type format.  The best thing we could find after asking on the OPA slack was the solution in this example.

```rego
trim_whitespace(s) := concat("-", parts) {
	parts := [lower(part) |
		some part in split(s, " ")
		not part in {"-"}
	]
}
teams := { x | x := trim_whitespace(input.session.teams[_])}
```

## Describe the ideal solution

See the example, the commented "preferred" block
https://play.openpolicyagent.org/p/aApnhKICLK

```rego
preferred := { x |
    some part in input.session.teams
    x := regex.replace(part, "[ -]+", "-")
}
```

## Describe a "Good Enough" solution

I'm not sure I can think of a different option.  Since rego already has support for regex matches my assumption is that the above option might be possible.

**Comment by anderseknert** [comment]
Thanks for suggesting that, @datfinesoul 👍 Would you like to take a shot at an implementation? :)

**Comment by datfinesoul** [comment]
@anderseknert My golang skills are practically non-existent at the moment so that might be somewhat of a problem, but if no one has time to tackle this in the coming months, I'll give it a shot as I improve.

**Comment by anderseknert** [comment]
Cool! I've labeled it as a good first issue, so it's not unthinkable that someone else wants to give it a shot. But if that happens, we'll have other issues for you if you're up for it :)

**Comment by boranx** [comment]
wouldn't the following work for this case? afaik, there's already one builtin replace method but probably it doesn't support general regex syntax

```rego
preferred := { x |
    some part in input.session.teams
    x := strings.replace_n({" ": "-"}, part)
}
```

**Comment by anderseknert** [comment]
@boranx yeah, for simple cases you can probably achieve what you need with a combination of the current builtin functions, iteration and some other constructs. Having the option to do replace on patterns rather than values seems like a good addition nonetheless :)

**Comment by boranx** [comment]
Hey folks, I wanted to give it a shot and created a small PR to implement the proposal

**Comment by anderseknert** [comment]
Awesome, @boranx 👏 😃
