### ISSUE TITLE
Add support for applying the with keyword to the data document

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#517]
Mocking the data document for test purposes is a common use case for applying the with keyword to the data document. If someone wants to test policies that depend on the data document, they should be able to programatically control the structure of the data document inside their tests (otherwise they need to build a custom test runner that sets up data for them...)

Initially, it may be sufficient if applying the with keyword to data document only mocked base documents. In the future, it could be extended to handle virtual documents.

**Comment by aeneasr** [comment]
Yes, in fact not being able to mock data documents makes testing policies impossible (as far as I was able to track this). I'd be open to help tackle this, but it probably needs a lot of knowledge of OPA's internals.

**Comment by tsandall** [comment]
@ashutosh-narkar is working on this right now. I think there will be an initial version ready this month.

**Comment by srenatus** [comment]
Would this allow for referencing variables, too?

I could imagine a `policy_test.rego` like

```
package common

policies01 = {
  "id1": { ... },
  "id2": { ... }
}

policies02 = {
  "id1": { ... },
  "id2": { ... }
}

test_resource_matches_exact_simple {
  resource_matches["id2"] with data.policies as policy01 with input as { "resource": "yadda" }
}

test_resource_matches_wildcard {
  resource_matches["id2"] with data.policies as policy02 with input as { "resource": "yadda" }
}
```

(Note: no idea if multiple `with`s work like in the example, but that's not my point 😉)

**Comment by tsandall** [comment]
@srenatus yep we actually added support for referring to references in 85ebd9ea12a8ae784d5f77bc984255cb49294472:

```
> x = [1,2,3]
Rule 'x' defined in package repl. Type 'show' to see rules.
> p { input[1] = 2 }
Rule 'p' defined in package repl. Type 'show' to see rules.
> p
undefined
> p with input as x
true
```

Also you can apply multiple with modifiers like you described.

**Comment by ashutosh-narkar** [comment]
@srenatus Here is an example with multiple `with`s
```ruby
package authz
allow_1 {
	x := data.policies[_]
	x.name = "test_policy"
}

allow_2 {
	x := data.policies[_]
	x.name = "test_policy"
	matches_role(input.role)
}

matches_role(my_role) {
    data.roles[my_role][_] = input.user
}
```
```ruby
package authz
policies = [{"name": "test_policy"}]
roles = {"admin": ["alice"]}

test_allow_single_with {
	allow_1 with data.policies as policies
}

test_allow_multiple_with {
	allow_2  with input as {"user": "alice", "role": "admin"}   with data.policies as policies  with data.roles as roles
}
```
