### ISSUE TITLE
add glibc 2.29 dependency for v0.44.0

### ISSUE THREAD

**Issue by cccsss01** [open-policy-agent/opa#5174]
I attempted to install the latest version of OPA, ie. v0.44.0, and received GLIBC_2.29 required.  Which I believes means in order to use this you need to be on a RHEL 9 for RHEL based distro.

**Comment by srenatus** [comment]
RHEL isn't a requirement, it's just that that's the lowest version of glibc that you can use OPA with. Unless you're using the static build, i.e. `linux_amd64_static`. But you've closed this, so I guess you've found that already...

**Comment by cccsss01** [comment]
I misspoke, it's not that RHEL 9 is required, but from the reading i'm doing, It's stating, you don't want to upgrade the glibc on a rhel 8 based distro and want to go to rhel 9.

**Comment by srenatus** [comment]
I'm not sure I understand this -- is it a question...? I'd have to double check, but IIRC some old but not-EOL'ed yet RHEL version had a glibc that was too old. Has this been an issue for you? 😃

**Comment by cccsss01** [comment]
rhel 8 based distro has glibc_2.28, which is to old.  It has not been resolved for me.  But I don't know if this is a opa problem, or a me problem.

**Comment by srenatus** [comment]
Try the static binaries please.
