### ISSUE TITLE
OPA SDK features (strict-builtin-errors, instrumentation, and explain (traces))

### ISSUE THREAD

**Issue by humbertoc-silva** [open-policy-agent/opa#5176]
### Discussed in https://github.com/orgs/open-policy-agent/discussions/269

<div type='discussions-op-text'>

<sup>Originally posted by **humbertoc-silva** September 10, 2022</sup>
Hi everyone,

I am testing the OPA SDK, and I would like to know if is it possible to use the following parameters as we use with the OPA server when we run a query.
 
- provenance
- explain
- metrics
- instrument
- strict-builtin-errors

Thank you.</div>

Accordingly to the discussion above, some information we can get from decision and status logs, but the following items can be a good enhancement for OPA SDK:

- Turn on strict-builtin-errors when querying policies.
- Turn on instrumentation when querying policies.
- Turn on explain (trace) when querying policies.

**Comment by charlieegan3** [comment]
I can work on this, this month! :)

**Comment by charlieegan3** [comment]
Hi @humbertoc-silva, we've merged https://github.com/open-policy-agent/opa/pull/5438, https://github.com/open-policy-agent/opa/pull/5447, https://github.com/open-policy-agent/opa/pull/5459 and https://github.com/open-policy-agent/opa/pull/5460 to implement this. These are mostly available by configuring parameters to `opa.Decision`/`opa.Partial`.

Hope that's what you were looking for 🙂

**Comment by srenatus** [comment]
Let's also update the GitHub discussion linked above

**Comment by charlieegan3** [comment]
👍 I've posted another answer on there now. If you think it makes sense, I can add an edit note to your answer?

**Comment by humbertoc-silva** [comment]
Hi @charlieegan3, yes, this is exactly what I am looking for, I will check it out as soon as possible, thank you!
