### ISSUE TITLE
HTTP API Authorization docs example failing

### ISSUE THREAD

**Issue by mikestead** [open-policy-agent/opa#518]
I've run through the [following example](http://www.openpolicyagent.org/docs/http-api-authorization.html) from the website but can't get point `3` to work.

    curl --user alice:password localhost:5000/finance/salary/alice

This fails with 

    Error: user alice is not authorized to GET url /finance/salary/alice

If I remove the second `allow` clause from the policy then it works. This seems to indicate we may need an `else` conditional between the two `allow`s? I'm new to OPA and not had any luck getting such a conditional to work.

Could you confirm this is an issue, or if I'm doing something wrong?

#### Update

Actually this appears to be a regression(?) When I use the docker image `openpolicyagent/opa:0.5.10` the example works but when I use `openpolicyagent/opa:0.5.11`+ then I get this issue.

**Comment by tsandall** [comment]
I believe this issue is fixed in #512. I'm going to cut the next release (0.5.13) which will resolve that. Sorry for the inconvenience.

**Comment by tsandall** [comment]
Confirmed this was fixed by #512. The fix is contained in release v0.5.13.

**Comment by mikestead** [comment]
@tsandall thanks for the quick fix
