### ISSUE TITLE
Keyword "if" returns true when there's an empty rule body

### ISSUE THREAD

**Issue by peteroneilljr** [open-policy-agent/opa#5190]
## Short description 
When using the `if` keyword in a rule head, the output will return `true` if the rule body is empty. Removing the `if` keyword returns the expected result that an empty rule body is not allowed.

## Steps To Reproduce

This returns "test_true" = true
```rego
package test

import future.keywords

test_true if {

}
```

This retuns the expected "rego_parse_error: found empty body"
```rego
package test

import future.keywords

test_true {

}

```

## Expected behavior
A rule head with the `if` keyword should return the same results as a rule head without it.

**Comment by ashutosh-narkar** [comment]
Closing in favor of https://github.com/open-policy-agent/opa/issues/5294
