### ISSUE TITLE
default function rule unexpectedly produces output field

### ISSUE THREAD

**Issue by ericjkao** [open-policy-agent/opa#5202]
## Short description 
Weird little corner case
`default f(x) := 1` creates an output of `"f": 1`. Parser corner case issue?

## Steps To Reproduce
Evaluate this playground: https://play.openpolicyagent.org/p/r2dzB5veNj
See the output of
```json
{
    "f": 1,
    "g": 2
}
```

## Expected behavior
Output is `{}`

## Additional context
OPA 0.44

**Comment by srenatus** [comment]
Related https://github.com/open-policy-agent/opa/issues/2445

But arguably there should just be no output in this case...? 🤔

**Comment by ericjkao** [comment]
> Related #2445
> 
> But arguably there should just be no output in this case...? 🤔

I think no output makes sense. In all other cases, the expectation is that a function definition itself (without function call) produces no output at all.
