### ISSUE TITLE
freebsd build for v0.44.0

### ISSUE THREAD

**Issue by yurivict** [open-policy-agent/opa#5206]
Downstream [report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266813).

**Comment by srenatus** [comment]
Thanks. That installation method isn't supported, I'm afraid. Let's fix the build instead.

**Comment by srenatus** [comment]
To be clear, I certainly want that port to work! Is there an option not to use "go install"?

**Comment by srenatus** [comment]
The dependencies are all bundled in the git repo. The preferred build method would be to run `make build` in the sources.

**Comment by yurivict** [comment]
```make build``` fails:
```
$ gmake build
Docker not installed or not running. Skipping OPA-WASM library build.
CGO_ENABLED=1 GOFLAGS="-buildmode=exe" go generate
CGO_ENABLED=1 GOFLAGS="-buildmode=exe" go build -tags=opa_wasm -o opa_freebsd_amd64 -ldflags " -X github.com/open-policy-agent/opa/version.Version=0.44.0 -X github.com/open-policy-agent/opa/version.Vcs=5701f4ab6e2f-dirty -X github.com/open-policy-agent/opa/version.Timestamp=2022-10-04T16:21:22Z -X github.com/open-policy-agent/opa/version.Hostname=yv.noip.me"
# github.com/open-policy-agent/opa
/usr/local/go119/pkg/tool/freebsd_amd64/link: running cc failed: exit status 1
ld: error: unable to find library -lwasmtime
cc: error: linker command failed with exit code 1 (use -v to see invocation)

gmake: *** [Makefile:121: go-build] Error 2
```

**Comment by srenatus** [comment]
Ah, right. There's no wasmtime lib for freebsd in wasmtime-go (because there's none in wasmtime's release artifacts). Bummer! Can you try this instead, please?

```
WASM_ENABLED=0 CGO_ENABLED=0 gmake build
```

We should fix the `Makefile` here to include more targets, so that `make build` just works on *BSD: https://sourcegraph.com/github.com/open-policy-agent/opa@f3c0630ea50b921630ae5a8ebddf17ae89b28ff1/-/blob/Makefile?L21-23

**Comment by yurivict** [comment]
make attempts to use git:
> gmake[1]: git: No such file or directory

Downloads during package build aren't allowed in virtually all packaging systems (except Arch).

Is there a way not to download anything?

**Comment by srenatus** [comment]
It just fails looking up the ref. I'll look into fixing that tomorrow.

**Comment by srenatus** [comment]
OK I'm fairly sure the `git` failure is [from this line](https://github.com/open-policy-agent/opa/blob/v0.44.0/Makefile#L444):

```
ifneq (,$(or $(findstring rc,$(VERSION)), $(findstring release-,$(shell git branch --contains HEAD))))
```
so while it's annoying and noisy, it should not affect the build at all.

**Comment by srenatus** [comment]
Did this resolve the issue for you? 👀

**Comment by srenatus** [comment]
Please reopen if this keeps being an issue for you!
