### ISSUE TITLE
Allow "undefined" to be passed to function as value 

### ISSUE THREAD

**Issue by t83714** [open-policy-agent/opa#5211]
## What is the underlying problem you're trying to solve?

Want to create a function to test if a field is either "undefined", null or empty string.

e.g. the `isEmpty` function below:

```rego
package test

isEmpty(v) {
    v == null
}

isEmpty(v) {
    not v
}

isEmpty(v) {
    v == ""
}


test {
    isEmpty(input.xxxx)
}
```

If we create a rego file `test.rego` with the content above, and run:
```bash
opa eval -d test.rego -i input.json  data.test.test
```

- When supply input file `input.json` as:

```json
{"xxxx": null}
```

We will get the correct `true` result:
```json
{
  "result": [
    {
      "expressions": [
        {
          "value": true,
          "text": "data.test.test",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

- However, when supply input file `input.json` as:

```json
{}
```

We will get the incorrect undefined result `{}`. 

## Describe the ideal solution

When a field is undefined / not set, the undefined value should be passed to the function for further evaluation.

Thus, the rule:

```rego
isEmpty(v) {
    not v
}
```
should allow us to get correct `true` result

**Comment by srenatus** [comment]
I'm afraid this is just not possible given the semantics of Rego. When an expression is undefined, it cannot be used as a function argument.

Basically, in your `isEmpty(input.xxx)` what fails isn't `isEmpty`, but the evaluation stops because its argument is undefined.

You can work around this -- if you feel you have to -- with something like this:
```rego
package test

isEmpty(v, _) {
    v == null
}

isEmpty(v, k) {
    not v[k]
}

isEmpty(v, k) {
    v[k] == ""
}


test {
    isEmpty(input, "xxxx")
}
```

<details><summary>Condensed version</summary>

```rego
package test

import future.keywords.if

isEmpty(null, _) = true

isEmpty(v, k) if not v[k]

isEmpty(v, k) if v[k] == ""

test if {
	isEmpty(input, "xxxx")
}
```
</details>

**Comment by t83714** [comment]
@srenatus Thanks a lot for your prompt reply.

The alternative solution you mentioned would be helpful in some cases. 

But the `input` JSON data, for most cases, would come with a complex structure.

e.g. we might need to test if `input.a.b.c.d.e` is empty. But the `input` JSON data could be undefined at any point along the JSON path. i.e. `input.a` or `input.a.b` or `input.a.b.c` could be undefined.

Would it be possible to introduce some kind of "lazy" evaluation feature to solve this?
i.e. for expression `isEmpty(input.a.b.c.e)`, we try NOT to evaluate the value of reference `input.a.b.c.e` until enter the function `isEmpty`.

I just think the feature could be handy for many cases when dealing with JSON `input` data. The current behaviour (although it's expected) might be counter-intuitive for some people like me 😄 .

Having said that, if it's too hard or not realistic for the current implementation, I guess we can close the ticket --- as it's not a blocker.

At this moment, I just have to remove the `not` case from `isEmpty` and move it to the `test` policy:

```rego
isEmpty(v) {
    v == null
}

isEmpty(v) {
    v == ""
}

test {
    isEmpty(input.a.b.c)
}

test {
    not input.a.b.c
}
```

**Comment by srenatus** [comment]
Are you aware of `object.get`? I think you could do something like `object.get(input, ["a", "b", "c"], "__undefined__") == "__undefined__")` to check if the nested key is undefined 🤔 

> Having said that, if it's too hard or not realistic for the current implementation, I guess we can close the ticket --- as it's not a blocker.

There are other approaches than introducing lazy semantics, some of them have been discussed here: https://github.com/open-policy-agent/opa/issues/2345b

I guess in JS, you'd use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)? Like `input?.a?.b?.c`.

**Comment by t83714** [comment]
Thanks, @srenatus 👍 

1> My use case will translate OPA's partial evaluation result to other DSLs later (e.g. SQL )

Because of that, I tend to avoid using built-in functions on any possible `unknown` fields.

`not input.a.b.c` is much easier to translate (and more generic & likely supported by any systems) than `object.get(input, ["a", "b", "c"], "__undefined__")`

2> I think one of the best thing in rego is its simplicity & minimal language feature.

Because of it, I don't think it's a good idea to solve this problem by adding new operator (like `//` mentioned in the ticket https://github.com/open-policy-agent/opa/issues/2345/).

The `lazy evaluation` solution, on the other hand, won't introduce any new operators to rego.

Combined with existing `not` operator, users can opt to implement their own functions to solve all related `undefined` issues.

e.g. we can have a `getOrElse ` function:
```rego
getOrElse(value, defaultValue) = [returnValue] {
  not value
  returnValue := defaultValue
}

getOrElse(value, defaultValue) = [returnValue] {
  returnValue := value
}
```

3> I think the only reason we need [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in JS is because it will throw an exception by default when accessing a property of undefined value.

Rego actually doesn't have the issue. i.e. accessing `input.a.b.c` never throw an exception or break your policy.

I think we just have an issue with handling `undefined`.

We can probably either introduce the `lazy evaluation` feature or introduce `undefined` as a new scalar value type.

Introducing `undefined` as a new scalar value type might also help to solve the `undefined` function / rule return value issue as some people mentioned in the ticket https://github.com/open-policy-agent/opa/issues/2345

**Comment by srenatus** [comment]
I suppose the current semantics work well for asserting that something is valid: `goodValues(input.a.b.c)` instead of checking something's absence...

**Comment by anderseknert** [comment]
Rego has it's roots in logic programming, and while it isn't what one might be used to from other languages, has many benefits when working with structured but dynamic data, IMHO. Compare something like:

```rego
some x, y, z
p := data.authz[x].users[y].endpoints[z].permissions
```
or
```rego
some i, j, k, m
sites[i].servers[j].name = apps[k].servers[m]
```

to what you'd need to write in e.g. Go, Python, or Javascript to accomplish the same thing... precisely because you'll need defensive checks for undefined or null at each step along the way... 🤷 Let's just be different 😄

While there are some things to improve handling of undefined, as linked to here and elsewhere, I don't see a complete overhaul of this as possible, or desirable, for OPA/Rego.

**Comment by t83714** [comment]
@anderseknert Thanks for your comments.
I have to say the language structure like this:
```rego
sites[i].servers[j].name = apps[k].servers[m]
```
is my favourite part of Rego ❤️ 

If we ever work out any solution to deal with `undefined` issue, I think it should be a solution that doesn't hurt the language feature above.

Instead of "defensive checks for undefined or null at each step along the way", I was wondering whether we can "box" `undefined` value safely so it (undefined value) can reach the end of the process (e.g. like what functional language does).

Would you think if we introduce `undefined` as a new scalar type with the following properties:
- if an expression produces an `undefined` value, it will fail during policy evaluation (similar to `false`)
- `not` operator will make the above expression pass during the policy evaluation
- any built-in operators/functions will produce a single `undefined` value when `undefined` is supplied as one of the input
- any expression currently fails will produce a single `undefined` value
- User-defined functions / rules follow the 4 rules above

Would the solution above potentially solves our `undefined` issue and also be compatible with all existing rego language feature?

**Comment by anderseknert** [comment]
Hey again! I'm not sure I follow.. if the expressions still would fail evaluation on undefined, then undefined would not be a scalar value like others, would it? I do not believe a change like this would be possible, at least not without quite dramatic changes to how Rego works... and I'm not sure I see the upside of such a change, I'm afraid :)

**Comment by t83714** [comment]
Hi @anderseknert, Thanks for your reply.

To clarify, I mean an expression will fail only when the final evaluation result of the expression is `undefined` (like if an expression will fail when it's evaluated to a boolean value `false`) rather than failing once produce an `undefined` in the process of evaluating the value of the expression. 

Another way to look at it is that I actually suggest making `undefined` work similar to `false` (that makes the expression fail). Plus, make any operators evaluated to `undefined` when taking `undefined` as one of the operands.

e.g. expression `(1!=1) == true` will be evaluated to `false == true` -> `false` and fail.

For the two approaches, the final outcome would still be the same for most cases (that's why I think it'd be compatible with current language features). But allow users to have a chance to handle `undefined` manually.

e.g. for rego expression:
```rego
input.apps[2].count + 1 > 2
```
and assume the `input` data is:
``` json
{
  "apps": [{
    "count": 3
  }]
}
```

Currently, when evaluating the expression, the expression will fail when evaluating the value of `apps[2].count`.

But for the new approach:
- `apps[2].count + 1 > 2` will be evaluated to  `undefined + 1 > 2`
- which will become `undefined > 2`
- which will eventually be evaluated to `undefined` and fail as the final value of the expression is `undefined`

Although the outcome of the two approaches remains the same, the second approach makes the following possible:

``` rego
isEmpty(apps[2].count + 1 > 2)
```

where `isEmpty` is defined as:

```rego
isEmpty(v) {
    not v
}
```

If we adopt the second approach, `isEmpty(apps[2].count + 1 > 2)` -> `isEmpty(undefined)` -> `not undefined` will not fail.

Having said that, I am not familiar with OPA's implementation. 

If it requires dramatic changes to the current language construct, I guess we can probably leave it at that.

**Comment by anderseknert** [comment]
Going back to the previous example:
```rego
some x, y, z
p := data.authz[x].users[y].endpoints[z].permissions
```
What would `p` evaluate to in this loop?
An `undefined` literal for all instances of data without `authz`? And an `undefined` literal for all instances of data.authz without `users`? And an `undefined` literal for all instances of data.authz.users without `endpoints`? And an `undefined` literal for all instances of data.authz.users.endpoints without `permissions`? 🙂

**Comment by t83714** [comment]
Thanks for your comments @anderseknert 

I think it might be easier to look at a few "real" cases.

Given the rule `test` below:

```rego
test {
  some x, y, z
  p := data.authz[x].users[y].endpoints[z].permissions
  isEmpty(p)
  z > 1
}
isEmpty(v) {
    not v
}
```

1> When `authz`'s data is:
```rego
authz:= [{
 "users": [{
   "endpoints": [{
     "permissions": false
   },{
     "test": 1
   },{
     "permissions": true
   }]
 }]
}]
```

During the evaluation of rule `test`, the following values will be emitted during the loop:
- `x=0; y=0; z=0; p=false`. `test` will fail because of `z > 1` (`isEmpty(v)` will not fail)
- `x=0; y=0; z=1; p=undefined`. `test` will fail because of `z > 1` (`isEmpty(v)` will not fail)
- `x=0; y=0; z=2; p=true`. `test` will fail because of `isEmpty(v)`

As `test` will fail for all values during the loop, the rule `test` will not match (has value `undefined`).

2> When `authz`'s data is:
```rego
authz:= [{
 "users": [{
   "endpoints": [{
     "permissions": false
   },{
     "permissions": true
   },{
     "test": 1
   }]
 }]
}]
```

During the evaluation of rule `test`, the following values will be produced during the loop:
- `x=0; y=0; z=0; p=false`. `test` will fail because of `z > 1` (`isEmpty(v)` will not fail)
- `x=0; y=0; z=1; p=true`. `test` will fail because of `isEmpty(v)`
- `x=0; y=0; z=2; p=undefined`. `test` will match

As `test` will match when `x=0; y=0; z=2; p=undefined`. the value of `test` will be `true`

3> When `authz`'s data is:
```rego
authz:= [{
 "users": [{
   "abc": [{
     "permissions": false
   },{
     "permissions": true
   },{
     "test": 1
   }]
 }]
}]
```

During the evaluation of rule `test`, the following values will be produced during the loop:
- `x=0; y=0; z=undefined; p=undefined`. 
  - `test` will fail because:
    -  `isEmpty(v)` will not fail
    - `z>1` will fail

As `test` will fail for all values during the loop, the rule `test` will not match (has value `undefined`).

4> When `authz`'s data is:
```rego
authz:= [{
 "abc": [{
   "def": [{
     "permissions": false
   },{
     "permissions": true
   },{
     "test": 1
   }]
 }]
}]
```

During the evaluation of rule `test`, the following values will be produced during the loop:
- `x=0; y=undefined; z=undefined; p=undefined`. 
  - `test` will fail because:
    -  `isEmpty(v)` will not fail
    - `z>1` will fail

As `test` will fail for all values during the loop, the rule `test` will not match (has value `undefined`).

5> When `authz`'s data is:
```rego
authz:= []
```
During the evaluation of rule `test`, the following values will be produced during the loop:
- `x=undefined; y=undefined; z=undefined; p=undefined`. 
  - `test` will fail because:
    -  `isEmpty(v)` will not fail
    - `z>1` will fail

As `test` will fail for all values during the loop, the rule `test` will not match (has value `undefined`).

**Comment by anderseknert** [comment]
@t83714 I appreciate the effort spent to motivate this, but I don’t think a change like this would be possible without a major rewrite of the language, and one that would break all kinds of things. As such, I will close this for now. Hopefully people interested in this will find the issue regardless, and can add to the discussion.

Thanks!

**Comment by anderseknert** [comment]
I should add though - there are several open issues available for how to better deal with undefined values. Hopefully with those getting attention, this would be less of an issue.
