### ISSUE TITLE
download bundles via OCI without credentials

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#5212]
## Short description 

Pulling bundles from OCI registries should work if there are no credentials involved. But it's been reported to raise an error:
```
{"error":"failed to authorize: failed to fetch oauth token: unexpected status: 500 ","host":"<some internal oci repo>","level":"info","msg":"trying next host","time":"2022-10-06T07:37:20Z"}
```

ℹ️ v0.44.0

**Comment by srenatus** [comment]
If you're looking into this, please LMK, I've got a branch with oras/v2 lying around. We shouldn't fix the current code, it's got to be changed significantly anyways.

**Comment by anderseknert** [comment]
Summoning @carabasdaniel 🧙🏻‍♂️😃

**Comment by srenatus** [comment]
Here's the WIP I've promised to share -- https://github.com/open-policy-agent/opa/compare/main...srenatus:opa:sr/oci/oras-v2-second-try

**Comment by gaurav137** [comment]
+1 on this issue. Hope this gets fixed soon.
