### ISSUE TITLE
repl: "dump" failing on case-sensitive file systems?

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#5229]
That's the evidence: https://github.com/open-policy-agent/opa/pull/5227#issuecomment-1273975492

There is no reason it should depend on case-insensitivity to work correctly. Let's make it work on case-sensitive FSes.

**Comment by burnerlee** [comment]
@srenatus could I pick this up?

**Comment by burnerlee** [comment]
@srenatus is converting the command to Lower case necessary [here](https://github.com/open-policy-agent/opa/blob/50d4e31d6b41382f8fa4d29f8be30b6974e4da74/repl/repl.go#L1357)? Either we can remove this lower case conversion, or we would have to pass the filepath in this function to recover the case sensitive filepath.
To fix this error, the final command generated should have the original filepath (case-sensitive)

**Comment by srenatus** [comment]
I've assigned you. Thanks for contributing 👏

**Comment by anderseknert** [comment]
Any updates on this @burnerlee ?

**Comment by Trolloldem** [comment]
Hi @srenatus. I see the issue is still present in OPA, may I try to finish what @burnerlee suggested and open a PR?

**Comment by srenatus** [comment]
Sure!
