### ISSUE TITLE
Request for an `object.key_exists(object, key)` built-in function

### ISSUE THREAD

**Issue by nevumx** [open-policy-agent/opa#5232]
## What is the underlying problem you're trying to solve?
Currently, if one wants to check if a key exists, (even if its value is `false`) the current best option is to write a hacky-looking utility function like this:
```
key_exists(object, key) {
	_ = object[key]
}
```
Or with the slightly more readable but also more verbose disjunction:
```
key_exists(object, key) {
	object[key]
}
key_exists(object, key) {
	object[key] == false
}
```

## Describe the ideal solution
The ideal solution would be an `object.key_exists(object, key)` built-in function that has the same behavior as those above, and possibly some similar functions like `object.keys(object)` or `object.values(object)` that have the same behavior as the built-in JavaScript functions of the same name.

## Describe a "Good Enough" solution
Just an `object.key_exists(object, key)` built-in function would be good enough.

## Additional Context
A scenario where a built-in function to tell if a key exists would be useful would be passing an object as an argument to a function in order to simulate named parameters, and some of those parameters are optional, and should either not exist, or match a specific value, as with the "optional_fourth" parameter in [this playground](https://play.openpolicyagent.org/p/5ttRJU2ycx).

**Comment by srenatus** [comment]
Hmm this never struck me as hacky. Compared with the work that would have to be put into a built-in for the same thing, it's quite nice and small. 

You could also write, I think, 
```
has_key(obj, key) if _ = obj[key]
```
with future.keywords.if.
Likewise, the other helpers should be straightforward to implement in rego. I'm not sure I'm convinced that this warrants extra helpers.

**Comment by srenatus** [comment]
ℹ️ https://github.com/anderseknert/opal/blob/0615b9bd2f88efcf569ad2ed657c16e92547edf9/lib/objects.rego#L3-L7

```rego
package objects

# Return all (top-level) keys in object o
keys(o) = [k | o[k]]

# Return all (top-level) values in object o
values(o) = [v | v := o[_]]
```

**Comment by anderseknert** [comment]
There's a whole bunch of simple built-in functions on my wish list too 🙂 I believe the need for that would be alleviated with https://github.com/open-policy-agent/opa/issues/3371 in place, as we'd then be able to provide whole classes of nice-to-have functions via some semi-official "stdlib". I do believe it's on the road map.

**Comment by anderseknert** [comment]
Superseded by https://github.com/open-policy-agent/opa/issues/5363

Which has an open PR, so this will be in soon 😃
