### ISSUE TITLE
Init-proxy has restart and crash loopback. 

### ISSUE THREAD

**Issue by vinhph0906** [open-policy-agent/opa#5233]
## Short description 
I have used opa-envoy-plugin for authz in my product. But it has an issue with the init-proxy container. For more detail: when init-proxy as a init container has finished, then this container because of some reason like Garbage Collection or `docker system prune`, was deleted. More detail at https://github.com/kubernetes/kubernetes/issues/67261. Then k8s will create a new one and re-run. But when it restarted Iptables have existed chain so it exited with code 1 with the reason Iptables: Chain already exists.
## Steps To Reproduce
Delete container init-proxy in docker. 
## Expected behavior
init-proxy should be resilient to running twice.

**Comment by srenatus** [comment]
It looks like you've got some debugging done here already _and_ you've got the means to reproduce it. Would you be interested in contributing a fix? 😃

**Comment by vinhph0906** [comment]
Hmmm. I just trace to root cause of this issue, but I till fix it yet. Maybe you can assign it to me. I will contribute as soon as possible.

**Comment by scaledapps** [comment]
@srenatus : Is there a workaround (version downgrade) that could help, until this issue gets fixed?

**Comment by srenatus** [comment]
@scaledapps This has been like it is forever, downgrading won't help.

The init container isn't that special, you could look at this, https://github.com/open-policy-agent/contrib/pull/190, and build it on your own until the fix lands (in opa-envoy-plugin).

**Comment by srenatus** [comment]
@scaledapps thanks to @vinhph0906's contribution, `openpolicyagent/proxy_init:v8` should no longer dive into a crashloop when its iptables chain already exists.

**Comment by scaledapps** [comment]
Thanks for the fix @vinhph0906!
