### ISSUE TITLE
Out-of-band metrics extraction

### ISSUE THREAD

**Issue by rlguarino** [open-policy-agent/opa#525]
It would be fantastic if the OPA server exposed metrics via a Prometheus endpoint.

Metrics that would be great to have:
* default go
* default pprof
* Rate (queries/second)
* Errors (Error/second)
* Duration (how long the queries take)

Let me know what you think.

**Comment by tsandall** [comment]
This would definitely be nice to have. The metrics you listed look right to me, i.e., throughput, latency, errors + golang runtime stats.

OPA does not currently have global/cross-request metrics. Metrics are recorded for individual queries and then if a client requests metrics, they are returned alongside the policy result in the API response. Do we need to introduce a global metrics collection so they can be queried/scraped via the API?

**Comment by rlguarino** [comment]
It's probably best to just use the Prometheus structs as the canonical source of truth for metrics data.

If there is already logic for calculating the latency of a request then it should be relatively simple to take that information and push it into a Prometheus Metric object before the are results are returned. All that would need to be done would be to create a new instance in the main entry-point and plumb it to the function calculating metrics.

It might also be worth while to use the https://github.com/go-kit/kit/tree/master/metrics package to be able to support other exposition formats in the future.

**Comment by tsandall** [comment]
I'm not familiar with the Prometheus API/Go client library but this sounds relatively straightforward.  Assuming there is some initialization required that could be done in the `opa/runtime` package before the server is started and then the client could be provided to the server. Then, whenever a request is processed, the server would invoke the client to push metrics to Prometheus.

In the server, we could either push the overall request latency, or, more fine-grained metrics like the time taken to parse, compile, and evaluate the query (each is recorded separately inside OPA.) Do you think we should emit each of these as separate metrics or just emit a single metric that is the sum + overhead of handling the API request?

This is the HTTP handler that responds to POST /v1/data[/path] requests: https://github.com/open-policy-agent/opa/blob/master/server/server.go#L638

We have timers for different phases of request handling:
- Parse: https://github.com/open-policy-agent/opa/blob/master/server/server.go#L656
- The `opa/rego` package takes care of rest: https://github.com/open-policy-agent/opa/blob/master/server/server.go#L685
- Metrics after evaluation are available here: https://github.com/open-policy-agent/opa/blob/master/server/server.go#L719

**Comment by rlguarino** [comment]
I think we should start with just the overall request duration and error rate for the different types of requests. The instrumentation of specific fine-grained routines sound like something that would be better served with [tracing](http://opentracing.io/) instead of metrics.

> Then, whenever a request is processed, the server would invoke the client to push metrics to Prometheus.

Prometheus actually works in the opposite direction. With Prometheus an instrumented server listens on a metrics endpoint that exposes the [proper format](https://prometheus.io/docs/instrumenting/exposition_formats/) and the Prometheus server scrapes that endpoint periodically.

**Comment by tsandall** [comment]
>  I think we should start with just the overall request duration and error rate for the different types of requests. The instrumentation of specific fine-grained routines sound like something that would be better served with tracing instead of metrics.

Sounds good. The required changes should be contained to the runtime and server packages then (i.e., no need to modify the parser/compiler/interpreter for now.) Adding an extra endpoint should be not a problem.

**Comment by rlguarino** [comment]
@tsandall Just so you know, I plan on taking a stab at this next week (after the holiday).

**Comment by tsandall** [comment]
Sounds great. I'm out for the first week of Jan but if you need help getting up in running ping #general on slack.openpolicyagent.org and @timothyhinrichs or someone else can help you out.

**Comment by tsandall** [comment]
Initial added in #590.
