### ISSUE TITLE
Making a Toggle button to switch Light/Dark Mode

### ISSUE THREAD

**Issue by UtkarshMishra12** [open-policy-agent/opa#5253]
## What is the underlying problem you're trying to solve?

Making a Toggle button to switch Light/Dark Mode
## Describe the ideal solution

Every developer/user wants to have a button on the website to switch between Dark/Light mode. As it improves the user experience.

My idea is simple, implement Dark mode for the website, making a toggle button where we can switch between Light Mode/Dark Mode.

Let me know your thoughts about it.

**Comment by anderseknert** [comment]
Hi @UtkarshMishra12 👋 

Yes, that + defaulting to the preferred light/dark setting of the user OS, would be pretty nice. If someone would want to work on this, why not? 🙂

Tangentially related; I've been pretty happy with the various dark mode extensions available for most browsers. Using those, I don't have to rely on the websites I visit to provide this. Some would however likely look better if they had provided this themselves.

**Comment by UtkarshMishra12** [comment]
So should I start working on this implementing the toggle feature? @anderseknert for the Home Page.

**Comment by anderseknert** [comment]
@UtkarshMishra12 I would probably start investigating the options for this in the docs, as that's where most of the content is. We're using Hugo for those, and there are probably some plugins for this we could leverage. Once that looks nice, the other pages should be fairly simple to cover.

**Comment by srenatus** [comment]
The Hugo stuff uses bulma. Let's be sure to check bulma's features for that before inventing our own.

https://github.com/jloh/bulma-prefers-dark might be relevant, too.

**Comment by anderseknert** [comment]
If someone wants to pick this up later, let’s re-open it then. Closing for the time being.
