### ISSUE TITLE
Changing the footer background color from gray to blue

### ISSUE THREAD

**Issue by UtkarshMishra12** [open-policy-agent/opa#5254]
## What is the underlying problem you're trying to solve?

Changing the footer background color from gray to blue

## Describe the ideal solution

As I was scrolling on the website when I see the footer it was having a gray color which looks odd compared to other colors present on the website.

So I just wanted to convert it into a blue color which will improve the look of the website. 

I'm attaching the screenshot below.

Before : 
![Screenshot (491)](https://user-images.githubusercontent.com/67385503/195989564-e78dcd44-e865-45d8-a979-d15f8ebb254d.png)

**Comment by UtkarshMishra12** [comment]
[Image Link](https://drive.google.com/file/d/16h6UMQ3Ts19Ci6HP25swHXycUup_edOA/view?usp=sharing)

You can see the updated footer.

**Comment by anderseknert** [comment]
Hmm, obviously this is subjective, but I'm not sure I agree with this. The footer is gray like the OPA logo, and many of the other elements already use that blue color. Can't say I feel strongly about this though :)

**Comment by UtkarshMishra12** [comment]
So what's the conclusion? The blue color will definitely improve the UX.

**Comment by anderseknert** [comment]
There’s no conclusion, and others are free to weigh in with their opinion. That a blue footer “definitely” would improve the UX is also just an opinion, and if others agree, we should have it changed.

**Comment by UtkarshMishra12** [comment]
Let me know about the thoughts of other maintainers & contributors. So that we can decide.

**Comment by Parsifal-M** [comment]
Just my two cents, I think the grey is fine, and I think making it blue might clash with the gradient coloring at the top of the page. Again as @anderseknert this is subjective 😅 and I'm no UX expert...

**Comment by peteroneilljr** [comment]
Hard to know without the specific color hexcode, there are many shades of blue. :) 

Can you provide the hexcode for the blue you're referring to? Or better yet, can you change the color with DevTools and take a screenshot so that we can see the side-by-side comparison?

**Comment by anderseknert** [comment]
@peteroneilljr WDYT? I have no strong opinion here.

**Comment by peteroneilljr** [comment]
I like it, I don't see any reason not to do it.

**Comment by UtkarshMishra12** [comment]
@peteroneilljr So may I proceed with it?

**Comment by peteroneilljr** [comment]
Yes! Go for it!
