### ISSUE TITLE
Test coverage threshold can exceed 100%

### ISSUE THREAD

**Issue by aholmis** [open-policy-agent/opa#5284]
## Short description 
When executing for example `opa test . -c --threshold 101` you get the error saying 
`Code coverage threshold not met: got 100.00 instead of 101.00`

A negative value is also accepted and used as any other number.

To avoid setting an unintended or impossible threshold, let's exit if the threshold is above 100 or less than 0

* Tested with OPA version 0.44.0

## Steps To Reproduce
Run tests with a code coverage threshold <0 or >100

## Expected behavior
If the threshold argument is <0 or >100, print this message and exit with a non-zero value
`Code coverage threshold must be between 0 and 100`

**Comment by hzliangbin** [comment]
@srenatus PTAL
