### ISSUE TITLE
Improve http.send cache lookup and freshness logic

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5300]
The current approach to cache lookups and freshness checks is to store the headers as sent by the remote server, and each time we check if an entry should be fetched from cache or from the remote, we parse all the relevant date-related headers — `Date`, `Cache-Control` (including `max-age`) and `Expires` in order to determine if the cache entry is fresh. 

Let's instead do this parsing only once — when the cache entry is created, and store the timestamps directly for comparison in the freshness checks. This would improve performance of cache lookups, but it would also nicely abstract away the details of the HTTP spec from the caching logic.

In order to do this, we'll need to extend the test suite for inter query caching in `http.send`, which surprisingly was almost non-existent before https://github.com/open-policy-agent/opa/pull/5298 .. while some e2e tests are added there, we'll probably need another approach to test expiry.

**Comment by srenatus** [comment]
Could you open an issue, please? (Or search for an existing one?) It seems like having a periodic cache-cleaning routine would help you, but let's flesh out the details together.

**Comment by lukyer** [comment]
Sure, I wasn't sure if this improves the situation somehow or not. I'm not too familiar with your codebase yet.
If you think this does not improve the cache cleaning behaviour, I'm happy to create new feature request issue.

**Comment by srenatus** [comment]
The idea here was to straighten something out that was a bit quirky in the code. No functional changes involved. Thanks for the issue!

**Comment by anderseknert** [comment]
@lukyer: @srenatus is right about that. However, this change does pave the way for what you suggest, as this would have been quite expensive before, as we'd have to iterate over each item, parse all the date-related headers, and check for expiry. Now we can just check for expiry directly.
