### ISSUE TITLE
server: compress large response payloads if client supports it

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5310]
For certain types of payloads, or just exploratory browsing of `/data`, the main time spent for these queries is not inside of OPA, but waiting for data in transit. If the client supports content encoding like gzip, compressing the data may provide quite a dramatic reduction of payload size and hence total response time.

1. If an integrating HTTP client sends an `Accept-Encoding` header including `gzip`...
2. ...and the payload is larger than some arbitrary number, like 1 kB...
3. Respond with a `Content-Encoding: gzip` header and a gzip compressed payload.

**Comment by srenatus** [comment]
https://pkg.go.dev/github.com/gorilla/handlers#CompressHandler we should perhaps just use something like that. 💭

**Comment by anderseknert** [comment]
Of course, @sanjeev98kumar 👍 

I would not expect much time to be spent setting anything up — just clone the repo and get hacking :)
But do see  https://www.openpolicyagent.org/docs/latest/contrib-code/ and https://www.openpolicyagent.org/docs/latest/contrib-development/ for some useful information on contributing. And feel free to ask any questions whenever you want.

**Comment by margelatu** [comment]
+1 for supporting compression, we're also in need of this feature.

**Comment by anderseknert** [comment]
@sanjeev98kumar any progress to report on this issue? 🙂

**Comment by burnerlee** [comment]
@anderseknert @srenatus can I pick this issue up if it's okay?

**Comment by srenatus** [comment]
@burnerlee since there's no response from @sanjeev98kumar for a while, I guess that's OK 👍

**Comment by burnerlee** [comment]
@srenatus can you help by giving me some insight into the issue? Like in which section of the project we're making this change and what do we exactly want to do?

**Comment by burnerlee** [comment]
I've opened a draft PR from what I could understand from the issue description. Do we need to add this handler somewhere else too?

**Comment by srenatus** [comment]
Ideally, tests would tell us, I think.

**Comment by irwanshofwan** [comment]
can I pick this issue or pair for this ? @anderseknert @srenatus

**Comment by anderseknert** [comment]
Hey @irwanshofwan! Perhaps we could get an update from @burnerlee first? He has an open PR for this here, but as far as I can see, there's a few unaddressed comments there. An unforseen event here is how the gorilla library was archived just recently, so whoever works on this issue will likely want to await[ this PR ](
https://github.com/open-policy-agent/opa/pull/5483)to be merged.

**Comment by anderseknert** [comment]
But either way, thanks for stepping up! 😃

**Comment by burnerlee** [comment]
hey @irwanshofwan please go ahead. I'm stuck in some other things rn and not able to contribute. Sorry for holding you guys back

**Comment by burnerlee** [comment]
i would suggest continuing the same PR. we just need to handle the tests right now

**Comment by irwanshofwan** [comment]
sure, will try continue from existing PR

**Comment by anderseknert** [comment]
Whatever works for you, but do see my note about gorilla above.

**Comment by irwanshofwan** [comment]
sure, I believe we can do it parallel for this issue and rebase after the gorilla mux solved.

**Comment by margelatu** [comment]
@irwanshofwan any news on this ? 

Context: we use OPA heavily at Adobe and in some scenarios need `gzip` support on both requests and responses as they get rather large.

**Comment by anderseknert** [comment]
@margelatu I believe this was put on hold while waiting for the router library situation to be resolved. But this is probably simple enough to pull off without having to use a helper from there, should anyone want to step up and do it :)

**Comment by AdrianArnautu** [comment]
@anderseknert I'd like to try out to do this feature, as suggested, without a helper. 
I'm working in the same team with @margelatu , we need OPA to be able to consume/produce compressed payloads.

**Comment by anderseknert** [comment]
@AdrianArnautu go for it! 👍
