### ISSUE TITLE
Semver builtin with support for short versions

### ISSUE THREAD

**Issue by roughbits01** [open-policy-agent/opa#5317]
```Rego
package play

import future.keywords.if

default hello := false

hello if semver.compare("1.0", "1.0")
```

I expect hello to be `true` here since both versions are equal. Any reason this is not supported and that we need to provide the full (`1.0.0`) version?

I have to do something like this to support these versions
```Rego
format(version) = semver if {
	count(indexof_n(version, ".")) == 0
	semver := concat("", [version, ".0.0"])
} else = semver {
	count(indexof_n(version, ".")) == 1
	semver := concat("", [version, ".0"])
} else = semver {
	semver := version
}
```

**Comment by anderseknert** [comment]
Hi there! I can't find anything in the SemVer [spec](https://semver.org/) that suggests the patch version would be optional. Is it?

**Comment by roughbits01** [comment]
You are right it's not in the spec. Found [this relevant conversation ](https://github.com/semver/semver/issues/237). Since it's not in the spec I guess nothing needs to change here unless we think it makes sense to add  relaxed version.

**Comment by anderseknert** [comment]
I think we should leave the current function as it is, given that it has "semver" in the name :) If other people go look for a solution to this, your code above should provide them that. If there's demand for a built-in function to compare "non-semantic" versions in the future, we can definitely consider that, but let's close this for now.
