### ISSUE TITLE
Future keywords don't appear to change the compatibility matrix for opa

### ISSUE THREAD

**Issue by TheLunaticScripter** [open-policy-agent/opa#5323]
I am building a bundle and utilizing the `--capabilities`  flag and have found that I am still able to build a bundle when the policy contains keywords like `if` or `contains`.

## Short description 
 
When attempting to run a build with keywords that were released as part of 0.42.0 the capabilities checks during build doesn't fail when given the capabilities file for 0.41.0 or even 0.17.0

## Steps To Reproduce
1. Create a policy file
2. Add the following rego

```
import future.keywords.contains
import future.keywords.if

deny contains msg if {
    msg := sprintf("there are %d violations", ["1"])
}
```
3. Run build command

```
opa build policy.rego --capabilities ~/go/src/github.com/open-policy-agent-opa/capabilities/v0.17.0.json
```
>Note: expected first capabilities file to fail is v0.41.0.json and v0.42.0.json should pass and successfully build

4. There is no error and a bundle is built
5. Add this code to the policy file

```
v := object.subset({{1,2,4},{1,4,5}},{1,2,4})
```

4. Run build command

```
$ opa build policy.rego --capabilities ~/go/src/github.com/open-policy-agent-opa/capabilities/v0.41.0.json
error: 1 error occurred: rules.rego:10: rego_type_error: undefined function object.subset
```
5. Error as shown is expected
6. Run opa build with expected passing capabilities file v0.42.0.json and bundle builds successfully.

**Comment by srenatus** [comment]
Thanks! This doesn't look correct indeed. The future kws should be in the caps files, but I suppose they aren't plumbed through properly...
