### ISSUE TITLE
Aligning the footer text to the center (CNCF Text)

### ISSUE THREAD

**Issue by UtkarshMishra12** [open-policy-agent/opa#5336]
## What is the underlying problem you're trying to solve?
Aligning the footer text to the center (CNCF Text)

## Describe the ideal solution
Before:
![image](https://user-images.githubusercontent.com/67385503/199391143-75336979-5e35-44bb-baf4-03760ada829e.png)

After:
![image](https://user-images.githubusercontent.com/67385503/199391180-ebd63d65-7930-4965-aade-997f8212b4ca.png)
It will fit as per the screen size.

**Comment by anderseknert** [comment]
Slack is probably a better place to ask about simple style changes like this. Even if we want to do this — and I'm not sure about that — this is not enough to warrant an issue. Let's pick up the conversation on Slack 🙂
