### ISSUE TITLE
enhance failed test output

### ISSUE THREAD

**Issue by ilrudie** [open-policy-agent/opa#5342]
## What is the underlying problem you're trying to solve?

When writing policy if a unit test fails it's often useful to copy the test into the Rego playground in order to analyze what is going wrong. The Rego playground has great detail in the output which is missing from the present test framework as far as I can tell.

## Describe the ideal solution

It would be a great enhancement if the failed test could print out the relevant results of every rule evaluation similar to how the rego playground shows results if nothing in the Rego text box is highlighted.

## Describe a "Good Enough" solution

It would still be helpful if the results if every rule evaluation had output. This may be easier to implement but likely would be more difficult to read.

## Additional Context

- I think the enhanced output could only print for the test that failed. All passing tests would just show normal output.
- Due to verbosity of the output as well as computational complexity putting this output behind a flag would probably be helpful.
    - idea for how the flags might be structured:
    ```
    --verbose-tests=none      # current behavior, also probably the default to maintain familiar behavior
    --verbose-tests=fail      # only failed tests print the new output
    --verbose-tests=all       # all tests would print the new output
    ```

**Comment by anderseknert** [comment]
Hi @ilrudie 👋 Did you try running with the `-v` flag on? It's not easy to digest, but at least it's something in that direction. Also, you might like https://github.com/anderseknert/rego-test-assertions

**Comment by ilrudie** [comment]
Hi @anderseknert, thanks for the suggestions.

We do use the -v flag to get that sort of stacktrace-style output. I still find that often I'm suggesting to folks to use Rego playground to help analyze why their test is failing. It's plausible that no enhancement to the test functionality in opa will be a replacement for the playground's great functionality but I thought this idea might help.

The rego-test-assertions looks cool. I'll have to dig into that more.

**Comment by anderseknert** [comment]
That does indeed help! The `opa test` command can emit `--coverage` so granted that you have some tool to parse that, you should be able to get pretty much the same thing from your terminal. Perhaps [ocov](https://github.com/C5T/ocov) from @dkorolev could be useful?
