### ISSUE TITLE
Consider row level security use case

### ISSUE THREAD

**Issue by AceHack** [open-policy-agent/opa#535]
Should I use this when I'm trying to enforce row level security at a code level where the database does not support it?

**Comment by tsandall** [comment]
Could you share more details on the use case you have in mind? It sounds like you have a collection of database results (e.g., a set of rows) and you want to filter which rows are returned to your client (e.g., by inspecting the column values in each row) or you want to filter which columns are returned to your client.

**Comment by AceHack** [comment]
@tsandall yes that is what I'm talking about.  In an ideal world, I would like to define policies in OPA and if the underlying db supports to actually push and execute that policy in the database.  If the db does not support it then there would be an OPA passthrough that understood the wire protocol and modified queries or results accordingly.

Here is the best db row level security documentation I can find for further details.
https://docs.microsoft.com/en-us/sql/relational-databases/security/row-level-security

We actually make sure of several db and some have row level security and some do not.

**Comment by tsandall** [comment]
OK. We're on the same page. Taking an OPA policy and pushing it down into the DB is an area of interest. To do this, the OPA policy would need to be compiled down to the policy or query language supported by the DB.

Implementing a passthrough for different protocols is probably outside the scope of OPA right now but the same enforcement mode could be achieved by integrating OPA either in the application or a sidecar proxy like Envoy, Linkerd, etc.

We're currently working on a partial evaluation feature in OPA that will make it easier to compile OPA policies/queries down to other languages (e.g., SQL).

**Comment by AceHack** [comment]
In the case where you can't push to the db or have a protocol level passthrough, an ORM plugin would be great that cloud automatically adds predicate filters (where clauses).  It would be great if this was design in a way that would make it easy to plug into any ORM but a reference ORM using the plugin would be a great example.

**Comment by tsandall** [comment]
Closing this for now. We're planning to work on row-level security in upcoming releases.

**Comment by amesas** [comment]
Any news on this? Still planned?

**Comment by tsandall** [comment]
@amesas we've done a bunch of work in this area. See this blog post https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4

There are links to example code in the contrib repository that show it in action.

**Comment by lamuertepeluda** [comment]
> @amesas we've done a bunch of work in this area. See this blog post https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4
> 
> There are links to example code in the contrib repository that show it in action.

Hi there @tsandall, the link you provided is not working. Did the content move to some other platform?

**Comment by srenatus** [comment]
I don't know what happened, but the link is working again.
