### ISSUE TITLE
http.send cache concurrency issues

### ISSUE THREAD

**Issue by asleire** [open-policy-agent/opa#5359]
## Short description 
The `http.send` interquery cache breaks during concurrent OPA requests.

Symptoms include:
 * The [usage](https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go#L87) counter increases even though the same request is being made
 * Even if there are only two unique `http.send` requests being made by the policy, when the `usage` counter reaches max size something breaks in a way that an outgoing http request is made on every single request to OPA

## Steps To Reproduce

In short:
1. Create a policy whose evaluation will cause 2 `http.send` requests force cached for 1 second
2. Run many concurrent requests to evaluate the policy
3. Look at outgoing requests

In long:

I don't know Go so I wouldn't know how to reproduce this directly in the OPA code. Initially I ran load tests against our OPA server and detected through our metrics system that OPA suddenly started making a lot of outgoing requests.

My minimal reproduction is as follows:
1. I cloned the OPA repository, and just before [this](https://github.com/open-policy-agent/opa/blob/e5bc273e5893b145298f2bfb994c101b6ff77300/topdown/cache/cache.go#L144) line I simply added a line `fmt.Println(time.Now().Second(), "unsafeInsert", c.usage, dropped)` which would tell me when something was inserted into the cache, and the size of the cache.
2. I added a policy that makes two `http.send` requests, each with a 1 second forced duration. See below for my policy. Note that I hid the URLs as I don't want just anyone to spam them :) Any URL that returns some amount of JSON data should do.
3. I run the OPA server using the following command: `go run main.go run policy -s --set=caching.inter_query_builtin_cache.max_size_bytes=1000000 --set=decision_logs.console=false --log-level error`
4. I run a load test on the OPA server using Locust and several users. See below for my script, and my observations.

**My OPA policy:** 
<details>
<summary>Click me</summary>

```
package loadtest

req1 := http.send({
	"url": "<url1>",
	"method": "GET",
	"raise_error": false,
	"force_cache": true,
	"force_cache_duration_seconds": 1,
})

req2 := http.send({
	"url": "<url2>",
	"method": "GET",
	"raise_error": false,
	"force_cache": true,
	"force_cache_duration_seconds": 1,
})

result := "OK" {
	not req1.error
    not req2.error
} else := "ERROR" {
	true
}
```

</details>

**My locust script:** 
<details>
<summary>Click me</summary>

```
from locust import HttpUser, task

class HelloWorldUser(HttpUser):
    @task
    def read(self):
        self.client.get("/v1/data/loadtest/result")
```

</details>

**Locust test run with a single user:**
This works just like one would expect. The output from OPA is as follows:
```
44 unsafeInsert 4757 0
44 unsafeInsert 10902 0
45 unsafeInsert 10902 0
45 unsafeInsert 10902 0
46 unsafeInsert 10902 0
46 unsafeInsert 10902 0
47 unsafeInsert 10902 0
47 unsafeInsert 10902 0
48 unsafeInsert 10902 0
48 unsafeInsert 10902 0
49 unsafeInsert 10902 0
49 unsafeInsert 10902 0
```
Every second, two items are inserted into the cache, and the cache size does not grow indefinitely

**Locust test run with two users:**
The output from OPA is as follows:
```
56 unsafeInsert 4757 0
56 unsafeInsert 10902 0
57 unsafeInsert 10902 0
57 unsafeInsert 15659 0
57 unsafeInsert 15659 0
57 unsafeInsert 21804 0
58 unsafeInsert 21803 0
58 unsafeInsert 20415 0
58 unsafeInsert 26559 0
58 unsafeInsert 32704 0
59 unsafeInsert 32704 0
59 unsafeInsert 31316 0
59 unsafeInsert 37461 0
59 unsafeInsert 43606 0
... // truncated, it keeps growing!
```
4 requests per second. I guess that's fine, but the cache size keeps growing!

At some point the cache size reaches the configured max size. And at that point the logs start looking like this:

<details>
<summary>Click me</summary>

```
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997022 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 995634 1
7 unsafeInsert 995634 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 997022 1
7 unsafeInsert 997023 1
7 unsafeInsert 997022 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 995635 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
7 unsafeInsert 997023 1
``` 
</details>
Very, very many outgoing requests per second. The cache is effectively broken

## Expected behavior
Caching should work even with concurrent requests :) 

## Additional context
I've reproduced this in the docker images `0.45.0` and `0.46.1`, as well as by compiling and running the main branch at [this](https://github.com/open-policy-agent/opa/tree/e5bc273e5893b145298f2bfb994c101b6ff77300) point.

Let me know if you need any more info

**Comment by asleire** [comment]
You may find this interesting (I did!): When we first noticed this issue in our cluster, we saw that an affected OPA container had a **huge** drop in memory usage the moment it started doing a lot of outgoing HTTP requests
![image](https://user-images.githubusercontent.com/631907/199986640-05f9fdde-40ec-47ce-8868-e6592bd34a0b.png)

**Comment by srenatus** [comment]
Thanks for writing this up.

> Caching should work even with concurrent requests :)

Yes, definitely 🙃 

So I can't pinpoint this right away, the only thing I notices is that if you go from

```go
	c.mtx.Lock()
	defer c.mtx.Unlock()
	return c.unsafeInsert(k, v)
```
to
```go
	c.mtx.Lock()
	defer c.mtx.Unlock()
	fmt.Println(time.Now().Second(), "unsafeInsert", c.usage, dropped)
	return c.unsafeInsert(k, v)
```
you will never see dropped != 0. Maybe it would be interesting to do this instead

```go
	c.mtx.Lock()
	defer c.mtx.Unlock()
	dropped = c.unsafeInsert(k, v)
	fmt.Println(time.Now().Second(), "unsafeInsert", c.usage, dropped)
	return
```

**Comment by asleire** [comment]
I think you're looking at the wrong line? The link I sent works for me 🤔 https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go#L144
![image](https://user-images.githubusercontent.com/631907/199989003-1ed2ff68-cff0-49a9-9180-4042bb6f649f.png)

Anyway, I don't think the `dropped` value isn't very interesting or relevant. I just added it when I was initially trying to reproduce using the cloned repository

**Comment by srenatus** [comment]
So please correct me if I'm wrong but there are two things here to think about, I suppose:
1. Why does the same request keep getting made in the first place, when it shouldn't be based on the caching logic?
1. what happens if the inter query cache is full?

**Comment by srenatus** [comment]
> I think you're looking at the wrong line? 

yes I was 😳 sorry about that. please ignore.

**Comment by asleire** [comment]
> 1. Why does the same request keep getting made in the first place, when it shouldn't be based on the caching logic?

I'm guessing there's no locking mechanism on identical `http.send` requests, so when OPA processes two concurrent requests those two requests will both see that the currently cached item has expired and they both will perform a new request and insert each response into the cache. 

It would be nice that OPA didn't make these concurrent identical requests, but my big issue is that when the cache eventually becomes full the cache barely seems to work at all

**Comment by srenatus** [comment]
> I'm guessing there's no locking mechanism on identical http.send requests, so when OPA processes two concurrent evals those two evals will both see that the currently cached item has expired and they both will perform a new http request and *insert each response into the cache.*

So you got me thinking -- the two requests shouldn't *each* be stored in the cache, but only one of them. But looking at the code, that's just half the story:

https://github.com/open-policy-agent/opa/blob/e5bc273e5893b145298f2bfb994c101b6ff77300/topdown/cache/cache.go#L141-L142

L141 will overwrite, but L142 will append.

**Comment by srenatus** [comment]
Similarly when that has happened, the extra copy is never removed: the c.l.Remove() in L136 will only remove one copy of it from the list:
https://github.com/open-policy-agent/opa/blob/e5bc273e5893b145298f2bfb994c101b6ff77300/topdown/cache/cache.go#L136

[playground](https://go.dev/play/p/cDUNrMx73jA)

**Comment by srenatus** [comment]
But none of this should happen in the first place:

https://github.com/open-policy-agent/opa/blob/e5bc273e5893b145298f2bfb994c101b6ff77300/topdown/cache/cache.go#L101-L105

Even for concurrent requests, the mutex lock on the cache should mean that for two concurrent requests of the same key (i.e. http.send args), only one should ever be made 🤔 Where does it go wrong...?

**Comment by asleire** [comment]
> the extra copy is never removed

It should be removed when the cache is full here: https://github.com/open-policy-agent/opa/blob/main/topdown/cache/cache.go#L136

> Even for concurrent requests, the mutex lock on the cache should mean that for two concurrent requests of the same key (i.e. http.send args), only one should ever be made

It only prevents them from accessing the cache at the same time, but they will both insert the cache item. Which will cause the size to increase twice. But when the cache item is eventually removed, the size is only decreased once. ... Right? Did I just figure it out? 😅

**Comment by srenatus** [comment]
OK I think I see the problem: While each Get and Insert method of the cache is guarded by a mutex, the caller doesn't do that: in `topdown/http.go`, we first check if the response is cached,

https://github.com/open-policy-agent/opa/blob/e5bc273e5893b145298f2bfb994c101b6ff77300/topdown/http.go#L1254

and then we insert the result.... your response has just popped up, and yes, I believe you've figured it out 😄

**Comment by srenatus** [comment]
Now, how will we solve this? 😅

**Comment by asleire** [comment]
Personally I might prefer if `http.send` somehow acquired a lock on the cache key before it checks the cache or executes the HTTP request. This way `http.send` can perform different HTTP requests concurrently while only doing identical HTTP requests once, which I'm guessing is the behavior most people would want from forced caching

**Comment by asleire** [comment]
Of course, the very easy fix is to simply make sure we subtract the size of the old value before replacing it and adding the size of the new value, as done in #5361. 

I tested with 10 concurrent requests, and while I'd still prefer multiple HTTP requests not be made, at least this fixes a bad bug 🙂 

<details>
<summary>Click me!</summary>

```
0 unsafeInsert 6145 0
0 unsafeInsert 6145 0
0 unsafeInsert 10902 0
0 unsafeInsert 10902 0
1 unsafeInsert 6145 0
1 unsafeInsert 6145 0
1 unsafeInsert 6145 0
1 unsafeInsert 10902 0
1 unsafeInsert 10902 0
1 unsafeInsert 10900 0
2 unsafeInsert 10900 0
2 unsafeInsert 6145 0
2 unsafeInsert 6145 0
2 unsafeInsert 6145 0
2 unsafeInsert 6145 0
2 unsafeInsert 6145 0
2 unsafeInsert 10902 0
2 unsafeInsert 10902 0
2 unsafeInsert 10902 0
2 unsafeInsert 10902 0
2 unsafeInsert 10902 0
2 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
3 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10900 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
4 unsafeInsert 10902 0
5 unsafeInsert 10901 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
5 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
6 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10901 0
7 unsafeInsert 10902 0
7 unsafeInsert 10901 0
7 unsafeInsert 10901 0
7 unsafeInsert 10901 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
7 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
8 unsafeInsert 10902 0
9 unsafeInsert 10901 0
9 unsafeInsert 10901 0
9 unsafeInsert 10901 0
9 unsafeInsert 10901 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10902 0
9 unsafeInsert 10901 0
9 unsafeInsert 10902 0
9 unsafeInsert 10901 0
9 unsafeInsert 10902 0
9 unsafeInsert 10901 0
9 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10901 0
10 unsafeInsert 10901 0
10 unsafeInsert 10901 0
10 unsafeInsert 10901 0
10 unsafeInsert 10901 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
10 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10901 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
11 unsafeInsert 10902 0
```
</details>

**Comment by anderseknert** [comment]
@asleire thanks for an excellent bug report! We'll look into it 👍

**Comment by ashutosh-narkar** [comment]
Let's try to fix this by investigating if we can lock the _cache check_ - _execute HTTP req_ - _insert in cache_ actions. I can look this.

**Comment by runes83** [comment]
When will there be a new releaes containing this fix?

**Comment by srenatus** [comment]
Tomorrow. 🤞
