### ISSUE TITLE
Consider Istio integration

### ISSUE THREAD

**Issue by AceHack** [open-policy-agent/opa#536]
https://istio.io/
Consider having this run as part of istio

**Comment by timothyhinrichs** [comment]
The Istio adapter for OPA merged just this week:

https://github.com/istio/istio/pull/2229

**Comment by AceHack** [comment]
That's like the fastest turn around for a request ever :)  Great news!!

**Comment by timothyhinrichs** [comment]
That was the easiest feature request we've ever had!
