### ISSUE TITLE
Hide successful tests trace from `-f json --explain fails`

### ISSUE THREAD

**Issue by FarisR99** [open-policy-agent/opa#5366]
## What is the underlying problem you're trying to solve?
Currently, the `json` output format for running `opa test` with `--explain fails` prints traces for all tests regardless of whether each test was successful.

This can lead to a lot of unnecessary information in the output, as someone looking for test failures would only care about the tests that failed.

For policies with a lot of lines and test files with many test cases, this can lead to the output to be very large and take a long time to generate.

## Describe the ideal solution
Remove traces from the output of successful tests, ideally before generating the JSON output.

Note that this will affect current users who may rely on traces in successful tests too, as well as those running `--verbose -f json` relying on OPA's current behaviour of `--verbose` defaulting to `--explain fails` .

## Describe a "Good Enough" solution
An extra flag that masks traces from successful tests before generating the JSON output.

## Additional Context
My team wants to manipulate the test output for CI/CD reasons, however we only care about traces for test failures, as the flag value `--explain fails` implies.

Our project contains many tests with policies that have many lines. This means the output takes tens of minutes to generate and the output file being hundreds of megabytes.

**Comment by FarisR99** [comment]
> Makes sense to me 👍 Just curious, what do you use to parse the traces? Or do you manually scan them for errors? 

Initially we wanted to "pretty print" the trace for failed tests like `-f pretty` does, in our Python script for GitLab pipelines, but looking at OPAs source code we noticed some complications in porting it over and have decided to skip parsing traces altogether

**Comment by anderseknert** [comment]
Doh, I just realized, "fails" in this context has no connection with "test failures" but rather about where _evaluation_ "fails"... those two are different things altogether. So if we were to have something like this, it would need to be under a new flag or option, where we printed a verbose trace only on _test failures_. This is pretty much how the `-v` flag without `--format json` works already, so I'm not sure why that was made an exception 🧐 but we likely can't change that without considering that to be breaking...
