### ISSUE TITLE
 opa_windows_amd64.exe for release 0.46.1 missing

### ISSUE THREAD

**Issue by christophwille** [open-policy-agent/opa#5378]
https://github.com/open-policy-agent/opa/releases/tag/v0.46.1 doesn't have Windows binaries (compared to https://github.com/open-policy-agent/opa/releases/tag/v0.45.0)

**Comment by srenatus** [comment]
It doesn't? I can see a opa_windows_amd64.exe there...?

**Comment by christophwille** [comment]
I should have made a screenshot... anyways, yes, it is there now.

**Comment by srenatus** [comment]
Maybe a GitHub glitch... The release process should have failed if the windows build wasn't successful.
