### ISSUE TITLE
Google Analytics 4 migration followup

### ISSUE THREAD

**Issue by chalin** [open-policy-agent/opa#5384]
This is a followup to:

- #5382

Cleanup tasks:

- [x] #5684
- [x] Connect the UA ID from the GA4 data steam
- [ ] #5683
- [ ] Confirm that the GA4 site tag is receiving events
- [ ] Confirm that the UA site tag is still receiving events (CNCF doesn't yet have access to this account)

/cc @caniszczyk @nate-double-u @srenatus

**Comment by srenatus** [comment]
⚠️ Our feedback thing isn't based on docsy: https://github.com/open-policy-agent/opa/blob/main/docs/website/layouts/partials/feedback.html

**Comment by srenatus** [comment]
Also, if the GA snippet is now injected via Netlify, we should remove the hugo code for it: https://github.com/open-policy-agent/opa/blob/main/docs/website/layouts/partials/google-analytics.html and it's usage in https://github.com/open-policy-agent/opa/blob/main/docs/website/layouts/_default/baseof.html#L11

**Comment by chalin** [comment]
Thanks for the clarifications @srenatus.

**Comment by srenatus** [comment]
@chalin Thanks for pushing this forward! One thing that isn't clear to me is whether you're still working on this, or if you've recorded these follow-ups for someone else to pick up. 🤔

**Comment by chalin** [comment]
@srenatus - I'm currently prioritizing the migration of other projects so that their GA4 site tags can start receiving data. I don't know if I'll be working on follow up tasks or not -- if I do, it probably wont be before 23Q3. So feel free to work on this PR when you feel the time is right :).

**Comment by chalin** [comment]
Hi. This is still relevant. Also see, https://github.com/open-policy-agent/opa/issues/5382#issuecomment-1437484416.
