### ISSUE TITLE
Add key file path entries to server config file schema

### ISSUE THREAD

**Issue by jimmyraywv** [open-policy-agent/opa#5391]
## What is the underlying problem you're trying to solve?

When configuring the OPA server with a config file, trying to get the keys properly configured for bundle signature verification is difficult. It requires copy and pasting key file contents. It would be much easier if key files could be pathed in the config file and read when the server starts. 

## Describe the ideal solution

Add `key_file` and `private_key_file` entries in the `keys` section of the config yaml. Then load these files and parse them.

## Describe a "Good Enough" solution

Duplicate the `--verification-key` and `--verification-key-id` flags for server, where the ID would match that of a `bundles[_].signing.keyid` entry

**Comment by ashutosh-narkar** [comment]
Related https://github.com/open-policy-agent/opa/issues/5146

**Comment by jimmyraywv** [comment]
I was able to get around it with --set-file for now. I think it would be a could config file entry. Thanks @ashutosh-narkar and @anderseknert. I guess we can close this one.

**Comment by anderseknert** [comment]
Thanks Jimmy!
