### ISSUE TITLE
base64 vs base64url encoding

### ISSUE THREAD

**Issue by phi1010** [open-policy-agent/opa#5406]
Hello, one suggestion: RFC7515 specifies an encoding named "base64url encoding" to be used with symmetric keys ("k")-type ( https://www.rfc-editor.org/rfc/rfc7515.html#appendix-C ); it might be useful to change the documentation hint from #2885 to refer to "base64url encoded (without padding)" instead of "base64 encoded (without padding)", since the current reference to base64 could be misleading.

**Comment by phi1010** [comment]
(relates to #2870)

**Comment by anderseknert** [comment]
The only built-in function that offers to "no padding" alternative is [base64url.encode_no_pad](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-encoding-base64urlencode_no_pad), so whoever goes looking for a built-in to do this is likely going to find the right one. But updating the docs is a good idea either way, so let's do that. Do you want to submit a PR, or should I fix it?
