### ISSUE TITLE
Configurable default query path

### ISSUE THREAD

**Issue by alvarogomez93** [open-policy-agent/opa#5409]
## What is the underlying problem you're trying to solve?
When executing a query using the default path https://www.openpolicyagent.org/docs/latest/rest-api/#get-a-document-webhook, the /v0/data API is used automatically. It would be nice if this could be changed to use /v1/data instead, which does support the addition of decision logs and the input document.

## Describe the ideal/Good Enough solution
Adding a parameter in the OPA config that allows choosing the default behavior of the empty path, e.g. http://localhost:8181/

**Comment by anderseknert** [comment]
Hi @alvarogomez93 👋 I don't mind having that option, but I'd be curious to learn more about when this is needed.

> does support the addition of decision logs and the input document.

The `v0` API supports decision logging just as the `v1` API. Do you mean that you need to have the `decision_id` included in the output from the evaluation? Both support an input document, with the only difference being that the `v1` API requires you to wrap it in an extra `"input"` attribute.

The reason the `v0` API exists is really for OPA to work in situations where the input and output format is decided by the integrating client, as is the case with e.g. Kubernetes admission control. If you control the client input/output format, like you do running the `v1` API, then I think the assumption is that you're also able to direct it to the endpoint you need for that, e.g. `/v1/data/my_policy/allow`.

**Comment by anderseknert** [comment]
Thanks, @nevumx! Although I'm not sure I follow. How is `/` simpler than something like `/v1/data/main`? I assume the clients calling OPA aren't humans, but other services, right? 🙂 Or is this purely a aesthetic thing? IMHO, the longer path is "simpler" in that it actually makes it clear what API is being requested by just looking at the path. Allowing `/` to route to the v1 API would mean you wouldn't know what to expect without looking at the OPA _config_ of the running instance.

**Comment by anderseknert** [comment]
Cleaning up for now 🧹 @alvarogomez93 @nevumx , let me know if you want to revisit this in the future 👍
