### ISSUE TITLE
Ability to convert ns since epoch to timestamp with format

### ISSUE THREAD

**Issue by cmorinupgrade** [open-policy-agent/opa#5414]
## What is the underlying problem you're trying to solve?
I have an input payload that is represented using the UTC format: `2022-11-23T18:19:16Z`

I am writing a test that needs to subtract 61 minutes from now to go above the 60 minutes threshold defined in my Rego rule.

`mergedAt := time.now_ns() - 61*60*1000*1000*1000 # 61 minutes in ns`

Then, I want to use that value for the `mergedAt` field in my test payload to simulate 61 minutes past eval time, since my rule is using `now` as a time reference point. 
However, that gives me nanoseconds since epoch, as described in the policy reference. However, I’d like to convert that back to UTC. I have documented a workaround down below, but having a built-in available for that use case would be cleaner.

## Describe the ideal solution
Have the ability to convert time in `ns` to `timestamp` with a specific format.

## Describe a "Good Enough" solution
Have the ability to convert time in `ns` to `timestamp` in UTC format (not customizable).

## Workaround

Here is how I was able to do it using `time.date` and `time.clock` builtins.

```
mergedAt := time.now_ns() - 61*60*1000*1000*1000 # 61 minutes in ns
    date := time.date(mergedAt)
    clock := time.clock(mergedAt)
    outdatedMergedAt := sprintf("%v-%v-%vT%v:%v:%vZ", [
        date[0],
        date[1],
        date[2],
        clock[0],
        clock[1],
        clock[2],
    ])
```

which yields the following result:
`2022-11-23T18:20:14Z`

#### Rule under test

```
default pr_merged_and_outdated := false
pr_merged_and_outdated {
    # PR is merged
    input.payload.merged

    # PR mergedAt metadata is not null
    input.payload.mergedAt

    # Calculating PR age
    now := time.now_ns()
    layout := "2006-01-02T15:04:05Z"
    merged_at_in_epoch := time.parse_ns(layout, input.payload.mergedAt)
    pr_age := now - merged_at_in_epoch

    # Violate rule if PR is merged and older than 1 hour
    violation_report_limit := time.parse_duration_ns("1h")
    pr_age > violation_report_limit
}
```

#### Test case

```
test_pr_merged_and_outdated {
    mergedAt := time.now_ns() - 61*60*1000*1000*1000 # 61 minutes in ns
    <need some way to convert mergeAt to timestamp in UTC format>
    payload := {
        "payload": {
            "merged": true,
            "mergedAt": mergedAt <---- this is ns, need timestamp here
        }
    }
}
```

**Comment by anderseknert** [comment]
Sounds like a good addition. Unrelated to that, but for the 61 minutes duration in your example, you could use:
```rego
mergedAt := time.now_ns() - time.parse_duration_ns("61m")
```
Which arguably is easier to read :)

**Comment by burnerlee** [comment]
@cmorinupgrade @anderseknert could I pick this issue up? I've used this project to build a multi factor authorization library, and am now looking forward to contribute to the project
