### ISSUE TITLE
rego_type_error on rego.metadata.* calls if schema present in annotation

### ISSUE THREAD

**Issue by yuriykobelev** [open-policy-agent/opa#5430]
## Short description 
opa test command has no schema flag. It makes the compilation broken if a policy file contains schema annotation.
OPA version: 0.46.1

Files structure:
`policies/policy.rego`

context of policy.rego file:
```
# METADATA
# scope: package
# schemas:
#   - input: schema["data-schema"]
package main

allow {
    rego.metadata.rule()
}
```

Command:
`opa test ./policies/ ./policies`

## Expected behavior
The `test` command should support the schema flag or at least (less desirable) ignore annotations that specify the schema to perform tests.

**Comment by srenatus** [comment]
For completeness' sake, this is the error you get from `opa test` now:
```
1 error occurred: policy.rego:7: rego_type_error: undefined schema: schema["data-schema"]
```

**Comment by anderseknert** [comment]
For even more completeness 😅 The bug affects not just `opa test` but any command calling `rego.metadata.*` when a schema is provided in the annotations, but not loaded from disk (which some commands have no option to do). I'd suggest we fix the bug for the scope of this issue, and then we can create a feature request issue for having a schema flag added to `opa test`, if that's desired.

**Comment by tsandall** [comment]
Agreed with @anderseknert that the appropriate fix here is to have the `rego.metadata.*` NOT fail when schema is not provided (since in many cases, it may not be.)
