### ISSUE TITLE
Users should be able to include metadata when loading policies into OPA

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#547]
There are a number of features that will require callers to supply metadata along with policies.

The current Policy API allows callers to supply raw policy files as input. For example:

```
PUT /v1/policies/xyz HTTP/1.1

package foo

p = 1
```

Similarly the bundle format does not include any metadata other than a revision identifier.

In some cases it may be useful to attach metadata about the policy like expiration time, dry run mode, etc. To support use cases like this we would need to expand the API to support metadata. This would apply to both the Policy API and bundles.

It's still unclear whether this information belongs in the policy or not.

**Comment by repenno** [comment]
This is useful but JSON does not allow comments or metadata. Other services like GRPC allow you to pass anything you define. I believe this goes back to the other open issue related to implementing a GRPC server

**Comment by repenno** [comment]
See

#841

**Comment by tsandall** [comment]
At the 2018/10/16 OPA meeting, @repenno shared a use case from Cisco that involves compiling abstract policy definitions into Rego and other policy systems (like traditional firewalls). In that use case, the abstract policy definition contains metadata that includes information on the policy like tenancy, arbitrary key-value pairs, author, timestamps on so on. Some of this information is used as context while other bits are purely metadata, i.e., they do not affect policy evaluation. Currently they maintain this metadata in a database and the policy management system is responsible for aggregating data/policy from OPA as well as the database in order to present a unified view to clients of the management system. This means that today the compilation process from abstract policy definition to Rego is lossy--some of the metadata is not present in the resulting Rego. @repenno expressed interest in resolving this by adding support for metadata in OPA.

Thoughts...

1. Policy decisions are a function of JSON in the policy query (`input`) and JSON cached in-memory in OPA (`data`). In some cases, policies may execute RPC calls to obtain additional data but that's not important here. Given that you can provide arbitrary JSON data as input, cache arbitrary JSON data in OPA's storage, and encode arbitrary JSON data into policies, I don't think we should introduce another source of information for policies to use to make decisions. This would mean that any kind of metadata support we eventually add to OPA is effectively inaccessible inside the policy. This already exists to some extent, e.g., the policy name/identifier is only for management purposes.

2. Given that OPA has rich support for storing and encoding arbitrary JSON data (which may or may not be used during policy evaluation), I don't see a strong reason to add additional support for metadata at this point. If we eventually have enough demand for features like shadowing, expiration, etc. we could revisit this.

**Comment by tsandall** [comment]
We're not planning to work on this in the short/medium term so I'm going to close this.
