### ISSUE TITLE
feat: Support collecting of all errors from function calls during evaluation

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5484]
## What is the underlying problem you're trying to solve?

I would like to make errors from functions visible in the [Rego playground](https://play.openpolicyagent.org).

## Describe the ideal solution
Ideally, it'd be possible to see all errors from functions executed in the processing of the query. For example, with this policy there are two errors hit for the query `data.play`:

```rego
package play

this_errors(number) := result {
	result := number / 0
}

this_errors_too(number) := result {
	result := number / 0
}

res1 := this_errors(1)

res2 := this_errors_too(1)
```

Evaluating this policy & query with `--strict-builtin-errors` only returns the first error:

```bash
$ opa eval --strict-builtin-errors -d policy.rego data.play
{
  "errors": [
    {
      "message": "div: divide by zero",
      "code": "eval_builtin_error",
      "location": {
        "file": "policy.rego",
        "row": 4,
        "col": 12
      }
    }
  ]
}
```

Running eval without strict errors `opa eval -d policy.rego data.play` would roll over two errors that we might want to know about if debugging a policy.

It would be nice to have a mechanism in OPA to show all errors from functions in addition to being able to set `--strict-builtin-errors` to halt once hitting the first one.

This would likely be best implemented as a `func(r *Rego)` like the other options, e.g.:

```golang
pq := rego.New(...).PrepareForEval(...)
rs, err := pq.Eval(input, rego.BuiltinErrorBuffer(buf))
if err != nil {
  // handle errors
}
// handle result (rs)
// do something with buf
```

(☝️ Credit to Torin 🙂)

**Comment by srenatus** [comment]
🚀 Having stuff turn undefined has been a constant head-scratcher for newcomers; and giving them something in hand right away would help a lot, I think.

**Comment by charlieegan3** [comment]
@srenatus, to clarify, are you suggesting that we also address the calling of functions with undefined with this work? For example, these raise no errors currently:

```rego
package play

func(inp) := true

allow := func(input.undefined)
```

```rego
package play

allow := object.get(input.undefined, "foo", "bar")
```

**Comment by srenatus** [comment]
No that's against how rego works, I'd say. We cannot get rid of all paper cuts, some things just need getting adjusted to.

**Comment by charlieegan3** [comment]
👍 Ok, I just wanted to check as that seemed like a different thing.

**Comment by charlieegan3** [comment]
https://github.com/open-policy-agent/opa/pull/5487 gives me enough functionality to update the playground so I'm going to mark this as done. If we'd like to expose this functionality in some other way, we can open a new issue.
