### ISSUE TITLE
OPA inspect gives different outputs on macOS and Windows

### ISSUE THREAD

**Issue by HarshPathakhp** [open-policy-agent/opa#5503]
## Short description 
Running OPA inspect command on a bundle directory gives different outputs across windows and macOS, with improper behaviour shown by Windows opa binary.
Problem - 
* On windows, the inspect command shows data files under namespace `data`, even for data files inside subfolders. Ideally, the namespace for such data files should have been `data.<subfolder_path>`, where <subfolder_path> is path of the subfolder relative to bundle root, and path separators are substituted by `.`
* Also, on windows, the inspect command doesn't work when the bundle directory path is stated as an absolute path. It raises manifest errors. 

Both these problems are described more in detail through an example below. 

Environment Details
* OPA version - 0.47.4
* Running on macOS and Windows

## Steps To Reproduce
1. Please download the sample bundle directory attached. ([opa_inspect.zip](https://github.com/open-policy-agent/opa/files/10283244/opa_inspect.zip))
2. On macOS and windows, run the following command - 
           1. `opa inspect opa_inspect/ -f json` -  this is without absolute paths
           2. `opa inspect <absolute path of bundle directory> -f json` -  this is with absolute paths
           3. Notice the outputs

### macOS
On macOS, the outputs were consistent. Data files present in `play` and `play2` subdirectories showed up in `data.play` and `data.play2` respectively. This seems like an expected behaviour.

Without absolute paths - 
```json
{
  "manifest": {
    "revision": "",
    "roots": [
      "a/b/c",
      "a/b/d",
      "play",
      "play2"
    ]
  },
  "signatures_config": {},
  "namespaces": {
    "data.a.b.c": [
      "opa_inspect/authz.rego",
      "opa_inspect/authz3.rego"
    ],
    "data.a.b.d": [
      "opa_inspect/authz2.rego"
    ],
    "data.play": [
      "opa_inspect/authz4.rego",
      "opa_inspect/play/data.json"
    ],
    "data.play2": [
      "opa_inspect/play2/data.json"
    ]
  }
}
```

With absolute paths

```json
{
  "manifest": {
    "revision": "",
    "roots": [
      "a/b/c",
      "a/b/d",
      "play",
      "play2"
    ]
  },
  "signatures_config": {},
  "namespaces": {
    "data.a.b.c": [
      "/Users/user1/opa_inspect/authz.rego",
      "/Users/user1/opa_inspect/authz3.rego"
    ],
    "data.a.b.d": [
      "/Users/user1/opa_inspect/authz2.rego"
    ],
    "data.play": [
      "/Users/user1/opa_inspect/authz4.rego",
      "/Users/user1/opa_inspect/play/data.json"
    ],
    "data.play2": [
      "/Users/user1/opa_inspect/play2/data.json"
    ]
  }
}
```

### Windows
On Windows, the output is inconsistent with that on macOS. Also, for absolute paths, the CLI doesn't work.

Without absolute paths

Notice how data files for even subfolders are inside the `data` namespace.
```json
{
  "manifest": {
    "revision": "",
    "roots": [
      "a/b/c",
      "a/b/d",
      "play",
      "play2"
    ]
  },
  "signatures_config": {},
  "namespaces": {
    "data": [
      "sample_inspect_bundle/play/data.json",
      "sample_inspect_bundle/play2/data.json"
    ],
    "data.a.b.c": [
      "sample_inspect_bundle\\authz.rego",
      "sample_inspect_bundle\\authz3.rego"
    ],
    "data.a.b.d": [
      "sample_inspect_bundle\\authz2.rego"
    ],
    "data.play": [
      "sample_inspect_bundle\\authz4.rego"
    ]
  }
}
```
With absolute paths
opa inspect Z:\sample_inspect_bundle -f json

```text
error: bundle Z:\sample_inspect_bundle: manifest roots [a/b/c a/b/d play play2] do not permit data at path '/Z:' (hint: check bundle directory structure)
```

**Comment by anderseknert** [comment]
Thanks for reporting this @HarshPathakhp! It does indeed look like a bug, and probably not too hard to fix provided access to a Windows machine. I could be wrong about that, but I'll add a good first issue label to this issue, hoping someone is willing to give it a shot.

**Comment by shm12** [comment]
It probably has something to do with the path separator on windows again

**Comment by harikannan512** [comment]
Hi @anderseknert @shm12,

Can I have a go at this issue? I am just starting out with contributing to open source and as far as this issue goes, I have access to both windows and mac os machines. If that's alright, please assign this issue to me. Thanks

**Comment by harikannan512** [comment]
Appreciate it, thanks a lot, I'll start working on this. Just to confirm, you mean drive letter that gets added as an extra prefix right to the input `path` right?

**Comment by shm12** [comment]
> With absolute paths opa inspect Z:\sample_inspect_bundle -f json
> 
> ```
> error: bundle Z:\sample_inspect_bundle: manifest roots [a/b/c a/b/d play play2] do not permit data at path '/Z:' (hint: check bundle directory structure)
> ```
This is what I mean. It's a different problem than the one of the incorrect namespaces

**Comment by harikannan512** [comment]
HI @shm12 
Thanks for your help. Looks like this fixes the issue. The tests all ran fine so I think this won't impact the general functioning of `inspect`. Quick question, do I add the namespace changes to this pr or shall I leave it be to be reviewed as is.

**Comment by shm12** [comment]
I think it's better to leave it as two separated PRs.

**Comment by shm12** [comment]
@anderseknert @srenatus, can either of you take a look at the PRs?

**Comment by srenatus** [comment]
I'm looking into it. We've had a holiday break over here. 💤

**Comment by harikannan512** [comment]
Apologies, I have closed the old PR and opened a new one as I created a commit in the old PR without signing off

**Comment by shm12** [comment]
Just so you know, to keep the original PR, you could revert the commit, recommit it, this time signed, and then force push it.

**Comment by anderseknert** [comment]
You don't even need to do that :) Just:
```
git commit --amend --signoff
git push --force
```
