### ISSUE TITLE
[rego] Store modules are not parsed unless supplementary modules are also supplied

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5511]
This issue is based on a community member's question [here](https://github.com/orgs/open-policy-agent/discussions/318).

The issue can be replicated with the following code:

```go
package main

import (
	"context"
	"testing"

	"github.com/open-policy-agent/opa/rego"
	"github.com/open-policy-agent/opa/storage"
	"github.com/open-policy-agent/opa/storage/inmem"
	"github.com/stretchr/testify/assert"
)

func Test_A(t *testing.T) {
	var err error
	ctx := context.Background()
	store := inmem.New()
	txn, err := store.NewTransaction(ctx, storage.WriteParams)
	assert.NoError(t, err)
	err = store.UpsertPolicy(ctx, txn, "a.rego", []byte("package a\ndefault allow := true"))
	assert.NoError(t, err)
	err = store.Commit(ctx, txn)
	assert.NoError(t, err)
	query := rego.New(
		rego.Store(store),
		rego.Module("b.rego", "package test"),
		rego.Query("data.a.allow"),
	)
	results, err := query.Eval(ctx)
	assert.NoError(t, err)
	assert.NotNil(t, results)
	assert.True(t, results.Allowed())
}

func Test_B(t *testing.T) {
	var err error
	ctx := context.Background()
	store := inmem.New()
	txn, err := store.NewTransaction(ctx, storage.WriteParams)
	assert.NoError(t, err)
	err = store.UpsertPolicy(ctx, txn, "a.rego", []byte("package a\ndefault allow := true"))
	assert.NoError(t, err)
	err = store.Commit(ctx, txn)
	assert.NoError(t, err)
	query := rego.New(
		rego.Store(store),
		//rego.Module("b.rego", "package test"),
		rego.Query("data.a.allow"),
	)
	results, err := query.Eval(ctx)
	assert.NoError(t, err)
	assert.NotNil(t, results)
	assert.True(t, results.Allowed())
}
```

Running `go test .` we can see that the second test fails:

```
$ go test .
--- FAIL: Test_B (0.00s)
    main_test.go:51: 
                Error Trace:    .../main_test.go:51
                Error:          Expected value not to be nil.
                Test:           Test_B
    main_test.go:52: 
                Error Trace:    .../main_test.go:52
                Error:          Should be true
                Test:           Test_B
FAIL
```

It appears to me that the apparent need to include `rego.Module` option here is confusing. In the `parseModules` function [here](https://github.com/open-policy-agent/opa/blob/9bd1bfb4e1440009be1e8d1a126d35d091d7f043/rego/rego.go#L1683-L1685) we can see that the parsing of modules in the store only occurs when the Rego object has modules set.

I'm not sure if this use case is unsupported or if this is a bug.

(OPA version: HEAD/0.47.4)

**Comment by srenatus** [comment]
Thanks for digging into this. It indeed looks like a bug to me, too. The right thing to do -- I think? -- would be to remove that early exit you've linked to. What do you think?

**Comment by charlieegan3** [comment]
OK, cool. It seemed like a bug to me too. I think removing that early exit is the correct thing to do. I was thinking that we could keep it if we extended the check to include `r.store.ListPolicies` > 0 too.

It makes sense to keep the behaviour that the function isn't timed with a metric unless parsing happens. I think I can get a PR for this done quite quickly so we can see what that looks like.

**Comment by charlieegan3** [comment]
See https://github.com/open-policy-agent/opa/pull/5520
