### ISSUE TITLE
`opa fmt` produces invalid code for parentheses and wildcard assignment

### ISSUE THREAD

**Issue by m273d15** [open-policy-agent/opa#5537]
Thanks for developing this great tool!

When I call `opa fmt` on my rego code it produces invalid code while the code
before the formatting is valid.

## Short description 

When I use an assignment as `msg := (first | second)[_]` to get all elements of the unified set of `first` and `second`, then opa produces the expected result.
If I run `opa fmt`, the result is `msg := first | second[_]`, which is invalid code and leads to an error message when executing opa.

Found with OPA version: `0.47.4` and the rego playground.

Example code ([rego playground](https://play.openpolicyagent.org/p/FyiGEfpY5o))
```rego
package play

first := {"one", "two"}
second := {"two", "three"}

example[msg] {
  msg := (first | second)[_]
}
```

Result after `opa fmt`
```rego
package play

first := {"one", "two"}

second := {"two", "three"}

example[msg] {
	msg := first | second[_]
}
```

## Steps To Reproduce
1. Via playground
  - Open https://play.openpolicyagent.org/p/FyiGEfpY5o
  - Click on "Evaluate"
  - You get valid output
  - Click on "Format"
  - Click on "Evaluate"
  - You see the error message
  ```
  1 error occurred: policy.rego:8: rego_type_error: or: invalid argument(s)
	have: (set[string], string, ???)
	want: (x: set[any], y: set[any], z: set[any])
  ```
2. Via CLI
  - Copy example code (see above)
  - Run OPA with empty input `{}` and evaluate `example` rule
  - You get valid output
  - Run `opa fmt` on the example code
  - Run OPA again
  - You see the error message
  ```
  1 error occurred: policy.rego:8: rego_type_error: or: invalid argument(s)
	have: (set[string], string, ???)
	want: (x: set[any], y: set[any], z: set[any])
  ```
  

## Expected behavior

The formatter should create semantically equivalent code.

**Comment by anderseknert** [comment]
Hi Kelvin! And thanks for reporting that. That is indeed a curious bug. An obvious workaround in the meantime would be to assign the result to a third var, and iterate over that, i.e:

```rego
example[msg] {
	third := first | second
	msg := third[_]
}
```
You could also use the `some ... in` looping construct, which seems to have the formatter actually _add_ parentheses 😅 Which is curious too, although not a bug per se.

```rego
package play

import future.keywords.in

first := {"one", "two"}
second := {"two", "three"}

example[msg] {
    some msg in first | second
    # fmt: some msg in (first | second)     
}
```

**Comment by m273d15** [comment]
Hi Anders, thanks for quick reply 🚀 and the workarounds/pointers to alternatives 🙏

**Comment by nevumx** [comment]
Hi folks, @anderseknert and I also found a similar behavior, but are unsure if it is part of the same bug: looking at [this playground](https://play.openpolicyagent.org/p/hkzIaSFAm9) it runs evaluates fine as-is, but after clicking the "Format" button, the parentheses disappear which [results in a type error](https://play.openpolicyagent.org/p/RImAVKcXvz). If it is part of the same bug, that works, and if it's part of a separate one, I can create a separate bug, depending any developers' thoughts.

**Comment by anderseknert** [comment]
Thanks @nevumx 👍 

@Trolloldem did some wonders fixing bugs in `opa fmt` recently.. I wonder if I'm able to summon his presence here 🧙

**Comment by anderseknert** [comment]
That'd be amazing! Thank you @Trolloldem 🙏

**Comment by Trolloldem** [comment]
> Thanks @nevumx +1
> 
> @Trolloldem did some wonders fixing bugs in `opa fmt` recently.. I wonder if I'm able to summon his presence here mage

I have investigated the issue and I found out what may be causing the problem.
Currently, a function is formatted by the functions [writeFunctionCall](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L626) and [writeCall](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L774). This last function is called in [writeTermParens](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L690). The `parens` parameters checks if parentheses must be added in the output format and is set to `false` when this function is called through [writeTerm](https://github.com/open-policy-agent/opa/blob/main/format/format.go#L686). 

The two problems notified by @m273d15 are linked to this procedure: 

- `msg := (first | second)[_]` is using the `Assign` function in `writeFunctionCall`. Its terms are `msg` and `(first | second)[_]` and both are processed by `writeTerm`, which sets `parens` to false, eliminating them from the output  when the second term is processed in `writeCall`
- `array := [(input.thing[i] == input.other[i]) | true]` performs and array comprehension, which processes  `(input.thing[i] == input.other[i])` through the function `writeTerm`

The first case may cause more problematic cases, for instance, using `opa fmt` on the following code:

```go
package play

example[ms] {
	a & (b | c)
}
```

Produces: 

```go
package play

example[ms] {
	a & b | c
}
```

which is valid code but do not equal what the user wanted to do in the first place. 

One possible solution to this is to be more conservative in eliminating parentheses and add a check inside of `writeCall` which checks the first character of the processed call is a `'('` and sets to true `parens` if needed. This may leave some unneded parentheses (e.g. `(1+(2+3))`) but should avoid these corner cases.
