### ISSUE TITLE
OCI Downloader has limited support for authentication methods

### ISSUE THREAD

**Issue by DerGut** [open-policy-agent/opa#5553]
## What is the underlying problem you're trying to solve?
The [OCI Downloader](https://www.openpolicyagent.org/docs/latest/configuration/#using-private-image-from-oci-repositories) currently only supports three types of authentication: 1) client TLS certificates, 2) basic authentication and 3) bearer tokens. Any other method specified in the `services.<servicename>.credentials` block simply gets ignored.
All the supported methods require the user to put static credentials into the config. In some setups this is not possible and temporary credentials need to be generated on demand to authenticate with a registry.

## Describe the ideal solution
Ideally, the OCI downloader should support any authentication method that can be understood by registry providers.

## Describe a "Good Enough" solution
I propose three "Good Enough" solutions:

### 1) Docker credential helpers
Docker uses a plugin mechanism called [docker credential helper](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) to be able to authenticate with any private third-party registry. Most cloud providers make use of this mechanism and provide their own implementation like the [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper). The docker CLI calls these binaries (if configured in the docker config) and retrieves credentials from them before sending requests to a  registry.

In the context of open policy agent, we could add a similar configuration, e.g. a path to a credential helper binary. If provided, the OCI downloader plugin would call the binary and ask for credentials before sending requests to a registry.

### 2) Cloud provider IMDS
The docker-credential helper implementation of cloud providers is often a wrapper around their Instance Metadata Service APIs. Open policy agent already maintains a set of IMDS API implementations to authenticate with cloud providers ([AWS](https://www.openpolicyagent.org/docs/latest/configuration/#using-ec2-metadata-credentials), [GCP](https://www.openpolicyagent.org/docs/latest/configuration/#gcp-metadata-token)) as part of the rest plugin. We could probably reuse that functionality and make it work for OCI registries too. Ideally, this should only be a matter of adding support for them in this function: https://github.com/open-policy-agent/opa/blob/f510d802cc2e74d06f0540cd0533b80a1107c75b/download/oci_dowload.go#L358-L384

The AWS metadata service configuration key is currently hidden under `services[_].credentials.s3_signing.metadata_credentials`. Probably because it was added as part of the S3 downloader feature. If we reused it for OCI registries, we can hopefully find a way to rename it while remaining backwards compatible.

### 3) Custom credential plugin
The rest plugin supports extensibility via [custom credential plugins](https://www.openpolicyagent.org/docs/latest/configuration/#custom-plugin). OCI registry auth doesn't support this method either. Exposing a way to implement custom authentication is a very powerful tool to make the OCI downloader work in unsupported  situations (such as this one).
It is closest to the _ideal solution_ and, in my opinion, it should be added regardless of the outcome of 1) and 2).

**Comment by srenatus** [comment]
Thanks for the detailed issue!

**Comment by carabasdaniel** [comment]
I can take a look at this if that would be ok

**Comment by anderseknert** [comment]
That'd be terrific, @carabasdaniel 😃

**Comment by anderseknert** [comment]
@carabasdaniel there seems to be a PR in progress from @DerGut. Perhaps you could help review? And see if there's anything more to it that we need to consider. Obviously all of it would not need to be included in that PR, so could very well be that it should be followed by other PRs.

**Comment by DerGut** [comment]
Hi @carabasdaniel I am trying to make use of the existing `Config.AuthPlugin()` in https://github.com/open-policy-agent/opa/pull/5560
In theory, this should allow us to reuse the already implemented `rest.HTTPAuthPlugin`s for the `OCIDownloader`. However, I'm still in the process of testing it out and evaluating whether it produces any user-facing changes while switching to clients produced by the plugins.

**Comment by DerGut** [comment]
I'm still actively working on this in https://github.com/open-policy-agent/opa/pull/5560

**Comment by anderseknert** [comment]
Yeah, don't mind the bot @DerGut :)

**Comment by anderseknert** [comment]
Awesome contribution, @DerGut 👏 Thank you!
