### ISSUE TITLE
Terraform Policy against a plan with a module

### ISSUE THREAD

**Issue by cyrus-mc** [open-policy-agent/opa#556]
I am trying to write a policy against a terraform plan that includes modules.

`{
  "repl": {
    "input": {
      "aws_iam_user.test": {
        "arn": "",
        "destroy": false,
        "destroy_tainted": false,
        "force_destroy": "false",
        "id": "",
        "name": "Testing",
        "path": "/",
        "unique_id": ""
      },
      "destroy": false,
      "vpc": {
        "aws_default_security_group.default": {
          "destroy": false,
          "destroy_tainted": false,
          "egress.#": "1",
          "egress.482069346.cidr_blocks.#": "1",
          "egress.482069346.cidr_blocks.0": "0.0.0.0/0",
          "egress.482069346.description": "",
          "egress.482069346.from_port": "0",
          "egress.482069346.ipv6_cidr_blocks.#": "0",
          "egress.482069346.prefix_list_ids.#": "0",
          "egress.482069346.protocol": "-1",
          "egress.482069346.security_groups.#": "0",
          "egress.482069346.self": "false",
          "egress.482069346.to_port": "0",
          "id": "",
          "ingress.#": "1",
          "ingress.753360330.cidr_blocks.#": "0",
          "ingress.753360330.description": "",
          "ingress.753360330.from_port": "0",
          "ingress.753360330.ipv6_cidr_blocks.#": "0",
          "ingress.753360330.protocol": "-1",
          "ingress.753360330.security_groups.#": "0",
          "ingress.753360330.self": "true",
          "ingress.753360330.to_port": "0",
          "name": "",
          "owner_id": "",
          "revoke_rules_on_delete": "false",
          "tags.%": "2",
          "tags.Name": "unit-tests",
          "tags.built-with": "terraform",
          "vpc_id": "${aws_vpc.environment.id}"
        },
`

How do I access elements in the module? I have tried input.vpc.aws_default_security_group.default

But a regex parse error is throw. If I leave off .default I get undefined.

**Comment by timothyhinrichs** [comment]
You can use x.y and x["y"] interchangeably as long as y doesn't include periods, spaces, hyphens, etc.  If y includes any of those special characters, you'll want to use the x["y"] format.  

So in this case you want `input.vpc["aws_default_security_group.default"]`.
