### ISSUE TITLE
AWS S3 config info is missed from documentation

### ISSUE THREAD

**Issue by vishrana** [open-policy-agent/opa#5562]
## Short description 

In the official do under [Amazon S3 Authentication section](https://www.openpolicyagent.org/docs/latest/management-bundles/#authentication) the information related to **web_identity_credentials** is missed. The [information present here](https://github.com/RichiCoder1/opa/blob/276166593ac8b7cb80c336868b17d2b67281008f/docs/content/configuration.md#using-eks-iam-roles-for-service-account-web-identity-credentials) should be present in the main doc website.

I was facing the issue by using the Metadata Credentials mentioned in the official docs. However, my issue is solved when I used web_identity_credentials.

## Steps To Reproduce

Go to [Amazon S3 Authentication section](https://www.openpolicyagent.org/docs/latest/management-bundles/#authentication) the information related to **web_identity_credentials** is missed. 
## Expected behavior

The [information present here](https://github.com/RichiCoder1/opa/blob/276166593ac8b7cb80c336868b17d2b67281008f/docs/content/configuration.md#using-eks-iam-roles-for-service-account-web-identity-credentials) should be present in the main doc website under AWS S3 Authentication section.

**Comment by ashutosh-narkar** [comment]
Addressed in https://github.com/open-policy-agent/opa/pull/5618
