### ISSUE TITLE
Add object.union_n to WebAssembly

### ISSUE THREAD

**Issue by robertgartman** [open-policy-agent/opa#5564]
We have strong use cases for the [object.union_n](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-object-objectunion_n) function from within OPA wasm module - running in the browser. However, it is not available in wasm as of OPA v0.48.0

Any compelling reasons not to include it?

**Comment by anderseknert** [comment]
Certainly no compelling reasons other than the fact that someone has to do the work for that to happen :) Some of the built-in functions have been contributed by the community, and we generally don't require them to provide a Wasm implementation, as that would pose a significant barrier for many. For some we've provided a Wasm-implementation later, but we've not gotten around to it for all of them. If you, or someone else would like to work on this, that'd be terrific.

Btw, I'd love to hear more about your use of OPA in the browser! 😃

**Comment by robertgartman** [comment]
Sounds promising, though I will unfortunately not be the contributor. Planned to stay on the 'user'-end of OPA.

> Btw, I'd love to hear more about your use of OPA in the browser! 😃

Might land in a blog soon.

**Comment by anderseknert** [comment]
Nice! Please keep me posted if/when that happens. I'll post a note on this in our contributors channel to see if anyone steps up to the challenge.

**Comment by philipaconrad** [comment]
For anyone looking to implement `object.union_n` in the browser, the quickest route is probably to call `object.union` in a loop, merging together each pair of objects until you have the final result.

The current Golang implementation tries to be a little more clever about the union'ing process, but the algorithmic changes there are *probably* unnecessary for WASM/JavaScript.

**Comment by anderseknert** [comment]
@philipaconrad without recursion and/or mutable vars, that’s tricky to do if the number of sets is arbitrary long / unknown, no?

**Comment by srenatus** [comment]
There must certainly are mutable vars in the c bits of our wasm code 🙃

**Comment by Azanul** [comment]
Hey there! This looks like a good first issue for me to start contributing to OPA.

Got here from Twitter.

**Comment by anderseknert** [comment]
That’s awesome, @Azanul 😃Let us know if you need any help getting started!
