### ISSUE TITLE
Auto Version update should be an option

### ISSUE THREAD

**Issue by perithompson** [open-policy-agent/opa#5579]
## What is the underlying problem you're trying to solve?

When using opa `server mode` in a container, the application auto updates to the latest version meaning the version of the container image and the version of the cli inside that container are out of sync immediately.  This should not be the default behaviour or at the very least a user should have the option to not download the latest version

```
opa
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-01-20T15:32:07Z"}
opa
{"current_version":"0.40.0","download_opa":"https://openpolicyagent.org/downloads/v0.48.0/opa_linux_amd64","latest_version":"0.48.0","level":"info","msg":"OPA is out of date.","release_notes":"https://github.com/open-policy-agent/opa/releases/tag/v0.48.0","time":"2023-01-20T15:32:07Z"}
```

## Describe the ideal solution

Have auto update optional when running `opa run --server` by adding `--keep-current`

## Describe a "Good Enough" solution

Have an update disabled option when running `opa run --server` by adding `--disable-auto-update`

## Additional Context

In airgapped installations, github may not be available or it may never be desirable for some organisations to automatically call out to github to download the latest binary

**Comment by perithompson** [comment]
on closer inspection it seems that there is a flag for this  [--skip-version-check ](https://github.com/open-policy-agent/opa/blob/4bc74912372fd5479cb8700074582723316d3b06/cmd/run.go#L285) although this flag does not seem to be  [documented](https://www.openpolicyagent.org/docs/latest/cli/#opa-run)?  I would expect that in a container this should be explicit

**Comment by srenatus** [comment]
It's been renamed to `--disable-telemetry`. That one should also be documented.

**Comment by ashutosh-narkar** [comment]
@perithompson  more information on  `--disable-telemetry` can be found [here](https://www.openpolicyagent.org/docs/latest/privacy/). Also to clarify OPA will not auto-update to the latest version. It will simply log a message containing information about the latest OPA version.

**Comment by anderseknert** [comment]
Like Ash said, there is not auto-update functionality in OPA, only an informative message getting printed if the running version is not the latest stable one. Closing for now.
