### ISSUE TITLE
opa istio plugin rego policy samples for grpc services

### ISSUE THREAD

**Issue by priyaadama** [open-policy-agent/opa#5605]
I am trying to integrate opa into my grpc service but looks like there is not appropriate sample how to do it

Why would this change make the OPA experience better?
Adding GRPC requests samples to rego examples would be of great help

**Comment by ashutosh-narkar** [comment]
@priyaadama are using the [OPA-Envoy plugin](https://www.openpolicyagent.org/docs/latest/envoy-introduction/) for this or OPA itself? If it's the former, there is an example [here](https://github.com/open-policy-agent/opa-envoy-plugin/tree/main/examples/grpc).

**Comment by srenatus** [comment]
The protoset can be combined to support multiple services. The matching of incoming requests to payload definitions is done based on the request path.

**Comment by priyaadama** [comment]
Thank you for the quick response.

Do we definitely need to pass protoset ? $ grpcurl -plaintext  127.0.0.1:51051 test.KitchenSink/Ping would not help? since  anyways matching of incoming requests to payload definitions is done based on the request path.

**Comment by srenatus** [comment]
> Do we definitely need to pass protoset?

Yes, opa-envoy-plugin does not use gRPC reflection like grpcurl does. It would need to know all the services _that are potentially call through envoy_, and it would quite difficult to configure that, I think.

**Comment by priyaadama** [comment]
ok, thank you @srenatus . I will be closing this
