### ISSUE TITLE
docs: net.cidr_overlap built-in function displayed even though marked as deprecated

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5607]
The `net.cidr_overlap` is deprecated in favor of `net.cidr_contains`, but for some reason, it still shows up in the docs, with broken content (as we've not provided data for generating this in the docs).

![Screenshot 2023-01-30 at 11 19 34](https://user-images.githubusercontent.com/510711/215450424-c447adb0-7df7-4379-baff-484725f3febe.png)

**Comment by anderseknert** [comment]
Oh, the a quick look at the source code show this to be deprecated in favor of `net.cidr_contains` ... so the bug here is then why this is displayed at all 🤔

**Comment by srenatus** [comment]
ℹ️ [this](https://github.com/open-policy-agent/opa/blob/main/internal/cmd/genbuiltinmetadata/main.go) is what generates the builtin_metadata.json that is consumed by [the hugo shortcut here](https://github.com/open-policy-agent/opa/blob/main/docs/website/layouts/shortcodes/builtin-table.html).

**Comment by anderseknert** [comment]
Thanks for the context @srenatus 👍 It's not directly apparent to me where we filter out the deprecated functions in that Hugo script. The other ones seem to be filtered out as they should, so I must be missing something 🤔

**Comment by srenatus** [comment]
I'm actually not sure that we should filter out deprecated functions in the first place. It would be nice if they had a shiny red or orange "deprecated" tag, though. Rationale: if I find, say, `net.cidr_overlap`, in some rego code I'm working on, and I'm unable to find *any* docs for that, I'll be lost. If I find docs saying what it does, and that it's deprecated, and, at best, what to use instead, would be nicer.

**Comment by anderseknert** [comment]
Agreed, but that's a [separate issue](https://github.com/open-policy-agent/opa/issues/5080) ;)

The question is how this filtering works today? This seems to be the only deprecated built-in getting listed.

**Comment by srenatus** [comment]
Maybe it's the only deprecated builtin that comes with a "canonical" category, i.e. "net"?
