### ISSUE TITLE
OPA interprets delta bundle with empty patch list as snapshot bundle

### ISSUE THREAD

**Issue by multigrid101** [open-policy-agent/opa#5629]
## Short description 

When OPA downloads a delta bundle and said delta bundle contains an empty array as a patch list, I would expect nothing in the current state of OPA to change. Instead, the bundle is interpreted as a snapshot bundle which leads to all data (including policies) being deleted.

The responsible code seems to be this here: https://github.com/open-policy-agent/opa/blob/main/bundle/bundle.go#L1188

I am aware that one could simply define this as "desired" behaviour but personally I find it completly unintuitive. Cost me a couple of hours of debugging to figure this out.

The reason I ran into this is because I had not yet implemented the 304 not modified answer for unchanged data. But even with that in place I am worried that due to some bug in the service providing the bundle an empty patchlist could be send and delete all existing data.

* OPA version: 0.48.0
-->

## Steps To Reproduce
* Can be reproduced by initializing opa with any snapshot bundle and then applying a delta bundle that has an empty list in the "data" array.
* Example output that OPA returned: Status API shows that last applied bundle (the one with the empty patch array) was falsely recognized to be of type "snapshot".

## Expected behavior
delta bundle with patch.json that contains `{"data":[]}` leads to no patches being applied an no change in opa internal state

**Comment by ashutosh-narkar** [comment]
@multigrid101 OPA expects a `patch.json` file that specifies a list of patch operations on the data to check if a bundle is a delta or not. As you correctly noted returning a `304` from the bundle server would be the right thing to do. We can update the docs to make this behavior more explicit.

**Comment by multigrid101** [comment]
Thanks a lot for your swift reply Ashutosh. Putting a hint in the docs that a patch.json with content `{"data":[]}` will actually cause the bundle to be interpreted as a snapshot bundle with no data indeed would make things clearer.

In the long term, I still think that those semantics are just... unclean... for lack of a better word. It just leads to unlikely but still weird edge cases like "what if there are data.json files AND a patch.json with empty data array?" Is that invalid? Would the data.json files (possibly with content) or the patch.json have priority? Is this consistent with the case of multiple bundle sources where one source delivers an empty patch.json and another source delivers a bundle with data.json files?

To me it seems that if a patch.json with empty data array was simply a no-op, it would make more docs unecessary and eliminate all of the above edge cases.

But I realize of course that there would be some effort associated to changing the code and since I have currently no experience with go I am not able to contribute this myself.

Anyway, thanks again for the quick reaction. At least we now know that the behaviour we observe is currently intended and can adjust our implementation accordingly

**Comment by ashutosh-narkar** [comment]
Thanks for adding more context here. 

The current behavior is if your bundle has a `patch.json` file, OPA will consider it a `delta` bundle. OPA will generate an error if a delta bundle contains any policy, data or wasm binary files. 

> what if there are data.json files AND a patch.json with empty data array

This would be considered a `delta` bundle and would result in a bundle load error.

> Would the data.json files (possibly with content) or the patch.json have priority? 

Same as above. This will result in an error as OPA will consider this a `delta` bundle.

> Is this consistent with the case of multiple bundle sources where one source delivers an empty patch.json and another source delivers a bundle with data.json files?

Assuming the bundle from the first source does not contain any policy, data or wasm binary files and only the patch file, this will be fine. The second source as long as it has no patch files will be considered a snapshot bundle and activate accordingly. Also these two bundle cannot share roots ie. they cannot overwrite each others data, policy etc. More on that [here](https://www.openpolicyagent.org/docs/latest/management-bundles/#multiple-sources-of-policy-and-data).

**Comment by multigrid101** [comment]
thanks for the clarification :)

**Comment by charlieegan3** [comment]
Hi @multigrid101, we've just merged some updates to the docs on this one. It's a tricky thing to configure and hope the new wording will be clearer.

Feel free to take a look over the changes here: https://github.com/open-policy-agent/opa/pull/5665

**Comment by multigrid101** [comment]
thanks for the update :)
