### ISSUE TITLE
Non-deterministic default values when assigned result of comprehension

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5645]
As reported by @anakrish in the [community discussion board](https://github.com/orgs/open-policy-agent/discussions/338), using comprehensions to assign default values allows the assignment to depend on non-constant refs, like `input`, `data` or built-ins like `http.send`. 

**Fails**
```rego
default foo := [input.message]
```

**Works**
```rego
default foo := [x | x := input.message]
```

**Comment by anakrish** [comment]
@anderseknert Is the following expected to work:

> default foo := [x | x := [1,2,3][_]]

Var is used within the comprehension, but it refers to a local variable within the comprehension.

**Comment by anderseknert** [comment]
I don't think we'll want to allow comprehensions to assign default values, no. If you can't use refs or built-in functions, you might as well use a constant value right away. If there's some use case I've neglected, do let me know :)

**Comment by anakrish** [comment]
According to the [default keyword documentation](https://www.openpolicyagent.org/docs/latest/policy-language/#default-keyword),

> The term may be any scalar, composite, or comprehension value but it may not be a variable or reference. If the value is a composite then it may not contain variables or references.

comprehensions are allowed. The doc doesn't state whether comprehensions could contain variables or references. If they could, then non-deterministic values can be created. And if they can't, then isn't much benefit to using comprehensions as you point out.

Would the fix for this issue be to disallow comprehensions in default values?

**Comment by anderseknert** [comment]
I'm not sure what the simpler option would be, but I'd go with that. Perhaps @ashutosh-narkar or @johanfylling could look into it.

**Comment by ashutosh-narkar** [comment]
From the [code](https://sourcegraph.com/github.com/open-policy-agent/opa@8df850e1ba98f1c509026ca7ee84c3f9c06ecf43/-/blob/ast/parser.go?L2114) it looks like we walk over the composite terms but we skip the comprehensions which would explain the discrepancy mentioned. Seems like we should be walking over comprehensions too ? I'm not sure why we skip them but maybe I'm missing something. @srenatus any ideas here?

**Comment by anakrish** [comment]
Another observation:

Expressions involving constants are disallowed in default rule:
   `default x = 1 + 1`
raises `illegal default rule (value cannot contain call)`.

The doc doesn't explicitly say that arithmetic expressions ought to be disallowed.

**Comment by anderseknert** [comment]
The compiler will turn that into:
```
default x := plus(1, 1)
```
i.e. just another built-in function call. You're right though, we could probably be more explicit about it in the docs.

**Comment by srenatus** [comment]
> Seems like we should be walking over comprehensions too ? I'm not sure why we skip them but maybe I'm missing something. @srenatus any ideas here?

I think our general stance there was that  **a default rules' value may never be undefined**. Calls, Vars, and Refs can be undefined, comprehensions are always `{}` or `set()` or `[]`, even if their body never succeeds. So, it's less about determinism, but about the assurance that if there's a default rule, the rule will have a value. It's impossible that the rule is undefined.

**Comment by anderseknert** [comment]
Huh, interesting! I had not considered that. I guess we can close this then?

**Comment by srenatus** [comment]
Not sure -- If the docs are confusing, let's fix them! 🤔

**Comment by anderseknert** [comment]
Added comment to clarify: https://github.com/open-policy-agent/opa/pull/5668
