### ISSUE TITLE
build: Delta bundle patch.json ignored by opa build command

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5664]
I was trying to create a delta bundle using the OPA build command, however I found that a snapshot bundle was created instead. (patch.json was now in fact data.json)

```
$ cat bundle/patch.json
{
  "data": [
    {"op": "replace", "path": "/foo/bar", "value": "updated" }
  ]
}
$ opa build bundle/
$ tar -tvf bundle.tar.gz
-rw-------  0 0      0          64 Jan  1  1970 /data.json
```

I think we should either: 

* Support the creation of a delta bundle in `opa build`, perhaps with the addition of a new flag
* Document that delta bundles are expected to be created programatically and that they cannot be created using `opa build`. Consider adding a warning to `opa build` when a bundle contains a single patch.json file.

**Comment by ashutosh-narkar** [comment]
I think if you use the `-b` flag ie. `opa build -b bundle/` it should generate the correct bundle.

**Comment by charlieegan3** [comment]
Ahh, interesting! Yes, I can confirm that this works as expected. I think we can close this in that case.
