### ISSUE TITLE
[bundle] Support reuse of persisted bundles based on ETag value

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5673]
## What is the underlying problem you're trying to solve?

I would like to use the persisted bundles to reduce startup times when working with large data bundles. If my OPA has already persisted a large bundle to the persistence directory, I'd like it to be reused if the ETag value from the original download still matches the current ETag value from the bundle server.

## Describe the ideal solution

OPA Bundle persistence supports [ETag/If-None-Match HTTP caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#etagif-none-match
) with the option of supporting other more complex headers such as `Cache-Control` in future.

When persistence is enabled, bundles are stored in the configured persistence directory (default `./.opa`).

For example, if I use this configuration:

```yaml
services:
  example:
    url: http://localhost:8080

bundles:
  example:
    service: example
    resource: bundle.tar.gz
    persist: true
```

After starting my OPA, the persistence directory will look like this:

```
 $ tree .opa
.opa
└── bundles
    └── example
        └── bundle.tar.gz

2 directories, 1 file
```

I propose adding an `index.json` file after downloading a bundle to this directory with the following format:

```json
{
  "bundles": [
    {
      "path": "bundle.tar.gz",
      "headers": {
        "ETag": "..."
      }
    }
  ]
}
```

The file would be added in each subdirectory, i.e.:

```
 $ tree .opa
.opa
└── bundles
    └── example
        ├── bundle.tar.gz
        └── index.json

2 directories, 2 files
```

When OPA is restarted, currently the bundle will be refreshed if the bundle service is operational, even if the Etag is the same. This proposal would have OPA send an If-None-Match header when an Etag value was set for a given bundle in the `index.json` file in the persistence directory. OPA would load the bundle on disk in the event of a 304 response. The server should still set the ETag when returning a 304.

## Additional Context

We are interested in making it possible to run OPA commands like this where the bundle can be cached between runs.

```
opa run -s https://example.com/bundle.tar.gz
```

See https://github.com/open-policy-agent/opa/issues/5674

**Comment by anderseknert** [comment]
I like it! Is there any benefit in storing one `index.json` file per folder though, and not just a single `index.json` in the root of the `bundle_persistence_directory` to keep track of all of them?

**Comment by charlieegan3** [comment]
My only thinking there was around corruptions to the index.json file. I was concerned that locking on a single index.json file for potentially many bundles might be bad for performance due to contention or introduce corruptions with dirty writes.

**Comment by anderseknert** [comment]
If you have a single OPA serve that many bundles, you're probably doing something wrong 😅 But fair enough. These should hopefully be opaque to an end-user anyway.

**Comment by charlieegan3** [comment]
I've been able to make a start on this today. Since for each path in the persistence dir there is only one bundle.tar.gz file, I think that it makes sense to just have a `manifest.json` file with the ETag stashed in it for now. I've got downloads saving the ETag in this way, but need to work on loading the persistence dir's manifest.json data into the store's etag list now.

**Comment by ashutosh-narkar** [comment]
After OPA loads bundles from the persistence directory, it will check the store for the ETag of the configured bundles and use that to configure the downloader and set the `If-None-Match` header in the call to the server. Now if OPA was started with disk storage this would result in the same bundle NOT being downloaded. If OPA was started with in-memory storage it would. I'm not sure if including the ETag in the manifest is the right approach here as it does not seem to be related to bundle metadata itself but more about the downloader mechanism. Also could cause confusion with the `revision` field imo. 

Now the meta question here is how we define a "large" bundle and should the user consider using disk storage for that and if not having an in-memory storage at the expense of an additional bundle download while OPA still serves user requests is good enough behavior. WDYT?

**Comment by charlieegan3** [comment]
Interesting, I hadn't considered the disk storage solution here. I can confirm that this sends the correct headers such that bundle redownloading can be avoided.

I think that the best thing to do here might be to alter https://github.com/open-policy-agent/opa/pull/5675 and have it map to config more like this:

```yaml
services:
  example:
    url: http://localhost:8080

bundles:
  example:
    service: example
    resource: bundle.tar.gz

storage:
  disk:
    auto_create: true
    # or something suitable, but likely not .opa since that's the default persistence dir
    directory: .opa-cache 
```

Wdyt @anderseknert? I think that we can do what we need by using the disk storage instead?

**Comment by charlieegan3** [comment]
It was our hope that we'd be able to avoid using the disk storage for this. Primarily since this functionality backs https://github.com/open-policy-agent/opa/issues/5674 which is helpful when performing rudimentary memory performance tests.

> After OPA loads bundles from the persistence directory, it will check the store for the ETag of the configured bundles

I think that I am correct in saying though that the Etag will never be set in the store when loading persisted bundles after a cold start of OPA. Is that right?

> I'm not sure if including the ETag in the manifest is the right approach here as it does not seem to be related to bundle metadata itself but more about the downloader mechanism

That said, we do have a mechanism to set an ETag on a bundle:

https://github.com/open-policy-agent/opa/blob/8f5500d078ad51901f296513cfb725820c0d4059/bundle/bundle.go#L57

However, when we're loading bundles from disk here:

https://github.com/open-policy-agent/opa/blob/8f5500d078ad51901f296513cfb725820c0d4059/internal/bundle/utils.go#L101

I don't think there's any way that the etag is set here since it's not set on the reader:

https://github.com/open-policy-agent/opa/blob/8f5500d078ad51901f296513cfb725820c0d4059/bundle/bundle.go#L699

Do you think that changing this behaviour is unsuitable to allow Etag values to persist across a cold start of an OPA?

> Also could cause confusion with the revision field imo

Perhaps, but as I see it this is an internal working of OPA and how it manages the contents of the persistence dir. The bundle file itself is unchanged. Would using a hidden file like `.index.json` or similar be an improvement?

> Now the meta question here is how we define a "large" bundle

Perhaps we could if the server sets a value for `Content-Length` greater than the available RAM we could warn the user that enabling disk storage would be a good call.

**Comment by charlieegan3** [comment]
@ashutosh-narkar, I've had a go at a draft implementation of this here: https://github.com/open-policy-agent/opa/pull/5687. I'd be interested to know if you still see problems with this approach.

**Comment by ashutosh-narkar** [comment]
Closing for now. We can revisit this enhancement in the future.

**Comment by charlieegan3** [comment]
👍 think it's fair 🙂
