### ISSUE TITLE
Support Ethereum `ecrecover` function and other Ethereum-specific cryptographic primitives [Web3 Kickoff 🚀]

### ISSUE THREAD

**Issue by amrap030** [open-policy-agent/opa#5708]
## What is the underlying problem you're trying to solve?

**Disclaimer**: I am not a cryptographic expert, but I will try to describe the request as best as possible.

Cryptographic signatures are a key part of the blockchain. They are used to prove ownership of an address without exposing its private key. This is useful not only on the blockchain but also to authorize incoming requests in a backend application.

When a user creates an Ethereum account, he creates a public-private keypair. The public key is generated from the private key using the Elliptic Curve Digital Signature Algorithm (**ECDSA**). You get a public address for your account by taking the last 20 bytes of the Keccak-256 hash of the public key and adding "0x" to the beginning. Those building blocks can be used to verify ownership of an Ethereum account address in the following way:

1. The owner of an Ethereum Account address signs an arbitrary message with his private key in the client application: `sig(message, publicAddress, privateKey)`
2. He sends the signature along with the message in a request to the backend: `send(sig, message)`
3. The backend can now use `ecrecover(message, sig)` to recover the user's `publicAddress` to verify ownership of the account.

**Example**:

```bash
message = "OPA is awesome!"
publicAddress = "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
privateKey = "0x..."

sig(message, publicAddress, privateKey) = "0x636d2808bd4ffba3a5010a72d5f427b2df69f7b07f52610dad2eb10e0fc24e297435228bac142dec01e113e16900f04ee6fc8ddc358bd6ad0ee1be9f90501f8c1c" = sig

ecrecover(message, sig) = "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc" = publicAddress
```

At this point we can allow the request or do any further checks. This process can be seen and tested in practice [here](https://etherscan.io/verifiedSignatures#) at Etherscan.

## Describe the ideal solution

In the ideal scenario, OPA would include the `ecrecover` function, used to recover an Ethereum account address from a message and signature.

```rego
allow if {
  address := eth.ec_recover(input.message, input.signature)
  address == "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
}
```

This would require a new built-in function called `eth.ec_recover(message, signature)`. You can have a look at [this](https://github.com/ethereum/go-ethereum/blob/master/crypto/signature_cgo.go) repo, it might help.

If this will be addressed, I think It would also make sense to also include a bunch of other cryptographic primitives that the Ethereum blockchain uses. This includes for example the ability to use `Keccak256` as a new built-in hash function.

```rego
allow if {
  hash := crypto.keccak256(input.message)
  hash == "..."
}
```

This would require a new built-in function called `crypto.keccak256(x)` or `eth.keccak256(x)`.

Next to that and without going into detail here, it might be useful to include the following functions from the official solidity [cheatsheet](https://docs.soliditylang.org/en/v0.8.14/cheatsheet.html?highlight=encodepack#global-variables):

```solidity
abi.decode(bytes memory encodedData, (...))
abi.encode(...)
abi.encodePacked(...)
abi.encodeWithSelector(bytes4 selector, ...)
abi.encodeCall(function functionPointer, (...))
abi.encodeWithSelector(functionPointer.selector, (...))
abi.encodeWithSignature(string memory signature, ...)
abi.encodeWithSelector(bytes4(keccak256(bytes(signature)), ...)
```

I think in general, it would be a great idea to support some web3 stuff :)

## Describe a "Good Enough" solution

In a first iteration, an implementation of the `ecrecover` function would be enough.

## Additional Context

- some information on Ethereum accounts: https://ethereum.org/en/developers/docs/accounts/
- ecRevover implementation in go: https://github.com/ethereum/go-ethereum/blob/master/crypto/signature_cgo.go
- article about Ethereum message signing/login: https://dev.to/shahbaz17/demystifying-login-with-ethereum-55dg
- solidity docs: https://docs.soliditylang.org/en/v0.8.14/index.html
- tool to sign and verify messages on Ethereum: https://etherscan.io/verifiedSignatures#

**Comment by ashutosh-narkar** [comment]
@amrap030 thanks for the detailed feature request! Today you can extend OPA via custom builtin functions https://www.openpolicyagent.org/docs/edge/extensions/#custom-built-in-functions-in-go and that process is pretty simple to implement.

We avoid pulling thirdparty dependencies into OPA and these builtins may requires that.  Also looks like [this](https://github.com/ethereum/go-ethereum/blob/master/crypto/secp256k1/secp256.go#L8) package calls C code which would mean the static OPA builds won't support this builtin. Is this correct @srenatus ?

**Comment by amrap030** [comment]
@ashutosh-narkar I think it doesn't need to use thirdparty dependencies, but it is probably not that easy to build such functions from scratch.

**Comment by anderseknert** [comment]
If there are generally useful cryptographic functions that could be added to OPA, that sounds good. Anything specific to blockchains or ethereum is IMHO better suited for custom functions.

**Comment by ashutosh-narkar** [comment]
Closing this for now as custom functions may be the approach to use here for now.
