### ISSUE TITLE
Suggestion: add "category" to top-level annotations

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5716]
One thing I find missing in the current set of "blessed" (i.e. top-level) annotations is something that could be used to group rules (or packages) of similar type. This could be either a domain, like `kubernetes` or `terraform`, or something more granular. This should be generic enough that it should have use-cases in many policy types.

I suggest we have a "category" attribute added for that purpose.

**Comment by charlieegan3** [comment]
I agree that something like this would be helpful. I had wondered about tags or labels before. `category` to me is one of a fixed set of things, rather than an arbitrary group name. Some other ideas might be `group` or `collection`?

**Comment by anderseknert** [comment]
Hmm, you are right about `category` limiting the number to one! I like `tags`, as it would be pretty much a free-form collection. The drawback would be some more work on the "client" to e.g. get all rules by a specific tag, but that would not require too much effort.

**Comment by charlieegan3** [comment]
Yeah true. I guess I see it as two different features, `tags`/`labels` vs `category`/`group`/`collection`.

I think `group` and `labels` make the most sense to me personally. Though I wouldn't be surprised if that were just my personal wording perferences.

**Comment by anderseknert** [comment]
Haha! I like `category` and `tags` better 😆 But I'm not losing sleep over this decision. If others have opinions, now would be a good time to vent them!

**Comment by ashutosh-narkar** [comment]
I like the idea of having a `tags` attribute. Not sure we need both `category` and `tags` in that case. Also how do you see this working? Do you have a use-case in mind?

**Comment by anderseknert** [comment]
@ashutosh-narkar I'm working on tooling that would use this type of metadata in order to display rules by e.g. category in generated docs. I can accomplish this already by using custom attributes, but it feels like a common enough attribute that it deserves top-level recognition. I think there's room for both category and tags, as category would easier be used for grouping (like `kubernetes`), and tags for random metadata (like `beta`, `side-effects`, `v1`, etc).

**Comment by charlieegan3** [comment]
One reason I'm weary of tags is that they often get used to store key:value data when they shouldn't. I suppose we have the custom section if people need that though.

**Comment by anderseknert** [comment]
@pauly4it what do you think?

**Comment by anderseknert** [comment]
Also, are there any other attributes that we think deserves top-level recognition? I've seen "severity" used in many policies, so that's one candidate.

**Comment by pauly4it** [comment]
I could see `category`, `tags`, and `severity` being helpful for some use cases, but as an OPA user I would expect any built-in annotation keys to apply to a broad set of use cases. For example, in application authorization/entitlements use cases, `severity` wouldn't necessarily apply to rules used allow an API call or user action. The currently supported annotation keys apply across many use cases, and the `custom` key provides the flexibility to allow users to add annotations for their specific use cases. Also, adding these keys to the official OPA annotations may make users feel they _should_ include those keys when specifying annotation metadata when it may not be appropriate.

Perhaps you could put this out to the broader OPA community as a more general question about additional annotation keys to support? If you see certain annotations being commonly used across use cases, those would seem like good candidates for official support in OPA.

**Comment by anderseknert** [comment]
At least to me, `category` (or whatever it will be named) seems generic enough to warrant inclusion. Leaving `severity` as a custom annotation seems reasonable.

**Comment by anderseknert** [comment]
I'll do fine with custom attributes, and consensus here was more challenging than I had expected. Perhaps rightly so :) If others want this, or some other attribute at the top level later, feel free to reopen.
