### ISSUE TITLE
Inter query cache for decision masking

### ISSUE THREAD

**Issue by mjungsbluth** [open-policy-agent/opa#5723]
## What is the underlying problem you're trying to solve?

With the addition of decision log dropping, the inter query cache is [used for evaluation](https://github.com/open-policy-agent/opa/blob/5c183f5ecb68e31d941f0f156b01c78c93e86387/plugins/logs/plugin.go#L983). In the same file, the query that is [prepared for masking](https://github.com/open-policy-agent/opa/blob/5c183f5ecb68e31d941f0f156b01c78c93e86387/plugins/logs/plugin.go#L916), the cache is not used. I suspect that this is an oversight that could be an easy target for increasing the efficiency as masking if it is used is probably on the hot path.

**Comment by anderseknert** [comment]
That does sound like an easy addition. Are you using `http.send` in your decision masking policies? Or is there some other usage of the inter query cache that I've forgotten about? 🙂

**Comment by srenatus** [comment]
I think it's all there is to it. But from spot-checking the two call sites, I'm not sure that drop decision _should_ use the IQBC like that: It's creating it afresh before passing it to the rego.New() call,
``
interQueryCache := cache.NewInterQueryCache(p.manager.InterQueryBuiltinCacheConfig())
```

So what would this even do? If there's a http.send in the policy, we'd store the result, but discard the cache, since that variable isn't used anywhere else.

I think it would perhaps be more consistent to remove the two IQBC-related lines from the drop decision call site. Unless, of course, there's a use case behind this that I'm unaware of.

**Comment by anderseknert** [comment]
Oh... yeah that does look rather wrong. If we want we could probably expose the cache from the server to the plugin manager? But I'm not sure there's a a use case for calling external services on drop/mask decisions 🤔

**Comment by srenatus** [comment]
I'd remove it. It's not working right now, and nobody has asked for it -- unless I'm misreading @mjungsbluth.

**Comment by mjungsbluth** [comment]
No opinion tbh. I was looking at obvious culprits for performance impact and this one looked odd/stood out

**Comment by anderseknert** [comment]
Removed here: https://github.com/open-policy-agent/opa/pull/5731

Not much more to do here, I think.. so I'm closing.
