### ISSUE TITLE
2uinc has adopted OPA

### ISSUE THREAD

**Issue by s33dunda** [open-policy-agent/opa#5729]
### Organization Name

2U, Inc

### Organization Website

2u.com

### Organization Logo (optional)

https://www.insidehighered.com/sites/default/server_files/media/2U_edX_Logo.jpg

### How is your organization using OPA?

OPA has been incorporated into our SDLC for both terraform and kubernetes deployments.
Shift left!

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by charlieegan3** [comment]
Hey Charles 👋 thanks for filing this. Great to hear you're using OPA! I have a PR open here to add you to the list: https://github.com/open-policy-agent/opa/pull/5735

See you in slack if you run into any issues!
