### ISSUE TITLE
docs: Headings are behind fixed header when following fragment links

### ISSUE THREAD

**Issue by kristiansvalland** [open-policy-agent/opa#5774]
## Short description

Anchor links (sections/headings) for docs served from openpolicyagent.org/docs/ does not take the fixed header/banner into account, as the heading (h2) is hidden behind the banner when following docs-links with #fragments. See attached image for how it looks in Mozilla Firefox.

This behaviour makes it harder to navigate and immediately understand where in the page one was actually directed to.

I've tested this in both Firefox and Chrome.

## Steps To Reproduce

1. Click the following link: https://www.openpolicyagent.org/docs/latest/#overview or any subsection link on the left navbar of the docs.
2. Observe that the "Overview" heading is not immediately visible, but is behind the banner.

## Expected behavior
The section heading should immediately be visible below the header.

## Potential solution

I found this StackOverflow question that might give some ideas:
https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

Not an HTML/CSS expert though, so I will leave the fix for someone else.

## Additional context

Firefox version 110.0.1
Chrome version 111.0.5563.64
Tested on Mac with Ventura 13.2.1

![opa-docs-anchor-links](https://user-images.githubusercontent.com/54534849/226282201-6b03ca1c-a5e4-4856-ab48-1b7b48cf3200.png)

**Comment by kristiansvalland** [comment]
I suggest adding the labels "Good first issue" and "docs" -- I do not think I am allowed to do so myself.

**Comment by charlieegan3** [comment]
I've got a fix for this in https://github.com/open-policy-agent/opa/pull/5775

I think the preview looks ok: https://deploy-preview-5775--openpolicyagent.netlify.app/

**Comment by kristiansvalland** [comment]
It seems like there is some unforeseen effects from the fix you implemented, @charlieegan3. Now links like https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-types-is_boolean behave weird:

- The selected entry is pushed to the right
- It is still behind the banner

Notice the `is_boolean` line in the image below

<img width="1218" alt="Screenshot 2023-03-22 at 14 59 13" src="https://user-images.githubusercontent.com/54534849/226928007-cb9cef70-6538-4034-bdff-f1134b5dc135.png">
