### ISSUE TITLE
`make release-patch` script produces a broken patch file

### ISSUE THREAD

**Issue by johanfylling** [open-policy-agent/opa#5784]
The `make release-patch` script produces a patch output with `CRLF` line terminations, which makes the `patch` command fail when fed to it.

This issue can be reproduced on macOS running on an M1 chip; other impacted setups are currently unknown.

## Steps To Reproduce
Run select steps outlined in the [release documentation](https://github.com/open-policy-agent/opa/blob/main/docs/devel/RELEASE.md#bugfix-release-process).
1. `make release-patch VERSION=0.14.1 > ~/release.patch`
2. `patch -p1 < ~/release.patch`

Step 2 will fail, and produce `*.rej` files.
If we strip the `CR` characters from the file (e.g. `tr -d '\015' <release.patch > release2.patch`), step 2 will pass when fed the modified patch file.

**Comment by srenatus** [comment]
> This issue can be reproduced on macOS running on an M1 chip; other impacted setups are currently unknown.

I've seen the same following your repro steps on an amd64 mac. So, M1-unrelated.

**Comment by johanfylling** [comment]
`cat -e <filename>` can be used to show the line endings in a file; `$` for LF (unix) and `^M$` for CRLF (win).
