### ISSUE TITLE
parse: include location of rule ref in AST

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5790]
AST information from a rule head currently only includes the location of the value, not the rule ref var itself.
```rego
package location

foo := "bar"
```
```shell
opa parse location.rego --format json --json-include locations
```
```json
{
  "rules": [
    {
      "head": {
        "name": "foo",
        "value": {
          "location": {
            "file": "location.rego",
            "row": 3,
            "col": 8
          },
          "type": "string",
          "value": "bar"
        },
        "assign": true,
        "ref": [
          {
            "type": "var",
            "value": "foo"
          }
        ]
      }
    }
  ]
}
```
For tooling that works with the AST, this location information would be useful.

**Comment by charlieegan3** [comment]
Hmm, interesting. I think that we might be able to dig into where `NewHead` and `RefHead` are used and make sure we're setting the location on the Head structs as they're initially created. It supports the JSON opts, but I don't think the location is getting set during parsing.

**Comment by Trolloldem** [comment]
I have taken a look into the code of `NewHead` and `RefHead` as suggested by @charlieegan3, and noticed that when they are called in [parseHead](https://github.com/open-policy-agent/opa/blob/main/ast/parser.go#L834), the `defer` function should handle the process of setting the `Location` of the `Head` of a `Rule`. 

While investigating the motivation that causes the output to have missing location, I tried to use the following code as an example:

 ```golang
package test

default allow = false
allow = true {
    input.method == "GET"
    input.path = ["getSalary", user]
    input.user == user
}
```

In this case the output relative to the line `allow = true` is the following:

```JSON
      "head": {
        "name": "allow",
        "value": {
          "location": {
            "file": "t2.rego",
            "row": 4,
            "col": 9
          },
          "type": "boolean",
          "value": true
        },
        "ref": [
          {
            "type": "var",
            "value": "allow"
          }
        ],
        "location": {
          "file": "t2.rego",
          "row": 4,
          "col": 1
        }
      },
      "location": {
        "file": "t2.rego",
        "row": 4,
        "col": 1
      }
```

There is a similar part of the output for the `default allow = false`. 

What I noticed after this, is that in [parseModule](https://github.com/open-policy-agent/opa/blob/main/ast/parser_ext.go#L632), the statement used in the example of @anderseknert is handled by the `Body` case insted of the `*Rule` one. This causes the method [ParseRuleFromBody](https://github.com/open-policy-agent/opa/blob/main/ast/parser_ext.go#L135) to create a new `Rule` struct. The problem with this approach is that the code used to configure the correct JSON setting in [Parse](https://github.com/open-policy-agent/opa/blob/main/ast/parser.go#L399) is never called on this new struct.

I have tried to add similar code in the switch statement mentioned above and this is the output for the example of @anderseknert:

```JSON
"rules": [
    {
      "body": [
        {
          "index": 0,
          "location": {
            "file": "test.rego",
            "row": 3,
            "col": 8
          },
          "terms": {
            "location": {
              "file": "test.rego",
              "row": 3,
              "col": 8
            },
            "type": "boolean",
            "value": true
          }
        }
      ],
      "head": {
        "name": "foo",
        "value": {
          "location": {
            "file": "test.rego",
            "row": 3,
            "col": 8
          },
          "type": "string",
          "value": "bar"
        },
        "assign": true,
        "ref": [
          {
            "type": "var",
            "value": "foo"
          }
        ],
        "location": {
          "file": "test.rego",
          "row": 3,
          "col": 1
        }
      },
      "location": {
        "file": "test.rego",
        "row": 3,
        "col": 1
      }
    }
  ]
```
I can work on this to further investigate if only this addition fixes the problem and add some tests.

**Comment by anderseknert** [comment]
That'd be amazing! Thanks @Trolloldem 😃

**Comment by anderseknert** [comment]
Seems to be missing still in some cases: https://github.com/open-policy-agent/opa/issues/6860
