### ISSUE TITLE
Unexpected behaviour when using the `not` operator

### ISSUE THREAD

**Issue by JasonMan34** [open-policy-agent/opa#5793]
## What is the underlying problem you're trying to solve?

Consider the following example:
```rego
package foo

object_has_key(o, k) {
	_ = o[k]
}

default data_has_foo = false
data_has_foo {
	object_has_key(input.data, "foo")
}

default data_missing_foo = false
data_missing_foo {
	not object_has_key(input.data, "foo")
}

default data_missing_foo_2 = false
data_missing_foo_2 {
	not data_has_foo
}

```

When calling `/v1/data/foo` with `input = {}`, the following result is returned:

|                    | `input = {}` |
|--------------------|--------------|
| data_has_foo       | `false` ✅    |
| data_missing_foo   | `false` ❌    |
| data_missing_foo_2 | `true` ✅     |

When calling `not data_has_foo` we get `data_missing_foo_2 = true` as expected  
However, when calling `not object_has_key(input.data, "foo")`, we get `data_missing_foo = false`, which is not what we want  
This is unexpected because there should be no difference between `data_missing_foo` and `data_missing_foo_2` - One negates the function's return value directly, and one negates a variable that is equal to the function's return value  
Also, I can't use `data_missing_foo` because in my real use-case we call `object_has_key` on objects with dynamic keys

## Describe the ideal solution

Ideally, both expressions should evaluate the same
|                    | `input = {}` |
|--------------------|--------------|
| data_has_foo       | `false` ✅    |
| data_missing_foo   | \*\* `true` ✅ \*\*    |
| data_missing_foo_2 | `true` ✅     |

## Describe a "Good Enough" solution

At the least , I would expect to see a runtime exception or warning that an invalid evaluation is being attempted

## Additional Context

OPA Version: v0.50.2

**Comment by srenatus** [comment]
Is this related? Lots of not-related discussion in https://github.com/open-policy-agent/opa/issues/3924

**Comment by JasonMan34** [comment]
> Is this related? Lots of not-related discussion in #3924

I couldn't find an answer in there. But I have a better example for the problem:

```rego
package foo

object_has_key(o, k) {
	_ = o[k]
}

data_has_foo := object_has_key(input.data, "foo")

data_missing_foo {
	not object_has_key(input.data, "foo")
}

data_missing_foo_2 {
	not data_has_foo
}
```

|                    | `input = {}` |
|--------------------|--------------|
| data_has_foo       | `missing from response` ✅    |
| data_missing_foo   | `missing from response` ❌    |
| data_missing_foo_2 | `true` ✅     |

The unexpected behavior stems from the fact that calling `not` on a function seems to behave differently to calling `not` on a variable. Coming from any other programming language, I would expect that if `a = b` then `not a` and `not b` would behave exactly the same, but that isn't the case here

**Comment by srenatus** [comment]
> The unexpected behavior stems from the fact that calling not on a function seems to behave differently to calling not on a variable. Coming from any other programming language, I would expect that if `a = b()` then `not a` and `not b()` would behave exactly the same, but that isn't the case here

This isn't exactly what happens. The compiler does this to your policy:

```rego
not object_has_key(input.data, "foo")
```
is compiled to
```rego
a = input.data
b = object_has_key(a, "foo")
not b
```
Now, when evaluating that, `a = input.data` *fails*. Hence `data_missing_foo` fails.

`object_has_key` lets you safely check if an object has a key, but it won't guard against **its arguments** being undefined. No function can do that.

**Comment by JasonMan34** [comment]
Ah, I see the issue now. In `data_missing_foo_2`, I'm calling `not` on an already defined value (undefined) so the whole thing evaluated to `true`  
But in `data_missing_foo`, `not` is never even reached because the whole evaluation fails earlier. Thank you
