### ISSUE TITLE
Include a `generated` property in AST output of `opa parse`

### ISSUE THREAD

**Issue by johanfylling** [open-policy-agent/opa#5819]
The AST output from the parser will sometimes include generated AST nodes that weren't put there by the user, but inferred by the parser. E.g. when executing `opa parse policy.rego --format json` on the policy:

```rego
package test

p1 := true

p2 { true }
```

we get the output:

```json
{
  "package": {
    "path": [
      {
        "type": "var",
        "value": "data"
      },
      {
        "type": "string",
        "value": "test"
      }
    ]
  },
  "rules": [
    {
      "body": [
        {
          "index": 0,
          "terms": {
            "type": "boolean",
            "value": true
          }
        }
      ],
      "head": {
        "name": "p1",
        "value": {
          "type": "boolean",
          "value": true
        },
        "assign": true,
        "ref": [
          {
            "type": "var",
            "value": "p1"
          }
        ]
      }
    },
    {
      "body": [
        {
          "index": 0,
          "terms": {
            "type": "boolean",
            "value": true
          }
        }
      ],
      "head": {
        "name": "p2",
        "value": {
          "type": "boolean",
          "value": true
        },
        "ref": [
          {
            "type": "var",
            "value": "p2"
          }
        ]
      }
    }
  ]
}
```

The above output contains a `body` entry for rule `p1` and a `head.value` entry for rule `p2`. If, e.g., a linter was to consume this AST, it has no way of knowing that these portions were generated by `OPA`, and not the user, as should therefore be ignored.
If the AST contained a `generated` (or similar) property for generated nodes, the imagined linter could use that in it's processing.

The `JSONOptions` struct could be used to inform json marshaling whether this new property should be included in the AST output.

**Comment by anderseknert** [comment]
This would indeed be useful for code analysis. I wonder what else is there! Off the top of my head, the future keywords `if` and `contains`, although they aren't generated, but rather the opposite — removed from the AST.

**Comment by anderseknert** [comment]
While a `generated` property would still be nice for when dealing with AST nodes without location, it seems that we (and by "we", I usually mean @charlieegan3) knowingly or unknowingly solved this as we added location data to the AST. As _values_ now come with an associated location, generated values may be distinguished precisely by their lack of location information. 

Having some option to attach some cosmetic information, like the beforementioned `contains` or `if` constructs, to the AST, would be nice, but at least there's that.

**Comment by anderseknert** [comment]
I think we can close this now, as the need for this has been met by [roast](https://github.com/anderseknert/roast). But if someone else feels that this is needed, we can re-open.
