### ISSUE TITLE
Allow augmenting OPA's labels via discovery

### ISSUE THREAD

**Issue by mjungsbluth** [open-policy-agent/opa#5832]
## What is the underlying problem you're trying to solve?
OPA has a very simply way of preventing a discovery configuration to break the configuration to the point that bundle updates are no longer possible: It silently drops labels that are configured via a discovery document. 

We have recently come across a few use cases where we could use adding labels via discovery as a cheap way to pass for example application metadata to both status updates and decision log. Another case is that labels are very convenient to parameterize policies without touching rego. 

The actual risk of modifying labels is also depending on if the discovery is actually using rego or for example like Styra DAS serves pre-computed static documents. 

## Describe the ideal solution

Make it safe to change/add all labels that do not break the sub-sequent discovery or bundle downloads. This would be quite an endeavour especially for non-static discovery documents. 

## Describe a "Good Enough" solution

Allow discovery to add labels to the OPA bootstrap configuration and continue to drop those that are already configured in the bootstrap configuration

**Comment by anderseknert** [comment]
Thanks @mjungsbluth! Seems like the last sentence got cut before it was finished, but the description is at least enough to get the gist of the problem ;)

**Comment by mjungsbluth** [comment]
@anderseknert yeah, I had a forced update this morning and then was caught up until I realized this was actually already posted 😄.

**Comment by ashutosh-narkar** [comment]
You've documented the risk here @mjungsbluth. If the service config is Rego and uses something like `opa.runtime()` to get labels configured in the boot configuration, this could lead to issues if we allow overwriting labels. Are you proposing the ability to add new labels and not overwrite the ones specified in the boot config. I could imagine where we don't allow any changes to the labels in the boot config but the ones in the service config can be added/removed/modified.

**Comment by mjungsbluth** [comment]
Hi @ashutosh-narkar, yes I was suggesting to allow only adding new labels that do not exist in the bootstrap config. Any change would be discarded.

Your proposal also sounds interesting if I understand it correctly but tbh I don’t see a need for being able to modify labels. If additions are allowed, you can always calculate an effective value in Rego using a bootstrap label and an added label.

**Comment by ashutosh-narkar** [comment]
Adding new labels and not changing the labels provided in the boot config sounds good to me. Just to clarify let's say the boot config has labels `{"a": 1, "b": 2}` and the first service config has the label `{"c": 3, "d": 4}`. Once this discovery bundle is activated, the labels on the manager are `{"a":1, "b":2, "c":3, "d": 4}`. Now the second discovery update has labels `{"a": "foo", "c": "bar"}`. What would the labels on the manager be after this update is activated? 

`{"a":1, "b": 2,  "c": bar}`  OR `{"a":1, "b": 2,  "c": "bar", "d": 4}`

**Comment by mjungsbluth** [comment]
I‘d suggest `{"a":1, "b": 2, "c": bar}`, i.e always start from the bootstrap config plus additions from discovery. I feel that the other option is hard to predict and also inconsistent around restarts.

**Comment by ashutosh-narkar** [comment]
Closed via https://github.com/open-policy-agent/opa/pull/5836
