### ISSUE TITLE
Compile to intermediate representation (IR) from a filesystem

### ISSUE THREAD

**Issue by kjothen** [open-policy-agent/opa#5833]
## What is the underlying problem you're trying to solve?
I would like to execute queries held in memory directly in the JVM. The [Jarl](https://github.com/borgeby/jarl) library offers this capability but only operates on policies that have first been compiled to the intermediate representation (IR). To obtain an IR, the OPA command line must be used. There is no means of loading an arbitrary OPA document or bundle into memory and querying it without first shelling out to the OPA command line, and neither does the OPA GRPC/REST server support compiling to the IR.

## Describe the ideal solution
Ideally, there is a JVM version of OPA that supports loading OPA documents (bundles, data, policies) from disk or memory that supports query. 

## Describe a "Good Enough" solution
Support compiling to the IR from a filesystem in the low-level Go SDK. This allows for a lightweight, client OPA SDK program to be built which can do one task: take a filesystem/tarball bundle or policy document and return a compiled IR version.  Mostly, this just requires completing the support of an arbitrary filesystem everywhere builders use file paths in the OPA code, much of which is already established. Completing support for filesystems is probably a good enough PR on its own. It opens the door to more OPA client use cases (notably because the go `io/fs` interface supports in-memory filesystems), and is work that has already started.

## Additional Context
I don't have a full PR ready just now, but I have successfully created a client GO SDK program that can compile to IR from a policy document loaded into memory if I change the following files to add filesystem support (I use the `MemFS` filesystem in the Client code).
![Screenshot 2023-04-17 at 10 14 46](https://user-images.githubusercontent.com/3463278/232441132-1ae9bb2e-75fc-4281-a2ee-36a93c066088.png)

Another potential advantage is that many of the 200+ instances of `WithTempFS` used in testing can be replaced with an in-memory filesystem instead. All the test data is in memory anyhow, but gets written to a temp file system for testing, which is unnecessary if using a memory-backed filesystem such as `MemFS`. I have an alternative `WithTestFS` which achieves this.

**Comment by anderseknert** [comment]
Hi there @kjothen 👋 A full OPA implementation on the JVM would be something 🙂 I have no objections to your "Good enough" solution, so if you'd want to submit a PR, perhaps we can take it from there? Thanks!

**Comment by kjothen** [comment]
Thanks for reading through issue, and for your encouragement @anderseknert. I shall work on that PR now...shouldn't be too long I hope.
