### ISSUE TITLE
OPA doesn't find key if its value is false

### ISSUE THREAD

**Issue by fardin01** [open-policy-agent/opa#5840]
## Short description 

I have noticed that if a certain key has false as a value, OPA ignores it. Take this policy code:

```
package play

violation[{"msg": msg}] {
    provided := {context | input.securityContext[context]}
    required := {context | context := input.requiredContexts[_]}
    missing := required - provided
    count(missing) > 0
    msg := sprintf("Missing: %v. Provided: %v. Required: %v", [missing, provided, required])
}
```

given the following input:

```
{
    "requiredContexts": [
        "runAsNonRoot",
        "privileged"
    ],
    "securityContext": {
        "capabilities": {
            "add": [
                "NET_ADMIN",
                "SYS_TIME"
            ]
        },
        "runAsNonRoot": true,
        "privileged": false
    }
}
```

The output is:

```
{
    "violation": [
        {
            "msg": "Missing: {\"privileged\"}. Provided: {\"capabilities\", \"runAsNonRoot\"}. Required: {\"privileged\", \"runAsNonRoot\"}"
        }
    ]
}
```

Notice how `privileged` is missing even though it is provided in the input.

If `privileged` is switched to true, the code behaves as expected.

## Steps To Reproduce

https://play.openpolicyagent.org/p/TAcoRAZZcS

## Expected behavior

The value of the key should not affect whether the key is found or not.

**Comment by srenatus** [comment]
If you want to check for the keys existence, use 
```rego
has_key(o, k) if _ = o[k]
```
or use the [`object.keys`](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-object-objectkeys) builtin, like
```rego
has_key(o, k) if k in object.keys(o)
```

(`import future.keywords.if` for if, it put more `{ ... }` on it instead.)

**Comment by anderseknert** [comment]
FWIW I've just answered your question on SO: https://stackoverflow.com/questions/76044732/opa-doesnt-find-key-if-its-value-is-false/76045239#76045239

**Comment by srenatus** [comment]
@anderseknert I didn't put half the effort into it. 😜
