### ISSUE TITLE
Decision logs can include duplicate masked paths

### ISSUE THREAD

**Issue by jwineinger** [open-policy-agent/opa#5847]
## Short description 
We're running OPA as sidecars in a EKS environment. We've had a few users report sporadic errors for JWT verification policy we have, so we enabled decision logging to try and track those down. 

We didn't want actual JWTs to end up in our logs, so we used a masking policy to replace the JWT value with... a few things. We use a rule with incremental definitions to replace the logged value of the JWT with more information to help us debug the error cases.

```
mask[{"op": "upsert", "path": "/input/jwt", "value": logged_value}] {
{
  # return the claims on the jwt if it decodes
  logged_value := io.jwt.decode(input.input.jwt)[1]
} {
  # if the input doesn't decode as a jwt, but is not empty, then log just the first 10 chars
  not io.jwt.decode(input.input.jwt)
  count(input.input.jwt) > 0
  jwt_substring := substring(input.input.jwt, 0, 10)
  logged_value := concat("", [jwt_substring, "***"])
}
```

These are not all of the incremental definitions we have, but a sample. These seem to work, but I've noticed that in some cases that we investigated, the decision log's masked key contains duplicate paths:

```
    "masked": [
      "/input/jwt",
      "/input/jwt"
    ],
```

* OPA version: 0.49.0

## Steps To Reproduce
I don't have them yet. 

## Expected behavior
It may be that several of our mask definitions yield for the same input, though we don't intend for that to happen. In this case, the duplicates in the mask key might actually be a good hint that our mask policies need work. However, the decision log itself seems to only return one of the yielded values, so there may be some lost debug data there. I don't know what I'd want for behavior there, but deduplicating the values in the masked key and also losing the other yielded values feels wrong because it is just hiding stuff.

**Comment by ashutosh-narkar** [comment]
Let's say we have a mask policy like below:

```rego
package system.log

mask[{"op": "upsert", "path": "/input/password", "value": x}] {
  input.input.foo
  x := "**FOOOOOO**"
}

mask[{"op": "upsert", "path": "/input/password", "value": x}] {
  input.input.bar
  x := "**BAAAAAR**"
}
```

And if you query OPA with an input like:

```
 curl -X POST -H "Content-Type: application/json" -d '{"input": {"foo": "GET", "bar": "POST", "password": "secret"}}' localhost:8181/v1/data/authz/allow
```

Below is a truncated version of the decision log:
```
{"decision_id":"7b7176f2-37c8-41d0-8754-214c46adb0b4","input":{"bar":"POST","foo":"GET","password":"**FOOOOOO**"},"labels":{"id":"08b3f88f-26bc-44c6-8010-a1e0ef9a8b9f","version":"0.52.0-dev"},"level":"info","masked":["/input/password","/input/password"], .....
```

So the `masked` field of the log which is an array has the entry `["/input/password","/input/password"]` which makes sense as both conditions in our mask policy were satisfied. Internally, OPA will replace the value for `password` with `**BAAAAAR**` for example and then overwrite it `**FOOOOOO**` for the other match. 

As you mentioned duplicates in the mask key serve as an indication that the mask policy needs to re-examined and fixing the policy itself seems the right path here imo.

**Comment by anderseknert** [comment]
I don't see anything directly actionable here, so I'll close this. Let me know if I missed something and we'll re-open.
