### ISSUE TITLE
io.jwt.decode_verify "iss" constraint permits no "iss" value

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [open-policy-agent/opa#5850]
## Short description 
We are using `io.jwt.decode_verify` function to both verify the token and check constraints. One of the constraints is "iss":
```
[valid, _, _] := io.jwt.decode_verify(token, {
	"alg": "RS256",
	"iss": "xxx",
	"cert": cert,
})
```
When there is no "iss" in the token payload, for example the token payload looks like below:
```
{  "sub": "1234567890",  "name": "John Doe" }
```
The function `io.jwt.decode_verify` returns `valid = true`.
This issue was replicated in a playground, [here](https://play.openpolicyagent.org/p/h2DJzcDfw6).
* OPA version: 0.51.0

## Expected behavior
The "iss" should we validated when it is passed as a constraint. When a token doesn't contain "iss", the result of verify should be false (`valid = false`).

## Additional context
The problem is related to this code [fragment](https://github.com/open-policy-agent/opa/blob/6a1af0fdebe155ca4496730ba7faeb62d0186ed0/topdown/tokens.go#L1063):
```
if constraints.iss != "" {
	if iss := payload.Get(jwtIssKey); iss != nil { // when iss is null, this branch is not executed
		issVal := string(iss.Value.(ast.String))
		if constraints.iss != issVal {
			return iter(unverified)
		}
	}
}
```

**Comment by anderseknert** [comment]
Agreed, that seems like an oversight. Would you want to submit a fix?

**Comment by AleksanderBrzozowski** [comment]
@anderseknert I can try 😉

**Comment by anderseknert** [comment]
Great! 😃

**Comment by anderseknert** [comment]
@AleksanderBrzozowski any progress? Let me know if you need any help 🙂

**Comment by AleksanderBrzozowski** [comment]
@anderseknert Thanks for reaching out, to be honest I was busy last two weeks, and I haven't investigated this issue yet.

I found some tests defined as yaml files, for example this [test-jwtdecodeverify-invalid-exp-type.yaml](https://github.com/open-policy-agent/opa/blob/8029cd417bfb87667a711a99c7ede360a6e0f3ad/test/cases/testdata/jwtdecodeverify/test-jwtdecodeverify-invalid-exp-type.yaml).
Should I create similar tests?
How I can invoke them?

**Comment by anderseknert** [comment]
Hey! Yep, adding YAML tests is the best option :)

They'll all be invoked by `make test`, but if you'd like to invoke individual tests, there's some instructions for doing so [here](https://github.com/open-policy-agent/opa/blob/main/test/cases/testdata/helloworld/test-helloworld-1.yaml) (of all places).
