### ISSUE TITLE
add OPA version to Prometheus metrics

### ISSUE THREAD

**Issue by jmoghisi** [open-policy-agent/opa#5852]
## What is the underlying problem you're trying to solve?
We have many OPA sidecar instances running at any one time.
We'd like to know what versions of OPA are deployed in each environment using our existing Grafana dashboards. 
We'd like to use Prometheus metrics to expose this (rather than building custom tooling that uses OPA's HTTP API).

## Describe the ideal solution
Add a guage to prometheus metrics with a tag containing the OPA version number, similar to existing `go_info` metric:

```text
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.20.2"} 1
```

For example:
```text
# HELP opa_info Information about the OPA environment.
# TYPE opa_info gauge
opa_info{version="0.50.0"} 1
```

**Comment by ashutosh-narkar** [comment]
The Status plugin should have access to the labels configured on the manager. These labels should include the OPA version. So if we were to add a new gauge in [here](https://sourcegraph.com/github.com/open-policy-agent/opa@6a1af0fdebe155ca4496730ba7faeb62d0186ed0/-/blob/plugins/status/metrics.go) we should be able to surface that info via the Status plugin by updating [this](https://sourcegraph.com/github.com/open-policy-agent/opa@6a1af0fdebe155ca4496730ba7faeb62d0186ed0/-/blob/plugins/status/plugin.go?L491) method. @jmoghisi if you'd like to contribute this feature happy to help.

**Comment by ashutosh-narkar** [comment]
This looks reasonable @jmoghisi. Looking forward to the PR. Thanks for looking into this!

**Comment by jmoghisi** [comment]
@ashutosh-narkar I have added the test. please may you review the PR?

**Comment by ashutosh-narkar** [comment]
Closed by https://github.com/open-policy-agent/opa/pull/5881.
