### ISSUE TITLE
Combination of ref rules can cause `invalid memory address` runtime error at eval-time

### ISSUE THREAD

**Issue by johanfylling** [open-policy-agent/opa#5859]
The following module:

```rego
package play

import future.keywords

a.b contains c { c := "bar"}

a[c] := 42 { c := "c" }
```

will result in the following error: 

```
runtime error: invalid memory address or nil pointer dereference
``` 

when evaluated.

**Comment by anderseknert** [comment]
I'm [not seeing](https://play.openpolicyagent.org/p/R50zSyIjSI) the error reported here, so I guess this has been resolved. If that's not the case, let me know and I'll re-open.
