### ISSUE TITLE
[eval] Update profile-sort flag to show valid options

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5862]
When using `--profile-sort` on `opa eval` it's not clear from the CLI help what the valid options are.

I think that all the valid options are [here](https://github.com/open-policy-agent/opa/blob/efb41bc28cf6714aaa60432c1591fa85ecb918c0/profiler/profiler.go#L97-L115). Also see here in [docs](https://www.openpolicyagent.org/docs/latest/policy-performance/#sort-criteria-for-the-profile-results).

Given that more than one option can be set, we'll need to validate this in some way other than with an Enum flag.

**Comment by ashutosh-narkar** [comment]
List of valid options can be found [here](https://www.openpolicyagent.org/docs/latest/policy-performance/#sort-criteria-for-the-profile-results) too.

**Comment by anderseknert** [comment]
Fixed in #5924 

Thanks @ecbenezra 👍
