### ISSUE TITLE
Add --format discard to `opa eval`

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5863]
I find myself doing a lot of experiments using `opa eval` where I don't particularly care for the output produced by evaluation (or at least not after having the value confirmed in a first evaluation), but I *do* care about the output of the various command line options like `--profile`. This is particularly annoying for queries that might generate a lot of data which clutter up the screen. What I'd like to see is thus the inverse of `--format raw` (which prints the value and **nothing else**) and have the "discard" (naming suggestions welcome) option show the output of eval flags, and **not** the value.

**Comment by anderseknert** [comment]
That'd be neat. I guess it could be that there are CI/CD scripts running `opa eval` depending on where the output currently goes though? 🤔

**Comment by srenatus** [comment]
Maybe it would be safe to only apply the change to *pretty* output? It's highly unlikely that anyone would parse that programmatically. Not sure if that would help your use case, though -- would it?

**Comment by srenatus** [comment]
An alternative could be `--output, -o`, which could be supplied with a file or `/dev/null`.

**Comment by anderseknert** [comment]
Yeah, although it might not be clear that would only impact the "value" getting sent there. I think I still like the "discard" option best, but anything is fine with me 🙂

**Comment by 26tanishabanik** [comment]
@anderseknert , can you kindly explain with an example for this when you say: "What I'd like to see is thus the inverse of --format raw (which prints the value and nothing else) and have the "discard" (naming suggestions welcome) option show the output of eval flags, and not the value."?

**Comment by 26tanishabanik** [comment]
@charlieegan3, makes total sense, thanks a lot for explaining with examples
I was wondering if I can work on this issue, seems like it can be a good starting point for me for contributing
What do you suggest, from where should I start?

**Comment by 26tanishabanik** [comment]
@charlieegan3 
I was able to produce this output, but had to create a new struct for discarded output:

<img width="1144" alt="Screenshot 2023-07-06 at 12 28 11 AM" src="https://github.com/open-policy-agent/opa/assets/50806654/51bf65f0-57b8-467f-8ff5-6d3d08aca428">

What do you think?

**Comment by anderseknert** [comment]
Adding `"result": "discarded"` seems OK when there is other output printed, like above, but if there isn't, I'd prefer if the output is blank / empty. If you use the discard format, you probably know what to expect anyway.

**Comment by charlieegan3** [comment]
Yeah I think that makes sense. 

So `$ opa eval '1+1' --format=discard` would output nothing at all, unless there were some error from `--fail` or `--show-builtin-errors`.

but `$ opa eval '1+1' --format=discard --profile` would look [as above](https://github.com/open-policy-agent/opa/issues/5863#issuecomment-1622305561)

**Comment by 26tanishabanik** [comment]
> I think that looks pretty promising! I think it's good to have the result present but labelled as "discarded".
> 
> Rather than needing to make a new struct, perhaps it'd be possible to write a custom `MarshalJSON` function like this: https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON ?

So, you are saying to use `unmarshal` instead of `encode`?

**Comment by charlieegan3** [comment]
[`Encode`](https://pkg.go.dev/encoding/json#Encoder.Encode) will use a custom `MarshalJSON` if it is defined.

An error example might look like:

```
$ opa eval '1/0' --show-builtin-errors
{
  "errors": [
    {
      "message": "div: divide by zero",
      "code": "eval_builtin_error",
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      }
    }
  ]
}
```

**Comment by 26tanishabanik** [comment]
Thanks @charlieegan3  for the inputs. It is coming up now:

```
func (o Output) MarshalJSON() ([]byte, error) {
	var s map[string]interface{} = map[string]interface{} {
		"metrics": o.Metrics,
		"profile": o.Profile,
	}
	return json.Marshal(s)
}

func Discard(w io.Writer, x interface{}) error {
	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "  ")
	field, ok := x.(Output)
	if ok {
		return encoder.Encode(field)
	}
	return encoder.Encode(x)
}
```

```
Output:
{
  "metrics": {
    "timer_rego_query_compile_ns": 517208,
    "timer_rego_query_eval_ns": 107417,
    "timer_rego_query_parse_ns": 183917
  },
  "profile": [
    {
      "total_time_ns": 94501,
      "num_eval": 2,
      "num_redo": 2,
      "num_gen_expr": 2,
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      }
    }
  ]
}
```

**Comment by charlieegan3** [comment]
Hey @26tanishabanik - would you feel ok to open a PR and we can chat in more detail about the code on there?

**Comment by 26tanishabanik** [comment]
> Hey @26tanishabanik - would you feel ok to open a PR and we can chat in more detail about the code on there?

Sure, @charlieegan3
