### ISSUE TITLE
Complete rule and partial object rule overlap causes `var requires evaluation` error

### ISSUE THREAD

**Issue by johanfylling** [open-policy-agent/opa#5870]
```rego
package test

p := 1

p[k] := v { k := input.key; v := input.value}
```

The above rule will cause a `var requires evaluation` error at eval-time.

## Expected behavior

Either:

A. Fail at compile-time, as the `test.p[k]` rule is generating documents (object key/values) within the extent of rule `test.p`, which is a violation similar to how the rules `test.p` and `test.p.q` are in conflict.

or

B. Fail at eval-time with an `eval_conflict_error`, as the two rules are assigning two conflicting values to `test.p`.

**Comment by johanfylling** [comment]
As an interesting, but related, aside: the following policy

```rego
package ex

p := 1

p := {"one": "two"}

p[k] := v { k := "foo"; v := "bar" }
```

will spawn the error: `eval_conflict_error: object keys must be unique`. Even though there is no key conflict between `one` and `foo`.

**Comment by anderseknert** [comment]
Trying the example in the original description, I get:

```
1 error occurred: policy.rego:3: rego_type_error: conflicting rules data.test.p[k] found
```

The second example gives:

```
1 error occurred: policy.rego:3: rego_type_error: conflicting rules data.ex.p[k] found
```

So I guess this is fixed?

**Comment by johanfylling** [comment]
Yet another drive-by fix when implementing general refs in rule heads, I believe 😄.

**Comment by anderseknert** [comment]
Excellent :)
