### ISSUE TITLE
Add a `crypto.x509.parse_and_verify_certificates_with_keys` builtin

### ISSUE THREAD

**Issue by IxDay** [open-policy-agent/opa#5882]
## What is the underlying problem you're trying to solve?
The current version of `crypto.x509.parse_and_verify_certificates` builtin does not provide a way to check against which key usage the certificate is validated. Due to the golang implementation of verify it will default to ([see code](https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/crypto/x509/verify.go;l=815-817)) `serverAuth`.
However, some validations may need a different key usage to be handled. In my case it would be `clientAuth` since I am trying to validate a certificate sent by an http client.

## Describe the ideal solution
Ideally it would be perfect to add an optional argument to the `crypto.x509.parse_and_verify_certificates` which is an array of key usages we want to check against (and default to `serverAuth` if not provided to keep the current behavior).

## Describe a "Good Enough" solution

I think an additional builtin `crypto.x509.parse_and_verify_certificates_with_keys` with an additional argument which is an array of string would be totally sufficient to address most of the problems.

## Additional Context

None for the moment, I may edit this later

**Comment by ashutosh-narkar** [comment]
[Currently](https://sourcegraph.com/github.com/open-policy-agent/opa@d718975b5de4b05cf2c88d5a52efaa33e71b0f0e/-/blob/topdown/crypto.go?L304) OPA sets `Roots` and `Intermediates` field of the [x509.VerifyOptions](https://pkg.go.dev/crypto/x509#VerifyOptions). If we were to add a new builtin may that could take an object that allows users to optionally specify `KeyUsages`, `DNSName` and other options of [x509.VerifyOptions](https://pkg.go.dev/crypto/x509#VerifyOptions). WDYT?

**Comment by AhmedGrati** [comment]
@ashutosh-narkar Can you assign it to me, if no one is working on this?

**Comment by yogisinha** [comment]
Hi @ashutosh-narkar , Can I pick this ?

**Comment by ashutosh-narkar** [comment]
Sure @yogisinha!

**Comment by yogisinha** [comment]
Hi @ashutosh-narkar ,
I am planning to add the builtin  `crypto.x509.parse_and_verify_certificates_with_key_usages` which will be called with an additional parameter which will be array of key usages like following:

`crypto.x509.parse_and_verify_certificates_with_key_usages(pem encoded certs data, ['KeyUsageServerAuth', 'KeyUsageClientAuth', 'KeyUsageCodeSigning'])`

I will maintain the map of this strings to actual Go constants defined in x509.go in std lib and pass the actual key usages in verifyOptions struct
I will also validate if the passed key usages strings are valid or not.

Users can pass empty array also in which case I will apply the KeyUsageServerAuth which is default in std lib.

lmk what you think ?

**Comment by ashutosh-narkar** [comment]
@yogisinha what if we create a new builtin called something like `crypto.x509.parse_and_verify_certificates_with_options`. The second argument would be an object that allows users to optionally specify KeyUsages, DNSName and other options of [x509.VerifyOptions](https://pkg.go.dev/crypto/x509#VerifyOptions). This way seems more flexible.

**Comment by yogisinha** [comment]
Ok, so the usage will be something like this, exposing the remaining options given by [x509.VerifyOptions](https://pkg.go.dev/crypto/x509#VerifyOptionsl). `Intermediates` and `Roots` are filled by cert data in 1st argument.

```
crypto.x509.parse_and_verify_certificates_with_options(
pem encoded cert data,
'{
"DNSName": "some_value", "CurrentTime": "value in epoch", 
"KeyUsages": ["KeyUsageServerAuth", "KeyUsageClientAuth", "KeyUsageCodeSigning"]}",
"MaxConstraintComparisons": "int value"
)'
)
```
thats how you are envisioning it ?

**Comment by ashutosh-narkar** [comment]
Yeah something like that.

**Comment by yogisinha** [comment]
Hi @ashutosh-narkar ,

Following is the code snippets of my main changes. I have some questions also abt main function. Please lmk what do you think. Thanks..

Declaring the builtin :

```
var CryptoX509ParseAndVerifyCertificatesWithOptions = &Builtin{
	Name: "crypto.x509.parse_and_verify_certificates_with_options",
	Description: `Returns one or more certificates from the given string containing PEM
or base64 encoded DER certificates after verifying the supplied certificates form a complete
certificate chain back to a trusted root.

The first certificate is treated as the root and the last is treated as the leaf,
with all others being treated as intermediates.`,
	Decl: types.NewFunction(
		types.Args(
			types.Named("certs", types.S).Description("base64 encoded DER or PEM data containing two or more certificates where the first is a root CA, the last is a leaf certificate, and all others are intermediate CAs"),
			types.Named("options", types.NewObject(
				nil,
				types.NewDynamicProperty(
					types.A,
					types.NewAny(
						types.S,
						types.N,
						types.NewSet(types.A),  // list of key usages will be taken in as a Set so that dup key usages entries will be de-duped automatically
					),
				)),
			).Description("object containing a set or array of neighboring vertices"),
		),
		types.Named("output", types.NewArray([]types.Type{
			types.B,
			types.NewArray(nil, types.NewObject(nil, types.NewDynamicProperty(types.S, types.A))),
		}, nil)).Description("array of `[valid, certs]`: if the input certificate chain could be verified then `valid` is `true` and `certs` is an array of X.509 certificates represented as objects; if the input certificate chain could not be verified then `valid` is `false` and `certs` is `[]`"),
	),
}
```

Function implementing the functionality. I just wanted to know that the approach of collecting the json info is right, or is there any other way. I am implementing the built in function first time. And another thing is function `verifyX509CertificateChainWithOptions`. This will be just copy of `verifyX509CertificateChain` with addition of one more option parameter. Do you want to add option parameter to existing function `verifyX509CertificateChain` and just pass nil in existing call sites. Its called from one place only.

```
func builtinCryptoX509ParseAndVerifyCertificatesWithOptions(_ BuiltinContext, operands []*ast.Term, iter func(*ast.Term) error) error {

	options, err := builtins.ObjectOperand(operands[0].Value, 1)
	if err != nil {
		return err
	}

	type verifyOptions struct {
		DNSName                  string
		CurrentTime              time.Time
		KeyUsages                []x509.ExtKeyUsage
		MaxConstraintComparisons int
	}

	var verifyOpt verifyOptions

	// Collect the cert verification options. this code will be moved to function like collectVerifyOptions..
	for _, key := range options.Keys() {
		switch t := options.Get(key).Value.(type) {
		case ast.String:
			if key.Value.String() == "DNSName" {
				verifyOpt.DNSName = t.String()
			}
		case ast.Number:
			switch key.Value.String() {
			case "CurrentTime":
				currTime, err := strconv.ParseInt(t.String(), 10, 64)
				if err != nil {
					return err
				}
				if currTime < 0 {
					return fmt.Errorf("CurrentTime %d can not be less than 0.", currTime)
				}
				verifyOpt.CurrentTime = time.UnixMilli(currTime)
			case "MaxConstraintComparisons":
				maxComparisons, err := strconv.Atoi(t.String())
				if err != nil {
					return err
				}
				if maxComparisons < 0 {
					return fmt.Errorf("MaxConstraintComparisons %d can not be less than 0.", maxComparisons)
				}
				verifyOpt.MaxConstraintComparisons = maxComparisons
			}
		case ast.Set:
			fmt.Println("Set  ", key.Value, t.String())
			t.Foreach(func(t *ast.Term) {
				// Collect the x509.ExtKeyUsage values in a list by looking up the
				// mapping of key usage strings to x509.ExtKeyUsage
			})

		}
	}

	verifyX509CertificateChainWithOptions(certs, verifyOpt)

	return ...
}
```

**Comment by ashutosh-narkar** [comment]
@yogisinha it's difficult to give feedback this way. I would recommend you open a draft PR and folks can chime in. Thanks.

**Comment by yogisinha** [comment]
@ashutosh-narkar  I created a Draft PR for this .  https://github.com/open-policy-agent/opa/pull/6583
Let me know your feedback. Sorry for the delay. I got sick for sometime in new year.
