### ISSUE TITLE
partial eval: invalidate cache when data changes

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#589]
The OPA server should invalidate the partial evaluation cache whenever data changes. In the short term it would be acceptable to invalidate on ANY data change. In the future, we should use the dependency analysis implementation to perform more fine-grained invalidation.

**Comment by srenatus** [comment]
> In the future, we should use the dependency analysis implementation to perform more fine-grained invalidation.

@tsandall Is this still on the table? 😃 (Just curious, really, no immediate needs)
