### ISSUE TITLE
AWS KMS support for OAuth2 Client Credentials JWT authentication

### ISSUE THREAD

**Issue by prasanthu** [open-policy-agent/opa#5892]
## What is the underlying problem you're trying to solve?
We would like to add support for AWS KMS keys to sign the client assertions used in OAuth2 Client Credentials JWT authentication. The current implementation signs the assertions using the `signing_key.private_key` value specified in the configuration. KMS keys or the private portion of an asymmetric KMS key cannot be exported in plain text from the HSMs. AWS KMS only allows to sign data using the [signing API](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html). The keyID, algorithm and the message(or digest) are the only parameters required for this API. This helps in improving the security of services using OPA.

## Describe the ideal solution
The `signing_key` configuration could support additional parameters for specifying keyId and cloud vendor. We can add support for signing using KMS in `oauth2ClientCredentialsAuthPlugin` [here](https://github.com/open-policy-agent/opa/blob/main/plugins/rest/auth.go#L174).
This will require changes in the way plugin uses `jws.SignLiteral` for [signing assertions](https://github.com/open-policy-agent/opa/blob/main/plugins/rest/auth.go#L241).

## Describe a "Good Enough" solution
We could add new plugin like `oauth2ClientCredentialsAuthPlugin` which supports only AWS KMS.

### Generating base64 encoded signature
When used with the ECDSA_SHA_256, ECDSA_SHA_384, or ECDSA_SHA_512 signing algorithms, the signature value is a DER-encoded object as defined by ANS X9.62–2005 and [RFC 3279 Section 2.2.3](https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3).
This is the most commonly used signature format and is appropriate for most uses. We need to perform the following steps to convert the DER-encoded object to a valid signature

1) Retrieve `r` & `s` values from the encoded structure
2) Compute signature size based on algorithm and size of `r` and `s` values
3) Copy `r` and `s` values after adding necessary padding to signature
4) Convert signature bytes to base64 using URL encoding without padding

**Comment by ashutosh-narkar** [comment]
Extending `oauth2ClientCredentialsAuthPlugin` seems reasonable if we want to support this in OPA. If this is something you'd like to contribute, feel free to do so. We're happy to help.

**Comment by prasanthu** [comment]
Let me come up with some code & we can discuss more in detail.

**Comment by ashutosh-narkar** [comment]
Just glanced at the code, it looks fine. Thanks for looking into this. I did see we pull in new deps, can we do w/o it or do we need to pull all of them in?

**Comment by prasanthu** [comment]
I  am calling AWS KMS API to sign the digest. https://docs.aws.amazon.com/sdk-for-go/api/service/kms/#KMS.Sign
Do you suggest any other alternatives for calling AWS APIs

**Comment by ashutosh-narkar** [comment]
We have some AWS related code in [here](https://github.com/open-policy-agent/opa/tree/main/internal/providers/aws). The question is the code that you are pulling in self-contained enough that we don't need to import the entire library.

**Comment by prasanthu** [comment]
Sorry for the late response, was busy last week. I will check this code and see if we can use this

**Comment by prasanthu** [comment]
@ashutosh-narkar I have changed the implementation to use Signed AWS request instead of pulling in AWS go libraries: https://github.com/open-policy-agent/opa/commit/d5ed3fc1a708a306afd671214d20b12317567f55
Sample config.yaml: https://gist.github.com/prasanthu/16e5e668ea864487d44dd7e95ff0d34b

I have done some basic testing, it works as expected. 

Pls give feedback

**Comment by ashutosh-narkar** [comment]
This looks much better. Can you please open a draft PR so that we can give more feedback. Thanks for looking into this.

**Comment by ashutosh-narkar** [comment]
Closed via https://github.com/open-policy-agent/opa/pull/5942.
