### ISSUE TITLE
Add tracing support to opa-envoy-plugin

### ISSUE THREAD

**Issue by RmStorm** [open-policy-agent/opa#5903]
## What is the underlying problem you're trying to solve?

Traces work and are available for the regular http OPA but they do not seem to be implemented in the opa-envoy-plugin which uses a grpc server instead of the http one. It would be nice to have traces there as well!

## Describe the ideal solution

The tracing provider/propagator is configurable and listens to the same config as the regular OPA instance. Allowing the user to choose between Otel/Zipkin/Datadog whatever.

## Describe a "Good Enough" solution

Simply implement the option to turn on Otel tracing in the envoy-plugin just like in OPA itself.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/issues/4290 also tracks this. Thanks for working on it! 🎉

**Comment by RmStorm** [comment]
Ah I didn't see that issue, I searched for 'tracing' and variants of that but it didn't show up. The PR is ready for review by the way. I'm running a fork now to get traces in production hahaha. Would love to get the change upstream instead.
