### ISSUE TITLE
[opa-envoy-plugin] support for multi-valued HTTP header addition

### ISSUE THREAD

**Issue by Pushpalanka** [open-policy-agent/opa#5925]
## Short description 
Attempted the `headers` rule as described in https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-additional-controls, but for a multi-valued header addition.

Eg:
```
"headers": {
"x-header": ["x-header value1", "value2"]
},
```

## Expected behavior
When the rule is set as above I expected an HTTP header added with two values defined. This flow worked fine with one valued header, but when the 2nd value is added for the header, it failed.

## Additional context
I suspect it is due to [this code segment](https://github.com/open-policy-agent/opa-envoy-plugin/blob/20fd4cf72e801c2918976fb24584007648c36d46/envoyauth/response.go#L305), that it limits to add only one header value for the Key.
```func transformToHTTPHeaderFormat(input interface{}, result *http.Header) error {

	takeResponseHeaders := func(headers map[string]interface{}, targetHeaders *http.Header) error {
		for key, value := range headers {
			var headerVal string
			var ok bool
			if headerVal, ok = value.(string); !ok {
				return fmt.Errorf("type assertion error")
			}

			targetHeaders.Add(key, headerVal)
		}
		return nil
	}
```
It will be great to have support for the multi-valued HTTP headers.

**Comment by srenatus** [comment]
Thanks for the report! Sounds like a reasonable extension. :+1:

**Comment by ashutosh-narkar** [comment]
@Pushpalanka if you'd like to contribute this feature we're happy to help. Thanks!

**Comment by ashutosh-narkar** [comment]
Completed in https://github.com/open-policy-agent/opa-envoy-plugin/pull/419.
