### ISSUE TITLE
Improve virtual doc caching to handle undefined values

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#593]
Currently, if a virtual doc is undefined, that information is not cached during evaluation (whereas if it is defined, the value is cached.) To avoid recomputing the virtual doc and arriving at undefined, evaluation should cache the fact that the doc was undefined.

**Comment by tsandall** [comment]
Closing this for now as it's not needed. We can revisit this in the future if necessary.

**Comment by srenatus** [comment]
✔️ This has now been implemented, thanks to @edpaget. 🎉
