### ISSUE TITLE
CEL support

### ISSUE THREAD

**Issue by RealHarshThakur** [open-policy-agent/opa#5932]
## What is the underlying problem you're trying to solve?

[CEL](https://github.com/google/cel-spec/tree/master) is gaining a lot of traction. It would be really nice if OPA can execute CEL natively. 

## Describe the ideal solution

The end goal would be OPA being able to evaluate CEL as a first-class citizen

## Describe a "Good Enough" solution

Have an extension mechanism where we can compile CEL to the IR OPA understands 

## Additional Context

CEL supports more than just boolean but I think even starting with boolean might be a great start 
https://github.com/google/cel-spec/blob/master/doc/langdef.md#evaluation
From ref- https://openpolicyagent.slack.com/archives/CBR63TK2A/p1683889902232589

**Comment by anderseknert** [comment]
Hi @RealHarshThakur 👋 

There are many policy languages out there :) What's not clear to me from the description is what you consider the benefits would be for integrating another policy language in OPA, as opposed to simply using that policy language?

Adding another language to OPA seems like it'd add a huge maintenance burden to me, and asking new users to choose between different languages... I'm having a hard time seeing how we'd be able to provide a good developer experience around that.

**Comment by RealHarshThakur** [comment]
I think K8s adopting it is a huge win for CEL - https://kubernetes.io/docs/reference/using-api/cel/
IMO, I think CEL will most likely help OPA grow as they're a lot of people hesitant in writing Rego and looking for alternatives.

**Comment by anderseknert** [comment]
If you want an OPA-like experience for Kubernetes and use CEL at the same time, I believe Gatekeeper provides something to that end. 

I don't think this is a viable/desirable option for OPA itself, I'm afraid.

**Comment by ashutosh-narkar** [comment]
Closing this for now given the scope of work and maintenance cost. @RealHarshThakur if you'd like to work on this, feel free to create a project in the [contrib](https://github.com/open-policy-agent/contrib) repo and more discussions/feedback can be provided there. Thanks!
