### ISSUE TITLE
When running opa build with optimization enabled (-O 1) the bundle that is generated is missing a level in the path to the rego file

### ISSUE THREAD

**Issue by deezkay** [open-policy-agent/opa#5933]
## Short description 
When running opa build with optimization enabled (-O 1) the bundle that is generated is missing a level in the path of the rego file.

For example
When generating a bundle without optimization I get the following bundle generated:-
```
# opa build -b data/c1/ -o data/c1.tar.gz
# tar tzf data/c1.tar.gz
tar: Removing leading `/' from member names
/data.json
/data/c1/c1.rego
/.manifest
```

When generating a bundle from the exact same rego and manifest files but with optimization enabled I get the following bundle generated:-
```
# opa build -b data/c1/ -o data/c1.tar.gz -O 1 -e c1/test
# tar tzf data/c1.tar.gz
tar: Removing leading `/' from member names
/data.json
/optimized/c1.rego
/.manifest
```

Note the difference in the rego file path in each case - missing a level of the path.

The missing level in the path is causing "Bundle activation failed: detected overlapping roots in bundle manifest" errors when multiple bundles are loaded.

## Steps To Reproduce
The following shows the example rego and manifest files to generate 2 bundles. The first steps show a non optimized opa bundle statement and the bundles generated. This output works as expected when the 2 bundles are loaded in OPA.
```
# tree -a data
data
├── c1
│   ├── .manifest
│   └── c1.rego
└── c2
    ├── .manifest
    └── c2.rego

# cat data/c1/c1.rego
package c1

test = result {
        input.X == "Y"
        result := {"condition":"test match"}
}
# cat data/c1/.manifest
{
        "roots": [
                "c1"
        ]
}
# cat data/c2/c2.rego
package c2

test = result {
        input.X == "Y"
        result := {"condition":"test match"}
}
# cat data/c1/.manifest
{
        "roots": [
                "c2"
        ]
}

# opa build -b data/c1/ -o data/c1.tar.gz
# tar tzf data/c1.tar.gz
tar: Removing leading `/' from member names
/data.json
/data/c1/c1.rego
/.manifest

# opa build -b data/c2/ -o data/c2.tar.gz
# tar tzf data/c2.tar.gz
tar: Removing leading `/' from member names
/data.json
/data/c2/c2.rego
/.manifest

# opa run -s -c config.yaml --addr localhost:8181
{"addrs":["localhost:8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-05-19T12:11:31+01:00"}
{"level":"warning","msg":"OPA running with uid or gid 0. Running OPA with root privileges is not recommended.","time":"2023-05-19T12:11:31+01:00"}
{"level":"info","msg":"Starting bundle loader.","name":"c2","plugin":"bundle","time":"2023-05-19T12:11:32+01:00"}
{"level":"info","msg":"Starting bundle loader.","name":"c1","plugin":"bundle","time":"2023-05-19T12:11:32+01:00"}
{"level":"info","msg":"Discovery update processed successfully. Etag updated to \"5f7313d82a223d5f1b2e0ba9f9421428\".","plugin":"discovery","time":"2023-05-19T12:11:32+01:00"}
{"level":"info","msg":"Bundle loaded and activated successfully. Etag updated to \"938472da02b9ada83f4c8f6ad7060505\".","name":"c2","plugin":"bundle","time":"2023-05-19T12:11:32+01:00"}
{"level":"info","msg":"Bundle loaded and activated successfully. Etag updated to \"c2e7d710ef700a6a76ac8a0a2e7dc7ea\".","name":"c1","plugin":"bundle","time":"2023-05-19T12:11:33+01:00"}
```

Then the following shows the steps with the optimized opa build statements to generate the 2 bundles. In this case the generated bundles contain the incorrect path to the rego file in each case, and when these bundles are loaded into OPA it produces the "Bundle activation failed: detected overlapping roots in bundle manifest" error when the 2nd bundle is loaded.

```
# opa build -b data/c1/ -o data/c1.tar.gz -O 1 -e c1/test
# tar tzf data/c1.tar.gz
tar: Removing leading `/' from member names
/data.json
/optimized/c1.rego
/.manifest

# opa build -b data/c2/ -o data/c2.tar.gz -O 1 -e c2/test
# tar tzf data/c2.tar.gz
tar: Removing leading `/' from member names
/data.json
/optimized/c2.rego
/.manifest

# opa run -s -c config.yaml --addr localhost:8181
{"addrs":["localhost:8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-05-19T12:17:33+01:00"}
{"level":"warning","msg":"OPA running with uid or gid 0. Running OPA with root privileges is not recommended.","time":"2023-05-19T12:17:33+01:00"}
{"level":"info","msg":"Starting bundle loader.","name":"c1","plugin":"bundle","time":"2023-05-19T12:17:34+01:00"}
{"level":"info","msg":"Starting bundle loader.","name":"c2","plugin":"bundle","time":"2023-05-19T12:17:34+01:00"}
{"level":"info","msg":"Discovery update processed successfully. Etag updated to \"e7b4b6fca8853afe97bac788f06d8ff3\".","plugin":"discovery","time":"2023-05-19T12:17:34+01:00"}
{"level":"info","msg":"Bundle loaded and activated successfully. Etag updated to \"587167cd191a3864f272bc2d343da514\".","name":"c1","plugin":"bundle","time":"2023-05-19T12:17:34+01:00"}
{"level":"error","msg":"Bundle activation failed: detected overlapping roots in bundle manifest with: [c1]","name":"c2","plugin":"bundle","time":"2023-05-19T12:17:35+01:00"}
```

## Expected behavior
The generated optimized bundle should look like the below (note the additional level in the /optimized path)
```
/data.json
/optimized/c1/c1.rego
/.manifest
```

## Additional context
OPA version output
```
Version: 0.52.0
Build Commit: 8d2c137662560cac83d9cf24cbdaecc934910333
Build Timestamp: 2023-04-27T17:57:23Z
Build Hostname: 8005d0be4a4c
Go Version: go1.20.3
Platform: linux/amd64
WebAssembly: unavailable`
```

**Comment by ashutosh-narkar** [comment]
@deezkay if you open the two optimized bundles you'll notice that their manifests have changed.  A extra `partial` root has been added to them. So now when you load these 2 bundles together, OPA gives an overlapping roots error. One way you could resolve this is by having a single manifest at the top level (ie. the `data` folder).

**Comment by deezkay** [comment]
Thanks @ashutosh-narkar.
Yes as you say I can see that opa build with optimization enabled has modified the original .manifest file I created and appended the partial root so that the version inside the tarball bundle now appears as follows
```
cat .manifest
{"revision":"","roots":["c1","partial"]}
```
I can see where the collision would occur when the c2 bundle is loaded because its .manifest file also contains the partial root.

So my question is, I want to load multiple bundles (a requirement of my OPA deployment) created using opa build with optimization - how can I achieve this if each .manifest files included inside each bundle is modified by opa build to contain the partial root?

**Comment by ashutosh-narkar** [comment]
@deezkay currently I don't think you'll be able to load multiple optimized bundles in OPA. If possible at the moment, you'll need to provide a single optimized bundle.

**Comment by anderseknert** [comment]
That's the issue being reported here, @ashutosh-narkar. There's nothing in the docs that would suggest that the optimization level of the build command should impact how the OPA server operates, and I would not expect anyone to come to that conclusion by reasoning about it.

**Comment by ashutosh-narkar** [comment]
Correct. We need to look into how to make this work with optimized bundles.
