### ISSUE TITLE
Add ability to add a custom message when returning system.authz policy

### ISSUE THREAD

**Issue by TheLunaticScripter** [open-policy-agent/opa#5938]
I have a system.authz policy that is doing some certificate verification when calling OPA. Currently, when we make the call and a certificate is not included opa is just returning the 403. It would be nice to be able to provide a more descriptive message as part of the return so that we can provide more self-service.

**Comment by ashutosh-narkar** [comment]
The authorization policies can return object responses as follows. Would this work for your use-case?

```rego
package system.authz

default allow := {
    "allowed": false,
    "reason": "unauthorized resource access"
}

allow := { "allowed": true } {   # Allow request if...
    "secret" == input.identity  # identity is the secret root key.
}

allow := { "allowed": false, "reason": reason } {
    not input.identity
    reason := "no identity provided"
}
```

**Comment by anderseknert** [comment]
What @ashutosh-narkar suggested should be the right course of action. Can re-open later if we missed something, but don't think there's more to do here right now.
