### ISSUE TITLE
Mock external_data function from Gatekeeper

### ISSUE THREAD

**Issue by fardin01** [open-policy-agent/opa#5956]
## Short description 
I understand it is possible to [mock functions](https://www.openpolicyagent.org/docs/latest/policy-testing/#data-and-function-mocking) in OPA tests. I want to write some tests for Rego policies that we use in Gatekeeper which happen to use the `external_data` function. I've tried to mock this function:
```rego
package team

violation[{"msg": msg}] {
	resp = external_data({"provider": "team", "keys": ["some-team"]})
	# Response format is {"errors": [], "responses": [["some-team", false]], "status_code": 200, "system_error": ""}
	not resp.responses[0][1]
	msg := sprintf("Not a valid team.", [])
}
```

```rego
package team_test

import data.team.violation
import future.keywords

mock_external_data(x) := {"errors": [], "responses": [["some-team", false]], "status_code": 200, "system_error": ""}

test_violation {
    violation with external_data as mock_external_data
}
```
The above code produces:
```
team_test.rego:9: rego_type_error: with keyword target must reference existing input, data, or a function
```
Is the problem with how I'm declaring the `mock_external_data`? Is there some way to register my own custom function at OPA runtime?

I would appreciate some help on how to fix this.

## Steps To Reproduce
`opa test team.rego team_test.rego`

**Comment by ashutosh-narkar** [comment]
One option I can think of is you create a [custom builtin](https://www.openpolicyagent.org/docs/latest/extensions/#custom-built-in-functions-in-go) to extend OPA, then create a capabilities.json with your builtin added and finally use the `--capabilities` flag on the `opa test` command to specify your created capabilities file.

**Comment by anderseknert** [comment]
Provided that you're mocking the function, you shouldn't need to create a custom function or otherwise modify OPA's code. Just download the [capabilities.json](https://raw.githubusercontent.com/open-policy-agent/opa/main/capabilities.json) file from the version of OPA you want to target, and then add `external_data` to the list:

```
{
  "builtins": [
    {
      "name": "external_data",
      "decl": {
        "args": [
          {
            "type": "object"
          }
        ],
        "result": {
          "type": "object"
        },
        "type": "function"
      }
    },
    # more functions here..
```

Policy could then look something like this (overly simplified) example:

```rego
package p

mock_external_data(o) := {}

x := external_data({})

test_external_data {
    x == {} with external_data as mock_external_data
}
```

```shell
opa test --capabilities capabilities.json .
PASS: 1/1
```

**Comment by fardin01** [comment]
Thank you very much @anderseknert. This actually covered my use case.
