### ISSUE TITLE
object.subset method fails to correctly determine whether two arrays are in a parent-child relationship.

### ISSUE THREAD

**Issue by DCRUNNN** [open-policy-agent/opa#5968]
## Short description 
The object.subset method seems to have a bug when determining whether two arrays are in a parent-child relationship. Here is an example:

## Steps To Reproduce
rego file：
```
array1 := [1,2,3,4,5]
array2 := [6,7,8]
object.subset(array1, array2)
```
expect：false
got：true

you can run the example above on the [playground](https://play.openpolicyagent.org/p/sGQCzMslCk)

## Additional context
This seems to be caused by line 201 in the file https://github.com/open-policy-agent/opa/blob/main/topdown/subset.go. 

I have written a custom function locally to determine whether two arrays are in a parent-child relationship, and modifying it as superElem := super.Elem(superCursor + subCursor) can solve the issue. 

This is the information regarding this problem. Please review it, and I will submit a PR later.

**Comment by anderseknert** [comment]
Nice! Thanks @DCRUNNN 👍 

Fixed in https://github.com/open-policy-agent/opa/pull/5969
