### ISSUE TITLE
Remove Wealthsimple as an OPA adopter

### ISSUE THREAD

**Issue by hannahyeates** [open-policy-agent/opa#5982]
### Organization Name

Wealthsimple

### Organization Website

https://www.wealthsimple.com/en-ca

### How is your organization using OPA?

OPA didn't end up working out for us as an authorization platform, so I would like to request that we are removed from the list of adopters.

### Update entry

- [X] Check this box if you want to update an existing entry.

**Comment by ashutosh-narkar** [comment]
@hannahyeates can you please submit a PR?  Also if you'd like to discuss your use-case, or suggest improvements that would have helped in OPA adoption feel free to create an [issue](https://github.com/open-policy-agent/opa/issues), [discussion](https://github.com/orgs/open-policy-agent/discussions) or post on Slack. Thanks for the consideration.
