### ISSUE TITLE
OPA SDK fails 'go mod tidy' for applications depending on go.opentelemetry.io/otel v1.16.0

### ISSUE THREAD

**Issue by ghaskins** [open-policy-agent/opa#6003]
## Short description 

Golang applications that depend on both:

* go.opentelemetry.io/otel v1.16.0
* github.com/open-policy-agent/opa v0.53.1

will fail with 'go mod tidy'.  I believe this is due to the transitive dependency on otel v1.14.0 in OPA.

**Comment by ghaskins** [comment]
Reference: https://github.com/temporalio/temporal/pull/4481

**Comment by srenatus** [comment]
There's no use fighting it, I guess. Let's get #6004 over the line.
