### ISSUE TITLE
Add support for passing custom result AST parsers

### ISSUE THREAD

**Issue by mcguiresm** [open-policy-agent/opa#6035]
## What is the underlying problem you're trying to solve?

By adding the support for passing custom result AST parsers, users that are able to reason about their data can make decisions in the parser to improve performance. In our implementation, we were able to bench a 10x increase over using `ast.ParseTerm()` 

## Describe the ideal solution

The ideal scenario would to allow user's to pass in a custom result AST parser in `rego/rego.go`, that if not supplied would fallback to `ast.ParseTerm()`.

For example: 
```go
func parseQuery(ctx context.Context, txn storage.Transaction, q string) (rego.PreparedEvalQuery, error) {
	r := rego.New(
		rego.Transaction(txn),
		// Other setup
		rego.ParseResultAST(parseResultAST),
	)

	return r.PrepareForEval(ctx)
}

func parseResultAST(s string) (*ast.Term, error) {
     // Implementation 
}
```

**Comment by tsandall** [comment]
@mcguiresm have you looked at [rego.GenerateJSON](https://pkg.go.dev/github.com/open-policy-agent/opa/rego#GenerateJSON)? Does it fit your use case?

**Comment by ashutosh-narkar** [comment]
Closing this for now. If using [rego.GenerateJSON](https://pkg.go.dev/github.com/open-policy-agent/opa/rego#GenerateJSON) does not resolve your use-case, feel free to re-open with more information.
