### ISSUE TITLE
Update to glibc-dynamic image

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#6037]
cc-dynamic has been deprecated: https://github.com/chainguard-images/images/blame/main/images/cc-dynamic/README.md#L23

We need Chainguard to add a `-dev` variant before we can update. I have a PR open here: https://github.com/chainguard-images/images/pull/894

**Comment by ashutosh-narkar** [comment]
Thanks for follow-up @charlieegan3!

**Comment by charlieegan3** [comment]
I think that https://github.com/chainguard-images/images/pull/937 is also needed before we can update. 🕐
