### ISSUE TITLE
plugins/discovery: a lot of boot config which is still active post discovery is erased

### ISSUE THREAD

**Issue by blacksails** [open-policy-agent/opa#6046]
## Short description 

Discovery is erasing a lot of the boot config, when the config is not present in the discovery bundle. 

A few examples:
- `persistence_directory` set at boot but not in discovery bundle, causes the default for `persistence_directory` to be used for service bundle persistence, but the boot config is still active in the discovery plugin.
- The active configuration of the discovery plugin is not visible in `GET /v1/config` because discovery erases it upon activating the first bundle.

## Steps To Reproduce

1. Start OPA with `persistence_directory` and `discovery` configured
1. Don't set `persistence_directory` or `discovery` in the discovery bundle. But enable `bundle.[*].persist`.
1. Call `GET /v1/config` and verify that neither `persistence_directory` or `discovery` is present.
1. Verify that service bundles are persisted at the default `persistence_directory` and not what was set at boot. (fix #6042)

## Expected behavior

- Exempting configuration in discovery should not erase boot configuration. 
- `GET /v1/config` should show any active configuration, and not *just* what discovery returned. `persistence_directory` and `discovery` is still active in the context of the discovery plugin.
- `persistence_directory` should either 
  - be split into two configuration points, discovery bundles and service bundles. Where only the one for service bundles is able to be overridden in discovery.
  - not be able to be overridden in discovery

## Additional context

PR #6042 partly addresses this with regards to `persistence_directory`

**Comment by ashutosh-narkar** [comment]
`GET /v1/config` returns whatever config is currently stored on the plugin manager.

If you run `opa run -s` and then run `curl localhost:8181/v1/config | jq .` the output is

```json
{
  "result": {
    "default_authorization_decision": "/system/authz/allow",
    "default_decision": "/system/main",
    "labels": {
      "id": "3c18ebba-3f7b-4097-b83d-5941bbb24ae2",
      "version": "0.53.1"
    }
  }
}
```

In the above output the `persistence_directory` field is missing. That's probably because we're not setting it [here](https://sourcegraph.com/github.com/open-policy-agent/opa@7c39ef5e8765c7c4979a4a0fb7ab699e08c36840/-/blob/config/config.go?L99). What other fields in the active config are missing?

**Comment by blacksails** [comment]
> What other fields in the active config are missing?

`discovery`

**Comment by ashutosh-narkar** [comment]
In [here](https://sourcegraph.com/github.com/open-policy-agent/opa@d310c4335ce6533f99b1b9f1279ecc16495432ab/-/blob/plugins/discovery/discovery.go?L383) we don't set the discovery config while reconfiguring the manager. If we did that, we should have the discovery config presented in the active config I think.

**Comment by blacksails** [comment]
@ashutosh-narkar exactly. That is what I initially also had in #6042 but I removed it again to keep the PR focused. Wouldn't it make sense to have discovery in the active config? If you think so I will do a PR more on that later today.

**Comment by ashutosh-narkar** [comment]
Makes sense to have it. Thanks for looking into this.

**Comment by ashutosh-narkar** [comment]
Fixed in https://github.com/open-policy-agent/opa/pull/6070.
