### ISSUE TITLE
Tabs in strings renders non-obvious error message

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6068]
Placing an actual tab character (and not `\t`) in a regular string [results](https://play.openpolicyagent.org/p/zFftyuc6Ca) in a non-obvious and hard to debug error message.

```rego
foo := "	foo"
```

```shell
1 error occurred: policy.rego:3: rego_parse_error: unexpected assign token: expected rule value term (e.g., foo := <VALUE> { ... })
	foo := "	foo"
	    ^
```

Whether this should be allowed or not, I don't know. But it's obviously not the assign token that's an issue here, so if this should be an error it should at least be reported accurately.

What does work:

```rego
foo := "\tfoo"
foo := `	foo`
```

**Comment by srenatus** [comment]
Another variant of this, I suppose: https://github.com/open-policy-agent/opa/issues/1129

**Comment by anderseknert** [comment]
🙂 Yeah, somewhat related!

Further research says that the tab character must be escaped as else it would not be a valid JSON value. So it's correct to flag this as an error. The error message should say something like "illegal tab character in string — use escape character \t instead".

**Comment by anderseknert** [comment]
This is a side effect of #6563, but I had no idea about that when I created this issue. Closing this, but hoping that the main issue is prioritized soon as it's making our error messages useless in so many places where they shouldn't be.

Replacing the `:=` with `=` in the first example will have OPA return an error message relevant to the error.

```
2 errors occurred:
policy.rego:5: rego_parse_error: illegal string literal: "	foo"
	foo = "	foo"
```
