### ISSUE TITLE
compile: add WithRoots compiler option

### ISSUE THREAD

**Issue by kubaj** [open-policy-agent/opa#6085]
## What is the underlying problem you're trying to solve?

I'd like to build an OPA bundle from Go using the compile API (github.com/open-policy-agent/opa/compile) but it's missing the support for providing bundle roots. I've tried to find some workaround for this, but I wasn't successful.

## Describe the ideal solution

Ideal situation would be that Go compile API has the same options when building OPA bundles as the OPA CLI's `build` command.

## Describe a "Good Enough" solution

Adding `WithRoots` compiler option used for specifying bundle's roots.

**Comment by kubaj** [comment]
I've tried this combination but based on error I've got:

```
load error: bundle policy.rego: bundle read failed: archive read failed: gzip: invalid header"
```

it looked that this option is used when you want to use the content of the already existing bundle to build the bundle. (e.g. combine multiple bundles together).

**Comment by ashutosh-narkar** [comment]
Let's say you have a folder with your policy, data and manifest file. Are you saying if you set `WithPaths` to point to that with bundle mode enabled, you get an error?
 
Adding a `WithRoots` option seems fine btw. If you'd like to contribute that would be great!
