### ISSUE TITLE
Add support for DELETE method in v1/data API

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#609]
The OPA v1/data API supports deletion/removal of data via JSON Patch, however, in some cases, it's easier to call v1/data with DELETE instead of crafting the JSON Patch. For example:

Instead of:

```
PATCH /v1/data/foo

[
  {"op": "remove", "path": "bar/baz"}
]
```

Callers would:

```
DELETE /v1/data/foo/bar/baz
```

The implementation should be relatively straightforward:

* Add a new v1DataDelete function to handle DELETE calls
  * Open a write txn
  * Call `storage.Store#Write(remove, <path>, nil)`
  * Commit txn on success (or Abort on error)
* Register handler with the others
* Update rest-api.md with docs on DELETE support (copying format from other sections)

**Comment by repenno** [comment]
I will take care of this one. I have interest on having ti working (;-)
