### ISSUE TITLE
Extend type checking of input in system.* policies

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6109]
Since the schema for `input` is known for these packages (authentication policy, decision log masking, etc), it would be a nice touch if we automatically provided their schemas to the compiler, so that e.g. typos, or incorrect attributes or types would be caught automatically .

```rego
package system.authz

allow {
	input.identty == "foo" 
}
```

This should be a compile time error, since there can never be a `identty` attribute in the input to `system.authz`, and so on.

**Comment by ashutosh-narkar** [comment]
Given a policy like 

```rego
package system.authz

allow {
	input.identty == "foo" 
}
```

We'd internally rewrite it to something like 

```rego
# METADATA
# schemas:
#   - input: schema.input
package system.authz

allow {
	input.identty == "foo" 
}
```

Then compile this modified policy with the known schema. Is this what you were thinking or do we expect the user to already have the metadata in their authz policy? I would think no but WDYT?

**Comment by ashutosh-narkar** [comment]
The problem with this is that the line numbers for errors will be reported per the internally updated policy and not match up with the original. So I think we'll need to pass that metadata to the compiler w/o changing the original policy.

**Comment by anderseknert** [comment]
Yeah... rather than rewriting the policy, I wonder if we could just allow a programmatic override for schema(s) that should be applied for the input/data in an evaluation? Another use case for that is in Regal, where authors of custom rules currently must add a package-level annotation to their custom rules, like:

```rego
# METADATA
# schemas:
#   - input: schema.regal.ast
package custom.regal.rules.naming["acme-corp-package"]
```

The schema for the `input` is going to be the same for all of rules starting with `custom.regal.*`, so demanding that users provide it in each file just seems... redundant, error prone, and easy to forget about. The argument against doing it automatically for known input/data would be that it's "magic" I suppose... but honestly, it's probably less magic to fail at compile time with a clear explanation than to fail at runtime without one? 

I think you could do this already by parsing another file/string with a subpackage annotation, like:

```rego
# METADATA
# scope: subpackages
# schemas:
#   - input: schema.input.authz
package system.authz
```

This works, but a problem with this approach, I think... is that it'll be conflict when someone is using bundles and they define "system" as a path being owned by their bundle. So we'd either need a way to work around that, or allow a programmatic solution to apply schemas without taking this ownership into accoiunt.

**Comment by ashutosh-narkar** [comment]
Schema verification for OPA's authorization policy input document was addressed in https://github.com/open-policy-agent/opa/pull/6141.

**Comment by anderseknert** [comment]
It's fine to close this for me then, @ashutosh-narkar .. or do you think we should do more here?

**Comment by ashutosh-narkar** [comment]
We can close this. If we think we need more checks we can always re-open.
