### ISSUE TITLE
How to call the custom function defined inside another rego 

### ISSUE THREAD

**Issue by jiangduzi** [open-policy-agent/opa#6111]
### Discussed in https://github.com/orgs/open-policy-agent/discussions/472

<div type='discussions-op-text'>

<sup>Originally posted by **jiangduzi** July 21, 2023</sup>
Need help, I want to reference different rego files in main.rego based on input.name. Then call custom functions defined inside that rego file but getting errors during compilation "rego_compile_error: called function policy.test shadowed".
My rego just like this:

**main.rego**

```rego
package play
import data.play.policies

allow {
    policy := policies[input.name]
    policy.test(input.params)
}
```

**policy1.rego**

```rego
package play.policies.policy1

test(params) {
    params["env"] == "dev"
}
```

**policy2.rego**

```rego
package play.policies.policy2

test(params) {
    params["env"] == "prod"
}
```

**Comment by ashutosh-narkar** [comment]
Closing as this is addressed [here](https://github.com/orgs/open-policy-agent/discussions/472).
