### ISSUE TITLE
opa run plan.json gives me the error  load error: 1 error occurred during loading: plan.json: invalid character 'ÿ' looking for beginning of value

### ISSUE THREAD

**Issue by Blueposey** [open-policy-agent/opa#6113]
## Short description 

example data[keys]

but instead I get the error 
  load error: 1 error occurred during loading: plan.json: invalid character 'ÿ' looking for beginning of value

**Comment by srenatus** [comment]
What are you trying to do? Please elaborate.

OPA cannot run plan files. Also, if you want to load JSON, you'd do it via `opa eval --data file.json`.

**Comment by ashutosh-narkar** [comment]
@Blueposey as mentioned [here](https://github.com/open-policy-agent/opa/issues/6096#issuecomment-1636518209), please provide the relevant details to repro the issue or elaborate your issue as Stephan mentioned. Closing this one. Feel free to re-open or create a new issue with the relevant details. Thanks!
