### ISSUE TITLE
Bundle paths should assume file:// protocol if none is specified

### ISSUE THREAD

**Issue by charlesdaniels** [open-policy-agent/opa#6114]
## What is the underlying problem you're trying to solve?

Create an OPA configuration file which uses a local bundle tarball.

## Describe the ideal solution

When a bundle is specified in the `bundles:` section of the config file, and a local file path is specified, it should be silently treated as if the `file://` protocol was used.

## Describe a "Good Enough" solution

This problem can be worked around today by manually inserted `file://`, although this does mean a fully qualified path needs to be used.

## Additional Context

`filedefault.tgz` could be any valid bundle.

```plain
$ ls
broken.yaml     filedefault.tgz works.yaml
$ cat broken.yaml
services:
  dummy: {}
bundles:
  bundle:
    service: dummy
    resource: "/Users/cad/f/tmp/filedefault/filedefault.tgz"

$ cat works.yaml
services:
  dummy: {}
bundles:
  bundle:
    service: dummy
    resource: "file:///Users/cad/f/tmp/filedefault/filedefault.tgz"
$ timeout 5s opa run -s -c ./broken.yaml
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-07-21T15:08:39-04:00"}
{"level":"info","msg":"Starting bundle loader.","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:39-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:39-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:39-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:39-04:00"}
{"current_version":"0.48.0","download_opa":"https://openpolicyagent.org/downloads/v0.54.0/opa_darwin_arm64","latest_version":"0.54.0","level":"info","msg":"OPA is out of date.","release_notes":"https://github.com/open-policy-agent/opa/releases/tag/v0.54.0","time":"2023-07-21T15:08:39-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:39-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:40-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:40-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:42-04:00"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"/Users/cad/f/tmp/filedefault/filedefault.tgz\": unsupported protocol scheme \"\"","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:43-04:00"}
{"level":"info","msg":"Shutting down...","time":"2023-07-21T15:08:44-04:00"}
{"level":"info","msg":"Server shutdown.","time":"2023-07-21T15:08:44-04:00"}
{"level":"info","msg":"Stopping bundle loader.","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:44-04:00"}
$ timeout 5s opa run -s -c ./works.yaml
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-07-21T15:08:50-04:00"}
{"level":"info","msg":"Starting bundle loader.","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:50-04:00"}
{"level":"info","msg":"Bundle loaded and activated successfully.","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:50-04:00"}
{"current_version":"0.48.0","download_opa":"https://openpolicyagent.org/downloads/v0.54.0/opa_darwin_arm64","latest_version":"0.54.0","level":"info","msg":"OPA is out of date.","release_notes":"https://github.com/open-policy-agent/opa/releases/tag/v0.54.0","time":"2023-07-21T15:08:50-04:00"}
{"level":"info","msg":"Shutting down...","time":"2023-07-21T15:08:55-04:00"}
{"level":"info","msg":"Server shutdown.","time":"2023-07-21T15:08:55-04:00"}
{"level":"info","msg":"Stopping bundle loader.","name":"bundle","plugin":"bundle","time":"2023-07-21T15:08:55-04:00"}
```

If the ideal solution was implemented, then both `broken.yaml` and `works.yaml` would work equally well.

```plain
$ opa version
Version: 0.48.0
Build Commit: 572e5c7ea0ed118900382908e7f1b68e1e665c04
Build Timestamp: 2023-01-09T16:07:13Z
Build Hostname: Mac-1673280730648.local
Go Version: go1.19.4
Platform: darwin/arm64
WebAssembly: unavailable
```

I see the same behavior in the current version of the SDK, I just happened to repro with this slightly older version of freestanding OPA.

---

If you are using the SDK and not the standalone binary, you might instead see messages formatted like this:

```plain
ERRO[0000] Bundle load failed: request failed: Get "/some/path/bundle.tgz": unsupported protocol scheme ""  name=bundle plugin=bundle
```

**Comment by ashutosh-narkar** [comment]
OPA assumes that if the `file` scheme is not explicitly provided, then the bundle needs to be downloaded from a remote source and hence initializes the http downloader. The relevant code is [here](https://github.com/open-policy-agent/opa/blob/main/plugins/bundle/plugin.go#L403). If OPA were to assume that the absence of `file://` in the bundle resource should be treated as a local file, this would be backward incompatible.

**Comment by charlesdaniels** [comment]
How would it break backwards-compatibility? The current behavior is that if `file` is not provided, then it throws an error and does not load the bundle. Presumably that means anyone with that type of config does not have a functioning setup.

**Comment by ashutosh-narkar** [comment]
You could probably check that an absence of the `file` scheme combined with a lack of a service config to imply that this is a local file.

**Comment by charlesdaniels** [comment]
I am admittedly unclear on how the service config works. Is there a situation where the users settings in the service section could cause a path that does not start with a schema to be a valid, fetch-able path?

**Comment by ashutosh-narkar** [comment]
Right if you specify a service then you don't need to specify a schema in the path. The `file` schema is treated special currently.

**Comment by charlesdaniels** [comment]
Oh I see. I wasn't aware of the interaction with the services thing. Honestly, making a special case for only when the services is missing seems like a footgun, because it means that the semantics of the path field change depending on some other component of the config changes. I could see someone using it with a local path, then later setting up a service and now it's fetching something totally different.

**Comment by ashutosh-narkar** [comment]
Good point. I was not recommending we do that for the same reason you mentioned.
