### ISSUE TITLE
OPA engine doesn't produce identical result if OPA engine is feed with normal bundles and with wasm bundles. 

### ISSUE THREAD

**Issue by rai-prashanna** [open-policy-agent/opa#6115]
Steps to replicate the bug. 

generate wasm bundle using /opa_linux_amd64_0.54 build -b . -t wasm
 /opa_linux_amd64_0.54 run bundle --server
curl -X POST --data-binary @test_input4.json 'http://localhost:8181/v1/data/authz/v1/policy'| jq

actual output from wasm bundle is 
{
  "result": {}
}

generate normal bundle using /opa_linux_amd64_0.54 build -b . 
 /opa_linux_amd64_0.54 run bundle --server
curl -X POST --data-binary @test_input4.json 'http://localhost:8181/v1/data/authz/v1/policy'| jq

actual output from normal bundle is 
{
  "result": {
    "allow": true
  }
}

**Comment by srenatus** [comment]
Please try to come to with some rego example to let us reproduce the problem. We're still left to guess too much to help out here.

**Comment by rai-prashanna** [comment]
The bundle containing wasm binary 
[wasm_bundle.tar.gz](https://github.com/open-policy-agent/opa/files/12135917/wasm_bundle.tar.gz)
The bundle containing  normal rego binary 
[normal_bundle.tar.gz](https://github.com/open-policy-agent/opa/files/12135918/normal_bundle.tar.gz)
my input json file used during rest api is as follows 
{
    "input":{
        "method": "GET",
        "resource": "BlueService",
        "roles": [
            "SystemModerator"
        ]
    }
}
curl -X POST --data-binary @test_inputdummy.json '[http://localhost:8181/v1/data/authz/policy'|](http://localhost:8181/v1/data/authz/policy'%7C)  jq
opa_linux_amd64_0.54 run -s normal_bundle.tar.gz
opa_linux_amd64_0.54 run -s wasm_bundle.tar.gz

The output from wasm bundle is as follows :
![image](https://github.com/open-policy-agent/opa/assets/21035884/9a11fddc-c9cc-4dd9-af4c-928eaffbe0ae)

The output from regobundle is as follows :
![image](https://github.com/open-policy-agent/opa/assets/21035884/2aaa77aa-9af2-4729-a23d-8402a50e7a98)

**Comment by srenatus** [comment]
When you've built the wasm bundle, have you checked that the entrypoint is `authz/policy/allow` and that that's the rule structure in the policy rego file?

**Comment by srenatus** [comment]
Also, please try with `opa run -s -b wasm-bundle.tgz`

**Comment by rai-prashanna** [comment]
Yes, I have annotated entrypoint into rego file. 
![image](https://github.com/open-policy-agent/opa/assets/21035884/b8da316a-df8a-421a-a8c4-06e3041c4ff9): 

The problem was solved when I added -b flag to opa engine.
