### ISSUE TITLE
`opa test --exit-zero-on-skipped` always returns exit code 0 when tests are skipped

### ISSUE THREAD

**Issue by fdaguin** [open-policy-agent/opa#6126]
## Short description

When launching `opa test` with `--exit-zero-on-skipped`, the exit code is 0 if a test both includes skipped and failed test rules.

## Steps To Reproduce

```bash
cat <<EOT > test.rego
package foo
test_pass { true }
test_fail { false }
todo_test_skip { true }
EOT
opa test --exit-zero-on-skipped test.rego
echo $?  # 0 but must be 2.
```

## Expected behavior

When launching `opa test` with `--exit-zero-on-skipped`, the exit code is 2 if a test both includes skipped and failed test rules.

**Comment by ashutosh-narkar** [comment]
Looks like the exit code is 0 with `--exit-zero-on-skipped` in a policy with no skipped test but does have a failed test.

```rego
package foo

test_pass { true }

test_fail { false }
```

```
$ opa test test.rego
test.rego:
data.foo.test_fail: FAIL (540.459µs)
--------------------------------------------------------------------------------
PASS: 1/2
FAIL: 1/2

$ echo $?
2
```

```
$ opa test --exit-zero-on-skipped test.rego
test.rego:
data.foo.test_fail: FAIL (77.667µs)
--------------------------------------------------------------------------------
PASS: 1/2
FAIL: 1/2

$ echo $?
0                  <---------- This should not be 0.
```

**Comment by fdaguin** [comment]
> Looks like the exit code is 0 with `--exit-zero-on-skipped` in a policy with no skipped test but does have a failed test.

Good catch! I added a test to cover this case in https://github.com/open-policy-agent/opa/pull/6127/commits/afddd691e9c483131626deb948d3a3ae912e76c5.
