### ISSUE TITLE
graph.reachable_paths sometimes returns nonsense paths

### ISSUE THREAD

**Issue by benweint** [open-policy-agent/opa#6128]
## Short description 

Sometimes, `graph.reachable_paths` will return paths that don't make any sense given the topology of the input graph. I've narrowed this down to a small, acyclic test case graph with 6 nodes, but I haven't been able to get a smaller test case yet.

## Steps to reproduce

I can reproduce in the OPA playground with OPA 0.55.0. Here's a [link](https://play.openpolicyagent.org/p/iqkx1Vyyz6) to a repro case.

Full text, for reference:

```
package play

g := {
  "a": ["b"],
  "b": ["c", "d", "e"],
  "c": ["e", "d"],
  "d": ["f"],
  "e": ["f"],
  "f": [],
}

all_paths := { p | p := graph.reachable_paths(g, {"a"})[_] }
```

Given this input, `all_paths` winds up producing:

```
[
    ["a", "b"],
    ["a", "b", "a", "b"],
    ["a", "b", "c", "d", "f"],
    ["a", "b", "c", "e", "f"]
]
``` 

... but note that `["a","b","a","b"]` is *not* a valid path given the input graph (because there is no edge from `b` to `a`). 

## Expected behavior

I would expect `all_paths` to only include paths representing valid traversals of the input graph.

**Comment by benweint** [comment]
Possibly related to #5871

**Comment by ashutosh-narkar** [comment]
Thanks for reporting this. Seems like a bug in the built-in. @benweint I'm closing this and we can keep track of any updates in https://github.com/open-policy-agent/opa/issues/5871.

**Comment by ashutosh-narkar** [comment]
If you'd like to work on this feel free to do so.
