### ISSUE TITLE
Rego.ResultSet.GetKey()

### ISSUE THREAD

**Issue by volck** [open-policy-agent/opa#6130]
## What is the underlying problem you're trying to solve?

While the `Allowed()` function is on a result set is nice, and allows us to directly interact with a decision, and we get a nice `bool` value back. However, if we use the following module;

```
package authz
x := 1
y := 5
ultimatequestion := "Answer to the Ultimate Question of Life, the Universe, and Everything"
```
with the query
 `data.authz`, and use the directions for integration the golang sdk with OPA, i.e. https://www.openpolicyagent.org/docs/latest/integration/#integrating-with-the-go-api, we still have to do some manual filtering on the expressions to get at the values. There should be a easier method that allow us to get the actual values from a lazy query directly. 

## Describe the ideal solution

A method, i.e. `getkey `or `getkey(s)` in which we can iterate a resultset and return valid data.

**Comment by srenatus** [comment]
Perhaps if you queried `v := data.authz[k]` instead, your bindings might be nicer to work with?
