### ISSUE TITLE
On the last day of month `time.add_date` counts months wrongly, instead uses x30 days

### ISSUE THREAD

**Issue by yemal** [open-policy-agent/opa#6131]
On the last day of a month `time.add_date` counts months wrongly, and instead uses x30 days.
It doesn't happen in the middle of the month though.

## Short description 

Tried different OPA versions including 0.53.1 and 0.55.0.

## Steps To Reproduce

```
❯ opa run
OPA 0.53.1 (commit , built at )

Run 'help' to see a list of commands and check for updates.

> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-07-31"), 0, -1, 0)))
"2023-07-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-07-31"), 0, -2, 0)))
"2023-05-31"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-07-31"), 0, -3, 0)))
"2023-05-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-07-31"), 0, -4, 0)))
"2023-03-31"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-07-31"), 0, -5, 0)))
"2023-03-03"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-07-31"), 0, -6, 0)))
"2023-01-31"
```
## Expected behavior

```
expect to have the last day of the month, as I'm deducting months, not 30 days
```
## Additional context

Any other day of a month (not the last one), seems to be working correctly:
```
❯ opa run
OPA 0.53.1 (commit , built at )

Run 'help' to see a list of commands and check for updates.

> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-08-01"), 0, -1, 0)))
"2023-07-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-08-01"), 0, -2, 0)))
"2023-06-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-08-01"), 0, -3, 0)))
"2023-05-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-08-01"), 0, -4, 0)))
"2023-04-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-08-01"), 0, -5, 0)))
"2023-03-01"
> sprintf("%d-%02d-%02d", time.date(time.add_date(time.parse_ns("2006-01-02","2023-08-01"), 0, -6, 0)))
"2023-02-01"
```

**Comment by anderseknert** [comment]
Hi there! That's an interesting observation, and one I hadn't encountered myself. For this command we're basically just deferring to Golang's [time.AddDate](https://pkg.go.dev/time#Time.AddDate) function, which comes with this interesting note:

> AddDate normalizes its result in the same way that Date does, so, for example, adding one month to October 31 yields December 1, the normalized form for November 31.

I would suspect that "normalization" is what you're seeing here. We probably can't change this behavior for an existing built-in function, but we could certainly add a similar note to the built-in reference in the OPA docs.

**Comment by charlieegan3** [comment]
The same issue can be seen in the golang function here: https://go.dev/play/p/XzN-jqm2mxl

I've opened https://github.com/open-policy-agent/opa/pull/6144 to better explain this functionality.
