### ISSUE TITLE
Search function in docs seems to have degraded, again

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6133]
Searching for "authentication" used to suggest the section on authentication/authorization of the OPA REST API. Similarly, searching for "annotations" would suggest that section in the docs, and so on. These now provide irrelevant suggestions :/ Not sure when this happened as I've been off for the last month.

**Comment by ashutosh-narkar** [comment]
@charlieegan3 may have an idea about this? We may need to see what the crawler is doing and maybe make some changes there. @charlieegan3 if you can take a look that would be great.

**Comment by anderseknert** [comment]
All of the search terms mentioned above now render the results I expected, so this seems to be "fixed" for the time being. Not satisfying at all not knowing what caused this though. Pure speculation, but could it be that there's a lag between a new release and the search index getting updated? Let's see what it looks like some time after the next release.

I'll close this for now but let's re-open immediately if we see this happening again.

**Comment by ashutosh-narkar** [comment]
> Pure speculation, but could it be that there's a lag between a new release and the search index getting updated?

The reindexing happens every Thursday. So the one that happened yesterday may explain this. We should probably trigger a reindex post a release to avoid the lag.

**Comment by anderseknert** [comment]
Ah, good to know! Yeah, if that was the core of this issue, we definitely should not tolerate a broken search feature for up to a week. Setting a reminder to get back to this by the end of the month.

**Comment by ashutosh-narkar** [comment]
We should also update the [release process docs](https://github.com/open-policy-agent/opa/blob/main/docs/devel/RELEASE.md) to add a note related to this.

**Comment by charlieegan3** [comment]
I've added a note to the release process docs about the crawler. https://github.com/open-policy-agent/opa/pull/6143, hope that looks ok.
