### ISSUE TITLE
[docs] Missing hint "future.keywords.if" for "Ordered (Else)"

### ISSUE THREAD

**Issue by keydon** [open-policy-agent/opa#6134]
## Short description 
the documentation of ["Ordered (Else)"](https://www.openpolicyagent.org/docs/latest/policy-reference/#ordered-else)
should also include that `import future.keywords.if` is needed, like many other places do.

## Steps To Reproduce

I was trying out the given example (slightly modified)
```
default a := 1
a := 5 if { 1 == 2 }
else := 10 if { 1 == 2 }
```

but I could not get it to work properly despite trying very hard :D
the funny thing is, there were no errors, but the output was unexpected :d
```
{
    "a": 5,
    "if": 10
}
```

my actual policy was way bigger of course, so it took me a while to spot the unexpected "if" in the result and then it finally clicked xD

## Expected behavior
Idealy one would get an error, but I guess there is none for backwards compatibility?
So at least a hint in the docs would be nice.

**Comment by ashutosh-narkar** [comment]
We could add a comment like below in the policy snippet. If you'd like to contribute that would be great!

```rego
# with `import future.keywords.if`
```

**Comment by Pushkarm029** [comment]
if no one is currently working on this issue, please assign me for this issue.
