### ISSUE TITLE
Partial object key rules contribute to static part of object type, but might not be defined at runtime

### ISSUE THREAD

**Issue by johanfylling** [open-policy-agent/opa#6138]
Running `opa check` on the following policy:

```rego
package test

main.allow := input.x

main[k] := v {
    k := input.k
    v := input.v
}

test_main {
    outcome := main with input as {"k": "foo", "v": "bar"}
    outcome == {"foo": "bar"}
}
```

will produce the following `rego_type_error`:

```
1 error occurred: policy.rego:12: rego_type_error: match error
	left  : object<allow: any>[any: any]
	right : object<foo: string>
```

The right-hand object should satisfy the type requirements of the dynamic type (`[any: any]`) of the left-hand object.

This can be reproduced in OPA `0.54.0`, but not in `0.53.1`, and might have been introduced by https://github.com/open-policy-agent/opa/issues/5972.

Note: The error is intermittent, so multiple executions might be required to produce the error (possibly related to [this](https://github.com/open-policy-agent/opa/issues/3729) bug).

**Comment by tsandall** [comment]
The type checker is working as expected here. The LHS includes a static property "allow" so the RHS will never match.

**Comment by anderseknert** [comment]
The error is intermittent, i.e. this compiles every 1 time out of 3 (or 10, or whatever) — so no matter what's expected this is a valid bug :) But good to know what _is_ expected.

**Comment by johanfylling** [comment]
In `test_main` of the example, `input.x` isn't defined, so at eval-time `outcome == {"foo": "bar"}` will hold true, with no defined `allow` property in `main`. I made the hasty assumption that the `any` type of `allow` also included it not being defined 😄.

I suppose something like `any<object[any: any], object<allow: any>[any: any]>` would be a more forgiving lhs type (?); but that'd grow pretty horribly the more known keys there are ..

**Comment by tsandall** [comment]
Updated the title to reflect that the issue is really about non-determinism as opposed to the type checker raising an error.

**Comment by johanfylling** [comment]
Is a viable course of action here to update type generation to merge all value types of contributing rules into the dynamic portion of the object type? e.g.:

```rego
package test

p[x] := y {
  x := 1
  y := 2
}

p.foo := "bar"

p.baz {
  input.x == 42
}
```
->
```
object[number: number, string: any<boolean, string>]
```
