### ISSUE TITLE
Update Developer Contributing Guide Link

### ISSUE THREAD

**Issue by Ronnie-personal** [open-policy-agent/opa#6146]
## Short description  
The document link at https://github.com/open-policy-agent/opa/blob/main/CONTRIBUTING.md points to the old version of the document.

## Steps To Reproduce
Contributing

Thanks for your interest in contributing to the Open Policy Agent (OPA) project!

Please refer to [OPA's contribution guidelines](https://www.openpolicyagent.org/docs/edge/contributing/) to find out how you can help.

## Expected behavior

Contributing

Thanks for your interest in contributing to the Open Policy Agent (OPA) project!

Please refer to [OPA's contribution guidelines](https://www.openpolicyagent.org/docs/latest/contributing/) to find out how you can help.

**Comment by anderseknert** [comment]
Thanks for reporting @Ronnie-personal 👍
