### ISSUE TITLE
Failing with rego_unsafe_var_error for a valid rego module

### ISSUE THREAD

**Issue by yadunandan004** [open-policy-agent/opa#6152]
## Short description 
So I ran this example from the envoy tutorial on my custom rego implementation. However, when I run it by calling Eval on the rego instance, i get rego_unsafe_var_error. 
Examples:

* OPA version: v0.55.0
* Language: Golang
* Example query, input, data, and policy that OPA was given
Rego Policy was found here: https://www.openpolicyagent.org/docs/latest/envoy-tutorial-standalone-envoy/
```
package authz

import future.keywords.if

import input.attributes.request.http as http_request

default allow := false

allow if {
        is_token_valid
        action_allowed
}

is_token_valid if {
        token.valid
        now := time.now_ns() / 1000000000
        token.payload.nbf <= now
        now < token.payload.exp
}

action_allowed if {
        http_request.method == "GET"
        token.payload.role == "guest"
        glob.match("/people", ["/"], http_request.path)
}

action_allowed if {
        http_request.method == "GET"
        token.payload.role == "admin"
        glob.match("/people", ["/"], http_request.path)
}

action_allowed if {
        http_request.method == "POST"
        token.payload.role == "admin"
        glob.match("/people", ["/"], http_request.path)
        lower(input.parsed_body.firstname) != base64url.decode(token.payload.sub)
}

token := {"valid": valid, "payload": payload} if {
        [_, encoded] := split(http_request.headers.authorization, " ")
        [valid, _, payload] := io.jwt.decode_verify(encoded, {"secret": "secret"})
}
```

Query: `authz.allow`
* Example output that OPA returned
Error:
`var authz is unsafe`
`var _ is unsafe`
* For server and CLI, the flags/configuration that you provided to OPA
* For server, any relevant log messages from OPA
* For Go and Wasm, the arguments you invoked OPA with
`go run main.go`

## Steps To Reproduce
A simple go program, which creates new rego instance, and later having called Eval, will reproduce this.

```
func main() {

	ctx := context.Background()


	r := rego.New(
		rego.Query("authz.allow"),
		rego.Module("policy.rego", <above policy>,
		))

	rs, err := r.Eval(ctx)
	if err!=nil{
		switch err := err.(type) {
		case ast.Errors:
			for _, e := range err {
				fmt.Println("error:", e.Message)
				fmt.Println("code:", e.Code)
				fmt.Println("row:", e.Location.Row)
				fmt.Println("filename:", e.Location.File)
			}
		default:
			// Some other error occurred.
		}
	}

	fmt.Println(rs.Allowed())


}
```

## Expected behavior
Evaluate to nil or any non erroneous behavior

## Additional context
Ran it on a custom implementation of envoy sidecar. Failed in that scenario. Then ran it on a singular go scratch file, shown above.

**Comment by anderseknert** [comment]
Your policy is valid, but I don't think your query is. Try changing it to `data.authz.allow`... and you might want to bind the result to a variable so that you can check the value of that binding in your code later, i.e. make the full query something like `x := data.authz.allow`.

**Comment by yadunandan004** [comment]
Missed data as the prefix for the query. My bad
