### ISSUE TITLE
Add a flag to optionally build without containerd dependency

### ISSUE THREAD

**Issue by slonka** [open-policy-agent/opa#6160]
## What is the underlying problem you're trying to solve?

Containerd frequently shows up on our security scans due to CVEs - https://osv.dev/list?page=2&q=containerd. In our case we don't use OCI download so it would be great if OPA could introduce a flag to build without containerd.

## Describe the ideal solution

I can run 

```
make GO_TAGS="-tags=no_oci" build
```

to build without containerd. And running 

```
go version -m opa_darwin_arm64  | grep containerd
```

shows no containerd included.

## Describe a "Good Enough" solution

Containerd is either included as a dependency or not, I don't think there is a "good enough" solution.

## Additional Context

Due to the frequency of CVEs reported in containerd the maintenance cost is higher. We would love to minimise that. I have created a [draft PR to show how it could be implemented.](https://github.com/open-policy-agent/opa/pull/6159)

**Comment by ashutosh-narkar** [comment]
Fixed in https://github.com/open-policy-agent/opa/pull/6159.
