### ISSUE TITLE
uuid parsing

### ISSUE THREAD

**Issue by Od1nB** [open-policy-agent/opa#6173]
## What is the underlying problem you're trying to solve?

Would be good to have a _native_ way to check for valid _uuid_. The current way of solving this is by making a rego function and doing a `regex.match(pattern, value)`. This is limited and not great for readability. If you wanted more information about the uuids, like version and other properties (ex. time in v1 and v2). 
This would bring more utility to the already built in package uuid in OPA

## Describe the ideal solution

This is mostly for extracting properties from an uuid and validating it, so a built in function: `uuid.parse(string) { ... }` would be a good addition. Potensial solutions:

- Depending on the results from the parsing, the function could return something like this `{valid, obj{propA:valA, ...}}`. The _valid_ variable should be a boolean on wether or not the input string is a uuid or not. If it resolves to false, the obj would be empty, `uuid.parse("123") -> {false, {}}`
- Another solution could be to return an object without a _valid_. If the input string is a uuid it will populate and return an object ( `{propA:valA, propB:valB, ...}`) and if not it would be an empty object or the object could be undefined. Depending on what you think would fit best.
Taking inspiration from `google/uuid` package, the object could contain properties like, version, variant, version, etc. All these are present in the [uuid.go](https://github.com/google/uuid/blob/06716f6a60da5ba158f1d53a8236a534968ff76e/uuid.go) file as methods on the _UUID_ type. 

## Describe a "Good Enough" solution

A minimum viable solution to this could be just a `uuid.isvalid(string) { ... }` function that spits out a true or false/undefined

## Additional Context

If an implementation instead of another dependency is needed, the code could be copied from the `google/uuid` package and the BSD copyright license could be added to the files. 

Example use:
```
valid_userid {
    is_string(input.userid)
    parsed_uuid := uuid.parse(input.userid)
    parsed_uuid.variant == "RFC4122"
    parsed_uuid.version == 4
}
```

**Comment by ashutosh-narkar** [comment]
This would be a good built-in addition. The first option indicating if the uuid is valid with the details in an object if valid seems a nice choice. If you'd like to contribute this feature that would be great!

**Comment by Od1nB** [comment]
Okey superb, I can start making an implementation of this

**Comment by srenatus** [comment]
Hmm. It's just details, but I think I'd prefer the "undefined or object" approach. 
```rego
valid(x) if uuid.parse(x)

valid("123") # => undefined
valid(proper_uuid) # => {"version": 4, "variant": "RFC4122"}
```

and it would work nicely with the example above, too,
```rego
valid_userid {
    is_string(input.userid)
    parsed_uuid := uuid.parse(input.userid) # undefined, i.e. eval aborted, if invalid
    parsed_uuid.variant == "RFC4122"
    parsed_uuid.version == 4
}
```

For the array-returning variant, we'd need to do this
```rego
valid_userid {
    is_string(input.userid)
    some parsed_uuid
    [true, parsed_uuid] = uuid.parse(input.userid)
    parsed_uuid.variant == "RFC4122"
    parsed_uuid.version == 4
}
```
or
```rego
valid_userid {
    is_string(input.userid)
    res := uuid.parse(input.userid)
    res[0] # valid
    parsed_uuid := res[1]
    parsed_uuid.variant == "RFC4122"
    parsed_uuid.version == 4
}
```

I think this variant is slightly more cumbersome to use.

**Comment by srenatus** [comment]
If you'd like the array-variant, you can build it from the undefined-variant:
```rego
valid_uuid(x) := [true, uuid.parse(x)]
else := [false, {}]
