### ISSUE TITLE
Confusing semantics when adding `if ...` to a partial set rule

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6184]
From the perspective of a clueless indivdual — and that would be me :) — it is difficult to understand the semantics of these expressions, and how adding `if true` to a rule head would alter the value/type of the rule(!)

```rego
a["b"]
```
As expected, this creates a set containing the value "b".

```rego
a["b"] if true
```

This creates a **map** with the key `b` and the value `true`. That is... not what I expected, as to me the `if` in `a["b"] if true` would be syntax sugar for `a["b"] { true }`, which apparently it isn't.

Now, I'm well aware that using `contains` would be the correct way to work with partial sets in ref-head rules, but given how that came out of backwards compatibility concerns, and `if` _also_ is a new keyword, it's hard to imagine backwards compatibility being the problem here.

The formatter also rewrites `a["b"] if true` -> `a["b"] = true` which to me is not semantically equivalent. I've tried finding anything on this in the docs but I've come up short.

**Comment by anderseknert** [comment]
A side effect of this — a trick we use in [Regal](https://github.com/StyraInc/regal) to distinguish:

```rego
a { true }
```
from
```rego
a = true { true }
```

Is to simply check the rule head value for the presence of a `location` attribute. Only in the latter case will there be a location, since in the former case the implied assignment is "generated" and cannot be traced to a location in the source code.

This "trick" however breaks for the beforementioned case, as a location for the value is added for the `true` value, despite no value being present on that location in the actual source code:

```
a["b"] if true
```
```shell
opa parse --format json --json-include locations p.rego
```
```json
{
  "head": {
    "value": {
      "location": {
        "file": "p.rego",
        "row": 5,
        "col": 1
      },
      "type": "boolean",
      "value": true
    }
  }
}
```

**Comment by tsandall** [comment]
Can we close this in favor of #6247?

**Comment by anderseknert** [comment]
Sure. Just so that I understand, while we will require `contains` and `if`, we don't want to require `if` for a rule without conditions, right? Provided the original example, I'd expect this:

```rego
a["b"]
```

to become this

```rego
a contains "b"
```

Without an if added / required. Is that correct?
