### ISSUE TITLE
AST: location missing for single entry rule head ref

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6199]
Having recently learnt that `rule.head.name` should be considered deprecated with the introduction of ref head rules (i.e. `a.b.c := true`) and that the name(s) should instead be derived from the entries in the `rule.head.ref` array. This works when there is more than one ref:

**Policy**
```rego
a.b.c := true
```
**AST**
```json
{
  "head": {
    "ref": [
      {
        "location": {"file": "p.rego", "row": 3, "col": 1},
        "type": "var",
        "value": "a"
      },
      {
        "location": {"file": "p.rego", "row": 3, "col": 3},
        "type": "string",
        "value": "b"
      },
      {
        "location": {"file": "p.rego", "row": 3, "col": 5},
        "type": "string",
        "value": "c"
      }
    ]
  }
}
```

But not for the traditional rule with a single "ref":

**Policy**
```rego
a := true
```

**AST**
```json
{
  "head": {
    "name": "a",
    "ref": [
      {
        "type": "var",
        "value": "a"
      }
    ]
  }
}
```
This means tools that use the AST for e.g. static analysis, will have to add special treatment for this distinction, and get the location from the rule head itself for when missing from the ref. Ideally, the location should be included in the ref even for the single entry ref.

Now, this isn't a huge deal, but it also seems like it would be easy enough to fix.

**Comment by Ronnie-personal** [comment]
I'm interested in fixing this bug.  Could you point out which code file needs to be fixed?

Thanks.
