### ISSUE TITLE
Non-cubic cube described in policy-language.md

### ISSUE THREAD

**Issue by rbanffy** [open-policy-agent/opa#6206]
## Short description 

In /docs/content/policy-language.md, (https://www.openpolicyagent.org/docs/latest/policy-language/#sets) the cube described is a very weird one. One would assume that little bit of surreal (a 3x4x5 "cube") is done on purpose. Should it be fixed?

## Steps To Reproduce

1. Open https://www.openpolicyagent.org/docs/latest/policy-language/#sets
2. Picture a 3x4x5 cube

## Expected behavior

It should be cubic.

## Additional context

https://en.wikipedia.org/wiki/Cube

**Comment by srenatus** [comment]
Good point! Let's use a word that describes the thing better. It's not a cube. I guess it would make sense to compare two sets, like, a cube's edge lengths would be a one-element set, whereas another three-dimensional body ([rectangular cuboid](https://en.wikipedia.org/wiki/Cuboid#Rectangular_cuboid)) would have an edge-length-set of more than one element... Or let's go with fruit or something. 😄

**Comment by rbanffy** [comment]
I thought about `brick`, but `rectangular_cuboid` sounds much more precise.
