### ISSUE TITLE
Add support for dynamic metadata

### ISSUE THREAD

**Issue by thiagotonon** [open-policy-agent/opa#6209]
## What is the underlying problem you're trying to solve?
It would be nice if we could inject dynamic metadata into OPA to be able to use it in other proxy steps configuration (for example envoy access logs)

## Describe the ideal solution
Like `response_headers_to_add`, `status_code` we could add a new keyword `dynamic_metadata` that will be used by the opa-envoy-plugin to[ inject the metadata](https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/internal/internal.go#L440) into the response ok or denied.

## Additional Context
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#dynamic-metadata
- https://github.com/envoyproxy/go-control-plane/blob/main/envoy/service/auth/v3/external_auth.pb.go#L302

**Comment by srenatus** [comment]
Yep that would be a cool feature. :+1:

**Comment by tjons** [comment]
I started working on this today, should have something wrapped up early next week @srenatus
