### ISSUE TITLE
AST: Allow jsonOptions to include Text field of Location struct

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6213]
Similarly to what was [previously done](https://github.com/open-policy-agent/opa/pull/5576) in order to [include the location in the parsed AST](https://github.com/open-policy-agent/opa/issues/3143), it would be useful for tools like [Regal](https://github.com/StyraInc/regal) to be able to use the `Text` field of the `Location` struct. This is however currently lost in serialization. 

If we could add a JSON option to have that optionally included in location data, it would be helpful to solve a certain class of problems in external tooling.

**Comment by charlieegan3** [comment]
I've looked into this a bit this afternoon, we have an alias type Location in the ast package.

https://github.com/open-policy-agent/opa/blob/0431567c26565fe2b4d6ddbdc2f91f3a1eb3214a/ast/term.go#L32

This is the type that's used to for all the ast Term Location values, and forms the majority of Locations used in the ast Go API.

It aliases the location.Location type: 

https://github.com/open-policy-agent/opa/blob/2131da3d9ce98c5d7fe3547c408c47267664c834/ast/location/location.go#L14

This is used more sparingly in ast & topdown.

I'm unsure of the history as to why we have the alias (https://github.com/open-policy-agent/opa/pull/2219). However, it makes it harder to implement this feature as we can't add functions to the alias type required to alter the marshalling behaviour.

Open to other ideas 🙂

**Comment by charlieegan3** [comment]
Update, https://github.com/open-policy-agent/opa/pull/6234 should be a working fix for this issue. My comment above was based on a mistake I made in testing!

**Comment by anderseknert** [comment]
Niiiiice!
