### ISSUE TITLE
JWT Validation allows no leeway to account for clock skew

### ISSUE THREAD

**Issue by keydon** [open-policy-agent/opa#6217]
## Short description 
* OPA version 0.51.0

the verification of an jwt failes sporadicly for me, because the current time exeeded the `exp` field by some tenths of a second.
The RFC itself knows about these timing issues and allows for implementations to support leeway up to some minutes.

Would be great if opa would add the ability to add a leeway of a couple mintutes to `exp` & `nbf`. Either to a global config or through a option in the method call of `io.jwt.decode_verify`

## Steps To Reproduce
try to verify an freshly expired jwt

## Expected behavior
successfull validation with some leeway

## Additional context
[RFC](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4)

**Comment by anderseknert** [comment]
Hi @keydon 👋 

While I'm not directly opposed to the idea, this could be achieved today already by validating the signature and verifying the claims in two separate steps, which I'd say is recommended over using `io.jwt.decode_verify`.

Once the signature is verified, you'd extract the claims, and check the `exp` claim against the current time + any leeway you may want. 

A benefit of this model is that you're able to send details on verification failures encountered back to the client, whereas `io.jwt.decode_verify` is rather opaque.

**Comment by ashutosh-narkar** [comment]
Closing this for now as there are builtins available which can achieve the requested feature.

**Comment by keydon** [comment]
hio @anderseknert 
thanks for the workaround. I will definitely look deeper into it. But on the first sight it does not look trivial what the built in function does https://github.com/open-policy-agent/opa/blob/master/topdown/tokens.go#L981

but maybe thats just golang thats so scary to me xD
You dont happen to have a gist or snippet that does reimplement that in rego already? :D

**Comment by anderseknert** [comment]
Something like this would be a start: https://play.openpolicyagent.org/p/9KqO6hFJry

Definitely not production code — I've not written a single test for the above ;) But it'll give you an idea about what it'd look like, and how you easily could extend this for your own requirements.

**Comment by keydon** [comment]
thank you for the pointers, much appreciated :)
