### ISSUE TITLE
OPA not parsing '+' character

### ISSUE THREAD

**Issue by Sahildange0** [open-policy-agent/opa#6225]

**Comment by srenatus** [comment]
Hello! 👋 

I'm afraid there is not much to go with here. Please provide some context so we can try to help you.

First and foremost, what are you parsing? Are you using `opa eval`, the REST API, or the Golang API? If it's the REST API, can you share the policy, payload, and how you're querying it?

**Comment by ashutosh-narkar** [comment]
Closing this for now. @Sahildange0 feel free to re-open with the information asked above. Thanks!
