### ISSUE TITLE
Getting is recursive error while no recursive call

### ISSUE THREAD

**Issue by dario-apaleo** [open-policy-agent/opa#6231]
## Short description 
Testing a sample to create a policy results in `is recursive` when I see no recursive call

Examples:

Working on playground

## Steps To Reproduce
Example [here](https://play.openpolicyagent.org/p/s8lkgXdtLv)

## Expected behavior
A better error message

## Additional context

I'm trying to create a policy that for a given set of urls, and for them a set of allowed roles, any input role matching the url roles should allow my request

**Comment by srenatus** [comment]
Your policy would be recursive if your input happened to be `{"request_url": "roles_test"}`. You might, but the compiler isn't able to figure out that it's impossible. The easiest workaround is to use some prefix for the lookup, like `data.roles[input.request_url]`

**Comment by tsandall** [comment]
Just to add onto what @srenatus said, all packages/rules are namespaced under `data` (which is why you can query for the output of rules or raw JSON under the same API path, e.g., GET /v1/data). So when you ask for `data[input.request_url]` in `allow` you're implicitly asking for `data.roles_test.allow`.

**Comment by dario-apaleo** [comment]
@tsandall and @srenatus thanks you so much for your quick response, I still don't see why my policy in the example can cause a recursive error, since my url is `url_1` and is not the package, or named after any method. 
Sorry if my question might sound silly, I'm completely new to this :(
