### ISSUE TITLE
Latest opa version does not work with go.opentelemetry.io/otel 1.18.0

### ISSUE THREAD

**Issue by alinalex1392** [open-policy-agent/opa#6233]
I am trying to get my project up to date in order to fix the security vulnerabilities. Currently, the latest version of opa v0.56.0 does not work with the go.opentelemetry.io/otel@1.18.0. Currently, I need to use go.opentelemetry.io/otel@1.16.0 and pin the automatic dependency update for this library. As the Semver suggests the upgrade to 1.18.0 should not be a breaking change for your side.

**Comment by anderseknert** [comment]
If previous upgrades are anything to go by, they are far from being uncomplicated. See e.g.: https://github.com/open-policy-agent/opa/pull/6004

That said, and upgrade would be welcome :) 

Could you please provide some details on the security vulnerabilities you mention?

**Comment by alinalex1392** [comment]
It is not a vulnerability that I can point out in regard to otel lib, just that our policy is to go latest as soon as we do not break Semver.

**Comment by anderseknert** [comment]
IMHO, SemVer doesn't help much for libraries before they reach 1.0.0, as the common (perhaps, mis-)conception is that breaking changes is OK before that.

**Comment by alesbrelih** [comment]
I had the same "issue" but it turned out that I just had to manually update exporters I was using in my project.

```
go get go.opentelemetry.io/otel/exporters/otlp/otlptrace@latest
go get go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@latest
```

Now it works. My go.mod:

```
	github.com/open-policy-agent/opa v0.56.0
	go.opentelemetry.io/otel v1.18.0
	go.opentelemetry.io/otel/exporters/prometheus v0.40.0
	go.opentelemetry.io/otel/metric v1.18.0
	go.opentelemetry.io/otel/sdk v1.18.0
	go.opentelemetry.io/otel/sdk/metric v0.40.0
	go.opentelemetry.io/otel/trace v1.18.0
	....
```
Weird.. I guess I need to look up how modules works under the hood.

**Comment by alinalex1392** [comment]
Thank you, this solution worked!
