### ISSUE TITLE
Add data file input for "opa exec" too.

### ISSUE THREAD

**Issue by nithish0502** [open-policy-agent/opa#6237]
Currently, there's no provision to add data file as input in "opa exec" command. This flag is not listed in the documentation for exec command also.

It would be helpful if we can do.
`opa exec --data data.json --bundle opa\policies input.json`
 just like,
`opa eval --data data.json --bundle opa\policies --input input.json`
 
 Also, if there's any workaround, please help.

**Comment by ashutosh-narkar** [comment]
You should be able to provide the paths to your policies/data to `opa exec` and also use the `-b` flag to enable bundle mode. Have you encountered any issues with this approach?

**Comment by nithish0502** [comment]
> You should be able to provide the paths to your policies/data to `opa exec` and also use the `-b` flag to enable bundle mode. Have you encountered any issues with this approach?

That's not my issue right now. I wanted to add a data.json file to supply values to a policy.rego file. I thought this would be helpful particulatly when we have to create template like policies and reuse it for various contexts.

**Comment by ashutosh-narkar** [comment]
I would imagine you can specify policy files, data files in the path and then the policy would be evaluated based on any data provided. Is that not the case?

**Comment by nithish0502** [comment]
> I would imagine you can specify policy files, data files in the path and then the policy would be evaluated based on any data provided. Is that not the case?

What I'm trying to do is setup rego policies in a centralized repository and have multiple data.json files, that would contain standards for each use case.

For example, Application 'A' might have to follow a set of naming conventions, likewise for Application 'B', but different standards. The data.json would contain the standards that I would check against the terraform plan for every application, that would be passed through a cicd pipeline.

Can you please suggest a way to achieve this?

**Comment by ashutosh-narkar** [comment]
There are few ways you can achieve this based on size of data, frequency of updates etc. One approach you could use is [bundles](https://www.openpolicyagent.org/docs/latest/management-bundles/). You could have the polices and data in one bundle or you could have separate bundle for policy and data and configure OPA to pull the bundle(s). Other option is you push this policy and data into OPA via the REST API. The bundle approach is recommended and should work for your case. Other options can be found [here](https://www.openpolicyagent.org/docs/latest/external-data/).

**Comment by ashutosh-narkar** [comment]
Closing this for now as we seem to have an existing mechanism to achieve what's asked for here. Feel free to re-open if there is a requirement.
