### ISSUE TITLE
Dependency issue when update open telemetry

### ISSUE THREAD

**Issue by ehsannm** [open-policy-agent/opa#6254]
If we update open-telemetry to v1.18.0 which is the latest one, we get build failed.

    github.com/open-policy-agent/opa/rego imports
        github.com/open-policy-agent/opa/plugins tested by
        github.com/open-policy-agent/opa/plugins.test imports
        github.com/open-policy-agent/opa/internal/distributedtracing imports
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc imports
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig: module go.opentelemetry.io/otel/exporters/otlp/otlptrace@latest found (v1.18.0), but does not contain package go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig

**Comment by srenatus** [comment]
Could you please try what's described here? https://github.com/open-policy-agent/opa/issues/6233

**Comment by ehsannm** [comment]
surprisingly it worked. Very weird. Thanks for the tips.
