### ISSUE TITLE
Built-in JWT decode_verify function fails to decode valid RSA-signed token

### ISSUE THREAD

**Issue by c0c0n3** [open-policy-agent/opa#6283]
## Short description 
Use the built-in `io.jwt.encode_sign` function to create an RSA-signed JWT, then use `io.jwt.decode_verify` to extract the payload and verify the signature. The `decode_verify` fails to extract the payload and verify the signature.

Examples:
* OPA version: 0.53.1; 0.57.0
* Example script to reproduce: https://play.openpolicyagent.org/p/FdHKI1S9fI

## Expected behavior
The `decode_verify` should be able to extract the JWT payload and verify its signature.

## Additional context
If you copy-paste the `jwt` string `encode_sign` outputs and the RSA pub key into https://jwt.io/, then `jwt.io` correctly extracts the payload and verifies the signature.

**Comment by c0c0n3** [comment]
Here's the test script published in the Rego playground---just in case it gets removed from there after a while.

```rego
package play

# RSA keys and JWKs generated on https://mkjwk.org/
# using the parameters below
#
#   Key Size         = 2048
#   Key Use          = Signature
#   Algorithm        = RS256: RSASSA-PKCS1-v1_5 using SHA-256
#   Key ID - Specify = k1
#   Show X.509       = Yes

rsa_pub_key := {
    "kty": "RSA",
    "e": "AQAB",
    "use": "sig",
    "kid": "k1",
    "alg": "RS256",
    "n": "rFdk9QnnPyQXhPgmHXtF7WupI3aCj-2YVprjEPkra-fPtxKRBjEC0AlDi7BhYilZzcpB2MGKAjzUvfKp7YFwAw7fp6M0fHKRyMtGDCzuu0bv6LX4uLFqLeft8UyjYX1Al3LVmX4VmRxVy88BxFh5H85WMtAOy3JPLYVpf6XZ7fOFEkNyzLY2hYklfsnbvG8ZJyNgAOTSx_33wOv8680NBme44lbCP3007sQGoFXpApsQZPbM1ug6AwDAQejGNVEq-EuGLmkjSEBlbKReUonoigqyRX-39qFIMrflkEYMahIewWQKUxwFFaR8BLPteRL072BZgqqIBgWG6XDyyONj9Q"
}

rsa_key_pair_jwk := {
    "p": "8ybS9TowEW0Y0xHpGBm7LGLoc5u8IF-EkuTFdFZ4DchkeFL1M0ditEJEUV7OlKWErxwRGWo6bA7rLmNA8URZZl_SlSYgWcDeKwHwGqrMXgTydzflYxRmS8azenSoXkiDxFE2Y5psq-6mXmlNYlimV0b7jIylgUUtRX1DAzI42fc",
    "kty": "RSA",
    "q": "tXKzhk6uYZoL8bkpVrp0xouyhWhgdAcXN5vDlx98aojbD4DkFj4Zd7_Utl9s5HWYEMJPvMTiYUDaJdkeSDBrmA4OH_4QS5R1DqVvBBMq3JJXvVzaZox7ysWXPeEnNXcYFK_qhtnFHN-ztTWk-WmcWaU-nfgg5WEwfrlRyLTD1nM",
    "d": "M01swzjoerZOvgl0pzAMF-oFloXvxdKPl7BRybqyv1NpVPEU9MfgM3eegNXHl4YBsq3zvgeXAqWDGuxCw23Vn0NtNqTxud4NIb3JI1S42Ez8m8SXvrsphXLWNQ-AT0QO10aa6S9MVKDHtXzw5LcFj39Hz6Z50Pw9L6rYReRkJF3sKJDv9mUjT9unobgHlnc99HQ-XB9r2md0WwdZI6COXAMT32Fgb9ZhBrq8VyhRiZLje7zmiPqYaB5XQKq6mJLhq26yvZ0leQw7DGVZ0Ot9FpdQky3_T80zhXxYi1-6-dttVhdlRGFsAjjXLPtbWhVTObDDKlcfzC7PWZkJhhO7_Q",
    "e": "AQAB",
    "use": "sig",
    "kid": "k1",
    "qi": "L2QvQX9uB1anD09Ai0ANKhAeWkRbFKRBBLSaCmV9ZteQeHuG_HUEdZp5NSzg0B4yySLsgT37-1Yc0PZNHWDWltIi7PlwpSiTuDpXRHHQlZOwfLKnu40JtJWgIw8e_yFga5SfcoUuv727GAiONQYXhIKDb1PkpXzEvwQQuoDidVc",
    "dp": "h7acunj-yUsuNujhRC1gdjbCbXx39U267k44E2YL3g2CXlJXP4bRhbES9qPHA9qagy5UMO5Eq3lsNNj7L26pw2UqYUsFdXMbzb9oJ0o7hSKXvoj5RGLncdX26RthujYZLaLyi4durkwmmb2GjqTSOxaIYntCCTP2P7nZhFgsuSM",
    "alg": "RS256",
    "dq": "pVCx3AZHvskZZMysq0YKKvMQXZfxeQUU1CdoloGrW20BGSj3poRBs-blKJvcnHG_cFV5TKWdE7qAhsdAXckv3kO__sn9kr7Zv9ReRzonbPswUWkN2yzXhLFt0IUYsg-lswNsDBzRCDOQieMsQclFGDAD0u1FG3fnNS4nI1P-sZ0",
    "n": "rFdk9QnnPyQXhPgmHXtF7WupI3aCj-2YVprjEPkra-fPtxKRBjEC0AlDi7BhYilZzcpB2MGKAjzUvfKp7YFwAw7fp6M0fHKRyMtGDCzuu0bv6LX4uLFqLeft8UyjYX1Al3LVmX4VmRxVy88BxFh5H85WMtAOy3JPLYVpf6XZ7fOFEkNyzLY2hYklfsnbvG8ZJyNgAOTSx_33wOv8680NBme44lbCP3007sQGoFXpApsQZPbM1ug6AwDAQejGNVEq-EuGLmkjSEBlbKReUonoigqyRX-39qFIMrflkEYMahIewWQKUxwFFaR8BLPteRL072BZgqqIBgWG6XDyyONj9Q"
}

jwks_tasty_config := {
    "keys": [
        rsa_key_pair_jwk
    ]
}


# Rego test showing you can encode using our JWKs but then decoding fails.
# Note if you copy-paste the `jwt` string below into https://jwt.io/ and use `rsa_pub_key`
# to verify the signature, jwt.io says the signature is valid.

jwks := json.marshal(jwks_tasty_config)

header := {
	"alg": "RS256",
	"typ": "JWT",
}

payload := {"iss": "me"}

jwt := io.jwt.encode_sign(header, payload, rsa_key_pair_jwk)

fail := io.jwt.decode_verify(jwt, {"cert": jwks})

```

**Comment by anderseknert** [comment]
Hi @c0c0n3 👋 

> Note if you copy-paste the `jwt` string below into https://jwt.io/ and use `rsa_pub_key` to verify the signature, jwt.io says the signature is valid.

So does OPA — your code code above is however including the whole key pair in the JWK, and not `rsa_pub_key`. If you only include the public key, i.e: 

```rego
jwks_tasty_config := {
    "keys": [
        rsa_pub_key
    ]
}
```

You'll see the expected result (successful verification).

**Comment by c0c0n3** [comment]
Hi @anderseknert !!

Thanks sooo much for the quick answer. It's actually my mistake, I just assumed (without checking :-) that `rsa_key_pair_jwk` would work too b/c the Rego implementation would ignore the extra fields in there and only consider the pub key ones. Sorry for making you waste your time on this :-)

In retrospect, the Rego implementation totally makes sense since you'd get the JWKs from the issuer's public OIDC config which should never (hopefully!) contain the private key fields.

**Comment by anderseknert** [comment]
That's a fair assumption to make, and I suppose it could be considered a bug that when provided a RSA key-pair JWK, the `io.jwt.decode_verify` built-in function picks the _private_ key component to use for verification rather than the public key.

On the other hand, and as you allude to — you almost certainly don't want to expose a private key this way, and if this built-in function's behavior helps someone see that, perhaps that's a good "bug"? 😅 

Interestingly, the `io.jwt.verify_rs256` built-in function _does not_ pick the private key for verification using the same JWKS, but successfully verifies the JWT using the public key component. This inconsistency is arguably a bug, but changing behavior in either direction would be a breaking change, and I don't think there's enough upside of such a change that it outweighs the risk.
