### ISSUE TITLE
opa-envoy-plugin fails to process request bodies with non-latin characters

### ISSUE THREAD

**Issue by CedricLempereur** [open-policy-agent/opa#6294]
## Short description 
Requests are stopped at the envoy plugin when request body contains non-latin characters
can be reproduced with the latest 0.57 

## Steps To Reproduce
using Istio w opa-envoy plugin, with the request body configured to be sent to the sidecar
When a request contains a non-latin character (for example Ø ), the request is stopped before reaching the opa rules
We can find the following error in the container log: "unexpected EOF"

## Expected behavior
the presence of non-latin character in the request body should not have any impact 

## Additional context
We have opa configured so that the request body is sent to the opa sidecar

**Comment by ashutosh-narkar** [comment]
It would be great if you could help reproduce the issue by providing the input, policy, decision log, error message and any other relevant info. For example in the [Envoy](https://www.openpolicyagent.org/docs/latest/envoy-tutorial-standalone-envoy/) tutorial,  I replaced the input in [this](https://www.openpolicyagent.org/docs/latest/envoy-tutorial-standalone-envoy/#creating-people) step to contain non-latin characters as shown below:

```bash
curl -i -H "Authorization: Bearer $BOB_TOKEN" -d '{"firstname":"Ø", "lastname":"YYYY"}' -H "Content-Type: application/json" -X POST http://example-app/people

curl -i -H "Authorization: Bearer $BOB_TOKEN" -d '{"firstname":"Älex", "lastname":"XXXX"}' -H "Content-Type: application/json" -X POST http://example-app/people
```

There was no error in the logs. Here is a decision log for a sample request:

```bash
{"bundles":{"default":{}},"decision_id":"d36eff38-069c-4c36-a8d0-881d7c6fd4a5","input":{"attributes":{"destination":{"address":{"socketAddress":{"address":"10.244.0.6","portValue":8000}}},"metadataContext":{},"request":{"http":{"body":"{\"firstname\":\"Ø\", \"lastname\":\"YYYY\"}","headers":{":authority":"example-app",":method":"POST",":path":"/people",":scheme":"http","accept":"*/*","authorization":"Bearer eyJhbGciOiAiSFMyNTYiLCAidHlwIjogIkpXVCJ9.eyJleHAiOiAyMjQxMDgxNTM5LCAibmJmIjogMTUxNDg1MTEzOSwgInJvbGUiOiAiYWRtaW4iLCAic3ViIjogIlltOWkifQ.5qsm7rRTvqFHAgiB6evX0a_hWnGbWquZC0HImVQPQo8","content-length":"39","content-type":"application/json","user-agent":"curl/8.1.2","x-envoy-auth-partial-body":"false","x-forwarded-proto":"http","x-request-id":"33e3928a-c6d9-403a-957a-a583e80689e0"},"host":"example-app","id":"4380994644596732875","method":"POST","path":"/people","protocol":"HTTP/1.1","scheme":"http","size":"39"},"time":"2023-10-10T21:03:57.552114Z"},"source":{"address":{"socketAddress":{"address":"10.244.0.7","portValue":42078}}}},"parsed_body":{"firstname":"Øö","lastname":"YYYY"},"parsed_path":["people"],"parsed_query":{},"truncated_body":false,"version":{"encoding":"protojson","ext_authz":"v3"}},"labels":{"id":"0b62a494-80e7-4beb-ba31-43099252c7c1","version":"0.57.0-envoy-1"},"level":"info","metrics":{"timer_rego_query_eval_ns":7203417,"timer_server_handler_ns":11231167},"msg":"Decision Log","path":"envoy/authz/allow","result":true,"time":"2023-10-10T21:03:57Z","timestamp":"2023-10-10T21:03:57.567052297Z","type":"openpolicyagent.org/decision_logs"}
```

**Comment by CedricLempereur** [comment]
Issue was with the request content-length not being calculated properly. No issues once we corrected the content-length.
