### ISSUE TITLE
OPA test coverage is not correct when rounding

### ISSUE THREAD

**Issue by aholmis** [open-policy-agent/opa#6307]
## Short description 

OPA version: 0.55.0

We run `opa test . -c --threshold 100` in our build pipeline to keep absolute full code coverage.
However, if 1 out of ~12000 lines are not covered, it is treated as 100% and passes the threshold.
I assume golang rounds up to nearest integer at some point when it's close enough, like 99.999999?
The `not_covered_lines` are still reported in the coverage report.

## Steps To Reproduce

I'm unsure at what number of lines this actually kicks in, but our codebase is over 12000 lines of rego, and it passes threshold of 100 even when 1 or 2 lines are not covered.

## Expected behavior

Fail the test coverage threshold when the percentage is mathematically lower.
I suggest to round down to closest nn.dd at all times.

**Comment by anderseknert** [comment]
Thanks Anders (and good to see you, btw!). That does indeed sound like an issue to address.

**Comment by aholmis** [comment]
Thanks for the swift response!
