### ISSUE TITLE
Add ratelimit policy example

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#632]
Several people found this thread on slack helpful to understand policy-authoring and suggested we commit to the docs.

https://openpolicyagent.slack.com/archives/C1H19LW4F/p1516200591000257

More generally, it could be valuable to have worked out policy examples in the docs, sort of tutorials for policy authoring.  Right now the tutorials are focused on integrations rather than writing policy.

**Comment by crawford** [comment]
@tim-styra Can you post the contents of that thread here? I don't have access to that Slack workgroup.

**Comment by tsandall** [comment]
@crawford you should be able to join at https://slack.openpolicyagent.org. We'll hopefully get this posted on the site shortly.

**Comment by tsandall** [comment]
This example has been lost to the Slack archive which we don't have access to. IIRC, the example included some examples of search which are covered by #1268

**Comment by johanbrandhorst** [comment]
![xkcd](https://user-images.githubusercontent.com/6604151/99701945-166e1300-2a8d-11eb-9f27-930f9bd9be5c.png)
