### ISSUE TITLE
Add best practices doc

### ISSUE THREAD

**Issue by tim-styra** [open-policy-agent/opa#633]
It would be helpful to include a doc describing best-practices around writing policies.

Topics:
* Conventions around equality (:=, ==, =)
* Conflict-resolution: allow-overrides-deny, deny-overrides-allow, in-order
* Collaboration/composition using import
* Performance: Writing linear-time policies that activate the trie rule indexer
* Performance: Using partial evaluation
* Functions versus rules
* How to use JWTs
* Unsafe variable errors -- how to debug them

**Comment by tsandall** [comment]
The outstanding best practice items have been fixed in #1268
