### ISSUE TITLE
opa strict check reporting unused argument for function with multiple implementations

### ISSUE THREAD

**Issue by fseldow** [open-policy-agent/opa#6332]
## Short description 
Hi OPA community, when i am running `OPA check -S` with version `v0.54.0`, it reports `unsued argument` for function with same but different implementations

My example rego is as below:
```
test(a, b) if {
	a == "a"
	b == "b"
}

test(a, b) if {
	a != "a"
}
```
https://play.openpolicyagent.org/p/ujnRA6YXVm

reports result `1 error occurred: policy.rego:28: rego_compile_error: unused argument b. (hint: use _ (wildcard variable) instead)`

For function `test`, the second implementation does not use the parameter `b`, however, this parameter is required in the first implementation

## Expected behavior
The current workaround is to add `_ := b` in the second function as the hint in the opa playground.
Will it be possible to scan all the functions with the name for the `unused argument` check? Or it is always suggested to add wildcard usage?

**Comment by anderseknert** [comment]
> Or it is always suggested to add wildcard usage?

Indeed, that is the right way to do it, as `b` is effectively unused in the second function declaration. So, just:

```rego
test(a, b) if {
	a == "a"
	b == "b"
}

test(a, _) if {
	a != "a"
}
```

**Comment by anderseknert** [comment]
For extra style points, you could even do this :)

```rego
test("a", "b")

test(a, _) if {
	a != "a"
}
```

Using [equals pattern matching](https://docs.styra.com/regal/rules/idiomatic/equals-pattern-matching) in the function args.

**Comment by fseldow** [comment]
thx @anderseknert for the recommended sytle!
