### ISSUE TITLE
[Minor][OPA Envoy plugin] Decision logs should have a non-null input even if context deadline exceeds

### ISSUE THREAD

**Issue by rudrakhp** [open-policy-agent/opa#6333]
## What is the underlying problem you're trying to solve?
* OPA running in a K8s env, envoy's `ext_authz` filter is configured to call OPA server for decisions (OPA uses [OPA Envoy Plugin](https://github.com/open-policy-agent/opa-envoy-plugin)).
* OPA version: 0.57.0
* OPA Envoy plugin version: 0.57.0-envoy
* K8s version: EKS 1.24
* When there is a huge spike in requests to OPA or OPA processing is slow, context deadline is exceeded or cancelled even before the request is picked up by OPA from queue. Under these circumstances, the `input` attribute in decision log is not populated. This can make debugging difficult as the exact request that has had it's context cancelled is not readily available.
## Describe the ideal solution
The `input` could be populated (initialised [here](https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/internal/internal.go#L371)) before [throwing a context deadline exceeded error](https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/internal/internal.go#L387) so we have more info on the exact request that has timed out/dropped. Unless it's not populated by design for some reason.

## Describe a "Good Enough" solution
N/A
Same as above.

## Additional Context
N/A
Was not sure if the right place for this was in bugs/feature request. Please let me know if more info/context in required. Thanks!

**Comment by ashutosh-narkar** [comment]
Hey @rudrakhp processing the input before reporting the error seems fine. I think the rationale for not populating the input iirc may have been that since the context deadline has already exceeded, input processing is unnecessary. But maybe as you suggest it may help in debugging. If you'd like to contribute that would be great. Thanks!

**Comment by rudrakhp** [comment]
@ashutosh-narkar raised a PR linked above, please review. Thanks!
