### ISSUE TITLE
VC Pod getting restarted - fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by dhananjaysarkin** [open-policy-agent/opa#6422]
root@bat-prod-simulator-site-e2e-lena-vc-6d96df4997-jrqdj:/code# ./govc version
govc 0.22.1

`2023/11/18 21:48:56 http: TLS handshake error from 192.168.24.1:13217: read tcp 192.168.32.8:443->192.168.24.1:13217: read: connection reset by peer
fatal error: concurrent map iteration and map write

goroutine 1438466 [running]:
runtime.throw(0x1004309, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc001a43078 sp=0xc001a43048 pc=0x42dad2
runtime.mapiternext(0xc001a43178)
	/usr/local/go/src/runtime/map.go:860 +0x520 fp=0xc001a43100 sp=0xc001a43078 pc=0x4105d0
github.com/vmware/govmomi/simulator.(*Session).Get(0xc0019cce40, 0xc000611dd0, 0xe, 0xc000a940f0, 0xe, 0x11789a0, 0xc0006aefd0)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/session_manager.go:364 +0x19c fp=0xc001a43650 sp=0xc001a43100 pc=0xb7e77c
github.com/vmware/govmomi/simulator.(*Service).call(0xc0007f7e60, 0xc001549ef0, 0xc001750900, 0x200, 0xc001750900)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/simulator.go:153 +0x1869 fp=0xc001a43898 sp=0xc001a43650 pc=0xb80829
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc0007f7e60, 0x1186fe0, 0xc00154b420, 0xc001073a00)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/simulator.go:472 +0x427 fp=0xc001a43c38 sp=0xc001a43898 pc=0xb82987
github.com/vmware/govmomi/simulator.(*Service).ServeSDK-fm(0x1186fe0, 0xc00154b420, 0xc001073a00)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/simulator.go:426 +0x48 fp=0xc001a43c68 sp=0xc001a43c38 pc=0xbbfb98
net/http.HandlerFunc.ServeHTTP(0xc000aec290, 0x1186fe0, 0xc00154b420, 0xc001073a00)
	/usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc001a43c90 sp=0xc001a43c68 pc=0x6d09f4
net/http.(*ServeMux).ServeHTTP(0x1bbb5e0, 0x1186fe0, 0xc00154b420, 0xc001073a00)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6 fp=0xc001a43cf0 sp=0xc001a43c90 pc=0x6d28c6
net/http.serverHandler.ServeHTTP(0xc000f74ea0, 0x1186fe0, 0xc00154b420, 0xc001073a00)
	/usr/local/go/src/net/http/server.go:2774 +0xab fp=0xc001a43d20 sp=0xc001a43cf0 pc=0x6d3cab
net/http.(*conn).serve(0xc000c685a0, 0x1188860, 0xc0013126c0)
	/usr/local/go/src/net/http/server.go:1878 +0x84c fp=0xc001a43fc8 sp=0xc001a43d20 pc=0x6cf9bc
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001a43fd0 sp=0xc001a43fc8 pc=0x45a001
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 1 [chan receive, 7380 minutes]:
main.main()
	/home/sre/go/src/github.com/vmware/govmomi/vcsim/main.go:225 +0x14bf

goroutine 5 [syscall, 7380 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b0e78ef38, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000ebbc98, 0x72, 0x0, 0x0, 0xfba0ef)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000ebbc80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000ebbc80, 0xc001a64000, 0x550000c000e47200, 0x3)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000011390, 0xc001982000, 0x1045378, 0x1b72c80)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000011390, 0xc000067e88, 0xc001982088, 0x655b3300, 0xc0007f7f80)
	/usr/local/go/src/net/tcpsock.go:260 +0x48
crypto/tls.(*listener).Accept(0xc00071b020, 0xc000067ee8, 0x18, 0xc000e47200, 0x6d4184)
	/usr/local/go/src/crypto/tls/tls.go:62 +0x37
net/http.(*Server).Serve(0xc000f74ea0, 0x1186b20, 0xc00071b020, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
github.com/vmware/govmomi/simulator/internal.(*Server).goServe.func1(0xc0007f7f80)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/internal/server.go:268 +0x6d
created by github.com/vmware/govmomi/simulator/internal.(*Server).goServe
	/home/sre/go/src/github.com/vmware/govmomi/simulator/internal/server.go:266 +0x5c

goroutine 1438462 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b0e78ebf8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0019ddf18, 0x72, 0x700, 0x70a, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0019ddf00, 0xc0012f3000, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0019ddf00, 0xc0012f3000, 0x70a, 0x70a, 0x203000, 0x3e7e3cf3907b1b64, 0x29754dbcf1fc2ad8)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000011738, 0xc0012f3000, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000c061e0, 0xc0012f3000, 0x70a, 0x70a, 0x300, 0x10, 0xc001b778a0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc001076cd8, 0x1177f40, 0xc000c061e0, 0x40b445, 0xdd68e0, 0xf90c80)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc001076a80, 0x117c8a0, 0xc000011738, 0x5, 0xc000011738, 0xc001b77988)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc001076a80, 0x1045300, 0xc001076bb8, 0x6c9ada)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc001076a80, 0xc00133b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*connReader).Read(0xc0014f43c0, 0xc00133b000, 0x1000, 0x1000, 0x5ef601, 0xc000011738, 0x0)
	/usr/local/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc00146e600)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00146e600, 0x4, 0x0, 0x0, 0x0, 0x0, 0x4c286d)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*conn).readRequest(0xc000c68500, 0x1188860, 0xc000b56940, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:964 +0xb03
net/http.(*conn).serve(0xc000c68500, 0x1188860, 0xc000b56940)
	/usr/local/go/src/net/http/server.go:1819 +0x6a8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 1438446 [runnable]:
crypto/tls.(*Conn).readFromUntil(0xc001077180, 0x117c8a0, 0xc000011778, 0x5, 0xc000011778, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xb1
crypto/tls.(*Conn).readRecordOrCCS(0xc001077180, 0x1045300, 0xc0010772b8, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc001077180, 0xc0014f52a1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*connReader).backgroundRead(0xc0014f5290)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xca

goroutine 1438468 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b0e78e578, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc001750718, 0x72, 0x700, 0x70a, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001750700, 0xc0012f3800, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc001750700, 0xc0012f3800, 0x70a, 0x70a, 0x203000, 0x421fa5, 0x36312e323931a380)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000011770, 0xc0012f3800, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000bed5a0, 0xc0012f3800, 0x70a, 0x70a, 0x0, 0x0, 0xc000475d00)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc001077058, 0x1177f40, 0xc000bed5a0, 0x40b445, 0xdd68e0, 0xf90c80)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc001076e00, 0x117c8a0, 0xc000011770, 0x5, 0xc000011770, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc001076e00, 0x1045300, 0xc001076f38, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc001076e00, 0xc0014f5241, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*connReader).backgroundRead(0xc0014f5230)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xca

goroutine 1438441 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b0df4dd30, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0015b5d18, 0x72, 0x700, 0x70a, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0015b5d00, 0xc0015a0000, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0015b5d00, 0xc0015a0000, 0x70a, 0x70a, 0x203000, 0x7f8b0dd48cc8, 0x3f)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000d003b8, 0xc0015a0000, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000a6a7e0, 0xc0015a0000, 0x70a, 0x70a, 0x300, 0x10, 0xc00160d8a0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc001a65ad8, 0x1177f40, 0xc000a6a7e0, 0x40b445, 0xdd68e0, 0xf90c80)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc001a65880, 0x117c8a0, 0xc000d003b8, 0x5, 0xc000d003b8, 0xc00160d988)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc001a65880, 0x1045300, 0xc001a659b8, 0x6c9ada)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc001a65880, 0xc0010f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*connReader).Read(0xc001937bc0, 0xc0010f0000, 0x1000, 0x1000, 0x5ef601, 0xc000d003b8, 0x0)
	/usr/local/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc001dc4720)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc001dc4720, 0x4, 0x0, 0x0, 0x0, 0x0, 0x4c286d)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*conn).readRequest(0xc000152b40, 0x1188860, 0xc000cf5000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:964 +0xb03
net/http.(*conn).serve(0xc000152b40, 0x1188860, 0xc000cf5000)
	/usr/local/go/src/net/http/server.go:1819 +0x6a8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 192123 [IO wait, 6447 minutes]:
internal/poll.runtime_pollWait(0x7f8b0df4e3b0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0016a7e18, 0x72, 0x700, 0x70a, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0016a7e00, 0xc001521000, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0016a7e00, 0xc001521000, 0x70a, 0x70a, 0x203000, 0xac59b4342a00acd2, 0x56f5815e6084838)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000011580, 0xc001521000, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000a2cb20, 0xc001521000, 0x70a, 0x70a, 0x300, 0x10, 0xc0014d38a0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc001408cd8, 0x1177f40, 0xc000a2cb20, 0x40b445, 0xdd68e0, 0xf90c80)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc001408a80, 0x117c8a0, 0xc000011580, 0x5, 0xc000011580, 0xc0014d3988)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc001408a80, 0x1045300, 0xc001408bb8, 0x6c9ada)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc001408a80, 0xc001219000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*connReader).Read(0xc001478330, 0xc001219000, 0x1000, 0x1000, 0x5ef601, 0xc000011580, 0x0)
	/usr/local/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc00146ff80)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00146ff80, 0x4, 0x0, 0x0, 0x0, 0x0, 0x4c286d)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*conn).readRequest(0xc0002dcaa0, 0x1188860, 0xc00032ac00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:964 +0xb03
net/http.(*conn).serve(0xc0002dcaa0, 0x1188860, 0xc00032ac00)
	/usr/local/go/src/net/http/server.go:1819 +0x6a8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 1438444 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b0e78e3d8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc001652298, 0x72, 0x700, 0x70a, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001652280, 0xc0015a0800, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc001652280, 0xc0015a0800, 0x70a, 0x70a, 0x203000, 0xd5e68a104227fb12, 0x1de048539e941273)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000d003f0, 0xc0015a0800, 0x70a, 0x70a, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000c06560, 0xc0015a0800, 0x70a, 0x70a, 0x300, 0x10, 0xc001a478a0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc001a65e58, 0x1177f40, 0xc000c06560, 0x40b445, 0xdd68e0, 0xf90c80)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc001a65c00, 0x117c8a0, 0xc000d003f0, 0x5, 0xc000d003f0, 0xc001a47988)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc001a65c00, 0x1045300, 0xc001a65d38, 0x6c9ada)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc001a65c00, 0xc000e03000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*connReader).Read(0xc001926630, 0xc000e03000, 0x1000, 0x1000, 0x5ef601, 0xc000d003f0, 0x0)
	/usr/local/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc001866a20)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc001866a20, 0x4, 0x0, 0x0, 0x0, 0x0, 0x4c286d)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*conn).readRequest(0xc000152be0, 0x1188860, 0xc000cd0380, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:964 +0xb03
net/http.(*conn).serve(0xc000152be0, 0x1188860, 0xc000cd0380)
	/usr/local/go/src/net/http/server.go:1819 +0x6a8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 1438467 [runnable]:
bytes.(*Buffer).WriteByte(0xc0015696e8, 0xc000e90131, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:266 +0xb4
github.com/vmware/govmomi/vim25/xml.(*Decoder).rawToken(0xc001569680, 0xc00135e0e0, 0xc00060ef20, 0xc000fb6420, 0xc0019cb400)
	/home/sre/go/src/github.com/vmware/govmomi/vim25/xml/xml.go:621 +0xaf5
github.com/vmware/govmomi/vim25/xml.(*Decoder).Token(0xc001569680, 0xc0015a100d, 0xeb1b60, 0xc001774658, 0xc00143f228)
	/home/sre/go/src/github.com/vmware/govmomi/vim25/xml/xml.go:292 +0x1002
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc001569680, 0xed8920, 0xc000cd0e40, 0x199, 0x0, 0x199, 0xec7160)
	/home/sre/go/src/github.com/vmware/govmomi/vim25/xml/read.go:343 +0x3387
github.com/vmware/govmomi/vim25/xml.(*Decoder).DecodeElement(0xc001569680, 0xcdcac0, 0xc000cd0e40, 0x0, 0x1, 0xc000cd0e80)
	/home/sre/go/src/github.com/vmware/govmomi/vim25/xml/read.go:151 +0x146
github.com/vmware/govmomi/vim25/xml.(*Decoder).Decode(...)
	/home/sre/go/src/github.com/vmware/govmomi/vim25/xml/read.go:139
github.com/vmware/govmomi/vim25/xml.Unmarshal(0xc0013e8c00, 0x195, 0x200, 0xcdcac0, 0xc000cd0e40, 0x5, 0xc00105ba18)
	/home/sre/go/src/github.com/vmware/govmomi/vim25/xml/read.go:133 +0xab
github.com/vmware/govmomi/simulator.UnmarshalBody(0xc001920510, 0xc0013e8c00, 0x195, 0x200, 0xc000f74e58, 0x0, 0x0)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/simulator.go:877 +0x1a2
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc0007f7e60, 0x1186fe0, 0xc00177a0e0, 0xc001073b00)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/simulator.go:463 +0x399
net/http.HandlerFunc.ServeHTTP(0xc000aec290, 0x1186fe0, 0xc00177a0e0, 0xc001073b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1bbb5e0, 0x1186fe0, 0xc00177a0e0, 0xc001073b00)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000f74ea0, 0x1186fe0, 0xc00177a0e0, 0xc001073b00)
	/usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000c68640, 0x1188860, 0xc001312740)
	/usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4`

**Comment by anderseknert** [comment]
Hi there 👋 Did you open this in the wrong project? AFAICS, there's nothing OPA-related in that command, or in the trace.

**Comment by dhananjaysarkin** [comment]
got created in the wrong project. issue is related govmomi.
