### ISSUE TITLE
Error rego_type_error: undefined function redis.get upon registering a plugin and running opa as a server.

### ISSUE THREAD

**Issue by anuraagramesh** [open-policy-agent/opa#6427]
## Short description 

I am getting the below error after registering [this](https://github.com/tibotix/opa-redis-plugin) plugin and running `opa run` as a server.

`error: initialization error: 1 error occurred: ./main.rego:6: rego_type_error: undefined function redis.get`

I have raised [this](https://github.com/tibotix/opa-redis-plugin/issues/10) issue in case the plugin implementation is incorrect but seems to be similar to [2738](https://github.com/open-policy-agent/opa/issues/2738) but in `opa run` instead of `opa build`. 

OPA version : `v0.58.0`

## Steps To Reproduce

1. Run Redis instance locally at `localhost:6379`
2. Create a new folder and navigate into it. 
3. Command - `go mod init opa-redis-plugin`
4. Create file - main.go (attached)
5. Command - `go mod tidy`
6. Command - `go build -o opa++`
7. Create file - config.yaml (attached)
8. Create file - main.rego (attached)
9. Command - `./opa++ run -s -c config.yaml ./main.rego`

The last command above (9) results in the below error : 

`error: initialization error: 1 error occurred: ./main.rego:6: rego_type_error: undefined function redis.get`

## Expected behavior

The server should start successfully and we should be able to make http calls to it.

## Additional context

Running opa as interactive shell without the rego policy (main.rego) and then executing redis commands works fine and is able to get/set values from locally running Redis instance. 

## Files 
main.go 

```
package main

import (
	"os"

	"github.com/open-policy-agent/opa/cmd"
	"github.com/open-policy-agent/opa/runtime"

	opa_redis_plugin "github.com/tibotix/opa-redis-plugin/plugin"
)

func main() {
	runtime.RegisterPlugin(opa_redis_plugin.PluginName, opa_redis_plugin.Factory{})

	if err := cmd.RootCommand.Execute(); err != nil {
		os.Exit(1)
	}
}
```

config.yaml

```
plugins:
  redis:
    enabled: true
    address: "redis://default@127.0.0.1:6379/0"
    max_retries: 3
    dial_timeout_in_seconds: 8.0
    read_timeout_in_seconds: 2.0

```

main.rego

```
package main

default allow := false                              # unless otherwise defined, allow is false

allow := true {                                     # allow is true if...
    redis.get("xyz") == "1"                          # there are zero violations.
}
```

**Comment by srenatus** [comment]
It could be related to how the policy passed on the CLI is loaded vs when the plugin is started. To figure that out:

❓ Does it work
1. when  using the policy API to upsert the policy that's using the plugin's builtin?
2. when using a bundle with such a policy?

**Comment by anuraagramesh** [comment]
Hey @srenatus , thanks for your response. 



> 1. when  using the policy API to upsert the policy that's using the plugin's builtin?

Yes, this did work. 

```
curl --location --request PUT 'localhost:8181/v1/policies/redispolicy?pretty=true' \
--header 'Content-Type: text/plain' \
--data-raw 'package main

default allow := false

allow := true {
    redis.get("xyz") == "1"
}'
```


> 2\. when using a bundle with such a policy?

No, this did not work. Here is what I tried : 

a. `opa build -b .` - fails with same error 
b. `tar -czf bundle.tar.gz main.rego` and then `./opa++ run --bundle ./bundle/bundle.tar.gz` - fails with same error

**Comment by srenatus** [comment]
Thanks for digging in. I think the plugin should register its new builtins in an init() function. They won't work until the plugin is started, but they'll be accepted by the compiler then.

Also note that since the config of them lives in the plugin, it cannot ever ever work with `opa eval`, since that doesn't start plugins iirc.

Am alternative would be to pass all connection info with the built-in call, similar to how http.send works.

**Comment by anuraagramesh** [comment]
Could you please point me to an example implementation of the init() function? I am new to Go and OPA, I apologize if I am missing something obvious. 

I tried the below which does not work : 

main.go 

```
package main

import (
	"os"

	"github.com/open-policy-agent/opa/cmd"
	"github.com/open-policy-agent/opa/runtime"

	opa_redis_plugin "github.com/tibotix/opa-redis-plugin/plugin"
)

func init() {
	runtime.RegisterPlugin(opa_redis_plugin.PluginName, opa_redis_plugin.Factory{})
}

func main() {

	if err := cmd.RootCommand.Execute(); err != nil {
		os.Exit(1)
	}
}
```

`go build -o opa++`

`./opa++ run -s -c config.yaml ./main.rego`

**Comment by srenatus** [comment]
https://github.com/tibotix/opa-redis-plugin/blob/master/internal/internal.go#L100 the commands need to be registered on init. They'll have to fail until the plugin is started, but they should them at least be known to the compiler where necessary.

**Comment by anuraagramesh** [comment]
Thanks for sharing the specifics. I will try this with the help of the plugin owner and see if it works.

**Comment by anuraagramesh** [comment]
Hey @srenatus , thanks for your prompt response and timely support. The plugin owner was able to make changes as per your comments and the plugin works as expected now. Thank you. I am closing the ticket now and will get back to you in case of any queries during subsequent testing.
