### ISSUE TITLE
[opa-envoy-plugin] Allowed key in response

### ISSUE THREAD

**Issue by PietervdWerk** [open-policy-agent/opa#6431]
## Short description 
In most examples using opa the `allow` key is used, as well as the documentation for the opa-envoy-plugin's [Additional Control documentation](https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-additional-controls). However, the plugin specifically looks for the [`allowed`](https://github.com/open-policy-agent/opa-envoy-plugin/blob/66532f1bd28ee3d57f39da1b7167b4315364a4b3/envoyauth/response.go#L96C13-L96C13) key instead:

```go
if val, ok = decision["allowed"]; !ok {
	return false, fmt.Errorf("unable to determine evaluation result due to missing \"allowed\" key")
}
```

## Expected behavior
The documentation shows a policy using the `allow` key which is generally used, I expected the plugin to look for the `allow` key.

## Additional context
To make it backwards compatible I propose supporting the 'allow' and 'allowed' key.

**Comment by anderseknert** [comment]
Hi there @PietervdWerk 👋 Just in the next section there's an explanation for how to compose the output document (i.e. the response): https://www.openpolicyagent.org/docs/latest/envoy-primer/#output-document

> To construct that output object using the policies demonstrated in the last section, you can use the following Rego snippet. Notice that we are using partial object rules so that any variables with undefined values simply have no key in the result object.

```rego
result["allowed"] := allow
result["headers"] := headers
result["response_headers_to_add"] := response_headers_to_add
result["request_headers_to_remove"] := request_headers_to_remove
result["body"] := body
result["http_status"] := status_code
```

**Comment by PietervdWerk** [comment]
Yes I understand, though I would love a way to configure this.

**Comment by ashutosh-narkar** [comment]
Closing this as the docs cover the required fields in the output document and hence seems not much is needed here.
