### ISSUE TITLE
Failed to flush decision logs on graceful shutdown

### ISSUE THREAD

**Issue by xiuwangthoughtworks** [open-policy-agent/opa#6443]
## Short description 
Failed to flush decisions log when run opa server with option --shutdown-wait-period  

Examples:

* OPA version: openpolicyagent/opa:0.43.0-envoy-rootless
* For server, the flags/configuration that provided to OPA:
```
- args:
    - run
    - --server
    - --config-file=/config/conf.yaml
    - --addr=localhost:8181
    - --diagnostic-addr=0.0.0.0:8282
    - --shutdown-grace-period=5
    - --shutdown-wait-period=5
    - --log-level=info
    image: openpolicyagent/opa:0.58.0-envoy-rootless
```
* For server, any relevant log messages from OPA:
```
Waiting 5s before initiating shutdown...
Shutting down...
Server shutdown.
Stopping bundle loader.
Stopping decision logger.
Flushing decision logs.
Status update failed: Post "http://marketplace-demo-dev-slp-svc.styra-istio-system:8080/v1/status": dial tcp 172.20.98.4:8080: connect: connection refused.
Error flushing decisions: log upload failed: Post "http://marketplace-demo-dev-slp-svc.styra-istio-system:8080/v1/logs": dial tcp 172.20.98.4:8080: connect: connection refused
Plugin stopped with decisions possibly still in buffer.
Stopping status reporter.
Status update failed: Post "http://marketplace-demo-dev-slp-svc.styra-istio-system:8080/v1/status": dial tcp 172.20.98.4:8080: connect: connection refused.
Listener exited.
```

## Steps To Reproduce
1. Run opa server with args --shutdown-wait-period

## Expected behavior
Can flush decision logs on graceful shutdown successfully

**Comment by ashutosh-narkar** [comment]
OPA tries to flush the decision logs by uploading them to the remote server. The logs show that the upload failed as the server was not reachable. OPA will retry but if the deadline is reached the plugin is stopped as OPA is shutting down.

**Comment by xiuwangthoughtworks** [comment]
The remote server is always there without any changing when OPA server graceful shutdown, and this issue only happens when running OPA server with args --shutdown-wait-period.
I noticed that [the same issue was solved before](https://github.com/open-policy-agent/opa/pull/2746), but the fix code has been changed back.

**Comment by ashutosh-narkar** [comment]
Closing this as it does not seem to a bug in OPA. Feel free to re-open if you think that's not the case.

**Comment by xiuwangthoughtworks** [comment]
I finally find the root cause is because of `istio-proxy` container shutdown before `opa-istio` container, all the connection will be refused once `istio-proxy` container shutdown.

**Comment by anderseknert** [comment]
Thanks for reporting back @xiuwangthoughtworks 👍 Perhaps it'll help someone else using a similar configuration.
