### ISSUE TITLE
OPA fmt in OPA 0.58+ improperly stripping assignment and term from chained rules

### ISSUE THREAD

**Issue by grantlanglois** [open-policy-agent/opa#6467]
## Short description 
OPA 0.58.0, specifically #6323 appears to have introduced what I believe to be a regression in opa fmt where the assignment operator and term in the rule heads of chain rules are removed from the re-written rule head. 

## Steps To Reproduce
In OPA 0.58+ the OPA fmt'ing the following:

```rego
instances_or_clusters[id] = ret {
  instances = input.resources["aws_db_instance"]
  ret = instances[id]
} {
  clusters = input.resources["aws_rds_cluster"]
  ret = clusters[id]
}
```

Results in the following:

```rego
instances_or_clusters[id] = ret if {
	instances = input.resources.aws_db_instance
	ret = instances[id]
}

instances_or_clusters[id] if {
	clusters = input.resources.aws_rds_cluster
	ret = clusters[id]
}
```

## Expected behavior

```rego
instances_or_clusters[id] = ret if {
	instances = input.resources.aws_db_instance
	ret = instances[id]
}

instances_or_clusters[id] = ret if {
	clusters = input.resources.aws_rds_cluster
	ret = clusters[id]
}
```

**Comment by anderseknert** [comment]
Thanks for the bug report, @grantlanglois! That does look like an oversight on my part. I'll take a look.
