### ISSUE TITLE
[opa-envoy-plugin] Decision Id in check response

### ISSUE THREAD

**Issue by PietervdWerk** [open-policy-agent/opa#6519]
## What is the underlying problem you're trying to solve?
When using the data api the decision_id is returned in the [response](https://github.com/open-policy-agent/opa/blob/main/docs/content/rest-api.md#response-message) when decision logging is enabled, but the response of the external authorization's check endpoint exposed by the opa-envoy-plugin does not have an option to return the decision_id.

Having an decision_id in a denied request allows our users to get help by our support team to identify problems.

## Describe the ideal solution
Include the decision_id in the response headers by default, or a way to enable this behavior.

## Additional Context
I would love a discussion on what solution would be best for the project and contribute the solution myself.

**Comment by srenatus** [comment]
I like this idea, thanks for bringing it up!

What do you think about using _dynamic metadata_ for this? I was having a quick look, and couldn't find it, but I'd guess there's a way to convert that into the response or request headers of your choosing via filters...?

**Comment by ashutosh-narkar** [comment]
Adding this to the _dynamic metadata_ and then having it consumed by the next filter makes sense to me as well. You can probably leverage the [Lua filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#dynamic-metadata-object-api) and then inject the metadata in the response flow.

**Comment by PietervdWerk** [comment]
I agree, the dynamic metadata would be a good place for it. I've created a pull request to add the decision id by default. Is this the expected behaviour or should there be a configuration toggle to enable this?

**Comment by srenatus** [comment]
I think it's fine to always include it if its always defined... What do you think, @ashutosh-narkar

**Comment by PietervdWerk** [comment]
I've added some tests and opened the PR for review, please let me know if you would like to see anything changed or added to my implementation of this feature. 👍
