### ISSUE TITLE
run subcommand ignoring --v1-compatible

### ISSUE THREAD

**Issue by ear7h** [open-policy-agent/opa#6536]
## Short description

`opa run --v1-compatible` does not seem to be turning on the v1 compiler.

```
$ opa version
Version: 0.60.0
Build Commit: 
Build Timestamp: 
Build Hostname: 
Go Version: go1.21.4
Platform: darwin/arm64
WebAssembly: unavailable
```

## Steps To Reproduce

```
echo "allow { true }\nallow" | opa run --v1-compatible
```

## Expected behavior

```
rego_parse_error: `if` keyword is required before rule body
```

## Additional context

The `build` command also seems to ignore `v1-compatible`. But `test` and `parse` do not.

Looking around the codebase, it's probably caused by this:

https://github.com/open-policy-agent/opa/blob/c0589c1272020ee8681a78fe432393008a28efb8/ast/parser.go#L127-L130

**Comment by johanfylling** [comment]
As @ashutosh-narkar says, `--v1-compatible` support for the `run` command will arrive in a future release of OPA. The `build` command is however supported, so if this doesn't behave as expected, there might be a bug.

Could you please provide an example that triggers the issue? 
If I run `opa build policy.rego --v1-compatible` (OPA 0.60.0) on the following policy, which resembles the one in your `steps to reproduce`: 

```
package test

allow { true }
```

I get the expected error: 

```
rego_parse_error: `if` keyword is required before rule body
```
