### ISSUE TITLE
Add Rego-Version attribute to Bundle

### ISSUE THREAD

**Issue by johanfylling** [open-policy-agent/opa#6578]
When OPA builds a bundle, the Rego version (0.x or 1.0) should be included as a manifest attribute.

When the version of the contained Rego is advertised by the bundle through this attribute, the OPA runtime loading it will not be required to be executed with the `--v1-compatible` (or future `--v0-compatible`) flag to correctly parse and evaluate the bundle's modules.

A bundle's rego-version attribute should take precedence over any applied `--v1-compatible`/`--v0-compatible` flag.

**Comment by ashutosh-narkar** [comment]
@johanfylling can this be closed?

**Comment by johanfylling** [comment]
Yes. Funny it didn't auto-close with the PR ..
