### ISSUE TITLE
Support for Unsigned Payload or provided content sha256 in AWS signing

### ISSUE THREAD

**Issue by prasanthj** [open-policy-agent/opa#6581]
## What is the underlying problem you're trying to solve?
AWS signing seems to only support signed payloads. AWS SDK typically supports both payload signing and disabling it in which case "UNSIGNED-PAYLOAD" will be set for `x-amz-content-sha256`. AWS signer implementation in OPA always generates content SHA256 from the request body [here](https://github.com/open-policy-agent/opa/blob/fe02b4f196c6f2af2b51ade9faaf562e11f00791/internal/providers/aws/signing_v4.go#L122) 
Add an ability to support unsigned payload or just use the value provided via input headers `x-amz-content-sha256`. This will enable uses cases where OPA is used only for signing requests (without doing http.send) where the payload is not known upfront. 

## Describe the ideal solution
If the input headers contain `x-amz-content-sha256` do not generate the content sha from request body instead use whatever is provided in the input.

## Describe a "Good Enough" solution
Provide a boolean argument to use unsigned payload.

**Comment by philipaconrad** [comment]
I think I most agree with the "ideal solution" described above. :slightly_smiling_face:

Allowing the user to pass through the `x-amz-content-sha256` header themselves (overriding any content hashing we do, or skipping it altogether!) seems a good way to make the unsigned payload use-case possible, *without* requiring the API surface to significantly change.

I would request that if this approach is implemented, that we add an unsigned payload usage example to the docs for `providers.aws.sign_req`. The "ideal" behavior could be a little surprising if it's undocumented!

**Comment by prasanthj** [comment]
I will send a PR shortly. Thanks for the pointer to doc, will make sure to update it.
