### ISSUE TITLE
CI: Upgrade to `actions/upload-artifact@v4` and `actions/download-artifact@v4`

### ISSUE THREAD

**Issue by sean-r-williams** [open-policy-agent/opa#6650]
## What is the underlying problem you're trying to solve?

GitHub Actions is currently using `actions/upload-artifact@v3`, which has known issues (see actions/upload-artifact#443). Looking at PRs like #6636, you can see [several](https://github.com/open-policy-agent/opa/actions/runs/8461684131/job/23181883494) [failed](https://github.com/open-policy-agent/opa/actions/runs/8461368696/job/23181063059) [checks](https://github.com/open-policy-agent/opa/actions/runs/8400402750/job/23007632765) due to 503s from uploading the artifact.

## Describe the ideal solution

GitHub has [released](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) v4 of their Artifacts actions last December. According to a GitHub dev (see https://github.com/actions/upload-artifact/issues/443#issuecomment-1856443273), these are powered by an entirely new backend that should resolve this issue.

## Describe a "Good Enough" solution

If something is explicitly chaining OPA to v3 of the Artifacts actions, providing a mechanism for PR authors to trigger a rerun would be appreciated.

**Comment by sean-r-williams** [comment]
FWICT, the `pull-request` workflow should be directly compatible with v4.

For `post-tag` and `post-merge`, however, the lack of unique artifact names will conflict with the new [unique artifact label requirements](https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact).

**Comment by anderseknert** [comment]
> providing a mechanism for PR authors to trigger a rerun would be appreciated

That would be useful for sure. If anyone knows of a way to accomplish that, let us know!

**Comment by ashutosh-narkar** [comment]
@sean-r-williams if you'd like to submit a fix for the `pull-request` workflow that would be great. We can look into doing the update for the others as well.

**Comment by srenatus** [comment]
I think this is done.
