### ISSUE TITLE
Add latest-envoy for linux/arm64

### ISSUE THREAD

**Issue by 3goats** [open-policy-agent/opa#6666]
Hi,

I'm trying to build out a test/dev environment using linux/arm64 platforms. Is there any chance you can provide the envoy images along with the standard linux/amd64 images ?

**Comment by ashutosh-narkar** [comment]
Closing this as we have an existing issue [here](https://github.com/open-policy-agent/opa/issues/4965).  If you'd like to contribute, the details are in the linked issue. Thanks.
