### ISSUE TITLE
OPA / blog

### ISSUE THREAD

**Issue by hpvd** [open-policy-agent/opa#6687]
It took me at least 3 visits, to understand OPAs blog is not **orphaned**, it's only the sorting... :-)

The first three time I only see the **2021** and thought: hmm is usage of OPA really future-proof if the blog is that old?

https://blog.openpolicyagent.org/

on desktop:

![2024-04-09_13h56_35](https://github.com/open-policy-agent/opa/assets/5681880/65bc0b5e-9177-45af-9374-08607f312142)

on mobil:

![2024-04-09_14h01_31](https://github.com/open-policy-agent/opa/assets/5681880/65a750cf-6384-4fe1-a8bf-1a08304919ec)

**Comment by anderseknert** [comment]
Heh, yeah, perhaps it's time to move on past graduation :) I've moved that out of the header now. Thanks for the pointer!
