### ISSUE TITLE
A pre built binary for darwin/amd64 wasn't released at v0.64.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [open-policy-agent/opa#6720]
https://github.com/open-policy-agent/opa/releases/tag/v0.64.0

<img width="949" alt="image" src="https://github.com/open-policy-agent/opa/assets/13323303/e435d081-b8a0-4a21-9ff7-5f78cd9747ee">

```console
$ gh release view -R open-policy-agent/opa --json assets v0.64.0 -q '.assets[].name'
opa_darwin_arm64
opa_darwin_arm64.sha256
opa_darwin_arm64_static
opa_darwin_arm64_static.sha256
opa_linux_amd64
opa_linux_amd64.sha256
opa_linux_amd64_static
opa_linux_amd64_static.sha256
opa_linux_arm64_static
opa_linux_arm64_static.sha256
opa_windows_amd64.exe
opa_windows_amd64.exe.sha256
```

The asset `opa_darwin_amd64` wasn't released.

**Comment by suzuki-shunsuke** [comment]
I think this is because the architecture of GitHub Actions Runner `macos-latest` was changed from amd64 to arm64.
I'll send a pull request.

https://github.com/open-policy-agent/opa/blob/75cc90abee5e0b7b3c2a5c0fcbb3c5f4b2b8a80a/.github/workflows/post-merge.yaml#L111

https://github.com/open-policy-agent/opa/blob/75cc90abee5e0b7b3c2a5c0fcbb3c5f4b2b8a80a/.github/workflows/post-merge.yaml#L127

https://github.com/open-policy-agent/opa/blob/75cc90abee5e0b7b3c2a5c0fcbb3c5f4b2b8a80a/Makefile#L19

https://github.com/open-policy-agent/opa/blob/75cc90abee5e0b7b3c2a5c0fcbb3c5f4b2b8a80a/Makefile#L286-L291

**Comment by ashutosh-narkar** [comment]
Good catch. We should probably pin the macos version to avoid this.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/open-policy-agent/opa/pull/6721
