### ISSUE TITLE
Support EKS Pod Identities for Signing S3 Bundle Requests

### ISSUE THREAD

**Issue by alghanmi** [open-policy-agent/opa#6724]
## What is the underlying problem you're trying to solve?
Currently, OPA supports [AWS Signatures using IAM Roles for Service Accounts (IRSA) in EKS](https://www.openpolicyagent.org/docs/latest/configuration/#using-eks-iam-roles-for-service-account-web-identity-credentials) to sign and retrieve bundles. [EKS Pod Identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) is _new_ way to manage permissions in EKS and would like OPA to add support for it.

## Describe the ideal solution
I don't know if this solution is inline with the OPA project policies, but if OPA used the AWS SDK to access S3 an [SDK upgrade](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html) would have added support for EKS Pod Identities. That said, I understand if the project does not want to uptake the SDK.  

## Describe a "Good Enough" solution
Similar to OPA's support of [IRSA](https://www.openpolicyagent.org/docs/latest/configuration/#using-eks-iam-roles-for-service-account-web-identity-credentials), [Pod Identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-configure-pods.html) export the `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` that can be used to retrieve the auth token.

## Additional Context
In November 2023, [AWS announced EKS Pod Identity](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-eks-pod-identity/) which is a a new feature that simplifies Kubernetes applications to obtain AWS IAM permissions. It is in a way the successor to [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) (IRSA). Many Kubernetes administrators are migrating from IRSA to Pod Identities for its simplified workflow, the ability to share roles across clusters and its support of session tags.

**Comment by ashutosh-narkar** [comment]
Adding a new method to provide creds seems fine. Feel free to contribute if you'd like. OPA does not vendor the SDK but you can see the implementations of existing providers for reference. Also the code [here](https://github.com/open-policy-agent/opa/tree/main/internal/providers/aws) might be helpful.

**Comment by wangchenjie629** [comment]
Kindly ask if there is somebody working for this issue?If not,I'm glad to undertake it. I am relatively new to contributing to open source projects,

**Comment by wangchenjie629** [comment]
Kindly ask if there is somebody working for this issue? If not,I'm glad to undertake it.
I ‘m relatively new to contributing to open source projects, but I am eager to learn and will do my best to complete this task.
Thanks ! @ashutosh-narkar

**Comment by ashutosh-narkar** [comment]
Sure @wangchenjie629 if you'd like to work on this please go ahead. Please let us know if you have any questions. Thanks.
