### ISSUE TITLE
Arrays are not explained in the language description

### ISSUE THREAD

**Issue by SpecLad** [open-policy-agent/opa#6727]
## Short description 
In https://www.openpolicyagent.org/docs/v0.64.1/policy-language/#sets it says:

> In addition to arrays and objects, Rego supports set values.

But this is the first time arrays are mentioned in this document. I would expect to see a section titled "Arrays" under "Composite Values" that specifically explains arrays.

## Steps To Reproduce
Not applicable

## Expected behavior
Not applicable

## Additional context

N/A

**Comment by anderseknert** [comment]
Agreed, it does seem like an oversight that arrays are missing entirely from that section. Would you consider adding that to the docs? 🙂 If not, let me know and I can do that.

**Comment by SpecLad** [comment]
Sorry, but I'm not well-versed in Rego enough to add something like that myself.

**Comment by anderseknert** [comment]
No worries! I'll add something. Thanks for reporting 👍
