### ISSUE TITLE
zinc.systems  has adopted OPA

### ISSUE THREAD

**Issue by chippyash** [open-policy-agent/opa#6776]
### Organization Name

Zinc Digital Business Systems

### Organization Website

zinc.systems

### How is your organization using OPA?

Implementing RBAC ACL controls

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by anderseknert** [comment]
The Rego Playground is set up to run all of the [Regal](https://docs.styra.com/regal) linter rules by default, but that's just a default set for the purpose of the playground. There is no requirement to agree with all of the rules :) If you download Regal yourself, you can easily [disable](https://docs.styra.com/regal#ignoring-rules) any rule you disagree with, like the `opa-fmt` rule. Here's an example of a Regal configuration file to disable the formatter rule:

**.regal/config.yaml**
```yaml
rules:
  style:
    opa-fmt:
      level: ignore
```

**Comment by anderseknert** [comment]
Hey! I think we're good to close this now? There wasn't a whole lot of data to add to the adopters file, but feel free to submit a PR with some more. You'll find it [here](https://github.com/open-policy-agent/opa/blob/main/ADOPTERS.md).
