### ISSUE TITLE
Strange null results for multi-expression-query in case of `false`

### ISSUE THREAD

**Issue by nkey0** [open-policy-agent/opa#6780]
Version: 0.64.1

In case of query with semicolon and 'false' result - query returns nil.

This is a test to reproduce an issue:

```go

func TestMultiQueryBug(t *testing.T) {
	set, _ := rego.New(
		rego.Query("true;0"),
	).Eval(context.Background())

	if set == nil {
		t.Fatal()
	}

	set, _ = rego.New(
		rego.Query("false;0"),
	).Eval(context.Background())

	if set == nil {
		t.Fatal()
	}
}
```

**Comment by srenatus** [comment]
What did you expect? The query `false;0` does not yield any results. It's a *single* query with two expressions, not a "multi-query" of two separate queries -- there's no such thing in Rego, I'm afraid.

**Comment by nkey0** [comment]
I am expect to receive the same results as for `true;0` except values should differ.

The first 
```if set == nil {
		t.Fatal()
``` is not failing, only the second one.

In the real case it is a query like:
`is_allowed;deny_reasons`

So, I want to get reasons if `is_allowed` == false, but currently I can't.

Or I should use ugly hack like `is_allowed_as_int;deny_reasons`;

**Comment by srenatus** [comment]
In a query, `;` is basically **and**. So you cannot treat it as `||`.

However, you can change your policy, I suppose, to get this:
> So, I want to get reasons if is_allowed == false, but currently I can't.

```rego
result.allow := is_allowed
result.reasons := deny_reasons
```
then query `data.your.package.result` and inspect object you get back. It should have either an `allow` or a `reasons` key.

**Comment by nkey0** [comment]
> In a query, ; is basically and.
OMG, I was sure it is just some kind of separator for the statements :)

Thanks for you help.
