### ISSUE TITLE
Add DCO checking

### ISSUE THREAD

**Issue by caniszczyk** [open-policy-agent/opa#680]
CNCF projects are expected to follow the DCO.

It's a one click install to enable this for all the OPA repos:
https://github.com/integration/dco

**Comment by caniszczyk** [comment]
@timothyhinrichs let me know when you want me to enable this for all of OPA, it will require all commits to be signed off moving forward (i.e., git commit -s)

**Comment by timothyhinrichs** [comment]
Torin told me we already set up DCO for all repos.  All contributors were
informed last week (git commit -s).

Tim

**Comment by caniszczyk** [comment]
I can confirm this is done: https://github.com/organizations/open-policy-agent/settings/installations/114275

Thanks :)
