### ISSUE TITLE
Define vulnerability reporting process

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#685]
We need to define a vulnerability reporting process according CII best practices. Creating a ticket to track the work.

Minimally, we need to establish a channel to report security issues (e.g., security@openpolicyagent.org) and then update the website with information on how to report them.

**Comment by caniszczyk** [comment]
@tsandall I'd recommend cargo culting what Envoy did:

https://github.com/envoyproxy/envoy/blob/master/SECURITY_RELEASE_PROCESS.md

**Comment by tsandall** [comment]
Fixed by #733
