### ISSUE TITLE
AST: missing location in some rule head refs 

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6860]
This was [reported in Regal](https://github.com/StyraInc/regal/issues/899), but my brief investigation suggests that the issue originates in OPA. Regal expects each part of a ref to include a `location`. However, a policy like this:

```rego
package p

import rego.v1

a.b if true

a.b := true
```

Transforms to an AST where the first `a.b` has no ref locations, and the second `a.b` does.

**rule.head.ref "a.b if true"**
```json
[
  {
    "type": "var",
    "value": "a"
  },
  {
    "type": "string",
    "value": "b"
  }
]
```

**rule.head.ref "a.b := true"**
```json
[
  {
    "location": {
      "col": 1,
      "file": "p.rego",
      "row": 7,
      "text": "b3V0cHV0"
    },
    "type": "var",
    "value": "output"
  },
  {
    "location": {
      "col": 8,
      "file": "p.rego",
      "row": 7,
      "text": "InVzZXJLYXJtYSI="
    },
    "type": "string",
    "value": "userKarma"
  }
]
```

I believe this inconsistency is a bug.

**Comment by kd-labs** [comment]
can I pick this up ?? ...it would be my first to contribute to opa codebase
