### ISSUE TITLE
rego_unsafe_var_error in array comprehensions

### ISSUE THREAD

**Issue by vvbogdanov87** [open-policy-agent/opa#6874]
I get the `resourcelimits.rego:178: rego_unsafe_var_error: var field is unsafe` error when using a variable inside the array comprehension.
```
violation[{"msg": msg}] {
	general_violation[{"msg": msg, "field": "containers"}]
}

violation[{"msg": msg}] {
	general_violation[{"msg": msg, "field": "initContainers"}]
}

general_violation[{"msg": msg, "field": field}] {
	max_cpu_orig := input.parameters.cpu
	max_cpu := canonify_cpu(max_cpu_orig)

	cpus := [c |
		container := input.review.object.spec[field][_]
		cpu_orig := container.resources.requests.cpu
		c := canonify_cpu(cpu_orig)
	]
	all := sum(cpus)

	# container := input.review.object.spec[field][_]
	
	all > max_cpu
	msg := sprintf("pod cpu request <%v> is higher than the maximum allowed of <%v>", [all, max_cpu_orig])
}
```
The error disappears if I uncomment the line `# container := input.review.object.spec[field][_]`.
Note that line `178` in the error message is the line `general_violation[{"msg": msg, "field": field}] {`
I get the same error in gatekeeper logs when applying a `ConstraintTemplate` to kubernetes and when I execute tests locally via `opa test .`
```shell
$ opa version
Version: 0.66.0
Build Commit: 91348a8ccc9fe54196e9874193a41eb5c5731de3
Build Timestamp: 2024-06-27T14:16:32Z
Build Hostname: 67d0ba19bc9b
Go Version: go1.22.4
Platform: linux/amd64
WebAssembly: available
```

**Comment by ashutosh-narkar** [comment]
In the line `container := input.review.object.spec[field][_]`, you're iterating over the data and the variable `field` is assigned to a value in the data which is then made part of the policy decision. When you comment out that line you get the error as you reported. In the `cpus` line, the variable `field` is scoped within the body of the comprehension.

**Comment by anderseknert** [comment]
@vvbogdanov87 the field variable won't escape the scope in which it's declared. I'm not sure why that field is included in the violation, as the total is aggregated from _all_ container types and not tied to one specifically. Either way, feel free to continue asking questions here and we'll answer, but I think we can close this issue.
