### ISSUE TITLE
Shutdown Log missing in OPA

### ISSUE THREAD

**Issue by vagrawal-nc** [open-policy-agent/opa#6884]
Hi,

We are experiencing some issue with OPA logging. We could see all requests/response and all logs when OPA starts however when OPA Shutting down that log is missing. Please see below logs which shows OPA started twice but there is no log for Shutting down.

We have stopped and started many times and each time only logs related to start and not for Shutting down.

We have tried the log-level both **info** and **Debug** but no change in logging. 

run --server --log-level debug --set=decision_logs.console=true

Currently OPA is latest version v0.66.0

![image](https://github.com/user-attachments/assets/b3d42a87-565f-4041-8e4c-2a2c894a6226)

Kindly someone confirm if any additional argument needed to get the Shutting down logs.

Thanks,

**Comment by charlieegan3** [comment]
These are the logs I see when SIGTERMing and SIGKILLing OPA:

```
$ opa run -s . # sigterm
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server. OPA is running on a public (0.0.0.0) network interface. Unless you intend to expose OPA outside of the host, binding to the localhost interface (--addr localhost:8181) is recommended. See https://www.openpolicyagent.org/docs/latest/security/#interface-binding","time":"2024-07-23T15:46:00+01:00"}
{"level":"info","msg":"Shutting down...","time":"2024-07-23T15:46:03+01:00"}
{"level":"info","msg":"Server shutdown.","time":"2024-07-23T15:46:03+01:00"}

$ opa run -s . # sigkill
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server. OPA is running on a public (0.0.0.0) network interface. Unless you intend to expose OPA outside of the host, binding to the localhost interface (--addr localhost:8181) is recommended. See https://www.openpolicyagent.org/docs/latest/security/#interface-binding","time":"2024-07-23T15:46:09+01:00"}
Killed: 9
```

I tested with pkill:

```sh
$ pkill opa # sends SIGINT

$ pkill -SIGKILL opa
```

Where are you running OPA and how are you collecting the logs? My guess is that the final logs from OPA are not being collected by your log aggregation.

**Comment by vagrawal-nc** [comment]
Thanks @charlieegan3 for your response. 

We are using Azure Web App for Container service which is connected with Azure Log Analytics service. All the console logs are sent into Azure Log Analytics. 

I could see all other logs like each requests, responses and startup etc. however only Shutting down is missing. We tried many times and behavior remain same hence log as ticket.

I am not sure any issues at log aggregation side since rest all logs coming except shutting down and no filter or settings have been applied.

Any other settings which enforce to send these logs again from OPA ?

Thanks,

**Comment by charlieegan3** [comment]
In this use case, OPA is not sending the logs to Azure Log Analytics, they are being collected internally to the Azure platform.

My theory remains that the final logs before the OPA container is shutdown and presumably deleted are missed by the log collector within Azure.

Have you tested another program that outputs when it gets a SIGINT to see if those logs are shown?

Here is a simple script you could run first testing:

```sh
#!/bin/bash

trap 'echo "shutting down"; exit 0' SIGINT

echo "Sleeping... Press Ctrl+C to interrupt."

# Sleep indefinitely
while true; do
  sleep 1
done
```

**Comment by vagrawal-nc** [comment]
Yes, we tried locally in Docker and it is logging properly. Tried few times and seems logging as expected.

As you said, could be an issue from Azure Log collector and we can investigate further. 


![image](https://github.com/user-attachments/assets/ad102cfe-1d44-4be8-a15c-bb20c04a0e50)

Thanks for your support and we are good to close the thread.

**Comment by charlieegan3** [comment]
Thanks @vagrawal-nc, feel free to re-open if you do narrow the issue down to being caused by something in OPA.
