### ISSUE TITLE
NOt able to validate token in my OPA  container 

### ISSUE THREAD

**Issue by surikalyani** [open-policy-agent/opa#6892]
![image](https://github.com/user-attachments/assets/1dd656f0-c6c6-4ea9-85ef-c816ce3b7cc2)
I tested my data with https://play.openpolicyagent.org/p/9af2cRleIv   and it works there . 
I am not able to debug my rego policy , why token validation is failing ?How to debug data if policy is not returning as expected .

**Comment by anderseknert** [comment]
Hi @surikalyani! And apoliogies for the very late response here. I had missed this for some reason, and saw it now that the stale bot flagged it. If you're still having issues with this, I'd suggest raising that either in the [OPA community discussion board](https://github.com/orgs/open-policy-agent/discussions) or the [OPA Slack](https://slack.openpolicyagent.org/).

I don't believe this is a bug in OPA, so while I'll close this here, I'd be happy to help you in any of the above mentioned channels.
