### ISSUE TITLE
"rego_type_error: multiple default rules" should include all locations where found

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#6897]
```
1 error occurred: /path/to/authz.rego:5: rego_type_error: multiple default rules data.authz.allow found
```

This error commonly happens when more files than intended are included for compilation. The error message however isn't that helpful, as it only provides one of the locations. We should fix this so that all locations are reported.

**Comment by tjons** [comment]
https://github.com/open-policy-agent/opa/pull/7164 should resolve this one :)
