### ISSUE TITLE
Handle incorrect user input in OPA envoy plugin

### ISSUE THREAD

**Issue by rudrakhp** [open-policy-agent/opa#6901]
## Short description 

OPA version: `0.63.0`
Today the OPA envoy plugin tries to parse the URL and return a generic error in case it fails. 
Code [pointer](https://github.com/open-policy-agent/opa-envoy-plugin/blob/1d562bd408716a077d8cb6207c8e318c3b1d4157/envoyauth/request.go#L93).

## Steps To Reproduce

Pass an invalid URL to an OPA server running the envoy plugin.

## Expected behavior

Status returned should be 400/BadRequest, but is 503/Server error instead.

## Additional context

Is there any way to identify these kinds of errors and return user defined status codes instead?

**Comment by ashutosh-narkar** [comment]
@rudrakhp the return status code is something that's controlled by Envoy. By default, when OPA returns an error, Envoy should send back a `HTTP 403 Forbidden`. This behavior can be controlled by the `status_on_error` field in the Envoy config. More details [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthz). I'm surprised you're getting a 503.

**Comment by rudrakhp** [comment]
@ashutosh-narkar you are right, we have the `status_on_error` set to `503`. But I was more concerned about handling all OPA errors with a single status. For example, the incorrect path error should return a different status (4XX) than say an OPA internal server error (5XX). That's not possible today?
PS: Thanks for recategorising this as a question, incorrectly raised it as a bug.

**Comment by ashutosh-narkar** [comment]
> For example, the incorrect path error should return a different status (4XX) than say an OPA internal server error (5XX). That's not possible today?

Currently OPA is configured to return `500`, `403` and `200` codes. Feel free to submit a PR if you'd like to improve this. You should be able to start [here](https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/internal/internal.go).

**Comment by rudrakhp** [comment]
@ashutosh-narkar thanks for the pointer, while I have a look at this can you also confirm if the status that the plugin returns can be transparently exposed to envoy as well? Do we need to configure a single `status_on_error` in the envoy filter?

**Comment by ashutosh-narkar** [comment]
> while I have a look at this can you also confirm if the status that the plugin returns can be transparently exposed to envoy as well? 

I think it should. The `status_on_error ` is when the server returns an error or cannot be reached. I would imagine the allow/deny response status gets passed as is.
