### ISSUE TITLE
Server opa should be able to Listen to a Unix Domain Socket

### ISSUE THREAD

**Issue by FrankJLhota** [open-policy-agent/opa#692]
This would be handy for testing, and for instances where opa services multiple local processes.

**Comment by tsandall** [comment]
This question has come up from a few users and while it's not been a blocker, it would be nice to have.

From an implementation point of view, the following changes should be made (minimally):

* [Add an extra listener loop in server.go](https://github.com/open-policy-agent/opa/blob/master/server/server.go#L298). The listener should open/create a unix domain socket and then [serve the Server on it](https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74).

* Plumb a file path argument for the domain socket through from the `cmd` package to the `server` package. See other server parameters for examples.

* If feasible, add an integration test that starts the server with unix domain socket listener enabled and validates that the HTTP API is served correctly.

**Comment by JAORMX** [comment]
Addressing this here https://github.com/open-policy-agent/opa/pull/752

**Comment by JAORMX** [comment]
Fixed in https://github.com/open-policy-agent/opa/pull/752

Should this be closed?

**Comment by tsandall** [comment]
Done.
