### ISSUE TITLE
builtins: Error JWT but payload is not JSON when using io.jwt.encode_sign with set as payload value

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#6925]
In this example, when running with all built-in errors, we get this:

```sh
1 error occurred: policy.rego:5: eval_builtin_error:
io.jwt.encode_sign: type is JWT but payload is not JSON
```

Without built-in errors, we get result1 as being undefined. This appears to be because the set of `roles` is not marshalled to JSON correctly as when using an array the result is defined.

```rego
package play

import rego.v1

result1 := io.jwt.encode_sign(
	{
		"typ": "JWT",
		"alg": "HS256",
	},
	{"roles": {"set item 1"}}, {
		"kty": "oct",
		"k": "AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow",
	},
)

result2 := io.jwt.encode_sign(
	{
		"typ": "JWT",
		"alg": "HS256",
	},
	{"roles": ["array item 1"]}, {
		"kty": "oct",
		"k": "AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow",
	},
)
```

In our documentation, payload is meant to be `payload (object[string: any]) JWS Payload`.

So I think we either need to update these docs to make it clear that sets are not supported, OR, change the behaviour to support the use of sets. My hope is that since it's impossible (no token returned) to use `io.jwt.encode_sign` with any `set` as a payload key, there isn't anyone out there relying on this functionality, so updating it to support sets should be acceptable?

Source: https://openpolicyagent.slack.com/archives/CBR63TK2A/p1723557818289189

**Comment by ashutosh-narkar** [comment]
The error is coming from the `json.Valid` call which is part of the Go std lib. So we probably need to clarify the behavior here I think.

**Comment by charlieegan3** [comment]
While that payload arg is _meant_ to be valid JSON, I feel like users expect objects being passed around inside OPA to be JSON too, or at least convertible to JSON when needed.

In the linked thread, instead of  `{"roles": {"set item 1"}}` the set came from a set rule, like this:

```rego
payload["roles"] contains "role" if ...
```

While _we_ know this is a set, users often will only see this as an array as the only way to look at that data is to marshal it to JSON.

I think there is a good case to be made for converting sets to arrays here since it doesn't appear to have any backwards compatibility issues.

**Comment by ashutosh-narkar** [comment]
> In the linked thread, instead of {"roles": {"set item 1"}} the set came from a set rule, like this:

Ohh the payload is generated from a policy decision. I missed that. So if we were to convert the result to an array in the policy, that would have worked, correct?

**Comment by charlieegan3** [comment]
Sorry, that detail was lost in my trying to get a simple example.

But yes, that'd be correct! If we did `{"roles": [r| some r in payload["roles"]]}` that works. Only sets make this fail.

I still feel like this, or round-tripping via JSON as not being a great experience.

**Comment by charlieegan3** [comment]
I would say that the implementation is a pretty simple change. We have this function that supports returning an error:

```go
func builtinJWTEncodeSign(bctx BuiltinContext, operands []*ast.Term, iter func(*ast.Term) error) error {

	inputHeaders := operands[0].String()
	jwsPayload := operands[1].String()
	jwkSrc := operands[2].String()
	return commonBuiltinJWTEncodeSign(bctx, inputHeaders, jwsPayload, jwkSrc, iter)

}
```

It relies on the fact that `String()` is 'usually JSON', rather than using term.MarshalJSON. Even if we changed the implementation and avoided introducing any new error handling the issue would be fixed (I think).

```go
func builtinJWTEncodeSign(bctx BuiltinContext, operands []*ast.Term, iter func(*ast.Term) error) error {
	inputHeaders, _ := operands[0].MarshalJSON()
	jwsPayload, _ := operands[1].MarshalJSON()
	jwkSrc, _ := operands[2].MarshalJSON()
	return commonBuiltinJWTEncodeSign(bctx, string(inputHeaders), string(jwsPayload), string(jwkSrc), iter)
}
```

**Comment by ashutosh-narkar** [comment]
> (though I think it would be better to handle the errors as that's what builtinJWTEncodeSignRaw does)

Agreed.

**Comment by charlieegan3** [comment]
It's never as simple as one thinks... but this is one way to solve this: https://github.com/open-policy-agent/opa/pull/6934
