### ISSUE TITLE
Add support for OpenTelemetry resource attributes

### ISSUE THREAD

**Issue by brettmc** [open-policy-agent/opa#6942]
## What is the underlying problem you're trying to solve?
I would like the traces emitted by OPA to contain custom resource attributes that I provide. For example, [`service.namespace`](https://opentelemetry.io/docs/specs/semconv/resource/#service-experimental), which allows me to differentiate between the traces from multiple OPA instances.

## Describe the ideal solution

Provide `distributed_tracing.resource_attributes` config, which accepts a list of key-value pairs, which are passed along to the OpenTelemetry SDK. Most OpenTelemetry SDKs do this via the [`OTEL_RESOURCE_ATTRIBUTES`](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/configuration/sdk-environment-variables.md#general-sdk-configuration) environment variable, and those would be passed to the tracer provider

## Describe a "Good Enough" solution

Using https://opentelemetry.io/docs/languages/go/resources/ `resource.WithFromEnv()`in https://github.com/open-policy-agent/opa/blob/291825ee772b0ecf2cb2d88a529c0acc8a39266c/internal/distributedtracing/distributedtracing.go#L102 could allow providing resource attributes from the environment

**Comment by ashutosh-narkar** [comment]
This seems like a good addition. Updating the config to provide key-value pairs seems like a good approach. Feel free to contribute this feature if you'd like.
