### ISSUE TITLE
Unable to access keys containing slashes under HTTP /v1/data

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#695]
If object keys under data contain slashes, callers cannot access them via the HTTP API. For example:

data.json:

```json
{
  "foo/bar": "baz"
}
```

```
opa run -s data.json
```

```
curl localhost:8181/v1/data/foo%2Fbar
```

The 'problem' is that gorilla/mux is decoding URL parameters automatically. What OPA receives is `foo/bar` instead of `foo%2Fbar`. We need to investigate to see if gorrila/mux can be configured to skip decoding.

There is a related issue for repeated slashes. By default, gorrila/mux returns a 301 in cases like `GET /v1/data/%2Ffoo`.

**Comment by srenatus** [comment]
☝️ took a quick stab at this in that branch -- it seems there's more to it than just GET...

However, the call you've mentioned would work:
```
$ curl 'localhost:8181/v1/data/foo%2Fbar'
{"result":"baz"}⏎
```
So, it's up to you -- I can't tell if this small improvement would help; or if maybe slashes in keys might not be a thing worth the hassle 🤔

**Comment by tsandall** [comment]
This is great! This change fixes the read operations, i.e., GET v1/data, POST v1/data, and POST v1/data.

I'm going to do a quick test to see if we can easily fix the write operations (PUT, PATCH, and DELETE) as well. If you like go ahead and submit a PR for your change.
