### ISSUE TITLE
calling `Module.String()` returns an invalid module for Rego V1

### ISSUE THREAD

**Issue by nikpivkin** [open-policy-agent/opa#6973]
## Short description 
`OPA v0.67.1`

## Steps To Reproduce
```go
package main

import "github.com/open-policy-agent/opa/ast"

func main() {
	mod := `package test
	
import rego.v1

allow if {
	1 < 2
}
`

	module, err := ast.ParseModuleWithOpts("test.rego", mod, ast.ParserOptions{})
	if err != nil {
		panic(err)
	}

	println(module.String())

	_, err = ast.ParseModuleWithOpts("test.rego", module.String(), ast.ParserOptions{})
	if err != nil {
		panic(err)
	}
}
```

Output:
```bash
go run .
package test

import rego.v1

allow = true { lt(1, 2) }
panic: 1 error occurred: test.rego:5: rego_parse_error: `if` keyword is required before rule body

goroutine 1 [running]:
main.main()
        /Users/nikita/projects/opa-test/main.go:24 +0x100
exit status 2
```

**Comment by johanfylling** [comment]
I believe the intention of `ast.Module.String()` is to output a human-readable representation of the module, and not to produce idiomatic Rego. For instance, the compiler might apply several modifications to the AST to prepare it for evaluation that won't directly translate to "correct" Rego. E.g.: it will drop directive imports, such as `future.keywords` and `rego.v1` and add local variables, rule bodies, etc. These changes are not guaranteed to represent idiomatic, or even "correct" Rego. There is also nothing stopping a user/developer from programmatically building an AST from scratch. `String()` is a means to produce a human-readable representation of that state.

To produce idiomatic Rego from AST, OPA provides functions like `format.Source()` and `format.Ast()`. I'd suggest using these if the end goal is to produce Rego that is guaranteed to be consumable by OPA.

**Comment by johanfylling** [comment]
I think having `Module.String()` include `if` and `contains` where appropriate for v1 modules improves readability, though.
