### ISSUE TITLE
variables in closure of every block are sometimes not recognized

### ISSUE THREAD

**Issue by bluebrown** [open-policy-agent/opa#6979]
## Short description 

Sometimes when using the `every` construct, variables from the outer scope are not recognized.

OPA version =  0.67.0

## Steps To Reproduce

Here is one reproduction https://github.com/bluebrown/opa-every-with-issue
See https://openpolicyagent.slack.com/archives/CBR63TK2A/p1725004042414319 for more context and examples

**Comment by srenatus** [comment]
```rego
package test

p {
	x := "foo"
	true with input[x] as 1
}
```
⬇️ 
```
1 error occurred: policy.rego:4: rego_compile_error: assigned var x unused
```
[PG](https://play.openpolicyagent.org/p/dqTdYCMo3M)
