### ISSUE TITLE
OPA Unable to Handle Escape Characters when UTF-8 with BOM encoded

### ISSUE THREAD

**Issue by adhilto** [open-policy-agent/opa#6988]
## Short description 
This problem was a problem on the [ScubaGear](https://github.com/cisagov/ScubaGear) project (though we've identified a fix). The input json files are generated via PowerShell 5, which encodes files as UTF-8 with BOM (byte-order mark). OPA is able to handle such files in most cases, but there are some json sequences that result in OPA outputting `unable to parse input: yaml`

It's possible there are other sequences that are problematic, but `\/` was a character sequence that consistently produced the issue.

Tested with version 0.64.1 on Windows 10.

## Steps To Reproduce
A concrete example:

First, generate a UTF-8 with BOM json file. For example, on PowerShell 5, run `@{"dates"=@(Get-Date)} | ConvertTo-Json | Set-Content "example.json" -Encoding "utf8"`.

That will save a file looking like this:
```
{
    "dates":  [
                  {
                      "value":  "\/Date(1725472274633)\/",
                      "DisplayHint":  2,
                      "DateTime":  "Wednesday, September 4, 2024 10:51:14 AM"
                  }
              ]
}
```

Use a rego file (example.rego) such as this:
```
package example
import future.keywords

dates contains date if{
    some date in input.dates
    startswith(date.DateTime, "Wednesday")
}
```

Execute OPA: `.\opa_windows_amd64.exe eval data.example.dates -i example.json -d example.rego -f values`. Output: `unable to parse input: yaml: line 4: found unknown escape character`.

Copy example.json into a new file and save it as just UTF-8 (no BOM). Name it example_nobom.json. Execute OPA again: `.\opa_windows_amd64.exe eval data.example.dates -i example_nobom.json -d example.rego -f values`. Output:
```
[
  [
    {
      "DateTime": "Wednesday, September 4, 2024 10:43:58 AM",
      "DisplayHint": 2,
      "value": "/Date(1725471838770)/"
    }
  ]
]
```

## Expected behavior
OPA to be able to parse the escape sequence. Alternatively, if UTF-8 with BOM isn't supported, for that to be appropriately documented (if it is already, I couldn't find it) and have a more user-friendly error message.

**Comment by ashutosh-narkar** [comment]
I would image this is the case with the latest OPA release as well. If you'd like to contribute a fix that would be great!

**Comment by anderseknert** [comment]
BOM! Now that's an issue I haven't dealt with in years :P 

JSON doesn't seem to [like that](https://www.rfc-editor.org/rfc/rfc8259#section-8.1), but..

> implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error

So I guess that's what we should do. Since we consume the whole input before passing it to the JSON decoder, this should be fairly easy to do. I'll take a look.

**Comment by anderseknert** [comment]
Yeah, that was easy :) PR up here #6989

**Comment by ISAG-MDH** [comment]
hi @ashutosh-narkar , as gdasher mentioned, i have a close similar problem.
It was working perfekt. From 1 Secondt to the next it is not working anymore. 
See https://github.com/cisagov/ScubaGear/issues/1696 
Can you help?
The Line 12 in the ProviderSettingsExport.json output looks fine:

![Image](https://github.com/user-attachments/assets/0c0157a0-396e-4332-8464-dbc2519a3327)

There should be an other parse error?
I tried in UTF8, UTF8-BOM in Powershell 5.1.
I also tried Powershell 7.5.1, there i get an other Error:
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 4.
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 2.

Hope anyone can help!
Thx and Best Regards,
Moha
