### ISSUE TITLE
How do I follow rego v2 development?

### ISSUE THREAD

**Issue by tamalsaha** [open-policy-agent/opa#700]
I am interested in using OPA. I saw that there is going to be Rego v2 language. How do I follow its development? What sort of timeline for its release? What happens to scripts written using Rego 1 ?

Thanks.

**Comment by tsandall** [comment]
Hi @tamalsaha, we're planning to make progress on the implementation during this quarter. I'd expect that by mid-quarter there will be something to play with. Once the initial implementation is in place, updates will become more regular. If you're interested in contributing, we have a weekly Hangouts meeting you can find a link to in the README.

Rego V1 syntax will be supported for the foreseeable future. When the time is right, we will publish a guide (or tool) to migrate to the newer syntax. For simple policies, this may end up being a no-op.

**Comment by tsandall** [comment]
@tamalsaha let us know if you have other questions.
