### ISSUE TITLE
print() fails on ref with local variable?

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#7032]
```rego
p {
	xs := {1,2,3}
	some i
	x := xs[i]	
	print(x)
}
```
✅ 

```rego
package play

p {
	xs := {1,2,3}
	some i
	print(xs[i])
}
```

:x: `1 error occurred: policy.rego:6: rego_compile_error: var __local1__ is undeclared`

<details><summary>compiler stages</summary>

RewriteLocalVars gives us this:
```rego
package play

p = true { __local0__ = {1, 2, 3}; print(__local0__[__local1__]) }
```

and `RewritePrintCalls` can't cope with that.

For the first policy (with `x := xs[i]`), we get this output of `RewriteLocalVars`:
```rego
package play

p = true { __local0__ = {1, 2, 3}; __local2__ = __local0__[__local1__]; print(__local2__) }
```
which `RewritePrintCalls` turns into
```rego
package play

p = true { __local0__ = {1, 2, 3}; __local2__ = __local0__[__local1__]; internal.print([{__local3__ | __local3__ = __local2__}]) }
```

**Comment by anderseknert** [comment]
This has been an issue I encounter on pretty much a daily basis since I started work on Regal. First reported here: https://github.com/open-policy-agent/opa/issues/5624

But I’m sure there are many variations, given how often it is seen.

**Comment by srenatus** [comment]
Yeah it's a duplicate. Thanks!
