### ISSUE TITLE
test-time-0947 potentially incorrect?

### ISSUE THREAD

**Issue by matajoh** [open-policy-agent/opa#7038]
##
When digging into tests as part of the rego-cpp implementation, I noticed that `test-time-0947` appears to be testing for time caching, but as written it will always be true regardless of the caching behaviour:

```opa
        package generated

        p {
          time.now_ns(t0)
          test.sleep("10ms")
          time.now_ns(t1)
          t1 = t2
        }
```

It appears from the name of the test that the line `t1 = t2` was probably intended to be `t0 = t1`. What is the intended behaviour here? I've verified that this is the same in both v0 and v1.

**Comment by srenatus** [comment]
I think you're correct there. As it stands, that test does nothing. 😳

**Comment by anderseknert** [comment]
Another case for not using the unification operator where not needed. Good catch!
