### ISSUE TITLE
organization_name has adopted OPA

### ISSUE THREAD

**Issue by pratimsc** [open-policy-agent/opa#7060]
### Organization Name

Marsh McLennan

### Organization Website

https://www.marshmclennan.com/

### Organization Logo (optional)

https://www.marshmclennan.com/content/dam/mmc-web/site-design/mmc-logo-v3-transparent-background-blue-letters.svg

### How is your organization using OPA?

Used are follows:
1. As Gatekeeper in their Kubernetes clusters
2. As Authorisation PDP (Policy Decision Point) by many apps for ingress traffic
3. As rules engine by some apps

### Update entry

- [ ] Check this box if you want to update an existing entry.

**Comment by anderseknert** [comment]
Thanks! That's some proper use of OPA right there 👍 I'll have it added to the adopters file!
