### ISSUE TITLE
opa authz for docker not working

### ISSUE THREAD

**Issue by CharanBR** [open-policy-agent/opa#711]
Hello,
I'm running docker-ce and opa on my SLES virtual machine.

I have setup auth plugin in /etc/docker/daemon.json, setup example.rego but I still see docker ps command is allowed. I'm following the tutorial exactly as in the docker auth tutorial but it doesn't work.

[[root@host ~]# docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
9e1f88ff3be0        openpolicyagent/opa-docker-authz:0.2   "/opa-docker-authz..."   14 minutes ago      Up 13 minutes                           loving_minsky
[root@host ~]# cat /root/policies/example.rego
package docker.authz

allow = false
[root@host ~]# cat /etc/docker/daemon.json
{
        "hosts": ["unix:///var/run/docker.sock"],
        "no-new-privileges": true,
        "icc": false,
        "live-restore": true,
        "authorization-plugin": ["opa-docker-authz"]
}](url)

**Comment by tsandall** [comment]
hey @CharanBR, sorry you're having problems with the tutorial. Can you post the output of `docker logs 9e1f88ff3be0`.  The plugin contaIner will log all policy checks it performs. This will help identify whether it's a plugin issue or a Docker issue.

**Comment by CharanBR** [comment]
hi @tsandall , here you go
[root@host~]# docker logs 9e1f88ff3be0
2018/04/20 15:34:05 Starting server.

**Comment by tsandall** [comment]
Hrmmm. If those are the only logs you see, it [indicates the plugin is not being called.](https://github.com/open-policy-agent/opa-docker-authz/blob/master/main.go#L69)

I have not configured Docker the way you show (with `/etc/docker/daemon.json`) before. In the [tutorial](http://www.openpolicyagent.org/docs/docker-authorization.html) we restart Docker with a command line argument that enables the plugin. Have you tried that?

**Comment by CharanBR** [comment]
my bad. I figured out the issue. It is "authorization-plugins" (with an 's' at the end) in the /etc/docker/daemon.json. This can be closed.
