### ISSUE TITLE
`schemas` annotation issue in v0.69.0

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#7116]
Originally reported by @garethahealy [here](https://github.com/redhat-cop/rego-policies/pull/332). Thanks Gareth! It seems like there's a regression in how OPA handles `schemas` annotations in v0.69.0.

Minimal code to reproduce:

**p.rego**
```rego
package p

# METADATA
# schemas:
# - data.p.x: schema["nope"]
bug := data.p.x
```

There is of course no "nope" schema, but that shouldn't matter when we run `opa check` without providing any schemas. However:

**OPA v0.68.0**
```
$ opa check p.rego
(no output)
```

**OPA v0.69.0**
```
$ opa check p.rego
1 error occurred: p.rego:6: rego_type_error: undefined ref: data.p.x
	data.p.x
	       ^
	       have: "x"
	       want (one of): ["x"]
```

**Comment by tjons** [comment]
a rudimentary bisect with some testing reveals that https://github.com/open-policy-agent/opa/commit/76f7038ea2d18f7d543950847260e61e6a80faaf is the source of the bug. I'll dig into it further and should have a fix this week

**Comment by anderseknert** [comment]
Excellent! Thanks @tjons 👍

**Comment by tjons** [comment]
Opened https://github.com/open-policy-agent/opa/pull/7124 to fix!
