### ISSUE TITLE
ast: Location Text attribute wrong for multivalue rules with generated body

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#7128]
```rego
package system.log
	
import rego.v1
	
mask contains "foo"
```

Parsing this policy and inspecting the `Text` attribute of the `mask` rule's `Location`, one would expext to see `mask contains "foo"`, as any other type of rule would work. Multivalue rules with generated bodies however don't get the full `Text`, but only the name of the rule, like `mask` in this case.

This leads to some issues in Regal wrt these rules, as [reported](https://github.com/StyraInc/regal/issues/1212) by @drewcorlin1

(since the `contains` keyword is not part of the AST, Regal has to scan the `Text` attribute in order to know if it's used)

**Comment by drewcorlin1** [comment]
thanks for the quick fix as usual @anderseknert !
