### ISSUE TITLE
Constraint of aud claim can only be specified as string for io.jwt.decode_verify built-in function

### ISSUE THREAD

**Issue by andriusm** [open-policy-agent/opa#7141]
## Short description 

The `aud` claim check in the `io.jwt.decode_verify` built-in function doesn't work when `aud` is specified as array. Looking at the documentation and the source it seems that the logic for `aud` claim is not quite correct. The [documentation](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-tokens-iojwtdecode_verify) specifies that `constraints` parameter can be a map of `string` to `any` but looking at the [source](https://github.com/open-policy-agent/opa/blob/main/topdown/tokens.go#L546-L548) I see that `aud` claim constraint is parsed as string only. But then checking the [validAudience](https://github.com/open-policy-agent/opa/blob/main/topdown/tokens.go#L704-L719) method which checks the constraint against the token's claim it looks like it can handle either string or an array. My understanding is that because `validAudience` is only called with a string value parameter is the reason why specifying an array doesn't work.

OPA version: 0.69.0

## Steps To Reproduce

This following method specifying `aud` as array does not work.

```
verify_token(token) := result if {
	jwks = jwks_request(jwks_url)

	[valid, _, payload] := io.jwt.decode_verify(
		token,
		{
			"cert": jwks,
			"aud": [ "aud1", "aud2" ],
		},
	)

	valid == true

	result = {"validity": valid, "claims": payload}
}
```

While this method specifying `aud` as string does work.

```
verify_token(token) := result if {
	jwks = jwks_request(jwks_url)

	[valid, _, payload] := io.jwt.decode_verify(
		token,
		{
			"cert": jwks,
			"aud": "aud1",
		},
	)

	valid == true

	result = {"validity": valid, "claims": payload}
}
```

## Expected behavior

Expected behaviour is that constraints for `aud` claim can be specified as both a string and an array.

## Additional context

In my case the tokens received contain `aud` claim, but they can be issued by different OAuth servers and so the claim's value can differ. I would consider not using this constraint at all, but it seems that `decode_verify` is written in a way that if a token has an `aud` claim then it tries to match it with a given constrain and without a constraint the verification fails.

**Comment by srenatus** [comment]
You can work around that by calling `decode_validate` once per aud:

```rego
verify_token(token) := result if {
	some aud in {"aud1", "aud2"}
	result := verify_token_with_aud(token, aud)
}

verify_token_with_aud(token, aud) := result if {
	jwks = jwks_request(jwks_url)

	[valid, _, payload] := io.jwt.decode_verify(
		token,
		{
			"cert": jwks,
			"aud": aud,
		},
	)

	valid == true

	result = {"validity": valid, "claims": payload}
}
```

I think it's a bit of a stretch to say that the docs claim that passing an array would work -- the type of `constraints` as `map[string]any` is under-specified. That said,
1. adding support for an array of `aud`s would be straightforward, but
2. it would make this kitchensink do-all-the-things-at-once builtin another bit worse, in my opinion...

But since "a little worse" hardly matters, if you feel like opening a PR, you're welcome to 😃

**Comment by andriusm** [comment]
Thanks for the suggestion, @srenatus but as I understand this method of iterating over audiences would be decoding the token and verifying the signature multiple times, as many as there are items in that array. At this point I don't know exactly how many items there will be in that array, but this policy would get a lot of traffic and I would prefer to conserve resources where possible i.e. decoding just once.

I agree that adding lots of logic to a built-in function to make it do all the things is not a great, but like I mentioned the source code already expects either a string or an array it's just limited by the constraint parsing part which confused me as to how it should really work.

I would like to get your input on the idea of `verify_decode` not checking the `aud` claim if the constraints do not specify it, because that would equally solve my issue and in fact would be simpler. Would that be ok, or is the verification process very formal and it has to match the `aud` constrains if the token provides it?

**Comment by andriusm** [comment]
@anderseknert my assumption was that the token would have one and only one `aud` value, but since I'm dealing with tokens issued by different servers the actual value is different. And so in my policy the intent was to see if at least any of the value in the constraint array matches the `aud` claim of the token. The source code for `aud` cosntraint validation seems to be implemented exactly like that - https://github.com/open-policy-agent/opa/blob/main/topdown/tokens.go#L704-L719

Regarding your suggestion of doing the decoding and verification separately I might end up doing that, but I thought that the policy would be simpler and I would need to write less logic if I would just use the `decode_verify` to do everything in one go. Do I understand correctly that you're saying that it was not your intention and it shouldn't be possible to specify the `aud` constraint as an array?

**Comment by anderseknert** [comment]
> any of the value in the constraint array matches the aud claim of the token. The source code for aud cosntraint validation seems to be implemented exactly like that

It's the other way around — that checks if any of the values in the `aud` claim from the token (which may be either a string or array) is equal to the `aud` constraint value.

> Regarding your suggestion of doing the decoding and verification separately I might end up doing that, but I thought that the policy would be simpler and I would need to write less logic if I would just use the decode_verify to do everything in one go.

Indeed, that is what you give up when doing custom verification. It's a fun coincidence but I'm actually working on a Rego based alternative to `io.jwt.decode_verify` just this week, and should have something published by the end of it. I can ping you then if you'd like to take a look :)

> Do I understand correctly that you're saying that it was not your intention and it shouldn't be possible to specify the aud constraint as an array?

Yes, that is correct. As mentioned, the semantics around arrays aren't as clear cut as a simple string comparison, and while a token may be intended for multiple audiences, a resource server is AFAIK always only a single audience.

**Comment by andriusm** [comment]
> It's the other way around — that checks if any of the values in the aud claim from the token (which may be either a string or array) is equal to the aud constraint value.
Thanks for pointing that out, misread the code due to pre-existing expectations.

> Indeed, that is what you give up when doing custom verification. It's a fun coincidence but I'm actually working on a Rego based alternative to io.jwt.decode_verify just this week, and should have something published by the end of it. I can ping you then if you'd like to take a look :)
That sounds interesting, especially if that would allow me to not having to specify the `aud` constraint when verifying. Would love to take look.

Should I close this issue now that it's clear that it's not a bug?

**Comment by anderseknert** [comment]
Yeah, let's do that. Thanks for raising this though! 👍
