### ISSUE TITLE
Best approach for testing policies locally

### ISSUE THREAD

**Issue by Scott-Wallace-ConnectedLab** [open-policy-agent/opa#715]
I'm currently trying to test out policies locally by executing the following flow:

1. Run OPA `docker run -p 8181:8181 openpolicyagent/opa   run --server --log-level debug`
2. Load a policy `curl -X PUT --data-binary @example.rego  localhost:8181/v1/policies/example`
3. Test the policy
```    
curl -X "POST" "http://localhost:8181/v1/data/httpapi/authz" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "path": "/users",
  "method": "GET",
  "user": "jim"
}'
```

My policy looks like the following:
```
package httpapi.authz

deny["a prereq for this req failed"] {
  input.user = "jim"
}

main = {
    "apiVersion": "admission.k8s.io/v1alpha1",
    "kind": "AdmissionReview",
    "status": status
}
default status = {
    "allowed": true
}

status = {
    "allowed": false,
    "status": {
        "reason": reason,
    },
} {
    concat("; ", deny, reason)
    reason != ""
}
```

The problem I am facing is I don't believe the policy is actually reading/seeing the body of the request (ie. so it can't see that path="/users" or that user="jim"). 

What is happening is that the policy will succeed for any incoming request (like Step 3). 
`{"result":{"deny":[],"main":{"apiVersion":"admission.k8s.io/v1alpha1","kind":"AdmissionReview","status":{"allowed":true}},"status":{"allowed":true}}}`

However if I change the policy line to `not input.user = "jim"` then the status returns as false.
`{"result":{"deny":["a prereq for this req failed"],"main":{"apiVersion":"admission.k8s.io/v1alpha1","kind":"AdmissionReview","status":{"allowed":false,"status":{"reason":"a prereq for this req failed"}}},"status":{"allowed":false,"status":{"reason":"a prereq for this req failed"}}}}`

Is there a better way to test out my policy locally? Or someway to read in the body of the request?

**Comment by tsandall** [comment]
Instead of loading the policy via the HTTP API you can try starting OPA with the policy file and the --watch flag. For example:

```
docker run -p 8181:8181 -v /policy/dir:/policies openpolicyagent/opa run --server --log-level debug --watch /policies
```

When you run OPA with one or more filepaths, OPA will load the files/directories. If you include the --watch flag (-w) then OPA will watch the filesystem for changes to those files. This allows you to modify the files and see the change immediately in OPA. OPA will log when it tries to reload a file.

An alternative to running OPA and manually exercising the policy is to write unit tests. OPA has a `test` subcommand that let's you run unit tests on your policies. The help text for the command shows how to get started.

The issue in this case is the curl message body, it needs to be `{"input": {"path": ...}}` instead of just `{"path": ...}`.

**Comment by tsandall** [comment]
OPA also has a "tracing" feature that's quite powerful and sometimes helpful in cases like this.

If you run this query:

```
curl -X "POST" "http://localhost:8181/v1/data/httpapi/authz?explain=full&pretty=true"
```

OPA will include an _explanation_ along with the result. The explanation shows (by default, at a very low level) how OPA arrived at the answer it returned. In this case, you'll see that OPA "fails" on the check against `reason`. Currently you can include _notes_ in the result by calling `trace(<msg>)` inside your policy. For example:

```
curl -X "POST" "http://localhost:8181/v1/data/httpapi/authz?explain=full&pretty=true"      -H 'Content-Type: application/json; charset=utf-8'      -d $'{
  "path": "/users",
  "method": "GET",
  "user": "jim"
}'
{
  "explanation": [
    "Enter data.httpapi.authz = _",
    "| Eval data.httpapi.authz = _",
    "| Enter main = __local1__ { true; __local2__ = data.httpapi.authz.status; __local1__ = {\"apiVersion\": \"admission.k8s.io/v1alpha1\", \"kind\": \"AdmissionReview\", \"status\": __local2__} }",
    "| | Eval true",
    "| | Eval __local2__ = data.httpapi.authz.status",
    "| | Enter status = {\"allowed\": false, \"status\": {\"reason\": reason}} { __local3__ = input; sprintf(\"%v\", [__local3__], __local0__); trace(__local0__); __local4__ = data.httpapi.authz.deny; concat(\"; \", __local4__, reason); neq(reason, \"\") }",
    "| | | Eval __local3__ = input",
    "| | | Eval sprintf(\"%v\", [__local3__], __local0__)",
    "| | | Eval trace(__local0__)",
    "| | | Note \"null\""
```

You can see in this case that input is not set.

We have a few planned improvements around tracing in the near future (e.g., surfacing notes better, showing values, etc.)

**Comment by Scott-Wallace-ConnectedLab** [comment]
Thanks for the help. Any suggestions for when testing policies within kubernetes (ie. restricting creating pods to a specific name or namespace) ?

**Comment by tsandall** [comment]
The biggest challenge I've run into is just figure out what the actual input data looks like (since Kube objects have so many fields and quite complex structures.) Once you have examples of the data, unit testing helps here.

To gather input, I've tried different approaches in the past, e.g., simply copying the input out of the OPA logs is one approach. Another thing you can try is [enabling diagnostics in OPA while it's deployed.](http://www.openpolicyagent.org/docs/monitoring-diagnostics.html#diagnostics) This way you can query OPA and see what it's being called with.

**Comment by tsandall** [comment]
One trick is to define your [rules incrementally](http://www.openpolicyagent.org/docs/how-do-i-write-policies.html#incremental-definitions). You can define rules incrementally in the same file or across files. For example:

policy1.rego:

```
package kubernetes.admission

deny["method must NOT be GET"] {
  input.method = "GET"
}
```

policy2.rego

```
package kubernetes.admission

deny["method must NOT be POST"] {
  input.method = "POST"
}

deny["method must NOT be DELETE"] {
  input.method = "DELETE"
}
```

If you load both these files (along w/ your main package), all of the deny rules will contribute to the policy decision.

**Comment by Scott-Wallace-ConnectedLab** [comment]
Ok that makes sense and will use that approach when we get to _real_ policies.

I have another question related to OPA, kube-mgmt and the kube api-server.

So say I have that all set up in my Kube cluster, I can see logs in OPA when I create a Pod or a Namespace, etc etc. What I'm see log wise is that OPA isn't getting all the data that we need that the api-server has. For this to be a viable approach for our use case we need to be able to see things like who is making the request and info on the kubernetes nodes.

For example, say we try to create a Pod:
> api-server logs
```
{
   "kind":"Event",
   "apiVersion":"audit.k8s.io/v1beta1",
   "metadata":{
      "creationTimestamp":"2018-04-23T19:14:22Z"
   },
   "level":"RequestResponse",
   "timestamp":"2018-04-23T19:14:22Z",
   "auditID":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
   "stage":"ResponseComplete",
   "requestURI":"/api/v1/namespaces/opa/pods",
   "verb":"create",
   "user":{
      "username":"admin",
      "uid":"1000",
      "groups":[
         "system:masters",
         "system:authenticated"
      ]
   },
   "sourceIPs":[
      "XXX.XX.XXX.XXX"
   ],
   "objectRef":{
      "resource":"pods",
      "namespace":"opa",
      "name":"nginx1",
      "apiVersion":"v1"
   },
   "responseStatus":{
      "metadata":{

      },
      "code":201
   },
   "requestObject":{
      "kind":"Pod",
      "apiVersion":"v1",
      "metadata":{
         "name":"nginx1",
         "namespace":"opa",
         "creationTimestamp":null,
         "labels":{
            "app":"nginx"
         }
      },
      "spec":{
         "containers":[
            {
               "name":"nginx",
               "image":"nginx:alpine",
               "resources":{

               },
               "terminationMessagePath":"/dev/termination-log",
               "terminationMessagePolicy":"File",
               "imagePullPolicy":"IfNotPresent"
            }
         ],
         "restartPolicy":"Always",
         "terminationGracePeriodSeconds":30,
         "dnsPolicy":"ClusterFirst",
         "securityContext":{

         },
         "schedulerName":"default-scheduler"
      },
      "status":{

      }
   },
   "responseObject":{
      "kind":"Pod",
      "apiVersion":"v1",
      "metadata":{
         "name":"nginx1",
         "namespace":"opa",
         "selfLink":"/api/v1/namespaces/opa/pods/nginx1",
         "uid":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
         "resourceVersion":"2268552",
         "creationTimestamp":"2018-04-23T19:14:22Z",
         "labels":{
            "app":"nginx"
         },
         "annotations":{
            "kubernetes.io/psp":"calico-kube-controllers"
         }
      },
      "spec":{
         "volumes":[
            {
               "name":"default-token-abcde",
               "secret":{
                  "secretName":"default-token-abcde",
                  "defaultMode":420
               }
            }
         ],
         "containers":[
            {
               "name":"nginx",
               "image":"nginx:alpine",
               "resources":{

               },
               "volumeMounts":[
                  {
                     "name":"default-token-abcde",
                     "readOnly":true,
                     "mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"
                  }
               ],
               "terminationMessagePath":"/dev/termination-log",
               "terminationMessagePolicy":"File",
               "imagePullPolicy":"IfNotPresent"
            }
         ],
         "restartPolicy":"Always",
         "terminationGracePeriodSeconds":30,
         "dnsPolicy":"ClusterFirst",
         "serviceAccountName":"default",
         "serviceAccount":"default",
         "securityContext":{

         },
         "schedulerName":"default-scheduler",
         "tolerations":[
            {
               "key":"node.alpha.kubernetes.io/notReady",
               "operator":"Exists",
               "effect":"NoExecute",
               "tolerationSeconds":300
            },
            {
               "key":"node.alpha.kubernetes.io/unreachable",
               "operator":"Exists",
               "effect":"NoExecute",
               "tolerationSeconds":300
            }
         ]
      },
      "status":{
         "phase":"Pending",
         "qosClass":"BestEffort"
      }
   }
}
```
> but OPA only gets
```
{
   "apiVersion":"v1",
   "kind":"Pod",
   "metadata":{
      "annotations":{
         "kubernetes.io/psp":"calico-kube-controllers"
      },
      "creationTimestamp":"2018-04-23T19:14:22Z",
      "labels":{
         "app":"nginx"
      },
      "name":"nginx1",
      "namespace":"opa",
      "resourceVersion":"2268564",
      "selfLink":"/api/v1/namespaces/opa/pods/nginx1",
      "uid":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
   },
   "spec":{
      "containers":[
         {
            "image":"nginx:alpine",
            "imagePullPolicy":"IfNotPresent",
            "name":"nginx",
            "resources":{

            },
            "terminationMessagePath":"/dev/termination-log",
            "terminationMessagePolicy":"File",
            "volumeMounts":[
               {
                  "mountPath":"/var/run/secrets/kubernetes.io/serviceaccount",
                  "name":"default-token-abcde",
                  "readOnly":true
               }
            ]
         }
      ],
      "dnsPolicy":"ClusterFirst",
      "nodeName":"random-node-name.com",
      "restartPolicy":"Always",
      "schedulerName":"default-scheduler",
      "securityContext":{

      },
      "serviceAccount":"default",
      "serviceAccountName":"default",
      "terminationGracePeriodSeconds":30,
      "tolerations":[
         {
            "effect":"NoExecute",
            "key":"node.alpha.kubernetes.io/notReady",
            "operator":"Exists",
            "tolerationSeconds":300
         },
         {
            "effect":"NoExecute",
            "key":"node.alpha.kubernetes.io/unreachable",
            "operator":"Exists",
            "tolerationSeconds":300
         }
      ],
      "volumes":[
         {
            "name":"default-token-abcde",
            "secret":{
               "defaultMode":420,
               "secretName":"default-token-abcde"
            }
         }
      ]
   },
   "status":{
      "conditions":[
         {
            "lastProbeTime":null,
            "lastTransitionTime":"2018-04-23T19:14:22Z",
            "status":"True",
            "type":"Initialized"
         },
         {
            "lastProbeTime":null,
            "lastTransitionTime":"2018-04-23T19:14:24Z",
            "status":"True",
            "type":"Ready"
         },
         {
            "lastProbeTime":null,
            "lastTransitionTime":"2018-04-23T19:14:22Z",
            "status":"True",
            "type":"PodScheduled"
         }
      ],
      "containerStatuses":[
         {
            "containerID":"docker://XXXXXXXXXXX",
            "image":"nginx:1.13-alpine",
            "imageID":"docker-pullable://nginx@sha256:XXXXXXXXXXX",
            "lastState":{

            },
            "name":"nginx",
            "ready":true,
            "restartCount":0,
            "state":{
               "running":{
                  "startedAt":"2018-04-23T19:14:23Z"
               }
            }
         }
      ],
      "hostIP":"XXX.XX.XX.XXX",
      "phase":"Running",
      "podIP":"XX.XXX.XX.XXX",
      "qosClass":"BestEffort",
      "startTime":"2018-04-23T19:14:22Z"
   }
}
```

It looks to me like OPA is only getting the `RequestObject` from api-server but we need OPA to see things like `user` and `verb` is there a way to get this data passed along from api-server to OPA?

Could maybe the using opa-kube-scheduler solve our use case? Ie. Prevent deletion of namespaces, restrict users from adding workloads to certain nodes

**Comment by tsandall** [comment]
OPA should be receiving a JSON serialized version of [this struct](https://github.com/kubernetes/api/blob/master/admission/v1beta1/types.go#L40) as the input document. The admission review contains the user authentication info (e.g., user and groups) as well as the operation (e.g., create/update/delete).

**Comment by Scott-Wallace-ConnectedLab** [comment]
I've added the `--authorization=basic` flag to my opa container in my yaml and this seems to get past my TLS handshake errors I've been seeing. However does this flag work with the kube-mgmt approach to setting up OPA on Kubernetes? The policies in https://github.com/open-policy-agent/opa/blob/e9d0297f385687afdcdffac8d0fbef51583fd664/docs/book/security.md#authentication--authorization look quite different from that in https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/403-admission-policy . I do see the kube-mgmt failing to get the webhook started since the code hangs on the default policy which looks like:
```
		package system

		default main = {
			"apiVersion": "admission.k8s.io/v1alpha1",
			"kind": "AdmissionReview",
			"status": {
				"allowed": true,
			},
		}
```

**Comment by tsandall** [comment]
hey @Scott-Wallace-ConnectedLab sorry for the delayed response.

I would not expect `--authorization` to have any affect on TLS connections. Handshake errors are usually caused by either OPA having the wrong certificates or the admission controller being registered with the wrong CA bundle.

The `--authorization` turns on authorization on the OPA API itself. This lets you restrict which APIs clients can call. This requires you to enable authentication on the OPA as well, however, since OPA only supports Bearer token authentication at this time, I'm not sure it'll work with Kubernetes admission control webhooks.

**Comment by Scott-Wallace-ConnectedLab** [comment]
Thanks for the help. This issue can be closed now. Those TLS handshake errors were handled by fixing the CN name in one of the certs being used. to `CN=opa_name.namespace.svc`
