### ISSUE TITLE
Please add syntax highlighting support using hightlight JS

### ISSUE THREAD

**Issue by liamwh** [open-policy-agent/opa#7171]
## What is the underlying problem you're trying to solve?
I want to use syntax highlighting for rego code.

## Describe the ideal solution
There is [highlightjs](https://highlightjs.org/) support for Rego.

**Comment by anderseknert** [comment]
That would indeed be nice :) I'm not sure this issue belongs in the OPA core project, as it's not something that we could solve within this repo. We can let the issue remain open for some time though if it helps drawing eyeballs here. I would suggest perhaps asking about this in the OPA Slack too, and the OPA discusssion board https://github.com/orgs/open-policy-agent/discussions

**Comment by charlieegan3** [comment]
https://highlightjs.readthedocs.io/en/latest/language-contribution.html looks to have a good guide here on getting started.
