### ISSUE TITLE
status endpoint not allowing pulling metrics

### ISSUE THREAD

**Issue by alfredocambera-bitso** [open-policy-agent/opa#7174]
## Short description 

The [status endpoint ](https://www.openpolicyagent.org/docs/latest/management-status/#prometheus-status-metrics)doesn't allow pulling metrics after enabling it. 

The OPA version is 0.65

## Steps To Reproduce

Here is the configuration file that I used:

```
status:
  prometheus: true
```

Then I tried to query the OPA pod and got:

```
$ curl -s -k https://10.1.1.2:8443/status
404 page not found
```

The endpoint is correct as I tried with metrics and it worked:

```
$ curl -s -k https://10.1.1.2:8443/metrics | head -n 3
# HELP go_cgo_go_to_c_calls_calls_total Count of calls made from Go to C by the current process.
# TYPE go_cgo_go_to_c_calls_calls_total counter
go_cgo_go_to_c_calls_calls_total 3
```

## Expected behavior

Being able to retrieve the status metrics

**Comment by anderseknert** [comment]
Might be this you're looking at https://github.com/open-policy-agent/opa/issues/4297
If so, you can enable console logging to activate the status plugin.

```yaml
status:
    console: true
   prometheus: true
```

**Comment by anderseknert** [comment]
I'll close this, as the underlying issue is already described in #4297, but do let us know if it still doesn't work with the status plugin enabled.
