### ISSUE TITLE
overlapping root error when using bundles from oci

### ISSUE THREAD

**Issue by bluebrown** [open-policy-agent/opa#7186]
## Short description 

OPA throws overlapping root errors on non overlapping roots,
when using bundles from OCI.

❯ opa version
Version: 0.70.0
Build Commit: 2ea031ea04e6a8afbc5dd22f656131dc3cfc5a7d
Build Timestamp: 2024-10-31T19:39:52Z
Build Hostname: 799a5774bce7
Go Version: go1.23.1
Platform: linux/amd64
WebAssembly: available

❯ oras version
Version:    1.2.0+unreleased
Go version: go1.23.2

## Steps To Reproduce

https://github.com/bluebrown/opa-issue-overlapping-roots

## Expected behavior

Should not throw overlapping root errors

**Comment by srenatus** [comment]
I've checked out your repo and had a look at the built bundles:
```
scratch/opa-issue-overlapping-roots % make one.tar.gz
opa build  -o one.tar.gz one/
scratch/opa-issue-overlapping-roots % tar tvf one
tar: Error opening archive: Error reading 'one'
scratch/opa-issue-overlapping-roots % tar tvf one.tar.gz 
-rw-------  0 0      0           3 Jan  1  1970 /data.json
-rw-------  0 0      0          31 Jan  1  1970 /one/one.rego
-rw-------  0 0      0          46 Jan  1  1970 /.manifest
scratch/opa-issue-overlapping-roots % tar xvf one.tar.gz /.manifest
tar: Removing leading '/' from member names
x .manifest
scratch/opa-issue-overlapping-roots % cat .manifest 
{"revision":"","roots":[""],"rego_version":0}
```
☝️ This isn't the roots you were expecting, is it?

The `opa build` command is missing `-b`: without it, it will ignore the `.manifest` file. So try this:

```diff
-	opa build $(BUILD_FLAGS) -o $@ $</
+ 	opa build $(BUILD_FLAGS) -o $@ -b $</
```

**Comment by bluebrown** [comment]
thank you :)
