### ISSUE TITLE
Single Policy loaded from single opa bundle returns rego_type_error: multiple default rules data.trigger.authz.allow found

### ISSUE THREAD

**Issue by carlosalmeida753** [open-policy-agent/opa#7197]
## Short description 
While deploying the OPA helm chart version 0.53.1 in Kubernetes hosted in Azure and loading an OPA bundle generated with opa command I get an error when doing the following request: https://localhost:51243/v1/data/trigger/authz/allow.

The error states: **rego_type_error: multiple default rules data.system.authz.allow found**

I have also deployed a docker image locally and checked if maybe the bundle was being loaded more than once but I only found one instance.

My config.yaml looks like this:

`bundles:
  authz:
    persist: true
    polling:
      max_delay_seconds: 120
      min_delay_seconds: 60
    resource: bundle_authorization.tar.gz
    service: azure-git
services:
  azure-git:
    credentials:
      bearer:
        token: REDACTED_TOKEN
    response_header_timeout_seconds: 5
    url: REDACTED_URL`

Here are the complete logs:

`{"level":"debug","msg":"Download in progress.","time":"2024-11-28T16:11:50Z"}
{"level":"debug","msg":"Bundle activation in progress (). Opening storage transaction.","name":"authz","plugin":"bundle","time":"2024-11-28T16:11:50Z"}
{"level":"debug","msg":"Opened storage transaction (4).","name":"authz","plugin":"bundle","time":"2024-11-28T16:11:50Z"}
{"level":"debug","msg":"Closing storage transaction (4).","name":"authz","plugin":"bundle","time":"2024-11-28T16:11:50Z"}
{"level":"debug","msg":"Persisting bundle to disk in progress.","name":"authz","plugin":"bundle","time":"2024-11-28T16:11:50Z"}
{"level":"debug","msg":"Bundle persisted to disk successfully at path /.opa/bundles/authz.","name":"authz","plugin":"bundle","time":"2024-11-28T16:11:50Z"}
{"level":"info","msg":"Bundle loaded and activated successfully.","name":"authz","plugin":"bundle","time":"2024-11-28T16:11:50Z"}
{"level":"debug","msg":"Waiting 1m19.766291594s before next download/retry.","time":"2024-11-28T16:11:50Z"}
2024/11/28 16:12:12 http: TLS handshake error from 127.0.0.1:36726: EOF
{"client_addr":"127.0.0.1:36752","level":"info","msg":"Received request.","req_body":"{\r\n    \"input\":REDACTED","req_id":1,"req_method":"POST","req_params":{},"req_path":"/v1/data/trigger/authz/allow","time":"2024-11-28T16:12:12Z"}
{"client_addr":"127.0.0.1:36752","level":"info","msg":"Sent response.","req_id":1,"req_method":"POST","req_path":"/v1/data/trigger/authz/allow","resp_body":"{\n  \"code\": \"internal_error\",\n  \"message\": \"1 error occurred: authz/bundle_authorization%!C(MISSING)policy.rego:30: rego_type_error: multiple default rules data.trigger.authz.allow found\"\n}\n","resp_bytes":190,"resp_duration":3.020045,"resp_status":500,"time":"2024-11-28T16:12:12Z"}`

## Steps To Reproduce
1. Deploy OPA 0.53.1 Helm Chart in Kubernetes with an OPA bundle configured
2. Perform requests to match that policy

## Expected behavior
Get a response of the JSON object containing the result of the query, true or false.

**Comment by carlosalmeida753** [comment]
The same policy works locally and if inserted in the helm chart directly.

**Comment by srenatus** [comment]
> 1.    Deploy OPA 0.53.1 Helm Chart in Kubernetes with an OPA bundle configured
> 2.    Perform requests to match that policy

I'm afraid without **your** OPA bundle, these are not steps to reproduce. This behaviour depends on the bundle, it's not like deploying OPA with a helm chart in k8s **always** leads to this error.

That said, I'd start with the bundle: can you share the output of `tar tvf bundle.tar.gz`?

**Comment by carlosalmeida753** [comment]
Sure, the output of what you requested is:

`-rw-------  0 0      0           3 jan 01  1970 /data.json\n
-rw-------  0 0      0        1624 jan 01  1970 /bundle_authorization\\policy.rego\n
-rw-------  0 0      0          46 jan 01  1970 /.manifest`

Let me also add that the same bundle works correctly locally. I can query the rules defined in the policy successfuly via the localhost endpoint supplied by running opa run.

**Comment by srenatus** [comment]
```
 -rw-------  0 0      0           3 jan 01  1970 /data.json
 -rw-------  0 0      0        1624 jan 01  1970 /bundle_authorization\\policy.rego
 -rw-------  0 0      0          46 jan 01  1970 /.manifest
```
OK so the `\\` looks funky there. But maybe it could still work.

> supplied by running opa run.
Can you share the exact command? There are multiple ways to load a bundle with their own subtleties.

**Comment by carlosalmeida753** [comment]
I ran the command: opa run --server --config-file=config.yaml and then I perform the request:

`curl -X POST http://localhost:8181/v1/data/trigger/authz/allow -H "Content-Type: application/json" -d "{\"input\":  REDACTED` which returns me:

`{"result":true}` which is the expected behaviour.

**Comment by srenatus** [comment]
Ah, so you're having OPA pull the bundle from an HTTP service. (I wasn't sure before, you could have been using `opa run -s -b bundle.tar.gz` or something with the bundle directory directly.)

Can you try building the bundle in a docker container? Something like
```sh
docker run -v $PWD:/w -w /w openpolicyagent/opa:latest build -b .
```
This is to rule out any funny business related to the `\\` in your path.

(I'm not sure if Windows' shell provides $PWD, but you can also put the absolute path of the current working directory there.)

**Comment by srenatus** [comment]
> {"result":true} which is the expected behaviour.

Well, if it's doing that, the bundle is OK and should work the same regardless -- also when deployed using helm in k8s.

**Comment by srenatus** [comment]
Can you download the bundle _as it is served_ and inspect it? Maybe something got out of sync between what you think the serving endpoint has and what it really has...? How do you deploy your bundle to your bundle service (or HTTP resource)?

**Comment by carlosalmeida753** [comment]
The issue is that it doesn't. I tried altering the deployment.yaml to only include the basic args in the opa run command and the result is the same, multiple default allow rules defined. I am not sure if there is a use case where the same bundle may be loaded more than once and that raises the error because there are duplicated policies, but when I do a docker run like you mentioned the bundle is only loaded once.

Regarding your last comment the bundle is downloaded with no changes from what the one I built. I am getting the bundle from a git repository in Azure, I pushed it to the repo and I am using opa sync to retrieve new updates.

**Comment by srenatus** [comment]
> OPA 0.53.1 Helm Chart

Wait, does this mean you're using OPA 0.53.1? Can you try with the latest release, 0.70.0, by any chance?

**Comment by carlosalmeida753** [comment]
I did as you indicated and now performing the same request for the allow rule returns: "authorization policy missing or undefined"

**Comment by srenatus** [comment]
"authorization policy missing or undefined" suggests that your OPA instance is configured to use a policy for authorization. Is it? If so, can you share your full config and the logs, please?

**Comment by carlosalmeida753** [comment]
Thank you, the solution was actually updating the opa-kube-mgmt helm chart from 8.3.0 to 8.5.11 which in turn uses the opa 0.69.0 version and setting the authz.enabled to false. Can you tell me where I need to define the authorization policy if I set authz.enabled? Also we have an issue if we use persist: true in the config.yaml to persist the bundle because the user rights of the user running the docker image in the pod instance are not sufficient, does this need to be explictly defined in the helm chart?

**Comment by carlosalmeida753** [comment]
I also have another issue right now where if I define my custom data outside of the policy.rego file and put it instead in the data.json, it seems that the data is not being correctly read because the same request that returns true when the data is inside the rego file, returns false when it is inside data.json instead.

**Comment by srenatus** [comment]
> Can you tell me where I need to define the authorization policy if I set authz.enabled?

I don't know about the helm chart, but there are [docs about the authorization policy here](https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization). In terms of "where does the policy come from?" -- It's configured to evaluate a _rule_. That rule would need to be defined in any Rego code that the OPA service is aware of -- must likely, it would be part of your bundle. I believe by default, the rule used is `data.system.authz.allow`; so you'd have something like

```rego
package system.authz
import rego.v1
allow if { ... }
```

in your bundle.

**Comment by srenatus** [comment]
> I also have another issue right now where if I define my custom data outside of the policy.rego file and put it instead in the data.json, it seems that the data is not being correctly read because the same request that returns true when the data is inside the rego file, returns false when it is inside data.json instead.

It's often best to verify the location of the data in your base document (i.e. the static parts without the rego) by narrowing it down, like
1. GET /v1/data
2. GET /v1/data/foo
2. GET /v1/data/foo/bar

until your certain about its location.

**Comment by carlosalmeida753** [comment]
Resolved the data.json issue, thank you. Regarding the authorization policy the helm charts defines one in the bootstrap folder if you set authz.enabled to true, like this:

![image](https://github.com/user-attachments/assets/c6067e34-3e11-4c8b-aac5-a81962871af9)

This policy is available in the bootstrap folder, when we run opa in the pod these are the arguments:

![image](https://github.com/user-attachments/assets/7d1e1b64-65a8-4714-97df-e20ebc95481b)

I would assume the last arg is to declare the folder where the authz.rego policy will be but it seems the we still get the authorization policy missing error. This error comes from the health probes in the opa pod.

**Comment by srenatus** [comment]
Does your bundle declare a root in its manifest? Otherwise, there'd be a conflict here, I think. Or it overrides your `system.authz`. 🤔

**Comment by carlosalmeida753** [comment]
I don't think so, my manifest looks like this:

`{"revision":"","roots":[""],"rego_version":0}`

It just seems that this authz.rego file is not being picked up. Should I explicitly declare it in the args, like bootstrap/authz.rego?

**Comment by srenatus** [comment]
I think the bundle might override it? Try setting roots to at least one part if your data tree that's in the bundle.

**Comment by carlosalmeida753** [comment]
Indeed setting the root resolved the last issue. Thank you so much for your help, everything is working now, I will close the ticket. Have a nice weekend!
