### ISSUE TITLE
REPL does not recognize some assignment expressions

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#726]
The REPL does not recognize assignments when the right hand side is rewritten. For example:

```
x = 2 * 3 + 4
```

Prints the value of x instead of assigning it.

The issue appears to be with how the REPL determines whether the equality represents an assignment. The REPL compiles the query and then checks if the result can still be interpreted as an assignment. The compile step is necessary to resolve references on the left hand side.

**Comment by DavidMa266** [comment]
It seems if the RHS is an object or a set that contains variables, this behavior also occurs.
```

> a = "hello"
> b = "world"
> c = {a:b}
+-------------------+
|         c         |
+-------------------+
| {"hello":"world"} |
+-------------------+
> c
1 error occurred: 1:1: rego_unsafe_var_error: var c is unsafe
> c = {"hello":"world"}
> c
{
  "hello": "world"
}
>  d= [a,b,c]
+-------------------------------------+
|                  d                  |
+-------------------------------------+
| ["hello","world",{"hello":"world"}] |
+-------------------------------------+
> d
1 error occurred: 1:1: rego_unsafe_var_error: var d is unsafe
```

**Comment by tsandall** [comment]
This issue is duplicated by #1104.
