### ISSUE TITLE
User Friendly Policy Execution Trace

### ISSUE THREAD

**Issue by nirajfeb** [open-policy-agent/opa#729]
I would like to consider the OPA as Policy Entitlement Engine. I have requirement to provide a proper explanation to end user if user is not entitled.
I only see "explain=full" to see policy execution trace and this not not user friendly. Please let me know if there are any other options for the policy execution trace.

**Comment by ashutosh-narkar** [comment]
Hello @nirajfeb , have your tried the **_pretty_**  parameter ? This will provide a human friendly format.

See this for more details https://www.openpolicyagent.org/docs/rest-api.html#explanations

**Comment by nirajfeb** [comment]
Yes I did, I am looking for something that a business user can understand. Pretty option is good for the implementer/policy writer.

**Comment by ashutosh-narkar** [comment]
OPA can also report decision logs that describe the queries. See [this](https://github.com/open-policy-agent/opa/blob/master/docs/book/decision_logs.md) .

Can you explain a bit more about the type of information a business user may need.

**Comment by tsandall** [comment]
hey @nirajfeb, can you provide a bit more detail about your use case?

Today OPA only supports the relatively low-level explanation mode that @ashutosh-narkar mentioned. That being said, we intend to support other explanation modes that provide higher level results. For example, if the explanation only reported the _names of rules that were evaluated_ would this be high level enough? We've also been kicking around the idea of adding docstrings to the policies. This way your policy authors could include  English descriptions of the rules and then those could be reported in the trace.

Let us know if this helps. Also, if you have more questions, feel free to post in #general on https://slack.openpolicyagent.org as other people might have ideas.

**Comment by nirajfeb** [comment]
Sure, I was planning to prepare a sample policy and their expected output in case of result is false from OPA server.
But I believe you got my point I really want to show rule name and input parameters of rule.

**Comment by tsandall** [comment]
If you can provide the samples and expected output, that would be perfect!

**Comment by tsandall** [comment]
Closing this for now. We can revisit based on demand.

**Comment by andrewbanchich** [comment]
@tsandall I'm interested in this.

My use case is I'd like to build a frontend library to generate visualizations of the decision tree, like a [zoomable sunburst](https://observablehq.com/@d3/zoomable-sunburst), so that end users can see a comprehensive explanation of why they are or are not allowed to do certain things.

The current output of the decision, e.g.

```
{
    "allow": true,
    "user_is_admin": true,
    "user_is_granted": []
}
```

doesn't provide the context that `user_is_admin` is a child of `allow`, so I can't build a tree from this,
