### ISSUE TITLE
equals operator issue

### ISSUE THREAD

**Issue by UmashankarSharma** [open-policy-agent/opa#738]
While working with equals operator in = is not working. Instead == works.

 > ["hello", "world"]
[
  "hello",
  "world"
]
> true = false
undefined
> 3.14<4
true
> true=false
undefined
> "hello"="bye"
undefined
> "hello"=="bye"
false

**Comment by tsandall** [comment]
hi @UmashankarSharma. The output you got is expected, though it's a little confusing at first.

The reason the output is different is that OPA treats `true = false` as a query -- when OPA can't prove a query, it prints "undefined" in the REPL. If you were calling OPA programmatically, the API would also indicate that the query is undefined.

On the other hand, OPA's REPL interprets expressions like `true == false` or `3+1 < 4` as asking for the _value_ of the expression. This means that the expression is actually rewritten to something like `x = true == false` and then OPA prints the value of x. Hence, the value `false` is printed in your cases.

Hope this helps.

**Comment by UmashankarSharma** [comment]
One more issue @tsandall 

I installed vscode extension but the path for workspace was messed up while running OPA:eval in vscode.

I did a minor change as below in extension.ts  and then it started to pick up the right ones.

line no : 215
        parseOPA('opa', editor.document.uri.path.substring(1), (pkg: string, _: string[]) => {

I am using windows 64 bit version.

Thanks.
Uma

**Comment by tsandall** [comment]
I've published a new version of the extension that should fix this. Let me know if you're still running into  problems.
