### ISSUE TITLE
http.send should support passing headers

### ISSUE THREAD

**Issue by redbaron** [open-policy-agent/opa#749]
It would be handy if  http.send supported passing headers.

**Comment by tsandall** [comment]
+1. The work to do this should be relatively straightforward. The only thing that I'm concerned about is if those headers are used to communicate secrets. If that's the case, we don't want to encourage people to hardcode secrets into their policies.

Work required:

* Update [topdown/http.go#executeHTTPRequest](https://github.com/open-policy-agent/opa/blob/master/topdown/http.go#L81) to pull headers out of the input object provided to `http.send` and construct the http.Request headers.

Related: #420

**Comment by repenno** [comment]
I will take a stab at this one

**Comment by kichristensen** [comment]
Isn't this closed by 3e0fe4ba7bcd8b7b6dd4e89c9de565e4d4e191d1?
