### ISSUE TITLE
REPL should tell users whether metrics, tracing, etc. are turned on/off

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#750]
Currently the REPL allows users to turn on/off features like metrics, tracing, etc. Users can toggle these but they can't tell whether the features are on off.

It would be nice if users could check which features are enabled.

**Comment by repenno** [comment]
Should we add a new command such as "show debug"?

**Comment by tsandall** [comment]
Sure, that sounds reasonable. What I would probably do is create a settings struct that can be serialized into JSON and printed to the console. Feel free to follow that approach or not (it seems like it'll be easy to keep the settings in-sync w/ the `show debug` command that way.)

**Comment by repenno** [comment]
> show debug
{
	"Trace": false,
	"Metrics": false,
	"Instrument": false
}

**Comment by tsandall** [comment]
Cool. We typically add struct field tags and make the fields follow `snake_case`. E.g., the output should be:

```
{
  "trace": false,
  "metrics": false,
  "instrument": false
}
```

**Comment by repenno** [comment]
sure, will do.

**Comment by repenno** [comment]
```
> show debug
{
	"trace": false,
	"metrics": false,
	"instrument": false
}
>
```
