### ISSUE TITLE
Deprecate --insecure-addr

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#763]
With the recent changes to --addr  (e.g., #762), we don't need --insecure-addr anymore. The goal will be to remove --insecure-addr by v0.11.

Work required:

* Add support for multiple --addr values (v0.9)
* Update docs to remove references to --insecure-addr and replace with --addr (v0.9)
* Add warning message on startup if --insecure-addr is used (v0.9)
* Remove --insecure-addr completely (v0.11)

/cc @JAORMX

**Comment by repenno** [comment]
Let me take a stab at this one

**Comment by tsandall** [comment]
Changes have been merged. We can target removal for the release after this one.
