### ISSUE TITLE
Implement Single sign on

### ISSUE THREAD

**Issue by kingzez** [open-policy-agent/opa#775]
Ask a question, can opa implement a service of Single sign on ? Could you give me some advice please ?

**Comment by tsandall** [comment]
Hi @kingzez, could you provide more information/background about your question?

OPA does not help you solve _authentication_, which is what an SSO provider does. You can use OPA to enforce _authorization_ policies for users that authenticate via SSO.

If you provide more detail, I can give a longer answer. Hope this helps.

**Comment by kingzez** [comment]
Hi @tsandall, thank you for answering me. 

My question  background: I have some web applications,  such as web application A at http:appA.com, web application B at http:appB.com,  phone application C and so on, these application has same user and they has different authorization operation. every user use one account  that login my applications.

So I just want implement SSO, and equipment authorization user. I want SSO combine with OPA , the SSO part I want implement by myself. 

In your reply, you said 

> OPA does not help you solve authentication

at SSO part , Did you have some advice?  :)

**Comment by tsandall** [comment]
I can't give much advice around selecting an SSO provider or implementing one yourself :-( Once you have figured out how you're going to _authenticate_ users, feel free to post questions here or on Slack about to integrate OPA for _authorization_.
