### ISSUE TITLE
opa config directory and kubernetes configmaps.

### ISSUE THREAD

**Issue by pwmorreale** [open-policy-agent/opa#782]
OPA doesn't play nice with kubernetes configmaps.  You can specify a directory as a last argument to an OPA command line and OPA will search the directory for various config (rego/yaml/etc) files.  

However, it will also traverse hidden directories within that parent, which, in the case of kubernetes, means finding and parsing the top-level soft links to the conf files as well as the parent instances. 

OPA then aborts with 'multiple default rules named <name>  found' errors.  Ouch.  Took quite a while to track this down.

If this was intended behavior, OPA could provide a -depth option to limit the recursive depth of the directory traverse, or perhaps an option to ignore hidden directories, or perhaps ignore soft links. 
Its quite useful, at least in kubernetes, to have OPA assume that files within a directory path are config files, however more control over the traverse is needed.

Repeat by creating a k8's configmap with one or more .rego files and invoking the opa image with an arg list that ends with the mount point of the configmap volume.

**Comment by tsandall** [comment]
Hrmmm. Thanks for raising this. I've run into this before but it slipped off my radar.

Of these options, I think that ignoring hidden directories is the best.

1. Recursion depth. If we use this, pretty much every Kubernetes manifest will need to include it (and set to --depth=1).

2. Ignore softlinks If we use this, OPA would have to load the files out of the subdirectories. This would be fine for policy, but if you were loading JSON/YAML files into OPA via configmaps, then their contents would be rooted at the wrong location under `data`.

Ignoring hidden directories by default feels like the best alternative. This way, if users _really_ need to use hidden directories, they can opt-in, but in the happy case, OPA will do the right thing.

**Comment by tsandall** [comment]
As a workaround you can specify the file paths to OPA explicitly. E.g., instead of:

```yaml
image: openpolicyagent/opa
args:
- run
- --server
- /policies
```

Do:

```yaml
image: openpolicyagent/opa
args:
- run
- --server
- /policies/file1.rego
- /policies/file2.rego
```

**Comment by pwmorreale** [comment]
yep, am specifying absolute paths atm, however that is less than optimal since it means that the file names must be known aprioi.   

nod, it works for us to ignore hidden dirs by default.

**Comment by fwilhe** [comment]
This issue just helped me figure out what was wrong. Thanks. Seems still an issue with 0.28.0.

**Comment by vilkovtato** [comment]
Confirming, that this is still an issue in 0.28.0. Are there plans for solving this? Thanks
