### ISSUE TITLE
How to reload inmem store?

### ISSUE THREAD

**Issue by tamalsaha** [open-policy-agent/opa#810]
I am trying to learn how to use opa from my Go library. In my case, the policy files will be mounted as configmap and I don't know which path is modified. So, I can't use `store.Write` method. How do I reload  a Store?

**Comment by srenatus** [comment]
If size permits, you could just replace the store, like
```go
// s is the service's state, we "update" the inmem store by replacing it
s.store = inmem.NewFromObject(map[string]interface{}{
	"policies": policies,
})
```

**Comment by tamalsaha** [comment]
We could do this. But this will mean we have to manager concurrent access from outside. If this can be done from the `Store` itself, then we can just pass the same `map`, but it can be done proeprly (using some  transaction etc).

**Comment by tsandall** [comment]
@tamalsaha you can either replace the store like @srenatus showed (which is quite simple if you wrap the store field access with a mutex) or you can call `store.Write(ctx, txn, storage.AddOp, storage.Path{}, v)` where `v` contains the new value for the store. I don't think there's a lot that OPA can do for you beyond that.

Closing this for now. Feel free to reply if you have more questions.

**Comment by tamalsaha** [comment]
Will `store.Write(ctx, txn, storage.AddOp, storage.Path{}, v)` update all the paths from `v`?

**Comment by tsandall** [comment]
That call will effectively replace the content of the store with the value v.

**Comment by tamalsaha** [comment]
Great! This will do. I am going to try it out. Thanks a lot.
