### ISSUE TITLE
Any update on rego v2?

### ISSUE THREAD

**Issue by tamalsaha** [open-policy-agent/opa#811]
Is there any update on rego v2? I could not find anything in the bi-weekly meeting notes.

xref: https://github.com/open-policy-agent/opa/issues/700#issuecomment-380284692

Thanks.

**Comment by tsandall** [comment]
@tamalsaha we're planning to integrate CEL as a library in OPA to offload a subset of evaluation. Beyond that we have already incorporated parts of the the proposal (like providing special operators for assignment `:=` and comparison `==`). Going forward we're planning to incorporate other parts of the proposal into the existing version of Rego.

**Comment by tamalsaha** [comment]
Is there a tentative timeline for this?

**Comment by tsandall** [comment]
We don't have a tentative timeline for all the features. Do you have a specific feature from the proposal in mind?

**Comment by tamalsaha** [comment]
I would to use something like a general purpose policy language where yaml DSLs are too restrictive. OPA fits the bill nicely. From the Rego v2 proposal I see

```
Rego v2 is a series of extensions to the Common Expression Language (CEL) with the aim of clarifying the flow of execution from Rego v1 while preserving its features and incorporating the non-Turing complete, partial evaluation semantics of CEL.
```

As someone who doesn't know both Rego v1 and v2 well, this makes me think that I should just wait :) . Since I did not see any update on Rego v2, it was not even clear if this was going to happen. Sometimes projects abandon ideas after proposal. That is why I ask.

**Comment by tsandall** [comment]
> I would to use something like a general purpose policy language where yaml DSLs are too restrictive. OPA fits the bill nicely.

The current version of OPA definitely fits the bill here. We love feedback though so if you run into issues, let us know.

> As someone who doesn't know both Rego v1 and v2 well, this makes me think that I should just wait :) . Since I did not see any update on Rego v2, it was not even clear if this was going to happen. Sometimes projects abandon ideas after proposal. That is why I ask.

It's on our TODO list to update the doc. For now the plan is to incorporate improvements into V1.

Hope this helps!
