### ISSUE TITLE
Data Filtering with SQL

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#830]
In some cases, context required for a policy decision cannot be replicated into OPA. In cases like this, parts of a policy that rely on external data could be returned to the service for further evaluation.

OPA's [Compile API](https://github.com/open-policy-agent/opa/blob/master/docs/book/rest-api.md#compile-api) allows callers to invoke partial evaluation to retrieve policy statements that depend on unknowns.  These policy statements can be translated into SQL predicates.

The initial goal will be to produce an example that shows how Rego policies can be translated to SQL for a simple CRUD app. The app will be implemented in Python and will use sqlite as it's backend.

**Comment by tsandall** [comment]
Contrib include an example now: https://github.com/open-policy-agent/contrib/tree/master/data_filter_example.

There is also a blog post on the work: https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4

We'll open new issues for future work.

**Comment by Bessonov** [comment]
@tsandall great blog post, thank you very much! Is there any update or more general way to transform the rules to sql?

> As long as the policies expressed in Rego do not perform joins, we can translate sets of Rego queries into SQL expressions that get appended onto WHERE clauses.

Where this limitation comes from? I know very little about OPA ATM and I'm not sure that it's a use case for me, but I can image build rules for related tables. (I'm sure I can flatten the structure with a `view` or like, but in my use case it should be avoided).

**Comment by dassio** [comment]
> Where this limitation comes from? 
I think it comes from the fact that when joining tables, you can name the temporary table anything like `temp_table` , and OPA can't produce a name that exactly matches the `temp_table`
