### ISSUE TITLE
Interesting Integrations

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#845]
This is a list of potential integrations with other projects.

## CI/CD 

- [Spinnaker](https://www.spinnaker.io/) is a popular continuous delivery tool. OPA could be integrated with Spinnaker to enforce admission/deployment policies in pipelines. Similar integration could be built for Jenkins. For example: https://blog.armory.io/deployment-policies-with-spinnaker/.

- GitHub actions. @lucperkins has written about [integrating OPA with GitHub actions](https://blog.openpolicyagent.org/policy-driven-continuous-integration-with-open-policy-agent-b98a8748e536) and enforcing policies in CI pipelines. See https://github.com/open-policy-agent/opa/issues/3014.

## SDKs

- NodeJS client library to query OPA for policy decisions.

- Heroku buildpack for deploying OPA next to applications.

## API Gateways & Platforms

- [Apigee](https://docs.apigee.com/) is a popular API management platform.

- [Ambassador API Gateway](https://blog.getambassador.io/) is an API gateway built on Envoy.  [via Daniel Bryant](https://twitter.com/danielbryantuk/status/1139182348065550337)

- AWS Lambda.

## Data sources

- [Grafaes](https://github.com/grafeas/grafeas) is an artifact metadata store that could be used to inform policy decisions in various use cases including Kubernetes admission control.

**Comment by nrshrivatsan** [comment]
Jenkinsfile based pipelines to perform quality gate assertions for policies could be a game changer!

**Comment by nrshrivatsan** [comment]
The deeper/inner notion really is **Permission driven & CONTINUOUSLY GOVERNED PDLC** for _Cloud native applications_

**Comment by EliuX** [comment]
An integration with Travis CI would be great. I imagine some easy code to add to your .travis.yml like
```yml
services:
  - opa
```

**Comment by futurama92** [comment]
Can i suggest an integration with VerneMQ or Mosquitto?

**Comment by tsandall** [comment]
@futurama92 sure! Can you provide a brief write up? E.g., provide 2-3 example policies you'd like to have enforced and if you're familiar with those projects how you think the integration might be implemented.

**Comment by jamengual** [comment]
**Jenkins Policy base Slave Election** 

An Integrations with Jenkins will be great and it has been mention and there are many places where OPA can be integrated with Jenkins at the job execution level that will be very useful.

Another level of integration that is often overlooked and which makes CICD/Security teams mad is the Jenkins Slave selection, which in Jenkins is very simplistic and has no guide rails of any kind.

The problem:  Slaves in Jenkins are selected by labels, in one Jenkins master all slaves are available to any user/Job no matter what folder restrictions the user have so there is no way to secure the selection of the Slave base on user:jobid:folderpath or a combination of those.

Imagine this scenario: Jenkins master is deployed in the CICD aws account and Jenkins slaves are distributed in every team's AWS account. If a user from TeamA learns the Label used for TeamB slave the user can change the Jenkins job to use TeamB's slave and run a job that could potentially cause problems, imagine if the pipeline runs terraform import then destroy or some other harmful script.

The proposed solution: An integration with Distributed Builds plugin(ideal) or an Integration of a Proxy/envoy sidecar or other that can intersect the call for the execution of a job in a slave and then run policy against the request arguments and allow/deny the request going to the slave and fail the build.

**Comment by anderseknert** [comment]
I think we should close this issue as it essentially never will be "done". Many of the listed potential integrations have been added already, some other integrations might not be that interesting any longer, and a ton of new ones could easily be added. The #development channel on the [OPA Slack](https://slack.openpolicyagent.org/) is a good place to go for discsussions on potential integrations. For existing integrations, see:

* The OPA [ecosystem](https://www.openpolicyagent.org/docs/latest/ecosystem/) page.
* The [Awesome OPA](https://github.com/anderseknert/awesome-opa) list.

**Comment by anderseknert** [comment]
Silent agreement is the best kind of agreement :) @tsandall I'll close this one for now. Feel free to reopen if you disagree with the above.
