### ISSUE TITLE
Add trace output to the test mode

### ISSUE THREAD

**Issue by mlbiam** [open-policy-agent/opa#856]
When running `opa test` I don't get any trace output, just the result.  To get the trace output I need to run the `opa run` command line and enable `trace`.  If this feature were available for `opa test` it would make for a much quicker development cycle

**Comment by tsandall** [comment]
OPA currently

**Comment by tsandall** [comment]
See my previous comment for details on expected behaviour.

The required changes can be made in:

- cmd/test.go: if verbose is true, instantiate topdown.BufferTracer and set on the test runner. 
- tester/reporter.go: update JSONReporter and PrettyReporter to emit trace results.

**Comment by srenatus** [comment]
🎉 I think is is done with #978 and #975, isn't it? 😃

**Comment by tsandall** [comment]
Fixed by #975 thanks to @srenatus!
