### ISSUE TITLE
REGO returnes `undefined` to the query result with no set of variables

### ISSUE THREAD

**Issue by ken5scal** [open-policy-agent/opa#869]
version: v0.9.0
environment: macOS

The following document says if the query is run against a rule with `no set of variables that would make the query true, the REGO prints false.`, but the actual value was `undefined`.

https://www.openpolicyagent.org/docs/get-started.html

```
> items = ["pizza", "apples", "bread", "coffee"]
> users = {"bob": {"likes": [0, 2]}, "alice": {"likes": [1, 2, 3]}}
> likes[[name, item]] { index = users[name].likes[_]; item = items[index] }
> likes[[name, "orange"]]
undefined
> likes[["mallony", item]]
undefined
```

Is there any difference between `undefined` and `false` in REGO? 
Is the above query supposed to return `undefined` or `false`?

**Comment by tsandall** [comment]
@ken5scal the `undefined` values are expected. The documentation should be updated.

The difference between _undefined_ and `false` is that undefined is not a value you can refer to in Rego (whereas `false` is just another JSON value.) With respect to how queries and rules evaluated, undefined and `false` behave the same. In order for a query to succeed (or for a rule to produce a value) ALL of the statements in the query (or body of the rule) must be _true_. In Rego, all values except undefined and `false` and considered _true_.

**Comment by timothyhinrichs** [comment]
Hi Kengo,

We're always happy to have contributions!

Tim

**Comment by ken5scal** [comment]
Resoved in #887  

@tsandall thanks!
