### ISSUE TITLE
Why use OPA ? And what advantage REST API use OPA?

### ISSUE THREAD

**Issue by kingzez** [open-policy-agent/opa#872]
- Why use OPA ?
- What advantage REST API use OPA (nodejs service)?

Can someone give advice ?

**Comment by tsandall** [comment]
@kingzez we have documentation that explains why you would want to use OPA: https://www.openpolicyagent.org/docs/#why-use-opa. We also have several talks linked in the README (https://github.com/open-policy-agent/opa#presentations) that answer this question. If you have more specific questions, feel free to create issues or ask on Slack.
