### ISSUE TITLE
Data in fetched bundle gets added with "." as root element

### ISSUE THREAD

**Issue by dan6518** [open-policy-agent/opa#896]
https://i.imgur.com/UNc1v91.png

When I configure OPA to fetch a bundle, it adds the data contained within that bundle to the "." root element. I expected my directory "root" to become the root element.

When I try to manually download the bundle from the same URL, I get the file "arkj26038.uncompressed", which contains my bundle (seen on the right).

Shouldn't the result of fetching this bundle be this instead?

```
result: {
  root: {
    ...
  }
}
```

If not, how do I query the data as it is now? For example, GET localhost:8181/v1/data/./root/servers does not work.

**Comment by tsandall** [comment]
@dan6518 it looks like this has to do with the way you are creating the bundle. For example:

```
torin:~/bundle-example$ cat root/data.json
{
    "foo": "bar"
}
torin:~/bundle-example$ ll
total 0
drwxr-xr-x  3 torin  staff    96B Aug 21 08:32 root
torin:~/bundle-example$ tar czvf bundle.tar.gz root
a root
a root/data.json
torin:~/bundle-example$ opa run bundle.tar.gz
OPA 0.9.2-dev (commit b2f400f0, built at 2018-08-20T23:35:01Z)

Run 'help' to see a list of commands.

> data
{
  "repl": {
    "version": {
      "BuildCommit": "b2f400f0",
      "BuildHostname": "spacebox.local",
      "BuildTimestamp": "2018-08-20T23:35:01Z",
      "Version": "0.9.2-dev"
    }
  },
  "root": {
    "foo": "bar"
  }
}
```

OTOH, if you run `tar czvf bundle.tar.gz .` in the same directory, then you get the data rooted under `.`.

Let me know if this answers your question.

**Comment by dan6518** [comment]
Yeah that clears things up, thanks! Now to figure out how to convince the library I'm using to use the first tar command instead of the second...
