### ISSUE TITLE
ConfigMaps not getting annotated indicating that they were not installed by sidecar

### ISSUE THREAD

**Issue by rite2nikhil** [open-policy-agent/opa#898]
Using the following demo tutorial and I not able to see the application of policy 
https://github.com/open-policy-agent/opa/blob/master/docs/book/kubernetes-admission-control.md

I do see api server requests making to the admission controller (opa container)

The kube-mgmt logs just have the first line. What is the best way to debug what policies are loaded and are being evaluated ?

**Comment by tsandall** [comment]
kube-mgmt will annotate the configmaps containing policies to indicate if they've been loaded successfully or if an error has occurred. E.g., if there's a syntax error then OPA will reject the policy and kube-mgmt will set the annotation accordingly on the configmap.

**Comment by tsandall** [comment]
You can also query OPA itself to list the policies that are loaded:

```
GET /v1/policies HTTP/1.1
```

That will list all of the policies that have been loaded into OPA.

**Comment by tsandall** [comment]
That indicates that kube-mgmt is not seeing the configmap in the first place. By default kube-mgmt will try to load policies out of configmaps in the `opa` namespace OR configmaps in other namespaces labelled `openpolicyagent.org/policy=rego`.

**Comment by rite2nikhil** [comment]
Thanks!  https://github.com/open-policy-agent/opa/pull/899
