### ISSUE TITLE
How to prevent deletes of policy config maps on cluster

### ISSUE THREAD

**Issue by rite2nikhil** [open-policy-agent/opa#900]
How does the system prevent deleting the policy config maps itself ? 
Using CRD instead of config maps and evaluating pros/cons ?

**Comment by tsandall** [comment]
@rite2nikhil out of the box, there isn't anything that would prevent this, however, you could write an admission control policy to prevent unauthorized delete/update operations against the configmaps.

If we had support for CRDs similar behaviour could be achieved with RBAC.

**Comment by rite2nikhil** [comment]
Do you know if supporting CRD is planned / in-progress ?

**Comment by tsandall** [comment]
@rite2nikhil it's not in-progress at the moment. If you're interested in contributing this to kube-mgmt, I'd be happy help you get started.

**Comment by tsandall** [comment]
Created an issue in the kube-mgmt repo to track this. https://github.com/open-policy-agent/kube-mgmt/issues/16
