### ISSUE TITLE
build artifacts checked into OPA source tree...

### ISSUE THREAD

**Issue by pwmorreale** [open-policy-agent/opa#905]
[pwm@silverton] opa (master *=)$ make image
go generate
go build -o opa_linux_amd64 -ldflags "-X github.com/open-policy-agent/opa/version.Version=0.9.2-dev -X github.com/open-policy-agent/opa/version.Vcs=d6a392d1-dirty -X github.com/open-policy-agent/opa/version.Timestamp=2018-08-27T18:11:37Z -X github.com/open-policy-agent/opa/version.Hostname=silverton.local"
sed -e 's/GOARCH/amd64/g' Dockerfile.in > .Dockerfile_amd64
sed -e 's/GOARCH/amd64/g' Dockerfile_debug.in > .Dockerfile_debug_amd64
docker build -t openpolicyagent/opa:0.9.2-dev	-f .Dockerfile_amd64 .
Sending build context to Docker daemon  23.28MB
Step 1/5 : FROM gcr.io/distroless/base
 ---> 1358ac6604c5
Step 2/5 : MAINTAINER Torin Sandall <torinsandall@gmail.com>
 ---> Using cache
 ---> 2bb4733f9765
Step 3/5 : ADD opa_linux_amd64 /opa
 ---> e9ea4dc3e16b
Step 4/5 : ENTRYPOINT ["/opa"]
 ---> Running in 544c3e6f4034
Removing intermediate container 544c3e6f4034
 ---> 4d42640e3998
Step 5/5 : CMD ["run"]
 ---> Running in 42424e040ba4
Removing intermediate container 42424e040ba4
 ---> 78ff4c75c54c
Successfully built 78ff4c75c54c
Successfully tagged openpolicyagent/opa:0.9.2-dev
docker build -t openpolicyagent/opa:0.9.2-dev-debug -f .Dockerfile_debug_amd64 .
Sending build context to Docker daemon  23.28MB
Step 1/5 : FROM gcr.io/distroless/base:debug
 ---> 3e52344f657a
Step 2/5 : MAINTAINER Torin Sandall <torinsandall@gmail.com>
 ---> Using cache
 ---> e7b7a6869052
Step 3/5 : ADD opa_linux_amd64 /opa
 ---> 97d0fc9db1ee
Step 4/5 : ENTRYPOINT ["/opa"]
 ---> Running in 45d5d273f8a2
Removing intermediate container 45d5d273f8a2
 ---> 73b539d7b8e6
Step 5/5 : CMD ["run"]
 ---> Running in f3f322ee2630
Removing intermediate container f3f322ee2630
 ---> 24eaba5bf9fa
Successfully built 24eaba5bf9fa
Successfully tagged openpolicyagent/opa:0.9.2-dev-debug
[pwm@silverton] opa (master *=)$ git status
On branch master
Your branch is up to date with 'origin/master'.

  Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ast/parser.go

no changes added to commit (use "git add" and/or "git commit -a")
[pwm@silverton] opa (master *=)$ git ls-files ast/parser.go
ast/parser.go
[pwm@silverton] opa (master *=)$ make clean
rm -f .Dockerfile_*
rm -f opa_*_*
rm -fr site.tar.gz docs/_site docs/node_modules docs/book/_book docs/book/node_modules
[pwm@silverton] opa (master *=)$ git ls-files ast/parser.go
ast/parser.go
[pwm@silverton] opa (master *=)$

**Comment by pwmorreale** [comment]
Still modifying the source:

[pwm@silverton] opa ((v0.9.1) *)$ which pigeon
/Users/pwm/go/bin/pigeon
[pwm@silverton] opa ((v0.9.1) *)$ git reset --hard
HEAD is now at d5ba22b7 Prepare v0.9.1 release
[pwm@silverton] opa ((v0.9.1))$ git status
HEAD detached at v0.9.1
nothing to commit, working tree clean
[pwm@silverton] opa ((v0.9.1))$ make deps
[pwm@silverton] opa ((v0.9.1))$ make image
go generate
go build -o opa_linux_amd64 -ldflags "-X github.com/open-policy-agent/opa/version.Version=0.9.1 -X github.com/open-policy-agent/opa/version.Vcs=d5ba22b7 -X github.com/open-policy-agent/opa/version.Timestamp=2018-08-27T21:26:12Z -X github.com/open-policy-agent/opa/version.Hostname=silverton.local"
sed -e 's/GOARCH/amd64/g' Dockerfile.in > .Dockerfile_amd64
sed -e 's/GOARCH/amd64/g' Dockerfile_debug.in > .Dockerfile_debug_amd64
docker build -t openpolicyagent/opa:0.9.1	-f .Dockerfile_amd64 .
Sending build context to Docker daemon  23.26MB
Step 1/5 : FROM gcr.io/distroless/base
 ---> 1358ac6604c5
Step 2/5 : MAINTAINER Torin Sandall <torinsandall@gmail.com>
 ---> Using cache
 ---> 4b3894199db5
Step 3/5 : ADD opa_linux_amd64 /opa
 ---> 57a6f411cf34
Step 4/5 : ENTRYPOINT ["/opa"]
 ---> Running in dbdc42f7dff6
Removing intermediate container dbdc42f7dff6
 ---> 643d0523ebaa
Step 5/5 : CMD ["run"]
 ---> Running in b9cccf994989
Removing intermediate container b9cccf994989
 ---> beec800ab6da
Successfully built beec800ab6da
Successfully tagged openpolicyagent/opa:0.9.1
docker build -t openpolicyagent/opa:0.9.1-debug -f .Dockerfile_debug_amd64 .
Sending build context to Docker daemon  23.26MB
Step 1/5 : FROM gcr.io/distroless/base:debug
 ---> 3e52344f657a
Step 2/5 : MAINTAINER Torin Sandall <torinsandall@gmail.com>
 ---> Using cache
 ---> 218f3f440793
Step 3/5 : ADD opa_linux_amd64 /opa
 ---> 8d16ad6e47ec
Step 4/5 : ENTRYPOINT ["/opa"]
 ---> Running in 4b132dc6acfe
Removing intermediate container 4b132dc6acfe
 ---> 859d326e5751
Step 5/5 : CMD ["run"]
 ---> Running in 855dad1d4646
Removing intermediate container 855dad1d4646
 ---> 0bf08d59fb4a
Successfully built 0bf08d59fb4a
Successfully tagged openpolicyagent/opa:0.9.1-debug
[pwm@silverton] opa ((v0.9.1) *)$ git status
HEAD detached at v0.9.1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ast/parser.go

no changes added to commit (use "git add" and/or "git commit -a")
[pwm@silverton] opa ((v0.9.1) *)$

**Comment by tsandall** [comment]
Hrmmm. I suspect there's something fishy going on in your development environment. Can you confirm that it's the `generate` step that's causing this file to change? Make sure you have a clean tree, then run `make deps && make generate`. This should reinstall pigeon and then regenerate parser.go. 

You should not see any changes assuming the right version of `pigeon` is being picked up. For example:

```
torin:~$ docker run -it --rm golang:1.10
root@ba55c73b46ea:/go# git clone https://github.com/open-policy-agent/opa.git src/github.com/open-policy-agent/opa
Cloning into 'src/github.com/open-policy-agent/opa'...
remote: Counting objects: 18241, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 18241 (delta 13), reused 27 (delta 9), pack-reused 18193
Receiving objects: 100% (18241/18241), 35.26 MiB | 7.78 MiB/s, done.
Resolving deltas: 100% (9952/9952), done.
root@ba55c73b46ea:/go# cd src/github.com/open-policy-agent/opa/
root@ba55c73b46ea:/go/src/github.com/open-policy-agent/opa# make deps
root@ba55c73b46ea:/go/src/github.com/open-policy-agent/opa# make generate
go generate
root@ba55c73b46ea:/go/src/github.com/open-policy-agent/opa# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

**Comment by pwmorreale** [comment]
This is completely related to attempting to build OPA outside of GOPATH.  

IOW, complete and utter pilot error.   Sorry for the noise.
