### ISSUE TITLE
Configuration yaml files should support reading from environment variables

### ISSUE THREAD

**Issue by dan6518** [open-policy-agent/opa#924]
https://www.openpolicyagent.org/docs/configuration.html

It would make deployments easier if config files supported importing values from environment variables, for example (or whichever other syntax):

```
services:
  - name: opa
    url: $OPASERVICEURL
```

**Comment by tsandall** [comment]
This would be nice to have.

We will need to refactor the config loading a bit to hide the implementation from consumers in OPA. E.g., the configuration loading could be factored into a separate package that calls the JSON/YAML parse and then does the environment variable substitution

**Comment by drasko** [comment]
If there is to be a config file, I would personally prefer `toml`. Mainflux configuration is simple, and `toml` is much simpler that `yaml`, has simpler parser, is not indent-sensitive, etc... Something like this maybe: https://karloespiritu.com/handling-configuration-files-in-go/

What actually bothers me is even that it looks simpler to have config file for Mainflux, you have to drag around config files with binary, point binary to correct paths to config files, etc... In the end is has less benefits for this particular case.

I am open to proposition, but would like to hear opinion of the maintainers and research a bit to see the clear benefits.

**Comment by patrick-east** [comment]
After some discussion with @tsandall the proposal is that we will add in some new CLI options to allow overriding config variables with a `--set KEY=VALUE` syntax (similar to Helms CLI for those that are familiar with it).

To support loading environment variables it will support passing in `${...}` notation values which will be evaluated inside of OPA (before passing config to plugins).

This provides a few features:
* Way we can avoid security concerns with passing secrets on the CLI
* Deployers can inject environment variables into arbitrary config settings (as requested originally in this RFE).
* Deployers can bootstrap the runtime without any config file and rely entirely on CLI args + ENV vars to start OPA configure its `services`
