### ISSUE TITLE
Misleading example in the docs

### ISSUE THREAD

**Issue by johscheuer** [open-policy-agent/opa#934]
In  the OPA docs `how does OPA works` there is an example data input and policy (which are reused in the getting started section). In the first place the policy is introduced (mainly how it is structured): https://www.openpolicyagent.org/docs/how-does-opa-work.html#policies in the following part `Putting It All Together` nearly the exact same policy is described in depth: https://www.openpolicyagent.org/docs/how-does-opa-work.html#putting-it-all-together. The only difference of these both policies are the following:

```bash
10c10
<     public_servers[server] = true
---
>     public_servers[server]
```

with the result that the above returns `true` (which means no `violations` are found because we don't have a server `true`). The second policy actually returns the `violation` like expected. 

I just wanted to ask if this was intended or if it actually is a bug in the docs before creating a PR and doing all the CLA stuff.

If it was intended the output in https://www.openpolicyagent.org/docs/how-does-opa-work.html#the-data-document is wrong because the `violations` are an empty array.

**Comment by tsandall** [comment]
hi @johscheuer, thanks for reporting this. `public_servers[server] = true` is incorrect. It was correct a long time ago, but we changed how sets are defined at one point, and apparently we missed this example in the docs.

If you could submit a PR to correct the issue, that would be great. There is no CLA for OPA, you just have to [sign-off on your commits following the DCO.](https://github.com/open-policy-agent/opa/blob/master/CONTRIBUTING.md#developer-certificate-of-origin)

**Comment by johscheuer** [comment]
Thanks for your fast feedback!
