### ISSUE TITLE
Question: /v2/decisions/ API availability and other aids in auditing compliance

### ISSUE THREAD

**Issue by Michael-Frank** [open-policy-agent/opa#936]
Question
@tsandall  
In slide 9 you mentionend a v2 api for enforcement: ` /v2/decisions/<path>`
https://de.slideshare.net/TorinSandall?utm_campaign=profiletracking&utm_medium=sssite&utm_source=ssslideview

1. I read it as: "get previously made decisions" - correct?
2. When will it be available? coud not find it yet.
3. Can that be used for auditing? e.g. make sure my policies are indeed in effect at the right points
4. Anything else, besides of the log push, to aid in verifiying that the rules are working as intended @ cluster scale from an auditors viewpoint?

**Comment by tsandall** [comment]
hey @Michael-Frank, answers to your questions are inline.

> I read it as: "get previously made decisions" - correct?

1. Not quite. /v2/decisions is/was meant to be a simplification of /v1/data. /v1/data let's callers (i) query for policy decisions, (ii) query for raw JSON data stored in OPA, (iii) write raw JSON data into OPA. /v2/decisions would only support (i).

> When will it be available? coud not find it yet.

We haven't committed to implementing it at this point. The work is not very challenging (it just involves adding another handler to the HTTP server) but it's also not high priority right now.

> Can that be used for auditing? e.g. make sure my policies are indeed in effect at the right points

OPA has a feature called the [Decision Log](https://www.openpolicyagent.org/docs/decision_logs.html) that let's you configure a remote HTTP endpoint that batches of decisions will be uploaded to. Each entry contains the input that was given to OPA, the query that was run, and the decision that OPA returned. Take a look at that.

>  Anything else, besides of the log push, to aid in verifiying that the rules are working as intended @ cluster scale from an auditors viewpoint?

Testing is a good way to validate your policies. Check out the [OPA documentation](https://www.openpolicyagent.org/docs/how-do-i-test-policies.html) to get started with the test framework. While there is no substitute for cluster-level auditing, it's often easier to review the policies & tests offline then trying to exercise them in a live system.


The other thing to consider is that with OPA you could write policies that just enumerate the policy violations that exist (without actually enforcing them). For example, if you wanted to know the list of violations that exist for all pods in a specific Kubernetes namespace, you could structure policies to return that kind of answer. You can find examples [here](https://github.com/open-policy-agent/library). Users have expressed interest in more support for this kind of use case with OPA. It's on the [roadmap](https://docs.google.com/presentation/d/1P74xECzR4gYsmuYREed0DnuN1OdnGsiLwJLj_ovcqk0/edit#slide=id.g3cfa3c06b4_0_0), however, we haven't committed to working on it yet.

Hope this answers your questions.

**Comment by Michael-Frank** [comment]
Tanks for the quick answer 👍 . I think you covered everything 😃 
Anywhere one can vote for roadmap tasks or is there perhaps an git issue allready?

**Comment by tsandall** [comment]
We don't actually have an issue for that Prometheus integration. If you'd like to file one and link to the roadmap that would be great (others will likely find it and comment/upvote.)
