### ISSUE TITLE
Query API does not work with Server example

### ISSUE THREAD

**Issue by ken5scal** [open-policy-agent/opa#939]
I am trying to retrieve servers with certain ports using the example from Ad-hoc query.

https://www.openpolicyagent.org/docs/rest-api.html#execute-an-ad-hoc-query

The above example uses "GET /v1/query?q=data.servers[i].ports[_] = "p2"; data.servers[i].name = name HTTP/1.1", which is supposed to return following result, but when use a curl command, it returns nothing.

# How I set up.
1. run docker image `openpolicyagent/opa:0.9.0`
2. Prepare Server-data.json

```
{
    "servers": [
        {"id": "s1", "name": "app", "protocols": ["https", "ssh"], "ports": ["p1", "p2", "p3"]},
        {"id": "s2", "name": "db", "protocols": ["mysql"], "ports": ["p3"]},
        {"id": "s3", "name": "cache", "protocols": ["memcache"], "ports": ["p3"]},
        {"id": "s4", "name": "dev", "protocols": ["http"], "ports": ["p1", "p2"]}
    ],
    "networks": [
        {"id": "n1", "public": false},
        {"id": "n2", "public": false},
        {"id": "n3", "public": true}
    ],
    "ports": [
        {"id": "p1", "networks": ["n1"]},
        {"id": "p2", "networks": ["n3"]},
        {"id": "p3", "networks": ["n2"]}
    ]
}
```
3. `curl -X PUT --data-binary @data.json localhost:8181/v1/data/servers`
4. Confirm the data by `curl -X GET http://localhost:8181/v1/data/servers`
5. Execute following command to retrieve server names with port id "p2"
```
curl -X GET \
  'http://localhost:8181/v1/query?q=data.servers%5Bi%5D.ports%5B_%5D%3D%22p2%22%3B%20data.servers%5Bi%5D.name%20%3D%20name' \
  -H 'content-type: application/json' 
```

# Expected Response

```
{
  "result": [
    {
      "i": 3,
      "name": "dev"
    },
    {
      "i": 0,
      "name": "app"
    }
  ]
}
```
* Executing this in `opa run server-data.json server-rule.rego`  works

```
> data.servers[i].ports[_] = "p2"; data.servers[i].name = name
+---+-------+
| i | name  |
+---+-------+
| 0 | "app" |
| 3 | "dev" |
+---+-------+
```

# Actual Response
* response 

```
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Sun, 09 Sep 2018 12:34:30 GMT
< Content-Length: 2
```

* OPA log

```
opa_1         | time="2018-09-09T12:34:52Z" level=info msg="Received request." client_addr="172.18.0.1:42180" req_body= req_id=65 req_method=GET req_params="map[q:[data.servers[i].ports[_]=\"p2\"; data.servers[i].name = name]]" req_path=/v1/query
opa_1         | time="2018-09-09T12:34:52Z" level=info msg="Sent response." client_addr="172.18.0.1:42180" req_id=65 req_method=GET req_path=/v1/query resp_body="{}" resp_bytes=2 resp_duration=2.1929 resp_status=200
```

**Comment by tsandall** [comment]
@ken5scal I think the issue has to do with how the data.json file is loaded into OPA:

```
curl -X PUT --data-binary @data.json localhost:8181/v1/data/servers
```

This call is going to load the content of `data.json` under `/data/servers/`. So, for example, to refer to the first server you would have to write: `data.servers.servers[0]`. If you instead ran `curl -X PUT ... /v1/data` the `data.json` content would be rooted at the right location. The problem with calling PUT on /v1/data is that it might conflict with policies that you've loaded. If you need to load data this way, I'd recommend you use a different root for the raw JSON data.

**Comment by tsandall** [comment]
Closed by accident. Let me know if this resolves your issue.

**Comment by ken5scal** [comment]
k, let me check

**Comment by tsandall** [comment]
OK, I am going to close the issue. If that doesn't explain the problem, feel free to post a comment and we can investigate further.
