### ISSUE TITLE
Specifying custom functions

### ISSUE THREAD

**Issue by aeneasr** [open-policy-agent/opa#949]
I was unable to find guidance on this in the docs (maybe I didn't look properly), but it does generally not seem possible to define my own functions on OPA. For example, I don't want to wait for #897 to land in master, but would rather just define & use it right away. I definitely agree that generic functions like this one should be available in OPA nonetheless (and contributed by the community), but some custom methods don't make sense to be generally available.

Is that something that is desirable in OPA or not?

**Comment by tsandall** [comment]
You can add your own built-in functions to OPA today. [See the this GoDoc example to get started.](https://godoc.org/github.com/open-policy-agent/opa/topdown#example-RegisterFunctionalBuiltin1)

If you are running OPA as a daemon this requires a recompile or use of the [new shared library loading feature.](https://github.com/open-policy-agent/opa/pull/883).

**Comment by aeneasr** [comment]
Awesome, thank you for the clarification and sorry for not looking thoroughly enough :)
