### ISSUE TITLE
Consuming OPA as an embedded service

### ISSUE THREAD

**Issue by aeneasr** [open-policy-agent/opa#951]
I would like to consume/run OPA s an embedded service, but I was not able to figure out how to do that properly. Is it possible to run OPA embedded in another Go program?

**Comment by tsandall** [comment]
@aeneasr to what extent do you want to embed OPA? Are you just looking to embed the evaluation engine or do you want to want to effectively run all (or most of) OPA inside another Go process (e.g., the HTTP server, bundle downloader, etc.)?

If you want the former see the GoDoc for the `rego` package to get started embedding the evaluation engine.

If you want the latter, see these two examples:

- https://github.com/open-policy-agent/example-api-authz-go - shows how to embed OPA as a library without the HTTP server but with other capabilities like bundle downloading, status reporting, etc. enabled.

- https://github.com/open-policy-agent/opa-istio-plugin - shows how to fork OPA and essentially run it as a service embedded inside another service. In this case, the opa-istio-plugin extends OPA to implement the Envoy ext_authz gRPC API.

**Comment by aeneasr** [comment]
Awesome!

**Comment by aeneasr** [comment]
Are there any plans on streamlining the [setup](https://github.com/open-policy-agent/example-api-authz-go/blob/master/internal/opa/opa.go) or am I best advised to c&p that part?
