### ISSUE TITLE
`ast.Copy` panics if input is a comment

### ISSUE THREAD

**Issue by aeneasr** [open-policy-agent/opa#960]
I'm not sure if this is caused by the code structure of [`opa-fuzz`](https://github.com/aeneasr/opa-fuzz/blob/master/main.go) but there seem to be several panics caused by (probably invalid) input, for example:

```
        C:/workspace/go/src/github.com/aeneasr/opa-fuzz/main.go:32 +0xe4
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237f (#)

Trace: goroutine 1 [running]:
runtime/debug.Stack(0x8add89, 0x37, 0xc00028f988)
        C:/Go/src/runtime/debug/stack.go:24 +0xae
main.run.func1(0xc00043f8aa, 0x2, 0x2)
        C:/workspace/go/src/github.com/aeneasr/opa-fuzz/main.go:43 +0x178
panic(0x8242c0, 0xbd17c0)
        C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/open-policy-agent/opa/ast.(*Module).Copy(0x0, 0xc00028fd50)
        C:/workspace/go/src/github.com/open-policy-agent/opa/ast/policy.go:218 +0x3d
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc0002a6620, 0xc00028fd50)
        C:/workspace/go/src/github.com/open-policy-agent/opa/ast/compile.go:244 +0x10e
main.run(0xc00043f8aa, 0x2, 0x2)
        C:/workspace/go/src/github.com/aeneasr/opa-fuzz/main.go:55 +0x1c8
main.main()
        C:/workspace/go/src/github.com/aeneasr/opa-fuzz/main.go:32 +0xe4
Panic caused by "runtime error: index out of range" was thrown with payload 
```

There is a wide variation of different inputs, but all contain a `#` somewhere and are prefixed by nothing, a space, a tab, or some other spac-y character.

**Comment by tsandall** [comment]
If the input to ParseModule does not include a package, ParseModule cannot create a well-formed module. If the input is effectively empty (e.g., only whitespace, only comments, etc.) then the return from ParseModule will be `nil, nil`. Callers can check for this and handle it accordingly (e.g., either return an error or ignore the empty file.)
