### ISSUE TITLE
Add regex template built-in

### ISSUE THREAD

**Issue by aeneasr** [open-policy-agent/opa#964]
I would like to propose to add another regex built-in. Here, the regular expression is delimited by two characters (eg `<` and `>` or `(` and `)`). This allows one to match strings against patterns like:

```
foo:<bar|baz>:bar
<.*>
...
```

A reference implementation can be found [here](https://github.com/ory/ladon/blob/master/compiler/regex.go#L100). That is a simplification of `gorilla/mux`'s [route templates](https://github.com/gorilla/mux/blob/master/regexp.go). I'm happy to use other implementations.

This type of pattern matching is typically used to remove the need for escaping characters in URN pattern matching, when pattern matching is still desired. Instead of doing `foo\.bar|baz\.bar` you write `foo.<bar|baz>.bar` which is less error prone (because accidentally writing `foo.bar|baz\.bar` matches `foo.bar.baz` but also `fooobar.baz`).

As always, happy to provide a PR!

**Comment by tsandall** [comment]
This seems reasonable. As far as implementation goes, it seems simple enough to copy the implementation out of ladon and into OPA (rather than vendoring it.) What do you think?

**Comment by aeneasr** [comment]
Yeah, totally! I'll set up a PR today.

**Comment by aeneasr** [comment]
Should this go in the `regex` "module"? So maybe `regex.match_template(template, pattern, output)`?

**Comment by tsandall** [comment]
That sounds good to me.
