### ISSUE TITLE
Add glob built-in

### ISSUE THREAD

**Issue by aeneasr** [open-policy-agent/opa#965]
I would like to propose the addition of glob functionality. With that I mean the possibility of matching simple strings against patters like `foo.*`, `foo:*`, `foo:*:bar`. The current functionality `reg.globs_match` does not implement that. Happy to tackle a PR!

This type of pattern matching is usually desirable when matching URNs, particularly URLs, for example matching a particular subdomain `*.mydomain.com`, `{foo,bar,baz}.mydomain.com`.

A library that implements this is [glob](https://github.com/gobwas/glob).

As always, happy to provide a PR!

**Comment by tsandall** [comment]
This has come up before -- it seems like we should add it.

If you use a thirdparty library like gobwas/glob to support this, please make sure to add a comprehensive set of docs to OPA that explain the glob syntax.

**Comment by aeneasr** [comment]
Ok, I think `glob` looks the most promising from my research. I'll probably c&p some examples from there to the docs. Should we prefix this with `glob.`?

**Comment by tsandall** [comment]
That sounds good to me. We can rename the language reference section for Regex to "Regex & Glob" or something. And then include a detailed description w/ examples of the glob syntax.

**Comment by tsandall** [comment]
For revendoring see: https://github.com/open-policy-agent/opa/blob/master/docs/devel/DEVELOPMENT.md#dependencies

If the `pigeon` dependency updated, make sure to regenerate the parser and commit the result.

**Comment by aeneasr** [comment]
Ok so coming back to this, I think we'd add these functions:

* `glob.match(pattern, delimiter, match, output)`: Where `output` is `true` if `match` (`api.github.com`) matches `pattern` (`*.github.com`) with set `delimiter` (`.`) and `false` otherwise.
* `globa.quote_meta(pattern, output)` returns an escaped version of pattern, so something along the lines of `glob.quote_meta("*.github.com", output)` would return `"\*.github.com"` for output. One can use this to combine escaped globs with globs that need processing.
