### ISSUE TITLE
Trailing Slashes in REST API endpoints Results in 405

### ISSUE THREAD

**Issue by salekinsirajus** [open-policy-agent/opa#972]
### Problem
When used the OPA REST API to upload data or policies, a slash at the endpoint causes the API to reject the request and results in a 405 (Method Not Allowed) response.

I am not sure if it is the case for _every_ endpoint, but that might very well be the case.

### How to Reproduce

Contents of `data.json`:
```json
{
  "users": [
    {
      "user_id": "343",
      "role": "admin"
    },
    {
      "user_id": "124",
      "role": "superuser"
    }
   ]
}
```
(Optional) The above file can be validated with `./opa run data.json` to make sure it's formatted correctly.

Now if we want to upload this data with the Data API, like this:
```bash
curl -X PUT localhost:8181/v1/data/ --data-binary @data.json -v

*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8181 (#0)
> PUT /v1/data/ HTTP/1.1
> Host: localhost:8181
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 153
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 153 out of 153 bytes
< HTTP/1.1 405 Method Not Allowed
< Date: Tue, 25 Sep 2018 22:09:41 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

```

However, if we remove the trailing slash (`localhost:8181/v1/data`), the API works as it's intended:
```bash
curl -X PUT localhost:8181/v1/data --data-binary @data.json

*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8181 (#0)
> PUT /v1/data HTTP/1.1
> Host: localhost:8181
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 153
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 153 out of 153 bytes
< HTTP/1.1 204 No Content
< Date: Tue, 25 Sep 2018 22:18:57 GMT
< 
* Connection #0 to host localhost left intact

# query the data api
curl -X GET localhost:8181/v1/data | python -mjson.tool
{
    "result": {
        "users": [
            {
                "policy_name": "admin",
                "user_id": "343"
            },
            {
                "policy_name": "superuser",
                "user_id": "124"
            }
        ]
    }
}
```

**Comment by srenatus** [comment]
@salekinsirajus Would you say that this needs a documentation improvement -- e.g. "Don't do this: ..." or "Do it this way... " -- or do the docs currently claim that `/data/` would work; or would you expect a REST API to not care for the trailing slash and propose changing the behaviour to match that expectation?

**Comment by tsandall** [comment]
405 is the wrong status code in this case.

We should review the current APIs and document the current behaviour (just in this issue would be a good start.) Then we can decide how to handle trailing slashes in a way that's consistent across all of the APIs.

**Comment by repenno** [comment]
This is a well-known issue with HTTP REST frameworks. Normally a redirect is sent if there is no trailing slashes to the URL with slashes (and vice-versa).  If enabled it should just work

https://godoc.org/github.com/gorilla/mux#Router.StrictSlash

BTW, some clients (such as curl?) *do not* follow redirects, POSTMAN does.

**Comment by repenno** [comment]
I guess I can fix this one

**Comment by tsandall** [comment]
Stripping the trailing slash on the V1 APIs should be fine.

**Comment by repenno** [comment]
okay, I will set Router.StrictSlash and see how it plays out
