### ISSUE TITLE
opa test: rewrite or warn about duplicate rules

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#976]
Given `foo.rego`,
```
package foo

bar(x, y) {
  x = y
}
```
and `foo_test.rego`,
```
package foo

test_bar {
  bar(3, 3)
}

test_baz {
  bar(true, true)
}

test_baz {
  bar(true, false)
}
```
the output of `opa test` will be
```
running "data.foo.test_bar"
running "data.foo.test_baz"
running "data.foo.test_baz"
PASS: 3/3
```
...and that somewhat makes sense, as for OPA, this is really _two_ tests, where `test_baz` has two different rule bodies, and one of them happens to be true, so we're fine.

However, I'd argue that any such test file _must have been a mistake_, and we should either **warn the user**, or **rewrite duplicate rules** in `_test.rego` files (`test_baz#01` and `test_baz#02` or something like that).

What do you think?

**Comment by tsandall** [comment]
If we want to treat this as invalid, I think the runner should just error and exit when it encounters duplicate rules. OTOH, this seems a bit harsh, so perhaps rewriting is better. It seems like a matter of taste. I'd lean towards rewriting. WDYT?

**Comment by srenatus** [comment]
_+1_ rewriting. I'd be interested in contributing, too. 😃

**Comment by tsandall** [comment]
Cool. I think the rewriting can be implemented [in the runner before the compile happens.](https://github.com/open-policy-agent/opa/blob/master/tester/runner.go#L135)
