### ISSUE TITLE
Handle session data

### ISSUE THREAD

**Issue by julianrz** [open-policy-agent/opa#984]
When multiple users are accessing OPA REST API, they can contribute conflicting data and rules. Can everything be optionally bound to session? Or provide some way to store data/rules in buckets, with lifecycle

**Comment by tsandall** [comment]
@julianrz, sorry for the delayed response.

We don't have a session construct in OPA currently, however, I think you can achieve what you want using OPA's built-in authentication & authorization support. See the Security docs for details: https://www.openpolicyagent.org/docs/security.html

In a nutshell, you could configure an authorization policy that restricts identities to specific namespaces. For example...

```
package system.authz

identity_namespaces = {"bob": "ns1", "alice": "ns2"}

default allow = false

allow {
  ns := identity_namespaces[input.identity]
  input.path[2] = ns  # path[0] is 'v1' and path[1] is 'data' or 'policies' or ...
}
```

**Comment by tsandall** [comment]
I am going to close this issue for now. If you have more questions along this topic feel free to comment and we can re-open.
