### ISSUE TITLE
Inconsistent subscripting

### ISSUE THREAD

**Issue by jrozentur** [open-policy-agent/opa#993]
You have to assign an array to a variable to subscript it. Why?
[1,2,3][_]
| 
1 error occurred: 1:8: rego_parse_error: no match found
	[1,2,3][_]
	       ^
> t:=[1,2,3]
Rule 't' defined in package repl. Type 'show' to see rules.
> t[_]
+------+
| t[_] |
+------+
| 1    |
| 2    |
| 3    |
+------+

**Comment by tsandall** [comment]
That's just the way the grammar is currently defined. Only references and variables can be dereferenced. In theory we could allow any term to be dereferenced, it's just questionable how useful that would be. Does this answer your question?

**Comment by jrozentur** [comment]
Thanks for the answer. Well, it is common to write a multi-part expression, where intermediate result is immediately reused, without naming it, although certainly naming does not hurt, and may result in a more readable code... Please FAQ it

**Comment by tsandall** [comment]
We have a description of refs in the language guide. Feel free to post an example that you think would be useful to include in the docs.
