### ISSUE TITLE
Comprehension of non-query result confusing

### ISSUE THREAD

**Issue by jrozentur** [open-policy-agent/opa#994]
```
> [x|x=[1,2,3]]
[
  [
    1,
    2,
    3
  ]
]
```
In most languages, this would have returned [1,2,3]

Why is this different from comprehension of query results (where it works intuitively), e.g.
```
> t:=[1,2,3]
Rule 't' re-defined in package repl. Type 'show' to see rules.
> [x|x=t[_]]
[
  1,
  2,
  3
]
```

**Comment by tsandall** [comment]
`x = [1,2,3]` can be understood as "find an x that makes the statement `x = [1,2,3]` true. Comprehensions like [x | ...] can be understood as "construct an array where x is in the array IF ... is true". 

OTOH, `[x | x = t[_]]` is effectively iterating over the elements in t and assigning them to x.

Hope this helps.

**Comment by jrozentur** [comment]
Yes, my understanding is that when x is a collection, x[_] effectively makes an iterator of it, and comprehensions take an iterator
