### ISSUE TITLE
how to use istio mixer OPA adapter with OPA Pull from LDAP/AD during evaluation

### ISSUE THREAD

**Issue by tangxusc** [open-policy-agent/opa#997]
I want to check user authorization with istio's mixer OPA adapter, but my user information is stored in an external system. I want to use Pull from LDAP / AD during evaluation to get data from LDAP / AD. What should I do? I see no explanation of this method in the document

**Comment by repenno** [comment]
There is another feature related to LDAP integration. 

#938 
https://github.com/open-policy-agent/opa/issues/938

**Comment by tsandall** [comment]
@tangxusc OPA does not (currently) have a built-in function to query a LDAP/AD during evaluation. We generally recommend that you put an authenticating proxy in front of LDAP/AD, see https://www.openpolicyagent.org/docs/best-practice-identity.html.

OPA does have an experimental built-in function `http.send` that you could use to execute an HTTP request inside the policy. Hope this helps.
